PSS MATLAB Toolboxes: Aerospace/Airships/Modeling/Models/ASM2.m File Reference
ASM2.m File Reference
Airship Model #2.
Functions
blank line function ASM2 ()
Airship Model #2.
Function Documentation
ASM2()
blank line function ASM2 ()
Contains the geometric and mass properties for a specific airship model.
The following geometric configuration is assumed:
double-ellipsoid hull with circular cross-section
two horizontal tail-fins (identical, symmetric, based on NACA 1412)
two vertical tail-fins (identical, symmetric, based on NACA 1412)
streamlined hanging gondola to house payload
The following design parameters are specified:
alt operating altitude [m]
L hull length [m]
D hull diameter [m]
ratio rear ellipsoid length / front ellipsoid length
xFinA start of fin at hull / hull length (meas from nose)
xFinB start of fin taper / hull length (meas from nose)
xFinC end of fin / hull length (meas from nose)
yzFinI inboard fin width / hull radius (meas from center axis)
yzFinO outboard fin width / hull radius (meas from center axis)
xGonA gondola leading edge / hull length (meas from nose)
xGonB gondola trailing edge / hull length (meas from nose)
zGon bottom of gondola / hull radius (meas from center axis)
rhoFab area density of skin fabric [kg/m^2]
mP payload mass [kg]
thrustMax maximum thrust capability [N]
xProp x-location of propellers / hull length (meas from nose)
zProp z-location of propellers / hull radius (meas from center axis)
x-distances for fins, gondola and props are dimensionless (with L) y,z-distances for fins, gondola and props are dimensionless (with D/2)
Form
d = ASM2;
Inputs
none
Outputs
none
References and(), ASM2(), and length().
Referenced by AirshipBallonets(), and ASM2().