PSS MATLAB Toolboxes: Aerospace/CubeSat/Help/FileHelp.m File Reference
FileHelp.m File Reference
Functions
function CreateCallback (in action, in modifier)
Create a callback string.
function FileHelp (in action, in modifier)
function GetH ()
Get the data structure stored in the figure window.
function Initialize ()
View the file headers.
function LoadDatabase ()
Load the databases.
function LoadHeader (in h)
Colors.
function PutH (in h)
Put the data structure into the user data.
function Quit ()
Quit.
function RunExample (in h)
Must consider path.
Function Documentation
CreateCallback()
function CreateCallback (in action, in modifier)
References LoadDatabase().
FileHelp()
function FileHelp (in action, in modifier)
References GetH(), and Initialize().
GetH()
function GetH ()
References CreateCallback(), and FileHelp().
Initialize()
function Initialize ()
Form
FileHelp(action, modifier)
Inputs
action Action modifier Modifier to the action
Outputs
none Copyright 1999 Princeton Satellite Systems, Inc. All rights reserved.
2021.1 Update database to look for FileHelpDatabase Get the data structure stored in the figure window
References get().
LoadDatabase()
function LoadDatabase ()
LoadHeader()
function LoadHeader (in h)
Load the data file Create the figure Draw the logo Controls List mode control List boxes Edit boxes New examples flag Load the header for the selected file
PutH()
function PutH (in h)
References FileHelp().
Quit()
function Quit ()
References get(), GetH(), PutH(), and set().
RunExample()
function RunExample (in h)
Build was created on a different platform. set value to prevent bug if new header is shorter than previous header set header itself and other strings set example Run an example
References GetH(), and Quit().