PSS MATLAB Toolboxes: Orbit/OrbitCoord/Alfriend2El.m File Reference
Alfriend2El.m File Reference
Orbit Module » Orbit Functions
Convert an Alfriend orbital element set into the standard orbital element set [a,th,i,q1,q2,W] -> [a,i,W,w,e,M].
Functions
function Alfriend2El (in ela)
Detailed Description
Form
 el = Alfriend2El( ela )
Inputs
 ela           (:,6) Alfriend orbital element set [a,th,i,q1,q2,W]
                        where:   th = true latitude
                                 q1 = e*cos(w)
                                 q2 = e*sin(w)
Outputs
 el            (:,6) Standard orbital element set [a,i,W,w,e,M]
[a,th,i,q1,q2,W] -> [a,i,W,w,e,M]
Function Documentation
Alfriend2El()
function Alfriend2El (in ela)
References Nu2M(), and set().
Referenced by CollisionDemoSimStruct(), CollisionSimStruct(), DFFSim(), FFEccDeltaElem2Hills(), FFEccHills2DeltaElem(), FFSim(), Mean2Osc(), and ViewRelativeMotion().