PSS MATLAB Toolboxes: FormationFlying/IntegratedSim/CommandLists/AutoDualPCCommandList.m File Reference
AutoDualPCCommandList.m File Reference
Command list for the following scenario.
Functions
function AutoDualPCCommandList ()
Command list for the following scenario.
Function Documentation
AutoDualPCCommandList()
function AutoDualPCCommandList ()
 - 9 spacecraft start in leader-follower formation
 - Auto initialize into 2 teams (max # per team set to 5)
 - Cluster goals sent for dual-plane P.C. w/ ref on circle
 - Guidance law distributes cluster goals, finds optimal assignment
 - All relatives achieve target states.
 Since version 7.
Form
 cmd = AutoDualPCCommandList;
Inputs
 none
Outputs
 cmd          (.)    Data structure of commands to be sent to the cluster
References AutoDualPCCommandList(), AutoDualPCSimStruct(), Command_Structure(), DFFControlLaw(), DFFTeamManagement(), Initialize(), set(), and Window_Structure().
Referenced by AutoDualPCCommandList(), and AutoDualPCSimStruct().