PSS MATLAB Toolboxes: Thermal/Brayton/BraytonWithRecuperator.m File Reference
BraytonWithRecuperator.m File Reference
Compressor inlet, T1: 300 K is a common value to use, as it lowers the compressor power consumption.
Functions
function BraytonWithRecuperator (in d, in doPlot)
Brayton Cycle with Recuperator.
ingroup ThermalFunctions function DefaultDataStructure ()
d.r is the pressure ratio of the compressor.
Detailed Description
A lower value means increased radiator size, a higher value means lower overall efficiency for the compressors.
Date
2024-02-17
Id
f14a4504d61ffeef217a0125076fdbaeeb4a0c30
Brayton Cycle with Recuperator
Function Documentation
BraytonWithRecuperator()
function BraytonWithRecuperator (in d, in doPlot)
References abs(), and(), Brayton(), BraytonWithRecuperator(), DefaultDataStructure(), NewFig(), Pressure(), and Watermark().
Referenced by BraytonWithRecuperator(), and CycleDesign().
DefaultDataStructure()
ingroup ThermalFunctions function DefaultDataStructure ()
Higher r means higher thermal efficiency but more mass. Typical closed-loop Brayton cycles for space applications have r = 2. The default working fluid is a 70/30 (molar ratio) mixture of Helium and Xenon.
The function draws a heat engine diagram with pressures and temperatures labeled, if there are no outputs or the doPlot flag is true.
Type BraytonWithRecuperator for a demo.
Form
 d = BraytonWithRecuperator;    % default data
 d = BraytonWithRecuperator( d, doPlot )
Inputs
 d (.) Input data structure
       .T4     (1,1) Turbine Inlet temperature (deg-K)
       .T1     (1,1) Compressor Inlet Temp temperature (deg-K)
       .P1     (1,1) Compressor Inlet Pressure (Atm)
       .pHeat  (1,1) Heat input (kW)
       .r      (1,1) Pressure ratio of compressor
       .name   (1,:) Name of gas or mixture
       .nr      (1,1) Recuperator effectiveness - how much heat we want to remove
       .nc     (1,1) Compressor efficiency
       .nt      (1,1) Turbine efficiency
       .nPX     (1,1) Exchanger pressure drop an empirically-determined factor
       .gamma   (1,1) Specific heat ratio
       .cP      (1,1) Specific heat (J/kg-K)
       .molWt   (1,1) Molecular Weight of the mixture in (g/mol)
       .yBase  (1,1) Base y height. Negative moves it up
       .image  (1,1) Image for diagram, default BraytonCycle.png
 doPlot  (1)   Flag for creating plot output
Outputs
 d (.) Data structure additions
       .P2   (1,1) Compressor outlet (Pa)
       .T2   (1,1) Compressor outlet (deg-K)
       .P3   (1,1) Heat exchanger inlet (Pa)
       .T3   (1,1) Heat exchanger inlet (deg-K)
       .P4   (1,1) Turbine inlet (Pa)
       .P5   (1,1) Recuperator inlet (Pa)
       .T5   (1,1) Recuperator inlet (deg-K)
       .P6   (1,1) Gas cooler inlet (Pa)
       .T6   (1,1) Gas cooler inlet (deg-K)
       .n    (1,1) Brayton cycle efficiency.
       .mDot    (1,1)   Mass flow (kg/s)
       .wC  (1,1) Compressor work (kW)
       .wT  (1,1) Turbine work (kW)
       .wNet (1,1) Net work (kW)
References: Barrett and Reid, "System Mass Variation and Entropy" Generation (2003). MIT Pebble-bed reactor. Wright, Lipinski, Vernon, and Sanchez, "Closed Brayton Cycle Power Conversion Systems" (2006). Wilson and Korakianitis, "The Design of High-Efficiency Turbomachinery and Gas Turbines," Second Edition, (2014). Copyright (c) 2018 Princeton Satellite Systems, Inc. All rights reserved.
Since 2018.1 2021.1 Fixed display of text. Previously if the function was run multiple times it would put the text in the wrong figure. 2022.1 Added entropy calculations and T-s diagram of cycle. Inputs Thermodynamics Cycle Temperature and Pressure Analyses Calculate specific entropy changes in cycle dS12 = d.cP*log(d.T2/d.T1) - R*log(d.P2/d.P1); % isentropic form dS45 = d.cP*log(d.T5/d.T4) - R*log(d.P5/d.P4) % isentropic form Calculate specific entropy at each part of cycle using differences Overall Efficiency Call Up Image and Label Outputs On It The numbers referred to in the script above, such as T1 or P2, represent the stage of the Brayton Cycle as it appears in this image. Create arrays to hold text and numeric values Plot T-s diagram using quiver plot Watermark Define the position and colors of the text boxes Power input BraytonWithRecuperator>>DefaultDataStructure
Referenced by AircraftPointMassRHSWithSideslip(), AircraftThrustFromFlight(), AntennaGain(), AtmNRLMSISE(), BearingLife(), BladeElement(), Brayton(), BraytonWithRecuperator(), CentrifugalCompressor(), DualRotorDesign(), EarthEnvironment(), EngineMap(), EntryLiftAndDrag(), EquilibriumControls(), ForceSimple(), FSailTB(), HalbachMotorDesign(), HeatExchangerWithLosses(), HeatTransferCoeffTaylor(), IsothermalHelio(), JetEngine(), LandingControlBilinear(), LargeFormationControl(), LiftCoeffStall(), LocallyOptimalConeClock3D(), LunarLandingControl(), LunarTrajectoryControl(), MassFuelElectricConstantUE(), MeasDoris(), MeasEarthTarget(), NavigationCameraSunStar(), OpticalNavigation(), OpticalNavigationMoon(), OpticalNavigationSun(), OptimalMLIDensity(), P3Axis(), PlanarHelioOptimal(), PlanarHelioOptimalSlidingTime(), PlanetSensorDualScan(), PMABCMachineRHS(), PMBMachineRHS(), RadiationShield(), RankineCycle(), ReactionWheelFriction(), RHS3DPointAircraft(), RHSACFlatEarth(), RHSAutomobile(), RHSGGRotational(), RHSGyro(), RHSIsothermal(), RHSLiftingReentry3D(), RHSLiftingSatellite(), RHSLunarLander(), RHSMEMSGyro(), RHSPointMassAircraft(), RHSReentry(), RHSRigidBodyWithDamping(), RHSRollingMissileLinear(), RHSSGCMG(), RHSThreeBody(), RWAWithPower(), SecondOrderGuidance(), SecondOrderGuidance3D(), SpurGear(), StaticEarthSensor(), StellarAttDetUKF(), SunEarthMagAttDet(), ThreeAxisControlDisturb(), ThrusterAndRWACommand(), ThrusterColdGas(), VAWTBldMdlRHS(), and VAWTRHS().