PSS MATLAB Toolboxes: OpticalNavigation/Terrain/CatmullRomSpline.m File Reference
CatmullRomSpline.m File Reference
$Date$
Functions
function CatmullRomSpline (in P)
Calculate Catmull–Rom for a chain of points with x 1:4.
ingroup OpticalNavigationFunctions function spline_maths (in P0, in P1, in P2, in P3)
The curve C will a single y point.
function tj (in ti, in Pi, in Pj, in alpha)
P0, P1, P2, and P3 should be (x,y) point pairs that define the Catmull-Rom spline.
Detailed Description
Id
cdac3216850fc22d018adcfcccf64df3650eb745
Calculate Catmull–Rom for a chain of points with x 1:4
Function Documentation
CatmullRomSpline()
function CatmullRomSpline (in P)
References and(), CatmullRomSpline(), Demo(), spline_maths(), and tj().
Referenced by CatmullRomSpline(), spline_maths(), and square().
spline_maths()
ingroup OpticalNavigationFunctions function spline_maths (in P0, in P1, in P2, in P3)
Form
 C = CatmullRomSpline( P )
Inputs
 P   (1,4) Control y points
Outputs
 C   (1,1) Y point
Reference https://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline Copyright (c) 2021 Princeton Satellite Systems, Inc. All rights reserved.
Since version 2021.1 Demo CatmullRomSpline>spline_maths
References and(), CatmullRomSpline(), get(), length(), and tj().
Referenced by CatmullRomSpline().
tj()
function tj (in ti, in Pi, in Pj, in alpha)
nPoints is the number of points to include in this curve segment. nPoints = 100; Parametric constant: 0.5 for the centripetal spline, 0.0 for the uniform spline, 1.0 for the chordal spline. Premultiplied power constant for the following tj() function. Calculate t0 to t4 Only calculate points between P1 and P2 Reshape so that we can multiply by the points P0 to P3 and get a point for each value of t. CatmullRomSpline>tj
Referenced by CatmullRomSpline(), GlideslopePlanner(), and spline_maths().