PSS MATLAB Toolboxes: Sail/Coordinates/ClockConversion.m File Reference
ClockConversion.m File Reference
Functions
function ClockConversion (in cone, in clock, in fromConv, in toConv, in d)
function McInnes (in r, in v)
McInnes' convention using the osculating orbit normal.
function NorthFrame (in uSun, in eciFlag)
Copyright (c) 2006 Princeton Satellite Systems, Inc.
function SunFrame (in d)
Transform north to ECI.
Function Documentation
ClockConversion()
function ClockConversion (in cone, in clock, in fromConv, in toConv, in d)
References and(), CEcl2Eq(), ClockConversion(), Constant(), Demo(), Dot(), Eul2Mat(), isempty(), McInnes(), NorthFrame(), Period(), Plot2D(), RVFromKepler(), SunFrame(), Unit(), vector(), and zeros().
Referenced by ClockConversion(), and ConeClockPatches().
McInnes()
function McInnes (in r, in v)
Referenced by AccelToLoading(), AnglesMcInnesToU(), ClockConversion(), FixedPitchControl(), FRotatingLagrange(), FRotatingPlanet(), FSailGuidance(), GeoOptimalMission(), GeoSwitchingMission(), LightnessToLoading(), LoadingToAccel(), LoadingToLightness(), LocallyOptimalTraj(), LunarDisplacement(), LunarHalo(), NonKeplerianPlanet(), NonKeplerianSun(), NorthFrame(), OpticalMcInnesToPSS(), OptimalPeriodNonKepler(), PlanetOptimalTraj(), PlottingParabolas(), SPIGuidance(), SunFrame(), UpdateSailOpticalProps(), and VarEqSailPlanet().
NorthFrame()
function NorthFrame (in uSun, in eciFlag)
 Apply a clock angle convention between McInnes, PSS, and JPL.
 Clock angle is measured from:
 1: The osculating orbit normal (McInnes)
 2: The cross product of the orbit normal and sun vector (PSS)
 3: Ecliptic north (JPL)
 4: The projection of the velocity vector on the sun perpendicular plane
 Forms 1 and 3 are only suitable for heliocentric orbits. Forms 2 and 4 are
 general. In addition, Forms 2 and 4 assume an X axis towards or away
 from the sun depending on the selected sign convention. The same sign
 convention is used for both clock frames, to and from.
 Since version 7.
Form
 clockNew = ClockConversion( cone, clock, fromConv, toConv, d )
 B = ClockConversion( cone, clock, fromConv, [], d )
Inputs
 cone           (1,n)  Out-of-plane angle (rad)
 clock          (1,n)  Out-of-plane angle (rad)
 fromConv       (1,1)  Index of incoming convention
 toConv         (1,1)  Index of outcoming convention
 d              (1,1)  Data needed to define frames
                        .r       (3,n) Position vector
                        .v       (3,n) Velocity vector
                        .s       (3,n) Unit vector to the sun
                        .c       (1,1) Sign convention for X axis
                        .eciFlag (1,1) ECI (1) or ecliptic (0) frame flag
Outputs
 clockNew       (1,n)  Out-of-plane angle (rad)
    OR
 B              (3,3)  Rotation matrix from the reference frame to the sail
All rights reserved. Demo Find sail normal of FROM convention convert force direction to normal PSS convert force direction to normal if needed JPL Campbell Sail forward normal Return a transformation matrix from the initial frame to the sail Assign output. Note that n = B'*[1;0;0] Convert sail normal to angles of TO convention McInnes convert normal to force direction PSS/Campbell JPL Campbell enforce 0 to 360 convention JPL clock angle is referenced from the projection of the north ecliptic onto the sun perpendicular plane.
References Cross(), McInnes(), QSail(), QTForm(), SunFrame(), Unit(), and vector().
Referenced by ClockConversion().
SunFrame()
function SunFrame (in d)
y axis is projection of north onto perpendicular plane Sun referenced frame via QSail. d.r is empty to refer to the velocity vector instead of the orbit normal.
References Cross(), McInnes(), and Unit().
Referenced by ClockConversion(), and NorthFrame().