PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/Initialize/ClusterGoalsDemoSimStruct.m File Reference
ClusterGoalsDemoSimStruct.m File Reference
Cluster goals demo simulation data structure.
Functions
blank line function ClusterGoalsDemoSimStruct ()
Cluster goals demo simulation data structure.
Function Documentation
ClusterGoalsDemoSimStruct()
blank line function ClusterGoalsDemoSimStruct ()
Set up the data structure for a demonstration of achieving cluster goals in a multiple-team hierarchy. Loads ClusterGoalsTeamOrg.mat.
Form
sim = ClusterGoalsDemoSimStruct;
Inputs
none
Outputs
sim (.) Simulation data structure to be input to DFFSimulation
References ClusterGoalsDemoCommandList(), ClusterGoalsDemoSimStruct(), DFFSimulation(), El2Alfriend(), JD2000(), length(), LoadGravityModel(), OrbRate(), SpacecraftParameters(), and zeros().
Referenced by ClusterGoalsDemoSimStruct().