PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/CommandLists/ClusterGoalsDemoCommandList.m File Reference
ClusterGoalsDemoCommandList.m File Reference
Command list for demonstrating the achievement of cluster goals.
Functions
blank line function ClusterGoalsDemoCommandList ()
Command list for demonstrating the achievement of cluster goals.
Function Documentation
ClusterGoalsDemoCommandList()
blank line function ClusterGoalsDemoCommandList ()
in a multiple-team hierarchy. Loads ClusterGoalsTeamOrg.mat
Form
cmd = ClusterGoalsDemoCommandList;
Inputs
none
Outputs
cmd (.) Data structure of commands to be sent to the cluster
References ClusterGoalsDemoCommandList(), Command_Structure(), DFFControlLaw(), DFFGuidanceLaw(), DFFTeamManagement(), EccTeamGoals_Structure(), Initialize(), length(), set(), and Window_Structure().
Referenced by ClusterGoalsDemoCommandList(), and ClusterGoalsDemoSimStruct().