PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/CommandLists/CollisionCommandList.m File Reference
CollisionCommandList.m File Reference
Command list for monitoring a collision.
Functions
blank line function CollisionCommandList ()
Command list for monitoring a collision.
Detailed Description
Same as ProjCircCommandList
Function Documentation
CollisionCommandList()
blank line function CollisionCommandList ()
Same as ProjCircCommandList
but with preemptive avoidance on.
Since version 7.
Form
cmd = CollisionCommandList;
Inputs
none
Outputs
cmd (.) Data structure of commands to be sent to the cluster
References CollisionCommandList(), and ProjCircCommandList().
Referenced by CollisionCommandList(), and CollisionSimStruct().