PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/Initialize/CollisionDemoSimStruct.m File Reference
CollisionDemoSimStruct.m File Reference
ProjCircSimStruct with a new command list to run collision survey.
Functions
blank line function CollisionDemoSimStruct (in duration)
ProjCircSimStruct with a new command list to run collision survey.
Function Documentation
CollisionDemoSimStruct()
blank line function CollisionDemoSimStruct (in duration)
Specifies two spacecraft and four orbits and initial drift is removed. The reconfiguration is first commanded with a small size which causes it to be rejected, and then again with a larger size for which it is approved. To just check the CollisionMonitor output set the duration to 600 seconds.
Form
sim = CollisionDemoSimStruct(duration)
Inputs
duration (1) Duration, seconds (optional)
Outputs
sim (.) Simulation data structure to be input to DFFSimulation
References Alfriend2El(), and(), CollisionDemoCommandList(), CollisionMonitor(), DFFSimulation(), El2Alfriend(), El2RV(), Geometry_Structure(), InitializeFormation(), isempty(), ProjCircSimStruct(), and set().