PSS MATLAB Toolboxes: Core/Common/Help/FileHelp.m File Reference
FileHelp.m File Reference
Functions
function CreateCallback (in action, in modifier)
Create a callback string.
function FileHelp (in action, in modifier)
function GetH ()
Get the data structure stored in the figure window.
function Initialize ()
View the file headers.
function LoadDatabase ()
Load the databases.
function LoadHeader (in h)
Colors.
function PutH (in h)
Put the data structure into the user data.
function Quit ()
Quit.
function RunExample (in h)
Must consider path.
Function Documentation
CreateCallback()
function CreateCallback (in action, in modifier)
References LoadDatabase().
Referenced by AirshipDesignGUI(), AirshipSimGUI(), BlockDiagramPlugIn(), DeriveData(), DetectionFilterBuilder(), DispG(), DisplayFilter(), Draw2DViewPlugIn(), FAero(), FAtmDensity(), FEngine(), FPlantNoise(), FSolar(), GetH(), GroupVariables(), GUICounter(), ParamGUI(), PointingBudgetGUI(), SpacecraftPlugIn(), and TelemetryOffline().
FileHelp()
function FileHelp (in action, in modifier)
References GetH(), and Initialize().
Referenced by GetH(), and PutH().
GetH()
function GetH ()
References CreateCallback(), and FileHelp().
Referenced by AirshipDesignGUI(), AirshipSimGUI(), AnimateCube(), AttitudeProfilePlugIn(), BlockDiagramPlugIn(), CADColor(), CommandPlugIn(), ComponentPopup(), ComputeGainsPlugIn(), Constant(), DeriveData(), DetectionFilterBuilder(), DispG(), DisplayFilter(), Draw2DViewPlugIn(), DrawSCPlugIn(), DrawThermalPlugIn(), FAero(), FAtmDensity(), FEngine(), FileHelp(), Finder(), FPlantNoise(), FSolar(), GroupVariables(), GUIColors(), GUICounter(), HelpSystem(), MessageQueue(), NormalizePlugIn(), OrbitDisplayPlugIn(), PlugInDemo(), PropagateOrbitPlugIn(), Quit(), ReactionWheel(), ReduceOrderPlugIn(), RunExample(), RWASmart(), SimulatePlugIn(), SpaceCamera(), SpacecraftPlugIn(), SpacecraftStatePlugIn(), StateSpacePlugIn(), StoppingPlugIn(), and TelemetryOffline().
Initialize()
function Initialize ()
Form
FileHelp(action, modifier)
Inputs
action Action modifier Modifier to the action
Outputs
none Copyright 1999 Princeton Satellite Systems, Inc. All rights reserved.
2021.1 Update database to look for FileHelpDatabase Get the data structure stored in the figure window
References get().
Referenced by ACInit(), ACPlot(), AircraftControl(), AircraftControlCAS(), AirshipControlSim(), AirshipDesignGUI(), AirshipInit(), AirshipMassModel(), AirshipSim(), AirshipSimGUI(), AirshipStabConDerivatives(), AirshipState(), AlignThruster(), AllanVariance(), AnimateCube(), AStarSearch(), AsteroidTrajectory(), AttitudeProfilePlugIn(), AttitudeProfileVis(), AutoDualPCCommandList(), AutoFormCommandList(), AxialFluxCoil(), Blobify(), BlockDiagramPlugIn(), BodyPlugIn(), BurnData_Structure(), CameraControls(), ClusterGoalsDemoCommandList(), CollisionDemoCommandList(), CollisionDetectCommandList(), CommandPlugIn(), ComponentPlugIn(), ComputeGainsPlugIn(), ComputeTLE(), Constraints_Structure(), Cost3D(), CostEstimate_Structure(), CubeSatModel(), CubeSatPowerAnalysis(), CycleDesign(), DefaultACState(), DefaultCommandList(), DeltaVCommand_Structure(), DemoManeuverCommandList(), DeriveData(), DesignUpperStage(), DetectionFilterBuilder(), DFFControl(), DFFSimGUI(), DFFSimulation(), DiscreteGVE(), DispG(), DisplayFilter(), Disturbances(), Draw2DViewPlugIn(), DrawHAWT(), DrawRobot(), DrawSCARA(), DrawSCPlugIn(), DrawSpacecraftInOrbit(), DrawThermalPlugIn(), DrawVAWT(), DualListPlugIn(), EccentricTetrahedronCommandList(), EccentricTetrahedronSimStruct(), EccGeometry_Structure(), EccTeamGoals_Structure(), EigenstructurePlugIn(), ElementsPlugIn(), Ellipsoid(), ExportVerticesToOBJ(), FAero(), FAtmDensity(), FEngine(), FFEccDiscreteHills(), FileHelp(), Finder(), FMovingBody(), FocalPlaneImage(), FormationDesignGUI(), FPlantNoise(), FrictionSmooth(), FSolar(), GAMin(), Geometry_Structure(), GroupVariables(), GUIColors(), GUICounter(), Gyro(), HelioFromPlanetInit(), HelpSystem(), HRG(), ImageOverlay(), ImpulsiveLPManeuver(), InitializeAxes(), InitializeFormation(), InitializeSailGravity(), InitializeSailSim(), InterpolateState(), JDStartTransfer(), KFExItMu(), KFSAAD(), LaunchGUI(), LoadOBJFile(), LoadOBJModel(), LQPlugIn(), MainDemoCommandList(), MakeSquareSail(), Maneuver_Structure(), MapIOPlugIn(), Measurements(), MHTGUI(), MHTInitializeTrk(), MHTInitialTrackScore(), MLog(), ModalReductionPlugIn(), ModelPlugIn(), NewtonianAeroPropertiesFromOBJFile(), NewtRaph(), NewtRaph2(), NormalizePlugIn(), ODETimeDisplay(), OpticalNavLunarLandmarkStar(), OpticalNavPlanetStar(), OrbitDisplayPlugIn(), Orientation_Structure(), Osc2Mean(), ParamGUI(), PlanningParameters_Structure(), PlotArrays(), PlugInDemo(), PointingBudgetGUI(), PopulateCostMatrix(), PowCompAnlytBsd(), ProjCircCommandList(), PropagateLowThrust(), PropagateOrbitPlugIn(), RateGyro(), ReduceCatalog(), ReduceOrderPlugIn(), RHSIsothermalCubeSat(), RHSLunarMission(), RWASmart(), SafeGuidanceSim(), SailMesh(), SearchVaneAngles(), SimpleManeuverCommandList(), SimulatePlugIn(), SISOListPlugIn(), SolarF(), SolarSysJPL(), SolidR(), SpaceCamera(), SpacecraftPlugIn(), SpacecraftStatePlugIn(), SPMMnvr(), SSA(), StarDataFromStarMatrix(), StarDataGeneration(), State_Structure(), StateSpacePlot(), StateSpacePlugIn(), StoppingPlugIn(), Team_Structure(), TeamGoals_Structure(), TeamManagementCommandList(), TelemetryOffline(), TestADCSCommandList(), TestControlCommandList(), TestMonitoringCommandList(), TestTeamMgtCommandList(), ThrusterAlignment(), ThrustModel(), TimeCntrl(), TimeGUI(), TimePlugIn(), TOMHTAssignment(), TorqueRod(), TorqueVAWT(), TransferOrbit(), TurboRamjetSim(), VAWTBldMdlRHS(), WindModel(), Window_Structure(), WireC(), WireDMch(), and WireInit().
LoadDatabase()
function LoadDatabase ()
Referenced by CreateCallback().
LoadHeader()
function LoadHeader (in h)
Load the data file Create the figure Draw the logo Controls List mode control List boxes Edit boxes New examples flag Load the header for the selected file
PutH()
function PutH (in h)
References FileHelp().
Referenced by AnimateCube(), BlockDiagramPlugIn(), ComponentPopup(), ComputeGainsPlugIn(), DeriveData(), DetectionFilterBuilder(), DispG(), DisplayFilter(), Draw2DViewPlugIn(), DrawThermalPlugIn(), FAero(), FAtmDensity(), FEngine(), Finder(), FPlantNoise(), FSolar(), GroupVariables(), GUIColors(), HelpSystem(), NormalizePlugIn(), OrbitDisplayPlugIn(), Quit(), ReactionWheel(), ReduceOrderPlugIn(), RWASmart(), SpaceCamera(), SpacecraftPlugIn(), SpacecraftStatePlugIn(), and StateSpacePlugIn().
Quit()
function Quit ()
References get(), GetH(), PutH(), and set().
Referenced by DetectionFilterBuilder(), RunExample(), and SAADMain().
RunExample()
function RunExample (in h)
Build was created on a different platform. set value to prevent bug if new header is shorter than previous header set header itself and other strings set example Run an example
References GetH(), and Quit().