PSS MATLAB Toolboxes: AC/ACAircraft/CreateMVSSetupFileEntries.m File Reference
CreateMVSSetupFileEntries.m File Reference
Functions
function CreateMVSSetupFileEntries (in d, in r, in vBody, in w, in cG, in eulerAngle, in engine, in scale)
Function Documentation
CreateMVSSetupFileEntries()
function CreateMVSSetupFileEntries (in d, in r, in vBody, in w, in cG, in eulerAngle, in engine, in scale)
References CreateMVSSetupFileEntries(), Cross(), QECI(), QTForm(), Throttle(), and vector().
Referenced by CreateMVSSetupFileEntries().