PSS MATLAB Toolboxes: FormationFlying/IntegratedSim/Initialize/DFFSimStruct.m File Reference
DFFSimStruct.m File Reference
Set up the data structure for a DFF simulation.
Functions
function DFFSimStruct (in el, in nOrbits, in nSC, in jD, in ideal)
Set up the data structure for a DFF simulation.
Detailed Description
All inputs are optional.
Function Documentation
DFFSimStruct()
function DFFSimStruct (in el, in nOrbits, in nSC, in jD, in ideal)
All inputs are optional.
 Since version 7.
Form
 sim = DFFSimStruct( el, nOrbits, nSC, jD, ideal );
Inputs
 el         (n,:)    Initial element set for all spacecraft.
 nOrbits     (1)     Number of orbits simulation will last.
 nSC         (1)     Number of spacecraft to simulate.
 jD          (1)     Julian date at start of simulation.
 ideal       (1)     Flag indicating whether to use ideal actuation.
Outputs
 sim          (.)    Simulation data structure to be input to DFFSimulation
References Date2JD(), DefaultCommandList(), DFFSimulation(), JD2000(), LoadGravityModel(), OrbRate(), set(), and SpacecraftParameters().
Referenced by DFFSimulation().