PSS MATLAB Toolboxes: FormationFlying/IntegratedSim/Software/DFFControlLaw.m File Reference
DFFControlLaw.m File Reference
The decentralized control law.
Functions
function DFFControlLaw (in action, in d, in k)
The decentralized control law.
Function Documentation
DFFControlLaw()
function DFFControlLaw (in action, in d, in k)
Form
 t = DFFControlLaw( action, d )
Inputs
 action        (1,:)     Action to be performed
 d             (1,1)     Data structure for inputs
 k             (1,1)     Spacecraft Indentifier
Outputs
 t             (1,1)     Output. Defined for actions
                         'get telemetry', 'get telemetry names' and
                         'get telemetry units' and any accessors
                         you may add.
References and(), get(), and LinOrbLQG().
Referenced by AutoDualPCCommandList(), AutoFormCommandList(), ClusterGoalsDemoCommandList(), CollisionDemoCommandList(), DefaultCommandList(), DemoManeuverCommandList(), DFFControl(), EccentricTetrahedronCommandList(), MainDemoCommandList(), ProjCircCommandList(), SimpleManeuverCommandList(), TeamManagementCommandList(), and TestControlCommandList().