PSS MATLAB Toolboxes: FormationFlying/IntegratedSim/Software/DFFParameterDatabase.m File Reference
DFFParameterDatabase.m File Reference
The parameter database for the decentralized formation flying framework.
Functions
function DFFParameterDatabase (in action, in d, in k)
The parameter database for the decentralized formation flying framework.
Function Documentation
DFFParameterDatabase()
function DFFParameterDatabase (in action, in d, in k)
Form
 t = DFFParameterDatabase( action, d )
Inputs
 action        (1,:)     Action to be performed
 d             (1,1)     Data structure for inputs
 k             (1,1)     Spacecraft Indentifier
Outputs
 t             (1,1)     Output. Defined for actions
                         'get telemetry', 'get telemetry names' and
                         'get telemetry units' and any accessors
                         you may add.
References and(), and get().
Referenced by DFFControl().