PSS MATLAB Toolboxes: FormationFlying/IntegratedSim/Software/DFFGuidanceLaw.m File Reference
DFFGuidanceLaw.m File Reference
The decentralized guidance law.
Functions
function DFFGuidanceLaw (in action, in d, in k)
The decentralized guidance law.
Function Documentation
DFFGuidanceLaw()
function DFFGuidanceLaw (in action, in d, in k)
Form
 t = DFFGuidanceLaw( action, d, k )
Inputs
 action        (1,:)     Action to be performed
 d             (1,1)     Data structure for inputs
 k             (1,1)     Unique spacecraft ID
Outputs
 t             (1,1)     Output. Defined for actions
                         'get telemetry', 'get telemetry names' and
                         'get telemetry units' and any accessors
                         you may add.
References and(), and get().
Referenced by AutoFormCommandList(), ClusterGoalsDemoCommandList(), CollisionDemoCommandList(), DefaultCommandList(), DFFControl(), EccentricTetrahedronCommandList(), MainDemoCommandList(), ProjCircCommandList(), and TeamManagementCommandList().