PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/Software/DFFCollisionMonitor.m File Reference
DFFCollisionMonitor.m File Reference
The Collision monitoring component for the decentralized framework.
Functions
blank line function DFFCollisionMonitor (in action, in d, in k)
The Collision monitoring component for the decentralized framework.
Function Documentation
DFFCollisionMonitor()
blank line function DFFCollisionMonitor (in action, in d, in k)
Form
t = DFFCollisionMonitor(action, d)
Inputs
action (1,:) Action to be performed d (1,1) Data structure for inputs k (1,1) Spacecraft Identifier
Outputs
t (1,1) Output. Defined for actions 'get telemetry', 'get telemetry names' and 'get telemetry units' and any accessors you may add.
References and(), and get().
Referenced by CollisionDetectCommandList(), DFFControl(), and TestMonitoringCommandList().