PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/Software/DFFAttitudeController.m File Reference
DFFAttitudeController.m File Reference
DFF attitude control routine.
Functions
blank line function DFFAttitudeController (in action, in d, in k)
DFF attitude control routine.
Function Documentation
DFFAttitudeController()
blank line function DFFAttitudeController (in action, in d, in k)
This routine implements attitude control for the DFF system. PID controllers are used for attitude control - momentum control is not used. The torque command is applied directly in the simulation, without the use of an RWA model. Provision is made for filters of arbitrary order for loop shaping. Inputs are the target quaternion and the true quaternion. Small angles are computed from the two quaternions. The target quaternion should be near the true quaternion for best results.
If there are no inputs it will perform a self-test.
Form
t = DFFAttitudeController(action, d, k)
Inputs
action (1,:) Action to be performed
d (.) Data structure for inputs k (1,1) Unique spacecraft identifier
Outputs
t (.) Data structure with outputs. Valid only with action 'update' and 'get telemetry'
References and(), DefaultData(), get(), isempty(), PID(), quaternion(), and RWA().
Referenced by AutoFormCommandList(), CollisionDemoCommandList(), DefaultCommandList(), DemoManeuverCommandList(), DFFControl(), MainDemoCommandList(), ProjCircCommandList(), SimpleManeuverCommandList(), TestADCSCommandList(), and TestControlCommandList().