PSS MATLAB Toolboxes: Core/Electrical/Motor/DualRotorDesign.m File Reference
DualRotorDesign.m File Reference
Design a dual rotor generator configuration.
Functions
ingroup ElectricalFunctions function DefaultDataStructure ()
This is an axial flux generator with an air coil and two magnet plates attached to the rotating shaft.
function DualRotorDesign (in d)
Design a dual rotor generator configuration.
Detailed Description
Date
2023-11-20
Id
9f802cf1d245c7165a16a9e7bbe1dd4e9fadb553
Function Documentation
DefaultDataStructure()
ingroup ElectricalFunctions function DefaultDataStructure ()
Type DualRotorDesign for a demo.
Form
d = DualRotorDesign; p = DualRotorDesign(d)
Inputs
d (.) Data structure .rO (1,1) Output radius (m) .rI (1,1) Inner radius (m) .n (1,1) Number of poles
.jPeak (1,1) Peak current (A/m^2)
.rho (1,1) Resistivity (mho/m) .bPeak (1,1) Peak magnetic field (T)
.wireD (1,1) Wire diameter (m)
.omega (1,1) Angular rate (rad/s)
.t (1,1) Thickness (m) .hM (1,1) Magnet height (m)
.densityMagnet (1,1) Density magnet (kg/m^3) .densityCopper (1,1) Density copper (kg/m^3) .densityCase (1,1) Density of the case (kg/m^3) .pOut (1,1) Power out (W) .tW (1,1) Winding thickness (m)
Outputs
p (.) Data structure .pOut (1,1) Power out (W) .pLoss (1,1) Power loss (W) .pEddy (1,1) Eddy power loss (W) .pI2R (1,1) Resistive loss (W) .torque (1,1) Torque (Nm) .eff (1,1) Conversion efficiency .mMagnet (1,1) Magnet mass (kg) .mCopper (1,1) Copper mass (kg) .mActive (1,1) Active mass (kg) .jPeak (1,1) Peak current (A/m^2)
.hA (1,1) Active height (m) .volume (1,1) Active volume (m^3)
Reference: M.C. Greaves, A.G. Simpson, B.D. Guymer, Dr G.R. Walker and D. A. Finn, "Ironless wheel motor for a direct drive vehicle application" Copyright (c) 2007, 2018 Princeton Satellite Systems, Inc. All rights reserved.
2019.1 Added a default data structure output. Fixed torque. Added case and shaft calculation 2020.2 Corrected power out equation 2023.1 Added eddy current losses and I2R losses to the output 2024.1 Added missing tW field to default data, fixing built-in demo Demo Geometry Output Mass calculations Volume Inertia Plot
DualRotorDesign()
function DualRotorDesign (in d)
References and(), DefaultDataStructure(), Demo(), DualRotorDesign(), Inertias(), and isempty().
Referenced by DualRotorDesign().