PSS MATLAB Toolboxes: FormationFlying/IntegratedSim/Initialize/EccentricTetrahedronSimStruct.m File Reference
EccentricTetrahedronSimStruct.m File Reference
Eccentric tetrahedron simulation data structure.
Functions
function EccentricTetrahedronSimStruct (in apg, in prg)
Eccentric tetrahedron simulation data structure.
Function Documentation
EccentricTetrahedronSimStruct()
function EccentricTetrahedronSimStruct (in apg, in prg)
Initialize a DFF simulation data structure for a 4 spacecraft tetrahedron geometry in an eccentric reference orbit.
Form
 sim = EccentricTetrahedronSimStruct
Inputs
 apg          (1)     Apogee of reference orbit    [km]
 prg          (1)     Perigee of reference orbit   [km]
Outputs
 sim          (.)    Simulation data structure, input to DFFSimulation
References and(), DFFSimulation(), EccentricTetrahedronCommandList(), EccentricTetrahedronSimStruct(), Initialize(), JD2000(), LoadGravityModel(), Period(), and SpacecraftParameters().
Referenced by EccentricTetrahedronSimStruct().