PSS MATLAB Toolboxes: Orbit/RHSOrbit/FOrbLEOPStopping.m File Reference
FOrbLEOPStopping.m File Reference
Orbit Module » Orbit Functions
Its companion function is FOrbLEOP.
Functions
function FOrbLEOPStopping (in t, in x, in d)
Detailed Description
 Events function for FOrbLEOP
Its companion function is FOrbLEOP
Form
 xDot = FOrbLEOP( t, x, d )
Inputs
 t                      Time (Not used)
 x             (7,1)    The state vector [r;v;m]
 d             (1,1)    Data structure (Not used)
                        .thrust    (1,1) Engine thrust (N)
                        .mu        (1,1) Gravitational parameter
                        .uE        (1,1) Exhaust velocity (m/s)
                        .cDA       (1,1) Drag area product
                        .burnStart (1,1) Start time of burn
                        .burnEnd   (1,1) End time of burn
Outputs
 value          (1,1)    Value of stopping condition
 isTerminal     (1,1)    1 if terminal
 direction      (1,1)    Direction of crossing the boundary
Function Documentation
FOrbLEOPStopping()
function FOrbLEOPStopping (in t, in x, in d)
References FOrbLEOP(), and vector().
Referenced by FOrbLEOP().