PSS MATLAB Toolboxes: Airships/Modeling/Models/GoodYearBlimp.m File Reference
GoodYearBlimp.m File Reference
Airship Model approximating the size and weight of the Goodyear Blimp.
Functions
function GoodYearBlimp ()
Airship Model approximating the size and weight of the Goodyear Blimp.
Function Documentation
GoodYearBlimp()
function GoodYearBlimp ()
 Contains the geometric and mass properties for a specific airship model
 The following geometric configuration is assumed:
 * double-ellipsoid hull with circular cross-section
 * two horizontal tail-fins (identical, symmetric, based on NACA 1412)
 * two vertical tail-fins   (identical, symmetric, based on NACA 1412)
 * streamlined hanging gondola to house payload
 The following design parameters are specified:
 * alt          operating altitude                              [m]
 * L            hull length                                     [m]
 * D            hull diameter                                   [m]
 * ratio        rear ellipsoid length / front ellipsoid length
 * xFinA        start of fin at hull / hull length       (from nose)
 * xFinB        start of fin taper / hull length         (from nose)
 * xFinC        end of fin / hull length                 (from nose)
 * yzFinI       inboard fin width / hull radius          (from x axis)
 * yzFinO       outboard fin width / hull radius         (from x axis)
 * xGonA        gondola leading edge / hull length       (from nose)
 * xGonB        gondola trailing edge / hull length      (from nose)
 * zGon         bottom of gondola / hull radius          (from x axis)
 * rhoFab       area density of skin fabric              [kg/m^2]
 * mP           payload mass                             [kg]
 * thrustMax    maximum thrust capability                [N]
 * xProp        x-location of propellers / hull length   (from nose)
 * zProp        z-location of propellers / hull radius   (from x axis)
 x-distances for fins, gondola and props are dimensionless (with L)
 y,z-distances for fins, gondola and props are dimensionless (with D/2)
Form
 d = GoodyearBlimp;
Inputs
 none
Outputs
 none
References and(), GoodYearBlimp(), and length().
Referenced by GoodYearBlimp().