PSS MATLAB Toolboxes: Core/Electrical/Components/HalbachMotorDesign.m File Reference
HalbachMotorDesign.m File Reference
$Date$
Functions
ingroup ElectricalFunctions function DefaultDataStructure ()
Type HalbachMotorDesign for a demo.
function HalbachMotorDesign (in d)
Design a dual rotor axial flux motor.
Detailed Description
Id
32b61479f03269b1075e582b1a3281af0dfb9085
Design a dual rotor axial flux motor.
Function Documentation
DefaultDataStructure()
ingroup ElectricalFunctions function DefaultDataStructure ()
Form
d = HalbachMotorDesign; p = HalbachMotorDesign(d)
Inputs
d (1,1) Data structure .rO (1,1) Output radius (m) .rI (1,1) Inner radius (m) .n (1,1) Number of poles
.jPeak (1,:) Peak (in time) current density (A/m^2) .rho (1,1) DC resistivity (ohm*m) .bPeak (1,1) Peak magnetic field (T)
.wireD (1,1) Wire diameter (m)
.omega (1,1) Angular rate (rad/s)
.t (1,1) Thickness (m) .hM (1,1) Magnet height (m)
.densityMagnet (1,1) Density magnet (kg/m^3) .densityCopper (1,1) Density copper (kg/m^3) .fLoss (1,1) Rotational coefficient of friction .eddyGreaves (1,1) Logical. True: Use eddy loss model of Greaves et. al. False: Use more general toolbox eddy loss model.
Outputs
p (1,1) Data structure .pOut (1,1) Power out (W) .pLoss (1,1) Power loss (W) .torque (1,1) Torque (Nm) .eff (1,1) Conversion efficiency .mMagnet (1,1) Magnet mass (kg) .mCopper (1,1) Copper mass (kg) .mActive (1,1) Active mass (kg)
Reference: M.C. Greaves, A.G. Simpson, B.D. Guymer, Dr G.R. Walker and D.A. Finn,"Ironless wheel motor for a direct drive vehicle application." Copyright (c) 2020 Princeton Satellite Systems, Inc. All rights reserved.
Since 2020.1. Demo Geometry Output Greaves et. al. model ACResistance.m model Plot HalbachMotorDesign>>DefaultDataStructure
HalbachMotorDesign()
function HalbachMotorDesign (in d)
References ACResistance(), and(), DefaultDataStructure(), Demo(), HalbachMotorDesign(), and Inertias().
Referenced by HalbachMotorDesign().