PSS MATLAB Toolboxes: AC/ACRDE/HyperRDE.m File Reference
HyperRDE.m File Reference
RDE model with a turbocharger.
Functions
function DefaultData ()
Mach profile.
ingroup ACFunctions function Demo ()
RDE model utilizing a turbo-pump or turbocharger that compresses flow so that the RDE can operate in low Mach.
function HyperRDE (in m, in d, in p)
RDE model with a turbocharger.
function PartStdAtm (in p, in j)
Get part of the standard atmosphere.
Detailed Description
Date
HyperRDE.m
Id
eb120b0553603a5fea18897272fca802d9c0d796
Function Documentation
DefaultData()
function DefaultData ()
Default data structure
Referenced by Accel(), DetectorModel(), DFFAttitudeController(), FSWClock(), GlideslopePlanner(), ImagerPSF(), IntegratePSFs(), PID3Axis(), Ramjet(), RamjetKerrebrock(), RDE(), RHSGeoJ2(), RocketH2O2(), SizeTurbineAndCompressor(), Turbofan(), Turbojet(), and TurbojetNoThrust().
Demo()
ingroup ACFunctions function Demo ()
The model calculates a transition transition point and shuts off the pump accordingly. The default fuel is hydrogen.
Chapman-Jouguet(CJ) conditions refer to the detonation wave in the combustion chamber. In the RDE this detonation wave revolves around the central axis of the burner.
The function uses array index j to fill the turbopump part of ts, iSp, and t, then fills second part.
This function needs the Curve Fitting Toolbox, Cantera and the SDToolbox. Find Cantera here: https://cantera.org/install/index.html
and the SDToolbox (Shock and Detonation Toolbox) here: http://shepherd.caltech.edu/EDL/PublicResources/sdt/
You must install both. If Cantera is not installed, you will get the error:
 Undefined function or variable 'Solution'.
 Error in CJspeed (line 25)
 gas1 = Solution(mech);
If the SDToolbox is not installed it will not find CJspeed(). CJspeed loads the file ohn.yaml which reference gri30.yaml (both in Cantera format).
Type HyperRDE for a demo.
Form
 [tS, iSp, t, mode] = HyperRDE( m, d, p )
 d = HyperRDE;
Inputs
 m   (1,:)  Mach number
 d   (.)       Data structure
             .gamma     (1,1) Specific heat ratio of air
             .cP        (1,1) Specific heat of air
             .qR        (1,1) Heating value of the fuel
             .mDotO2    (1,1) O2 mass flow (kg/s)
             .aInlet    (1,1) Inlet area (m^2)
             .piC       (1,1) Compressor pressure ratio
             .TurboPump (1,1) Data structure for TurboPump
             .nB        (1,1) Burner efficiency factor
 p   (.)  Atmosphere structure
Outputs
 tS  (1,:)  Specific thrust (N/(kg/s)) or (m/s)
 iSp  (1,:) Specific impulse (s)
 t    (1,:)  Thrust (N)
 mode (1,:)  0 = turbopump
References: Shepherd, J.E. and Kasahara, J. (2017) "Analytical Models for the Thrust of a Rotating Detonation Engine. GALCITFM, FM2017.001. , Pasadena CA. (Unpublished) @iverbatim Shepherd, Josheph E. California Institute of Technology, "Shock and Detonation Toolbox" http://shepherd.caltech.edu/EDL/PublicResources/sdt/ Copyright (c) 1993-2019 Mattingly, Jack D. "Elements of Gas Turbine Propulsion AIAA Education Series" American Institute of Aeronautics and Astronautics, 2005 pp.138 - 141 Copyright (c) 2019 Princeton Satellite Systems, Inc. All rights reserved.
Since version 2019.1 Demo Constants If Mach is less than Mach transition, yes turbopump, shock to store values but cycle analysis of turbopump uses free stream air
Set reference Mach reference markers Shock equation for static pressure Mattingly temperature at station 2 from shock Mattingly Since not shocking inflow, set p2 t2 equal to atmosphere for input into turbopump Square Mach number Turbopump Calculate when ram pressure equals output pressure of turbopump Plot Finds where ram pressure exceeds turbopump Print Mach transition Compute CJ Mach using new process with turbopump on Calculate speed of sounds at bruner inlet a3 and detonation aCJ Compute CJ Temperature and Pressure Second Formula Compute specific thrust as per equation on page 20 If Mach is greater than Mach transition, no turbopump, yes shock,
Set index j to after transition point Shock equation for static pressure Mattingly Temperature at station 2 Mattingly Pressure and temp at station 2 and 3 are assumed equal Compute CJ Mach using new way Compute CJ Temperature and Pressure Second Formula in RDE paper Calculate ISP and thrust based on mass flow uEff = sqrt(2*(d.piC-1)*p.pressure(k)./p.density(k) + m .* p.speedOfSound; If no outputs specified plot with Mach transition point highlighted Generate Ramjet Output for comparison Plot iSp and tS } Plot height profile of demo if demo is called Demo
Referenced by AbsDa(), AccelToSailProps(), AccelToThrustAndQ(), ACResistance(), ActiveAeroSurfacesDisplay(), ActuatorDiskFromPower(), AdaptiveThresholding(), AddFillToPlots(), AdvanceRatio(), AeroDragForce(), AerodynamicHeatFlux(), AerodynamicShock(), AerodynamicShockMinimize(), AeroForceAndTorqueCombined(), AeroFormFactor(), AERToNu(), AggregateComponents(), AirCoreMagneticTorquerDesign(), AirCoreTorquerModel(), AircraftCostCalculation(), AircraftDesign(), AircraftDragDataStructures(), AircraftEquilibrium(), AircraftGroupMass(), AircraftThrustFromFlight(), AirData(), AirlinerSeat(), AirlinerSeats(), AirMass(), AiryDefocused(), AiryDisk(), AiryDiskInPixels(), AiryResolution(), AlbedoFromTextureMap(), AlignThruster(), AllanVariance(), AlphaBetaToU(), AlphaCentauriSystem(), AlphaFromQNV(), AltitudeSH(), AngleDetermination(), AngleOfAttackMaxLD(), AngleOfView(), AntennaPoint(), AOverAStar(), ApolloGuidanceCoordinates(), ApolloLunarDescentGuidance(), ApolloTrajectory(), AreaFromActuatorDisk(), AreaRatioFromMach(), AreaTriMesh(), ArrayToLinspace(), AspectRatio(), AssignColors(), AsteroidCentroid(), AsteroidProperties(), AtmDens1(), AtmDensMars2(), AtmDensTitan(), AtmDensUranus(), AtmEarth(), AtmGamma(), AtmJ70(), AtmJ70ToGround(), AtmNRLMSISE(), AtmScaleHeightsStdAtm(), AtomicMass(), AttitudeControlSimRWA(), AttitudeProfileToTorque(), AttitudeProfileVis(), AU2M(), AutoFormGeometry(), AutoRadar(), AxialFluxCoil(), AzElToU(), BallisticCoefficient(), BandGapToWavelength(), BankedTurn(), BarPlot(), BarycenterEarthMoon(), BathtubCurve(), BatteryDesign(), BatterySize(), BDipole(), BDipoleCoeff(), BDipolePlanet(), BearingLife(), BEMHAWT(), BEMVAWT(), BEP(), BFromHHysteresis(), BHalbach(), BHalbachAxialFluxMotor(), BilinearInterpolation(), BilinearTangentAltitude(), BilinearTangentLaw(), BinaryImage(), BinaryToString(), BiotSavart(), BladeElement(), BladeSolidity(), BladeStress(), BldFlex(), BlurParameter(), Box(), BoxWithRoundedSection(), Brayton(), BraytonIdeal(), BreguetRangeEquation(), BurnoutVelocity(), CADToSimParameters(), CalibrateSunSensor(), CalibrationCube(), CameraCalibration(), CameraCalibrationModel(), CameraImage(), CameraResolution(), CannyEdgeDetector(), CatmullRomSpline(), CD0Composite(), CDCLComposite(), CDCLHypersonic(), CDCLSubsonic(), CDSkinFriction(), CentroidNoise(), Centroids(), CircleFit(), CircleOfConfusion(), CircularManeuver(), CLAlpha(), CLCDFreeMolecular(), CLComposite(), ClimbAngle(), ClockConversion(), CNRComp(), CoarseCentroids(), ColdGas(), ColorSpread(), ColumnSizeCellArray(), CompactPCIChassis(), ComplexToReal(), ComputeAirfoilCoeff(), ComputeCoeffFromShape(), ComputePayloadFraction(), ComputeTLE(), Cone(), ConeAreaAndDerivatives(), ConeClockConvention(), ConeClockToU(), ConstantDynamicPressureVelocity(), ConstellationGroundContact(), ConstellationMaxDistance(), ConvolveImage(), CookeTriplet(), CoplanarOrbit(), CostMatrixRows(), CouplingStress(), CPGas(), CPHypersonic(), CPIAdjust(), CPvsTipSpeedRatio(), CreateAircraftModel(), CreateKVector(), CreateLensTable(), CRTBP2kms(), CRTBPJacobiConstant(), CTPropeller(), CubeSatAero(), CubeSatDisturbanceAnalysis(), CubeSatFaces(), CubeSatModel(), CubeSatPowerAnalysis(), CubeSatPropulsion(), CubeSatRadiationPressure(), CycleDesign(), CylinderWithHemisphere(), CylindricalTank(), DataRate(), DataRateGain(), DataRateOrbit(), DateStringToJD(), DBPower(), DBSignal(), DBWToNW(), DebugLog(), DeltaAngleForNewRADec(), DeltaQToRate(), DeltaWing(), DesignUpperStage(), DetectorModel(), DFFSimGUI(), DiameterAWG(), DigitalFilter(), Diode(), DiscreteTrajectoryToDeltaV(), Disk(), DiskWithHole(), DisplayStars(), DispWithTitle(), DistAero(), DistAlbedo(), DistRadiation(), DistSolar(), DMS2Rad(), DNString2Date(), DoubleIntegratorWithAccel(), DownrangeAndAltFromTarget(), DragAnlytMdl(), DragCoeff(), DragForce(), DragLoss(), DragPolar(), DragPolarFromData(), DrawAircraft(), DrawAlphaBeta(), DrawCAD(), DrawCubeSat(), DrawCubeSatSolarAreas(), DrawFOV(), DrawHAWT(), DrawLens(), DrawMirror(), DrawPatch(), DrawRobot(), DrawSCARA(), DrawSphere(), DrawVAWT(), DrawVertices(), DriftRateSigma(), DualRotorDesign(), DVConstantThrust(), DVGeoTrx(), DVGlideslope(), DVLowThrust(), DVOrbitDrag(), DVReentry(), DynamicPressureAndHeat(), EarthAlb(), EarthBc(), EarthEclipseDuration(), EarthEscape(), EarthOrbToHelioOrb(), ECI2MeanElements(), ECIToRLP(), EclipseFromECI(), EclipticInjectionPlane(), EffFocalLength(), El2RV(), ElectricPropulsionDesign(), ElectricThrust(), ElectricThrusterPower(), ElectronsToIons(), EllipseToS(), EmittanceParallelPlates(), EnergyHeight(), EnergyPhoton(), EnergyWRTMoon(), EngineDataFromTable(), EngineMap(), EngineTable(), EntryLiftAndDrag(), EquilibriumControls(), ErrorCombination(), EstimateCost(), Extrude(), ExtrudeFromProfile(), FAeroSurfaceAccommodation(), FAIR(), FElectricPropulsion(), FFEccEstimateCost(), FFEccGenerateTeamGoals(), FFEccHexahedronGeometry(), FFEccTetrahedronGeometry(), FindDriftTerm(), FindIfInBetween(), FindMinSet(), FitEllipse(), FitPair(), FitPSFToData(), FixLineEndings(), FlightEquilibrium(), FlightPathAngleFromCartEl(), FlybyConstantThrust(), FlybyHyperbola(), FlybyOptimal(), FlywheelStresses(), FocalLengthFromAngleOfView(), FocalPlaneImage(), FOPID(), FormDragCoeff(), FormFactorSurfaceOfRevolution(), FormFactorWing(), FracDI(), Fractal(), Frequency(), FResp(), FrictionLaminar(), FrictionSmooth(), Frustrum(), FuelFromRange(), FuelMassFromAccel(), FuelTimeOptimalAccel(), Fuselage(), GainPattern(), GAMin(), GasProperties(), GaussianDerivative(), GaussianImageFilter(), GaussianKernal(), GaussianRSG(), Gearbox(), GenerateGrid(), GenerateSwath(), GenerateTeamGoals(), GeneticAlgorithm(), GeoEclps(), GeoMagLatLon(), GeomagneticRigidity(), GeomPatch(), GeoOptimalMission(), GeoSwitchingMission(), GetCADVF(), GetStarPatch(), GetSubsystemMass(), Glide(), GlideslopeCircumnav(), GlideslopeGuidance(), GlideslopePlanner(), GlobeGrid(), GravitationalTimeDilation(), GravityGradientAnalytical(), GravityGradientBoom(), GravityGradientEigenvalues(), GravityGradientFrequency(), GravityGradientFromR(), GravityMap(), GravityUnitsConverter(), GroundEffect(), GroundStation(), GroundStationVisibility(), GroundTrackErrorBudget(), GuidedLaunchOpt2D(), GVEGuidance(), HalbachField(), HalbachMotorDesign(), HallThrusterModel(), HALOFamily(), HALOInit(), HALOState(), HeatExchangerWithLosses(), HeatingValue(), HeatTransferChannel(), HeatTransferCoeffTaylor(), HelicalGear(), HelioFromPlanetInit(), HelioToBPlane(), HeXeMixture(), HgCdTe(), HgCdTeWavelength(), Hills2DeltaElem(), HingeMoment(), HMS2Rad(), HoopStress(), HorizonAngle(), HorizonUnitVectors(), ICONS(), IdealJetEngineEfficiency(), IDotS4(), Illumination(), ImageDerivative(), Imager(), ImagerPSF(), ImpulsiveLPManeuver(), ImpulsiveManeuver(), InclinationRate(), InducedDragCoeff(), InertiaCubeSat(), InertiaFromOBJFile(), InertiaTubeSat(), Inflation(), InformDlg(), InitializeCostMatrix(), InitializeFormation(), InletAndNozzle(), InletLoss(), InsideAngleRange(), IntegratePSFs(), InterferenceFit(), IntersectPlaneAndSphere(), IntersectPlanet(), IsentropicExpansion(), ISO(), ISOEquivalent(), IsothermalLunar(), ISSCoord(), ISSOrbit(), IteratePeriodicOrbit(), IterativeImpulsiveManeuver(), JDStartTransfer(), JDToFirstOfMonth(), JDToMidnight(), JetEngine(), Knudsen(), L2OrbitPlots(), L2OrbitSim(), LADAREquation(), LADARTransmitPower(), LagrangePointsL1ToL5(), LambertDoubleRendezvous(), LandingControl(), LandingControlGravityTurn(), LandingDistance(), LargeFormationControl(), LaserBeamRadius(), LaserPower(), LatexScientificNotation(), LatLonToRangeAzimuth(), LDDeltaWing(), LensMakerFormula(), LETGuess(), LETPhasing(), LibrationCoeff(), LiftAndDragCoeff(), LiftAndDragJonesSearsHaack(), LiftAndDragSeaLevelToOrbit(), LiftAnlytMdl(), LiftCoeff(), LiftCoeffStall(), LiftToDragFromMach(), LightGathering(), LinearImageFilter(), LinearSinCosToQuadCos(), LinkBudget(), LinkOrbitAnalysis(), LiquidMetalProps(), Lissajous(), LLRToProb(), LoadCAD(), LoadILRSDataFromFRD(), LoadingToAccel(), LoadOBJFile(), LoadSAADData(), LocallyOptimalTraj(), LocalStarMap(), LocalTimeToGMT(), LocalTimeToJD(), LocusOfVisibility(), LogBaseN(), Logistic(), LossAtmosphericGas(), LossFreeSpace(), LowEnergyEarthToMoonTransfer(), LowEnergyTransferInCRTBP(), LowThrustDVToTransfer(), LowThrustTimeToTransfer(), LPCircularTimeWeight(), LPEccentricTimeWeight(), LRLoopAntenna(), LRRectangleAntenna(), LTPlaneChange(), LTSpiral(), LumenToWatt(), LunarDisplacement(), LunarHalo(), LunarLandingTargetState(), LunarProfile(), LunarTargeting(), LunarTrajectoryControl(), LunarVisibility(), LVModelFeasibilityFix(), LVThrustToWeight(), LyapunovFamily(), M2E(), MachAcrossShock(), MachFromAreaRatio(), MachFromMassFlowParameter(), MachFromPressureRatio(), MachSwept(), MagneticControl(), MagneticDipole(), MagneticDipoleCart(), MagneticFieldDipole(), MagneticHysteresis(), MagneticTorquerDesign(), MagneticTorquerDipoleMoment(), MahalanobisDistance(), MakeDistribution(), ManeuverDuration(), MarsRot(), MassBudget(), MassBudgetInput(), MassCrewAndPassenger(), MassEquivalentDV(), MassFlow(), MassFuelElectricConstantPower(), MassFuelElectricConstantThrust(), MassFuelElectricConstantUE(), MassInflowSupersonic(), MassPressureVessel(), MassPropertiesSolidObjFile(), MassPropertiesTetrahedron(), MassVolH2O2(), MatchingCircuit(), MatlabColorToObj(), MatrixDisplay(), MaximumDeltaV(), MaxShockIncidenceAngle(), MedianImageFilter(), MergeAngleRange(), MeshEllipsoid(), MHTDistance(), MHTInitialTrackScore(), MHTLLR(), MHTTrackMerging(), MHTTrackScore(), MHTTrackScoreKinematic(), MHTTrackScoreSignal(), MHTTrackTable(), MHTTrkToB(), MinimumExhaustVelocity(), MixedFlowTurbofan(), MixedFlowTurbofanProfile(), MolWt2R(), MomentumUnloading(), MoonRot(), MutualInductanceCoaxialCoil(), MutualInductanceCoil(), NACABladeMOI(), NavigationCameraSunStar(), NavTargetTrackingLunar(), NavTargetTrackingPlanetary(), NeptuneAirshipSizing(), NewtonianAerodynamicsFromCAD(), NewtonianAeroPropertiesFromOBJFile(), NewtonianAlphaFromCAD(), NewtonianCPFromCAD(), NewtonianForceECI(), NewtonianForceFromCAD(), NFromMT(), NonDimensionalOrbit(), NonKeplerianPlanet(), NonKeplerianSun(), NORAD(), NormalDistribution(), NoseCone(), Notch(), NPhase(), NuclearReactorModel(), NuclearThermalUE(), NumericalTransferFunction(), NusseltLaminar(), NutationMWA(), Nyquist(), ObliqueShockAngle(), OmegaFromU(), OmegaLVLH(), OpenFrame(), OpticalAngleError(), OpticalMagnification(), OpticalNavAccuracy(), OpticalNavigationMeasurement(), OpticalNavPlanetStarNoiseMatrix(), OpticalRadialDistortion(), OptimalAngleOfAttackHypersonic(), OptimalAssignment(), OptimalLunarLanding(), OptimalMLIDensity(), OptimalPayloadRatio(), OptimalTrajectory(), OptimalVehicle(), OrbDecay(), OrbElemDiff(), OrbitClosestPoint(), OrbitFromSynodic(), OrbitInsertion(), OrbitLoweringManeuvers(), OrbitRoundTripTransferTimes(), OrbMnvrLowerApogee(), OrbMnvrPhaseChange(), OrbTrackECI3D(), OrbView(), OverArea(), Panel(), PanelBoxCAD(), PanelFrame(), PanelWithCenterHole(), PanelWithCutout(), ParabolaToS(), ParabolicReflector(), ParasiticDragCoefficient(), ParksTransformation(), PartialDisk(), PatchedConicPlanner(), Period(), PeriodicOrbitFromGuess(), PeriodToSemimajorAxis(), Perpendicular(), PerUnitNormalization(), PID(), PID3Axis(), PILeaky(), Pilot(), PinholeCamera(), PitchMotorSizing(), PixelFlux2D(), PixelSpread(), PlanarHelioOptimal(), PlanarHelioOptimalSlidingTime(), PlanetAlignments(), PlanetaryAtmDens(), PlanetCentroid(), PlanetOpposition(), PlanetOptimalTraj(), PlanetSensorDualScan(), PlanetSim2D(), PlanetTrajectoryPlot(), PlanetWithTerrain(), PlanetWithTerrainPatch(), PlanetYear(), PlateTwoSided(), PlaybackControls(), Plot3Vector(), PlotAngleRange(), PlotBPlane(), PlotColor(), PlotDoubleYAxis(), PlotEMTraj(), PlotHysteresis(), PlotLET(), PlotLET3BP(), PlotLunarOrbit(), PlotOrbitPage(), PlotSEMTraj(), PlottingParabolas(), PlotV(), PlotVector(), PlotXYTrajectory(), PointInGridInTriangle(), PointInPolygon(), PointInTriangle(), PointSpreadFunction2DGaussian(), PolarStars(), PolygonProps(), PopulateCostMatrix(), PorkChopPlot(), PorkChopTOF(), PorkChopTOFKepler(), PositionLabel(), PowerFromActuatorDisk(), PowerPropeller(), PowerReceived(), PrandtlGlauertCorrection(), PrandtlNikuradse(), PrandtlNumber(), PressureDropChannel(), PressureRatioFromMach(), PressureRatioFromTemp(), PressureTotal(), PrintToImage(), PrivilegedAssignment(), ProbabilityOfFailure(), ProbDetection(), ProbToLLR(), ProcessASCIIGravityModel(), Propagate3BP(), Propagate4BP(), PropagateCRTBP(), PropagateCRTBPBackwards(), PropagateCRTBPToXAxis(), PropagateLowThrust(), PropellerEfficiency(), PtchCnc(), QFrom2U(), QFromDQ(), QFromU(), QRFuel(), QRHydrocarbon(), QRotateToAlignWithCon(), QSail(), QSpin(), QuadCost(), R2P5(), RadarEquationSN(), RadarPulseTrain(), RadarSN(), RadarThermalNoise(), RADecToPix(), RadiationBelts(), RadiationShapeFactor(), RadiationShield(), RAEToM(), Ramjet(), RamjetExternalHeatSource(), RamjetKerrebrock(), RamRecovery(), RandChiSquared(), RandomOrbit(), RandP(), RandPN(), RayleighPitotTube(), RayTraceLens(), RayTraceMirror(), RayTransferMatrix(), RayTransferMatrixFromLensFile(), RDE(), ReactionWheelDesign(), ReactionWheelFriction(), ReadBSPFile(), ReadCSVTable(), ReadImage(), RectangularBeam(), RectifierFullWave(), RectifierNPhase(), RectifierThreePhase(), RectilinearMotion(), RefineXAxisIntercept(), ReflectionLaw(), RelativeStateFromPoints(), RelativeVelocityError(), ReliabilityMOfN(), ReliabilityParallel(), ReliabilitySeries(), ResistanceAWG(), ResistivityCopper(), ReynoldsNumber(), RFSystemNoise(), RHS3DPointAircraft(), RHSClockDrift(), RHSCRTBP(), RHSCRTBP(), RHSFlatEarthSet(), RHSIsothermalCubeSat(), RHSPlanet3DToAB(), Ring(), RLagrange(), RMSNoiseImager(), RocketChemical(), RocketEquationRelativistic(), RocketFromUEAndT(), RocketH2O2(), RocketMass(), RocketModel(), RocketVariableUEAndT(), RollPitchToQECI(), RootLocus(), RootSort(), RotateOrbit(), RotBeamBending(), RPV2AE(), RToNu(), RTSS(), RVOrbGen(), RVToMEq(), RWAMnvrSizing(), RWAModel(), RWAPatch(), RWASizing(), SailMesh(), SailPatchVertices(), SailPropsToAccel(), SatelliteSubsystemMass(), SatelliteVisibility(), SaveMovie(), SCARAIK(), SCMG(), SecondOrderGuidance(), SecondOrderGuidance3D(), SectorPatch(), SegmentIntersection(), SelectTarget(), SEMGravAcc(), SemimajorAxisRevisit(), ShaftStresses(), Shannon(), ShapedStrut(), ShowCAD(), ShowThreeImages(), SignTest(), SimpAtm(), SimpleFuselage(), SimpleLiftAndDrag(), Simplex(), Simulate2DApproach(), SimulatedAnnealing(), SimulateFlyby(), SimulatePlanarHelioTrajectory(), SimulateStraightLineTrajectory(), SkinDepth(), SliderBar(), SolarCell(), SolarCellPower(), SolarFlux(), SolarFluxFromPlateECI(), SolarFlx(), SolarPressureForce(), SolarSysJPL(), SolarSystemElements(), SolarWingSupport(), SolidRocketInertia(), SolveLinearSinCos(), SonicBoom(), SonicBoomHypersonic(), SphericalGrid(), SphericalTankFluidHeight(), SphOI(), SpurGear(), SSFromNonlinear(), SSTokamak(), StagnationPAndT(), StallVelocity(), StarCameraBasicModel(), StarCameraModel(), StarCentroid(), StarCentroidCOM(), StarDensity(), StarTexture(), StateDisplay(), StaticEarthSensor(), StaticPumping(), SteamTablesSuperheatedEnthalpy(), StraightLineConstantAccel(), StraightLineConstantThrust(), StraightLineOptimal(), StreamlineShockAngle(), StrehlRatio(), StripedQuadrant(), Strut(), SubOrbTrajAnalysis(), SunAzEl(), SunBeta(), SunSensor(), SunVectorPointing(), SurfaceAreaEllipsoid(), SurfaceAreaEllipsoidRevolution(), SurfaceOfRevolution(), Sweep(), SweepAngle(), SwitchTime(), Symmetrize(), SynodicFromSemimajorAxes(), SynodicPlanets(), TakeoffDistance(), TakeoffTransition(), TakeoffVelocity(), TAntennaGround(), TargetFromRPVD(), TargetInFocalPlane(), Targeting3BP2(), Targeting4BP(), TargetSlew(), TaxiingFuel(), TelescopeAperture(), TemperatureTotal(), TempRatioFromMachAndGamma(), TempRatioFromPressure(), TempSph(), TerminatorPlanet(), TerrainCamera(), TGG(), ThermalEquilibrium(), Theta0(), Throttle(), ThrusterAlignment(), ThrusterAndRWACommand(), ThrusterCAD(), ThrusterCommand(), ThrusterLayout(), ThrusterPatch(), ThrustPropeller(), ThrustTurbofan(), TileOBJSphere(), TimeLabel(), TimeOfFlightHyperbola(), TimeStringToJD(), TimeToVelocity(), TOMHTTree(), ToneRanging(), Torus(), TotalPressureAndTemperature(), TPlate(), TrajectoryBetweenTwoPlanets(), TrajectoryOptimization(), TransformSEMRToHelio(), TReceiver(), Triangle(), TriangleWave(), TriangularManeuver(), TriangularTruss(), TrigReduction(), TripDistance(), TripTime(), TrueAnomalySpacing(), TrueAnomalyStartHyperbola(), Truss(), TrxCntrl(), TSky(), TSTODragData(), TSTOSizing(), Tube(), TubeArc(), TubeBetweenPoints(), TubeSatFaces(), TubeSatModel(), TubeSection(), Tubing(), Turbofan(), Turbofanramjet(), Turbojet(), TurbojetNoThrust(), TurboRamjet(), TurboRamjetSim(), TurboRamRocket(), TurningRadius(), TVDesign(), TwoDEscape(), TwoObjectTrajectoryViewer(), TwosComplementToFloat(), TwoUToQ(), UChannel(), UDipole(), UEQR(), UFromAlphaBeta(), UMinGG(), UnitVectorAverage(), UnitVectorFromOffset(), UranusAirshipSizing(), URWAPyramid(), USR30Motor(), UToConeClock(), V0FromJacobiConstant(), VAWTBearingDistance(), VCFlatFile(), VelAltFpaToAENu(), VelocityLabel(), VelocityTimeDilation(), VEscape(), VM2Electrons(), VM2Int(), VM2Photons(), VM2PSFPeak(), VMToPhotons(), VStall(), WalkerConstellation(), Watermark(), Wavelength(), WavelengthToBandGap(), WaveletMorlet(), Wedge(), WeldThroatArea(), WettedArea(), Wind(), WindAdmittance(), WindClass(), WindDeterministic(), WindProfile(), WindShear(), WindShearExponent(), WindspeedHours(), WindStochastic(), WindTurbinePower(), Wing(), WingAreaToTaper(), WingFromParameters(), WingSizingForPullUp(), WMM(), WorldToCamera(), WorstEclipseFraction(), WriteBSPFile(), WriteEngineData(), XenonTankSupport(), YBComp(), and ZodiacalLight().
HyperRDE()
function HyperRDE (in m, in d, in p)
References and(), get(), HyperRDE(), RDE(), and Series().
Referenced by HyperRDE().
PartStdAtm()
function PartStdAtm (in p, in j)
Referenced by Turbofanramjet(), TurboRamjet(), and TurboRamRocket().