PSS MATLAB Toolboxes: Aerospace/SpacecraftEstimation/StarSimulation/IntegratePSFs.m File Reference
IntegratePSFs.m File Reference
IntegratePSFs>>DefaultData.
Functions
function DefaultData ()
Finds the output of each pixel through numerical integration.
blank line function IntegratePSFs (in d, in nPix)
Function Documentation
IntegratePSFs()
blank line function IntegratePSFs (in d, in nPix)
References and(), Centroid(), DefaultData(), Demo(), get(), Imager(), ImagerPSF(), IntegratePSFs(), length(), NewFig(), RHSGaussianPSF(), set(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by IntegratePSFs().