PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/Analysis/MessageAnalysis.m File Reference
MessageAnalysis.m File Reference
post-simulation message analysis for DFF Post-simulation message analysis for DFF.
Functions
blank line function MessageAnalysis (in msg)
Detailed Description
Since version 7.
Form
MessageAnalysis(msg)
Inputs
msg (.) Array of message data structures transmitted between spacecraft over the ISL. After a simulation has been run using the DFFSimulation function, obtain the messages with: msg = DFFISLManagement('get messages');
Outputs
none
Post-simulation message analysis for DFF.
Function Documentation
MessageAnalysis()
blank line function MessageAnalysis (in msg)
References DFFISLManagement(), DFFSimulation(), get(), isempty(), length(), and zeros().