PSS MATLAB Toolboxes: AC/ACControl/Pilot.m File Reference
Pilot.m File Reference
Functions
function Pilot (in kP, in tauDelay, in tauLead, in tauLag, in tauNeuro, in nDelay, in sType, in tSamp)
Function Documentation
Pilot()
function Pilot (in kP, in tauDelay, in tauLead, in tauLag, in tauNeuro, in nDelay, in sType, in tSamp)
References and(), C2DelZOH(), C2DZOH(), Delay(), Demo(), FResp(), isempty(), ND2SS(), Pade(), Pilot(), Rename(), Series(), SSEmpty(), and statespace().
Referenced by AircraftControlCAS(), AirshipControlSim(), CompE(), and Pilot().