PSS MATLAB Toolboxes: SC/Dynamics/PlotFlex.m File Reference
PlotFlex.m File Reference
Functions
function PlotFlex (in d, in eta, in opt)
function PlotModeShape (in d, in eta, in mode)
Copyright (c) 1997-2005 Princeton Satellite Systems, Inc.
Function Documentation
PlotFlex()
function PlotFlex (in d, in eta, in opt)
References GetFlex(), isempty(), PlotFlex(), and PlotModeShape().
Referenced by GetFlex(), and PlotFlex().
PlotModeShape()
function PlotModeShape (in d, in eta, in mode)
 Plots the flex model including the mode shapes.
 If only d is entered (first form below) the function will plot the mode
 shapes for unit mode displacments. The 'model' option plots the total node
 displacement for the given mode displacement, eta. The 'nodes' option plots
 the total node displacment for unit modal displacements.
 See GetFlex for formatting data into the needed structure.
Form
 PlotFlex( d )
 PlotFlex( d, eta, opt )
Inputs
 d      (:)     Flex model data structure
                .name   (1,:)   Name of the component
                .nNodes (1,1)   Number of nodes
                .nModes (1,1)   Number of modes
                .node   (n)     Node data structure
                                .r       (3,1)  Location of each node
                                                with respect to the origin
                                .mass    (1,1)  Mass of each node
                                .inertia (3,3)  Inertia of each node
                                .nodeID  (1,1)  Node id
                .mode   (m)     Mode data structure
                                .modeID  (1,1)  Mode id
                                .phi     (6,n)  x = phi*eta where
                                               eta is the mode displacement
                                .omega   (1,1)  Modal frequency
 eta    (m)     Mode displacements*
 opt    (p,:)   Options*        'mode shapes' (default value)
                                'model', total node displacement
                                'nodes'
                                    * Optional inputs
Outputs
 None
 All rights reserved.
Plot the mode shape
References isempty(), length(), NewFig(), Plot2D(), set(), TitleS(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by PlotFlex().