PSS MATLAB Toolboxes: Interplanetary/LowEnergyManeuver/PropagateCRTBPBackwards.m File Reference
PropagateCRTBPBackwards.m File Reference
PropagateCRTBPBackwards>RHSCRTBP.
Functions
function Demo ()
RHS.
function PropagateCRTBPBackwards (in y, in t0, in tF, in mu)
ingroup InterplanetaryFunctions function RHSCRTBP (in ignoredArg, in y, in mu)
Copyright (c) 2010 Princeton Satellite Systems, Inc.
Detailed Description
Date
PropagateCRTBPBackwards.m
Id
0345ae7bbe6275ea28027ce8ee69c7f4278233e9
Function Documentation
Demo()
function Demo ()
References PropagateCRTBPBackwards().
PropagateCRTBPBackwards()
function PropagateCRTBPBackwards (in y, in t0, in tF, in mu)
References Constant(), Demo(), PropagateCRTBPBackwards(), RHS(), RHSCRTBP(), vector(), and zeros().
Referenced by Demo(), PropagateCRTBPBackwards(), and RHSCRTBP().
RHSCRTBP()
ingroup InterplanetaryFunctions function RHSCRTBP (in ignoredArg, in y, in mu)
 Propagate an arbitrary CRTBP with origin at the secondary body
 backwards
Form
 [yvec, tvec] = PropagateCRTBPBackwards(y,t0,tF,mu);
Inputs
 y     (6,1) Current state vector [r;v]
 t0    (1,1) Initial time
 tF    (1,1) Final time (positive)
 mu    (1,1)    CRTBP mass parameter
Outputs
 yvec   (6,:) State vector
 tvec   (1,:) Time vector
All rights reserved.
Since version 2018.1 < PropagateCRTBPBackwards>RHSCRTBP
References Demo(), PropagateCRTBPBackwards(), and TimeLabl().
Referenced by PeriodicOrbitFromGuess(), PropagateCRTBPBackwards(), and RHSCRTBP().