PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/CommandLists/ProjCircCommandList.m File Reference
ProjCircCommandList.m File Reference
Command list for achieving a dual-plane projected circle,.
Functions
blank line function ProjCircCommandList ()
Command list for achieving a dual-plane projected circle,.
Function Documentation
ProjCircCommandList()
blank line function ProjCircCommandList ()
with the reference on one of the circles.
Since version 7.
Form
cmd = ProjCircCommandList;
Inputs
none
Outputs
cmd (.) Data structure of commands to be sent to the cluster
References Command_Structure(), DFFAttitudeController(), DFFControlLaw(), DFFGuidanceLaw(), DFFTeamManagement(), Initialize(), ProjCircCommandList(), set(), and Window_Structure().
Referenced by CollisionCommandList(), ProjCircCommandList(), and ProjCircSimStruct().