PSS MATLAB Toolboxes: Aerospace/Interplanetary/LowEnergyManeuver/PropagateCRTBPToXAxis.m File Reference
PropagateCRTBPToXAxis.m File Reference
Propagate the CRTBP equations of motion for arbitrary mu.
Functions
ingroup InterplanetaryFunctions function Demo ()
Finds the state when the trajectory hits the x-axis.
function PropagateCRTBPToXAxis (in y, in t0, in tol, in mu)
Propagate the CRTBP equations of motion for arbitrary mu.
Detailed Description
Date
PropagateCRTBPToXAxis.m
Id
f406d11d952edb2b5c7626b438289b4f360c2564
Function Documentation
Demo()
ingroup InterplanetaryFunctions function Demo ()
Type PropagateCRTBPToXAxis for a demo
Form
[tF, yF] = PropagateCRTBPToXAxis(y,t0,tol,mu);
Inputs
y (6,1) Current state vector [r;v] t0 (1,1) Initial time tol (1,1) Convergence tolerance mu (1,1) CRTBP mass ratio
Outputs
tF (1,1) Time at the intersection with the x-axis yF (6,1) State at the intersection with the x-axis Copyright (c) 2010 Princeton Satellite Systems, Inc. All rights reserved.
Since version 2018.1 Earth is the default Plot PropagateCRTBPToXAxis>Demo
PropagateCRTBPToXAxis()
function PropagateCRTBPToXAxis (in y, in t0, in tol, in mu)
References abs(), Demo(), Mag(), NewFig(), PropagateCRTBP(), PropagateCRTBPToXAxis(), and vector().
Referenced by PropagateCRTBPToXAxis().