PSS MATLAB Toolboxes: FormationFlying/Demos/Guidance/RendezvousSim.m File Reference
RendezvousSim.m File Reference
Demonstrate rendezvous control with PD or LQ Published Demo
Functions
function RHS (in x, in ignoredArg, in d)
Copyright (c) 2020 Princeton Satellite Systems, Inc.
Detailed Description
This allows for both a PD controller and LQ (linear quadratic) controller. Both work in continuous time. Script contains an embedded RHS function.
See also
LinOrb, QCR, Riccati, DispWithTitle, TimeLabl, RK4, Odd
Function Documentation
RHS()
function RHS (in x, in ignoredArg, in d)
All rights reserved. Constants Design a quadratic regulator Design a PD controller Simulation Plotting Hills equations
Referenced by AllanVariance(), AsteroidTrajectory(), BilinearTangentAltitude(), BilinearTangentLaw(), CDKF45(), ClimbAngle(), Cost3D(), CostLowThrust2D(), CostSail2D(), CostSail3D(), CovarianceRHS(), CycleDesign(), DrawCubeSatSolarAreas(), DVFromMassAndIsp(), EarthEscape(), ECI2OrbitPlane(), EquilibriumControls(), FCoreAndMoving(), FFMaintenanceSim(), FLagrange(), FLowThrust2D(), FOPID(), FPlanetControl(), FRotatingLagrange(), FRotatingPlanet(), FRY(), FSolarSailAngles(), FSolstice(), FSRHS(), FTimeVaryingI(), GeoOptimalMission(), GetHillsMats(), GetLVLHMats(), GuidedLaunch2DSim(), GuidedLaunch3DRHS(), HeatExchangerWithLosses(), ImagerPSF(), InitializeSailSim(), IntegratePSFs(), IteratePeriodicOrbit(), J2Prop(), LargeFormationControl(), LaunchOptions(), LaunchRHSData(), LunarTargeting(), MachFromAreaRatio(), MaxShockIncidenceAngle(), NonlinearEstimator(), ObliqueShockAngle(), OptimalAngleOfAttackHypersonic(), PrandtlNikuradse(), PressureDropChannel(), Propagate4BP(), PropagateCRTBPBackwards(), QFrenet(), RadiationShield(), RelState2Absolute(), RHS2DAnglePolarOrbit(), RHS2DCylindricalOrbit(), RHS2DOrbit(), RHS2DPolarOrbit(), RHS3DOrbit(), RHSCartesian(), RHSCartesianRadialAccel(), RHSCRTBP(), RHSCubeSat(), RHSEquinoctial(), RHSFlatEarthSet(), RHSHelio2DOrbit(), RHSLaunchVehicle2D(), RHSMinTOrbitInjection(), RHSMomentum(), RHSOpt2DOrbit(), RHSOpt3DOrbit(), RHSRVPlanetFixed(), RHSSNP(), RHSSNP(), RK4TI(), RocketH2O2(), RWASmart(), SafeGuidanceSim(), SailClosedLoopNLEqns(), SCARAIK(), SecondOrderGuidance(), SecondOrderGuidance3D(), SimulateFlyby(), SolveFlybyPower(), SRiccati(), SSFromNonlinear(), StateSpacePlugIn(), StraightLineConstantAccel(), SubOrbTrajAnalysis(), TestFFEccLinOrb(), TrueAnomalyStartHyperbola(), UKF(), UKFP(), UKUDF(), UMinGG(), WT_Blades(), and WT_VAWTBlades().