PSS MATLAB Toolboxes: Propulsion/Demos/Rocket/SLSLaunchAnalysis.m File Reference
SLSLaunchAnalysis.m File Reference
Artemis Launch Analysis Published Demo
Functions
function DVFromMassAndIsp (in mF, in mT, in iSp)
Copyright (c) 2022 Princeton Satellite Systems, Inc.
Detailed Description
Compute the change in velocity, DV, from masses and iSp dV = DVFromMassAndIsp(mF, mT, iSp)
This script analyzes the SLS launch vehicle. It designs an all-liquid booster, using the same RS-25 engines, and compares the performance. It includes launch simulations.
The following gives reference information used in the script.
System
https://www.nasa.gov/exploration/systems/sls/factsheets.html http://www.braeunig.us/space/specs/sls.htm
The SLS core stage and its two solid rocket boosters (SRBs) generated a total of 8.8 million pounds of thrust
Solid Rocket Booster Details (5 segment)
Length: 177 feet (53.9 meters) Diameter: 3.71 meters Total mass: 731,885 kg each Propellant mass: 631,495 kg Propellant: polybutadiene acrylonitrile (PBAN) Thrust: 16,000 kN each Specific impulse: 242 s (sea level), 268 s (vacuum) Operational time: 127 seconds
Core Stage Details
Length: Approximately 212 feet (64.6 meters) Diameter: 27.6 feet (8.4 meters) Dry mass: Approximately 188,000 lbs (85,275 kg) Burnout mass: 112,000 kg Usable propellant mass: 979,452 kg Capacities: Liquid Hydrogen (LH2) 537,000 gallons (2 million liters) (317,000 pounds) | Liquid Oxygen (LOX)196,000 gallons (741,941 liters) (1.86 million pounds)
RS-25D Details:
Thrust: 416,300 lbs. (~1860 kN) (sea level), 512,300 lbs. (2280 kN) (vacuum) Specific impulse: 363 s (sea level), 453 s (vacuum) Dry Mass: 3,525 kg
See also
: RocketModel, RocketMass, TimeHistory, LatexExp,
DisplayLatexTable, AtmDens2, StdAtm, SLSLaunchAnalysis>RHS
SLSLaunchAnalysis>SRBThrustInterp, SLSLaunchAnalysis>DVParallel
SLSLaunchAnalysis>DVFromMassAndIsp
mF - fuel mass mT - total mass
Artemis Launch Analysis Published Demo
Function Documentation
DVFromMassAndIsp()
function DVFromMassAndIsp (in mF, in mT, in iSp)
All Rights Reserved.
Since version 2023.1 2023.1 Pass data to StdData/RocketModel for faster simulation Setup Parallel DV of SRBs and RS25s SLS Properties SRB Properties RS-25 Properties All liquid booster (LB) Mass of fuel burned in parallel (core+LB) LB tank will only be partially filled for the SLS with LBs Velocity change for parallel boostoer Liquid booster volume SLS with LB Properties LB Properties SLS SRB vs SLS LB Comparison Simulate with LBs The RS-25 thrust and iSp varies with altitude Get current RS-25 thrust and specific impulse for engines Simulate with SRBs Get current RS-25 thrust and specific impulse for engines
References abs(), and(), AtmDens2(), DVFromMassAndIsp(), and RHS().
Referenced by DVFromMassAndIsp().