PSS MATLAB Toolboxes: Aerospace/SAAD/GUI/SMInputs.m File Reference
SMInputs.m File Reference
Functions
function CGAdv ()
get main window position
function ClosedFormMethod (in methodButton, in name, in code, in shortName)
Brings up a window for customizing the inputs to the given solution method.
function Covariances (in name, in ignoredArg, in shortName)
Get stored values.
function DCAdv ()
get main window position
function DeleteUnavailableHSAs (in hSAs, in avail)
Determines which HSAs were last used for this solution method.
function KalAdv ()
Position window correctly, and get list of all method names except this one.
function LastHSAs (in methodButton)
get main window position
function NMAdv ()
get main window position
function NumMethod (in name, in code, in shortName)
Get stored values.
function SetCFFlags (in methodButton, in windowName, in flagName)
function SMInputs (in action, in solutionMethod, in varargin)
Function Documentation
CGAdv()
function CGAdv ()
Inputs
none
Outputs
a Handle to the window created Get initial values Sizing Basic properties Error Tolerance SVD Tolerance Show Condition Number Help button
ClosedFormMethod()
function ClosedFormMethod (in methodButton, in name, in code, in shortName)
Form
h = SMInputs(action, solutionMethod, varargin)
Inputs
action 'Open Window' or 'Set Values' solutionMethod String containing the solution method
Outputs
h Handle to window created Copyright (c) 1997-8 Princeton Satellite Systems, Inc. All rights reserved. if using a closed form method, varargin contains the handle to the checkbox for this method Subfunctions to create each of the input windows
References and(), get(), and SAADTool().
Covariances()
function Covariances (in name, in ignoredArg, in shortName)
Inputs
name Method name, used for callbacks code Shorter, 1 or 2 character name used for labeling shortName Used to label window; default value is name
Outputs
a Handle to the window created Correlate method names, number, and input names Position window correctly Other sizing values get main window position Determine which boxes will be checked Determine which boxes will be active Button names, spacing Make state buttons Buttons for other options
References and(), and get().
DCAdv()
function DCAdv ()
Inputs
none
Outputs
a Handle to the window created Get initial values Sizing Basic properties Forgetting factor Number of Iterations Attitude Reference Help button
DeleteUnavailableHSAs()
function DeleteUnavailableHSAs (in hSAs, in avail)
Checks the userdata of the methodButton; if userdata doesn't exist or is invalid then the first output is determined by the HSAs with available data, and lastHSAs is -1. Otherwise, both hSAs and lastHSAs are the same as the userdata
Inputs
methodButton (1) Handle to the checkbox for this method
Outputs
hSAs (1) 1 if HSA 1, 2 if HSA 2, 3 if both, 0 if none avail (2) For each HSA, 1 means data is available, 0 means no data lastHSAs (1) Userdata of methodButton if it exists and is valid (has value in 0:3); -1 else
KalAdv()
function KalAdv ()
Inputs
name Method name, used for callbacks code Shorter, 1 or 2 character name used for labeling shortName Used to label window; default value is name
Outputs
a Handle to the window created Sizing their contents to allow room between left side and text and all frames are 2 points higher than their contents get main window position Make Covariance window Get initial values - they are stored in radians^2, and the default display units are deg^2 Table Header move position reference down
References get().
LastHSAs()
function LastHSAs (in methodButton)
Inputs
none
Outputs
a Handle to the window created Get initial values Sizing Basic properties X Tolerance Cost Tolerance Max number of steps Show intermediate steps Help button
NMAdv()
function NMAdv ()
Inputs
none
Outputs
a Handle to the window created Get initial values Basic properties Sizing Cost Tolerance Show progress reports Use Steepest Descent Help button
NumMethod()
function NumMethod (in name, in code, in shortName)
Inputs
methodButton Handle to the checkbox for this method name Method name, used for callbacks code Shorter, 1 or 2 character name used for labeling shortName Used to label window; default value is name
Outputs
a Handle to the window created Position window correctly no change get main window position: maxHigh and maxWide are from SAADData Determine which button should appear pressed, and if any should be inactivated because of lack of data Store handles to other radio buttons in userdata
SetCFFlags()
function SetCFFlags (in methodButton, in windowName, in flagName)
Inputs
hSAs (1) 1 if HSA1, 2 if HSA2, 3 if both, 0 if neither avail (2) avail(i) = 1 if data is available for HSAi =0 if no data
Outputs
hSAs (1) 1 if HSA 1, 2 if HSA 2, 3 if both, 0 if none
SMInputs()
function SMInputs (in action, in solutionMethod, in varargin)