PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/DefaultData/SpacecraftParameters.m File Reference
SpacecraftParameters.m File Reference
Obtain the specified set of fixed spacecraft parameters (for DFF system).
Functions
blank line function SpacecraftParameters ()
Obtain the specified set of fixed spacecraft parameters (for DFF system).
Function Documentation
SpacecraftParameters()
blank line function SpacecraftParameters ()
Form
d = SpacecraftParameters;
Inputs
none
Outputs
d (.) Data structure of spacecraft parameters
References DefaultTankData(), DFFThrusters(), get(), length(), set(), SpacecraftParameters(), and vector().
Referenced by AutoDualPCSimStruct(), AutoFormSimStruct(), ClusterGoalsDemoSimStruct(), CollisionDetectSimStruct(), DemoManeuverSimStruct(), DFFSimStruct(), EccentricTetrahedronSimStruct(), MainDemoSimStruct(), ProjCircSimStruct(), SimpleManeuverSimStruct(), SpacecraftParameters(), TeamManagementSimStruct(), TestADCSSimStruct(), TestCollisionSimStruct(), TestControlSimStruct(), and TestTeamMgtSimStruct().