PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/Sensors/StateSensor.m File Reference
StateSensor.m File Reference
State sensor.
Functions
blank line function StateSensor (in action, in d, in k)
State sensor.
Detailed Description
Gives the ideal states of the system.
Function Documentation
StateSensor()
blank line function StateSensor (in action, in d, in k)
Gives the ideal states of the system.
Form
y = StateSensor(action, d, k)
Inputs
action (1,:) 'initialize', 'derivative', 'output', 'fail' d (1,1) Depends on the action k (1,1) Unique Spacecraft Identifier
Outputs
y (1,1) Depends on the action
References get(), set(), and zeros().