PSS MATLAB Toolboxes: Aerospace/SC/Sensor/StaticEarthSensor.m File Reference
StaticEarthSensor.m File Reference
StaticEarthSensor>Demo.
Functions
function Demo ()
Static Earth sensor model.
blank line function StaticEarthSensor (in q, in r, in d)
Function Documentation
StaticEarthSensor()
blank line function StaticEarthSensor (in q, in r, in d)
References DefaultDataStructure(), Demo(), length(), Mag(), QForm(), QMult(), SinD(), StaticEarthSensor(), Unit(), and zeros().
Referenced by Demo(), and StaticEarthSensor().