PSS MATLAB Toolboxes: OpticalNavigation/Demos/Terrain/SyntheticTerrain.m File Reference
SyntheticTerrain.m File Reference
SyntheticTerrain is a script created to create synthetic terrain Published Demo
Functions
function square (in hmap, in interp, in iteration, in scale, in im_m, in im_n, in input_location_x, in input_location_y, in method)
Copyright (c) 2021 Princeton Satellite Systems, Inc.
Detailed Description
function to perform square portion of square-diamond interpolation
Allan et al.'s work https://doi.org/10.1109/AERO.2019.8741780 to create a s terrain generator for the lunar surface to create high resolution images from the currently available low resolution images from http://imbrium.mit.edu/
This script upscales the input image and outputs a synthetic higher resolution version of the input image:
separates the high and low frequencies of the input image
performs fractal synthesis by the diamond-square method on the high frequency portion of the image and uses the Catmull-Rom spline interpolation method to generate new data
performs bilinear interpolation on the low frequency component of the image
recombines the high and low frequencies of the input image and returns the final image
key input variables the user can change:
c_img - the input image (this should be a dem but the script was mostly tested on optical images. may need different frequency splitting method for low contrast dems avaialable.) the input image needs to be a square with even # of pixels. I recommend starting with a small 500x500 image.
scale - determines the upscaling of the input image. this needs to be a power of 2. i.e. scale = 2, 4, 8, 16 etc.
freq - determines the frequency split between high and low frequencies. make use of the figure showing the frequency split to determine what the frequency should be for the input image. This needs to be between [0,1].
interp - sets the interpolation method. by default this is 'spline' for Catmull-Rom Spline and 'linear', or linear interpolation, is only used on edge cases. However this can be changed to 'linear' for the entire image for comparison. This can only be 'spline' or 'linear'.
key outputs:
hmap - final heightmap. this is the upscaled input image. size will be scale*input image size
method - matrix with indices indicating if a pixel was interpolated with the square or diamond method and the iteration number. 1:iter_max are squares for each iteration. iter_max+1:iter_max+iter_max are diamonds for each iteration. useful for debugging or for understanding final image artifacts.
Online resources:
Diamond-square method https://stevelosh.com/blog/2016/06/diamond-square/
catmull rom spline https://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline
SyntheticTerrain is a script created to create synthetic terrain Published Demo
Function Documentation
square()
function square (in hmap, in interp, in iteration, in scale, in im_m, in im_n, in input_location_x, in input_location_y, in method)
All rights reserved.
Since version 2021.1 Lunar image Fourier transform to separate high and low freq data Taken from Maggie Kautz's homework for OPTI 512L from UArizona fourier transforms to split high and low frequencies by freq input variable Fourier transform original image Make a meshgrid the same size as input image Change this variable to change frequency split Use meshgrid to greate high and low pass filters Use high and low pass filters on fourier transform of the original image Inverse fourier transform to return data we can use Take real portion of inverse fft for visualization purposes Make real portion of fft into rgb images for visualizations at the end of the code Plot frequency split to see if freq variable needs to be changed High freq: square-diamond interpolation perform square-diamond interpolation only on high frequency portion get size of high frequency portion set upscaling factor (needs to be power of 2: 2,4,8,16, etc.) set interpolation method (either 'linear' or 'spline') initilize heightmap and diamond-square method output add existing data to heightmap position original data determined by scale*x+1,scale*y+1 starts at 1,1 when x=y=0 save position of original data rename original data to square input variables Low freq: bilinear interpolation use matlab function to bilinear interpolate low frequency data Rejoin frequencies recombine processed high and low frequencies normalize make rgb for visualization Plotting Original terrain image subplots to see before and after for low and high frequencies final output image Square interpolation
References and(), CatmullRomSpline(), get(), length(), square(), and zeros().
Referenced by AccelToSailProps(), AirshipGeometry(), AlphaCentauriSystem(), AutoPoint(), C2DelZOH(), C2DFOH(), C2DPulse(), C2DZOH(), C2DZOHWD(), CalibrateSunSensor(), CalibrationCube(), CameraDatabase(), CameraImage(), CentroidNoise(), ClimbAngle(), CompareHills(), ConeClockPatches(), ConvolveImage(), DBsmToSM(), DetectorModel(), DLyapG(), DQCE(), DrawAirship(), DrawSCPlanPlugIn(), DRiccati(), FindMinSet(), FlightEquilibrium(), FrictionLaminar(), GeoOptimalMission(), GeoSwitchingMission(), GPSSatellite(), GridPathCost(), GridSuccessorNodes(), GridTraverseCost(), GroundStationVisibility(), HRakoczy(), HUD(), InducedDragCoeff(), IntersectPlaneAndSphere(), LatLonToR(), LyapG(), MakeSquareSail(), MSR(), OptimalAssignment(), OrbitalPlane(), OrbMnvrHohmann(), PlanetTransferLambert(), PlotLambertTransfer(), PltOrbit(), PointCameraModel(), PressureDropChannel(), QCE(), RadarCrosssection(), RADecToPix(), RandChiSquared(), ReshapeCovariance(), Riccati(), S4DeployTorque(), SailEnvironment(), SatelliteVisibility(), SkewSq(), SMToDBsm(), SpaceCamera(), SqrFOV(), square(), StarDensity(), StarPrediction(), SunSensor(), Symmetrize(), TransformGridCoordinates(), Truss(), UKF(), VisualizeSailAttitude(), WorstFirstAssignment(), and ZodiacalLight().