PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/Initialize/TestControlSimStruct.m File Reference
TestControlSimStruct.m File Reference
Set up the data structure for testing the controller.
Functions
blank line function TestControlSimStruct (in e)
Set up the data structure for testing the controller.
Function Documentation
TestControlSimStruct()
blank line function TestControlSimStruct (in e)
Since version 7.
Form
sim = TestControlSimStruct;
Inputs
e (1) Reference orbit eccentricity
Outputs
sim (.) Simulation data structure to be input to DFFSimulation
References DFFSimulation(), JD2000(), LoadGravityModel(), OrbRate(), SpacecraftParameters(), TestControlCommandList(), and TestControlSimStruct().
Referenced by DemoManeuverCommandList(), SimpleManeuverSimStruct(), TestControlCommandList(), and TestControlSimStruct().