PSS MATLAB Toolboxes: FormationFlying/IntegratedSim/CommandLists/TestControlCommandList.m File Reference
TestControlCommandList.m File Reference
Command list for the testing the controller.
Functions
function TestControlCommandList ()
Command list for the testing the controller.
Detailed Description
Two spacecraft initialized
Function Documentation
TestControlCommandList()
function TestControlCommandList ()
Two spacecraft initialized
 in a leader-follower formation, plus a small semi-major axis difference.
 One is initialized as the reference. The other is commanded to achieve
 non-centered out-of-plane periodic motion. Ideal actuation and perfect
 state-sensing are assumed. No gravitational perturbations are modeled.
 The eccentricity may be set in the TestControlSimStruct file.
 Since version 7.
Form
 cmd = TestControlCommandList;
Inputs
 none
Outputs
 cmd          (.)    Data structure of commands to be sent to the cluster
References and(), Command_Structure(), DFFAttitudeController(), DFFControlLaw(), DFFTeamManagement(), EccGeometry_Structure(), Geometry_Structure(), Initialize(), plus(), set(), Team_Structure(), TestControlCommandList(), TestControlSimStruct(), and Window_Structure().
Referenced by TestControlCommandList(), and TestControlSimStruct().