PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/CommandLists/TestMonitoringCommandList.m File Reference
TestMonitoringCommandList.m File Reference
Command list for Collision Detection Simulation.
Functions
blank line function TestMonitoringCommandList ()
Command list for Collision Detection Simulation.
Function Documentation
TestMonitoringCommandList()
blank line function TestMonitoringCommandList ()
Since version 7.
Form
cmd = TestMonitoringCommandList;
Inputs
none
Outputs
cmd (.) Data structure of commands to be sent to the cluster
References Command_Structure(), DFFCollisionMonitor(), DFFTeamManagement(), Initialize(), set(), and TestMonitoringCommandList().
Referenced by TestCollisionSimStruct(), and TestMonitoringCommandList().