PSS MATLAB Toolboxes: Aerospace/FormationFlying/IntegratedSim/Initialize/TestCollisionSimStruct.m File Reference
TestCollisionSimStruct.m File Reference
Set up a DFF simulation data structure to demonstrate collision detection.
Functions
blank line function TestCollisionSimStruct (in el, in nOrbits, in nSC, in jD, in ideal)
Set up a DFF simulation data structure to demonstrate collision detection.
Function Documentation
TestCollisionSimStruct()
blank line function TestCollisionSimStruct (in el, in nOrbits, in nSC, in jD, in ideal)
by the Collision Monitoring agent. All inputs are optional
Since version 7.
Form
sim = TestCollisionSimStruct(el, nOrbits, nSC, jD, ideal);
Inputs
el (n,:) Initial element set for all spacecraft. nOrbits (1) Number of orbits simulation will last. nSC (1) Number of spacecraft to simulate. jD (1) Julian date at start of simulation. ideal (1) Flag indicating whether to use ideal actuation.
Outputs
sim (.) Simulation data structure, input to DFFSimulation
References DFFSimulation(), JD2000(), LoadGravityModel(), OrbRate(), set(), SpacecraftParameters(), and TestMonitoringCommandList().