PSS MATLAB Toolboxes: FormationFlying/IntegratedSim/CommandLists/TestADCSCommandList.m File Reference
TestADCSCommandList.m File Reference
Command list for testing the proper function of the ADCS.
Functions
function TestADCSCommandList ()
Command list for testing the proper function of the ADCS.
Function Documentation
TestADCSCommandList()
function TestADCSCommandList ()
 Since version 7.
Form
 cmd = TestADCSCommandList;
Inputs
 none
Outputs
 cmd          (.)    Data structure of commands to be sent to the cluster
References Command_Structure(), DFFAttitudeController(), DFFAttitudeManeuver(), Initialize(), and TestADCSCommandList().
Referenced by TestADCSCommandList(), and TestADCSSimStruct().