PSS MATLAB Toolboxes: Aerospace/SC/Sensor/ToneRanging.m File Reference
ToneRanging.m File Reference
Functions
function Delay (in s, in t, in tau)
function Square (in s)
Demo.
function ToneRanging (in rS, in r, in fClock, in nTones)
Function Documentation
Delay()
function Delay (in s, in t, in tau)
References ToneRanging().
Square()
function Square (in s)
Speed of light Round trip time Outgoing tones Incoming tone through squaring function
Referenced by AnalyzeVariableTimeDV(), CalibrationCube(), ComplexToReal(), DBsmToSM(), ErrorCombination(), FindMinSet(), FPSensors(), GPSOrbit(), Markov(), RADecToPix(), RMarkov(), SkewSq(), SMarkov(), SMToDBsm(), and WorstFirstAssignment().
ToneRanging()
function ToneRanging (in rS, in r, in fClock, in nTones)
References Demo().
Referenced by Delay().