PSS MATLAB Toolboxes: WindTurbine/Sim/Models/Blades/WT_VAWTBlades.m File Reference
WT_VAWTBlades.m File Reference
Functions
function WT_BladesRHS2 (in x, in d)
Copyright (c) 2008 Princeton Satellite Systems, Inc.
function WT_VAWTBlades (in input, in time)
Function Documentation
WT_BladesRHS2()
function WT_BladesRHS2 (in x, in d)
 Default Wind Turbine Blade Model. For use in WTSim.m.
 Forms:
 ioData = WT_Blades;                 % Obtain i/o data
 output = WT_Blades( input, time );  % Update with current sim time
 output = WT_Blades( input, -1 );    % initialize
Inputs
 input       (.)  Input data structure
 time        (1)  Simulation time
Outputs
 output      (.)  Output data structure
All rights reserved. return input / output structure (use "memory" field for internal states) initialize input.blades supplied inputs wind speed integrate the angular rate with net torque The generator torque is computed below for this example. Inputs from the transmission block are not used (as in the HAWT example). update state send output RHS FUNCTION
WT_VAWTBlades()
function WT_VAWTBlades (in input, in time)
References Mag(), RHS(), RK4TI(), TorqueVAWT(), Wind(), WT_Blades(), WT_BladesRHS2(), and WTSim().
Referenced by WT_VAWTSetup().