PSS MATLAB Toolboxes: WindTurbine/Sim/SetupFiles/WT_HAWTSetup.m File Reference
WT_HAWTSetup.m File Reference
Copyright (c) 2008 Princeton Satellite Systems, Inc.
Functions
function WT_HAWTSetup ()
Detailed Description
 Default setup file for wind turbine simulation. For use in WTSim.m.
 Forms:
 % Obtain input/output data structure information
 ioData = WT_WindModel;
 % Supply input data, update, and return output
 output = WT_WindModel( input );
Inputs
 input       (.)  Input data structure
Outputs
 output      (.)  Output data structure
All rights reserved. < Define Model Names:
Define Model Names:
Function Documentation
WT_HAWTSetup()
function WT_HAWTSetup ()
References and(), eig(), HAWTRHS(), Jacobian(), Kaimal(), QCR(), TorqueHAWT(), Wind(), WindModel(), WT_Blades(), WT_Controller(), WT_Converter(), WT_Estimator(), WT_Generator(), WT_Grid(), WT_HAWTSetup(), WT_Structure(), WT_Tach(), WT_Transmission(), WT_WindModel(), WT_WindSensor(), and WTSim().
Referenced by WT_HAWTSetup().