PSS MATLAB Toolboxes: Core/WindTurbine/Sim/SetupFiles/WT_HAWTDFIGSetup.m File Reference
WT_HAWTDFIGSetup.m File Reference
Setup file for use in WTSim.m.
Functions
blank line function WT_HAWTDFIGSetup ()
Detailed Description
Uses WT_DFIG for the Generator model.
Form
d = WT_HAWTDFIGSetup
Inputs
input None
Outputs
output (.) Setup data structure. Contains a data structure for every model in the simulation. Copyright (c) 2008 Princeton Satellite Systems, Inc. All rights reserved. < Define Model Names:
Define Model Names:
Function Documentation
WT_HAWTDFIGSetup()
blank line function WT_HAWTDFIGSetup ()
References and(), DFIGEquilibrium(), eig(), HAWTRHS(), Jacobian(), Kaimal(), QCR(), TorqueHAWT(), Wind(), WindDeterministic(), WindModel(), WindStochastic(), WT_Blades(), WT_Controller(), WT_Converter(), WT_DFIG(), WT_Estimator(), WT_Grid(), WT_HAWTDFIGSetup(), WT_Structure(), WT_Tach(), WT_Transmission(), WT_WindModel(), WT_WindSensor(), and WTSim().
Referenced by WT_HAWTDFIGSetup().