PSS MATLAB Toolboxes: Core/WindTurbine/Sim/SetupFiles/WT_VAWTSetup.m File Reference
WT_VAWTSetup.m File Reference
Setup file for vertical axis wind turbine sim.
Functions
blank line function WT_VAWTSetup ()
Detailed Description
For use in WTSim.m.
Forms:
% Obtain input/output data structure information ioData = WT_WindModel;
% Supply input data, update, and return output output = WT_WindModel(input);
Inputs
input (.) Input data structure
Outputs
output (.) Output data structure Copyright (c) 2008 Princeton Satellite Systems, Inc. All rights reserved. < Define Model Names:
Define Model Names:
Function Documentation
WT_VAWTSetup()
blank line function WT_VAWTSetup ()
References and(), TorqueHAWT(), Wind(), WindModel(), WT_Converter(), WT_Grid(), WT_Structure(), WT_Transmission(), WT_VAWTBlades(), WT_VAWTController(), WT_VAWTEstimator(), WT_VAWTTach(), WT_WindModel(), WT_WindSensor(), and WTSim().