PSS MATLAB Toolboxes: WindTurbine/Sim/Models/Transmission/WT_Transmission.m File Reference
WT_Transmission.m File Reference
Functions
function WT_Transmission (in input, in time)
Function Documentation
WT_Transmission()
function WT_Transmission (in input, in time)
References Wind(), WT_Transmission(), and WTSim().
Referenced by WT_HAWTDFIGSetup(), WT_HAWTSetup(), WT_Transmission(), and WT_VAWTSetup().