PSS MATLAB Toolboxes: AC/ACClasses/@acstate/acstate.m File Reference
acstate.m File Reference
Create a zero vector the size of a.
Functions
function abs (in a)
Computes the absolute value of acstate.
function acstate (in r, in q, in w, in v, in wR, in mass, in inertia, in cG, in engine, in)
Create an object of class acstate.
function get (in x, in s)
Get an element of the class acstate.
function length (in a)
Length of a state vector.
function plus (in a, in b)
Add two objects of class acstate.
function subsasgn (in a, in s, in b)
Assign a(i)
function subsref (in a, in s)
Finds a(i)
function zeros (in a)
Create a zero vector the size of a.
Function Documentation
abs()
function abs (in a)
Form
 b = abs( a )
Inputs
 a           (:)   Object of class acstate
Outputs
 b           (:)  Object of class acstate
References acstate(), and length().
Referenced by A2Perige(), AC(), AccelVector2ManeuverStruct(), ACEngEq(), ACModes(), ADCull(), AircraftPointMassControl(), AircraftThrustFromFlight(), AirData(), AirshipAeroAnalysis(), AirshipAutopilot(), AirshipTrim(), Alias(), AlphaFromQNV(), AlphBeta(), Altitude(), AnimateCube(), ApogeeRaisingDeltaV(), ApolloLunarDescentGuidance(), ApproachCost2D(), AtmJ70(), AtmNRLMSISE(), AttitudeControlSimRWA(), AutoFormGeometry(), AutoRadarUKF(), AxisEqual(), AZLaunch(), BEMHAWT(), BHarm(), BilinearTangentLaw(), BisectionZero(), BraytonWithRecuperator(), CameraCalibrationModel(), CameraImage(), ChangePerigee(), CircleOfConfusion(), CLComposite(), ClimbAngle(), ComputeRE(), ComputeTLE(), ConjGrad(), CookeTriplet(), CoordinateFrameFromUV(), CostLowThrust2D(), CostSail2D(), CostSail3D(), CrossTrackDeltaV(), CW2Roll(), CwValid(), CycleDesign(), DCMotor(), DeltaElem2Hills(), DeltaQTarget(), DeltaWing(), Dipole(), DisplayStars(), dists(), DMSModel(), DrawAirship(), DrawLens(), DST(), DSTCrit(), DVFromMassAndIsp(), DVGeoTrx(), DVGlideslope(), DVHoh(), DWheel(), EarthGuidance(), ECIToNED(), Eclipse(), EffPw(), EFToLatLonAlt(), EigEval(), EqPartials(), ErrorCombination(), ESA(), ESAChord(), ESACS(), ESAssign(), EstimateCost(), EVAssgnC(), FFEccHills2Goals(), FFEccYExt(), FFEccZExt(), FImage(), FindDriftTerm(), FitHist(), FitPSFToData(), FitStarHist(), FitStarMoffat(), Flyby(), FPlanetControl(), FPSensors(), Fractal(), FResp(), FRespG(), FRespPlot(), FrictionBristle(), FRotatingLagrange(), FRSMPlan(), FSolarPanelThermal(), ga(), GainPattern(), GaussianDerivative(), GaussianImageFilter(), GeoEclps(), GetAirshipLinMod(), GetStarPatch(), GimbalRates(), GJInv(), GlideslopeGuidance(), GridTraverseCost(), GroundTrack(), GTrack(), HCw2R(), HeatFP(), HgCdTeWavelength(), Hills2DeltaElem(), HQuadrantBillow(), HSAData(), HSRCAD(), IGormont(), Imager(), InterferenceFit(), IntersectLineAndEllipsoid(), IsothermalHelio(), ISSCoord(), IteratePeriodicOrbit(), IterativeImpulsiveManeuver(), J2Prop(), JacchiaLineberry(), JacobianODE(), JCart2Sp(), LagrangePointsL1ToL5(), LambertTOF(), LandingControl(), LandingControlBilinear(), LandingControlGravityTurn(), LaunchTime(), LETGuess(), LETPhasing(), LiftAnlytMdl(), LoadCatalog(), LocalAngleOfAttack(), LocallyOptimalTraj(), LowEnergyTransferInCRTBP(), LowThrustControl(), LowThrustGVE_EventFcn(), LowThrustTimeToTransfer(), LPvsCF(), LTSpiral(), LunarDisplacement(), LunarHalo(), LunarTargeting(), M2EEl(), M2NuPb(), MachFromMassFlowParameter(), MachFromPressureRatio(), MagAirC(), ManeuverCost(), ManeuverStruct2AccelVector(), MassPropertiesTetrahedron(), Mat2Eul(), MeanAnom(), MeasEarthChord(), MeasEarthSensor(), MeasMagnetometerEarth(), MeasNadirStar(), MeasRateGyro(), MeasRelativePosition(), MeasStarTracker(), MeasState(), MeasSunSensorDigital(), Measurements(), MergeAngleRange(), MinDEllipsoid(), MutualInductanceCoil(), NearestOffset(), NPSPM(), Nu2E(), NumericalTransferFunction(), OnlineApproximator(), OptDIH(), Optic2D(), OptimalAssignment(), OptimalCharacteristicVelocity(), OptimalImpulseDuration(), OptimalTripTime(), OrbMnvrBielliptic(), OrbMnvrCircularize(), OrbMnvrHohmann(), OrbMnvrOneTangent(), OrbMnvrPerigee(), OrbTrack(), OrbView(), Outliers(), P3Axis(), PAL(), PanelWithCenterHole(), PanelWithCutout(), PatchedConicPlanner(), PCState(), PDAL(), Perpendicular(), PhasePlane(), PIDWithLag(), PinholeStarCamera(), PitchEst(), PlanarHelioOptimal(), Plot2DTrajectory(), PlotSailForce(), PlotZermelo(), PltOrbit(), PolarStars(), Polygon(), PPDelay(), PrintEigenvalues(), Propagate4BP(), PropagateCRTBPToXAxis(), PtchCnc(), PWMSeq(), QRotateToAlign(), QRotateToAlignWithCon(), QToPFTarget(), RaDec2Q(), RadialOscillation(), RAEToM(), Ramp(), RandPN(), RapidSwath(), RateGyro(), ReactionWheel(), ReactionWheelFriction(), RectangularBeam(), RectilinearMotion(), RefineXAxisIntercept(), RestrictDeltaV(), RHS3DPointAircraft(), RHSAiryDefocusedPSF(), RHSAutoSuspension(), RLP(), RLPMnvr(), RocketH2O2(), RPQ(), RToNu(), RV2El(), RVFromKepler(), RVOrbGen(), RVOrbHF(), RVSet2El(), RWA(), RWABristle(), RWASmart(), RWAWithPower(), S2Z(), SafeGuidance(), SafeGuidanceBurnData(), SailClosedLoopNLEqns(), ScaleState(), SegmentIntersection(), SeparationGuidance(), ShapedStrut(), Simplex(), Simplex2(), SingleAxisDrive(), SolarCell(), SolveLambdaFlyby(), SolveLinearSinCos(), SolveT(), SpaceCamera(), SphericalTankFluidHeight(), SpinChange(), SPMMnvr(), SqrFOV(), SRiccati(), SSFromNonlinear(), StageTimes(), StarMeasurement(), StarPrediction(), StoppingConditions(), StraightLineConstantAccel(), SubOrbLambert(), SubPoly(), SunNadir(), TempCyl(), TerminatorLine(), TimeOfFlightHyperbola(), TimeToVelocity(), TransferOrbit(), TreePlot(), TrueAnomalyStartHyperbola(), TrxCntrl(), TSolarP(), UnwrapPhase(), VaneAngles(), VInfRPToRV(), VPQ(), WindFunction(), Wing(), WireInit(), WorstCasePerturbations(), WPZ(), WrapPhase(), YRMax(), and ZFresp().
acstate()
function acstate (in r, in q, in w, in v, in wR, in mass, in inertia, in cG, in engine, in)
Form
 x = acstate( r, q, w, v, wR, mass, inertia, cG, engine,
 actuator, sensor, flex, disturb )
Inputs
 r       (3,1) ECI position vector
 q       (4,1) Quaternion from ECI to body
 w       (3,1) Inertial body rate in body frame
 v       (3,1) Velocity of cm wrt air
 wR      (:,1) Angular velocity of rotors
 mass    (1,1) Mass
 inertia (6,1) Inertia
 cG      (3,1) Center of mass
 engine  (:,1) Engine states
 actuator(:,1) Actuator states
 sensor  (:,1) Sensor states
 flex    (:,1) Flex model states organized [x;v] by appendage
 disturb (:,1) Disturbance model states
Outputs
 x           (1,1) State vector
References acstate(), and vector().
Referenced by abs(), AC(), ACSensor(), acstate(), AirshipInit(), AirshipSensor(), AirshipState(), AirshipTrim(), DefaultACState(), DrawAC(), GenerateAirshipAeroMats(), and get().
get()
function get (in x, in s)
Form
 y = get( x, s )
Inputs
 x           (:)   Object of class acstate
 s           (1,:) Element of class acstate
Outputs
 y           (:)   Output
References acstate().
length()
function length (in a)
Form
 n = length( a )
Inputs
 a           (:)   Object of class acstate
Outputs
 n           (1,1) Length
Referenced by A2Apogee(), A2Perige(), AB2RADec(), abs(), ABToDQ(), AC(), Accel(), AccelToSailProps(), AccelToThrustAndQ(), AccelVector2ManeuverStruct(), ACModes(), ACPlot(), ACResistance(), ACTF(), ActiveAeroSurfacesDisplay(), ACTrim(), ACWeightEstimation(), ADCull(), AddAxes(), AddCubesatComponent(), AddedMass(), AddMass(), AddMassDot(), AddRobotArm(), AddSurf(), ADGen(), AdvanceRatio(), AeroDragForce(), AerodynamicHeatFlux(), AerodynamicShock(), AeroHeatFlux(), AggregateComponents(), AirCoreMagneticTorquerDesign(), AircraftCostCalculation(), AircraftDesign(), AircraftDragDataStructures(), AircraftEquilibrium(), AircraftPointMassCLPSim(), AircraftPointMassSim(), AircraftThrustFromFlight(), AirData(), AirlinerSeats(), AirMass(), AirshipAeroAnalysis(), AirshipBallonets(), AirshipControlSim(), AirshipCV(), AirshipGeometry(), AirshipInit(), AirshipIntegrals(), AirshipMDot(), AirshipStabConDerivatives(), AirshipState(), AirshipTrimAnalysis(), AiryDefocused(), AiryDiskInPixels(), AiryResolution(), AllanVariance(), AllCaps(), AlphaBetaToU(), AlphaCentauriSystem(), AlphaFromQNV(), Altitude(), AltitudeSH(), AngleOfView(), AnglePatch(), AngleSepFromRotation(), AngRate(), AnimateCube(), AntennaPoint(), APlanet(), ApogeeDV(), ApolloTrajectory(), Append(), AppliedDeltaVDPT(), ApplyProfileToModel(), ApproachConst2D(), ApproachConst2DIneq(), ArrayPatch(), ArrayToLinspace(), ASM1(), ASM2(), ASM3(), ASM4(), AStarAttitudeTrajectory(), AStarSearch(), AtmNRLMSISE(), AttitudeControlSimRWA(), AttitudeProfilePlugIn(), AttitudeProfileVis(), AutoCADColor(), AutoCorr(), AutoFormGeometry(), AutoPoint(), AxialFluxCoil(), AZLaunch(), BalanceAirshipPayload(), BallisticCoefficient(), BarPlot(), BarycenterEarthMoon(), BatterySize(), BDipole(), BEMHAWT(), BFromHHysteresis(), BHalbach(), BHalbachAxialFluxMotor(), BHarm(), BilinearInterpolation(), BinaryToString(), BiotSavart(), BladeElement(), BldFlex(), Blobify(), BlockDiagramPlugIn(), BlurParameter(), BObjIntF(), BoundedMutation(), Box(), BraytonIdeal(), BuildAirshipMassModel(), BuildAirshipModel(), CableTensionExample(), CADColor(), CADToSimParameters(), CalibrateSunSensor(), CameraCalibration(), CameraCalibrationModel(), CameraDatabase(), CameraImage(), CameraResolution(), CameraTransform(), CCDRes(), CD0Composite(), CDAirship(), CDCLComposite(), CDCLHypersonic(), CDCLSubsonic(), CDSkinFriction(), CentroidCOM(), CentroidNoise(), Centroids(), CHarmD(), CheckDeltaVs(), CheckForDuplicateTracksMS(), CircleFit(), CircleOfConfusion(), CirclePhase(), CLComposite(), ClimbAngle(), close(), CloseIfHandle(), CloseMatFile(), ClusterGoalsDemoCommandList(), ClusterGoalsDemoSimStruct(), Clutter(), ClutterArea(), CNRComp(), CoarseCentroids(), CollisionInit(), CollisionMonitor(), CollisionMonteCarlo(), CombineOBJFiles(), CombTemp(), CompareHills(), CompE(), ComputeCoeffFromShape(), ComputeDeltaV(), ComputeDistance(), ComputeDuration(), ComputeDurationFraction(), ComStar(), ConeAreaAndDerivatives(), ConeClockConvention(), ConeClockPatches(), ConeClockToQConstrained(), ConeClockToU(), ConfidenceInterval(), ConformalCoilsInCylinder(), ConjGrad(), ConstellationGroundContact(), Constraints_Structure(), CostEstimate_Structure(), CostLowThrust2D(), CostSail2D(), CostSail3D(), CostVis(), Counter(), CovarianceRHS(), CPGas(), CPHypersonic(), CreateAircraftModel(), CreateCADTable(), CreateKVector(), CreateLensTable(), CrossSection(), CToDRand(), CTPropeller(), CubeSatDisturbanceAnalysis(), CubeSatFaces(), CubeSatPowerAnalysis(), CW2Roll(), CWSimAndPlot(), CycleDesign(), DataRateOrbit(), Date2JD(), DateStringToJD(), DeBlankLT(), DebugLog(), DeFocus(), DeleteFromList(), DeleteIfHandle(), DeltaML(), DeltaVAnalysis(), DerivationTemplate(), DesignUpperStage(), DetectorModel(), DFFThrusters(), DHArcDXi(), DiffCorr(), Difference(), DifferenceMagnitude(), DigitalFilter(), Diode(), DiscreteTrajectoryToDeltaV(), DisplaySailProperties(), DisplayStars(), DistAero(), DistributedAlbedo(), Disturbances(), DMSModel(), DoDeltaV(), DragCoeff(), DragForce(), DragLoss(), Draw2DViewPlugIn(), DrawAC(), DrawAircraft(), DrawAirship(), DrawAlphaBeta(), DrawBlobs(), DrawCAD(), DrawCubeSatSolarAreas(), DrawFieldLines(), DrawFOV(), DrawHAWT(), DrawLens(), DrawMirror(), DrawPatch(), DrawSailAngles(), DrawSailMeshVectors(), DrawSCPlugIn(), DrawSpacecraftInOrbit(), DrawSpacecraftPatches(), DrawSphere(), DrawStarImageCentroids(), DrawThermalPlugIn(), DrawVAWT(), DriftRateSigma(), DSpnStab(), DST(), DSunCone(), DTAToDTS(), DTSToDTA(), DVConstantThrust(), DVForTime(), DVGeoTrx(), DVGlideslope(), DVLowThrust(), DVReentry(), DWheel(), E2M(), E2Nu(), EarthAlb(), EarthBc(), EarthEclipseDuration(), EarthEnvironment(), EarthEscape(), EarthMoon(), EarthMoonSystemConstants(), EarthOrbToHelioOrb(), Eclipse(), EclipseFill(), EffFocalLength(), EigEval(), ElectricPropulsionDesign(), EllipsePhase(), EmittanceParallelPlates(), EnergyHeight(), EnergyPerRing(), EngineMap(), EngineTable(), EntryLiftAndDrag(), EP2M(), Equal(), ESAssign(), ESAssignDraper(), EstimateCost(), EVAssgnC(), EVDesMat(), ExportCAD(), ExportDSim(), ExportDXF(), ExportOBJ(), ExportToPSSMatrix(), Extrude(), ExtrudeFromProfile(), FAeroSurfaceAccommodation(), FAIR(), FBudget(), FDC(), FElectricPropulsion(), FFEccDeltaElem2Hills(), FFEccDMatPeriodic(), FFEccEstimateCost(), FFEccFrameCompare(), FFEccH(), FFEccProp(), FFEccRMat(), FFEccShapes(), FFEccYExt(), FFEccZExt(), FFIntegrate(), FFSim(), FFTEngy(), FGravityGradientStiffness(), FGs(), FIC(), FICP(), Figui(), FileFullpath(), FindComponents(), Finder(), FindIfInBetween(), FindSolsticeOrEquinox(), FindValidAngleRange(), FinGeometry(), FitHist(), FitPair(), FitStarHist(), FitStarMoffat(), FixLineEndings(), fixpopupuicontrol(), flength(), FlightEquilibrium(), FlightPathAngle(), FMovingBody(), FocalLengthFromAngleOfView(), FOPID(), FOrbCart(), FOrbCartH(), FOrbitMultiSpacecraft(), FOrbKF(), FormDragCoeff(), FormFactorSurfaceOfRevolution(), FormFactorWing(), FourierSeries(), FP2RADec(), FracDI(), Frenet2Hills(), FResp(), FRespG(), FRespPlot(), FrictionBristle(), FrictionSmooth(), FSailCombined(), FSailEarthMoon(), FSailEarthSun(), FSailTB(), FTB(), FTrim(), FuelMassFromAccel(), FuelTimeOptimalAccel(), FuelUpdt(), FunNames(), Fuselage(), FXModel(), GainPattern(), GAMin(), Gamma(), GenerateAirshipAeroMats(), GenerateAirshipLinMods(), GenerateGrid(), GenerateSwath(), GeneticAlgorithm(), GeoMagLatLon(), GeomagneticRigidity(), GeoOptimalMission(), GeoSwitchingMission(), GetCADVF(), GetFileRoot(), GetFileSuffix(), GetFlex(), GetFuelBudgetDataFromCAD(), GetModes(), GetModificationDate(), GetStage(), Glide(), GlideslopePlanner(), Glitch(), GND(), GOESLeg(), GondolaGeometry(), GoodYearBlimp(), GPSOrbit(), GravityGradientFrequency(), GravityHelio(), GroundEffect(), GroundStationVisibility(), GroundTrack(), GroundTrackErrorBudget(), GSModel(), GSS(), GStarUKFNL(), GTrack(), GUIColors(), GuidedLaunch2DSim(), GuidedLaunch3DRHS(), HalbachField(), HallThrusterModel(), HALOFamily(), HArci(), HCw2R(), HeatExchangerWithLosses(), HeatTransferChannel(), HeatTransferCoeffTaylor(), HeliopauseSailAngle(), Hexahedron(), HgCdTeWavelength(), Hills2Frenet(), HillsEqns(), HillsEqnsSLO(), HingeMoment(), HMagEl(), HMS2Rad(), HorizonAngle(), HorizonUnitVectors(), HQuadrantBillow(), HRakoczy(), HRangeMeasurement(), HRG(), HSAData(), HSMA(), HSRCAD(), HydrazineThruster(), HysteresisOutput(), IdealJetEngineEfficiency(), IdealRkt(), IDotS4(), IDrift(), IFOV(), IGormont(), ImageNoise(), ImageOverlay(), ImagerPSF(), InducedDragCoeff(), InertiaCubeSat(), InertiaFromOBJFile(), Inertias(), InertiaTubeSat(), Inflation(), InitializeAxes(), InitializeFormation(), InletAndNozzle(), InletLoss(), IntData(), IntegrateMassProps(), IntegratePSFs(), InterpolateCircle(), InvP(), IsCircGeom(), IsEccGeom(), Isothermal(), IsothermalLunar(), IterativeImpulsiveManeuver(), J2Prop(), JacchiaLineberry(), JDStartTransfer(), JDToFirstOfMonth(), JetEngineEfficiency(), KFPredict(), KFUpdate(), Knudsen(), KSmooth(), LabelLine(), LADAREquation(), LADARTransmitPower(), LambertDoubleRendezvous(), LandingControlBilinear(), LandingCost2D(), LandingCost2DONS(), LandingLegsCAD(), LaserBeamRadius(), LatLonPlot(), LatLonToR(), LDDeltaWing(), LensMakerFormula(), LEPDS(), LETGuess(), LFBal(), LibrationCoeff(), LiftAndDrag(), LiftAndDragJonesSearsHaack(), LiftAndDragSeaLevelToOrbit(), LiftCoeff(), LiftCoeffStall(), Limit(), LinkAnalysisTool(), LinkBudget(), LiquidMetalProps(), Lissajous(), LoadAirfoilFile(), LoadCAD(), LoadCatalog(), LoadFlex(), LoadGravityModel(), LoadLunarTopography(), LoadOBJFile(), LoadOBJModel(), LoadSAADData(), LocalStarMap(), LossAtmosphericGas(), LossPrecipitation(), LowSpeedAeroData(), LowThrustDVToTransfer(), LowThrustTimeToTransfer(), LPCircularTimeWeight(), LPEccentric(), LPEccentricGVE(), LPEccentricTimeWeight(), LPvsCF(), LQC(), LRRectangleAntenna(), LTPlaneChange(), LTSpiral(), LumenToWatt(), LunarDisplacement(), LunarHalo(), LunarModuleFirstStage(), LunarModuleSecondStage(), LunarProfile(), LunarTargeting(), LunarTrajectoryControl(), LunarVisibility(), LVCombineSRB(), LVModelFeasibilityReport(), LVStageTimes(), Lyapunov(), M2E(), M2EApp(), M2EEl(), M2EP(), M2MS(), M2Nu(), M2NuPb(), M2NuS(), MachAcrossShock(), MachFromMassFlowParameter(), MachNumber(), MagAirC(), MagControlTwoAxis(), MagDPT(), MagField(), MagFieldPlanet(), MagneticDipole(), MagneticHysteresis(), MagneticTorquer(), MagneticTorquerDesign(), MagneticTorquerDipoleMoment(), MagPlot(), ManeuverEnvelope(), ManeuverStruct2AccelVector(), ManeuverSuccessorNodes(), ManeuverSuccessorNodes3D(), Map(), Markov(), MassBudgetInput(), MassPressureVessel(), MassProp(), MassPropertiesSolidObjFile(), MaximumDV(), MaxShockIncidenceAngle(), MaxTimeStep(), MeasGPS(), MeasRangeGroundStation(), MeasRateIntegratingGyro(), MeasState(), Measurements(), MeasurementsSunMagUKF(), MedianImageFilter(), MergeNOAAWindData(), MeshSOR(), MessageAnalysis(), MHTDistanceUKF(), MHTHypothesisDisplay(), MHTLLR(), MHTMatrixSortRows(), MHTTrackMerging(), MHTTrackMgmt(), MHTTrackScoreKinematic(), MHTTrackTable(), MHTTrkToB(), MinimumExhaustVelocity(), MixedFlowTurbofan(), MixedFlowTurbofanProfile(), MolWt(), MS2M(), MSR(), MSThrustModel(), MSTOR(), MSVRatio(), MultiBEPPlot(), NACABladeMOI(), NavTargetTrackingLunar(), NavTargetTrackingPlanetary(), ND2SS(), NeptuneAirshipSizing(), NewtonianAerodynamicsFromCAD(), NewtonianAeroPropertiesFromOBJFile(), NewtonianCPFromCAD(), NewtonianForceECI(), NewtonianForceFromCAD(), NFromJ(), NFromMT(), NonDimensionalOrbit(), NonKeplerianPlanet(), NonKeplerianSun(), NormalDistribution(), NoseCone(), NPhase(), NPlot(), NRLArray(), Nu2E(), NumericalTransferFunction(), NusseltDeveloping(), ObliqueShockAngle(), Occurences(), OddEven(), ODETimeDisplay(), Optic2D(), OpticalAngleError(), OpticalMagnification(), OpticalNavPlanetStar(), OpticalSurfaceProperties(), OptimalAngleOfAttackHypersonic(), OptimalAssignment(), OptimalCharacteristicVelocity(), OptimalExhaustVelocity(), OptimalLunarLanding(), OptimalPayloadRatio(), OptimalTrajectory(), OrbitalPlane(), OrbitDeltaV(), OrbitDrag(), OrbitInsertion(), OrbitLoweringManeuvers(), OrbitODGenObs(), OrbitProp(), OrbitRoundTripTransferTimes(), OrbTrack(), OrbView(), Orientation_Structure(), OverArea(), PackageOrbitDataForPlayback(), Panels(), PanelThermalModel(), PanelWithCenterHole(), ParabolicReflector(), Parallel(), ParasiticDragCoefficient(), ParksTransformation(), PayloadMassForBurnoutVelocity(), PCGoals(), PDrag(), PIDMIMO(), PinholeCamera(), PinholeCameraStruct(), PinholeStarCamera(), PivotMch(), Pix2U(), PixelFlux2D(), PixelsHist(), PixelSpread(), PlanetaryRadiationAndAlbedo(), PlanetEnvironment(), PlanetOpposition(), PlanetPosJPL(), PlanetSim2D(), PlanetWithTerrain(), PlanetWithTerrainPatch(), PlanetYear(), PlateTwoSided(), PlaybackOrbitSim(), Plot2DTrajectory(), PlotDoubleYAxis(), PlotEMTraj(), PlotLET(), PlotLET3BP(), PlotLunarOrbit(), PlotModeShape(), PlotPayloadFraction(), PlotSEMTraj(), PlottingParabolas(), PlotTracks(), PlotVector(), PlotWindField(), PlotZermelo(), Plume(), PointCameraModel(), PolygonProps(), PopulateCostMatrix(), PorkChopPlot(), PositionDeltaV(), PositionLabel(), PowerDesign(), PowerReceived(), PrandtlGlauertCorrection(), PrandtlNikuradse(), PrandtlNumber(), PredictCollision(), Pressure(), PressureDropChannel(), PressureRatioFromMach(), PrintEigenvalues(), PrintTitle(), PrivilegedAssignment(), ProcessCatalog(), PropagateCRTBPToPeriapse(), PropagateLowThrust(), PropellerEfficiency(), PropellerThrust(), PropEph(), PWMSeq(), QESilicon(), QSpin(), QToPFTarget(), RadarAccuracy(), RadarCrosssection(), RadarEquation(), RadarPulseTrain(), RadBFp(), RadDa(), RADec2FP(), Ramjet(), RamjetKerrebrock(), Ramp(), RamRecovery(), RandPM(), RandSC(), RankineCycle(), RateGyro(), RateOfClimb(), RayleighPitotTube(), RayTraceLens(), RayTraceMirror(), RayTransferMatrix(), RayTransferMatrixFromLensFile(), RAzToLatLon(), RDE(), REA(), ReactionWheel(), ReactionWheelFriction(), ReactionWheelStress(), ReadBSPFile(), ReadLensData(), RearrangeCatalog(), RectifierFullWave(), RectifierNPhase(), RectilinearMotion(), ReduceCatalog(), ReduceOrder(), ReduceOrderPlugIn(), ReentryPlot(), RelativeStateFromPoints(), RelativeVelocityError(), ReliabilityMOfN(), ReliabilityParallel(), ReliabilitySeries(), RepeatGroundTrack(), Residual(), ResistivityCopper(), RestrictIDSet(), ReynoldsNumberKinematic(), RHAzToECEF(), RHSAiryDefocusedPSF(), RHSAiryPSF(), RHSAutomobile(), RHSClockDrift(), RHSGGRotational(), RHSGyro(), RHSHelioWithPlanets(), RHSHysteresisDamper(), RHSIsothermalCubeSat(), RHSIsothermalUKF(), RHSLiftingReentry3D(), RHSLiftingSatellite(), RHSLunarMission(), RHSLunarOrbit(), RHSMEMSGyro(), RHSReactionWheel(), RHSReentry(), RHSRigidBodyWithDamping(), RHSRobot(), RHSRobotInitialize(), RHSSGCMG(), RHSVAWTPitchControl(), Ring(), RLPMnvr(), RMoonECI(), RocketChemical(), RocketDrag(), RocketEquation(), RollYawEstimator(), RootLocus(), ROrb(), RotateECI2Hills(), RotateOBJFile(), RotorAssemblyAerodynamics(), RouthArray(), RPQ(), RSHMoon(), RSunECI(), RV2AE(), RV2ElDPT(), RVOrbGenDV(), RVOrbHF(), RVSet2El(), RWA(), RWABristle(), RWACountToRate(), RWASmart(), SafeGuidanceSimPlots(), SailEnvironment(), SailEphemAlmanac(), SailPatchVertices(), SatelliteVisibility(), SaveMovie(), SaveStructure(), SCARAIK(), ScDB(), SCHarm(), SDG(), SearchKVector(), SectorPatch(), SEMGravAcc(), SetPayloadMass(), ShapedStrut(), ShapeFlt(), SHarmD(), SHELSFlange(), ShowTeams(), SigmaPointsChol(), SignTest(), SimpAtm(), SimpleFuselage(), SimpleLiftAndDrag(), Simplex(), Simplex(), Simulate2DApproach(), SimulatePlanarHelioTrajectory(), SingleCrossover(), SizeTurbineAndCompressor(), SKDataF(), SLR(), SMADiffDPT(), SNR(), SolarCell(), SolarCellCoverage(), SolarCellPower(), SolarF(), SolarFlux(), SolarFluxFromPlateECI(), SolarFluxHistorical(), SolarFluxPrediction(), SolarPressureForce(), SolarSysJPL(), SolarSysState(), SolarWingSupport(), SolidR(), SolveSigma(), SonicBoomHypersonic(), SortFK5(), SpaceCamera(), SpacecraftParameters(), SpacecraftThermal(), SphericalTankFluidHeight(), SpinChange(), SpinDataF(), spline_maths(), SPMDataF(), SPMDataT(), SPMMnvr(), square(), SRiccati(), SSFromNonlinear(), SSOutput(), StageTimes(), StarCameraBasicModel(), StarCameraModel(), StarCentroid(), StarCentroidCOM(), StarDataFromStarMatrix(), StarDataGeneration(), StarDensity(), StarIDPyramid(), StarMeasurement(), StarPrediction(), StarTexture(), StateDisplay(), StateSpacePlot(), StaticEarthSensor(), StaticStall(), StdAtm(), SteamTablesSuperheatedEnthalpy(), StellarAttDetUKF(), StellarNavigation(), Step(), StoppingConditions(), StrehlRatio(), StripedQuadrant(), StrMtch(), StructToCell2D(), StructuralMass(), SubOrbTrajAnalysis(), SunBeta(), SunCone(), SunEarthMagAttDet(), SunEarthMoonSystemConstants(), SunMagAttDet(), SunNadir(), SunRA(), SunSensor(), SurfaceOfRevolution(), Sweep(), SweepAngle(), TakeoffTransition(), TargetInFocalPlane(), TargetSlew(), TAttenuator(), TCoeff(), TeamLevels(), TeamManagementCommandList(), TeamManagementSimStruct(), TelescopeAperture(), TempCyl(), TesselatePolygon(), TestLPCircular(), TestLPEccentric(), TestLPEccentricGVE(), Tetrahedron(), ThermalColorMap(), ThermalEquilibrium(), Thermnet(), Throttle(), ThrstLevel(), ThrustAngleExplicit(), ThrustAngleVGain(), ThrusterAndRWACommand(), ThrusterCAD(), ThrusterCommand(), ThrusterLayout(), ThrusterPatch(), ThrustModel(), TileOBJSphere(), TLETime(), TMatrix(), TNoiseCascade(), TOMHTTree(), tournSelect(), TrajectoryOptimization(), Trans3DMF(), TransferOrbit(), TransformECI2Hills(), TransformSEMRToHelio(), Tree(), TreeAdd(), TreeBldCAD(), TreeDraw(), TreeH(), TreeInit(), TreePlot(), TreePrnt(), Triangle(), TriangleWave(), TriangularTruss(), TriMesh3DMF(), Truss(), TrxCntrl(), TSCurve(), TSky(), TSolarP(), TSTODragData(), TSTOFlightProfile(), Tube(), TubeSatFaces(), TubeSatModel(), TubeSection(), Tubing(), Turbofan(), Turbofanramjet(), Turbojet(), TurbojetNoThrust(), TurboRamjet(), TurboRamRocket(), U2FP(), U2Pix(), U2Q(), UChannel(), UDKalmanFilter(), UE(), UEO2H2(), UEQR(), UGravity(), UKFPredict(), UKFRTSS(), UKFWeight(), Unit(), UnnormalizeGravity(), UpdateSailOpticalProps(), UranusAirshipSizing(), VAtm(), VAWTAspectRatio(), VCFlatFile(), VelocityLabel(), VerifyCollStruct(), VFToMassStructure(), ViewFormation(), ViewGeometry(), ViewRelativeMotion(), VInf(), VM2Photons(), VMToPhotons(), Volumes(), VolumeToDimension(), VolumeToPressureBD(), VPQ(), Watermark(), Weather(), WeathLeg(), WheelSpeed(), WindClass(), WindFunction(), WindLatLon(), WindLatLonAlt(), WindspeedHours(), Wing(), WingAreaToTaper(), WingFromParameters(), WireC(), WireDMch(), WireFRB(), WireInit(), WorldToCamera(), WorstCasePerturbations(), WPZ(), WriteEngineData(), WT_Controller(), WT_Estimator(), WT_MultiBody(), WT_VAWTController(), WT_VAWTEstimator(), XenonTank(), ZermeloCost(), ZeroPayloadDistance(), ZeroPayloadTime(), ZFresp(), and ZodiacalLight().
plus()
function plus (in a, in b)
Form
 c = plus( a, b  )
Inputs
 a           (:) Object of class acstate
 b           (:) Object of class acstate
Outputs
 c           (:)  Object of class acstate
subsasgn()
function subsasgn (in a, in s, in b)
Form
 a = subsasgn( a, s, b )
Inputs
 a           (:)   Object of class acstate
 s           (:)   Structure
Outputs
 b           (1,1)  Scalar
subsref()
function subsref (in a, in s)
Form
 b = subsref( a, s )
Inputs
 a           (:)   Object of class acstate
 s           (:)   Structure
Outputs
 b           (1,1)  Scalar
zeros()
function zeros (in a)
Form
 b = zeros( a )
Inputs
 a           (:)   Object of class acstate
Outputs
 b           (:)  Object of class acstate
Referenced by AC(), ACBuild(), AccelToSailProps(), AccelVector2ManeuverStruct(), ACEngine(), ACModes(), ACPlot(), ActiveAeroSurfacesDisplay(), ADCull(), AddAxes(), AddedMass(), AddFillToPlots(), AddMass(), AddMassDot(), AddOuterLoop(), AddView(), ADGen(), AeroD(), AeroDragForce(), AerodynamicShock(), AerodynamicShockMinimize(), AeroForceAndTorqueCombined(), AGravity(), AI2Rate(), AircraftEquilibrium(), AircraftPointMassCLPSim(), AircraftPointMassDLM(), AircraftPointMassRHS(), AircraftPointMassSim(), AirMass(), Airship_KLat(), Airship_KLon(), AirshipAeroAnalysis(), AirshipBallonets(), AirshipControlSim(), AirshipDynamics(), AirshipInit(), AirshipLinMod(), AirshipPropeller(), AirshipSensor(), AirshipSim(), AirshipStabConDerivatives(), AirshipState(), AirshipTrim(), AirshipTrimAnalysis(), AiryDefocused(), AlbedoFromTextureMap(), AllanVariance(), AlphaBetaToU(), AlphaCentauriSystem(), AlphaFromQNV(), Altitude(), AltitudeSH(), AnglePatch(), AngRate(), AnimateRE(), AntennaPoint(), APlanet(), APMLinMod(), ApogeeDV(), ApolloLunarDescentGuidance(), ApolloTrajectory(), Append(), AreaOfRectCircInt(), AssemblePlant(), AStarAttitudeTrajectory(), AStarSearch(), AtmNRLMSISE(), AtmScaleHeightsStdAtm(), AttitudeControlSimRWA(), AttitudeProfileToTorque(), AttitudeProfileVis(), AutoCorr(), AutoFormGeometry(), AutoRadar(), BallisticCoefficient(), BatterySize(), BDipole(), BDipolePlanet(), BEMHAWT(), BEMVAWT(), BFromHHysteresis(), BilinearInterpolation(), BinaryImage(), BiotSavart(), BldFlex(), BlockDiagonal(), BlockDiagramPlugIn(), BMF(), BoundingBox(), BraytonIdeal(), BuildAirshipModel(), C2DelZOH(), C2DFOH(), C2DPulse(), C2DZOH(), C2DZOHWD(), CalibrateSunSensor(), CalibrationCube(), CameraCalibration(), CameraCalibrationModel(), CCVModel(), CCVSobel(), CDCLComposite(), CentrifugalCompressor(), CentroidCOM(), CHarmD(), CheckDeltaVs(), CheckForDuplicateTracksMS(), ClimbAngle(), ClockConversion(), close(), ClusterGoalsDemoSimStruct(), Clutter(), ClutterArea(), CNRComp(), CollisionMonitor(), CollisionMonteCarlo(), CollProbSet(), ColorSpread(), CompareHills(), ComputeCoeffFromShape(), ComputeDuration(), ComputeTLE(), ConeClockPatches(), ConeClockToQConstrained(), ConeClockToU(), ConjGrad(), ConstellationGroundContact(), ConstellationMaxDistance(), CoordinateFrameFromUV(), CostEstimate_Structure(), CostLowThrust2D(), Counter(), CPHypersonic(), CreateAircraftModel(), CreateKVector(), CrossSection(), CRTBPLinearSystem(), CT2REq(), CToDRand(), CubeSatAero(), CubeSatDisturbanceAnalysis(), CubeSatPropulsion(), CW2Roll(), CWSimAndPlot(), DataRateOrbit(), Date2JD(), DefaultCommandList(), DelLZ(), DeltaAlfriend2El(), DeltaEl2Alfriend(), DeltaElem2Hills(), DeltaVCommand_Structure(), DeltaWing(), DFFSim(), DFFThrusters(), DigitalFilter(), Dipole(), DiscreteGVE(), DiscreteTrajectoryToDeltaV(), DistAero(), DistAlbedo(), DistRadiation(), DistSolar(), Disturbances(), Draw2DViewPlugIn(), DrawAircraft(), DrawAlphaBeta(), DrawCircularPlane(), DrawFieldLines(), DrawHAWT(), DrawMirror(), DrawRobot(), DrawSailAngles(), DrawSailMeshVectors(), DrawSpacecraftInOrbit(), DrawSpacecraftPatches(), DrawSphere(), DrawTerrain(), DrawThermalPlugIn(), DrawVAWT(), DriftRateSigma(), DSpnStab(), DST(), DSTM(), DUnit(), DVGeoTrx(), DVGlideslope(), DVReentry(), DWheel(), E2M(), E2Nu(), EarthAlb(), EarthBc(), EarthEclipseDuration(), EarthEnvironment(), EarthEscape(), EarthGuidance(), EarthMoon(), EarthMoonRotFrame(), EarthOrbToHelioOrb(), ECI2MeanElements(), ECIToRLP(), Eclipse(), EFToLatLonAlt(), El2RV(), EllipsePatch(), EmittanceParallelPlates(), EnergyHeight(), EngineTable(), Eq2RV(), EqPartials(), ESAChord(), ESACS(), ESAssign(), ESAssignDraper(), EstimateCost(), EVDesMat(), Factorl(), FAeroSurfaceAccommodation(), FAIR(), FAKM(), FBudget(), FElectricPropulsion(), FFEccDeltaElem2Hills(), FFEccDiscreteHills(), FFEccDMatPeriodic(), FFEccEstimateCost(), FFEccFrameCompare(), FFEccGenerateTeamGoals(), FFEccHexahedronGeometry(), FFEccLinOrb(), FFEccProp(), FFEccRMat(), FFEccShapes(), FFEccTetrahedronGeometry(), FFEccYExt(), FFEccZExt(), FFIntegrate(), FFMaintenanceTests(), FFSim(), FHingeOrbit(), FindDriftTerm(), FindMinSet(), FindPeaks(), FitPSFToData(), FitStarHist(), FitStarMoffat(), FixLineEndings(), FlightEquilibrium(), FlightPathAngle(), FMovingBody(), FOrbitMultiSpacecraft(), FOrbKF(), ForceAndTorqueEnvelope(), FourierSeries(), FracDI(), Fractal(), Frenet2Hills(), FResp(), FRespG(), FrictionBristle(), FrictionSmooth(), FRSMPlan(), Frustrum(), FS4Deployment(), FSailCombined(), FSolarSailAngles(), FTB(), FTBRef(), FTimeVaryingI(), FuelMassFromAccel(), FuelTimeOptimalAccel(), Fuselage(), FXModel(), ga(), GAMin(), GaussianCPDF(), GaussianDerivative(), GaussianImageFilter(), GenerateAirshipAeroMats(), GenerateSwath(), GenerateTeamGoals(), GeoMagLatLon(), GeomagneticRigidity(), GeoOptimalMission(), GeoSwitchingMission(), GetFlex(), GetHSA(), GlideslopeCircumnav(), GlideslopeGuidance(), Glitch(), GOESLeg(), GPSOrbit(), GPSSatellite(), GravityGradientBoom(), GravityGradientEigenvalues(), GravityGradientFrequency(), GravityGradientFromR(), GroundEffect(), GroundStationVisibility(), GroundTrackErrorBudget(), GSModel(), GSS(), GTrack(), GuidedLaunch2DSim(), GuidedLaunch3DRHS(), Gyro(), GyroKalmanFilter(), HalbachField(), HALOFamily(), HeatExchangerWithLosses(), HeliopauseSailAngle(), Hexahedron(), HgCdTeWavelength(), Hills2DeltaElem(), Hills2Frenet(), HillsEqns(), HillsEqnsSLO(), HillsFramePlot(), HMagEl(), HorizonAngle(), HQuadrantBillow(), HRangeMeasurement(), HSAData(), HSRCAD(), HydrazineThruster(), HysteresisOutput(), IdealActuator(), IDotS4(), Illumination(), ImagerPSF(), IMU(), InertiaFromOBJFile(), Inertias(), Inflation(), InitializeCostMatrix(), InitializeFormation(), InitialOrientation(), IntegrateMassProps(), IntegratePSFs(), InterpolateCircle(), InterpolateState(), IntersectLineAndCone(), IntersectLineAndEllipsoid(), IntersectPlanet(), Isothermal(), IsothermalLunar(), IsZero(), IteratePeriodicOrbit(), J20002RotPuls(), J2Prop(), JacobianODE(), JDToFirstOfMonth(), KFSunAndEarth2(), KSmooth(), L1011(), LADAREquation(), LADARTransmitPower(), LambdaToConeClock3D(), LambertDoubleRendezvous(), LambertTOF(), LandingConst2D(), LandingConst2DONS(), LandingControl(), LandingControlGravityTurn(), LargeFormationControl(), LaserBeamRadius(), LatLonPlot(), LatLonToR(), LEPDS(), LFBal(), LFState(), LibrationCoeff(), LibrationFrequency(), LibrationRHS(), LiftAndDrag(), LiftAndDragJonesSearsHaack(), LiftAndDragSeaLevelToOrbit(), LiftCoeff(), LiftCoeffStall(), LinkAnalysisTool(), LinkOrbitAnalysis(), LinOrb(), LinOrbLQG(), LinOrbNormalized(), Lissajous(), LoadAtt(), LoadFlex(), LoadGEM(), LoadingToLightness(), LoadLP150Q(), LoadLunarTopography(), LoadSGM150(), LocallyOptimalConeClock3D(), LocallyOptimalTraj(), LocusOfVisibility(), LossPrecipitation(), LowThrustDVToTransfer(), LowThrustSim(), LowThrustTimeToTransfer(), LPCircular(), LPCircularTimeWeight(), LPEccentric(), LPEccentricGVE(), LPEccentricTimeWeight(), LPvsCF(), LQC(), LQOrbitController(), LSQLaunch(), LTPlaneChange(), LunarDisplacement(), LunarProfile(), LunarTargeting(), LunarTrajectoryControl(), LunarVisibility(), LVModelFeasibilityReport(), LVStageTimes(), Lyapunov(), LyapunovFamily(), M2E(), M2EApp(), MachFromMassFlowParameter(), MagAirC(), MagControlTwoAxis(), MagFieldData(), MagFieldPlanet(), MagneticDipole(), MagneticDipoleCart(), MagneticFieldDipole(), MagneticHysteresis(), MagneticTorquer(), MagneticTorquerDesign(), ManeuverStruct2AccelVector(), Markov(), MassPropertiesSolidObjFile(), Mat2Eul(), Mat2Q(), MaximumDV(), MaxShockIncidenceAngle(), MBModel(), MC33Switching(), MeasCamera(), MeasDoris(), MeasEarthSensor(), MeasEarthTarget(), MeasGPS(), MeasMagnetometerEarth(), MeasRadar(), MeasRateGyro(), MeasRelativePosition(), MeasStarTracker(), MeasState(), MeasSunSensorDigital(), Measurements(), MedianImageFilter(), MeshSOR(), MeshToPatch(), MessageAnalysis(), MHTDistanceUKF(), MHTHypothesisDisplay(), MHTLLR(), MHTTrackMgmt(), MHTTrackScore(), MHTTrackScoreKinematic(), MHTTrkToB(), MinDEllipsoid(), MinE4BP(), MixedFlowTurbofanProfile(), ModulationSpectralEfficiency(), MSThrustModel(), MSVRatio(), MultiBEPPlot(), MutualInductanceCoil(), NavigationCameraSunStar(), NavTargetTrackingPlanetary(), ND2SS(), NewtonianAerodynamicsFromCAD(), NewtonianAeroPropertiesFromOBJFile(), NewtonianCPFromCAD(), NewtonianForceECI(), NewtonianForceFromCAD(), NewtonsMethod(), NewtonSolver(), NominalSafeGuidance(), NonDimensionalOrbit(), NonKeplerianPlanet(), NonKeplerianSun(), NonlinearEstimator(), NormalDistribution(), NormalizationMatrix(), NPhase(), NPSPM(), Nu2E(), NusseltDeveloping(), ObliqueShockAngle(), OH6A(), OmegaLVLH(), OpticalNavigationMeasurement(), OpticalNavLunarLandmarkStar(), OpticalNavPlanetStar(), OpticalNavPlanetStarNoiseMatrix(), OptimalAngleOfAttackHypersonic(), OptimalAssignment(), OptimalCharacteristicVelocity(), OptimalExhaustVelocity(), OptimalLunarLanding(), OptimalPayloadRatio(), OrbitalPlane(), OrbitClosestPoint(), OrbitDrag(), OrbitJacobian(), OrbitODGenObs(), OrbitProp(), OrbView(), Orientation_Structure(), Osc2Mean(), OverArea(), PackageOrbitDataForPlayback(), PAL(), PanelThermalModel(), PanelWithCenterHole(), ParabolicReflector(), Parallel(), ParasiticDragCoefficient(), PartialDisk(), PatchedConicPlanner(), PayloadMassForBurnoutVelocity(), PDAL(), PDrag(), PIDMIMO(), PinholeStarCamera(), PitchLoop(), PixelFlux2D(), PixelMapCentroid(), PixelsHist(), PlanarHelioOptimal(), PlanetaryRadiationAndAlbedo(), PlanetEnvironment(), PlanetOptimalTraj(), PlanetPosJPL(), PlanetSensorDualScan(), PlanetSim2D(), PlanetTrajectoryPlot(), PlanetWithTerrain(), PlanetWithTerrainPatch(), PlanetYear(), Plot2DTrajectory(), Plot3D(), PlotCone(), PlotLET(), PlotLET3BP(), PlotLunarOrbit(), PlotModeShape(), PlotPayloadFraction(), PlottingParabolas(), PlotVector(), PlotWindField(), PltOrbit(), Plume(), PMABCMachineRHS(), PMMachineABCRHS(), PointInGridInTriangle(), PointInPolygon(), PointInTriangle(), PolygonProps(), PowCompAnlytBsd(), PowerDesign(), PrandtlGlauertCorrection(), PrandtlNikuradse(), PressureDropChannel(), PrintEigenvalues(), PrivilegedAssignment(), ProcessCatalog(), ProjLine(), Propagate3BP(), Propagate4BP(), PropagateCRTBP(), PropagateCRTBPBackwards(), PropagateCRTBPToPeriapse(), PropagateLowThrust(), PropagateState(), PropagateState3D(), PropellerEfficiency(), PropellerThrust(), PropEph(), PWMSeq(), QAlign(), QAlignWithCon(), QBToIDot(), QESilicon(), QForm(), QIToBDot(), QLatLon(), QProp(), QRotateToAlignWithCon(), QSail(), QSpin(), QSunNadir(), QSunPointing(), QTForm(), QToConeClock(), RadarEquation(), RadarPulseTrain(), RadBFp(), Ramjet(), RandChiSquared(), Random(), RandP(), RankineCycle(), RayTraceLens(), RayTraceMirror(), RayTransferMatrix(), RBModel(), RDE(), RE2Hills(), RE2SLO(), REA(), ReactionWheel(), ReactionWheelFriction(), ReadHorizons(), ReadMagField(), ReadTopexPOE(), RectifierNPhase(), RectifierThreePhase(), RectilinearMotion(), RelativeStateFromPoints(), RelativeVelocityError(), ReliabilityMOfN(), Residual(), ResistivityCopper(), RestrictIDSet(), RHAzToECEF(), RHS3DPointAircraft(), RHSAiryDefocusedPSF(), RHSAiryPSF(), RHSAutomobile(), RHSBilliards(), RHSClockDrift(), RHSCRTBP(), RHSCubeSat(), RHSGaussianPSF(), RHSGeoJ2(), RHSGGRotational(), RHSHelioWithPlanets(), RHSHysteresisDamper(), RHSIsothermalCubeSat(), RHSMarsOrbit(), RHSMEMSGyro(), RHSMoffatPSF(), RHSPlanet3DToAB(), RHSPointMass(), RHSPointMassAircraft(), RHSReactionWheel(), RHSRigidBody(), RHSRigidBodyMass(), RHSRigidBodyOffsetCM(), RHSRigidBodyWithDamping(), RHSSGCMG(), RHSTSTO(), RHSVAWTPitchControl(), Ring(), RMoonECI(), RocketDrag(), RollEst(), RollPitchToQECI(), RollYawEstimator(), RootLocus(), RotateOrbit(), RouthArray(), RPQ(), RSHMoon(), RSunECI(), RTSS(), RV2El(), RVFromKepler(), RVOrbGen(), RVOrbHF(), RVSet2El(), RWA(), RWABristle(), RWAPatch(), RWASmart(), SafeGuidance(), SafeGuidanceSimPlots(), SailEnvironment(), SailEphemAlmanac(), SailMesh(), SailPatchVertices(), SatelliteSubsystemMass(), SatelliteVisibility(), SaturnsRings(), ScanToTrackAuto(), SCARAIK(), SCHarm(), SCwPivot(), SDG(), SecondOrderGuidance(), SecondOrderGuidance3D(), SectorPatch(), SeeTLE(), SelectTarget(), SEMGravAcc(), ShapedStrut(), SHarmD(), SimpAtm(), SimpleLiftAndDrag(), Simplex(), Simplex(), SimplexScaling(), Simulate2DApproach(), Simulate3DLanding(), SimulateFlyby(), SimulatePlanarHelioTrajectory(), SimulateStraightLineTrajectory(), SkewDipl(), SolarCell(), SolarCellCoverage(), SolarCellPower(), SolarF(), SolarFluxHistorical(), SolarFluxPrediction(), SolarPressureForce(), SolarSysJPL(), SolarSysState(), SolarSystemElements(), SolidR(), SolidRocketInertia(), SortTeamGoals(), SphJacobian(), SpinChange(), SPMMnvr(), square(), SRiccati(), SSFromNonlinear(), SSOutput(), SSTokamak(), StageTimes(), StarCentroid(), StarCentroidCOM(), StarDensity(), StarIDPyramid(), StarMeasurement(), StarMeasurementUKF(), StarTexture(), State_Structure(), StateDisplay(), StateSensor(), StateSpacePlot(), StaticEarthSensor(), StdAtm(), SteamTablesSuperheatedEnthalpy(), StellarAttDetUKF(), Step(), StoppingConditions(), STOVL(), StraightLineConstantAccel(), StripedQuadrant(), StructuralMass(), SubOrbLambert(), SubOrbTrajAnalysis(), SubPoly(), SunData(), SunEarthMagAttDet(), SunGuidance(), SunMagAttDet(), SunNadir(), SunSensor(), SunVectorPointing(), SurfaceOfRevolution(), Sweep(), TargetInFocalPlane(), TBModel(), TeamManagementSimStruct(), TelescopeAperture(), TerminatorPlanet(), TestLPCircular(), TestLPEccentric(), TestLPEccentricGVE(), Tetrahedron(), ThermalColorMap(), ThermalConductivityAndViscHeXe(), ThrstLevel(), ThrusterAndRWACommand(), ThrusterColdGas(), ThrusterCommand(), ThrustModel(), TOMHTAssignment(), TOMHTTree(), Torus(), TransformLagrangePoints(), Tree(), TreeAdd(), TreeH(), TreeInit(), TriangleWave(), TrnsZero(), TSCurve(), TSolarP(), Tube(), TubeArc(), TubeSatFaces(), TubeSection(), TubeWithBends(), Turbofan(), Turbofanramjet(), Turbojet(), TurboRamjet(), TurboRamjetSim(), TurboRamRocket(), TwoBodyRateModel(), TwoDEscape(), TwoDOptimalSailAngle(), U2Q(), UDKalmanFilter(), UEO2H2(), UGravity(), UKFPredict(), UKFRTSS(), UnnormalizeGravity(), URWAPyramid(), UToConeClock(), VarEqT(), VarGausP(), VarGausT(), VAtm(), VAWTBldMdlRHS(), VAWTRHS(), VDA(), VFToMassStructure(), ViewFormation(), ViewGeometry(), ViewRelativeMotion(), VIModel(), VM2Photons(), VPQ(), WalkerConstellation(), WheelSpeed(), Wind(), WindFunction(), WindLatLon(), WindLatLonAlt(), WindspeedHours(), WindStochastic(), WingFromParameters(), WireC(), WireFRB(), WireInit(), WorstCasePerturbations(), WorstFirstAssignment(), WPZ(), WT_MultiBody(), YRMax(), and ZFresp().