var dir_194da6f70622c34c2b9b6460bde1f39a =
[
    [ "BlockDiagonal.m", "_block_diagonal_8m.html", "_block_diagonal_8m" ],
    [ "ColCompR.m", "_col_comp_r_8m.html", "_col_comp_r_8m" ],
    [ "ComplexToReal.m", "_complex_to_real_8m.html", "_complex_to_real_8m" ],
    [ "Cross.m", "_cross_8m.html", "_cross_8m" ],
    [ "DelLZ.m", "_del_l_z_8m.html", "_del_l_z_8m" ],
    [ "Dot.m", "_dot_8m.html", "_dot_8m" ],
    [ "DUnit.m", "_d_unit_8m.html", "_d_unit_8m" ],
    [ "DupVect.m", "_dup_vect_8m.html", "_dup_vect_8m" ],
    [ "Factorl.m", "_factorl_8m.html", "_factorl_8m" ],
    [ "GenSub.m", "_gen_sub_8m.html", "_gen_sub_8m" ],
    [ "GJInv.m", "_g_j_inv_8m.html", "_g_j_inv_8m" ],
    [ "Inv3x3.m", "_inv3x3_8m.html", "_inv3x3_8m" ],
    [ "InvP.m", "_inv_p_8m.html", "_inv_p_8m" ],
    [ "IsSing.m", "_is_sing_8m.html", "_is_sing_8m" ],
    [ "IsZero.m", "_is_zero_8m.html", "_is_zero_8m" ],
    [ "LeastSq.m", "_least_sq_8m.html", "_least_sq_8m" ],
    [ "Mag.m", "_mag_8m.html", "_mag_8m" ],
    [ "Orthogonalize.m", "_orthogonalize_8m.html", "_orthogonalize_8m" ],
    [ "Product.m", "_product_8m.html", "_product_8m" ],
    [ "RowCompU.m", "_row_comp_u_8m.html", "_row_comp_u_8m" ],
    [ "Sep.m", "_sep_8m.html", "_sep_8m" ],
    [ "Skew.m", "_skew_8m.html", "_skew_8m" ],
    [ "SkewSq.m", "_skew_sq_8m.html", "_skew_sq_8m" ],
    [ "SkewSymm.m", "_skew_symm_8m.html", "_skew_symm_8m" ],
    [ "SumC.m", "_sum_c_8m.html", "_sum_c_8m" ],
    [ "SumV.m", "_sum_v_8m.html", "_sum_v_8m" ],
    [ "SXV.m", "_s_x_v_8m.html", "_s_x_v_8m" ],
    [ "Unit.m", "_unit_8m.html", "_unit_8m" ]
];