var dir_35528a66d9bb73b82711c608b97a75d8 =
[
    [ "ABC2SRF.m", "_a_b_c2_s_r_f_8m.html", "_a_b_c2_s_r_f_8m" ],
    [ "ABToDQ.m", "_a_b_to_d_q_8m.html", "_a_b_to_d_q_8m" ],
    [ "AngleEncoder.m", "_angle_encoder_8m.html", "_angle_encoder_8m" ],
    [ "Capacitor.m", "_capacitor_8m.html", "_capacitor_8m" ],
    [ "ClassERFAmplifier.m", "_class_e_r_f_amplifier_8m.html", "_class_e_r_f_amplifier_8m" ],
    [ "ConformalCoilsInCylinder.m", "_conformal_coils_in_cylinder_8m.html", "_conformal_coils_in_cylinder_8m" ],
    [ "Diode.m", "_diode_8m.html", "_diode_8m" ],
    [ "DToA.m", "_d_to_a_8m.html", "_d_to_a_8m" ],
    [ "ForceBetweenCoils.m", "_force_between_coils_8m.html", "_force_between_coils_8m" ],
    [ "HalbachMotorDesign.m", "_halbach_motor_design_8m.html", "_halbach_motor_design_8m" ],
    [ "Inductor.m", "_inductor_8m.html", "_inductor_8m" ],
    [ "LRLoopAntenna.m", "_l_r_loop_antenna_8m.html", "_l_r_loop_antenna_8m" ],
    [ "LRRectangleAntenna.m", "_l_r_rectangle_antenna_8m.html", "_l_r_rectangle_antenna_8m" ],
    [ "MatchingCircuit.m", "_matching_circuit_8m.html", "_matching_circuit_8m" ],
    [ "MutualInductanceCoaxialCoil.m", "_mutual_inductance_coaxial_coil_8m.html", "_mutual_inductance_coaxial_coil_8m" ],
    [ "MutualInductanceCoil.m", "_mutual_inductance_coil_8m.html", "_mutual_inductance_coil_8m" ],
    [ "NPhase.m", "_n_phase_8m.html", "_n_phase_8m" ],
    [ "ParksTransformation.m", "_parks_transformation_8m.html", "_parks_transformation_8m" ],
    [ "PerUnitNormalization.m", "_per_unit_normalization_8m.html", "_per_unit_normalization_8m" ],
    [ "RectifierFullWave.m", "_rectifier_full_wave_8m.html", "_rectifier_full_wave_8m" ],
    [ "RectifierNPhase.m", "_rectifier_n_phase_8m.html", "_rectifier_n_phase_8m" ],
    [ "RectifierThreePhase.m", "_rectifier_three_phase_8m.html", "_rectifier_three_phase_8m" ],
    [ "SRF2ABC.m", "_s_r_f2_a_b_c_8m.html", "_s_r_f2_a_b_c_8m" ],
    [ "Transformer.m", "_transformer_8m.html", "_transformer_8m" ],
    [ "TransformerRHS.m", "_transformer_r_h_s_8m.html", "_transformer_r_h_s_8m" ]
];