var dir_f0c27188b7458088ffe5ea0f97594639 =
[
    [ "BEP.m", "_b_e_p_8m.html", "_b_e_p_8m" ],
    [ "CNRComp.m", "_c_n_r_comp_8m.html", "_c_n_r_comp_8m" ],
    [ "ConstellationGroundContact.m", "_constellation_ground_contact_8m.html", "_constellation_ground_contact_8m" ],
    [ "ConstellationMaxDistance.m", "_constellation_max_distance_8m.html", "_constellation_max_distance_8m" ],
    [ "DataRate.m", "_data_rate_8m.html", "_data_rate_8m" ],
    [ "DataRateGain.m", "_data_rate_gain_8m.html", "_data_rate_gain_8m" ],
    [ "DataRateOrbit.m", "_data_rate_orbit_8m.html", "_data_rate_orbit_8m" ],
    [ "DBPower.m", "_d_b_power_8m.html", "_d_b_power_8m" ],
    [ "DBSignal.m", "_d_b_signal_8m.html", "_d_b_signal_8m" ],
    [ "DBSignalToPower.m", "_d_b_signal_to_power_8m.html", "_d_b_signal_to_power_8m" ],
    [ "DBWToNW.m", "_d_b_w_to_n_w_8m.html", "_d_b_w_to_n_w_8m" ],
    [ "DBWToPW.m", "_d_b_w_to_p_w_8m.html", "_d_b_w_to_p_w_8m" ],
    [ "DopplerBlind.m", "_doppler_blind_8m.html", "_doppler_blind_8m" ],
    [ "DopplerShift.m", "_doppler_shift_8m.html", "_doppler_shift_8m" ],
    [ "FPD.m", "_f_p_d_8m.html", "_f_p_d_8m" ],
    [ "FPFA.m", "_f_p_f_a_8m.html", "_f_p_f_a_8m" ],
    [ "Frequency.m", "_frequency_8m.html", "_frequency_8m" ],
    [ "FrequencyToWavelength.m", "_frequency_to_wavelength_8m.html", "_frequency_to_wavelength_8m" ],
    [ "ModulationSpectralEfficiency.m", "_modulation_spectral_efficiency_8m.html", "_modulation_spectral_efficiency_8m" ],
    [ "MultiBEPPlot.m", "_multi_b_e_p_plot_8m.html", "_multi_b_e_p_plot_8m" ],
    [ "PeriodToSemimajorAxis.m", "_period_to_semimajor_axis_8m.html", "_period_to_semimajor_axis_8m" ],
    [ "ProbDetection.m", "_prob_detection_8m.html", "_prob_detection_8m" ],
    [ "Shannon.m", "_shannon_8m.html", "_shannon_8m" ],
    [ "TToPower.m", "_t_to_power_8m.html", "_t_to_power_8m" ],
    [ "Wavelength.m", "_wavelength_8m.html", "_wavelength_8m" ],
    [ "WavelengthToFrequency.m", "_wavelength_to_frequency_8m.html", "_wavelength_to_frequency_8m" ],
    [ "YBComp.m", "_y_b_comp_8m.html", "_y_b_comp_8m" ]
];