var dir_ce4fba5851d76f2e2e0e019c2bddaa35 =
[
    [ "Anim2Q.m", "_anim2_q_8m.html", "_anim2_q_8m" ],
    [ "AnimQ.m", "_anim_q_8m.html", "_anim_q_8m" ],
    [ "AU2Q.m", "_a_u2_q_8m.html", "_a_u2_q_8m" ],
    [ "DeltaQToRate.m", "_delta_q_to_rate_8m.html", "_delta_q_to_rate_8m" ],
    [ "DQ2Mat.m", "_d_q2_mat_8m.html", "_d_q2_mat_8m" ],
    [ "Eul2Q.m", "_eul2_q_8m.html", "_eul2_q_8m" ],
    [ "Mat2Q.m", "_mat2_q_8m.html", "_mat2_q_8m" ],
    [ "Q2AU.m", "_q2_a_u_8m.html", "_q2_a_u_8m" ],
    [ "Q2Eul.m", "_q2_eul_8m.html", "_q2_eul_8m" ],
    [ "Q2Mat.m", "_q2_mat_8m.html", "_q2_mat_8m" ],
    [ "QAxisRot.m", "_q_axis_rot_8m.html", "_q_axis_rot_8m" ],
    [ "QBToIDot.m", "_q_b_to_i_dot_8m.html", "_q_b_to_i_dot_8m" ],
    [ "QError.m", "_q_error_8m.html", "_q_error_8m" ],
    [ "QForm.m", "_q_form_8m.html", "_q_form_8m" ],
    [ "QFromDQ.m", "_q_from_d_q_8m.html", "_q_from_d_q_8m" ],
    [ "QMult.m", "_q_mult_8m.html", "_q_mult_8m" ],
    [ "QPose.m", "_q_pose_8m.html", "_q_pose_8m" ],
    [ "QRand.m", "_q_rand_8m.html", "_q_rand_8m" ],
    [ "QTForm.m", "_q_t_form_8m.html", "_q_t_form_8m" ],
    [ "QUnit.m", "_q_unit_8m.html", "_q_unit_8m" ],
    [ "QZero.m", "_q_zero_8m.html", "_q_zero_8m" ],
    [ "Sa2Q.m", "_sa2_q_8m.html", "_sa2_q_8m" ],
    [ "U2Q.m", "_u2_q_8m.html", "_u2_q_8m" ]
];