PSS MATLAB Toolboxes: Link Functions
Link Functions
Link Module
The Link module functions.
Directories
directory Coverage
Coverage and visibility .
directory Ladar
Ladar transmission .
directory LinkDesign
Orbit analysis and link budgets .
directory LinkUtilities
Helpful utilities .
directory Optical
Optical links .
directory Radar
Radar equations and cross-section .
directory RF
Link loss and temperature functions .
Description
Functions
function AntennaGain (in d, in frequency)
Antenna gain from area and efficiencies as a function of frequency.
function AntennaPoint (in r, in p, in q, in b)
Compute the boresight matrix or attitude quaternion.
function Beamwidth3dB (in d, in frequency, in fIllumination)
Antenna 3 dB angle for a parabolic antenna.
function BEP (in type, in bitRate, in cOverN)
Computes the bit error probability given C/N and the bit rate.
function Clutter (in type, in f, in thetaG, in sS)
Compute clutter for land or sea.
function ClutterArea (in theta, in r, in u, in rP, in t)
Compute clutter area.
function CNRComp (in pFA, in pD, in n)
Compute the carrier to noise ratio.
function ConstellationGroundContact (in el, in d, in jD0, in zone, in m, in nP)
Compute the number of contacts for a constellation with ground users.
function ConstellationMaxDistance (in el, in pl, in m, in nP)
Compute maximum distances between satellites in a constellation.
function DataRate (in power, in d)
Computes communications sytems data rates.
function DataRateGain (in power, in d)
Computes communications sytems data rates from gains.
function DataRateOrbit (in r, in rGS, in power, in jD, in d)
Computes data rate over an orbit.
function DBmToPower (in dBm)
Convert from dBm to power.
function DBPower (in p)
Power conversion to decibels.
function DBSignal (in s)
Signal conversion to decibels.
function DBSignalToPower (in dBW)
Convert decibels to power (invert decibels).
function DBsmToSM (in dBsm)
Convert from dBsm to m^2.
function DBWToNW (in powerDB)
Convert dBW (decibels-Watts) to nanowatts.
function DBWToPower (in dBW)
Convert from dBW to power.
function DBWToPW (in powerDB)
Convert dBW to picowatts.
function DopplerBlind (in fT, in vR)
Finds Doppler blind speeds.
function DopplerShift (in fT, in vR)
Doppler shift.
function FPD (in cNR, in pD, in yB, in n)
Function called by fzero to compute the carrier to noise ratio.
function FPFA (in yB, in pFA, in n)
Right hand side for probability of false alarm computation.
function Frequency (in band, in new, in which)
Outputs the frequencies for specified bands of electromagnetic radiation.
function FrequencyToWavelength (in f, in c)
Converts frequency to wavelength.
function Gain3dB (in theta3DB, in fIllumination, in eff)
Antenna 3 dB gain for a parabolic antenna.
function GainPattern (in antDiam, in centerFreq, in angle)
Compute an antenna gain pattern as a function of the incidence angle.
function GenerateSwath (in d, in r, in q, in t)
Generate dynamical plots of antenna patterns.
function GroundStationVisibility (in rGroundStation, in jD, in rSC, in horizonAngle)
Determine ground station visibility for spacecraft position(s).
function ISLFOV (in r, in q, in b, in a3dB, in rT, in t)
Determines if a satellite is visible to an ISL.
function LADAREquation (in d)
Solves one form of the laser radar equation (ladar).
function LADARTransmitPower (in d)
Computes required Ladar transmit power.
function LinkAnalysisTool (in spaceLink, in groundLink, in orbit)
Performs a link analysis for a satellite over an orbit.
function LinkBudget (in dIn, in fileName)
Performs a link budget for a satellite.
function LossAtmosphericGas (in f, in E)
Computes the link attenuation due to gas.
function LossDepointing (in theta, in theta3DB, in d)
Computes the depointing loss.
function LossFreeSpace (in f, in r)
Computes the free space loss.
function LossPolarization (in psi)
Computes the polarization loss.
function LossPrecipitation (in f, in zone, in pTime, in latitudeS, in longitudeS, in hS, in rSC, in tau)
Computes the link attenuation due to precipation (rain).
function ModulationSpectralEfficiency (in modulation)
Spectral efficiency of different modulation schemes.
function MultiBEPPlot (in s, in bitRate, in cOverN, in threshold)
Computes and plots multiple bit error rates on the same plot.
function NElementsPhasedArray (in w, in h, in f, in theta)
Compute the number of elements needed to prevent grating lobes.
function NoisePower (in t, in b)
Computes the noise power required from bandwidth and noise temperature.
function OpticalBackgroundNoise (in s, in wavelength)
Computes optical background noise for various sources.
function OpticalLinkBudget (in d)
Create an optical link budget.
function OpticalReceiverNoiseDensity (in d)
Compute the receiver noise density.
function PeriodToSemimajorAxis (in p, in mu)
Computes semi-major axis from orbital period.
function PhasedArray (in f, in beamwidth, in thetaMax, in eta)
Generate a phased array.
function PowerReceived (in pT, in aR, in aT, in r, in fGHz)
Computes the power received by an antenna.
function PowerToDBm (in power)
Convert from power to dB milliwatts.
function PowerToDBW (in power)
Convert from power to dB watts.
function ProbDetection (in n, in cNR, in pFA)
Probability of detection for a diffuse target.
function RadarAccuracy (in type, in d)
Compute radar accuracy.
function RadarCrosssection (in type, in lambda, in d)
Computes radar crossections.
function RadarEquation (in solveFor, in d, in lambda)
Solves the radar equation.
function RadarEquationPulse (in solveFor, in d)
Solves the radar equation.
function RadarEquationSN (in type, in d)
Computes signal to noise ratios from the radar equation.
function RadarPulseTrain (in fGHz, in tau, in tauP, in t)
Generates a pulse train.
function RadarSN (in d)
Computes the radar signal to noise ratio for a pulsed monostatic radar.
function RadarThermalNoise (in b, in f)
Computes thermal noise for radar or any communications system.
function RadarWindows (in window)
Parameters for different radar windows.
function RFSystemNoise (in tA, in tT, in lR, in f)
Computes system noise.
function SatelliteVisibility (in r1, in r2, in horizonAngle, in planet)
Determines the visibility between the points in r2 and r1.
function Shannon (in name, in x)
The Shannon information theorem relating S/N and C/B.
function SMToDBsm (in m)
Convert m^2 to dBsm.
function SNR (in d)
Compute the signal to noise ratio.
function TAntennaGround (in tSky, in aRain, in tGround)
Compute the temperature of an antenna on the ground.
function TAttenuator (in t, in loss)
Compute the temperature of an attenuator.
function TMoon (in ignoredArg)
Noise temperature of the Moon.
function TNoiseCascade (in d)
Compute the noise of a cascade series.
function TPlanet (in f, in planet)
Noise temperature of a planet.
function TrackingAccuracy (in d)
Computes radar tracking accuracy.
function TReceiver (in tA, in lFRX, in tF, in tERX)
Compute the noise temperature of a receiver attached to an antenna.
function TSky (in f, in e)
Brightness temperature of the sky.
function TSun (in f, in thetaE, in hasPolarizer)
Noise temperature of the sun.
function TToPower (in T, in b)
Convert temperature to power via bandwidth.
function Wavelength (in band, in ignoredArg)
Outputs the wavelengths for bands of electromagnetic radiation.
function WavelengthToFrequency (in lambda, in c)
Converts wavelength to frequency.
function YBComp (in n, in pFA)
yB computation used as part of the probability of detection algorithm.
Function Documentation
AntennaGain()
function AntennaGain (in d, in frequency)
Antenna types are circular aperture or horn, omnidirectional or dipole, and helical. Omnidirectional antenna have a fixed gain of 1.5, circular and helical are functions of the geometry and frequency.
Type AntennaGain to run a demo for a circular aperture.
Form
 d = AntennaGain;  % data structure
 g = AntennaGain( d, frequency )
Inputs
 d             (.)   Antenna data structure
                       .type             (1,:) Type string
                       .area             (1,1) Area (circular or horn), m^2
                       .effIllumination  (1,1) Illumination efficiency
                       .effSpillover     (1,1) Spillover efficiency
                       .effSurfaceFinish (1,1) Surface finish efficiency
                       .effOhmic         (1,1) Ohmic losses
                       .effImpedance     (1,1) Impedancy mismatch losses
                       .eff              (1,1) Miscellaneous
                       .n                (1,1) Number of turns (helical)
                       .c                (1,1) Circumference (helical)
                       .s                (1,1) Spacing (helical)
 frequency    (1,:)  Frequency (GHz)
Outputs
 g            (:)    Gain (dB)
References: Maral, G. and M. Bousquet. (1998) Satellite Communications Systems. Wiley. pp. 14-17
References and(), AntennaGain(), DefaultDataStructure(), Frequency(), Illumination(), and isempty().
Referenced by AntennaGain(), DataRateGain(), LinkAnalysisTool(), and LinkBudget().
AntennaPoint()
function AntennaPoint (in r, in p, in q, in b)
The quaternion is from planet fixed to body. Leave the one empty that you do NOT want to compute. In other words if b is empty it will compute q. The antenna boresight is defined as the local z-axis.
Form
 g = AntennaPoint( r, p, q, b )
Inputs
 r             (3,:)    Planet fixed position vector (km)
 p             (3,1)    Point on planet
 q             (4,:)    Planet fixed to body quaternion [q_s;q_x;q_y;q_z]
 b             (4,1)    Boresight quaternion or []
Outputs
 q             (4,:)    Planet fixed to body quaternion [q_s;q_x;q_y;q_z]
  -or-
 b             (4,:)    Boresight quaternion or []
References AntennaPoint(), Demo(), length(), Plot2D(), QTForm(), quaternion(), vector(), and zeros().
Referenced by AntennaPoint().
Beamwidth3dB()
function Beamwidth3dB (in d, in frequency, in fIllumination)
Form
 theta3dB = Beamwidth3dB( d, f, fIllumination )
Inputs
 d             (1,1)   Aperture (m)
 frequency     (1,:)   Frequency (GHz)
 fIllumination (1,1)   Illumination factor (deg)
Outputs
 theta3dB      (:)     3 dB angle (deg)
References: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems. Wiley. pp. 17-18.
References and(), Frequency(), Illumination(), isempty(), and Plot2D().
Referenced by LinkAnalysisTool(), and LinkBudget().
BEP()
function BEP (in type, in bitRate, in cOverN)
Five types of modulation, 'BPSK' 'QPSK' 'DE-BPSK' 'DE-QPSK' 'D-BPSK' are available.
Type BEP for a demo of a 1 MB/s channel.
Form
 bEP = BEP( type, bitRate, cOverN )
Inputs
 type    (1,:)   Modulations: 'BPSK' 'QPSK' 'DE-BPSK' 'DE-QPSK' 'D-BPSK'
 bitRate    (1,1)   Bit rate (bps)
 cOverNo    (1,:)   (C/N)T (dB)
Outputs
 bEP     (1,:)   Bit error probability
 eOverN (1,:)   Energy per bit (dB)
References: Maral, G. and M. Bousquet, "Satellite Communications Systems Third Edition", Wiley, 1993, p. 125.
References and(), BEP(), Demo(), and Energy().
Referenced by BEP(), LinkBudget(), LinkOrbitAnalysis(), and MultiBEPPlot().
Clutter()
function Clutter (in type, in f, in thetaG, in sS)
Form
 sigma0 = Clutter( type, f, thetaG, sS )
Inputs
 type          (1,:)    Type 'sea', 'desert', 'farmland', 'wooded hills',
                        'mountains'
 f             (1,1)    Frequency (GHz)
 thetaG        (1,1)    Grazing angle (rad)
 sS            (1,1)    Sea state (0-8);
Outputs
 sigma0        (1,:)    Clutter coefficient
References Clutter(), Constant(), Frequency(), length(), Plot2D(), and zeros().
Referenced by Clutter(), and ClutterArea().
ClutterArea()
function ClutterArea (in theta, in r, in u, in rP, in t)
Form
 a = ClutterArea( theta, r, u, rP, t )
Inputs
 theta             (1,1)  Beamwidth (deg)
 r                 (3,:)  Orbit position
 u                 (3,1)  Boresight
 rP                (1,1)  Planet radius
 t                 (1,1)  Pulsewidth
Outputs
 a                 (1,:)   Clutter area
References and(), Clutter(), ClutterArea(), IntersectLineAndEllipsoid(), length(), Mag(), Plot2D(), Unit(), and zeros().
Referenced by ClutterArea().
CNRComp()
function CNRComp (in pFA, in pD, in n)
The inputs are the probability of false alarms, probability of detection and number of pulses.
Run a demo by typing CNRComp.
Form
 cNR = CNRComp( pFA, pD, n )
Inputs
 pFA           (1,1)  Probability of false alarm
 pD            (1,1)  Probability of detection
 n             (1,:)  Number of pulses
Outputs
 cNR           (1,:)   Carrier to noise ratio
See also
FPD.
References and(), CNRComp(), Demo(), FPD(), IsVersionAfter(), length(), Plot2D(), YBComp(), and zeros().
Referenced by CNRComp(), FPD(), and LADARTransmitPower().
ConstellationGroundContact()
function ConstellationGroundContact (in el, in d, in jD0, in zone, in m, in nP)
Type ConstellationGroundContact for a demo of a polar orbit with a contact group at the equator and one at the pole. The Julian date is set so that the equator group is visible at the start. The pole group will always be visible each orbit. The equator group appears again 12 hours later.
Form
 iOpp = ConstellationGroundContact( el, d, jD0, zone, m, nP )
Inputs
 el      (6,:)   Kepler elements [a;i;w;W;e;M]
 d       (1,1)   Allowable range for a contact (km)
 jD0     (1,1)   Start Julian Date  (days)
 zone    (:)     Zone data structure
                 .lat (1,2) [min max] latitude (deg)
                 .lon (1,2) [min max] latitude (deg)
                 .n   (1,1) Number of users in zone
 m       (1,1)   Number of time steps per orbit period
 nP      (1,1)   Number of orbit periods to analyze
Outputs
 iOpp    (:,:)   Percent contacts per zone
References and(), ConstellationGroundContact(), CosD(), Demo(), DupVect(), isempty(), JD2T(), length(), Mag(), Period(), Plot2D(), RVOrbGen(), set(), SinD(), TimeLabl(), TruEarth(), and zeros().
Referenced by ConstellationGroundContact().
ConstellationMaxDistance()
function ConstellationMaxDistance (in el, in pl, in m, in nP)
Computes only interplanar distances.
Form
 maxDist = ConstellationMaxDistance( el, pl, m, nP )
Inputs
 el      (6,:)   Kepler elements
 pl      (1,:)   Plane id
 m       (1,1)   Number of time steps
 nP      (1,1)   Number of periods to analyze
Outputs
 maxDist    (1,:)   Maximum distance.
References ConstellationMaxDistance(), Demo(), isempty(), Mag(), Period(), Plot2D(), RVOrbGen(), TimeLabl(), WalkerConstellation(), and zeros().
Referenced by ConstellationMaxDistance().
DataRate()
function DataRate (in power, in d)
Computes channel data rate from transmission and receiver areas. Need 22 Mbps for 1080p HDTV. Type DataRate for a demo of the New Horizons X-band system.
Form
 dR = DataRate;   % data structure
 dR = DataRate( power, d )
Inputs
 power  (1,:) Power transmit (W)
 d      (.)   Data structure
             .fGHz           (1,1) Frequency (GHz)
             .range          (1,1) Range (km)
                .areaTransmit   (1,1) Transmission area (m^2)
             .areaReceive    (1,1) Receiver area (m^2)
             .tempS          (1,1) Receiver noise temperature (deg-K)
                .modulation     (1,:) 'BPSK' 'QPSK' 'DE-BPSK' 'DE-QPSK' 'D-BPSK'
            .sN             (1,1) Signal to noise ratio
Outputs
 dR (1,:) Data rate (bps)
Reference: Bousquet, Maral, "Satellite Communications Systems", Third Ed., Wiley, 1998. p 130
See also
ModulationSpectralEfficiency
References and(), DataRate(), Demo(), Frequency(), FrequencyToWavelength(), ModulationSpectralEfficiency(), Plot2D(), and Product().
Referenced by DataRate(), and DataRateGain().
DataRateGain()
function DataRateGain (in power, in d)
This is similar to data rate except that you enter antenna gains in dB. Accounts for the free space loss only, other losses should be passed in via the lossOther field.
Type DataRateGain for a demo.
Form
 d = DataRateGain;  % data structure
 [dR,pR,b] = DataRateGain( power, d )
Inputs
 power       (1,:) Power transmit (W)
 d           (.)   Data structure
                   .fGHz         (1,1) Frequency (GHz)
                   .range        (1,1) Range (km)
                   .gainTransmit    (1,1) Transmit antenna gain (dB)
                   .gainReceive (1,1) Receiver antenna gain (dB)
                   .tempS        (1,1) Receiver noise temperature (deg-K)
                   .lossOther    (1,1) Other losses (dB)
                   .modulation   (1,:) 'BPSK' 'QPSK' 'DE-BPSK' 'DE-QPSK' 'D-BPSK'
                   .sN           (1,1) Signal to noise ratio
Outputs
 dR          (1,:) Data rate (bps)
 pR          (1,:) Power received (W)
 b           (1,:) Bandwidth (Hz)
Reference: Bousquet, Maral, "Satellite Communications Systems", Third Ed., Wiley, 1998. p 130
See also
ModulationSpectralEfficiency, DataRate, DBSignalToPower
References and(), AntennaGain(), DataRate(), DataRateGain(), DBSignalToPower(), Demo(), Frequency(), FrequencyToWavelength(), ModulationSpectralEfficiency(), Plot2D(), and Product().
Referenced by DataRateGain(), and DataRateOrbit().
DataRateOrbit()
function DataRateOrbit (in r, in rGS, in power, in jD, in d)
Data rate is a function of range. This functino sets the slant range based on the orbit. Type DataRateOrbit for a demo.
Form
 d  = DataRateOrbit;   % data structure
 dR = DataRateOrbit( r, rGS, power, d )
Inputs
 r           (3,:) Vector of orbit positions in ECI (km)
 rGS         (3,1) Position of ground station in ECEF (km)
 power       (1,:) Power transmit (W)
 jD          (1,:) Julian date
 d           (.)   Data structure
                   .fGHz         (1,1) Frequency (GHz)
                   .range        (1,1) Range (km), computed
                   .gainTransmit    (1,1) Transmit antenna gain (dB)
                   .gainReceive (1,1) Receiver antenna gain (dB)
                   .tempS        (1,1) Receiver noise temperature (deg-K)
                   .modulation   (1,:) 'BPSK' 'QPSK' 'DE-BPSK' 'DE-QPSK' 'D-BPSK'
                   .sN           (1,1) Signal to noise ratio
                   .lossOther    (1,1) Additional losses (dB)
Outputs
 dR          (1,:) Data rate (bps)
References DataRateGain(), DataRateOrbit(), Demo(), ECIToEF(), Frequency(), ISSOrbit(), JD2T(), LatLonToR(), length(), Mag(), Plot2D(), RVOrbGen(), Unit(), and zeros().
Referenced by DataRateOrbit().
DBmToPower()
function DBmToPower (in dBm)
dBm is computed from the power in mW
Form
 power = DBmToPower( dBm )
Inputs
 dBm           (1,:)    dB of mW signal
Outputs
 power         (1,:)    Power (W)
Reference: Edde, B., "Radar," Prentice-Hall, pp. 702-703
References DBmToPower(), and Plot2D().
Referenced by DBmToPower().
DBPower()
function DBPower (in p)
dB = 20 log10(s).
Form
 dB = DBPower( p )
Inputs
 p       (:)     Power
Outputs
 dB      (:)     Decibels
References: Lambert, S. G. and W. L. Casey (1995.) Laser Communications in Space. Artech, Boston.
References and(), DBPower(), Demo(), and Plot2D().
Referenced by DBPower().
DBSignal()
function DBSignal (in s)
dB = 10 log10(s).
Form
 dB = DBSignal( s )
Inputs
 s            (:)     Signal
Outputs
 dB            (:)     Decibels
References: Lambert, S. G. and W. L. Casey (1995.) Laser Communications in Space. Artech, Boston.
References and(), DBSignal(), Demo(), and Plot2D().
Referenced by DBSignal(), LinkAnalysisTool(), LinkBudget(), and RadarSN().
DBSignalToPower()
function DBSignalToPower (in dBW)
Type DBSignalToPower for a demo.
Form
 power = DBSignalToPower( dBW )
Inputs
 powerDB       (1,:)  Power (dBW)
Outputs
 power         (1,:)  Power (W) or signal
References DBSignalToPower(), and Plot2D().
Referenced by DataRateGain(), DBSignalToPower(), LinkOrbitAnalysis(), and RadarSN().
DBsmToSM()
function DBsmToSM (in dBsm)
Form
 m = DBsmToSM( dBsm )
Inputs
 dBsm          (1,:)    dB square meters
Outputs
 m             (1,1)    Square meters
References DBsmToSM(), Plot2D(), Square(), and square().
Referenced by DBsmToSM().
DBWToNW()
function DBWToNW (in powerDB)
Form
 power = DBWToNW( powerDB )
Inputs
 powerDB       (1,:)  Power (dB)
Outputs
 power         (1,:)  Power (nW)
References Demo(), and Plot2D().
DBWToPower()
function DBWToPower (in dBW)
Form
 power = DBWToPower( dBW )
Inputs
 dBW           (1,:)    dBW
Outputs
 power         (1,:)    Power (W)
References DBWToPower(), and Plot2D().
Referenced by DBWToPower().
DBWToPW()
function DBWToPW (in powerDB)
Form
 power = DBWToPW( powerDB )
Inputs
 powerDB       (1,:)  Power (dB)
Outputs
 power         (1,:)  Power (pW)
References Plot2D().
DopplerBlind()
function DopplerBlind (in fT, in vR)
Form
 fR = DopplerBlind( fT, vR )
Inputs
 fT    (1,1)   Transmit Frequency (GHz)
 vR    (1,:)   Relative velocity (m/sec)
Outputs
 fR    (1,:)   Pulse repetition frequency
References: Edde, B., Radar: Principles, Technology, Applications, Prentice-Hall PTR, 1995, p. 307.
References Constant(), DopplerBlind(), Frequency(), and Plot2D().
Referenced by DopplerBlind().
DopplerShift()
function DopplerShift (in fT, in vR)
Form
 [fD, fR] = DopplerShift( fT, vR )
Inputs
 fT           (1,1)   Transmit Frequency (GHz)
 vR           (1,:)   Relative velocity (m/sec)
Outputs
 fD           (1,:)   Doppler shift
 fR           (1,:)   Receive frequency (GHz)
References: Edde, B., Radar: Principles, Technology, Applications, Prentice-Hall PTR, 1995, p. 305.
References Constant(), DopplerShift(), Frequency(), and Plot2D().
Referenced by DopplerShift().
FPD()
function FPD (in cNR, in pD, in yB, in n)
Form
 x = FPD( cNR, pD, yB, n )
Inputs
 CNR           (1,1)  Carrier to noise ratio
 pD            (1,1)  Probability of detection
 yB            (1,1)  Upper range of integrand
 n             (1,:)  Number of pulses
Outputs
 x             (1,1)   Value
See also
CNRComp.
References CNRComp().
Referenced by CNRComp().
FPFA()
function FPFA (in yB, in pFA, in n)
 Used for computing yB in the equation
 pFA = 1 - gammainc( n, yB )
 Called by fzero. See also YBComp.
Form
 x = FPFA( yB, pFA, n )
Inputs
 yB            (1,1)    Quantity to be solved for
 pFA           (1,1)    Probability of false alarm
 n             (1,1)    Number of pulses
Outputs
 x             (1,1)    pFA - 1 + gammainc( n, yB )
Reference: Yoder, M. J. and D. Seliverstov, "End-to-end laser radar code for coherent CW lasers," Laser Radar Technology and Applications Proceedings SPIE, Volume 2748, pp. 232-245.
References and(), and YBComp().
Referenced by YBComp().
Frequency()
function Frequency (in band, in new, in which)
Form
 Frequency;
 f = Frequency( band, new, which )
Inputs
 band      (1,:)  Band, for example 'uhf', 'visible'
 new       (1,1)  1 = Use new bands, i.e. 'a', 'b'
 which     (1,1) 'low' 'high' or 'both'
Outputs
 f          (:)    Frequency (Hz)
References Demo(), Frequency(), and isempty().
Referenced by ACResistance(), Alias(), AntennaGain(), Beamwidth3dB(), BodeGP(), ClassERFAmplifier(), Clutter(), DataRate(), DataRateGain(), DataRateOrbit(), DBode(), Disturbances(), DopplerBlind(), DopplerShift(), FFTEngy(), Frequency(), FrequencyToWavelength(), FResp(), FRespG(), FRespPlot(), GND(), GPMargin(), GravityGradientBoom(), GravityGradientFrequency(), GSS(), Integral(), LADAREquation(), LADARTransmitPower(), LeadLag(), LinkBudget(), LinkOrbitAnalysis(), LogLimit(), LossAtmosphericGas(), LossDepointing(), LossPrecipitation(), LRLoopAntenna(), LRRectangleAntenna(), MagPlot(), NElementsPhasedArray(), NumericalTransferFunction(), NutationMWA(), Nyquist(), PerUnitNormalization(), PGains(), PhasedArray(), PIDProper(), PIDWithLag(), PowerReceived(), PWMSeq(), RadarPulseTrain(), RadarSN(), SkinDepth(), SVPlot(), TMoon(), TPlanet(), TSky(), TSun(), TTPlots(), WavelengthToFrequency(), WaveletMorlet(), WindAdmittance(), WPZ(), WReson(), and ZFresp().
FrequencyToWavelength()
function FrequencyToWavelength (in f, in c)
Form
 lambda = FrequencyToWavelength( f, c )
Inputs
 f           (1,:)     Frequency (Hz)
 c           (1,1)     Propagation speed (m/s)
Outputs
 lambda     (1,:)     Wavelength (m)
References Frequency(), isempty(), Plot2D(), and Wavelength().
Referenced by DataRate(), DataRateGain(), LinkOrbitAnalysis(), RadarSN(), and Wavelength().
Gain3dB()
function Gain3dB (in theta3DB, in fIllumination, in eff)
Form
 g = Gain3dB( theta3DB, fIllumination, eff )
Inputs
 theta3DB      (1,1)   3 dB Angle (deg)
 fIllumination (1,1)   Illumination factor (deg)
 eff           (1,1)   Efficiency
Outputs
 g             (:)   Gain (dB)
References: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems. Wiley. pp. 18
References and(), Illumination(), isempty(), and Plot2D().
Referenced by LinkAnalysisTool().
GainPattern()
function GainPattern (in antDiam, in centerFreq, in angle)
Compute an antenna gain pattern as a function of the incidence angle for a circular dish antenna.
Type GainPattern for a demo.
Form
 g = GainPattern( antDiam, centerFreq, angle );
Inputs
 antDiam       (1,1)   Antenna diameter  (m)
 centerFreq    (1,1)   Center frequency (MHz)
 angle         (1,:)   Incidence angle (rad)
Outputs
 g             (1,:)   Gain
References abs(), Demo(), GainPattern(), length(), and Plot2D().
Referenced by GainPattern().
GenerateSwath()
function GenerateSwath (in d, in r, in q, in t)
This function will animate ground patterns on a 2D and 3D map of any planet. Each antenna has a boresight rotation matrix that aligns the boresight then a list of azimuth and elevation points defining the boundary. Each list has a dB level associated with it and there may be multiple lists per antenna. az must range from 0 to 2*pi.
Each antenna beam is a different color with different shades per dB level.
The output is a set of patterns per antenna. Each pattern is the latitude and longitude of the beam edge. Each lat and lon entry is one row per time step.
The d.antenna(k).b matrix rotates a vector from the z-axis to the desired direction in the body frame. Azimuth is from the +x axis and elevation from the xy-plane. x, y, z are defined in the body frame.
Form
 swath = GenerateSwath( d, r, q, t )
Inputs
 d  (.)    Parameters
            .planet (1,:) Name of planet
            .antenna (:)
                        .b       (3,3) Boresight rotation matrix
                        .pattern (:)   Pattern per dB level
                                      .dB (1,1) Decibel level
                                      .az (1,:) Azimuth (rad)
                                      .co (1,:) Coelevation (rad)
 r  (3,:)  Planet fixed position vector (km)
 q  (4,:)  Planet fixed to body quaternion [q_s;q_x;q_y;q_z]
 t  (1,:)  Time (sec)
Outputs
 swath  (:) One element per antenna
            .lat     (n,1) Latitude of beam center (rad)
            .lon     (n,1) Longitude of beam center (rad)
             .pattern (:) One entry per pattern
             .lat     (n,:) Latitude (rad)
             .lon     (n,:) Longitude (rad)
             .dB      (n,1) dB level
References and(), AzCoElToU(), Constant(), Demo(), Eul2Mat(), GenerateSwath(), IntersectLineAndEllipsoid(), length(), Map(), Period(), Plot2D(), QLVLH(), QTForm(), quaternion(), R2LatLon(), RVFromKepler(), set(), TimeLabl(), vector(), and zeros().
Referenced by GenerateSwath().
GroundStationVisibility()
function GroundStationVisibility (in rGroundStation, in jD, in rSC, in horizonAngle)
Has a built-in demo.
Form
 visible = GroundStationVisibility( rGroundStation, jD, rSC, horizonAngle )
Inputs
 rGroundStation   (3,m)   Earth fixed location of station(s)
 jD               (1,n)   Julian date
 rSC              (3,n)   Position(s) of spacecraft, ECI frame
 horizonAngle     (1,1)   Minimum elevation to ground station (rad)
Outputs
 visible          (n,m)   Matrix of visible flags
See also
SatelliteVisibility, ECIToEF, LatLonAltToEF
References Cross(), Demo(), Dot(), ECIToEF(), GroundStationVisibility(), JD2000(), JD2T(), LatLonAltToEF(), length(), Map(), NewFig(), RVFromKepler(), SatelliteVisibility(), square(), Unit(), and zeros().
Referenced by GroundStationVisibility(), LinkAnalysisTool(), and LinkOrbitAnalysis().
ISLFOV()
function ISLFOV (in r, in q, in b, in a3dB, in rT, in t)
Any number of satellites can be tested against any number of boresights on a satellite. The output is the distance of the target from the satellite when the target is within the angle specified by a3dB.
The output is a cell array of 1 by n vectors.
Type ISLFOV for a demo. In the demo one spacecraft is in the same orbit and displace by pi/16. The other is in a lower orbit. The boresight vectors point at the two targets at the start.
Form
 sp = ISLFOV( r, q, b, a3dB, rT, t )
Inputs
 d             (3,n)    Spacecraft positinn vector
 q             (4,n)    Spacecraft quaternion from ECI to Body
 b             (3,m)    Boresight vectors
 a3dB          (1,m)    3 dB angles for each boresight
 rT            {w}      (3,:) target vectors
 t             (1,n)    TIme vector
Outputs
 p             {m,w}    (1,:) Distance vectors
References and(), ISLFOV(), quaternion(), and vector().
Referenced by ISLFOV().
LADAREquation()
function LADAREquation (in d)
Computes probability of detection, carrier to noise ratio and received power.
Run the built-in demo by typing LADAREquation.
Form
 [pD, cNR, pR] = LADAREquation( d )
Inputs
 d             (.)    Parameters
                        .lambda (1,1) Wavelength
                        .theta  (1,1) Beam divergence
                        .r      (1,m) Range (m)
                        .b      (1,1) Bandwidth (Hz)
                        .pT     (1,n) Transmit power
                        .xC     (1,1) Target cross section
                        .d      (1,1) Aperture diameter
                        .etaQ   (1,1) Quantum efficiency
                        .etaM   (1,1) Mixer efficiency
                        .etaE   (1,1) Electronics efficiency
                        .etaT   (1,1) Transmitter efficiency
                        .etaR   (1,1) Receiver efficiency
                        .rho    (1,1) Target reflectivity
                        .n      (1,1) Number of pulsewidths
                        .tA     (1,m) Transmission loss
                        .thetaT (1,:) Beam divergence corresponding to tA
                        .pFA    (1,1) Probability of false alarm
                        .k      (1,1) Beam shape factor
                        .x      (1,m) Auxiliary array for x-axis of plot
                        .xLabel (1,m) Corresponding label
Outputs
 pD            (n,m)   Probability of detection
 cNR           (n,m)   Carrier to noise ratio
 pR            (n,m)   Power received
Reference: Yoder, M. J. and D. Seliverstov, "End-to-end laser radar range code for coherent CW lasers," Proceedings SPIE Laser Radar and Applications, 10-11 April 1996, Orlando, FLA, pp. 232-245.
References Altitude(), and(), Demo(), Frequency(), LADAREquation(), length(), Wavelength(), YBComp(), and zeros().
Referenced by LADAREquation().
LADARTransmitPower()
function LADARTransmitPower (in d)
Run the build in demo by typing LADARTransmitPower.
Form
 [cNR, pR, pT] = LADARTransmitPower( d )
Inputs
 d             (1,1)    Parameters
                        .lambda (1,1) Wavelength
                        .theta  (1,1) Beam divergence
                        .r      (1,m) Range (m)
                        .pD     (1,n) Probability of detection
                        .xC     (1,1) Target cross section
                        .a      (1,1) Aperture area
                        .etaQ   (1,1) Quantum efficiency
                        .etaM   (1,1) Mixer efficiency
                        .etaE   (1,1) Electronics efficiency
                        .etaT   (1,1) Transmitter efficiency
                        .etaR   (1,1) Receiver efficiency
                        .rho    (1,1) Target reflectivity
                        .n      (1,1) Number of pulsewidths
                        .tA     (1,m) Transmission loss
                        .thetaT (1,:) Beam divergence corresponding to tA
                        .pFA    (1,1) Probability of false alarm
                        .k      (1,1) Beam shape factor
                        .x      (1,m) Auxiliary array for x-axis of plot
                        .xLabel (1,m) Corresponding label
Outputs
 cNR           (n,m)   Carrier to noise ratio
 pR            (n,m)   Power received
 pT            (n,m)   Power transmitted
References and(), CNRComp(), Demo(), Frequency(), LADARTransmitPower(), length(), Wavelength(), and zeros().
Referenced by LADARTransmitPower().
LinkAnalysisTool()
function LinkAnalysisTool (in spaceLink, in groundLink, in orbit)
The routine will automatically propagate for a full earth rate/orbit cycle starting at the JD in the orbit data structure. Keplerian orbit kinematics are assumed. Transformation to Earth-fixed is done with TruEarth. This function includes a precipitation model to estimate rain loss.
You can run a demo by typing LinkAnalysisTool.
Form
 LinkAnalysisTool; % demo
 [gOverT, cOverN0, lRain, lFS, lA] = LinkAnalysisTool( spaceLink, groundLink, orbit )
Inputs
 spaceLink     (.)    Space link data structure, transmit
                        .theta3DB                    (1,1) 3 dB antenna angle (deg)
                        .effTransmit                 (1,1) Transmit efficiency
                        .powerTransmit               (1,1) Transmit power (W)
                        .lossEdge                    (1,1) Edge loss (dB)
                        .lossTransmitterFeed         (1,1) Feed loss (dB)
                        .frequency                   (1,1) Transmit frequency (GHz)
 groundLink    (.)    Ground link data structure, receive
                        .latitude                    (1,1) Latitude (deg)
                        .longitude                   (1,1) Longitude (deg)
                        .altitude                    (1,1) Altitude (km)
                        .horizonAngle                (1,1) Minimum angle above the horizon (rad)
                        .antenna.type                (1,:) Antenna type
                        .antenna.area                (1,1) Antenna area (m^2)
                        .antenna.eff                 (1,1) Antenna efficiency
                        .thetaDepointing             (1,1) Pointing error (deg)
                        .tGround                     (1,1) Ground noise temperature (deg-K)
                        .tFeeder                     (1,1) Ambient feeder temperature (deg-K)
                        .lossReceiver                (1,1) Receiver loss (dB)
                        .lossFeeder                  (1,1) Feeder loss (dB)
                        .climateZone                 (1,1) Climate zone (a-q)
                        .precipitationFractionOfTime (1,1) Fraction of time with precipitation
                        .polarizationTiltAngle       (1,1) Polarization tilt angle (deg)
 orbit         (.)    Orbit data structure
                        .el (1,6)  [a i w W e M] [(km) (rad) (rad) (rad) () (rad)]
                        .jD (1,1)  Epoch (Julian Days)
                        .t  (1,:)  Time (sec) from epoch
Outputs
 gOverT        (1,:)     g/T (dB) at the ground station
 cOverN0       (1,:)     c/N0, carrier to noise density ratio (dB-Hz)
 lRain         (1,:)     Rain loss (dB)
 lA            (1,:)     Atmospheric gas loss (dB)
 lFS           (1,:)     Free space loss (dB)
References Altitude(), and(), AntennaGain(), Beamwidth3dB(), DateStringToJD(), DBSignal(), Gain3dB(), GroundStationVisibility(), HorizonAngle(), JD2T(), LatLonAltToEF(), length(), LinkAnalysisTool(), LossAtmosphericGas(), LossDepointing(), LossFreeSpace(), LossPrecipitation(), Mag(), Period(), Plot2D(), RVFromKepler(), TAntennaGround(), TAttenuator(), TimeLabl(), TReceiver(), TruEarth(), TSky(), and zeros().
Referenced by LinkAnalysisTool().
LinkBudget()
function LinkBudget (in dIn, in fileName)
You can either enter the elevation (horizon) angle or enter the latitude, longitude and altitude of the ground station and the earth-fixed satellite position vector. You can also either enter the ground station G/T or ground station antenna, noise temperature and losses.
If you want to compute rain losses you must enter the ground station information and the climate zone. See LossPrecipitation.m for more details.
Important outputs are:
 C/N     is the carrier to noise ratio for the desired bandwidth
 C/No    is the carrier to noise ratio
 EIRP    is the Equivalent Isotropic Radiated Power for the transmitter
 which is the figure of merit for a transmitter
 Eb/No   is similar to C/N only it is for the input bitrate
Required Eb/No is an input and based on the specificiation of your communications system. LinkBudget computes the bit error rate which should be low if you have some margin over the required Eb/No.
All inputs and outputs are in data structures.
If the optio0nal fileName is entered it will generate a latex table in a file fileName.tex that can be \input(fileName.tex) into any latex document.
Type LinkBudget for a demo.
Form
 dIn = LinkBudget;   % data structure
 LinkBudget;   % demo
 dOut = LinkBudget( dIn, fileName )
Inputs
 dIn     (.)   Input data structure
              .transmitterPower        (1,1) Transmit power (W)
              .feedLoss                (1,1) Feed loss (dB)
              .transmitAntennaDiameter (1,1) Diameter (m)
              .transmitAntennaEff      (1,1) Aperture efficiency
              .transmitAntennaType     (1,:) 'circular aperture' or 'dipole'
              .pathLength              (1,1) Range (km)
              .frequency               (1,1) Frequency (GHz)
              .requiredEbOverNo        (1,1) Required Eb/No (dB)
              .channelBandwidth        (1,1) Bandwidth (MHz)
              .bitRate                 (1,1) Bit rate (Mbits/s)
              .fIllumination           (1,1) Illumination angle (deg)
              .pointingError           (1,1) Pointing error (deg)
              .psi                     (1,1) Polarization angle error (deg)
              .elevationAngle          (1,1) Elevation from ground plane (deg)
              .modulation              (1,:) Modulation type, see BEP.m
 Either enter this or the receive antenna gain and temperature:
 .receiveSystemGT         (1,1) G/T for receiver
 Or these:
 .tAttenuatorAmbient      (1,1) Ambient attenuator
 temperature (deg-K)
 .lossAttenuator          (1,1) Attenuator loss (dB)
 .tGround                 (1,1) Ground noise temperature (deg-K)
 .feedLossGround          (1,1) Feed loss (dB)
 .tAttenuatorAmbient      (1,1) Ambient temperature (deg-K)
 For the receive antenna gain use these:
 .receiveAntennaDiameter  (1,1) Diameter (m)
 .receiveAntennaEff       (1,1) Aperture efficiency
 .receiveAntennaType      (1,:) 'circular aperture' or
 'dipole'
 Or:
 .receiveAntennaGain      (1,1) Gain (dB)
 Optional Fields for rain losses:
 .climateZone             (1,1) Letter for zone A-H
 .precipitationFract      (1,1) Time with rain
 .latitude                (1,1) Station latitude (deg)
 .longitude               (1,1) Station longitude (deg)
 .altitude                (1,1) Station altitude (deg)
 .rEF                     (3,1) EF position (km)
 fileName   (1,:)  Filename for .tex file
Outputs
 dOut   (.)
              .transmitterPower (1,1) Power (W)
              .feedLoss         (1,1) Feeder loss (dB)
              .pathLoss          (1,1) Free space loss along path (dB)
              .frequency         (1,1) Frequency (GHz)
              .pathLength        (1,1) Path length (km)
              .antennaGain       (1,1) Transmit antenna gain (dB)
              .EIRP              (1,1) Equivalent Isotropic Radiated
                                       Power (dB/K)
              .requiredEbOverNo     (1,1) Received Eb/No (dB)
              .channelBandwidth (1,1) Bandwidth (dB-Hz)
              .bitRate           (1,1) Bit Rate (dB-Mb/s)
              .boltzmannConstant    (1,1) Boltzmann's Constant (dB)
              .absorptionLoss    (1,1) Loss from atmosphere gas (dB)
              .polarizationLoss (1,1) Loss form polarization mismatch (dB)
              .rainLoss          (1,1) Loss from rain (dB)
              .receiveSystemGT  (1,1) G/T (dB)
              .pointingLoss      (1,1) Loss (dB)
              .receivedPower     (1,1) Power (dBW)
              .receivedCNo       (1,1) C/No (dB-Hz)
              .receivedCN        (1,1) C/N  (dB-Hz)
              .receivedEbNo      (1,1) Received Eb/No (dB)
              .margin            (1,1) Link margin (dB)
See also
: LossPrecipitation, BEP
References and(), AntennaGain(), Beamwidth3dB(), BEP(), Constant(), DBSignal(), Demo(), Frequency(), HorizonAngle(), Illumination(), isempty(), LatLonAltToEF(), length(), LinkBudget(), LossAtmosphericGas(), LossDepointing(), LossFreeSpace(), LossPolarization(), LossPrecipitation(), TAntennaGround(), TAttenuator(), TReceiver(), TSky(), and vector().
Referenced by LinkBudget().
LossAtmosphericGas()
function LossAtmosphericGas (in f, in E)
Assumes the signal passes through a fixed slice of atmosphere. To make the output a gain change to sign of the output to negative. This function is valid for frequencies between 0.3 and 50 GHz and outside of this range it will throw an error.
Type LossAtmosphericGas for a demo.
Form
 LossAtmosphericGas;   % Demo
 a = LossAtmosphericGas( f, E )
Inputs
 f              (1,m)  Frequency (GHz)
 E              (1,n)  Elevation angle (deg)
Outputs
 a              (n,m)  Loss (dB)
Reference: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems, Third Edition. John Wiley. p. 57.
References and(), Demo(), Frequency(), isempty(), length(), LossAtmosphericGas(), and Plot2D().
Referenced by LinkAnalysisTool(), LinkBudget(), LinkOrbitAnalysis(), and LossAtmosphericGas().
LossDepointing()
function LossDepointing (in theta, in theta3DB, in d)
 Forms:
 l = LossDepointing( theta, theta3DB )
 l = LossDepointing( theta, fHz, d )
Inputs
 theta          (:)  Depointing (deg)
 theta3DB       (:)  3DB Angle  (deg)
 theta          (:)  Depointing (deg)
 fHz            (:)  Frequency (Hz)
 d              (:)  Antenna diameter (m)
Outputs
 l              (n,m)  Loss (dB)
Reference: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems, Third Edition. John Wiley. p. 27.
References and(), Frequency(), LossDepointing(), and Mesh2().
Referenced by LinkAnalysisTool(), LinkBudget(), and LossDepointing().
LossFreeSpace()
function LossFreeSpace (in f, in r)
This is the loss due to the spreading of the beam which goes as the distance squared. The default output is a 2D mesh plot.
Type LossFreeSpace for a demo.
Form
 l = LossFreeSpace( f, r )
Inputs
 f              (1,m)  Frequency (GHz)
 r              (1,n)  Distance (km)
Outputs
 l              (n,m)  Loss (dB)
Reference: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems, Third Edition. John Wiley. p. 25.
References and(), Demo(), and LossFreeSpace().
Referenced by LinkAnalysisTool(), LinkBudget(), and LossFreeSpace().
LossPolarization()
function LossPolarization (in psi)
 Type LossPolarization for a demo.
 Loss is converted to a gain by making it negative.
Form
 l = LossPolarization( psi )
Inputs
 psi   (:)  Angle between transmit and receive planes (deg)
Outputs
 l     (:)  Loss (dB)
Reference: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems, Third Edition. John Wiley. p. 27.
References and(), CosD(), LossPolarization(), and Plot2D().
Referenced by LinkBudget(), LinkOrbitAnalysis(), and LossPolarization().
LossPrecipitation()
function LossPrecipitation (in f, in zone, in pTime, in latitudeS, in longitudeS, in hS, in rSC, in tau)
The output is a loss in dB. This is a positive quantity. The negative must be used to get the gain for a link equation. e.g. 10 dB loss = -10 dB gain. This function only works in the northern hemisphere. Type LossPrecipitation for a demo for the 'K' zone.
Form
 aRain = LossPrecipitation( f, zone, pTime, latitudeS, longitudeS, hS, rSC, tau )
 aRain = LossPrecipitation( f, zone, pTime, E, tau )
Inputs
 f              (1,1)  Frequency (GHz)
 zone           (1,1)  Climate zone (A-Q)
 pTime          (1,1)  Precipation percentage of time
 latitudeS      (1,1)  Latitude of ground station (deg)
 longitudeS     (1,1)  Longitude of ground station (deg)
 hS             (1,1)  Ground station height (km)
 rSC            (3,1)  Spacecraft vector, EF (km)
 tau            (1,1)  Polarization tilt angle (deg)
Outputs
 aRain          (1,1)  Link attenuation (dB)
Reference: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems, Third Edition. John Wiley. pp. 47-57.
References and(), Frequency(), get(), HorizonAngle(), LatLonAltToEF(), length(), LossPrecipitation(), Plot2D(), vector(), and zeros().
Referenced by LinkAnalysisTool(), LinkBudget(), LossPrecipitation(), and TAntennaGround().
ModulationSpectralEfficiency()
function ModulationSpectralEfficiency (in modulation)
BPS = bandwidth* spectral efficiency
There is a built-in demo that cycles through all the types.
Form
 eff = ModulationSpectralEfficiency( modulation )
Inputs
 modulation (1,:)   'BPSK' 'QPSK' 'DE-BPSK' 'DE-QPSK' 'D-BPSK'
Outputs
 eff           (1,1) bps/Hz
Reference: Bousquet, M. and Maral, G. "Satellite Communications Systems, 3rd Edition," Wiley p 121.
References and(), and zeros().
Referenced by DataRate(), and DataRateGain().
MultiBEPPlot()
function MultiBEPPlot (in s, in bitRate, in cOverN, in threshold)
 n < m
Form
 MultiBEPPlot( s, bitRate, cOverN )
Inputs
 s              (1,:)     Type of modulation
 bitRate        (1,n)     Bit rate
 cOverN         (1,m)     C/N (carrier to noise ratio) (dB)
 threshold      (1,1)     Bit error rate threshold for plot
Outputs
 None
References and(), BEP(), isempty(), length(), MultiBEPPlot(), NewFig(), and zeros().
Referenced by MultiBEPPlot().
NElementsPhasedArray()
function NElementsPhasedArray (in w, in h, in f, in theta)
Form
 n = NElementsPhasedArray( w, h, f, theta )
Inputs
 w             (1,1)    Width (m)
 h             (1,1)    Height (m)
 f             (1,1)    Frequency (GHz)
 theta         (1,1)    Max scan angle (deg)
Outputs
 n             (1,1)    Number of elements
References Constant(), Frequency(), NElementsPhasedArray(), Plot2D(), and SinD().
Referenced by NElementsPhasedArray().
NoisePower()
function NoisePower (in t, in b)
 Has a built-in demo.
Form
 p = NoisePower( t, b )
Inputs
 t          (1,:)  Noise temperature (deg-K)
 b          (1,:)  Bandwidth (Hz)
Outputs
 p          (1,1)  Noise Power
Reference: Swenson, G.W. (2000.) "Intragalactically Speaking." Scientific American. July 2000. p. 46.
References and(), isempty(), and Mesh2().
OpticalBackgroundNoise()
function OpticalBackgroundNoise (in s, in wavelength)
 Available sources are Solar, Lunar, Mercury, Venus, Mars, Jupiter,
 Saturn
 Sunlit clouds, sunlit snow and ice, starfield.
 The last four are per steradian so you must multiply times the
 field-of-view.
Form
 [i, u] = OpticalBackgroundNoise( s, wavelength )
Inputs
 s             {:}    Sources
 wavelength    (1,1)  Wavelength  [ .53 .85 1.06 1.3 1.5] micrometer
Outputs
 i             (:)     Irradiance or radiance
 u             (:)     Corresponding units
References: Lambert, S. G. and W. L. Casey (1995.) Laser Communications in Space. Artech, Boston. p. 155.
References and().
OpticalLinkBudget()
function OpticalLinkBudget (in d)
Assumes divergence limited transmitter. Has a built-in demo for Pluto mission.
Form
 [pR, b] = OpticalLinkBudget( d )
Inputs
 d      (.)   Input data structure
                 d.wavelength               Wavelength (m)
                 d.transmitApertureDiameter Transmit aperture (m^2)
                 d.thetaOffset              Pointing error (rad)
                 d.transmitPower            Transmission Power (W)
                 d.waveFrontError           Wavefront error
                                            Loss is exp(-2*pi*error/wavelength)
                 d.range                    Range (m)
                 d.receiverLoss             Receiver loss (0 to 1)
                 d.receiverPointingLoss     Receiver pointing loss (0 to 1)
                 d.receiveApertureDiameter  Receiver aperture diameter (m)
Outputs
 pR            (1)     Receive power
 b             (:)     Budget struct
References: Lambert, S. G. and W. L. Casey (1995.) Laser Communications in Space. Artech, Boston.
References and(), OpticalLinkBudget(), and Wavelength().
Referenced by OpticalLinkBudget().
OpticalReceiverNoiseDensity()
function OpticalReceiverNoiseDensity (in d)
Form
 nO = OpticalReceiverNoiseDensity( d )
Inputs
 d            (:)     Input data structure
                       d.type   'Coherent', 'Direct'
 All
 ---
 d.M      Avalanche gain of the detector
 d.kEff   Ionization coefficient of the photodiode
 d.pB     Received background power (W)
 d.rD     Detector responsivity
 d.iDU    Unmultiplied dc dark noise current
 d.iDM    Multiplied dc dark noise current
 d.T      Effective noise temperature of the feedback resistor
 d.rF     Resistance of the feedback resistor
 d.pAvg   Average signal power over the bit period
 Coherent
 --------
 d.pLO    Local oscillator power incident upon the photodetector
Outputs
 nO            (:)     Noise density
References: Lambert, S. G. and W. L. Casey (1995.) Laser Communications in Space. Artech, Boston. pp. 145-168.
References and(), and OpticalReceiverNoiseDensity().
Referenced by OpticalReceiverNoiseDensity().
PeriodToSemimajorAxis()
function PeriodToSemimajorAxis (in p, in mu)
Computes semi-major axis from the period. This provides a convenient way to get repeat tracks by making the period an integral fraction of one day.
Type PeriodToSemimajorAxis for a demo around the earth.
Form
 a = PeriodToSemimajorAxis( p, mu )
 a = PeriodToSemimajorAxis( p )     (Earth)
Inputs
 p   (1,:) Period (s)
 mu  (1,1) Gravitational parameter (km^3/s^2) [optional: default Earth]
Outputs
 a   (1,:) Semi-major axis (km)
See also
Period
References Demo(), get(), Period(), PeriodToSemimajorAxis(), Plot2D(), and TimeLabl().
Referenced by PeriodToSemimajorAxis(), and SemimajorAxisRevisit().
PhasedArray()
function PhasedArray (in f, in beamwidth, in thetaMax, in eta)
Form
 d = PhasedArray( f, beamwidth, thetaMax )
Inputs
 f             (1,1)    Frequency (GHz)  or string, e.g. 'ku'
 beamwidth     (1,1)    Beamwidth (deg)
 thetaMax      (1,1)    Maximum scan angle (deg)
 eta           (1,1)    Aperture efficiency
Outputs
 d             (1,1)    Data structure
                        .wAntenna          (1,1) Width of the antenna
                        .wElement          (1,1) Width of the element
                        .n                 (1,1) Number of elements
                        .g0                (1,1) Gain (dB)
                        .gThetaMax         (1,1) Gain at thetaMax (dB)
                        .beamwidthThetaMax (1,1) Beamwidth at thetaMax
References Constant(), CosD(), Frequency(), and PhasedArray().
Referenced by PhasedArray().
PowerReceived()
function PowerReceived (in pT, in aR, in aT, in r, in fGHz)
This just computes the free space losses due to distance. Everything else is ideal. It is useful for rough sizing of antennas. The example in the demo is for space to earth power transmission at 2.45 GHz.
The default output is a 2D mesh plot. Type PowerReceived for a demo.
Form
 PowerReceived;  % Demo
 [pR,gT,gR] = PowerReceived( pT, aR, aT, r, fGHz )
Inputs
 pT  (1,m)  Transmit power (W)
 aR   (1,1)  Receive antenna area (m^2)
 aT   (1,1)  Transmit antenna area
 r    (1,:)  Range (km)
 fGHz (1,1)  Frequency (GHz)
Outputs
 pR (1,:)  Power received (W)
 gT  (1,1)  Gain, transmit antenna
 gR  (1,1)  Gain, receive antenna
Reference: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems, Third Edition. John Wiley. p. 22.
References and(), Constant(), Demo(), Frequency(), length(), Plot2D(), and PowerReceived().
Referenced by PowerReceived().
PowerToDBm()
function PowerToDBm (in power)
Form
 dBm = PowerToDBm( power )
Inputs
 power         (1,:)    Power (W)
Outputs
 dBm           (1,1)    Power (dBm)
References Plot2D(), and PowerToDBm().
Referenced by PowerToDBm().
PowerToDBW()
function PowerToDBW (in power)
Form
 dBW = PowerToDBW( power )
Inputs
 power         (1,:)    Power (W)
Outputs
 dBW           (1,1)    Power (dBW)
References Plot2D(), and PowerToDBW().
Referenced by PowerToDBW().
ProbDetection()
function ProbDetection (in n, in cNR, in pFA)
Form
 pD = ProbDetection( n, cNR, pFA )
Inputs
 n             (1,1)    Number of pulses
 cNR           (1,:)    Carrier to noise ratio
 pFA           (1,:)    Probability of false alarm
Outputs
 pD            (1,1)    Probability of detection
Reference: Yoder, M. J. and D. Seliverstov, "End-to-end laser radar code for coherent CW lasers," Laser Radar Technology and Applications Proceedings SPIE, Volume 2748, pp. 232-245.
References and(), Demo(), Plot2D(), and YBComp().
RadarAccuracy()
function RadarAccuracy (in type, in d)
 Computes, angle, velocity, range or all. All computations need .sNR.
 theta is needed for angle, .t and .f for velocity, .b for range.
 Any one field of d can be an array. If more than one is an array
 it will use the first it finds.
 For a built in demo type "RadarAccuracy."
Form
 y = RadarAccuracy( type, d )
Inputs
 type          (1,:)     'all', 'angle', 'velocity', 'range'
 d             (1,:)
                        .b     (1,:) Bandwidth
                        .sNR   (1,:) Signal/noise ratio (dB)
                        .f     (1,:) Frequency (GHz)
                        .t     (1,:) Integration Period (sec)
                        .theta (1,:) Beamwidth (any)
Outputs
 y             (:,:)    Accuracy if 'all' [velocity;range;angle]
References and(), length(), and RadarAccuracy().
Referenced by RadarAccuracy().
RadarCrosssection()
function RadarCrosssection (in type, in lambda, in d)
 Types                            d
 cylinder               [radius length]
 sphere                 [diameter]
 diplane                [length of hinge, width of plane]
 triangular trihedral   [side]
 square trihedral       [side]
 circular trihedral     [side]
 flat rectangular plate [length width]
Form
 sigma = RadarCrossection( type, lambda, d )
Inputs
 type          (1,:)    String with type
 lambda        (1,:)    Wavelength
 d             (1,:)    Parameters
Outputs
 sigma      (1,:)     Crossection
References and(), length(), square(), and Wavelength().
Referenced by RadarEquationPulse(), and RadarEquationSN().
RadarEquation()
function RadarEquation (in solveFor, in d, in lambda)
Can compute range or power. This function assumes
 that the losses are not functions of wavelength and that the target area is
 a flat plate. Lambda is a scalar. The radar is assumed to be monostatic.
 Has a built in demo and will plot if no arguments are specified.
 There are several options. You can enter an RCS data structure or use the
 RCS as d.sigma. You can enter receive and transmit antenna gains or aperture
 areas.
 This function is a wrapper for RadarEquationPulse.
Form
 y = RadarEquation( solveFor, d, lambda )
Inputs
 solveFor      (1,:)    'range' or 'power'
 d             (1,1)    Parameters
                        .r      (1,:) Range (m)
                        .pT     (1,:) Transmit power
                        .rCS    (1,1) Target crossection data structure
                                      .type   (1,:) Crossection type
                                      .lambda (1,:) Wavelength
                                      .d      (1,1) Data structure
                        .a      (1,1) Aperture area
                        .f      (1,1) Receiver loss (dB)
                        .etaA   (1,1) Aperture efficiency
                        .b      (1,1) Bandwidth
                        .nL     (1,1) Number of pulsewidths
                        .lI     (1,1) Pulse integration loss (dB)
                        .lS     (1,1) System loss (dB)
                        .lA     (1,1) Propagation path losses (dB)
                        .sI     (1,1) Signal to interference ratio (dB)
 lambda        (1,:)    Wavelength
Outputs
 y             (:,:)    Power or range
References and(), length(), RadarEquation(), RadarEquationPulse(), scalar(), TPlanet(), Wavelength(), and zeros().
Referenced by RadarEquation().
RadarEquationPulse()
function RadarEquationPulse (in solveFor, in d)
Can compute range or power. This function assumes
 that the losses are not functions of wavelength and that the target area is
 a flat plate. Lambda is a scalar. The radar is assumed to be monostatic.
 Has a built in demo and will plot if no arguments are specified.
 There are several options. You can enter an RCS data structure or use the
 RCS as d.sigma. You can enter receive and transmit antenna gains or aperture
 areas.
Form
 y = RadarEquationPulse( solveFor, d )
Inputs
 solveFor      (1,:)    'range' or 'power'
 d             (1,1)    Parameters
                        .lambda (1,1) Wavelength
                        .r      (1,:) Range (m)
                        .pT     (1,:) Transmit power
                        .rCS    (1,1) Target crossection data structure
                                      .type   (1,:) Crossection type
                                      .lambda (1,:) Wavelength
                                      .d      (1,1) Data structure
                        .sigma  (1,1) Crosssection (m^2)
                        .a      (1,1) Aperture area
                        .aR     (1,1) Receive aperture area
                        .gA     (1,1) Transmit antenna gain (dB)
                        .gR     (1,1) Receive antenna gain (dB)
                        .f      (1,1) Receiver loss (dB)
                        .etaA   (1,1) Aperture efficiency
                        .b      (1,1) Bandwidth
                        .cR     (1,1) Pulse compression ratio
                        .nL     (1,1) Number of pulsewidths
                        .lI     (1,1) Pulse integration loss (dB)
                        .lS     (1,1) System loss (dB)
                        .lA     (1,1) Propagation path losses (dB)
                        .lGP    (1,1) Ground plane losses (dB)s
                        .sI     (1,1) Signal to interference ratio (dB)
Outputs
 y             (1,:)    Power or range
References and(), isempty(), Plot2D(), RadarCrosssection(), RadarEquationPulse(), RFSystemNoise(), scalar(), TPlanet(), and Wavelength().
Referenced by RadarEquation(), and RadarEquationPulse().
RadarEquationSN()
function RadarEquationSN (in type, in d)
 If no arguments are entered it will run demos of all types.
 if .sigma is entered it will ignore .rCS.
Form
 y = RadarEquationSN( type, d )
Inputs
 type          (1,:)    'pc', 'search', 'tracking', 'cw', 'pulse doppler'
 d             (1,1)    Parameters
                        .lambda  (1,1) Wavelength
                        .r       (1,:) Range (m)
                        .pT      (1,1) Transmit power (average for pulse)
                        .rCS     (1,1) Target crossection data structure
                                      .type   (1,:) Crossection type
                                      .lambda (1,:) Wavelength
                                      .d      (1,1) Data structure
                        .sigma   (1,1) Crosssection (m^2)
                        .a       (1,1) Aperture area
                        .aR      (1,1) Receive aperture area
                        .gA      (1,1) Transmit antenna gain (dB)
                        .gR      (1,1) Receive antenna gain (dB)
                        .f       (1,1) Receiver loss (dB)
                        .etaA    (1,1) Aperture efficiency ()
                        .b       (1,1) Bandwidth (Hz)
                        .cR      (1,1) Pulse compression ratio
                        .nL      (1,1) Number of pulsewidths
                        .lI      (1,1) Pulse integration loss (dB)
                        .lS      (1,1) System loss (dB)
                        .lA      (1,1) Propagation path losses (dB)
                        .lGP     (1,1) Ground plane losses (dB)s
                        .bS      (1,1) Tracking servo bandwidth (Hz)
                        .omega   (1,1) Search rate (deg/s)
                        .pRF     (1,1) Pulse repetition frequency (pps)
                        .thetaAz (1,1) Azimuth beamwidth (deg)
                        .lW      (1,1) Window loss (dB) CW Only
Outputs
 y             (1,:)    Power or range
References Demo(), RadarCrosssection(), RadarEquationSN(), RadarWindows(), RFSystemNoise(), TPlanet(), and Wavelength().
Referenced by RadarEquationSN().
RadarPulseTrain()
function RadarPulseTrain (in fGHz, in tau, in tauP, in t)
 Type RadarPulseTrain for a demo.
 Since version 11.
Form
 p = RadarPulseTrain( fGHz, tau, tauP, t )
Inputs
 fGHz           (1,1)    Frequency (GHz)
 tau            (1,1)    Pulsewidth (sec)
 tauP           (1,1)    Pulsing period
 t              (1,:)    Time vector (sec)
Outputs
 p              (1,:)    Pulse train
References Demo(), Frequency(), length(), Plot2D(), RadarPulseTrain(), vector(), and zeros().
Referenced by RadarPulseTrain().
RadarSN()
function RadarSN (in d)
 Losses are positive dB. A loss of 10 would be 10 dB.
 If aTarg is not [] it will compute sigma. Otherwise sigma will be
 used. sN, pR and PN will be a vectors if d.r is a vector. eRP is a
 scalars.
 Type RadarSN for a demo of an L band radar from the reference.
Form
 [sN, eRP, pR, pN] = RadarSN( d )
Inputs
 d  (1,1) Data structure
           .freq   (1,1) Frequency (GHz)
           .aAnt   (1,1) Antenna area (m^2)
           .aTarg  (1,1) Target area  (m^2)
           .sigma  (1,1) Cross-section (m^2)
           .type   (1,:) 'coherent integration' or
                         'non-coherent integration'
           .n      (1,1) Number of pulses integrated
           .r      (1,:) Range (km)
           .eps    (1,1) Antenna efficiency
           .lossT  (1,1) Transmit loss (dB)
           .lossR  (1,1) Receiver loss (dB)
           .f      (1,1) Receiver noise factor (> 1)
           .tA     (1,1) Noise seen at the antenna input (deg-K)
           .pT     (1,1) Transmit power (W)
Outputs
 sN     (1,:) Signal to noise ratio  (dB)
 eRP (1,1) Effective radiated power (W)
 pR  (1,:) Received power at the antenna (W)
 pN  (1,:) Noise power (W)
Reference: Edde, B., "Radar Principles, Technology Applications," Prentice-Hall, 1995, pp. 30-37.
References and(), Constant(), Cross(), DBSignal(), DBSignalToPower(), Demo(), DispWithTitle(), Frequency(), FrequencyToWavelength(), isempty(), Plot2D(), RadarSN(), vector(), and Wavelength().
Referenced by MeasRadar(), and RadarSN().
RadarThermalNoise()
function RadarThermalNoise (in b, in f)
Form
 n = RadarThermalNoise( b, f )
Inputs
 b             (1,:)    Bandwidth (Hz)
 f             (1,1)    Receiver noise factor
Outputs
 n             (1,:)    System noise (W)
References Demo(), Plot2D(), and RadarThermalNoise().
Referenced by RadarThermalNoise().
RadarWindows()
function RadarWindows (in window)
 'rectangle', 'triangle', 'cosine', 'hann', 'hamming', 'k-b 2.5'...
 'k-b 3.0', 'd-c 2.5', 'd-c 3.0'
 Parameters: Highest sidelobe level (dB)
 Sidelobe roll-off (dB/octave)
 Coherent gain
 Equivalent noise bandwdith (bins)
 3 dB Bandwidth (bins)
 Scallop loss (dB)
 Worst case process loss (dB);
Form
 y = RadarWindows( window )
Inputs
 dBm           (1,:)    Window name
Outputs
 y            (1,7)     Parameters
Referenced by RadarEquationSN().
RFSystemNoise()
function RFSystemNoise (in tA, in tT, in lR, in f)
 If tT is [] it is assumed to be 290 deg-K.
Form
 tS = RFSystemNoise( tA, tT, lR, f )
Inputs
 tA            (1,1)    Antenna noise temperature (deg-K)
 tT            (1,1)    Thermodynamic temperature (deg-K)
 lR            (1,1)    Receiver ohmic losses (0 to 1)
 f             (1,1)    Receiver noise figure (1+)
Outputs
 tS            (1,1)    System noise temperature (deg-K)
References and(), Demo(), isempty(), RFSystemNoise(), and TSun().
Referenced by RadarEquationPulse(), RadarEquationSN(), and RFSystemNoise().
SatelliteVisibility()
function SatelliteVisibility (in r1, in r2, in horizonAngle, in planet)
It does not return the line of sight. If no outputs are requested it generates a 3D plot showing the planet and the arc where the r2 is visible. This routine assumes that the planet is a sphere.
Form
 visible = SatelliteVisibility( r1, r2, horizonAngle, planet )
Inputs
 r1           (3,1)     Viewing satellite
 r2           (3,:)     Viewed satellite
 horizonAngle (1,1)     Angle above horizon for visibility
 planet       (1,:)     Any planet name in the database
Outputs
 visible     (1,:)     1 if satellite is visible
References and(), Demo(), Dot(), DupVect(), isempty(), length(), Mag(), Map(), NewFig(), SatelliteVisibility(), set(), square(), Unit(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by GroundStationVisibility(), MeasCamera(), MeasRadar(), and SatelliteVisibility().
Shannon()
function Shannon (in name, in x)
 C/B = log ( 1 + S/N )
 2
 C   is the information content and B is the bandwidth.
 S/N is the signal to noise ratio. Enter one parameter and return the
 other. If no arguments are entered it will run a demo. If there are
 no output parameters it will plot the results.
Form
 y = Shannon( name, x )
Inputs
 name   (1,:)   'S/N' or 'C/B'
 x     (1,:)   Value(s)
Outputs
 y     (1,:)   S/N or C/B
References: Edde, B. (1995.) Radar. Prentice-Hall. p. 125.
References and(), Demo(), Plot2D(), and Shannon().
Referenced by Shannon().
SMToDBsm()
function SMToDBsm (in m)
Form
 dBsm = SMToDBsm( m )
Inputs
 m             (1,1)    Square meters
Outputs
 dBsm          (1,:)    dB square meters
References Plot2D(), SMToDBsm(), Square(), and square().
Referenced by SMToDBsm().
SNR()
function SNR (in d)
 Type SNR for a demo. Will create a plot for no outputs.
Form
 sNR = SNR( d )
Inputs
 d            (:)     Input data structure
                       d.pS       (1,:) Required signal       (W)
                       d.rD       (1,:) Detector responsivity (A/W)
                       d.nO       (1,:) Noise density         (A^2/Hz)
                       d.B        (1,:) Receiver bandwidth    (Hz)
Outputs
 sNR           (:)     Signal to noise ratio
References: Lambert, S. G. and W. L. Casey (1995.) Laser Communications in Space. Artech, Boston, pp. 145-146.
References and(), length(), and SNR().
Referenced by SNR().
TAntennaGround()
function TAntennaGround (in tSky, in aRain, in tGround)
 Rain acts as an attenuator for the sky.
 Type TAntennaGround for a demo. See also TSky and LossPrecipitation.
Form
 tA = TAntennaGround( tSky, aRain, tGround )
Inputs
 tSky          (1,1)  Ambient temperature of the sky
 aRain         (1,1)  Rain Loss (dB)
 tGround       (1,1)  Ambient temperature of the ground (deg-C)
Outputs
 tA            (1,1)  Antenna noise temperature
References: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems. Wiley. p. 37.
References and(), Demo(), LossPrecipitation(), TAntennaGround(), and TSky().
Referenced by LinkAnalysisTool(), LinkBudget(), LinkOrbitAnalysis(), and TAntennaGround().
TAttenuator()
function TAttenuator (in t, in loss)
t is the ambient temperature of the attenuator and tE is the effective input noise temperature. Has a demo.
Form
 tE = TAttenuator( t, loss )
Inputs
 t             (1,:)  Ambient temperature of the attenuator
 loss          (1,:)  Loss (dB)
Outputs
 tE            (1,:)  Effective input noise temperature
Reference: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems. Wiley. pp. 30.
References and(), length(), Plot2D(), and TAttenuator().
Referenced by LinkAnalysisTool(), LinkBudget(), and TAttenuator().
TMoon()
function TMoon (in ignoredArg)
Constant at 250 deg-K.
Form
 t = TMoon( f )
Inputs
 f             (1,:)  Frequency (GHz)
Outputs
 t             (1,:)  Moon noise temperature (deg-K)
References: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems. Wiley. pp. 37.
References and(), Constant(), and Frequency().
TNoiseCascade()
function TNoiseCascade (in d)
 Has a default input with three entries.
Form
 [t, f] = TNoiseCascade( d )
Inputs
 d             (:)  Data structure
                    .t  (1,1) Temperature (deg-K)
                    .g  (1,1) Gain (dB)
Outputs
 t             (1,1)  Temperature
 f             (1,1)  Noise figure
References: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems. Wiley. pp. 17-18.
References and(), length(), and series().
TPlanet()
function TPlanet (in f, in planet)
 Type TPlanet for a demo.
Form
 t = TPlanet( f, planet )
Inputs
 f             (1,:)  Frequency (GHz)
 planet        (1,:)  Planet, either 'earth' (default) or 'mars'
Outputs
 t             (1,:)  Planet noise temperature (deg-K)
References: Ho, C., Slobin, S., Sue, M. and E. Njoku, "Mars Background Noise Temperatures Received by Spacecraft Antennas," IPN Progress Report 142-149, May 15, 2002.
References and(), Frequency(), Plot2D(), and TPlanet().
Referenced by RadarEquation(), RadarEquationPulse(), RadarEquationSN(), and TPlanet().
TrackingAccuracy()
function TrackingAccuracy (in d)
 The tracking constant depends on the type of tracking. If omitted it is
 set to one.
 For a demo type TrackingAccuracy.
Form
 sigma = TrackingAccuracy( d )
Inputs
 d             (1,1)    Parameters
                        .sN     (1,1) Signal/Noise ratio (dB)
                        .n      (1,1) Number of pulse integrated
                        .lambda (1,:) Wavelengths (m)
                        .l      (1,1) Width of aperture (m)
                        .kT     (1,1) Tracking constant
Outputs
 sigma         (1,:)     1 sigma accuracy (rad)
References and(), set(), and TrackingAccuracy().
Referenced by TrackingAccuracy().
TReceiver()
function TReceiver (in tA, in lFRX, in tF, in tERX)
tA is the ambient temperature of the antenna and tERX is the receiver noise temperature. tF is the feeder noise temperature. This function combines them to compute the noise temperature at the input.
Form
 tR = TReceiver( tA, lFRX, tF, tERX )
Inputs
 tA            (1,1)  Antenna temperature (deg-K)
 lFRX          (1,:)  Feeder loss (dB)
 tF            (1,1)  Feeder temperature (deg-K)
 tERX          (1,1)  Effective input noise temperature of receiver (deg-K)
Outputs
 tR            (1,1)  Temperature at input (deg-K)
References: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems. Wiley. pp. 31.
References and(), Demo(), Plot2D(), and TReceiver().
Referenced by LinkAnalysisTool(), LinkBudget(), LinkOrbitAnalysis(), and TReceiver().
TSky()
function TSky (in f, in e)
Limited to frequencies between 2.5 and 60 GHz. Type TSky for a demo.
Form
 t = TSky( f, e )
Inputs
 f            (1,n)  Frequency (GHz)
 e            (1,m)  Elevation angle (deg)
Outputs
 t            (n,m)  Temperature
References: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems. Wiley. pp. 36.
References and(), Demo(), Frequency(), isempty(), length(), Plot2D(), and TSky().
Referenced by LinkAnalysisTool(), LinkBudget(), LinkOrbitAnalysis(), TAntennaGround(), and TSky().
TSun()
function TSun (in f, in thetaE, in hasPolarizer)
 Uses the formula t = a f^(-0.75) where a is adjusted to agree with p. 354
 of the reference and the noise maximums and minimus are limited according
 to the plot on p. 253. The numbers generated by this routine are approximate
 and even the reference is inconsistent with its numbers. Strictly speaking,
 the formula is only valid for K-band and a = 120000
Form
 [dT, t] = TSun( f, thetaE, hasPolarizer )
Inputs
 f             (1,:)  Frequency (GHz)
 thetaE        (1,1)  Aperture (deg)
 polarizer     (1,1)  1 if has polarizer
Outputs
 dT            (1,:)  Change in ambient temperature (deg-K)
 t             (1,:)  Sun noise temperature (deg-K)
References: Maral, G. and M. Bousquet. (1998.) Satellite Communications Systems. Wiley. pp. 352-353.
References and(), Frequency(), and TSun().
Referenced by RFSystemNoise(), and TSun().
TToPower()
function TToPower (in T, in b)
Form
 p = TToPower( T, b )
Inputs
 T            (1,m)   Temperature (deg-K)
 b             (1,n)   Bandwidth (Hz)
Outputs
 p             (n,m)   Power
Wavelength()
function Wavelength (in band, in ignoredArg)
 Type Wavelength for a demo. See also FrequencyToWavelength.
 Since version 3.
Form
 lambda = Wavelength( band, new )
Inputs
 band    (1,:)  Band, i.e. 'lf', 'ka'
 new     (1,1)  Use new bands, i.e. 'a', 'b'
Outputs
 lambda  (:)    Wavelength (m)
References Demo(), FrequencyToWavelength(), and Wavelength().
Referenced by AiryDefocused(), AiryDisk(), AiryDiskInPixels(), AiryResolution(), BandGapToWavelength(), BlurParameter(), CameraResolution(), DetectorModel(), EnergyPerRing(), EnergyPhoton(), FrequencyToWavelength(), HgCdTeWavelength(), IFOV(), LADAREquation(), LADARTransmitPower(), LaserBeamRadius(), LaserPower(), LRLoopAntenna(), LRRectangleAntenna(), LumenToWatt(), MeasRadar(), OpticalLinkBudget(), PixelFlux2D(), PixelSpread(), PlanckL(), QESilicon(), RadarCrosssection(), RadarEquation(), RadarEquationPulse(), RadarEquationSN(), RadarSN(), RHSAiryDefocusedPSF(), RHSAiryPSF(), RHSHelio2DOrbit(), VM2Photons(), VM2PSFPeak(), VMToPhotons(), Wavelength(), WavelengthToBandGap(), WavelengthToFrequency(), and WiensDsp().
WavelengthToFrequency()
function WavelengthToFrequency (in lambda, in c)
Form
 f = WavelengthToFrequency( lambda, c )
Inputs
 lambda  (1,:)     Wavelength (m)
 c       (1,1)     Propagation speed (default is speed of light)
Outputs
 f       (1,:)     Frequency
References Frequency(), isempty(), Plot2D(), and Wavelength().
YBComp()
function YBComp (in n, in pFA)
See also
FPFA.
Form
 [yB, err] = YBComp( n,  pFA )
Inputs
 n             (1,1)    Number of pulses
 pFA           (1,:)    Probability of false alarm
Outputs
 yB            (1,1)   yB value
 err           (1,1)   Error
Reference: Yoder, M. J. and D. Seliverstov, "End-to-end laser radar code for coherent CW lasers," Laser Radar Technology and Applications Proceedings SPIE, Volume 2748, pp. 232-245.
References and(), Demo(), FPFA(), and IsVersionAfter().
Referenced by CNRComp(), FPFA(), LADAREquation(), and ProbDetection().