PSS MATLAB Toolboxes: Interplanetary Functions
Interplanetary Functions
Interplanetary Module
The Interplanetary module functions.
Directories
directory Ephemeris
Planetary ephemeris.
directory Landers
directory LowEnergyManeuver
Low energy maneuvers in cislunar space.
directory LowEnergyManeuverData
Data for the cislunar low-energy maneuvers.
directory Optimization
2D and 3D orbit transfer optimization tools
directory Optimization
2D and 3D orbit transfer optimization tools
directory OrbitCoord
Heliocentric coordinate transformations.
directory OrbitInsertion
Insertion from heliocentric to planetary orbit.
directory RHSFunctions
Dynamics functions for integration.
directory ThreeBody
Three-body dynamics and halo orbits.
directory VehicleDesign
Vehicle modeling for interplanetary missions.
directory Visualization
Plotting functions specific to interplanetary trajectories.
Description
Functions
function AlphaCentauriSystem (in jD)
Model of the Alpha-Centauri system.
function ApophisOrbit ()
Generate elements and orbit state for the asteroid Apophis.
function ApproachConst2D (in u, in d, in t, in x0, in xF)
Equality constraints for the 2D orbit insertion problem.
function ApproachConst2DIneq (in u, in d, in t, in x0, in xF)
Equality constraints for the 2D orbit insertion problem.
function ApproachCost2D (in u)
Cost for the landing for a 2D orbit problem.
function ApproachCost2DMag (in u)
Cost for the landing for a 2D orbit problem.
function AsteroidProperties (in name)
Asteroid properties.
function AtmDensMars2 (in h)
Computes the atmospheric density of Mars.
function AtmDensNeptune (in h)
Computes Neptune's atmospheric density using scale heights.
function AtmDensTitan (in h)
Computes the atmospheric density of Titan using a curve fit.
function AtmDensUranus (in h)
Compute the atmospheric density on Uranus.
function BDipoleJupiter (in r, in jD)
Computes Jupiter's magnetic field based on a tilted dipole model.
function BDipolePlanet (in r, in jD, in planet)
Computes the geocentric magnetic field based on a tilted dipole model.
function BilinearTangentAltitude (in d, in t)
Bilinear tangent law for maximizing altitude on launch.
function BilinearTangentLaw (in u, in g, in a, in h, in n, in opt, in dT)
Bilinear tangent law for orbit insertion or landing.
function BilinearTangentVector (in r, in v, in g, in a, in h, in n, in opt, in type)
Bilinear tangent law in vector form for orbit insertion or landing.
function C3ToV (in c3, in r, in mu)
Convert c3 to orbital velocity.
function CheckForOptimizationToolbox ()
Check to see if MATLAB contains the Optimization Toolbox.
function CRTBP2kms (in stateIn, in distanceUnit, in muPrimary, in muSecondary)
Scales CRTBP Jacobi coordinates to km and sec.
function CRTBPJacobi (in x, in mu)
Compute the Jacobi constant for a state in the CRTBP system.
function CRTBPJacobiConstant (in y, in mu)
Calculate from Jacobi constant from a scaled state vector.
function CRTBPLinearSystem (in x, in mu)
Compute linear system matrix for the circular restricted 3 body problem.
function CRTBPRHS (in x, in t, in mu)
Right-hand-side for the circular restricted three body problem.
function EarthEscape (in el0, in jD, in days, in gRatio)
Simulate an escape trajectory from Earth using CRTBPRHS.
function EarthHelioState (in jD)
Compute the position and velocity of Earth in the heliocentric frame.
function EarthOrbToHelioOrb (in jD0, in elEarth, in SCParams)
Computes the heliocentric orbital elements after an Earth escape spiral.
function ECIToSunEarthRot (in jD, in JPL)
Convert ECI to Sun Earth rotating coordinates about the barycenter.
function EclipseHelio (in r, in rP, in planetID, in jD)
Determines eclipses in heliocentric coordinates.
function EclipticInjectionPlane (in jD, in vEcl)
Computes the parking orbit plane for a heliocentric injection.
function EnergyWRTMoon (in t, in y, in muMoon, in jDate)
Keplerian Energy with respect to the Moon.
function FCRTBPRHS (in x, in t, in mu, in a, in uE)
Right-hand-side for the forced circular restricted three body problem.
function FEarthMoon (in x, in t, in jD, in muMoon, in muEarth)
Gravity acceleration in the earth moon system.
function FEarthMoonSun (in t, in x, in flag, in d)
Orbit dynamics with spherical harmonic models of the Earth and Moon gravity.
function FHel (in x, in t, in d)
Orbit equations for InterstellarSim.
function FindDepartureDate (in jD0, in planet1, in planet2, in years)
Find the best departure date for TrajectoryBetweenTwoPlanets.
function FlybyHyperbola (in r, in v, in rP, in mu)
Compute the required orbital elements for a flyby.
function FSolarSail (in t, in x, in flag, in d)
Solar sail simulation right hand side.
function FuelTimeOptimalAccel (in d, in uE, in thrust)
Computes the optimal acceleration for a fuel/time problem.
function GalileanSatelliteOrbits (in jD)
Low precision orbits of the four major Galilean satellites.
function GVEGuidance (in el, in elT, in index)
Apply Gauss Variation Equations to determine in-plane thrust direction.
function HALOFamily (in Ax, in Az, in system, in point)
Compute and plot a family of stable HALO orbits in the given system.
function HALOInit (in Ax, in Az, in system, in point, in d0, in doPlot)
Compute a stable initial state for a HALO orbit.
function HALOPlot (in d, in type, in f, in plots)
Generate a plot of a HALO trajectory.
function HALOState (in Ax, in Az, in phiXY, in phiZ, in system, in point, in t)
Approximate an initial state for a HALO orbit given the orbit size.
function HelioFromPlanetInit (in name, in xP, in jD)
Initialize a heliocentric orbit from a planet centered orbit.
function HelioPlot (in p, in duration, in jD0, in r, in rName, in ecl)
Plot planets and a trajectory in the heliocentric frame.
function HelioToBPlane (in r0, in v0, in rA, in vA)
Transformation matrix from the heliocentric to B-plane frame.
function HelioToPlanet (in jD, in planet, in kEarth)
Computes the transformation matrix from heliocentric to planet fixed frame.
function InterpolateState (in target, in time, in fileName)
Interpolate a planet's state for a given Julian Date.
function IteratePeriodicOrbit (in p1, in mu, in family, in doSave)
Compute a periodic orbit for a LET transfer.
function J20002RotPuls (in stateIn, in primaryEph, in muPrimary)
Transform from J2000 frame to rotating-pulsating.
function J20002RotPulsPlanetMoon (in stateIn, in primaryEph, in muPrimary, in secondaryEph)
Transform a state vector from the J2000 reference frame to a rotating.
function JDStartTransfer (in jD0, in planetPair, in transferTime, in duration, in n)
Find the Julian Date for a straight line trajectory to the target.
function Kms2CRTBP (in stateIn, in distanceUnit, in muPrimary, in muSecondary)
Transform from km and sec to Jacobi coordinates for circular restricted.
function L2OrbitPlots (in x, in d)
Simulate and plot an Earth orbit to L2 point low thrust transfer.
function L2OrbitSim (in x, in d, in times)
Simulate the Earth orbit to L2 point low thrust transfer.
function LambertDoubleRendezvous (in planet1, in planet2, in jD0, in days, in duration)
Double rendezvous problem between two planets.
function LandingControl (in v, in h, in uV, in d)
Landing controller.
function LandingControlBilinear (in action, in d)
Implements a bilinear tangent landing controller.
function LandingControlGravityTurn (in v, in d)
Gravity turn landing controller.
function LandingForce (in x, in ignoredArg, in d)
Landing force in the body frame.
function LETGuess (in p1, in mu, in family)
Compute a periodic orbit for a LET transfer.
function LETPhasing (in x0, in desiredPhasing, in moon, in planet, in et, in jDate)
Calculate the nominal transfer time for a low energy transfer.
function LibrationCoeff (in mu, in gama, in n)
Compute the nth coefficient for the about a collinear libration point.
function LibrationData (in system)
Compute libration point data for the restricted three body problem.
function LibrationRHS (in x, in ignoredArg, in c2, in c3, in c4)
Computes the time derivative of a state at a collinear libration point.
function LibrationRHSODE45 (in ignoredArg, in x, in ignoredArg, in c2, in c3, in c4)
Compute the time derivative of a state at a collinear libration point,.
function Lissajous (in system, in point, in Ax, in Az, in phiXY, in phiZ, in N)
Compute the lissajous trajectory about a collinear libration point.
function LowEnergyEarthToMoonTransfer (in jD, in r0)
Compute a ballistic lunar capture trajectory from a circular Earth orbit.
function LowEnergyTransferInCRTBP (in r1, in r2, in mu, in orientation)
Calculate a low energy transfer in a CRTBP.
function LowThrustCRTBP_StopFcn (in t, in x, in d)
Stoppping Function for the circular restricted three body problem.
function LowThrustDVToTransfer (in dT, in m0, in thrust, in Isp)
Compute delta-v assuming full thrust applied during all transfer times.
function LowThrustGVE_EventFcn (in t, in y, in k, in ykdes, in tol)
Stopping event function for low thrust GVE sim using ode solver.
function LowThrustGVERHS (in x, in t, in xDes, in thrust, in mDot, in index, in mu)
Right-hand side for low thrust GVE simulation.
function LowThrustRendezvousSim (in el0, in elT, in mass0, in thrust, in Isp, in elemOrder, in mu)
Simulation of low thrust maneuver to rendezvous with target orbit.
function LowThrustTimeToTransfer (in el0, in elT, in aMax, in mu)
Compute the time to transfer each element from initial to target value.
function LyapunovFamily (in Ax, in system, in point)
Generate a family of planar Lyapunov orbits.
function LyapunovInit (in Ax, in system, in point, in doPlot)
Compute a stable initial state for a Lyapunov orbit.
function MarsRot (in jD, in useSec)
Computes the matrix that transforms from ECI to areographic axes.
function MinE4BP (in elements, in dV1Eph, in dtTarg, in et, in muMoon, in p, in jDate)
Minimize the keplerian energy of the final state of a transfer orbit.
function NeptuneAirshipSizing (in h, in m0)
Size an airship to operate with neutral buoyancy on Neptune.
function NeptuneDensity (in h)
Compute the atmosphere density on Neptune given the altitude.
function OrbitLoweringManeuvers (in action, in d, in t, in v)
Lower orbits starting from a hyperbolic orbit.
function OrbitRoundTripTransferTimes (in pA, in pB, in dep, in ret, in N)
Compute transfer start times for a round trip between orbits.
function PatchedConicElements (in vInf, in rP, in mu)
Computes patched conic elements.
function PatchedConicPlanner (in planet, in r, in v, in t, in muC, in pPF)
Helps design patched conic trajectories.
function PeriodicOrbitFromGuess (in yRef, in t0, in tFRef, in mu)
Find a second perpendicular crossing of the x-axis.
function PlanarHelioOptimal (in d, in maxIter, in iterDisp, in thrust0, in phi0)
Compute coplanar optimal trajectory, direct method, with fmincon.
function PlanarHelioOptimalSlidingTime (in d, in maxIter, in iterDisp, in thrust0, in phi0)
Compute optimal trajectory.
function PlanetAlignments (in planet1, in planet2, in jD)
Plots planet alignments fur successive synodic periods.
function PlanetaryAtmDens (in h, in planet)
Computes the atmospheric density for planets, higher fidelity model.
function PlanetaryDistanceToSun (in name, in jD)
Finds the distance to the sun and the solar flux.
function PlanetaryRadiationAndAlbedo (in action, in r, in uS)
Computes the albedo and radiation flux for planets.
function PlanetEnvironment (in rECI, in vECI, in jD, in e)
Compute the environment parameters for a selected planet.
function PlanetHelioPhase (in kPlanet, in jD, in useAlmanac)
Compute the phase angle in the ecliptic plane of a given planet at jD.
function PlanetId (in planet)
Planet id number from name.
function PlanetOpposition (in planets, in jDStart, in n)
Compute Julian Dates for times when two planets are closest with almanac.
function PlanetPositionEMBarycenter (in action, in d)
The position vectors, gravitational parameters and velocity for the planets.
function PlanetPosJPL (in action, in d, in ecl)
Get positions for an array of planets using the JPL ephemeris.
function PlanetTrajectoryPlot (in xP, in jD0, in years, in p1, in p2)
Plots a spacecraft between two planets.
function PlanetTransferLambert (in jD, in dT, in planet1, in planet2, in doPlot)
Generate a Lambert transfer between two planets.
function PlanetWithTerrain (in h, in scale)
Generate vertices and faces for a planet with terrain.
function PlanetWithTerrainPatch (in h, in scale, in p)
Generate vertices and faces for a planet patch with terrain.
function PlotBPlane (in r0, in v0, in rA, in vA)
B-plane plots using HelioToBPlane.
function PlotLET (in elements, in dV1Eph, in det, in jDate, in muMoonMultiplier, in h)
Plot the Low Energy Transfer.
function PlotLET3BP (in elements, in dV1Eph, in det, in jDate, in h)
Plot the Low Energy Transfer, 3 Body Problem.
function PorkChopMin (in dateRange, in tOFRange, in planet1, in planet2, in type, in doPlot)
Search for multiple minima in a porkchop plot.
function PorkChopPlot (in dV, in jDDep, in jDArr, in titleStr)
Create the porkchop plot from the delta-V array and dates.
function PorkChopTOF (in dateRange, in tOFRange, in planetDep, in planetArr, in nDate, in nTOF, in type)
Generate time of flight porkchop plot with TOF vs departure data.
function PorkChopTOFKepler (in dateRange, in tOFRange, in planetDep, in planetArr, in nDate, in nTOF)
Generate time of flight porkchop plot with delta-V per departure data.
function Propagate3BP (in y, in t0, in tF, in jDate, in stmcalc)
Propagate a Sun-Earth 3BP with origin at the Earth system barycenter.
function Propagate4BP (in y, in t0, in tF, in jDate, in stmcalc, in acc, in muMoonMultiplier)
Propagate a Sun-Earth-Moon 4BP with origin at the Earth-Moon barycenter.
function PropagateCRTBP (in y0, in t0, in tF, in mu, in stmcalc)
Propagate an arbitrary CRTBP with origin at the secondary body.
function PropagateCRTBPToPeriapse (in y, in t0, in tF, in mu)
Propagate the CRTBP initial state to the next perigee.
function PropagateNBody (in x0, in t, in mass, in name, in tol, in eps)
Propagate n-bodies in an n-body problem.
function ReadAsteroidDatabase (in a, in file)
Read in an asteroid database file and return elements.
function RHS2DAnglePolarOrbit (in x, in ignoredArg, in d)
RHS for 2D polar orbit, angle formulation.
function RHS2DCylindricalOrbit (in x, in ignoredArg, in d)
RHS for constant thrust in cylindrical coordinates.
function RHSAlphaCentauriMission (in x, in t, in d)
Simple dynamical model for a flight to Alpha-Centauri.
function RHSCRTBP (in t, in y, in mu)
Compute the RHS of the CRTBP equations of motion.
function RHSHelioWithPlanets (in x, in t, in d)
Right hand side for a heliocentric system with a thruster.
function RHSMarsOrbit (in x, in ignoredArg, in mu)
Right hand side for a Mars orbit simulation.
function RotPuls2J2000 (in stateIn, in primary, in muPrimary)
Transform a state vector from a rotating pulsating reference frame to J2000.
function Simulate2DApproach (in t, in x0, in phi, in a, in d, in name)
Simulate a 2D planetary approach.
function SimulatePlanarHelioTrajectory (in mD, in mF, in thrust, in uE, in r0, in rT, in mu, in phi, in t)
Simulate a planar heliocentric trajectory.
function SolarSysJPL (in id, in jD, in ecl)
Computes the JPL position vectors of the planets as a function of time.
function SolarSysState (in d, in jD)
Computes planet heliocentric states for a range of dates.
function SphereOfInfluenceHelio (in k)
Computes the ratio of the sphere of influence for interplanetary.
function SynodicPlanets (in planet1, in planet2, in jD)
Computes the synodic period from planets.
function Targeting3BP2 (in elements, in dV1Eph, in dt, in et, in muMoon, in jDate)
Transfer a CRTBP LET to the restricted 3 body, non-planar problem.
function Targeting4BP (in elements, in dV1Eph, in dtTarg, in et, in p, in jDate, in muMoonMultiplier, in muPlanet)
Transfer a LET from the restricted 3BP to the Sun/Planet/Moon 4BP.
function TitanAtmosphere (in h)
Titan density model from stored data.
function TrajectoryBetweenTwoPlanets (in jD0, in planet1, in planet2, in years, in n, in opts, in nRSim)
Optimal 3D trajectory between two planets, fixed time (fmincon)
function TrueAnomalyStartHyperbola (in a, in e, in t, in nu2, in mu)
Starting true anomaly to reach a true anomaly in time t.
function TwoDEscape (in mu, in rI, in uE, in thrust, in m0, in mF, in rB, in planet)
Simulate a low thrust departure from a planet.
function UranusAirshipSizing (in h, in m0)
Size an airship to operate with neutral buoyancy on Uranus.
function V0FromJacobiConstant (in x0, in j, in mu)
Calculate an initial velocity from the jacobi constant.
Function Documentation
AlphaCentauriSystem()
function AlphaCentauriSystem (in jD)
Includes stars A, B and a hyopthetical planet around A.
Type AlphaCentauriSystem for a demo.
Form
 r = AlphaCentauriSystem( jD )
Inputs
 jD             (1,:)    Julian date
Outputs
 r              (9,:)     [rA;rB;rP]. rA: position vector of Alpha
                         Centauri A in km. rB: Position vector of Alpha
                         Centauri B in km. rP: Position vector of a
                         hypothetical planet orbiting at 1 AU around
                         Alpha Centauri A, in km.
References AlphaCentauriSystem(), and(), AssignColors(), Constant(), Demo(), DupVect(), JD2000(), length(), NewFig(), set(), square(), TitleS(), Unit(), vector(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by AlphaCentauriSystem(), and RHSAlphaCentauriMission().
ApophisOrbit()
function ApophisOrbit ()
Utilizes an ephemeris point from 2009.
Form
 [elA, rA, vA, jD] = ApophisOrbit
Inputs
 None
Outputs
 elA (1,6) [a i Omega omega e M]
 rA  (3,1) Heliocentric position (km)
 vA  (3,1) Heliocentric velocity (km)
 jD  (1,1) Julian day number of epoch
References and(), ApophisOrbit(), Constant(), Date2JD(), RV2El(), and RVFromKepler().
Referenced by ApophisOrbit(), and PorkChopTOFKepler().
ApproachConst2D()
function ApproachConst2D (in u, in d, in t, in x0, in xF)
The constraint is the state. The function integrates the trajectory to find the values.
Form
 [cIn, cEq] = ApproachConst2D( u, d, t, x0, xF )
Inputs
 u     (2,:) [phi;a]
 d     (.)   Data structure describing spacecraft model
 t     (1,:) Time steps
 x0    (.)   Initial state
 xF    (.)   Final state
Outputs
 cIn   (1,1)    Inequality contraints
 cEq   (3,1)    Equality constraints
References ApproachConst2D(), length(), Mag(), RHS2DAnglePolarOrbit(), and RK4().
Referenced by ApproachConst2D().
ApproachConst2DIneq()
function ApproachConst2DIneq (in u, in d, in t, in x0, in xF)
The constraint is the state. The function integrates the trajectory to find the values.
Form
 [cIn, cEq] = ApproachConst2DIneq( u, d, t, x0, xF )
Inputs
 u     (2,:) [phi;a]
 d     (.)   Data structure describing spacecraft model
             .phi   angle
             .a     magnitude
 t     (1,:) Time steps
 x0    (.)   Initial state
 xF    (.)   Final state
Outputs
 cIn   (1,1)    Inequality contraints
 cEq   (3,1)    Equality constraints
References ApproachConst2DIneq(), length(), Mag(), RHS2DAnglePolarOrbit(), and RK4().
Referenced by ApproachConst2DIneq().
ApproachCost2D()
function ApproachCost2D (in u)
The cost is the total acceleration for the maneuver. This is computed from the decision variable.
Form
 cost = ApproachCost2D( u, ~ )
Inputs
 u       (2,:)   [phi;a]
Outputs
 cost    (1,1)   Total acceleration
References abs(), and ApproachCost2D().
Referenced by ApproachCost2D().
ApproachCost2DMag()
function ApproachCost2DMag (in u)
The cost is the total acceleration for the maneuver. This is computed from the decision variable.
Form
 cost = ApproachCost2DMag( u, ~ )
Inputs
 u       (2,:)   [phi;a]
Outputs
 cost    (1,1)   Total acceleration
References ApproachCost2DMag(), and Mag().
Referenced by ApproachCost2DMag().
AsteroidProperties()
function AsteroidProperties (in name)
Form
 [gm, semi, naif] = AsteroidProperties( name )
Inputs
 name         (1,:) Asteroid, one of Ceres, Eros, Apophis
Outputs
 gM           (1,1) Gravitational constant (km^3/s^2)
 semi         (1,3) Ellipsoidal semi-major axes (km)
 naif         (1,1) NAIF code
References AsteroidProperties(), and Demo().
Referenced by AsteroidProperties().
AtmDensMars2()
function AtmDensMars2 (in h)
 For h > 100 km the temperature is kept constant.
 Type AtmDensMars2 for a demo.
Form
 [rho, t, p] = AtmDensMars2( h )
Inputs
 h          (1,:)        Altitude (km)
Outputs
 rho        (1,:)        Atmospheric Density (kg/m^3)
 t          (1,:)        Temperature (deg-K)
 p          (1,:)        Pressure (N/m^2)
Reference: http://www.grc.nasa.gov/WWW/K-12/airplane/atmosmrm.html
References Altitude(), AtmDensMars2(), Demo(), and Pressure().
Referenced by AtmDensMars2(), and PlanetaryAtmDens().
AtmDensNeptune()
function AtmDensNeptune (in h)
Valid from 0 to 1400 km.
 Type AtmDensNeptune for demo.
Form
 rho = AtmDensNeptune( h )
Inputs
 h  (1,:) Altitude (km)
Outputs
 rho    (1,:) Atmospheric Density (kg/m^3)
References: C. G. Justus, Aleta Duvall, Vernon W. Keller, ATMOSPHERIC MODELS FOR AEROENTRY AND AEROASSIST
References AtmDensNeptune().
Referenced by AtmDensNeptune(), and PlanetaryAtmDens().
AtmDensTitan()
function AtmDensTitan (in h)
Type AtmDensTitan for a demo.
Form
 [rho, t] = AtmDensTitan( h )
Inputs
 h          (1,:)   Altitude (km)
Outputs
 rho        (1,:)   Atmospheric Density (kg/m^3)
 t          (1,:)   Temperature (deg-K)
Reference: J. H. Waite, Jr., J. M. Bell, R. Lorenz, R. Achterberg, and F. M. Flasar, "A New Titan Atmospheric Model for Mission Engineering Applications," 43rd Lunar and Planetary Science Conference, 2012.
References Altitude(), and(), AtmDensTitan(), Demo(), and PlotDoubleYAxis().
Referenced by AtmDensTitan().
AtmDensUranus()
function AtmDensUranus (in h)
Form
 rho = AtmDensUranus( h )
Inputs
 h      (1,:)   Altitude (km)
Outputs
 rho    (1,:)   Density (kg/m^3)
Reference: NASA Uranus Fact Sheet https://nssdc.gsfc.nasa.gov/planetary/factsheet/uranusfact.html
References Altitude(), and(), AtmDensUranus(), Demo(), MolWt2R(), and Plot2D().
Referenced by AtmDensUranus(), and PlanetaryAtmDens().
BDipoleJupiter()
function BDipoleJupiter (in r, in jD)
 The output is in Jupiter centric inertial coordinates.
 Type BDipoleJupiter for an example in a 200,000 km orbit in the
 Jupiter equatorial plane.
Form
 b = BDipoleJupiter( r, jD )
Inputs
 r           (3,:)   Position vector in the ECI frame
 jD          (1,:)   Julian days
Outputs
 b           (3,:)   Magnetic field (T)
Reference: K. Khurana, M. Kivelson, V. Vasyliunas, N. Krupp, J. Woch, b. Mauk, W. Kurth, "The Configuration of Jupiter's Magnetosphere".
BDipolePlanet()
function BDipolePlanet (in r, in jD, in planet)
This function includes all planets with magnetic fields. It calls BDipole if planet is not entered or it is the Earth.
Type BDipolePlanet for a demonstration of a spacecraft around jupiter
Form
 b = BDipolePlanet( r, jD, planet )
Inputs
 r           (3,:)   Position vector in the ECI frame (km)
 jD          (1,:)   Julian date
 planet      (1,:)   Planet name (not case sensitive)
Outputs
 b           (3,:)   Magnetic field in the ECI frame (T)
Reference: https://nssdc.gsfc.nasa.gov/planetary/factsheet/
References and(), BDipole(), BDipolePlanet(), Constant(), CosD(), Date2JD(), Demo(), Dipole(), ECIToPlanet(), Mag(), Plot2D(), RVOrbGen(), SinD(), Unit(), vector(), and zeros().
Referenced by BDipolePlanet().
BilinearTangentAltitude()
function BilinearTangentAltitude (in d, in t)
We assume the vehicle is constant and the final time is known. Assumes constant acceleration. The model is in a cartesian frame with gravity constant and in the negative y direction.
The boundary conditions are for the x velocity to equal the orbital velocity and the y velocity to be zero.
If the ratio of rocket acceleration to gravity is too low you cannot achieve a circular orbit. In that case the cost will be high. The result will be a non-zero radial velocity. This will depend on the initial x and y velocities.
Type BilinearTangentAltitude for a demo for an upper stage with a rocket engine capable of 1.5 g.
This routine uses fminsearchbnd which is freely available on the web.
Form
 [beta, yF, cost] = BilinearTangentAltitude( d, t )
Inputs
 d       (.)    Data structure
                 .mu     (1,1) Gravitational constant
                 .r      (1,1) Initial radius
                 .u      (1,1) Initial x velocity
                 .v      (1,1) Initial y velocity
                 .thrust (1,1) Engine thrust
                 .mass   (1,1) Mass
                 .tF     (1,1) End time for the burn
                 .opt     (.)   fminsearch options
 t       (1,:)  Time vector for beta
Outputs
 beta    (1,:)  Thrust angle from horizontal
 yF      (1,1) Altitude
 cost    (1,1) Final cost
Reference: Arthur E. Bryson, Jr., Y. C. Ho, "Applied Optimal Control: Optimization, Estimation, and Control," Orbit, pp. 83-86.
References Altitude(), and(), BilinearTangentAltitude(), Demo(), MassEquivalentDV(), RHS(), and vector().
Referenced by BilinearTangentAltitude().
BilinearTangentLaw()
function BilinearTangentLaw (in u, in g, in a, in h, in n, in opt, in dT)
Assumes constant acceleration of gravity and constant engine acceleration. For applicable landing or takeoff problems the first is true, the latter is usually not due to the decrease in mass of the vehicle. The thrust angle is from the horizontal and g is along the vertical. It uses fminsearch to find the optimal angles.
The launch or landing vector may not be vertical. Units may be of any type as long as they are consistent.
Type BilinearTangentLaw for a demo from the reference.
Form
 BilinearTangentLaw; % demo
 [beta, t] = BilinearTangentLaw( u, g, a, h, n, opt, dT )
Inputs
 u       (1,1)  Final or initial velocity
 g       (1,1)  Acceleration of gravity
 a       (1,1)  Engine acceleration
 h       (1,1)  Final or initial altitude
 n       (1,1)  Number of steps
 opt     (1,:)  fminsearch options
 dT      (1,1)  Time step in place of n
Outputs
 beta    (1,n)  Thrust angle from horizontal
 t       (1,n)  Corresponding time vector
 tMin    (1,1) Minimum time
               If there are no outputs, generates a plot.
Reference: Arthur E. Bryson, Jr., Y. C. Ho, "Applied Optimal Control: Optimization, Estimation, and Control," Orbit, pp. 83-86.
References abs(), and(), BilinearTangentLaw(), Demo(), isempty(), Plot2D(), RHS(), and vector().
Referenced by BilinearTangentLaw(), and LandingControlBilinear().
BilinearTangentVector()
function BilinearTangentVector (in r, in v, in g, in a, in h, in n, in opt, in type)
 Generates a vector given an orbit's r and v vector.
 r and v are used to determine the orbit plane.
 Type BilinearTangentVector for a demo of a lunar takeoff.
 Units may be of any type as long as they are consistent.
 Since Version 11
Form
 [w, t, q] = BilinearTangentVector( r, v, g, a, h, n, opt, type )
Inputs
 r       (3,1)  Orbit vector ECI
 v       (3,1)   Orbit velocity ECI
 g       (1,1)  Surface acceleration
 a       (1,1)  Engine acceleration
 h       (1,1)  Final or initial altitude
 n       (1,1)  Number of steps
 opt     (1,:)  fminsearch options
 type    (1,1) 0 = takeoff, 1 = landing
Outputs
 w       (3,n)  Thrust vector ECI
 t       (1,n)  Corresponding time vector
 q       (4,n)  Quaternion from ECI to the thrust vector
References Unit(), and vector().
C3ToV()
function C3ToV (in c3, in r, in mu)
C_3 is a measure of the excess specific energy over that required to just barely escape from a massive body. C3 is twice the specific orbital energy of the escaping object. Type C3ToV for a heliocentric demo.
Form
 v = C3ToV( c3, r, mu )
Inputs
 c3      (1,:) C3 characteristic energy (km^2/s^2)
 r       (1,1) Distance from sun (km)
 mu      (1,1) Gravitational parameter (km^3/sec^2), default sun
Outputs
 v       (1,:) Heliocentric velocity (km/s)
References C3ToV(), Constant(), and Plot2D().
Referenced by C3ToV().
CheckForOptimizationToolbox()
function CheckForOptimizationToolbox ()
Performs a check to see if the working version of MATLAB contains the Optimization Toolbox. If it does not exist or has not been installed an error message will occur.
Form
 CheckForOptimizationToolbox
Inputs
 none
Outputs
 none
References CheckForOptimizationToolbox().
Referenced by CheckForOptimizationToolbox(), LowEnergyEarthToMoonTransfer(), MinE4BP(), PeriodicOrbitFromGuess(), Targeting3BP2(), and Targeting4BP().
CRTBP2kms()
function CRTBP2kms (in stateIn, in distanceUnit, in muPrimary, in muSecondary)
Scales coordinates from Jacobi coordinates of the Circular Restricted Three Body Problem to units of kilometers and seconds
Form
 [stateOut,sec2tu] = CRTBP2kms(stateIn,distanceUnit,muPrimary,muSecondary);
Inputs
 stateIn       (6,1)  Initial state vector
 distanceUnit   (1,1)   Distance between Primary and Secondary bodies (km)
 muPrimary     (1,1)   Gravitational Parameter of Primary body
 muSecondary    (1,1)   Gravitational Parameter of Secondary body
Outputs
 stateOut       (1,6)  Output state vector
 sec2tu        (1,1)   Scaling factor for time
References and(), Constant(), CRTBP2kms(), Demo(), Parameter(), and vector().
Referenced by CRTBP2kms(), and LowEnergyEarthToMoonTransfer().
CRTBPJacobi()
function CRTBPJacobi (in x, in mu)
Centered at the barycenter.
Form
 C = CRTBPJacobi( x, mu )
Inputs
 x            (6,1)     The state vector [r;v]
 mu           (1,1)     Non-dimensional mass parameter.
                         Smaller mass divided by total mass of system.
Outputs
 C            (1,1)     Jacobi constant of integration
References CRTBPJacobi(), and vector().
Referenced by CRTBPJacobi().
CRTBPJacobiConstant()
function CRTBPJacobiConstant (in y, in mu)
The default three-body problem is the Earth, Moon, and sun. Type CRTBPJacobiConstant for a demo with two identical vectors.
Form
 j = CRTBPJacobiConstant(y,mu)
Inputs
 y   (6,n)  State vector in scaled coordinates [r;v]
 mu (1,1)   CRTBP mass parameter
Outputs
 j   (n,1)  Jacobi constant
References and(), Constant(), CRTBPJacobiConstant(), Demo(), and vector().
Referenced by CRTBPJacobiConstant(), IteratePeriodicOrbit(), LETGuess(), MinE4BP(), and V0FromJacobiConstant().
CRTBPLinearSystem()
function CRTBPLinearSystem (in x, in mu)
Computes the matrix M such that
 x = [r; v]
 M = [ 0     I;
 ddU   K]
 xDot = M*x
which is:
 rDot = v
 vDot = ddU*r + K*v
Type CRTBPLinarSystem for a demo.
Form
 M = CRTBPLinearSystem( x, mu )
Inputs
 x         (6,1)   Position and velocity in CRTBP system [r; v]
 mu        (1,1)   Mass parameter
Outputs
 M         (6,6)   Linear system state space matrix
References and(), CRTBPLinearSystem(), and zeros().
Referenced by CRTBPLinearSystem().
CRTBPRHS()
function CRTBPRHS (in x, in t, in mu)
 X is along primary - secondary body line
 Z is normal to plane of motion
 Y completes right-hand system
 Since version 10.
Form
 xDot = CRTBPRHS( x, t, mu )
Inputs
 x            (6,1)     The state vector [r;v]
 t            (1,1)     Time (unused)
 mu           (1,1)     Non-dimensional mass parameter.
                         Smaller mass divided by total mass of system.
Outputs
 xDot         (6,1)     The derivative of the state vector
References CRTBPRHS(), and vector().
Referenced by CRTBPRHS(), EarthEscape(), EarthOrbToHelioOrb(), PlotEMTraj(), and PlotSEMTraj().
EarthEscape()
function EarthEscape (in el0, in jD, in days, in gRatio)
Simulates the circular restricted three-body problem.
Form
 s = EarthEscape( el0, jD, days, gRatio )
Inputs
 el0     (1,6)   Earth orbit elements
 jD      (1,1)   Reference Julian date
 days    (1,1)   Number of days to run simulation
 gRatio  (1,1)   Ratio of Earth/Sun gravity at which to stop sim
Outputs
 s        (.)    Data structure with fields:
                   s.crtbp   CRTBP system data
                   s.time    Time vector (sec)
                   s.rECI    ECI position
                   s.vECI    ECI velocity
                   s.rHE     Helio centric position (xy=ecliptic)
                   s.vHE     Helio centric velocity
                   s.gEarth  Gravitational acceleration from Earth
                   s.gSun    Gravitational acceleration from Sun
                   s.vEsc    Theoretical escape velocity magnitude
                   s.dVEscape Delta-v vector for escape from init orbit
References and(), CEcl2Eq(), CEcl2SER(), CRTBPRHS(), Date2JD(), Demo(), EarthEscape(), El2RV(), isempty(), length(), Mag(), RHS(), SunEarthMoonSystemConstants(), Trajectory(), Unit(), vector(), VEscape(), and zeros().
Referenced by EarthEscape().
EarthHelioState()
function EarthHelioState (in jD)
Uses SunV1 and a first difference for velocity.
Form
 [rHE, vHE] = EarthHelioState( jD )
Inputs
 jD          (1,1)   Julian date
Outputs
 r           (3,1)  Position heliocentric
 v           (3,1)  Velocity heliocentric
References and(), CEcl2Eq(), Date2JD(), EarthHelioState(), and SunV1().
Referenced by EarthHelioState().
EarthOrbToHelioOrb()
function EarthOrbToHelioOrb (in jD0, in elEarth, in SCParams)
 Performs a simulation of the spiral out from Earth using ode113 and
 FCRTBPRHS, and stops once the sun gravity acceleration dominates that
 of Earth.
 Since version 2014.1
Form
 [elHelio, rSEMI, vSEMI, t1, mass] = EarthOrbToHelioOrb( jD0, elEarth, SCParams)
Inputs
 jD0           (1,:)     Julian Date
 elEarth       (1,6)     Initial orbital elements in the ECI frame
 SCParams       (.)      Design parameters for the spacecraft
   .mass0                     Mass             (kg)
   .thrust                    Thrust           (kN)
   .Isp                       Specific impulse (sec)
   .uE                        Exhaust velocity (km/s)
Outputs
 elHelio       (:,6)     Orbital elements in the heliocentric frame
 rSEMI         (3,:)     Position vector in the heliocentric frame
 vSEMI         (3,:)     Velocity vector in the heliocentric frame
 t1            (1,:)     Time vector
See also
SunEarthMoonSystemConstants, TransformECIToSEMR,
CRTBPRHS, FCRTBPRHS, LowThrustCRTBP_StopFcn
References and(), CRTBPRHS(), Date2JD(), Demo(), EarthOrbToHelioOrb(), El2RV(), FCRTBPRHS(), length(), LowThrustCRTBP_StopFcn(), RV2El(), SEMRToSEMI(), SunEarthMoonSystemConstants(), TransformECIToSEMR(), Unit(), vector(), and zeros().
Referenced by EarthOrbToHelioOrb().
ECIToSunEarthRot()
function ECIToSunEarthRot (in jD, in JPL)
 The coordinate frame is +x pointing at the Earth along
 the Sun-Earth line. +z normal to the Sun-Earth (ecliptic) plane
 and +y completing the set.
 Computes the plane by looking at the sun vector at jD(k) and then 1 day
 later. By default, "SunV1" is used to get the sun vector. If a second
 argument is entered, the JPL ephemerides are used.
 Type ECIToSunEarthRot for a demo.
 Since version 11.
Form
 m = ECIToSunEarthRot( jD, JPL )
Inputs
 jD             (1,:)      Julian date (days)
 JPL            (1,1)      Optional. Enter this input (any value) to use
                           the JPL ephemerides. Otherwise, SunV1 is used.
Outputs
 m              {:}        Rotation matrices
 z              (3,:)      Rotation axes
References and(), ECIToSunEarthRot(), get(), set(), SunV1(), and vector().
Referenced by ECIToSunEarthRot().
EclipseHelio()
function EclipseHelio (in r, in rP, in planetID, in jD)
You must initialize the JPL ephemerides prior to using this function. For example, with the earth and moon.
 PlanetPosJPL( 'initialize', [3 10] );
Form
 nEclipse = EclipseHelio( r, rP, planetID )
 nEclipse = EclipseHelio( r, [], planetID, jD )
Inputs
 r         (3,1) Position vector of spacecraft (km)
 rP        (3,:) Heliocentric planet positions
 planetID  (1,:) Planet IDs corresponding to the output of PlanetPosJPL
 jD        (1,:) Julian dates
Outputs
 nEclipse   (1,:) Eclipse fraction
References and(), Eclipse(), isempty(), PlanetPosJPL(), and vector().
EclipticInjectionPlane()
function EclipticInjectionPlane (in jD, in vEcl)
The parking orbit is defined in the ECI frame. The injection velocity is defined in the ecliptic frame.
Type EclipticInjectionPlane for a demo.
Form
 [rAAN, inc] = EclipticInjectionPlane( jD, v )
Inputs
 jD      (1,1) Julian date of injection
 vEcl    (3,1) Velocity vector in the ecliptic frame (xy ecliptic plane)
Outputs
 rAAN     (1,1) Right ascension of the ascending node (rad)
 inc      (1,1) Orbit inclination (rad)
 dVEq     (3,1) Earth-relative velocity in ECI (km/s)
 nEq      (3,1) Orbit-normal vector for parking orbit
References and(), CEcl2Eq(), Cross(), Demo(), EclipticInjectionPlane(), Mag(), NewFig(), OrbNEl(), RVOrbGen(), set(), SunV1(), Unit(), and vector().
Referenced by EclipticInjectionPlane().
EnergyWRTMoon()
function EnergyWRTMoon (in t, in y, in muMoon, in jDate)
This calls InterpolateState and PlanetPositionEMBarycenter that must be initialized prior to use. For example:
InterpolateState([],[],'bin2000.405') PlanetPositionEMBarycenter('initialize',[0 3 10]); EnergyWRTMoon(0, zeros(6,1), 4.9028e+03, JD2000);
You must call PlanetPositionEMBarycenter with [0 3 10] on initialize. (Sun, Earth Moon)
Type EnergyWRTMoon for a demo.
Form
 e = EnergyWRTMoon( t, y, muMoon, jDate )
Inputs
 t       (1,1)   Seconds after epoch (s)
 y       (6,1)   State vector in Earth/Moon Barycentered frame
 muMoon  (1,1)   Gravitational Parameter of the moon
 jDate   (1,1)   Julian date
Outputs
 e       (1,1)   Keplerian energy (MJ)
References and(), Demo(), Energy(), EnergyWRTMoon(), InterpolateState(), JD2000(), Parameter(), PlanetPositionEMBarycenter(), and vector().
Referenced by EnergyWRTMoon(), and MinE4BP().
FCRTBPRHS()
function FCRTBPRHS (in x, in t, in mu, in a, in uE)
The state includes mass.
Form
 xDot = FCRTBPRHS( x, t, mu, a, uE )
Inputs
 x            (7,1)     The state vector [r;v;m]
 t            (1,1)     Time (unused)
 mu           (1,1)     Non-dimensional mass parameter.
                         Smaller mass divided by total mass of system.
 a            (3,1)     Acceleration applied to body in rotating frame
 uE           (1,1)     Exhaust velocity (non-dimensional)
Outputs
 xDot         (7,1)     The derivative of the state vector
References FCRTBPRHS(), and vector().
Referenced by EarthOrbToHelioOrb(), FCRTBPRHS(), and L2OrbitSim().
FEarthMoon()
function FEarthMoon (in x, in t, in jD, in muMoon, in muEarth)
Uses MoonV1 to locate the moon. Point mass model for the Earth and perturbation model for the moon using APlanet.
Form
 xDot = FEarthMoon( x, t, jD, muMoon, muEarth )
Inputs
 x           (6,1)   [r;v]
 t           (1,1)   Time
 jD          (1,1)   Julian date
 muMoon      (1,1)   Gravitational parameter for the moon
 muEarth     (1,1)   Gravitational parameter for the earth
Outputs
 xDot        (6,1)   State derivative
References and(), APlanet(), FEarthMoon(), Mag(), and MoonV1().
Referenced by FEarthMoon().
FEarthMoonSun()
function FEarthMoonSun (in t, in x, in flag, in d)
Includes a point mass sun model. Uses MoonV1 and SunV1 for ephemeris, EarthRot, MoonRot, and AGravityC for the gravity models, and APlanet for the sun perturbation.
Note that MoonV1 and SunV1 are low accuracy ephemeris models. For actual mission planning you will need to use more accurate solar and lunar ephemerides. In addition, you may need more accurate moon and earth rotation models. These models are suitable for mission design since the required delta-Vs won't change much but timing will. In addition, if you compare results using this model to models with different ephemerides, the results will not match.
Designed to be called by ode113. See also EarthMoonSunSim.
Form
 varargout = FEarthMoonSun( t, x, flag, d )
Inputs
 t                      Time (sec)
 x             (:,1)    The state vector [r;v]
 d              (.)     Data structure
                        .mass  (1,1) Mass
                        .force (3,1) External force
                        .earth (1,1)
                                    .mu (1.1) Gravitational potential
                                    .nZ (1.1) Number of zonal harmonics
                                    .nT (1.1) Number of tesseral harmonics
                                    .s  (:,:) S terms
                                    .c  (:,:) C terms
                                    .j  (:)   m = 0 terms
                                    .a  (1.1) Planet radius
                        .moon (1,1)
                                    .mu (1.1) Gravitational potential
                                    .nZ (1.1) Number of zonal harmonics
                                    .nT (1.1) Number of tesseral harmonics
                                    .s  (:,:) S terms
                                    .c  (:,:) C terms
                                    .j  (1,:) m = 0 terms
                                    .a  (1.1) Planet radius
                        .jDStart
                        .muSun
Outputs
 vargout          (:,:)     Depends on flag
References AGravityC(), and(), APlanet(), EarthRot(), MoonRot(), MoonV1(), and SunV1().
Referenced by FSailEarthMoon(), and FSailEarthSun().
FHel()
function FHel (in x, in t, in d)
 Since version 2.
Form
 [xDot, thrust, power] = FHel( x, t, d )
Inputs
 x            (5,1)     The state vector [x;y;xDot;yDot;m]
 t                      Time
 d            (:)       Data structure
Outputs
 xDot         (5,1)     The derivative of the state vector
 thrust       (1,1)     The thrust
 power        (1,1)     The available power
References FHel(), and vector().
Referenced by FHel().
FindDepartureDate()
function FindDepartureDate (in jD0, in planet1, in planet2, in years)
This will scan for one orbit of the departure planet (one of it's years) and find date with the best geometry given the desired duration. This is when the relative distance between the planets at the arrival date is the greatest, i.e. opposing sides of the orbits. This is most suitable for planets far from Earth where the trajectory approaches a straight line.
For the struct form of planet2, this will calculate updated orbital elements for the new epoch using the gravitational parameter of the sun.
Form
 [jD,planet2] = FindDepartureDate( jD0, planet1, planet2, years )
Inputs
 jD0       (1,1)  Start Julian Date
 planet1   (1,1)  Id of departure planet (1-9)
 planet2    (1,1)  Id of arrival planet (1-9) or data structure
                  .name (1,:) Name
                  .el   (1,6) Orbital elements - epoch must be jD0
 years      (1,1)  Mission duration (years)
Outputs
 jD        (1,1)  Updated Julian Date
 planet2    (.)   If planet2 is a structure, updated elements
                  .name (1,:) Name
                  .el   (1,6) Orbital elements - new epoch of jD
References TrajectoryBetweenTwoPlanets().
Referenced by TrajectoryBetweenTwoPlanets().
FlybyHyperbola()
function FlybyHyperbola (in r, in v, in rP, in mu)
Form
 b = FlybyHyperbola( r, v, rP, mu )
Inputs
 r   (1,1)   Distance
 v   (1,1)   Velocity
 rP (1,:)   Perigee
 mu (1,1)   Mu
Outputs
 b   (1,1)  Datastructure
           .a  (1,1) semimajor axis
            .e  (1,1) eccentricity
            .rP (1,1) perigee
            .vP (1,1) perigee velocity
            .t  (1,1) Time to r
            .h  (1,1) Hyperbolic anomaly at r
References Demo(), FlybyHyperbola(), RV2A(), TimeLabl(), and VOrbit().
Referenced by FlybyHyperbola().
FSolarSail()
function FSolarSail (in t, in x, in flag, in d)
Form
 vargout = FSolarSail( t, x, flag, d )
Inputs
 t                      Time
 x             (6,1)    The state vector [r;v]
 flag          (1,:)    Flags for ode113
 d             (1,1)    Data structure
                        .jDStart   (1,1) Julian date of simulation start
                        .muSun     (1,1) Central body gravitational parameter
                        .sail      (1,1) Sail data structure
                                         .normal (3,1) Sail normal
                                         .area   (1,1) Sail area
                                         .sigmaT (1,1) Sail transparency
                                         .sigmaA (1,1) Sail absorptivity
                                         .sigmaD (1,1) Sail diffusivity
                                         .sigmaS (1,1) Sail specular reflection
                        .mass      (1,1) Spacecraft mass
                        .planetsOn (1,1) 1 if planets are on
Outputs
 xDot          (6,1)     The state vector derivative d[r;v]/dt
References vector().
FuelTimeOptimalAccel()
function FuelTimeOptimalAccel (in d, in uE, in thrust)
 Type FuelTimeOptimalAccel for a demo
 This function requires the function fminsearchbnd
 http://www.mathworks.com/matlabcentral/fileexchange/8277
 which is available for free.
 Since version 2014.1
Form
 [thrust, uE, mFuel, time] = FuelTimeOptimalAccel( d, uE, thrust )
Inputs
 d       (1,1) Data structure
                 .sigmaP (1,1) Specific power
                 .sigmaF (1,1) Structural fraction
                 .eff    (1,1) Engine efficiency
                 .massP  (1,1) Mass payload
                 .u      (1,1) Final velocity
                 .w      (1,1) Time weight
 uE      (1,1) Initial guess for uE (km/s)
 thrust  (1,1) Initial guess for thrust (N)
Outputs
 q  (1,1) Data structure
           .uE        (1,1) Exhaust velocity
           .thrust    (1,1) Thrust (N)
           .time      (1,1) Acceleration time (s)
           .massPower (1,1) Power system mass (kg)
           .massFuel  (1,1) Fuel mass (kg)
           .massTotal (1,1) Total mass (kg)
References Demo(), FuelTimeOptimalAccel(), length(), and zeros().
Referenced by FuelTimeOptimalAccel().
GalileanSatelliteOrbits()
function GalileanSatelliteOrbits (in jD)
Uses orbital elements which ignores all perturbations. The satellites are 'Io' 'Europa' 'Ganymede' 'Callisto'. The outputs are
 r[Io 3xn; Europa 3xn; Ganymeded 3xn; Callisto 3xn];
 v[Io 3xn; Europa 3xn; Ganymeded 3xn; Callisto 3xn];
Form
 [r,v,name] = GalileanSatelliteOrbits( jD )
Inputs
 jD           (1,:) Julian day numbers
Outputs
 r            (12,:) [x;y;z;x;y;z...]
 v            (12,:) [x;y;z;x;y;z...]
 name         {4}    Corresponding name
GVEGuidance()
function GVEGuidance (in el, in elT, in index)
 For use with a low-thrust orbit transfer, for changing one Keplerian
 element at a time.
 Since version 2014.1
Form
 uRSW = GVEGuidance( el, elT, index )
Inputs
 el            (1,6)    Orbital elements [a,i,W,w,e,M] in radians
                        (distance units arbitrary). Can also accept
                        dimensions (6,1)
 elT           (1,6)    Target orbital elements. Can also accept
                        dimensions (6,1)
 index         (1,1)    Index of element to change, in the order above,
                        from 1 to 5.
Outputs
 uRSW          (3,1)    Unit thrust vector, with
                        x,y,z components in the radial, along-track, and
                        orbit-normal (or cross-track) directions,
                        respectively.
References and(), Cross(), Demo(), El2RV(), GVEGuidance(), M2Nu(), OrbElemDiff(), Unit(), and vector().
Referenced by GVEGuidance(), LowThrustGVERHS(), and LowThrustTimeToTransfer().
HALOFamily()
function HALOFamily (in Ax, in Az, in system, in point)
Type HALOFamily for a demo.
 Since version 11.
Form
 ds = HALOFamily( Ax, Az, system, point );
Inputs
 Ax      (1,n)   Amplitudes of oscillation in the x direction (AU)
 Az      (1,n)   Amplitudes of oscillation in the z direction (AU)
 system   (:)    String name of system: 'SEM' or 'EM'
 point   (1,1)   Which libration point: L1 (1) or L2 (2)
Outputs
 ds       (.)    Data structure array with system constants and fields:
                   .point
                   .x0
                   .x0f
                   .tf
                   .x0Hist
                   .t
                   .xSTM
                   .x
References: Online course notes, Prof. J.D. Mireles James, Rutgers University. http://www.math.rutgers.edu/~jmireles/notes.html
References and(), Demo(), HALOFamily(), HALOInit(), HALOPlot(), length(), and zeros().
Referenced by HALOFamily().
HALOInit()
function HALOInit (in Ax, in Az, in system, in point, in d0, in doPlot)
Type HALOInit for a demo.
 Since version 11.
Form
 d = HALOInit( Ax,Az, system, point, d0, doPlot );
Inputs
 Ax      (1,1)   Amplitude of oscillation in the x direction (AU)
 Az      (1,1)   Amplitude of oscillation in the z direction (AU)
 system   (:)    String name of system: 'SEM' or 'EM'
 point   (1,1)   Which libration point: L1 (1) or L2 (2)
 d0      (.)     Data structure output from previous call. Optional.
 doPlot  (1,1)   Flag to plot (1) or not (0)
Outputs
 d       (.)     Data structure output with system constants and fields:
                   .point
                   .x0
                   .x0f
                   .tf
                   .x0Hist
                   .t
                   .xSTM
                   .x
References: Online course notes, Prof. J.D. Mireles James, Rutgers University. http://www.math.rutgers.edu/~jmireles/notes.html
References and(), Demo(), HALOInit(), and isempty().
Referenced by HALOFamily(), HALOInit(), HALOPlot(), and LyapunovFamily().
HALOPlot()
function HALOPlot (in d, in type, in f, in plots)
Type HALOPlot for a demo which loads SEML2OrbitData.mat
Form
 f = HALOPlot( d, type, f, plots )
Inputs
 d       (.)     Data structure output from HALOInit
 type    (:)     Type of plot:
                     'time' = time history
                     'traj' = spatial trajectory(s)
 f       (1,1)   Handle to figure to add plot(s) to. Optional.
 plots   {:}     Cell array, one or more frames to plot (traj type only)
                   Options are: xy, yz, xz, xyz
Outputs
 f       (1,1)   Handle to figure.
References HALOInit(), and HALOPlot().
Referenced by HALOFamily(), HALOPlot(), and LyapunovFamily().
HALOState()
function HALOState (in Ax, in Az, in phiXY, in phiZ, in system, in point, in t)
Type HALOState for a demo.
Form
 [r,v,p] = HALOState( Ax,Az,phiXY,phiZ, system, point, t )
Inputs
 Ax      (1,1)   Amplitude of oscillation in the x direction (AU)
 Az      (1,1)   Amplitude of oscillation in the z direction (AU)
 phiXY   (1,1)   Initial angle in the XY plane (rad)
 phiZ    (1,1)   Initial phase angle for z oscillation (rad)
 system   (:)    String name of system: 'SEM' or 'EM'
 point   (1,1)   Which libration point: L1 (1) or L2 (2)
 t       (1,1)   Time from initial state
Outputs
 r       (3,1)   Approx. initial HALO position in rotating system. (AU)
 v       (3,1)   Approx. initial HALO velocity in rotating system. (AU)
 p       (1,1)   Approx. HALO period (nondimensional time)
References: Online course notes, Prof. J.D. Mireles James, Rutgers University. http://www.math.rutgers.edu/~jmireles/notes.html
References Demo(), and HALOState().
Referenced by HALOState(), and LyapunovFamily().
HelioFromPlanetInit()
function HelioFromPlanetInit (in name, in xP, in jD)
xP is in the ECI planet centered frame.
Type HelioFromPlanetInit for a demo of an equatorial 7000 km circular earth orbit.
This only works with the planets (including Pluto). It uses the low-fidelity almanac functions.
 Forms:
 xH = HelioFromPlanetInit( planet, xP, jD )
Inputs
 name    (1,1)   Planet name
 xP      (6,1)   State in the planet centered ECI frame
 jD      (1,1)   Julian date
Outputs
 xH      (6,1)   State in the heliocentric frame
References CEcl2Eq(), Constant(), Date2JD(), Demo(), HelioFromPlanetInit(), Initialize(), JD2T(), Planets(), and SolarSys().
Referenced by HelioFromPlanetInit().
HelioPlot()
function HelioPlot (in p, in duration, in jD0, in r, in rName, in ecl)
It uses PlanetPosJPL for the planetary ephemerides. Can handle any number of spacecraft [r1;r2;r3...]. The default plot is in the equatorial frame; pass in the ecliptic flag to plot in the ecliptic frame.
Form
 HelioPlot( p, duration, jD0, r, rName )
Inputs
 p             (1,:)   Planets 1-9, 10 (moon)
 duration      (1,1)   Duration of the study (years)
 jD0           (1,1)   Julian date to start computation or date array
 r             (3*m,:) Spacecraft trajectory [r1;r2;r3...] (km)
 rName         {m}     Names objects in r
 ecl           (1,1)   If entered plot in ecliptic
Outputs
 None.
References and(), PlanetPosJPL(), and Planets().
Referenced by JDStartTransfer().
HelioToBPlane()
function HelioToBPlane (in r0, in v0, in rA, in vA)
The B-plane frame is a plane moving with the planet and perpendicular to the incoming velocity of the asteroid.
Type HelioToBPlane for a demo.
Form
 [m, bN] = HelioToBPlane( r0, v0, rA, vA )
Inputs
 r0 (3,1)   Position vector planet
 v0 (3,1)   Velocity vector planet
 rA (3,1)   Position vector asteroid
 vA (3,1)   Velocity vector asteroid
Outputs
 m    (3,3)   Transformation matrix
 n   (3,1)   Trajectory orbit normal
 bN  (3,1)   B-plane normal
References and(), Constant(), Cross(), Demo(), Dot(), HelioToBPlane(), PlotBPlane(), Trajectory(), Unit(), and vector().
Referenced by HelioToBPlane(), and PlotBPlane().
HelioToPlanet()
function HelioToPlanet (in jD, in planet, in kEarth)
 Includes all of the planets and many of the moons. Returns the identity
 matrix if the moon is unknown. For the Earth's moon it returns the true
 rotation matrix.
See also
CEcl2Eq, ECIToPlanet
 Since version 2014.1
Form
 c = HelioToPlanet( jD, planet, kEarth )
Inputs
 jD         (1,1)  Julian date
 planet     (1,:)  Name of the planet
 kEarth     (1,1)  If 0 use TruEarth, if 1 is TruEarth with eofe
Outputs
 c         (3,3)  Matrix from heliocentric to planet fixed
References and().
InterpolateState()
function InterpolateState (in target, in time, in fileName)
Uses the JPL ephemeris files. The returned state is measured from the solar system barycenter and in the Earth equatorial frame. Can be initialized with the binary file name by passing empty for the other inputs, then future calls may omit the file name. The initialization status can be checked with a single empty input.
A binary file can be generated from a text file (ex. ascp2000.405) using the tool EphemUtil, available via ftp:
 ftp://ssd.jpl.nasa.gov//pub/eph/export/
in the folder C-versions/hoffman. You must compile the tool for your system.
Visit http://ssd.jpl.nasa.gov/?planet_eph_export for more information about these ephemerides.
Form
 [X, GM] = InterpolateState( target, time, fileName )
 status = InterpolateState( [], [], fileName )
 status = InterpolateState( [] )
 1. Mercury
 2. Venus
 3. Earth-Moon Barycenter
 4. Mars
 5. Jupiter
 6. Saturn
 7. Uranus
 8. Neptune
 9. Pluto
 10. Geocentric Moon
 11. Sun
Inputs
 Target    (1,1)       Planet ID
 Time      (1,1)       Julian date (days)
 fileName   (:)        Binary file name if not initialized
Outputs
 X         (6,1)       Planetary state vector, Earth mean equatorial frame
 GM        (1,1)       Corresponding gravitational parameter (km3/s2)
References and(), Date2JD(), Initialize(), InterpolateState(), isempty(), JD2000(), and zeros().
Referenced by EnergyWRTMoon(), InterpolateState(), PlanetPosJPL(), and SolarSysJPL().
IteratePeriodicOrbit()
function IteratePeriodicOrbit (in p1, in mu, in family, in doSave)
The orbit has nearest periapsis at r1. Loads the corresponding mat-files to the selected family: f16, f17, f18, f19, f20, and f26. If desired will save updated data to mat-files.
Type IteratePeriodicOrbit for a demo.
Form
 d = IteratePeriodicOrbit( p1, mu, family )
Inputs
 mu      (1,1) Gravity ratio of the CRTBP
 p1      (1,1) Nearest periapse radius
 family (1,:) Family name from Markellos catalog e.g. 'f16','f16p'
 doSave  (1)   Whether to save data
Outputs
 d       (:)  Data structure with information about the orbit
References abs(), and(), Constant(), CRTBPJacobiConstant(), Demo(), IteratePeriodicOrbit(), PeriodicOrbitFromGuess(), PropagateCRTBP(), RHS(), and zeros().
Referenced by IteratePeriodicOrbit().
J20002RotPuls()
function J20002RotPuls (in stateIn, in primaryEph, in muPrimary)
Transform a state vector from the J2000 reference frame to a rotating-pulsating reference frame centered on the secondary body.
Form
 stateOut = J20002RotPuls(stateIn,primaryEph,muPrimary)
Inputs
 stateIn     (6,1)   Initial state vector
 primaryEph  (6,1)   State vector of Primary
 muPrimary   (1,1)   Gravitational Parameter the Primary
Outputs
 stateOut    (6,1)   Output state vector
References Coordinates(), J20002RotPuls(), Mag(), Parameter(), Unit(), vector(), and zeros().
Referenced by J20002RotPuls(), LETPhasing(), LowEnergyEarthToMoonTransfer(), PlotLET(), PlotLET3BP(), and Targeting3BP2().
J20002RotPulsPlanetMoon()
function J20002RotPulsPlanetMoon (in stateIn, in primaryEph, in muPrimary, in secondaryEph)
 pulsating reference frame centered at the barycenter of the secondary
 body's system.
 Since version 9.
Form
 stateOut = J20002RotPulsPlanetMoon(stateIn,primaryEph,muPrimary,secondaryEph);
Inputs
 stateIn        (6,1)   Initial state vector
 primaryEph     (6,1)   State vector of Primary Object
 muPrimary       (1)    Gravitational Parameter of Object
 secondaryEph   (6,1)   State vector of Secondary Object
Outputs
 stateOut       (6,1)   Output state vector
References vector().
Referenced by MinE4BP().
JDStartTransfer()
function JDStartTransfer (in jD0, in planetPair, in transferTime, in duration, in n)
Starts at jD0. You specify the [departure target] planets using JPL ids, where 1 = Mercury and 9 = Pluto. jD0 may be a Julian day number or date array:
 [year month day hour minute second]
Type JDStartTransfer for a demo.
Form
 jDS = JDStartTransfer( jD0, planetPair, transferTime, duration, n )
Inputs
 jD0           (1,1) Julian date to start computation or date array
 planetPair    (1,2) Planets [departure target]
 transferTime  (1,1) Duration of the transfer (years)
 duration      (1,1) Duration of the study (years)
 n             (1,1) Number of steps
Outputs
 jDD           (1,1) Departure date
See also
PlanetPosJPL
References and(), Constant(), Date2JD(), Demo(), HelioPlot(), Initialize(), JDStartTransfer(), length(), PlanetPosJPL(), Planets(), and Unit().
Referenced by JDStartTransfer().
Kms2CRTBP()
function Kms2CRTBP (in stateIn, in distanceUnit, in muPrimary, in muSecondary)
Transforms a state vector from units associated with Jacobi coordinates of the Circular Restricted Three Body Problem to units of km and sec
Form
 [stateOut,mu,sec2tu] = Kms2CRTBP(stateIn,distanceUnit,muPrimary,muSecondary);
Inputs
 stateIn        (1,6)  Initial state vector
 distanceUnit    (1)   Distance from the Primary to the Secondary
 muPrimary       (1)   Gravitational Parameter of the Primary
 muSecondary     (1)   Gravitational Parameter of the Secondary
Outputs
 stateOut         (1,6)       Output state vector
 mu                (1)     Gravitational Parameter of the CRTBP
 sec2tu            (1)     Scaling factor for time
References and(), Kms2CRTBP(), Parameter(), and vector().
Referenced by Kms2CRTBP(), and MinE4BP().
L2OrbitPlots()
function L2OrbitPlots (in x, in d)
Sequence is: spiral out / coast / reverse thrust / halo orbit
Type L2OrbitPlots for a demo which loads SEML2OrbitData.mat
Form
 L2OrbitPlots( x, d )
Inputs
 x       (4,1)   Decision variables [phase, T1, T2, dT]
                 - phase   Initial phase angle of Earth orbit in xy plane
                 - T1      Time to stop spiral thrust arc
                 - T2      Time to start insertion thrust arc
                 - dT      Duration of reverse thrust arc
 d        (.)    Data structure describing spacecraft model and CRTBP
 system
Outputs
 None
See also
L2OrbitSim.
References and(), Circle(), Demo(), get(), isempty(), L2OrbitPlots(), L2OrbitSim(), LTSpiral(), NewFig(), set(), and SunEarthMoonSystemConstants().
Referenced by L2OrbitPlots().
L2OrbitSim()
function L2OrbitSim (in x, in d, in times)
Consists of the sequence: spiral out / coast / reverse thrust / halo orbit
Type L2OrbitSim for a demo.
Form
 [t,y,dv] = L2OrbitSim( x, d, times )
Inputs
 x       (4,1)   Decision variables [phase, T1, T2, dT]
                 - phase   Initial phase angle of Earth orbit in xy plane
                 - T1      Time to stop spiral thrust arc
                 - T2      Time to start insertion thrust arc
                 - dT      Duration of reverse thrust arc
 d        (.)    Data structure describing spacecraft model and CRTBP
 system
 times   (1,:)   Vector of times over which to evaluate dynamic system.
 Optional. Default is to use d.times.
Outputs
 t       (N,1)   Time vector
 y       (N,7)   State vector: [x, y, z, vx, vy, vz, mass]
 dv      (1,1)   Total delta-v over trajectory
References:
 Online course notes, Prof. J.D. Mireles James, Rutgers University.
 http://www.math.rutgers.edu/~jmireles/notes.html
 M. T. Ozimek and K. C. Howell, "Low-Thrust Transfers in the Earth?Moon
 System, Including Applications to Libration Point Orbits",
 JOURNAL OF GUIDANCE, CONTROL, AND DYNAMICS Vol. 33, No. 2,
 March/April 2010, DOI: 10.2514/1.43179
References and(), Cross(), Demo(), FCRTBPRHS(), L2OrbitSim(), Plot2D(), Plot3D(), SunEarthMoonSystemConstants(), Trajectory(), Unit(), and vector().
Referenced by L2OrbitPlots(), and L2OrbitSim().
LambertDoubleRendezvous()
function LambertDoubleRendezvous (in planet1, in planet2, in jD0, in days, in duration)
Go from one planet1 to planet2, wait some days, then come back. The DVs are assumed to be impulsive. A simple search for a start date is performed to look for the minimum outbound DV given the selected transfer time.
Longer transfer times result in smaller delta-v with an optimum at the equivalent Hohmann transfer.
If the transfer time is too short for an elliptical transfer the function will produce a warning.
Form
 d = LambertDoubleRendezvous( planet1, planet2, jD0, days, duration )
Inputs
 planet1   (1,:)   Starting planet
 planet2   (1,:)   Target planet
 jD0       (1,1)   Reference Julian date
 days      (1,:)   Vector of days (from jD0) to search over
 duration  (1,3)   Mission durations:
                     (1)   Number of days out      (Planet1 to Planet2)
                     (2)   Number of days to stay  (at Planet2)
                     (3)   Number of days back     (Planet2 to Planet1)
Outputs
 d          (.)    Data structure with all data describing the double
                   rendezvous transfer trajectories.
See also
PlanetTransferLambert
References and(), close(), Date2JD(), Demo(), Figui(), JD2Date(), LambertDoubleRendezvous(), length(), NewFig(), PlanetTransferLambert(), SynodicPlanets(), and zeros().
Referenced by LambertDoubleRendezvous().
LandingControl()
function LandingControl (in v, in h, in uV, in d)
 Determines the thrust vector and throttle for landing on a planet.
 Uses a bang-bang for vertical control during terminal ascent.
 Horizontal control is velocity damping.
 This function generates throttle and thrust vector
 orientation. Thrust vector orientation is achieved by reorienting
 the vehicle or the engine nozzle. The reorientation controller needs
 to be fast enough so that the engine is pointing along the desired
 vector. You can set the throttle to zero until you reach the desired
 orientation.
 The control has four modes:
 Mode 1 - Drive the vertical velocity to zero and hover
 Mode 2 - Drive all velocities to zero
 Mode 3 - Bang-Bang vertical control
 Mode 4 - Engine balances gravity
 vMaxFrac is the fraction of the maximum velocity allowed during Mode 3.
 The maximum velocity is for free-fall.
 This is used as the terminal control for an optimal landing
 guidance algorithm.
 When you reach mode 4 it is up to you to set the throttle to zero.
 The terminal errors will depend on the time step of your controller.
 Type LandingControl for a 2D lunar landing demo.
Form
 d = LandingControl( v, h, uV, d )
Inputs
 v   (3,1)  Velocity vector (km/s)
 h   (1,1)  Altitude (km)
 uV (3,1)   Vertical unit vector (+up)
 d   (1,1)  Data structure
           .accel              (1,1) Maximum acceleration (km/s^2)
           .gainRate           (1,1) Velocity gain
           .g                  (1,1) Gravitational acceleration at the surface in (km/s^2)
           .mode               (1,1) Mode setting 1-4
           .velocityThreshold   (1,1) Rate to switch modes
           .hLanding           (1,1) Landing gear height
           .vMaxFrac           (1,1) Maximum velocity during mode 3
Outputs
 d        (1,1) Data structure
                 .u          (3,1)  Thrust unit vector
                 .throttle   (1,1)  Throttle setting from 0 to 1
                 .mode       (1,1) Mode setting 1-4
References abs(), Altitude(), and(), Demo(), Dot(), LandingControl(), Mag(), Plot2D(), RK4(), set(), Throttle(), TimeLabl(), Unit(), vector(), and zeros().
Referenced by LandingControl(), and LandingControlBilinear().
LandingControlBilinear()
function LandingControlBilinear (in action, in d)
This is for a circular planet. It uses LandingControl.m
The function has two paths. One is used on initialization, the other each time step to update the controller. The function will plot the beta angles for the controller.
You can bypass attitude control in which case the thrust will always be in the correct direction.
Terminal descent happens after the bilinear tangent runs out of steps or if the spacecraft is below a landing altitude threshold.
All data and inputs and outputs are stored in the data structure, d.
Form
 d = LandingControlBilinear( action, d )
Inputs
 action (1,:) 'initialize' or 'update'
 d        (.)  Data structure inputs
               .nG         (1,1) Engine acceleration is this number times
                                 gravity
               .mu         (1,1) Gravitational constant
               .inertia    (1,1) Inertia matrix
               .aCS         (.)  PID3Axis data structure
                                 .zeta   (1,1) Damping ratio
                                 .omega  (1,1) Undamped natural frequency
                                 .tauInt (1,1) Integrator time
                                 .omegaR (1,1) Rate filter frequency
               .mass       (1,1) Mass (kg)
               .bypassACS  (1,1) 1 = bypass attitude control
               .landing     (.)  Landing control data structure
                                 .omega (1,1) Undamped natural frequency
                                 .zeta  (1,1) Damping ratio
Outputs
 d          (1,1) Data structure outputs
               .aCS       (.)  PID3Axis data structure
                               .eci_vector (3,1) Pointing vector
               .a        (1,1) Acceleration
               .thrust   (1,1) Engine thrust
               .beta     (1,:) Thrust direction angles
               .t        (1,:) Corresponding times
               .throttle (1,1) Throttle setting
               .index    (1,1) Index for betas
               .landing  (.)  Landing control data structure
                               .gainForward  (1,1) Forward gain
                               .tau          (1,1) Time constant
                               .accel        (1,1) Acceleration
                               .g            (1,1) Gravity
                               .mode         (1,1) Mode
See also
LandingControl, BilinearTangentLaw, PIDMIMO, PID3Axis
References abs(), Altitude(), and(), BilinearTangentLaw(), Constant(), Cross(), DefaultDataStructure(), Dot(), Inertias(), LandingControl(), LandingControlBilinear(), length(), Mag(), PID3Axis(), PIDMIMO(), Plot2D(), QTForm(), set(), Throttle(), TimeLabl(), Unit(), and vector().
Referenced by LandingControlBilinear(), and LunarLandingControl().
LandingControlGravityTurn()
function LandingControlGravityTurn (in v, in d)
 Thrusts along the velocity vector. You can adjust the forward
 and integral games to get a soft landing.
 The gravity acts as a bias acceleration.
 Type LandingControlGravityTurn for a 2D Europa landing demo.
 Since version 2014.1
Form
 [u, throttle, d] = LandingControlGravityTurn( v, d )
Inputs
 v        (3,1) Velocity vector (km/s)
 d        (1,1) Data structure
                 .accel     (1,1) Maximum acceleration (m/s^2)
                 .gain   (1,1) Velocity gain
                 .tau    (1,1) Integrator time constant
                 .dT     (1,1) Time step
                 .intV   (1,1) Integral of velocity
Outputs
 u         (3,1)    Thrust unit vector
 throttle  (1,1)    Throttle setting from 0 to 1
 d         (1,1)    Data structure
                 .intV   (1,1) Integral of velocity
References abs(), Altitude(), and(), Constant(), Demo(), get(), Integral(), LandingControlGravityTurn(), Plot2D(), RK4(), Throttle(), TimeLabl(), vector(), and zeros().
Referenced by LandingControlGravityTurn().
LandingForce()
function LandingForce (in x, in ignoredArg, in d)
 Cancels gravity and adds velocity damping. This is effectively and
 inelastic collision with a large body.
Inputs
 x       (:,1)  State vector [r;v;q;w] (km,km/s,,rad/s)
 t       (1,1)  Time (unused) (s)
 d       (1,1)  Data structure for the simulation
                 .mass     (1,1) Vehicle mass (kg)
                 .hLanding (1,1) Altitude at which to apply forces (km)
                 .rP       (1,1) Planet radius (km)
                 .mu       (1,1) Gravitational parameter (km^3/s^2)
                 .damping  (1,1) Velocity damping factor
Outputs
 force   (3,1)   Force (N)
 torque  (3,1)   Torque (Nm) (Always zero)
References Altitude(), and(), Constant(), LandingForce(), Mag(), QForm(), and vector().
Referenced by LandingForce().
LETGuess()
function LETGuess (in p1, in mu, in family)
The orbit has nearest periapsis at r1. Loads a mat-file for the specified family which must be in the paty.
Form
 [d] = LETGuess( p1, mu, family );
Inputs
 mu             (1,1)  Gravity ratio of the CRTBP
 p1             (1,1)  Nearest periapse radius
 family         (1,:)  Family name from Markellos catalog
                         - 'f16'
                         - 'f16p'
Outputs
 d              (:)  Data structure with inforamation about the orbit
References abs(), Constant(), CRTBPJacobiConstant(), Demo(), length(), LETGuess(), PeriodicOrbitFromGuess(), PropagateCRTBP(), and V0FromJacobiConstant().
Referenced by LETGuess(), and LowEnergyTransferInCRTBP().
LETPhasing()
function LETPhasing (in x0, in desiredPhasing, in moon, in planet, in et, in jDate)
The names of the moon and planet must be available in the Constant database. Type LETPhasing for a demo.
Form
 [det,orbits] = LETPhasing(x0,desiredPhasing,moon,planet,et,jDate)
Inputs
 x0             (1,1) Initial guess for a transfer time
 desiredPhasing (1,1) Angle of the moon at the final time in the
                       Sun/Planet rotating coordinate system
 moon               (1,:) String name of moon
 planet             (1,:) String name of planet
 et             (1,1) Seconds after the epoch jDate at which the
                       transfer initiates
 jDate           (1,1) Julian date
Outputs
 det             (1,1) Estimated transfer time
 orbits             (1,1) Number of lunar orbits during transfer
References abs(), and(), Constant(), Demo(), J20002RotPuls(), JD2000(), LETPhasing(), PlanetPositionEMBarycenter(), and RV2El().
Referenced by LETPhasing(), and LowEnergyEarthToMoonTransfer().
LibrationCoeff()
function LibrationCoeff (in mu, in gama, in n)
Form
 c = LibrationCoeff( mu, gama, n );
Inputs
 mu    (1,1) Non-dimensional mass of smaller primary body
             (the larger primary body's mass is 1-mu)
 gama   (1,1) Non-dimensional distance from smaller primary body to
             the collinear libration point, where the distance between
             the two primary bodies is 1.
 n     (1,:) The index of the desired coefficient. Must be n >= 2
Outputs
 c     (1,:) The nth coefficient for use in the equations of motion.
References Demo(), length(), LibrationCoeff(), and zeros().
Referenced by LibrationCoeff(), and Lissajous().
LibrationData()
function LibrationData (in system)
This generates normalized coefficients. Normalization of time is based on the orbit rate of the secondary relative to the primary.
Type LibrationData for a demo for the sun-earth-moon system
Form
 d = LibrationData( system )
Inputs
 system     (:) Name of two-body system, options:
             - 'SEM'  Sun - Earth/moon
             - 'EM'   Earth - moon
Outputs
 d  (.)  Data structure containing the following information
        .mu     (1,1) Non-dimensional mass of smaller primary body
        .mR     (1,1) Mass ratio, larger body to smaller body
        .L1     (1,1) Non-dimensional distance from smaller body to L1 point
        .L2     (1,1) Non-dimensional distance from smaller body to L2 point
        .L3     (1,1) Non-dimensional distance from larger body to L3 point
        .L4     (1,1) Non-dimensional distance from either body to L4 point
        .L5     (1,1) Non-dimensional distance from either body to L5 point
        .wXY1   (1,1) Natural frequency of x-y motion at L1
        .wXY2   (1,1) Natural frequency of x-y motion at L2
        .wZ1    (1,1) Natural frequency of z motion at L1
        .wZ2    (1,1) Natural frequency of z motion at L2
        .k1     (1,1) Amplitude ratio for L1, Ax = k*Ay
        .k2     (1,1) Amplitude ratio for L2, Ax = k*Ay
References and(), and LibrationData().
Referenced by LibrationData(), and Lissajous().
LibrationRHS()
function LibrationRHS (in x, in ignoredArg, in c2, in c3, in c4)
Uses the equations of motion (up to 3rd order) for the circular restricted three-body problem. Formatted for PSS RK4/RK45 integrators.
Form
 xDot = LibrationRHS( x, t, c2, c3, c4 )
Inputs
 x             (6,1) Current state  [x;y;z;dxdt;dydt;dzdt]
 t             (1,1)  Time (not used)
 c2            (1,1)  Coefficient on 1st order terms
 c3            (1,1)  Coefficient on 2nd order terms
 c4            (1,1)  Coefficient on 3rd order terms
Outputs
 xDot          (6,1) Time derivative of the state, x
Reference: Farquar, Robert, "The Control and Use of Libration Point Satellites", Goddard Space Flight Center, NASA TR R-346, September 1970.
References LibrationRHS(), RK4(), RK45(), and zeros().
Referenced by LibrationRHS(), and Lissajous().
LibrationRHSODE45()
function LibrationRHSODE45 (in ignoredArg, in x, in ignoredArg, in c2, in c3, in c4)
using the equations of motion (up to 3rd order) for the circular restricted three-body problem. Formatted for MATLAB's ode integrators.
Form
 xDot = LibrationRHSODE45( ~, x, ~, c2, c3, c4 )
Inputs
 t             (1,1) Time (not used, but included for consistency with ode45 call)
 x             (6,1) Current state  [x;y;z;dxdt;dydt;dzdt]
 junk          (1,1) Place holder for call to ode45, not used
 c2            (1,1) Coefficient on 1st order terms
 c3            (1,1) Coefficient on 2nd order terms
 c4            (1,1) Coefficient on 3rd order terms
Outputs
 xDot          (6,1) Time derivative of the state
Reference: Farquar, Robert, "The Control and Use of Libration Point Satellites", Goddard Space Flight Center, NASA TR R-346, September 1970.
Referenced by Lissajous().
Lissajous()
function Lissajous (in system, in point, in Ax, in Az, in phiXY, in phiZ, in N)
Type Lissajous for a demo.
Form
 [x1,x2,x3,Ay,t] = Lissajous( system, point, Ax, Az, phiXY, phiZ, N )
Inputs
 system (1,:)   Name of two-body system, options:
                - 'SEM'  Sun - Earth/moon
                - 'EM'   Earth - moon
 point   (1,1)  Libration point number (1 or 2)
 Ax      (1,1)  x amplitude
 Az      (1,1)  z amplitude
 phiXY   (1,1)  Initial phase offset in x-y plane
                (measured positive from -x to +y axis)
 phiZ    (1,1)  Initial phase offset in z-axis
 N       (1,1)  Number of periods to compute trajectory over
                     (entering 0 returns initial conditions)
Outputs
 x1      (6,1) Trajectory computed from continuous solution [x;y;z;dx;dy;dz]
               x = -Ax*cos( wXY*t + phiXY )
               y = (Ax/k)*sin( wXY*t + phiXY )
               z = Az*sin( wXY*t + phiZ )
 x2      (6,1) Trajectory integrated using RK4
 x3      (6,1) Trajectory integrated using ode45
 Ay      (1,1) y amplitude (equal to Ax/k, where k is from LibrationData)
 t       (1,:) Time vector
Reference: Farquar, Robert, "The Control and Use of Libration Point Satellites", Goddard Space Flight Center, NASA TR R-346, September 1970.
References Demo(), IsVersionAfter(), length(), LibrationCoeff(), LibrationData(), LibrationRHS(), LibrationRHSODE45(), Lissajous(), Mag(), NewFig(), RK4(), Trajectory(), vector(), and zeros().
Referenced by Lissajous().
LowEnergyEarthToMoonTransfer()
function LowEnergyEarthToMoonTransfer (in jD, in r0)
From circular trajectory about Earth with a radius of r0 to a weakly captured lunar orbit.
Requires the Optimization Toolbox.
Form
 [LETTrans,debugData] = LowEnergyEarthToMoonTransfer(jD,r0)
Inputs
 jD             (1)  Julian Date of transfer
 r0             (1)  Initial circular orbit radius (km)
Outputs
 LETTrans       (.)  Data structure with information about the orbit
                .elements            ecliptic orbital elements of the
                                     initial state
                .initialStateJ2000   Initial state vector
                .maneuver            Magnitude of the initial maneuver
                .timeOfFlight        Period of the transfer
                .finalEnergy         Final energy level
                .family              CRTBP orbit family
                .muMoon              Gravitational Parameter of the moon
                .muPlanet            Gravitational Parameter of the planet
                .cTraj               Jacobi constant of the final state
                .cL2                 Jacobi constant of the L2 point
                .burns               number of burn maneuvers performed
 debugData
Reference: Griesemer, P. R., Ocampo, C. A., and Cooley, D. S., "Targeting Ballistic Lunar Capture Trajectories Using Periodic Orbits in the Sun-Earth CRTBP", accepted for publication by the AIAA Journal of Guidance, Control, and Dynamics, Feb, 2010.
See also
: LowEnergyTransferInCRTBP, LETPhasing, Targeting3BP2
References and(), CheckForOptimizationToolbox(), close(), Constant(), CRTBP2kms(), Demo(), El2RV(), Energy(), isempty(), J20002RotPuls(), JD2000(), LagrangePointsL1ToL5(), LETPhasing(), LowEnergyEarthToMoonTransfer(), LowEnergyTransferInCRTBP(), Mag(), MinE4BP(), Parameter(), Period(), PlanetPositionEMBarycenter(), PlotLET(), PlotLET3BP(), RotPuls2J2000(), RV2El(), Step(), Targeting3BP2(), Targeting4BP(), and vector().
Referenced by LowEnergyEarthToMoonTransfer().
LowEnergyTransferInCRTBP()
function LowEnergyTransferInCRTBP (in r1, in r2, in mu, in orientation)
The transfer is from a circular orbit of radius r1 to a circular orbit of radius r2.
Type LowEnergyTransferInCRTBP for a demo between two circular orbits.
Form
 LET = LowEnergyTransferInCRTBP( r1,r2,mu,orientation );
Inputs
 r1             (1,1)  Initial circular orbit radius
 r2             (1,1)  Final circular orbit radius
 mu             (1,1)  Gravity ratio of the CRTBP
 orientation    (1,1)  orientation of the maneuver
                         - ' '
                         - 'p'
Outputs
 LET            (.)  Data structure with information about the orbit
                      .mu
                      .JacobiConstant
                      .initialState
                      .period
                      .tF
                      .dV1
                      .family
                      .dV2
                      .theta2
References abs(), and(), Constant(), Demo(), Energy(), LETGuess(), LowEnergyTransferInCRTBP(), Mag(), NewFig(), PropagateCRTBP(), PropagateCRTBPToPeriapse(), Unit(), XLabelS(), and YLabelS().
Referenced by LowEnergyEarthToMoonTransfer(), and LowEnergyTransferInCRTBP().
LowThrustCRTBP_StopFcn()
function LowThrustCRTBP_StopFcn (in t, in x, in d)
 Since version 10.
Form
 [value, isterminal, direction] = LowThrustCRTBP_StopFcn(t,x,d)
Inputs
 t          (:,1)     Time
 x           (:,3)     Position
 d           (1,1)     Data structure
                       .L        (1,1) Sun/earth distance
                       .rE       (1,1) Earth dimensioned barycentric position
                       .rS       (1,1) Sun dimensioned barycentric position
                       .ratio    (1,1) Desired ratio of sun to earth gravity
                       .muSun    (1,1) Gravitational potential of the sun
                       .muEarth  (1,1) Gravitational potential of the earth
Outputs
 value       (1,1)    Value
 isterminal (1,1)    1 if a terminal condition
 direction   (1,1)    Sign of direction
References LowThrustCRTBP_StopFcn(), and Mag().
Referenced by EarthOrbToHelioOrb(), and LowThrustCRTBP_StopFcn().
LowThrustDVToTransfer()
function LowThrustDVToTransfer (in dT, in m0, in thrust, in Isp)
 Approximate delta-V required to transfer to another orbit. Assumes one
 Keplerian element is changed at a time. Takes in transfer times from
 another function.
Form
 [dVTot,dVElem] = LowThrustDVToTransfer( dT, m0, thrust, Isp )
Inputs
 dT            (5,1)     Transfer times for each orbital element (sec)
                           See LowThrustTimeToTransfer.m
 m0            (1,1)     Initial mass of spacecraft (kg)
 thrust        (1,1)     Thrust magnitude (kN)
 Isp           (1,1)     Specific impulse (sec)
Outputs
 dVTot         (1,1)     Total delta-v for changing all elements (km/s)
 dVElem        (5,1)     Delta-v for changing each element (km/s)
References Demo(), length(), LowThrustDVToTransfer(), LowThrustTimeToTransfer(), and zeros().
Referenced by LowThrustDVToTransfer().
LowThrustGVE_EventFcn()
function LowThrustGVE_EventFcn (in t, in y, in k, in ykdes, in tol)
Terminate when the abs value of difference between current element and desired element is less than tolerance.
Form
 [value,isterminal,direction] = LowThrustGVE_EventFcn(t,y,k,ykdes,tol)
Inputs
 t             (1,1)       Time (not used)
 y             (6,1)       State vector (arbitrary units)
 k             (1,1)       Index of element to check (1 <= k <= 6)
 ykdes         (1,1)       Desired value of kth element (same units)
 tol           (1,1)       Threshold passing tolerance (same units)
Outputs
 value         (1,1)       Value of function evaluation. Positive: y(k)
                           is different from ykdes by more than tol.
 isterminal    (1,1)       1 - terminal condition
 direction     (1,1)       0 - direction does not matter
References abs(), and(), LowThrustGVE_EventFcn(), and vector().
Referenced by LowThrustGVE_EventFcn(), and LowThrustRendezvousSim().
LowThrustGVERHS()
function LowThrustGVERHS (in x, in t, in xDes, in thrust, in mDot, in index, in mu)
Accounts for changing mass as fuel is consumed.
Form
 xDot = LowThrustGVERHS(x,t,xDes,thrust,mDot,index,mu);
Inputs
 x             (7,1)       State vector: 6 Keplerian orbital elements
                           and mass (kg) [a,i,W,w,e,M,m]
 t             (1,1)       Time (not used)
 xDes          (6,1)       Target state vector: 6 Keplerian orbital
                           elements [a,i,W,w,e,M]
 thrust        (1,1)       Thrust magnitude (kN)
 mDot          (1,1)       Mass flow rate (kg/sec)
 index         (1,1)       Index of which state element to track, 1 - 5
 mu            (1,1)       Gravitational parameter
Outputs
 xDot          (7,1)       State derivatives
See also
GVEDynamics, GVEGuidance
References and(), GVEDynamics(), GVEGuidance(), LowThrustGVERHS(), and vector().
Referenced by LowThrustGVERHS(), and LowThrustRendezvousSim().
LowThrustRendezvousSim()
function LowThrustRendezvousSim (in el0, in elT, in mass0, in thrust, in Isp, in elemOrder, in mu)
Applies constant magnitude, variable direction thrust to optimally change each element one at a time, according to specified order.
Form
 [t,el,r,v,mass,acc,accRSW] = LowThrustRendezvousSim( ...
 el0, elT, mass0, thrust, Isp, elemOrder, mu);
Inputs
 el0         (1,6)     Initial Keplerian orbital elements [a,i,W,w,e,M]
 elT         (1,6)     Target Keplerian orbital elements
 mass0       (1,1)     Initial mass (kg)
 thrust      (1,1)     Thrust magnitude (kN)
 Isp         (1,1)     Specific impulse (s)
 elemOrder   (1,5)     Order in which to change elements
 mu          (1,1)     Gravitational constant
Outputs
 t           (1,:)     Simulation time vector
 el          (:,6)     Orbital elements
 r           (3,:)     Inertial position
 v           (3,:)     Inertial velocity
 mass        (1,:)     Mass
 acc         (3,:)     Accleration in inertial frame
 accRSW      (3,:)     Acceleration in RSW (radial / tangent / normal)
See also
: LowThrustTimeToTransfer, LowThrustGVE_EventFcn, LowThrustGVERHS
References Constant(), LowThrustGVE_EventFcn(), LowThrustGVERHS(), LowThrustRendezvousSim(), LowThrustTimeToTransfer(), Plot2D(), and vector().
Referenced by LowThrustRendezvousSim().
LowThrustTimeToTransfer()
function LowThrustTimeToTransfer (in el0, in elT, in aMax, in mu)
 Type LowThrustTimeToTransfer for a demo.
 Since version 2014.1
Form
 [dT,dT0,dTT,elDot0,elDotT] = LowThrustTimeToTransfer( el0, elT, aMax, mu )
Inputs
 el0           (1,6)       Initial Keplerian elements [a,i,W,w,e,M]
 elT           (1,6)       Target Keplerian orbital elements
 aMax          (1,1)       Acceleration bound (km/sec^2)
 mu            (1,1)       Gravitational constant (km^3/sec^2)
Outputs
 dT            (5,1)       Approx. time to transfer each element (sec)
 dT0           (5,1)       Time to transfer each element at el0  (sec)
 dTT           (5,1)       Time to transfer each element at elT  (sec)
 elDot0        (5,:)       Element rates over one orbit at el0 (*&zwj;/sec)
 elDotT        (5,:)       Element rates over one orbit at elT (*&zwj;/sec)
See also
: GVEDynamics, GVEGuidance
References abs(), Constant(), Demo(), GVEDynamics(), GVEGuidance(), length(), LowThrustTimeToTransfer(), OrbElemDiff(), and zeros().
Referenced by LowThrustDVToTransfer(), LowThrustRendezvousSim(), and LowThrustTimeToTransfer().
LyapunovFamily()
function LyapunovFamily (in Ax, in system, in point)
 Specify a range of orbit amplitudes (Ax), the system (Sun-Earth/Moon or
 Earth-Moon), and the point (L1 or L2)
 Type LyapunovFamily for a demo
 Since version 11.
Form
 ds = LyapunovFamily( Ax, system, point )
Inputs
 Ax        (1,:)     Normalized obit amplitudes
 system    (:)       Name of system 'SEM' or 'EM'
 point     (1,1)     Point, L1 (1) or L2 (2)
Outputs
 ds        (.)       Data structure with stored periodic trajectories
References: Online course notes, Prof. J.D. Mireles James, Rutgers University. http://www.math.rutgers.edu/~jmireles/notes.html
References and(), Demo(), HALOInit(), HALOPlot(), HALOState(), Lyapunov(), LyapunovFamily(), and zeros().
Referenced by LyapunovFamily().
LyapunovInit()
function LyapunovInit (in Ax, in system, in point, in doPlot)
Type LyapunovInit for a demo
 Since version 11.
Form
 d = LyapunovInit( Ax, system, point, doPlot );
Inputs
 Ax      (1,1)   Amplitude of oscillation in the x direction (AU)
 system   (:)    String name of system: 'SEM' or 'EM'
 point   (1,1)   Which libration point: L1 (1) or L2 (2)
 doPlot  (1,1)   Flag to plot (1) or not (0)
Outputs
 d       (.)     Data structure output with system constants and fields:
                   .point
                   .x0
                   .x0f
                   .tf
                   .x0Hist
                   .t
                   .xSTM
                   .x
References: Online course notes, Prof. J.D. Mireles James, Rutgers University. http://www.math.rutgers.edu/~jmireles/notes.html
References and(), Lyapunov(), and LyapunovInit().
Referenced by LyapunovInit().
MarsRot()
function MarsRot (in jD, in useSec)
 If two arguments are entered it will add secular components.
Form
 g = MarsRot( jD, useSec )
Inputs
 jD           Julian Date
 useSec       Add secular variations
Outputs
 g            ECI To Areographic matrix
References: Escobal, P. R., Methods of Orbit Determination, Krieger, pp. 419-421.
References Demo(), and MarsRot().
Referenced by MarsRot(), and PlanetRot().
MinE4BP()
function MinE4BP (in elements, in dV1Eph, in dtTarg, in et, in muMoon, in p, in jDate)
The default bodies are the Earth and the Moon.
Form
 [elementsNew,dV1EphNew,dtNew,f,jTraj,jL2,dV2EphNew,tM2New] =
 MinE4BP(elements,dV1Eph,dtTarg,et,muMoon,p,dV2Eph,tM2)
Inputs
 elements       (1,6)  Ecliptic orbital elements of the initial state
 dV1Eph          (1)   Magnitude of the initial maneuver
 dtTarg          (1)   Transfer time
 et              (1)   Seconds after the epoch at which the orbit begins
 muMoon          (1)   Gravitational Parameter of the moon
 p               (1)   L2 distance from the moon
Outputs
 elementsNew     (1)   Optimized ecliptic elements
 dV1EphNew       (1)   Optimized initial maneuver magnitude
 dtNew           (1)   Optimized transfer time
 f               (1)   Final energy with resepect to the moon
 jTraj           (1)   Jacobi constant of the final state
 jL2             (1)   Jacobi constant of the L2 point
References and(), CheckForOptimizationToolbox(), Constant(), CRTBPJacobiConstant(), El2RV(), EnergyWRTMoon(), J20002RotPulsPlanetMoon(), Kms2CRTBP(), Mag(), MinE4BP(), Parameter(), PlanetPositionEMBarycenter(), Propagate4BP(), Unit(), and zeros().
Referenced by LowEnergyEarthToMoonTransfer(), and MinE4BP().
NeptuneAirshipSizing()
function NeptuneAirshipSizing (in h, in m0)
A simple mass balance is applied. For neutral buoyancy, the total mass of the vehicle must equal the mass of the atmospheric gas displaced. In this case, the total mass of the vehicle is approximated as:
Vehicle Mass = Payload Mass + Hull Fabric Mass + Lifting Gas Mass
 80% H, 19% He, 1% Methane.
 as a function of the sphere radius.
Type NeptuneAirshipSizing for a demo.
Form
 d = NeptuneAirshipSizing( h, m0 )
Inputs
 h       (1,n)     Altitude vector (km), keep below 1400 km.
 m0      (1,m)     Payload mass vector (kg)
Outputs
 d       (.)       Data structure with information including:
                     .h            (1,n)   Altitude vector input
                     .m0           (1,m)   Payload mass vector input
                     .massAir      (m,n)   Mass of air (kg)
                     .massGas      (m,n)   Mass of lifting gas (kg)
                     .massHull     (m,n)   Mass of fabric hull (kg)
                     .massVehicle  (m,n)   Mass of vehicle (kg)
                     .sigmaFabric  (1,1)   Areal density of fabric
                     .R            (m,n)   Radius of balloon (m)
                     .S            (m,n)   Surface area of balloon (m^2)
                     .V            (m,n)   Volume of balloon (m^3)
                     .rhoA         (1,n)   Density of air across
                                             altitude (kg/m^3)
References Altitude(), and(), Demo(), length(), NeptuneAirshipSizing(), and vector().
Referenced by NeptuneAirshipSizing(), and UranusAirshipSizing().
NeptuneDensity()
function NeptuneDensity (in h)
This is a third degree polynomial fit.
Form
 rho = NeptuneDensity( h )
Inputs
 h       (1,:)   Altitude (km)
Outputs
 rho     (1,:)   Density (kg/m^3)
Reference: ATMOSPHERIC MODELS FOR AEROENTRY AND AEROASSIST C. G. Justus, Aleta Duvall, Vernon W. Keller
References Altitude(), NeptuneDensity(), and Plot2D().
Referenced by NeptuneDensity().
OrbitLoweringManeuvers()
function OrbitLoweringManeuvers (in action, in d, in t, in v)
This routine will change orbits. The first is for insertion into the planetary orbit from a hyperbola. The second and additional to lower apoapsis. All maneuvers happen at periapsis. All are in-plane maneuvers. You need at least one orbit. d.maneuver is compute during initialization.
Type OrbitLoweringManeuvers for a demo of lunar insertion.
Form
 [u,d] = OrbitLoweringManeuvers( action, d, t, v )
Inputs
 action   (1,:)   'initialize' or 'update'
 d        (.)     Data structure
                  .mu        (1,1) Gravitational parameter (km^2/s^3)
                  .mass      (1,1) Initial mass (kg)
                  .thrust    (1,1) Thrust (N)
                  .uE        (1,1) Exhaust velocity (km/s)
                  .el0       (1,6) Hyperbolic elements [a i lon arg e M]
                  .orbit     (.)   Orbit data structure
                                   .a  (1,1) Semi-major axis (km)
                                   .e  (1,1) Eccentricity
 t        (1,1)   Time (s) or file name for printing the maneuver plan
 v        (3,1)   Velocity vector
Outputs
 u        (3,1)   Thrust vector
 d        (.)     Data structure adds
                   .massFuelUsed (1,1) Total propellant usage (kg)
                   .dVTotal      (1,1) Total delta V (km/s)
                   .maneuver     (.)   Orbit data structure
                                       .t  (1,1) Time of maneuver
                                       .dT (1,1) Maneuver duration
References and(), Constant(), Demo(), length(), M2Nu(), ManeuverDuration(), Nu2M(), OrbitLoweringManeuvers(), Period(), TimeOfFlightHyperbola(), Unit(), vector(), and VOrbit().
Referenced by OrbitLoweringManeuvers().
OrbitRoundTripTransferTimes()
function OrbitRoundTripTransferTimes (in pA, in pB, in dep, in ret, in N)
Type OrbitRoundTripTransferTimes for a demo.
Form
 [t1,t2,t3,t4] = OrbitRoundTripTransferTimes( pA, pB, dep, ret, N )
Inputs
 pA    (.)     Planet A data structure
               .theta0    Phase angle (rad)
               .n         Orbit rate  (rad/s)
 pB    (.)     Planet B data structure
               .theta0    Phase angle (rad)
               .n         Orbit rate  (rad/s)
 dep   (.)     Departure data structure
               .dT
               .dTheta
 ret   (.)     Return data structure
               .dT
               .dTheta
 N     (1,1)   Number of times to compute
Outputs
 t1    (1,N)   Outbound departure times (sec)
 t2    (1,N)   Outbound arrival times
 t3    (1,N)   Return departure times
 t4    (1,N)   Return arrival times
See also
PlanetHelioPhase
References Date2JD(), Demo(), isempty(), length(), NewFig(), OrbitRoundTripTransferTimes(), and PlanetHelioPhase().
Referenced by OrbitRoundTripTransferTimes().
PatchedConicElements()
function PatchedConicElements (in vInf, in rP, in mu)
Calculates the planet centric hyperbolic elements. a is in consistent units with mu and vInf. Given any vInf, you can find the elements that pass through rP.
Type PatchedConicElements for a demo.
Form
 [a, e, phiL] = PatchedConicElements( vInf, rP, mu )
Inputs
 vInf    (1,1) Velocity at the sphere of influence
 rP      (1,1) Periapsis
 mu      (1,1) Planet gravitational parameter
Outputs
 a       (1,1) Semi-major axis
 e       (1,1) Eccentricity
 phiL    (1,1) Limiting true anomaly (rad)
Reference: Allman, M. C. and V. R. Bond, "Modern Astrodynamics," Princeton University Press, 1996,p. 94.
References and(), Constant(), and PatchedConicElements().
Referenced by PatchedConicElements().
PatchedConicPlanner()
function PatchedConicPlanner (in planet, in r, in v, in t, in muC, in pPF)
Provide a demo in the Earth-Moon system.
Form
 PatchedConicPlanner;  % demo
 [vInf, b, el, r0] = PatchedConicPlanner( planet, r, v, t, muC, pPF )
Inputs
 planet (1,:) Planet data structure
              .mu    (1,1) Gravitational parameter
              .radius     (1,1) Planet radius
              .name  (1,:) Planet name
 r      (3,:) Spacecraft position
 v      (3,:) Spacecraft velocity
 t      (1,:) Corresponding time vector
 muC    (1,1) Gravitational constant for the central body
 pPF    (1,1) Patch point fraction of sphere of influence
Outputs
 vInf   (1,1) Velocity at infinity for the planet centric hyperbola
 b      (1,1) Impact parameter
 el     (1,6) Hyperbola elements
 r0     (1,1) Periapsis
References abs(), Constant(), Cross(), Demo(), Dot(), get(), Mag(), Map(), Mat2Q(), NewFig(), PatchedConicPlanner(), Period(), QForm(), RPRA2AE(), RV2El(), RVOrbGen(), SphOI(), TitleS(), Unit(), vector(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by PatchedConicPlanner().
PeriodicOrbitFromGuess()
function PeriodicOrbitFromGuess (in yRef, in t0, in tFRef, in mu)
Find the crossing from an initial guess that begins with the first. The initial guess should end on the x-axis at tF, and should be close to a half periodic orbit.
This requires the Optimization Toolbox.
Type PeriodicOrbitFromGuess for a demo.
Form
 [tFNew, yNew, stm] = PeriodicOrbitFromGuess(yRef,t0,tFRef,mu)
Inputs
 yRef   (6,1) Current state vector [r;v]
 t0     (1,1) Initial time
 tF     (1,1) Initial estimate of final time
 mu     (1,1) CRTBP mass ratio
Outputs
 tFNew  (1,1) Time at the intersection with the x-axis
 yFNew  (6,1) State at the intersection with the x-axis
 stm   (6,6) State transistion matrix
References and(), CheckForOptimizationToolbox(), close(), Demo(), PeriodicOrbitFromGuess(), Plot2D(), PropagateCRTBP(), RHSCRTBP(), set(), and vector().
Referenced by IteratePeriodicOrbit(), LETGuess(), and PeriodicOrbitFromGuess().
PlanarHelioOptimal()
function PlanarHelioOptimal (in d, in maxIter, in iterDisp, in thrust0, in phi0)
Transfer between two circular, heliocentric orbits with electric propulsion. The cost function is the total mass of the vehicle. Requires the Optimization Toolbox from Mathworks.
Specific combinations of parameters may not provide a solution. fmincon will fail to converge in that case. The power is calculated from the thrust, exhaust velocity, and thrust efficiency. The engine mass is calculated from the specific power.
 P  = 0.5 T*uE/eta
 mE = P/sigma
The total mass is
 m0 = mP + (1 + f)*mF + mE
where mP is the mass of the payload, f is the fuel structural fraction, and mE is the mass of the engine.
Type PlanarHelioOptimal for a demo to Mars
Form
 d0 = PlanarHelioOptimal
 [phi, thrust, t, data] = PlanarHelioOptimal( d, maxIter, iterDisp )
Inputs
 d      (.)    Data structure
                .uE        Exhaust velocity
                .r0        Initial radius
                .rF        Final radius
                .mu        Gravitational parameter of the sun
                .f         Fuel structural fraction
                .tF        Final time (s)
                .eta       Thrust efficiency
                .sigma     Specific power (W/kg)
                .scale     [distance; v radial; v tangential]
                .dVF       Additional velocity to allow at final
 maxIter     (1)     Maximum number of iterations
 iterDisp ('')  Display, default 'iter-detailed'
 thrust0  (1)   Initial thrust, optional
 phi0     (:)   Initial angles, optional
Outputs
 phi     (1,n) Thrust angle (rad)
 t       (1,n) Times (s)
 thrust  (1,1) Thrust (N)
 data     (.)  Results data structure
               .p  (1,1) Power       (W)
               .mD (1,1) Dry mass   (kg)
               .mF (1,1) Fuel mass  (kg)
               .dV (1,1) Delta-V  (km/s)
               .dF (1,1) Final distance achieved (km)
               .vF (1,1) Final velocity achieved (km/s)
See also
SimulatePlanarHelioTrajectory, PlanarHelioOptimalSlidingTime
References abs(), and(), Constant(), DefaultDataStructure(), Demo(), DVConstantThrust(), isempty(), Mag(), PlanarHelioOptimal(), PlanarHelioOptimalSlidingTime(), RHS2DCylindricalOrbit(), RK4(), SimulatePlanarHelioTrajectory(), ThrustElectric(), Trajectory(), UToMF(), and zeros().
Referenced by PlanarHelioOptimal().
PlanarHelioOptimalSlidingTime()
function PlanarHelioOptimalSlidingTime (in d, in maxIter, in iterDisp, in thrust0, in phi0)
The cost function is the total mass of the vehicle. This version allows the "switch" time to be a variable, with one time step before the switch and another after.
Specific combinations of parameters may not provide a solution. fmincon will fail to converge in that case. The power is calculated from the thrust, exhaust velocity, and thrust efficiency. The engine mass is calculated from the specific power.
P = 0.5 T*uE/eta mE = P/sigma
The total mass is
m0 = mP + (1 + f)*mF + mE
where mP is the mass of the payload, f is the fuel structural fraction, and mE is the mass of the engine.
Type PlanarHelioOptimalSlidingTime for a demo to Mars
Form
 d0 = PlanarHelioOptimalSlidingTime
 [phi, thrust, t, data] = PlanarHelioOptimalSlidingTime( d, maxIter, iterDisp )
Inputs
 d      (.)   Data structure
               .uE        Exhaust velocity
               .r0        Initial radius
               .rF        Final radius
               .mu        Gravitational parameter of the sun
               .f         Fuel structural fraction
               .tF        Final time (s)
               .eta       Thrust efficiency
               .sigma     Specific power (W/kg)
               .maxThrust Maximum allowable thrust (N)
 maxIter    (1,1)   Maximum number of iterations
Outputs
 phi     (1,n) Thrust angle (rad)
 t       (1,n) Times (s)
 thrust  (1,1) Thrust (N)
 data     (.)  Results data structure
               .p  (1,1) Power       (W)
               .mD (1,1) Dry mass   (kg)
               .mF (1,1) Fuel mass  (kg)
               .dV (1,1) Delta-V  (km/s)
               .dF (1,1) Final distance achieved (km)
               .vF (1,1) Final velocity achieved (km/s)
See also
SimulatePlanarHelioTrajectory
References and(), DefaultDataStructure(), Demo(), PlanarHelioOptimalSlidingTime(), RHS2DCylindricalOrbit(), and SimulatePlanarHelioTrajectory().
Referenced by PlanarHelioOptimal(), and PlanarHelioOptimalSlidingTime().
PlanetAlignments()
function PlanetAlignments (in planet1, in planet2, in jD)
Uses Planets for ephemerides.
Type PlanetAlignments for an Earth/Mars demo.
Form
 PlanetAlignments( planet1, planet2, jD )
Inputs
 planet1 (1,:) Planet 1 name
 planet2 (1,:) Planet 2 name
 jD      (1,1) Julian date
Outputs
 None
References Constant(), Date2JD(), Demo(), NewFig(), OrbRate(), Period(), PlanetAlignments(), Planets(), RVFromKepler(), SolarSystemElements(), and SynPer().
Referenced by PlanetAlignments().
PlanetaryAtmDens()
function PlanetaryAtmDens (in h, in planet)
Uses AtmDens2 for the Earth, AtmDensMars2 for Mars and AtmDens1 for the other planets. This function has a built-in demo.
Form
 rho = PlanetaryAtmDens( h, planet )
Inputs
 h           (1,:)   Altitude (km)
 planet      (1,:)   'earth', 'mercury', 'venus', 'mars', 'pluto'
                     'jupiter' 'saturn' 'uranus' 'neptune' 'titan'
Outputs
 rho        (1,:)   Atmospheric Density (kg/m^3)
See also
AtmDens1, AtmDens2, AtmDensMars2, AtmDensUranus, AtmDensNeptune
References Altitude(), and(), AtmDens1(), AtmDens2(), AtmDensMars2(), AtmDensNeptune(), AtmDensUranus(), Demo(), and PlanetaryAtmDens().
Referenced by PlanetaryAtmDens().
PlanetaryDistanceToSun()
function PlanetaryDistanceToSun (in name, in jD)
 For moons this uses only the planetary distance.
Form
 [r, f] = PlanetaryDistanceToSun( name, jD )
Inputs
 name      (1,:)   Name of moon or planet
 jD        (1,:)   Julian date (days)
Outputs
 r         (1,:)   Distance (au)
 f         (1,:)   Solar flux (W/m^2)
References and(), Date2JD(), and PlanetaryDistanceToSun().
Referenced by PlanetaryDistanceToSun().
PlanetaryRadiationAndAlbedo()
function PlanetaryRadiationAndAlbedo (in action, in r, in uS)
 Uses the Constant database for planetary constants and the Planets function
 to determine the average planetary distance for solar flux.
 Type PlanetaryRadiationAndAlbedo for a demo at Mars and the Earth.
See also
SolarFlx, EarthAlb, EarthRad
Form
 PlanetaryRadiationAndAlbedo( 'initialize', planet )
 [qR, qA] = PlanetaryRadiationAndAlbedo( 'update', r, uS )
Inputs
 action    (1,:)   'initialize' or 'update'
 r         (3,:)   Satellite position relative to center or planet name
                   or the planet name if action is 'initialize'
 uS        (3,1)   Unit vector to the Sun
Outputs
 qR        (1,:)   Radiation flux
 qA        (1,:)   Albedo flux
References and(), Constant(), EarthAlb(), EarthRad(), length(), Mag(), PlanetaryRadiationAndAlbedo(), Planets(), SolarFlx(), Unit(), vector(), and zeros().
Referenced by PlanetaryRadiationAndAlbedo().
PlanetEnvironment()
function PlanetEnvironment (in rECI, in vECI, in jD, in e)
Calculate the optical fluxes, atmospheric density, and magnetic field at specific locations and dates at a planet, including eclipses. This data is required by the disturbance model. Magnetic field models are available for Jupiter, Saturn, and Neptune. Atmospheric models are included for Mercury, Venus, Mars, Pluto, and Europa.
 Forms:
 PlanetEnvironment( planetName )
 e = PlanetEnvironment( rECI, vECI, jD, e )
Inputs
 planetName  (1,:)   String name of planet for initialization
  --
 rECI        (3,:)    Position vectors in ECI frame
 vECI        (3,:)    Velocity vectors
 jD          (1,:)    Time scalar or array in Julian date
 e            (.)     Initial structure
Outputs
 e            (.)     Environment data with updated data
                      See Disturbances
See also
: AtmDens1, SunVectorECI, Eclipse, MagFieldData, MagFieldPlanet
References and(), AtmDens1(), Constant(), Disturbances(), ECIToPlanet(), Eclipse(), isempty(), JD2000(), length(), Mag(), MagFieldData(), MagFieldPlanet(), PlanetEnvironment(), PlanetRotation(), Plot2D(), PltOrbit(), RVFromKepler(), scalar(), SunVectorECI(), TimeLabl(), Unit(), VAtm(), and zeros().
Referenced by PlanetEnvironment().
PlanetHelioPhase()
function PlanetHelioPhase (in kPlanet, in jD, in useAlmanac)
Uses PlanetPosJPL for ephemeris.
Form
 theta = PlanetHelioPhase( kPlanet, jD );
Inputs
 kPlanet   (1,1)   Index of planet (e.g. 3 is Earth)
 jD        (1,1)   Julian date
Outputs
 theta     (1,1)   Phase angle of planet in x-y (ecliptic) plane
References PlanetHelioPhase(), PlanetPosJPL(), Planets(), and SolarSysState().
Referenced by OrbitRoundTripTransferTimes(), and PlanetHelioPhase().
PlanetId()
function PlanetId (in planet)
Includes the moon (10). The sun is 0 for the JPL ephemerides.
Type PlanetId for a demo.
Form
 id = PlanetId(planet)
Inputs
 planet {:} Planet names (Mercury through Moon)
Outputs
 id      (1,1)  Planet id
References PlanetId().
Referenced by PlanetId().
PlanetOpposition()
function PlanetOpposition (in planets, in jDStart, in n)
Oppositions for Mars and Earth:
 2012 Mar  3 20:04
 2014 Apr  8 20:57
 2016 May 22 11:11
 2018 Jul 27 05:07
 2020 Oct 13 23:20
Type PlanetOpposition for a demo recreating this table. This function utilizes the almanac functions Planet and SolarSys. Note that the dates are off by 17 days due to the ephemeris errors.
Form
 PlanetOpposition;   % demo
 c = PlanetOpposition( planets, jDStart, n )
Inputs
 planets    [1,2]  Planet numbers
 jDStart (1,1)  Julian date of start (Julian Days)
 n       (1,1)  Number of oppositions
Outputs
 c       (1,:)  Oppositions (Julian Days)
See also
Planets, SolarSys
References and(), Constant(), Date2JD(), Demo(), JD2T(), JDToDateString(), length(), Period(), PlanetOpposition(), Planets(), SolarSys(), SynPer(), and Unit().
Referenced by PlanetOpposition().
PlanetPositionEMBarycenter()
function PlanetPositionEMBarycenter (in action, in d)
The frame is centered on the Earth-Moon Barycenter and the plane is ecliptic, i.e. xy-plane is the mean earth's orbital plane. d cannot be empty on initialize.
Type PlanetPositionEMBarycenter for a demo
Form
 [rB,vB,mu] = PlanetPositionEMBarycenter( action, d )
Inputs
 action (1,:) 'initialize' or 'update'
 d          (1,n) Julian date (days) for 'update' or  planet ids (1-9)
                 for initialize
Outputs
 rB      (3,n) Planetary position vectors
 vB     (3,n) Velocity vectors
 mu         (1,n) Corresponding gravitational parameters
References and().
Referenced by EnergyWRTMoon(), LETPhasing(), LowEnergyEarthToMoonTransfer(), MinE4BP(), PlotLET(), PlotLET3BP(), Propagate3BP(), Propagate4BP(), Targeting3BP2(), and Targeting4BP().
PlanetPosJPL()
function PlanetPosJPL (in action, in d, in ecl)
Gives the position vectors, gravitational parameters and velocity for the planets. The frame is heliocentric and can be either in the Earth's equatorial plane (default) or the ecliptic plane. Modeled after PlanetPosition.
 0. Sun (at origin)
 1. Mercury
 2. Venus
 3. Earth
 4. Mars
 5. Jupiter
 6. Saturn
 7. Uranus
 8. Neptune
 9. Pluto
 10. Geocentric Moon
 11. Earth-Moon Barycenter
This calls the function InterpolateState which returns planet states in the Earth equatorial frame and measured from the solar system barycenter. If necessary, this loads the file lnxp1600p2200.405 into InterpolateState.
You must first initialize this function with a set of planet IDs and then you can retrieve the states for a specific Julian date.
Form
 PlanetPosJPL( 'initialize', id )
 [r, mu, v] = PlanetPosJPL( 'update', jD, ecl )
Inputs
 action    (1,:)       'initialize' or 'update'
 id  or jD  (1,n)       Julian date (days) for update or planet ids
 ecl       (1,1)       Flag for ecliptic plane (1), default is equatorial (0)
Outputs
 r         (3,n)       Planetary position vectors
 mu        (1,n)       Corresponding gravitational parameters
 v         (3,n)       Velocity vectors
References and(), InterpolateState(), length(), PlanetPosJPL(), and zeros().
Referenced by CubeSatLunarEnvironment(), EclipseHelio(), FOrbitGeneral(), HelioPlot(), JDStartTransfer(), LunarTargeting(), PlanetHelioPhase(), PlanetPosJPL(), PlanetTrajectoryPlot(), PorkChopTOF(), RHSLunarMission(), RHSStateLunarMission(), RHSUKFCisLunarMission(), SailEphemAlmanac(), SailEphemJPL(), SolarSysJPL(), and TrajectoryBetweenTwoPlanets().
PlanetTrajectoryPlot()
function PlanetTrajectoryPlot (in xP, in jD0, in years, in p1, in p2)
Requires running PlanetPosJPL('initialize', [p1 p2]) first. THe beginning states are marked with "o" and the end states with "x".
Form
 PlanetTrajectoryPlot( xP, jD0, years, p1, p2 )
Inputs
 xP    (3,:)   Trajectory of spacecraft (km)
 jD0   (1,1)   Start Julian date (days)
 years (1,1)   Number of years in simulation (years)
 p1    (1,1)   Planet id 1 (1-9)
 p2    (1,1)   Planet id 2 (1-9)
Outputs
 hF   (1,1)    Figure handle
 hL   (1,:)    Line handles
References and(), Constant(), Date2JD(), Demo(), PlanetPosJPL(), PlanetTrajectoryPlot(), PlanetYear(), RVOrbGen(), Trajectory(), and zeros().
Referenced by PlanetTrajectoryPlot().
PlanetTransferLambert()
function PlanetTransferLambert (in jD, in dT, in planet1, in planet2, in doPlot)
Uses the almanac for the planet positions, see Planets. Computes the transfers using LambertTOF.
Form
 [dV, dVA, dVB, elT, tM] = PlanetTransferLambert( jD, dT, planet1, planet2 )
 [dV, dVA, dVB, elT, tM] = PlanetTransferLambert( jD, dT, planet1, el2 )
Inputs
 jD      (1,1) Start Julian date
 dT      (1,1) Transfer time (s)
 planet1    (1,:) Name of starting planet, or orbital elements at jD
   or el1       (1,6)
 planet2    (1,:) Name of ending planet, or orbital elements at jD
   or el2       (1,6)
 doPlot  (1,1) Flag to create plot
Outputs
 dV      (1,1) Total delta-V
 dVA     (1,1) First delta-V
 dVB     (1,1) Second delta-V
 elT     (1,6) Transfer elements [a i W w e M]
 tM      (1,1) Transfer type, 'direct' (1) or 'retrograde' (-1)
References Cross(), Date2JD(), Dot(), El2RV(), LambertTOF(), Mag(), Planets(), PlanetTransferLambert(), Plot3D(), RV2El(), RVFromKepler(), RVOrbGen(), set(), SolarSystemElements(), and square().
Referenced by LambertDoubleRendezvous(), and PlanetTransferLambert().
PlanetWithTerrain()
function PlanetWithTerrain (in h, in scale)
Adds a height map to a sphere to produce a 3D terrain map. theta needs to include 0 and pi. lambda should include 0 but not 2*pi.
scale exaggerates the surface variations from a sphere to make them easier to see.
Rendering the planet is done with patch.
patch('vertices',v,'faces',f,'facecolor',[0.5 0.5 0.5],...
 'facelighting','gouraud','linestyle','none');
axis equal ambient = 0.2; diffuse = 1; specular = 0.0; material([ambient diffuse specular])
Type PlanetWithTerrain for a model of the moon using Clementine data.
Form
 [v, f] = PlanetWithTerrain( h, f )
Inputs
 h   (.)     Height map data structure
             .r       (theta,lambda)   Distance from center
             .lambda     (1,:)            Equatorial angle
             .theta   (1,:)            Angle from pole
             .rEq     (1,1)            Equatorial radius (m)
             .name    (1,:)            Planet name
 scale (1,1) Exaggerate the terrain by this factor
Outputs
 v   (:,3) Vertices
 f   (:,3) Faces
References and(), Demo(), length(), NewFig(), PlanetWithTerrain(), RSHMoon(), TitleS(), Watermark(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by PlanetWithTerrain(), PlanetWithTerrainPatch(), and PlotLunarOrbit().
PlanetWithTerrainPatch()
function PlanetWithTerrainPatch (in h, in scale, in p)
Adds a height map to a sphere to produce a 3D terrain map.
scale exaggerates the surface variations from a sphere to make them easier to see.
Rendering the planet is done with patch.
patch('vertices',v,'faces',f,'facecolor',[0.5 0.5 0.5],...
 'facelighting','gouraud','linestyle','none');
axis equal ambient = 0.2; diffuse = 1; specular = 0.0; material([ambient diffuse specular])
This function will not handle the pole. use PlanetWithTerrain for orbits that go over the pole.
p is an optional 3xn array of position vectors to be plotted.
Type PlanetWithTerrainPatch for a model of the moon using Clementine data.
Form
 PlanetWithTerrainPatch( h, scale, p )
Inputs
 h     (.)   Height map data structure
             .r       (theta,lambda)   Distance from center
             .lambda     (1,:)            Equatorial angle
             .theta   (1,:)            Angle from pole
             .rEq     (1,1)            Equatorial radius (m)
             .name    (1,:)            Planet name
 scale (1,1) Exaggerate the terrain by this factor
 p     (3,:)    Line to plot
Outputs
 None
References and(), Demo(), isempty(), length(), NewFig(), PlanetWithTerrain(), PlanetWithTerrainPatch(), RSHMoon(), TitleS(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by PlanetWithTerrainPatch(), and Simulate3DLanding().
PlotBPlane()
function PlotBPlane (in r0, in v0, in rA, in vA)
Type PlotBPlane for a demo.
Form
 PlotBPlane( r0, v0, rA, vA )
Inputs
 r0 (3,1)   Position vector planet
 v0 (3,1)   Velocity vector planet
 rA (3,1)   Position vector asteroid
 vA (3,1)   Velocity vector asteroid
Outputs
 None
References Circle(), Constant(), Demo(), get(), HelioToBPlane(), Mag(), NewFig(), Normal(), PlotBPlane(), set(), Unit(), vector(), and VEscape().
Referenced by HelioToBPlane(), and PlotBPlane().
PlotLET()
function PlotLET (in elements, in dV1Eph, in det, in jDate, in muMoonMultiplier, in h)
Plot the Low Energy Transfer for a 4 body problem in a Non-Rotating Frame as well as in a Sun-Earth Rotating Frame. You must initialize the Barycenter using PlanetPositionEMBarycenter('initialize',[0, 3,10]);
Type PlotLET for a demo.
Form
 h = PlotLET(elements,dV1Eph,det,jDate,h)
Inputs
 elements                (1,6)  Ecliptic orbital elements of the initial state
 dV1Eph                  (1,1)  Magnitude of the initial burn
 det                     (1,1)  Transfer time
 jDate                   (1,1) Julian date
 muMoonMultiplier        (1,1) 0 to 1, for the purpose of easing between 3BP and 4BP
 h                       (1,2)  Optional. Figure handles to use for plots.
Outputs
 h         (1,2 Figure handles used for the plots.
References and(), Constant(), Demo(), El2RV(), Energy(), J20002RotPuls(), length(), Moons(), NewFig(), PlanetPositionEMBarycenter(), PlotLET(), Propagate4BP(), set(), Unit(), and zeros().
Referenced by LowEnergyEarthToMoonTransfer(), PlotLET(), and Targeting4BP().
PlotLET3BP()
function PlotLET3BP (in elements, in dV1Eph, in det, in jDate, in h)
For a 3 body problem in a Non-Rotating frame as well as in a Sun-Earth Rotating Frame. Create two windows.
Form
 [h,yVec,tVec] = PlotLET3BP(elements,dV1Eph,det,jDate,h);
Inputs
 elements   (1,6)   Ecliptic orbital elements of the intial state
 dV1Eph    (1,1)   Magnitude of the initial burn
 det       (1,1)   Transfer time
 h         (1,2)   Optional. Figure handles to use for plots.
Outputs
 h         (1,2)    Figure handles used for the plots.
 yVec      (6.:)    States in non-rotating frame
 tVec      (1,:)    Time vector
References Constant(), Demo(), El2RV(), Energy(), J20002RotPuls(), length(), Moons(), NewFig(), PlanetPositionEMBarycenter(), PlotLET3BP(), Propagate3BP(), set(), Unit(), vector(), and zeros().
Referenced by LowEnergyEarthToMoonTransfer(), PlotLET3BP(), and Targeting3BP2().
PorkChopMin()
function PorkChopMin (in dateRange, in tOFRange, in planet1, in planet2, in type, in doPlot)
Classic impulsive interplanetary trajectories have two minima, dubbed Type I and Type II. These correspond to trajectories with less than 180 degree arc and more than 180 degree arc, or the "short" and "long" way. Either the short or the long transfer may be the minimum delta-V for the launch opportunity. This routine computes the full Lambert solution including the launch geometry for each minima. If plots are requested, it will create the porkchop plot and plot the Lambert transfers.
Form
 [type1,type2] = PorkChopMin( dateRange,tOFRange, planet1, planet2, type, doPlot )
Inputs
 dateRange   (1,2)       [jDStart jDEnd]   (Julian date)
 tOFRange    (1,2)       [tOFStart tOFEnd] (days)
 planetDep   (1,:)       Departure planet  (Only major planets)
 planetArr   (1,:)       Arrival planet    (Only major planets)
 type        (1,1)       1: departure DV (default) 2: total DV
 doPlot      (1,1)       Create plots and text printout
Outputs
 type1        (.)        Short opportunity struct
                         .dV.total (1,1) Total DV (km/s)
                         .dV.a     (3,1) First DV (km/s)
                         .dV.b     (3,1) Second DV (km/s)
                         .jDDep    (1,1) Departure date
                         .jDArr    (1,1) Arrival date
                         .tOF      (1,1) Time of flight (days)
                         .tM       (1,1) Transfer flag (+/-1)
                         .rAL      (1,1) Launch ascension (rad)
                         .decL     (1,1) Launch declination (rad)
 type2        (.)        Long opportunity struct
See also
: PorkChopTOF, PorkChopPlot
References and(), Date2JD(), PorkChopMin(), PorkChopPlot(), and PorkChopTOF().
Referenced by PorkChopMin().
PorkChopPlot()
function PorkChopPlot (in dV, in jDDep, in jDArr, in titleStr)
Form
 PorkChopPlot( dV, jDDep, jDArr, titleStr )
Inputs
 dV          (nDate,nTOF)  Delta V required (km/s)
 jDDep       (nDate,nTOF)  Departure dates
 jDArr       (nDate,nTOF)  Arrival dates
References and(), Date2JD(), Demo(), get(), length(), NewFig(), PorkChopPlot(), PorkChopTOF(), set(), TitleS(), XLabelS(), and YLabelS().
Referenced by PorkChopMin(), PorkChopPlot(), and PorkChopTOFKepler().
PorkChopTOF()
function PorkChopTOF (in dateRange, in tOFRange, in planetDep, in planetArr, in nDate, in nTOF, in type)
dV row is a particular time of flight and column is a particular date. This function handles single arcs, multiple revolutions are not allowed. This function only handles the major planets (including Pluto.) The planets are entered as strings so the names can be displayed on the plot. If there are no outputs the function creates two plots, one of the porkchop and a second of the miniumum delta-V Lambert transfer.
The velocity may be departure only, type 1, or the total for both departure and arrival, type 2. Type 2 is the default.
Type PorkChopTOF for a demo of Earth to Mars trajectories in 2005.
Form
 [dV,tOF,jDDep,jDArr,tM] = PorkChopTOF(dateRange,tOFRange,planetDep,planetArr,nDate,nTOF,type)
Inputs
 dateRange   (1,2)         [jDStart jDEnd]   (Julian day number)
 tOFRange    (1,2)         [tOFStart tOFEnd] (days)
 planetDep   (1,:)         Departure planet  (Only major planets)
 planetArr   (1,:)         Arrival planet    (Only major planets)
 nDate       (1,1)         Number of dates   (default: 90)
 nTOF        (1,1)         Number of TOF     (default: 200)
 type        (1,1)         1: departure DV. 2: total DV (default)
Outputs
 dV          (nDate,nTOF)  Delta V required (km/s)
 tOF         (nDate,nTOF)  Time of flight
 jDDep       (nDate,nTOF)  Departure dates
 jDArr       (nDate,nTOF)  Arrival dates
 tM          (nDate,nTOF)  Transfer type. 1: <180 degrees, -1: >180 degrees
See also
: PlanetPosJPL, LambertTOF, DVTarget
References and(), Constant(), Date2JD(), Demo(), DVTarget(), isempty(), LambertTOF(), PlanetPosJPL(), Planets(), and PorkChopTOF().
Referenced by PorkChopMin(), PorkChopPlot(), PorkChopTOF(), and PorkChopTOFKepler().
PorkChopTOFKepler()
function PorkChopTOFKepler (in dateRange, in tOFRange, in planetDep, in planetArr, in nDate, in nTOF)
The delta velocity computed is the total for both departure and arrival. Each row of dV is a particular time of flight and column is a particular date. This function only handles single arcs. Multiple revolutions are not allowed. If there are no outputs the function creates two plots, one of the porkchop and a second of the miniumum delta-V Lambert transfer.
The departure planet can be any major planet (including Pluto) and is defined by name and ephemeris computed with PlanetPosJPL (ecliptic plane). The arrival planet is defined by Keplerian elements. For example, as done in the demo:
 dateRange = [Date2JD([2005 6 20]) Date2JD([2005 11 7])];
 tOFRange  = [125 450]; % days
 [elA, ~,~, jD] = ApophisOrbit;
 PorkChopTOFKepler(dateRange,tOFRange,'Earth',[elA jD]);
Type PorkChopTOF for a demo of Earth to Apophis trajectories.
 Usage:
 PorkChopTOFKepler;  % demo
 [dV,tOF] = PorkChopTOFKepler(dateRange,tOFRange,planetDep,planetArr,nDate,nTOF)
Inputs
 dateRange   (1,2)         [jDStart jDEnd] (Julian day number)
 tOFRange    (1,2)         [tOFStart tOFEnd] (days)
 planetDep   (1,:)         Departure planet (Only major planets)
 planetArr   (1,7)         [Arrival planet elements (6) jDEpoch (1)]
 nDate       (1,1)         Number of dates (default 90)
 nTOF        (1,1)         Number of TOF (default 200)
Outputs
 dV          (nDate,nTOF)  Delta V required (km/s)
 tOF         (nDate,nTOF)  Time of flight
 jDDep       (nDate,nTOF)  Departure dates
 jDArr       (nDate,nTOF)  Arrival dates
 tM          (nDate,nTOF)  Transfer type. 1: <180 degrees, -1: >180 degrees
References and(), ApophisOrbit(), Constant(), Date2JD(), Demo(), isempty(), Planets(), PlotLambertTransfer(), PorkChopPlot(), PorkChopTOF(), and PorkChopTOFKepler().
Referenced by PorkChopTOFKepler().
Propagate3BP()
function Propagate3BP (in y, in t0, in tF, in jDate, in stmcalc)
These are dimensional equations (mks) that use the JPL planetary ephemerides. PlanetPositionEMBarycenter must be initialized with the sun as the first body.
Type Propagate3BP for a demo.
Form
 [yvec, tvec] = Propagate3BP(y,t0,tF,jDate,stmcalc)
Inputs
 y       (6,1) Current state vector [r;v] (km;km/s)
 t0      (1,1) Initial time (s)
 tF      (1,1) Final time (s)
 jDate   (1,1) Julian date
 stmcalc    (1,1) true if propagating the STM, false otherwise
Outputs
 yvec    (6,:) State vector
 tvec    (1,:) Time vector
References Constant(), Demo(), Mag(), PlanetPositionEMBarycenter(), Plot3D(), Propagate3BP(), STM(), vector(), and zeros().
Referenced by PlotLET3BP(), Propagate3BP(), Propagate4BP(), and Targeting3BP2().
Propagate4BP()
function Propagate4BP (in y, in t0, in tF, in jDate, in stmcalc, in acc, in muMoonMultiplier)
These are dimensional equations (mks) that use the JPL planetary ephemerides. PlanetPositionEMBarycenter must be initialized with the sun, planet, and moon, as in
PlanetPositionEMBarycenter('initialize',[0 3 10]);
Form
 [yvec, tvec] = Propagate4BP(y,t0,tF,jDate,stmcalc,acc)
Inputs
 y                   (6,1) Current state vector [r;v]
 t0                  (1,1) Initial time
 tF                  (1,1) Final time
 jDate               (1,1) Julian date
 stmcalc             (1,1) 1 if propagating the STM, 0 otherwise
 acc                 (1,1) 1 if there is thrust, 0 if ballistic
 muMoonMultiplier    (1,1) 0 to 1, for the purpose of easing between 3BP and 4BP
Outputs
 yvec      (6,:) State vector
 tvec      (1,:) Time vector
See also
: PlanetPositionEMBarycenter, Propagate3BP
References abs(), and(), Constant(), Demo(), JD2000(), Mag(), PlanetPositionEMBarycenter(), Plot3D(), Propagate3BP(), Propagate4BP(), RHS(), STM(), vector(), and zeros().
Referenced by MinE4BP(), PlotLET(), Propagate4BP(), and Targeting4BP().
PropagateCRTBP()
function PropagateCRTBP (in y0, in t0, in tF, in mu, in stmcalc)
The default bodies are the earth and sun. It can propagate just the dynamical equations or the state transition matrix. These are nondimensional equations.
This is a special case of the general three-body problem where the primary and secondary bodies move in circular orbits about the common center of mass, and the effect of the gravitational attraction of the smallest body (i.e. a moon) is ignored. Propagation is done using ode113.
Type PropagateCRTBP for a demo of the Earth/Sun system.
Form
 [t, y] = PropagateCRTBP(y0,t0,tF,mu,stmcalc)
Inputs
 y0             (6,1)   Current state vector [r;v], nondimensional
 t0             (1,1)   Initial time
 tF             (1,1)   Final time
 mu             (1,1)   CRTBP mass parameter, muS/(muS+muP)
 stmcalc        (1,1)   true if propagating the STM, false otherwise
Outputs
 t               (1,:)  Time vector
 y               (6,:) State vector
References and(), Demo(), Plot2D(), PropagateCRTBP(), STM(), vector(), and zeros().
Referenced by IteratePeriodicOrbit(), LETGuess(), LowEnergyTransferInCRTBP(), PeriodicOrbitFromGuess(), PropagateCRTBP(), PropagateCRTBPToPeriapse(), PropagateCRTBPToXAxis(), and RefineXAxisIntercept().
PropagateCRTBPToPeriapse()
function PropagateCRTBPToPeriapse (in y, in t0, in tF, in mu)
Type PropagateCRTBPToPeriapse to see a demo of a stored orbit family.
Form
 [yF, tF] = PropagateCRTBPToPeriapse(y,t0,tF,mu)
Inputs
 y  (6,1) Current state vector [r;v] (coordinates are
           centered at the secondary body)
 t0 (1,1) Initial time
 tF  (1,1) Upper bound on final time
 mu  (1,1)  CRTBP mass ratio
Outputs
 yF (6,1) State at the periapse
 tF (1,1) Time at the periapse
References and(), isempty(), length(), Mag(), Plot2D(), PropagateCRTBP(), PropagateCRTBPToPeriapse(), vector(), and zeros().
Referenced by LowEnergyTransferInCRTBP(), and PropagateCRTBPToPeriapse().
PropagateNBody()
function PropagateNBody (in x0, in t, in mass, in name, in tol, in eps)
Inputs are the initial state vector, the time vector and the gravitational parameters.
The demo is earth orbit and another for Alpha-Centauri including A and B and a hypothetical planet at 1 AU from Alpha-Centauri A.
This function includes the right-hand-side and uses ode113 for propagation.
Form
 x = PropagateNBody( x0, t, mass, name, tol, eps )
Inputs
 x0             (6*n,1)  State vector [r;v;r;v;r;v...]
 t              (1,:)    Time vector
                (1,:)    Masses
 name           {:}      Name of body
 tol            (1,2)    [abs rel]
Outputs
 x              (6*n,:)     State vector
References: http://www.physics.buffalo.edu/phy302/topic1/index.html http://www.scholarpedia.org/article/N-body_simulations
References and(), and vector().
ReadAsteroidDatabase()
function ReadAsteroidDatabase (in a, in file)
Reads the file astorb.dat found at http://naic.edu/~nolan/astorb.html. A short version is included with the toolbox. For the full version you need to download astrob.dat and put it in your MATLAB path.
There are four ways of selecting asteroids:
 'all'               All of the asteroids in the database
 [1 7 300]           Selected lines in the database
 'ceres'             Name of one asteroid
 {'ceres' 'egeria'}  A cell array of names
If no outputs are given, it will display the asteroids and propagate them for one Earth year. It draws the orbits of the Earth and Jupiter for reference.
Type ReadAsteroidDatabase for a demo using astorbshort.dat.
Form
 [el, jD, name, id] = ReadAsteroidDatabase( 'all' )
 [el, jD, name, id] = ReadAsteroidDatabase( 'ceres' )
 [el, jD, name, id] = ReadAsteroidDatabase( [1 7 300] )
 [el, jD, name, id] = ReadAsteroidDatabase( {'ceres' 'netis'} )
 ReadAsteroidDatabase( 'ceres' ); % make plot
Inputs
 a     (-)     Asteroids to return (see above)
 file (1,:)    Optional file name
Outputs
 el    (:,6)      Elements
 jD    (:,1)      Julian date of epoch
 name  {:}     Names
 id    {:}     Id (may not be a number)
Reference: http://naic.edu/~nolan/astorb.html
References and().
RHS2DAnglePolarOrbit()
function RHS2DAnglePolarOrbit (in x, in ignoredArg, in d)
Inputs include the throttle and thrust angle. Default data structure is for Pluto. u is the radial direction and v is the tangent direction.
Form
 xDot = RHS2DPolarOrbit( x, t, d )
Inputs
 x     (4,1) [r;u;v;theta] [km;km/s;km/s;rad/s]
 t     (1,1) Time (s) (unused)
 d     (.)   Data structure describing spacecraft model
            .a    (1,1) Throttle
                .phi    (1,1) Angle from tangent (rad)
             .mu   (1,1) Gravitational parameter (km^3/s^2)
             .aMax (1,1) Maximum acceleration (km/s^2)
Outputs
 xDot  (4,1) [rDot;uDot;vDot;thetaDot] [km;km/s;km/s;rad/s]/s
Reference: Bryson, A, and Ho Yu-Chi, "Applied Optimal Control", Hemisphere, p 67.
References and(), RHS(), RHS2DAnglePolarOrbit(), and Throttle().
Referenced by ApproachConst2D(), ApproachConst2DIneq(), and RHS2DAnglePolarOrbit().
RHS2DCylindricalOrbit()
function RHS2DCylindricalOrbit (in x, in ignoredArg, in d)
Computes the right hand side for the planar dynamical equations with a central gravitational force. Includes time varying mass.
With no arguments it returns the data structure.
Form
 d     = RHS2DCylindricalOrbit;  % data structure
 xDot  = RHS2DCylindricalOrbit( x, ~, d )
Inputs
 x     (5,1) [u;v;r;m;theta] u = dr/dt
 t     (1,1) Time (unused)
 d     (.)   Data structure
             .uE     (1,1) Exhaust velocity (km/s)
             .mu     (1,1) Central force gravitational constant (m^3/s^2)
             .mD     (1,1) Dry mass (kg)
             .thrust    (1,1) Thrust (N)
             .phi   (1,1) Steering angle from tangential (rad)
Outputs
 xDot   (4,1) d[u;v;r;m;theta]/dt
References Constant(), RHS(), and RHS2DCylindricalOrbit().
Referenced by PlanarHelioOptimal(), PlanarHelioOptimalSlidingTime(), RHS2DCylindricalOrbit(), and SimulatePlanarHelioTrajectory().
RHSAlphaCentauriMission()
function RHSAlphaCentauriMission (in x, in t, in d)
Form
 xDot = RHSAlphaCentauriMission( x, t, d )
Inputs
 x              (7,:)    [r;v;m] Position, velocity, and spacecraft mass
                         in km, km/s, kg. If no thrust: set m=0.
 t              (1,1)    Time in seconds after jD0
 d              (1,1)    Structure
                         .center (1,1) 1 = sun, 2 = alpha-centauri
                         .thrust (1,3) Thrust vector in N (m>0 only)
                         .uE     (1,1) Exhaust velocity in m/s (m>0only)
                         .mDry   (1,1) Dry mass in kg (m>0 only)
Outputs
 xDot           (7,:)    [v;a;mDot], time derivative of each element of
                         x in km/s, km/s^2, kg/s
See also
AlphaCentauriFlight
References AlphaCentauriSystem(), and(), Mag(), RHSAlphaCentauriMission(), set(), SunV1(), and vector().
Referenced by RHSAlphaCentauriMission().
RHSCRTBP()
function RHSCRTBP (in t, in y, in mu)
 For arbitrary 'mu' parameter - smaller mass divided by total mass of system.
 Since version 9.
Form
 yDot = RHSCRTBP( t, y, mu )
Inputs
 t              (1,1)    Time (not used)
 y              (6,1)    State vector [r;v]
 mu             (1,1)    CRTBP mass ratio
Outputs
 yDot           (6,1)   Time derivative of the state vector
References Demo(), RHS(), RHSCRTBP(), vector(), and zeros().
RHSHelioWithPlanets()
function RHSHelioWithPlanets (in x, in t, in d)
 Uses the ephemerides from Planets and SolarSysState to compute
 the planet locations in the heliocentric frame.
 Since version 2014.1
 Forms:
[xDot, g] = RHSHelioWithPlanets(x, t, d)
Inputs
 x       (7,1)   State in the heliocentric frame [r;v;m]
 t       (1,1)   Time since jD0, sec
 d       (1,1)   Data structure
                 .mDry   (1,1) Dry mass (kg)
                 .thrust (3,1) Heliocentric thrust vector (N)
                 .uE     (1,1) Exhaust velocity (m/s)
                 .p      (1,1) Planet data structure
                 .jD0    (1,1) Julian date at the start of the
                               simulation
                 .muPlanet
Outputs
 xH      (7,1)   State in the heliocentric frame
 g       (1,1)   Output data structure
                 .accelSun     (3,1) Acceleration due to the sun
                 .accelThrust  (3,1) Acceleration due to the engine
                 .accelPlanet   (3,:) Acceleration due to planets
See also
APlanet
References and(), APlanet(), length(), Mag(), Planets(), RHSHelioWithPlanets(), SolarSysState(), vector(), and zeros().
Referenced by RHSHelioWithPlanets().
RHSMarsOrbit()
function RHSMarsOrbit (in x, in ignoredArg, in mu)
 Forms:
 xDot = RHSMarsOrbit( x, ~, mu )
Inputs
 x     (:,1)   State [rECI;vECI;...]
 t     (1,1)   Time (not used)
 mu    (1,1)   Gravitational constant
Outputs
 xDot  (:,1)   dx/dt
References Mag(), RHSMarsOrbit(), and zeros().
Referenced by RHSMarsOrbit().
RotPuls2J2000()
function RotPuls2J2000 (in stateIn, in primary, in muPrimary)
Transforms from a rotating frame centered on the secondary body of a sun/planet system to the J2000 reference frame with the same center.
Form
 stateOut = RotPuls2J2000( stateIn, primary, muPrimary);
Inputs
 stateIn          (6,1)    Current state vector [r;v]
 primary          (6,1)    State vector of Primary
 muPrimary         (1)     Gravitational Parameter of Primary
Outputs
 stateOut         (1,6)       Output state vector
References Coordinates(), Cross(), Mag(), Parameter(), RotPuls2J2000(), Unit(), and vector().
Referenced by LowEnergyEarthToMoonTransfer(), and RotPuls2J2000().
Simulate2DApproach()
function Simulate2DApproach (in t, in x0, in phi, in a, in d, in name)
Models a rocket with throttle approaching a point mass planet.
Form
 Simulate2DApproach( t, x0, phi, a, d, name )
Inputs
 t       (1,:)   Time vector
 x0      (4,1)   Initial state [r;u;v;theta]
 phi     (1,:)   Thrust angle (rad)
 a       (1,:)   Acceleration due to the rocket (0-1)
 d        (.)    Data structure describing spacecraft model
                 .mu   (1,1) Gravity
                .a    (1,1) Throttle (-1 to 1)
                 .aMax (1,1) Max accel
 name    (1,:)   Name for the plots
Outputs
 x       (4,:)   [r;v] Cartesian position and velocity (km,km/s)
References and(), Cross(), Demo(), Dot(), length(), Mag(), Plot2D(), RHS2DPolarOrbit(), RK4(), RK45(), Simulate2DApproach(), Throttle(), TimeLabl(), Trajectory(), Unit(), vector(), VInfRPToRV(), and zeros().
Referenced by Simulate2DApproach().
SimulatePlanarHelioTrajectory()
function SimulatePlanarHelioTrajectory (in mD, in mF, in thrust, in uE, in r0, in rT, in mu, in phi, in t)
Assumes a constant thrust with a planar angle of phi. If there are no outputs the function creates two plots, one a time history and the other a 2D trajectory.
Type SimulatePlanarHelioTrajectory for a constant thrust demo.
Form
 [xEnd,xCyl,fHat] = SimulatePlanarHelioTrajectory( mD, mF, thrust, uE, r0, rT, mu, phi, t )
Inputs
 mD      (1,1) Dry mass (kg)
 mF      (1,1) Fuel mass (kg)
 thrust  (1,1) Thrust (N)
 uE      (1,1) Exhaust velocity (km/s)
 r0      (1,1) Initial radius (km)
 rT      (1,1) Final radius (km)
 mu      (1,1)
 phi     (1,:)   Thrust angles (rad)
 t       (1,:+1) Corresponding times (s)
Outputs
 xEnd    (5,1) Final state [u,v,r,mF,theta]
 xCyl    (2,:) Cylindrical trajectory [r;theta]
 fHat    (2,:) Thrust direction
References and(), Constant(), Demo(), length(), RHS2DCylindricalOrbit(), RK4(), SimulatePlanarHelioTrajectory(), TimeLabl(), and zeros().
Referenced by PlanarHelioOptimal(), PlanarHelioOptimalSlidingTime(), and SimulatePlanarHelioTrajectory().
SolarSysJPL()
function SolarSysJPL (in id, in jD, in ecl)
If no outputs are given will plot the positions of the input planets. If no inputs are given it will compute the vectors for the entire solar system. Comparable to SolarSys. The default XY plane is Earth Mean Equator and Equinox of Reference Epoch (Earth equatorial). The origin is the center of the sun. Will create a plot when called without outputs.
Form
 [rx0, ry0, rz0, vx, vy, vz] = SolarSysJPL( id, jD, ecl )
Inputs
 id          (n,1)   Numeric ID of planet(s)
 jD          (m,1)   Julian dates
 ecl         (1,1)   Flag for ecliptic plane instead of equatorial
Outputs
 rx0           (n,m)   x component,  one row per planet (au)
 ry0           (n,m)   y component,  one row per planet (au)
 rz0           (n,m)   z component,  one row per planet (au)
 vx            (n,m)   vx component, one row per planet (km/s)
 vy            (n,m)   vy component, one row per planet (km/s)
 vz            (n,m)   vz component, one row per planet (km/s)
 n is the number of planets
See also
PlanetPosJPL.
References and(), CEcl2Eq(), Date2JD(), Demo(), Initialize(), InterpolateState(), length(), PlanetPosJPL(), SolarSys(), SolarSysJPL(), and zeros().
Referenced by SolarSysJPL().
SolarSysState()
function SolarSysState (in d, in jD)
The data structure is from Planets.
Form
 x = SolarSysState( d, jD )
Inputs
 d   (.)      Data structure
              .iv      (n,2)   Inclination wrt ecliptic plane     (rad)
              .Wv      (n,2)   Longitude of ascending node wrt vernal equinox  (rad)
              .wv      (n,2)   Argument of perhelion      (rad)
              .av      (n,2)   Mean distance (au)
              .ev      (n,2)   Eccentricity
              .Lv      (n,3)   Mean longitude (rad)
              .name    (n,:)   Name of planet
              .jdref   (1,1)   Reference Julian date
              .T       (1,:)   Julian centuries from J2000.0   (centuries)
 jD (1,:)     Julian date
Outputs
 x  (6,:,:)   [state,date,planet]
References JD2T(), length(), Planets(), SolarSys(), SolarSysState(), and zeros().
Referenced by PlanetHelioPhase(), RHSHelioWithPlanets(), SolarSysState(), and SolarSystemElements().
SphereOfInfluenceHelio()
function SphereOfInfluenceHelio (in k)
missions.
 planet                    sun
 ?-------------------------?
 |<---------- 1 ---------->|
 |----->|
 rOR
Form
 rOR = SphereOfInfluenceHelio( k )
Inputs
 k    (1,:) Planet ID 1 = Mercury 9 = Pluto
Outputs
 rOR    (:)  Ratio of sphere of influence for the planet to
          distance between the planet and sun
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 288-291.
References and(), set(), and SphereOfInfluenceHelio().
Referenced by SphereOfInfluenceHelio().
SynodicPlanets()
function SynodicPlanets (in planet1, in planet2, in jD)
 Type SynodicPlanets for an example in Jupiter orbit.
 Since version 2014.1
Form
 p = SynodicPlanets( planet1, planet2, jD )
Inputs
 planet1   (1,:)   Starting planet name
 planet2   (1,:)   Target planet name
 jD        (1,1)   Julian date
Outputs
 p        (1,1)   Synodic period
See also
Planets, SolarSystemElements, SynodicFromSemimajorAxes
References and(), Constant(), Demo(), JD2000(), Planets(), SolarSystemElements(), SynodicFromSemimajorAxes(), and SynodicPlanets().
Referenced by LambertDoubleRendezvous(), and SynodicPlanets().
Targeting3BP2()
function Targeting3BP2 (in elements, in dV1Eph, in dt, in et, in muMoon, in jDate)
Form
 [elementsNew,dV1EphNew] = Targeting3BP2(elements,dV1Eph,dt,et,muMoon)
Inputs
 elements       (1,6) Ecliptic orbital elements of the initial state
 dV1Eph         (1,1) Magnitude of the initial burn
 dt            (1,1) Transfer time
 et            (1,1) Seconds after the Epoch at which the transfer
                           is initiated
 muMoon         (1,1) Gravitational parameter of the Moon
 jDate         (1,1) Julian date
Outputs
 elementsNew    (1,6) Converged ecliptic orbital elements
 dV1EphNew      (1,1) Converged maneuver magnitude
References CheckForOptimizationToolbox(), Constant(), Demo(), El2RV(), J20002RotPuls(), Mag(), PlanetPositionEMBarycenter(), PlotLET3BP(), Propagate3BP(), Targeting3BP2(), and Unit().
Referenced by LowEnergyEarthToMoonTransfer(), and Targeting3BP2().
Targeting4BP()
function Targeting4BP (in elements, in dV1Eph, in dtTarg, in et, in p, in jDate, in muMoonMultiplier, in muPlanet)
Form
 [elementsNew,dV1EphNew,dtNew,exitflag] = Targeting4BP(elements,dV1Eph,
 dtTarg,et,p,jDate,muPlanet)
Inputs
 elements          (1,6) Ecliptic orbital elements of the initial state
 dV1Eph            (1,1) Magnitude of the initial burn
 dtTarg            (1,1) Transfer time
 et                (1,1) Seconds after the Epoch at which the transfer
                         is initiated
 p                 (1,1) Distance from the moon to L2
 jDate             (1,1) Julian date
 muMoonMultiplier  (1,1) 0 to 1, parameter to ease between 3BP and 4BP
 muPlanet          (1,1) Gravitational parameter of the planet
Outputs
 elementsNew       (1,6) Converged ecliptic orbital elements
 dV1EphNew         (1,1) Converged maneuver magnitude
 dtNew             (1,1) Converged transfer time
 exitflag          (1,1) 1 if successful
References and(), CheckForOptimizationToolbox(), Constant(), Demo(), El2RV(), Mag(), PlanetPositionEMBarycenter(), PlotLET(), Propagate4BP(), Targeting4BP(), and Unit().
Referenced by LowEnergyEarthToMoonTransfer(), and Targeting4BP().
TitanAtmosphere()
function TitanAtmosphere (in h)
Type TitanAtmosphere for a demo. The data extends through 1300 km altitude and is interpolated beyond that.
Requires the mat file TitanDensityData.mat
Form
 TitanAtmosphere( h )
Inputs
 h          (1,:) Altitude (km)
Outputs
 rho        (1,:) Density (kg/m^3)
References Altitude(), and(), isempty(), Plot2D(), and TitanAtmosphere().
Referenced by TitanAtmosphere().
TrajectoryBetweenTwoPlanets()
function TrajectoryBetweenTwoPlanets (in jD0, in planet1, in planet2, in years, in n, in opts, in nRSim)
Uses the JPL ephemerides. planet2 can be a number from 1-9 or a data structure. This stops at the target. The objective, which is minimized, is the total acceleration required. Generates a trajectory plot.
Type TrajectoryBetweenTwoPlanets for two demos: Earth to Mars using both JPL ephemerides, and Earth to Pluto using a data structure for planet2.
Form
 s = TrajectoryBetweenTwoPlanets( jD0, planet1, planet2, years, n, opts, nRSim )
Inputs
 jD0       (1,1)  Start Julian Date
 planet1   (1,1)  Id of departure planet (1-9)
 planet2    (1,1)  Id of arrival planet (1-9) or data structure
                  .name (1,:) Name
                  .el   (1,6) Orbital elements - epoch must be jD0
 years      (1,1)  Mission duration (years)
 n         (1,1)  Number of steps in solution
 opts       (.)    Data structure for fmincon
 nRSim     (1,1)  Ratio of sim points to optimization points
Outputs
 s         (.)   Output structure
                 .x    (6,:)  States
                 .a    (3,:)  Acceleration vector (km/s^2)
                 .jD0  (1,:)  Julian date
                 .t    (1,:)  Elapsed time (s)
See also
: FindDepartureDate
References and(), Constant(), Date2JD(), Demo(), FindDepartureDate(), isempty(), PlanetPosJPL(), RHSOrbit(), RV2El(), TrajectoryBetweenTwoPlanets(), and vector().
Referenced by FindDepartureDate(), and TrajectoryBetweenTwoPlanets().
TrueAnomalyStartHyperbola()
function TrueAnomalyStartHyperbola (in a, in e, in t, in nu2, in mu)
Utilizes fminbnd to find the solution. Type TrueAnomalyStartHyperbola for a demo in lunar orbit.
Form
 nu1 = TrueAnomalyStartHyperbola(a,e,t,nu2,mu)
Inputs
 a   (1,1)   Semi-major axis
 e      (1,1)   Eccentricity
 t   (1,1)   Time of flight
 nu2    (1,1)   True anomaly (rad)
 mu  (1,1)   Gravitational parameter
Outputs
 nu1    (1,1)   True anomaly (rad)
References abs(), Demo(), RHS(), TimeOfFlightHyperbola(), and TrueAnomalyStartHyperbola().
Referenced by TrueAnomalyStartHyperbola().
TwoDEscape()
function TwoDEscape (in mu, in rI, in uE, in thrust, in m0, in mF, in rB, in planet)
Treat the problem as planar. Creates a plot of the simulated spiral and a time history plot of the delta-V, fuel consumed, and orbit eccentricity. You can add radiation belts to any planet, though not all have radiation belts. The spiral into orbit is the same.
Form
 [mX, xP, t] = TwoDEscape( mu, rI, uE, thrust, m0, mF, rB, planet )
 Inputs
 mu     (1,1) Gravitational parameter
 rI     (1,1) Initial radius (km)
 uE     (1,1) Exhaust velocity (m/s)
 thrust (1,1) Thrust (N)
 m0     (1,1) Dry mass  (kg)
 mF     (1,1) Fuel mass  (kg)
 rB     (1,2) Radiation belt start/stop
 planet (1,:) Planet name
 Outputs
 mX     (1,1) Fuel consumed (kg)
 xP     (6,n) State vector [r;v]
 t      (1,n) Time vector corresponding to xP (s)
References and(), Demo(), El2RV(), LowThrustEscape(), Period(), Plot2D(), RHS2DOrbit(), RK4(), RV2El(), RVOrbGen(), TimeLabl(), Unit(), vector(), Watermark(), and zeros().
UranusAirshipSizing()
function UranusAirshipSizing (in h, in m0)
A simple mass balance is applied. For neutral buoyancy, the total mass of the vehicle must equal the mass of the atmospheric gas displaced. In this case, the total mass of the vehicle is approximated as:
 Vehicle Mass = Payload Mass + Hull Fabric Mass + Lifting Gas Mass
Assume the lifting gas is Hydrogen.
Assume a fixed chemical content of atmosphere, constant at all
altitudes. 82.5% H, 15.2% He, 2.3% Methane.
Assume a spherical shape for the balloon to compute volume and
surface area as a function of the sphere radius.
Type UranusAirshipSizing for a demo.
Form
 d = UranusAirshipSizing( h, m0 )
Inputs
 h       (1,n)     Altitude vector (km).
 m0      (1,m)     Payload mass vector (kg).
Outputs
 d       (.)       Data structure with information including:
                     .h            (1,n)   Altitude vector input
                     .m0           (1,m)   Payload mass vector input
                     .massAir      (m,n)   Mass of air (kg)
                     .massGas      (m,n)   Mass of lifting gas (kg)
                     .massHull     (m,n)   Mass of fabric hull (kg)
                     .massVehicle  (m,n)   Mass of vehicle (kg)
                     .sigmaFabric  (1,1)   Areal density of fabric
                     .R            (m,n)   Radius of balloon (m)
                     .S            (m,n)   Surface area of balloon (m^2)
                     .V            (m,n)   Volume of balloon (m^3)
                     .rhoA         (1,n)   Density of air across
                                             altitude (kg/m^3)
Reference: Uranus Fact Sheet https://nssdc.gsfc.nasa.gov/planetary/factsheet/uranusfact.html
See also
: NeptuneAirshipSizing, UranusDensity
References Altitude(), and(), Demo(), length(), NeptuneAirshipSizing(), UranusAirshipSizing(), and vector().
Referenced by UranusAirshipSizing().
V0FromJacobiConstant()
function V0FromJacobiConstant (in x0, in j, in mu)
Calculate an initial velocity in the y-direction from the jacobi constant and the position on the x-axis
Type V0FromJacobiConstant for a demo.
Form
 vY0 = V0FromJacobiConstant(x0,J,mu)
Inputs
 x0 (1,1)   Position on the x-axis
 j   (1,1)  Jacobi constant
 mu (1,1)   CRTBP mass parameter
Outputs
 vY0    (1,1)   Initial velocity in the y direction
References and(), Constant(), CRTBPJacobiConstant(), Demo(), and V0FromJacobiConstant().
Referenced by LETGuess(), and V0FromJacobiConstant().