PSS MATLAB Toolboxes: Propulsion Functions
Propulsion Functions
Propulsion Module
The Propulsion module functions.
Directories
directory Chemical
Hydrocarbon and hydrogen rockets.
directory Electric
Electric thruster models and design functions.
directory Gas
Gas mixture properties.
directory MultiStage
Multiple stage rocket calculations.
directory Nuclear
Nuclear thermal rocket.
directory Rocket
Rocket and plume models.
directory Utilities
Propulsion utilities.
Description
Functions
function AreaRatioFromMach (in M, in gamma)
Computes the area ratio from Mach Number.
function BloDownMass (in mPress, in rhoFuel, in vTank, in rPress, in T, in p)
Generates a blowdown curve of mass vs pressure.
function ColdGas (in s, in aStar, in p0, in pA, in t0, in e)
Determines performance of a cold gas rocket.
function CombTemp (in nR, in nP, in hR, in hP, in cPP)
Computes the combustion temperature of a gas mixture.
function DesignUpperStage (in d, in fileName)
Design an upper stage using RocketMass and create a CAD model.
function ElectricPropulsionDesign (in x, in doPlot)
Design an electric propulsion system.
function ElectricThrust (in Isp, in power, in eff)
Compute the electric propulsion thrust from power and specific impulse.
function ElectricThrusterPower (in Isp, in T, in eff)
Compute the electric propulsion power from thrust and specific impulse.
function EP2M (in e, in p, in mPayload)
Converts structural and payload ratios into masses.
function EPPS (in npp, in ms0, in ms1, in m02, in mp0, in mp1, in v0, in v1)
Payload and structural mass ratios for parallel stages.
function EVToV (in atom, in eV)
Convert electron volts to velocity.
function FElectricPropulsion (in uE, in sF, in sP, in mP, in eta, in f, in dV)
Computes the total mass, fuel mass and power for an electric thruster.
function Fuels (in fuel)
Computes molecular weight, ratio of specific heats and gas constant.
function Gamma (in cP, in n)
Computes the ratio of specific heats of a gas mixture.
function GasMass (in vTank, in mWt, in T, in p)
Generates a blowdown curve of mass vs pressure.
function HallThrusterArray (in w)
Create a PPPL Hall thruster array picture.
function IdealRkt (in g, in aStar, in p0, in pA, in t0, in e, in m)
Computes the thrust and exhaust velocity for an ideal rocket.
function IsentropicExpansion (in M, in gamma)
Computes isentropic expansion.
function Isp2V (in iSP, in g)
Compute specific impulse from exhaust velocity.
function KEVToJ (in keV)
Convert keV to J.
function M2EP (in m0, in mF, in mPayload)
Converts masses to structural and payload ratios.
function M2MS (in m0, in mF, in mPayload)
Converts total, final and payload masses to stage masses and ratios.
function MachFromAreaRatio (in aR, in gamma)
Computes the Mach number from area ratio.
function MachNumber (in u, in gamma, in molWt, in T)
Compute the Mach number.
function MassEquivalentDV (in dV, in uE, in mI, in thrust)
Computes the constant mass that will produce the same delta-V.
function MassVolH2O2 (in m, in fR, in type)
H2/O2 mass and volume.
function MinimumExhaustVelocity (in sR, in dV)
Finds the minimum exhaust velocity based on the structural ratio.
function MolWt (in m, in n)
Computes the molecular weight of a gas mixture.
function MS2M (in mS, in eS, in mPayload)
Converts stage and payload masses to total masses and final masses.
function MSTOR (in e, in p, in v, in mPayload)
Computes the multistage tradeoff ratios.
function NuclearThermalUE (in t, in fuel)
Compute the exhaust velocity for a nuclear rocket with H2 fuel.
function OptimalVehicle (in x, in doPlot)
Finds an electric thrust propelled mass-optimal vehicle.
function Plume (in thrust, in rREA, in tREA, in uREA, in gREA, in normal, in r, in area, in tArea, in angInf, in sigma)
Compute the plume forces and torques on a set of elemental areas.
function QRFuel (in fuel)
The lower heating value for fuels.
function QRHydrocarbon (in n, in m)
The lower heating value for a hydrocarbon fuel.
function QRHydrogen ()
The lower heating value for H2 + 1/2 O2 -> H20.
function RocketChemical (in p0, in pA, in aStar, in aE, in qR, in gamma, in f, in throttle)
Computes the thrust and exhaust velocity of a chemical rocket.
function RocketFromUEAndT (in uE0, in uEA, in t0, in tA, in pA, in p)
Computes the thrust and exhaust velocity as a function of pressure.
function RocketH2O2 (in p0, in pA, in aStar, in aE, in f, in tP)
H2/O2 rocket model.
function RocketMass (in Isp, in mP, in fS, in dV)
Compute masses for a single stage to produce the required delta-v.
function RocketModel (in h, in iSpR, in thrustR, in pR, in atmData)
Generic rocket model as a function of altitude.
function RocketVariableUEAndT (in uE0, in t0, in uE)
Computes the thrust and exhaust velocity given one pair [uE0,t0].
function SolidR (in g, in t0, in aStar, in a, in n, in R, in sigmaP, in dT, in rhoP, in mP0, in cAB, in nAB, in rM, in l, in x)
Computes the right hand side of the dynamical equations for a solid rocket engine.
function SolidRocketInertia (in mDot, in a, in b, in rho, in h)
Computes the inertia and inertia derivative for a solid rocket.
function SpecificPower (in powerPlant, in engine)
Computes the specific power of engine/power plant combinations.
function SpeedSnd (in gamma, in molWt, in T)
Compute the speed of sound.
function SphericalTankFluidHeight (in vT, in vF)
Compute the height of fuel in a spherical fuel tank.
function TCoeff (in g, in e, in p)
Computes the ideal thrust coefficient for a nozzle with a diverging portion.
function TElec (in T, in molWt, in gamma, in eff, in TC, in p)
Computes the thrust and specific impulse of an electric thruster.
function ThrusterLayout (in action, in varargin)
Tool for thruster layout.
function ThrustToAStar (in fuel, in thrust, in p0, in pA, in e)
Computes throat area (A*) for a given thrust.
function TVDesign (in mPayload, in dV, in thrust, in eff, in sR, in pR)
Design an electric transfer vehicle from delta-V.
function UE (in gamma, in m, in t0, in p0, in pE)
Computes the ideal exhaust velocity of a rocket.
function UEO2H2 (in n, in t0, in p0, in pE)
Computes the exhaust velocity of a O2/H2 rocket.
function UEQR (in qR, in gamma, in p0, in pE)
Computes the exhaust velocity of a rocket from fuel lower heating value.
function V2Isp (in v, in g)
Compute specific impulse from exhaust velocity.
function VolumeToDimension (in v, in type, in aR)
Computes the dimensions of a tank.
function VolumeToPressureBD (in vT, in vF, in pI)
Generates the final pressure.
function VToEV (in atom, in v)
Convert velocity to electron volts.
Function Documentation
AreaRatioFromMach()
function AreaRatioFromMach (in M, in gamma)
Type AreaRatioFromMach for a demo.
Form
 M = AreaRatioFromMach( aR, gamma )
Inputs
 M             (1,:)   Mach number
 gamma         (1,1)   Ratio of specific heats
Outputs
 aR            (1,:)   Area ratio Exit Area/Throat Area
References: Hill, P.G., Peterson, C. R., "The Mechanics and Thermodynamics of Propulsion," Addison-Wesley Publishing
Company, 1970, p. 49.
References AreaRatioFromMach(), Demo(), and Plot2D().
Referenced by AreaRatioFromMach(), MachFromAreaRatio(), and RocketH2O2().
BloDownMass()
function BloDownMass (in mPress, in rhoFuel, in vTank, in rPress, in T, in p)
Type BloDownMass for a demo.
Form
 mFuel = BloDownMass( mPress, rhoFuel, vTank, rPress, T, p )
Inputs
 mPress      (1,1)    Mass of pressurant
 rhofuel     (1,1)    Density of the fuel
 vTank       (1,1)    Tank volume
 rPress      (1,1)    Gas constant of pressurant (default is helium)
 T           (1,1)    Temperature (deg-K)
 p           (1,:)    Pressure
Outputs
 mFuel        (1,:)   Mass of the fuel
References BloDownMass(), isempty(), MolWt2R(), Plot2D(), and Pressure().
Referenced by BloDownMass().
ColdGas()
function ColdGas (in s, in aStar, in p0, in pA, in t0, in e)
Thrust and mDot are functions of (p0,e). All inputs are mks. You need to compute p0 and t0 from the volume of the tank, mass of fuel and temperature.
Type ColdGas for a demo.
Form
 [thrust, iSP, rho, mDot] = ColdGas( s, aStar, p0, pA, t0, e )
Inputs
 s             (1,:) Gas to be used.
 aStar         (1,1) Throat area (m^2)
 p0            (n)   Chamber pressure after heating (N/m^2)
 pA            (1,1) Ambient pressure (N/m^2)
 t0            (1,1) Temperature after heating (deg-K)
 e             (1,1) Area ratio
Outputs
 thrust       (n,m)  Thrust level (N)
 iSP          (m)    Specific impulse (sec)
 rho          (n)    Gas density (kg/m^3)
 mDot         (n)    Mass flow (kg/sec)
References and(), ColdGas(), Demo(), GasProperties(), IdealRkt(), Plot2D(), and Pressure().
Referenced by ColdGas(), and ThrusterColdGas().
CombTemp()
function CombTemp (in nR, in nP, in hR, in hP, in cPP)
Form
 t = CombTemp( nR, nP, hR, hP, cPP )
Inputs
 nR            (n)     Number of moles of each reactant
 nP            (m)     Number of moles of each product
 hR            (n)     Heat of formation of each reactant
 hP            (m)     Heat of formation of each product
 cPP           (m)     Heat capacity of each product
Outputs
 t                     Combustion temperature
References: Martinez-Sanchez, M. "16.53 Course Notes" M.I.T. 1979.
References length().
DesignUpperStage()
function DesignUpperStage (in d, in fileName)
Creates four components, oxidizer tank, fuel tank, shell and engine nozzle. The origin is at the base of the nozzle.
Form
 g = DesignUpperStage( d, fileName )
Inputs
 d        (.)  Data structure
               .name    (1,:) Model name
               .mR      (1,1) Mixture ratio fuel/oxidizer
               .sR      (1,1) Structural ratio
               .mF      (1,1) Fixed mass including payload
               .rhoO    (1,1) Density oxidizer
               .rhoF    (1,1) Density fuel
               .iSp     (1,1) Specific impulse
               .dV      (1,1) Delta-V (km/s)
               .nD      (1,1) Nozzle diameter
               .nL      (1,1) Nozzle Length
               .eR      (1,1) Nozzle exit ratio
               .aR      (1,1) Vehicle length/width
 fileName (1,:) Create an obj file filename.obj (optional)
Outputs
 g       (.)    CAD data structure
References and(), BuildCADModel(), CreateBody(), Demo(), DesignUpperStage(), Initialize(), length(), RocketMass(), and set().
Referenced by DesignUpperStage().
ElectricPropulsionDesign()
function ElectricPropulsionDesign (in x, in doPlot)
Uses the payload mass, the required delta-V, the required thrust, the ratio of structure to fuel mass (for tanks, etc.) and the power per unit mass. It will check to see the the input exhaust velocity is less than the minimum based on the structural ratio.
Type ElectricPropulsionDesign for a demo.
Form
 ElectricPropulsionDesign;   % demo
 x = ElectricPropulsionDesign;   % input data structure
 d = ElectricPropulsionDesign( x, doPlot )
Inputs
 x               (.)    Data structure
                      .dV     Total delta V capability (m/sec)
                      .uE     Exhaust velocity (m/sec)
                      .pR     Power to propulsion system mass ratio (w/kg)
                      .sR     Structural mass to fuel ratio
                      .mP     Payload mass (kg)
                      .thrust Thrust (N)
 doPlot       (1)    Flag to create plot
Outputs
 d            (.)    Data structure additions
                      .mT     Total mass
                      .mS     Structural mass
                      .mR     Propulsion system mass
                      .mF     Fuel mass
                      .mD     Dry mass
                      .power  Total power (w)
References and(), Demo(), ElectricPropulsionDesign(), length(), MinimumExhaustVelocity(), and Plot2D().
Referenced by ElectricPropulsionDesign(), OptimalVehicle(), and TVDesign().
ElectricThrust()
function ElectricThrust (in Isp, in power, in eff)
The governing equations are:
 T = mdot*ue
 eff*P = 0.5*mdot*ue^2
so that eff*P is the jet power that is converted to kinetic energy.
Type ElectricThrust for a demo at 100 kW.
Form
 [thrust,mdot] = ElectricThrust( Isp, power, eff )
Inputs
 Isp     (1,:)    Specific impulse, sec
 power   (1,1)    Engine power, W
 eff     (1,1)    Thrust efficiency
Outputs
 thrust (1,:)    Engine power, W
 mdot   (1,:)    Mass flow rate, kg/s
References and(), Demo(), ElectricThrust(), and Plot2D().
Referenced by ElectricThrust().
ElectricThrusterPower()
function ElectricThrusterPower (in Isp, in T, in eff)
The governing equations are:
 T = mdot*ue
 eff*P = 0.5*mdot*ue^2
so that eff*P is the jet power that is converted to kinetic energy.
Type ElectricThrusterPower for a demo at 5000 sec Isp.
Form
 [power,mdot] = ElectricThrusterPower( Isp, T, eff )
Inputs
 Isp   (1,:)    Specific impulse, sec
 T     (1,:)    Thrust, N
 eff   (1,1)    Thrust efficiency, default 1
Outputs
 power (1,:)    Engine power, W
 mdot  (1,:)    Mass flow rate, kg/s
References and(), Demo(), ElectricThrusterPower(), and Plot2D().
Referenced by ElectricThrusterPower().
EP2M()
function EP2M (in e, in p, in mPayload)
 1 2 3 4 ... payload
Form
 [m0, mf] = EP2M( e, p, mpayload )
Inputs
 e         (1,:) Stage structural ratios
 p          (1,:) Stage payload ratios
 mpayload   (1,1) Payload mass
Outputs
 m0         (1,:) Total mass of each stage (including everything above)
 mf         (1,:) Final mass of each stage (including everything above)
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 199-202.
References and(), and length().
Referenced by MSTOR().
EPPS()
function EPPS (in npp, in ms0, in ms1, in m02, in mp0, in mp1, in v0, in v1)
Form
 [e, p, m00, m01] = EPPS( npp, ms0, ms1, m02, mp0, mp1, v0, v1 )
Inputs
 npp         (1,1)  Fraction of 1st stage fuel burned in parallel with
             (1,1)  0th stage
 ms0         (1,1)  Structural mass of 0th stage
 ms1         (1,1)  Structural mass of 1st stage
 m02         (1,1)  Payload of 1st stage
 mp0         (1,1)  Propellant used during 0th stage burn
 mp1         (1,1)  Total propellant in the 1st stage
 v0          (1,1)  Exhaust velocity of 0th stage
 v1          (1,1)  Exhaust velocity of 1st stage
Outputs
 e           (1,1)  Stage structural ratios
 p           (1,1)  Stage payload ratios
 m00         (1,1)  Total vehicle mass
 m01         (1,1)  Mass of 1st stage after separation
References and().
EVToV()
function EVToV (in atom, in eV)
Type EVToV for a demo.
Form
 v = EVToV( atom, eV )
Inputs
 atom          {:}    Atom name see AtomicMass
 eV            (1,:)  Energy (eV)
Outputs
 v             (1,:)  Velocity (km/s)
References EVToV().
Referenced by EVToV().
FElectricPropulsion()
function FElectricPropulsion (in uE, in sF, in sP, in mP, in eta, in f, in dV)
Form
 [mT, mF, p] = FElectricPropulsion( uE, sF, sP, mP, eta, f, dV )
Inputs
 uE         (1,:) Exhaust velocity (m/s)
 sF         (1,1) Structural mass ratio (mass structure/mass fuel)
 sP         (1,1) Specific power (mass power/watt)
 mP         (1,1) Payload mass (kg)
 eta        (1,1) Efficiency
 f          (1,1) Thrust (N)
 dV         (1,1) Delta v (m/s)
Outputs
 mT         (1,:) Total mass (kg)
 mF         (1,:) Fuel mass (kg)
 p          (1,:) Power (W)
References and(), Demo(), FElectricPropulsion(), length(), Plot2D(), and zeros().
Referenced by FElectricPropulsion().
Fuels()
function Fuels (in fuel)
Compute parameters for some well known fuels. All are for frozen flow. If no arguments are entered it will list all possible fuels. You may enter a number for fuel or a name, which is not case sensitive.
Form
 Fuels;         % List fuels
 [m, g, r, s] = Fuels( fuel )
Inputs
 fuel        (1,:)  Fuel ID or fuel name
Outputs
 m           (1,1)  Molecular weight
 g           (1,1)  Ratio of specific heats
 r           (1,1)  Gas constant
 s           (1,1)  Fuel
References and(), and Fuels().
Referenced by Fuels(), and NuclearThermalUE().
Gamma()
function Gamma (in cP, in n)
Form
 [gammaM, nM] = Gamma( cP, n )
Inputs
 cP            (:)     Specific heats of the constituents (cal/mole deg K)
 n             (:)     Number of moles of each constituent
Outputs
 gammaM        (:)     Ratio of specific heat of the mixture (cal/mole deg K)
 nM            (:)     Number of moles in the mixture
References: Martinez-Sanchez, M. "16.53 Course Notes" M.I.T. 1979.
References length().
Referenced by AerodynamicShockMinimize(), AtmGamma(), CollisionMonitor(), CollisionMonteCarlo(), GuidedLaunchOpt2D(), MachFromPR(), PressureRatioFromTemp(), RateOfClimb(), RFromCPAndGamma(), RocketH2O2(), TempRatioFromMachAndGamma(), TempRatioFromPressure(), UE(), and UEO2H2().
GasMass()
function GasMass (in vTank, in mWt, in T, in p)
Form
 [mFuel, density] = GasMass( vTank, mWt, T, p )
Inputs
 vTank        (1,1)   Tank volume
 mWt          (1,1)   Molecular weight of the fuel (default is xenon)
 T            (1,1)   Temperature (deg-K)
 p            (1,:)   Pressure
Outputs
 mFuel        (1,:)   Mass of the fuel
 density      (1,:)   Density of the fuel
References isempty(), MolWt2R(), Plot2D(), and Pressure().
HallThrusterArray()
function HallThrusterArray (in w)
Form
 [v, f] = HallThrusterArray( w )
Inputs
 w         (1,1)  Width
Outputs
 v          (:,3) Vertices
 f          (:,3) Faces
References Box(), Frustrum(), HallThrusterArray(), Mag(), NewFig(), set(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by HallThrusterArray().
IdealRkt()
function IdealRkt (in g, in aStar, in p0, in pA, in t0, in e, in m)
p0 or e may be vectors. If p0 or e is an array then the other will be turned into an array of equal length. Type IdealRkt for a demo.
Form
 [thrust, uE, iSP, cT, pRatio] = IdealRkt( g, aStar, p0, pA, t0, e, m )
Inputs
 g            (1,1)  Ratio of specific heats
 aStar        (1,1)  Throat area (m^2)
 p0           (1,n)  Chamber pressure after heating (N/m^2)
 pA           (1,1)  Ambient pressure (N/m^2)
 t0           (1,1)  Temperature after heating (deg-K)
 e            (m)    Area ratio (exit area/throat area)
 m            (1,1)  Molecular weight (kg/mole)
Outputs
 thrust       (n,m)  Thrust level (N)
 uE           (n)    Exhaust velocity (m/sec)
 iSP          (n)    Specific impulse (sec)
 cT           (m)    Thrust coefficient
 pRatio       (m)    Pressure ratio
References and(), IdealRkt(), length(), Mesh2(), MolWt2R(), Plot2D(), Pressure(), TCoeff(), and V2Isp().
Referenced by ColdGas(), CubeSatPropulsion(), IdealRkt(), and ThrusterColdGas().
IsentropicExpansion()
function IsentropicExpansion (in M, in gamma)
Type IsentropicExpansion for a demo.
Form
 [pR, rhoR, tR] = IsentropicExpansion( M, gamma )
Inputs
 M             (1,:)   Mach number
 gamma         (1,1)   Ratio of specific heats
Outputs
 pR            (1,1)   p0/p
 rhoR          (1,1)   rho0/rho
 tR            (1,1)   t0/t
References: Hill, P.G., Peterson, C. R., "The Mechanics and Thermodynamics of Propulsion," Addison-Wesley Publishing
Company, 1970, p.47.
References Demo(), IsentropicExpansion(), and Plot2D().
Referenced by IsentropicExpansion(), and RocketH2O2().
Isp2V()
function Isp2V (in iSP, in g)
Specifying "g" is optional.
Form
 v = Isp2V( iSP, g )
Inputs
 iSP         (1,:)  Specific impulse (sec)
 g           (1,1)  Acceleration of gravity (9.80665 m/sec^2)
Outputs
 v            (1,:)  Exhaust velocity
References Plot2D().
KEVToJ()
function KEVToJ (in keV)
Form
 j = KEVToJ( keV )
Inputs
 keV            (1,:)  Energy (keV)
Outputs
 j              (1,:)  Power (J)
Reference: Szirmay, L. V., "Nuclear Fusion Reactor Design Fundamentals, p. 184.
References Energy().
Referenced by QESilicon().
M2EP()
function M2EP (in m0, in mF, in mPayload)
 1 2 3 4 ... payload
Form
 [e, p] = M2EP( m0, mF, mPayload )
Inputs
 m0          (1,:)  Total mass of each stage (including everything above)
 mF          (1,:)  Final mass of each stage (including everything above)
 mPayload    (1,1)  Payload mass
Outputs
 e           (1,:)  Stage structural ratios
 p           (1,:)  Stage payload ratios
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 199-202.
References and(), and length().
Referenced by MSVRatio(), and OptimalPayloadRatio().
M2MS()
function M2MS (in m0, in mF, in mPayload)
 Stage Order: 1, 2, 3, 4, ... N, payload
Form
 [mS, eS] = M2MS( m0, mF, mPayload )
Inputs
 m0          (1,:)  Total mass of each stage (including everything above)
 mF          (1,:)  Final mass of each stage (including everything above)
 mPayload    (1,1)  Payload mass
Outputs
 mS          (1,:)  Fully fueled mass of the stage
 eS          (1,:)  Stage structural ratios
 pS          (1,:)  Stage payload ratios
 mSP         (1,:)  Stage propellant mass
 mSS         (1,:)  Stage structural mass
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 199-202.
References and(), and length().
Referenced by LVCombineSRB().
MachFromAreaRatio()
function MachFromAreaRatio (in aR, in gamma)
The throat is at Mach 1.
Type MachFromAreaRatio for a demo.
Form
 M = MachFromAreaRatio( aR, gamma )
Inputs
 aR            (1,1)   Area ratio Exit Area/Throat Area
 gamma         (1,1)   Ratio of specific heats
Outputs
 M             (1,1)   Mach number
References: Hill, P.G., Peterson, C. R., "The Mechanics and Thermodynamics of Propulsion," Addison-Wesley Publishing
Company, 1970, p. 221.
References and(), AreaRatioFromMach(), Demo(), MachFromAreaRatio(), RHS(), and Secant().
Referenced by MachFromAreaRatio(), and RocketH2O2().
MachNumber()
function MachNumber (in u, in gamma, in molWt, in T)
Form
 m = MachNumber( u, gamma, molWt, T )
Inputs
 u           (n)    Velocity (m/sec)
 gamma       (1,1)  Ratio of specific heats
 molWt       (1,1)  Average molecular weight of the gas (kg/mole)
 T           (m)    Temperature (deg-K)
Outputs
 m           (n,m)   Mach number
References length(), MachNumber(), Mesh2(), and SpeedSnd().
Referenced by MachNumber().
MassEquivalentDV()
function MassEquivalentDV (in dV, in uE, in mI, in thrust)
 Given a change in velocity and exhaust velocity this routine
 will compute the equivalent constant mass that will produce the
 same delta-v as a time-varying mass.
 Type MassEquivalentDV for a demo. It shows that the total delta-v
 is the same. As expected, the time varying delta-v changes more
 slowly at first and faster at the end.
 Units may be of any type as long as they are consistent. Examples are
 given.
 Since version 2014.1
Form
 [mEq, tBurn, mF] = MassEquivalentDV( dV, uE, mI, thrust )
Inputs
 dV      (1,1)  Desired change in velocity (km/s)
 uE      (1,1)  Exhaust velocity (km/s)
 mI      (1,1) Initial mass (kg)
 thrust (1,1)   Thrust (kN)
Outputs
 mEq      (1,1) Equivalent constant mass
 tBurn   (1,1)  Burn duration
 mF      (1,1) Mass of fuel
References and(), Constant(), Demo(), MassEquivalentDV(), Plot2D(), and TimeLabl().
Referenced by BilinearTangentAltitude(), and MassEquivalentDV().
MassVolH2O2()
function MassVolH2O2 (in m, in fR, in type)
For H2 + 1/2 O2 = H2O fR = 0.8889. For the SSME fR ranges from 0.6 to 0.86.
Type MassVolH2O2 for a demo of the Space Shuttle external tank.
Form
 [mH2, mO2, vH2, vO2] = MassVolH2O2( m, fR, type )
Inputs
 m       (1,:) Mass (kg)
 fR      (1,:) Fuel ratio O2/H2
 type     ''   Type string: 'slush', 'liquid'
Outputs
 mH2     (1,:) Mass H2 (kg)
 mO2     (1,:) Mass O2 (kg)
 vH2     (1,:) Volume H2 (kg)
 vO2     (1,:) Volume O2 (kg)
References and(), Demo(), isempty(), and MassVolH2O2().
Referenced by MassVolH2O2().
MinimumExhaustVelocity()
function MinimumExhaustVelocity (in sR, in dV)
Type MinimumExhaustVelocity for a demo.
Form
 uE = MinimumExhaustVelocity( sR, dV )
Inputs
 sR (1,:) Structural ratio
 dV (1,:) Delta V
Outputs
 uE (1,:) Minimum exhaust velocity
References Demo(), length(), MinimumExhaustVelocity(), and Plot2D().
Referenced by ElectricPropulsionDesign(), and MinimumExhaustVelocity().
MolWt()
function MolWt (in m, in n)
Form
 [mM, nM] = MolWt( m, n )
Inputs
 m             (:)     Molecular weight of the constituents
 n             (:)     Number of moles of each constituent
Outputs
 mM            (1,1)   Molecular weight of the mixture
 nM            (1,1)   Number of moles in the mixture
References: Martinez-Sanchez, M. "16.53 Course Notes" M.I.T. 1979.
References length().
Referenced by UEO2H2().
MS2M()
function MS2M (in mS, in eS, in mPayload)
 1 2 3 4 ... payload
Form
 [m0, mF] = MS2M( mS, eS, mPayload )
Inputs
 mS          (1,:)  Fully fueled mass of the stage
 eS          (1,:)  Stage structural ratios
 mpayload    (1,1)  Payload mass
Outputs
 m0          (1,:)  Total mass of each stage (including everything above)
 mF          (1,:)  Final mass of each stage (including everything above)
 pS          (1,:)  Stage payload ratios
 mSP         (1,:)  Stage propellant mass
 mSS         (1,:)  Stage structural mass
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 199-202.
References and(), and length().
Referenced by BurnoutVelocity(), LSQLaunchSim(), and RemoveStage().
MSTOR()
function MSTOR (in e, in p, in v, in mPayload)
Form
 [stor, ptor, m0, mf] = MSTOR( e, p, v, mPayload )
Inputs
 e            (1,:) Stage structural ratios
 v            (1,:) Exhaust velocity of each stage
 p            (1,:) Stage payload ratios
 mpayload     (1,1) Payload mass
Outputs
 stor         (1,:) dm*&zwj;/dmsk-Structural tradeoff ratio
 ptor         (1,:) dm*&zwj;/dmpk-Payload tradeoff ratio
 m0           (1,1) Initial mass
 mf           (1,1) Final mass
References and(), EP2M(), and length().
NuclearThermalUE()
function NuclearThermalUE (in t, in fuel)
Form
 uE = NuclearThermalUE( t, fuel )
Inputs
 t           (1,:) Temperature (deg-K)
 fuel         ''   Fuel name, default 'Hydrogren'
Outputs
 uE          (1,:) Exhaust velocity (m/sec)
See also
: Fuels
References Demo(), Fuels(), NuclearThermalUE(), Plot2D(), and UE().
Referenced by NuclearThermalUE().
OptimalVehicle()
function OptimalVehicle (in x, in doPlot)
The routine takes the power-to-mass ratio and finds the constant exhaust velocity that minimizes the total mass. Since v11 uses fminbnd to prevent singularities due to the structural ratio.
Type OptimalVehicle for a demo.
Form
 d = OptimalVehicle( x, doPlot )
Inputs
 x     (.)   Data structure
                     .dV     Total delta V capability (m/sec)
                     .uE     Exhaust velocity (m/sec)
                     .pR     Power to propulsion system mass ratio (W/kg)
                     .sR     Structural mass to fuel ratio
                     .mP     Payload mass (kg)
                     .eff    Conversion efficiency
                     .thrust Thrust (N)
 doPlot (1)  Flag to pretty-print the design
Outputs
 d     (.)   Updated data structure with:
                     .mT     Total mass
                     .mS     Structural mass
                     .mR     Propulsion system mass
                     .mF     Fuel mass
                     .mD     Dry mass
                     .power  Total power (w)
See also
: ElectricPropulsionDesign
References and(), Demo(), ElectricPropulsionDesign(), IsVersionAfter(), OptimalVehicle(), and set().
Referenced by OptimalVehicle(), and TVDesign().
Plume()
function Plume (in thrust, in rREA, in tREA, in uREA, in gREA, in normal, in r, in area, in tArea, in angInf, in sigma)
While designed for far field calculations it uses z buffering to ensure that mass is conserved. This routine works in the metric system!!!!
Form
 [f, t] = Plume( thrust, rREA, tREA, uREA, gREA, normal, r, area, tArea, angInf, sigma )
Inputs
 thrust        (m)   Rocket engine thrust (N)
 rREA          (3,m) Vector from c.m. to the rocket engine (m)
 tREA          (m)   Chamber temperature of the thruster
 uREA          (3,m) Thruster unit plume vector
 gREA          (m)   Ratio of specific heats for the gas
 normal        (3,n) Surface normal vector
 r             (3,n) Vector from c.m. to the panel center (m)
 area          (n)   Elemental area (m^2)
 tArea         (n)   Average surface temperature
 angInf              Plume turning angle at infinity (usually near /2 rad);
 sigma         (2)   Surface accommodation coefficents
                     [normal, tangential]
Outputs
 f            (3,m) Force vectors
 t            (3,m) Torque vectors
References: Fox, S.M. "Effects of Plume Impingement on a Momentum Bias Communications Satellite," J. Spacecraft and Rockets, 20(1) 55-60.
References and(), Cross(), Dot(), isempty(), length(), Mag(), Plume(), REA(), set(), Unit(), vector(), and zeros().
Referenced by Plume(), and SKDataF().
QRFuel()
function QRFuel (in fuel)
Form
 qR = QRFuel( fuel )
Inputs
 fuel         (1,:)     Fuel string
Outputs
 qR           (1,1)     Lower heating value (J/kg)
References: http://en.wikipedia.org/wiki/Heat_of_combustion
References Demo(), QRHydrocarbon(), and QRHydrogen().
QRHydrocarbon()
function QRHydrocarbon (in n, in m)
The fuel is CnHm. n can also be the name of a jet fuel: JP-3 through JP-8
Form
 qR = QRHydrocarbon( n, m )
Inputs
 n            (1,1)     Number of carbon atoms or fuel name
 m            (1,1)     Number of hydrogen atoms
Outputs
 qR           (1,1)     Lower heating value (J/kg)
References: Hill, P.G., Peterson, C. R., "The Mechanics and Thermodynamics of Propulsion," Addison-Wesley Publishing
Company, 1970, p. 221.
References Demo(), get(), and QRHydrocarbon().
Referenced by QRFuel(), and QRHydrocarbon().
QRHydrogen()
function QRHydrogen ()
Form
 qR = QRHydrogen
Inputs
 none
Outputs
 qR           (1,1)     Lower heating value (J/kg)
References: Hill, P.G., Peterson, C. R., "The Mechanics and Thermodynamics of Propulsion," Addison-Wesley Publishing
Company, 1970, p. 221.
References QRHydrogen().
Referenced by QRFuel(), QRHydrogen(), and UEQR().
RocketChemical()
function RocketChemical (in p0, in pA, in aStar, in aE, in qR, in gamma, in f, in throttle)
Thrust is per unit area. The default is an H2/O2 rocket with f as the mixture raio. This was formerly called RocketH2.
Type RocketChemical for a demo.
qR must be the energy per unit mass of fuel + oxygen.
Form
 [thrust, uEQ] = RocketChemical( p0, pA, aStar, aE, qR, gamma, f )
Inputs
 p0            (1,1)   Combustion pressure    (N/m^2)
 pA            (1,:)   Exhaust pressure       (N/m^2)
 aStar         (1,1)   Throat area            (m^2)
 aE            (1,1)   Exit area              (m^2)
 qR            (1,1)   Energy fuel            (J/kg)
 gamma         (1,1)   Ratio of specific heats
 f             (1,1)   H2/O2 ratio (2 = stoichiometric)
 throttle      (1,1)   throttle value (0 < throttle < 1)
Outputs
 thrust        (1,:)   Thrust                 (N)
 uEQ           (1,:)   Exhaust velocity       (m/s)
References: Martinez-Sanchez, M. "16.53 Course Notes" M.I.T. 1979.
References Altitude(), and(), Constant(), Demo(), Energy(), isempty(), length(), Plot2D(), RocketChemical(), and StdAtm().
Referenced by RocketChemical().
RocketFromUEAndT()
function RocketFromUEAndT (in uE0, in uEA, in t0, in tA, in pA, in p)
Utilizes the engine data measured at vacuum and a specified reference pressure.
Type RocketFromUEAndT for a demo of the Shuttle Main Engine (SME).
Form
 [t, uE] = RocketFromUEAndT( uE0, uEA, t0, tA, pA, p )
Inputs
 uE0    (1,1) Exhaust velocity in vacuum
 uEA (1,1) Exhaust velocity at pressure pA
 t0  (1,1) Thrust in vacuum
 tA  (1,1) Thrust at pressure pA
 pA  (1,1) Reference pressure
 p   (1,:) Pressure
Outputs
 t   (1,1) Thrust
 uE  (1,1) Exhaust velocity
References and(), Demo(), Plot2D(), Pressure(), and RocketFromUEAndT().
Referenced by RocketFromUEAndT(), and TurboRamRocket().
RocketH2O2()
function RocketH2O2 (in p0, in pA, in aStar, in aE, in f, in tP)
Type RocketH2O2 for a demo of the Space Shuttle Main Engine at sea level.
If p0 is any character it will return a default data structure.
Form
 [thrust, uE, qR] = RocketH2O2( p0, pA, aStar, aE, f, tP )
Inputs
 p0      (1,1) Chamber pressure      (N/m^2)
 pA      (1,1) Ambient pressure      (N/m^2)
 aStar   (1,1) Throat area           (m^2)
 aE      (1,1) Exit area             (m^2)
 f       (1,1) Mixture ratio         (kg O2/kg H2)
 tP      (1,1) Preheat temperature  (deg-K)
Outputs
 thrust  (1,1) Thrust                (N)
 uE      (1,1) Exhaust velocity      (m/s)
 qR      (1,1) Energy per unit mass  (J/kg)
References: http://en.wikipedia.org/wiki/Space_Shuttle_Main_Engine Hill, P. and C. Peterson, "Mechanics and Thermodynamics of Propulsion", p. 353-361.
References abs(), and(), AreaRatioFromMach(), DefaultData(), Demo(), Energy(), Gamma(), IsentropicExpansion(), MachFromAreaRatio(), RHS(), RocketH2O2(), and UEQR().
Referenced by RocketH2O2().
RocketMass()
function RocketMass (in Isp, in mP, in fS, in dV)
The structural fraction will limit the achievable delta-v.
Type RocketMass for a demo of a LH2/LO2 rocket.
Form
 [mF, mT, mS, e] = RocketMass( Isp, mP, fS, dV )
Inputs
 Isp          (1,1) Specific impulse     (sec)
 mP           (1,1) Payload mass         (kg)
 fS           (1,1) Structural fraction
 dV           (1,:) Required delta v     (km/sec)
Outputs
 mF          (1,:) Fuel mass              (kg)
 mT          (1,:) Total mass             (kg)
 mS          (1,:) Structural mass        (kg)
 e           (1,:) Payload fraction
Reference: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, p. 187.
References Demo(), and RocketMass().
Referenced by DesignUpperStage(), HSVMassEstimation(), and RocketMass().
RocketModel()
function RocketModel (in h, in iSpR, in thrustR, in pR, in atmData)
Given boundary conditions it will generate a curve of thrust and specific impulse as a function of altitude. It uses the standard atmosphere model so the range of altitudes is 0 to 80 km.
Type RocketModel for a demo of the Space Shuttle Main Engine.
Form
 [thrust,iSp] = RocketModel(h,iSpR,thrustR,pR)
Inputs
 h       (1,:) Altitude (km)
 iSpR    (1,2) Specific impulse (s)
 thrustR (1,2) Thrust (N)
 pR      (1,2) Pressure (N/m^2)
 atmData  (.)  Atmosphere data for StdAtm
Outputs
 thrust  (1,:) Thrust  N)
 iSp     (1,:) Specific impulse (s)
References Altitude(), and(), Demo(), Plot2D(), Pressure(), RocketModel(), and StdAtm().
Referenced by RocketModel().
RocketVariableUEAndT()
function RocketVariableUEAndT (in uE0, in t0, in uE)
 This assumes that the available energy from combustion and the engine
 efficiency does not change. The relationship is parabolic.
 You can also input T instead of uE and the output will be uE.
 This relationship does not extend beyond stochiometric conditions.
 Type RocketVariableUEAndT for a demo for the RL10B-2.
 Since version 2014.1
Form
 t = RocketVariableUEAndT( uE0, t0, uE )
Inputs
 uE0    (1,1) Reference exhaust velocity (m/s)
 t0  (1,1) Reference thrust in vacuum (N)
 uE  (1,:) Exhaust velocity (m/s)
Outputs
 t   (1,:) Thrust (N)
References and(), Demo(), Plot2D(), and RocketVariableUEAndT().
Referenced by RocketVariableUEAndT().
SolidR()
function SolidR (in g, in t0, in aStar, in a, in n, in R, in sigmaP, in dT, in rhoP, in mP0, in cAB, in nAB, in rM, in l, in x)
The state vector is
 [pressure;volume;mass].
In this model the burning area is assumed to be a function
 aB = cAB.*(mP.^nAB)
nAB is an array of exponents and cAB is an array of coefficients.
 mP = 1 - x(3)/mP0
The initial pressure must be > 0. Any small number will do.
Form
 [dX, dI] = SolidR( g, t0, aStar, a, n, R, sigmaP, dT, rhoP, mP0, cAB, nAB, rM, l, x )
Inputs
 g           (1,1)   Ratio of specific heats for the gas
 t0          (1,1)   Combustion temperature
 aStar       (1,1)   Throat area
 a           (1,1)   Burning rate coefficient
 n           (1,1)   Burning rate exponent
 R           (1,1)   Gas constant
 sigmaP      (1,1)   Burning rate temperature sensitivity coefficient
 dT          (1,1)   Change in temperature from nominal
 rhoP        (1,1)   Fuel density
 mP0         (1,1)   Total propellant mass
 cAB         (1,:)   Burning area coefficients
 nAB         (1,:)   Burning area exponents
 rM          (1,1)   Propellant radius
 l           (1,1)   Engine length
 x           (3,1)   State [pressure;volume;mass]
Outputs
 dX          (3,1)   State derivative
 dI          (2,1)   Inertia derivatives [polar; transverse]
References and(), Initialize(), length(), Pressure(), vector(), and zeros().
SolidRocketInertia()
function SolidRocketInertia (in mDot, in a, in b, in rho, in h)
 Assumes a uniform density. Also assumes that the inner surface is a
 cylinder. Burning is on the entire inside surface.
 mDot must be negative.
 Type SolidRocketInertia
 for a demo
 Since version 8.
Form
 [i, iDot, bDot] = SolidRocketInertia( mDot, a, b, rho, h )
Inputs
 mDot          (1,1)    Mass time derivative
 a             (1,1)    Outer radius
 b             (1,1)    Inner radius
 rho           (1,1)    Density
 h             (1,1)    Length
Outputs
 iDot          (3,3)    Inertia derivative
 i             (3,3)    Inertia
 bDot          (1,1)    Derivative of the inner radius
References and(), Demo(), SolidRocketInertia(), and zeros().
Referenced by SolidRocketInertia().
SpecificPower()
function SpecificPower (in powerPlant, in engine)
Power plants are fusion and nep, nuclear electric propulsion. Engines are DFD (direct thrust production), Lithium force accelerator, ion and Hall. The specific powers are combined as:
 sigma = 1/(1/sigmaP + 1/sigmaE)
Type SpecificPower for the specific power for a NEP and Hall combination.
Form
 [sigma,sigmas] = SpecificPower( powerPlant, engine )
Inputs
 powerPlant (1,:)  'fusion', 'solar' or 'nep'
 engine      (1,:)  'dfd', 'lifa', 'ion', 'hall', 'mpd'
Outputs
 sigma       (1,1)   Specific power (kW/kg)
 sigmas      (1,2)   Specific power of [plant engine]
References and(), and SpecificPower().
Referenced by SpecificPower().
SpeedSnd()
function SpeedSnd (in gamma, in molWt, in T)
Type SpeedSnd for a demo using Helium.
Form
 a = SpeedSnd( gamma, molWt, T )
Inputs
 gamma         (1,1) Ratio of specific heats
 molWt         (1,1) Average molecular weight of the gas (kg/mole)
 T             (1,:) Temperature (deg-K)
Outputs
 a             (1,:) Speed of sound (m/sec)
References: Hill, P.G., C. R. Peterson, Mechanics and Thermodynamics of Propulsion, Addison-Wesley, Reading, MA, 1970, p. 47.
References and(), MolWt2R(), Plot2D(), and SpeedSnd().
Referenced by MachNumber(), and SpeedSnd().
SphericalTankFluidHeight()
function SphericalTankFluidHeight (in vT, in vF)
Form
 h = SphericalTankFluidHeight( vT, vF )
Inputs
 vT          (1,1)  Tank volume
 vF          (1,1)  Fluid volume
Outputs
 h           (1,1)  Height of fuel
References abs(), Demo(), length(), Plot2D(), and SphericalTankFluidHeight().
Referenced by SphericalTankFluidHeight().
TCoeff()
function TCoeff (in g, in e, in p)
If no outputs are specified it will generate a plot. If both e and p are vectors it will create a mesh plot. If only one is a vector it will create an xy plot.
If only g is specified it will use e = linspace(15,600) and p = logspace(2,4). If no inputs are specified g will be set equal to 1.2. To get the real thrust coefficient multiply the result by an efficiency factor (typically 0.98).
inf is a legitimate pressure ratio but you cannot generate plots with it.
Form
 [cF, x] = TCoeff( g, e, p )
Inputs
 g   (1,1) Ratio of specific heats for the gas
 e   (1,n) Area ratio (exit area/throat)
 p   (1,m) Chamber pressure/ambient pressure
Outputs
 cF (m,n) Thrust coefficient
 x   (1,n) Ratio of exhaust pressure to chamber pressure
References and(), get(), isempty(), length(), Mesh2(), Pressure(), set(), TCoeff(), and vector().
Referenced by IdealRkt(), TCoeff(), and ThrustToAStar().
TElec()
function TElec (in T, in molWt, in gamma, in eff, in TC, in p)
The exhaust velocity is computed from the element data and temperature. Computes the jet power from the mass flow and efficiency.
Form
 [iSP, power, mdot, AStar] = TElec( T, molWt, gamma, eff, TC, p )
Inputs
 T            (1,:) Thrust                  (N)
 molWt        (1,1) Molecular weight        (kg/mole)
 gamma        (1,1) Ratio of specific Heats
 eff          (1,1) Efficiency
 TC           (1,1) Chamber Temperature     (K)
 p            (1,1) Chamber Pressure        (N/m^2)
Outputs
 iSP          (1,:) Specific Impulse        (sec)
 power        (1,:) Power Consumption       (watts)
 mdot         (1,:) Mass flow               (kg/sec)
 AStar        (1,:) Throat area             (m^2)
References and(), MolWt2R(), Plot2D(), Pressure(), and V2Isp().
ThrusterLayout()
function ThrusterLayout (in action, in varargin)
Draws the plume vector in red and torque unit vector in green. It computes the feasibility of both positive and negative torque about all three axes.
The locations must be with respect to the center of mass unless a cM is entered.
Type ThrusterLayout for a demo of putting thrusters on a cube. There are 4 thrusters which is the minimum for 3 axis torques.
Form
 ThrusterLayout( 'initialize', fileName )
 [t, f, u] = ThrusterLayout( 'update', u, r, cM )
Inputs
 action            (1,:) 'initialize'
 fileName          (1,:) File name for the CAD model to be displayed
 action            (1,:) 'update'
 u                 (3,:) Force unit vectors
 r                 (3,:) Thruster locations
 cM                (3,1) Center of mass location
Outputs
 t                 (3,:) Torque vectors for each thruster
 f                 (1,6) Feasibility for each torque
 u                 (n,6) Modulation of thruster for each vector
References and(), Demo(), isempty(), length(), LoadCAD(), ThrusterLayout(), and vector().
Referenced by ThrusterLayout().
ThrustToAStar()
function ThrustToAStar (in fuel, in thrust, in p0, in pA, in e)
Form
 aStar = ThrustToAStar( fuel, thrust, p0, pA, e )
Inputs
 fuel         (1,:)  Fuel type, ex. 'air','nitrogen'
 thrust       (1,1)  Thrust level (N)
 p0           (1,1) Chamber pressure (N/m^2)
 pA           (1,1)  Ambient pressure (N/m^2)
 e            (1,1)  Area ratio (exit area/throat area)
Outputs
 aStar        (1,1)  Throat area (m^2)
See also
GasProperties, TCoeff
References GasProperties(), TCoeff(), and ThrustToAStar().
Referenced by ThrustToAStar().
TVDesign()
function TVDesign (in mPayload, in dV, in thrust, in eff, in sR, in pR)
Compute the optimal exhaust velocity and design the vehicle. Type TVDesign for a demo.
Form
 x = TVDesign( mPayload, dV, thrust, eff, sR, pR )
Inputs
 mPayload  (1,1)    Mass of the payload
 dV        (1,1)    Total delta-V capacity (km/sec)
 thrust    (1,1)    Total vehicle thrust (N)
 eff       (1,1)    Efficiency
 sR        (1,1)    Structural Ratio
 pR        (1,1)    Power ratio
Outputs
 x          (.)    Data structure
See also
: OptimalVehicle, ElectricPropulsionDesign
References and(), Demo(), ElectricPropulsionDesign(), OptimalVehicle(), and TVDesign().
Referenced by TVDesign().
UE()
function UE (in gamma, in m, in t0, in p0, in pE)
 Since version 2.
Form
 uE = UE( gamma, m, t0, p0, pE )
Inputs
 gamma         (1,n)   Ratio of specific heats
 m             (1,m)   Molecular weight of the combustion products kg/mole
 t0            (1,1)   Combustion temperature (deg-K)
 p0            (1,1)   Combustion pressure    (N/m^2)
 pE            (1,1)   Exhaust pressure       (N/m^2)
Outputs
 uE            (m,n)   Exhaust velocity
References Gamma(), length(), Mesh2(), and MolWt2R().
Referenced by NuclearThermalUE(), and UEO2H2().
UEO2H2()
function UEO2H2 (in n, in t0, in p0, in pE)
Form
 uE = UEO2H2( n, t0, p0, pE )
Inputs
 n             (1,:)   Number of molecules of H2 per O2 molecule
 t0            (1,1)   Combustion temperature (deg-K)
 p0            (1,1)   Combustion pressure    (N/m^2)
 pE            (1,1)   Exhaust pressure       (N/m^2)
Outputs
 uE            (1,:)   Exhaust velocity
References Gamma(), length(), MolWt(), UE(), UEO2H2(), and zeros().
Referenced by UEO2H2().
UEQR()
function UEQR (in qR, in gamma, in p0, in pE)
The exhaust pressures are used as a ratio so can be any units.
Type UEQR for a demo.
Form
 uE = UEQR( qR, gamma, p0, pE )
Inputs
 qR            (1,1)   Heating value          (J/kg)
 gamma         (1,1)   Ratio of specific heats
 p0            (1,1)   Combustion pressure    (N/m^2)
 pE            (1,:)   Exhaust pressure       (N/m^2)
Outputs
 uE            (1,:)   Exhaust velocity       (m/s)
References: Martinez-Sanchez, M. "16.53 Course Notes" M.I.T. 1979.
References Altitude(), Demo(), length(), Plot2D(), QRHydrogen(), StdAtm(), and UEQR().
Referenced by RocketH2O2(), and UEQR().
V2Isp()
function V2Isp (in v, in g)
 Since version 1.
Form
 iSP = V2Isp( v, g )
Inputs
 v           (1,:)  Exhaust velocity
 g           (1,1)  Acceleration of gravity (9.806 m/sec^2)
Outputs
 iSP         (1,:)  Specific impulse (sec)
References Plot2D().
Referenced by IdealRkt(), and TElec().
VolumeToDimension()
function VolumeToDimension (in v, in type, in aR)
Four types may be entered:
 'sphere'
 'cylinder' (with spherical endcaps)
 'cylinder flat ends'
 'cylinder with constrained radius' (aR = diameter)
Form
 d = VolumeToDimension( v, type, aR )
Inputs
 v            (1,1)   Volume
 type         (1,1)   Type of tank 'sphere' 'cylinder' 'cylinder flat ends'
                       'cylinder constrained radius'
 aR            (1,1)   Length/width or diameter for constrained cylinder
Outputs
 d             (1,1)   Dimension
                       .diameter (1,1) Diameter
                       .length   (1,1) Length
References length().
VolumeToPressureBD()
function VolumeToPressureBD (in vT, in vF, in pI)
Form
 pF = VolumeToPressureBD( vT, vF, pI )
Inputs
 vT            (1,1)    Total tank volume (m^3)
 vF            (1,1)    Volume available for fuel (m^3)
 pI            (1,:)    Initial pressure (N/m^2)
Outputs
 pF            (1,:)    Final pressure (N/m^2)
References length(), Plot2D(), Pressure(), and VolumeToPressureBD().
Referenced by VolumeToPressureBD().
VToEV()
function VToEV (in atom, in v)
 Type VToEV for a demo.
Form
 eV = VToEV( atom, v )
Inputs
 atom          {:}    Atom name see AtomicMass
 v             (1,:)  Velocity (km/s)
Outputs
 eV            (1,:)  Energy (eV)
References VToEV().
Referenced by VToEV().