PSS MATLAB Toolboxes: AC Functions
AC Functions
AC Module
Aircraft module functions.
Directories
directory ACActuator
Actuators.
directory ACAero
Aerodynamics.
directory ACAirbreathing
directory ACAircraft
Aircraft models.
directory ACAtmosphere
directory ACClasses
Classes.
directory ACControl
Control systems.
directory ACCoord
Coordinate frames.
directory ACData
Data.
directory ACDemoFuns
Functions supporting demos.
directory ACDynamics
Aircraft dynamics.
directory ACEngine
Engine thrust functions.
directory ACGraphics
Aircraft graphics.
directory ACNewtonian
directory ACPointMass
directory ACRDE
directory ACThermal
Thermal module.
directory ACUtils
directory ACWind
Description
Functions
function A10 (in q)
Provides two A10 aircraft models: conventional and tilt-wing.
function AC (in x, in t, in dT, in d, in opt)
Dynamics model for an aircraft.
function ACAero (in alpha, in beta, in x, in d, in qBar, in control, in flex, in rho)
Aerodynamic model.
function ACBuild (in database)
Build the aircraft model.
function ACEngEq (in d, in v, in r)
Find the equilibrium state of the engine.
function ACEngine (in x, in d, in control, in altitude, in machNo)
Aircraft engine model.
function ACInit (in x, in d, in stateName)
Initialize the aircraft model.
function ACModes (in g)
Compute the aircraft modes for straight and level flight.
function ACPlot (in x, in opt, in d, in g, in nPts, in dT, in nSim)
Plots the aircraft data.
function ACPointMassControl (in x, in p, in dAC, in dC)
Point mass control of flight path angle, velocity and angle of bank.
function ACSensor (in x, in d, in opt)
Generic aircraft sensor.
function ACThrust (in idl, in mil, in max, in yH, in xM, in h, in m, in p)
Thrust model for a gas turbine engine.
function ActiveAeroSurfacesDisplay (in action, in varargin)
Color the active aerodynamic surfaces.
function ACTrim (in x, in d, in w, in g, in options)
Aircraft trimming algorithm.
function ACWeightEstimation (in d, in tol, in units, in fileName)
Computes aircraft weight.
function ADC (in vT, in alt)
Implements the "Air Data Computer" model.
function AdvanceRatio (in v, in n, in d)
Compute the propeller advance ratio.
function AeroCoefficientPointMass (in aE, in bE, in h, in d)
Aerodynamic model with sideforce from a rudder.
function AeroD (in f, in axisSystem)
Compute the state space system based on aerodynamic derivatives.
function AerodynamicHeatFlux (in m, in l, in p)
Heat flux as a function of mach number.
function AerodynamicShock (in m0, in p0, in gamma, in theta)
Compute Mach number and pressure for aerodynamics shocks.
function AerodynamicShockMinimize (in m0, in p0, in gamma, in mF, in n, in opts)
Find a set of oblique shocks that minimize the pressure loss.
function AeroForceAndTorqueCombined (in alpha, in beta, in V, in e, in u, in d, in ignoredArg)
Compute force and torque an aircraft from M = 0 to M = inf.
function AeroFormFactor (in type, in m, in d)
Aerodynamic form factor.
function AIRC (in q)
AIRC aircraft model.
function AircraftControl (in action, in d)
Implements an aircraft control system.
function AircraftControlCAS (in action, in d)
Implements a pitch rate control augmentation system.
function AircraftCostCalculation (in varargin)
Computes aircraft cost.
function AircraftDesign (in d, in n, in tol, in p)
Design an aircraft.
function AircraftDragDataStructures (in aircraft)
Generates data structures for select aircraft.
function AircraftEquilibrium (in mass, in gamma, in h, in m, in d)
Computes the equilibrium thrust and wing area.
function AircraftGroupDataStructure (in varargin)
Build the AircraftGroupMass data structure.
function AircraftGroupMass (in group, in MTOM, in p)
Create masses for an aircraft.
function AircraftGroupMassStatement (in mFuel, in p, in fileName)
Create a mass statement for an aircraft.
function AircraftPointMassCLPSim (in x0, in cmd, in t, in data)
Simulate the controlled trajectory of a point mass aircraft model.
function AircraftPointMassControl (in x, in xDot, in cmd, in cmdDot, in Tcbar, in data)
Compute the control inputs for a point mass aircraft model.
function AircraftPointMassDLM (in x, in u, in t)
Generate a discrete time-varying linear model of a point-mass aircraft.
function AircraftPointMassRHS (in x, in u, in data)
Compute the state derivatives of a point mass aircraft model.
function AircraftPointMassRHSWithSideslip (in state, in ignoredArg, in u, in d)
Point mass dynamic model with sideslip as an input.
function AircraftPointMassSim (in x0, in u, in t, in data)
Simulate the trajectory x(t) of a point mass aircraft model given u(t)
function AircraftPowerAndThrust (in s, in d)
Computes aircraft power and thrust for a set of trajectory segments.
function AircraftSizing (in d)
AIRCRAFTSIZING size an aircraft.
function AircraftThrustFromFlight (in h, in v, in vC, in mass, in d)
Computes the thrust required for an aircraft trajectory.
function AircraftTrajectoryControl (in s, in d, in tauGamma, in tauV, in vSet, in gammaSet)
AIRCRAFTTRAJECTORYCONTROL Control function for a 3D point mass aircraft.
function AircraftWeights (in range, in iSp, in lD, in u, in frac)
AIRCRAFTWEIGHTS Compute weights using a simple model.
function AirlinerSeat (in w)
Generate CAD data for an airliner seat.
function AirlinerSeats (in d, in p)
Layout airliner seats.
function AirMass (in h0, in theta)
Computes the relative air mass to sea level and a vertical path.
function AlphaFromQNV (in q, in v, in n)
Compute angle of attack.
function AlphBeta (in vB, in vBDot)
Compute angle of attack and sideslip.
function AngleOfAttackMaxLD (in cD0, in k, in cLA)
Angle of attack for maximum L/D.
function AOverAStar (in gamma, in machNo)
A/A* computation from mach number and ratio of specific heats.
function APMLinMod (in x, in u, in tau, in g)
Compute a linear model for a point mass aircraft at a flight condition.
function AspectRatio (in b, in S)
Compute aircraft aspect ratio.
function AtmosphereLayers (in h)
Names the atmospheric layer for altitude h.
function BankedTurn (in phi, in v)
Compute properties for a banked turn.
function BladeElement (in t, in vC, in omega, in d)
BladeElement computes the inducted velocity.
function BldFlex (in g, in useMode, in rBase, in bLocalToGlobal, in zeta)
Creates the flex model interfaces.
function Boeing737 (in arg)
Look up Boeing 737-800 data parameters.
function BreguetRangeEquation (in d, in velocity, in altitude)
Computes the Breguet range.
function BToS (in alpha, in opt)
Convert from the body axes to stability axes.
function BToW (in alpha, in beta, in opt)
Convert from the body frame to wind axes.
function CCVSobel (in q)
CCV aircraft model with a pitch pointing mode.
function CD0Composite (in m, in d, in alpha, in p, in gamma)
Drag coefficient for subsonic, supersonic and hypersonic flight.
function CDCLComposite (in m, in d, in alpha, in p)
Lift and drag coefficients for subsonic, supersonic and hypersonic flight.
function CDCLHypersonic (in m, in alpha, in p, in l, in cParasitic)
Hypersonic lift and drag coefficients for a flat plate.
function CDCLSubsonic (in m, in alpha, in p, in l, in aR, in e, in cLAlpha)
Subsonic lift and drag coefficients for a flat plate.
function CDSkinFriction (in m, in l, in p, in model)
Skin friction coefficient using a variety of models.
function CDWave (in m, in alpha, in t, in mDD, in cDM1)
Wave drag using Ackeret theory.
function CLCDFreeMolecular (in v, in m, in tW, in beta, in tA, in sigmaN, in sigmaT)
Computes the CL and CD for free molecular flow.
function CLCMWing (in alpha, in z)
Lift and moment coefficients of a thin wing.
function CLComposite (in m, in d, in alpha, in gamma)
Lift coefficient for subsonic, supersonic and hypersonic flight.
function ClimbAngle (in h, in v, in d)
Compute climb angle.
function ComputeAlphaConstantFlightPathAngle (in x, in d)
Computes the angle of attack for a constant flight path angle.
function ConcordeLD (in m)
Optimal lift and drag coefficients for the Concorde.
function ConcordeProperties (in machNo)
Returns Concorde properties.
function ConstantDynamicPressureVelocity (in h, in q, in atmData)
Computes the velocity and Mach profile for constant dynamic pressure.
function CPHypersonic (in m, in gamma)
Hypersonic coefficient of pressure.
function CreateAircraftModel (in file)
Interactive tool to create an aircraft model.
function CTPropeller (in angle, in j)
Compute the propeller thrust coefficient.
function DC8 (in q, in n)
DC 8 stability derivatives model.
function DefaultACData ()
Provide a default aircraft data structure.
function DefaultACState ()
Provide a default aircraft state.
function DragCoeff (in d, in mach, in p, in cP)
Computes drag coefficients for a vehicle using simple formulas.
function DragLoss (in m, in d)
Compute drag loss using LiftAndDragJonesSearsHaack.
function DragPolar (in cD0, in cL, in kI)
Computes the drag polar.
function DragPolarFromData (in cD, in cL)
Compute the drag polar from data lift and drag coefficient data.
function DragUndercarriage (in m, in s, in f)
Computes drag coefficient increment due to the undercarriage.
function DrawAC (in mode, in g, in x, in h, in units)
Draws an aircraft in the NED frame.
function DrawAircraft (in action, in g, in h, in x, in t, in tU)
Draws an aircraft.
function DrawAlphaBeta (in p0, in q, in vB, in l)
Draws angle of attack and sideslip.
function DrawAngles (in p0, in p, in name)
Draws angles and arcs between them.
function DrawTerrain (in type, in d, in hAxes)
Draw terrain.
function DynamicPressureAndHeat (in h, in l, in qMax)
Heat, velocity and temperature at a fixed dynamic pressure.
function ECIToNED (in r, in opt, in f)
Convert from the ECI frame to the NED frame.
function EnergyHeight (in hE, in n)
Compute energy height contours.
function EngineDataFromTable (in m, in h, in d)
Generate engine data from a table.
function EngineExample (in type)
Example engine parameters.
function EngineMap (in h, in m, in d)
Engine performance map from a table lookup.
function EngineTable (in type, in h, in m, in d, in p)
Generate an engine table for a matrix of altitudes and mach.
function EquilibriumControls (in x, in d)
EquilibriumControls finds controls to maintain equilibrium.
function EulNED (in r, in qECIToB, in e)
Euler angles given ECI information.
function EulRate (in e, in w)
Euler rates.
function F100 (in q)
Gas Turbine 16th-order F100 linear model: Pratt and Whitney.
function F16 (in q)
The F16 aircraft properties database.
function F16Act (in x, in controlInput, in actuatorData)
Models the F16 actuators as first order lags with time constants.
function F16Actuator (in x, in control, in d)
Model for the F16 actuators.
function F18Model (in machNo, in altitude)
Generates a state space F-18 model from a range of models.
function FAIR (in t, in f, in units)
Computes the gas constants for hydrocarbon/air mixtures.
function FlightEquilibrium (in gamma, in h, in v, in d)
Compute flight equilibrium.
function FLToM (in fL)
Convert flight level to meters.
function FMixedExhaustTurbofan (in tauTL, in alpha, in tauLambda, in tT4, in p, in d, in gamma6, in gamma16, in alphaP, in r16, in r6, in tol)
Function called by FZero to solve for tauTL.
function FormDragCoeff (in d, in machNo, in p)
Computes form drag including wave drag.
function FormFactorSurfaceOfRevolution (in m, in f)
Computes the form factor for a body of revolution.
function FormFactorWing (in m, in t, in lambda)
Computes the form factor for a wing.
function FTrim (in v, in x, in d, in g, in w, in nR)
Cost function for the trimming algorithm.
function FuelFromRange (in mD, in lOverD, in r, in v, in sFC)
Computes the fuel as a function of range.
function GeoMagLatLon (in r)
Geomagnetic latitude and longitude.
function GeomagneticRigidity (in r)
Geomagnetic rigidity using a dipole model.
function Glide (in h, in v, in d, in cL)
Compute glide angle, range and velocity.
function GroundEffect (in h, in w)
Ground effect factor that multiplies the induced drag.
function HeatingValue (in name)
Heating values.
function HorizontalWind (in IYD, in SEC, in ALT, in GLAT, in GLONG, in STL, in F107A, in F107, in AP, in SW)
Horizontal wind model HWM93 covering all altitude regions.
function HUD (in mode, in g, in x, in h, in c)
Implements a "heads-up-display".
function HUDCntrl (in action)
Perform actions specified by the HUD.
function IdealJetEngineEfficiency (in m0, in t0, in tT4, in piC, in gamma, in piF, in alpha)
Computes the jet engine efficiency for an ideal turbofan engine.
function InducedDragCoeff (in e, in aR, in m)
Induced drag coefficient for all Mach numbers.
function InletAndNozzle (in l, in w, in h, in angle)
Generate vertices for an inlet and a nozzle.
function InletLoss (in m)
Computes the inlet loss in an aircraft engine due to shockwaves.
function JacobVB (in v)
Convert from the body axes to stability axes.
function JetEngine (in m, in d, in q)
A simple jet engine model.
function JetEngineAnalysis (in p, in d)
Jet engine analysis.
function JetEngineDefinitions (in type, in engine)
Definitions of data.
function JetEngineEfficiency (in f, in hPR, in v0, in fOverMDotA, in v9, in units, in v19, in alpha)
Computes the jet engine efficiency for an engine.
function JetEnginePerformance (in p, in d)
Jet engine performance.
function Knudsen (in rho, in T, in mu, in m, in l)
Knudsen number.
function LandingDistance (in m, in vL, in t, in cL, in cD0, in muR, in hB, in d, in rho)
Computes landing distance.
function LDDeltaWing (in v, in h, in d, in alpha)
Computes the lift and drag coefficients for a swept wing.
function LiftAndDrag (in d, in altitude, in velocity, in cP, in alpha)
Computes lift and drag coefficients for a vehicle using simple formulas.
function LiftAndDragJonesSearsHaack (in m, in d)
Lift and drag using the R.T.
function LiftCoeff (in alpha, in cLAlpha, in cL0, in m, in delta)
Computes the ideal lift coefficient from 0 through supersonic.
function LiftCoeffStall (in alpha, in d)
Computes the lift coefficient using a table lookup.
function LiftToDragFromMach (in m)
Computes the L/D ratio from Mach number.
function LocalAngleOfAttack (in alpha, in aB, in delta)
Compute the local angle of attack.
function LowSpeedAeroData (in fileName, in a, in p, in d, in q, in alpha0)
Generates a file for sc_aero_newtonian.cc/.h.
function MachAcrossShock (in m1, in gamma, in theta)
Compute the Mach number across a shock.
function MachFromMassFlowParameter (in gamma, in r, in mFP, in m0, in units)
Mach number from mass flow parameter.
function MachFromPR (in pR, in gamma)
Computes Mach number from pressure ratio and gamma.
function MachFromPressureRatio (in gamma, in pR, in tol)
Computes the Mach number from pressure ratio.
function MachSwept (in m, in sweep)
Effective Mach number with sweep.
function MassCrewAndPassenger (in nFlightDeck, in nPassenger, in longRange)
Mass of crew and passengers.
function MassFlow (in m0, in p0, in t0, in piDMax, in eD, in gamma, in r, in m2, in units)
Computes the mass flow divided by the inlet area.
function MassFlowParameter (in gamma, in cP, in machNo, in units)
Mass flow parameter.
function MassFlowParameterR (in gamma, in r, in machNo, in units)
Mass flow parameter with gamma, r and Mach number as inputs.
function MassInflowSupersonic (in gamma, in machNo2, in piD, in altitude, in machNo)
Mass inflow for a supersonic diffuser.
function MaxShockIncidenceAngle (in m1, in gamma)
Compute maximum incidence angle.
function MergeNOAAWindData (in data1, in data2)
Merge two NOAA wind data sets.
function MissileMassEstimation (in d, in tol, in fileName)
Computes missile weight.
function MixedFlowTurbofan (in action, in varargin)
Mixed flow turbofan engine performance.
function MixedFlowTurbofanProfile (in ref, in p, in h, in v)
Mixed flow turbofan engine performance profile for p, h and v.
function NewtonianAerodynamicsFromCAD (in alpha, in beta, in uMag, in rho, in g, in c, in angle, in uSurf, in display)
Compute force and torque for a CAD model.
function NewtonianAeroTable (in fileName, in g, in a, in p)
Generates a file for sc_aero_newtonian.cc/.h.
function NewtonianAlphaFromCAD (in uMag, in rho, in g, in mass, in lift)
Compute the static angle of attack to balance gravity.
function NewtonianCPFromCAD (in uMag, in alpha, in rho, in g, in z)
Compute the center of pressure from the cad model.
function NewtonianForceFromCAD (in u, in rho, in g)
Compute force for a CAD model.
function NFromJ (in j, in d, in v, in h)
Compute the rotation rate from the advance ratio.
function NFromMT (in mT, in d, in h, in v)
Compute the rotation rate from the tip Mach number.
function NOAAWindData (in area, in lvl, in latLonData)
Load wind data from the NOAA web site.
function ObliqueShockAngle (in m1, in delta, in gamma)
Compute the oblique shock angle from the streamline deflection angle.
function OH6A (in q)
OH6A hover model.
function OptimalAngleOfAttackHypersonic (in m, in p, in l, in cParasitic)
Optimal angle of attack for hypersonic flow.
function ParasiticDragCoefficient (in d)
Parasitic drag coefficient for a set of aircraft components.
function PlotGasTurbineData (in dP, in p, in units, in g)
Generate plots from the Gas Turbine analysis functions.
function PlotWindField (in d, in altRange, in fig)
Plot the wind field from a data structure array.
function PowerPropeller (in u0, in d, in thrust, in rho)
Compute propeller power.
function PrandtlGlauertCorrection (in m, in delta)
Computes the Prandtl Glauert Compressibility correction.
function PressureRatioFromMach (in gamma, in m)
Computes impact to static pressure ratio from Mach number and gamma.
function PressureRatioFromTemp (in tau, in eta, in gamma)
Computes pressure ratio from temperature ratio, efficiency and gamma.
function PressureTotal (in p, in gamma, in machNo)
Total pressure.
function PropellerEfficiency (in etaMax, in machNo)
Computes propeller efficency from Mach number.
function PropellerMomentum (in t, in d, in h, in v)
Design a propeller using actuator disk theory.
function PropellerPower (in rho, in a, in t, in v)
Propeller power and induced velocity.
function PropellerThrust (in x, in rho, in d)
Propeller thrust.
function QECI (in r, in e)
Compute ECI to body quaternion from ECI position and Euler angles.
function Ramjet (in m, in d, in p)
Ramjet model including aerodynamic losses.
function RamjetExternalHeatSource (in m, in p, in d)
Ramjet model including aerodynamic losses.
function RamjetKerrebrock (in m, in d, in p)
Ramjet jet engine model producing thrust and specific fuel consumption.
function RamRecovery (in machNo)
Ram recovery in an inlet.
function RateOfClimb (in d, in velocity, in altitude)
Computes the rate of climb and acceleration.
function RayleighPitotTube (in m, in gamma)
Stagnation pressure ratio in supersonic flow.
function RDE (in m, in d, in p)
Engine model - RDE - producing zero thrust and specific fuel consumption.
function RHS2DPointMass (in x, in ignoredArg, in d)
Simulate a point mass aircraft model in 2 dimensions.
function RHS3DPointAircraft (in s, in ignoredArg, in d)
3D point aircraft model with time varying mass.
function RHSACFlatEarth (in x, in ignoredArg, in d)
Dynamics model for an aircraft on a flat Earth.
function RHSFlatEarthSet (in x, in d, in opt)
Finds the set point for RHSFlatEarth with fminsearch.
function RHSLiftingSatellite (in x, in ignoredArg, in d)
Right-hand-side of satellite with lift.
function RHSPointMassAircraft (in x, in ignoredArg, in d)
RHSPointMassAircraft Right hand side for a point mass aircraft.
function RHSRollingMissileLinear (in x, in ignoredArg, in d)
Right-hand-side for a linear rolling missile.
function RNEH (in r, in units)
Convert from the ECI frame to the NEH frame.
function Scimitar (in m, in ignoredArg, in ignoredArg)
Models a Scimitar engine from Reaction Engines, Ltd.
function SimpleLiftAndDrag (in m, in d)
Lift and drag for the drag polar.
function SonicBoom (in h)
Compute the sonic boom scale factor.
function SonicBoomHypersonic (in drag, in m, in h, in atmData)
Hypersonic sonic boom based on drag.
function StallVelocity (in m, in cLMax, in s, in rho)
Computes takeoff velocity.
function StateSpacePlot (in opt, in x, in y, in u, in d)
Plots statespace data.
function StaticPumping (in cP, in altitude, in pR, in g)
Static pumping of air.
function STOVL (in q)
Short Takeoff Vertical Landing aircraft model.
function SToW (in beta, in opt)
Convert from stability axes to wind axes.
function StreamlineShockAngle (in theta, in m1, in gamma)
Compute streamline deflection angle from the oblique shock angle.
function SweepAngle (in m)
SWEEPANGLE Compute sweep angle as function of Mach number.
function Takeoff (in d, in altitude)
Computes the required roll distance and liftoff velocity.
function TakeoffDistance (in m, in vLO, in t, in cL, in cD0, in muR, in hB, in d, in rho)
Computes takeoff distance.
function TakeoffTransition (in hSc, in n, in gamma)
Compute the radius and length of transition.
function TakeoffVelocity (in m, in cLMax, in s, in f, in rho)
Computes takeoff velocity.
function TaxiingFuel (in t, in m)
Compute taxiing fuel.
function TemperatureTotal (in t, in gamma, in machNo)
Total temperature.
function TempRatioFromMachAndGamma (in m, in gamma)
Computes the total temperature ratio from Mach number and gamma.
function TempRatioFromPressure (in pi, in eta, in gamma)
Computes temperature ratio.
function Theta0 (in t0, in machNo, in units)
Computes the dimensionless total temperature.
function Throttle (in tT4SLS, in t0, in machNo, in units)
Computes the value of the burner temperature given the throttle ratio.
function ThrustConstant (in ignoredArg, in ignoredArg, in d)
Constant thrust and fuel consumption model.
function ThrustPropeller (in type, in varargin)
Compute propeller thrust.
function ThrustTurbofan (in f0, in k1, in k2, in v)
Compute turbofan thrust as a function of static thrust and velocity.
function TotalPressureAndTemperature (in p, in t, in gamma, in m)
Computes the total pressure and temperature at a Mach number.
function Trajectory (in x, in ignoredArg, in segment, in setPoint, in distance, in dT, in time)
Determines the set points to achieve a trajectory.
function Trans3DMF (in m, in g, in r)
Transform a 3D data structure.
function Turbofan (in m, in d, in q)
Turbofan jet engine model produces thrust and specific fuel consumption.
function Turbofanramjet (in m, in d, in p)
Models a turbofanramjet.
function Turbojet (in m, in d, in p)
Jet engine model producing thrust and specific fuel consumption.
function TurbojetNoThrust (in m, in d, in p)
Jet engine model producing zero thrust and specific fuel consumption.
function TurboRamjet (in m, in d, in p)
Models a turboramjet.
function TurboRamRocket (in m, in d, in p)
Model of a combined cycle engine with turbofan, ramjet and rocket.
function TurningRadius (in v, in n)
Compute turning radius and turning rate.
function UFromAlphaBeta (in alpha, in beta)
Compute wind vector from angle of attack and sideslip.
function VBDToVBT (in vB, in vBDot)
Compute the total velocity derivative from the body velocity.
function VStall (in d, in altitude)
Computes the stall velocity.
function VTToVB (in vT, in alpha, in beta)
Compute body velocity from alpha, beta and vT.
function WettedArea (in type, in d)
Aerodynamic wetted area for different structures.
function WindFunction (in alt, in lat, in day, in check)
Approximate the Horizontal Wind Model (HWM93) with analytic functions.
function WindGust (in h, in u0, in sigma, in wingSpan, in f, in w)
Wind gust model.
function WindModel (in action, in varargin)
Combined steady-state and gust model for wind.
function WindsGUI (in action, in modifier)
GUI for generating wind data over a range of parameters.
function WindsPlot (in action, in modifier)
Generate 3D plots of wind data vs.
function WindTrendsDemo (in dataType, in makemovie)
Animate the variation of wind magnitude and direction.
function WingAreaToTaper (in c, in s, in b, in sweep)
Generates the taper and trailing edge angle for a wing.
function WingFromParameters (in c, in s, in b, in sweep, in t)
Generates vertices and faces for a wing based on the wing parameters.
function WingSizingForPullUp (in pullUp, in m, in h, in cLAlpha, in alpha, in thrust, in mass, in sweep)
Sizes a wing for dynamic pull up.
function WriteEngineData (in fileName, in d)
Write engine data to a table.
Function Documentation
A10()
function A10 (in q)
 The tiltable wing panel model is available as lateral, longitudinal
 and full. No actuator dynamics are included. The conventional A-10
 model includes just the lateral dynamics.
Form
 x = A10( q )
Inputs
 q                      String describing the type of data
Outputs
 x                      The properties
Reference: 1. Liefer, R. K., "Eigenstructure Placement Design of Lateral-Directional Fire/Flight Control System For Advanced A-10 Aircraft, CSDL-T-764, December 1981. @iverbatim 2. Henwood, B. E., "A Decoupled Longitudinal Flight Control System for a Direct Force A-10 Aircraft," CSDL-T-766, December 1981. 3. Orr H. A., "An Integrated Fire/Flight Control System for a Conventionally Configured A-10 Aircraft," CSDL-T-794, December 1982.
References A10(), and and().
Referenced by A10(), and ESAssignDraper().
AC()
function AC (in x, in t, in dT, in d, in opt)
Updates the data structure x.
This model can include:
Flexible appendages
Spinning rotors
Nonlinear aerodynamics
Disturbance models
You can supply up to six routine names to customize the simulation:
 d.aero.name     = 'YourAeroFunctionName'        - default []
 d.actuator.name = 'YourActuatorFunctionName'    - default []
 d.engine.name   = 'YourEngineFunctionName'      - default []
 d.rotor.name    = 'YourRotorFunctionName'       - default []
 d.sensor.name   = 'YourSensorFunctionName'      - default []
 d.disturb.name  = 'YourDisturbanceFunctionName' - default []
 Your aerodynamics routine must be in the form:
 gAero = YourAeroFunctionName( alpha, beta, x, d.aero, qBar, control )
where gAero is a data structure that computes the forces and torques on all of the components and an addition the the mass and inertia matrix.
gAero is a data structure of the form:
 gAero.torque  (3,1) Core torques
 gAero.force   (3,1) Core forces
 gAero.modal   (:,1) Modal forces
 gAero.inertia (3,3) Delta inertia due to aerodynamics
 gAero.mass    (3,3) Delta mass matrix due to aerodynamics
If the last terms are zero return [] for them. All terms are in the body frame.
 Your engine routine must be in the form:
 gEngine = YourEngineFunctionName( x.engine, d.engine, control, altitude, machNo )
where gEngine is a data structure that contains the forces and torques on the aircraft due to the engines and the engine state derivatives.
gEngine is a data structure of the form
 gEngine.torque      (3,1) Core torques
 gEngine.force       (3,1) Core forces
 gEngine.dX          (:,1) Engine state derivatives
 gEngine.mDot        (1,1) Fuel consumption
 gEngine.inertiaDot  (3,3) Inertia derivative due to fuel consumption
 gEngine.cGDot       (3,1) CG derivative due to fuel consumption
 gEngine.torqueRotor (:,1) Torques on rotors
 Your rotor routine must be in the form:
 torque = YourRotorFunctionName( gEngine.torqueRotor, d.control, d.rotor )
where torque is a data structure that contains the torques on all rotors.
 gEngine.torqueRotor (:,1) Torques on rotors
 Your actuator routine must be in the form:
 [dXActuator, control] = YourActuatorFunctionName( x.actuator, d.control, d.actuator )
 where torque is a data structure that contains the torques on all rotors.
 Your sensor routine must be in the form:
 x = YourSensorFunctionName( x, d, opt )
 when opt = 'rhs'
 x = dXSensor
 when opt = 'meas'
 x = measurement
 Your disturbance routine must be in the form:
 disturb = YourDisturbanceFunctionName( x.disturb, d.disturb )
 where
 disturb.xDot   - disturbance state derivatives
 disturb.torque - disturbance torque
 disturb.force  - disturbance force
Form
 [x, measurement] = AC( x, t, dT, d, opt )
Inputs
 x             (:)         Aircraft state
                           r          (3,1) ECI position vector
                           q          (4,1) Quaternion from ECI to body
                           w          (3,1) Inertial body rate in body frame
                           v          (3,1) Velocity of cm wrt air
                           wR         (:,1) Angular velocity of rotors
                           mass       (1,1) Mass
                           inertia    (6,1) Inertia
                           cG         (3,1) Center of mass
                           engine     (:,1) Engine states
                           actuator   (:,1) Actuator states
                           sensor     (:,1) Sensor states
                           flex       (:,1) Flex model states organized [x;v] by appendage
                           disturb    (:,1) Disturbance model states
 t             (1,1)       Time
 dT            (1,1)       Time step
 d             (:)         Aircraft data structure
                           d.wPlanet  (3,1) Planet rate
                           d.mu       (1,1) Planet gravitational parameter
                           d.theta0   (1,1) Initial angle between planet
                                            x-axis and ECI x-axis
                           d.atmData  (1,:) Atmospheric data
                           d.atmUnits (1,:) Atmospheric data units
                           d.rotor    (:)   Rotor data structure
                                      .u       (3,1) Unit vector
                                      .inertia (1,1) Spin axis inertia
                           d.flex     (:)   See get BldFlex
                           d.engine   (:)   Private engine data structure
                           d.aero     (:)   Private aerodynamics data structure
                           d.actuator (:)   Private actuator data structure
                           d.sensor   (:)   Private sensor data structure
                           d.disturb  (:)   Private disturbance data structure
                           d.control  (:)   Control data structure
                                            .elevator
                                            .aileron
                                            .rudder
                                            .throttle
 opt           (1,:)       Options
                           'integrate'   (default)
                           'xdot'
                           'meas'
Outputs
 x             (:)         Aircraft state  'integrate'
                           acceleration    'xdot'
 measurement   (:)         Measurement data structure
                                            opt
References abs(), acstate(), AirData(), AlphBeta(), Altitude(), and(), BldFlex(), Cross(), Difference(), ECIToNED(), Eul2Q(), Euler(), get(), GetFlex(), IConv(), isempty(), length(), Mag(), Q2Eul(), QForm(), QIToBDot(), QMult(), QPose(), QTForm(), quaternion(), QUnit(), SkewSymm(), Unit(), vector(), and zeros().
Referenced by ACResistance(), AirshipLinMod(), AirshipTrim(), C2DelZOH(), C2DPulse(), C2DZOH(), CToDRand(), FResp(), FRespG(), GND(), GSS(), SkinDepth(), and SRiccati().
ACAero()
function ACAero (in alpha, in beta, in x, in d, in qBar, in control, in flex, in rho)
Form
 g = ACAero( alpha, beta, x, d, qBar, control, flex, rho )
Inputs
 alpha                 Angle of attack (deg)
 beta                  Sideslip (deg)
 x                     State
 d                     Aerodynamic data
 qBar                  Dynamic pressure
 control               Controls
                        .aileron
                        .rudder
                        .elevator
 flex                  Flex data structure
 rho                   Atmospheric density
Outputs
 g                   .torque  (3,1) Core torques
                     .force   (3,1) Core forces
                     .modal   (:,1) Modal forces
                     .inertia (3,3) Delta inertia due to aerodynamics
                     .mass    (3,3) Delta mass matrix due to aerodynamics
References ACAero(), and(), and vector().
Referenced by ACAero(), and DefaultACData().
ACBuild()
function ACBuild (in database)
Form
 d = ACBuild( database )
Inputs
 database       (1,:)      Database name
Outputs
 d             (:)         Aircraft data structure
                           .aero
                           .engine
                           .flex
                           .mu
                           .equatorialRadiusPlanet
                           .wPlanet
                           .name
                           .mu
                           .rotor
References Database(), vector(), and zeros().
Referenced by DefaultACData().
ACEngEq()
function ACEngEq (in d, in v, in r)
Form
 x = ACEngEq( d, v, r )
Inputs
 d                     Aircraft data
 v              (3,1)  Velocity
 r              (3,1)  Position
Outputs
 x                     Equilibrium engine state
See also
Altitude, AirData, ACEngine
References abs(), ACEngEq(), ACEngine(), AirData(), Altitude(), and Mag().
Referenced by ACEngEq().
ACEngine()
function ACEngine (in x, in d, in control, in altitude, in machNo)
 Uses a piecewise linear model to map throttle to commanded power and a
 lag to model the response of the throttle to the input command.
Form
 g = ACEngine( x, d, control, altitude, machNo )
Inputs
 x                     State
 d                     Engine data
 control               Controls
 machNo         (1,1)  Mach number
 altitude       (1,1)  Altitude
Outputs
 g                     Output data structure
                       .torque      (3,1) Core torques
                       .force       (3,1) Core forces
                       .xDot        (:,1) Engine state derivatives
                       .mDot        (1,1) Fuel consumption
                       .inertiaDot  (3,3) Inertia derivative due to fuel consumption
                       .cGDot       (3,1) CG derivative due to fuel consumption
                       .torqueRotor (:,1) Torques on rotors
See also
ACThrust
References ACEngine(), ACThrust(), Altitude(), and(), and zeros().
Referenced by ACEngEq(), ACEngine(), and DefaultACData().
ACInit()
function ACInit (in x, in d, in stateName)
Form
 d = ACInit( x, d, stateName )
Inputs
 x             (:)         Aircraft state
                           r          (3,1) ECI position vector
                           q          (4,1) Quaternion from ECI to body
                           w          (3,1) Inertial body rate in body frame
                           v          (3,1) Velocity of cm wrt air
                           wR         (:,1) Angular velocity of rotors
                           mass       (1,1) Mass
                           inertia    (6,1) Inertia
                           cG         (3,1) Center of mass
                           engine     (:,1) Engine states
                           actuator   (:,1) Actuator states
                           sensor     (:,1) Sensor states
                           flex       (:,1) Flex model states organized [x;v] by appendage
                           disturb    (:,1) Disturbance model states
 d             (:)         Aircraft data structure
                           d.wPlanet  (3,1) Planet rate
                           d.mu       (1,1) Planet gravitational parameter
                           d.theta0   (1,1) Initial angle between planet
                                            x-axis and ECI x-axis
                           d.atmData  (1,:) Atmospheric data
                           d.atmUnits (1,:) Atmospheric data units
                           d.rotor    (:)   Rotor data structure
                                      .u       (3,1) Unit vector
                                      .inertia (1,1) Spin axis inertia
                           d.flex     (:)   See get BldFlex
                           d.engine   (:)   Private engine data structure
                           d.aero     (:)   Private aerodynamics data structure
                           d.actuator (:)   Private actuator data structure
                           d.sensor   (:)   Private sensor data structure
                                            .name (:,:) Names
                           d.disturb  (:)   Private disturbance data structure
                           d.control  (:)   Control data structure
                                            .elevator
                                            .aileron
                                            .rudder
                                            .throttle
 stateName    (1,1)
 .sensor   {:}   Names for the sensor states
 .actuator {:}   Names for the actuator states
Outputs
 d             (:)         Aircraft data structure
References and(), BldFlex(), get(), Initialize(), Unit(), and vector().
Referenced by AirshipInit(), and AirshipTrim().
ACModes()
function ACModes (in g)
Form
 m = ACModes( g )
Inputs
 g           (:)   statespace data structure
Outputs
 m           (:)   Modes
References abs(), ACModes(), and(), eig(), get(), length(), Period(), statespace(), vector(), and zeros().
Referenced by ACModes().
ACPlot()
function ACPlot (in x, in opt, in d, in g, in nPts, in dT, in nSim)
opt is 'info', 'init', 'store', 'plot'
 If opt is 'info' d is a list of plots. Otherwise it is
 the d returned from ACPlot. The calls are
 d = ACPlot( x, 'init', plots, g, nPts, dT, nSim )
 do k = 1:nSim
 d = ACPlot( x, 'store', d, control )
 end
 ACPlot( x, 'plot', d )
 Possible plots are:
 Altitude
 Euler angles
 Quaternion
 Angular rate
 Position ECI
 Velocity
 Alpha (also get beta and total velocity)
 Mass
 Inertia
 CG
 Engine states
 Actuator states
 Sensor states
 Flex model states
 Disturbance model states
Form
 d = ACPlot( x, opt, d, g, nPts, dT, nSim )
Inputs
 x      (:)     Aircraft state vector or 'plot' if opt is 'store'
 opt    (n,:)   Options 'info'
                        'init'
                        'store'
                        'plot'
 d      (:)     Internal data structure or list of plots
 g      (:)     Aircraft data structure or d.control when opt = 'store'
 nPts   (1,1)   Number of plot steps
 dT     (1,1)   Sim time step
 nSim   (1,1)   Number of sim steps
 units  (1,:)   Units
Outputs
 d      (:)     Internal data structure or list of plots
References ACPlot(), AlphBeta(), Altitude(), and(), ECIToNED(), Euler(), EulNED(), get(), Initialize(), length(), Mag(), NewFig(), Plot2D(), QMult(), QPose(), quaternion(), set(), Throttle(), TimeLabl(), vector(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by ACPlot().
ACPointMassControl()
function ACPointMassControl (in x, in p, in dAC, in dC)
The controller controls velocity and angle of climb. dC.mode can be 'takeoff', 'climb' or 'bank'. It will automatically transition to climb if the velocity exceeds the takeoff velocity. The routine uses a combination of feedforward and feedback compensation.
When banking, the aircraft does not climb. However, you can set a bank angle during climb.
This function has two data structures. dC has the control specific data and dAC is aircraft data. dAC is the same datastructure used in RHS3DPointAircraft.m.
Form
 dC = ACPointMassControl( x, p, dAC, dC )
Inputs
 x   (7,1)  State [v;gamma;psi;x;y;h;m] (metric)
 p   (1,1)  Standard atmosphere data structure
 dAC     (.)  Data structure for aircraft
            .lDData     (1,1) Lift/drag data structure
           .cDCL       (1,1) Pointer to lift/drag function
           .thrust     (1,1) Pointer to the thrusst function
           .thrustData (1,1) Thrust data structure
           .lDData     (1,1) Lift/drag data structure
 dC      (.)  Control Data structure
           .vSet       (1,1) Setpoint for velocity
           .gammaSet   (1,1) Setpoint for flight path angle
           .bankSet    (1,1) Setpoint for bank angle
           .vTakeoff   (1,1) Takeoff velocity
           .mode       (1,:) Mode name
Outputs
 dC  (.)  Control data structure outputs
           .throttle (1,1) Throttle setting (0 to 1)
           .alpha    (1,1) Angle of attack (rad)
           .phi      (1,1) Bank angle
See also
RHS3DPointAircraft, AircraftPointMassControl.
References ACPointMassControl(), AircraftPointMassControl(), and(), Constant(), RHS3DPointAircraft(), set(), Takeoff(), and Throttle().
Referenced by ACPointMassControl().
ACSensor()
function ACSensor (in x, in d, in opt)
Outputs are:
z acceleration
roll rate (rad/sec)
angle of attack (deg)
Form
 g = ACSensor( x, d, opt )
Inputs
 x           (:)   acstate data structure
 d           (:)   Aircraft data structure
 opt               'rhs'  outputs state derivatives
                   'meas' outputs measurements
Outputs
 g           (:)   Sensor output
                   .aN        (1,1) Normal acceleration
                   .q         (1,1) Pitch rate
                   .alpha     (1,1) Angle of attack
                   .p         (1,1) Roll rates
                   .r         (1,1) Yaw rates
                   .altitude  (1,1) Altitude
                   .machNo    (1,1) Mach number
                   .qBar      (1,1) Dynamic pressure
References ACSensor(), acstate(), AirData(), AlphBeta(), Altitude(), get(), Mag(), and Normal().
Referenced by ACSensor(), and DefaultACData().
ACThrust()
function ACThrust (in idl, in mil, in max, in yH, in xM, in h, in m, in p)
Form
 thrust = ACThrust( idl, mil, max, yH, xM, h, m, p )
Inputs
 idl           (alt,mach)  Thrust coefficients for idle power
 mil           (alt,mach)  Military power
 max           (alt,mach)  Max Power
 yH            (alt)       Row coefficient values
 xM            (mach)      Columns of matrices
 h                         Altitude
 m                         Mach number
 p                         Power
Outputs
 thrust                    Thrust
References Altitude(), isempty(), and Plot2D().
Referenced by ACEngine().
ActiveAeroSurfacesDisplay()
function ActiveAeroSurfacesDisplay (in action, in varargin)
You initialize the function with a CAD data structure and then pass angle of attack and sideslip angles. Draws a 3D image. Has a demo of the X-15.
Form
 ActiveAeroSurfacesDisplay( 'initialize', g )
 ActiveAeroSurfacesDisplay( 'update', alpha, beta )
Inputs
 action         (1,:)  'initialize' or 'update'
 alpha          (1,:)  Angle of attack (rad)
 beta           (1,:)  Sideslip (rad)
 g              (1,1)  CAD data structure
Outputs
 None
References ActiveAeroSurfacesDisplay(), and(), Demo(), length(), LoadCAD(), vector(), and zeros().
Referenced by ActiveAeroSurfacesDisplay(), and NewtonianCPFromCAD().
ACTrim()
function ACTrim (in x, in d, in w, in g, in options)
Uses the function FTrim.
 This algorithm determines the Euler angles, body rates, engine state
 and control settings. Initial settings are obtained from d and g. Uses
 fminsearch.
Form
 [x, d, cost] = ACTrim( x, d, w, g, options )
Inputs
 x             (:)    Aircraft state
 d             (:)    Aircraft data structure
 w             (:,1)  Weights:
                       [vTDot, alphaDot, betaDot, wDot, vT, rDot, eDot, engDot]
 g             (:)    Constraint structure
                        .vT    (1,1) Velocity             (required)
                        .rDot  (1,1) Climb rate           (optional)
                        .eDot  (3,1) Euler angle rate     (optional)
 options              Options for fmins
Outputs
 x             (:)    Trimmed aircraft state
 d             (:)    Trimmed aircraft data structure
 cost                 .start
                      .end
References and(), Euler(), FTrim(), and length().
ACWeightEstimation()
function ACWeightEstimation (in d, in tol, in units, in fileName)
Any parameter can be varied except type.
 You vary the parameter by having more than one value in the array. You
 need to enter the fields of the datastruture in the order shown.
 Type ACWeightEstimation for a demo for a 150 seat passenger aircraft.
 This is an alternative to AircraftGroupMassStatement that uses a
 different weight model. Unlike AircraftGroupMassStatement this function
 will plots weights versus the parameter you let vary.
 Not all values of parameters will produce a feasible design. If the
 weight goes to infinity you will need to adjust some of your
 parameters. See the demo for a working set of inputs.
 The function will only print a table if you have one design.
Form
 g = ACWeightEstimation( d, tol, units, fileName )
Inputs
 d           (1,1)  Data structure with parameters
                     .type                 (1,:) 'military', 'transport'
                     .nPassengers          (1,n) Number of passengers
                     .weightPayload        (1,n) Weight of payload and crew
                     .dFuselage            (1,n) Fuselage diameter (ft/m)
                     .lFuselage            (1,n) Fuselage lengths (ft/m)
                     .thrustToWeight       (1,n) Thrust to weight ratio
                     .wingLoading          (1,n) Wing loading
                     .structuralLF         (1,n) Structural load factor
                     .thicknessRatio       (1,n) Thickness Ratio
                     .sweepAngle           (1,n) Sweep ratio
                     .tipRootChordRatio    (1,n) Tip Chord/Root Chord
                     .aspectRatio          (1,n) Aspect ratio
                     .thrustToEngineWeight (1,n) Thrust to Engine Weight
                     .fractionFuel         (1,n) Fuel to gross weight ratio
 tol         (1,1) Tolerance on computation
 units       (1,1) 'mks' or 'english'
 fileName   (1,:) Filename for the latex table (for one design)
Outputs
 g           (1,1)   Structure
                     .gWT           (1,n)  Gross weight or mass
                     .wingWT        (1,n)  Wing weight or mass
                     .fuselageWT    (1,n)  Fuselage weight or mass
                     .engineWT      (1,n)  Engine weight or mass
                     .fuelWT        (1,n)  Fuel weight or mass
                     .fixedEWT      (1,n)  Fixed equipment weight or mass
                     .empWT         (!,n)  Empanage weight or mass
                     .landingGearWT (1,n)  Landing gear
                     .passengerWT   (1,n)  Weight passengers
                     .payloadWT     (1,n)  Weight passengers
                     .miscWT        (1,n)  Everything else
References ACWeightEstimation(), AircraftGroupMassStatement(), and(), Fuselage(), length(), set(), Sweep(), and Wing().
Referenced by ACWeightEstimation().
ADC()
function ADC (in vT, in alt)
Form
 [aMach, qBar] = ADC( vT, alt )
Inputs
 vT             (1,1)  Velocity (ft/sec)
 alt            (1,1)  Altitude (ft)
Outputs
 aMach          (1,1)  Mach Number
 qBar           (1,1)  Dynamic pressure
References ADC(), and Altitude().
Referenced by ADC().
AdvanceRatio()
function AdvanceRatio (in v, in n, in d)
 Computes the advance ratio for a propeller. This is a dimensionless
 ratio used to compute the relative magnitude of the airspeed vs the
 propeller speed. Inversely proportional to the "tip speed ratio" and
 proportional but with a multiplying factor for the helicopter mu ratio.
 Type AdvanceRatio for a demo.
Form
 j = AdvanceRatio( v, n,d )
Inputs
 v  (1,:) Free stream velocity
 n  (1,:) RPS
 d  (1,1) Propeller diameter
Outputs
 j  (1,:) Advance ratio
Reference: Clancy, L.J. (1975), Aerodynamics, Section 17.2, Pitman Publishing Limited, London
References AdvanceRatio(), and(), Demo(), length(), and Plot2D().
Referenced by AdvanceRatio().
AeroCoefficientPointMass()
function AeroCoefficientPointMass (in aE, in bE, in h, in d)
 Adds the ground effect and includes a quadratic term for the sideforce
 in the drag polar.
Form
 [cD,cC,cL] = AeroCoefficientPointMass( aE, bE, h, d )
Inputs
 aE             (1,1)  Angle of attack
 bE             (1,1)  Sideslip angle
 h              (1,1)  Altitude
 d               (.)   Data structure
                       .cCScale (1,1) Sideforce scale
                       .cLAlpha (1,1) Lift slope
                       .aE0     (1,1) Zero lift angle
                       .cD0     (1,1) Zero lift drag
                       .aL      (1,1) Induced drag due to the lift
                                      coefficient
                       .aC      (1,1) Induced drag due to the sideforce
                                      coefficient
                       .l       (1,1) Wing span
Outputs
 cD             (1,1)  Drag coefficient
 cC             (1,1)  Side force coefficient
 cL             (1,1)  Lift coefficient
See also
GroundEffect and DragPolar
References AeroCoefficientPointMass(), Altitude(), and(), DragPolar(), GroundEffect(), and Wing().
Referenced by AeroCoefficientPointMass().
AeroD()
function AeroD (in f, in axisSystem)
 See DC8.m for an example of the database format.
 The state vector is either:
 'wind':      [vT; alpha; beta; p; q; r; phi; theta; psi]
 or
 'stability': [u; v; w; p; q; r; phi; theta; psi]
Form
 [g, gLat, gLon] = AeroD( f, axisSystem )
Inputs
 f                     Aircraft data or database for input
 axisSystem            'wind', 'stability'
Outputs
 g                     State space system of type statespace
 gLat                  Lateral dynamics
 gLon                  Longitudinal dynamics
References AeroD(), DC8(), EigEval(), Euler(), getsub(), statespace(), Step(), SVPlot(), Throttle(), vector(), and zeros().
Referenced by AeroD().
AerodynamicHeatFlux()
function AerodynamicHeatFlux (in m, in l, in p)
 Type AerodynamicHeatFlux for a demo.
Form
 qDot = AerodynamicHeatFlux( m, l, p )
Inputs
 m               (1,:)     Mach number
 l               (1,1)     Characteristic length (m)
 p                (.)      Standard atmosphere
Outputs
 qDot            (1,:)  Heat flux (W/m^2)
References AerodynamicHeatFlux(), Demo(), length(), NewFig(), and StdAtm().
Referenced by AerodynamicHeatFlux().
AerodynamicShock()
function AerodynamicShock (in m0, in p0, in gamma, in theta)
The default for theta is 90 degrees, a normal shock.
Type AerodynamicShock for a demo.
Form
 [m1, pTR, p1] = AerodynamicShock( m0, p0, gamma, theta )
Inputs
 m0    (1,:)  Free stream mach number
 p0     (1,:)  Free stream pressure
 gamma  (1,1)  Fluid ratio of specific heats
 theta  (1,1)  Oblique shock angle (rad)
Outputs
 m1    (1,:)  Mach number after the shock
 pTR    (1,1)  pt1/pt0
 p1     (1,:)  Pressure after the shock
Reference: Ames Research Staff, "Equations, Tables and Charts for Compressible Flow," Report 1135.
References AerodynamicShock(), and(), Demo(), length(), MachAcrossShock(), Pressure(), StdAtm(), vector(), and zeros().
Referenced by AerodynamicShock(), AerodynamicShockMinimize(), AerodynamicShockTest(), and RDE().
AerodynamicShockMinimize()
function AerodynamicShockMinimize (in m0, in p0, in gamma, in mF, in n, in opts)
Requires fmincon from the MATLAB optimization toolbox.
Type AerodynamicShockMinimize for a demo.
Form
 [pR, angle] = AerodynamicShockMinimize( m0, p0, gamma, mF, n, opts )
Inputs
 m0    (1,:)  Free stream mach number
 p0     (1,1)  Free stream pressure
 gamma  (1,1)  Fluid ratio of specific heats
 mF    (1,1)  Mach number after the final shock
 n      (1,1)  Number of shocks
 opts  (.)    Optimization parameters
Outputs
 pR     (1,1)  Total pressure ratio
 angle (1,n)  Shock angles (rad)
References AerodynamicShock(), AerodynamicShockMinimize(), Demo(), Gamma(), HasOptimizationToolbox(), Pressure(), set(), StdAtm(), vector(), and zeros().
Referenced by AerodynamicShockMinimize().
AeroForceAndTorqueCombined()
function AeroForceAndTorqueCombined (in alpha, in beta, in V, in e, in u, in d, in ignoredArg)
Form
 [force, torque, cL, cD] = AeroForceAndTorqueCombined( alpha, beta,
 V, e, u, d, display )
Inputs
 alpha          (1,:) Angle of attack
 beta           (1,:) Sideslip
 V              (1,:) Velocity
 e               (.)  Environment data structure
                      .a   (1,:) Speed of sound
                      .rho (1,:) Density
                      .kV  (1,:) Kinematic viscosity
                      .t   (1,:) Time vector
 u              (n,:) Control angle vector. Mapping is in d
 d               (.)  Data structure
                       .g  (.)   Aircraft CAD data structure for
                                 Newtonian Flow
                       .surface
                                .name (1,:) Name of surface
                       .logistic
                                .m    (1,1) Mach number for center
                                .a    (1,1) Coefficient
                                .b    (1,1) Coefficient
 display        (1,1)  If 1 display the active surfaces
Outputs
 force          (3,1)  Force in body frame (N)
 torque         (3,1)  Torque in body frame (Nm)
 cL             (1,:)  Lift coefficient
 cD             (1,:)  Drag coefficient
See also
NewtonianAerodynamicsFromCAD, InducedDragCoeff
References AeroForceAndTorqueCombined(), and(), ConcordeLD(), Demo(), InducedDragCoeff(), NewtonianAerodynamicsFromCAD(), Plot2D(), StdAtm(), vector(), and zeros().
Referenced by AeroForceAndTorqueCombined().
AeroFormFactor()
function AeroFormFactor (in type, in m, in d)
 For wings, fuselages and nacelles.
 Mach number and sweep ratio must be entered for wings.
Form
 k = AeroFormFactor( type, r )
Inputs
 type       (1,:) 'wing' 'fuselage' 'nacelle'
 m          (1,1)  Mach number (for wings)
 d                .r      (1,1)  Ratio: t/c for wing l/d for others
                  .lambda (1,1)  Quarter chord sweep
Outputs
 k          (1,:) Form factor
References AeroFormFactor(), and(), and Demo().
Referenced by AeroFormFactor(), and ParasiticDragCoefficient().
AIRC()
function AIRC (in q)
Form
 x = AIRC( q )
Inputs
 q                      String describing the type of data
Outputs
 x                      The properties
References AIRC(), and and().
Referenced by AIRC().
AircraftControl()
function AircraftControl (in action, in d)
 Action is either 'initialize' or update. You implement your controller
 in this function.
 Since version 3 (ACT)
Form
 y = AircraftControl( action, d )
Inputs
 action         (1,:)       Action for function
 d              (:)         Input
Outputs
 y              (1,1)       Output depends on action
References AircraftControl(), CInputs(), and Initialize().
Referenced by AircraftControl().
AircraftControlCAS()
function AircraftControlCAS (in action, in d)
Form
 y = AircraftControCAS( action, d )
Inputs
 action         (1,:)       Action for function
 d              (:)         Input
Outputs
 y              (1,1)       Output depends on action
References C2DZOH(), Initialize(), and Pilot().
AircraftCostCalculation()
function AircraftCostCalculation (in varargin)
Enter data as parameter pairs. It creates 3 latex tables in the files:
 filename_TotalRDTE.tex
 filename_TotalMA.tex
 filename_TotalOperations.tex
These can be imported into any Latex document.
Form
 c = AircraftCostCalculation( varargin )
Inputs
 varargin    Parameter pairs
 'filename'
 'weight'
 'cpi_now'
 'year'
 'speed'
 'cost per engine'
 'number of engines'
 'number of static test airplanes'
 'number of rdte airplanes'
 'block distance'
 'fuel weight'
 'fuel price'
 'fuel density'
 'number of airplanes'
 'number of years'
 'number of crew'
 'number of passengers'
 'rdte production rate'
 'cost passenger insurance'
 'cost cabin attendants'
 'cost passenger handling'
 'cost of maintaining ground equipment'
 'cost of depreciation of ground equipment'
 'cost of airplane servicing'
 'cost engine'
 'average flight time'
 'average block time'
 'material' - string (aluminum, stainless steel, alloy, composite
 'difficult'
 'cad savubg'
 'engineering dollar rate airframe'
 'observability'
 'cost meal service'
 'tooling labor rate'
 'profit r&d'
 'interest rate r&d'
 'interest rate manufacturing'
 'profit manufacturing'
 'hull insurace'
 'interior cost factor'
 'amount of mission fuel'
 'airframe and systems maintenance materials cost'
 'engine maintenance materials cost'
 'cost freight handling'
 'airframe depreciation factor'
 'propeller rpice'
 'number of aircraft'
 'number of flight hours per year per crew member'
 'cost propellers'
 'number of propellers per airplane'
 'engine spare parts depreciation factor'
 'engine spare parts factor'
 'engine spare parts depreciation period'
 'engine spare parts price factor'
 'test and simulation facilities cost'
 'spare parts depreciation factor'
 'spare parts factor '
 'spare parts depreciation period'
 'manufacturing manhour rate'
 'production flight test operation cost'
 'vacation pay constant'
 'salary reference year'
 'oil density'
 'oil cost'
 'aircraft naintenance rate'
 'engine maintenance hours'
 'engine maintenance labor rate'
 'engine depreciation factor'
 'maintenance hours flight'
 'overhead factor labor'
 'overhead factor materials'
 'cost depreciation propellers'
 'avionics depreciation factor'
 'avionics  depreciation period'
 'airplane depreciation period'
 'engine depreciation period'
Outputs
 All outputs are in latex tables
Reference: J. Roskam, "Airplane Design: Part VII: Airplane Cost Estimation Design, Development, Manufacturing and Operating," 1990. CPI Data, http://minneapolisfeorg/research/data/us/calc/hist1913.cfm CPI Calculator http://www.bls.gov/cpi/
References and(), Demo(), length(), Parameter(), and Takeoff().
AircraftDesign()
function AircraftDesign (in d, in n, in tol, in p)
The function generates the group mass statement for the aircraft from the range, speed and altitude of the aircraft along with the number of passengers and the payload. The input is a data structure described below.
The function fEngine is of the form
 [thrust, sfc] = MyEngine( mach, p );
where p is the datastructure from StdAtm.
Form
 d = AircraftDesign( d, n, tol, p )
Inputs
 d  (1,1)   Data structure
             .range                  (1,1) Aircraft range (km)
             .altitude               (1,1) Cruise altitude (km)
             .machClimb              (1,1) Climb and descent Mach
             .machCruise             (1,1) Cruise Mach
             .runway                 (1,1) Runway length (m)
             .fPAClimb               (1,1) Climb flight path angle (rad)
             .fEngine                (1,:) Engine function
             .nEngine                (1,1) Number of engines
             .tTaxi                  (1,1) Taxiing time (min)
             .nPassengers.economy    (1,1) Number of passengers economy
             .nPassengers.business   (1,1) Number of passengers business
             .nPassengers.first      (1,1) Number of passengers first
             .fuselage.length           (1,1) Fuselage length (m)
             .fuselage.diameter         (1,1) Fuselage diameter (m)
             .nCrew                     (1,1) Number of flight crew
             .mass                  (1,1) Mass (kg)
             .nAttendants               (1,1) Number of attendants
             .rhoFuel                   (1,1) Fuel density (kg/m^3)
             .specificMassTank          (1,1) Fuel tank specific mass (kg/kg)
             .s                         (1,1) Wing area (m^2)
             .length                 (1,1) Wing chord (m)
             .aspectRatio            (1,1) Wing aspect ratio
             .cLAlpha                (1,1) Lift coefficient (1/rad)
             .thickness                 (1,1) Wing thickness ratio
             .lOverD                    (1,1) Lift/Drag
 n   (1,1)   Steps per segment
 tol    (1,1)   Tolerance for the mass computation (kg)
 p   (1,1)   Group mass datastructure -
             see AircraftGroupDataStructure
Outputs
 d       (1,1)   Data structure
References AircraftDesign(), AircraftGroupDataStructure(), AircraftGroupMassStatement(), and(), Demo(), Fuselage(), length(), Plot2D(), Scimitar(), StdAtm(), TanD(), and Wing().
Referenced by AircraftDesign().
AircraftDragDataStructures()
function AircraftDragDataStructures (in aircraft)
 Includes the F4/Phantom II, A4/Skyhawk, Cessna 172, Boeing 747-400, and
 Airbus a380.
 Type AircraftDragDataStructures for a demo.
Form
 d = AircraftDragDataStructures( aircraft )
Inputs
 aircraft       (1,:)  Aircraft name
Outputs
 d              (1,1)  Aircraft parameters
                       .length      (1,1) Representative length (m)
                       .oswaldEff   (1,1) Oswald efficiency factor
                       .aspectRatio (1,1) Aspect ratio for wing (length/mean chord)
                       .thickness   (1,1) Ratio of length to thickness
                       .s           (1,1) Area (m^2)
                       .zetaTrans   (1,1) Transonic damping factor
                       .sweep       (1,1) Sweep angle (deg)
                       .a0          (1,1) Lift curve slope
                       .alpha0      (1,1) Zero lift angle of attack
                       .m0          (1,1) Mach number for linear skin
                                          friction coefficient
                       .cD0         (1,1) Zero lift drag coefficient
References AircraftDragDataStructures(), and(), Demo(), length(), LiftAndDrag(), StdAtm(), and Sweep().
Referenced by AircraftDragDataStructures(), AircraftEquilibrium(), and LiftAndDrag().
AircraftEquilibrium()
function AircraftEquilibrium (in mass, in gamma, in h, in m, in d)
 This function determines the required thrust and wing area to
 balance the drag and gravity forces at any flight condition. You can
 enter flight path angle, altitude, mach number and the drag data
 structure. gamma, h, and m can be vectors. The drag data structure
 can be an array to enter different wing characteristics for segments
 of the wing, for example in a double delta wing.
 Type AircraftEquilibrium for a demo.
Form
 [thrust, s] = AircraftEquilibrium( mass, gamma, h, m, d )
Inputs
 mass            (1,1)  Mass (kg)
 gamma           (1,:)  Flight path angle (rad)
 h               (1,:)  Altitude (m)
 m               (1,:)  Mach number
 d               (:)    Drag data structure  (See LiftAndDrag)
Outputs
 thrust          (1,:) Thrust
 s               (1,:) Wing area
See also
LDDeltaWing
References AircraftDragDataStructures(), AircraftEquilibrium(), Altitude(), and(), Demo(), LDDeltaWing(), length(), LiftAndDrag(), StdAtm(), Wing(), and zeros().
Referenced by AircraftEquilibrium().
AircraftGroupDataStructure()
function AircraftGroupDataStructure (in varargin)
Enter parameter pairs.
You can get a list of all parameters and default values by calling the function with no inputs. The parameter names are descriptive. All units are metric where applicable. This data structure is used with AircraftGroupMass and CAD/MassBudget.
The default value is used for any parameter pair you do not enter.
Form
 AircraftGroupDataStructure; % parameters and default values
 d = AircraftGroupDataStructure; % default parameters
 d = AircraftGroupDataStructure( varargin )
Inputs
 varargin {:}   Parameter pairs: parameter, value
Outputs
 d        (1,1) AircraftGroupMass data structure
References AircraftGroupDataStructure(), AircraftGroupMass(), and(), get(), and MassBudget().
Referenced by AircraftDesign(), and AircraftGroupDataStructure().
AircraftGroupMass()
function AircraftGroupMass (in group, in MTOM, in p)
 You pass in the subsystem name and the aircraft mass. As shown in the
 demo, you need to iterate on the function as you build up the aircraft
 mass. Type AircraftGroupMass for a demo which just calls
 AircraftGroupMassStatement.
Form
 m = AircraftGroupMass( group, MTOM, p )
Inputs
 group     (1,:) Group name
 MTOM      (1,1) Takeoff mass (kg)
 p         (1,1) Data structure for the aircraft
Outputs
 m        (1,1) Mass (kg)
References: Kundu, A., J. "Aircraft Design", Cambridge.
References AircraftGroupMass(), AircraftGroupMassStatement(), and(), Demo(), and Takeoff().
Referenced by AircraftGroupDataStructure(), AircraftGroupMass(), and MassBudget().
AircraftGroupMassStatement()
function AircraftGroupMassStatement (in mFuel, in p, in fileName)
 You pass in the mass of fuel and the datastructure with the aircraft
 parameters.
 Type AircraftGroupMassStatement for a demo.
Form
 [m, g] = AircraftGroupMassStatement( mFuel, p, fileName )
Inputs
 group     (1,:) Group name
 p         (1,1) Data structure for the aircraft (optional)
 fileName  (1,:) File name for latex table
Outputs
 m         (1,:) Group mass (kg)
 g         {:}   Group names
See also
AircraftGroupMass
References AircraftGroupMassStatement(), and and().
Referenced by ACWeightEstimation(), AircraftDesign(), AircraftGroupMass(), AircraftGroupMassStatement(), HSVMassEstimation(), and MissileMassEstimation().
AircraftPointMassCLPSim()
function AircraftPointMassCLPSim (in x0, in cmd, in t, in data)
 This simulation includes feedback control. The control law is based on
 feedback linearization, so that the closed loop system approximates a
 linear system with desirable dynamic properties.
 State:     x = [V;gama;psi;x;y;h;Tbar]
 V     true airspeed
 gama  air relative flight path angle
 psi   air relative flight heading angle
 x     East position
 y     North position
 h     altitude
 Tbar  normalized excess thrust
 Control:   u = [Lbar;phi;Tcbar]
 Lbar    normalized excess lift
 phi     bank angle
 Tcbar   normalized excess thrust command
 Command:   cmd = [h;v;psi;x;y]
 h       altitude command (m)
 v       velocity command (true airspeed, m/s)
 psi     heading command (rad)
 x       eastward position (m)
 y       northward position (m)
Form
 [x,u,xDot,cmd] = AircraftPointMassCLPSim( x0, cmd, t, data );
Inputs
 x0      (7,1)    Initial state vector
 cmd     (3,N)    Command vector (only h,v,psi need to be provided)
 t       (1,N)    Time vector for integration
 data             Data structure with fields:
                  a     Body-frame disturbance accel. (forward,x-track,normal)
                  W     Wind speeds (East,North,up)
                  g     Gravitatioanl acceleration
                  tau   Engine thrust response time
Outputs
 x       (7,N)    State vector
 u       (3,N)    Control input vector
 xDot    (7,N)    Time derivative of state vector
 cmd     (5,N)    Command vector (all command variables are output)
References AircraftPointMassCLPSim(), AircraftPointMassControl(), AircraftPointMassRHS(), length(), RK4(), vector(), Wind(), and zeros().
Referenced by AircraftPointMassCLPSim().
AircraftPointMassControl()
function AircraftPointMassControl (in x, in xDot, in cmd, in cmdDot, in Tcbar, in data)
 State:     x = [V;gama;psi;x;y;h;Tbar]
 V     true airspeed
 gama  air relative flight path angle
 psi   air relative flight heading angle
 x     East position
 y     North position
 h     altitude
 Tbar  normalized excess thrust
 Control:   u = [Lbar;phi;Tcbar]
 Lbar    normalized excess lift
 phi     bank angle
 Tcbar   normalized excess thrust command
 Command:   cmd = [h;v;psi;x;y]
 h       altitude command (m)
 v       velocity command (true airspeed, m/s)
 psi     heading command (rad)
 x       eastward position (m)
 y       northward position (m)
Form
 u = AircraftPointMassControl( x, xDot, cmd, cmdDot, Tcbar, data );
Inputs
 x       (7,1)    State vector
 xDot    (7,1)    Time derivative of state vector
 cmd     (5,1)    Command vector
 cmdDot  (5,1)    Time derivative of command vector
 Tcbar    (1)     Current value of normalzed excess thrust command
 data             Data structure with fields:
                     a     Body-frame disturbance accel. (forward,x-track,normal)
                     W     Wind speeds (East,North,up)
                     g     Gravitatioanl acceleration
                     tau   Engine thrust response time
Outputs
 u       (3,1)    Control input vector
References abs(), AircraftPointMassControl(), vector(), and Wind().
Referenced by ACPointMassControl(), AircraftPointMassCLPSim(), and AircraftPointMassControl().
AircraftPointMassDLM()
function AircraftPointMassDLM (in x, in u, in t)
 At each time step k, a linearized model of the open-loop aircraft
 dynamics is generated using APMLinMod. This continuous model is then
 discretized at a sampling time equal to the current time step, t(k+1)-t(k).
 The process is repeated to generate a matrix-form expression that
 describes small motion dx(t) about the nominal trajectory x(t).
 dx(t) = H*dx(0) + G*du(t)
 The control input to the linear system is du(t), which is small changes
 about the nominal control input u(t). The output is dy(t), which is
 just the position component (east, north, and altitude) of the state
 vector.
 dy(t) = C*dx(t)
 The vectors dx(t) and du(t) are column vectors, stacked over multiple
 time points. The sizes are:
 dy: 3*N rows, 1 column
 dx: 7*N rows, 1 column
 du: 3*N rows, 1 column
 H: 7*N rows, 7 columns
 G: 7*N rows, 3*N columns
 C: 3*N rows, 7*N columns
 State:     x = [V;gama;psi;x;y;h;Tbar]
 V     true airspeed
 gama  air relative flight path angle
 psi   air relative flight heading angle
 x     East position
 y     North position
 h     altitude
 Tbar  normalized excess thrust
 Control:   u = [Lbar;phi;Tcbar]
 Lbar    normalized excess lift
 phi     bank angle
 Tcbar   normalized excess thrust command
Form
 [A,B,C,G,H] = AircraftPointMassDLM( x, u, t );
Inputs
 x       (7,N)    State trajectory
 u       (3,N)    Control input trajectory
 t       (1,N)    Time vector over which trajectories are defined
Outputs
 A       (7,7)    Discrete linear state transition matrix (at last time)
 B       (7,3)    Discrete linear control effect matrix (at last time)
 C       (3N,7N)  State output matrix
 G       (7N,3N)  Discrete time varying input effect matrix
 H       (7N,7)   Discrete time varying state transition matrix
References AircraftPointMassDLM(), and(), APMLinMod(), C2DZOH(), vector(), and zeros().
Referenced by AircraftPointMassDLM().
AircraftPointMassRHS()
function AircraftPointMassRHS (in x, in u, in data)
 State:     x = [V;gamma;psi;x;y;h;Tbar]
 V     true airspeed
 gamma  air relative flight path angle
 psi   air relative flight heading angle
 x     East position
 y     North position
 h     altitude
 Tbar  normalized excess thrust
 Control:   u = [Lbar;phi;Tcbar]
 Lbar    normalized excess lift
 phi     bank angle
 Tcbar   normalized excess thrust command
Form
 xDot = AircraftPointMassRHS( x, u )
Inputs
 x        (7,1)   State vector
 u        (3,1)   Control vector
 data             Data structure with fields:
                     a     Body-frame disturbance acceleration
                           (forward,x-track,normal)
                     W     Wind speeds (East,North,up)
                     g     Gravitational acceleration
                     tau   Engine thrust response time
Outputs
 xDot     (7,1)   State time derivative
References AircraftPointMassRHS(), vector(), Wind(), and zeros().
Referenced by AircraftPointMassCLPSim(), AircraftPointMassRHS(), and AircraftPointMassSim().
AircraftPointMassRHSWithSideslip()
function AircraftPointMassRHSWithSideslip (in state, in ignoredArg, in u, in d)
 The function uses AtmDens2 for atmospheric density.
 The built-in aero model is
 cC = 2*pi*bE*d.cCScale;
 f  = GroundEffect( h, d.l );
 cL = 2*pi*f*(aE - d.aE0);
 cD = d.cD0 + d.aL*cL^2 + d.aC*cC^2;
 cCScale scales the effective lift in the y direction to the wing
 area. If you use your own aero function you, don't need these fields in
 d.
 If the point mass is within hTakeoff of the ground downward forces
 are balanced by the ground.
 Your supplied aerodynamics force function is of the form
 [cD,cC,cL] = feval( d.aerofun, alphaEff, betaEff, h, d )
 h is altitude. This allows you to model ground effect.
Form
 stateDot = AircraftPointMassRHSWithSideslip( state, t, u, d )
Inputs
 state          (7,1)  [v;gamma;psi;h;thrust;x;y]
 t              (1,1)  Time
 u              (4,1)  Control [angle of attack;side slip;bank angle;
                                thrust]
 d               (.)   Data structure
                       .mass    (1,1) Mass
                       .aeroFun (1,:) Name of aerodynamics function
                       .g       (1,1) Gravitational acceleration
                       .S       (1,1) Reference area
                       .hTakeoff(1,1) Altitude for ground force
                                      constraint
                       .l       (1,1) Wing span (for ground effect)
                       .cCScale (1,1) Sideforce scale
                       .aE0     (1,1) Zero lift angle
                       .cD0     (1,1) Zero lift drage
                       .aL      (1,1) Induced drag due to the lift
                                      coefficient
                       .aC      (1,1) Induced drag due to the sideforce
                                      coefficient
                       .vWP     (1,1) Wind
                       .cLAlpha (1,1) Lift curve slope
                       .tauThrust (1,1) Thrust time constant
Outputs
 stateDot      (7,1)  Derivative
Reference: T. Kinoshita1 and F. Imado, "The Application of an UAV Flight Simulator -The Development of a New Point Mass Model for an Aircraft-", SICE-ICASE International Joint Conference Oct. 18-21, 2006,Bexco, Busan, Korea.
References AircraftPointMassRHSWithSideslip(), and(), AtmDens2(), and DefaultDataStructure().
Referenced by AircraftPointMassRHSWithSideslip(), and SSFromNonlinear().
AircraftPointMassSim()
function AircraftPointMassSim (in x0, in u, in t, in data)
 This is an open loop simulation. No feedback is applied, only the
 specified control input u(t) is applied.
 State:     x = [V;gama;psi;x;y;h;Tbar]
 V     true airspeed
 gama  air relative flight path angle
 psi   air relative flight heading angle
 x     East position
 y     North position
 h     altitude
 Tbar  normalized excess thrust
 Control:   u = [Lbar;phi;Tcbar]
 Lbar    normalized excess lift
 phi     bank angle
 Tcbar   normalized excess thrust command
Form
 [x,xDot] = AircraftPointMassSim( x0, u, t, data );
Inputs
 x0      (7,1)    Initial state vector
 u       (3,N)    Control input vector
 t       (1,N)    Time vector for integration
 data             Data structure with fields:
                     a     Body-frame disturbance accel. (forward,x-track,normal)
                     W     Wind speeds (East,North,up)
                     g     Gravitatioanl acceleration
                     tau   Engine thrust response time
Outputs
 x       (7,N)    State vector
 xDot    (7,N)    Time derivative of state vector
References AircraftPointMassRHS(), AircraftPointMassSim(), length(), RK4(), vector(), Wind(), and zeros().
Referenced by AircraftPointMassSim().
AircraftPowerAndThrust()
function AircraftPowerAndThrust (in s, in d)
The built-in demo is for a Boeing 737-800
Form
 l = AircraftPowerAndThrust( s, d )
Inputs
 s   (1,:) Vector of trajectory segment data structures
           .phase       (1,:) Character array containing the name of
                              this segment
           .v           (1,1) Velocity of this segment. If v<3, assumes
                              v is the Mach number. (m/s or Mach)
           .h           (1,1) Starting altitude of this segment (m)
           .rateOfClimb (1,1) Rate of climb of this segment (m/s)
           .range       (1,1) If rateOfClimb is zero, the range of this
                              segment (m). If rateOfClimb is not zero,
                              range is automatically computed.
 d  (.)   Aircraft data structure, by default produced by Boeing737.m
 .mass    (1,1) Max takeoff mass (kg)
 .sFC     (1,1) Thrust-specific fuel consumption, kg/s*N
 .e       (1,1) Oswald efficiency
 .aR      (1,1) Aspect ratio
 .s       (1,1) Wing area (m^2)
 .cD0     (1,1) Zero-lift drag coefficient, clean
 .cLAlpha (1,1) Coefficient of lift over angle of attack
Outputs
 l   {}  Table of results, or l = struct('s','d'}
References and(), Boeing737(), set(), and Wing().
AircraftSizing()
function AircraftSizing (in d)
Uses a set of rules of thumb.
 Type AircraftSizing for a demo.
Form
d = AircraftSizing(r, m, h)
Inputs
 d   (.)    Data structure
           .r    (1,1)  Range (km)
           .m       (1,1)   Peak Mach number
           .h       (1,1)   Altitude (m)
           .fuel    (1,:) Type of fuel (H2, Jet)
           .mP   (1,1) Mass payload (kg)
Outputs
 d   (.)    Data structure augmented
 l    {}   Latex table
Reference: Eric M. Braun,Frank K. Lua, Donald R. Wilson, Jos A. Camberos, "Airbreathing rotating detonation wave engine cycle analysis", Aerospace Science and Technology 27 (2013) 201?208.
References AircraftSizing(), Altitude(), and set().
Referenced by AircraftSizing().
AircraftThrustFromFlight()
function AircraftThrustFromFlight (in h, in v, in vC, in mass, in d)
 Type AircraftThrustFromFlight for a demo
Form
 d      = AircraftThrustFromFlight;
 thrust = AircraftThrustFromFlight( h, v, vC, mass, d );
Inputs
 h       (1,:) Altitude (m)
 v       (1,:) Velocity (m/s)
 vC      (1,:) Rate of climb (m/s)
 mass    (1,:) Mass (kg)
 d       (.)   Aircraft data structure
               .e       (1,1) Oswald efficiency
               .aR      (1,1) Aspect ratio
               .s       (1,1) Wing area (m^2)
               .cD0     (1,1) Zero-lift drag coefficient, clean
               .cLAlpha (1,1) Coefficient of lift over angle of attack
Outputs
 thrust (1,:)   Thrust (N)
References abs(), AircraftThrustFromFlight(), Altitude(), DefaultDataStructure(), Demo(), InducedDragCoeff(), length(), StdAtm(), and Wing().
Referenced by AircraftThrustFromFlight().
AircraftTrajectoryControl()
function AircraftTrajectoryControl (in s, in d, in tauGamma, in tauV, in vSet, in gammaSet)
Computes the angle of attack and thrust for a 3D point mass aircraft. Only the first two elements of the state vector are used. It calls EquilibriumControls.
Form
 [T, alpha] = AircraftTrajectoryControl( s, d, tauGamma, tauV, vSet, gammaSet )
Inputs
 s     (:,1)   State vector [v;gamma;...]
 d     (.)     Data structure
               .m        (1,1) Aircraft mass (kg)
               .g        (1,1) Gravitational acceleration (m/s^2)
               .thrust   (1,1) Thrust (N)
               .alpha       (1,1) Angle of attack (rad)
               .phi      (1,1) Roll angle (rad)
               .s       (1,1) Surface area (m^2)
               .cD0     (1,1) Zero lift drag
                .k          (1,1) Lift drag coupling term
               .cLAlpha (1,1) Lift coefficient
 tau   (1,1)   Filter time constant
Outputs
 T     (1,1)   Thrust
 alpha (1,1)   Angle of attack
References AircraftTrajectoryControl(), and(), EquilibriumControls(), and vector().
Referenced by AircraftTrajectoryControl().
AircraftWeights()
function AircraftWeights (in range, in iSp, in lD, in u, in frac)
 The function generates the weights for an aircraft as a function
 of flight phase.
 frac is optional. Defaults are from Rayment.
 It uses the Bregeut range equation for cruise.
 Takeoff, climb and landiing use frac. 1-w(5) is the fraction of fuel.
 Type AircraftWeights for a demo of a 747-300
Form
 [w,phase,wFR] = AircraftWeights(range, iSp, lD, u, frac)
Inputs
 range   (1,1)  Range (km)
 iSp     (1,1) Cruise specific impulse (s)
 lD      (1,1) Cruise lift/drag ratio
 u       (1,1) Cruise velocity (km/hr)
 frac    (1,3) Fractional weight after [takeoff climb landing]
Outputs
 w       (1,5) Weight
 phase   {1,5} Corresponding phase
 wFR     (1,1) Weight fuel/Weight takeoff
References AircraftWeights(), and(), and Takeoff().
Referenced by AircraftWeights().
AirlinerSeat()
function AirlinerSeat (in w)
 Sizes it based on the width. It assumes only the width changes.
 Type AirlinerSeat for a demo.
Form
 [v, f, d] = AirlinerSeat( w )
Inputs
 w          (1,1) Width
Outputs
 v          (:,3)  Vertices
 f          (:,3)  Faces
 d          (1,3)  Dimensions
Reference: Fielding, J. P, "Introduction to Aircraft Design," Cambridge University Press, 1999.
References AirlinerSeat(), and(), Demo(), NewFig(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by AirlinerSeat(), and AirlinerSeats().
AirlinerSeats()
function AirlinerSeats (in d, in p)
Allows for first class, business class and economy.
Type AirlinerSeats for a demo.
Form
 d = AirlinerSeats( d, p )
Inputs
 d  (1,:)  Data structure
            .type        (1,:) 'First', 'Business', 'Economy', 'Other'
            .nRows       (1,1) Number of rows
            .pRow        (1,:) Pattern per row
 p   (1,1)  Data structure with parameters
            .pitch       (1,3) [first business economy]
            .width       (1,3) [first business economy]
            .widthAisle (1,3) [first business economy]
            .widthExit   (1,1) Exit aisle
            .exits       (1,1) Exit location row
Outputs
 d  (1,1)  Data structure
References AirlinerSeat(), AirlinerSeats(), and(), Demo(), isempty(), length(), NewFig(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by AirlinerSeats().
AirMass()
function AirMass (in h0, in theta)
 Uses the standard atmosphere.
 Type AirMass for a demo
Form
 m = AirMass( h0, theta )
Inputs
 h0             (1,1)  Altitude (km)
 theta          (1,:)  Angle from vertical (deg)
Outputs
 m              (1,:)  Relative air mass
References AirMass(), Altitude(), and(), Demo(), length(), Plot2D(), StdAtm(), and zeros().
Referenced by AirMass().
AlphaFromQNV()
function AlphaFromQNV (in q, in v, in n)
Form
 alpha = AlphaFromQNV( q, v, n )
Inputs
 q           (4,1) Quaternion from velocity frame to body
 v           (3,1) Velocity vector
 n           (3,:) Normals
Outputs
 alpha       (1,*) Angle of attack (rad)
References abs(), AlphaFromQNV(), AU2Q(), Demo(), Dot(), length(), Plot2D(), QForm(), vector(), and zeros().
Referenced by AlphaFromQNV().
AlphBeta()
function AlphBeta (in vB, in vBDot)
Form
 [alpha, beta, alphaDot, betaDot, vT, vTDot] = AlphBeta( vB, vBDot )
Inputs
 vB          (3,1) Velocity in the body frame
 vBDot       (3,1) Acceleration in the body frame
Outputs
 alpha       (1,1) Angle of attack (rad)
 beta        (1,1) Sideslip angle (rad)
 alphaDot    (1,1) Derivative of angle of attack (rad)
 betaDot     (1,1) Derivative of sideslip angle (rad)
 vT          (1,1) Total velocity
 vTDot       (1,1) Derivative of total velocity
Reference: Stevens, B.L., Lewis, F.L. , "Aircraft Control and Simulation," John Wiley & Sons, 1992, p. 64, 82.
References abs(), and(), and Mag().
Referenced by AC(), ACPlot(), ACSensor(), AirshipLinMod(), AirshipSensor(), AirshipStabConDerivatives(), AirshipTrim(), and JacobVB().
AngleOfAttackMaxLD()
function AngleOfAttackMaxLD (in cD0, in k, in cLA)
 This assumes
 cD = cD0 + k*cL^2
 cL = cLA*alpha
Form
 [alpha, lD] = AngleOfAttackMaxLD( cD0, k, cLA )
Inputs
 cD0         (1,1) Zero angle of attack drag
 k           (1,1) Induced drag coefficient
 cLA         (1,1) Lift curve slope
Outputs
 alpha       (1,1) Angle of attack (rad)
 lD          (1,1) Maximum lift over drag
References AngleOfAttackMaxLD(), Demo(), and Plot2D().
Referenced by AngleOfAttackMaxLD().
AOverAStar()
function AOverAStar (in gamma, in machNo)
Form
 a = AOverAStar( gamma, machNo )
Inputs
 gamma      (1,1)   Ratio of specific heats
 machNo     (1,:)   Mach number
Outputs
 a          (1,:)   A/A*
Reference: Mattingly, "Elements of Gas Turbine Propulsion," McGraw-Hill, 1996, p. 878.
References and(), AOverAStar(), Demo(), and Plot2D().
Referenced by AOverAStar(), MassFlow(), and MassInflowSupersonic().
APMLinMod()
function APMLinMod (in x, in u, in tau, in g)
 At each time step k, a linearized model of the open-loop aircraft
 dynamics is generated using APMLinMod. This continuous model is then
 discretized at a sampling time equal to the current time step, t(k+1)-t(k).
 The process is repeated to generate a matrix-form expression that
 describes the
 State:     x = [V;gama;psi;x;y;h;Tbar]
 V     true airspeed
 gama  air relative flight path angle
 psi   air relative flight heading angle
 x     East position
 y     North position
 h     altitude
 Tbar  normalized excess thrust
 Control:   u = [Lbar;phi;Tcbar]
 Lbar    normalized excess lift
 phi     bank angle
 Tcbar   normalized excess thrust command
Form
 [A,B] = APMLinMod( x, u, tau, g );
Inputs
 x       (7,1)    State trajectory
 u       (3,1)    Control input trajectory
 tau      (1)     Time constant for engine response
 g        (1)     Acceleration due to gravity (default 9.81)
Outputs
 A       (7,7)    State transition matrix (continuous time)
 B       (7,3)    Control effect matrix (continuous time)
References and(), APMLinMod(), and zeros().
Referenced by AircraftPointMassDLM(), and APMLinMod().
AspectRatio()
function AspectRatio (in b, in S)
Form
 aR = AspectRatio( b, S )
Inputs
 b       (1,1) Wingspan
 S       (1,1) Surface area
Outputs
 a        (1,1) Aspect ratio
References AspectRatio(), and Demo().
Referenced by AspectRatio().
AtmosphereLayers()
function AtmosphereLayers (in h)
 Type AtmosphereLayers for a picture of the atmosphere.
Form
 layer = AtmosphereLayers( h )
Inputs
 h              (1,1)  Altitude (km)
Outputs
 layer          (1,:)  Name of layer
Reference: http://www.ace.mmu.ac.uk/eae/Atmosphere/Older /Atmospheric_Layers.html
References Altitude(), and AtmosphereLayers().
Referenced by AtmosphereLayers().
BankedTurn()
function BankedTurn (in phi, in v)
 Type BankedTurn for a demo.
Form
 [r, v] = BankedTurn( n, phi )
Inputs
 v               (1,:) Velocity (m/s)
 phi             (1,:) Bank angle (rad)
Outputs
 n               (1,:) Lift/weight
 r               (1,:) Turning radius (m)
Reference: Mair, W. and D. L. Birdsall, "Aircraft Performance," Cambridge, p. 217-218.
References and(), BankedTurn(), Demo(), and Plot2D().
Referenced by BankedTurn().
BladeElement()
function BladeElement (in t, in vC, in omega, in d)
Assumes constant twist. v or omega can be length 1. The thrust and torque coefficients are by the U.S. convention, i.e. do not divide by solidity.
Form
 [vIT,q,cT,cQ,phi] = BladeElement(t,vC,omega,d)
Inputs
 t     (1,:) Thrust
 vC    (1,1) Velocity (m/s)
 omega (1,1) Rotational rate (rad/s)
 d     (.)   Data structure
             .a      (1,1) Lift curve slope
             .rho    (1,1) Density (kg/m^3)
             .b      (1,1) Number of blades
             .c      (1,1) Chord (m)
             .R      (1,1) Blade length (m)
             .theta1    (1,1) Blade washout angle (rad/m)
             .delta  (1,1) Local blade section drag coefficient
Outputs
 vI    (1,:) Induced velocity at the tip
 cT    (1,:) Thrust coefficient
 cQ    (1,:) Torque coefficient
 phi   (:,:) Inflow angle (Columns are for each element of t and q)
 s     (1,1) Blade solidity
Reference: Bramwell, A.R.S. "Helicopter Dynamics," Edward Arnold, 1976. pp. 90-96.
References and(), BladeElement(), DefaultDataStructure(), Demo(), and length().
Referenced by BladeElement().
BldFlex()
function BldFlex (in g, in useMode, in rBase, in bLocalToGlobal, in zeta)
Form
 d = BldFlex( g, useMode, rBase, bLocalToGlobal, zeta )
Inputs
 g              (:)     Flex model data structure
 useMode        (1,:)   Modes to use
 rBase          (3,1)   Base location
 bLocalToGlobal (1,:)   Name of model
 zeta           (1,:)   Modal damping
Outputs
 d              (:)     Model data structure
                .nModes (1,1)   Number of modes
                .name   (1,:)   Name of the component
                .k      (n,n)   Modal stiffness matrix
                .c      (n,n)   Modal damping matrix
                .iC     (n,3)   Modal coupling inertia matrix
                .fC     (n,3)   Force coupling matrix
                .phi    (n,6)   Transformation to modal coordinates
References BldFlex(), Demo(), isempty(), length(), SkewSymm(), and zeros().
Referenced by AC(), ACInit(), and BldFlex().
Boeing737()
function Boeing737 (in arg)
Calling without input produces a list of available parameters. All results are mks.
Form
 v = Boeing737(arg)
Inputs
 arg (1,:) Parameter, 'aspect ratio, 'wing area', etc.
Outputs
 v   (1,1) Value of request parameter
References: http://www.b737.org.uk/techspecsdetailed.htm Junzi Sun, Jacco M. Hoekstra, Joost Ellerbroek,"Aircraft Drag Polar Estimation Based on a Stochastic Hierarchical Model."
References Boeing737(), ListCases(), and Parameter().
Referenced by AircraftPowerAndThrust(), and Boeing737().
BreguetRangeEquation()
function BreguetRangeEquation (in d, in velocity, in altitude)
Form
 range = BreguetRangeEquation( d, velocity, altitude )
Inputs
 d              (1,1)  See "ConcordeProperties.m"
 velocity       (1,:)  Velocity (m/sec)
Outputs
 range         (1,:)  Range (km)
Reference: Mair, W. A. and D. L. Birdsall, "Aircraft Performance," Cambridge, pp. 167-168.
References and(), BreguetRangeEquation(), ConcordeProperties(), Demo(), Plot2D(), and StdAtm().
Referenced by BreguetRangeEquation().
BToS()
function BToS (in alpha, in opt)
Form
 b = BToS( alpha, opt )
Inputs
 alpha       (1,1) Angle of attack (rad)
 opt         (1,:) 'matrix' or 'quaternion'
Outputs
 b           (3,3) Transformation matrix
             (4,1) Quaternion
Reference: Stevens, B.L., Lewis, F.L. , Aircraft Control and Simulation, John Wiley & Sons, 1992, p. 63.
References and(), Mat2Q(), and quaternion().
BToW()
function BToW (in alpha, in beta, in opt)
Form
 b = BToW( alpha, beta, opt )
Inputs
 alpha       (1,1) Angle of attack (rad)
 beta        (1,1) Sideslip angle (rad)
 opt         (1,:) 'matrix' or 'quaternion'
Outputs
 b           (3,3) Transformation matrix
             (4,1) Quaternion
Reference: Stevens, B.L., Lewis, F.L., "Aircraft Control and Simulation," John Wiley & Sons, 1992, p. 63.
References Mat2Q(), and quaternion().
Referenced by AirshipStabConDerivatives().
CCVSobel()
function CCVSobel (in q)
Form
 x = CCVSobel( q )
Inputs
 q                      String describing the type of data
Outputs
 x                      The properties
Reference: Stevens, B.L., Lewis, F.L. , Aircraft Control and Simulation, John Wiley & Sons, 1992, pp. 354-358.
References and(), CCV(), CCVSobel(), EigEval(), isempty(), statespace(), Step(), SVPlot(), and zeros().
Referenced by CCVSobel().
CD0Composite()
function CD0Composite (in m, in d, in alpha, in p, in gamma)
 This combines subsonic, supersonic and hypersonic. All regimes
 have a Mach number correction. The skin friction model is selectable.
 If gamma is not entered it will be computed from p.
 Type CD0Composite for a demo at an altitude of 1 km.
Form
 [cD0, cDW, cDF, cDP] = CD0Composite( m, d, alpha, p, gamma )
Inputs
 m       (1,:)   Free stream Mach number
 d        (.)   Data structure
                 .length         (1,1) Characteristic length (m)
                 .oswaldEff      (1,1) Oswald efficiency factor
                 .aspectRatio     (1,1) Aspect ratio
                 .cDM1           (1,1) Drag coefficient at Mach 1
                 .mDD            (1,1) Drag divergence Mach number
                 .thicknessRatio    (1,1) Thickness to chord ratio
                 .model          (1,:) Skin friction model
 alpha   (1,:)   Angle of attack (rad)
 p        (.)    Standard atmosphere data structure
 gamma   (1,1)   Ratio of specific heats, optional
Outputs
 cD0      (1,:)     Drag coefficient
 cDW      (1,:)     Wave drag
 cDF      (1,:)  Skin friction drag
 cDP      (1,:)  Pressure drag
See also
CDWave, CPHypersonic, CDSkinFriction
References and(), AtmGamma(), CD0Composite(), CDSkinFriction(), CDWave(), CPHypersonic(), Demo(), isempty(), length(), Pressure(), and StdAtm().
Referenced by CD0Composite(), and CDCLComposite().
CDCLComposite()
function CDCLComposite (in m, in d, in alpha, in p)
 This combines subsonic, supersonic and hypersonic. All regimes
 have a Mach number correction.
Form
 [cL, cD, cD0] = CDCLComposite( m, d, alpha, p )
Inputs
 m       (1,:)  Freestream Mach number
 d        (.)  Data structure
                 .oswaldEff      (1,1) Oswald efficiency factor
                 .aspectRatio     (1,1) Aspect ratio
                 .cLM1           (1,1) Lift ratio at Mach 1
                 .cLAlpha        (1,1) Lift curve slope (1/rad)
                 .sweep          (1,1) Sweep angle (rad)
                 .l              (1,1) Characteristic length (m)
                 .u              (1,:) Velocity (m/s)
                 .nu             (1,1) Kinematic viscosity
                 .cDM1           (1,1) Drag coefficient at Mach 1
                 .mDD            (1,1) Drag divergence Mach number
                 .thicknessRatio    (1,1) Thickness to chord ratio
 alpha   (1,:)   Angle of attack (rad)
 p        (.)    Standard atmosphere data structure
Outputs
 cL      (1,:)  Lift coefficient
 cD      (1,:)  Drag coefficient
 cD0     (1,:)   Zero lift drag coefficient
See also
CLComposite, CD0Composite
References and(), CD0Composite(), CDCLComposite(), CLComposite(), Demo(), length(), Sweep(), and zeros().
Referenced by CDCLComposite().
CDCLHypersonic()
function CDCLHypersonic (in m, in alpha, in p, in l, in cParasitic)
Includes pressure effects, skin friction and parasitic drag.
The default Standard Atmosphere is at 1000 m.
Type CDCLHypersonic for a demo. One demo shows the variation of cD and cL with respect to Mach. The other shows the variation with respect to angle of attack. This function includes the pressure correction with Mach for cP. It also includes skin friction and parasitic drag.
Form
 [cD, cL] = CDCLHypersonic( m, alpha, p, l, cParasitic )
Inputs
 m           (1,:)    Freestream Mach number
 alpha       (1,:)   Angle of attack (rad)
 p            (.)    Standard atmosphere data structure
 l           (1,1)   Characteristic length
 cParasitic (1,1)   Parasitic drag
Outputs
 cD          (1,:)  Drag coefficient
 cL          (1,:)  Lift coefficient
See also
CPHypersonic, CDSkinFriction
References and(), AtmGamma(), CDCLHypersonic(), CDSkinFriction(), CPHypersonic(), Demo(), isempty(), length(), Plot2D(), and StdAtm().
Referenced by CDCLHypersonic(), OptimalAngleOfAttackHypersonic(), and RHSLiftingSatellite().
CDCLSubsonic()
function CDCLSubsonic (in m, in alpha, in p, in l, in aR, in e, in cLAlpha)
 The default Standard Atmosphere is at 1000 m. Default e is 0.95 and
 default aR is 6.
 Type CDCLSubsonic for a demo. One demo shows the variation of
 cD and cL with respect to Mach. The other shows the variation with
 respect to angle of attack.
Form
 [cD, cL] = CDCLSubsonic( m, alpha, p, l, aR, e, cLAlpha )
Inputs
 m           (1,:)    Freestream Mach number
 alpha       (1,:)   Angle of attack (rad)
 p            (.)    Standard atmosphere data structure
 l           (1,1)   Characteristic length
 e           (1,1)   Oswald efficiency factor (0 to 1)
 aR          (1,1)   Wing aspect ratio
 cLAlpha     (1,:)   Either a constant or a function handle
Outputs
 cD          (1,:)  Drag coefficient
 cL          (1,:)  Lift coefficient
See also
CDSkinFriction, InducedDragCoeff, DragPolar
References and(), CDCLSubsonic(), CDSkinFriction(), Demo(), DragPolar(), InducedDragCoeff(), length(), Plot2D(), and Wing().
Referenced by CDCLSubsonic().
CDSkinFriction()
function CDSkinFriction (in m, in l, in p, in model)
 The default is Prandtl-Schlichting. The default standard atmosphere
 is at 1000 m. 'miller' or 'compressible' should be used for
 supersonic flow.
 It uses 5e5 for Reynold's number at low speeds so that there isn't a
 low-speed singularity.
 Type CDSkinFriction for a demo of Prandtl-Schlichting and the
 compressible models.
Form
 cF = CDSkinFriction( m, l, p, model )
Inputs
 m          (1,:) Mach number
 l          (1,1) Characteristic length (m)
 p           (.)  Standard atmosphere data structures
 model      (1,:) Model. Available models:
                        'prandtl-schlichting'
                        'prandtl'
                        'kempf-karman'
                        'schultz-grunov'
                        'miller'
                        'compressible'
Outputs
 cF         (1,:) Skin friction
References: http://www.cfd-online.com/Wiki/Skin_friction_coefficient
References and(), CDSkinFriction(), Demo(), Friction(), isempty(), length(), Plot2D(), and StdAtm().
Referenced by CD0Composite(), CDCLHypersonic(), CDCLSubsonic(), CDSkinFriction(), DragCoeff(), FormDragCoeff(), LiftAndDragJonesSearsHaack(), OptimalAngleOfAttackHypersonic(), and ParasiticDragCoefficient().
CDWave()
function CDWave (in m, in alpha, in t, in mDD, in cDM1)
 It uses a logistic function to deal with the drag divergence region.
 Type CDWave for a demo.
Form
 cD = CDWave( m, alpha, t, cDM1 )
Inputs
 m           (1,:)  Freestream Mach number
 alpha       (1,1) Angle of attack (rad) (0 is the default)
 mDD         (1,1) Mach drag divergence  (0.8 is the default)
 t            (1,1) Thickness ratio       (0 is the default)
 cDM1        (1,1) Drag at Mach 1        (0.05 is the default)
Outputs
 cD          (1,:)  Drag coefficient
Reference: B. W. McCormick, "Aerodynamics, Aeronautics, and Flight Mechanics, John Wiley & Sons, 1979, pp. 274-279. J. D. Anderson Jr., "Introduction to Flight 3rd Edition", McGraw-Hill, 1989, p. 215.
References CDWave().
Referenced by CD0Composite(), and CDWave().
CLCDFreeMolecular()
function CLCDFreeMolecular (in v, in m, in tW, in beta, in tA, in sigmaN, in sigmaT)
If tA is entered, it will use Maxwellian. It has built in sigmaN and sigmaT.
Form
 CLCDFreeMolecular( v, m, tW, beta, tA, sigmaN, sigmaT )
Inputs
 v          (1,1) Velocity  (m/sec)
 m          (1,1) Mean molecular weight
 tW     (1,1) Plate data structure
 beta   (1,:) Angle between the plate and the flow
 tA     (1,1) Atmospheric Temperature
 sigmaN (1,:) Normal accommodation coefficients
 sigmaT (1,:) Tangential accommodation coefficients
Outputs
 cL     (1,:) Lift coefficient
 cD      (1,:) Drag coefficient
Reference: Storch, J.A., "Aerodynamic Disturbances on Spacecraft in Free-Molecular Flow," October 2002, SMC-TR-03-06.
References AccommodationCoefficients(), and(), AtmTemp(), CLCDFreeMolecular(), Constant(), Demo(), isempty(), MolWt2R(), Normal(), and Plot2D().
Referenced by CLCDFreeMolecular().
CLCMWing()
function CLCMWing (in alpha, in z)
Form
 CLCMWing( alpha, z )
 [cL, cM] = CLCMWing( alpha, z )
Inputs
 alpha       (1,:) Angle of attack (rad)
 z           (1,:) Camber ratio z = 1/8R where R is the radius of
                   curvature
Inputs
 cL          (1,:) Lift coefficent
 cM          (1,:) Quarter chord moment coefficient
 cL0         (1,:) Lift coefficent at zero angle of attack
Reference: McCormick, B. W., "Aerodynamics, Aeronautics and Flight Mechanics," Wiley, 1979, p. 86.
References and(), and CLCMWing().
Referenced by CLCMWing().
CLComposite()
function CLComposite (in m, in d, in alpha, in gamma)
This combines subsonic, supersonic and hypersonic. All regimes have a Mach number correction. If alpha is not entered it will compute just the lift curve coefficient.
 Type CLComposite for a demo.
Form
 cL = CLComposite( m, d, alpha, gamma )
Inputs
 m       (1,:)    Freestream Mach number
 d        (.)    Data structure
                 .cLM1           (1,1) Lift ratio at Mach 1
                 .cLAlpha        (1,1) Lift curve slope (1/rad)
                 .sweep          (1,1) Sweep angle (rad)
                 .thicknessRatio    (1,1) Thickness to chord ratio
 alpha   (1,:)   Angle of attack (rad)
 gamma   (1,1)   Ratio of specific heats (Default = 1.4)
Outputs
 cL      (1,:)  Lift coefficient
See also
CPHypersonic
References abs(), and(), CLComposite(), CPHypersonic(), Demo(), get(), isempty(), length(), Plot2D(), and Sweep().
Referenced by CDCLComposite(), and CLComposite().
ClimbAngle()
function ClimbAngle (in h, in v, in d)
 Ground effect is included and the scale factor is the square root of s.
 This uses DragCoeff for the drag coefficients. If the altitude is zero
 then the gravity force is assumed to be zero.
 Type ClimbAngle for a demo
Form
 gamma = ClimbAngle( h, v, d )
Inputs
 h               (1,:) Altitude (m)
 v               (1,:) Velocity (m/s)
 d                (.)  Data structure
                       .mass         (1,1) Mass (kg)
                       .s            (1,1) Reference area (m^2)
                       .cLAlpha      (1,1) Lift coefficient
                       .thrust       (1,:) Thrust force (N)
                       .length       (1,1) Representative length (e.g. mean chord) (m)
                       .oswaldEff    (1,1) Oswald efficiency factor (optional)
                       .aspectRatio (1,1) Aspect ratio for wing (length/mean chord)
                       .thickness    (1,1) Ratio of length to thickness
                       .m1Peak       (1,1) Peak at M = 1 an alternative to zetaTrans
Outputs
 gamma          (1,:) Climb angle
See also
DragCoeff
References abs(), Altitude(), and(), ClimbAngle(), Constant(), Demo(), DragCoeff(), length(), Plot2D(), RHS(), square(), StdAtm(), and zeros().
Referenced by ClimbAngle().
ComputeAlphaConstantFlightPathAngle()
function ComputeAlphaConstantFlightPathAngle (in x, in d)
Form
 alpha = ComputeAlphaConstantFlightPathAngle( x, d )
Inputs
 x          (4,1)   [v;gamma;h;m]
 d           (.)    Data structure
                    .aero     (.)   Aero data structure
                    .cDCL     (1,1) Pointer to lift and drag function
                   .thrust   (1,1) Thrust
                   .atmData  (.)   Data structure
Outputs
 alpha      (1,1)   Angle of attack (rad)
References and(), ComputeAlphaConstantFlightPathAngle(), SimpleLiftAndDrag(), and StdAtm().
Referenced by ComputeAlphaConstantFlightPathAngle(), and TurboRamjetSim().
ConcordeLD()
function ConcordeLD (in m)
Output is function of Mach number. Type ConcordeLD for a demo
Form
 [cL, cD, k1, k2] = ConcordeLD( m )
Inputs
 m          (1,:) Mach number
Outputs
 cL         (1,:) Lift coefficient
 cD         (1,:) Drag coefficient
 k1         (1,:) Drag at zero lift
 k2         (1,:) Drag from lift coefficient (Induced drag)
Reference: Austyn Mair, W. and D.L.L. Birdsall (1992.) Aircraft Performance. Cambridge. pp. 40-41 and p.261.
References and(), and ConcordeLD().
Referenced by AeroForceAndTorqueCombined(), ConcordeLD(), and LiftAndDragJonesSearsHaack().
ConcordeProperties()
function ConcordeProperties (in machNo)
The SFC and F/delta are only valid between M = 1 and M = 2.
Form
 d = ConcordeProperties( machNo )
Inputs
 machNo         (1,1)  Mach number
Outputs
 d               (.)   Aircraft parameters
                       .massDry     (1,1)
                       .massFuel    (1,1)
                       .massDesign  (1,1) Design point for calculations
                       .sFC         (1,:) Specific fuel consumption
                       .cL          (1,:) Lift coefficient
                       .cD          (1,:) Drag coefficient
                       .k1          (1,:) Drag polar coefficient 1
                       .k2          (1,:) Drag polar coefficient 2
                       .wingArea    (1,1) Wing area (m^2)
                       .wingLoading (1,1) Wing loading
                       .name        (1,:) Name
                       .cLCoeff     (1,1) Lift coefficient
                       .cLMax       (1,1) Maximum lift coefficient
                       .fOverDelta  (1,:) Force over P/P0
 def             {:,3} Property definitions
Reference: Mair, W. A. and D. L. Birdsall, "Aircraft Performance," Cambridge, pp. 167-168.
References and(), and Wing().
Referenced by BreguetRangeEquation(), and RateOfClimb().
ConstantDynamicPressureVelocity()
function ConstantDynamicPressureVelocity (in h, in q, in atmData)
Computes the velocity and Mach number profile for constant dynamic pressure as a function of altitude and desired dynamics pressure. This function uses StdAtm. This profile is useful for ramjets and scramjets.
For speed, if using in a loop, pass it atmData which can be loaded with the operation:
atmData = load('AtmData.txt');
Type ConstantDynamicPressureVelocity for an example with a dynamic pressure of 7000 N/m^2.
Form
 [v, mach] = ConstantDynamicPressureVelocity( h, q, atmData )
Inputs
 h         (1,:) Altitude (km)
 q         (1,1) Dynamic pressure (N/m^2)
 atmData   (1,:) File name for standard atmosphere
Outputs
 v         (1,:) Velocity (m/s)
 mach      (1,:) Mach number
References Altitude(), and(), Constant(), ConstantDynamicPressureVelocity(), Demo(), PlotDoubleYAxis(), Pressure(), and StdAtm().
Referenced by ConstantDynamicPressureVelocity().
CPHypersonic()
function CPHypersonic (in m, in gamma)
Type CPHypersonic for a demo.
Form
 cP = CPHypersonic( m, gamma )
Inputs
 m       (1,:) Freestream Mach number
 gamma   (1,1) Ratio of specific heats (Default = 1.4)
Outputs
 cP      (1,:) Pressure coefficient
References CPHypersonic(), Demo(), isempty(), length(), Plot2D(), Pressure(), RayleighPitotTube(), and zeros().
Referenced by CD0Composite(), CDCLHypersonic(), CLComposite(), CPHypersonic(), and OptimalAngleOfAttackHypersonic().
CreateAircraftModel()
function CreateAircraftModel (in file)
To build a model type CreateAircraftModel('MyOBJFile.obj'). Then enter data in the GUI by using the mouse to pick points to compute geometric properties.
The function automatically computes the inertia matrix and center of mass from the model. This is computed for an areal mass of 1. When you add an aircraft mass, the inertia will be updated.
The data can be stored in a data structure in a .mat file. The input file must be of type .obj. There are many ways to convert file types. For example you can convert a .stl file to a .obj file using this web page:
https://www.meshconvert.com
Type CreateAircraftModel for a demo of a Gulfstream 350.
Form
 CreateAircraftModel( file )
Inputs
 file  (1,:) File name - needs to be a complete path name
Outputs
 Saves to a MAT file
References and(), CreateAircraftModel(), Demo(), InertiaFromOBJFile(), length(), LoadCAD(), set(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by CreateAircraftModel(), and RHSACFlatEarth().
CTPropeller()
function CTPropeller (in angle, in j)
 This is the minimum power to drive a propeller. This is based on
 actuator disk theory.
 Type CTPropeller for a demo.
Form
 cT = CTPropeller( angle, j )
Inputs
 angle   (1,:) deg
 j       (1,:) Advance ratio
Outputs
 cT     (1,:) Thrust coefficient
Reference: McCormick 1979, Figure 7.8.
References CTPropeller(), Demo(), length(), and Plot2D().
Referenced by CTPropeller().
DC8()
function DC8 (in q, in n)
Form
 x = DC8( q, n )
Inputs
 q                      String describing the type of data
 n                      Set
Outputs
 x                      The properties
Reference: McRuer, D., Ashenas, I., and D. Graham, Aircraft Dynamics and Automatic Control, Princeton, 1973, pp. 711-714
References and(), and DC8().
Referenced by AeroD(), and DC8().
DefaultACData()
function DefaultACData ()
The F16 model is used.
Form
 x = DefaultACData
Inputs
 None
Outputs
 d             (:)         Aircraft data structure
References ACAero(), ACBuild(), ACEngine(), ACSensor(), DefaultACData(), and F16().
Referenced by DefaultACData().
DefaultACState()
function DefaultACState ()
Form
 x = DefaultACState;
Inputs
 None
Outputs
 x               Aircraft state vector, consisting of:
                  - r       (3,1) ECI position vector
                  - q       (4,1) Quaternion from ECI to body
                  - w       (3,1) Inertial body rate in body frame
                  - v       (3,1) Velocity of cm wrt air
                  - wR      (:,1) Angular velocity of rotors
                  - mass    (1,1) Mass
                  - inertia (6,1) Inertia
                  - cG      (3,1) Center of mass
                  - engine  (:,1) Engine states
                  - actuator(:,1) Actuator states
                  - sensor  (:,1) Sensor states
                  - flex    (:,1) Flex model states
                  - disturb (:,1) Disturbance model states
References acstate(), DefaultACState(), ECIToNED(), Eul2Q(), Initialize(), QMult(), quaternion(), vector(), and VTToVB().
Referenced by DefaultACState().
DragCoeff()
function DragCoeff (in d, in mach, in p, in cP)
 You will have to call this routine for the wing, fuselage and tail
 separately using different characteristic lengths. The wing and tail use
 the mean chord and the fuselage uses the length.
 Altitude and mach must be the same length or altitude can be length 1.
 zetaTrans is a factor to prevent the form drag from becoming
 infinite at M = 1. The default produces a factor of 10 drag rise
 at M = 1.
 The default of the Oswald Efficiency factor is 0.95.
 The drag will be cD0 + kInduced*cL^2
 The supersonic and subsonic drag formulas are blending at M = 1.
 Type DragCoeff for a demo.
 If no output arguments are used it will plot the various components
 of drag.
Form
 [cD0, kInduced, y] = DragCoeff( d, mach, p, cP )
Inputs
 d               (.)   Aircraft parameters
                       .length      (1,1) Representative length (e.g. mean chord) (m)
                       .oswaldEff   (1,1) Oswald efficiency factor (optional)
                       .aspectRatio (1,1) Aspect ratio for wing (length/mean chord)
                       .thickness   (1,1) Ratio of length to thickness
                       .s           (1,1) Reference area
                       .zetaTrans   (1,1) Damping for transonic (optional)
                       .m1Peak      (1,1) Peak at M = 1 an alternative to zetaTrans
 mach           (1,n)  Mach number
 p               (.)   Standard atmosphere data structure
 cP             (1,1)  Parasitic drag coefficient
Outputs
 cD0            (1,n) Zero lift drag coefficient
 kInduced        (1,n) Drag induced due to lift
 y               (.)  Data structure output
                       .cD0
                       .skinFriction
                       .kInduced
                       .formDrag
                       .parasiticDrag
Reference: Miller, R. "16.751 Class Notes," MIT, 1977. Anderson, J. D., "Introduction to Flight 3rd Edition," McGraw-Hill, 1989.
References Altitude(), and(), CDSkinFriction(), Demo(), DragCoeff(), FormDragCoeff(), InducedDragCoeff(), isempty(), length(), and StdAtm().
Referenced by ClimbAngle(), DragCoeff(), FlightEquilibrium(), Glide(), and LiftAndDrag().
DragLoss()
function DragLoss (in m, in d)
 This function is most useful for supersonic vehicles. It gives you the
 loss in delta-v due to drag. This routine uses Euler integration.
 mdV/dt = T - D
 dV     = (T-D)*dt/m
 dm/dt  = -T/uE
 Type DragLoss for a demo of the Concorde.
Form
 dV = DragLoss( m, d )
Inputs
 m  (1,:) Mach number
 d   (.)  Data structure
           .l   (1,1) Aircraft length (m)
           .h   (1,:) Altitude (m)
           .p   (1,1) Standard Atmosphere
           .b   (1,1) Span (m)
           .s   (1,1) Surface area (m^2)
           .v   (1,1) Volume (m^3)
           .sL  (1,1) Lifting surface (m^2)
           .uE  (1,1) Exhaust velocity (m/s)
           .t   (1,1) Thrust (N)
           .m   (1,1) Initial mass (kg)
Outputs
 dV (1,:) Drag loss (m/s)
References Altitude(), and(), Demo(), DragLoss(), Euler(), length(), LiftAndDragJonesSearsHaack(), and Wing().
Referenced by DragLoss().
DragPolar()
function DragPolar (in cD0, in cL, in kI)
 Computes the drag polar, cD = cD0 + k*cL^2
 This is the simplest realistic drag model for an aircraft.
 Type DragPolar for a demo.
Form
 cD = DragPolar( cD0, cL, kI )
Inputs
 cD0   (1,:)  Zero lift drag coefficient
 cL    (1,:)  Lift coefficient
 kI    (1,:)  Induced drag coefficient
Outputs
 cD    (1,:)  Drag coefficient
Reference: John D. Anderson, Jr. "Introduction to Flight", 3rd Edition, McGraw-Hill, 1989
References Demo(), DragPolar(), and Plot2D().
Referenced by AeroCoefficientPointMass(), CDCLSubsonic(), and DragPolar().
DragPolarFromData()
function DragPolarFromData (in cD, in cL)
 The drag polar is cD = cD0 + k*cL^2
 Does a least squares curve fit.
 Type DragPolarFromData for a demo.
Form
 [cD0, k] = DragPolarFromData( cD, cL )
Inputs
 cD      (1,:)   Drag coefficients
 cL      (1,:)   Lift coefficients
Outputs
 cD0     (1,1)   Drag at zero lift
 k       (1,1)   Induced drag coefficient
References and(), Demo(), DragPolarFromData(), and LeastSq().
Referenced by DragPolarFromData().
DragUndercarriage()
function DragUndercarriage (in m, in s, in f)
 Type  DragUndercarriage for a demo.
Form
 deltaCD = DragUndercarriage( m, s, f )
Inputs
 m              (1,1)  Mass (m)
 s              (1,1)  Reference area (m^2)
 f              (1,1)  If entered the flaps are down
Outputs
 deltaCD        (1,1)  Change in drag coefficient
Reference: Mair, W. A. and D. L. Birdsall, "Aircraft Performance," Cambridge, p. 124.
References and(), and DragUndercarriage().
Referenced by DragUndercarriage().
DrawAC()
function DrawAC (in mode, in g, in x, in h, in units)
The aircraft state vector can either be of type acstate or
 x.r
 x.q
or [r;v;q;omega]
Form
 h = DrawAC( mode, g, x, h, units )
Inputs
 mode        (1,:) 'run', 'init', 'close'
 g                 Aircraft image data structure
 x                 Aircraft state vector
 h                 Handles to the display
 units       (1,:) Units
Outputs
 h                 Handles to the display
References acstate(), Altitude(), close(), Constant(), DrawTerrain(), ECIToNED(), get(), isempty(), length(), Q2Mat(), QMult(), QPose(), quaternion(), set(), Trans3DMF(), vector(), XLabelS(), YLabelS(), and ZLabelS().
DrawAircraft()
function DrawAircraft (in action, in g, in h, in x, in t, in tU)
Draws an aircraft consisting of multiple components. The demo loads Gulfstream.obj.
Form
 DrawAircraft;   % demo
 h = DrawAircraft( 'initialize', g )
 DrawAircraft( 'update', g, h, x, t, tU )
Inputs
 action    (1,:) 'initialize', 'update', 'movie'
 g         (.)
                 .name       (1,:) Name of object
                 .radius     (1,1) Radius of the entire object
                 .component  (.)   Component data structure
                                   .v        (:,3)   Vertices
                                   .f        (:,3)   Faces
                                   .color    (1,3    Color
                                   .name     (1,:)   Name of the component
                 .offset     (3,1) Offset of image center
 h        (1,:) Handles to the patches
 x        (3,:) [r;v;q;omega]
 t        (1,:) Time vector
 tU       (1,:) Time units
Outputs
 h        (.)
               .fig  (1,1) Handles to the figure
               .h    (1,k) Handles to the patches
 mV       (1,:) Movie frames
References close(), CosD(), Demo(), DrawAircraft(), DrawAlphaBeta(), DupVect(), get(), isempty(), length(), LoadCAD(), Mat2Q(), NewFig(), Q2Mat(), QMult(), SaveMovie(), set(), SinD(), Unit(), vector(), and zeros().
Referenced by DrawAircraft().
DrawAlphaBeta()
function DrawAlphaBeta (in p0, in q, in vB, in l)
If your figure does not use axis image the arrows may look strange.
Type DrawAlphaBeta for a demo.
Form
 DrawAlphaBeta( p0, q, vB, l )
Inputs
 p0    (3,1) Origin
 q     (4,1) XYZ to body
 vB    (3,1) Body frame velocity
 l     (1,1) Vector length
Outputs
 h     (1,:) Handles to objects
References and(), Demo(), DrawAlphaBeta(), length(), NewFig(), QForm(), Unit(), and zeros().
Referenced by DrawAircraft(), and DrawAlphaBeta().
DrawAngles()
function DrawAngles (in p0, in p, in name)
You can name the angles with the optional name argument. If your figure does not use axis image the arrows may look strange.
Type DrawAngles for a demo.
Form
 DrawAngles( p0, p, name )
Inputs
 p0    (3,1) Origin
 p     (3,:) End points
 name  {:}   Names of the angle
Outputs
 None
References and(), and DrawAngles().
Referenced by DrawAngles().
DrawTerrain()
function DrawTerrain (in type, in d, in hAxes)
Form
 [h, v] = DrawTerrain( type, d, hAxes )
Inputs
 type        (1,:) Type 'flat' is the only option
 d           (1,1) Dimension data, for 'flat'
                   d.w width of grid
                   d.n number of points
 hAxes       (1,1) Handle to axes
Outputs
 h                 Handle to the patch
 v                 Vertices
References zeros().
Referenced by DrawAC().
DynamicPressureAndHeat()
function DynamicPressureAndHeat (in h, in l, in qMax)
 Type DynamicPressureAndHeat for a demo at the Space Shuttle maximum
 dynamic pressure.
Form
 [v, t, qDot] = DynamicPressureAndHeat( h, l, qMax )
Inputs
 h               (1,:)     Altitude (km)
 l               (1,1)     Initial flight path angle at h0 (rad)
 qMax            (1,1)     Maximum dynamic pressure
Outputs
 v               (1,:)     Velocity (m/s)
 t               (1,:)     Temperature stagnation (deg-K)
 qDot            (1,:)     Heat flux (W/m^2)
References Altitude(), and(), Demo(), DynamicPressureAndHeat(), Plot2D(), Pressure(), StdAtm(), and TemperatureStagnation().
Referenced by DynamicPressureAndHeat().
ECIToNED()
function ECIToNED (in r, in opt, in f)
Form
 b = ECIToNED( r, opt, f )
Inputs
 r           (3,1) Position vector ECI
 opt         (1,:) 'matrix' or 'quaternion'
                     (default is matrix)
 f           (1,1) Flattening factor (optional)
Outputs
 b           (3,3) Transformation matrix
             (4,1) Quaternion
Reference: Stevens, B.L., Lewis, F.L., Aircraft Control and Simulation, John Wiley & Sons, 1992, p. 36.
References abs(), and(), isempty(), Mat2Q(), quaternion(), and vector().
Referenced by AC(), ACPlot(), AirshipLinMod(), AirshipStabConDerivatives(), AirshipTrim(), DefaultACState(), DrawAC(), EulNED(), FTrim(), and QECI().
EnergyHeight()
function EnergyHeight (in hE, in n)
 This combines potential and kinetic energy.
 Type EnergyHeight for a demo.
Form
 [v, h] = EnergyHeight( hE )
Inputs
 hE              (1,m) Energy height (m)
Outputs
 v               (m,n) Velocity for each height (m/s)
 h               (m,n) Altitude for each height s(m)
Reference: Anderson, J. D., "Introduction to Flight, 3rd Edition," McGraw-Hill, 1989.
References Altitude(), and(), Demo(), Energy(), EnergyHeight(), length(), Plot2D(), and zeros().
Referenced by EnergyHeight().
EngineDataFromTable()
function EngineDataFromTable (in m, in h, in d)
Form
 [thrust, sFC] = EngineDataFromTable( m, h, d )
Inputs
 m           (1,:)  Mach Number
 h           (1,:)  Altitude (m)
 d           (1,1)  Data structure with thrust and sFC data
                    .m        (1,n) Mach number
                    .h        (1,m) Altitude (m)
                    .thrust   (m,n) Thrust (N)
                    .sFC      (m,n) Specific fuel consumption  (kg/N-s)
Outputs
 t           (m,n)  Thrust (N)
 sFC         (m,n)  Thrust specific fuel consumption (kg/N-s)
References Altitude(), and(), Demo(), and EngineDataFromTable().
Referenced by EngineDataFromTable().
EngineExample()
function EngineExample (in type)
Returns a data structure.
Form
 d = EngineExample( type )
Inputs
 type      (1,:) 'turbofan', 'ramjet'
Outputs
 d         (1,1)  Data structure
Reference: Mattingly, "Elements of Gas Turbine Propulsion," McGraw-Hill, 1996.
References EngineExample().
Referenced by EngineExample(), EngineTable(), MixedFlowTurbofan(), and MixedFlowTurbofanProfile().
EngineMap()
function EngineMap (in h, in m, in d)
Rows are altitude, columns Mach number. It will plot 2D meshes. If h or m are outside the range of d.h or d.m, it will give an error.
Type EngineMap for a demo using JetEngine as the source.
Form
 [iSp, fS] = EngineMap(h,m,d)
 d         = EngineMap;
Inputs
 h  (1,:)   Altitude (m)
 m  (1,:)   Mach number
 d  (.)     Data structure
             .h    (1,:)Altitude (m)
             .m    (1,:) Mach number
             .iSp  (:,:) Specific impulse (s)
             .fS   (:,:) Specific thrust (N/kg/s)
Outputs
 iSp  (:,:) Specific impulse (s)
 fS   (:,:) Specific thrust (N/kg/s)
See also
: JetEngine.
References Altitude(), DefaultDataStructure(), Demo(), DupVect(), EngineMap(), JetEngine(), length(), NewFig(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by EngineMap().
EngineTable()
function EngineTable (in type, in h, in m, in d, in p)
 Each row of output is an altitude and each column a Mach number.
Form
 [t, sFC] = EngineTable( type, h, m, d, p )
Inputs
 type        (1,:) 'turbofan' or 'ramjet'
 h           (1,:) Altitude
 m           (1,:) Mach number
 d           (1,1) Engine parameter data structure (see EngineExample.m)
 p           (1,1) Throttle settings (turbofan only)
                   .afterburner   (1,1) Afterburner on == 1
                   .throttleRatio (1,1) Throttle ratio
                   .tT4           (1,1) Combustor temperature (K)
                   .tT7           (1,1) Afterburner temperature (K)
Outputs
 t           (:,:)  Thrust (N)
 sFC         (:,:)  Thrust specific fuel consumption
See also
MixedFlowTurbofan, RamjetH2
References Altitude(), and(), Demo(), EngineExample(), EngineTable(), length(), MixedFlowTurbofan(), Ramjet(), StdAtm(), Throttle(), and zeros().
Referenced by EngineTable().
EquilibriumControls()
function EquilibriumControls (in x, in d)
For a point mass aircraft. Calls RHSPointMassAircraft via fminsearch.
Type EquilibriumControls for a demo.
Form
 d = EquilibriumControls( x, d )
Inputs
 x     (6,1) State [v;gamma;psi;xE;yN;h]
 d     (.)   Data structure see RHSPointMassAircraft
Outputs
 d     (.)   Data structure see RHSPointMassAircraft
References Altitude(), DefaultDataStructure(), Demo(), EquilibriumControls(), RHS(), and RHSPointMassAircraft().
Referenced by AircraftTrajectoryControl(), and EquilibriumControls().
EulNED()
function EulNED (in r, in qECIToB, in e)
Form
 e = EulNED( r, qECIToB, e )
Inputs
 r           (3,1) ECI Position vector
 qECIToB     (4,1) Quaternion from ECI to B
 e           (3,1) Euler angles [phi;theta;psi]
Outputs
 e           (3,1) Euler angles [phi;theta;psi]
Reference: Stevens, B.L., Lewis, F.L. , Aircraft Control and Simulation, John Wiley & Sons, 1992, p. 38.
References and(), ECIToNED(), Euler(), Q2Eul(), QMult(), QPose(), quaternion(), and vector().
Referenced by ACPlot(), and AirshipSensor().
EulRate()
function EulRate (in e, in w)
Form
 eDot = EulRate( e, w )
Inputs
 e           (3,1) Euler angles [phi;theta;psi]
 w           (3,1) Angular rates wrt NED [p;q;r]
Outputs
 eDot        (3,1) Euler rates d[phi;theta;psi]/dt
Reference: Stevens, B.L., Lewis, F.L. , Aircraft Control and Simulation, John Wiley & Sons, 1992, p. 38.
References and(), and Euler().
F100()
function F100 (in q)
 F100-PW-100(3) Continuous time model
Form
 x = F100( q )
Inputs
 q                      String describing the type of data
Outputs
 x                      The properties
References and(), and F100().
Referenced by F100().
F16()
function F16 (in q)
 If p = 'catalog' it will list a catalog of available data. Inputs are
 not case sensitive. If no output arguments are specified it will plot
 the data.
Form
 [x,xCol,xRow] = F16( q )
Inputs
 q                      String describing the type of data
Outputs
 x                      The properties
 xCol                   Column indices
 xRow                   Row indices
References Altitude(), Database(), F16(), Limit(), NewFig(), vector(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by DefaultACData(), F16(), F16Act(), and F16Actuator().
F16Act()
function F16Act (in x, in controlInput, in actuatorData)
 based int by actuatorData
Form
 [dX, control] = F16Act( x, controlInput, actuatorData )
Inputs
 x             (:)   State
 controlInput  (:)   Control commands
 actuatorData  (:)   Data
Outputs
 dX          (:)   State derivatives
 control     (:)   Controls
References F16().
F16Actuator()
function F16Actuator (in x, in control, in d)
Each has a lag.
Form
 [dX, control] = F16Actuator( x, control, d )
Inputs
 x             (4,1)       Lag state
 control       (1,1)       Control structure
                           .throttle  (1,1) Throttle command
                           .elevator  (1,1) Elevator command
                           .aileron   (1,1) Aileron command
                           .rudder    (1,1) Rudder command
 d             (1,1)       Lags
                           .throttleLag  (1,1) Throttle lag
                           .elevatorLag  (1,1) Elevator lag
                           .aileronLag   (1,1) Aileron lag
                           .rudderLag    (1,1) Rudder lag
Outputs
 dX            (4,1)       Lag state derivatives
 control       (1,1)       Control structure
                           .throttle  (1,1) Throttle command
                           .elevator  (1,1) Elevator command
                           .aileron   (1,1) Aileron command
                           .rudder    (1,1) Rudder command
References F16(), and Throttle().
F18Model()
function F18Model (in machNo, in altitude)
The mach #s range from .35 to 0.7 and altitudes from 15 kFt to 32 kFt. Loads the F18.mat file.
Form
 [g, machNo, altitude, def] = F18Model( machNo, altitude )
Inputs
 machNo         (1,1)  Mach number
 altitude       (1,1)  Altitude (kFt)
Outputs
 g              (1,1)  State space model
 machNo         (1,1)  Nearest Mach number
 altitude       (1,1)  Nearest altitude (kFt)
 def            {:,3}  State, input and output definitions
Reference: Mueller, J. B, "Applications of Linear-Parameter Varying Control Techniques to the F/A-18 Systems Research Aircraft", Master's thesis, University of Minnesota, July 2000.
References Altitude(), and and().
FAIR()
function FAIR (in t, in f, in units)
This model
 is valid between 300 deg-R and 4000 deg-R or 167 deg-K and 2222 deg-K.
 pR = exp( (phi - phi0)/R ) where
 phi0 = phi(600,0) - R(600,0)*log(pR(600,0))
 where each variable is f(t,f) and temperature is in deg-R.
Form
 [r, cP, h, pR] = FAIR( t, f, units )
Inputs
 t          (1,n)   Temperature
 f          (1,m)   Mass of fuel/mass of air
 units      (1,:)   'eng' or 'mks'
Outputs
 r         (m,1)   Gas constant
 cP        (n,m)   Specific heat at constant pressure
 h         (n,m)   Enthalpy
 R         (n,m)   Phi
References and(), Constant(), Demo(), DupVect(), FAIR(), isempty(), length(), Mesh2(), Plot2D(), Pressure(), and zeros().
Referenced by FAIR().
FlightEquilibrium()
function FlightEquilibrium (in gamma, in h, in v, in d)
 Ground effect is included and the scale factor is the square root of s.
 This uses DragCoeff for the drag coefficients. If the altitude is zero
 then the gravity force is assumed to be zero.
 Type  FlightEquilibrium for a demo
Form
 d = FlightEquilibrium( gamma, h, v, d )
Inputs
 gamma           (1,:) Flight path angle (deg)
 h               (1,:) Altitude (m)
 v               (1,:) Velocity (m/s)
 d               (1,1) Data structure
                       .mass         (1,1) Mass (kg)
                       .s            (1,1) Reference area (m^2)
                       .cLAlpha      (1,1) Lift coefficient
                       .length       (1,1) Representative length (e.g. mean chord) (m)
                       .oswaldEff    (1,1) Oswald efficiency factor (optional)
                       .aspectRatio (1,1) Aspect ratio for wing (length/mean chord)
                       .thickness    (1,1) Ratio of length to thickness
                       .m1Peak       (1,1) Peak at M = 1 an alternative to zetaTrans
Outputs
 d               (1,1) Data structure
                       .m      (1,:) Mach number
                       .rho    (1,:) Atmospheric density (kg/m^3)
                       .t      (1,:) Stagnation temperature (deg-K)
                       .q      (1,:) Dynamica pressure (N/m^2)
                       .drag   (1,:) Drag force (N)
                       .lift   (1,:) Lift force (N)
                       .thrust (1,:) Thrust force (N)
                       .cD0    (1,:) Drag coefficient
                       .kI     (1,:) Induced drag coefficient
References Altitude(), and(), Demo(), DragCoeff(), FlightEquilibrium(), length(), Plot2D(), square(), StdAtm(), and zeros().
Referenced by FlightEquilibrium().
FLToM()
function FLToM (in fL)
Flight level is a term used with aircraft. FL 150 is 15000 ft or 100 ft for FL 1.
Form
 m = FLToM( fL )
Inputs
 fL  (1,:) Flight level
Outputs
 m   (1,:) Meters
References Altitude(), FLToM(), and Plot2D().
Referenced by FLToM().
FMixedExhaustTurbofan()
function FMixedExhaustTurbofan (in tauTL, in alpha, in tauLambda, in tT4, in p, in d, in gamma6, in gamma16, in alphaP, in r16, in r6, in tol)
Only y is used by FZero.
 The other outputs are used after tauTL is found.
Form
 [y, m6, m16, piF, tauF, piCH, tauCH] = FMixedExhaustTurbofan( tauTL,
 alpha, tauLambda, tT4, p, d, gamma6, gamma16, alphaP, r16, r6, tol )
Inputs
 See JetEnginePerformance
Outputs
 See JetEnginePerformance
References FMixedExhaustTurbofan(), and JetEnginePerformance().
Referenced by FMixedExhaustTurbofan().
FormDragCoeff()
function FormDragCoeff (in d, in machNo, in p)
 Type FormDragCoeff for a demo.
Form
 cF = FormDragCoeff( d, machNo, altitude, p )
Inputs
 d            (.)   Aircraft parameters
                       .length         (1,1) Representative length (m)
                       .thickness      (1,1) Thickness ratio
                       .zetaTrans      (1,1) Transonic damping factor
                       .formDragCoeff   (1,1) Form drag merging coefficient
 machNo      (1,:)  Mach number
 p            (.)   Standard atmosphere structure
Outputs
 cF          (1,:)  Form drag coefficient
See also
: PrandtlGlauertCorrection, SkinFrictionCoeff
Reference: Miller, R. "16.751 Class Notes," MIT, 1977.
References CDSkinFriction(), Demo(), FormDragCoeff(), length(), Logistic(), Plot2D(), PrandtlGlauertCorrection(), and StdAtm().
Referenced by DragCoeff(), FormDragCoeff(), and LiftAndDrag().
FormFactorSurfaceOfRevolution()
function FormFactorSurfaceOfRevolution (in m, in f)
 The drag on a body of revolution is k cF S where S is the wetted
 area and cF is the skin friction coefficient.
 Type FormFactorSurfaceOfRevolution for demo.
Form
 k = FormFactorSurfaceOfRevolution( m, f )
Inputs
 m          (1,:)   Mach number
 f          (1,:)   Fineness ratio (l/d)
Outputs
 k          (1,:)   Form factor
Reference: http://adg.stanford.edu/aa241/drag/BODYFORMFACTOR.HTML
References and(), Demo(), FormFactorSurfaceOfRevolution(), length(), and Plot2D().
Referenced by FormFactorSurfaceOfRevolution().
FormFactorWing()
function FormFactorWing (in m, in t, in lambda)
 The drag on a lifting surface is k cF S where S is the wetted
 area and cF is the skin friction coefficient.
 Type FormFactorWing for demo.
Form
 k = FormFactorWing( m, t, lambda )
Inputs
 m          (1,:)   Mach number
 t          (1,:)   Thickness ratio t/c
 lambda     (1,1)   Sweep angle
Outputs
 k          (1,:)   Form factor
Reference: http://adg.stanford.edu/aa241/drag/lsformfactor.html
References and(), Demo(), FormFactorWing(), length(), Plot2D(), and Sweep().
Referenced by FormFactorWing().
FTrim()
function FTrim (in v, in x, in d, in g, in w, in nR)
Form
 j = FTrim( v, x, d, g, w, nR )
Inputs
 v                   Adjustable variables
 x             (:)   Aircraft state
                           r          (3,1) ECI position vector
                           q          (4,1) Quaternion from ECI to body
                           w          (3,1) Inertial body rate in body frame
                           v          (3,1) Velocity of cm wrt air
 d             (:)    Aircraft data structure
 g             (:)    Constraint structure
                        .vT    (1,1) Velocity             (required)
                        .rDot  (1,1) Climb rate           (optional)
                        .eDot  (3,1) Euler angle rate     (optional)
 w             (11,1)  Weights [vDot, wDot, rDot, eDot, engDot]
 nR             (1)   Number of rotors
Outputs
 j                    Scalar cost
References ECIToNED(), Eul2Q(), Euler(), length(), QMult(), quaternion(), and vector().
Referenced by ACTrim().
FuelFromRange()
function FuelFromRange (in mD, in lOverD, in r, in v, in sFC)
 Type FuelFromRange for a demo using the Scimitar engine at Mach 5.
Form
 mF = FuelFromRange( mD, lOverD, r, v, sFC )
Inputs
 mD          (1,1)  Dry mass (kg)
 lOverD      (1,1)  Lift to drag ratio
 r           (1,:)  Range (km)
 v           (1,1)  Velocity (m/s)
 sFC         (1,1)  Specific Fuel Consumption (kg/N-s)
Outputs
 range       (1,:)  Range (km)
Reference: http://web.mit.edu/16.unified/www/FALL/ thermodynamics/notes/node98.html
References Demo(), FuelFromRange(), LiftToDragFromMach(), Plot2D(), Scimitar(), and StdAtm().
Referenced by FuelFromRange().
GeoMagLatLon()
function GeoMagLatLon (in r)
 Type GeoMagnLatLon for a demo.
Form
 [lat, lon] = GeoMagLatLon( r )
Inputs
 r              (3,:)  Position vector
Outputs
 lat            (1,:)  Latitude (rad)
 lon            (1,:)  Longitude (rad);
Reference: http://www.cosmicrays.org/muon-cutoff-rigidity.php
References and(), CosD(), Demo(), GeoMagLatLon(), length(), SinD(), Unit(), vector(), and zeros().
Referenced by GeoMagLatLon().
GeomagneticRigidity()
function GeomagneticRigidity (in r)
 Type GeomagneticRigidity for a demo.
Form
 p = GeomagneticRigidity( r )
Inputs
 r              (3,:)  Position vectors
Outputs
 p              (1,:) Rigidity
Reference: http://www.cosmicrays.org/muon-cutoff-rigidity.php
References CosD(), Demo(), GeomagneticRigidity(), length(), SinD(), and zeros().
Referenced by GeomagneticRigidity().
Glide()
function Glide (in h, in v, in d, in cL)
 Type Glide for a demo of a Cessna 172. In this example we add a
 parasitic drag cofficient of 0.21 to account for the fuselage.
Form
 [angle, v, r] = Glide( h, v, d, cL  )
Inputs
 h               (1,:) Altitude (m)
 v               (1,:) Velocity (m/s)
 d                (.)  Data structure
                       .mass         (1,1) Mass (kg)
                       .s            (1,1) Reference area (m^2)
                       .length       (1,1) Representative length (e.g. mean chord) (m)
                       .oswaldEff    (1,1) Oswald efficiency factor (optional)
                       .aspectRatio (1,1) Aspect ratio for wing (length/mean chord)
                       .thickness    (1,1) Ratio of length to thickness
                       .m1Peak       (1,1) Peak at M = 1 an alternative to zetaTrans
 cL              (1,:) Lift coefficient (otpional)
Outputs
 angle          (1,:) Glide angle
 v              (1,:) Glide velocity
 r              (1,:) Glide range
Reference: Anderson, J. D., "Introduction to Flight 3rd Edition,", McGraw-Hill 1989, pp 294-297.
References Altitude(), and(), Constant(), Demo(), DragCoeff(), Glide(), length(), StdAtm(), and Wing().
Referenced by Glide(), and GlideSlope().
GroundEffect()
function GroundEffect (in h, in w)
Form
 f = GroundEffect( h, w )
Inputs
 h              (1,:)  Altitude
 w              (1,1)  Wing span
Outputs
 f              (1,1)  Lift scale factor
See also
: Logistic
References Altitude(), Demo(), GroundEffect(), length(), Logistic(), Plot2D(), Wing(), and zeros().
Referenced by AeroCoefficientPointMass(), and GroundEffect().
HeatingValue()
function HeatingValue (in name)
 The  higher heating value (HHV) is determined by bringing all the
 products of combustion back to the original pre-combustion temperature and
 and condensing any vapor produced. The lower heating value (LHV) is
 determined by subtracting the heat of vaporization of the water from
 the higher heating value.
 Type HeatingValue for a demo.
Form
[hhV,lhV] = HeatingValue(name)
Inputs
 name (1,:) 'hydrogen', 'methane', 'kerosene'
Outputs
 hHV (1,1) Higher heating value (J/kg)
 lHV (1,1) Higher heating value (J/kg)
Reference: Kerrebrock, J.L, "Aircraft Engines and Gas Turbines", MIT Press, 1992, pp. 36-39
References and(), Demo(), and HeatingValue().
Referenced by HeatingValue().
HorizontalWind()
function HorizontalWind (in IYD, in SEC, in ALT, in GLAT, in GLONG, in STL, in F107A, in F107, in AP, in SW)
 MSIS-86 density model and GWS4 for thermospheric winds.
 UT, Local Time, and Longitude are used independently in the
 model and are not of equal importance for every situation.
 For the most physically realistic calculation these three
 variables should be consistent.
 Since version 3.5 (ACT).
Form
 [W, WBT, WCT] = HorizontalWind( IYD, SEC, ALT, GLAT, GLONG, STL, F107A,
 F107, AP, SW )
 Additional comments:
 To turn on or off particular variations pass SW as the last
 argument where SW is a 25 element array with
 0 for off
 1 for on
 2 or main effects off but cross terms on
 The variations:
 1  - F10.7 EFFECT ON MEAN
 2  - TIME INDEPENDENT
 3  - SYMMETRICAL ANNUAL
 4  - SYMMETRICAL SEMIANNUAL
 5  - ASYMMETRICAL ANNUAL
 6  - ASYMMETRICAL SEMIANNUAL
 7  - DIURNAL
 8  - SEMIDIURNAL
 9  - DAILY AP
 10 - ALL UT/LONG EFFECTS
 11 - LONGITUDINAL
 12 - UT AND MIXED UT/LONG
 13 - MIXED AP/UT/LONG
 14 - TERDIURNAL
 16 - ALL WINDF VAR
 17 - ALL WZL VAR
 18 - ALL UN1 VAR
 19 - ALL WDZL VAR
 24 - ALL B FIELDS (DIV)
 25 - ALL C FIELDS (CURL)
 For example, to get zonal averages (no diurnal or
 longitudinal variations) set SW(7), SW(8), SW(14),
 and SW(10) equal to 0.  To just remove tidal variations
 set SW(7), SW(8), and SW(14) equal to 0.
 If no arguments are entered it will run a demo.
Inputs
 IYD   (1,1) YEAR AND DAY AS YYYYDDD
 SEC   (1,1) UT(SEC)  (Not important in lower atmosphere)
 ALT   (1,1) ALTITUDE(KM)
 GLAT  (1,1) GEODETIC LATITUDE(DEG)
 GLONG (1,1) GEODETIC LONGITUDE(DEG)
 STL   (1,1) LOCAL APPARENT SOLAR TIME(HRS)
 F107A (1,1) 3 MONTH AVERAGE OF F10.7 FLUX (Use 150 in lower atmos.)
 F107  (1,1) DAILY F10.7 FLUX FOR PREVIOUS DAY ( " )
 AP    (1,2) [MAGNETIC INDEX(DAILY) (use 4 in lower atmos.),
              CURRENT 3HR ap INDEX (used only when SW(9)=-1.)]
 SW    (1,25) Switches
Outputs
 W     (1,2) [MERIDIONAL (m/sec + Northward) ZONAL (m/sec + Eastward)]
 WBT   (1,2)
 WCT   (1,2)
Reference: A. E. HEDIN (1/25/93) (4/9/93)
 Copyright (c) 2003 Princeton Satellite Systems, Inc.
 All Rights Reserved.
References and(), get(), HorizontalWind(), and set().
Referenced by HorizontalWind(), WindFunction(), WindLatLon(), WindModel(), and WindTrendsDemo().
HUD()
function HUD (in mode, in g, in x, in h, in c)
 If c is entered it will animate the controls when the mode is 'run',
 otherwise it will output the control values in h when the mode
 is 'run'. Can have helicopter or fixed-wing type controls.
Form
 h = HUD( mode, g, x, h, c )
Inputs
 mode        (1,:) 'run' or 'init'
 g                 .atmData        Atmospheric data
                   .atmUnits       Units
                   .type           'helicopter' or 'fixed wing'
 x                 State vector of type ACState or
                   x.v (3,1) velocity vector
                   x.h (1,1) altitude
                   x.e (3,1) Euler angles
 h           (:,:) Structure containing figure handles and control settings
                    .control
                     For a fixed wing this is
                     .rudder
                     .aileron
                     .elevator
                     .throttle
                     For a helicopter this is
                     .rudder
                     .lateralCyclic
                     .longitudinalCyclic
                     .collective
                     .throttle
 c           (:)   Initial control settings inputs and button definitions
                   For a fixed wing
                   .control
                   .rudderMax             (1,1) Max rudder
                   .aileronMax            (1,1) Aileron max
                   .elevatorMax           (1,1) Elevator max
                   For a helicopter
                   .control
                   .rudderMax             (1,1) Max rudder
                   .lateralCyclicMax      (1,1) Lateral Cyclic max
                   .longitudinalCyclicMax (1,1) Longitudinal Cyclic max
                   .collectiveMax         (1,1) Collective max
Outputs
 h           (:)    Figure handles and outputs
                    .control
References and(), Euler(), get(), HUD(), set(), square(), and vector().
Referenced by HUD(), and HUDCntrl().
HUDCntrl()
function HUDCntrl (in action)
Define a data structure
 global hUDOutput
 hUDOutput = struct('pushbutton1',0,'pushbutton2',0,'checkbox1',0,...
 'checkbox2',0,'checkbox3',0)
 At the end of your simulation loop type
 HUDCntrl;
 end;
 This routine is called by a callback routine in HUD.m. You do not
 normally call it yourself.
Form
 HUDCntrl( action )
Inputs
 action    (1,:) Action to take
Outputs
 None
References HUD(), and HUDCntrl().
Referenced by HUDCntrl().
IdealJetEngineEfficiency()
function IdealJetEngineEfficiency (in m0, in t0, in tT4, in piC, in gamma, in piF, in alpha)
m0, piC or piF can be vectors. Alpha may be zero, i.e pure turbojets can be analyzed. Note that heating value is not an input as it does not impact efficiency. Note that any units for temperature can be used as only their ratio, i.e. tT4/t0, is used internally.
Type JetEngineEfficiency for a demo.
Form
 [etaO, etaT, etaP] = IdealJetEngineEfficiency( m0, t0, tT4, piC, gamma, piF, alpha )
Inputs
 m0         (1,:)   Mach number
 t0         (1,1)   Inlet temperature
 tT4        (1,1)   Combustor temperature
 piC        (1,:)   Compressor pressure ratio
 gamma      (1,1)   Ratio of specific heat
 piF        (1,:)   Fan pressure ratio
 alpha      (1,1)   Bypass ratio
Outputs
 etaO       (1,:)   Total efficiency
 etaT       (1,:)   Thermal efficiency
 etaP       (1,:)   Propulsive efficiency
References Demo(), IdealJetEngineEfficiency(), isempty(), JetEngineEfficiency(), length(), and Plot2D().
Referenced by IdealJetEngineEfficiency().
InducedDragCoeff()
function InducedDragCoeff (in e, in aR, in m)
 At supersonic speeds provides combined vortex and wave drag.
 Drag is cD0 + k*cL^2.
 This function includes a linear term in the square root for the
 supersonic mach numbers that allows it to match the
 subsonic induced drag at M = 1. Otherwise it would produce a jump in
 the drag at M = 1.
 Type InducedDragCoeff for a demo
Form
 k = InducedDragCoeff( e, aR, m )
Inputs
 e              (1,1) Oswald efficiency factor (0 to 1)
 aR             (1,1) Wing aspect ratio
 m              (1,:) Mach number
Outputs
 k              (1,:) Induced drag coefficient
Reference: http://adg.stanford.edu/aa241/drag/LiftWaveDrag.html
References and(), Demo(), InducedDragCoeff(), length(), Plot2D(), square(), and Wing().
Referenced by AeroForceAndTorqueCombined(), AircraftThrustFromFlight(), CDCLSubsonic(), DragCoeff(), InducedDragCoeff(), and LiftAndDrag().
InletAndNozzle()
function InletAndNozzle (in l, in w, in h, in angle)
The inlet is +x.
Type InletAndNozzle for a demo.
Form
 [v, f] = InletAndNozzle( l, w, h, angle )
Inputs
 l     (1,1)  x length
 w     (1,1)  y width
 h     (1,1)  z height
 angle  (1,1)  Inlet ramp angle
Outputs
 v      (:,3) Vertices
 f      (:,3) Faces
References and(), Demo(), DrawVertices(), InletAndNozzle(), and length().
Referenced by InletAndNozzle().
InletLoss()
function InletLoss (in m)
Computes p02/p01 due to inlet shock losses. Uses an empirical relationship. The ratio will be 1 for Mach numbers between 0 and 1. Above Mach 7.812 the ratio is zero.
Type InletLoss for a demo.
Form
 pR = InletLoss( m )
Inputs
 m   (1,:)   Mach number
Outputs
 pR (1,:)    p02/p01
Reference: Benson, T. J., "An Interactive Educational Tool for Turbojet Engines," May 1995, NASA Lewis Research Center
References and(), Demo(), InletLoss(), length(), and Plot2D().
Referenced by InletLoss().
JacobVB()
function JacobVB (in v)
Form
 m = JacobVB( v )
Inputs
 v           (3,1) Velocity
Outputs
 m           (3,3) Jacobian matrix
                   [Vx/alpha Vx/beta Vx/vT]
                   [Vy/alpha Vy/beta Vy/vT]
                   [Vz/alpha Vz/beta Vz/vT]
Reference: Stevens, B.L., Lewis, F.L. , Aircraft Control and Simulation, John Wiley & Sons, 1992, p. 63.
References AlphBeta(), and(), Jacobian(), and Mag().
JetEngine()
function JetEngine (in m, in d, in q)
Specific Fuel Consumption is constant in this model. Thrust varies with altitude and Mach number.
Type JetEngine for a demo.
Form
 [t, i] = JetEngine( m, d, q )
Inputs
 m  (n,1)   Mach number
 d  (1,1)   Data structure for engine
           .tStatic   (1,1) Static thrust
           .kM        (1,1) Mach number coefficient, thrust
           .kI        (1,1) Mach number coefficient, impulse
           .iSp0      (1,1) Specific Impulse at Mach = 0
 q (1,1)   Standard atmosphere
Outputs
 t   (1,1)  Thrust
 i      (1,1)  Specific Impulse
References Altitude(), and(), DefaultDataStructure(), Demo(), JetEngine(), Plot2D(), and StdAtm().
Referenced by EngineMap(), JetEngine(), and TurboRamjet().
JetEngineAnalysis()
function JetEngineAnalysis (in p, in d)
You can vary up to two of the parameters in p. You can get demos by typing
 JetEngineAnalysis( 'Ramjet' ), etc.
If you enter JetEngineAnalysis('Ramjet', 1) it will echo the d and p structures.
Engine parameters are in d and given below. You only need to enter parameters that are relevant to your engine. For example, ramjets don't require fan and compressor parameters.
Turbojets and turbofans may have afterburners.
This function is used to design engines. Once you have a design (possibly from an external source) use JetEnginePerformance to study it at different throttle settings.
Supported engines are:
 'Ramjet'
 'Turbojet'
 'Dual Exhaust Turbofan',
 'Mixed Flow Turbofan'
 'Turboprop'
Form
 [g, d, p, def] = = JetEngineAnalysis( p, d )
Inputs
 p         (1,1) Performance parameters
                  See def or GasTurbineDefinitions.m
 d         (1,1) Engine data structure
                  See def or GasTurbineDefinitions.m
 echo      (1,1) Just return outputs
Outputs
 g         (1,1) Output data structure
                  .fO            (n,m) Fuel/air ratio
                  .etaO          (n,m) Overall efficiency
                  .etaP          (n,m) Propulsive efficiency
                  .etaT          (n,m) Thermal efficiency
                  .fOverMDotA    (n,m) Specific force
                  .s             (n,m) Specific fuel consumption
                  .alpha         (n,m) Bypass ratio
                  .mDotOverA2    (n,m) Mass flow per unit area at the diffuser exit
                  .forceOverA2   (n,m) Force per unit area at the diffuser exit
                  .rhoU          (n,m) External airflow per unit area
 d         (1,1) Input data structure
 p         (1,1) Performance parameters
 def       (1,1) Definition data structure
                 .p    p parameters
                 .d    d parameters
Reference: Mattingly, "Elements of Gas Turbine Propulsion," McGraw-Hill, 1996.
References and(), get(), isempty(), JetEngineAnalysis(), JetEngineDefinitions(), JetEnginePerformance(), Ramjet(), Turbofan(), and Turbojet().
Referenced by JetEngineAnalysis().
JetEngineDefinitions()
function JetEngineDefinitions (in type, in engine)
If no output arguments are specified it will
 produce a tab delimited table. If no input and no output arguments
 are given it will output a list of all inputs for all of the
 available engines. type is the analysis type.
Form
 def = JetEngineDefinitions( type, engine )
Inputs
 typeIn     (1,:)   'performance' or 'analysis'
 engineIn   (1,:)   'Ramjet', 'Turbojet', 'Single Spool Turbojet',
                    'Dual Exhaust Turbofan', 'Mixed Flow Turbofan',
                    'Turboprop'
Outputs
 def       (:)       Definition data structure
                     .type (1,:)   Type
                     .engine (1,:) Engine
                     .p            p parameters {name description units mks units english}
                     .d            d parameters {name description units mks units english}
References and().
Referenced by JetEngineAnalysis(), JetEnginePerformance(), and MixedFlowTurbofan().
JetEngineEfficiency()
function JetEngineEfficiency (in f, in hPR, in v0, in fOverMDotA, in v9, in units, in v19, in alpha)
Form
 [etaO, etaT, etaP] = JetEngineEfficiency( f, hPR, v0, fOverMDotA, v9, units, v19, alpha )
Inputs
 f          (1,1)   Fuel/air ratio
 hPR        (1,1)   Fuel heating value
 v0         (1,:)   Velocity
 fOverMDotA (1,:)   Specific thrust
 v9         (1,:)   Exit velocity
 units      (1,:)   'eng' or 'mks'
 v19        (1,:)   Exit velocity second exhaust
 alpha      (1,1)   Bypass ratio
Outputs
 etaO       (1,:)   Total efficiency
 etaT       (1,:)   Thermal efficiency
 etaP       (1,:)   Propulsive efficiency
References JetEngineEfficiency(), length(), Plot2D(), and StdAtm().
Referenced by IdealJetEngineEfficiency(), and JetEngineEfficiency().
JetEnginePerformance()
function JetEnginePerformance (in p, in d)
You can vary up to two of the parameters in p.
You can get demos by typing
JetEnginePerformance('Ramjet'), etc.
References and(), get(), isempty(), JetEngineDefinitions(), JetEnginePerformance(), Ramjet(), Turbofan(), and Turbojet().
Referenced by FMixedExhaustTurbofan(), JetEngineAnalysis(), and JetEnginePerformance().
Knudsen()
function Knudsen (in rho, in T, in mu, in m, in l)
Type Knudsen for a demo in a nitrogen atmosphere.
Form
 kN = Knudsen( rho, T, mu, m, l )
Inputs
 rho   (1,:)      Density (kg/m^3)
 T     (1,:)   Temperature (deg-K)
 mu    (1,:)   Viscosity (deg-K)
 m     (1,1)   Molecular weight
 l     (1,1)   Characteristic length
Outputs
 kN    (1,:)    Knudsen number
References AbsoluteViscosity(), Altitude(), AtmDens2(), AtmTemp(), Demo(), Knudsen(), length(), Plot2D(), and Step().
Referenced by Knudsen().
LandingDistance()
function LandingDistance (in m, in vL, in t, in cL, in cD0, in muR, in hB, in d, in rho)
 Set cL to zero eliminate lift. muR is generally 0.4 for braking.
 t is for thrust reversing.
 Type LandingDistance for a demo.
Form
 sL = LandingDistance( m, vL, t, cL, cD0, muR, hB, d, rho )
Inputs
 m              (1,1)  Mass (kg)
 vL             (1,1)  Landing velocity (m/s)
 cL             (1,1)  Lift coefficient
 cD0            (1,1)  Drag coefficient
 muR            (1,1)  Rolling resistance
 hB             (1,1)  Altitude/wing span
 d               (.)   Drag data structure
 rho            (1,1)  Atmospheric density (kg/m^3)
Outputs
 sL             (1,:)  Landing distance (m)
Reference: Anderson, J. D., "Introduction to Flight 3rd Edition,", McGraw-Hill 1989, pp 324-326.
References Altitude(), Demo(), LandingDistance(), and StallVelocity().
Referenced by LandingDistance().
LDDeltaWing()
function LDDeltaWing (in v, in h, in d, in alpha)
 Type LDDeltaWing for a demo of the Space Shuttle wing.
Form
 [cD, cL, kI, y]  = LDDeltaWing( v, h, d )
Inputs
 v       (1,:)  Velocity (m/s)
 h       (1,:)  Altitude (m)
 d       (1,1)  Aircraft parameters
                .length      (1,:) Representative length (e.g. mean chord) (m)
                .oswaldEff   (1,1) Oswald efficiency factor (0.9 to 1.0)
                .aspectRatio (1,1) Aspect ratio for wing (length/mean chord)
                .thickness   (1,1) Ratio of length to thickness
                .s           (1,1) Area
                .zetaTrans   (1,1) Damping for transonic
                .sweep       (1,:) Sweep angles (deg)
                .span        (1,:) Span of each section
 alpha   (1,1)  Angle of attack (rad)
Outputs
 cD      (1,:)  Drag coefficient
 cL      (1,:)  Lift coefficient
 kI      (1,:)  Induced drag coefficient
 y       (1,:)  Lift and drag data structure
See also
LiftAndDrag.
References Altitude(), and(), Demo(), LDDeltaWing(), length(), LiftAndDrag(), Plot2D(), StdAtm(), and Sweep().
Referenced by AircraftEquilibrium(), and LDDeltaWing().
LiftAndDrag()
function LiftAndDrag (in d, in altitude, in velocity, in cP, in alpha)
 You will have to call this routine for the wing, fuselage and tail
 separately using different characteristic lengths. The wing and tail use
 the mean chord and the fuselage uses the length.
 Altitude and velocity must be the same length.
 zetaTrans is a "fudge" factor to prevent the form drag from becoming
 infinite at M = 1. m0 is another "fudge" factor that prevents the
 skin friction from going to infinity at Mach = 0. It fits a linear
 function to the skin friction curve whose value and slope match the
 curve at that Mach number.
 If wing area is not entered it computes lift and drag per unit area.
 Type LiftAndDrag for a demo.
Form
 y = LiftAndDrag( d, altitude, velocity, cP, alpha )
Inputs
 d              (1,1)  Aircraft parameters
                       .length      (1,1) Representative length (e.g. mean chord) (m)
                       .oswaldEff   (1,1) Oswald efficiency factor (0.9 to 1.0)
                       .aspectRatio (1,1) Aspect ratio for wing (length/mean chord)
                       .thickness   (1,1) Ratio of length to thickness
                       .s           (1,1) Area (m^2) optional
                       .zetaTrans   (1,1) Damping for transonic
                       .sweep       (1,1) Sweep angle
                       .a0          (1,1) Lift curve slope
                       .alpha0      (1,1) Zero lift angle of attack
                       .m0          (1,1) Mach number for linear skin
                                          friction coefficient
 altitude       (1,n)  Altitude (m)
 velocity       (1,n)  Velocity at altitude (m/sec)
 cP             (1,1)  Parasitic drag coefficient
 alpha          (1,n:) Angle of attack (rad)
Outputs
 y              (1,1)  Output data structure
                       .reynoldsNumber (1,n) Reynold's number
                       .skinFriction   (1,n) Skin friction
                       .formDrag       (1,n) Form drag
                       .kInduced       (1,n) Drag induced due to lift
                       .parasiticDrag  (1,n) Parasitic drag
                       .cD0            (1,n) Zero lift drag coefficient
                       .cD             (1,n) Drag coefficient
                       .cLOpt          (1,n) Optimal lift coefficient.
                       .cL             (1,n) Lift coefficient.
                       .lift           (1,n) Lift
                       .drag           (1,n) Drag
                       .loading        (1,n) Wing loading
See also
InducedDragCoeff, SkinFrictionCoeff and FormDragCoeff,
LiftCoeff, DragCoeff
Reference: Miller, R. "16.751 Class Notes," MIT, 1977.
References AircraftDragDataStructures(), Altitude(), and(), CosD(), DragCoeff(), FormDragCoeff(), InducedDragCoeff(), isempty(), length(), LiftAndDrag(), LiftCoeff(), StdAtm(), Sweep(), Wing(), and zeros().
Referenced by AircraftDragDataStructures(), AircraftEquilibrium(), LDDeltaWing(), and LiftAndDrag().
LiftAndDragJonesSearsHaack()
function LiftAndDragJonesSearsHaack (in m, in d)
Jones, Sears, and Haack model.
This is for the minimum drag of a supersonic body with fixed lift, span, length, and volume. Either d.h or d.p is needed.
if cL is not entered it will compute the optimal cL.
Volume and surface area includes fuselage and wings.
Type LiftAndDragJonesHaackSears for a demo.
 Forms:
 d = LiftAndDragJonesSearsHaack;  % default data structure
 [lift, dragTotal, qCL, cD] = LiftAndDragJonesSearsHaack( m, d )
Inputs
 m           (1,1) Mach number
 d            (.)  Data structure
                   .l      (1,1) Aircraft length (m)
                   .h      (1,:) Altitude (m)
                   .p       (.)  Standard Atmosphere struct
                   .b      (1,1) Span (m)
                   .s      (1,1) Surface area (m^2)
                   .v      (1,1) Volume (m^3)
                   .sL     (1,1) Lifting surface  (m^2)
                   .cL     (1,1) Lift coefficient
                   .alpha  (1,1) Angle of attack
Outputs
 lift        (1,1) Lift (N)
 dragTotal   (1,1) Drag (N)
 qCL         (1,1) Dynamic pressure times lift coefficient (N/m^2)
 cD          (1,1) Drag coefficient
Reference: "Applied Aerodynamics: A Digital Textbook", Version 5.0, January 2007, Desktop Aeronautics, Inc.
See also
: ConcordeLD, SurfaceAreaEllipsoidRevolution, StdAtm,
 CDSkinFriction
References Altitude(), and(), CDSkinFriction(), ConcordeLD(), Demo(), length(), LiftAndDragJonesSearsHaack(), Plot2D(), StdAtm(), SurfaceAreaEllipsoidRevolution(), Wing(), and zeros().
Referenced by DragLoss(), LiftAndDragJonesSearsHaack(), RHSLaunchVehicle2D(), RocketDrag(), and TSTODragData().
LiftCoeff()
function LiftCoeff (in alpha, in cLAlpha, in cL0, in m, in delta)
 The zero mach lift coefficient is
 cL = cL0 + cLAlpha*alpha;
 Also applies the Prandtl Glauert compressibility correction. Does not
 account for stall.
Form
 cL = LiftCoeff( alpha, cLAlpha, cL0, m, delta )
Inputs
 alpha           (1,:)  Angle of attack
 cLAlpha         (1,1)  Coefficient dcL/dAlpha
 cL0             (1,1)  Lift at zero angle of attack
 m               (1,:)  Mach number
 delta           (1,1)  If entered use the transonic damping
Outputs
 cL              (1,:) Lift coefficient
See also
PrandtlGlauertCorrection
References Demo(), length(), LiftCoeff(), PrandtlGlauertCorrection(), and zeros().
Referenced by LiftAndDrag(), and LiftCoeff().
LiftCoeffStall()
function LiftCoeffStall (in alpha, in d)
Type LiftCoeffStall for a demo.
Form
 cL = LiftCoeffStall( alpha, d )
Inputs
 alpha   (1,:)   Angle of attack (rad)
 d          (.)     Data structure
                 .alpha  (1,:) Angle of attack (rad)
                 .cL     (1,:)  Lift coefficient
Outputs
 cL     (1,:)   Lift coefficient
References DefaultDataStructure(), Demo(), isempty(), length(), LiftCoeffStall(), Plot2D(), and zeros().
Referenced by LiftCoeffStall(), and RHSFlatEarthSet().
LiftToDragFromMach()
function LiftToDragFromMach (in m)
 This is an empirical relationship developed by Dietrich Kuchemann for
 predicting the L/D ratio at high Mach (M>1).
 Type LiftToDragFromMach for a demo.
Form
 lOverD = LiftToDragFromMach( m )
Inputs
 m              (1,:)  Mach number
Outputs
 lOverD         (1,:)  L/D ratio
Reference: John D. Anderson, Jr. "Introduction to Flight", 3rd Edition, McGraw-Hill,
Ch. 10, Hypersonic Vehicles, Eq. 10.15, p. 552
References Demo(), LiftToDragFromMach(), and Plot2D().
Referenced by FuelFromRange(), and LiftToDragFromMach().
LocalAngleOfAttack()
function LocalAngleOfAttack (in alpha, in aB, in delta)
 The surface rotates by an angle delta about a body axis aB. The
 freestream velocity direction in the body frame is assumed to be:
 vDirB = [-cos(alpha);0;-sin(alpha)]
Form
 alphaE = LocalAngleOfAttack( alpha, aB, delta )
Inputs
 alpha     (1,1)   Angle of attack (rad)
 aB        (3,1)   Unit axis vector of control surface for rotation
 delta     (1,1)   Angle of rotation about axis (rad)
Outputs
 alphaE    (1,1)   Effective or local angle of attack at the plate.
References abs(), AU2Q(), Cross(), Dot(), LocalAngleOfAttack(), Normal(), QTForm(), Unit(), and vector().
Referenced by LocalAngleOfAttack().
LowSpeedAeroData()
function LowSpeedAeroData (in fileName, in a, in p, in d, in q, in alpha0)
Generates a file low speed aero data. Each surface has the following data:
axis vector (3x1) position vector of axis (3x1)
The axis vector will be unitized. There is one set of the above per component.
Type LowSpeedAeroData for a demo that will produce the file 'DemoLowSpeedAeroData'
Form
 LowSpeedAeroData( fileName, a, p, d, alpha0 )
Inputs
 fileName       (1,:) Filename
 a              (3,:) Axes
 p              (3,:) Points of axes
 d              (1,:) Data structures with drag data
 q              (4,:) Quaternion from body to surface axes
 alpha0         (1,:) Zero lift angle
Outputs
 None
References length(), LowSpeedAeroData(), set(), Unit(), and vector().
Referenced by LowSpeedAeroData().
MachAcrossShock()
function MachAcrossShock (in m1, in gamma, in theta)
It automatically limits theta to angles for which m1*sin(theta) >= 1. At the minimum angle there is no drop in Mach across the shock. The maximum value for theta is pi/2, a normal shock.
Type MachAcrossShock for a demo showing oblique shock angles for a range of shock angles.
Form
 [m2, theta] = MachAcrossShock( m1, gamma, theta )
Inputs
 m1    (1,1)  Mach number before shock
 gamma  (1,1)  Fluid ratio of specific heats
 theta  (1,:)  Oblique shock angle (rad)
Outputs
 m2    (1,1)  Mach number after shock
 theta  (1,:)  Limited oblique shock angle (rad)
Reference: Ames Research Staff, "Equations, Tables and Charts for Compressible Flow," Report 1135, equation 131.
References Demo(), DispWithTitle(), isempty(), length(), MachAcrossShock(), Plot2D(), and StreamlineShockAngle().
Referenced by AerodynamicShock(), and MachAcrossShock().
MachFromMassFlowParameter()
function MachFromMassFlowParameter (in gamma, in r, in mFP, in m0, in units)
You need to enter a guess for the Mach number since any mass flow parameter has two possible Mach numbers. The initial guess must be on the same side of 1 as the expected Mach Number.
This routine uses a Newton-Raphson method to find the Mach number.
Form
 machNo = MachFromMassFlowParameter( gamma, r, mFP, m0, units )
Inputs
 gamma      (1,1)   Rate of specific heats
 r          (1,1)   Gas constant
 mFP        (1,:)   Mass flow parameter
 m0         (1,:)   Initial guess
 units      (1,:)   'eng' or 'mks'
Outputs
 machNo     (1,:)   Mach number
Reference: Mattingly, "Elements of Gas Turbine Propulsion," McGraw-Hill, 1996, p. 124.
References abs(), Demo(), length(), MachFromMassFlowParameter(), MassFlowParameterR(), Parameter(), Plot2D(), and zeros().
Referenced by CentrifugalCompressor(), and MachFromMassFlowParameter().
MachFromPR()
function MachFromPR (in pR, in gamma)
Form
 m = MachFromPR( pR, gamma )
Inputs
 pR         (1,n)   Pressure ratio
 gamma      (1,1)   Gamma
Outputs
 m          (1,n)   Mach number
References and(), Gamma(), MachFromPR(), Plot2D(), and Pressure().
Referenced by MachFromPR().
MachFromPressureRatio()
function MachFromPressureRatio (in gamma, in pR, in tol)
Form
 m = MachFromPressureRatio( gamma, pR, tol )
Inputs
 gamma          (1,1)       Ratio of specific heats
 pR             (1,:)       Pressure ratio
 tol            (1,1)       tolerance
Outputs
 m              (1,:)       Mach number
References abs(), Demo(), isempty(), MachFromPressureRatio(), Plot2D(), and Pressure().
Referenced by MachFromPressureRatio().
MachSwept()
function MachSwept (in m, in sweep)
 Type MachSwept for a demo.
Form
 mEff = MachSwept( m, sweep )
Inputs
 m        (1,:)  Mach number
 sweep     (1,:)  Sweep (deg)
Outputs
 mEff     (1,:)  Effective Mach number
Reference: Anderson, J. D., "Introduction to Flight, 3rd Edition", McGraw-Hill, 1989, pp. 227-228
References CosD(), Demo(), MachSwept(), Plot2D(), Sweep(), and Wing().
Referenced by MachSwept().
MassCrewAndPassenger()
function MassCrewAndPassenger (in nFlightDeck, in nPassenger, in longRange)
 Includes all associated mass that is dependent on the number of
 passengers. It estimates the number of flight attendants.
 Type MassCrewAndPassenger for a demo.
Form
 m = MassCrewAndPassenger( nFlightDeck, nPassenger, longRange )
Inputs
 nFlightDeck (1,1) Number of flight deck members
 nPassengers (1,1) Number of passengers
 longRange   (1,1) Any entry will give numbers for long range aircraft
Outputs
 m           (1,1) Mass (kg)
Reference: http://adg.stanford.edu/aa241/structures/ componentweight.html
References and(), Demo(), and MassCrewAndPassenger().
Referenced by MassCrewAndPassenger().
MassFlow()
function MassFlow (in m0, in p0, in t0, in piDMax, in eD, in gamma, in r, in m2, in units)
The code
 is based on a constant Mach number at station 2 which is the exit
 of the diffuser and inlet to the fan or compressor.
Form
 mDot = MassFlow( m0, p0, t0, piDMax, eD, gamma, r, m2, units )
Inputs
 m0         (1,:)   Inlet mach number
 p0         (1,1)   Inlet pressure
 t0         (1,1)   Inlet temperature
 piDMax     (1,1)   Maximum diffuser pressure ratio
 eD         (1,1)   Diffuser efficiency
 gamma      (1,1)   Rate of specific heats, cP/cV
 r          (1,1)   Gas constant
 m2         (1,1)   Mach number at exit of diffuser
 units      (1,:)   'eng' or 'mks'
Outputs
 mDot       (1,:)   Mass flow
References and(), AOverAStar(), AtmGamma(), Demo(), isempty(), MassFlow(), MassFlowParameterR(), RamRecovery(), and StdAtm().
Referenced by MassFlow().
MassFlowParameter()
function MassFlowParameter (in gamma, in cP, in machNo, in units)
Form
 mFP = MassFlowParameter( gamma, R, machNo, units )
Inputs
 gamma      (1,1)   Rate of specific heats
 cP         (1,1)   Specific heat
 machNo     (1,:)   Mach number
 units      (1,:)   'eng' or 'mks'
Outputs
 mFP        (1,:)   Mass flow parameter
Reference: Mattingly, "Elements of Gas Turbine Propulsion," McGraw-Hill, 1996, p. 124.
References MassFlowParameter(), Parameter(), and Plot2D().
Referenced by CentrifugalCompressor(), MassFlowParameter(), MassFlowParameterR(), and MassInflowSupersonic().
MassFlowParameterR()
function MassFlowParameterR (in gamma, in r, in machNo, in units)
 An alternative function is MassFlowParameter which takes cP
 as an input.
Form
 mFP = MassFlowParameterR( gamma, r, machNo, units )
Inputs
 gamma      (1,1)   Rate of specific heats
 r          (1,1)   Gas constant
 machNo     (1,:)   Mach number
 units      (1,:)   'eng' or 'mks'
Outputs
 mFP        (1,:)   Mass flow parameter
Reference: Mattingly, "Elements of Gas Turbine Propulsion," McGraw-Hill, 1996, p. 124.
References and(), MassFlowParameter(), MassFlowParameterR(), Parameter(), and Plot2D().
Referenced by MachFromMassFlowParameter(), MassFlow(), and MassFlowParameterR().
MassInflowSupersonic()
function MassInflowSupersonic (in gamma, in machNo2, in piD, in altitude, in machNo)
Form
 mA = MassInflowSupersonic( gamma, machNo2, piD, p0, t0, tauR )
Inputs
 gamma      (1,1)   Ratio of specific heats
 machNo2    (1,1)   Mach number at station 2
 piD        (1,1)   Diffuser pressure ratio (nearly 1)
 altitude   (1,1)   Altitude (m)
 cP         (1,1)   Specific heat constant pressure
 machNo     (1,:)   Mach number
 units      (1,:)   'eng' or 'mks'
Outputs
 mA         (1,:)   mdot/a
References Altitude(), AOverAStar(), Demo(), MassFlowParameter(), MassInflowSupersonic(), Plot2D(), and StdAtm().
Referenced by MassInflowSupersonic().
MaxShockIncidenceAngle()
function MaxShockIncidenceAngle (in m1, in gamma)
Also computes beta at theta max.
Type MaxShockIncidenceAngle for a demo.
Form
 [theta, beta] = MaxShockIncidenceAngle( m1, gamma )
Inputs
 m1    (1,:)   Mach number after shock
 gamma  (1,1)   Fluid ratio of specific heats
Outputs
 theta  (1,:)   Maximum incidence angle (rad)
 beta   (1,:)   Shock wave angle (rad)
Reference: Ames Research Staff, "Equations, Tables and Charts for Compressible Flow," Report 1135.
References Demo(), length(), MaxShockIncidenceAngle(), Plot2D(), RHS(), and zeros().
Referenced by MaxShockIncidenceAngle(), and ObliqueShockAngle().
MergeNOAAWindData()
function MergeNOAAWindData (in data1, in data2)
There are two possibilities:
1) Some cities in common, but one is low alt., the other high alt. Here, we append the alt / wind data for each common city. 2) No cities in common. Just append like this: data = [data1, data2]
Form
 data = MergeNOAAWindData( data1, data2 )
Inputs
 data1           (.)   Data set 1 from NOAAWindData
 data2           (.)   Data set 2 from NOAAWindData
Outputs
 data            (.)   Merged data set
References get(), length(), NOAAWindData(), and set().
MissileMassEstimation()
function MissileMassEstimation (in d, in tol, in fileName)
This is an alternative to AircraftGroupMassStatement that uses a different weight model. The model is based on R. Miller's model from MIT course 16.751. If you enter fileName it will create a file with a latex table. It is similar to HSVMassEstimation except that it uses range as an input and does not include landing gear.
Not all values of parameters will produce a feasible design. If the weight goes to infinity you will need to adjust some of your parameters. See the demo for a working set of inputs.
Form
 d       = MissileMassEstimation; % Return default data structure
 [g, h]  = MissileMassEstimation( d, tol, fileName )
Inputs
 d           (.)    Data structure
                     .massPayload            (1,1) Mass of payload
                     .dFuselage              (1,1) Fuselage diameter (m)
                     .lFuselage              (1,1) Fuselage length (m)
                     .wingLoading            (1,1) Wing loading (kg/m^2)
                     .structuralLF           (1,1) Structural load factor
                     .thicknessRatio         (1,1) Thickness Ratio
                     .sweepAngle             (1,1) Sweep ratio
                     .tipRootChordRatio      (1,1) Tip Chord/Root Chord
                     .aspectRatio            (1,1) Aspect ratio
                     .fuelStructuralFraction    (1,1) Fuel to gross weight ratio
                     .massEngine             (1,1) Engine mass
                     .fSMaterial             (1,1) Factor to adjust for materials
                     .range                  (1,1) Range (km)
                     .vCruise                (1,1) Cruise velocity (m/s)
 tol         (1,1) Tolerance on computation
 fileName    (1,:) Filename for the latex table (for one design)
Outputs
 g           (.)   Data structure
                     .gM             (1,1)  Gross mass
                     .wing           (1,1)  Wing mass
                     .fuselageWT     (1,1)  Fuselage mass
                     .engineWT       (1,1)  Engine mass
                     .fuelWT         (1,1)  Fuel mass
                     .fixedEWT          (1,1)  Fixed equipment mass
                     .empWT          (!,1)  Empanage mass
                     .landingGear    (1,1)  Landing gear mass
                     .payload        (1,1)  Payload mass
                     .misc           (1,1)  Everything else
 h            (.)  Data structure
                     .wingArea       (1,1)  Wing area
                     .mF             (1,1)  Mass fueld
References AircraftGroupMassStatement(), Fuselage(), and Wing().
MixedFlowTurbofan()
function MixedFlowTurbofan (in action, in varargin)
A mixed flow turbofan is one in which the fan and core streams mix in the same nozzle. This model supports afterburning. The outputs are the same as RamjetH2. Only mks units are supported in this function.
Type MixedFlowTurbofan for a demo.
This function employs a reference model and its outputs are deviations from the reference model. Type
 ref = MixedFlowTurbofan
to get the reference data structure along with the demo.
Note that only ref.h0 need be entered for the atmospheric parameters.
The following are computed from the Standard Atmosphere and AtmGamma as follows.
 q = StdAtm( ref.h0 );
 ref.p0        = q.pressure;
 ref.a0        = q.speedOfSound;
 ref.t0        = q.temperature;
 ref.rho       = q.density;
 ref.gammaC    = AtmGamma( ref.t0 );
Form
 [t, tSFC, f, M, thR] = MixedFlowTurbofan( action, varargin )
Inputs
 action      (1,:) 'initialize' 'update'
 if action == struct
 t           (.) Default data
 if action == 'initialize'
 ref         (1,1) Reference conditions
 See JetEngineDefinitions.m
 if action == 'update'
 h           (1,1) Altitude
 v           (1,1) Velocity
 p           (1,1) Throttle settings
 .afterburner   (1,1) Afterburner on == 1
 .throttleRatio (1,1) Throttle ratio
 .tT4           (1,1) Combustor temperature (K)
 .tT7           (1,1) Afterburner temperature (K)
Outputs
 if action == 'initialize'
 ref         (1,1) Full set of reference conditions
 if action == 'update'
 t           (1,1)  Thrust (N/m^2)
 tSFC        (1,:)  Thrust specific fuel consumption
 f           (1,1)  Fuel air ratio structure
 .f   (1,1) Fuel air ratio
 .fAB (1,1) Afterburner fuel air ratio
 .fO  (1,1) Mixed fuel air ratio
 M           (1,:)  Mach number
 thR         (1,:)  Thrust to mass flow ratio
Reference: Mattingly, "Elements of Gas Turbine Propulsion," McGraw-Hill, 1996, 2005, p.551
References Altitude(), and(), AtmGamma(), Demo(), EngineExample(), get(), JetEngineDefinitions(), length(), MixedFlowTurbofan(), set(), StdAtm(), and Throttle().
Referenced by EngineTable(), MixedFlowTurbofan(), and MixedFlowTurbofanProfile().
MixedFlowTurbofanProfile()
function MixedFlowTurbofanProfile (in ref, in p, in h, in v)
 A mixed flow turbofan is one in which the fan and core streams
 mix in the same nozzle. This model supports afterburning.
 This is the same code as in JetEnginePeformance but designed for
 a single input. The outputs are the same as RamjetH2. Only mks units
 are supported in this function.
 Type MixedFlowTurbofanProfile for a demo
 This function calls MixedFlowTurbofan
 Note that only ref.h0 need be entered for the atmospheric parameters.
 The following are computed from the Standard Atmosphere and AtmGamma
 as follows.
 q = StdAtm( ref.h0 );
 ref.p0        = q.pressure;
 ref.a0        = q.speedOfSound;
 ref.t0        = q.temperature;
 ref.rho       = q.density;
 ref.gammaC    = AtmGamma( ref.t0 );
Form
 [t, tSFC] = MixedFlowTurbofanProfile( ref, p, h, v )
Inputs
 ref         (1,1) Reference conditions
                   See MixedFlowTurbofan.m
 p           (1,1) Throttle settings
                   .afterburner   (1,:) Afterburner on == 1
                   .throttleRatio (1,:) Throttle ratio
                   .tT4           (1,:) Combustor temperature (K)
                   .tT7           (1,:) Afterburner temperature (K)
 h           (1,:) Altitude
 v           (1,:) Velocity
Outputs
 t           (1,:)  Thrust (N/m^2)
 tSFC        (1,:)  Thrust specific fuel consumption (kg/N/s)
Reference: Mattingly, "Elements of Gas Turbine Propulsion," McGraw-Hill, 1996, 2005, p.551
References Altitude(), and(), AtmGamma(), Demo(), EngineExample(), length(), MixedFlowTurbofan(), MixedFlowTurbofanProfile(), Plot2D(), StdAtm(), Throttle(), and zeros().
Referenced by MixedFlowTurbofanProfile().
NewtonianAerodynamicsFromCAD()
function NewtonianAerodynamicsFromCAD (in alpha, in beta, in uMag, in rho, in g, in c, in angle, in uSurf, in display)
Shadowing is not modeled. Vertices must be entered into faces counterclockwise. The axis of rotation for the fuselage should be [0;0;0]; Plots will be against whichever input, alpha or beta, changes the most.
Lift and drag are assumed to be in the x-z plane. Drag is opposite the velocity vector. Lift is normal to drag in the x-z plane.
Form
 [force, torque, cL, cD, lOverD, aTotal] =
 NewtonianAerodynamicsFromCAD( alpha, beta, uMag,
 rho, g, c, angle, uSurf, display )
Inputs
 alpha          (1,:)  Angle of attack (rad)
 beta           (1,:)  Sideslip angle (rad)
 uMag           (1,:)  Velocity (m/s)
 rho            (1,:)  Density (kg/m^3)
 g               (.)   CAD data structure
 c              (3,1)  Center of mass (m)
 angle          (n,:)  Surface angles (rad)
 uSurf          (3,n)  Axis of rotation for the surface
 display        (1,1)  If entered draw the vehicle and active surfaces
Outputs
 force          (3,:)  Force (N)
 torque         (3,:)  Torque (Nm)
 cL             (1,:)  Lift coefficient
 cD             (1,:)  Drag coefficient
 lOverD         (1,:)  L/D
 aTotal         (1,1)  Total area
Reference for Demo: X-15 Flight 91, http://en.wikipedia.org/wiki/X-15_Flight_91 http://www.whiteeagleaerospace.com/blog/2009/08/24/the-highest-x-15-flight/
References and(), Demo(), InertiaFromOBJFile(), length(), LoadCAD(), NewtonianAerodynamicsFromCAD(), PolygonProps(), StdAtm(), UFromAlphaBeta(), vector(), and zeros().
Referenced by AeroForceAndTorqueCombined(), and NewtonianAerodynamicsFromCAD().
NewtonianAeroTable()
function NewtonianAeroTable (in fileName, in g, in a, in p)
 Generates a file with vertex and face data for triangles that
 make up a surface for the aero model. Each
 surface has the following matrices:
 axis vector             (3x1)
 position vector of axis (3x1)
 vertices                (mx3)
 faces                   (nx3)
 The axis vector will be unitized. There is one set of the above
 per component.
Form
 NewtonianAeroTable( fileName, g, a, p )
Inputs
 fileName       (1,:) Filename
 g               (.)  Component data structure (see BuildCADModel)
 a              (3,:) Axes
 p              (3,:) Points of axes
Outputs
 None
References and(), BuildCADModel(), NewtonianAeroTable(), set(), Unit(), and vector().
Referenced by NewtonianAeroTable().
NewtonianAlphaFromCAD()
function NewtonianAlphaFromCAD (in uMag, in rho, in g, in mass, in lift)
 This routine requires mks units because gravity is defined internally.
 fErr gives you the error at the end of the iterations by fzero.
 lift is optional. If not added it will balance the lift against
 gravity. Lift is defined as along z in the body frame.
 Type NewtonianAlphaFromCAD for a demo of X-15 Flight 91.
 The demo uses x15.obj.
Form
 [alpha, fErr] = NewtonianAlphaFromCAD( uMag, rho, g, mass, lift )
Inputs
 uMag           (1,1)  Magnitude of the velocity (m/s)
 rho            (1,1)  Density (kg/m^3)
 g               (.)   CAD data structure
 mass           (1,1)  Vehicle mass (kg)
 lift           (1,1)  Desired lift (N)
Outputs
 alpha          (1,:)  Angle of attack to balance gravity (rad)
 fErr           (3,1)  Force error
Reference: X-15 Flight 91, http://en.wikipedia.org/wiki/X-15_Flight_91 http://www.whiteeagleaerospace.com/blog/2009/08/24/the-highest-x-15-flight/
References and(), Demo(), LoadCAD(), NewtonianAlphaFromCAD(), NewtonianForceFromCAD(), StdAtm(), and UFromAlphaBeta().
Referenced by NewtonianAlphaFromCAD().
NewtonianCPFromCAD()
function NewtonianCPFromCAD (in uMag, in alpha, in rho, in g, in z)
 It only computes the x value of the center-of-mass.
Form
 [c, tErr] = NewtonianCPFromCAD( uMag, alpha, rho, g, z )
Inputs
 uMag           (1,1)  Magnitude of the velocity
 alpha          (1,:)  Angle of attack (rad)
 rho            (1,1)  Density
 g              (1,1)  CAD data structure
 z              (1,1)  Z location of center of mass
Outputs
 c              (1,1)  Center of pressure in x
 tErr           (3,1)  Torque error
Reference for Demo: X-15 Flight 91, http://en.wikipedia.org/wiki/X-15_Flight_91 http://www.whiteeagleaerospace.com/blog/2009/08/24/the-highest-x-15-flight/
References ActiveAeroSurfacesDisplay(), Cross(), Demo(), Dot(), DupVect(), length(), LoadCAD(), NewtonianCPFromCAD(), Plot2D(), PolygonProps(), StdAtm(), UFromAlphaBeta(), vector(), and zeros().
Referenced by NewtonianCPFromCAD().
NewtonianForceFromCAD()
function NewtonianForceFromCAD (in u, in rho, in g)
Shadowing is not modeled. Vertices must be entered into faces counterclockwise.
Form
 force = NewtonianForceAndTorqueFromCAD( u, rho, g )
Inputs
 u              (3,:)  Body frame velocity
 rho            (1,:)  Density
 g               (.)   CAD data structure
Outputs
 force          (3,:)  Force
References Demo(), Dot(), length(), LoadCAD(), Mag(), NewtonianForceFromCAD(), Plot2D(), PolygonProps(), StdAtm(), Unit(), vector(), and zeros().
Referenced by NewtonianAlphaFromCAD(), and NewtonianForceFromCAD().
NFromJ()
function NFromJ (in j, in d, in v, in h)
It also computes the propeller tip Mach number. Either or both altitude and velocity can be vectors. If they are both vectors they must be the same length.
Type NFromJ for a demo.
Form
 [n,mT] = NFromJ( j, d, v, h )
Inputs
 j  (1,:) Advance ratio
 d  (1,1) Blade diameter (m)
 v  (1,:) Free stream velocity (m/s)
 h  (1,:) Altitude (m, optional)
Outputs
 n  (1,:) Rotation rate (rps)
 mT (1,:) Tip Mach number (if h is specified)
Reference: W.A. Mair and D.L. Birdsall, "Aircraft Performance", Cambridge, 1992, pp. 97-98
References Altitude(), and(), isempty(), length(), NFromJ(), Plot2D(), and StdAtm().
Referenced by NFromJ().
NFromMT()
function NFromMT (in mT, in d, in h, in v)
It also computes the advance ratio. Either or both altitude and velocity can be vectors. If they are both vectors they must be the same length.
Type NFromMT for a demo.
Form
 [n,j] = NFromMT( mT, h, d, v )
Inputs
 mT (1,1) Tip Mach number
 d  (1,1) Blade diameter (m)
 h  (1,:) Altitude (m)
 v  (1,:) Velocity (m/s)
Outputs
 n (1,:) Rotation rate (rps)
 j (1,:) Advance ratio
Reference: W.A. Mair and D.L. Birdsall, "Aircraft Performance", Cambridge, 1992, pp. 97-98
References Altitude(), and(), Demo(), length(), NFromMT(), and StdAtm().
Referenced by NFromMT().
NOAAWindData()
function NOAAWindData (in area, in lvl, in latLonData)
The web site is:
 https://aviationweather.gov/data/windtemp/
 http://aviationweather.gov/api/data/nws/windtemp/?region=#1&fcst=06&level=#2
where #1 and #2 denote the first and second arguments, 'region' and 'level'
For more information on the data format, see:
https://aviationweather.gov/data/api/
NOTE: You must have a working internet connection to use this function.
Form
 data = NOAAWindData( area, lvl, latLonData )
Inputs
 area            (:)   Geographic area to get wind data from.
                       Choose from:
                        chicago, boston, miami, ft worth, salt lake,
                        san francisco hawaii western pacific
 lvl             (:)   Altitude level. Choose from:  low, high
 latLonData      (:)   Data structure array of city lat/lon data
Outputs
 data            (.)   Wind data set with fields:
                       .code      (:)     3 letter city/airport code
                       .lat       (1)     Latitude of location
                       .lon       (1)     Longitude of location
                       .h        (1,n)    Vector of altitudes
                       .heading  (1,n)    Vector of wind headings
                       .windMag  (1,n)    Vector of wind magnitudes
                       .windN    (1,n)    Vector of wind north components
                       .windE    (1,n)    Vector of wind east components
References Altitude(), and(), get(), set(), and Wind().
Referenced by MergeNOAAWindData(), and PlotWindField().
ObliqueShockAngle()
function ObliqueShockAngle (in m1, in delta, in gamma)
 Type ObliqueShockAngle for a demo showing oblique shock angles for a
 range of Mach numbers.
Form
 theta = ObliqueShockAngle( m1, delta, gamma )
Inputs
 m1    (1,1)  Mach number after shock
 delta  (1,:)  Streamline deflection angle
 gamma  (1,1)  Fluid ratio of specific heats
Outputs
 theta  (1,:)  Oblique shock angle
Reference: Ames Research Staff, "Equations, Tables and Charts for Compressible Flow," Report 1135.
References Demo(), isempty(), length(), MaxShockIncidenceAngle(), NewFig(), ObliqueShockAngle(), Plot2D(), RHS(), set(), XLabelS(), YLabelS(), and zeros().
Referenced by ObliqueShockAngle().
OH6A()
function OH6A (in q)
Form
 x = OH6A( q )
Inputs
 q                      String describing the type of data
Outputs
 x                      The properties
Reference: Bryson, A. E. Jr. "Control of Spacecraft and Aircraft", Princeton, p.274.
References EigEval(), OH6A(), statespace(), Step(), SVPlot(), and zeros().
Referenced by OH6A().
OptimalAngleOfAttackHypersonic()
function OptimalAngleOfAttackHypersonic (in m, in p, in l, in cParasitic)
Includes pressure effects, skin friction and parasitic drag.
The default Standard Atmosphere is at 1000 m.
Type CDCLHypersonic for a demo. One demo shows the variation of cD and cL with respect to Mach. The other shows the variation with respect to angle of attack. This function includes the pressure correction with Mach for cP. It also includes skin friction and parasitic drag.
Form
 alpha = OptimalAngleOfAttackHypersonic( m, p, l, cParasitic )
Inputs
 m           (1,:)    Freestream Mach number
 p            (.)    Standard atmosphere data structure
 l           (1,1)   Characteristic length
 cParasitic (1,1)   Parasitic drag
Outputs
 alpha       (1,:)   Angle of attack (rad)
See also
CPHypersonic, CDSkinFriction
References and(), CDCLHypersonic(), CDSkinFriction(), CPHypersonic(), Demo(), isempty(), length(), Plot2D(), RHS(), StdAtm(), and zeros().
ParasiticDragCoefficient()
function ParasiticDragCoefficient (in d)
Form
 cP = ParasiticDragCoefficient( d )
Inputs
 d          (:)   Array of data
                  .u      (1,:) Velocity (m/s)
                  .h      (1,:) Altitude (m)
                  .component
                       .type (1,:) 'fuselage', 'wing', 'nacelle'
                       .l    (1,1) Length (m)
                       .d    (1,1) Diameter (m)
                       .s    (1,1) Surface area (m)
                       .q    (1,1) Interference factor 0-1
                       .r    (1,1) t/c for wings, L/D for all others
Outputs
 cP         (1,:)  Parasitic drag coefficient
See also
WettedArea, AeroFormFactor, SkinFriction
References AeroFormFactor(), Altitude(), CDSkinFriction(), Demo(), length(), ParasiticDragCoefficient(), Plot2D(), set(), StdAtm(), WettedArea(), and zeros().
Referenced by ParasiticDragCoefficient().
PlotGasTurbineData()
function PlotGasTurbineData (in dP, in p, in units, in g)
Form
 PlotGasTurbineData( dP, p, units, g )
Inputs
 dP         (1,n)   Independent variable names
 p          (1,m)   Independent variable
 units      (1,:)   'eng' or 'mks'
 g          (1,1)   Data structure
Outputs
 None
PlotWindField()
function PlotWindField (in d, in altRange, in fig)
Each element of the has a single lat/lon coordinate, and a vector of wind speeds and headings across an altitude range.
See also
: NOAAWindData, MergeMOAAWindData
Form
 PlotWindField( windData )
Inputs
 d           (.)     Wind data set from NOAAWindData.
 altRange   (1,2)    Altitude range. Optional. (km)
 fig         (1)     Figure handle. Optional.
Outputs
 fig         (1)     Figure handle.
References Altitude(), and(), get(), length(), NewFig(), NOAAWindData(), PlotWindField(), set(), vector(), Wind(), and zeros().
Referenced by PlotWindField().
PowerPropeller()
function PowerPropeller (in u0, in d, in thrust, in rho)
This is the minimum power to drive a propeller. This is based on actuator disk theory.
Type PowerPropeller for a demo.
Form
 power = PowerPropeller( u0, d, thrust, rho )
Inputs
 u0      (1,:) Velocity (m/s)
 d       (1,1) Propeller diameter (m)
 thrust  (1,:) Thrust  (N)
 rho     (1,:) Density (kg/m^3)
Outputs
 thrust (1,:) Power (W)
Reference: https://web.mit.edu/16.unified/www/FALL/thermodynamics /notes/node86.html
References Demo(), and PowerPropeller().
Referenced by PowerPropeller().
PrandtlGlauertCorrection()
function PrandtlGlauertCorrection (in m, in delta)
 The correction is modified by a damping term, delta, to prevent
 infinite values at M = 1. delta should be less than 0.1.
 Type PrandtlGlauertCorrection for a demo.
Form
 pG = PrandtlGlauertCorrection( m, delta )
Inputs
 m               (1,:)  Mach number
 delta           (1,1)  If entered use this for transonic damping
Outputs
 pG              (1,:) Prandtl Glauert correction
References Demo(), length(), PrandtlGlauertCorrection(), and zeros().
Referenced by FormDragCoeff(), LiftCoeff(), and PrandtlGlauertCorrection().
PressureRatioFromMach()
function PressureRatioFromMach (in gamma, in m)
 For supersonic flow uses the Rayleigh pitot tube formula.
Form
 pR = PressureRatioFromMach( gamma, m )
Inputs
 gamma          (1,:)       Ratio of specific heats
 m              (1,:)       Mach number
Outputs
 pR             (1,:)       Pressure ratio
See also
: RayleighPitotTube
Reference: Anderson, John D. Introduction to Flight, Third Edition, McGraw-Hill, 1989. Ch. 4, Basic Aerodynamics
References and(), Demo(), isempty(), length(), Plot2D(), Pressure(), PressureRatioFromMach(), and RayleighPitotTube().
Referenced by PressureRatioFromMach().
PressureRatioFromTemp()
function PressureRatioFromTemp (in tau, in eta, in gamma)
Form
 pi = PressureRatioFromTempRatio( tau, eta, gamma )
Inputs
 tau        (1,n)  Temperature ratio
 eta        (1,n)  Efficiency
 gamma      (1,n)  Gamma
Outputs
 pi         (1,n)   Pressure ratio
References and(), Demo(), Gamma(), Pressure(), and PressureRatioFromTemp().
Referenced by PressureRatioFromTemp().
PressureTotal()
function PressureTotal (in p, in gamma, in machNo)
Form
 pT = PressureTotal( p, gamma, machNo )
Inputs
 p          (1,1)   Pressure
 gamma      (1,1)   Ratio of specific heats
 machNo     (1,:)   Mach number
Outputs
 pT          (1,:)  Total pressure
References Demo(), Plot2D(), Pressure(), and PressureTotal().
Referenced by PressureTotal().
PropellerEfficiency()
function PropellerEfficiency (in etaMax, in machNo)
 Type PropellerEfficiency for a demo.
Form
 eta = PropellerEfficiency( etaMax, machNo )
Inputs
 etaMax     (1,1)   Maximum efficiency
 machNo     (1,:)   Mach number
Outputs
 eta        (1,:)   Efficiency
References Demo(), length(), PropellerEfficiency(), and zeros().
Referenced by PropellerEfficiency().
PropellerMomentum()
function PropellerMomentum (in t, in d, in h, in v)
It computes power and efficiency from thrust and blade diameter.
Type PropellerMomentum for a demo.
Form
 [p,eff] = PropellerMomentum( t, d, h, v )
Inputs
 t   (1,:) Thrust (N)
 d   (1,1) Diameter (m)
 h  (1,:) Altitude (m)
 v   (1,:) Velocity (m/s)
Outputs
 p   (1,:) Power (W)
 eff (1,:) Efficiency
 w   (1,:) Propeller induced velocity (m/s)
Reference: McCormick, B. W., "Aerodynamics, Aeronautics, and Flight Mechanics," John Wiley, 1979, pp. 343-347.
References Altitude(), and(), PropellerMomentum(), and StdAtm().
Referenced by PropellerMomentum().
PropellerPower()
function PropellerPower (in rho, in a, in t, in v)
Form
 [p, w] = PropellerPower( rho, a, t, v )
Inputs
 rho       (1,1) Density (kg/m^3)
 a         (1,1) Propeller disk area (m^2)
 t         (1,:) Thrust (N)
 v         (1,1) Velocity (m/s)
Outputs
 p         (1,:) Power (W)
 w         (1,:) Induced velocity (m/s)
Reference: McCormick, Barnes W. "Aerodynamics, Aeronautics and Flight Mechanics," John Wiley & Sons, 1979, p. 345.
References and(), and PropellerPower().
Referenced by PropellerPower().
PropellerThrust()
function PropellerThrust (in x, in rho, in d)
 d.N and rho can be vectors. The thrust coefficient is a function of
 advance ratio.
 cT = CTFun( j ) where j = v/(n*d) where d is the diameter of the blade
 and n is rad/s.
 Type PropellerThrust for a demo
Form
 thrust = PropellerThrust( x, rho, d )
Inputs
 x       (13,1)  State [r;v;q;omega]
 rho     (1,:)   Density (kg/m^3)
 d       (.)     Data structure
                 .N  (1,:) RPM
                 .cT (1,1) Thrust coefficent function
                 .d  (1,1) Diameter of blade (m)
Outputs
 t         (1,:) Thrust (N)
References and(), length(), Mag(), Plot2D(), PropellerThrust(), and zeros().
Referenced by PropellerThrust().
QECI()
function QECI (in r, in e)
Form
 qECIToB = QECI( r, e )
Inputs
 r           (3,1) ECI Position vector
 e           (3,1) Euler angles [phi;theta;psi]
Outputs
 qECIToB     (4,1) Quaternion from ECI to B
See also
ECIToNED
Reference: Stevens, B.L., Lewis, F.L. , Aircraft Control and Simulation, John Wiley & Sons, 1992, p. 38.
References and(), ECIToNED(), Eul2Q(), Euler(), QMult(), quaternion(), and vector().
Referenced by AirshipInit(), AirshipState(), AirshipTrim(), CreateMVSSetupFileEntries(), and GenerateAirshipAeroMats().
Ramjet()
function Ramjet (in m, in d, in p)
The default fuel is H2. Computes the thrust and exhaust velocity including aerodynamic losses.
Inputs u and h must have the same lengths. This function calls the standard atmosphere model. If no inputs are given and just one output it will return the default data structure.
Type Ramjet for a demo. The demo varies the altitude from 10 to 40 km and the Mach number from 1.5 to 7.
Form
 Ramjet; % demo
 [t, tSFC, uE, f, iSp, thR] = Ramjet( m, d, p )
Inputs
 m           (1,:)  Mach number
 d            (.)   Data structure
                    .gamma    (1,1) Airflow ratio of specific heats
                    .qR       (1,1) Joules/kg for the fuel  (default H2)
                    .etaB     (1,1) Combustion efficiency
                    .t04      (1,1) Combustor temperature
                    .cP       (1,1) Air specific heat
                    .pEOverPA (1,1) Ratio of exit pressure to atmospheric pressure
                    .aI       (1,1) Inlet area
                    .rD       (1,1) Diffuser pressure ratio
                    .rC       (1,1) Combustor pressure ratio
                    .rN       (1,1) Nozzle pressure ratio
                    .aE       (1,1) Exit area
 p           (.)    Standard atmosphere
Outputs
 t           (1,:)  Thrust (N)
 tSFC        (1,:)  Thrust specific fuel consumption
 uE          (1,:)  Exhaust velocity (m/s)
 f           (1,:)  Fuel air ratio
 m           (1,:)  Mach number
 iSp         (1,:)  Specific impulse (sec)
 thR         (1,:)  Thrust to mass flow ratio
Reference: Hill, P.G. and Peterson, C. R., "The Mechanics and Thermodynamics of Propulsion," Addison-Wesley, Reading, MA, 1970, pp. 154-157.
References and(), DefaultData(), Demo(), isempty(), length(), Plot2D(), Ramjet(), StdAtm(), and zeros().
Referenced by EngineTable(), JetEngineAnalysis(), JetEnginePerformance(), Ramjet(), RamjetExternalHeatSource(), RamjetKerrebrock(), Turbofanramjet(), TurboRamjet(), TurboRamjetSim(), and TurboRamRocket().
RamjetExternalHeatSource()
function RamjetExternalHeatSource (in m, in p, in d)
Computes the thrust and exhaust velocity including aerodynamic losses.
Type RamjetExternalHeatSource for a demo.
Form
 RamjetExternalHeatSource;  % demo
 [t, uE] = RamjetExternalHeatSource( m, p, d )
Inputs
 m           (1,:)  Mach numer
 p           (.)    Atmosphere data structure
                    .density         (1,:) Atmospheric Density (kg/m^3)
                    .temperature     (1,:) Temperature (deg-K)
                    .pressure        (1,:) Pressure (N/m^2)
 d           (.)    Data structure
                    .gamma    (1,1) Airflow ratio of specific heats
                    .etaB     (1,1) Combustion efficiency
                    .qR       (1,1) Power from the heat source
                    .cP       (1,1) Air specific heat
                    .pEOverPA (1,1) Ratio of exit pressure to atmospheric pressure
                    .aI       (1,1) Inlet area
                    .rD       (1,1) Diffuser pressure ratio
                    .rC       (1,1) Combustor pressure ratio
                    .rN       (1,1) Nozzle pressure ratio
                    .aE       (1,1) Exit area
Outputs
 t           (1,:)  Thrust (N)
 uE          (1,:)  Exhaust velocity (m/s)
Reference: Hill, P.G. and Peterson, C. R., "The Mechanics and Thermodynamics of Propulsion," Addison-Wesley, Reading, MA, 1970, pp. 154-157.
References and(), AtmEarth(), Demo(), MolWt2R(), Plot2D(), Pressure(), Ramjet(), and RamjetExternalHeatSource().
Referenced by RamjetExternalHeatSource().
RamjetKerrebrock()
function RamjetKerrebrock (in m, in d, in p)
 Type RamjetKerrebrock for a demo.
Form
[t, iSp, tS] =  RamjetKerrebrock(m, d, p)
 d =  RamjetKerrebrock;
Inputs
 m  (1,:)   Mach number
 d  (1,1)   Data structure for engine
         .gamma     (1,1) Specific heat ratio of air
         .cP        (1,1) Specific heat of air
         .qR        (1,1) Heating value of fuel
         .tT4       (1,1) Temperature at station 4
         .aInlet    (1,1) Inlet area
 p   (1,1)  Standard atmosphere
Outputs
 t   (1,:)  Thrust (N)
 iSp  (1,:) Specific impulse (s)
 tS  (1,:)  Specific thrust
Reference: Kerrebrock, J. http://web.mit.edu/16.unified/www/FALL/thermodynamics/notes/node85.html
References and(), DefaultData(), Demo(), isempty(), length(), Plot2D(), Ramjet(), RamjetKerrebrock(), and StdAtm().
Referenced by RamjetKerrebrock(), and TurboRamjet().
RamRecovery()
function RamRecovery (in machNo)
 This computes the loss of pressure due to shocks. It is based on
 Military Specification 5008B.
Form
 etaR = RamRecovery( machNo )
Inputs
 machNo     (1,:)   Mach number
Outputs
 etaR       (1,:)   Ram recovery
References Demo(), length(), Plot2D(), and RamRecovery().
Referenced by MassFlow(), and RamRecovery().
RateOfClimb()
function RateOfClimb (in d, in velocity, in altitude)
Form
 [rateOfClimb, accel] = RateOfClimb( d, velocity, altitude )
Inputs
 d              (1,1)  See "ConcordeProperties.m"
 velocity       (1,:)  Velocity
 altitude       (1,:)  Altitude (m)
Outputs
 rateOfClimb    (1,:)  Range (m/s)
 accel          (1,:)  Acceleration (m/s^2)
Reference: Mair, W. A. and D. L. Birdsall, "Aircraft Performance," Cambridge, pp. 271-272.
References Altitude(), and(), ConcordeProperties(), Gamma(), length(), Plot2D(), RateOfClimb(), and StdAtm().
Referenced by RateOfClimb().
RayleighPitotTube()
function RayleighPitotTube (in m, in gamma)
 Only valid for hypersonic flight, i.e.
 m > sqrt((gamma-1)/2*gamma)
Form
 pR = RayleighPitotTube( m, gamma )
Inputs
 m              (1,:)  Mach number
 gamma          (1,1)  Ratio of specific heats
Outputs
 pR             (1,:)  Pressure ratio stagnation/p at infinity
Reference: Anderson, John D. Introduction to Flight, Third Edition, McGraw-Hill, 1989. Eq. 4.79
References and(), AtmGamma(), Demo(), length(), Plot2D(), Pressure(), and RayleighPitotTube().
Referenced by CPHypersonic(), PressureRatioFromMach(), and RayleighPitotTube().
RDE()
function RDE (in m, in d, in p)
RDE is a rotating detotation engine. The default data structure has the afterburner off. The default fuel is hydrogen.
Type RDE for a demo.
Form
 RDE;   % demo
 [t, iSp, tS] = RDE( m, d, p )
 d = RDE;   % default data
Inputs
 m  (1,:)   Mach number
 d   (.)  Data structure for engine
         .gamma     (1,1) Specific heat ratio of air
         .cP        (1,1) Specific heat of air
         .qR        (1,1) Heating value of the fuel
         .mDotO2    (1,1) O2 mass flow (kg/s)
         .tT4       (1,1) Temperature at station 4
         .aInlet    (1,1) Inlet area (m^2)
         .mDiffuser (1,1) Diffuser
         .piC       (1,1) Compressor pressure ratio
 p  (.)  Standard atmosphere
Outputs
 t   (1,:)  Thrust (N)
 iSp  (1,:) Specific impulse (s)
 tS  (1,:)  Specific thrust (N/(kg/s))
Reference: Eric M. Braun,Frank K. Lua, Donald R. Wilson, Jos A. Camberos, "Airbreathing rotating detonation wave engine cycle analysis", Aerospace Science and Technology 27 (2013) 201?208.
See also
: TurbojetNoThrust, AerodynamicShock
References AerodynamicShock(), and(), DefaultData(), Demo(), length(), Plot2D(), RDE(), TurbojetNoThrust(), and zeros().
Referenced by HyperRDE(), and RDE().
RHS2DPointMass()
function RHS2DPointMass (in x, in ignoredArg, in d)
 This model requires drag and thrust functions to be passed as part
 of the data structure. The thrust function is of the form
 [thrust, sFC] = ThrustFunction( m, d, p )
 where thrust is the scalar thrust. The drag function is of the form
 [lift, drag] = DragFunction( m, d ),
 where d is a data structure and drag is the scalar drag.
Form
 d = RHS2DPointMass;
 xDot = RHS2DPointMass( x, t, d )
 [thrust, drag] = RHS2DPointMass( x, t, d )
Inputs
 x       (5,1)    [v;gamma;h;mass;range]
 t       (1,1)    Time vector for integration
 d       (1,1)    Data structure
                  .tFcn           (1,1) Pointer to thrust function
                  .g              (1,1) Gravitational acceleration
                  .engine         (1,1) Structure to engine data
                  .aero           (1,1) Structure to aero data
Outputs
 if 1 output:
 xDot     (5,1)    d[v;gamma;h;mass;range]/dt
 if 2 outputs
 thrust   (1,1)    Thrust
 drag     (1,1)    Drag
References and(), RHS2DPointMass(), scalar(), and vector().
Referenced by RHS2DPointMass(), and TurboRamjetSim().
RHS3DPointAircraft()
function RHS3DPointAircraft (in s, in ignoredArg, in d)
If a time constant for a control is set to zero it will make the control and actual values the same and remove those states.
d.thrust can be a scalar, in which case mDot = 0 or a function of the form:
 [thrust, sFC] = d.thrust( mach, d, p );
where p is the standard atmosphere model and d is the data for the engine model.
This routine uses meters for distance. With numerical integration you just need the first output. The others are for getting information about intermediate values.
Form
 d = RHS3DPointAircraft;dg
 [sDot, D, L, rho, thrust, mach, q, iSp] = RHS3DPointAircraft( s, t, d )
Inputs
 s   (7,1)   State [v;gamma;psi;x;y;h;m] (metric)
 t   (1,1)   Time (s) (unused)
 d    (.)    Data structure
             .mass       (1,1) Dry mass of the aircraft (kg)
             .s          (1,1) Reference area (m^2)
             .cDCL       (1,1) Lift and drag function or
                         (1,3) [cLAlpha, cD0, kInduced]
             .lDData      (.)  Data to be passed to cDCL
             .atmData     (.)  Data for StdAtm
             .alpha      (1,1) Angle of attack (rad)
             .phi        (1,1) Bank angle (rad)
             .thrust     (1,1) Thrust function pointer or thrust
Outputs
 s      (7,1)    State derivative d[v;gamma;psi;x;y;h;gm]/dt
 D      (1,1)    Drag
 L      (1,1)    Lift
 rho    (1,1)    Density
 thrust (1,1)    Engine thrust
 q      (1,1)    Dynamic pressure
 iSp    (1,1)    Engine specific impulse
References abs(), and(), Constant(), DefaultDataStructure(), Demo(), RHS3DPointAircraft(), scalar(), set(), SimpleLiftAndDrag(), StdAtm(), vector(), and zeros().
Referenced by ACPointMassControl(), and RHS3DPointAircraft().
RHSACFlatEarth()
function RHSACFlatEarth (in x, in ignoredArg, in d)
This uses the data structure generated by CreateAircraftModel. The default data structure is from the Gulfstream model. +z is normal to the Earth's surface.
You can add your own lift, drag and thrust models of the form:
lift = Lift(q, alpha, mach, d); Drag = Drag(q, alpha, mach, d); Thrust = Thrust(mach, rho, d);
Enter as pointers in the data structure.
v is in the body frame.
This function does not have provision for actuator lags.
Form
 d = RHSACFlatEarth;   % data structure
 [xDot, force, torque, lift, drag] = RHSACFlatEarth( x, ~,  d )
Inputs
 x       (13,1) State vector [r;v;q;omega;thrust] (m,m/s,~,rad/s)
 t       (1,1)  Time (s) (not used)
 d       (.)    Data structure
Outputs
 xDot    (13,1) State vector derivative [r;v;q;omega] (m,m/s,~,rad/s)
 force   (3,1)  Force (N)
 torque (3,1)  Torque (Nm)
 lift    (1,1)  Lift force (N)
 drag    (1,1)  Drag force (N)
References CreateAircraftModel(), DefaultDataStructure(), and RHSACFlatEarth().
Referenced by RHSACFlatEarth(), and RHSFlatEarthSet().
RHSFlatEarthSet()
function RHSFlatEarthSet (in x, in d, in opt)
This finds the throttle setting, elevator angle and angle of attack.
Type RHSFlatEarthSet for a demo which loads Gulfstream.mat
Form
 RHSFlatEarthSet;
 [q,control] = RHSFlatEarthSet( x, d, opt )
Inputs
 x       (13,1) State vector [r;v;q;omega] (m,m/s,~,rad/s)
 d       (.)    Data structure (RHSACFlatEarth)
 opt     (.)    Data structure for fminsearch
Outputs
 q       (4,1) Quaternion from ECI to body
 control    (.)   Control data structure
References and(), Demo(), LiftCoeffStall(), Mag(), Mat2Q(), RHS(), RHSACFlatEarth(), RHSFlatEarthSet(), set(), Throttle(), and vector().
Referenced by RHSFlatEarthSet().
RHSLiftingSatellite()
function RHSLiftingSatellite (in x, in ignoredArg, in d)
This function includes orientation, and wheel speed. The disturbance function returns the body torque in Nm and the inertial force in N. It assumes 3 orthogonal reaction wheels.
Form
 d =  RHSLiftingSatellite;
 [xDot,L,D,tAero] = RHSLiftingSatellite(x,~,d)
Inputs
 x   (16,1) State vector [r;v;q;omega;omegaW]
 t   (1,1)    Time
 d   (.)      Data structure for the simulation
             .mu      (1,1) Gravitational parameter
             .cD0     (1,1) Zero angle drag coefficient
             .cLAlpha (1,1) Lift coefficient
             .s       (1,1) Area for lift and drag (m^2)
             .eps     (1,1) Oswald efficiency factor
             .inrW    (1,1) Wheel polar inertia (kg-m^2)
             .inr     (3,3) Inertia matrix (kg-m^2)
             .tC      (1,1) Control torque (Nm)
             .tD      (3,1) Disturbance torque (Nm)
             .tW      (3,1) Wheel torque (Nm)
             .rCP     (1,1) Moment arm of center of pressure
             .x0      (16,1) Default state
             .mass    (1,1) Mass
             .alphaW  (1,1) Angle of attack
             .l       (1,1) Characteristic length
             .cPara   (1,1) Parasitic drag coefficient
Outputs
 xDot        (13,1)     State vector derivative
References AbsoluteViscosity(), and(), AtmDens2(), AtmSnd(), AtmTemp(), CDCLHypersonic(), Cross(), DefaultDataStructure(), KinematicViscosity(), length(), RHSLiftingSatellite(), Unit(), and vector().
Referenced by RHSLiftingSatellite().
RHSPointMassAircraft()
function RHSPointMassAircraft (in x, in ignoredArg, in d)
Includes runway forces. Includes variable mass.
To get the default data structure, type:
 d = RHSPointMassAircraft
The state is [velocity;flight path angle; turn angle; x direction; y direction; altitude; mass fuel]
 Form
 [xDot,lift,drag] = RHSPointMassAircraft( ~, x, d )
Inputs
 t     (1,1) Time (unused)
 x     (7,1) State [v;gamma;psi;xE;yN;h;mF]
 d     (.)   Data structure
             .cD0      (1,1) Drag coefficient with zero lift
             .aR       (1,1) Wing aspect ratio
             .eps      (1,1) Oswald efficiency factor
             .cLAlpha  (1,1) Lift coefficient
             .s        (1,1) Lift/drag area (m^2)
             .g        (1,1) Gravitational acceleration (m/s^2)
             .alpha    (1,1) Angle of attack (rad)
             .phi      (1,1) Bank angle (rad)
             .thrust   (1,1) Engine thrust (N)
             .m        (1,1) Dry mass (kg)
             .f        (3,1) Force vector (N)
             .fSp      (1,1) Specific fuel consumption (kg/Ns)
             .density  (1,1) Atmosphere density (kg/m^3)
Outputs
 xDot  (7,1) State derivative [v;gamma;psi;xE;yN;h;mF]
 lift  (1,1) Lift (N)
 drag  (1,1) Drag (N)
References DefaultDataStructure(), get(), RHSPointMassAircraft(), vector(), Wing(), and zeros().
Referenced by EquilibriumControls(), and RHSPointMassAircraft().
RHSRollingMissileLinear()
function RHSRollingMissileLinear (in x, in ignoredArg, in d)
Right hand side for a linear rolling missile
d = RHSRollingMissileLinear
returns the default data structure.
Form
 xDot = RHSRollingMissileLinear( x, ~, d )
Inputs
 x     (5,1) [pitch/yaw;angle of attack, pitch rate, yaw rate;roll angle]
 t     (1,1)    Time (unused)
 d     (.)   Data structure
             .p          (1,1) Roll rate (rad/s)
             .mAlpha        (1,1)
             .zDelta     (1,1)
             .mDelta     (1,1)
             .mAlphaDot  (1,1)
             .mQ         (1,1)
             .zAlpha     (1,1)
             .zDelta     (1,1)
             .iX         (1,1) Roll inertia (kg/m^2)
             .iY         (1,1) Pitch inertia (kg/m^2)
             .deltaY     (1,1) Yaw flap deflection (rad)
             .deltaP     (1,1) Pitch flap deflection (rad)
                       .
Outputs
 xDot   (5,1)   d[pitch/yaw;angle of attack, pitch rate, yaw rate, roll angle]/dt
Reference: Richard Lestage, "Analysis of Control and Guidance for Rolling Missiles with a Singlee Plane of Control Fins," AIAA-2000-3971, AIAA Guidance, Navigation, and Control Conference and Exhibit 14-17 August 2000 Denver,CO.
References and(), DefaultDataStructure(), and RHSRollingMissileLinear().
Referenced by RHSRollingMissileLinear().
RNEH()
function RNEH (in r, in units)
 This is the frame with x pointing north, y pointing east and U up from
 the earth's surface. This is not a right handed frame.
Form
 rNEH  = RNEH( r, units )
Inputs
 r           (3,1) Position vector (m)
 units       (1,:) Units
Outputs
 rNEH        (3,1) [N;E;H]
Reference: Stevens, B.L., Lewis, F.L. , Aircraft Control and Simulation,John Wiley & Sons, 1992, p. 36.
References and().
Scimitar()
function Scimitar (in m, in ignoredArg, in ignoredArg)
 Uses lookup tables from publicly available data. It interpolates
 from the input data. This model doesn't use d or q. The model assumes
 a particular Mach number altitude profile.
 Type Scimitar for a demo.
Form
 [t, sFC, h] = Scimitar( m, d, q )
Inputs
 m           (1,1)  Mach number
 d           (1,1)  Engine data structure (not used)
 q           (1,1)  Standard atmosphere (not used)
Outputs
 t           (1,1)  Thrust (N)
 sFC         (1,1)  Specific Fuel Consumption (kg/N-s)
 h           (1,1)  Assumed altitude (m)
Reference: https://spiral.imperial.ac.uk:8443/bitstream/10044 /1/1456/1/EUCASS07_scimitar_5_08_03.pdf
References Scimitar().
Referenced by AircraftDesign(), FuelFromRange(), and Scimitar().
SimpleLiftAndDrag()
function SimpleLiftAndDrag (in m, in d)
 The standard atmosphere fields must have the same dimension as Mach.
 Type SimpleLiftAndDrag for a demo at constant altitude.
Form
 d = SimpleLiftAndDrag( 'a' );
 [lift, drag] = SimpleLiftAndDrag( m, d )
Inputs
 m          (1,:)   Mach
 d          (1,1)   Data structure
                    .cLAlpha (1,1) Lift coefficient
                    .cD0     (1,1) Drag coefficient
                    .k       (1,1) Induced drag coefficient
                    .s       (1,1) Area
                    .p       (1,1) Standard atmosphere
                    .alpha   (1,1) Angle of attack
Outputs
 lift       (1,1)   Lift force
 drag       (1,1)   Drag force
 qCL        (1,1)   Dynamic pressure times the lift coefficient
References and(), Demo(), isempty(), length(), SimpleLiftAndDrag(), StdAtm(), and zeros().
Referenced by ComputeAlphaConstantFlightPathAngle(), RHS3DPointAircraft(), SimpleLiftAndDrag(), and TurboRamjetSim().
SonicBoom()
function SonicBoom (in h)
 Type SonicBoom for a demo.
Form
 scale = SonicBoom( h );
Inputs
 h             (1,:)   Altitude (meters)
Outputs
 scale         (1,:)   Sonic boom scale factor
 p             (1,:)   Atmospheric pressure    (N/m^2)
See also
: StdAtm.
References Altitude(), Demo(), Plot2D(), SonicBoom(), and StdAtm().
Referenced by SonicBoom().
SonicBoomHypersonic()
function SonicBoomHypersonic (in drag, in m, in h, in atmData)
Form
 [dP, i, t] = SonicBoomHypersonic( drag, m, h, atmData )
Inputs
 drag    (1,1)  Drag force (N)
 m       (1,1) Mach number
 h       (1,:)  Altitude (km)
 atmData (:,6) Atmospheric data for StdAtm
Outputs
 pG      (1,:)  N wave overpressure (N)
 i       (1,:) Positive Phase Impulse (N/s)
 t      (3,:) Duration (s)
Reference: Plotkin, K.J., "Review of Sonic Boom Theory," AIAA-89=-1105, 1989.
References Altitude(), Constant(), Demo(), length(), SonicBoomHypersonic(), and StdAtm().
Referenced by SonicBoomHypersonic().
StallVelocity()
function StallVelocity (in m, in cLMax, in s, in rho)
 Type StallVelocityTakeoffVelocity for a demo.
Form
 vStall = StallVelocity( m, cLMax, s, rho )
Inputs
 m              (1,1)  Mass (m)
 cLMax          (1,1)  Maximum Lift coefficient
 s              (1,1)  Reference area
 rho            (1,1)  Atmospheric density (kg/m^3)
Outputs
 vStall         (1,:)  Stall velocity
Reference: Anderson, J. D., "Introduction to Flight 3rd Edition,", McGraw-Hill 1989, pp 318-324.
References Demo(), and StallVelocity().
Referenced by LandingDistance(), StallVelocity(), and TakeoffVelocity().
StateSpacePlot()
function StateSpacePlot (in opt, in x, in y, in u, in d)
opt is 'init', 'store', 'plot'
 The calls are
 d = StateSpacePlot( 'init', plots, nPts, nSim )
 plots is a data structure containting
 plots.x       states to plot e.g. [1:4 6 9] or 'all'
 plots.u       inputs to plot or 'all'
 plots.y       outputs to plots or 'all'
 plots.g       state space data structure
 do k = 1:nSim
 d = StateSpacePlot( 'store', x, y, u, d )
 end
 StateSpacePlot( 'plot', d )
Form
 d = StateSpacePlot( opt, x, y, u, d )
Inputs
 opt    (n,:)   Options 'init'
                        'store'
                        'plot'
 x      (:)     State vector "plots" data structure
 y      (:)     Outputs      or nPts
 u      (:)     Inputs       or nSim
 d      (:)     Internal data structure or n steps in the sim
Outputs
 d      (:)     Internal data structure or list of plots
References get(), Initialize(), length(), Plot2D(), statespace(), TimeLabl(), vector(), and zeros().
StaticPumping()
function StaticPumping (in cP, in altitude, in pR, in g)
Form
 [mDot, v] = StaticPumping( cP, altitude, pR, g )
Inputs
 cP         (1,1)   Specific heat
 altitude   (1,1)   Altitude (m) (Unused if g entered)
 pR         (1,:)   Pressure ratio
 g          (1,1)   Standard atmosphere
Outputs
 mDot       (1,:)   Mass (kg/m^2)
 v          (1,:)   Velocity
References Altitude(), AtmGamma(), Demo(), Plot2D(), Pressure(), StaticPumping(), and StdAtm().
Referenced by StaticPumping().
STOVL()
function STOVL (in q)
Form
 x = STOVL( q )
Inputs
 q                      String describing the type of data
Outputs
 x                      The properties
Reference: Lee, H. P., Jr., Yousseff, H.M. and R.P. Habek, "Application of Eigenstructure Assignment to the Design of STOVL Flight Control Systems," AIAA 88-4140-CP.
References and(), Takeoff(), and zeros().
SToW()
function SToW (in beta, in opt)
Form
 b = SToW( beta, opt )
Inputs
 beta        (1,1) Sideslip angle (rad)
 opt         (1,:) 'matrix' or 'quaternion'
Outputs
 b           (3,3) Transformation matrix
             (4,1) Quaternion
Reference: Stevens, B.L., Lewis, F.L. , Aircraft Control and Simulation, John Wiley & Sons, 1992, p. 63.
References and(), Mat2Q(), and quaternion().
StreamlineShockAngle()
function StreamlineShockAngle (in theta, in m1, in gamma)
Type StreamlineShockAngle for a demo.
Form
 delta = StreamlineShockAngle( theta, gamma )
Inputs
 theta  (1,:)  Oblique angle (rad)
 m1    (1,:)  Mach number
 gamma  (1,1)  Fluid ratio of specific heats
Outputs
 delta  (1,:)  Streamline deflection shock angle  (rad)
References Demo(), Plot2D(), and StreamlineShockAngle().
Referenced by MachAcrossShock(), and StreamlineShockAngle().
SweepAngle()
function SweepAngle (in m)
 Type SweepAngle for a demo.
Form
 angle = SweepAngle(m)
Inputs
 m       (1,:)  Mach number
Outputs
 angle   (1,:) Sweep angle (rad)
References Demo(), length(), Plot2D(), Sweep(), and SweepAngle().
Referenced by SweepAngle().
Takeoff()
function Takeoff (in d, in altitude)
To see a demo, run with no inputs: [s,v,def] = Takeoff;
Form
 [sTotal, vLiftoff, def] = Takeoff( d, altitude )
Inputs
 d               (.)   See "ConcordeProperties.m"
 altitude       (1,1)  Altitude (m)
Outputs
 sTotal         (1,1)  Ground roll (m)
 vLiftoff       (1,1)  Liftoff velocity (m/s)
 def            {12,3} Data structure definition
Reference: Mair, W. A. and D. L. Birdsall, "Aircraft Performance," Cambridge, p. 139.
References Altitude(), and(), and Takeoff().
Referenced by ACPointMassControl(), AircraftCostCalculation(), AircraftGroupMass(), AircraftWeights(), LaunchSummary(), LVThrustToWeight(), STOVL(), Takeoff(), TakeoffDistance(), and TSTOSizing().
TakeoffDistance()
function TakeoffDistance (in m, in vLO, in t, in cL, in cD0, in muR, in hB, in d, in rho)
 Type  TakeoffDistance for a demo.
Form
 sLO = TakeoffDistance( m, vLO, t, cL, cD0, muR, hB, d, rho )
Inputs
 m              (1,1)  Mass (kg)
 vLO            (1,1)  Lift off velocity (m/s)
 cL             (1,1)  Lift coefficient
 cD0            (1,1)  Drag coefficient
 muR            (1,1)  Rolling resistance
 hB             (1,1)  Altitude/wing span
 d               (.)   Drag data structure
 rho            (1,1)  Atmospheric density (kg/m^3)
Outputs
 sLO            (1,:)  Takeoff distance (m)
Reference: Anderson, J. D., "Introduction to Flight 3rd Edition,", McGraw-Hill 1989, pp 318-324.
References Altitude(), Demo(), Takeoff(), and TakeoffDistance().
Referenced by TakeoffDistance().
TakeoffTransition()
function TakeoffTransition (in hSc, in n, in gamma)
 The aircraft must reach the flight path angle at the screen height.
 hSc, n and gamma may be vectors but they must be the same length or
 of length 1.
 Type TakeoffTransition for a demo.
Form
 [s, v, r] = TakeoffTransition( hSc, n, gamma )
Inputs
 hSc             (1,:) Screen height (m)
 n               (1,:) Lift/weight
 gamma           (1,:) Flight path angle (rad)
Outputs
 s               (1,:) Length of transition (m)
 v               (1,:) Velocity (m/s)
 r               (1,:) Turning radius (m)
Reference: Mair, W. and D. L. Birdsall, "Aircraft Performance," Cambridge, p. 141-142.
References and(), Demo(), length(), Plot2D(), and TakeoffTransition().
Referenced by TakeoffTransition().
TakeoffVelocity()
function TakeoffVelocity (in m, in cLMax, in s, in f, in rho)
 Type  TakeoffVelocity for a demo.
Form
 vLO = TakeoffVelocity( m, cLMax, s, f, rho )
Inputs
 m              (1,1)  Mass (kg)
 cLMax          (1,1)  Maximum Lift coefficient
 s              (1,1)  Reference area (m^2)
 f              (1,1)  Factor of safety on stall velocity
 rho            (1,1)  Atmospheric density (kg/m^3)
Outputs
 vLO            (1,:)  Liftoff velocity (m/s)
See also
: StallVelocity
Reference: Anderson, J. D., "Introduction to Flight 3rd Edition,", McGraw-Hill 1989, pp 318-324.
References Demo(), StallVelocity(), and TakeoffVelocity().
Referenced by TakeoffVelocity().
TaxiingFuel()
function TaxiingFuel (in t, in m)
 Based on A320 and B777 data.
 Type TaxiingFuel for a demo.
Form
 mF = TaxiingFuel( t, m )
Inputs
 t             (1,1)    Taxiing duration (min)
 m             (1,:)    Liftoff mass (kg)
Outputs
 mF            (1,:)    Taxiing fuel (kg);
Reference: http://www.airliners.net/aviation-forums/tech_ops /read.main/140800/
References and(), Demo(), Plot2D(), and TaxiingFuel().
Referenced by TaxiingFuel().
TemperatureTotal()
function TemperatureTotal (in t, in gamma, in machNo)
Form
 tT = TemperatureTotal( t, gamma, machNo )
Inputs
 t          (1,1)   Temperature
 gamma      (1,1)   Ratio of specific heats
 machNo     (1,:)   Mach number
Outputs
 tT          (1,:)  Total pressure
References Demo(), Plot2D(), and TemperatureTotal().
Referenced by TemperatureTotal().
TempRatioFromMachAndGamma()
function TempRatioFromMachAndGamma (in m, in gamma)
Form
 tR = TempRatioFromMachAndGamma( cP, gamma )
Inputs
 m          (1,n)   Specific heat
 gamma      (1,1)   Gamma
Outputs
 tR         (1,n)   Temperature ratio
Reference: Mattingly, "Elements of Gas Turbine Propulsion," McGraw-Hill, 1996.
References and(), Demo(), Gamma(), Plot2D(), and TempRatioFromMachAndGamma().
Referenced by TempRatioFromMachAndGamma().
TempRatioFromPressure()
function TempRatioFromPressure (in pi, in eta, in gamma)
Form
 tau = TempRatioFromPressure( pi, eta, gamma )
Inputs
 pi         (1,n)   Pressure ratio
 eta        (1,n)   Efficiency
 gamma      (1,n)   Gamma
Outputs
 tau        (1,n)  Temperature ratio
Reference: Mattingly, "Elements of Gas Turbine Propulsion," McGraw-Hill, 1996.
References Demo(), Gamma(), Pressure(), and TempRatioFromPressure().
Referenced by TempRatioFromPressure().
Theta0()
function Theta0 (in t0, in machNo, in units)
Form
 theta0 = Theta0( gamma, t0, machNo, units )
Inputs
 gamma           (1,n)   Burner temperature at sea level static
 t0              (1,n)   Temperature
 machNo          (1,m)   Mach number
 units           (1,:)   'mks' or 'eng'
Outputs
 theta0          (n,m)   Dimensionless total temperature
Reference: Mattingly, "Elements of Gas Turbine Propulsion," McGraw-Hill, 1996, p. 479.
References Demo().
Referenced by Throttle().
Throttle()
function Throttle (in tT4SLS, in t0, in machNo, in units)
 and the burner value at sea level static conditions.
Form
 tT4 = Throttle( tT4SLS, throttleRatio, t0, machNo, units )
Inputs
 tT4SLS          (1,1)  Burner temperature at sea level static
 t0              (1,1) Ambient temperature
 m0              (1,1) Mach number
 units           (1,1) Unit type
Outputs
 tT4             (1,1)   Burner temperature
References and(), Demo(), length(), Plot2D(), StdAtm(), Theta0(), Throttle(), and Unit().
Referenced by ACPlot(), ACPointMassControl(), AeroD(), Airship_KLon(), AirshipSim(), CreateMVSSetupFileEntries(), EngineTable(), F16Actuator(), LandingControl(), LandingControlBilinear(), LandingControlGravityTurn(), MixedFlowTurbofan(), MixedFlowTurbofanProfile(), RHS2DAnglePolarOrbit(), RHS2DPolarOrbit(), RHSFlatEarthSet(), Simulate2DApproach(), and Throttle().
ThrustConstant()
function ThrustConstant (in ignoredArg, in ignoredArg, in d)
 Returns constant thrust and specific fuel consumption.
Form
 [thrust,fSp] = ThrustConstant( ~, ~, d )
Inputs
 x     (6,1) State vector (unused)
 t     (1,1) Time (unused)
 d     (.)   Data structure
             .thrust   (1,1) Engine thrust (N)
             .fSp      (1,1) Specific fuel consumption (kg/Ns)
Outputs
 thrust (1,1) Thrust (N)
 fSp     (1,1) Specific fuel consumption (kg/Ns)
References and(), Constant(), ThrustConstant(), and vector().
Referenced by ThrustConstant().
ThrustPropeller()
function ThrustPropeller (in type, in varargin)
 There are two options, 'power' or 'thrust'. With power the thrust is
 t = propeller efficiency*power/velocity
 If it is thrust the it is
 thrust = cT*rho*N^2*d^4
 where the constants are defined below.
 Type ThrustPropeller for a demo.
Form
 thrust = ThrustPropeller( 'thrust', rho, cT, N, d )
 thrust = ThrustPropeller( 'power', etaP, v, p )
Inputs
 type            (1,:) 'power' or 'thrust'
 rho             (1,:) Density (kg/m^2)
 cT              (1,1) Thrust coefficient
 N               (1,1) RPS
 d               (1,1) Propeller diameter (m)
 etaP            (1,1) Propulsive efficiency
 v               (1,:) Velocity (m/s
 p               (1,1) Power (W)
Outputs
 thrust          (1,:) Thrust (N)
Reference: Mair, W. and D. L. Birdsall, "Aircraft Performance," Cambridge, p.97.
References and(), Demo(), and ThrustPropeller().
Referenced by ThrustPropeller().
ThrustTurbofan()
function ThrustTurbofan (in f0, in k1, in k2, in v)
 f = f0*(1 - k1*v + k2*v^2)
 Type ThrustTurbofan for a demo of the Rolls-Royce RB211.
 Any units for static thrust can be used.
Form
 f = ThrustTurbofan( f0, k1, k2, v )
Inputs
 f0              (1,1) Static thrust
 k1              (1,1) Coefficient (s/m)
 k2              (1,1) Coefficient (s/m)^2
 v               (1,:) Velocity (m/s)
Outputs
 f               (1,:) Thrust (same units as f0)
Reference: Mair, W. and D. L. Birdsall, "Aircraft Performance," Cambridge, p.83.
References and(), Demo(), Plot2D(), ThrustTurbofan(), and Turbofan().
Referenced by ThrustTurbofan().
TotalPressureAndTemperature()
function TotalPressureAndTemperature (in p, in t, in gamma, in m)
Computes the total pressure and temperature given a pressure and temperature of a gas flow at Mach number m.
Type TotalPressureAndTemperature for a demo at 10 km altitude.
Form
 [p0, t0] = TotalPressureAndTemperature( p, t, gamma, m )
Inputs
 p       (1,1)   Pressure
 t       (1,1)   Temperature
 gamma   (1,1)   Ratio of specific heats
 m       (1,:)   Mach number
Outputs
 p0      (1,:)   Total pressure
 t0      (1,:)   Total temperature
Reference: Benson, T. J., "An Interactive Educational Tool for Turbojet Engines," May 1995, NASA Lewis Research Center
References and(), AtmGamma(), Demo(), Plot2D(), Pressure(), StdAtm(), and TotalPressureAndTemperature().
Referenced by TotalPressureAndTemperature().
Trajectory()
function Trajectory (in x, in ignoredArg, in segment, in setPoint, in distance, in dT, in time)
Form
 [segment, setPoint, distance, time] = Trajectory( x, t, segment,
 setPoint, distance, dT, time )
Inputs
 x         (6,1) State
 t         (1,1) Time (s)
 segment   (1,1) Segment number
 setPoint  (.)   Data structure
                 .v         (1,1) Velocity (m/s)
                 .h             (1,1) Altitude (m)
                 .d             (1,1) Distance (m)
                 .psi        (1,1) Heading (rad)
                 .transition    {:}   Transition type
                 .phi        (1,1) Bank angle (rad)
                 .gamma      (1,1) Flight path angle (rad)
 distance  (1,1) Distance since start of segment
 time      (1,1) Time since start of segment
Outputs
 segment   (1,1) Segment number
 setPoint  (.)   Data structure
 distance  (1,1) Distance since start of segment
 time      (1,1) Time since start of segment
References Altitude(), and set().
Referenced by ApolloTrajectory(), CWSimAndPlot(), EarthEscape(), EarthMoonRotFrame(), GlideSlope(), HelioToBPlane(), ImpulsiveLPManeuver(), ImpulsiveManeuver(), L2OrbitSim(), Lissajous(), LunarTrajectoryControl(), NavObservables(), OptimalLunarLanding(), OrbTrack(), OrbTrackECI3D(), PlanarHelioOptimal(), PlanetTrajectoryPlot(), Plot2DTrajectory(), Plot3DOrbit(), Plot3DTrajectory(), PlotEMTraj(), PlotSEMTraj(), PlotXYTrajectory(), PlotZermelo(), SafeGuidanceSimPlots(), SecondOrderGuidance(), Simulate2DApproach(), Simulate2DLanding(), and SLPLTrajectory().
Trans3DMF()
function Trans3DMF (in m, in g, in r)
r is optional.
Form
 g = Trans3DMF( m, g, r )
Inputs
 m           (3,3) Transformation matrix.
 g           (.)   Data structure
                   .m    (:)   Data structure for meshes
                               .v                  (:,3) Vertices
                               .f                  (:,:) Faces
                               .ambientCoefficient (1,1)
                               .diffuseColor       (3,1)
                               .specularColor      (3,1)
                               .specularControl    (1,1)
                               .transparencyColor  (3,1)
                   .name (1,:) Name
 r           (3,1) Position vector
Outputs
 g           (.) Transformed data structure
References DupVect(), isempty(), length(), and vector().
Referenced by DrawAC().
Turbofan()
function Turbofan (in m, in d, in q)
Type Turbofan for a demo.
The numbers and letters in the code refer to
a ambient
0 stagnation
1 inlet to diffuser
2 inlet to compressor
3 inlet to the burner
4 inlet to the turbine
5 outlet from the turbine and inlet to the afterburner
6 inlet to the nozzle
7 outlet from the nozzle
8 outlet from the fan
Form
[t, tSFC, tS, temp] = Turbofan(m, d, q)
Inputs
 m  (n,1)       Mach number
 d   (.)        Data structure for engine
                 .gamma     (1,1) Specific heat ratio of air
                 .gamma1    (1,1) Specific heat ratio of combustion gas
                 .cP        (1,1) Specific heat of air
                 .cP1       (1,1) Specific heat of combustion gas
                 .etaD      (1,1) Diffusor efficiency
                 .etaF      (1,1) Fan efficiency
                 .etaC      (1,1) Compressor efficiency
                 .etaN      (1,1) Nozzle efficiency
                 .beta      (1,1) Bypass ratio
                 .mDiffusor (1,1) Mach number at the diffusor exit
                 .qR        (1,1) Gas constant of fuel
                 .t04       (1,1) Combustor exit temperature deg-K
                 .p08OP0A   (1,1) Fan pressure ratio
                 .p04OP03   (1,1) Pressure ratio across the burner
                 .p06OP05   (1,1) Pressure ratio across the afterburner
                 .aInlet    (1,1) Inlet area (m^2)
                 .mDiffusor (1,1) Diffusor Mach number
 q    (.)       Standard atmosphere
Outputs
 t       (m,n)       Thrust (N)
 tSFC    (m,n)       Specific fuel consumption (kg/s/N)
 tS      (m,n)       Specific thrust (N/kg/s)
 temp    (m,n,10)    Temperatures
Reference: Hill, P. G. and Peterson, C. R. "Mechanics and Thermodynamics of Propulsion," Addison Wesley, 1970.
References and(), DefaultData(), Demo(), length(), Pressure(), StdAtm(), Turbofan(), and zeros().
Referenced by JetEngineAnalysis(), JetEnginePerformance(), ThrustTurbofan(), Turbofan(), Turbofanramjet(), TurboRamjetSim(), and TurboRamRocket().
Turbofanramjet()
function Turbofanramjet (in m, in d, in p)
 Uses Ramjet and Turbofan. An earlier version used a table lookup.
 It matches the ramjet thrust and turbfan thrust at machTransition.
 Type Turbofanramjet for a demo.
Form
 [t, sFC] = Turbofanramjet( m, d, p )
Inputs
 m           (1,1)  Mach number
 d           (1,1)  Data structure
                    .machTransition (1,1) Transition to ramjet M
                    .ramjet         (1,1) Ramjet data structure
                    .turbofan       (1,1) Turbofan data structure
                    .aInlet         (1,1) Inlet area
 p           (1,1)  Standard atmosphere
Outputs
 t           (1,1)  Thrust (N)
 sFC         (1,1)  Specific Fuel Consumption (kg/N-s)
References and(), Demo(), isempty(), length(), PartStdAtm(), Plot2D(), Ramjet(), StdAtm(), Turbofan(), Turbofanramjet(), and zeros().
Referenced by Turbofanramjet(), TurboRamjetSim(), and TurboRamRocket().
Turbojet()
function Turbojet (in m, in d, in p)
 The default data structure has the afterburner off. The default
 fuel is kerosene.
 Type Turbojet for a demo.
 The demo is for the F135 engine.
Form
[t, iSp, tS] =  Turbojet(m, d, p)
 d = Turbojet;
Inputs
 m  (1,:)   Mach number
 d  (1,1)   Data structure for engine
         .gamma     (1,1) Specific heat ratio of air
         .cP        (1,1) Specific heat of air
         .qR        (1,1) Heating value of the fuel
         .tT4       (1,1) Temperature at station 4
         .tT7       (1,1) Temperature at station 7 (afterburner)
         .aInlet    (1,1) Inlet area (m^2)
 p   (1,1)  Standard atmosphere
Outputs
 t   (1,:)  Thrust (N)
 iSp  (1,:) Specific impulse (s)
 tS  (1,:)  Specific thrust (N/kg/s)
Reference: Kerrebrock, J.L, "Aircraft Engines and Gas Turbines", MIT Press, 1992, pp. 36-39
References and(), DefaultData(), Demo(), isempty(), length(), Plot2D(), Turbojet(), and zeros().
Referenced by JetEngineAnalysis(), JetEnginePerformance(), Turbojet(), TurboRamjet(), and TurboRamRocket().
TurbojetNoThrust()
function TurbojetNoThrust (in m, in d, in p)
 The default fuel is kerosene.
 Type TurbojetNoThrust for a demo.
Form
[pT7,pR,pRM] = TurbojetNoThrust(m, d, p)
 d = TurbojetNoThrust;
Inputs
 m  (1,:)   Mach number
 d  (1,1)   Data structure for engine
         .gamma     (1,1) Specific heat ratio of air
         .tT4       (1,1) Temperature at station 4
         .piC       (1,1) Compressor pressure ratio
 p   (1,1)  Standard atmosphere
Outputs
 p7    (1,:)    Exit pressure
 pR    (1,:) pT7/p0
 pRM   (1,:) Max of compressor or ram
 t7    (1,:) Exit temperature
Reference: Kerrebrock, J.L, "Aircraft Engines and Gas Turbines", MIT Press, 1992, pp. 36-39
References and(), DefaultData(), Demo(), isempty(), length(), Pressure(), StdAtm(), and TurbojetNoThrust().
Referenced by RDE(), and TurbojetNoThrust().
TurboRamjet()
function TurboRamjet (in m, in d, in p)
 Uses Ramjet and JetEngine. An earlier version used a table lookup. It
 matches the ramjet thrust and turbofan thrust at machTransition.
 Type TurboRamjet for a demo.
Form
 [t, iSp] = TurboRamjet( m, d, p )
Inputs
 m           (1,1)  Mach number
 d            (.)   Data structure
                     .machTransition (1,1) Transition to ramjet M
                     .ramjet         (1,1) Ramjet data structure
                     .turbojet       (1,1) Turbojet data structure
                     .aInlet         (1,1) Inlet area
 p            (.)   Standard atmosphere struct
Outputs
 t   (1,:)  Thrust (N)
 iSp  (1,:) Specific impulse (s)
 tS  (1,:)  Specific thrust (N/kg/s)
References and(), Demo(), isempty(), JetEngine(), length(), PartStdAtm(), Plot2D(), Ramjet(), RamjetKerrebrock(), StdAtm(), Turbojet(), TurboRamjet(), and zeros().
Referenced by TurboRamjet().
TurboRamRocket()
function TurboRamRocket (in m, in d, in p)
This type of engine could be used in the first stage of a two stage to orbit booster or in a single stage to orbit booster.
The mode field is
 0 Turbofan/turbojet
 1 Ramjet
 2 Rocket
You can pick the turbojet model, both Turbofan and Turbojet are compatible, but Ramjet is fixed to be Ramjet.m. The rocket engine model is the simple RocketFromUEAndT.m that computes exhaust velocity and specific impulse from the values at two pressures.
Type TurboRamRocket for a demo of an all H2 engine.
Form
[thrust, mDot, uE] = TurboRamRocket(m, h, d, s)
Inputs
 m       (1,1) Mach number
 d        (1,1) Data structure
               .mode         (1,1) Mode
               .nTurbojets   (1,1) Number of turbojets
               .nRamjets     (1,1) Number of ramjets
               .nRockets     (1,1) Number of rockets
               .turbojetFun  (1,1) Turbojet/turbofan model
               .turbojetData    (1,1) Data structure see Turbojet or Turbofan
               .ramjetData   (1,1) Data structure see Ramjet.m
               .rocketData   (1,1) Data structure see RocketFromUEAndT.m
 p       (1,1) Standard atmosphere model data structure see StdAtm.m
Outputs
 thrust  (1,1) Thrust            (N)
 mDot    (1,1) Mass flow         (kg/s)
 uE      (1,1) Exhaust velocity  (m/s)
See also
Turbojet, Turbofan, Ramjet, RocketFromUEAndT, Turbofanramjet
References and(), Demo(), length(), PartStdAtm(), Ramjet(), RocketFromUEAndT(), StdAtm(), Turbofan(), Turbofanramjet(), Turbojet(), TurboRamRocket(), and zeros().
Referenced by TurboRamRocket().
TurningRadius()
function TurningRadius (in v, in n)
 These are a function of the lift/weight ratio and the velocity.
 Type TurningRadius for a demo.
Form
 [r, omega] = TurningRadius( v, n )
Inputs
 v               (1,n) Velocity (m/s)
 n               (1,m) Lift/Weight
Outputs
 r               (m,n) Radius (m)
 omega           (m,n) Angular rate (rad/s)
Reference: Anderson, J. D., "Introduction to Flight, 3rd Edition," McGraw-Hill, 1989 p 328.
References and(), Demo(), Mesh2(), and TurningRadius().
Referenced by TurningRadius().
UFromAlphaBeta()
function UFromAlphaBeta (in alpha, in beta)
This is the velocity vector. When alpha is zero the velocity vector is along +x. When it is 90 it is along +z.
Form
 u = UFromAlphaBeta( alpha, beta )
Inputs
 alpha       (1,:) Angle of attack (rad)
 beta        (1,:) Sideslip angle (rad)
Outputs
 u           (3,:) Body vector
Reference: MAE142_Lecture13.pdf
References and(), Demo(), UFromAlphaBeta(), and vector().
Referenced by NewtonianAerodynamicsFromCAD(), NewtonianAlphaFromCAD(), NewtonianCPFromCAD(), and UFromAlphaBeta().
VBDToVBT()
function VBDToVBT (in vB, in vBDot)
 and its derivatives.
Form
 vTDot = VBDToVBT( vB, vBDot )
Inputs
 vB          (3,1) Velocity in the body frame
 vBDot       (3,1) Acceleration in the body frame
Outputs
 vTDot       (1,1) Acceleration
References and().
VStall()
function VStall (in d, in altitude)
Form
 vStall = VStall( d, altitude )
Inputs
 d              (1,1)  Data structure
                       .cLMax      (1,1) Max lift coefficient
                       .wingArea   (1,1) Wing area
                       .massDesign (1,1) mass
 altitude       (1,1)  Altitude (m)
Outputs
 vStall         (1,1)  Stall velocity
Reference: Mair, W. A. and D. L. Birdsall, "Aircraft Performance," Cambridge, p. 139.
References Altitude(), and(), Demo(), Plot2D(), StdAtm(), VStall(), and Wing().
Referenced by VStall().
VTToVB()
function VTToVB (in vT, in alpha, in beta)
Form
 vB = VTToVB( vT, alpha, beta )
Inputs
 vT          (1,1) Velocity
 alpha       (1,1) Angle of attack (rad)
 beta        (1,1) Sideslip angle (rad)
Outputs
 vB          (3,1) Velocity in the body frame
Reference: Stevens, B.L., Lewis, F.L. , Aircraft Control and Simulation, John Wiley & Sons, 1992, p. 64.
References and().
Referenced by DefaultACState().
WettedArea()
function WettedArea (in type, in d)
 For wings, fuselages and nacelles.
 Mach number and sweep ratio must be entered for wings.
Form
 sW = WettedArea( type, d )
Inputs
 type       (1,:) 'wing' 'fuselage' 'nacelle'
 d          (1,1)  Data structure
                   .d    (1,1)  Diameter
                   .s    (1,1)  Wing area
                   .l    (1,1)  Length
Outputs
 sW         (1,:)  Wetted area (m^2)
References and(), Demo(), WettedArea(), and Wing().
Referenced by ParasiticDragCoefficient(), and WettedArea().
WindFunction()
function WindFunction (in alt, in lat, in day, in check)
Form
 [mag,dir] = WindFunction( alt, lat, day, check );
Inputs
 alt        (1,M)    Altitude (km)
 lat        (1,N)    Latitude (deg)
 day         (1)     Day of the year
 check       (1)     Flag, indicates whether to check against HWM93
Outputs
 mag        (M,N)    Wind magnitude (m/s)
 dir        (M,N)    Wind direction, measured north to east (deg)
References abs(), HorizontalWind(), length(), Wind(), WindFunction(), and zeros().
Referenced by WindFunction(), and WindTrendsDemo().
WindGust()
function WindGust (in h, in u0, in sigma, in wingSpan, in f, in w)
Generates state space equations or spectral densities.
Form
 g = WindGust( h, u0, sigma, wingSpan, f, w )
Inputs
 h             (:,:)    Altitude (m)
 u0            (1,1)    Aircraft mean speed wrt air mass
 sigma         (3,1)    Standard deviation of the gust velocity
                        sigma.u
                        sigma.v
                        sigma.w
 wingSpan      (1,1)    Wing span
 f                      function to be performed
                        'spectral' spectral densities
                        'state'    state space equations for velocity
                        'accel'    state space equations for acceleration
 w             (1,:)    Frequencies at which to compute power spectral densities
Outputs
 g                      Wind gust output of type statespace
Reference: McRuer, D., Ashkenas, I., and D. Graham, Aircraft Dynamics and Automatic Control," Princeton, 1973, p 654.
References Altitude(), and(), statespace(), Wind(), and Wing().
Referenced by WindModel().
WindModel()
function WindModel (in action, in varargin)
To be used in simulation.
Form
 wind = WindModel( action, x, mET )
Inputs
 action (:) String argument specifying the action to take
 'initialize'   Initialize with data. Second input,
 x, is data structure with fields:
 .jD   Initial Julian date at start of sim
 .gustPeriod         Period at which gust model matrices are updated [sec]
 .steadyStatePeriod Period at which steady-state wind is computed [sec]
 .sigmaU            Standard deviation of gust velocity in x [m/s]
 .sigmaV                Standard deviation of gust velocity in y [m/s]
 .sigmaW                Standard deviation of gust velocity in z [m/s]
 'xdot'         Compute wind gust state derivatives.
 Second input, x, is the 5x1 wind gust
 state vector.
 'update'       Update the model and return the
 wind velocity. Remaining inputs
 for this case described below.
 x       (.)     Aircraft state data structure. The disturbance
 state vector must be a 5x1 vector for the wind
 gust states: u (1), v (2), w (2).
 mET     (1,1)   Mission-elapsed time    [sec]
Outputs
 wind    (3,1)    Velocity of wind in body frame  [m/s]
See also
: WindGust, HorizontalWind.
References and(), HorizontalWind(), Initialize(), Period(), vector(), and WindGust().
Referenced by WT_HAWTDFIGSetup(), WT_HAWTSetup(), and WT_VAWTSetup().
WindsGUI()
function WindsGUI (in action, in modifier)
Form
 WindsGUI( action, modifier );
Inputs
 action           (:)  Action to be taken by the GUI
 modifier         (:)  Accompnying data
Outputs
 none
WindsPlot()
function WindsPlot (in action, in modifier)
altitude, latitude, longitude, time.
Form
 WindsPlot( action, modifier );
Inputs
 action           (:)  Action to be taken by the GUI
 modifier         (:)  Accompanying data
Outputs
 none
WindTrendsDemo()
function WindTrendsDemo (in dataType, in makemovie)
Data obtained from the HWM93 model (see HorizontalWind.m) and the analytic model that approximates it (see WindFunction.m). Loads the mat-file winds_wc_dayvar.mat
Form
 WindTrendsDemo( type, makemovie )
Inputs
 dataType      (1)  Data type:
                     - 1   Horizontal Wind Model
                     - 2   Analytic function
                     - 3   Error
 makemovie     (1)  Flag indicating whether to make movie
Outputs
 none
References and(), HorizontalWind(), Wind(), and WindFunction().
WingAreaToTaper()
function WingAreaToTaper (in c, in s, in b, in sweep)
 s and b are for the entire wing (both sides of the fuselage).
 WingAreaToTaper( c, s, b, sweep ), with no outputs,
 will generate a picture of the wing.
Form
 [f, omegaT] = WingAreaToTaper( c, s, b, sweep )
Inputs
 c       (1,1) Root chord length (m)
 s       (1,1) Wing area (m^2)
 b       (1,1) Wing span (m)
 sweep  (1,1) Sweep angle (rad)
Outputs
 f       (1,1) Taper
 omegaT  (1,1) Trailing edge angle (rad)
References and(), Demo(), get(), length(), NewFig(), set(), Sweep(), TitleS(), Wing(), WingAreaToTaper(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by WingAreaToTaper().
WingFromParameters()
function WingFromParameters (in c, in s, in b, in sweep, in t)
 Produces a symmetric airfoil.
Form
 [v, f] = WingFromParameters( c, s, b, sweep, t )
Inputs
 c       (1,1) Root chord length (m)
 s       (1,1) Wing area (m^2)
 b       (1,1) Wing span (m)
 sweep    (1,1) Sweep angle (rad)
 t       (1,1) Thickness ratio
Outputs
 v       (:,3) Vertices
 f       (:,3) Faces
References and(), Demo(), length(), NewFig(), Sweep(), Wing(), WingFromParameters(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by WingFromParameters().
WingSizingForPullUp()
function WingSizingForPullUp (in pullUp, in m, in h, in cLAlpha, in alpha, in thrust, in mass, in sweep)
 Type WingSizingForPullUp for a demo
Form
 s = WingSizingForPullUp( pullUp, m, h, cLAlpha, alpha, thrust, mass, sweep )
Inputs
 pullUp        (1,1)    Pull up (g)
 m             (1,1)    Mach number
 cLAlpha       (1,1)    Lift coefficient for alpha (1/rad)
 thrust        (1,1)    Engine thrust (N)
 alpha         (1,1)    Angle of attack (rad)
 mass          (1,1)    Mass (kg)
 sweep         (1,1)    Sweep angle (rad)
Outputs
 s             (1,1)    Wing area (m^2)
References Demo(), StdAtm(), Sweep(), Wing(), and WingSizingForPullUp().
Referenced by WingSizingForPullUp().
WriteEngineData()
function WriteEngineData (in fileName, in d)
 The file is compatible with the DSim2 function sc_ac_engine.cc/h
Form
 WriteEngineData( fileName, d )
Inputs
 fileName    (1,:)  Filename
 d           (1,1)  Data structure with thrust and sFC data
                    .m        (1,n) Mach number
                    .h        (1,m) Altitude (m)
                    .thrust   (m,n) Thrust (N)
                    .sFC      (m,n) Specific fuel consumption  (kg/N-s)
Outputs
 None
References Altitude(), and(), Demo(), length(), and WriteEngineData().
Referenced by WriteEngineData().