PSS MATLAB Toolboxes: LunarMissions Functions
LunarMissions Functions
LunarMissions Module
The LunarMissions module functions are organized into subfolders.
Directories
directory Gateway
Lunar Gateway functions including disturbances and control .
directory LunarCoord
Coordinate transformations including three-body frames. .
directory LunarEnvironment
Topography and local environment .
directory LunarEnvironment
Topography and local environment .
directory LunarEphemeris
Elements and rotations that are a function of time .
directory LunarLanding
Landing dynamics and control .
directory LunarMission
Lunar mission analysis .
directory LunarRHS
Orbital dynamics functions .
Description
Functions
function ApolloGuidanceCoordinates (in xLF, in rTLF)
Computes Apollo guidance coordinates.
function ApolloLunarDescentGuidance (in x, in t, in d)
Apollo lunar module landing guidance.
function ApolloTrajectory (in rTG, in vTG, in aTG, in rG, in vG, in t)
Generates an Apollo lunar landing trajectory.
function BarycenterEarthMoon (in jD)
Computes the ECI position of the Earth-Moon Barycenter.
function CommandListProcessing (in jD0, in cList, in kCurrent, in jD)
Processes command lists.
function CubeSatLunarEnvironment (in x, in t, in d)
Lunar environment calculations for the CubeSat dynamical model.
function EarthMoon (in r, in jD, in scale, in rMoon)
Plot an orbit track in the Earth/Moon System.
function EarthMoonRotFrame (in r, in jD, in scale, in lagrange, in lunarCone)
Plot an orbit track in the Earth/Moon Rotating System.
function EarthMoonSystemConstants ()
Specifies Earth-Moon system constants.
function ECIToEarthMoonRot (in jD)
Convert ECI to Earth Moon rotating coordinates about the barycenter.
function EMBToEMBND (in r, in v)
Scale EMB system to be non-dimensional.
function ForceSimple (in d)
Simple thruster force model for orbit simulations.
function FThrustLander (in massFuel, in d)
Returns thrust and exhaust velocity for a rocket engine.
function FuelMassFromAccel (in accel, in dT, in massDry, in uE)
Computes the fuel mass to achieve the desired acceleration vector.
function GravityHelio (in r, in jD, in rP, in mu, in iD, in d)
Calculate the heliocentric gravity for the position and date.
function LandingConst2D (in x, in d)
Equality constraints for the landing for a 2D flat planet problem.
function LandingConst3D (in x, in d)
Equality constraints for the landing for a 2D flat planet problem.
function LandingCost2D (in x, in ignoredArg)
Cost for the landing for a 2D flat planet problem.
function LandingCost3D (in x, in d)
Cost for the landing for a 3D planet problem.
function LandingLegsCAD (in varargin)
Generates a CAD component for a lunar module first stage legs.
function LFToECI (in xLF, in jD)
Lunar fixed to ECI transformation.
function LoadLP150Q (in fileName)
Load the LP150Q Lunar gravity model.
function LoadLunarTopography (in nH)
Reads in the Clementine data.
function LoadSGM150 (in fileName)
Load the SGM150 Lunar gravity model.
function LunarAngle (in nH, in lat, in lon, in azimuth, in s, in c, in n)
Computes the angle needed to see over lunar terrain.
function LunarLandingControl (in x, in t, in dRHS, in d)
Spacecraft control during landing.
function LunarLandingTargetState (in lat, in lon, in alt, in f)
Lunar landing target state.
function LunarMissionControl (in action, in jD, in dC, in dSim, in meas, in cList)
Implements a lunar mission control system.
function LunarOrbitInsertion (in hLunarOrbit, in dR, in dV, in mI, in uE, in thrust)
Computes parameters for a lunar orbit insertion.
function LunarPolarOrbit (in a, in e, in jD)
Computes a polar lunar orbit.
function LunarProfile (in nH, in lambda, in theta, in s, in c)
Draw a lunar profile given lambda and theta.
function LunarRelativeState (in x, in jD, in rTarget)
Position and velocity relative to the target.
function LunarTarget (in x, in jD, in downrange)
Lunar surface landing target.
function LunarTargeting (in date, in el0, in rP, in inc, in fIf, in simJDP, in opts)
Generate transfer orbit elements for a lunar mission (fmincon).
function LunarVisibility (in lat, in lon, in jD0, in r, in t, in nH)
Computes visibility of a satellite in lunar orbit.
function MoonECIElements ()
Computes the moon ECI elements.
function MoonRot (in jD, in type)
Computes the matrix that transforms from ECI to selenographic axes.
function NoForce (in varargin)
Thruster force model producing zero force.
function OrbitStateMatrices (in x, in xF, in dT, in d)
Generate the orbit state matrices.
function PlotEMTraj (in r, in frame, in jD)
Plot a trajectory in the Earth-Moon system.
function PlotLunarOrbit (in rECI, in jD, in uSun, in thrust, in magF)
Plot a 3D orbit around the moon.
function PlotSEMTraj (in r, in frame, in jD)
Plot an orbit track in the Sun/Earth-Moon Rotating System.
function PropagateState (in x, in beta, in dT, in d)
Propagate the 2D state for the landing problem.
function PropagateState3D (in x, in dT, in d)
Propagate the 3D state for the landing problem.
function RHSLunarLander (in x, in t, in d)
Spacecraft attitude and orbit dynamics with a disturbance function.
function RHSLunarMission (in x, in t, in d)
Right hand side for orbit and attitude dynamics for a lunar mission simulation.
function RHSLunarOrbit (in x, in t, in d)
Right hand side for a lunar mission simulation with only orbit dynamics.
function RHSPlanet3D (in x, in ignoredArg, in d)
Cartesian orbital equations in a planet fixed (rotating) frame.
function RHSPlanet3DToAB (in x, in d, in dT)
This function computes the matrices a and b for dx/dt = a*x + b*u .
function RHSRVPlanetFixed (in x, in t, in d)
Right hand side for translational motion in the planet fixed frame.
function RHSSGCMG (in x, in ignoredArg, in d)
Computes the right hand side for single gimbal CMGs.
function RHSTrajectory (in x, in t, in d)
Right-Hand-Side function for solar system object trajectories with moon.
function RSHMoon (in nH, in lambda, in theta, in s, in c)
Generates a topographic map of the moon using spherical harmonics.
function SecondOrderGuidance (in action, in x, in d)
Implements a 2nd order guidance law.
function SecondOrderGuidance3D (in action, in x, in d)
Implements a 2nd order guidance law in 3 dimensions.
function SEMGravAcc (in rSEM)
Computes the acceleration due to the Sun and the Earth/Moon.
function SEMIToSEMR (in jD, in rSEMI, in vSEMI)
Transform heliocentric frame to Sun-Earth/Moon barycentered rotating frame.
function SEMRToSEMI (in jD, in rSEMR, in vSEMR)
Transform from Sun-Earth/Moon rotating to inertial frame.
function SEMToSEMND (in r, in v)
Scale state in SEM system (rotating or inertial) to be non-dimensional.
function Simulate2DLanding (in t, in beta, in d, in name)
Simulate the 2D landing problem and generate plots.
function Simulate3DLanding (in dT, in d, in name)
Simulate a 3D landing and generate plots.
function SunEarthMoonSystemConstants ()
Specifies Sun-Earth-Moon system constants.
function TransformECIToEMBR (in jD, in rECI, in vECI)
Transform ECI pos.
function TransformECIToSEMR (in jD, in rECI, in vECI)
Transform ECI pos.
function TransformEMBRToECI (in jD, in rEMBR, in vEMBR)
Transform pos.
function TransformSEMRToECI (in jD, in rSEMR, in vSEMR)
Transform Sun-Earth-Moon rotating (SEMR) state to ECI frame.
function TransformSEMRToHelio (in jD, in rSEMR, in vSEMR)
Transform Sun-Earth-Moon rotating (SEMR) state to the heliocentric frame.
function UMinGG (in inr)
Vector from ECI to body that minimizes the gravity gradient torque.
Function Documentation
ApolloGuidanceCoordinates()
function ApolloGuidanceCoordinates (in xLF, in rTLF)
The origin coincides continuously with the current landing site (the frame rotates with the moon); the XG-axis is vertical; the ZG-axis lies in, or near, the plane containing the LM and the landing site and points forward; and the YG-axis completes the right-hand triad.
Type ApolloGuidanceCoordinates for a demo.
Form
 [rG,vG] = ApolloGuidanceCoordinates( xLF, rTLF )
Inputs
 xLF   (6,1)   State vector
 rTLF   (3,1)   Target position
Outputs
 rG    (3,1)   Position in guidance coordinates
 vG    (3,1)   Velocity in guidance coordinates
Reference: Klumpp, A. R. "Apollo Guidance Navigation and Control," MIT Charles Stark Draper Laboratory, June 1971, R-695.
References and(), ApolloGuidanceCoordinates(), Constant(), Cross(), Demo(), DispWithTitle(), Mag(), Unit(), and vector().
Referenced by ApolloGuidanceCoordinates().
ApolloLunarDescentGuidance()
function ApolloLunarDescentGuidance (in x, in t, in d)
If no inputs or outputs are specified it will simulate a lunar landing using the guidance system. Three phases are implemented:
P63 Braking phase P64 Approach phase P66 Terminal descent phase The land flag is used in P66 to tell it to land.
x is normal to the lunar surface and z is downrange
Form
 [aCG, d] = ApolloLunarDescentGuidance( x, t, d )
Inputs
 x   (6,1)    State vector [rCG;vCG]
 t   (1,1)    Time (sec)
 d   (.)      Data structure
Outputs
 a  (3,1)   Command acceleration (m/sec^2)
 d   (.)     Data structure
Reference: Klumpp, A. R. "Apollo Lunar Descent Guidance," Automatica, Vol. 10, pp. 133-146, Pergamon Press, 1974.
References abs(), and(), ApolloLunarDescentGuidance(), Constant(), Demo(), Limit(), vector(), and zeros().
Referenced by ApolloLunarDescentGuidance().
ApolloTrajectory()
function ApolloTrajectory (in rTG, in vTG, in aTG, in rG, in vG, in t)
Type ApolloTrajectory for a demo.
Form
 [r, v, a] = ApolloTrajectory( rTG, vTG, aTG, rG, vG, t )
Inputs
 rTG   (3,1)    R target (m)
 vTG   (3,1)    V target (m/s)
 aG    (3,1)    Acceleration target(m/s^2)
 rTG   (3,1)    R start (m)
 vTG   (3,1)    V start (m/s)
 t     (1,:)    Time (s)
Outputs
 r     (3,:)   Position (m)
 v     (3,:)   Velocity (m/s)
 a     (3,:)   Acceleration (m/s^2)
Reference: Klumpp, A. R. "Apollo Lunar Descent Guidance," Automatica, Vol. 10, pp. 133-146, Pergamon Press, 1974.
References Altitude(), and(), ApolloTrajectory(), Constant(), Demo(), length(), Plot2D(), Trajectory(), and zeros().
Referenced by ApolloTrajectory().
BarycenterEarthMoon()
function BarycenterEarthMoon (in jD)
 Uses MoonV1 for ephemeris and Constant to look up the gravitational
 parameters.
Form
 b = BarycenterEarthMoon( jD )
Inputs
 jD             (1,:)      Julian date (days)
Outputs
 b              (3,:)      Barycenter
References and(), BarycenterEarthMoon(), Constant(), Demo(), JD2000(), length(), MoonV1(), and Plot3D().
Referenced by BarycenterEarthMoon().
CommandListProcessing()
function CommandListProcessing (in jD0, in cList, in kCurrent, in jD)
The command list cell array format is {time command data} where data is a data structure for that command. The command list rows should be in order of Julian date. You can also use +sec instead of jD in which case the time is +sec after the previous command. For example, +6 indicates 6 seconds after the previous command. If the first command is +sec then it is +sec from the time passed on initialization.
Type CommandListProcessing for a demo.
Form
kCurrent = CommandListProcessing(jD0, cList, kCurrent, jD)
Inputs
 jD0       (1,1)    Base Julian date before any commands
 cList     {:,3} Command list {time tag, string description, data structure}
 kCurrent  (1,1) Current command
 jD        (1,1) Current Julian date
Outputs
 kCurrent  (1,1) Current command
CubeSatLunarEnvironment()
function CubeSatLunarEnvironment (in x, in t, in d)
Computes sun location with SunV1 and accounts for eclipses from the Earth and the Moon via Eclipse. All environment constants including gravity are defined here.
Form
 e = CubeSatLunarEnvironment             % data structure
 e = CubeSatLunarEnvironment( x, t, d )
Inputs
 x        (14,1)    [r;v;q;w;b]
 t         (1,1)    Time, sec
 d          (.)     Data structure
                    .jD0          Julian date of epoch
                    .surfData (.) optional; empty to skip optical calcs
                    .gravity  (.)
                         .center  Index of gravity center
Outputs
 env        (.)     Environmental data
                    .r            ECI position (km)
                    .v            ECI velocity (km/s)
                    .q            ECI to body quaternion
                    .mu           Gravitational constant (km3/s2)
                    .radiusPlanet Radius of the center planet (km)
                    .rho          Distance from the Moon (km)
                    .radiation    Planetary radiation W/m2
                    .albedo       Planet bond albedo fraction
                    .uSun         Sun unit vector (ECI)
                    .rSun         Sun distance (km)
                    .solarFlux    Solar flux at position (W/m2)
                    .nEcl         Eclipse fraction (source intensity, 0-1)
                    .accelGrav    Acceleration due to gravity
                    .rMoon        Moon position
                    .vMoon        Moon velocity
See also
SunV1, Eclipse, AtmDens2, AtmJ70, BDipole
References and(), APlanet(), AtmDens2(), AtmJ70(), BDipole(), CubeSatAttitude(), CubeSatLunarEnvironment(), Eclipse(), isempty(), Mag(), MoonRot(), PlanetPosJPL(), quaternion(), SunV1(), Unit(), and vector().
Referenced by CubeSatLunarEnvironment(), and RHSLunarMission().
EarthMoon()
function EarthMoon (in r, in jD, in scale, in rMoon)
The plots are in the ECI frame. Has a built-in demo for an orbit with an apogee of 400,000 km, a perigee of 7000 km, and a duration of 5 days.
 Forms:
 EarthMoon( r, jD, scale, rMoon )
 EarthMoon( elements, jD, scale, rMoon )
Inputs
 r                (3,:) ECI position vectors (km) -or-
                  (1,6) elements
 jD               (:)   Julian dates
 scale            (1,2) Planet scale (optional, default is [1 1])
 rMoon            (3,:) Moon position
Outputs
 none
See also
MoonV1, MoonEl.
References and(), Axis3D(), EarthMoon(), Equal(), JD2000(), length(), Map(), MoonEl(), MoonV1(), NewFig(), RPRA2AE(), RVFromKepler(), set(), TimeLabl(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by EarthMoon(), and LunarTargeting().
EarthMoonRotFrame()
function EarthMoonRotFrame (in r, in jD, in scale, in lagrange, in lunarCone)
The input vectors are in the ECI frame. Has a built-in demo for an orbit
with an apogee of 400,000 km, a perigee of 7000 km, and a duration of 5 days.
 Forms:
 EarthMoonRotFrame( r, jD, scale, lagrange, lunarCone )
Inputs
 r                (3,:) ECI position vectors (km) or
                  (1,6) elements
 jD               (:)   Julian dates
 scale            (1,2) Planet scale (optional, default is [1 1])
 lagrange         (1,1) If entered draw lagrange points
 lunarCone        (1,3) [lat, lon, angle]
Outputs
 none
References and(), Axis3D(), Cone(), Constant(), Cross(), EarthMoonRotFrame(), Equal(), JD2000(), LagrangePointsL1ToL5(), LatLonToR(), Map(), MoonEl(), MoonV1(), NewFig(), RPRA2AE(), RVOrbGen(), set(), Trajectory(), Unit(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by EarthMoonRotFrame().
EarthMoonSystemConstants()
function EarthMoonSystemConstants ()
Form
 d = EarthMoonSystemConstants()
Inputs
 none
Outputs
 d       (.)     Data structure output with system constants and fields:
                   .system   ''    Name of system - 'EM'
                   .muMoon   (1,1) Moon gravity constant (km^3/sec^2)
                   .muEarth  (1,1) Earth gravity constant
                   .mu       (1,1) Non-dimensional mass parameter
                   .L        (1,1) Length unit (Earth-moon) (km)
                   .T        (1,1) Time unit (lunar period) (s)
                   .Re       (1,1) Radius earth (km)
                   .Rm       (1,1) Radius moon (km)
                   .xL1      (1,1) L1 distance (nd)
                   .xL2      (1,1) L2 distance (nd)
References and(), EarthMoonSystemConstants(), get(), and length().
Referenced by EarthMoonSystemConstants(), and PlotEMTraj().
ECIToEarthMoonRot()
function ECIToEarthMoonRot (in jD)
 The coordinate frame is +x pointing at the moon along
 the earth-moon line. +z normal to the earth moon plane
 and +y completing the set. Uses MoonV1. Computes the plane
 by looking at the moon vector at jD(k) and then 1 day later.
 Type
 ECIToEarthMoonRot
 for a demo
 Since version 10.
Form
 m = ECIToEarthMoonRot( jD )
Inputs
 jD             (1,:)      Julian date (days)
Outputs
 m              {:}        Rotation matrix
 z              (3,:)      Rotation axis
References and(), ECIToEarthMoonRot(), MoonV1(), set(), and vector().
Referenced by ECIToEarthMoonRot().
EMBToEMBND()
function EMBToEMBND (in r, in v)
Scale position and velocity in EMB system (rotating or inertial) by distance and velocity units to make non-dimensional
Form
 [rND,vND] = EMBToEMBND( r, v )
Inputs
 r            (3,:)       Position vector in EMBR frame
 v            (3,:)       Velocity vector in EMBR frame
Outputs
 rND           (3,:)       Position vector in ECI frame
 vND           (3,:)       Velocity vector in ECI frame
References and(), Constant(), EMBToEMBND(), and vector().
Referenced by EMBToEMBND().
ForceSimple()
function ForceSimple (in d)
Models the force for a thruster using a direction vector and a scalar magnitude.
Form
 d = ForceSimple;      % default data structure
 f = ForceSimple( d )
Inputs
 d         (.)   Data structure
                 .uThrustECI (3,1)  Thrust unit vector in the ECI frame
                 .thrustMag  (1,1) Thrust magnitude (N)
Outputs
 f         (3,1) ECI force vector (N)
References and(), DefaultDataStructure(), ForceSimple(), scalar(), and vector().
Referenced by ForceSimple().
FThrustLander()
function FThrustLander (in massFuel, in d)
Outputs thrust aligned with the specified vector. The thrust is set to zero once the fuel mass is at or below zero.
Form
 [thrust, uE] = FThrustLander( massFuel, d )
Inputs
 massFuel (1,1) Mass of fuel (kg)
 d        (.)   Data structure
                .thrust  (1,1) Thrust magnitude (N)
                .uE      (1,1) Exhaust velocity (m/s)
                .uThrust (3,1) Thrust unit vector
Outputs
 thrust (3,1)   Thrust vector (N)
 uE      (1,1) Exhaust velocity (m/s)
References and(), FThrustLander(), set(), and vector().
Referenced by FThrustLander(), and RHSRVPlanetFixed().
FuelMassFromAccel()
function FuelMassFromAccel (in accel, in dT, in massDry, in uE)
Type FuelMassFromAccel for a demo with a constant acceleration.
Form
 massFuel = FuelMassFromAccel( accel, dT, massDry, uE )
Inputs
 accel      (1,:)  Acceleration vector
 dT        (1,:)  Time vector
 massDry   (1,1)  Dry mass
 uE        (1,1)  Exhaust velocity
Outputs
 massFuel  (1,1)  Fuel mass (kg)
References Demo(), FuelMassFromAccel(), length(), TimeLabl(), vector(), and zeros().
Referenced by FuelMassFromAccel().
GravityHelio()
function GravityHelio (in r, in jD, in rP, in mu, in iD, in d)
Julian date is only used if lunar gravitational harmonics are used. If the field, sphHarmMoon, is not empty, it uses the moon harmonics.
Form
 a = GravityHelio( r, jD, rP, mu, iD, d )
Inputs
 r       (3,1)   Heliocentric position (km)
 jD      (1,1)   Julian date (days)
 rP      (3,:)   Heliocentric planet locations (km)
 mu      (1,:)   Gravitational constants (km^3/s^2)
 iD      (1,:)   JPL planet ids
 d       (.)     Data structure
                     .muSun        (1,1)   Sun gravity constants
                     .sphHarmMoon  (.)     Data structure for the moon harmonics
                     .moonID       (1,1)   The index for the moon id in iD
Outputs
 a       (3,:)   ECI force vector (N)
See also
APlanet, AGravityC, MoonRot
References AGravityC(), and(), APlanet(), Constant(), GravityHelio(), isempty(), length(), Mag(), MoonRot(), and vector().
Referenced by GravityHelio().
LandingConst2D()
function LandingConst2D (in x, in d)
The constraint is the terminal altitude and velocities. They must be zero. The function integrates the trajectory to find the values.
Form
 [cIn, cEq, s, t] = LandingConst2D( x, d )
Inputs
 x       (:,1)   [beta;dT]
 d        (.)    Data structure describing spacecraft model
                 .hFinal (1,1) Final altitude
                 .a      (1,1) Acceleration
                 .g      (1,1) Gravity
                 .x      (4,1) Initial condition
                 .n      (1,1) Number of segments
Outputs
 cIn    (1,1)   Inequality contraints, empty
 cEq    (3,1)   Equality constraints, [altitude;x velocity;y velocity]
 s      (4,1)   Final state
 t      (1,:)   Corresponding times
See also
: RHSPlanetTakeoff
References and(), LandingConst2D(), RHSPlanetTakeoff(), RK4(), and zeros().
Referenced by LandingConst2D(), and OptimalLunarLanding().
LandingConst3D()
function LandingConst3D (in x, in d)
The constraint is the terminal altitude and velocities. They must be zero. The function integrates the trajectory to find the values.
Form
 [cIn, cEq, s, t] = LandingConst3D( x, d )
Inputs
 x       (:,1)   [beta;alpha;thrust;dT]
 d        (.)    Data structure describing spacecraft model
                 .timeOpt (1,1) Variable dT if true, otherwise constant
Outputs
 cIn    (1,1)   Inequality contraints, empty
 cEq    (5,1)   Equality constraints, [altitude;y;x velocity;y velocity;z velocity]
 s      (:,1)   Final state
 t      (1,:)   Corresponding times
See also
: RHSPlanet3DPFFrame
References and(), LandingConst3D(), Mag(), RHSPlanet3D(), and RK4().
Referenced by LandingConst3D().
LandingCost2D()
function LandingCost2D (in x, in ignoredArg)
The cost is the total time for the maneuver. This is computed from the decision variable.
Form
 cost = LandingCost2D( x, ~ )
Inputs
 x       (:,1)   [beta;dT]
 d        (.)    Data structure describing spacecraft model
Outputs
 cost    (1,1)   Total time
References LandingCost2D(), and length().
Referenced by LandingCost2D(), and OptimalLunarLanding().
LandingCost3D()
function LandingCost3D (in x, in d)
The cost is the weighted sum of total time and fuel mass. This is computed from the decision variable.
Form
 cost = LandingCost3D( x, d )
Inputs
 x       (:,1)   [beta;alpha;thrust;dT]
 d        (.)    Data structure describing spacecraft model
                 .timeW (1,1)  Time weight
                 .fuelW (1,1)  Fuel weight
                 .uE    (1,1)  Exhaust velocity
Outputs
 cost    (1,1)   Time weighted with total fuel consumed
References and(), and LandingCost3D().
Referenced by LandingCost3D().
LandingLegsCAD()
function LandingLegsCAD (in varargin)
Use 'scale' to change the size of the legs. Use 'xy spacing' to adjust the distance between the legs. These legs are based on the Apollo Lunar Module.
Type LandingLegsCAD for a demo.
Form
 [v, f] = LandingLegsCAD( varargin )
Inputs
 'scale' and 'xy spacing'
Outputs
 v(:,3) Vertices
 f(:,3) Faces
 a(1,:) Area
References and(), LandingLegsCAD(), length(), and Parameter().
Referenced by LandingLegsCAD().
LFToECI()
function LFToECI (in xLF, in jD)
Form
 xECI = LFToECI(xLF,jD)
Inputs
 xLF   (6,1)    State vector [r;v] (km,km/s)
 jD    (1,1)    Julian date
Outputs
 xECI   (6,1)   State vector [r;v] (km,km/s)
References and(), Cross(), LFToECI(), MoonRot(), and vector().
Referenced by LFToECI(), and LunarTrajectoryControl().
LoadLP150Q()
function LoadLP150Q (in fileName)
The model is normalized.
Form
 gravityModel = LoadLP150Q( fileName )
Inputs
 fileName        (1,:) Filename
Outputs
 gravityModel    (.)   Data structure
                       .name (1,:) Model name
                       .mu   (1,1) Gravitational constant (km^3/sec^2)
                       .a    (1,1) Model earth radius (km)
                       .c    (n,n) Cosine coefficients
                       .s    (n,n) Sine coefficients
                       .isNormalized (1,1)  Boolean
References StringToTokens(), and zeros().
LoadLunarTopography()
function LoadLunarTopography (in nH)
 It will automatically read the file gltm2b.topo.
 If no output arguments are found it will create a file Topography.txt
 with the s and c coefficients.
Form
 [s,c] = LoadLunarTopography( nH )
Inputs
 nH            (1,1)  Highest harmonic
Outputs
 s             (:,:)  Normalized sine coefficients
 c             (:,:)  Normalized cosine coefficients
Reference: Smith, D. E., Zuber, M. T., Neumann, G. A., "Topography of the Moon from the Clementine lidar", Journal of Geophysical Research, Vol. 102, No. E1, pp. 1591-1611, January 25, 1997.
References and(), Factorl(), isempty(), length(), Limit(), LoadLunarTopography(), and zeros().
Referenced by AltitudeSH(), LoadLunarTopography(), LunarAngle(), LunarProfile(), LunarVisibility(), and RSHMoon().
LoadSGM150()
function LoadSGM150 (in fileName)
The model is normalized.
Form
 gravityModel = LoadSGM150( fileName )
Inputs
 fileName        (1,:) Filename
Outputs
 gravityModel    (1,1) Data structure
                       .name (1,:) Model name
                       .mu   (1,1) Gravitational constant (km^3/sec^2)
                       .a    (1,1) Model earth radius (km)
                       .c    (n,n) Cosine coefficients
                       .s    (n,n) Sine coefficients
                       .isNormalized  (1,1)  True
References zeros().
LunarAngle()
function LunarAngle (in nH, in lat, in lon, in azimuth, in s, in c, in n)
 You need to enter a spherical harmonic lunar topography model.
 It loads the default model from LoadLunarTopography if you don't enter
 s or c. n is the number of azimuth points so it computes the topgraphy
 for the full range of azimuths from 0 to 360 degrees.
 Type LunarAngle for a demo.
Form
 elevation = LunarAngle( nH, lat, lon, azimuth, s, c, n  )
Inputs
 nH            (1,1)  Highest harmonic
 lat           (1,1)  Latitude of the location
 lon           (1,1)  Longitude of the location
 azimuth       (1,:)  Azimuth points starting from north
 s             (:,:)  Normalized sine coefficients
 c             (:,:)  Normalized cosine coefficients
 n             (1,1)  Number of points along each azimuth
Outputs
 elevation    (1,n)  Elevation as a function of azimuth (rad)
 azimuth      (1,n)  Corresponding azimuth (rad)
References LoadLunarTopography().
LunarLandingControl()
function LunarLandingControl (in x, in t, in dRHS, in d)
This implements a spacecraft control system for landing.
Form
 d = LunarLandingControl;   % default data
 [d,dRHS] = LunarLandingControl( x, t, dRHS, d )
Inputs
 x       (20,1) State vector [r;v;q;w;m;inertia]
                          (km,km/s,-,rad/s,kg,kg-m^2)
 t       (1,1)  Time  (s)
 dRHS    (.) Data structure for the simulation. See RHSLunarLander
 d       (.)    Data structure for the controller
Outputs
 d       (.)    Data structure for the controller
 dRHS    (.) Data structure for the simulation.
References and(), Date2JD(), DefaultDataStructure(), LandingControlBilinear(), LunarLandingControl(), Mag(), PID3Axis(), PIDMIMO(), QTForm(), RHSLunarLander(), Unit(), and vector().
Referenced by LunarLandingControl().
LunarLandingTargetState()
function LunarLandingTargetState (in lat, in lon, in alt, in f)
Form
 x = LunarLandingTargetState( lat, lon, alt, f )
Inputs
 lat     (1,1)   Target latitude
 lon     (1,1)   Target longitude
 alt     (1,1)   Target altitude
 f       (1,1)   Flattening factor
Outputs
 x     (6,1)   State [r;v]
References Constant(), Cross(), Demo(), DispWithTitle(), LatLonAltToEF(), and LunarLandingTargetState().
Referenced by LunarLandingTargetState().
LunarMissionControl()
function LunarMissionControl (in action, in jD, in dC, in dSim, in meas, in cList)
The command list cell array is {time command data} where data is a data structure for that command. The command list rows should be in order of Julian date. You can also use +sec instead of jD in which case the time is +sec after the previous command. If the first command is +sec then it is +sec from the time passed on initialization.
Supported commands:
 Command                          data
 'align with a quaternion',        struct('q_target',[0;1;0;0]);...
 'lunar orbit insertion prepare',   struct('thrust',20,'massInitial',6,...
 'uE', 290*9.806,...
 'body_vector',[1;0;0],...
 'hLunarOrbit',200);...
 'align for lunar insertion',      [];...
 'start main engine',              struct('iD',1,'thrust',20)};
uE is exhaust velocity in m/s. massInitial is the mass at the start of the burn. hLunarOrbit is the altitude of the burn.
meas can be the state vector.
dC = LunarMissionControl gives the default data structure. This also opens a GUI that shows the command list and current command that is being executed.
Commands are implemented via the dSim data structure. This is compatible with RHSLunarMission.
Form
 dC = LunarMissionControl   % default data structure
 [dC, dSim] = LunarMissionControl( action, jD, dC, dSim, meas, cList )
Inputs
 action  (1,:)   'initialize', 'update', 'terminate'
 jD      (1,1)   Julian date
 dC      (.)     Controller data structure
 dSim    (.)     Simulation data structure
 meas    (.)     Measurement data structure or state vector
                 .qECIToBody (4,1) Quaternion
                 .rECI       (3,1) ECI position
                 .vECI       (3,1) ECI velocity
                 .omega      (3,1) Body rate
                 .omegaRWA   (:,1) RWA rates
 cList   {:,3}   Command list cell array
-------
Outputs
 dC      (.)     Controller data structure
 dSim    (.)     Simulation data structure
LunarOrbitInsertion()
function LunarOrbitInsertion (in hLunarOrbit, in dR, in dV, in mI, in uE, in thrust)
Computes the total velocity change, the vector direction for the burn and the duration of the burn. This always burns in the direction of the velocity error. You should approach the moon in the right direction so that the resulting orbit is achieved.
If your input is elements dR must be part of the orbit track otherwise it won't work. The moon relative position must be at the point in the orbit specified by the mean anomaly.
Type LunarOrbitInsertion for a demo.
Form
[deltaV, uECI, tBurn] = LunarOrbitInsertion(hLunarOrbit, dR, dV, mI, uE, thrust)
Inputs
 hLunarOrbit    (1,:)   Perigee altitude or lunar orbital elements
 dR          (3,1)  Relative position vector at start (km)
 dV          (3,1)  Relative velocity vector at start (km/s)
 mI          (1,1)  Initial mass (kg)
 uE          (1,1) Exhaust velocity (m/s)
 thrust      (1,1) Thrust (N)
Outputs
 deltaV  (1,1)   Velocity change (km/s)
 uECI    (3,1)   Vector for burn
 tBurn   (1,1)   Burn duration (sec)
References and(), and vector().
LunarPolarOrbit()
function LunarPolarOrbit (in a, in e, in jD)
Form
 x = LunarPolarOrbit( a, e, jD )
Inputs
 a      (1,1)   Semi-major axis
 e      (1,1)   Eccentricity
 jD (1,1)   Julian date
Outputs
 x      (6,1) [r;v] (km,km/s) ECI
References Constant(), El2RV(), LunarPolarOrbit(), MoonRot(), QForm(), U2Q(), and Unit().
Referenced by LunarPolarOrbit().
LunarProfile()
function LunarProfile (in nH, in lambda, in theta, in s, in c)
 Lambda and theta are 1-dimensional arrays.
 Type LunarProfile for a demo.
Form
 r =  LunarProfile( nH, lambda, theta, s, c )
Inputs
 nH            (1,1)  Highest harmonic
 lambda        (1,:)  Equatorial angles
 theta         (1,:)  Angles from pole
 s             (:,:)  Normalized sine coefficients
 c             (:,:)  Normalized cosine coefficients
References and(), Demo(), DupVect(), isempty(), length(), LoadLunarTopography(), LunarProfile(), PAL(), Plot2D(), SCHarm(), and zeros().
Referenced by LunarProfile().
LunarRelativeState()
function LunarRelativeState (in x, in jD, in rTarget)
Also returns latitude, longitude and altitude.
Form
 d = LunarRelativeState(x,jD,rTarget)
Inputs
 x       (20,1) State vector [r;v;..] (km,km/s)
 jD      (1,1)   Julian date
 rTarget (3,1)   Target position in the lunar frame (km)
Outputs
 d       (.)     Data structure for the output
                 .lat   (1,1) Latitude (deg)
                 .lon   (1,1) Longitude (deg)
                 .alt   (1,1) Altitude (km)
                 .r     (3,1) Relative position (km)
                 .v     (3,1) Relative velocity (km/s)
References Altitude(), and(), Cross(), EFToLatLonAlt(), LunarRelativeState(), MoonRot(), and vector().
Referenced by LunarRelativeState().
LunarTarget()
function LunarTarget (in x, in jD, in downrange)
Form
 r = LunarTarget( x, jD, downrange )
Inputs
 x         (20,1)  State vector [r;v;..] (km,km/s)
 jD        (1,1)   Julian date
 downrange (3,1)   Downrange distance
Outputs
 r         (3,1)   Landing spot in the lunar fixed frame
References LunarTarget(), MoonRot(), Unit(), and vector().
Referenced by LunarTarget().
LunarTargeting()
function LunarTargeting (in date, in el0, in rP, in inc, in fIf, in simJDP, in opts)
Uses the JPL Ephemerides for the Earth and moon. The target is the perilune altitude of the hyperbolic passage of the moon. The function propagates the resulting trajectory using ode113. It propagates to the target point. You can specify radius of perilune and orbit inclination.
This function uses Lambert to target a point on the Earth/Moon interface. The point is where the hyperbolic passage of the moon starts. This justifies the single body Lambert solution.
The spacecraft starts in any Earth orbit.
Requires fmincon in the optimization toolbox. See fmincon for the definition of the argument opts.
Type LunarTargeting for a demo.
Form
 [x0,eL,v,jD0] = LunarTargeting( date, a0, rP, inc, fIf, opts )
Inputs
 date    (1,:)  Date [yy mm dd hh mm ss] or Julian date
                of lunar encounter. "Encounter": When spacecraft reaches
                earth/moon interface.
 el0     (1,5)  Initial keplerian orbital elements [a,i,W,w,e] in km and
                radians
 rP      (1,1)  Desired perilune distance (km)
 inc     (1,1)  Desired Lunar orbit inclination (rad)
 fIf     (1,1)  The Earth/Moon gravitational interface point from the
                moon
 simJDP  (1,1)  Logical. If false, jDP is computed from Keplerian lunar
                elements. If true, jDP is computed more accurately via
                simulation. Default: False
 opts    (.)    Optimization tolerance data structure
Outputs
 x0      (1,6)  Initial state [r,v] in km and km/s
 elL     (6,1)  Final lunar keplerian orbital elements [a,i,W,w,e,M] in
                km and radians
 v       (3,2)  Initial and interface velocity in km/s
 jD0     (1,1)  Start Julian date
 jDP     (1,1)  Julian date of perilune
References abs(), and(), APlanet(), Date2JD(), Demo(), EarthMoon(), El2RV(), HasOptimizationToolbox(), isempty(), LambertTOF(), length(), LunarTargeting(), Mag(), Period(), PlanetPosJPL(), Plot3D(), RHS(), RV2El(), TimeLabl(), vector(), and zeros().
Referenced by LunarTargeting().
LunarVisibility()
function LunarVisibility (in lat, in lon, in jD0, in r, in t, in nH)
Uses the Clementine surface model. The orbit is in the inertial frame but lunar centric.
Type LunarVisibility for a demo.
Form
 kVis = LunarVisibility( lat, lon, jD0, r, t, nH )
Inputs
 lat   (1,1)    Latitude of the ground target (rad)
 lon   (1,1)    Longitude of the ground target (rad)
 jD0   (1,1)    Julian data of start (days)
 r     (3,:)    ECI frame orbit (rad)
 t     (1,:)    Times corresponding to points in r (s)
 nH    (1,1)    Number of harmonics in the surface model (72 maximum)
Outputs
 kVis   (1,:)   1 if the satellite is visible, 0 if not
See also
RSHMoon.
References Constant(), Date2JD(), Demo(), LatLonToR(), length(), LoadLunarTopography(), LunarVisibility(), Mag(), Map(), MoonRot(), NewFig(), Plot2D(), RPRA2AE(), RSHMoon(), RVOrbGen(), TimeLabl(), U2RADec(), Unit(), Watermark(), and zeros().
Referenced by LunarVisibility().
MoonECIElements()
function MoonECIElements ()
Uses the state of the moon from a single epoch to compute elements. Type MoonECIElements for a comparison with MoonV1 and MoonV2.
Form
 [el, jD] = MoonECIElements
Inputs
 None
Outputs
 el      (1,6)   [a i W w e M]
 jD      (1,1)   Epoch  of elements
Reference: JPL Horizons, https://ssd.jpl.nasa.gov/horizons.cgi (2020)
References and(), MoonECIElements(), MoonV1(), MoonV2(), Plot2D(), RV2El(), RVOrbGen(), and TimeLabl().
Referenced by MoonECIElements().
MoonRot()
function MoonRot (in jD, in type)
 mean is the default type.
 Type MoonRot for a demo.
Form
 [g, omega] = MoonRot( jD, type )
Inputs
 jD      (1,1) Julian Date
 type    (1,4) 'mean' or 'true'
Outputs
 g       (3,3) ECI To Selenographic
 omega   (3,1) ECI Polar rotation vector
References: Escobal, P. R., Methods of Orbit Determination, Krieger, pp. 413-416.
References Demo(), MoonRot(), and vector().
Referenced by CubeSatLunarEnvironment(), FEarthMoonSun(), GravityHelio(), LFToECI(), LunarPolarOrbit(), LunarRelativeState(), LunarTarget(), LunarVisibility(), MoonRot(), OpticalNavLunarLandmarkStar(), PlanetRot(), PlotLunarOrbit(), and RHSLunarOrbit().
NoForce()
function NoForce (in varargin)
Form
 [t,f] = NoForce( varargin )
Inputs
 None used.
Outputs
 t         (3,:) Body torque vector (Nm)
 f         (3,:) Body force vector (N)
References NoForce(), and vector().
Referenced by NoForce().
OrbitStateMatrices()
function OrbitStateMatrices (in x, in xF, in dT, in d)
 The matrices are ax = b
 x is the vector of decision variables or controls
 The order is [x1;x2;x3;...;xN] where each x is a vector
 xI is only used to compute the term mu/R^3. A constant xI is
 sufficient for most low-altitude landings.
 Type OrbitStateMatrices for a demo.
Form
 [a,b,xF0,aX,bX] = OrbitStateMatrices( xI, xF, dT, d )
Inputs
 x       (6,:)   States [x;y;z;vX;vY;vZ]
 xF      (6,:)   Final desired state   [x;y;z;vX;vY;vZ]
 dT      (1,1)   Delta time
 d        (.)    Data structure describing spacecraft model
                 .beta   (1,:) Thrust angle in rv plane
                 .alpha  (1,:) Thrust angle out of plane
                 .thrust (1,:) Thrust (N)
                 .accel  (1,:) 'constant' or 'free'
                 .m0     (1,1) Dry mass
                 .radius (1,1) Planet radius
Outputs
 a     (6,3*n)   Matrix multiplying the decision variables
 b     (6,1)     Right hand side
 xF0   (6,1)     Final state without control
 aX    {n}       Cell array of state transition matrices
 bX    {n}       Cell array of input matrices
References OrbitStateMatrices(), and vector().
Referenced by OrbitStateMatrices().
PlotEMTraj()
function PlotEMTraj (in r, in frame, in jD)
 Type PlotEMTraj for a demo
 Since version 11.
Form
 p = PlotEMTraj( r, frame, jD )
Inputs
 r         (3,:)   Trajectory data
 frame      (:)    Coordinate frame. May be one of the following:
                     'EMBRND'    Earth-Moon Barycenter Rotating Non-Dim.
                     'EMBR'      Earth-moon Barycenter Rotating
                     'ECI'       Earth-centered Inertial
                     'MCI'       Moon-centered Inertial
                     'MCR'       Moon-centered Rotating
 jD        (1,1)   Julian date time vector
Outputs
 None
References and(), CRTBPRHS(), Date2JD(), Demo(), Dim(), EarthMoonSystemConstants(), length(), MoonV1(), PlotEMTraj(), set(), Trajectory(), TransformEMBRToECI(), and vector().
Referenced by PlotEMTraj().
PlotLunarOrbit()
function PlotLunarOrbit (in rECI, in jD, in uSun, in thrust, in magF)
The terrain magnification factor increases the height of the terrain making it easier to see.
Type PlotLunarOrbit for a demo.
Form
 PlotLunarOrbit( rECI, jD, uSun, magF )
Inputs
 rECI    (3,:)  ECI frame orbit (km)
 jD      (1,:)  Julian date (day)
 uSun    (3,:)  Sun vector
 thrust  (3,:)  Thrust Vectors
 magF    (1,1)  Terrain magnification factor
Outputs
 None
References Constant(), Date2JD(), Demo(), length(), Mag(), MoonRot(), NewFig(), PlanetWithTerrain(), PlotLunarOrbit(), RSHMoon(), RVFromKepler(), TimeLabl(), TitleS(), Unit(), vector(), Watermark(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by PlotLunarOrbit().
PlotSEMTraj()
function PlotSEMTraj (in r, in frame, in jD)
 The input vectors are in the ECI frame. Has a built-in demo for an orbit
 with an apogee of 400,000 km, a perigee of 7000 km, and a duration of 5 days.
 Type PlotSEMTraj for a demo.
 Forms:
 h = PlotSEMTraj( r, frame, jD )
Inputs
 r                (3,:) position vectors (km)
 frame            (1,1) frame of r
                        'SEMRND', 'SEMR', 'ECI'
 jD               (:)   Julian dates
Outputs
 h                (1,1) Figure handle
References and(), Constant(), CRTBPRHS(), Demo(), length(), NewFig(), PlotSEMTraj(), set(), Trajectory(), and Watermark().
Referenced by PlotSEMTraj().
PropagateState()
function PropagateState (in x, in beta, in dT, in d)
Form
 xP = PropagateState( x, beta, dT, d )
Inputs
 x       (4,:)   Initial state [x;y;vX;vY]
 beta    (1,:)   Thrust angle (rad)
 dT      (1,:)   Delta time for each step
 d        (.)    Data structure describing spacecraft model
                 .a (1,1) Thrust acceleration (m/s^2)
                 .g (1,1) Gravitation acceleration (m/s^2)
                 .n (1,1) Number of steps
Outputs
 xP    (4,:)   State
See also
: RHSPlanetTakeoff, RK4
References PropagateState(), RHSPlanetTakeoff(), RK4(), and zeros().
Referenced by PropagateState(), and Simulate2DLanding().
PropagateState3D()
function PropagateState3D (in x, in dT, in d)
Propagate the state with RHSPlanet3D and RK4 for the given control angles. If the fuel mass becomes negative, thrust is set to zero.
Form
 xP = PropagateState3D( x, dT, d )
Inputs
 x       (7,1)   Initial state [x;y;z;vX;vY;vZ;m]
 dT      (1,:)   Delta time for each step
 d        (.)    Data structure describing spacecraft model
                 .beta   (1,:) Thrust angle in rv plane
                 .alpha  (1,:) Thrust angle out of plane
                 .thrust (1,:) Thrust (N)
                 .accel  (1,:) 'constant' or 'free'
                 .m0     (1,1) Dry mass
                 .n      (1,1) Number of steps to simulate
                 .nG     (1,1) Multiplier of 'g', gravity, for 'constant'
Outputs
 xP    (7,:)   State
See also
: RHSPlanet3D
References and(), Mag(), PropagateState3D(), RHSPlanet3D(), RK4(), set(), and zeros().
Referenced by PropagateState3D(), and Simulate3DLanding().
RHSLunarLander()
function RHSLunarLander (in x, in t, in d)
This is a rigid body with an external force and torque input. The position is in km. The gravity model is for a point mass. The force and torque area constant across the integration time step.
The function fDist (which should be a pointer) is of the form
 [force, torque] = MyFun( x, t, d )
You can add additional fields to d. force must be in N in the body frame and torque in Nm in the body frame. This function allows you to add forces and torques within the integration loop. This is required for forces and torques that are functions of time or the state vector.
Form
 xDot = RHSLunarLander( x, t, d )
Inputs
 x       (20,1) State vector [r;v;q;w;m;inertia] (km,km/s,,rad/s,kg,kg-m^2)
 t       (1,1)  Time  (s)
 d       (1,1)  Data structure for the simulation
                 .torque   (3,1) External torque (Nm)
                 .thrust   (1,1) Engine Thrust (N)
                 .uThrust   (3,1) Unit vector in the body frame
                 .rThrust   (3,1) Thrust position in the body frame
                 .inertia  (3,3) Vehicle inertia (kg-m^2)
                 .inertia  (3,3) Vehicle inertia (kg-m^2)
                 .massDry  (1,1) Vehicle dry mass (kg)
                 .aGrav    (1,1) Pointer to gravity function
Outputs
 xDot   (:,1)     dx/dt
References and(), Constant(), Cross(), Date2JD(), DefaultDataStructure(), Euler(), JD2000(), Mag(), QIToBDot(), QTForm(), RHSLunarLander(), Skew(), Unit(), and vector().
Referenced by LunarLandingControl(), and RHSLunarLander().
RHSLunarMission()
function RHSLunarMission (in x, in t, in d)
Includes solar disturbances and the power model. Any number of reaction wheels can be simulated. Reaction wheels are optional. It also includes states for the IMU (gyro and accelerometer) bias.
The gravity model includes the Earth, Sun and the Moon.
The Moon gravity model can have spherical harmonics.
The solar power model includes eclipses due to the Moon and Earth
but not self-shadowing.
You can select the Moon or Earth as the coordinate center for orbit propagation. Get the default data structure by typing:
 d = RHSLunarMission
Set up the state name output by typing:
 RHSLunarMission( x );
You must initialize the JPL ephemerides prior to using this function. Type:
 PlanetPosJPL( 'initialize', [0 3 10] );
 Forms:
 d = RHSLunarMission;            % data structure
 RHSLunarMission( x );       % initialize persistent variables
 [xDot, p] = RHSLunarMission( x, t, d )
Inputs
 x     (:,1)   State [rECI;vECI;qECIToBody;omega;massFuel;pBattery;
                      iMUBiasAccel;iMUBiasGyro;omegaRWA]
 t     (1,1)   Time
 d     (.)     Data structure
                    .jD0        (1,1) Julian date of epoch
                    .mass       (1,1) Spacecraft mass (kg)
                    .inertia    (3,3) Spacecraft inertia (kg-m2)
                    .power       (.)  Power data, see SolarCellPower
                    .opticalModel * Handle, see CubeSatRadiationPressure
                    .surfData    (.)  optional; empty to skip optical calcs
                    .thruster    (.)
                    .rWA         (.)
                    .iMU         (.)
                    .gravity     (.)
                    .forceBody  (3,1) Body forces (N)
                    .torqueBody (3,1) Body torques (Nm)
Outputs
 xDot  (:,1)   dx/dt
 p     (.)     Data structure with internally computed variables
References and(), Cross(), CubeSatLunarEnvironment(), CubeSatRadiationPressure(), Date2JD(), DupVect(), IMU(), InertiaCubeSat(), Initialize(), isempty(), length(), PlanetPosJPL(), QForm(), QIToBDot(), QTForm(), RHSLunarMission(), Skew(), and SolarCellPower().
Referenced by RHSLunarMission().
RHSLunarOrbit()
function RHSLunarOrbit (in x, in t, in d)
This function implements only orbit dynamics. The Moon gravity model can have spherical harmonics. Get the default data structure by typing:
 d = RHSLunarOrbit
Set up the state name output by typing:
 RHSLunarOrbit( x );
Form
 d = RHSLunarOrbit            % data structure
 RHSLunarOrbit( x );      % initialize persistent variables
 [xDot, p] = RHSLunarOrbit( x, t, d )
Inputs
 x     (:,1)   [rECI;vECI;m]
 t     (1,1)   Time
 d     (.)     Data structure
Outputs
 xDot  (:,1)   dx/dt
 p     (.)     Data structure with internally computed variables
References Date2JD(), isempty(), length(), Mag(), MoonRot(), and RHSLunarOrbit().
Referenced by RHSLunarOrbit().
RHSPlanet3D()
function RHSPlanet3D (in x, in ignoredArg, in d)
The gravity function returns the gravitational accelerations in the planet fixed frame. It must be of the form
 a = GravFun( r, gFunData )
where a is in the planet fixed frame. d.mu is not used in this case. The planet rotation is around the ECI z axis. The default data structure is for the the moon.
Form
 xDot = RHSPlanet3D( x, ~, d )
Inputs
 x     (7,1)   State [r;v;m], where m is fuel mass
 t     (1,1)   Time (not used)
 d      (.)    Data structure
               .mu       (1,1) Gravitational constant
               .gFun      (@)  Handle to the gravity function
               .gFunData     (.)  Gravity function data structure
               .omega    (1,1) Planet rotation rate
               .uThrust  (3,1) Unit thrust vector
               .thrust   (1,1) Thrust (N)
               .uE       (1,1) Exhaust velocity (m/s)
               .m0       (1,1) Dry mass, total mass is m0 + m
Outputs
 xDot   (7,1)   State derivative [r;v;m]
References Constant(), isempty(), Mag(), RHSPlanet3D(), Skew(), Unit(), and vector().
Referenced by LandingConst3D(), PropagateState3D(), RHSPlanet3D(), RHSPlanet3DONS(), and RHSPlanet3DToAB().
RHSPlanet3DToAB()
function RHSPlanet3DToAB (in x, in d, in dT)
This is for the function RHSPlanet3D. If aL is entered it will use an analytical solution for a spherical planet. The mass state equation is not output. b multiplies the acceleration vector.
Type RHSPlanet3DToAB for a demo.
Form
 [a,b,aC] = RHSPlanet3DToAB( x, d, dT )
Inputs
 x   (6,1)  [r;v] (km/km/s)
 d   (.)   Data structure for RHSPlanet3D
 dT  (1,1) Time step
Outputs
 a   (6,6) State transition matrix
 b   (6,3) Input matrix
 aC  (6,6) Continuous
References and(), C2DZOH(), Demo(), DispWithTitle(), Mag(), RHSPlanet3D(), RHSPlanet3DToAB(), Skew(), vector(), and zeros().
Referenced by RHSPlanet3DToAB().
RHSRVPlanetFixed()
function RHSRVPlanetFixed (in x, in t, in d)
You can pass in user defined thrust functions via d.funThrust and gravitational acceleration functions via d.funGrav
 [thrust,uE] = Thrust( massFuel, d )
thrust must be in N and uE in m/s. and custom gravitational acceleration functions for d.gFun; accelGrav is in km/s^2:
 accelGrav   = Gravity( x, d )
If gFun is not a pointer it is assumed to be the gravitational constant.
Type RHSRVPlanetFixed for the default data structure.
Form
 xDot = RHSRVPlanetFixed( x, t, d )
 d    = RHSRVPlanetFixed;  % data structure
Inputs
 x   (7,1) [r;v;massFuel]
 t   (1,1) Time (s)
 d   (.)   Data structure
           .funThrust      @   Thrust function handle
           .dataFunThrust (.)  Thrust function data
           .rVStruct      (.)  Data for orbit RHS function
           .massDry      (1,1) Dry mass (kg)
Outputs
 x   (7,1) d[r;v;massFuel]/dt
See also
: FThrustLander, RHSOrbitPlanetFixed
References and(), Constant(), FThrustLander(), Mag(), RHS(), RHSOrbitPlanetFixed(), and RHSRVPlanetFixed().
Referenced by RHSRVPlanetFixed().
RHSSGCMG()
function RHSSGCMG (in x, in ignoredArg, in d)
 This has a built-in speed controller for the CMG wheel. It can handle
 any number of CMGs but the default is three.
Form
 [xDot,hECI,inr] = RHSSGCMG(x,~,d)
Inputs
 x      (7+2*n)     [q;omega;omegaCMG(2*n,1)]
 t      (1,1)        Time (not used)
 d      (.)          Data structure
                     .omegaS (1,1)         CMG wheel setpoint
                     .inr    (3+2*n,3+2*n) Inertia matrix (for 3 CMGs)  (kg-m^2)
                     .inrCMG (3,3)         Inertia matrix for CMG (2-axis) (kg-m^2)
                     .kC     (1,1)         Rate control gain (Nm-s)
                     .torque (3,1)         External torque (Nm)
                     .tC     (n,1)         CMG gimbal torque  (Nm)
Outputs
 xDot   (7+2*n)       d[q;omega;omegaCMG(2*n,1)]/dt
 hECI   (3,1)         ECI momentum (Nms)
 inr    (3+2*n,3+2*n) Inertia matrix (kg-m^2)
References CMG(), DefaultDataStructure(), length(), and zeros().
RHSTrajectory()
function RHSTrajectory (in x, in t, in d)
This model explicitly includes the moon. You must initialize the JPL ephemerides before running this function.
 PlanetPosJPL( 'initialize', planets  );
Planets contains the JPL ephemeris ids from 1 to 11. The force model must be of the form f = ForceModel(r, v, d) where d can be any data structure. f is the force vector in N in the ECI frame.
Form
 d        = RHSTrajectory;            % Get the default data structure
 RHSTrajectory( x );       % initialize persistent variables
 [xDot, p] = RHSTrajectory( x, t, d ); % Call during simulation
Inputs
 x     (6*n,1) State [r;v] for n bodies
 t     (1,1)   Time since start date
 d     (.)     Date
               .jD0      (1,1) Julian date at start
               .mu       (1,1) Sun gravitational parameter
               .planets  (1,:) Planet IDs.
               .object   (:)   Data structures for object
                               .mass            (1,1) Mass
                               .forceModel      (.)   Force model structure
                               .gravity        (.)   Gravity model structure
                               .cM             (3,1) Center of mass
Outputs
 xDot  (6*n,:) State derivative d[r;v]/dt
 p     {}      Auxiliary outputs
See also
: PlanetPosJPL, ForceSimple, GravityHelio, NoForce
References Planets(), RHSTrajectory(), and vector().
Referenced by RHSTrajectory().
RSHMoon()
function RSHMoon (in nH, in lambda, in theta, in s, in c)
 Type RSHMoon for a demo.
 This uses Clementine data. The highest harmonic is 72.
 If s and c are not entered it will load the lunar surface coefficients
 each time is called. You can load the coefficients yourself using
 [s,c] = LoadLunarTopography( nH );
Form
 [r, lambda, theta] = RSHMoon( nH, lambda, theta, s, c )
Inputs
 nH            (1,1)  Highest harmonic
 lambda        (j)    Equatorial angle
 theta         (i)    Angle from pole
 s             (:,:)  Normalized sine coefficients
 c             (:,:)  Normalized cosine coefficients
Outputs
 r             (i,j)  Radius
 lambda        (j)    Equatorial angle
 theta         (i)    Angle from pole
Reference: Smith, D. E., Zuber, M. T., Neumann, G. A., "Topography of the Moon from the Clementine lidar", Journal of Geophysical Research, Vol. 102, No. E1, pp. 1591-1611, January 25, 1997.
References and(), DupVect(), isempty(), length(), LoadLunarTopography(), Mesh2(), PAL(), RSHMoon(), SCHarm(), Watermark(), and zeros().
Referenced by LunarVisibility(), PlanetWithTerrain(), PlanetWithTerrainPatch(), PlotLunarOrbit(), and RSHMoon().
SecondOrderGuidance()
function SecondOrderGuidance (in action, in x, in d)
Uses a 2nd order controller to provide guidance for landing. Demonstrated in a cartesian system with x along vertical. Includes centripetal and gravitational acceleration.
 'initialize' computes the time to land from the tolerance.
 'update' updates the control accelerations.
You generally want zeta to be 1. Lower omegas will reduce the control accelerations. An omega of 0.01 gives roughly the Apollo LM landing guidance. If it is much lower you can overshoot and then have to return to the landing site.
Type SecondOrderGuidance for a demo. The demo is in cartesian coordinates with gravity and centripetal acceleration along x.
Form
 a = SecondOrderGuidance( action, x, d )
Inputs
 action (1,:) 'initialize' or 'update'
 x      (6,1) State [r;v]
 d      (.)   Data structure
              .x       (6,1) Target [r;v]
              .tol     (1,1) Tolerance for damping
              .zeta    (1,1) Damping ratio
              .omega   (1,1) Undamped natural frequency (rad/s)
              .t       (1,1) Time to damp
              .rP      (1,1) Equatorial radius
              .mu      (1,1) Gravitational constant
Outputs
 a     (3,:)   Control accelerations
References and(), Constant(), DefaultDataStructure(), Demo(), NewFig(), Plot2D(), RHS(), RK4(), SecondOrderGuidance(), TimeLabl(), Trajectory(), XLabelS(), YLabelS(), and zeros().
Referenced by SecondOrderGuidance(), and SecondOrderGuidance3D().
SecondOrderGuidance3D()
function SecondOrderGuidance3D (in action, in x, in d)
Uses a 2nd order controller to provide guidance for landing. Demonstrated in a cartesian system.
 'initialize' computes the time to land from the tolerance.
 'update' updates the control accelerations.
You generally want zeta to be 1. Lower omegas will reduce the control accelerations. An omega of 0.01 gives roughly the Apollo LM landing guidance. If it is much lower you can overshoot and then have to return to the landing site.
Type SecondOrderGuidance3D for a demo of lunar landing. This replicates the demo in SecondOrderGuidance.
Form
 d = SecondOrderGuidance3D
 a = SecondOrderGuidance3D( action, x, d )
Inputs
 action (1,:) 'initialize' or 'update'
 x      (6,1) State [r;v]
 d      (.)   Data structure
              .x       (6,1) Target [r;v]
              .tol     (1,1) Tolerance for damping
              .zeta    (1,1) Damping ratio
              .omega   (1,1) Undamped natural frequency (rad/s)
              .t       (1,1) Time to damp
              .rP      (1,1) Equatorial radius
              .mu      (1,1) Gravitational constant
Outputs
 a     (3,:)   Control accelerations
References and(), Constant(), DefaultDataStructure(), Demo(), DownrangeAndAltFromTarget(), Mag(), Plot2D(), RHS(), RK4(), SecondOrderGuidance(), SecondOrderGuidance3D(), TargetFromRPVD(), TimeLabl(), Unit(), and zeros().
Referenced by SecondOrderGuidance3D().
SEMGravAcc()
function SEMGravAcc (in rSEM)
 The position is in the Sun-Earth/Moon frame.
 Type SEMGravAcc for a built-in demo creating gravity contour plots.
 Since version 10.
Form
 [gSun,gEM,gCompare] = SEMGravAcc( rSEM )
Inputs
 rSEM          (2,:)    Position vector in SEM frame
Outputs
 gSun          (:,:)    Gravitational acceleration due to the Sun
 gEM           (:,:)    Gravitational acceleration due to the Earth/Moon
 gCompare      (:,:)    gEM/gSun
References Accel(), and(), Constant(), Demo(), length(), NewFig(), SEMGravAcc(), vector(), and zeros().
Referenced by SEMGravAcc().
SEMIToSEMR()
function SEMIToSEMR (in jD, in rSEMI, in vSEMI)
Transform position and velocity from inertial heliocentric frame to the Sun-Earth/Moon barycentered rotating frame.
The SEMR coordinate frame has xy in the ecliptic plane.
 +x points at the earth along the Sun-Earth line.
 +z normal to the ecliptic plane
 +y completes the right-handed system.
Uses an analytic formula for the ecliptic longitude to define the rotation in the xy plane. Uses a constant value of the Earth rotation rate around the sun to transform the velocity.
Form
 [rSEMR,vSEMR,m] = SEMIToSEMR( jD, rSEMI, vSEMI )
Inputs
 jD            (1,:)       Julian date (days)
 rSEMI         (3,:)       Position vector in SEMI frame
 vSEMI         (3,:)       Velocity vector in SEMI frame
Outputs
 rSEMR         (6,:)       Position vector in SEMR frame
 vSEMR         (6,:)       Velocity vector in SEMR frame
 m              {:}        Rotation matrix
References and(), and vector().
SEMRToSEMI()
function SEMRToSEMI (in jD, in rSEMR, in vSEMR)
Transform pos. and vel. from Sun-Earth/Moon barycentered rotating frame to inertial heliocentric frame.
The SEMR coordinate frame has xy in the ecliptic plane.
 +x points at the earth along the Sun-Earth line.
 +z normal to the ecliptic plane
 +y completes the right-handed system.
Uses an analytic formula for the ecliptic longitude to define the rotation in the xy plane. Uses a constant value of the Earth rotation rate around the sun to transform the velocity.
Form
 [rSEMI,vSEMI,m] = SEMRToSEMI( jD, rSEMR, vSEMR )
Inputs
 jD            (1,:)       Julian date (days)
 rSEMR         (6,:)       Position vector in SEMR frame
 vSEMR         (6,:)       Velocity vector in SEMR frame
Outputs
 rSEMI         (3,:)       Position vector in SEMI frame
 vSEMI         (3,:)       Velocity vector in SEMI frame
 m              {:}        Rotation matrix
References and(), and vector().
Referenced by EarthOrbToHelioOrb().
SEMToSEMND()
function SEMToSEMND (in r, in v)
Scale position and velocity in SEM system (rotating or inertial) by distance and velocity units to make non-dimensional
Form
 [rND,vND] = SEMToSEMND( r, v )
Inputs
 r            (3,:)       Position vector in EMBR frame
 v            (3,:)       Velocity vector in EMBR frame
References and(), Constant(), SEMToSEMND(), and vector().
Referenced by SEMToSEMND().
Simulate2DLanding()
function Simulate2DLanding (in t, in beta, in d, in name)
Form
 Simulate2DLanding( t, beta, d, name )
Inputs
 t       (1,:)   Time vector
 beta    (1,:)   Thrust angle (rad)
 d        (.)    Data structure describing spacecraft model
                 .x (4,1) Initial state (ex. [0;h;-u;0])
                 .g (1,1) Gravitational acceleration
                 .a (1,1) Thrust acceleration (m/s^2)
                 .n (1,1) Number of steps
 name     ''     Name for the plots
Outputs
 None
See also
PropagateState
References Altitude(), and(), get(), Plot2D(), PropagateState(), set(), TimeLabl(), Trajectory(), and vector().
Simulate3DLanding()
function Simulate3DLanding (in dT, in d, in name)
Form
 Simulate3DLanding( dT, d, name )
Inputs
 dT       (1,:)  Time step vector
 d        (.)    Data structure describing spacecraft model
                 .s0     (7,1) State [x;y;z;vX;vY;vZ;m]
                 .beta   (1,:) Thrust angle in rv plane
                 .alpha  (1,:) Thrust angle out of plane
                 .thrust (1,:) Thrust (N)
                 .accel   ''   'constant' or 'free'
 name    (1,:)   Name for the plots
Outputs
 None
See also
: PropagateState3D, Plot2D, PlanetWithTerrainPatch
References Altitude(), and(), PlanetWithTerrainPatch(), Plot2D(), PropagateState3D(), TimeLabl(), vector(), and zeros().
SunEarthMoonSystemConstants()
function SunEarthMoonSystemConstants ()
 Useful for non-dimensionalizing in the Sun-Earth-Moon system.
 Since version 11.
Form
 d = SunEarthMoonSystemConstants
Inputs
 none
Outputs
 d  (1,1)   Data structure output with system constants and fields:
           .system   (1,:) Name of system - 'SEM'
           .muMoon   (1,1) Gravitational parameter of the moon
           .muEarth  (1,1) Gravitational parameter of the Earth
           .muSun    (1,1) Gravitational parameter of the Sun
           .mu       (1,1) Mu of the SEM system
           .au       (1,1) Astronomical unit (km)
           .L        (1,1) Sun/Earth distance = .au
           .T        (1,1) Earth year
           .Re       (1,1) Earth radius
           .Rm       (1,1) Moon radius
           .Rs       (1,1) Sun radius
           .xL1      (1,1) Earth/Sun L1 distance
           .xL2      (1,1) Earth/Sun L2 distance
           .v        (1,1) Earth velocity (km/s)
References and(), get(), length(), and SunEarthMoonSystemConstants().
Referenced by EarthEscape(), EarthOrbToHelioOrb(), L2OrbitPlots(), L2OrbitSim(), and SunEarthMoonSystemConstants().
TransformECIToEMBR()
function TransformECIToEMBR (in jD, in rECI, in vECI)
and vel. to Earth Moon barycenter rotating frame.
The EMBR coordinate frame is +x pointing at the earth along the earth-moon line. +z normal to the earth moon plane and +y completing the set. Uses MoonV1. Computes the plane by looking at the moon vector at jD(k) and then 1 day later.
 Type
 TransformECIToEMBR
 for a demo
 Since version 10.
Form
 [rEMBR,vEMBR,m] = TransformECIToEMBR( jD, rECI, vECI )
Inputs
 rECI          (6,:)       Position vector in ECI frame
 vECI          (6,:)       Velocity vector in ECI frame
 jD            (1,:)       Julian date (days)
Outputs
 rEMBR         (6,:)       Position vector in EMBR frame
 vEMBR         (6,:)       Velocity vector in EMBR frame
 m              {:}        Rotation matrix
References and(), MoonV1(), set(), TransformECIToEMBR(), and vector().
Referenced by TransformECIToEMBR().
TransformECIToSEMR()
function TransformECIToSEMR (in jD, in rECI, in vECI)
and vel. to Sun-Earth-Moon rotating (SEMR) frame.
The SEMR coordinate frame is +x pointing at the earth along the sun-earth line. +z normal to the sun-earth plane and +y completing the set. Uses CEcl2Eq.
 Type
 TransformECIToSEMR
 for a demo
 Since version 10.
Form
 [rSEMR,vSEMR,m] = TransformECIToSEMR( jD, rECI, vECI )
Inputs
 rECI          (6,:)       Position vector in ECI frame
 vECI          (6,:)       Velocity vector in ECI frame
 jD            (1,:)       Julian date (days)
Outputs
 rSEMR         (6,:)       Position vector in SEMR frame
 vSEMR         (6,:)       Velocity vector in SEMR frame
 m              {:}        Rotation matrix
References and(), CEcl2Eq(), set(), TransformECIToSEMR(), and vector().
Referenced by EarthOrbToHelioOrb(), TransformECIToSEMR(), and TransformSEMRToHelio().
TransformEMBRToECI()
function TransformEMBRToECI (in jD, in rEMBR, in vEMBR)
and vel. from Earth Moon barycenter rotating frame to ECI
The EMBR coordinate frame is +x pointing at the earth along the earth-moon line. +z normal to the earth moon plane and +y completing the set. Uses MoonV1. Computes the plane by looking at the moon vector at jD(k) and then 1 day later.
 Type
 TransformEMBRToECI
 for a demo
 Since version 10.
Form
 [xECI,vECI,m] = TransformEMBRToECI( xEMBR, jD )
Inputs
 jD            (1,:)       Julian date (days)
 rEMBR         (3,:)       Position vector in EMBR frame
 vEMBR         (3,:)       Velocity vector in EMBR frame
Outputs
 rECI          (6,:)       Position vector in ECI frame
 vECI          (6,:)       Velocity vector in ECI frame
 m              {:}        Rotation matrix
References and(), MoonV1(), set(), TransformEMBRToECI(), and vector().
Referenced by PlotEMTraj(), and TransformEMBRToECI().
TransformSEMRToECI()
function TransformSEMRToECI (in jD, in rSEMR, in vSEMR)
The SEMR coordinate frame is +x pointing at the earth along the sun-earth line. +z normal to the sun-earth plane and +y completing the set. Uses CEcl2Eq.
Form
 [rECI,vECI,m] = TransformSEMRToECI( jD, rSEMR, vSEMR )
Inputs
 jD            (1,:)    Julian date (days)
 rSEMR         (3,:)    Position vector in SEMR frame
 vSEMR         (3,:)    Velocity vector in SEMR frame
Outputs
 rECI          (3,:)    Position vector in ECI frame
 vECI          (3,:)    Velocity vector in ECI frame
 m              {:}     Rotation matrix
References and(), CEcl2Eq(), set(), and vector().
Referenced by TransformSEMRToHelio().
TransformSEMRToHelio()
function TransformSEMRToHelio (in jD, in rSEMR, in vSEMR)
The SEMR coordinate frame is +x pointing at the earth along the sun-earth line. +z normal to the sun-earth plane and +y completing the set.
Type TransformSEMRToHelio for a demo
Form
 [rHelio,vHelio,mRot] = TransformSEMRToHelio( jD, rSEMR, vSEMR )
Inputs
 jD            (1,:)       Julian date (days)
 rSEMR         (3,:)       Position vector in SEMR frame
 vSEMR         (3,:)       Velocity vector in SEMR frame
Outputs
 rHelio          (3,:)       Position vector in heliocentric frame
 vHelio          (3,:)       Velocity vector in heliocentric frame
 mRot            (3,3)       Rotation matrix
See also
TransformSEMRToECI and SunV2
References and(), Constant(), Date2JD(), Demo(), length(), Mag(), set(), SunV2(), TransformECIToSEMR(), TransformSEMRToECI(), TransformSEMRToHelio(), and vector().
Referenced by TransformSEMRToHelio().
UMinGG()
function UMinGG (in inr)
Uses fminsearch. Type UMinGG for a demo with NASA Gateway.
Form
 u = UMinGG(inr)
Inputs
 inr           (3,3)  Inertia matrix
Outputs
 u             (3,1)  Unit vector
References Cross(), Demo(), Mag(), RaDec2U(), RHS(), UMinGG(), Unit(), and vector().
Referenced by UMinGG().