PSS MATLAB Toolboxes: Thermal Functions
Thermal Functions
Thermal Module
The Thermal module functions.
Description
Functions
function AbsDa (in alpha, in dA, in S)
Absorbed radiation from an incremental area.
function AbsoluteViscosity (in gas, in t)
Computes the absolute viscosity.
function AeroHeatFlux (in f, in sigma, in type)
Aerodynamic heat flux.
function AxialTurbineDesign (in varargin)
Design an axial turbine.
function BladeSpacing (in alpha1, in alpha2)
Computes s/b - blade spacing divided by the chord.
function BladeStress (in u, in rH, in rT, in rhoM, in aTOAH)
Compute stress on turbine blades.
function BlckBody ()
Aborptivity and emissivity of a black body.
function Brayton (in d)
Brayton Cycle.
function BraytonIdeal (in gamma, in pR, in cP, in t3, in qR, in effTC)
Ideal Brayton cycle.
function BTUToJoule (in bTU)
Converts BTUs to Joules.
function CentrifugalCompressor (in d)
Designs a centrifugal compressor.
function CycleDesign (in fXe, in heat, in t1, in t4, in p1, in a, in r, in n, in pR, in nC, in nT, in nR, in doPlot)
Brayton cycle design from temperature, pressure and efficiencies.
function DrawThermalPlugIn (in action, in hFig, in modifier)
Draw a thermal diagram.
function EmittanceParallelPlates (in e)
Computes the emittance of plates in parallel.
function FrictionLaminar (in rE, in type)
Computes the laminar friction.
function FSolarPanelThermal (in x, in d)
Used by fmins from SolarPanelThermal to compute panel temperatures.
function GrayBody (in alphaOrEpsilon)
Aborptivity and emissivity of a gray body.
function HeatExchanger (in d)
Designs a heat exchanger for a one sided heat flux.
function HeatExchangerWithLosses (in d, in doPlot)
Implements a flat plate heat exchanger with radiation losses.
function HeatFP (in q2, in alpha2, in e2, in e1, in k, in fC, in tau)
Computes the temperature at two surfaces of a flat plate.
function HeatShieldCoating (in name)
Values for heat shield coatings.
function HeatTransferChannel (in d, in doPlot)
Designs a heat exchanger for a one sided heat flux.
function HeatTransferCoeff (in nU, in k, in d)
Computes the Heat transfer coefficient.
function HeatTransferCoeffTaylor (in u, in d, in l)
HeatTransferCoeffTaylor Heat transfer coefficient based on Taylor.
function HeXeMixture (in fXe)
Compute gas properties for a helium/xenon mixture.
function ImpactThickness (in material, in m, in v, in a, in fS)
For turbine blades going through the shell.
function Isothermal (in el, in center, in d, in jD)
Model a spacecraft as an isothermal radiator.
function IsothermalHelio (in r, in qECIToBody, in nEclipse, in mass, in heat, in temp, in d)
Isothermal model in heliocentric orbit.
function IsothermalLunar (in el, in d, in jD)
Model a spacecraft as an isothermal radiator in lunar orbit.
function JouleToBTU (in j)
Converts Joules to BTUs.
function KinematicViscosity (in mu, in rho)
Computes the Kinematic viscosity.
function LambertL (in theta, in E)
Lambert's cosine law.
function LiquidMetalProps (in metal, in t)
Liquid metal thermal properties.
function NusseltDeveloping (in x, in D, in rE, in isHFD)
Computes the Nusselt number for developing turbulent flow.
function NusseltLaminar (in g, in type)
Computes the Nusselt number for laminar flow.
function NusseltTurbulent (in rE, in pR)
Computes the Nusselt number for fully developed turbulent flow.
function OptimalMLIDensity (in tH, in tC, in d)
Determine optimal Multi-layer Insulation (MLI) density.
function PanelThermalModel (in g, in flux)
Computes the temperatures of a panel from a CAD model.
function PlanckL (in T, in lambda)
Planck's law for a black body.
function PlotThermal (in q, in temp, in t, in g, in units)
Plots flux and temperature.
function PrandtlNikuradse (in rE)
Computes the Fanning friction factor for fully developed turbulent flow.
function PrandtlNumber (in mu, in cP, in k)
Computes the Prandtl Number.
function PressureDropChannel (in d)
Computes the channel pressure drop.
function RadBFp (in epsilon, in T1, in Tn)
Radiation between equal area flat plates.
function RadDa (in T, in epsilon, in da)
Radiation from an incremental area.
function RadiationShapeFactor (in w1, in w2, in l, in units)
Computes the radiation shape factor.
function RadiationShield (in d)
Computes temperatures on a radiation shield with MLI.
function RadiatorCoating (in name)
Values for radiator coatings.
function RankineCycle (in p3, in p4, in doPlot)
Simple Rankine Cycle from turbine pressures.
function ReynoldsNumberKinematic (in u, in d, in nu)
Computes the Reynolds number.
function RHSAerodynamicHeating (in d)
Compute aerodynamic heating.
function RHSIsothermal (in x, in t, in d)
Model a spacecraft as an isothermal radiator.
function SizeTurbineAndCompressor (in d)
Designs the turbine and compressor for a Brayton cycle.
function SolarPanelThermal (in d)
Compute the front/back temperatures of a solar panel.
function SpaceCamera (in action, in modifier, in g, in jD)
Draw spacecraft in orbit about a planet, as seen by an in-situ camera.
function SpacecraftThermal (in mode, in g, in e)
Compute the temperature in input flux for the spacecraft components.
function SteamTablesSuperheatedEnthalpy (in p, in s)
Enthalpy for superheated steam or compressed water.
function TempConv (in from, in to, in tI)
Converts temperatures between units.
function TempCyl (in alpha, in epsilon, in rOverL, in S, in n, in u)
Temperature of a cylinder.
function TempFP (in alpha, in epsilon, in S, in n, in u)
Temperature of a flat plate.
function TempSph (in alpha, in epsilon, in S)
Temperature of a sphere.
function ThermalColorMap (in temp, in tempMax, in colorMap)
Generates a color corresponding to a temperature.
function ThermalConductivity (in gas, in t)
Computes the thermal conductivity.
function ThermalConductivityAndViscHeXe (in t, in f)
Computes the thermal conductivity and viscosity.
function ThermalEquilibrium (in d, in q, in t, in nIts, in epsilon)
This function computes the thermal equilibrium for a system.
function ThermalImager (in action, in g, in d)
Color a spacecraft or planet corresponding to a temperature.
function Thermnet (in mn, in cnm, in cc, in inm, in onm, in rnm, in rc, in tnom)
Creates a set of first order differential equations to model.
function TSCurve (in t)
Generate the TS curve for water and steam.
function WiensDsp (in T)
Computes the peak black body wavelength as a function of temperature.
Function Documentation
AbsDa()
function AbsDa (in alpha, in dA, in S)
 Type AbsDa for a demo.
Form
 q = AbsDa( alpha, dA, S )
Inputs
 alpha       (1,1)    Absorptivity
 dA          (1,1)    Incremental area
 S           (1,:)    Heat flux
Outputs
 q           (1,:)    Absorbed heat flux (watts)
References: Van Vliet, R. M., Passive Temperature Control in the Space Environment, MacMillan, 1965, p. 4.
References AbsDa(), Demo(), and Plot2D().
Referenced by AbsDa().
AbsoluteViscosity()
function AbsoluteViscosity (in gas, in t)
Absolute viscosity. Extrapolates beyond the range of data. The data might not be valid for the input temperature. For example, the gas may become a liquid at a low temperature or a molecule mau dissociate at a high temperature.
Type AbsoluteViscosity for a demo for xenon.
Form
 mu = AbsoluteViscosity( gas, t )
Inputs
 gas   (1,:)   Gas
 t     (1,:)   Temperature (deg-K)
Outputs
 mu    (1,:)   Absolute viscosity (Pa s)
Reference: https://www.engineeringtoolbox.com/ gases-absolute-dynamic-viscosity-d_1888.html
References AbsoluteViscosity().
Referenced by AbsoluteViscosity(), HeatTransferChannel(), Knudsen(), PressureDropChannel(), RHSLiftingSatellite(), and SizeTurbineAndCompressor().
AeroHeatFlux()
function AeroHeatFlux (in f, in sigma, in type)
The input may be a data structure or a file name of a .mat file containing the data structure. Since this uses the standard atmosphere model it only works up to 80 km. See StdAtm.m.
This model uses the assumption that the tip is blunt and that the Prandtl number is 1. The heat flux is therefore (1/4)cF rho V^3. The characteristic length is the radius of a nose cone or length of the flat surface.
Type AeroHeatFlux for a demo.
Form
 AeroHeatFlux
 qDot = AeroHeatFlux( f, sigma )
Inputs
 f            (1,:)     Filename
                        or
              (1,1)     Data structure
                        .time     (1,:) Time (sec)  (Plotting only)
                        .velocity (1,:) Velocity (m/s)
                        .altitude (1,:) Altitude (m)
                        .range    (1,:) Range (m) (Plotting only)
 sigma        (1,1)    Characteristic length (m)
 type         (1,:)    'laminar plate' 'turbulent plate' 'blunt nose'
Outputs
 qDot         (1,:)     Heat flux (W/m^2)
References: H. Julian Allen and A. J. Eggers, Jr., "A Study of the Motion and Aerodynamic Heating of Ballistic Missiles Entering the Earth's Atmosphere at High Supersonic Speeds," NACA Report 1381. Hankey, W., 'Re-entry Aerodynamics", AIAA Press.
References AeroHeatFlux(), Altitude(), and(), length(), and StdAtm().
Referenced by AeroHeatFlux().
AxialTurbineDesign()
function AxialTurbineDesign (in varargin)
Assumes repeating stages. Uses mean line analysis. The reaction, flow coefficient and loading coefficient determine the design.
The output data structure has all the values in the input plus values computed in the function. The latex formatted output can be saved to a file using CreateLatexTable or printed in the command window using DisplayLatexTable.
Type AxialTurbineDesign for a demo taken from Example 4.2 in the reference on pages 138-139.
Form
 [d, l] = AxialTurbineDesign( varargin )
Inputs
 varargin       {.}   Parameter pairs
                       'name'          (1,:) Name of the turbine
                       'reaction'      (1,1) Reaction
                       'power'         (1,1) Power (MW)
                       'r tip'         (1,1) Radius of tip (m)
                       'omega'         (1,1) Angular rate (rad/s)
                       'mass flow'     (1,1) Mass flow (kg/s)
                       'flow coeff'    (1,1) Flow coefficient
                       'loading coeff'  (1,1) Loading coefficient
                       'reheat factor' (1,1) Reheat factor
                       'material'      (1,:) Material or data structure
Outputs
 d              (.)    Data structure
 l              {:,3}  Latex formatted output
Reference: S.L. Dixon and C.A. Hall, "Fluid Mechanics and Thermodynamics of Turbomachinery, 7th Edition," Butterworth-Heineman, 2014, pp. 138
See also
: ImpactThickness, BladeStress
References and(), AxialTurbineDesign(), CreateLatexTable(), DisplayLatexTable(), and plus().
Referenced by AxialTurbineDesign().
BladeSpacing()
function BladeSpacing (in alpha1, in alpha2)
Form
 sB = BladeSpacing( alpha1, alpha2 )
Inputs
 alpha1
 alpha2
Outputs
 sB
BladeStress()
function BladeStress (in u, in rH, in rT, in rhoM, in aTOAH)
Blade stress with linear taper. Type BladeStress for a demo.
Form
 sigma = BladeStress( u, rH, rT, rhoM, aTOAH )
Inputs
 u       (1,:) Velocity (m/s)
 rH      (1,1) Hub radius (m)
 rT      (1,1) Tip radius (m)
 rhoM       (1,1) Material density (kg/m^3)
 aTOAH   (1,1) Area ratio tip to hub
Outputs
 sigma   (1,:) Stress (MPa)
Reference: S.L. Dixon and C.A. Hall, "Fluid Mechanics and Thermodynamics of Turbomachinery, 7th Edition," Butterworth-Heineman, 2014, pp. 152.
References and(), BladeStress(), Demo(), and Plot2D().
Referenced by BladeStress().
BlckBody()
function BlckBody ()
Form
 [alpha, epsilon] = BlckBody
Inputs
Outputs
 alpha      (1,1)  Absorptivity
 epsilon    (1,1)  Emissivity
References and(), and BlckBody().
Referenced by BlckBody().
Brayton()
function Brayton (in d)
d.r is the pressure ratio of the compressor. Higher r means higher thermal efficiency but more mass. Typical closed-loop Brayton cycles for space applications have r = 2. The default working fluid is a 70/30 (molar ratio) mixture of Helium and Xenon.
The function draws a heat engine diagram with pressures and temperatures labeled, if there are no outputs or the doPlot flag is true.
Type Brayton for a demo.
Form
 d = Brayton( d )
Inputs
 d (.) Input data structure
       .T3     (1,1) Turbine Inlet temperature (deg-K)
       .T1     (1,1) Compressor Inlet Temp temperature (deg-K)
       .P1     (1,1) Compressor Inlet Pressure (Atm)
       .pHeat  (1,1) Heat input (kW)
       .r      (1,1) Pressure ratio of compressor
       .name   (1,:) Name of gas or mixture
       .nc     (1,1) Compressor efficiency
       .nt      (1,1) Turbine efficiency
       .nPX     (1,1) Exchanger pressure drop an empirically-determined factor
       .gamma   (1,1) Specific heat ratio
       .cP      (1,1) Specific heat (J/kg-K)
       .molWt   (1,1) Molecular Weight of the mixture in (g/mol)
       .image  (1,1) Image for diagram, default BraytonCycle.png
Outputs
 d (.) Data structure additions
       .P2   (1,1) Compressor outlet (Pa)
       .T2   (1,1) Compressor outlet (deg-K)
       .P3   (1,1) Heat exchanger inlet (Pa)
       .T3   (1,1) Heat exchanger inlet (deg-K)
       .P3   (1,1) Turbine inlet (Pa)
       .P4   (1,1) Gas cooler inlet (Pa)
       .T4   (1,1) Gas cooler inlet (deg-K)
       .n    (1,1) Brayton cycle efficiency.
       .mDot    (1,1)   Mass flow (kg/s)
       .wC  (1,1) Compressor work (kW)
       .wT  (1,1) Turbine work (kW)
       .wNet (1,1) Net work (kW)
References: Barrett and Reid, "System Mass Variation and Entropy" Generation (2003). MIT Pebble-bed reactor. Wright, Lipinski, Vernon, and Sanchez, "Closed Brayton Cycle Power Conversion Systems" (2006). Wilson and Korakianitis, "The Design of High-Efficiency Turbomachinery and Gas Turbines," Second Edition, (2014).
d.r is the pressure ratio of the compressor. Higher r means higher thermal efficiency but more mass. Typical closed-loop Brayton cycles for space applications have r = 2. The default working fluid is a 70/30 (molar ratio) mixture of Helium and Xenon.
The function draws a heat engine diagram with pressures and temperatures labeled, if there are no outputs or the doPlot flag is true.
Type Brayton for a demo.
Form
 d = Brayton( d )
Inputs
 d (.) Input data structure
       .T3     (1,1) Turbine Inlet temperature (deg-K)
       .T1     (1,1) Compressor Inlet Temp temperature (deg-K)
       .P1     (1,1) Compressor Inlet Pressure (Atm)
       .pHeat  (1,1) Heat input (kW)
       .r      (1,1) Pressure ratio of compressor
       .name   (1,:) Name of gas or mixture
       .nc     (1,1) Compressor efficiency
       .nt      (1,1) Turbine efficiency
       .nPX     (1,1) Exchanger pressure drop an empirically-determined factor
       .gamma   (1,1) Specific heat ratio
       .cP      (1,1) Specific heat (J/kg-K)
       .molWt   (1,1) Molecular Weight of the mixture in (g/mol)
       .image  (1,1) Image for diagram, default BraytonCycle.png
Outputs
 d (.) Data structure additions
       .P2   (1,1) Compressor outlet (Pa)
       .T2   (1,1) Compressor outlet (deg-K)
       .P3   (1,1) Heat exchanger inlet (Pa)
       .T3   (1,1) Heat exchanger inlet (deg-K)
       .P3   (1,1) Turbine inlet (Pa)
       .P4   (1,1) Gas cooler inlet (Pa)
       .T4   (1,1) Gas cooler inlet (deg-K)
       .n    (1,1) Brayton cycle efficiency.
       .mDot    (1,1)   Mass flow (kg/s)
       .wC  (1,1) Compressor work (kW)
       .wT  (1,1) Turbine work (kW)
       .wNet (1,1) Net work (kW)
References: Barrett and Reid, "System Mass Variation and Entropy" Generation (2003). MIT Pebble-bed reactor. Wright, Lipinski, Vernon, and Sanchez, "Closed Brayton Cycle Power Conversion Systems" (2006). Wilson and Korakianitis, "The Design of High-Efficiency Turbomachinery and Gas Turbines," Second Edition, (2014).
References and(), Brayton(), DefaultDataStructure(), Demo(), and Pressure().
Referenced by Brayton(), BraytonIdeal(), BraytonWithRecuperator(), CycleDesign(), HeXeMixture(), and SizeTurbineAndCompressor().
BraytonIdeal()
function BraytonIdeal (in gamma, in pR, in cP, in t3, in qR, in effTC)
Computes the efficiency, mass flow and temperatures. This power plant has a single compressor and turbine. Both are 100% efficient, unless eff is entered
The cycle points are
1 - compressor inlet 2 - compressor outlet 3 - turbine inlet 4 - turbine outlet
Note: t2 = t4 in this ideal cycle.
Type BraytonIdeal for a demo comparing helium, nitrogen and carbon dioxide.
Form
 [eff, mDot, t] = BraytonIdeal( gamma, pR, cP, t3, qR, effTC )
Inputs
 gamma    (1,1)  Ratio of specific heats
 pR       (1,:)  Pressure ratio
 t3       (1,1)  Temperature at end of combustor  (deg-K)
 cP       (1,1)  Specific heat constant pressure J/kg deg-K
 qR       (1,1)  Heat input (W)
 effTC    (.)    Efficiency data structure
                 .turbine    (1,1) Turbine efficiency
                 .compressor (1,1) Compressor efficiency
Outputs
 eff      (1,1)  Thermal efficiency
 mDot     (1,:)  Mass flow (kg/s)
 t        (4,:)  Cycle temperatures (deg-K)
References: N. Ait Messaoudene, "Thermal Power Plants," ME 435, University of Hail.
References and(), Brayton(), BraytonIdeal(), Demo(), length(), Plot2D(), Pressure(), and zeros().
Referenced by BraytonIdeal().
BTUToJoule()
function BTUToJoule (in bTU)
Type BTUToJoule for a demo.
Form
 j = BTUToJoule(bTU)
Inputs
 bTU   (1,:) BTU
Outputs
 j     (1,:) Joules
See also
JouleToBTU.
References BTUToJoule(), JouleToBTU(), and Plot2D().
Referenced by BTUToJoule(), and JouleToBTU().
CentrifugalCompressor()
function CentrifugalCompressor (in d)
Type CentrifugalCompressor for a demo from the reference.
Form
 CentrifugalCompressor;     % demo
 d = CentrifugalCompressor;     % data structure
 d = CentrifugalCompressor( d )
Inputs
 d              (.)    Input data structure
                       .d2 (1,1) Outlet diameter of the impeller
Outputs
 d              (.)    Augmented data structure
Reference: Mattingly, Jack D. ,"Elements of Gas Turbine Propulsion," McGraw Hill, 1996, pp 677-683.
References CentrifugalCompressor(), DefaultDataStructure(), MachFromMassFlowParameter(), MassFlowParameter(), MolWt2R(), and zeros().
Referenced by CentrifugalCompressor().
CycleDesign()
function CycleDesign (in fXe, in heat, in t1, in t4, in p1, in a, in r, in n, in pR, in nC, in nT, in nR, in doPlot)
If there are no outputs or doPlot is true this will create figures.
Form
[dOut,dP] = CycleDesign(fXe,heat,t1,t4,p1,a,r,n,pR,nC,nT,nR,doPlot)
Inputs
 fXe     (1,1) Mass fraction of Xenon in Xe/He mixture
 heat    (1,1) Heat input (kW)
 T1      (1,1) Compressor Inlet Temp temperature (deg-K)
 T4      (1,1) Turbine Inlet temperature (deg-K)
 P1      (1,1) Compressor Inlet Pressure (Atm)
 a       (1,1) total pipe area, m^2
 r       (1,1) pipe radius
 n       (1,1) number of pipes
 pR      (1,1) Pressure ratio of compressor
 nC      (1,1) Compressor efficiency
 nT      (1,1) Turbine efficiency
 nR      (1,1) Recuperator ratio
 doPlot  (1,1) Create plots (with output)
Outputs
 dOut    (.)   Output
 dP      (1,1) Pressure drop of P2
See also
HeatTransferCoeffTaylor, HeXeMixture, BraytonWithRecuperator
References abs(), and(), Brayton(), BraytonWithRecuperator(), CycleDesign(), Demo(), HeatTransferCoeffTaylor(), HeXeMixture(), Initialize(), isempty(), length(), Pressure(), and RHS().
Referenced by CycleDesign().
DrawThermalPlugIn()
function DrawThermalPlugIn (in action, in hFig, in modifier)
Shows each node and a line where there is conductivity or radiative heat transfer between nodes. First you initialize the routine
 tag = DrawThermalPlugIn( 'initialize',g  )
where g is a CAD model with the added field thermalNet which is struct with fields, b, the input matrix, k, the thermal conductivity matrix, and l, the radiative coupling matrix. Each matrix is n-by-n where n is the number of components.
To update write
 DrawThermalPlugIn( 'update', tag, t )
where t(k) is the temperature of component k.
Each node is colored based on the temperature. You can set the maximum temperature by writing
 DrawThermalPlugIn( 'set max temp', tag, tMax )
Has a built-in demo using ThermalCube.mat
Form
 DrawThermalPlugIn( action, modifier )
Inputs
 action      (1,:)  Action
 modifier    (1,:)  Modifier to the action
Outputs
 tag         (1,:)  The tag that identifies the display
See also
: ThermalCube, ThermalColorMap
References and(), CloseFigure(), DrawThermalPlugIn(), get(), GetH(), GetNewTag(), Icosahedron(), Initialize(), isempty(), length(), PutH(), set(), ThermalColorMap(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by DrawThermalPlugIn().
EmittanceParallelPlates()
function EmittanceParallelPlates (in e)
 The heat flux through the plates is then sigma T^4/nB.
 The rest is reflected.
 Type EmittanceParallePlates for a demo.
Form
 nB = EmittanceParallelPlates( e )
Inputs
 e           (1,:)    Plate emittances
Outputs
 nB          (1,1)    Number of black plates
References: Van Vliet, R. M., Passive Temperature Control in the Space Environment, MacMillan, 1965, pp. 78-86
References Demo(), EmittanceParallelPlates(), length(), and zeros().
Referenced by EmittanceParallelPlates().
FrictionLaminar()
function FrictionLaminar (in rE, in type)
Turbulent flow generally happens for rE > 1e4.
Type FrictionLaminar for a demo.
Form
 f = FrictionLaminar( rE, type )
Inputs
 rE        (1,:)    Reynold's number
 type      (1,:) 'square', 'circular' 'flat plates'
Outputs
 f         (1,:)    Friction factor
Reference: L. C. Thomas, "Heat Transfer," Prentice-Hall, 1992, p. 465-466.
References Demo(), Friction(), FrictionLaminar(), Plot2D(), and square().
Referenced by FrictionLaminar(), and PressureDropChannel().
FSolarPanelThermal()
function FSolarPanelThermal (in x, in d)
 This returns a cost for the deviations of the front/back solar panel
 temperature equations from zero.
Form
 y = FSolarPanelThermal( x, d )
Inputs
 x               (2,1) [tF;tB] Front and back temperatures
 d               (1,1) Data structure
                       .alpha (1,1) Absorptivity
                       .epsF  (1,1) Front emissivity
                       .epsB  (1,1) Back emissivity
                       .etaP  (1,1) Fraction of flux to power
                       .k     (1,1) Front/back conductivity
                       .s     (1,1) Solar flux
Outputs
 y               (1,1) Cost
References abs(), and(), and SolarPanelThermal().
Referenced by SolarPanelThermal().
GrayBody()
function GrayBody (in alphaOrEpsilon)
Form
 [alpha, epsilon] = GrayBody( alphaOrEpsilon )
Inputs
 alphaOrEpsilon  (1,:) Either alpha or epsilon
Outputs
 alpha           (1,:) Absorptivity
 epsilon         (1,:) Emissivity
References: Van Vliet, R. M., Passive Temperature Control in the Space Environment, MacMillan, 1965, p. 5.
References and().
HeatExchanger()
function HeatExchanger (in d)
The output data structure has all the value in the input plus values computed in the function.
Type HeatExchanger for demos with Helium/Xenon and Helium.
Form
 [d, l] = HeatExchanger( d )
Inputs
 d              (.)    Input data structure
                       .q         W
                       .tInlet    K
                       .tOutlet   K
                       .mach
                       .pressure  ATM
                       .cP
                       .gamma
                       .molWt
Outputs
 d              (.)    Output data structure
                       .mDot (1)  Mass flow
                       .u    (1)  Speed
                       .rhoI (1)  Inlet density
                       .rhoO (1)  Outlet density
                       .areaChannel
                       .hChannel
 l              {:,3}  Latex formatted output
References and(), HeatExchanger(), and plus().
Referenced by HeatExchanger().
HeatExchangerWithLosses()
function HeatExchangerWithLosses (in d, in doPlot)
A flat plate heat exchanger. One side has a uniform thermal input. The other has radiation heat loss. k may be a pointer to a function
 k = fun( tB, d.kData )
that returns the total conductance.
Type HeatExchangerWithLosses for a demo.
Form
 d = HeatExchangerWithLosses;
 [tB,tS4,q4] = HeatExchangerWithLosses( d, doPlot )
Inputs
 d       (.)    Data structure
             .l      (1,1) Length (m)
             .k      (1,1) Thermal conductance (W/m2 deg-K), or handle
             .kData  (.)   Data structure to data for k, optional
             .qDot   (1,1) Heat flux (W/m)
            .n      (1,1) Number of divisions in length
             .mDot   (1,1) Cooling gas flow (kg/s)
            .cP     (1,1) Gas heat capacity  (J/kg deg-K)
                .eps    (1,1) Emissivity of the shell
             .tB0    (1,1) Initial duct temperature (deg-K)
             .c      (1,1) Circumference, perimeter of channel receiving flux
 doPlot
Outputs
 tB      (1,:)  Gas temperature (deg-K)
 tS4     (1,:) Wall temperature (deg-K)
 q4      (1,:) Radiative heat flux (W/m^2)
References DefaultDataStructure(), Demo(), HeatExchangerWithLosses(), length(), RHS(), RK4(), and zeros().
Referenced by HeatExchangerWithLosses().
HeatFP()
function HeatFP (in q2, in alpha2, in e2, in e1, in k, in fC, in tau)
 given that the heat input is on face 2. Both sides emit to free space.
Form
 [t1, t2] = HeatFP( q2, alpha2, e2, e1, k, fC, tau )
Inputs
 q2          (1,1)   Heat flux on face 2  (watts/m^2)
 alpha2      (1,1)   Absorptivity of face 2
 e2          (1,1)   Emissivity of face 2
 e1          (1,1)   Emissivity of face 1
 k           (1,1)   Conductivity between the faces (watts/deg-K)
 fC          (1,1)   Fraction of incoming heat converted to electricity
 tau         (1,1)   Fractional error
Outputs
 t1          (1,1)   Temperature of face 1
 t2          (1,1)   Temperature of face 2
References abs().
HeatShieldCoating()
function HeatShieldCoating (in name)
 'name' is not case sensitive. All values are averages.
 If no input is entered it will return the available materials.
Form
 [alpha, epsilon, ratio] = HeatShieldCoating( name )
Inputs
 name        (1,:)    Name
Outputs
 alpha       (1,1)    Absorptivity
 epsilon     (1,1)    Emissivity
 ratio       (1,1)    alpha/epsilon
References: Van Vliet, R. M., Passive Temperature Control in the Space Environment, MacMillan, 1965, p. 108.
HeatTransferChannel()
function HeatTransferChannel (in d, in doPlot)
The output data structure has all the values in the input plus values computed in the function. The latex formatted output can be saved to a file using CreateLatexTable or printed in the command window using DisplayLatexTable.
Type HeatTransferChannel for a demo with a 70% Helium/ 30% Xenon mixture.
Form
 [d, l] = HeatTransferChannel( d, doPlot )
Inputs
 d              (.)    Input data structure
                       .name       (1,:)   Name
                       .length      (1,1)   Channel length (m)
                       .w          (1,1)   Channel width (m)
                       .h          (1,1)   Channel height (m)
                       .q          (1,1)   Total heat flux (MW)
                       .cP         (1,1)   Heat capacity (J/kg-K)
                       .gamma      (1,1)   Ratio of specific heats
                       .tInlet     (1,1)   Inlet temperature (deg-K)
                       .tOutlet    (1,1)   Outlet temperature (deg-K)
                       .pressure   (1,1)   Inlet pressure (Atm)
                       .gas        {1,2*n) {'name' fraction ...}
                       .kC         (1,1)   Inlet pressure drop
                                           coefficient
                       .kE         (1,1)   Outlet pressure drop
                                           coefficient
Outputs
 d              (.)    Additions to the data structure
                       .mDot    (1,1)   Mass flow rate (kg/s)
                       .u           (1,1)   Velocity (m)
                       .qChannel    (1,1)   Heat flux (W/m)
                       .dP       (1,1)   Pressure drop (Atm)
                       .area     (1,1)   Channel area (m^2)
                       .d        (1,1)   Channel dimension (m)
 l              {:,3}  Latex formatted output
References AbsoluteViscosity(), and(), CreateLatexTable(), Demo(), DisplayLatexTable(), HeatTransferChannel(), HeatTransferCoeff(), length(), NusseltLaminar(), NusseltTurbulent(), Plot2D(), plus(), PrandtlNumber(), Pressure(), PressureDropChannel(), ReynoldsNumberKinematic(), RFromCPAndGamma(), and ThermalConductivity().
Referenced by HeatTransferChannel().
HeatTransferCoeff()
function HeatTransferCoeff (in nU, in k, in d)
Type HeatTransferCoeff for a demo.
Form
 h = HeatTransferCoeff( nU, k, d )
Inputs
 nU (1,:)   Nusselt number
 k      (1,:)   Conductivity (W/m deg-K)
 d      (1,:)   Diameter (m)
Outputs
 h      (1,:)    Heat transfer coefficient (W/m^2 deg-K)
Reference: L. C. Thomas, "Heat Transfer," Prentice-Hall, 1992, p. 477.
References HeatTransferCoeff(), and Plot2D().
Referenced by HeatTransferChannel(), HeatTransferCoeff(), and SizeTurbineAndCompressor().
HeatTransferCoeffTaylor()
function HeatTransferCoeffTaylor (in u, in d, in l)
The Nusselt exponent is limited for z/d < 1 to 1. The correlation is only valid for z/d > 1.
Type HeatTransferCoeffTaylor for a demo
Default properties are for a He/Xe mixture and an N2 gas.
Form
 d = HeatTransferCoeffTaylor
 [h,nU,rE,rho,pR,dP,hAve] = HeatTransferCoeffTaylor(u,d,l)
Inputs
 u     (1,1) Velocity (m/s)
 d     (.)   Data structure
             .p      (1,1) Pressure (N/m^2)
             .mDot   (1,1) Mass flow rate (kg/s)
             .tB     (1,1) Bulk temperature (K)
             .tW     (1,1) Wall temperature (K)
             .mu     (1,1) Dynamic viscosity (Pa s)
             .l      (1,1) Channel length (m)
             .d      (1,1) Channel diameter (m)
             .a      (1,1) Channel area (m^2)
             .lambda (1,1) Heat transfer coefficient W/(m K)
             .cP     (1,1) Heat capacity (J/(kg K)
             .m      (1,1) Molecular weight (kg/mol)
 l     (1,:) Points for computing h
Outputs
 h     (1,:)    Heat transfer coefficient (W/m^2 K)
 nU    (1,:) Nusselt number
 rE    (1,1) Reynold's number
 rho   (1,1) Density (kg/m^3)
 pR    (1,:) Prandtl number
 dP    (1,1) Pressure drop/pressure
 hAve  (1,1) Average heat coefficient
Reference: Ersheng You, Lei Shi, Zuoyi Zhang,"Thermodynamics
Properties of Binary Gas Mixtures for Brayton Space Nuclear Power System," Proceedings of the HTR 2014 Weihai, China, October 27-31, 2014 Paper HTR2014-61286.
References and(), DefaultDataStructure(), Demo(), HeatTransferCoeffTaylor(), length(), MolWt2R(), PrandtlNumber(), Pressure(), and ReynoldsNumber().
Referenced by CycleDesign(), and HeatTransferCoeffTaylor().
HeXeMixture()
function HeXeMixture (in fXe)
Form
 [cP,gamma,mu,fHe] = HeXeMixture(fXe)
Inputs
 fXe   (1,:)   Mass fraction of Xenon in mixture
Outputs
 cP    (1,:)   Specific heat (J/kg-K)
 gamma (1,:)   cP/cV
 mu    (1,:)   Molecular weight (kg/mole)
 fHe   (1,:)   Fraction of Helium in mixture
 R     (1,:)   Gas constant
Reference: Closed Brayton Cycle Power Conversion Systems for Nuclear Reactors: Modeling, Operations, and Validation Steven A. Wright, Ronald J. Lipinski, Milton E. Vernon, Travis Sanchez SANDIA REPORT, SAND2006-2518 April 2006
References and(), Brayton(), Demo(), and HeXeMixture().
Referenced by CycleDesign(), and HeXeMixture().
ImpactThickness()
function ImpactThickness (in material, in m, in v, in a, in fS)
Form
 t = ImpactThickness( material, m, v, a, fS )
Inputs
 material
 m
 v
 a
 fS
Outputs
 t
Isothermal()
function Isothermal (in el, in center, in d, in jD)
 This is useful for preliminary estimates of radiator area.
 The spacecraft illuminated area is aS with radiators of area aR.
 You enter the orbit and the center (any of the nine planets or the sun)
 plus the orbital elements and spacecraft properties. The function will
 compute the temperature as a function of time.
 This function includes solar, albedo and radiation.
 In a heliocentric orbit planetary encounters are ignored. In planetary
 orbit albedo, planetary radiation and eclipses are modeled.
 For a demo of a geosynchronous spacecraft type Isothermal.
Form
 t = Isothermal( el, center, d, jD )
Inputs
 el       (1,6) Orbital elements [a i W w e M]
 center   (1,:) Name of center (major planets and sun)
 d        (1,1) Data structure
                .aR    (1,1) Radiator area (m^2)
                .aS    (1,1) Spacecraft illuminated area (m^2)
                .alpha (1,1) Spacecraft absorption (0-1)
                .epsR  (1,1) Radiator emissivity (0-1)
                .t0    (1,1) Initial Temperature (deg-K)
                .cP    (1,1) Average specific heat of the spacecraft (J/kg deg-K)
                .m     (1,1) Spacecraft mass  (kg)
                .p     (1,n) Power consumption (W)
 jD       (1,n) Julian dates
Outputs
 t        (1,n) Temperatures (deg-K)
References: Agrawal, B. ,"Design of Geosynchronous Spacecraft," Prentice-Hall, 1986, pp. 281-283
References and(), CEcl2Eq(), Constant(), Date2JD(), EarthAlb(), EarthRad(), Eclipse(), Isothermal(), JD2T(), length(), Mag(), Planets(), plus(), RK4(), RVFromKepler(), SolarFlx(), SolarSys(), Unit(), vector(), and zeros().
Referenced by Isothermal(), and IsothermalHelio().
IsothermalHelio()
function IsothermalHelio (in r, in qECIToBody, in nEclipse, in mass, in heat, in temp, in d)
Calculates the temperature derivative.
Form
 tempDot    = IsothermalHelio( qECIToBody, nEclipse, mass, heat, temp, d )
Inputs
 r           (3,1) Vector to sun
 qECIToBody (4,1) Quaternion
 nEclipse       (1,1) Eclipse
 mass        (1,1) Mass (kg))
 heat        (1,1) Heat generated internally (W)
 temp        (1,1) Temperature (deg-K)
 d              (.)   Data structure
                    .cP     (1,1) Specific heat (J/kg-deg-K)
Outputs
 tempDot   (1,1) Temperature derivative (deg-K/s)
References abs(), Constant(), DefaultDataStructure(), Dot(), Eclipse(), Isothermal(), Mag(), and QForm().
IsothermalLunar()
function IsothermalLunar (in el, in d, in jD)
 This is useful for preliminary estimates of radiator area.
 The spaceccraft illuminated area is aS with radiators of area aR.
 You enter the orbital elements and spacecraft properties. The function will
 compute the temperature as a function of time.
 This function includes solar, albedo and radiation. Both lunar and
 earth eclipses are modeled.
 Type IsothermalLunar for a demo.
Form
 IsolthermalLunar;
 t = Isothermal( el, d, jD )
Inputs
 el       (1,6) Orbital elements [a i W w e M]
 d        (1,1) Data structure
                .aR    (1,1) Radiator area (m^2)
                .aS    (1,1) Spacecraft illuminated area (m^2)
                .alpha (1,1) Spacecraft absorption (0-1)
                .epsR  (1,1) Radiator emissivity (0-1)
                .t0    (1,1) Initial Temperature (deg-K)
                .cP    (1,1) Average specific heat of the spacecraft (J/kg deg-K)
                .m     (1,1) Spacecraft mass  (kg)
                .p     (1,:) Internal power consumption (W)
 jD       (1,n) Julian dates
Outputs
 t        (1,n) Temperature (deg-K)
References and(), Constant(), Date2JD(), Demo(), DupVect(), EarthAlb(), EarthRad(), Eclipse(), IsothermalLunar(), length(), Mag(), MoonV1(), RK4(), RVFromKepler(), SunV1(), Unit(), and zeros().
Referenced by IsothermalLunar().
JouleToBTU()
function JouleToBTU (in j)
Type JouleToBTU for a demo.
Form
 bTU = JouleToBTU(j)
Inputs
 j   (1,:) Joules
Outputs
 bTU (1,:) BTU
See also
BTUToJoule.
References BTUToJoule(), JouleToBTU(), and Plot2D().
Referenced by BTUToJoule(), and JouleToBTU().
KinematicViscosity()
function KinematicViscosity (in mu, in rho)
Type KinematicViscosity for a demo.
Form
 nu = KinematicViscosity( mu, rho )
Inputs
 mu    (1,:)   Viscosity (kg/m-s)
 rho   (1,:)   Density   (kg/m^3)
Outputs
 nu    (1,:)   Kinematic viscosity (m^2/s)
Reference: L. C. Thomas, "Heat Transfer," Prentice-Hall, 1992, p. 477.
References KinematicViscosity(), and Plot2D().
Referenced by KinematicViscosity(), and RHSLiftingSatellite().
LambertL()
function LambertL (in theta, in E)
 Type LambertL for a demo.
 Since version 1.
Form
 dE = LambertL( theta, E )
Inputs
 theta  (1,:) Angle (rad)
 E       (1,:) Total emissive power
Outputs
 dE      (1,:) Flux per unit solid angle (dE/dw)
References: Thomas, L. C., Heat Transfer, Prentice-Hall, 1992, pp. 271-273.
LiquidMetalProps()
function LiquidMetalProps (in metal, in t)
Outputs liquid metal properties. Type LiquidMetalProps for a dem of Lithium, Sodium and LBE (lead-bismuth).
Form
 [lambda,mu,rho,cP] = LiquidMetalProps(metal,t)
Inputs
 metal   (1,:) Metal (Na, Li or LBE)
 t       (1,:) Temperature (deg-K)
Outputs
 lambda  (1,:) Thermal conductivity (W/m K)
 mu      (1,:) Dynamics viscosity (Pa s)
 rho     (1,:) Density (kg/m^3)
 cP      (1,:) Heat Capacity (J/kg K)
Reference: Y.Liu and P. Teng, "Numerical investigation on heat transfer characterization of liquid lithium metal in pipe," May 2021, http://just.ustc.edu.cn.
References and(), Demo(), length(), and LiquidMetalProps().
Referenced by LiquidMetalProps().
NusseltDeveloping()
function NusseltDeveloping (in x, in D, in rE, in isHFD)
This correlation was developed for air in short smooth tubes.
Form
 fN = NusseltDeveloping( rE, pR )
Inputs
 x      (1,:)   Distance along pipe
 D      (1,1)   Diameter of pipe
 rE     (1,:)   Reynolds number
 isHFD   (1)    Whether a hydrodynamic calming section is used, in which case
                HFD conditions exist from the start.
Outputs
 fN    (1,:)     Factor multiplying the Nusselt number
Reference: L. C. Thomas, "Heat Transfer," Prentice-Hall, 1992, p. 471.
References length(), NusseltDeveloping(), Plot2D(), and zeros().
Referenced by NusseltDeveloping().
NusseltLaminar()
function NusseltLaminar (in g, in type)
Developing laminar flow of air in a circular pipe with uniform wall temperature.
Type NusseltLaminar for a demo.
Form
 nU = NusseltLaminar( g, type )
Inputs
 g     (1,:)   x/D/(RePr)
 type  (1,:)   hfd or tfd
               hfd - hydrodynamic fully developed flow (default)
               tfd - thermal fully developed flow
Outputs
 nU    (1,:)    Nusselt number
Reference: L. C. Thomas, "Heat Transfer," Prentice-Hall, 1992, p. 470.
References Demo(), NusseltLaminar(), and Plot2D().
Referenced by HeatTransferChannel(), NusseltLaminar(), and SizeTurbineAndCompressor().
NusseltTurbulent()
function NusseltTurbulent (in rE, in pR)
Turbulent flow generally happens for rE > 1e4.
Type NusseltTurbulent for a demo.
Form
 nU = NusseltTurbulent( rE, pR )
Inputs
 rE    (1,:)   Reynolds number
 pR    (1,:)   Prandtl number
Outputs
 nU    (1,:)    Nusselt number
Reference: L. C. Thomas, "Heat Transfer," Prentice-Hall, 1992, p. 471.
References NusseltTurbulent(), Plot2D(), and PrandtlNikuradse().
Referenced by HeatTransferChannel(), NusseltTurbulent(), and SizeTurbineAndCompressor().
OptimalMLIDensity()
function OptimalMLIDensity (in tH, in tC, in d)
Type OptimalMLIDensity for a demo
Form
 d = OptimalMLIDensity;          % data structure
 [nD,q,C] = OptimalMLIDensity(tH,tC,d)
Inputs
 tH (1,1)  Hot temperature
 tC (1,1)  Cold temperature
 d   (.)   Input data structure
           .n      (1,1) Number of layers
           .cS     (1,1) Conduction coefficient
           .cR     (1,1) Radiative coefficient
           .gamma  (1,1) Conduction exponent
           .epsTR  (1,1) Effective emissivity
Outputs
 nD  (1,:)  MLI density (layers/cm)
 q   (1,:)  Heat flux (W/m^2)
 C   (1,:)  Conductance (W/m^2 K)
Reference: C. W. Keller, G. R. C. Cunningham, and A. P. Glassford. "Final Report Thermal Performance of Multilayer Insulations" Technical Report NASA CR-134477, Lockheed Missiles & Space Company, April 1974.
References and(), DefaultDataStructure(), Demo(), NewFig(), OptimalMLIDensity(), XLabelS(), and YLabelS().
Referenced by OptimalMLIDensity(), and RadiationShield().
PanelThermalModel()
function PanelThermalModel (in g, in flux)
 It always uses the side with the largest area.
Inputs
 g               (1,1)  CAD data structure
 flux            (1,1)  Solar flux
Outputs
 t               (:,4)  [t on sun, t standby sun, t on eclipse,
                        t standby eclipse]
 p               (:,2)  [p on, p standby]
References Eclipse(), length(), Mag(), Panel(), and zeros().
PlanckL()
function PlanckL (in T, in lambda)
Also computes the total flux over the range of wavelengths.
Type PlanckL for a demo.
Form
 PlanckL
 [q, lambda, qTotal] = PlanckL( T, lambda )
Inputs
 T            (1,n) Temperature (deg-K)
 lambda       (n,m) Wavelength vector (micro-meters)
Outputs
 q            (n,m) Black body flux density (watts/m^2-microns)
 lambda       (n,m) Wavelength vector (micro-meters)
 qTotal       (n,1) Total flux (watts/m^2)
References: Thomas, L. C., Heat Transfer, Prentice-Hall, 1992, p. 265
References Wavelength().
PlotThermal()
function PlotThermal (in q, in temp, in t, in g, in units)
Form
 PlotThermal( q, temp, t, g, units )
Inputs
 q              (:,:)  Flux. Each row is a component
 temp           (:,:)  Temperature. Each row is a component
 t              (1,:)  Time (sec)
 g              (1,1)  Spacecraft data structure
 units          {2}    {'Flux units' 'Temperature units' }
Outputs
 None
References and().
PrandtlNikuradse()
function PrandtlNikuradse (in rE)
Turbulent flow generally happens for rE > 1e4.
Type PrandtlNikuradse for a demo. This compares the explicit formula with the Prandtl/Nikuradse equation.
Form
 f = PrandtlNikuradse( rE )
Inputs
 rE   (1,:) Reynold's number
Outputs
 f     (1,:)    Fanning friction factor
Reference: L. C. Thomas, "Heat Transfer," Prentice-Hall, 1992, p. 471.
References Demo(), Friction(), isempty(), length(), Plot2D(), PrandtlNikuradse(), RHS(), and zeros().
Referenced by NusseltTurbulent(), PrandtlNikuradse(), and PressureDropChannel().
PrandtlNumber()
function PrandtlNumber (in mu, in cP, in k)
Pr << 1, thermal diffusivity dominates. Pr >> 1, momentum diffusivity dominates.
Type PrandtlNumber for a demo.
Form
 pR = PrandtlNumber( mu, cP, k )
Inputs
 mu    (1,:) Viscosity of the gas (kg/m-s)
 cP    (1,:) Heat capacity (J/kg)
 k     (1,:) Thermal conductivity of the gas (W/(m K))
Outputs
 pR    (1,:)    Prandtl Number
Reference: L. C. Thomas, "Heat Transfer," Prentice-Hall, 1992, p. 471.
References and(), Demo(), length(), Plot2D(), and PrandtlNumber().
Referenced by HeatTransferChannel(), HeatTransferCoeffTaylor(), PrandtlNumber(), and SizeTurbineAndCompressor().
PressureDropChannel()
function PressureDropChannel (in d)
Type PressureDropChannel for a demo.
Form
 dP = PressureDropChannel( d )
Inputs
 d       (.)     Input data structure
                 .length    (1,1)   Channel length (m)
                 .w          (1,1)   Channel width or diameter (m)
                    .h          (1,1)   Channel height (m)
                 .u          (1,1)   Velocity (m/s)
                 .cP         (1,1)   Heat capacity (J/kg-K)
                 .gamma      (1,1)   Ratio of specific heats
                 .tInlet     (1,1)   Inlet temperature (deg-K)
                .tOutlet    (1,1)   Outlet temperature (deg-K)
                 .pressure   (1,1)   Inlet pressure (ATM)
                .gas        {1,2*n) {'name' fraction ...}
                    .tube       (1,:)   'square', 'circular', 'flat plate'
Outputs
 dP     (1,1)   Pressure drop (Pa)
Reference: L. C. Thomas, "Heat Transfer," Prentice-Hall, 1992, p. 471.
References AbsoluteViscosity(), Demo(), FrictionLaminar(), isempty(), length(), Plot2D(), PrandtlNikuradse(), Pressure(), PressureDropChannel(), ReynoldsNumberKinematic(), RFromCPAndGamma(), RHS(), RK4(), square(), and zeros().
Referenced by HeatTransferChannel(), PressureDropChannel(), and SizeTurbineAndCompressor().
RadBFp()
function RadBFp (in epsilon, in T1, in Tn)
 Since version 1.
Form
 [Nb, q] = RadBFp( epsilon, T1, Tn )
Inputs
 epsilon     (1,:)  Vector of emissivities
 T1          (1,1)  Temperature of first surface (K)
 Tn          (1,1)  Temperature of nth surface (K)
Outputs
 Nb          (1,1)  Equivalent black plates
 q           (1,1)  Heat flux
References: Van Vliet, Passive Temperature Control in the Space Environment, MacMillan, 1965, pp. 78-86.
References length(), and zeros().
RadDa()
function RadDa (in T, in epsilon, in da)
 Type RadDa for a demo.
Form
 q = RadDa( T, epsilon, da )
Inputs
 T              (1,:) Temperature (deg-K)
 epsilon        (1,1) Emissivity
 da             (1,1) incremental area (m^2)
Outputs
 q              (1,:) Heat flux (watts)
References: Van Vliet, R. M., Passive Temperature Control in the Space Environment, MacMillan, 1965, p. 3.
References length(), Plot2D(), and RadDa().
Referenced by RadDa().
RadiationShapeFactor()
function RadiationShapeFactor (in w1, in w2, in l, in units)
w1, w2 and L need to be in the same units.
TypeRadiationShapeFactors for a demo.
Form
 f = RadiationShapeFactor( w1, w2, l, units )
Inputs
 w1    (1,1)    Plate one width
 w2    (1,1) Plate two width
 l     (1,:) Distance
 units (1,:) Units for plot
Outputs
 f  (1,:) Shape factor
References and(), Demo(), Plot2D(), and RadiationShapeFactor().
Referenced by RadiationShapeFactor().
RadiationShield()
function RadiationShield (in d)
Uses fzero to solve for the surface temperature.
Type RadiationShield for a demo. Surface coefficients are white paint.
Form
 d = RadiationShield       % data structure
 [tS, tI] = RadiationShield( d )
Inputs
 d   (.) Input data structure
         .n      (1,1) Number of layers of MLI
         .cS     (1,1) Conduction coefficient
         .cR     (1,1) Radiative coefficient
         .gamma  (1,1) Conduction exponent
         .epsTR  (1,1) Effective emissivity
         .alphaS (1,1) Surface absorption coefficient
         .epsS   (1,1) Surface emittance  coefficient
         .epsI   (1,1) Emissivity of inner wall
         .qS     (1,1) Surface flux (W/m^2) - default is sun
         .tol    (1,1) Tolerance for iteration on temperature
Outputs
 tS (1,1) Surface temperature    (K)
 tI  (1,1) Inner wall temperature (K)
 qI  (1,1) Flux from inner wall   (W/m^2)
 k   (1,1) Conductance            (W/m^2 K)
 out  (.)  Output data
           .err  (1,1) Error in RHS
           .nD   (1,1) MLI density   (layers/cm)
           .qMLI (1,1) MLI heat flux (W/m^2)
See also
: OptimalMLIDensity
References and(), DefaultDataStructure(), Demo(), OptimalMLIDensity(), RadiationShield(), and RHS().
Referenced by RadiationShield().
RadiatorCoating()
function RadiatorCoating (in name)
 'name' is not case sensitive. All values are averages.
 If no input is entered it will return the available materials.
Form
 [alpha, epsilon, ratio] = RadiatorCoating( name )
Inputs
 name        (1,:)    Name
Outputs
 alpha       (1,1)    Absorptivity
 epsilon     (1,1)    Emissivity
 ratio       (1,1)    alpha/epsilon
References: Van Vliet, R. M., Passive Temperature Control in the Space Environment, MacMillan, 1965, p. 121.
RankineCycle()
function RankineCycle (in p3, in p4, in doPlot)
This models the most basic Rankine Cycle. The steam tables need to accessible to this function:
 Steam_Tables_Temperature.xlsx
 Steam_Tables_Pressure.xlsx
 Steam_Tables_Superheated.xlsx
Type RankineCycle for a demo from the reference.
Form
 [power,eff] = RankineCycle(p3,p4)
Inputs
 p3      (1,1) Pressure at the turbine inlet (MPa)
 p4      (1,1) Pressure at the turbine outlet (MPa)
 doPlot  (1,1) Create plot even if outputs are requested
Outputs
 eff     (1,1) Cycle efficiency
 t       (1,4) Cycle temperatures
Reference: https://www.nuclear-power.com/nuclear-engineering/ thermodynamics/thermodynamic-cycles/rankine-cycle-steam- turbine-cycle/example-of-rankine-cycle-problem-with-solution/
See also
: SteamTablesSuperheatedEnthalpy, TSCurve
References and(), DefaultDataStructure(), isempty(), length(), Plot2D(), Pressure(), RankineCycle(), SteamTablesSuperheatedEnthalpy(), TSCurve(), and zeros().
Referenced by RankineCycle().
ReynoldsNumberKinematic()
function ReynoldsNumberKinematic (in u, in d, in nu)
Turbulent flow generally happens for rE > 1e4. d is a characteristic length. It is typically diameter for pipe flow.
Type ReynoldsNumberKinematic for a demo.
Form
 rE = ReynoldsNumberKinematic( u, d, nu )
Inputs
 u     (1,:)   Velocity (m/s)
 d     (1,:)   Characteristic length (m)
 nu    (1,:)   Kinematic viscosity (m^2/s)
Outputs
 rE    (1,:)   Reynolds number
Reference: L. C. Thomas, "Heat Transfer," Prentice-Hall, 1992, p. 374.
References length(), Plot2D(), and ReynoldsNumberKinematic().
Referenced by HeatTransferChannel(), PressureDropChannel(), ReynoldsNumberKinematic(), and SizeTurbineAndCompressor().
RHSAerodynamicHeating()
function RHSAerodynamicHeating (in d)
 This is a flat plate model.
Form
 qDot = RHSAerodynamicHeating( d )
Inputs
 d       (1,1)   Data structure
                 .rho (1,1) Density (kg/m^3)
                 .v   (1,1) Velocity (m/s)
                 .s   (1,1) Surface area (m^2)
                 .cH  (1,1) Heat transfer coefficient
Outputs
 qDot    (1,1)   Heating rate
Reference: http://worldofaerospace.googlepages.com/Calculate- Aerodynamic-Heating-Rate.htm
RHSIsothermal()
function RHSIsothermal (in x, in t, in d)
This model works only in Earth orbit.
alpha is the absorptivity (0 to 1)
epsilon is the emissivity (0 to)
m is the mass (kg)
cp is the specific heat
a_r is the radiator area
a_s is the surface area
Form
 xDot = RHSIsothermal( x, t, d )
Inputs
 x        (1,1) Temperature
 t        (1,1) Time
 d         (.)  Data structure
                .a1    (1,1) epsilon*a_r/cp*m
                .a2    (1,1) alpha*a_s/cp*m
                .a3    (1,1) 1/cp*m
                .p     (1,1) Internal power
                .jD0   (1,1) Julian date at t = 0
                .rECI  (3,1) ECI Position vector
 jD       (1,n) Julian dates
Outputs
 xDot     (1,1) Temperatures (deg-K)
References: Agrawal, B. ,"Design of Geosynchronous Spacecraft," Prentice-Hall, 1986, pp. 281-283
References and(), Date2JD(), DefaultDataStructure(), EarthAlb(), EarthRad(), Eclipse(), Mag(), SolarFlx(), SunV1(), Unit(), and vector().
Referenced by RHSIsothermalPState(), and RHSIsothermalUKF().
SizeTurbineAndCompressor()
function SizeTurbineAndCompressor (in d)
The output data structure has all the values in the input plus values computed in the function. The latex formatted output can be saved to a file using CreateLatexTable or printed in the command window using DisplayLatexTable.
Type SizeTurbineAndCompressor for a demo with a 70% Helium/30% Xenon mixture.
Form
 d = SizeTurbineAndCompressor       % default data
 [d, l] = SizeTurbineAndCompressor( d )
Inputs
 d              (.)    Input data structure
                       .name       (1,:)   Name
                       .length      (1,1)   Channel length (m)
                       .w          (1,1)   Channel width (m)
                       .h          (1,1)   Channel height (m)
                       .q          (1,1)   Total heat flux (MW)
                       .cP         (1,1)   Heat capacity (J/kg-K)
                       .gamma      (1,1)   Ratio of specific heats
                       .tInlet     (1,1)   Inlet temperature (deg-K)
                       .tOutlet    (1,1)   Outlet temperature (deg-K)
                       .pressure   (1,1)   Inlet pressure (Atm)
                       .gas        {1,2*n) {'name' fraction ...}
                       .kC         (1,1)   Inlet pressure drop
                                           coefficient
                       .kE         (1,1)   Outlet pressure drop
                                           coefficient
Outputs
 d              (.)    Additions to the data structure
                       .mDot    (1,1)   Mass flow rate (kg/s)
                       .u           (1,1)   Velocity (m)
                       .qChannel    (1,1)   Heat flux (W/m)
                       .dP       (1,1)   Pressure drop (Atm)
                       .area     (1,1)   Channel area (m^2)
                       .d        (1,1)   Channel dimension (m)
 l              {:,3}  Latex formatted output
Reference: Hill, P. G. and Peterson C. R.,"Mechanics and Thermodynamics of Propulsion," Addison-Wesley Publishing Company, 1970,
References AbsoluteViscosity(), and(), Brayton(), CreateLatexTable(), DefaultData(), DisplayLatexTable(), HeatTransferCoeff(), length(), NusseltLaminar(), NusseltTurbulent(), Plot2D(), plus(), PrandtlNumber(), Pressure(), PressureDropChannel(), ReynoldsNumberKinematic(), RFromCPAndGamma(), SizeTurbineAndCompressor(), and ThermalConductivity().
Referenced by SizeTurbineAndCompressor().
SolarPanelThermal()
function SolarPanelThermal (in d)
 Asumes that the front of the panel is illuminated and the back
 has not illumination.
 Type SolarPanelThermal for a demo.
Form
 [tF, tB] = SolarPanelThermal( d )
Inputs
 d               (1,1) Data structure
                       .alpha (1,1) Absorptivity
                       .epsF  (1,1) Front emissivity
                       .epsB  (1,1) Back emissivity
                       .etaP  (1,1) Fraction of flux to power
                       .k     (1,1) Front/back conductivity
                       .s     (1,1) Solar flux
Outputs
 tF              (1,1) Front temperature
 tB              (1,1) Back temperature
 c               (1,1) Final cost
References and(), FSolarPanelThermal(), IsVersionAfter(), and SolarPanelThermal().
Referenced by FSolarPanelThermal(), and SolarPanelThermal().
SpaceCamera()
function SpaceCamera (in action, in modifier, in g, in jD)
An imager function can be specified, for instance optical or thermal coloration. If no function is specified the CAD colors are used.
 There are five calls you need to make when using this plugin.
 (1) INITIALIZE
 tag = SpaceCamera( 'initialize', d, g, jD )
 d      data structure
 .camera            (:)  Camera model
 .position         (1,4) Position of the window
 .planetName       (1,:) Planet name
 .imagerFunction   (1,:) Imager function (can be handle, optional)
 .name             (1,:) Name for the plugin (optional)
 .scale            (1,1) Flag to scale up the spacecraft (optional)
 .ambientStrength  (1,1) Default strength if not 0 (optional)
 g      is the spacecraft CAD data structure. It contains the ECI orbit
 position of the spacecraft. The field for orbit position
 .rECI must be in kilometers. The spacecraft model must be in
 meters.
 jD     is the Julian date
 You need to save tag to call the function in subsequent calls.
 (2,3) UPDATE THE SPACECRAFT AND CAMERA
 If you are updating the camera you should make these two calls in sequence:
 SpaceCamera( 'update camera',     tag, camera, jD )
 SpaceCamera( 'update spacecraft', tag, g, jD )
 The data structure in the 'update camera' call is as follows:
 camera   Camera data structure, see CameraDatabase
 .position       (3,1) Position of camera (m)
 .up             (3,1) Up unit vector in the camera frame
 .focalLength    (1,1) Focal length
 .aperture       (1,1) Aperture diameter
 .rho            (1,1) Imager diameter
 .rBody          (3,1) Location of camera in ECI frame, if known. (m)
 .qBody          (4,1) Orientation of camera from ECI frame, if known
 (4) EXTRACT IMAGE
 To extract an image type
 rGB = SpaceCamera( 'get frame', tag )
 (5) QUIT
 To close the display type
 SpaceCamera( 'quit', tag )
 There are additional calls for interacting with the camera.
 'get scene attitude'  Return the ECI to planet-fixed transformation
 'set ambient'         Set an ambient strength for the patches
 'toggle names'        Toggle the spacecraft names
 'get camera'          Get the camera model
 'get model'           Get the target CAD model
Form
 tag = SpaceCamera( action, modifier, g, jD )
Inputs
 action      (1,:)  Action
 modifier    (1,:)  Modifier to the action
 g           (1,1)  Spacecraft data structure
 jD          (1,1)  Julian Date
Outputs
 tag         (1,:)  The tag that identifies the display
                    or another output
References abs(), and(), CameraDatabase(), close(), CloseFigure(), Date2JD(), ECIToPlanet(), El2RV(), get(), GetH(), GetNewTag(), Imager(), Initialize(), isempty(), length(), LoadCatalog(), Map(), PlotPlanet(), PutH(), RaDec2U(), set(), SpaceCamera(), square(), and vector().
Referenced by FImage(), and SpaceCamera().
SpacecraftThermal()
function SpacecraftThermal (in mode, in g, in e)
This computes the average temperature of each component. The optical input is a flux vector with magnitude in watts. The number of points generated will equal the length of the longest transformation matrix in g or the longest member of e. If the number of points is > 1 all other members of e and transformation matrices in g must equal that number of 1.
The computations can use shadowing. To get shadowing you must enter the shadow and scanLines fields.
Form
 temperature = SpacecraftThermal( mode, g, e )
Inputs
 mode      ''        String: 'init' or 'run'
 g         (.)       Spacecraft data structure
 e         (.)       Disturbances data structure
                     .planet             (1,:) Will compute density and mu for various
                                               planets
                     .planetRadius       (1,:) Radius of the planet (km)
                     .albedo             (1,1) Albedo fraction
                     .radiation          (1,1) Planet radiation (watts)
                     .s                  (3,:) Solar optical radiation flux vector (watts)
                     .r                  (3,:) Distance from gravity center (km)
                     .tSamp              (1,1) Sample time between transformation matrices in g
                     .shadow             (1,1) 1 for on, 0 for off
                     .nScanLines         (1,1) Number of scan lines for shadowing
                     .showScans          (1,1) 1 means show the HSRCAD scan display
                     .computePR          (1,1) 1 means include planetary radiation
                     .units              (1,:) 'm', 'in', 'ft'
Outputs
 p            (:)    Output data structure
                     .qSun        (:) Flux from the sun
                     .qAlbedo     (:) Albedo flux
                     .qRadiation  (:) Planetary radiation flux
                     .qTotal      (:) Total flux
                     .temperature (:) Temperature
References and(), Disturbances(), get(), HSRCAD(), isempty(), length(), and vector().
SteamTablesSuperheatedEnthalpy()
function SteamTablesSuperheatedEnthalpy (in p, in s)
Requires that this file be in the search path:
 Steam_Tables_Superheated.xlsx
You enter pressure and entropy and get enthalpy. The data range is 0.01 to 1000 MPa. Type SteamTablesSuperheatedEnthalpy for a demo.
Form
 h = SteamTablesSuperheatedEnthalpy(p,s)
Inputs
 p      (1,:) Pressure (MPa)
 s      (1,1) Entropy (kJ/kg K)
Outputs
 h      (1,:) Enthalpy (kJ/kg)
References and(), Demo(), get(), isempty(), length(), Plot2D(), Pressure(), SteamTablesSuperheatedEnthalpy(), and zeros().
Referenced by RankineCycle(), and SteamTablesSuperheatedEnthalpy().
TempConv()
function TempConv (in from, in to, in tI)
Form
 tC = TempConv( from, to ,tI )
Inputs
 from       (1,1)    Units of tI ('K','R','C','F')
 to         (1,1)    Units of tC ('K','R','C','F')
 tI         (1,:)    Temperature (deg from)
Outputs
 tC         (1,:)    Converted temperature (deg to)
References Plot2D().
TempCyl()
function TempCyl (in alpha, in epsilon, in rOverL, in S, in n, in u)
Includes ends.
Form
 T = TempCyl( alpha, epsilon, rOverL, S, n, u )
Inputs
 alpha         (1,1)  Absorptivity
 epsilon       (1,1)  Emissivity
 rOverL        (1,1)  Ratio of radius to length
 S             (1,1)  Heat flux (watts)
 n             (3,1)  Unit vector of axis of symmetry
 u             (3,:)  Unit vectors to flux source
Outputs
 T             (1,:)  Temperature (deg-K)
References abs(), length(), Plot2D(), Unit(), and vector().
TempFP()
function TempFP (in alpha, in epsilon, in S, in n, in u)
Form
 t = TempFP( alpha, epsilon, S, n, u )
Inputs
 alpha         (1,1)  Absorptivity
 epsilon       (1,1)  Emissivity
 S             (1,1)  Heat flux (watts)
 n             (3,1)  Outward unit vector
 u             (3,:)  Unit vector to flux source
Outputs
 t             (1,:)  Temperature (K)
References: Van Vliet, R. M., Passive Temperature Control in the Space Environment, MacMillan, 1965, p. 6.
References Normal(), Plot2D(), TempFP(), Unit(), and vector().
Referenced by TempFP().
TempSph()
function TempSph (in alpha, in epsilon, in S)
 Type TempSph for a demo.
Form
 T = TempSph( alpha, epsilon, S )
Inputs
 alpha         (1,1)  Absorptivity
 epsilon       (1,1)  Emissivity
 S             (1,1)  Heat flux (watts)
Outputs
 T                    Temperature (deg-K)
References: Van Vliet, R. M., Passive Temperature Control in the Space Environment, MacMillan, 1965, p. 6.
References Demo(), Plot2D(), and TempSph().
Referenced by TempSph().
ThermalColorMap()
function ThermalColorMap (in temp, in tempMax, in colorMap)
 colorMap is optional.
 Type ThermalColorMap for a demo.
Form
 rGB = ThermalColorMap( temp, tempMax, colorMap )
Inputs
 temp           (1,n)       Temperatures
 tempMax        (1,1)       Maximum temperature
 colorMap       (:,3)       Color colorMap. Each row is [r b g]
Outputs
 rGB            (n,3)       Colors representing the temperature.
References length(), NewFig(), set(), ThermalColorMap(), and zeros().
Referenced by DrawThermalPlugIn(), ThermalColorMap(), and ThermalImager().
ThermalConductivity()
function ThermalConductivity (in gas, in t)
Thermal conductivity of gases. Extrapolates beyond the range of data. The data may not be valid for any t since the substance may not be a gas or a molecule may dissociate at the input temperature.
Type ThermalConductivity for a demo for Xenon.
Form
 mu = ThermalConductivity( gas, t )
Inputs
 gas   (1,:)   Gas
 t     (1,:)   Temperature (deg-K)
Outputs
 k    (1,:)   Thermal conductivity (mW/m-K)
Reference: https://www.engineersedge.com/heat_transfer/ thermal-conductivity-gases.htm Heat Transfer, Lindon C. Thomas, Prentice-Hall, 1992
References ThermalConductivity().
Referenced by HeatTransferChannel(), SizeTurbineAndCompressor(), and ThermalConductivity().
ThermalConductivityAndViscHeXe()
function ThermalConductivityAndViscHeXe (in t, in f)
Thermal conductivity of gases. Extrapolates beyond the range of data. The data may not be valid for any t since the substance may not be a gas or a molecule may dissociate at the input temperature.
Type ThermalConductivityAndViscHeXe for a demo.
Form
 [k,mu] = ThermalConductivityAndViscHeXe( t, f )
Inputs
 t     (1,:)   Temperature (deg-K)
 f     (1,1)   Mole fraction of Xe
Outputs
 k     (1,:)   Thermal conductivity (W/m-K)
 mu    (1,:)   Viscosity (W/m-K)
Reference: Heat Transfer and Pressure Drop in Concentric Annular Flows of Binary Inert Gas Mixtures R.S. Reid, J.J. Martin, D.J. Yocum,* and E.T. Stewart
References and(), Plot2D(), Pressure(), ThermalConductivityAndViscHeXe(), and zeros().
Referenced by ThermalConductivityAndViscHeXe().
ThermalEquilibrium()
function ThermalEquilibrium (in d, in q, in t, in nIts, in epsilon)
 with conductive and radiative heat exchange.
 lT^4 + kT = bq
 Contains Built-in Demo which evalutates two nodes connected by a
 conductor.
Form
 [t, err] = ThermalEquilibrium( d, q, t, nIts, epsilon )
Inputs
 d           (:)   System matrices data structure
                   .k   linear term
                   .l   quadratic term
                   .b   input matrix
 q           (:)   Input fluxes
 t           (:)   Node temperatures
 nIts        (1,1) Number of iterations
 epsilon     (1,1) Error
Outputs
 t           (:)   Node temperatures
 err         (:)   Node temperature error
References and(), Demo(), DupVect(), isempty(), length(), and ThermalEquilibrium().
Referenced by ThermalEquilibrium().
ThermalImager()
function ThermalImager (in action, in g, in d)
Form
 h     = ThermalImager( action, g, d )  becomes
 h     = ThermalImager( 'initialize', h, d )
 color = ThermalImager( 'spacecraft', g, d )
 hSurf = ThermalImager( 'planet', g, d )
Inputs
 action (1,:)   Action string
 g      (.)     Data structure
 d          (.)     Data structure
Outputs
 h      (:)     Varies depending on action.
References Constant(), PlotPlanet(), and ThermalColorMap().
Thermnet()
function Thermnet (in mn, in cnm, in cc, in inm, in onm, in rnm, in rc, in tnom)
 a thermal circuit. Inputs are the nodal masses,
 a conductive node map, a radiative
 node map, an input node map and an output node map. The output
 is a set of first order differential equations in the form
 .
 T = aT + bq
 y = cT
 where T is the nodal temperature, q is the thermal input
 and y is the vector of measurements.
 A node map has one row for each node and as many columns as
 are necessary to specify the connections.
 Each node map is accompanied by a coefficient map that gives
 either the conductive or radiative heat transfer coefficents
 for the node pair. Radiative heat transfer is of the form:
 4     4
 q   = a(T   - T  )
 ij      i     j
 Thermnet linearizes about the nominal temperature. The result
 is
 3       3
 q   = a(T  T  - T  T )
 ij      ni i    nj j
 where the n indicates a nominal temperature. The radiative heat
 transfer coefficient causes an asymmetry between nodes.
 Thermnet will automatically make the a matrix symmetric for
 conduction. Thermnet will warn you if you entered a coefficient
 twice and the two were different. You only have to specify the
 connection in one direction.
 If you want a node to conduct or radiate to infinity just
 input "inf" as the node to which it is radiating or conducting.
Form
 [a, b, c, ac, ar] = Thermnet( mn, cnm, cc, inm, onm, rnm, rc, tnom )
Inputs
 mn          (1,n)    Thermal mass of each node
 cnm         (n,:)    Conduction node map
 cc          (n,:)    Conduction coefficients
 inm         (m,:)    Input node map (nodes with inputs)
 onm         (p,1)    Output node map (nodes with outputs)
 rnm         (n,:)    Radiation node map
 rc          (n,:)    Radiation coefficients
 tnom        (1,n)    Nominal temperature for linearization
Outputs
 a           (n,n)    Plant matrix
 b           (n,m)    Input matrix
 c           (p,n)    Output matrix
 ac          (n,n)    Conduction part of the plant matrix
 ar          (n,n)    Radiative (quartic) coefficient matrix
References and(), length(), set(), Thermnet(), and vector().
Referenced by Thermnet().
TSCurve()
function TSCurve (in t)
Requires that
 Steam_Tables_Temperature.xlsx
be in the search path. Type TSCurve for a demo. If t is entered s will be [sL;sV] corresponding to t
Form
 [s,t] = TSCurve(t)
Inputs
 t      (1,:) Temperature (K)
Outputs
 s      (1 or 2,:) Entropy (kJ/kg K)
 t      (1,:)      Temperature (K)
References and(), isempty(), length(), Plot2D(), TSCurve(), and zeros().
Referenced by RankineCycle(), and TSCurve().
WiensDsp()
function WiensDsp (in T)
 This function has a built-in demo.
Form
 lambda = WiensDsp( T )
Inputs
 T            (1,:) Temperatures (deg-K)
Outputs
 lambda       (1,:) Wavelength vector (meters)
References: Thomas, L. C., Heat Transfer, Prentice-Hall, 1992, p. 266
References Plot2D(), vector(), and Wavelength().