PSS MATLAB Toolboxes: Imaging Functions
Imaging Functions
Imaging Module
The Imaging module functions.
Directories
directory Calibration
directory ImageData
Sample images.
directory ImageMatching
Image matching.
directory ImageProcessing
Image processing.
directory Optics
Optics functions.
directory PSFUtils
Point spread function utilities.
directory Utilities
General imaging utilities.
Description
Functions
function AdaptiveThresholding (in a, in thresh, in n)
Applies and adaptive threshold to an image.
function AiryDefocused (in z, in r, in lambda, in a, in R)
Compute the Airy disk for defocused light.
function AiryDiskInPixels (in f, in lambda, in a, in w)
Compute the pixel width of the Airy disk.
function AiryResolution (in d, in f, in pixelWidth, in lambda, in eps)
Draw the Airy pattern for a point light source.
function AngleOfView (in f, in d)
Compute the angle of view.
function BinaryImage (in q, in threshold)
Generate a binary image.
function BlurParameter (in f, in v, in r, in N, in lambda, in D)
Find the blur parameter.
function CalibrationCube (in w, in r, in n)
Create a calibration cube for lens calibration.
function CameraCalibration (in pD, in pW, in nL)
Calibrates a camera.
function CameraCalibrationModel (in d, in pW)
Computes points in the camera coordinates.
function CannyEdgeDetector (in a)
Applies a mask to do Canny edge detection.
function CannyEnhancer (in i, in sigma, in eps, in thresh)
Canny edge detector.
function Centroids (in action, in varargin)
Generate centroid distributions.
function CircleFit (in x, in y)
Fit a circle to data.
function CircleOfConfusion (in s1, in s2, in f, in a)
Computes the circle of confusion for an optical system.
function ConeAreaAndDerivatives (in m, in x)
Cone area and derivatives.
function ConvolveImage (in a, in mask)
Convolves an image with a mask.
function CookeTriplet (in x, in d)
Computes the output angle from a Cooke Triplet.
function CornerDetector (in dX, in dY, in n, in thresh)
Corner detector.
function CreateLensTable (in l, in fileName)
Creates a lens table from l.
function DetectorModel (in action, in varargin)
Detector model with photon and electron noise sources and A/D conversion.
function DrawLens (in l, in f, in n)
Draws lenses from a standard lens table.
function DrawMirror (in l, in f, in n)
Draws mirrors.
function EffFocalLength (in f, in d)
Computes the effective focal length using thin lens approximation.
function ElectronsToIons (in nE, in zI)
From electrons compute the number density of the ions.
function EllipseImageFit (in x, in y, in ignoredArg)
Fit an ellipse to point data.
function EllipseToS (in a, in b, in x0, in y0)
Convert ellipse parameters to s.
function EnergyPhoton (in lambda)
Energy of a photon.
function FitPSFToData (in r0, in int, in pixels, in d, in options)
Refine the pixel fit numerically using fminsearch.
function FocalLengthFromAngleOfView (in alpha, in d)
Compute the focal length from angle of view.
function FocalPlaneImage (in action, in varargin)
Visualize a focal plane image using a mesh.
function FresnelNumber (in a, in lambda, in R)
Compute the Fresnel Number.
function GaussianDerivative (in q, in sigma, in eps)
Generate an image derivative using a Gaussian kernal.
function GaussianImageFilter (in q, in sigma, in eps, in y)
Apply a Gaussian filter and derivative to an image.
function GaussianKernal (in x, in sigma)
Gaussian point spread function.
function GradientOperator (in type)
Image gradient operators.
function HysteresisThreshold (in iN, in e0K, in tauH, in tauL)
Hysteresis threshold.
function ImageDerivative (in i, in a)
Generate an image derivative.
function ImageNoise (in i, in g, in s)
Generate noise for an image.
function Imager (in x, in h, in y, in ignoredArg)
Display an image in figure given image data.
function ImagerPSF (in d, in nPix)
Finds the output of each imager pixel through numerical integration of PSF.
function IndexedImageToRGB (in x, in cmap)
Converts an indexed image to RGB.
function ISO (in iso)
Attentuation factor at an iso number.
function ISOEquivalent (in iso)
Ratio of sensitivity to ISO 100.
function LaserBeamRadius (in d, in lambda, in z)
Laser beam radius.
function LaserPower (in d, in lambda, in z, in power)
Laser power.
function LensMakerFormula (in l, in nAmbient)
Compute the focal lengths of lenses.
function LightGathering (in D, in eta)
Computes stellar magnitude visible to a telescope.
function LinearImageFilter (in i, in a)
Apply a linear noise filter to an image.
function LumenToWatt (in lambda, in l)
Outputs lumens/watt.
function MedianImageFilter (in i, in m)
Apply a median noise filter to an image.
function NonMaxSuppression (in e0, in eS)
Non max suppression.
function OpticalAngleError (in a, in theta, in alpha, in aE, in d, in n)
Errors due to planet measurement related errors.
function OpticalMagnification (in fO, in fE)
Computes optical magnification of a telescope.
function OpticalRadialDistortion (in rT, in k, in tol)
Computes the measured radius from the true radius.
function ParabolaToS (in p, in x0, in y0)
Convert parabola parameters to s.
function PinholeCamera (in r, in f)
Perform pinhole camera transformation on points.
function PixelFlux2D (in e, in q)
Compute the integrated flux from a pixel in 2D.
function PixelSpread (in f, in a, in lambda, in w)
Compute the pixel spread of a collimated light beam.
function PointSpreadFunction2DGaussian (in p, in p0, in sigma)
Compute the point spread function for a 2D gaussian.
function PoissonNoise (in p0, in f, in b)
Smear the pixels with poisson noise.
function QESilicon (in lambda)
Quantum efficiency of silicon.
function RayTraceLens (in r, in l)
Ray trace a lens assembly.
function RayTraceMirror (in r, in l)
Ray trace for mirrors.
function RayTransferMatrix (in d, in x)
Computes the ray transfer matrix for an optical system.
function RayTransferMatrixFromLensFile (in l, in x, in nA)
Computes the ray transfer matrix from a lens file or table.
function ReadImage (in f)
Read an image.
function ReadLensData (in file, in ignoredArg)
Draws lenses with spherical or flat surfaces.
function ReflectionLaw (in u1, in n)
Apply the vector form of the law of reflection.
function RHSAiryDefocusedPSF (in x, in y, in d)
Point Spread Function for the Airy defocused function.
function RHSAiryPSF (in x, in y, in d)
Point Spread Function for an Airy function.
function RHSGaussianPSF (in x, in y, in d)
Point Spread Function for multiple Gaussian PSF.
function RHSMoffatPSF (in x, in y, in d)
Point Spread Function for a Moffat function.
function RMSNoiseImager (in p)
Finds the RMS noise of an imager.
function SnellsLaw (in n, in i, in mu)
Apply the vector form of Snell's law of refraction.
function SnellsLawCurve (in r, in s, in nO, in nI, in isConcave)
Apply Snell's law of refraction to a curve of the form.
function StarCentroid (in i, in x, in y)
Finds the centroid given intensities on n pixels and their coordinates.
function StellarMagnitude (in mIn, in units)
Stellar magnitude for a variety of sources.
function StrehlRatio (in bD, in N)
Compute the Strehl Ratio from defocus and Fresnel number.
function TargetInFocalPlane (in p, in qTToI, in qCToI, in d, in e, in v, in f, in i)
Project a target into the focal plane.
function VM2Photons (in v, in lambda)
Converts apparent visual magnitude to intensity in photons/s/m^2.
function VMToPhotons (in vM, in t, in l)
Converts apparent visual magnitude to photons/s/micron.
function ZodiacalLight (in r, in beta)
Computes zodiacal light due to dust.
Function Documentation
AdaptiveThresholding()
function AdaptiveThresholding (in a, in thresh, in n)
Type AdaptiveThresholding for a demo with the asteroid Bennu.
Form
 d = AdaptiveThresholding(a,thresh,n)
Inputs
 a      (:,:)   uint8 Grayscale image
 thresh (1,1) Threshold (fraction of maximum value)
 n       (1,1)  Size of mean mask
Outputs
 d       (:,:)  uint8 Thresholded image. 0: below threshold. 255: above
               threshold.
Reference: https://homepages.inf.ed.ac.uk/rbf/HIPR2/adpthrsh.htm
References AdaptiveThresholding(), and(), ConvolveImage(), Demo(), Imager(), and isempty().
Referenced by AdaptiveThresholding().
AiryDefocused()
function AiryDefocused (in z, in r, in lambda, in a, in R)
 This routine uses integral to numerically integrate the distribution.
 Type AirDefocused for a demo. It shows several different defocus
 settings and also shows the Airy point spread function.
Form
 AiryDefocused( z, r, lambda, a, R )
Inputs
 z           (1,1)   Distance of wave plane (mm)
 r           (1,:)   Points in plane (mm)
 lambda      (1,1)   Wavelength (nm)
 a           (1,1)   Aperture (mm)
 R           (1,1)   Distance from aperture to Gaussian image plane (mm)
Outputs
 p           (1,1)   Output
Reference: Virendra N. Mahajan, "Beam Focusing and Depth of Focus," The Aerospace Corporation.
References AiryDefocused(), and(), Demo(), FresnelNumber(), length(), Wavelength(), and zeros().
Referenced by AiryDefocused().
AiryDiskInPixels()
function AiryDiskInPixels (in f, in lambda, in a, in w)
Form
 p = AiryDiskInPixels( f, lambda, a, w )
Inputs
 f           (1,1)   Focal length (mm)
 lambda      (1,1)   Wavelength (nm)
 a           (1,1)   Aperture (mm)
 w           (1,1)   Pixel width (micro-m)
Outputs
 p           (1,1)   Airy disk radius (pixels)
References AiryDiskInPixels(), Demo(), Disk(), length(), Plot2D(), and Wavelength().
Referenced by AiryDiskInPixels().
AiryResolution()
function AiryResolution (in d, in f, in pixelWidth, in lambda, in eps)
 Type AiryResolution for a demo.
Form
 [i, pixels] = AiryResolution( d, f, pixelWidth, lambda, eps )
Inputs
 d               (1,1) Aperture
 f               (1,1) Focal length
 pixelWidth      (1,1) Width of a pixel
 lambda          (1,1) Wavelength
 eps             (1,1) Center obstruction (0 < eps < 1)
Outputs
 i               (1,:) Intensity
 pixels          (1,:) Pixel location
Reference: http://en.wikipedia.org/wiki/Airy_disc
References AiryResolution(), Demo(), Disk(), length(), Plot2D(), and Wavelength().
Referenced by AiryResolution().
AngleOfView()
function AngleOfView (in f, in d)
Full-angle, not half-angle.
 If the imaging element is 2-dimensional it will compute two angles.
 Type
 AngleOfView
 for a demo.
Form
 alpha = AngleOfView( f, d )
Inputs
 f               (1,1) Focal length
 d               (2,1) Dimensions of film or imaging chip
Outputs
 alpha           (2,1) Angle of view (rad)
Reference: http://en.wikipedia.org/wiki/Angle_of_view
References and(), AngleOfView(), Demo(), and length().
Referenced by AngleOfView(), AutoPoint(), and PointCameraModel().
BinaryImage()
function BinaryImage (in q, in threshold)
Threshold is a fraction of the maximum.
Form
 b = BinaryImage( q, threshold )
Inputs
 q              (n,m)       Grayscale image
 threshold      (1,1)       Threshold 0 to 1
Outputs
 b              (n,m)       Binary image
References and(), BinaryImage(), Demo(), Imager(), set(), and zeros().
Referenced by BinaryImage().
BlurParameter()
function BlurParameter (in f, in v, in r, in N, in lambda, in D)
 if v = f sigma is zero. The default for D is inf. v may be a 1 D array.
 Type BlurParameter for a demo.
Form
 sigma = BlurParameter( f, v, r, N, lambda, D )
Inputs
 f           (1,1)   Focal length (mm)
 v           (1,:)   Distance from image plane to lens (mm)
 r           (1,1)   Lens radius (mm)
 N           (1,1)   F stop
 lambda      (1,1)   Wavelength (nm)
 D           (1,1)   Distance of the object point to the lens (mm)
Outputs
 sigma       (1,:)  Blur parameter/camera parametr
Reference: Chaudhuri, S. and A. N. Rajagopalan, "Depth from Defocus: A Real Aperture Imaging Approach," Springer-Verlag, 1999, p. 10.
References and(), BlurParameter(), Demo(), length(), Parameter(), Plot2D(), and Wavelength().
Referenced by BlurParameter().
CalibrationCube()
function CalibrationCube (in w, in r, in n)
The cube is an n by n array of squares on the +x, +y and +z faces of the cube. The squares are w by w. The squares are placed so that the squares are evenly distributed on each face. For calibration the camera should be place along the [1;1;1] unit vector. You might have adjust the point-of-view in the demo to not get triangles instead of squares.
Form
 p = CalibrationCube( w, r, n )
Inputs
 w       (1,1)    Width of square
 r       (1,1)    Width of the cube
 n       (1,1)    Square array is n by n
Outputs
 p       (3,:)    Points
References and(), Box(), CalibrationCube(), Demo(), get(), NewFig(), Square(), square(), vector(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by CalibrationCube(), CameraCalibration(), CameraCalibrationModel(), GaussianDerivative(), and ImageDerivative().
CameraCalibration()
function CameraCalibration (in pD, in pW, in nL)
Form
 dE = CameraCalibration( pD, pW, nL )
Inputs
 pD      (2,:)    Measured coordinates
 pW      (3,:)    Corresponding world coordinates
 nL      (1,1)    If entered estimate k1 and k2
Outputs
 dE      (1,1)    Data structure
                  .o     (2,1) [x,y] origin
                  .s     (2,1) [x,y] pixel dimensions
                  .f     (1,1) Focal length
                  .k1    (1,1) Radial error r^2 coeff
                  .k2    (1,1) Radial error r^4 coeff
                  .R     (3,3) Rotation matrix
                  .T     (3,1) Offset
                  .alpha (1,1) Focal length ratio
Reference: Trucco, E., Verri, A., "Introductory Techniques for 3-D Computer Vision," Prentice-Hall, 1998, Chapter 6.
References and(), CalibrationCube(), CameraCalibration(), CameraCalibrationModel(), Cross(), Demo(), length(), Orthogonalize(), Parameter(), Q2Mat(), set(), U2Q(), Unit(), and zeros().
Referenced by CameraCalibration().
CameraCalibrationModel()
function CameraCalibrationModel (in d, in pW)
If k1 and k2 are unrealistically large it will not converge.
Form
 pD = CameraCalibrationModel( d, pW )
Inputs
 d       (1,1)    Data structure
                  .o    (2,1) [x,y] origin
                  .s    (2,1) [x,y] pixel dimensions
                  .f    (1,1) Focal length
                  .k1   (1,1) Radial error r^2 coeff
                  .k2   (1,1) Radial error r^4 coeff
                  .R    (3,3) Rotation matrix
                  .T    (3,1) Offset
 pW      (3,:)    World coordinates
Outputs
 pD      (2,:)    Distorted coordinates (units of pW)
Reference: Trucco, E., Verri, A., "Introductory Techniques for 3-D Computer Vision," Prentice-Hall, 1998, Chapter 6.
References abs(), and(), CalibrationCube(), CameraCalibrationModel(), Demo(), DupVect(), length(), Q2Mat(), U2Q(), Unit(), and zeros().
Referenced by CameraCalibration(), and CameraCalibrationModel().
CannyEdgeDetector()
function CannyEdgeDetector (in a)
Uses a 5x5 mask.
Type CannyEdgeDetector for a demo with the asteroid Bennu.
Form
 c = CannyEdgeDetector(a)
Inputs
 a              (n,m)        Grayscale image
Outputs
 c              (n,m)        Edges
See also
ConvolveImage
References CannyEdgeDetector(), ConvolveImage(), and Demo().
Referenced by CannyEdgeDetector().
CannyEnhancer()
function CannyEnhancer (in i, in sigma, in eps, in thresh)
Sigma and eps are parameters for the Gaussian derivative. thresh is a noise threshold for the direction calculation. This prevents directions appearing for very small values of the derivative.
Form
 CannyEnhancer;
 [eS, eO] = CannyEnhancer( i )
 [eS, eO] = CannyEnhancer( i, sigma )
 [eS, eO] = CannyEnhancer( i, sigma, eps )
 [eS, eO] = CannyEnhancer( i, sigma, eps, thresh )
Inputs
 i              (n,m)       Grayscale
 sigma          (1,1)       Standard deviation
 eps            (1,1)       Epsilon
 thresh         (1,1)       Fraction of max derivative to set to zero
Outputs
 eS             (:,:)       Edge strength
 eO             (:,:)       Orientation of the edge normal
See also
: GaussianDerivative
Reference: Trucco, E. and A. Verri, "Introductory Techniques for 3-D Computer Vision, Prentice-Hall, 1998, p. 76.
References and(), CannyEnhancer(), GaussianDerivative(), and set().
Referenced by AsteroidCentroid(), CannyEnhancer(), and PlanetCentroid().
Centroids()
function Centroids (in action, in varargin)
 You define the centroid shape using e.r, e.theta and e.h.
 You must call Centroids( 'initialize', e ) first and then
 p = Centroids( 'update', e, p, k ) on every update step.
 Type Centroids for a demo.
Form
 Centroids( 'initialize', e )
 m = Centroids( 'update', e, p, k )
Inputs
 action      (1,:)   'initialize' 'update'
 e           (1,1)   Data structure
                     .m      (1,1) Rows
                     .n      (1,1) Columns
                     .pixel  (1,1) Pixel dimension (micro-m)
                     .fpn    (1,1) Fixed pattern noise (e-)
                     .rho    (1,n) Centroid radial value (pixel)
                     .theta  (1,m) Angle about the centroid
                     .h      (1,n) Normalized height at radial position
 p           (n,m)   Pixel intensities
 k           (1,1)   Frame
Outputs
 m           (n,m)   Pixel map
References and(), Centroid(), Centroids(), Demo(), FocalPlaneImage(), length(), and set().
Referenced by CentroidCOM(), Centroids(), CoarseCentroids(), DetectorModel(), DrawStarImageCentroids(), PostProcessCOM(), and StarCentroidCOM().
CircleFit()
function CircleFit (in x, in y)
The equation is
(x-a)^2 + (y-b)^2 = r^3 x^2 - 2ax + a^2 + y^2 - 2by + b^2 - r^2 = 0 x^2 + y^2 -2ax -2by + a^2 + b^2 - r^2
Form
 [a, b, r] = CircleFit( x, y )
Inputs
 x              (:,1) x data
 y              (:,1) y data
Outputs
 a              (1,1)  x center
 b              (1,1)  y center
 r              (1,1)  Circle radius
References Circle(), CircleFit(), Demo(), and length().
Referenced by AsteroidCentroid(), CircleFit(), and PlanetCentroid().
CircleOfConfusion()
function CircleOfConfusion (in s1, in s2, in f, in a)
Type CircleOfConfusion for a demo.
Form
 c = CircleOfConfusion( s1, s2, f, a )
Inputs
 s1            (1,:)   Where the camera is focused
 s2            (1,1)   True location
 f             (1,1)   Focal length
 a             (1,1)   Aperture
Outputs
 c            (1,:)   Circle of confusion
 m             (1,:)   Magnification
References: http://en.wikipedia.org/wiki/Circle_of_confusion
References abs(), and(), Circle(), CircleOfConfusion(), Demo(), length(), and Plot2D().
Referenced by CircleOfConfusion().
ConeAreaAndDerivatives()
function ConeAreaAndDerivatives (in m, in x)
Type ConeAreaDerivative for a demo.
Form
 [a, dA, dA2] = ConeAreaAndDerivatives( m, x )
Inputs
 m              (1,1) Slope
 x              (1,:) Position from origin
Outputs
 a              (1,:) Area
 dA             (1,:) Derivative of the area
 dA2            (1,:) Second derivative of the area
References and(), Cone(), ConeAreaAndDerivatives(), Demo(), length(), and Plot2D().
Referenced by ConeAreaAndDerivatives().
ConvolveImage()
function ConvolveImage (in a, in mask)
The mask must be square. Some masks:
Edge detection [0 1 0; 1 -4 1; 0 1 0] [1 0 -1; 0 0 0;-1 0 1] Identity [0 0 0; 0 1 0;0 0 0] Type ConvolveImage for a demo with the asteroid Bennu using box blur.
Form
 c = ConvolveImage(a,mask)
Inputs
 a              (n,m)        uint8, Grayscale image
 mask           (n,n)        Mask
Outputs
 c              (n,m)        uint8, Convolved rayscale image
References ConvolveImage(), Demo(), and square().
Referenced by AdaptiveThresholding(), CannyEdgeDetector(), and ConvolveImage().
CookeTriplet()
function CookeTriplet (in x, in d)
You select the focal lengths of the 3 lenses and the position of lens 2.
Lens 1 Lens 2 Lens 3
 |          |         |
Form
 theta = CookeTriplet( x, d )
Inputs
 x               (1,1) The delta position of L3
 d               (1,1) Data structure
                       .f (1,3) Focal lengths
                       .x (1,3) Initial locations
                       .y (1,1) Initial ray
Outputs
 theta           (1,1) Output  angle from triplet
References abs(), and(), CookeTriplet(), Demo(), and RayTransferMatrix().
Referenced by CookeTriplet(), CreateLensTable(), DrawLens(), and RayTraceLens().
CornerDetector()
function CornerDetector (in dX, in dY, in n, in thresh)
n is the dimension of the region. thresh is the eigenvalue threshold. The corner output is [row start, row end, col start col end]
Form
 CornerDetector;
 [iC, coord] = CornerDetector( dX, dY, n )
 [iC, coord] = CornerDetector( dX, dY, n, thresh )
Inputs
 dX             (:,:)   Derivative in the x direction
 dY             (:,:)   Derivative in the y direction
 n              (1,1)   Neighborhood size
 thresh         (1,1)    Threshold
Outputs
 iC             (:,:)   Corner image
 c              (:,:)  Corner pixels
Reference: Trucco, E. and A. Verri, "Introductory Techniques for 3-D Computer Vision, Prentice-Hall, 1998, p. 83-85.
References and(), and CornerDetector().
Referenced by CornerDetector().
CreateLensTable()
function CreateLensTable (in l, in fileName)
If the fileName is not entered it will generate a table in the workspace. Otherwise, it will create a latex table.
Type CreateLensTable for a demo.
Form
 CreateLensTable( x, fileName )
Inputs
 l          (:) Lens data structure
 fileName   (:) File name or file id
Outputs
 None
References CookeTriplet(), CreateLensTable(), Demo(), length(), and ReadLensData().
Referenced by CreateLensTable().
DetectorModel()
function DetectorModel (in action, in varargin)
Includes all noise sources. You enter target or centroid locations. You can define centroids using e.r, e.theta and e.h for shape. If you enter a pixelmap, it is assumed to be in photons - it is multiplied by the quantum efficiency to get the electron counts.
You must call DetectorModel('initialize', e) first and then p = DetectorModel('update', e, p, i) on every update step. The fixed noise parameters are stored in persistent cariables,
Form
 e = DetectorModel( 'struct' )
 DetectorModel( 'initialize', e )
 p = DetectorModel( 'update', e, p, i )
 [r,m] = DetectorModel( 'rss', e )
Inputs
 e            (.)    Data structure
                     .m      (1,1) Rows
                     .n      (1,1) Columns
                     .f      (1,1) Focal length (mm)
                     .a      (1,1) Aperture (mm)
                     .pixel  (1,1) Pixel dimension (micro-m)
                     .tau    (1,1) Integration time (s)
                     .qE     (1,1) Quantum efficiency (e-/photon)
                     .eta    (1,1) Throughput
                     .lambda (1,1) Wavelength (nm)
                     .r      (1,1) Distance from sun (AU)
                     .kappa (1,1) Stray light multiplier
                     .fpn    (1,1) Fixed pattern noise (e-)
                     .ndr    (1,1) Temporal noise (e-)
                     .dark   (1,1) Dark current (e-/s)
                     .alpha  (1,1) Global photo response non uniformity
                     .kTC    (1,1) Temperature noise (e-)
                     .kAD    (1,1) A/D conversion (V/e-)
                     .gain   (1,1) A/D gain Forward A/D gain
                     .bits   (1,1) A/D bits
                     .vS     (1,1) Voltage swing (V)
                     .centroid (1,1)  Flag is true for centroid locations
                     .rho    (1,n) Centroid radial value (pixel)
                     .theta  (1,m) Angle about the centroid
                     .h      (1,n) Normalized height at radial position
 x           (2,:)  Position in pixel plane (m) or pixel map
 i           (:,1)  Intensity (photons/s)
Outputs
 p           (n,m)   Pixels (V)
 r           (1,1)   Root sum square of the noise  (e-) or
 m           (1,1)   Mean noise (e-)
Reference: M. Knutson and D. Miller, "Fast Star Tracker Centroid Algorithm for High Performance CubeSat with Air Bearing Validation," June 2012 MIT SSL # 5-12
See also
:
Centroids
References and(), Centroid(), Centroids(), DefaultData(), Demo(), get(), length(), square(), Wavelength(), and ZodiacalLight().
Referenced by RMSNoiseImager().
DrawLens()
function DrawLens (in l, in f, in n)
 Type DrawLens for a demo
Form
 DrawLens( l, f, n )
Inputs
 l         (:)     Lens data structure
                   .r     (1,1) Radius of one surface
                   .t     (1,1) Thickness
                   .matl  (1,:) Material name
                   .index (1,1) Index of Refraction
                   .vNo   (1,1) Abbe V-number, the reciprocal of the
                                relative dispersion of the material
                   .sa    (1,1) Semi aperture
 f          (1,1)  Figure handle
 n          (1,1)  Number of points per curve
Outputs
 None
References abs(), CookeTriplet(), Demo(), DrawLens(), isempty(), length(), NewFig(), ReadLensData(), XLabelS(), and YLabelS().
Referenced by DrawLens(), LensMakerFormula(), RayTraceLens(), and ReadLensData().
DrawMirror()
function DrawMirror (in l, in f, in n)
 Type DrawMirror for a demo
Form
 DrawMirror( l, f, n )
Inputs
 l         (:)     Mirror data structure
                   .s       (1,6) [x^2 y^2 xy x y 1]
                   .sa      (1,1) Semi aperture (radius about x)
                   .r       (1,1) Radius of hole in mirror
                   .concave (1,1) 1 if concave wrt ray coming from -x
 f          (1,1)  Figure handle
 n          (1,1)  Number of points per curve
Outputs
 None
References Demo(), DrawMirror(), isempty(), length(), NewFig(), Quadratic(), XLabelS(), YLabelS(), and zeros().
Referenced by DrawMirror(), EllipseToS(), and RayTraceMirror().
EffFocalLength()
function EffFocalLength (in f, in d)
 d(1) is the distance between lens 1 and lens 2.
 Type EffFocalLength for a demo.
Form
 fE = EffFocalLength( f, d )
Inputs
 f             (1,n)   Focal length
 d             (1,n-1) Distance between lenses
Outputs
 fE            (1,1)   Effective focal length
References: http://www.mellesgriot.com/products/optics/fo_2_4.htm
References and(), Demo(), EffFocalLength(), and length().
Referenced by EffFocalLength().
ElectronsToIons()
function ElectronsToIons (in nE, in zI)
 Typing ElectronsToIons gives the electrons in a D-He3 reaction.
Form
 nI = ElectronsToIons( nE, zI )
Inputs
 nI        (1,2)  Number densities of the electrons
 zI        (1,2)  Electrons per ion
Outputs
 nI         (1,1) Number of electrons
References Demo(), and ElectronsToIons().
Referenced by ElectronsToIons().
EllipseImageFit()
function EllipseImageFit (in x, in y, in ignoredArg)
The ellipse is ax^2 + bxy + cy^2 + dx + ey + f = 0; The output vector is [a;b;c;d;e;f]; The output vector is good to within a scale factor. If r is entered it will do an additional minimization using a as the starting vector using fminsearch.
Form
 EllipseImageFit;
 aR           = EllipseImageFit( x, y )
 [aR, a, err] = EllipseImageFit( x, y, r )
Inputs
 x              (1,:)        x values
 y              (1,:)        y values
 r              (1,1)        If entered fit using downhill simplex
Outputs
 aR             (1,6)       [a;b;c;d;e;f] robust fit
 a              (1,6)       [a;b;c;d;e;f] regular fit
 err            (1,1)      Error
Reference: Trucco, E. and A. Verri, "Introductory Techniques for 3-D Computer Vision, Prentice-Hall, 1998, p. 103-107.
References and(), EllipseImageFit(), and vector().
Referenced by EllipseImageFit().
EllipseToS()
function EllipseToS (in a, in b, in x0, in y0)
 Type EllipseToS for a demo
Form
 s = EllipseToS( a, b, x0, y0 )
Inputs
 a         (1,1) x-axis width
 b         (1,1) y-axis width
 x0        (1,1) x-axis origin
 y0        (1,1) y-axis origin
Outputs
 s         (1,6) Coefficients of [x^2 y^2 xy x y 1]
References Demo(), DrawMirror(), EllipseToS(), and isempty().
Referenced by EllipseToS().
EnergyPhoton()
function EnergyPhoton (in lambda)
 Type EnergyPhoton for a demo
Form
 e = EnergyPhoton( lambda )
Inputs
 lambda    (1,:) Wavelength (micro-m)
Outputs
 e         (1,:) Energy Joules
References Demo(), Energy(), EnergyPhoton(), Plot2D(), and Wavelength().
Referenced by EnergyPhoton().
FitPSFToData()
function FitPSFToData (in r0, in int , in pixels, in d, in options)
Type FitPSFToData for a demo of a single pixel.
Form
 r = FitPSFToData( r0, int, pixels, d, options )
Inputs
 r0      (2,:)   Initial centroid positions (in pixels)
 int     (1,:)   Intensities from star IDs
 pixels  (:,:)   Pixel map
 d        (.)    Data structure
                 .nUse (1,1) Number of rows to use
                 .mUse (1,1) Number of columns to use
 options    (1,3)   Options for fminsearch [tolX, tolFun, numIterations]
Outputs
 r       (2,:)   Refined centroid positions
References abs(), Demo(), FitPSFToData(), ImagerPSF(), RHSGaussianPSF(), StarCentroidCOM(), and zeros().
Referenced by FitPSFToData().
FocalLengthFromAngleOfView()
function FocalLengthFromAngleOfView (in alpha, in d)
If the imaging element is 2-dimensional it will compute two f.
Type FocalLengthFromAngleOfView for a demo.
Form
 f = FocalLengthFromAngleOfView( alpha, d )
Inputs
 alpha           (2,1) Angle of view (rad)
 d               (2,1) Dimensions of film or imaging chip
Outputs
 f               (1,1) Focal length
Reference: http://en.wikipedia.org/wiki/Angle_of_view
References and(), Demo(), FocalLengthFromAngleOfView(), and length().
Referenced by FocalLengthFromAngleOfView().
FocalPlaneImage()
function FocalPlaneImage (in action, in varargin)
 Initialize creates a new figure, which is stored in a persistent
 variable. Update will then update the image in this figure.
 Type FocalPlaneImage for a demo with random pixel intensities.
Form
 FocalPlaneImage( 'initialize', e )
 FocalPlaneImage( 'update', p, k )
Inputs
 action      (1,:)   'initialize' 'update'
 action = 'initialize'
    e            (.)    Data structure
                         .m    (1,1) pixels
                         .n    (1,1) pixels
 action = 'update'
    p           (n,m)   Pixel intensities
    k           (1,1)   Frame index
Outputs
 None
References Demo(), FocalPlaneImage(), and Initialize().
Referenced by Centroids(), FocalPlaneImage(), LoadStarImage(), ProcessStarImage(), RMSNoiseImager(), and TargetInFocalPlane().
FresnelNumber()
function FresnelNumber (in a, in lambda, in R)
This represents the number of Fresnel's half wave zones in the pupil.
Form
 N = FresnelNumber( a, lambda, R )
Inputs
 a           (1,1)   Aperture (mm)
 lambda      (1,1)   Wavelength (nm)
 R           (1,1)   Distance from aperture to Gaussian image plane (mm)
Outputs
 N           (1,1)   Fresnel Number
Reference: Virendra N. Mahajan, "Beam Focusing and Depth of Focus," The Aerospace Corporation.
Referenced by AiryDefocused(), RHSAiryDefocusedPSF(), and StrehlRatio().
GaussianDerivative()
function GaussianDerivative (in q, in sigma, in eps)
This does derivatives in two directions in both x and y.
Form
 GaussianDerivative;
 d = GaussianDerivative( q, sigma, eps )
Inputs
 q              (n,m)        Grayscale image
 sigma          (1,1)        Standard deviation of the Gaussian kernal
 eps            (1,1)        Epsilon
Outputs
 dX             (n+4,m+4)   Derivative in the x direction
 dY             (n+4,m+4)   Derivative in the y direction
References abs(), and(), CalibrationCube(), ColorMapGrayScale(), Demo(), GaussianDerivative(), GaussianKernal(), Imager(), ReadImage(), set(), and zeros().
Referenced by CannyEnhancer(), and GaussianDerivative().
GaussianImageFilter()
function GaussianImageFilter (in q, in sigma, in eps, in y)
Form
 iF = GaussianImageFilter( q, sigma, eps, y )
Inputs
 q              (n,m)       Grayscale image
 sigma          (1,1)       Standard deviation
 eps            (1,1)       Size of filter box; default, 0.01
 y              (1,1)       If entered filter along y
Outputs
 qF             (n,m)       Processed image
References abs(), and(), Demo(), GaussianImageFilter(), GaussianKernal(), Imager(), set(), and zeros().
Referenced by GaussianImageFilter().
GaussianKernal()
function GaussianKernal (in x, in sigma)
Form
 GaussianKernal;
 y = GaussianKernal( x, sigma );
Inputs
 x              (1,:)       Input
 sigma          (1,1)       Standard deviation
Outputs
 y              (1,1)       Gaussian of (x)
References Demo(), GaussianKernal(), and Plot2D().
Referenced by GaussianDerivative(), GaussianImageFilter(), and GaussianKernal().
GradientOperator()
function GradientOperator (in type)
Form
 [dX, dY] = GradientOperator( type )
Inputs
 type           (1,:)     'roberts' 'sobel' 'prewitt3x3', 'prewitt4x4'
Outputs
 dX             (:,:)     X gradient operator
 dY             (:,:)     Y gradient operator
References GradientOperator().
Referenced by GradientOperator().
HysteresisThreshold()
function HysteresisThreshold (in iN, in e0K, in tauH, in tauL)
This only works for grayscale images. Has a built-in demo using CalibrationPattern.jpg.
Form
 HysteresisThreshold;
 p = HysteresisThreshold( iN, e0K, tauH, tauL )
Inputs
 iN             (:,:)       Edge strength
 e0K            (:,:)       Orientation of the edge normal index
 tauH           (1,1)       Upper threshold
 tauL           (1,1)       Lower threshold
Outputs
 p              {}          List of points
See also
NonMaxSuppression
Reference: Trucco, E. and A. Verri, "Introductory Techniques for 3-D Computer Vision, Prentice-Hall, 1998, p. 77.
References HysteresisThreshold().
Referenced by HysteresisThreshold().
ImageDerivative()
function ImageDerivative (in i, in a)
The default it the mask a = [1 2 1;0 0 0;-1 -2 -1]/8 (Sobel) but any mask can be input.
Form
 ImageDerivative;
 ImageDerivative( i );
 d = ImageDerivative( i, a )
Inputs
 i              (n,m)     Grayscale image (double)
 a              (:,:)     Kernel
Outputs
 d              (n,m)     Derivative
References CalibrationCube(), ColorMapGrayScale(), Demo(), ImageDerivative(), Imager(), ReadImage(), and set().
Referenced by ImageDerivative().
ImageNoise()
function ImageNoise (in i, in g, in s)
Form
 p = ImageNoise( i, g, s )
Inputs
 i              (n,m)       Image
 g              (1,1)       Gaussian
 .sigma (1,1) Standard deviation
 .bias  (1,1) Bias
 s              (1,1)       Salt and pepper noise
 .l     (1,1) Threshold
 .iMax  (1,1) Maximum
 .iMin  (1,1) Minimum
Outputs
 p              (n,m)       Noise
References and(), Imager(), isempty(), length(), and set().
Imager()
function Imager (in x, in h, in y, in ignoredArg)
If x or y is 2 dimensional ColorMapGrayScale is used for the color mapping. If two images are entered it will draw both and abs(x-y). Has a built-in demo using SCImage.mat
Form
 Imager                 % demo
 h = Imager( x, h, y, n )
Inputs
 x              (n,m,3 or 1)     RGB image 1
 h              (1,1)            Figure handle
 y              (n,m,3 or 1)     RGB image 2
 n              (1,1)            Any input don't plot difference
Outputs
 h              (1,1)       Figure handle
See also
image, ColorMapGrayScale
References abs(), and(), ColorMapGrayScale(), Demo(), get(), Imager(), and isempty().
Referenced by AdaptiveThresholding(), BinaryImage(), GaussianDerivative(), GaussianImageFilter(), ImageDerivative(), ImageNoise(), Imager(), ImagerPSF(), IndexedImageToRGB(), IntegratePSFs(), LinearImageFilter(), MedianImageFilter(), QXToAlphaDelta(), RayTransferMatrix(), ReadImage(), RMSNoiseImager(), SpaceCamera(), and SPIGuidance().
ImagerPSF()
function ImagerPSF (in d, in nPix)
The default plot output colors the pixels as a function of height. A built in 2D Gaussian function is available for demos or as a reasonable approximation to a real point spread function.
funPSF must be of the form:
 funPSF(x,y,d)
x and y are arrays passed by integral2. They are two dimensional. Your function must return the same size array. funPSF gets passed the centroids and intensities of the point spread functions through the data structure d as d.rPSF and d.iPSF. You can attach any other data you want to d.funData as shown above.
Type ImagerPSF for a demo using RHSGaussianPSF. The demo is for a 70 by 60 pixel imaging chip.
Form
 d = ImagerPSF       % default data structure
p = ImagerPSF(d, nPix)
Inputs
 d      (.)     Data structure for imager
                 .funPSF    (*)  Pointer to point spread function RHS
                 .funData   (.)  Function data
                 .rPSF     (2,:) Location of PSF in imager frame (um)
                                 1st row (x): columnwise
                                 2nd row (y): rowwise
                 .iPSF     (1,:) Magnitude of each PSF
                 .m        (1,1) Rows
                 .n        (1,1) Columns
                 .xPixel   (1,1) X dimension of each pixel (um)
                 .yPixel   (1,1) Y dimension of each pixel (um)
 nPix  (1,1)   Number of pixels (radius) to integrate each PSF over when
                  computing individual pixels values. default: 6
Outputs
 p           (m,n)  Pixel output
 iC          (1,:)  Intensity of each centroid
References and(), Centroid(), DefaultData(), Demo(), get(), Imager(), ImagerPSF(), length(), NewFig(), RHS(), RHSGaussianPSF(), set(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by CoarseCentroids(), FitPSFToData(), ImagerPSF(), IntegratePSFs(), and StarCentroidCOM().
IndexedImageToRGB()
function IndexedImageToRGB (in x, in cmap)
Form
 r = IndexedImageToRGB( x, cmap )
Inputs
 x              (m,n)       Indexed image
 cmap            (:,3)       Color map
Outputs
 r              (m,n,3)     RGB
References and(), Imager(), and IndexedImageToRGB().
Referenced by IndexedImageToRGB().
ISO()
function ISO (in iso)
Type ISO for a demo
Form
 f = ISO( iso )
Inputs
 iso      (1,:) ISO number
Outputs
 f        (1,:) Attenuation
References Demo(), ISO(), and Plot2D().
Referenced by BearingLife(), ISO(), and ISOEquivalent().
ISOEquivalent()
function ISOEquivalent (in iso)
Type ISOEquivalent for a demo
Form
 sens = ISOEquivalent( iso )
Inputs
 iso      (1,:) ISO number
Outputs
 e         (1,:) Ratio with ISO 100
References Demo(), ISO(), ISOEquivalent(), and Plot2D().
Referenced by ISOEquivalent().
LaserBeamRadius()
function LaserBeamRadius (in d, in lambda, in z)
Form
 r = LaserBeamRadius( d, lambda, z )
Inputs
 d        (1,1)   Aperture (m)
 lambda   (1,1)   Wavelength (m)
 z        (1,1)   Distance (m)
Outputs
 r        (1,1)   Beam radius (m)
References Demo(), LaserBeamRadius(), length(), Plot2D(), Wavelength(), and zeros().
Referenced by LaserBeamRadius(), and LaserPower().
LaserPower()
function LaserPower (in d, in lambda, in z, in power)
Form
 p = LaserPower( d, lambda, z, power )
Inputs
 d        (1,1)   Aperture (m)
 lambda   (1,1)   Wavelength (m)
 z        (1,:)   Distance (m)
 power    (1,1)   Input power (W)
Outputs
 p        (1,:)   Power at z (W/m^2)
 r        (1,:)   Beam radius (m)
References Demo(), LaserBeamRadius(), LaserPower(), Plot2D(), and Wavelength().
Referenced by LaserPower().
LensMakerFormula()
function LensMakerFormula (in l, in nAmbient)
Type LensMakerFormula for a demo of a Harting lens.
Form
 LensMakerFormula
 f = LensMakerFormula( l, nAmbient )
Inputs
 l         (.)     Lens data structure
                   .r     (1,1) Radius of one surface
                   .t     (1,1) Thickness
                   .matl  (1,:) Material name
                   .index (1,1) Index of Refraction
                   .vNo   (1,1) Abbe V-number, the reciprocal of the
                                relative dispersion of the material
                   .sa    (1,1) Semi aperture (i.e. radius)
Outputs
 None
See also
ReadLensData, DrawLens
References Demo(), DrawLens(), length(), LensMakerFormula(), and ReadLensData().
Referenced by LensMakerFormula(), and RayTransferMatrixFromLensFile().
LightGathering()
function LightGathering (in D, in eta)
 Type LightGathering for a demo.
Form
 m = LightGathering( D, eta )
Inputs
 D             (1,:)   Aperture (mm)
 eta           (1,1)   Product of fill factor and quantum efficiency
Outputs
 m            (1,:)   Stellar Magnitude
References: http://astronomyonline.org/Science/TelescopeMagnification.asp
References and(), Demo(), LightGathering(), Plot2D(), and Product().
Referenced by LightGathering().
LinearImageFilter()
function LinearImageFilter (in i, in a)
Has a built-in demo using MoonAndStars.jpg.
Form
 LinearImageFilter;         % demo
 iF = LinearImageFilter( i, a )
Inputs
 i              (:,:)       Grayscale image (double)
 a              (n,n)       Mask
Outputs
 iF             (:,:)       Filtered image
See also
conv2.
References Demo(), Imager(), LinearImageFilter(), and set().
Referenced by LinearImageFilter().
LumenToWatt()
function LumenToWatt (in lambda, in l)
 If lambda is an array, l must be a scalar. If lambda is a scalar
 l can be an array.
 Type LumenToWatt to get the conversion curve.
Form
 w = LumenToWatt( lambda, l )
Inputs
 lambda    (1,:) Wavelength (micro-m)
 l         (1,:) Lumens
Outputs
 w         (1,:) Watts or lumens/watt
References and(), Demo(), get(), isempty(), length(), LumenToWatt(), Plot2D(), scalar(), and Wavelength().
Referenced by LumenToWatt().
MedianImageFilter()
function MedianImageFilter (in i, in m)
Form
 MedianImageFilter;        % demo
 iF = MedianImageFilter( i, m )
Inputs
 i              (:,:)     Grayscale image (double)
 m              (1,1)     Width of region for median computation
Outputs
 iF             (:,:)     Processed image
References Demo(), DupVect(), Imager(), length(), MedianImageFilter(), set(), and zeros().
Referenced by MedianImageFilter().
NonMaxSuppression()
function NonMaxSuppression (in e0, in eS)
Thins the edges.
Form
 NonMaxSuppression;
 [iN, e0K] = NonMaxSuppression( e0, eS )
Inputs
 e0             (n,m)       Orientation of the edge normal
 eS             (n,m)       Edge strength
Outputs
 iN             (n,m)       Edge strength
 e0K            (n,m)       Orientation index of the edge normal
Reference: Trucco, E. and A. Verri, "Introductory Techniques for 3-D Computer Vision, Prentice-Hall, 1998, p. 77.
References and(), and NonMaxSuppression().
Referenced by NonMaxSuppression().
OpticalAngleError()
function OpticalAngleError (in a, in theta, in alpha, in aE, in d, in n)
 The errors are due to the measurement angle of the star/planet vector,
 the error due to the uncertainty in the radius of the planet
 and the error due to the planet chordwidth measurement error.
 The first and last are due to the resolution of the camera and
 the middle due to the uncertainty in the actual radius of the planet.
 Type OpticalAngleError for a demo of the error for a earth orbiting
 spacecraft using the moon as a measurement source.
Form
 err = OpticalAngleError( a, theta, alpha, aE, d, n )
Inputs
 a           (1,1)  Planet radius (rad)
 theta       (1,1)  Angle between the planet vector and star (rad)
 alpha       (1,1)  Angular radius of the planet (rad)
 aE          (1,1)  Planet radius error (rad)
 d           (1,:)  Aperture (mm)
 n           (1,1)  Number of points to average for chord
Outputs
 err         (1,1)  Data structure
                   .a        (1,1) Error due to radius error (km)
                   .theta   (1,1) Error due to star/planet error (km)
                   .alpha    (1,1) Error due to chord error (km)
References and(), Constant(), Demo(), length(), OpticalAngleError(), Plot2D(), and vector().
Referenced by OpticalAngleError().
OpticalMagnification()
function OpticalMagnification (in fO, in fE)
 Type OpticalMagnification for a demo.
Form
 m = OpticalMagnification( fO, fE )
Inputs
 fO            (1,1)   Focal length objective
 fE            (1,:)   Focal length eyepiece
Outputs
 m            (1,:)   Magnification
References: http://en.wikipedia.org/wiki/Eyepiece
References Demo(), length(), OpticalMagnification(), and Plot2D().
Referenced by OpticalMagnification().
OpticalRadialDistortion()
function OpticalRadialDistortion (in rT, in k, in tol)
 Type OpticalRadialDistortion for a demo.
Form
 rM = OpticalRadialDistortion( rT, k, tol )
Inputs
 rT            (1,1)   True radius
 k             (1,2)   Distortion coefficients
 tol           (1,1)   Tolerance for solver. A fraction of rT.
Outputs
 rM            (1,1)   Measured radius
References: Trucco, E. and Verri, A., "Introductory Techniques for 3-D Computer Vision," Prentice-Hall, 1998, p. 37.
References and(), Demo(), and OpticalRadialDistortion().
Referenced by OpticalRadialDistortion().
ParabolaToS()
function ParabolaToS (in p, in x0, in y0)
 The parabola ais is parallel to x and of the form
 (y-y0)^2 + 4p(x-x0)
 Type ParabolaToS for a demo
Form
 s = ParabolaToS( p, x0, y0 )
Inputs
 p         (1,1) Distance of vertex from the focus
 x0        (1,1) x-axis origin
 y0        (1,1) y-axis origin
Outputs
 s         (1,6) Coefficients of [x^2 y^2 xy x y 1]
References and(), Demo(), isempty(), and ParabolaToS().
Referenced by ParabolaToS().
PinholeCamera()
function PinholeCamera (in r, in f)
Transforms points in the camera frame to points in the focal plane using the pinhole transformation, which depends only on focal length. r is in the camera frame with +z outward from the focal plane along the camera boresight. While the input f is specified as mm the output will be in whatever units you use for f.
Type PinholeCamera for a demo.
Form
 PinholeCamera           % demo
 p = PinholeCamera( r, f )
Inputs
 r           (3,:) Points in the camera frame
 f           (1,1) Focal length (mm)
Outputs
 p           (2,:) Points in the focal plane (mm)
References Demo(), length(), PinholeCamera(), and Plot2D().
Referenced by MeasCamera(), PinholeCamera(), and TargetInFocalPlane().
PixelFlux2D()
function PixelFlux2D (in e, in q)
 Type PixelFlux2D for a demo.
Form
 PixelFlux2D( e, q )
Inputs
 e           (1,1)   Data structure
                     .lambda (1,1) Wavelength (nm)
                     .f      (1,1) Focal length (mm)
                     .a      (1,1) Aperture (mm)
                     .i0     (1,1) Peak flux
                     .mu     (1,1) Centroid (mm);
 q           (1,n)   Coordinates of pixel edges
Outputs
 f           (1,n-1) Integrated flux over a pixel
References Centroid(), Coordinates(), Demo(), get(), length(), NewFig(), PixelFlux2D(), set(), Wavelength(), XLabelS(), YLabelS(), and zeros().
Referenced by PixelFlux2D().
PixelSpread()
function PixelSpread (in f, in a, in lambda, in w)
 Assumes diffraction limited optics.
 Since version 9.
Form
 PixelSpread
 n = PixelSpread( f, a, lambda, w )
Inputs
 f              (1,1) Focal length
 a              (1,1) Aperture
 lambda         (1,1) Wavelength
 w              (1,1) Pixel width
Outputs
 n              (1,1) Number of pixels
References Demo(), length(), PixelSpread(), and Wavelength().
Referenced by PixelSpread().
PointSpreadFunction2DGaussian()
function PointSpreadFunction2DGaussian (in p, in p0, in sigma)
This is the shape of a star that is effectively a point light source. The output is unitized so the peak is 1.
Type PointSpreadFunction2DGaussian for a demo.
Form
 PointSpreadFunction2DGaussian;
 i = PointSpreadFunction2DGaussian( p, p0, sigma )
Inputs
 p             (2,:)  [x;y] positions
 p0            (2,1)  Center
 sigma         (1,1)  Sigma for psf
Outputs
 i             (y,x)  2D Gaussian
Reference: Bruce R. Hancock, Robert C. Stirbl,Thomas J. Cunningham, Bebrata Pain,Chris J. Wrigley, Peter G . Ringold Jet"CMOS Active Pixel Sensor Specific Performance Effects on Star Tracker Imager Position Accuracy", Propulsion Laboratory, California Institute of Technology, Pasadena, CA 91109
References and(), Demo(), Mesh2(), and PointSpreadFunction2DGaussian().
Referenced by CentroidNoise(), GroundTrackErrorBudget(), and PointSpreadFunction2DGaussian().
PoissonNoise()
function PoissonNoise (in p0, in f, in b)
Smear a pixelmap with Poisson shot noise. Shot noise operates on the number of electrons. It is a type of noise that can be modeled as a Poisson process. If b is not entered it will use 5% of the max pixel count.
The default scaling is for an 8 bit discretization. The conversion to counts, excluding noise, is f*p + b. To convert counts back to the original intensity, (p - b)/f.
Form
 p = PoissonNoise( pixels, f, b)
Inputs
 pixels    (m,n)     Pixelmap
 f         (1,1)     Convert from pixelmap units to counts.
 b         (1,1)     Flat background, in counts, to apply before shot noise
Outputs
 p         (m,n)     Pixels as counts with noise
 f         (1,1)     Pixelmap conversion used.
 b         (1,1)     Flat background used.
References and(), and PoissonNoise().
Referenced by CoarseCentroids(), and PoissonNoise().
QESilicon()
function QESilicon (in lambda)
Uses the values for photovoltaic efficiency.
Form
 [qE,r] = QESilicon( lambda )
Inputs
 lambda (1,:) Wavelength (nm)
Outputs
 qE      (1,:) Quantum efficiency
 r       (1,:) Responsivity
References KEVToJ(), length(), Plot2D(), QESilicon(), Wavelength(), and zeros().
Referenced by QESilicon().
RayTraceLens()
function RayTraceLens (in r, in l)
For a demo of a Cooke Triplet lens type RayTraceLens
Form
 r = RayTraceLens( r, l )
Inputs
 r         (:)     Ray source definition
                   .p     (2,1) Origin
                   .m     (2,1) Ray unit vector
 l         (:)     Lens data structure
                   .r     (1,1) Radius of one surface
                   .t     (1,1) Thickness
                   .matl  (1,:) Material name
                   .index (1,1) Index of Refraction
                   .vNo   (1,1) Abbe V-number, the reciprocal of the
                                relative dispersion of the material
                   .sa    (1,1) Semi aperture
Outputs
 r         (:)     Ray source definition
                   .p     (2,:) Origins
                   .m     (2,:) Ray unit vectors
References CookeTriplet(), Demo(), DrawLens(), get(), length(), RayTraceLens(), ReadLensData(), set(), SnellsLawCurve(), vector(), and zeros().
Referenced by RayTraceLens().
RayTraceMirror()
function RayTraceMirror (in r, in l)
Form
 r = RayTraceMirror( r, l )
Inputs
 r         (:)     Ray source definition
                   .p     (2,1) Origin
                   .m     (2,1) Ray unit vector
 l         (:)     Mirror data structure
                   .s     (1,6) [x^2 y^2 xy x y 1]
                   .sa    (1,1) Semi aperture (radius about x)
                   .r     (1,1) Radius of hole in mirror
Outputs
 r         (:)     Ray source definition
                   .p     (2,:) Origins
                   .m     (2,:) Ray unit vector
References Demo(), DrawMirror(), get(), length(), Mag(), RayTraceMirror(), SnellsLawCurve(), vector(), and zeros().
Referenced by RayTraceMirror().
RayTransferMatrix()
function RayTransferMatrix (in d, in x)
 Optical element types  Relevant data structure elements
 type                   d   n1   n2   r    f
 'free space'           X
 'flat interface'           X    X
 'curved interface'         X    X    X
 'flat mirror'
 'curved mirror'                      X
 'thin lens'                               X
 In the data structure R is + for concave lenses. f is + for converging
 lenses. You can ignore elements that are not relevant to your element.
 d(1) is the first optical element (nearest to the image)
 d(2) is the next element encountered, etc.
 Your data structure need only contain elements that you wish to use.
 However every data structure must be the same. For example, to use
 just thin lens and distances d(k) = struct('type', 'thin lens', 'f', 10, 'd', 0);
 The distance from the optical axis is the distance on entry to the
 optical system, i.e. at the first element.
 Type RayTransferMatrix for a zoom lens demo. This is a simple 4 lens
 system. We only move the diverging lens.
Form
 [m, xT] = RayTransferMatrix( d, x )
Inputs
 d             (1,1)   Optical system elements
                       .type (1,:) Type of lens
                       .d    (1,1) Distance
                       .n1   (1,1) Initial refractive index
                       .n2   (1,1) Final refractive index
                       .r    (1,1) Radius of curvature
                       .f    (1,1) Focal length
 x             (2,:)   Rays [distance from optical axis;angle]
Outputs
 m             (2,2)   Transfer matrix
 xT            (2,:)   Rays [distance from optical axis;angle]
References: http://en.wikipedia.org/wiki/Ray_transfer_matrix_analysis
References and(), Demo(), Imager(), length(), Plot2D(), RayTransferMatrix(), and zeros().
Referenced by CookeTriplet(), RayTransferMatrix(), and RayTransferMatrixFromLensFile().
RayTransferMatrixFromLensFile()
function RayTransferMatrixFromLensFile (in l, in x, in nA)
The distance from the optical axis is the distance on entry to the optical system, i.e. at the first element.
Type RayTransferMatrixFromLensFile for a double Gauss lens demo.
Form
 [mT, xT] = RayTransferMatrixFromLensFile( l, x, nA )
Inputs
 l             (:)     Lens data structure
                       .r     (1,1) Radius of one surface
                       .t     (1,1) Thickness
                       .matl  (1,:) Material name
                       .index (1,1) Index of Refraction
                       .vNo   (1,1) Abbe V-number, the reciprocal of the
                                relative dispersion of the material
                       .sa    (1,1) Semi aperture
 x             (2,:)   Rays [distance from optical axis;angle]
 nA            (1,1)   Ambient index of refraction
Outputs
 mT            (2,2)   Transfer matrix
 xT            (2,:)   Rays [distance from optical axis;angle]
References: http://en.wikipedia.org/wiki/Ray_transfer_matrix_analysis
References Demo(), length(), LensMakerFormula(), RayTransferMatrix(), RayTransferMatrixFromLensFile(), and ReadLensData().
Referenced by RayTransferMatrixFromLensFile().
ReadImage()
function ReadImage (in f)
Converts to grayscale
Form
 ReadImage;
 g = ReadImage( f )
Inputs
 f              (1,:)       File name
Outputs
 g              (:,:)       Grayscale image
References Demo(), Imager(), ReadImage(), and set().
Referenced by GaussianDerivative(), ImageDerivative(), and ReadImage().
ReadLensData()
function ReadLensData (in file, in ignoredArg)
Set the radius to zero for a flat surface in which case p is the location of the plane. Otherwise p is the location of the center of of the surface.
Type ReadLensData('demo') for a demo.
The file format is tab delimited
 14 deg Split Rear Crown Triplet
 radius thickness material index V-no sa
 56.940  11.2   SSK4  1.618   55.1   26.4
 -69.060   8.600  SF8  1.689   31.2   24.0
 77.520   4.000  air                 21.0
 8.280  air                 21.1 <- a stop
 -818.920  7.200  SK10 1.623   56.9   24.0
 -59.320   0.400  air                 24.0
 162.520   7.20   SK10 1.623   56.9   24.0
 Can also handle files with the material column omitted.
Form
 l = ReadLensData( file, t )
Inputs
 file      (1,:)   File name
Outputs
 l         (:)     Lens data structure
                   .r     (1,1) Radius of one surface
                   .t     (1,1) Thickness
                   .matl  (1,:) Material name
                   .index (1,1) Index of Refraction
                   .vNo   (1,1) Abbe V-number, the reciprocal of the
                                relative dispersion of the material
                   .sa    (1,1) Semi aperture (i.e. radius)
 t         (1,:)   Title
References and(), DrawLens(), length(), ReadLensData(), and StringToTokens().
Referenced by CreateLensTable(), DrawLens(), LensMakerFormula(), RayTraceLens(), RayTransferMatrixFromLensFile(), and ReadLensData().
ReflectionLaw()
function ReflectionLaw (in u1, in n)
 The incoming ray points at the surface.
Form
 u2 = ReflectionLaw( u1, n )
Inputs
 u1              (3,1) Incoming ray
 n               (3,1) Normal
Outputs
 u2              (3,1) Reflected ray
Reference: Hanrahan, P. "Refraction"
References Demo(), Normal(), ReflectionLaw(), Unit(), and vector().
Referenced by ReflectionLaw().
RHSAiryDefocusedPSF()
function RHSAiryDefocusedPSF (in x, in y, in d)
All distance parameters x, y, and r must have the same units. Performs an integration of a Bessel function using trapz.
Form
f =  RHSAiryDefocusedPSF(x,y,d)
Inputs
 x   (:,:)       X coordinates (micro-m)
 y   (:,:)       Y coordinates (micro-m)
 d    (.)        Data structure
                 .d  (.) Data structure for PSF
                           .a      (1,1) Aperture     (mm)
                           .lambda (1,1) Wavelength   (nm)
                           .f      (1,1) Focal length (mm)
                           .bD     (1,1) Defocus phase aberration
                 .r (2,:) Centers of PSF (micro-m)
                 .i (1,:) Intensities of PSF
Outputs
 f   (n,m)       Pixel output
Reference: Virendra N. Mahajan, "Beam Focusing and Depth of Focus," The Aerospace Corporation.
See also
:
besselj, trapz
References abs(), and(), FresnelNumber(), length(), Wavelength(), and zeros().
RHSAiryPSF()
function RHSAiryPSF (in x, in y, in d)
The units within the pixel frame are microns. The aperture and wavelength are specified in millimeters. The wavelength is in nanometers.
Form
f = RHSAiryPSF(x,y,d)
Inputs
 x   (:,:)       X coordinates (um)
 y   (:,:)       Y coordinates (um)
 d   (1,1)       Data structure
                 .d (1,1) Data structure for PSF
                           .a      (1,1) Aperture     (mm)
                           .lambda (1,1) Wavelength   (nm)
                           .f      (1,1) Focal length (mm)
                 .r (2,:) Centers of PSF (um)
                 .i (1,:) Intensities of PSF
Outputs
 f           (n,m)  Pixel output
References and(), length(), Wavelength(), and zeros().
RHSGaussianPSF()
function RHSGaussianPSF (in x, in y, in d)
$$ f = i \exp(-((x - \mu_x)^2 + (y - \mu_y)^2)/(2\sigma^2)) $$
Form
 f = RHSGaussianPSF(x,y,d)
Inputs
 x   (:,:)       X coordinates
 y   (:,:)       Y coordinates
 d    (.)        Data structure
                 .d    (.)  Data structure for PSF
                               .sigma (1,1) Standard deviation
                 .r   (2,:) Centers of PSF
                 .i   (1,:) Intensities of PSF
Outputs
 f   (n,m)       Pixel output
References zeros().
Referenced by FitPSFToData(), ImagerPSF(), IntegratePSFs(), StarCentroidCOM(), and VM2PSFPeak().
RHSMoffatPSF()
function RHSMoffatPSF (in x, in y, in d)
Form
f = RHSMoffatPSF(x,y,d)
Inputs
 x   (:,:)       X coordinates
 y   (:,:)       Y coordinates
 d   (1,1)       Data structure
                 .d      (.)  Data structure for PSF
                               .rho     (1,1) Radial scaling
                               .beta    (1,1) Exponent
                 .r      (2,:) Centers of PSF
                 .i      (1,:) Intensities of PSF
Outputs
 f           (n,m)  Pixel output
Reference: J.R. Parker, "Practical Computer Vision Using C," John Wiley and Sons, 1994.
References and(), and zeros().
RMSNoiseImager()
function RMSNoiseImager (in p)
You pass in the pixel frame of the detector model or any imager frame.
Type RMSNoiseImager for a demo.
Form
 [s, m] = RMSNoiseImager( p )
Inputs
 p           (m,n)   Pixel map
Outputs
 s           (1,1)   RMS Noise
 m           (1,1)   Mean
Reference: http://en.wikipedia.org/wiki/Signal_to_noise_ratio_(imaging)
References Demo(), DetectorModel(), FocalPlaneImage(), Imager(), RMSNoiseImager(), and set().
Referenced by RMSNoiseImager().
SnellsLaw()
function SnellsLaw (in n, in i, in mu)
This can work with 2 or 3 dimensional rays. The refracted ray is in the same direction as the incoming ray. It returns t = [0;0;0] for total internal reflection.
Type SnellsLaw for a demo.
Form
 t = SnellsLaw( n, i, mu )
Inputs
 n               (3,1) Normal
 i               (3,1) Incoming ray
 mu              (1,1) n1/n2
Outputs
 t               (3,1) Refracted ray
Reference: Hanrahan, P. "Refraction"
References vector().
SnellsLawCurve()
function SnellsLawCurve (in r, in s, in nO, in nI, in isConcave)
s(1)x^2 + s(2)y^2 + s(3)xy + s(4)x + s(5)y + s(6) = 0
A circle of radius 2 with origin [0;0] would have s = [1 1 0 0 0 -4]
If the lens center is on the x axis and its radius is r we get
(x-x0)^2 + y^2 = r^2
or [1 1 0 -2x0 0 x0^2-r^2]
with a ray of the form x = at + x0, y = bt + y0;
All output vectors are unitized.
Type SnellsLaw for a demo showing 3 rays hitting a circle.
Form
 [rO, miss] = SnellsLawCurve( r, s, nO, nI, isConcave )
Inputs
 r               (:)  Ray structure
                       .m  (2,1) [a;b] (slopes)
                       .p  (2,1) [x0;y0]
 s               (1,6) Curve coefficients [x^2 y^2 xy x y 1]
 nO              (1,1) Index of refraction outside
 nI              (1,1) Index of refraction inside
 isConcave       (1,1) 1 = concave default is convex
Outputs
 rO              (:)   Ray structure
                        .m  (2,1) [a;b]
                        .p  (2,1) [x0;y0]
 miss            (:)   1 if the ray missed
Reference: Hanrahan, P. "Refraction"
Referenced by RayTraceLens(), and RayTraceMirror().
StarCentroid()
function StarCentroid (in i, in x, in y)
This uses the point spread function method.
Type StarCentroid for a demo which will draw the centroid and the intensity map.
Form
 [x0, y0] = StarCentroid( i, x, y )
Inputs
 i            (1,:)  Intensity
 x            (1,:)  x coordinate
 y            (1,:)  y coordinate
Outputs
 x0           (1,1)  x centroid
 y0           (1,1)  y centroid
Reference: C. Fosu, G. W. Hein, B. Eissfeller, "Determination of Centroid of CCD Star Images," ISPRS XXXV Congress.
References and(), Demo(), get(), length(), Mag(), Map(), NewFig(), StarCentroid(), and zeros().
Referenced by StarCentroid().
StellarMagnitude()
function StellarMagnitude (in mIn, in units)
Form
 StellarMagnitude
 [i, type] = StellarMagnitude( mIn, units )
Inputs
 mIn      (1,1) Magnitude
 units    (1,:) 'lux' or 'w/m^2'
Outputs
 i        (1,1) Intensity
 type     (1,:) Example of this intensity
See also
VM2Int
References StellarMagnitude(), and VM2Int().
Referenced by StellarMagnitude().
StrehlRatio()
function StrehlRatio (in bD, in N)
Type StrehlRatio for a demo.
Form
 s = StrehlRatio( bD, N )
Inputs
 bD          (1,:)   Defocus parameter
 N           (1,1)   Fresnel number
Outputs
 s           (1,1)  Strehl Ratio
Reference: Virendra N. Mahajan, "Beam Focusing and Depth of Focus," The Aerospace Corporation.
References and(), Demo(), FresnelNumber(), length(), Plot2D(), and StrehlRatio().
Referenced by StrehlRatio().
TargetInFocalPlane()
function TargetInFocalPlane (in p, in qTToI, in qCToI, in d, in e, in v, in f, in i)
Type TargetInFocalPlane for a demo
Form
 p = TargetInFocalPlane( p, qTToI, qCToI, d, e, v, f, i )
Inputs
 p           (n,m)   Pixel map
 qTToI       (4,1)   Quaternion from target to ECI
 qCToI       (4,1)   Quaternion from camera to ECI
 d           (3,1)   Vector from camera to target in the ECI frame
 e            (.)    Optics data structure
 v           (:,3)   Vertices
 f           (:,3)   Face list
 i           (1,:)   Radiance of each face
Outputs
 p           (n,m)   Pixel map
References Demo(), DupVect(), FocalPlaneImage(), length(), PinholeCamera(), PointInGridInTriangle(), QForm(), QMult(), QPose(), Radiance(), set(), TargetInFocalPlane(), vector(), and zeros().
Referenced by TargetInFocalPlane().
VM2Photons()
function VM2Photons (in v, in lambda)
Default is 500 nm.
The apparent visual magnitude of the Sun is -26.85.
Type VM2Photons to see photon flux as a function of visual magnitude and wavelength.
Form
 i = VM2Photons( v, lambda )
Inputs
 v                 (:)    Visual magnitude
 lambda            (1,1)  Wavelength (nm)
Outputs
 i                 (:)    Intensity (photons/s/m^2)
References: Berry, M. (1981). Principles of cosmology and gravitation. Cambridge University Press, Cambridge, England, 10.
References and(), Demo(), length(), VM2Photons(), Wavelength(), and zeros().
Referenced by VM2Photons().
VMToPhotons()
function VMToPhotons (in vM, in t, in l)
 Includes corrections for temperature and wavelength.
Inputs
greater than 1 they must have the same length.
 Type VMToPhotons for a demo.
 Since version 11.
Form
 p = VMToPhotons( vM, t, l )
Inputs
 v                 (1,:)  Visual magnitude
 t                 (1,:)  Temperature (deg-K)
 l                 (1,:)  Wavelength (nm)
Outputs
 i                 (:)   Photons/s/m^2/micron
References: Witthoft, C. http://pubpages.unh.edu/~mwidholm/MathPad/ examples/starmag.txt
References and(), Demo(), isempty(), length(), Plot2D(), VMToPhotons(), and Wavelength().
Referenced by VMToPhotons().
ZodiacalLight()
function ZodiacalLight (in r, in beta)
The zodiacal light is caused by sunlight scattered by interplanetary dust particles.
Type ZodiacalLight for a demo
Form
 m = ZodiacalLight( r, beta )
Inputs
 r         (1,:) Radius from the sun (AU)
 beta      (1,:) Ecliptic latitude (rad)
Outputs
 m         (1,:) Intensity (W/m^2/rad^2)
Reference: R. Meissner, "Brightness Measurements of Stars and the Night-Sky with a Silicon-Photomultiplier-Telescope" Physikalischen Institut A, 9/2012.
References and(), Demo(), length(), Plot2D(), square(), VM2Int(), and ZodiacalLight().
Referenced by DetectorModel(), and ZodiacalLight().