PSS MATLAB Toolboxes: Plotting Functions
Plotting Functions
Plotting Module
Directories
directory GUI
directory Parametric
Support for parametric plots.
directory Templates
Templates for simulation types.
directory Utilities
Plotting utilities.
Description
Functions
function AnimationGUI (in action, in varargin)
This function creates a GUI for doing animations.
function AppliedDeltaVDPT (in varargin)
Compute the applied delta-v from the applied force.
function ComputeDeltaV (in varargin)
Takes the 3-axis force in [kg*m/s/s] and computes the delta-v in [m/s].
function ComputeDistance (in varargin)
Computes the distance of each spacecraft from the center, given the.
function DerivationTemplate (in varargin)
The template for new derivation functions.
function DeriveData (in action, in modifier)
This function creates an interface for deriving data.
function Difference (in varargin)
Differences two vectors.
function DifferenceMagnitude (in varargin)
Compute the magnitude of the difference between vectors.
function DisplayFilter (in action, in modifier)
This function creates an interface for displaying variables in the.
function ECI2HillsDFF (in varargin)
Transform ECI pos & vel to Hills pos & vel for FormationFlying sims.
function FormatUnderscore (in sIn)
Replaces all underscores in strings with '\_'.
function GetSimData (in file, in dataName, in iD)
Get the data from an ObjectAgent simulation.
function GroupVariables (in action, in modifier)
This function creates an interface for grouping variables.
function InitializeAxes (in handle, in scData, in tgtData, in time, in keepView, in point, in cameraTarget, in axisType)
Initialize the axes for an animation with AnimationGUI.
function MagDPT (in varargin)
Compute the Magnitude of a vector of data in the PlottingTool.
function ParamGUI (in action, in modifierA, in modifierB)
This GUI allows you to make parametric plots.
function ParamPlot (in data, in yName, in xName, in figName, in figNum, in prop, in propVal)
Parametric Plotting.
function ParamStruct (in varargin)
Create a parametric plotting data structure.
function PlotCone (in z, in u, in theta, in fig, in color)
Creates a cone with angular width 2*theta about the vector u.
function PlotEngine (in y, in yName, in x, in xName, in sat, in satPB, in var, in varPB, in elmPB, in figName, in figNum, in prop, in propVal, in hAxes)
Create figures with automatically labeled and organized plots.
function PlottingTool (in action, in modifier, in data)
Plot and animate simulation data from a GUI.
function PlottingToolStruct (in r, in t)
Save 3D trajectories in the PlottingTool format.
function PlotVector (in v, in fig, in color)
Plots a set of 2-D or 3-D vectors.
function PTVersion (in action, in v, in ignoredArg)
Output the version string.
function ReadOutputFile (in fId, in fileName)
Read in simulation output text file for use with the PlottingTool.
function RotateECI2Hills (in varargin)
Transform ECI frame coordinates to Hills frame.
function RV2ElDPT (in varargin)
Transform ECI position and velocity into orbital elements.
function SMADiffDPT (in varargin)
Compute the semi-major axis difference between each spacecraft and its reference.
function TransformECI2Hills (in varargin)
A Plotting Tool derivation function for transforming ECI coordinates to Hills frame.
Function Documentation
AnimationGUI()
function AnimationGUI (in action, in varargin)
 Callback Usage:
 x = AnimationGUI( action, a, b, c  )
 Command Line Usage:
 AnimationGUI( 'initialize', scData, tgtData, time, options )
Inputs
 action          (1,:)   Action to take. Use 'initialize' to create GUI.
 scData           (.)    Spacecraft data strcture. Fields:
                           .r    (3,n)    Position
                           .t    (1,n)    Time
                           .c    (3,1)    Constant color, OR:
                           .c    (3,n)    Time-varying color
                           .name (:)      Name for labeling
                           .axis (3,n)    Axis vector for pointing cone
                           .angle(1,n)    Field of view of cone
 tgtData          (.)    Target data strcture.     Fields: r, t, c
 time            (1,N)   Time vector with N points.
 options          (.)    Data structure with display options.
   .axisType     (1,:)   Specifies how to draw axis background
                         and labels. Choices: 'Hills', 'LVLH', 'Earth',
                         'EarthHR' or any other planet name. If a planet
                         is chosen it will be drawn in the background.
                         In this case it is best to supply planet-fixed
                         coordinates so that the trajectory is drawn
                         properly with respect to the planet image.
   .docked       (1,1)   Flag. Specify whether the axes are docked with
                         the UI controls (1) or in a separated window (0)
   .view         (1,:)   String. '2D' or '3D'. If 2D, 3rd row is set to 0.
   .date         (1,1)   Initial Julian date, for lighting of planet axis type
                         only. In this case the time units must be seconds
                         for accurate lighting effects.
Outputs
 x                (:)    Outputs only supplied when called as a callback
                         function from the GUI.
See also
: InitializeAxes
References and(), Constant(), InitializeAxes(), set(), and vector().
Referenced by CameraControls(), FFEccGenerateTeamGoals(), FFEccHexahedronGeometry(), FFEccTetrahedronGeometry(), InitializeAxes(), PackageOrbitDataForPlayback(), PlaybackOrbitSim(), and ViewRelativeMotion().
AppliedDeltaVDPT()
function AppliedDeltaVDPT (in varargin)
Form
 out = AppliedDeltaVDPT( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
References length().
ComputeDeltaV()
function ComputeDeltaV (in varargin)
Form
 out = ComputeDeltaV( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
References and(), and length().
ComputeDistance()
function ComputeDistance (in varargin)
 relative position vector.
Form
 out = ComputeDistance( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
References length(), and vector().
DerivationTemplate()
function DerivationTemplate (in varargin)
 An example of transforming from ECI to Hills frame is provided.
Form
 out = DerivationTemplate( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
References length().
DeriveData()
function DeriveData (in action, in modifier)
 in the  Plotting Tool.
Form
 DeriveData( action, modifier  )
Inputs
 action          (1,:)   Action to be taken by the gui (used mostly
                         for callbacks)
 modifier        (1,:)   Modifier to the action
Outputs
References CloseFigure(), CreateCallback(), DeriveData(), get(), GetH(), Initialize(), isempty(), PlottingTool(), PutH(), and set().
Referenced by DeriveData().
Difference()
function Difference (in varargin)
Form
 out = Difference( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
References length().
Referenced by AC(), CollisionMonteCarlo(), DeltaElem2Hills(), GaussianCPDF(), GenSub(), JacobianODE(), LPvsCF(), RHSClockDrift(), and SSFromNonlinear().
DifferenceMagnitude()
function DifferenceMagnitude (in varargin)
Form
 out = DifferenceMagnitude( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
References length().
DisplayFilter()
function DisplayFilter (in action, in modifier)
 Plotting Tool
Form
 x = DisplayFilter( action, modifier  )
Inputs
 action          (1,:)   Action to be taken by the gui (used mostly
                         for callbacks)
 modifier        (1,:)   Modifier to the action
Outputs
 x
References CloseFigure(), CreateCallback(), DisplayFilter(), get(), GetH(), Initialize(), isempty(), PlottingTool(), PutH(), and set().
Referenced by DisplayFilter().
ECI2HillsDFF()
function ECI2HillsDFF (in varargin)
Form
 out = ECI2HillsDFF( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
FormatUnderscore()
function FormatUnderscore (in sIn)
 so that the underscore is not
 interpreted as a subscript for text graphics.
 Works with either a string input or a cell array of strings.
 Type FormatUnderscore for a demo.
Form
 sOut = FormatUnderscore( sIn )
Inputs
 sIn             {:}    Text to be modified
Outputs
 sOut            {:}    Converted strings
References FormatUnderscore().
Referenced by FormatUnderscore().
GetSimData()
function GetSimData (in file, in dataName, in iD)
Form
 y = GetSimData( file, dataName, iD)
Inputs
 file          (1,:)  Name of simulation file
 dataName       (m,:) Name of simulation data
                      Enter '?' for a list of all names
 iD             (1,1)  Spacecraft I.D.
Outputs
 y             {n}(m,:) Matrix of simulation data
GroupVariables()
function GroupVariables (in action, in modifier)
 used by the Plotting Tool.
Form
 x = GroupVariables( action, modifier  )
Inputs
 action          (1,:)   Action to be taken by the gui (used mostly
                         for callbacks)
 modifier        (1,:)   Modifier to the action
Outputs
 x
References CloseFigure(), CreateCallback(), get(), GetH(), GroupVariables(), Initialize(), isempty(), PlottingTool(), PutH(), and set().
Referenced by GroupVariables().
InitializeAxes()
function InitializeAxes (in handle, in scData, in tgtData, in time, in keepView, in point, in cameraTarget, in axisType)
Form
 InitializeAxes( handle, scData, tgtData, time, keepView, point, cameraTarget, axisType  )
Inputs
 handle                 Handle to the axes
 scData                 Data structure with position & time for each spacecraft
 tgtData                Data structure with position & time for each target
 time                   Time data
 keepView               Flag indicating whether to keep the current view or not
 point*
 cameraTarget*
 axisType               Specify the type of axes to use.
                           'default'   x, y, z
                           'Hills'     x-Radial, y-Along-track, z-Cross-track
                           'LVLH'      x-Along-track, y-Cross-track, z-Radial
                           'PLANET'    The planet will be drawn in the background
Outputs
 d                      Data structure for AnimationGUI.
References AnimationGUI(), Cross(), Initialize(), and length().
Referenced by AnimationGUI().
MagDPT()
function MagDPT (in varargin)
Form
 out = MagDPT( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
References length(), PlottingTool(), and vector().
ParamGUI()
function ParamGUI (in action, in modifierA, in modifierB)
Form
 ParamGUI( action, modifier  )          For callbacks
 ParamGUI( ds )                         To initialize with a data structure
 ParamGUI                               To initialize empty
Inputs
 action          (1,:)   Action to be taken by the developer (used mostly
                         for callbacks)
 modifierA       (1,:)   Modifier to the action
 modifierB       (1,:)   Modifier to the action
Outputs
 None
References and(), CreateCallback(), get(), Initialize(), and ParamGUI().
Referenced by ParamGUI().
ParamPlot()
function ParamPlot (in data, in yName, in xName, in figName, in figNum, in prop, in propVal)
Form
 y = ParamPlot( data, yName, xName )
Inputs
 data                (.)  Parametric Plotting Data Structure
 yName               (:)  Name of variable to plot
 xName               (:)  Name of x-axis variable
 figName             (:)  Figure title (optional)
 figNum              (1)  Figure number (optional)
Outputs
 y                 {i}(j,k) i cells of j vectors, k long
ParamStruct()
function ParamStruct (in varargin)
Form
 ParamDS = ParamStruct( varargin )
Inputs
 varargin           {:}   Pairs of parameter names / parameter values.
Outputs
 ParamStruct        Parametric plotting data structure
PlotCone()
function PlotCone (in z, in u, in theta, in fig, in color)
 Type PlotCone for a demo
Form
 PlotCone( z, u, theta, fig, color )
Inputs
 z             (3,1)     Location of cone point
 u             (3,1)     Center axis of the cone
 theta          (1)      Half-width of the cone [deg]
 fig            (1)      Figure handle (optional)
 color          (:)      Color of the cone (optional, default blue)
Outputs
 none
References Cross(), isempty(), Mag(), NewFig(), PlotCone(), set(), Unit(), vector(), and zeros().
Referenced by PlotCone().
PlotEngine()
function PlotEngine (in y, in yName, in x, in xName, in sat, in satPB, in var, in varPB, in elmPB, in figName, in figNum, in prop, in propVal, in hAxes)
Form
 PlotEngine( y, yName, x, xName, sat, satPB, var, varPB, elmPB, figName, figNum, prop, propVal, hAxes );
 Note:  The y-axis data is grouped by two categories, satellite and variable.
 It is a cell array of "k" matrices, with each matrix of size "lxm".
 - k   Number of satellites (or similar grouping)
 - l   Number of variables (assuming single element)
 - m   Length of the x-data.
Inputs
 y              {k}(l,m) y-axis data
 yName              (:)  Name of y-axis data (can include units)
 x                 (:,m) x-axis data
 xName              (:)  Name of x-axis data (can include units)
 sat             {k}(:)  Satellite names
 satPB              (:)  Satellite plot method
 var             {l}(:)  Variable names
 varPB              (:)  Variable plot method
 elmPB              (:)  Element plot method
 figName            (:)  Figure Name
 figNum             (1)  Fignure Number
 prop               (:)  String name of a plotting property
 propVal            (:)  Value associated with property
 hAxes              (1)  handle to the axes
Outputs
 none
References and().
PlottingTool()
function PlottingTool (in action, in modifier, in data)
To load data from the workspace:
 PlottingTool( 'load sim data', d );
where "d" is a data structure with fields:
 .time
 .data
 .dataNames
 .objNames
 .units
Form
 tag = PlottingTool( action, modifier )
Inputs
 action          (1,:)   Action to be taken
 modifier        (:)     Modifier to the message
Outputs
 tag             (1,:)   Returns the window tag on initialization
References and(), and close().
Referenced by DeriveData(), DisplayFilter(), GroupVariables(), MagDPT(), PlottingToolStruct(), PTVersion(), and ReadOutputFile().
PlottingToolStruct()
function PlottingToolStruct (in r, in t)
 Use the output of this function in this call:
 PlottingTool( 'load sim data', d );
Form
 d = PlottingToolStruct( r, t )
Inputs
 r               (3,n)   3D position vectors
 t               (1,n)   Time vector, optional
Outputs
 d                (:)    Data structure formatted for PlottingTool
  .data
  .dataNames
  .time
  .groups
References PlottingTool(), and vector().
PlotVector()
function PlotVector (in v, in fig, in color)
 The vectors are drawn from the origin using quiver.
 Has a built-in demo which uses the Coordinates function to make a
 figure with axes, and three random vectors are drawn in white.
Form
 q = PlotVector( v, fig, color )
Inputs
 v             (m,n)   Set of vectors, where m is the dimension (2 or 3),
                       and n is the number of vectors
 fig            (1)    Figure handle (optional)
 color          (:)    Color of vector (optional, default 'white')
Outputs
 q              (:)    Handles to quiver objects
References and(), Coordinates(), Demo(), isempty(), length(), Mag(), PlotVector(), set(), Unit(), vector(), and zeros().
Referenced by PlotVector(), and SailForceSubplots().
PTVersion()
function PTVersion (in action, in v, in ignoredArg)
Outputs
 action      (1,:)     'get' or 'check'
 v           (1,:)     Version string
 fileName    (1,:)     The filename being checked
Outputs
 s           (1,:)    Version string
References get(), and PlottingTool().
ReadOutputFile()
function ReadOutputFile (in fId, in fileName)
Form
 d = ReadOutputFile( fId, fileName )
Inputs
 fId                          (1)      Id of file to be read
 fileName                     (:)      Optional input string for error messages
Outputs
 d                            (1)      Data structure with the following fields
                                       ( nD  = number of data elements
                                         nObj= number of objects
                                         nT  = number of time points )
 .data                   {1,nSc}  Cell array of (nDxnT) matrices of raw data
 .dataNames              {1,nD}   Cell array of strings of element names
 .dataUnits              {1,nD}   Cell array of strings of element units
 .excluded               {1,:}    Cell array of names of elements not to be displayed
 .groups                 (:)      Array of data structures of grouped elements
 .name       (:)      String of group name
 .elements   {1,:}    Cell array of names of elements to be included in group
 .jDEpoch                (1)      Start time of simulation as Julian date
 .objNames               {1,nSc}  Cell array of strings of object names
 .time                   (1,nT)   Vector of elapsed simulation time in seconds
References PlottingTool().
RotateECI2Hills()
function RotateECI2Hills (in varargin)
Form
 out = RotateECI2Hills( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
References length().
RV2ElDPT()
function RV2ElDPT (in varargin)
Form
 out = RV2ElDPT( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
References and(), and length().
SMADiffDPT()
function SMADiffDPT (in varargin)
Form
 out = SMADiffDPT( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
References and(), and length().
TransformECI2Hills()
function TransformECI2Hills (in varargin)
Form
 out = TransformECI2Hills( varargin )
Inputs
 varargin         (:)   Variable number of inputs, raw simulation data.
Outputs
 out             (1,:)  Derived output data.
References length().