PSS MATLAB Toolboxes: Missions Functions
Missions Functions
Missions Module
The Missions module functions.
Directories
directory Comsat
Commercial GEO satellite example.
directory ComsatData
Data for the Comsat mission.
directory FastReorientation
Fast slew maneuver example.
directory SunNadir
Implement sun-nadir pointing control.
Description
Functions
function ATTDataT (in dT, in nPts)
Generates the data needed for a attitude data collection in TrnsfOrb.m.
function CDist (in a)
Control demand distribution.
function ComStar (in q, in gUICode)
The ComStar satellite properties database GUI.
function Core2SA (in a, in u)
Transform core frame to solar array frame.
function DlVDataT (in deltaV)
Generates the data needed for a delta Vs in TrnsfOrb.m.
function DST (in w, in nSim, in database, in dT)
Simulate a dual-spin-turn.
function DSTDataT (in nSim, in dT)
Generates the data needed for a dual spin turn in TrnsfOrb.m.
function FRSCGen (in axis0, in af, in bf, in cf, in df, in xmodel, in tbbscale, in qrefto0i, in umnvr, in xf, in dt, in nhalf, in rate, in iner, in maxaccel, in i)
Executes the fast reorientation system slew maneuver.
function FRSMPlan (in qRefTo0, in maxAccel, in dT, in iner, in qRefTo1)
Plans the fast reorientation system slew maneuver.
function FRSProp (in aF, in bF, in cF, in dF, in xF, in axis0, in xModel, in tBBScale, in qRefTo0i, in uMnvr, in dT, in rate, in iner, in maxAccel)
Propagates the target profile for the fast reorientation slew maneuver.
function FRSTarg (in qRefTo0, in uSensor0, in uTargetRef)
Compute the target quaternion for the fast reorientation system.
function FRSTorque (in aF, in bF, in cF, in dF, in xF, in tBBScale, in uMnvr, in nHalf, in rate, in iner, in i)
Calculates the torque for the fast reorientation system slew maneuver.
function FuelUpdt (in fuelUsed, in tId, in fuelMass, in database)
Updates the fuel mass.
function GetHSA (in w, in rA, in dec, in el, in jD0, in dT, in nPts, in database)
Gets HSA attitude data.
function HSMA (in mA, in id)
Computes the half system moment arms.
function I2B (in q, in uI)
Transform sun vector from I frame to body frame.
function ICSN (in xNoSun, in orbitRate, in beta, in alpha, in alphaLimit)
Initial quaternion and solar array angle given the sun geometry.
function InjDataT (in elements, in rA, in dec, in w, in hW)
Generates the data needed for an injection in TrnsfOrb.m.
function IntData (in elements, in rA, in dec, in w, in hW, in fuelMass)
Generates the data needed for initialization in TransferOrbit.m.
function OddEven (in thrusterIDs)
Count the number of odd and even numbered thrusters in use.
function OrbitDeltaV (in el, in dV, in mu)
Updates orbital elements based on an impulsive delta-V.
function PitchEst (in x, in p, in dT, in iZ, in q, in r, in u, in z, in zValid)
Kalman Filter for pitch.
function PitchLoop (in inrPitch, in inrWheel, in beta, in zetaM, in zetaP)
Design the Pitch Loop including a tach loop for the wheel.
function Pressure (in mFuel, in database, in temp)
Computes the REA and tank pressure.
function REA (in id, in p, in dT, in database)
Computes the thrust and fuel consumed for thrusters.
function RHSSNP (in x, in ignoredArg, in inr, in invInr, in tExt, in inrW, in uW, in tW, in eSAC)
Spacecraft sun-nadir RHS with 4 RWA's and 2 solar arrays.
function RollEst (in inr, in hW, in wo, in q, in r, in dT, in sType)
Designs the dual-spin-turn roll estimator.
function SA2Core (in a, in u)
Transform a vector from the sun sensor frame to the core frame.
function SAForm (in e)
Creates a small angle transformation matrix.
function Shadow (in sunAlpha, in sunBeta, in s)
Find the surfaces that are in shadow.
function SKDataF (in dV, in cM, in tDist, in aCSThrusters, in dVThrusters, in plumeDrag)
Generates the data needed to compute stationkeeping maneuvers.
function SpinChange (in p, in axis, in w, in wF, in wait, in inertia, in cM, in tId, in eventName, in database)
Simulates a spin change.
function SpinDataF (in inr, in iAxis, in cM, in dW, in thrusters)
Computes spin precession maneuver data for fuel budgets.
function SpinDataT (in axis, in wF, in tID, in dTDelay)
Generates the data needed for a spin change in TrnsfOrb.m.
function SpinREst (in accel, in K, in x, in T, in pulsewidth)
Estimates rate from measurements of period.
function SPMDataF (in inr, in cM, in w, in attI, in attF, in pwF, in jD, in thrusters)
Computes spin precession maneuver data for fuel budgets.
function SPMDataT (in tID, in pulsewidth, in rAF, in decF)
Generates the data needed for an SPM maneuver in TrnsfOrb.m.
function SPMMnvr (in p, in tId, in pulsewidth, in jD, in inertia, in cM, in w, in rAI, in decI, in rAF, in decF, in database)
Performs a spin precession maneuver.
function SSAD (in mSS, in eyeCoeff, in uSun, in roll)
Sun sensor attitude determination for sun-nadir pointing.
function SSOutput (in e, in nE, in u, in uSun, in a, in n)
Models the output for array mounted analog sun sensors.
function SunRA (in i, in uSun, in beta)
Compute the orbit right ascension angle.
function ThrstLevel (in time, in pulsewidth, in fallConst, in)
Computes the thrust level of a set of thrusters.
function ThrustModel ()
Computes the thruster torques based on exponential rise and fall time model.
function TransferOrbit (in event, in mET, in a, in eventName, in dateStart, in database, in units)
Simulates transfer orbit.
Function Documentation
ATTDataT()
function ATTDataT (in dT, in nPts)
 Since version 1.
Form
 x = ATTDataT( dT, nPts )
Inputs
 dT         (1,1)   Time between samples (sec)
 nPTS       (1,1)   Number of samples
Outputs
 x          (2,1)   Formatted data
CDist()
function CDist (in a)
Finds the actuation distribution matrix that distributes a control demand among n bidirectional actuators. The control distribution matrix is found be solving the constrained optimization problem
 J = 0.5*u'*u + L( x - a*u )
where x is the desired control demand. The control demand for each actuator is found from
 u = h*x;
Form
 h = CDist( a )
Inputs
 a            (m,n)     The unit vectors for the actuators
                        where the control demand is of length m
                        and the number of actuators equal to n
Outputs
 h            (n,m)     The control distribution matrix
ComStar()
function ComStar (in q, in gUICode)
If q = 'Catalog' it will list a catalog of available data. Inputs are case sensitive.
Form
 [x, u] = ComStar( q, gUICode )
Inputs
 q             (1,:)    String describing the type of data
Outputs
 x             (:,:)    The properties
 u             (1,:)    Units
References ComStar(), Database(), get(), HelpSystem(), isempty(), length(), and set().
Referenced by ComStar(), and GetHSA().
Core2SA()
function Core2SA (in a, in u)
Transforms a vector from the core frame to the solar array frame when the sun sensor is attached to a solar array that is rotated an angle a with respect to the core. When a = 0 the +z array axis is aligned with the +z core axis.
Form
 v = Core2SA( a, u )
Inputs
 a            (1,1)      Angle (rad)
 u            (3,1)     Vector in the core frame
Outputs
 v             (3,1)    Vector in the array frame
References vector().
Referenced by SSOutput().
DlVDataT()
function DlVDataT (in deltaV)
 Since version 1.
Form
 x = DlVDataT( deltaV )
Inputs
 deltaV      (1,1)   Delta V (km/sec)
Outputs
 x           (1,1)   Formatted data
DST()
function DST (in w, in nSim, in database, in dT)
Form
 [w, wMWA, q, t] = DST( w, nSim, database, dT )
Inputs
 w              (3,1)   Body rate at start (rad/sec)
 nSim           (1,1)   Number of steps
 database       (1,:)   Database
 dT             (1,1)   Time step
Outputs
 w              (3,1)   Body rate at finish
 wMWA           (3,1)   Momentum wheel speed
 q              (4,:)   Quaternion
 t              (1,:)   Time
References abs(), and(), Database(), DST(), DSTCrit(), FGs(), length(), NewFig(), RK4(), XLabelS(), YLabelS(), and zeros().
Referenced by DST(), and TransferOrbit().
DSTDataT()
function DSTDataT (in nSim, in dT)
 Since version 1.
Form
 x = DSTDataT( nSim, dT )
Inputs
 nSim        (1,1)   Number of simulation steps
 dT          (1,1)   Step size
Outputs
 x           (2,1)   Formatted data
References Step().
FRSCGen()
function FRSCGen (in axis0, in af, in bf, in cf, in df, in xmodel, in tbbscale, in qrefto0i, in umnvr, in xf, in dt, in nhalf, in rate, in iner, in maxaccel, in i)
 This is a combination of both the FRSProp and FRSTorque functions.
 i.e. It computes the maneuver torque and updates the model at the
 same rate.
 Since version 2.
Form
 [qrefto0, modelrate, tfrs, xmodel, umnvrf, umnvr, xf]
 = FRSCGen( axis0, af, bf, cf, df, xmodel, tbbscale, qrefto0i,
 umnvr, xf, dt, nhalf, rate, iner, maxaccel, i )
Inputs
 axis0         (3,1)   The maneuver axis unit vector
 af            (n,n)   The shaping filter plant matrix
 bf            (n,1)   The shaping filter input matrix
 cf            (1,n)   The shaping filter measurement matrix
 df            (1,1)   The shaping filter feedthrough matrix
 xmodel        (2,1)   Initial model angle and rate (0,0)
 tbbscale      (1,1)   Converts acceleration to torque
 qrefto0i      (4,1)   Quaternion from sensor/axis to s/c at start
 umnvr         (1,1)   Sign of the maneuver
 xf            (n,1)   The shaping filter state
 dt            (1,1)   The control time period
 nhalf         (1,1)   Half the number of control periods in the maneuver
 rate          (3,1)   The body rate
 iner          (3,3)   The inertia matrix
 maxaccel      (1,1)   The maximum acceleration
 i             (1,1)   The maneuver step
Outputs
 qrefto0       (4,1)   Quaternion from reference to spacecraft axes
 modelrate     (3,1)   The model body rate
 tfrs          (3,1)   FRS torque
 xmodel        (2,1)   Model angle and rate (0,0)
 umnvrf        (1,1)   Maneuver acceleration command output of filter
 umnvr         (1,1)   Sign of the maneuver
 xf            (n,1)   The shaping filter state
References and(), AU2Q(), Cross(), FRSProp(), FRSTorque(), QMult(), quaternion(), and vector().
FRSMPlan()
function FRSMPlan (in qRefTo0, in maxAccel, in dT, in iner, in qRefTo1)
 All outputs feed the command generator.
 Since version 2.
Form
 [qRefTo0, axis0, maxAccel, nHalf, tBBScale, xModel, uMnvr]
 = FRSMPlan( qRefTo0, maxAccel, dT, iner, qRefTo1 )
Inputs
 qRefTo0        (4,1)  Quaternion from the reference to the s/c
 maxAccel       (1,1)  Maximum acceleration
 dT             (1,1)  Control time period
 iner           (3,3)  Inertia matrix
 qRefTo1        (4,1)  Target quaternion
Outputs
 qRefTo0       (4,1)   Initial quaternion from the reference to the s/c
 axis0         (3,1)   Maneuver axis unit vector
 maxAccel      (3,1)   Maximum acceleration
 nHalf         (1,1)   Half the number of control periods in the maneuver
 tBBscale      (3,1)   Converts acceleration to torque
 xModel        (2,1)   Initial model angle and rate (0,0)
 uMnvr         (1,1)   Starting sign of the maneuver (+1)
References abs(), and(), Q2AU(), QMult(), QPose(), quaternion(), vector(), and zeros().
FRSProp()
function FRSProp (in aF, in bF, in cF, in dF, in xF, in axis0, in xModel, in tBBScale, in qRefTo0i, in uMnvr, in dT, in rate, in iner, in maxAccel)
 Since version 2.
Form
 [qRefTo0, modelRate, xModel, xF]
 = FRSProp( aF, bF, cF, dF, xF, axis0, xModel, tBBScale, qRefTo0i,
 uMnvr, dT, rate, iner, maxAccel )
Inputs
 aF            (n,n)   The shaping filter plant matrix
 bF            (n,1)   The shaping filter input matrix
 cF            (1,n)   The shaping filter measurement matrix
 dF            (1,1)   The shaping filter feedthrough matrix
 xF            (n,1)   the shaping filter state
 axis0         (3,1)   The maneuver axis unit vector
 xModel        (2,1)   initial model angle and rate (0,0)
 tBBScale      (1,1)   Converts acceleration to torque
 qRefTo0i      (4,1)   Quaternion from sensor/axis to s/c at start
 uMnvr         (1,1)   Sign of the maneuver
 dT            (1,1)   The propagation period
 rate          (3,1)   The body rate
 iner          (3,3)   The inertia matrix
 maxAccel      (1,1)   The maximum acceleration
Outputs
 qRefTo0       (4,1)   Quaternion from reference to s/c
 modelRate     (3,1)   The model body rate
 xModel        (2,1)   Model angle and rate
 xF            (n,1)   The shaping filter state
References and(), AU2Q(), QMult(), quaternion(), and vector().
Referenced by FRSCGen().
FRSTarg()
function FRSTarg (in qRefTo0, in uSensor0, in uTargetRef)
 This routine assumes that you wish to
 point uSensor0 (which is input in the spacecraft frame) at
 uTargetRef which is input in the reference frame.
 Since version 2.
Form
 qRefTo1 = FRSTarg( qRefTo0, uSensor0, uTargetRef )
Inputs
 qRefTo0        (4,1)  Quaternion from the reference to the s/c
 uSensor0       (3,1)  Sensor unit vector in the s/c frame
 uTargetRef     (3,1)  Target vector in the reference frame
Outputs
 qRefTo1        (4,1)  Quaternion from the reference to the s/c target
References AU2Q(), Cross(), QForm(), QMult(), quaternion(), Unit(), and vector().
FRSTorque()
function FRSTorque (in aF, in bF, in cF, in dF, in xF, in tBBScale, in uMnvr, in nHalf, in rate, in iner, in i)
 Since version 2.
Form
 [tFRS, uMnvrF, uMnvr, xF]
 = FRSTorque( aF, bF, cF, dF, xF, tBBScale, uMnvr, nHalf, rate, iner, i )
Inputs
 aF            (n,n)   The shaping filter plant matrix
 bF            (n,1)   The shaping filter input matrix
 cF            (1,n)   The shaping filter measurement matrix
 dF            (1,1)   The shaping filter feedthrough matrix
 xF            (n,1)   The shaping filter state
 tBBScale      (1,1)   Converts acceleration to torque
 uMnvr         (1,1)   Sign of the maneuver
 nHalf         (1,1)   Half the number of control periods in the maneuver
 rate          (3,1)   The body rate
 iner          (3,3)   The inertia matrix
 i             (1,1)   The maneuver step
Outputs
 tFRS          (3,1)   frs torque
 uMnvrF        (1,1)   Maneuver acceleration command output of filter
 uMnvr         (1,1)   Sign of the maneuver
 xF            (n,1)   The shaping filter state
References Cross().
Referenced by FRSCGen().
FuelUpdt()
function FuelUpdt (in fuelUsed, in tId, in fuelMass, in database)
 This function can handle any number of thrusters and any number
 of fuel tanks (i.e. elements of fuelMass.)
 Since version 1.
Form
 fuelMass = FuelUpdt( fuelUsed, tId, fuelMass, database )
Inputs
 fuelUsed     (1,n)     Fuel used by thrusters
 tId          (1,n)     Thrusters used
 fuelMass     (1,m)     Fuel mass
 database     (1,:)     Spacecraft properties database
Outputs
 fuelMass     (1,m)     Fuel mass
References and(), length(), and REA().
Referenced by TransferOrbit().
GetHSA()
function GetHSA (in w, in rA, in dec, in el, in jD0, in dT, in nPts, in database)
 Since version 1.
Form
 GetHSA( w, rA, dec, el, jD0, dT, nPts, database )
Inputs
 w               (3,1)  Body rate
 rA              (1,1)  Right ascension (rad)
 dec             (1,1)  Declination (rad)
 el              (1,6)  Keplerian Elements [a,i,W,w,e,M]
 jD0             (1,1)  Initial Julian date
 dT              (1,1)  Time between samples (sec)
 nPts            (1,1)  How many samples
 database        (1,:)  Spacecraft properties database
Outputs
 None
References ComStar(), Constant(), Delay(), El2RV(), HSAData(), HSAPlot(), Mag(), SSA(), SunV1(), and zeros().
Referenced by TransferOrbit().
HSMA()
function HSMA (in mA, in id)
 Since version 1.
Form
 mAHS = HSMA( mA, id )
Inputs
 mA           (3,n) Moment arms
 id           (1,n) Thruster ids
Outputs
 mAHS         (3,2) Half System moment arms
References length(), and Sep().
I2B()
function I2B (in q, in uI)
Transforms the sun vector defined in the ECI xz-plane into the spacecraft whose nominal frame is with the +z axis pointing at the earth, +y along orbit anti-normal and +x completing the right-hand set (LVLH). The spacecraft rotates about the +z axis with alpha.
Form
 uB = I2B( q, uI )
Inputs
 q           (4,1)   Quaternion from the inertial to the body frame
 uI          (3,1)   Sun vector in the I frame
Outputs
 uB          (3,1)   Sun vector in the B frame
References and(), QForm(), and vector().
ICSN()
function ICSN (in xNoSun, in orbitRate, in beta, in alpha, in alphaLimit)
Given an inertial frame defined with the sun in the +ZY plane, compute the initial spacecraft quaternion and solar array angle given the sun beta angle and alpha, the angle between the spacecraft and the sun projection in the ZX plane.
Form
 [q, sAAngle, w] = ICSN( xNoSun, orbitRate, beta, alpha, alphaLimit )
Inputs
 xNoSun        (1,1) Either +1 for +x or -1 for -x
 orbitRate     (1,1) Orbit rate
 beta          (1,1) Angle from orbit plane to the sun (rad)
 alpha         (1,1) Angle from the sun line in the orbit plane
 alphaLimit    (1,1) Range of alpha during which the rate limit is to be enforced
Outputs
 q             (4,1) Quaternion
 saAngle       (1,1) Solar array angle
 w             (3,1) Body rate
See also
SunNadir.
References and(), Mat2Q(), quaternion(), and SunNadir().
InjDataT()
function InjDataT (in elements, in rA, in dec, in w, in hW)
 Since version 1.
Form
 x = InjDataT( elements, rA, dec, w, hW )
Inputs
 elements     (1,6)       Keplerian elements
 rA           (1,1)       Right ascension (deg)
 dec          (1,1)       Declination (deg)
 w            (3,1)       Spin vector (rad/sec)
 hW           (1,1)       Wheel momentum
Outputs
 x            (1,7)       Formatted data
References vector().
IntData()
function IntData (in elements, in rA, in dec, in w, in hW, in fuelMass)
Form
 x = IntData( elements, rA, dec, w, hW, fuelMass )
Inputs
 elements     (1,6)    Keplerian elements
 rA           (1,1)    Right ascension (deg)
 dec          (1,1)    Declination (deg)
 w            (3,1)    Spin vector (rad/sec)
 hW           (1,1)    Wheel momentum
 fuelMass     (1,n)    Fuel mass (per tank) (lbf)
Outputs
 x            (1,8+n)  Formatted data
References length(), TransferOrbit(), and vector().
OddEven()
function OddEven (in thrusterIDs)
 Since version 1.
Form
 [nOdd, nEven] = OddEven( thrusterIDs )
Inputs
 thrusterIDs  (n)   Array of the thruster ID numbers
Outputs
 nOdd         (1,1) Number of odd thrusters
 nEven        (1,1) Number of even thrusters
References and(), and length().
OrbitDeltaV()
function OrbitDeltaV (in el, in dV, in mu)
Form
 el = OrbitDeltaV( el, dV, mu )
Inputs
 el              (1,6)  Keplerian Elements [a,i,W,w,e,M] (angles in rad)
 dV              (3,1)  Vector delta-V
 mu              (1,1)  Gravitational constant
Outputs
 el              (1,6)  Keplerian Elements [a,i,W,w,e,M] (angles in rad)
References El2RV(), length(), RV2El(), and vector().
Referenced by TransferOrbit().
PitchEst()
function PitchEst (in x, in p, in dT, in iZ, in q, in r, in u, in z, in zValid)
 Since version 1.
Form
 [x, p] = PitchEst( x, p, dT, iZ, q, r, u, z, zValid )
Inputs
 x               (2,1)  State [angle;rate]
 p               (2,2)  Covariance matrix
 dT              (1,1)  Time step
 iZ              (1,1)  Pitch axis inertia
 q               (2,2)  Plant covariance (continuous time)
 r               (1,1)  Input covariance
 u               (1,1)  Deterministic input
 z               (1,1)  Measurement
 zValid          (1,1)  Threshold for valid measurements
Outputs
 x               (2,1)  State
 p               (2,2)  Covariance matrix
References abs().
PitchLoop()
function PitchLoop (in inrPitch, in inrWheel, in beta, in zetaM, in zetaP)
If no output arguments are entered, or torqueStep is entered, the function will plot the step response of the system.
The pitch controller input is pitch and the output is wheel speed demand. The tach controller has two inputs: [wheel speed;wheel speed demand + nominal wheel speed] Its output is torque. The wheel speed demand must include the nominal wheel speed!
Each controller has one state.
Form
 [aM, bM, cM, dM, aP, bP, cP, dP, clEv] = PitchLoop( inrPitch, inrWheel, beta, zetaM, zetaP,
 wM, wP, dT, dTransform, torqueStep )
Inputs
 inrWheel         (1,1) Wheel inertia
 inrPitch         (1,1) Pitch inertia
 beta             (1,1) Wheel rate damping constant
 zetaM            (1,1) Tach loop damping ratio
 zetaP            (1,1) Pitch loop damping ratio
 wM               (1,1) Tach loop undamped natural frequency
 wP               (1,1) Pitch loop undamped natural frequency
 dT               (1,1) Sampling period
 dTransform       (1,1) 'Delta', or 'Z' default is 'Z'
 torqueStep       (2,1) External disturbance and friction torque
Outputs
 aM               (1,1) Tach loop plant matrix
 bM               (1,2) Tach loop input matrix
 cM               (1,1) Tach loop measurement matrix
 dM               (1,2) Tach loop feedthrough matrix
 aP               (1,1) Pitch loop plant matrix
 bP               (1,1) Pitch loop input matrix
 cP               (1,1) Pitch loop measurement matrix
 dP               (1,1) Pitch loop feedthrough matrix
 cLEv             (5,1) Closed loop eigenvalues
References and(), C2DelZOH(), C2DZOH(), eig(), isempty(), NewFig(), TitleS(), XLabelS(), YLabelS(), and zeros().
Pressure()
function Pressure (in mFuel, in database, in temp)
 Since version 1.
Form
 [p,pSystem] = Pressure(mFuel,database,temp)
 [p,pSystem] = Pressure(mFuel,database)
Inputs
 mFuel          (1,n)   Propellant mass per system
 database       (1,:)   Spacecraft properties database
 temp           (1,n)   System temperature
Outputs
 p              (1,m)   Thruster pressure
 pSystem        (1,n)   System pressure
References and(), BloDown(), Constant(), length(), MolWt2R(), and REA().
Referenced by AerodynamicShock(), AerodynamicShockMinimize(), AirData(), AtmDensMars2(), AtmScaleHeightsStdAtm(), BloDown(), BloDownMass(), Brayton(), BraytonIdeal(), BraytonWithRecuperator(), CD0Composite(), ColdGas(), ConstantDynamicPressureVelocity(), CPHypersonic(), CubeSatPropulsion(), CycleDesign(), DefaultTankData(), DynamicPressureAndHeat(), FAIR(), FBudget(), FOrbHF2(), GasMass(), GPressure(), HeatTransferChannel(), HeatTransferCoeffTaylor(), HoopStress(), HydrazineThruster(), IdealRkt(), LaunchSummary(), MachFromPR(), MachFromPressureRatio(), MassPressureVessel(), PDrag(), PressureDropChannel(), PressureRatioFromMach(), PressureRatioFromTemp(), PressureTotal(), RamjetExternalHeatSource(), RankineCycle(), RayleighPitotTube(), REA(), RocketFromUEAndT(), RocketModel(), SimpAtm(), SizeTurbineAndCompressor(), SolidR(), StagnationPAndT(), StaticPumping(), SteamTablesSuperheatedEnthalpy(), StructuralMass(), TCoeff(), TElec(), TempRatioFromPressure(), ThermalConductivityAndViscHeXe(), TotalPressureAndTemperature(), TransferOrbit(), Turbofan(), TurbojetNoThrust(), VolumeToPressureBD(), and XenonTank().
REA()
function REA (in id, in p, in dT, in database)
 The units in this model will depend on the units in the database.
 p must correspond to the database units.
 Since version 1.
Form
 [thrust, dF, impulse, iSP] = REA( id, p, dT, database )
Inputs
 id              (:)    Thruster ids
 p               (:)    Pressure
 dT              (:)    Pulsewidth (sec)
 database        (1,:)  Database name
Outputs
 thrust          (:)    Thrust
 dF              (:)    Fuel consumed
 impulse         (:)    Total impulse per thruster
 iSp             (:)    Specific impulse
References and(), Database(), length(), Pressure(), SumC(), vector(), and zeros().
Referenced by FuelUpdt(), Plume(), Pressure(), REAModel(), SpinChange(), SPMMnvr(), and ThrustModel().
RHSSNP()
function RHSSNP (in x, in ignoredArg, in inr, in invInr, in tExt, in inrW, in uW, in tW, in eSAC)
Form
 xDot = RHSSNP( x, t, inr, invInr, tExt, inrW, uW, tW, eSAC )
Inputs
 x            (15,1)    The state vector
 t                      Time
 inr          (3,3)     Inertia
 invInr       (3,3)     Inverse inertia
 tExt         (3,1)     External torque
 inrW         (6)       [SA,RWA] inertias
 uW           (3,6)     [SA,RWA] unit vectors
 tW           (6)       [SA,RWA] torque
 eSAC         (2)       Solar array commanded angle (always one step)
Outputs
 xDot         (15,1)    The derivative of the state vector
See also
GSModel, SunNadirPointingSim
References RHS(), and RWA().
Referenced by RHSSNP().
RollEst()
function RollEst (in inr, in hW, in wo, in q, in r, in dT, in sType)
 Since version 1.
Form
 [L, a] = RollEst( inr, hW, wo, q, r, dT, sType )
Inputs
 inr             (3,3)  Inertia
 hW              (1,1)  Internal momentum
 wo              (1,1)  Spin rate
 q               (2,2)  State noise
 r               (1,1)  Measurement noise
 dT              (1,1)  Time step
 sType           (1,:)  Type of transform
Outputs
 L               (2,1)  Gain matrix
 a               (2,2)  State transition matrix
References C2DelZOH(), C2DZOH(), eig(), FResp(), isempty(), QCE(), and zeros().
SA2Core()
function SA2Core (in a, in u)
Transforms a vector from the sun sensor frame to the core frame when the sun sensor is attached to a solar array that is rotated an angle a with respect to the core. When a = 0 the +z array axis is aligned with the +z core axis.
Form
 v = SA2Core( a, u )
Inputs
 a            (1,1)     Angle (rad)
 u            (3,1)     Vector in the array frame
Outputs
 v            (3,1)     Vector in the core frame
References vector().
SAForm()
function SAForm (in e)
Form
 c = SAForm( e )
Inputs
 e      (3,1) [ex;ey;ez] defined positive from the unrotated to the rotated
              frame
Outputs
 c      (3,3) Transforms from the nominal frame to the rotated frame
References SkewSymm().
Shadow()
function Shadow (in sunAlpha, in sunBeta, in s)
The s vector is the shadow regions. The first two are for alpha, the second for beta. Each surface can have two alpha limits and one beta limit.
Form
 k = Shadow( sunAlpha, sunBeta, s )
Inputs
 sunAlpha    (1,1)   Alpha angle of sun (orbit plane from +x)
 sunBeta     (1,1)   Beta angle of sun (out of plane)
 s           (6,n)   Limits for each surface [alpha1Min alpha1Max alpha2Min
                     alpha2Max betaMin betaMax]
Outputs
 k                   Set of surfaces in shadow
References and(), and vector().
SKDataF()
function SKDataF (in dV, in cM, in tDist, in aCSThrusters, in dVThrusters, in plumeDrag)
 Since version 1.
Form
 x = SKDataF( dV, cM, tDist, aCSThrusters, dVThrusters, plumeDrag )
Inputs
 dV                  (1,1) Delta-V
 cM                  (3,1) Center of mass
 tDist               (1,1) Disturbance (fraction of dV force)
 aCSThrusters        (1,n) ACS thrusters
 dVThrusters         (1,m) dV thrusters
 plumeDrag           (1,1) Plume drag factor 0.00 to 1.00
Outputs
 x                (1,11+n+m) sFormatted data
References length(), and Plume().
SpinChange()
function SpinChange (in p, in axis, in w, in wF, in wait, in inertia, in cM, in tId, in eventName, in database)
Form
 [w, fuelUsed] = SpinChange( p, axis, w, wF, wait, inertia, cM, tId, eventName, database )
Inputs
 p               (1,n)  Thruster pressure (psi)
 axis            (3,1)  Spin change axis
 w               (3,1)  Initial body rate (rad/sec)
 wF              (3,1)  Final body rate (rad/sec)
 wait            (n-1)  Delays between burns (sec)
 inertia         (3,3)  Inertia matrix
 cM              (3,1)  Center-of-mass
 tID             (1,n)  Thruster id's
 eventName       (1,:)  Event name
 database        (1,:)  Database name
Outputs
 w               (3,1)  Final body rate
 fuelUsed        (1,m)  Fuel consumed per tank
References abs(), Database(), FRB(), length(), MomArm(), Plot2D(), REA(), RK4(), and zeros().
Referenced by TransferOrbit().
SpinDataF()
function SpinDataF (in inr, in iAxis, in cM, in dW, in thrusters)
Form
 x = SpinDataF( inr, iAxis, cM, dW, thrusters )
Inputs
 inr           (1,1)    Spin axis inertia
 iAxis         (1,1)    Axis of spin change
 cM            (3,1)    Center of mass
 dW            (1,1)    Delta spin rate
 thrusters     (1,n)    Thruster IDs
Outputs
 x             (1,12+n) Spin change data
References length().
SpinDataT()
function SpinDataT (in axis, in wF, in tID, in dTDelay)
Form
 x = SpinDataT( axis, wF, tID, dTDelay )
Inputs
 axis         (3,1)  Axis for spin change
 wF           (1,1)  Final spin rate after each burn (up to 3) (rpm)
 tID          (1,n) Thrusters to be used
 dTDelay      (1,1) Delay between burns (1 less than the # of burns)
Outputs
 x            (1,7+n) Formatted data
References Delay().
SpinREst()
function SpinREst (in accel, in K, in x, in T, in pulsewidth)
 Since version 1.
Form
 x = SpinREst( accel, K, x, T, pulsewidth )
Inputs
 accel          (1,1)   Thruster angular acceleration per unit time
 K              (1,1)   Gain
 x              (1,1)   Rate estimate
 T              (1,1)   Measured period
 pulsewidth     (1,1)   Thruster pulsewidth (duration of the acceleration)
Outputs
 x              (1,1)   Rate estimate
References plus().
SPMDataF()
function SPMDataF (in inr, in cM, in w, in attI, in attF, in pwF, in jD, in thrusters)
 Since version 1.
Form
 x = SPMDataF( inr, cM, w, attI, attF, pwF, jD, thrusters )
Inputs
 inr           (1,1) Spin axis inertia
 cM            (3,1) Center of mass
 w             (3,1) Spin rate (rpm)
 attI          (1,2) Initial [ra,dec] (deg)
 attF          (1,2) Final [ra,dec] (deg)
 pwF           (1,1) Pulsewidth fraction
 jD            (1,1) Julian date
 thrusters     (1,n) Thruster IDs
Outputs
 x             (1,12+n)  Formatted data
References length(), RLP(), and SunV1().
SPMDataT()
function SPMDataT (in tID, in pulsewidth, in rAF, in decF)
 Since version 1.
Form
 x = SPMDataT( tID, pulsewidth, rAF, decF )
Inputs
 tID           (1,n) Ids of thruster to be used
 pulsewidth    (1,1) Pulsewidth
 rAF           (1,1) Final right ascension
 decF          (1,1) Final declination
Outputs
 x             (1,4+n) Formatted data
References length().
SPMMnvr()
function SPMMnvr (in p, in tId, in pulsewidth, in jD, in inertia, in cM, in w, in rAI, in decI, in rAF, in decF, in database)
Form
 [fuelUsed, qECIToBody] = SPMMnvr( p, tId, pulsewidth, jD, inertia, cM, w, rAI, decI, rAF, decF, database )
Inputs
 p               (1,:)  Thruster pressure (psia)
 tId             (1,:)  Thruster ids
 pulsewidth      (1,1)  Pulsewidth for all thrusters
 jD              (1,1)  Julian date
 inertia         (3,3)  Spacecraft inertia
 cM              (3,1)  Spacecraft center-of-mass
 w               (3,1)  Initial body rate
 rAI             (1,1)  Initial right ascension (rad)
 decI            (1,1)  Initial declination (rad)
 rAF             (1,1)  Final right ascension (rad)
 decF            (1,1)  Final declination (rad)
 database        (1,:)  Database to use
 Database
 'SSA Boresight Vector'
 'REA Rise Time'
 'REA Fall Time'
 'Spin Axis'
 'SSA FOV'
 'SSA Boresight Vector'
 'SSA Aperture Vector'
 'r thruster'
 'u thruster'
 'REA Model'
Outputs
 fuelUsed     (1,n)   Fuel used per thruster
 qECIToBody   (4,:)   The ECI to body quaternion
References abs(), and(), Constant(), Cross(), Database(), FRB(), Initialize(), length(), MomArm(), NPSPM(), Plot2D(), QForm(), QTForm(), quaternion(), RaDec2Q(), REA(), RK4(), SSA(), SunV1(), ThrustModel(), U2RADec(), Unit(), vector(), and zeros().
Referenced by TransferOrbit().
SSAD()
function SSAD (in mSS, in eyeCoeff, in uSun, in roll)
 The sun sensors may be attached to the spacecraft solar array.
See also
SSEye.
 Since version 1.
Form
 [yaw, sAPitch] = SSAD( mSS, eyeCoeff, uSun, roll )
Inputs
 mSS          (n)       Magnitude of each sun sensor output
 eyeCoeff     (m)       Eye coefficients where mSS = a[1]*x^0 + a[2]*x^1 +...
                        where x = cos(theta)
 uSun         (3,1)     Sun vector in the body frame
 roll         (1,1)     Measured roll angle
Outputs
 yaw           (1,1)    Yaw Measurement
 sAPitch       (1,1)    Solar array pitch measurement
References isempty(), set(), SSEye(), and vector().
SSOutput()
function SSOutput (in e, in nE, in u, in uSun, in a, in n)
 Since version 1.
Form
 m = SSOutput( e, nE, u, uSun, a, n )
Inputs
 e            (2,1)     Solar array angles
 nE           (4,1)     Index for the sun sensors that tells which array
                        they are on (1 or 2)
 u            (3,4)     Sun sensor eye vectors
 uSun         (3,1)     The sun vector in the body frame
 a            (:,1)     Eye coefficients
 n            (1,1)     Number of counts above zero (e.g. for an 8 bit output
                        enter 256)
Outputs
 m            (1,4)     Eye output in counts
References Core2SA(), length(), vector(), and zeros().
SunRA()
function SunRA (in i, in uSun, in beta)
Computes the orbit right ascension angle given the sun unit vector (or right ascension and declination), the sun beta angle and the inclination of the orbit.
Type SunRA for a demo.
Form
 rA = SunRA( i, uSun, beta )
Inputs
 i            (1,1)  Inclination (rad)
 uSun         (3,1)  Sun Vector or [rASun (rad);decSun (rad)];
 beta         (1,n)  Beta angles (rad)
Outputs
 rA           (1,n)  Right ascension of the ascending node (rad)
References and(), isempty(), length(), Plot2D(), SunRA(), and U2RADec().
Referenced by SunRA().
ThrstLevel()
function ThrstLevel (in time, in pulsewidth, in fallConst, in)
Form
 [thrustLevel, turnedOff] = ThrustLevel( time, pulsewidth, fallConst,...
 thrustLevelOld, aFall, aRise, bRise )
Inputs
 time           (1,1) Time since pulse started
 pulsewidth     (n)   Pulsewidth
 fallConst      (n)   Thruster fall time constant
 thrustLevelOld (n)   Previous thrust level
 aFall          (n)   exp(-timeStep/fallConst)
 aRise          (n)   exp(-timeStep/riseConst)
 bRise          (n)   1 - aRise
Outputs
 thrustLevel    (n)   Thrust level, between 0 and 1
 turnedOff      (x)   Indices of any thrusters which were turned
                      off during this call. 0 <= x <=n
References and(), length(), set(), vector(), and zeros().
ThrustModel()
function ThrustModel ()
database is only used if no output arguments are entered.
Form
 [torque, timeSinceCEP, nPulses, firingInfo] = ThrustModel( dT, thrusterInfo,
 firingInfo, spinRate, nPulses, CEP, timeSinceCEP, database )
Inputs
 dT                  Time step
 thrusterInfo (10,n) [tID; riseConst; fallConst; pulsewidth;
                      peakTorque; aFall; aRise; bRise]
 firingInfo    (5,n) [delayFraction; thrusterDelay; thrusterFiring;
                      thrusterTimeOn; thrustLevel]
 spinRate            Spin rate (rad/sec)
 nPulses             Number of pulses to go
 CEP                 True (1) if the sun has just passed through the
                      sensor boresight, false (0) otherwise
 timeSinceCEP        Time since the last CEP
 The following are elements in one of the Info arrays and/or inputs
 to the second form:
 tID            (n)  Thruster IDs
 riseConst      (n)  Rise time constant
 fallConst      (n)  Fall time constant
 pulsewidth     (n)  Pulsewidth
 aFall          (n)  exp(-dT./fallConst)
 aRise          (n)  exp(-dT./riseConst)
 bRise          (n)  1 - aRise
 peakTorque   (3,n)  Peak torque for each thruster
 delayFraction  (n)  Fraction of a spin period between CEP (sun passing)
 and each thruster firing
 delay          (n)  Delay from CEP in seconds
 thrusterFiring (n)  Each element is true (1) if that thruster is
 firing, false (0) if not
 thrusterTimeOn (n)  Time since each thruster started firing
 thrustLevel    (n)  Current fraction of peak torque being output
Outputs
 torque         (3) Total thruster torque
 timeSinceCEP (1,1) Time since the last CEP
 nPulses      (1,1) (Updated) number of pulses to go
 firingInfo   (5,n) [delayFraction; delay; thrusterFiring;
                     ThrusterTimeOn; thrustLevel]
References and(), Delay(), Initialize(), isempty(), length(), Plot2D(), REA(), set(), and zeros().
Referenced by SPMMnvr().
TransferOrbit()
function TransferOrbit (in event, in mET, in a, in eventName, in dateStart, in database, in units)
Form
 TransferOrbit( event, mET, a, eventName, dateStart, database )
Inputs
 event           (:,:) Event to be simulated
 mET             (1,1) Mission elapsed time [h,m,s]
 a               (1,:) Event data
 eventName       (1,:) Name of event
 dateStart       (1,6) [year month day hour minute second]
 database        (1,:) Database name
 inertiaName     (1,:) Name of the starting inertia
 units           (2,3) ['mks'|'lbf'|'sft';'deg'|'rad';'rpm'|'rps']
References abs(), and(), Constant(), Database(), Date2JD(), DST(), FuelUpdt(), GetHSA(), Initialize(), isempty(), length(), OrbitDeltaV(), Period(), PltOrbit(), Pressure(), RaDec2U(), SpinChange(), and SPMMnvr().
Referenced by IntData().