PSS MATLAB Toolboxes: MHT Functions
MHT Functions
MHT Module
The MHT module functions API.
Directories
directory ACControl
Control systems.
directory ACGraphics
Aircraft graphics.
directory Demos
Aircraft demos.
directory DynamicalModels
A variety of dynamical models used in the demonstrations.
directory LinkUtilities
Helpful utilities .
directory SensorModels
Sensor models needed for the UKF demos.
directory TrackInitialization
Function to create tracks from management for each application.
directory TrackManagement
The core functions implementing hypothesis formating and track pruning. The functions in this folder are parsed.
directory TrackScoring
Track scoring functions.
Description
Files
file glpk.m
If there is no input output the version and syntax.
Functions
function AddScan (in data, in sensorType, in sensorID, in param, in scan)
Add a scan to the scan data structure array.
function AutomobileLaneChange (in passer, in dX, in y, in v, in gain)
Implements lane change control by pointing the wheels at the target.
function AutomobilePassing (in passer, in passee, in dY, in dV, in dX, in gain)
Implements passing control by pointing the wheels at the target.
function AutoRadar (in x, in d)
Automotive (2D) radar.
function AutoRadarUKF (in x, in d)
Automotive (2D) radar model for use with UKF.
function BilliardCollision (in x, in d)
Billiard collision model.
function CheckForDuplicateTracksMS (in trk, in allTrees)
Check for duplicate tracks.
function DoubleIntegratorWithAccel (in dT)
Plant model for a double integrator with an acceleration state.
function LLRToProb (in lLR)
Convert log likelihood ratios to probablities.
function MahalanobisDistance (in x, in mu, in s)
Compute the Mahalanobis Distance.
function MHTDistance (in s)
Finds the MHT distance for use in gating computations.
function MHTDistanceUKF (in d)
Finds the MHT distance for use in gating computations using UKF.
function MHTGUI (in varargin)
A graphical user interface (GUI) for multiple hypothesis testing (MHT)
function MHTHypothesisDisplay (in hyp, in trk, in k, in t)
Display hypothesis data in a console view.
function MHTInitialize (in varargin)
Initializes the MHT parameter data structure from parameter pairs.
function MHTInitializeTrk (in f)
Initialize the trk data structure.
function MHTInitialTrackScore (in betaNT, in vC, in pD, in pFA, in pH1, in pH0)
Initialize the track likelihood ratio.
function MHTLLR (in lLR, in alpha, in beta, in s, in d, in isDet)
Update the log likelihood ratio.
function MHTLLRUpdate (in lRK, in lRS, in lLR)
Update the log likelihood ratio.
function MHTMatrixSortRows (in b)
Sort the matrix rows in ascending order.
function MHTMatrixTreeConvert (in b)
Convert from MHT track matrix to tree or tree to matrix.
function MHTTrackMerging (in b)
Merges tracks.
function MHTTrackMgmt (in b, in trk, in zScan, in d, in scan, in t)
Track management algorithms including track reduction and pruning.
function MHTTrackScore (in y, in varargin)
Track score given a scan of data.
function MHTTrackScoreKinematic (in y, in h, in r, in p, in pD)
Kinematic track score.
function MHTTrackScoreSignal (in pD, in pFA, in pH1, in pH0)
Signal track score.
function MHTTrackTable (in h, in trk, in k, in pos)
Generate a uitable object with measurement indices.
function MHTTreeDiagram (in tracks, in w, in update)
Generates a tree diagram for MHT tracks.
function MHTTrkToB (in trk)
Converts a "trk" data structure to a "b" matrix.
function PlotTracks (in trk)
Plot the track states vs.
function ProbToLLR (in p)
Convert probabilities to log likelihood ratios.
function Residual (in y, in f)
Generates residual, measurement matrix and measurement noise matrix.
function RHSAutomobile (in x, in ignoredArg, in d)
Right hand side for a 2D automobile.
function RHSAutomobileXY (in x, in ignoredArg, in ignoredArg)
Double integrator model for a car.
function RHSBilliards (in x, in t, in d)
Billiard ball model.
function ScanToTrack1D (in xMeas, in d, in scan0, in treeID, in tag)
Initializes a new track.
function ScanToTrackAuto (in xMeas, in d, in scan0, in treeID, in tag)
Initializes a new track for an automobile from radar measurements.
function ScanToTrackBilliards (in scan, in d, in scan0, in treeID, in tag)
Initializes a new track.
function SpectralRadius (in m)
Compute the spectral radius of a matrix.
function SpectralRadiusJumpMarkov (in a, in p)
Compute the spectral radius of a discrete jump Markov system.
function TOMHTAssignment (in trk, in M, in glpkParams)
Track oriented MHT assignment.
function TOMHTPruneTracks (in tracks, in soln, in scan0, in opts)
Track-oriented MHT - track pruning algorithm.
function TOMHTTree (in b0, in m)
Generates the Track Oriented MHT matrix and tree.
function TOMHTTreeAnimation (in action, in tracks)
Animates a TOMHT tree.
Function Documentation
AddScan()
function AddScan (in data, in sensorType, in sensorID, in param, in scan)
Form
 scan = AddScan( data, sensorType, sensorID, param, scan )
Inputs
 data         (.)    Data
 sensorType (1,1)   Integer for the data type
 sensorID    (1,1)   Integer for sensor ID
 param        (.)    Parameter data structure
                     .hFun   (1,:) Pointer to measurement function
                     .hData   (.)  Data structure for the measurement
                                   function
 scan         (:)    Scan data structure
Outputs
 scan         (:)    Data structure array with new scan appended
                     .data       (.)   Data
                     .sensorType (1,1) Integer for data type
                     .sensorID   (1,1) Integer for sensor ID
                     .param      (1,1) Parameter data structure
References Append(), isempty(), and Parameter().
AutomobileLaneChange()
function AutomobileLaneChange (in passer, in dX, in y, in v, in gain)
 Generates a steering angle demand and torque demand.
Form
 passer = AutomobileLaneChange;
 passer = AutomobileLaneChange( passer, dY, v, gain )
Inputs
 passer (1,1)  Car data structure
                 .mass      (1,1) Mass (kg)
                 .delta     (1,1) Steering angle (rad)
                 .r         (2,4) Position of wheels (m)
                 .cD        (1,1) Drag coefficient
                 .cF        (1,1) Friction coefficient
                 .torque       (1,1) Motor torque (Nm)
                 .area      (1,1) Frontal area for drag (m^2)
                 .x         (6,1) [x;y;vX;vZ;theta;omega]
                 .errOld    (1,1) Old position error
                 .passState (1,1) State of passing maneuver
 dX      (1,1)  Lead in x
 dY      (1,1)  Relative position in y
 dV      (1,1)  Relative velocity in x
 gain    (1,3)  Gains [position velocity position derivative]
Outputs
 passer (1,1)  Car data structure with updated fields:
                 .delta
                 .errOld
                 .torque
References and(), AutomobileLaneChange(), Friction(), and RHSAutomobile().
Referenced by AutomobileLaneChange().
AutomobilePassing()
function AutomobilePassing (in passer, in passee, in dY, in dV, in dX, in gain)
 Generates a steering angle demand and torque demand.
 Prior to passing the passState is 0. During the passing it is 1.
 When it returns to its original lane the state is set to 0.
Form
 passer = AutomobilePassing
 passer = AutomobilePassing( passer, passee, dY, dV, dX, gain )
Inputs
 passer (1,1)  Car data structure
                 .mass      (1,1) Mass (kg)
                 .delta     (1,1) Steering angle (rad)
                 .r         (2,4) Position of wheels (m)
                 .cD        (1,1) Drag coefficient
                 .cF        (1,1) Friction coefficient
                 .torque       (1,1) Motor torque (Nm)
                 .area      (1,1) Frontal area for drag (m^2)
                 .x         (6,1) [x;y;vX;vZ;theta;omega]
                 .errOld    (1,1) Old position error
                 .passState (1,1) State of passing maneuver
 passee  (1,1)  Car data structure
 dY      (1,1)  Relative position in y
 dV      (1,1)  Relative velocity in x
 dX      (1,1)  Relative position in x
 gain    (1,3)  Gains [position velocity position derivative]
Outputs
 passer (1,1)  Car data structure with updated fields:
                 .passState
                 .delta
                 .errOld
                 .torque
References and(), AutomobilePassing(), Friction(), RHSAutomobile(), and set().
Referenced by AutomobilePassing().
AutoRadar()
function AutoRadar (in x, in d)
 Returns azimuth, range and range rate. The state vector may be
 any order. You pass the indices for the position and velocity states.
 The angle of the car is passed in d even though it may be in the state
 vector. The target must be within the field of view. If it is not the
 data is zero and the valid flag is 0. The radar also has a maximum
 range.
 This does not model the signal to noise ratio of a radar.
 The power received of a radar goes as 1/r^4. In this model the signal
 goes to zero a the maximum range.
 The valid flag is set to zero if the target is not in the field of
 view or out of range.
 x can be organized in any way you would like. For example:
 x    = [x1;y1;vX1;vY1;x3;y3;vX3;vY3];
 d.kR = [1 5;2 6];
 d.kV = [3 7;4 8];
 Type AutoRadar for a demo. The tracked car is oscillating about
 the y position.
Form
 [y, v] = AutoRadar( x, d )
Inputs
 x  (:,n)   State may be any order.
 d (1,1)   Filter data structure
             .kR         (2,:) Position index
             .kV         (2,:) Velocity index
             .kT         (1,:) Torque index
             .theta      (1,:) Angle of car +x car respect to +x
                               inertial
             .noise      (3,1) 1 sigma noise (m; m/s; rad)
             .fOV        (1,1) Angle from +x for detection (rad)
             .maxRange   (1,1) Maximum range (m)
             .t          (1,n) Time vector
             .noLimits   (1,1) Set to 1 if range and fov limits are to
                               be ignored.
Outputs
 y  (3*m,1) Measurements [range;range rate; azimuth] (m, m/s, rad)
 v   (m,1)   1 if the measurement is valid, 0 if it not valid
References and(), AutoRadar(), Demo(), Mag(), Measurements(), Plot2D(), set(), TimeLabl(), Unit(), vector(), and zeros().
Referenced by AutoRadar().
AutoRadarUKF()
function AutoRadarUKF (in x, in d)
 Returns azimuth, range and range rate.
Form
 y = AutoRadarUKF( x, d )
Inputs
 x  (4,1)   State
 d  (.)    Filter data structure
             .theta  (1,:) Angle of car +x with respect to +x inertial
Outputs
 y  (3,1)   Measurements [range;range rate; azimuth] (m, m/s, rad)
References abs(), and(), Mag(), Measurements(), and UKF().
BilliardCollision()
function BilliardCollision (in x, in d)
Models wall collisions.
Form
 x = BilliardCollision( x, d )
Inputs
 x   (4*nBalls,1)   State [x;vX;y;vY]
 t    (1,1)          Unused.
 d    (1,1)          Data structure
                     .nBalls (1,1) Number of balls
                     .xLim   (1,2) [xMin xMax]
                     .yLim   (1,2) [yMin yMax]
Outputs
 x   (4*nBalls,1)   State [x;y;vX;vY]
CheckForDuplicateTracksMS()
function CheckForDuplicateTracksMS (in trk, in allTrees)
 Compares treeID, measHist, scanHist, sensorHist.
 Cycles through all tracks. Compares j'th track with k'th track (k>j).
 If the two tracks have identical (treeID, measHist, scanHist, sensorHist),
 they are marked as a duplicate pair.
 If the two tracks have identical (measHist, scanHist, sensorHist) and
 input "allTrees" is true, they are marked as a duplicate pair.
Form
 dup = CheckForDuplicateTracks( trk, allTrees )
Inputs
 trk       (:)     Track data structure array. Must include fields:
                     .treeID       Integer track-tree ID
                     .measHist     Integer array of measurement numbers
                     .scanHist     Integer array of scan numbers
                     .sensorHist   Integer array of sensor IDs
 allTrees  (1,1)   If 1, then look for duplicates across all trees.
 If 0, then look for duplicates within each tree.
 Default is 0.
Outputs
 dup       (N,2)   Matrix of duplicate tracks. N rows of index pairs.
                   For example, dup = [3 5;4 7] means that trk(3) and
                   trk(5) are duplicates, and that trk(4) and trk(7) are
                   duplicates.
References and(), isempty(), length(), and zeros().
DoubleIntegratorWithAccel()
function DoubleIntegratorWithAccel (in dT)
State vector is [x;v;a]. Input vector is [0;0;da/dt]
Form
 [a, b] = DoubleIntegratorWithAccel( dT )
Inputs
 dT       (1,1)  Time step
Outputs
 a        (3,3)  State transition matrix
 b        (3,1)  Input matrix
References Demo(), DoubleIntegratorWithAccel(), and vector().
Referenced by DoubleIntegratorWithAccel().
LLRToProb()
function LLRToProb (in lLR)
Type LLRToProb for a demo.
Form
 p = LLRToProb( lLR )
Inputs
 lLR       (1,:) Log likelihood ratio
Outputs
 p         (1,:) Probability
Reference: Blackman, S. and R. Popoli, "Design and Analysis of Modern Tracking Systems," Artech House, 1999.
References and(), Demo(), LLRToProb(), and Plot2D().
Referenced by LLRToProb(), and ProbToLLR().
MahalanobisDistance()
function MahalanobisDistance (in x, in mu, in s)
 In statistics, Mahalanobis distance is a distance measure based on
 correlations between variables.
 This appears in the exponential term of the multivariate Gaussian.
 Type MahalanobisDistance for a demo.
Form
 d = MahalanobisDistance( x, mu, s )
Inputs
 x           (:,1)   State
 mu          (:,1)   Mean
 s           (:,:)   Covariance matrix
Outputs
 d           (1,1)   Mahalanobis Distance
Reference: http://en.wikipedia.org/wiki/Mahalanobis_distance
References Demo(), MahalanobisDistance(), and vector().
Referenced by MahalanobisDistance().
MHTDistance()
function MHTDistance (in s)
 The measurement function is of the form h(x,d) where d is a data
 structure.
 The most time consuming operation is this operation
 (z-h*x)'*b \ (z-h*x)
 where b = h*p*h' + r
 The matrix inversion of b is of the order of the measurement vector.
 As the uncertainty gets smaller, the residual must be smaller to remain
 within the gate.
 Type MHTDistance for a demo of a rectilinear motion problem. The
 vehicle is under constant acceleration. The measurement is distance
 from the origin. A linear Kalman filter is used which is implemented
 with KFPredict and KFUpdate.
 See MHTDistanceUKF for an alternative approach.
Form
 [y, del] = MHTDistance( s )
Inputs
 s        (1,1)  Data structure for the filter
Outputs
 y        (1,1)  MHT distance
 del      (1,1)  MHT Residual
References and(), Demo(), KFPredict(), KFUpdate(), MHTDistance(), MHTDistanceUKF(), Residual(), and vector().
Referenced by MHTDistance(), and MHTDistanceUKF().
MHTDistanceUKF()
function MHTDistanceUKF (in d)
 The measurement function is of the form h(x,d) where d is the UKF
 data structure. MHTDistanceUKF uses sigma points. The code is similar
 to UKFUpdate. Unlike MHTDistance this does not use the Jacobian of the
 measurement function.
 As the uncertainty gets smaller, the residual must be smaller to
 remain within the gate.
 See MHTDistance for an alternative approach.
Form
 [k, del] = MHTDistanceUKF( d )
Inputs
 d         (.)   UKF data structure
Outputs
 k        (1,1)  MHT distance
 del      (1,1)  MHT Residual
References DupVect(), Jacobian(), length(), MHTDistance(), MHTDistanceUKF(), Residual(), UKF(), UKFUpdate(), and zeros().
Referenced by MHTDistance(), and MHTDistanceUKF().
MHTGUI()
function MHTGUI (in varargin)
 Forms:
 MHTGUI            Initialize blank MHTGUI if it does not yet exist;
 bring existing MHTGUI window to the front.
 MHTGUI(trk)       Update the GUI with given track data.
 MHTGUI(trk,hyp)   Update the GUI with given track and hypothesis data.
 MHTGUI(trk,hyp,'hide')    Update the GUI with given data but do not
 bring it to the front.
Inputs
 trk       (.)   Track data structure array. See MHTTrackMgmt.m
 hyp       (.)   Hypothesis data structure.  See TOMHTAssignment.m
 option    ''    Optional argument to specify window visibility. Use
                 this with "hide" to prevent flashing window during
                 repeated updates of the MHTGUI in a simulation loop.
Outputs
 None
References and(), Initialize(), MHTGUI(), MHTTrackMgmt(), and TOMHTAssignment().
Referenced by MHTGUI().
MHTHypothesisDisplay()
function MHTHypothesisDisplay (in hyp, in trk, in k, in t)
Form
 MHTHypothesisDisplay( hyp, trk, k, t )
Inputs
 hyp         (.)     Hypothesis data structure
 trk         (:)     Tracks array
 k           (1,1)   Scan
 t           (1,1)   Time
References isempty(), length(), MLog(), Tree(), and zeros().
MHTInitialize()
function MHTInitialize (in varargin)
 You must enter the desired Kalman filter type (KF, EKF, or UKF) and
 associated filter data using the following parameters:
 'filter type'  (1,:) One of {'kf','ekf','ukf'}
 'filter data'   (.)  Filter data structure, see KFInitialize
 The filter data is appended to fScanToTrackData field automatically;
 only additional fields should be passed in via input using the
 parameter 'scan to track data'.
 Use the 'create track' parameter, with any value, to also create the
 first track from the filter data. nTrk will be set to 1.
 Type MHTInitialize for a demo data structure using KF. The fields are
 documented below.
Form
 [mhtData, trk] = MHTInitialize( varargin )
Inputs
 varargin       {:}  Parameter pairs
Outputs
 mhtData        (1,1) Data structure of track management parameters
 trk            (1,1) First track data structure
 Field              Size   Parameter name
 .pFA              (1,1)  'probability false alarm'
 .pH1              (1,1)  'probability of signal if target present'
 .pH0              (1,1)  'probability of signal if target absent'
 .pD               (1,1)  'probability of detection'
 .vC               (1,1)  'measurement volume'
 .nScan            (1,1)  'number of scans'
 .gate             (1,1)  'gate'
 .mBest            (1,1)  'm best'
 .nTrk             (1,1)  'number of tracks'
 .fScanToTrack     (1,:)  'scan to track function' i.e. @ScanToTrack1D
 .fScanToTrackData  (.)   'scan to track data'
 .fDistance        (1,:)  'distance function', i.e. @MHTDistance
 .hypScanLast      (1,1)  'hypothesis scan last'
 .pruneTracks      (1,1)  'prune tracks'
 .removeDuplicateTracksAcrossAllTrees
 (1,1)  'remove duplicate tracks across all trees'
 .avgScoreHistoryWeight
 (1,1)  'average score history weight'
 Set by the function from the filter type and data parameters:
 .predict (1,:) Kalman filter predict function, i.e. @KFPredict
 .update  (1,:) Kalman filter update function, i.e. @KFUpdate
See also
: MHTInitializeTrk
References and(), and UKF().
MHTInitializeTrk()
function MHTInitializeTrk (in f)
 This should be called by all custom scan-to-track functions to ensure
 a uniform data structure for tracks.
Form
 trk = MHTInitializeTrk( f )
Inputs
 f    (.) Filter data structure, see KFInitialize
Outputs
 trk    (.) Data structure
            .filter           Kalman filter data structure
            .mP         (x,1) Mean state prediction
            .pP         (x,x) Covariance prediction
            .m          (x,1) Mean state
            .p          (x,x) Covariance
            .meas       (1,:) Measurement indices
            .sensor     (1,:) Sensor indices
            .score      (1,1) Score
            .scoreTotal (1,1) Total score
            .treeID     (1,1) Tree ID of track
            .scanHist   (1,n) Scan index history
            .measHist   (1,n) Measurement index history
            .sensorHist (1,n) Sensor index history
            .mHist      (j,:) Full measurement history
            .tHist      (j,:) Time history
            .d          (1,m) MHT distance
            .new
            .gate       (1,m) Gate booleans
            .tag        (1,1) Unique track tag
            .scan0      (1,1) Scan number at which this track is created
References Initialize(), KFInitialize(), and Tree().
Referenced by ScanToTrack1D(), ScanToTrackAuto(), and ScanToTrackBilliards().
MHTInitialTrackScore()
function MHTInitialTrackScore (in betaNT, in vC, in pD, in pFA, in pH1, in pH0)
 Type MHTInitialTrackScore for a demo showing the effect of pD.
Form
 llR = MHTInitialTrackScore( betaNT, vC, pD, pFA, pH1, pH0 )
Inputs
 betaNT  (1,1) New target density
 vC      (1,1) Control volume
 pD      (1,1) Probability of detection
 pFA     (1,1) Probability of false alarm
 pH1     (1,1) Probability of a signal if a target is present
 pH0     (1,1) Probability of a signal if a target is absent
Outputs
 lR      (1,1) Initial Likelihood ratio
Reference: Blackman, S. and R. Popoli, "Design and Analysis of Modern Tracking Systems," Artech House, 1999, p. 331.
References and(), Demo(), Initialize(), MHTInitialTrackScore(), MHTTrackScoreSignal(), and Plot2D().
Referenced by MHTInitialTrackScore().
MHTLLR()
function MHTLLR (in lLR, in alpha, in beta, in s, in d, in isDet)
 Type MHTLLR for a demo of having a sequence of no detections.
Form
 LLR = MHTLLR( lLR, alpha, beta, s, d, isDet )
Inputs
 lLR           (1,1) Log likelihood ratio
 alpha         (1,1) Probability of false alarm
 beta          (1,1) Probability of missed detection
 s             (:,:) Covariance matrix for states
 d             (:,1) Residual vector
 isDet         (1,1) 1 if the target is detected
Outputs
 lLR           (1,1) Log likelihood ratio
Reference: Richardson, H. R., "Multiple Multistage Hypothesis Tests: A Sequential Detection Approach to Target Tracking," Ph.D Thesis Queen's University, Ontario, Canada, June 1992, p. 45.
References Demo(), length(), MHTLLR(), Plot2D(), Residual(), vector(), and zeros().
Referenced by MHTLLR().
MHTLLRUpdate()
function MHTLLRUpdate (in lRK, in lRS, in lLR)
Inputs
Form
 lLR = MHTLLRUpdate( lRK, lRS, lLR )
Inputs
 lRK       (1,:) Kinematic likelihood ratios
 lRS       (1,:) Signal likelihood ratios
 lLR       (1,1) Log likelihood ratio
Outputs
 lLR       (1,1) Log Likelihood ratio
Reference: Blackman, S. and R. Popoli, "Design and Analysis of Modern Tracking Systems," Artech House, 1999, p. 328-330.
References and().
MHTMatrixSortRows()
function MHTMatrixSortRows (in b)
Move the first non-zero entry
 of the matrix to be in the first column.
Form
 [b2,ks] = MHTMatrixSortRows( b )
Inputs
 b       (:,:)  Matrix representation of tracks
Outputs
 b2      (:,:)   Matrix with rows sorted
 ks      (1,:)   Sort array
References length().
MHTMatrixTreeConvert()
function MHTMatrixTreeConvert (in b)
 Type MHTMatrixTreeConvert for a demo. Draws a tree if no outputs are
 requested.
Form
 n = MHTMatrixTreeConvert( b )
Inputs
 n        {:}    Nodes
                 .parent        (1,1) Parent
                 .name       (1,1) Number of observation
                 .scan       (1,1) Scan number
 b        (:,:)  Matrix representation
Outputs
 n or b
References MHTMatrixTreeConvert().
Referenced by MHTMatrixTreeConvert(), MHTTrkToB(), and TOMHTTree().
MHTTrackMerging()
function MHTTrackMerging (in b)
 Rules: - One measurement is associated with each track
 - If two tracks only differ by missed measurements they are
 merged
 Type MHTTrackMerging for a demo.
Form
 b = MHTTrackMerging( b, n )
Inputs
 b        (m,n)  [scans, tracks]
Outputs
 kD       (1,:)  Tracks to delete
Reference: A. Amditis1, G. Thomaidis1, P. Maroudis, P. Lytrivis1 and G. Karaseitanidis1, "Multiple Hypothesis Tracking Implementation," www.intechopen.com.
References and(), Demo(), length(), and MHTTrackMerging().
Referenced by MHTTrackMerging().
MHTTrackMgmt()
function MHTTrackMgmt (in b, in trk, in zScan, in d, in scan, in t)
 It creates new tracks each scan. A new track is created
 Tracks are pruned to eliminate those of low probability and find the
 hypothesis which includes consistent tracks. Consistent tracks do
 not share any measurements.
 This is typically used in a loop in which each step has new
 measurements, known as "scans".
 The simulation can go in this loop to generate y or you can run the
 simulation separately and store the measurements in y. This can be
 helpful when you are debugging your MHT code.
 For real time systems y would be read in from your sensors.
 zScan = [];
 for k = 1:n
 zScan = AddScan( y(:,k), [], [], [], zScan ) ;
 [b, trk, sol, hyp, trkData] = MHTTrackMgmt( b, trk, zScan, trkData, k, t );
 MHTGUI(trk,sol);
 for j = 1:length(trk)
 trkData.fScanToTrackData.v =  myData
 end
 if( ~isempty(zScan) && makePlots )
 TOMHTTreeAnimation( 'update', trk );
 end
 t = t + dT;
end
 The reference provides good background reading but the code in this
 function is not based on the reference. Other good references are
 books and papers by Blackman.
Form
 [b, trk, sol, hyp, d] = MHTTrackMgmt( b, trk, zScan, d, scan, t )
Inputs
 b        (m,n)  [scans, tracks]
 trk      (:)    Track data structure
 zScan    (1,:)  Scan data structure
 d        (1,1)  Track management parameters
 scan     (1,1)  The current scan ID
 t        (1,1)  Time
Outputs
 b        (m,1)  [scans, tracks]
 trk      (:)    Track data structure array
 sol      (.)    Solution data structure from TOMHTAssignment
 hyp      (.)    Best hypothesis
 d        (.)    Parameters with updated scan index
Reference: A. Amditis1, G. Thomaidis1, P. Maroudis, P. Lytrivis1 and G. Karaseitanidis1, "Multiple Hypothesis Tracking Implementation," www.intechopen.com.
See also
: MHTTrackScore, TOMHTAssignment, TOMHTPruneTracks
References and(), isempty(), length(), MHTTrackScore(), MLog(), TOMHTAssignment(), TOMHTPruneTracks(), and zeros().
Referenced by MHTGUI(), and PlotTracks().
MHTTrackScore()
function MHTTrackScore (in y, in varargin)
 This is the product of kinematic and signal track scores.
 Assumes a Gaussian distribution for false returns. If you only enter
 the first 5 arguments for  you will just get the kinematic track score.
 Type MHTTrackScore for a demo with just the kinematic track score.
Form
 [lR, lRK, lRS] =  MHTTrackScore( y, filter, pD, pFA, pH1, pH0 )
Inputs
 y       (m,1) Measurement vector (scan)
 filter  (.)  Filter data structure
 pD      (1,1) Probability of detection
 pFA     (1,1) Probability of false alarm
 pH1     (1,1) Probability of a signal if a target is present
 pH0     (1,1) Probability of a signal if a target is absent
Outputs
 lR      (1,1) Likelihood ratio
 lRK     (1,1) Kinematic likelihood ratio
 lRS     (1,1) Signal likelihood ratio
Reference: Blackman, S. and R. Popoli, "Design and Analysis of Modern Tracking Systems," Artech House, 1999.
References and(), Demo(), get(), MHTTrackScore(), Plot2D(), Residual(), vector(), and zeros().
Referenced by MHTTrackMgmt(), and MHTTrackScore().
MHTTrackScoreKinematic()
function MHTTrackScoreKinematic (in y, in h, in r, in p, in pD)
 This is the likelihood ratio for the kinematics
 Assumes a Gaussian distribution for false returns.
 Type MHTTrackScoreKinematic for a demo with a decreasing covariance
 matrix for a 1D problem and a fixed residual error.
Form
 lR = MHTTrackScoreKinematic( y, h, r, p, v )
Inputs
 y         (m,1) Measurement residual vector
 h         (m,n) Measurement matrix
 r         (m,m) Measurement covariance matrix
 p         (n,n) Covariance matrix
 pD        (1,1) Probability of detection on 1 scan
Outputs
 lR        (1,1) Likelihood ratio
Reference: Blackman, S. and R. Popoli, "Design and Analysis of Modern Tracking Systems," Artech House, 1999.
References and(), Demo(), isempty(), length(), MHTTrackScoreKinematic(), Plot2D(), vector(), and zeros().
Referenced by MHTTrackScoreKinematic().
MHTTrackScoreSignal()
function MHTTrackScoreSignal (in pD, in pFA, in pH1, in pH0)
 All inputs can be vectors but the must have the same dimension.
 Type MHTTrackScoreSignal for a demo showing the effect of pD.
Form
 llR = MHTTrackScoreSignal( pD, pFA, pH1, pH0 )
Inputs
 pD      (1,1) Probability of detection
 pFA     (1,1) Probability of false alarm
 pH1     (1,1) Probability of a signal if a target is present
 pH0     (1,1) Probability of a signal if a target is absent
Outputs
 lR      (1,1) Likelihood ratio
Reference: Blackman, S. and R. Popoli, "Design and Analysis of Modern Tracking Systems," Artech House, 1999, p. 330.
References and(), Demo(), MHTTrackScoreSignal(), and Plot2D().
Referenced by MHTInitialTrackScore(), and MHTTrackScoreSignal().
MHTTrackTable()
function MHTTrackTable (in h, in trk, in k, in pos)
 Rows are labeled as <treeID>.<tag>
 Columns are labeled with scan ID.
 Contents of table cells are measurement IDs for each scan.
 Type MHTTrackTable for a demo. Creates 2 table windows.
Form
 t = MHTTrackTable( h,  trk, k, pos )  New table "t" in figure "h"
 t = MHTTrackTable( [], trk, k, pos )  New table "t" in new figure
 MHTTrackTable( t,  trk, k )       Update table "t" with "k" tracks
 MHTTrackTable( t,  trk )          Update table "t" with all tracks
Inputs
 h         (1,1)   Figure handle or table handle
 trk       (:)     Track data structure
 k         (1,:)   Integer array. Set of tracks to include in table.
 pos       (1,4)   Normalized position of table in figure.
Outputs
 t         (1,1)   Graphics handle for uitable object.
References Demo(), get(), isempty(), length(), MHTTrackTable(), MHTTrkToB(), and NewFig().
Referenced by MHTTrackTable().
MHTTreeDiagram()
function MHTTreeDiagram (in tracks, in w, in update)
 w is optional, the defaults are:
 .name      = 'Tree';
 .width     = 400;
 .fontName  = 'Times';
 .fontSize  = 10;
 .linewidth = 1;
 .linecolor = 'r';
 .rootSizeRatio = 1.5;
 Type MHTTreeDiagram for a demo using a matrix input.
Form
 MHTTreeDiagram( n, w, update )
Inputs
 tracks    (.)   Data structure array of track information, OR:
           {:}   Cell array of tree node data, OR:
          (:,:)  Matrix of track data with track IDs in first column
 w        (1,1)  Diagram data structure
 .name      (1,:) Tree name
 .width     (1,1) Circle width
 .fontName  (1,:) Font name
 .fontSize  (1,1) Font size
 .linewidth (1,1) Line width
 .linecolor (1,1) Line color, char or numeric
 .rootSizeRatio (1,1)
 update   (1,1)  If entered update an existing plot
Outputs
 None
References MHTTreeDiagram().
Referenced by MHTTreeDiagram(), and MHTTrkToB().
MHTTrkToB()
function MHTTrkToB (in trk)
 The bMeas or "b" matrix represents a stacked set of track-trees.
 Each row is a different path through a track-tree
 Each column is a different scan/sensor combination.
 Each value in the matrix is a measurement index for that scan.
 The first column of the "b" matrix has the object ID for each track.
 Several tracks may have the same object ID. In this case, they
 represent alternative sets of measurements that may be attributed to
 the object.
 Each of the remaining columns represents a different scan and sensor.
 If there are multiple sensors, the matrix is organized by sensor.
 The first set of columns are for the first sensor, the second set for
 the second sensor, and so on. An example is provided below for clarity.
 In this example, we have two scans, two sensors, and object IDs 5,6,7.
 Each object has two different tracks.
 ObjID   Sens1/Scan1   Sens1/Scan2   Sens2/Scan1   Sens2/Scan2
 5          1             1             2             1
 5          2             0             1             0
 6          1             3             3             1
 6          1             0             1             2
 7          1             3             1             1
 7          1             0             2             3
 The scans for sensor 1 are listed in the first two columns. The scans
 for the next sensor are listed in the next two columns. Note that each
 sensor could have a different number of scans.
 The numbers 0,1,2,3 appear in the matrix. Each of these numbers is a
 measurement index. Measurements taken during each scan are indexed
 starting at 1. A value of 0 means the track has no measurement from
 that sensor for that scan.
 Type MHTTrkToB for a demo. Will draw the tree if there are no outputs.
Form
 [bMeas,bSens,bScan] = MHTTrkToB( trk )
Inputs
 trk       (:)    Track data structure array
Outputs
 bMeas    (:,:)   Measurement ID Matrix
 bSens    (:,:)   Sensor ID Matrix
 bScan    (:,:)   Scan ID Matrix
References and(), Demo(), isempty(), length(), Measurements(), MHTMatrixTreeConvert(), MHTTreeDiagram(), MHTTrkToB(), set(), TreeDiagram(), and zeros().
Referenced by MHTTrackTable(), MHTTrkToB(), and TOMHTAssignment().
PlotTracks()
function PlotTracks (in trk)
time. Creates one figure with subplots.
Plots trk.mHist vs. trk.tHist, where mHist is the history of the mean states returned from the Kalman filter. This data is stored with the tracks by MHTTrackMgmt.
Form
 PlotTracks( trk )
Inputs
 trk   (:)   Track data structure array
Outputs
 None.
References get(), length(), MHTTrackMgmt(), NewFig(), and TitleS().
ProbToLLR()
function ProbToLLR (in p)
 Type ProbToLLR for a demo.
Form
 lLR = ProbToLLR( p )
Inputs
 p         (1,:) Probability
Outputs
 lLR       (1,:) Log likelihood ratio
Reference: Blackman, S. and R. Popoli, "Design and Analysis of Modern Tracking Systems," Artech House, 1999.
References and(), Demo(), LLRToProb(), Plot2D(), and ProbToLLR().
Referenced by ProbToLLR().
Residual()
function Residual (in y, in f)
Handles linear and nonlinear systems. The latter use the Jacobian of the measurement function. The former uses the h matrix. For nonlinear systems .h is the pointer to the measurement function.
This handles empty y matrices.
Form
 [z, h, r] = Residual( y, f )
Inputs
 y  (m) Measurement data structure
         .data  (:,1) Measurements
         .param (1,1) Parameter data structure
                     .hFun   (1,:) Pointer to measurement function
                     .hData  (1,1) Data structure for measurement function data
                     .r      (:,:) Measurement covariance matrix
 f   (1,1) Filter data structure
           .m     (n,1) State vector
           .r     (m,1) Residual
           .h     (m,n) Output matrix
Outputs
 z  (m,1) Residual
 h  (m,n) Linearized measurement matrix y = h*x or
 r  (m,m) Noise covariance matrix
References and(), isempty(), Jacobian(), length(), Measurements(), Parameter(), Residual(), vector(), and zeros().
Referenced by CubeSatDisturbanceAnalysis(), DCMotorParitySpace(), EKFUpdate(), FX(), FXNM(), FXNMTE(), IEKFUpdate(), KFUpdate(), LSSVD(), MHTDistance(), MHTDistanceUKF(), MHTLLR(), MHTTrackScore(), QuadCost(), Residual(), RHSCubeSat(), and TRD().
RHSAutomobile()
function RHSAutomobile (in x, in ignoredArg, in d)
Form
 xDot = RHSAutomobile( x, t, d )
Inputs
 x  (6*n,1) State, [x;y;vX;vY;theta;omega]
 t         Time, unused
 d  (1,1)   Data structure
             .car   (n,1)  Car data structure
                            .mass  (1,1) Mass (kg)
                            .delta (1,1) Steering angle (rad)
                            .r     (2,4) Position of wheels (m)
                            .cDF   (1,1) Frontal drag coefficient
                            .cDS   (1,1) Side drag coefficient
                            .cF    (1,1) Friction coefficient
                            .fT    (1,1) Traction force (N)
                            .areaF (1,1) Frontal area for drag (m^2)
                            .areaS (1,1) Side area for drag (m^2)
                            .fRR   (1,2) [f0 K]
Outputs
 x  (6*n,1)  d[x;y;vX;vY;theta;omega]/dt
References DefaultDataStructure(), Friction(), length(), and zeros().
Referenced by AutomobileLaneChange(), and AutomobilePassing().
RHSAutomobileXY()
function RHSAutomobileXY (in x, in ignoredArg, in ignoredArg)
Form
 xDot = RHSAutomobileXY( x, t, d )
Inputs
 x  (4,1)   State [x;y;vX;vY]
 t         Time, unused
 d         Data, unused
Outputs
 x  (4,1)   State derivative d[x;y;vX;vY]/dt
RHSBilliards()
function RHSBilliards (in x, in t, in d)
2D double integrators. t is not used.
Form
 xDot = RHSBilliards( x, t, d )
Inputs
 x   (4*nBalls,1)       State [x;y;vX;vY]
 t    (1,1)          Unused.
 d    (1,1)          Data structure
                      .nBalls (1,1) Number of balls
Outputs
 xDot (4*nBalls,1)    State d[x;y;vX;vY]/dt
References zeros().
ScanToTrack1D()
function ScanToTrack1D (in xMeas, in d, in scan0, in treeID, in tag)
 d includes a field with a velocity estimate. The measurement
 directly initializes the position state.
Form
 trk = ScanToTrack1D( xMeas, d, scan0, treeID, tag )
Inputs
 xMeas     (1,1)   Scan which is a position measurement
 d         (1,1)   Data structure
                     .v (1,1) Velocity
                     .a (3,3) State transition matrix
                     .b (3,1) Input matrix
                     .h (1,3) Measurement matrix
                     .p (3,3) State covariance matrix
                     .q (3,3) Model covariance matrix
                     .r (1,1) Measurement covariance matrix
 scan0     (1,1)   Scan number at which this track is created
 treeID    (1,1)   Track-tree ID. The track is inside this tree.
 tag       (1,1)   Unique tag to distinguish from all other tracks
Outputs
 trk      (1,1) Track data structure
References MHTInitializeTrk().
ScanToTrackAuto()
function ScanToTrackAuto (in xMeas, in d, in scan0, in treeID, in tag)
 The new state estimate is [x;y;vX;vY]. It is derived from the
 radar measurement by directly computing x and y and assuming that
 the range rate is entirely along x. x is the direction along the
 highway.
Form
 trk = ScanToTrackAuto( xMeas, d, scan0, treeID, tag )
Inputs
 xMeas    (1,1)   Position measurement data
 d       (1,1)   Data structure
                  .x      (6,1) State of tracking car
                  .filter   (1,1) Filter data structure
 scan0    (1,1)   Scan number at which this track is created
 treeID (1,1)   Track-tree ID. The track is inside this tree.
 tag     (1,1)   Unique tag to distinguish from all other tracks
Outputs
 trk     (1,1)   Track data structure
See also
MHTInitializeTrk.
References and(), MHTInitializeTrk(), and zeros().
ScanToTrackBilliards()
function ScanToTrackBilliards (in scan, in d, in scan0, in treeID, in tag)
 The measurement directly initializes the position state.
Form
 trk = ScanToTrackBilliards( scan, d, scan0, treeID, tag )
Inputs
 scan     (1,1)    Scan which is a position measurement
                     .data
                     .sensorID
 d        (1,1)    Data structure
                   .filter
                     .v (1,1) Velocity
                     .a (3,3) State transition matrix
                     .b (3,1) Input matrix
                     .h (1,3) Measurement matrix
                     .p (3,3) State covariance matrix
                     .q (3,3) Model covariance matrix
                     .r (1,1) Measurement covariance matrix
 scan0     (1,1)   Scan number at which this track is created
 treeID    (1,1)   Track-tree ID. The track is inside this tree.
 tag       (1,1)   Unique tag to distinguish from all other tracks
Outputs
 trk      (1,1) Track data structure
References MHTInitializeTrk().
SpectralRadius()
function SpectralRadius (in m)
 Type SpectralRadius for a demo for the matrix [0 1;-0.5 -0.1],
 a damped oscillator.
Form
 rho = SpectralRadius( m )
Inputs
 m              {:,:}    Matrix
Outputs
 rho            (1,1)    Spectral radius
References SpectralRadius().
Referenced by SpectralRadius().
SpectralRadiusJumpMarkov()
function SpectralRadiusJumpMarkov (in a, in p)
p must be symmetric and the same size as the number of matrices in a.
Type SpectralRadiusJumpMarkov for two examples from A. Vargas.
a = {[0 2;0 0.5], [0.5 0;2 0]}; p = [0.5 0.5;0.5 0.5];
a = {[2 1;0 0], [0 1;0 2]}; p = [0.1 0.9;0.9 0.1];
Form
 rho = SpectralRadiusJumpMarkov( a, p )
Inputs
 a    {:}    Cell array of state matrices nxn
 p    (n,n) Transition probability matrix
Outputs
 rho  (1,1)  Vector in b
Reference: V.Gupta, R. M. Murray, L. Shi, B. Sinopili, "Networked Sensing, Estimation and Control Systems," January 2010. A. N. Vargas, "A brief overview of Markov jump linear systems," Seminar at BCAM.
References and(), Markov(), and SpectralRadiusJumpMarkov().
Referenced by SpectralRadiusJumpMarkov().
TOMHTAssignment()
function TOMHTAssignment (in trk, in M, in glpkParams)
Generates hypotheses.
 This function calls the glpk function installed by GLPKMEX. If glpk is
 not installed an error will be thrown.
 The "b" matrix represents a stacked set of track-trees:
 each row is a different path through a track-tree;
 each column is a different scan;
 values in matrix are index of measurement for that scan.
 A valid hypothesis is a combination of rows of b (a combination of
 track-tree paths), such that the same measurement is not repeated.
 Solution vector "x" is 0|1 array that selects a set of track-tree-paths.
 Objective is to find the hypothesis that maximizes total score.
Form
 d = TOMHTAssignment( trk, M, glpkParams );
Inputs
 trk         (.)       Data structure array of track information
                       From this data we will obtain:
 b           (nT,nS)   Matrix of measurement IDs across scans
 trackScores (1,nT)    Array of total track scores
 treeIDs     (1,nT)    Array of track ID numbers. A common ID across
                           multiple tracks means they are in the same
                           track-tree.
 M           (1,1)     Number of hypotheses to generate.
 glpkParams  (.)       Data structure with glpk parameters.
Outputs
 d           (.)   Data structure with fields:
                   .nT     Number of tracks
                   .nS     Number of scans
                   .M      Number of hypotheses
                   .pairs  Pairs of hypotheses for score constraints
                   .nPairs Number of pairs
                   .A      Constraint matrix for optimization
                   .b      Constraint vector for optimization
                   .c      Cost vector for optimization
                   .lb     lower bounds on solution vector
                   .ub     upper bounds on solution vector
                   .conType  Constraint type array
                   .varType  Variable type array
                   .x        Solution vector for optimization
                   .hypothesis(:)  Array of hypothesis data, see below
 d.hypothesis(:)   Data structure array with fields:
 .treeID       Vector of track-tree IDs in hypothesis
 .trackIndex   Vector of track indices in hypothesis.
 Maps to rows of "b" matrix.
 .tracks       Set of tracks in hypothesis. These are
 the selected rows of "b" matrix.
 .trackScores  Vector of scores for selected tracks.
 .score        Total score for hypothesis.
Reference: Blackman, S. and R. Popoli, "Design and Analysis of Modern Tracking Systems," Artech House, 1999.
References and(), glpk(), Initialize(), isempty(), MHTTrkToB(), Normal(), set(), vector(), and zeros().
Referenced by MHTGUI(), MHTTrackMgmt(), and TOMHTPruneTracks().
TOMHTPruneTracks()
function TOMHTPruneTracks (in tracks, in soln, in scan0, in opts)
 Keep the following tracks
 * Tracks with the "N" highest scores
 * Tracks in the "M best" hypotheses
 * Tracks that have:
 1. track ID, and
 2. the first "P" measurements
 found in "M best" hypotheses
Form
 [tracksP,keep,prune,d] = TOMHTPruneTracks( tracks, soln, scan0, opts )
Inputs
 tracks    (.)     Data structure array of tracks
 soln      (.)     Solution from TOMHTAssignment
 scan0     (1,1)   Starting scan index. This is the depth in the
                   track-tree at which point # scans to match is added.
 opts      (.)     Options
                       .nHighScoresToKeep
                       .nFirstMeasMatch
Outputs
 tracksP   (.)     Data structure array of tracks after pruning.
 keep      (1,:)   Index list of original tracks we kept
 prune     (1,:)   Index list of original tracks we pruned
 d         (.)     Data structure to record how "keep" indices were
                   found:
                     .bestTrackScores
                     .bestHypFullTracks
                     .bestHypPartialTracks
References and(), and TOMHTAssignment().
Referenced by MHTTrackMgmt().
TOMHTTree()
function TOMHTTree (in b0, in m)
 Type TOMHTTree for a demo.
Form
 b = TOMHTTree( b0, m )
Inputs
 b0        (:,:)   Initial matrix
 m         (:)     Measurement data structure array
                   .t (1,:) Track IDs associated with the measurement
                   .s (1,1) Scan for this measurement
Outputs
 b         (:,:)   Matrix [tracks,measurements]
Reference: A. Amditis1, G. Thomaidis1, P. Maroudis, P. Lytrivis1 and G. Karaseitanidis1, "Multiple Hypothesis Tracking Implementation," www.intechopen.com.
References and(), Demo(), length(), MHTMatrixTreeConvert(), TOMHTTree(), TreeDiagram(), and zeros().
Referenced by TOMHTTree().
TOMHTTreeAnimation()
function TOMHTTreeAnimation (in action, in tracks)
 Type TOMHTTreeAnimation for a demo.
Form
 TOMHTTreeAnimation( action, tracks )
 TOMHTTreeAnimation( action, tree   )
 TOMHTTreeAnimation( action, b      )
Inputs
 action            'initialize' or 'update'
 tracks    (.)     Track data structure array, OR:
 tree      {.}     Tree data structure cell array, OR:
 b         (:,:)   Track tree matrix with IDs in first column
Outputs
 None
See also
MHTTreeDiagram.
References TOMHTTreeAnimation().
Referenced by TOMHTTreeAnimation().