PSS MATLAB Toolboxes: Airships Functions
Airships Functions
Airships Module
The Airships module functions.
Directories
directory AirshipGUI
Airship Design GUI .
directory Analysis
Analysis of airships, including, trim, dynamics, and wind .
directory Control
Airship control functions .
directory Mass
Airship mass models and properties .
directory Modeling
Airship modeling including inertia, lift and drag. .
directory Models
Example models.
directory Simulation
Airship simulations tools including a GUI .
Description
Functions
function AddedMass (in type, in rho, in d)
Generate the added mass for various geometric shapes.
function Airship3DLayout (in name, in h, in surfaceType, in n)
Plot a 3D layout of an airship model, including hull, fins, and gondola.
function Airship_KLat (in action, in data)
The lateral-directional control laws for an airship.
function Airship_KLon (in action, in data)
The longitudinal control laws for an airship.
function AirshipAero (in alpha, in beta, in x, in d, in qBar, in control, in flex, in rho)
Aerodynamic forces and moments for an airship.
function AirshipAeroAnalysis (in model)
Plot the airship aero coefficients across angle of attack and sideslip.
function AirshipAutopilot (in action, in data)
Autopilot for an airship.
function AirshipBallonets (in name, in h, in bvf)
Plot a 3D airship hull, fins, gondola, and show internal ballonets.
function AirshipCoefficients ()
Load the approximate aerodynamic coefficients for an airship.
function AirshipControlSim (in latLon, in h0, in v0, in psi0, in theta0, in trajDes)
Controlled airship simulation with autopilot and feedback control.
function AirshipCV (in a1, in a2)
Compute the x-location of the center of volume of an airship hull.
function AirshipDesignGUI (in action, in modifier, in data)
High-level airship design tool.
function AirshipDrag (in h, in u, in A, in Cd)
Compute the approximate drag on an airship.
function AirshipDynamics (in linModFile)
Examine the open-loop root locus across altitude, velocity, pitch.
function AirshipGeometry (in L, in D, in ratio)
Compute the main geometric properties of an airship hull.
function AirshipInertiaFactors (in a1, in a2, in b)
Compute the added mass/inertia factors for an airship hull.
function AirshipInit (in d, in latLonAlt, in vAB, in eul, in trim, in wind)
Initialize an aircraft data structure and state for airship simulation.
function AirshipIntegrals (in a1, in a2, in b, in hullFraction, in xo)
Compute the geometric integrals for a double-ellipsoid airship hull.
function AirshipLinMod (in d, in h, in theta, in alpha, in V, in useAlpha)
Compute a linearized model of an airship at a given flight condition.
function AirshipMassModel (in varargin)
Initialize and update the airship mass model as it changes with alt.
function AirshipMaxCruise (in Cd0, in Vol23, in Pmax, in h)
Evaluate the maximum velocity and thrust for the airship.
function AirshipMDot (in h, in hDot)
Estimate the precent rate of change of mass per minute across altitude.
function AirshipPropeller (in ignoredArg, in d, in control, in ignoredArg, in ignoredArg)
Airship propeller model.
function AirshipSensor (in x, in d, in opt)
Sensor model for airship.
function AirshipSim (in d, in x, in T, in dT, in ignoredArg)
Simulate an airship in flight.
function AirshipSimGUI (in action, in ignoredArg, in ignoredArg)
GUI for setting up airship simulations.
function AirshipStabConDerivatives (in mdl, in h, in theta, in alpha, in V)
Compute the stability and control derivatives for an airship model.
function AirshipState (in d, in latLonAlt, in vAB, in eul)
Compute the airship state vector as an acstate object from a model.
function AirshipStatespace (in g, in useAlpha)
Extract the long.
function AirshipTrim (in d, in h, in theta, in alpha, in V)
Compute the trim controls for an airship at a given flight condition.
function AirshipTrimAnalysis (in data)
Compute the trim controls for an airship at a range of flight conditions.
function BalanceAirshipPayload (in name)
Determine the x-location of the payload that provides long.
function BuildAirshipMassModel (in name, in h, in xon, in bvf)
Generate a distributed mass model for an axisymmetric airship.
function BuildAirshipModel (in name, in xoN)
Build the aerodynamic model of an airship.
function CDAirship (in alpha, in delta)
The drag coefficient of airship as a function of angle of attack.
function CLAirship (in alpha)
The lift coefficient of an airship envelope.
function CMAirship (in dK, in v, in alpha)
The moment coefficient of an airship envelope.
function DrawAirship (in L, in D, in ratio, in n, in orientation)
Create a 3-D image of an airship hull.
function FinFactors (in J1, in Sf, in Sfh, in vol)
Compute the hull and fin efficiency factors for an airship.
function FinGeometry (in a1, in a2, in b, in xFinA, in xFinB, in xFinC, in yzFinI, in yzFinO)
Compute the fin reference area, hull projection, mean chord and width.
function GenerateAirshipAeroMats (in name, in xo, in h, in theta, in alpha, in V)
Compute the aerodynamic force and torque for an airship.
function GenerateAirshipLinMods (in d, in h, in V, in theta)
Generate linear models of an airship at a range of flight conditions.
function GetAirshipLinMod (in name, in h, in V, in theta)
Obtain the linear model of an airship at a particular flight condition.
function GondolaGeometry (in a1, in a2, in b, in xGonA, in xGonB, in zGon)
Compute the surface area and center of mass of an airship gondola.
function HalfEllipsoid (in a, in b)
Compute volume, surf area, centroid and specific MOI of half-ellipsoid.
function IntegrateMassProps (in comp)
Integrate the mass properties of multiple components into a single body.
function LatLon (in city)
Find the latitude and longitude of a major U.S.
function SolarCellCoverage (in h, in u, in S, in Cd, in P0, in Emax, in fSun, in etaProp, in etaCell)
Evaluates the required solar cell coverage for a particular airship.
function StructuralMass (in VMax, in kSV, in rhoF, in alt, in mP)
Determine the mass available for airship structure and systems.
function WindLatLon (in XLAT, in XLONG, in ALT, in IDAY, in XLST)
Compute horizontal wind variance with latitude and longitude.
function WindLatLonAlt (in XLAT, in XLONG, in ALT, in IDAY, in XLST)
Compute horizontal wind variance with latitude, longitude, and altitude.
Function Documentation
AddedMass()
function AddedMass (in type, in rho, in d)
At this point
 only 'prolate spheroid' is included.
Form
 [mAdded, rOrigin, volume, m] = AddedMass( type, rho, d )
Inputs
 type        (1,:)  'prolate spheroid'
 rho         (1,1)   Density of surrounding fluid
 d           (1,1)   Data structure depends on body
                     .x    (1,1) x length
                     .y    (1,1) y length
Outputs
 mAdded      (6,6)  Added mass
 rOrigin     (3,1)  Origin
 volume      (1,1)  Volume
 m           (6,6)  Generalized mass
References AddedMass(), and(), length(), and zeros().
Referenced by AddedMass(), and BuildAirshipModel().
Airship3DLayout()
function Airship3DLayout (in name, in h, in surfaceType, in n)
Form
 Airship3DLayout( name, h, surfaceType, n );
Inputs
 name          (:)       Name of airship model file.
 h             (1)       Altitude (m)
 surfaceType   (:)       Surface type ('solid' or 'mesh') Default solid.
 n             (1)       Number of vertices to plot (default 25)
Outputs
 none
References AirshipCV(), AirshipGeometry(), Altitude(), and(), ASM4(), BuildAirshipMassModel(), Ellipsd(), and NewFig().
Airship_KLat()
function Airship_KLat (in action, in data)
The default controllers are stored in AirshipControllers.mat
Form
 d = Airship_KLat( action, data )
Inputs
 action        (:)   String name of action to take. Choices are:
                        * 'init'        ...  Supply statespace controllers and
                                                           initialize matrices
                        * 'update'      ...  Supply the error inputs and compute
                                                                    the controls
                        * 'reset'       ...  Reset controller states to zero
 data          (.)   Data structure required for action
                        if action == 'init'
                           - data.k_rr  ...  statespace controller,
                                                     r -to- rudder
                           - data.k_rv  ...  statespace controller,
                                                     v -to- rudder
                           - data.k_ap  ...  statespace controller,
                                                     p -to- aileron (diff flaps)
                           - data.rate  ...  update rate [Hz]
                        if action == 'update'
                           - data.p     ...  roll rate error         [rad/s]
                           - data.r     ...  yaw rate error          [rad/s]
                           - data.v     ...  lateral velocity error  [m/s]
Outputs
 d             (.)   Data structure of control outputs
                           - d.dRUD_sym ...  Symmetric rudder command      [rad]
                           - d.dAIL     ...  Aileron command (diff flaps)  [rad]
References and(), C2DZOH(), get(), getabcd(), statespace(), and zeros().
Airship_KLon()
function Airship_KLon (in action, in data)
The default controllers are stored in AirshipControllers.mat
Form
 d = Airship_KLon( action, data )
Inputs
 action        (:)   String name of action to take. Choices are:
                        * 'init'        ...  Supply statespace controllers and
                                                           initialize matrices
                        * 'update'      ...  Supply the error inputs and compute
                                                                    the controls
                        * 'reset'       ...  Reset controller states to zero
 data          (.)   Data structure required for action
                        if action == 'init'
                           - data.k_tu  ...  statespace controller,
                                                   u -to- throttle
                           - data.k_mu  ...  statespace controller,
                                                   u -to- mu (prop pitch angle)
                           - data.k_dw  ...  statespace controller,
                                                   w -to- elevator deflection
                           - data.k_dq  ...  statespace controller,
                                                   q -to- elevator deflection
                           - data.rate  ...  update rate [Hz]
                        if action == 'update'
                           - data.q     ...  pitch rate error       [rad/s]
                           - data.u     ...  axial velocity error   [m/s]
                           - data.w     ...  normal velocity error  [m/s]
Outputs
 d             (.)   Data structure of control outputs
                           - d.throttle ... Throttle command
                           - d.mu       ... Propeller pitch command      [rad]
                           - d.dELV_sym ... Symmetric elevator command   [rad]
References and(), C2DZOH(), get(), getabcd(), statespace(), Throttle(), and zeros().
AirshipAero()
function AirshipAero (in alpha, in beta, in x, in d, in qBar, in control, in flex, in rho)
All terms in body frame.
Form
 g = AirshipAero( alpha, beta, x, d, qBar, control, flex, rho )
Inputs
 alpha                 Angle of attack (rad)
 beta                  Sideslip (rad)
 x                     State
 d                     Aerodynamic data
 qBar                  Dynamic pressure
 control               Controls
 flex                  Flexible states (not implemented)
 rho                   Atmospheric density
Outputs
 g                   .torque  (3,1) Core torques
                     .force   (3,1) Core forces
                     .modal   (:,1) Modal forces
                     .inertia (3,3) Delta inertia due to aerodynamics
                     .mass    (3,3) Delta mass matrix due to aerodynamics
References and().
Referenced by AirshipTrim(), BuildAirshipModel(), and GenerateAirshipAeroMats().
AirshipAeroAnalysis()
function AirshipAeroAnalysis (in model)
Form
 AirshipAeroAnalysis
Inputs
 model       (1,:)      Name of airship design script
Outputs
 none
See also
BuildAirshipModel
References abs(), AirshipAeroAnalysis(), and(), ASM3(), BuildAirshipModel(), length(), NewFig(), and zeros().
Referenced by AirshipAeroAnalysis().
AirshipAutopilot()
function AirshipAutopilot (in action, in data)
 Given the desired trajectory and the current measured state, compute the
 body-frame velocity and angular rate commands for the controllers.
Form
 cmd = AirshipAutopilot( action, data )
Inputs
 action        (:)   String name of action to take. Choices are:
                        * 'reset'      ...  Reset the commands to current states
                        * 'set limits' ...  Supply rate limits
                        * 'set dt'     ...  Supply the time step
                        * 'update'     ...  Update the commands
 data          (.)   Data required for action
                        if action == 'reset'
                           (when no data provided, sets all to 0)
                           - data.u     ...  current axial velocity     [m/s]
                           - data.v     ...  current lateral velocity   [m/s]
                           - data.w     ...  current normal velocity    [m/s]
                           - data.p     ...  current roll rate          [rad/s]
                           - data.q     ...  current pitch rate         [rad/s]
                           - data.r     ...  current yaw rate           [rad/s]
                        if action == 'set limits'
                           - data.u     ...  rate limit, axial velocity    [m/s/s]
                           - data.v     ...  rate limit, lateral velocity  [m/s/s]
                           - data.w     ...  rate limit, normal velocity   [m/s/s]
                           - data.p     ...  rate limit, roll rate         [rad/s/s]
                           - data.q     ...  rate limit, pitch rate        [rad/s/s]
                           - data.r     ...  rate limit, yaw rate          [rad/s/s]
                        if action == 'set dt'
                           - data       ...  time-step [sec]
                        if action == 'update'
                           - trajDes    ...  desired trajectory data   (psi,theta,vel)
                           - trajMeas   ...  measured trajectory data  (psi,theta,vel)
                           - stateMeas  ...  measured state data       (p,q,r,u,v,w)
Outputs
 cmd           (.)   Data structure of commanded rates
                           - cmd.u     ...  Axial velocity command      [m/s]
                           - cmd.v     ...  Lateral velocity command    [m/s]
                           - cmd.w     ...  Normal velocity command     [m/s]
                           - cmd.p     ...  Roll rate command           [rad/s]
                           - cmd.q     ...  Pitch rate command          [rad/s]
                           - cmd.r     ...  Yaw rate command            [rad/s]
References abs(), and(), Limit(), Normal(), set(), and WrapPhase().
AirshipBallonets()
function AirshipBallonets (in name, in h, in bvf)
Form
 AirshipBallonets( name, h );
Inputs
 name          (:)       Name of airship model file.
 h             (1)       Altitude (meters)
Outputs
 none
References AirshipCV(), AirshipGeometry(), Altitude(), and(), ASM2(), BuildAirshipMassModel(), Ellipsd(), get(), length(), NewFig(), set(), and zeros().
AirshipCoefficients()
function AirshipCoefficients ()
 Includes drag coefficients for hull, fins and gondola, and lift
 coefficients for the fins.
Form
 d = AirshipCoefficients;
Inputs
 none
Outputs
 d           (.)       Data structure containing aerodynamic coefficients
References AirshipCoefficients(), and and().
Referenced by AirshipCoefficients(), and BuildAirshipModel().
AirshipControlSim()
function AirshipControlSim (in latLon, in h0, in v0, in psi0, in theta0, in trajDes)
Loads the saved file AirshipControllers.mat
Form
 p = AirshipControlSim( latLon, h0, v0, psi0, theta0, trajDes );
Inputs
 latLon       (1,2)  Initial latitude & longitude                    [deg]
                        - Or, you may supply the string name of a U.S. city.
                        - Type "help LatLon" for more information.
 h0            (1)   Initial altitude                                [km]
 v0            (1)   Initial velocity                                [m/s]
 psi0          (1)  Initial heading angle                            [deg]
 theta0        (1)  Initial flight-path angle                        [deg]
 trajDes       (.)   Data structure containing desired trajectory.
                     Has the following fields:
       .vel   (1,N)     Time-history of desired velocity             [m/s]
       .psi   (1,N)     Time-history of desired heading angle        [deg]
       .theta (1,N)     Time-history of desired flight-path angle    [deg]
       .dT     (1)      Time-step used in desired trajectory         [sec]
Outputs
 p             (.)   Structure with time-histories of recorded simulation data
References and(), CoordinateTransform(), Date2JD(), Gyro(), Initialize(), length(), Mag(), NewFig(), Pilot(), quaternion(), set(), and zeros().
AirshipCV()
function AirshipCV (in a1, in a2)
 A double-ellipsoid geometry is assumed, where the front ellipsoid
 has length a1, and the rear ellipsoid has length a2.
Form
 xcv = AirshipCV( a1, a2 )
Inputs
 a1          (1)       semi-major axis of front ellipsoid
 a2          (1)       semi-major axis of rear ellipsoid
Outputs
 xcv         (1)       x-Location of hull center of volume
                           (measured back from nose)
References and(), and length().
Referenced by Airship3DLayout(), AirshipBallonets(), BuildAirshipModel(), FinGeometry(), and GondolaGeometry().
AirshipDesignGUI()
function AirshipDesignGUI (in action, in modifier, in data)
Form
 tag = AirshipDesignGUI( action, modifier )
Inputs
 action          (1,:)   Action to be taken by the Airship Design GUI
 modifier        (:)     Modifier applied to action
 data            (:)     Data passed
Outputs
 tag             (1,:)   Returns the window tag on initialization
References CloseFigure(), CreateCallback(), get(), GetH(), HelpSystem(), Initialize(), isempty(), and set().
AirshipDrag()
function AirshipDrag (in h, in u, in A, in Cd)
Form
 D = AirshipDrag( h, u, A, Cd );
Inputs
 h           (1)       Altitude           [m]
 u           (1)       Velocity           [m/s]
 A           (1)       Reference Aera     [m^2]
 Cd          (1)       Zero-incidence drag coeffcient
Outputs
 D           (1)       Total drag force   [N]
References Altitude(), and StdAtm().
AirshipDynamics()
function AirshipDynamics (in linModFile)
Form
 AirshipDynamics( linModFile )
Inputs
 linModFile     (:)    Name of mat-file containing open-loop models
Outputs
 none
References set(), and zeros().
AirshipGeometry()
function AirshipGeometry (in L, in D, in ratio)
 Assume a double-ellipsoid configuration.
Form
 [S, V, a1, a2, b] = AirshipGeometry( L, D, ratio )
Inputs
 L           (1)       Length of hull                       [m]
 D           (1)       Diameter of hull                     [m]
 ratio       (1)       Ratio of rear to front ellipsoid length
Outputs
 S           (1)       Surface aera                         [m^2]
 V           (1)       Volume                               [m^3]
 a1          (1)       Semi-major axis of front ellipsoid   [m]
 a2          (1)       Semi-major axis of rear ellipsoid    [m]
 b           (1)       Semi-minor axis of each ellipsoid    [m]
References and(), HalfEllipsoid(), length(), and square().
Referenced by Airship3DLayout(), AirshipBallonets(), and BuildAirshipModel().
AirshipInertiaFactors()
function AirshipInertiaFactors (in a1, in a2, in b)
 A double ellipsoid geometry is assumed.
 For a single ellipsoid, a1 = a2.
Form
 [k1, k2, kp] = AirshipInertiaFactors( a1, a2, b );
Inputs
 a1          (1)       Semi-major axis of front ellipsoid   [m]
 a2          (1)       Semi-major axis of rear ellipsoid    [m]
 b           (1)       Semi-minor axis of each ellipsoid    [m]
Outputs
 k1          (1)       Coefficient of added mass, axial
 k2          (1)       Coefficient of added mass, normal
 kp          (1)       Coefficient of added inertia, rotational
Reference: "Inertia Factors of Ellipsoids for use in Airship Design", NACA Report No. 210 by L.B. Tuckerman.
 Copyright (c) 2003 Princeton Satellite Systems, Inc.
 All rights reserved.
Referenced by BuildAirshipModel().
AirshipInit()
function AirshipInit (in d, in latLonAlt, in vAB, in eul, in trim, in wind)
Form
 [d,x] = AirshipInit( d, latLonAlt, vAB, eul, trim, wind );
Inputs
 d              (.)    Initial aircraft data structure, generated from
                        "BuildAirshipModel", or you may supply just the
                        name of an airship model.
 latLonAlt     (4,1)   Latitude (deg), Longitude (deg), Altitude (km),
                        4th element is Julian Date (default is JD2000)
 vAB           (3,1)   Velocity (m/s), alpha (rad), beta (rad)
 eul           (3,1)   Roll, Pitch, Yaw (rad)
 trim           (1)    Indicates whether to trim (1) or not (0).
                        (default is 1)
 wind           (.)    Wind data structure. See "WindModel.m". Optional.
Outputs
 d              (.)    Aircraft data structure, updated with state
                        information and trim controls (if desired)
 x              (.)    Initial aircraft state, class "acstate"
References ACInit(), acstate(), AirshipMassModel(), AirshipTrim(), Altitude(), and(), ASM3(), BuildAirshipModel(), CoordinateTransform(), Cross(), IConvP(), Initialize(), isempty(), JD2000(), length(), QECI(), quaternion(), set(), Wind(), and zeros().
Referenced by AirshipLinMod(), AirshipSim(), and AirshipStabConDerivatives().
AirshipIntegrals()
function AirshipIntegrals (in a1, in a2, in b, in hullFraction, in xo)
Form
 [I1, I3, J1, J2] = AirshipIntegrals( a1, a2, b, hullFraction, xo );
Inputs
 a1            (1)       Semi-major axis of front ellipsoid   [m]
 a2            (1)       Semi-major axis of rear ellipsoid    [m]
 b             (1)       Semi-minor axis of each ellipsoid    [m]
 hullFraction  (1)       Fraction of total length regarded as hull
                           (point from nose at which fins begin)
 xo            (1)       x-Location of body-frame origin      [m]
                           (measured back from nose)
Outputs
 I1            (1)       Integral of (dA/dx) from nose to hull length / (vol)^(2/3)
 I3            (1)       Integral of x*(dA/dx) from nose to hull length / L*(vol)^(2/3)
 J1            (1)       Integral of 2*r from nose to hull length / (vol)^(2/3)
 J2            (1)       Integral of 2*r*x from nose to hull length / L*(vol)^(2/3)
Reference: Jones, DeLaurier, "Aerodynamic Estimation Techniques for Aerostats and Airships", AIAA Lighter-than-Air Systems Conference, Anapolis MD, 1981, Paper No. 81-1339.
 Copyright (c) 2003 Princeton Satellite Systems, Inc.
 All rights reserved.
References Integral(), and length().
Referenced by BuildAirshipModel(), and FinFactors().
AirshipLinMod()
function AirshipLinMod (in d, in h, in theta, in alpha, in V, in useAlpha)
Form
 g = AirshipLinMod( d, h, theta, alpha, V );
Inputs
4 INPUTS:
 d           (.)       Airship model data structure
 h           (1)       Altitude                             [m]
 theta       (1)       Flight path angle                    [rad]
 alpha       (1)       Angle of attack                      [rad]
 V           (1)       Total velocity                       [m/s]
OR 2 INPUTS:
 d           (.)       Airship model data structure
 x           (.)       Aircraft state object                [m]
Outputs
 g           (.)       State-space data structure
 Copyright (c) 2003 Princeton Satellite Systems, Inc.
 All rights reserved.
References AC(), AirshipInit(), AlphBeta(), Altitude(), and(), BuildAirshipModel(), ECIToNED(), get(), Mag(), Q2Eul(), QMult(), QPose(), quaternion(), and zeros().
AirshipMassModel()
function AirshipMassModel (in varargin)
 Forms:
 m = AirshipMassModel( 'initialize', 'yourModelName' );
 m = AirshipMassModel( 'initialize', modelDataStructure );
 m = AirshipMassModel( 'update', h );
 m = AirshipMassModel( 'update' );
Inputs
 action        (:)       'initilize' or 'update'
 data          (:)       Depends on action.
                           * With 'initialize', this may be the name of
                              an airship design script, or the structure
                              generated from "BuildAirshipModel".
 * With 'update', this is a 2 element vector
 [h,rho], with altitude (h) in meters and
 atmospheric density (rho) in kg/m^3
 OPTIONAL:
 A 3rd element may also be provided, the
 ballonet volume fraction (bvf). If not
 provided, it is set to 1.
 NOTE: If no data is provided with 'update', the current airship mass
 model is returned without being changed.
Outputs
 m             (.)       Airship mass model, a data structure with fields:
                           .mass       Total mass of the airship
                           .inertia    Moment of inertia
                           .cM         Center of mass position
References and(), Initialize(), set(), and vector().
Referenced by AirshipInit(), AirshipState(), and BuildAirshipModel().
AirshipMaxCruise()
function AirshipMaxCruise (in Cd0, in Vol23, in Pmax, in h)
 throughout its altitude range. The maximum velocity and thrust are
 computed based upon
 the assumption that thrust = drag at the maximum velocity, with a
 constant power limit applied throughout.
Form
 [llh,ra,rEF,t] = DASim( x0, d, hMin );
Inputs
 Cd0            (1,1)      Zero angle drag coefficient
 Vol23          (1,1)      Reference area, volume^(2/3) (m^2)
 Pmax           (1,1)      Maximum available power (W)
 h              (1,N)      Altitude vector (m)
Outputs
 Vmax           (1,N)      Maximum velocity at each altitude
 Tmax           (1,N)      Maximum required thrust at each altitude
 q              (1,N)      Max dynamic pressure at each altitude
References Altitude(), and(), NewFig(), and vector().
AirshipMDot()
function AirshipMDot (in h, in hDot)
Form
 mDot = AirshipMDot( h, hDot );
Inputs
 h          (1,:)    Array of altitudes (m)
 hDot        (1)     Nominal climb rate (m/s)
Outputs
 mDot       (1,:)    Percent rate of change of mass
References AirshipMDot(), length(), NewFig(), and set().
Referenced by AirshipMDot().
AirshipPropeller()
function AirshipPropeller (in ignoredArg, in d, in control, in ignoredArg, in ignoredArg)
The airship has two counter-rotating propellers mounted to opposite sides of the gondola. They are nominally aligned in the +x direction.
Each propeller is assumed to have a maximum thrust capability of "d.thrustMax".
The thrust may be directed by simultaneously rotating each propeller about the y-axis through the angle "control.mu".
The total thrust may be controlled via "control.throttle", which linearly scales the magnitude.
The output is a data structure that contains the forces and torques on the airship due to the propeller thrust.
Form
 g = AirshipPropeller( x, d, control, altitude, machNo )
Inputs
 x                     State
 d                     Engine data
 control               Controls
 altitude       (1,1)  Altitude
 machNo         (1,1)  Mach number
Outputs
 g                     Output data structure
                       .torque      (3,1) Core torques
                       .force       (3,1) Core forces
                       .xDot        (:,1) Engine state derivatives
                       .mDot        (1,1) Fuel consumption
                       .inertiaDot  (3,3) Inertia derivative due to fuel consumption
                       .cGDot       (3,1) CG derivative due to fuel consumption
                       .torqueRotor (:,1) Torques on rotors
References Altitude(), and(), Cross(), and zeros().
Referenced by BuildAirshipModel().
AirshipSensor()
function AirshipSensor (in x, in d, in opt)
Outputs are:
 roll rate        (rad/sec)
 pitch rate       (rad/sec)
 yaw rate         (rad/sec)
 axial velocity   (m/s)
 lateral velocity (m/s)
 normal velocity  (m/s)
 angle of attack  (rad)
 sideslip angle   (rad)
 roll angle       (rad)
 pitch angle      (rad)
 yaw angle        (rad)
 altitude         (m)
Form
 g = AirshipSensor( x, d, opt )
Inputs
 x           (:)   acstate data structure
 d           (:)   Aircraft data structure
 opt               'rhs'  outputs state derivatives
                   'meas' outputs measurements
Outputs
 g           (:)   Sensor output
                   .p         (1,1) Roll rates
                   .q         (1,1) Pitch rate
                   .r         (1,1) Yaw rates
                   .u         (1,1) Axial velocity
                   .v         (1,1) Lateral velocity
                   .w         (1,1) Normal velocity
                   .alpha     (1,1) Angle of attack
                   .beta      (1,1) Sideslip Angle
                   .phi       (1,1) Bank Angle
                   .altitude  (1,1) Altitude
References acstate(), AlphBeta(), Altitude(), EulNED(), get(), Mag(), Normal(), and zeros().
Referenced by BuildAirshipModel().
AirshipSim()
function AirshipSim (in d, in x, in T, in dT, in ignoredArg)
Form
 data = AirshipSim( d, x, T, dT, control );
Inputs
 d              (.)    Aircraft data structure
 x              (:)    Initial state, class "acstate"
 T              (1)    Length of simulation (sec)
 dT             (1)    Optional. Time step (sec). Default is 0.1 sec.
 control        (.)    Optional. Control input data structure with
                       following fields, where integer N > T/dT.
                        - throttle  (1,N) Throttle command (0-1)
                        - mu        (1,N) Thrust vector angle
                        - dELVL     (1,N) Left elevator deflection
                        - dELVR     (1,N) Right elevator deflection
                        - dRUDT     (1,N) Top rudder deflection
                        - dRUDB     (1,N) Bottom rudder deflection
Outputs
 out            (.)    Recorded state data. Data structure with fields:
                        - t      Time (sec)
                        - lat    Latitude (deg)
                        - long   Longitude (deg)
                        - alt    Altitude (km)
                        - V      Airspeed velocity (m/s)
                        - alpha  Angle of attack (deg)
                        - beta   Sideslip angle (deg)
                        - phi    Roll angle (deg)
                        - theta  Pitch angle (deg)
                        - psi    Heading angle (deg)
                        - p      Roll rate (deg/s)
                        - q      Pitch rate (deg/s)
                        - r      Yaw rate (deg/s)
                        - mass   Total mass, with all internal gas (kg)
                        - cG     Center of gravity location (m)
References AirshipInit(), Altitude(), and(), ASM3(), ECIToEF(), EFToLatLonAlt(), Euler(), get(), Initialize(), JD2000(), JD2T(), Plot2D(), Q2Eul(), Throttle(), TimeGUI(), vector(), and zeros().
Referenced by AirshipSimGUI().
AirshipSimGUI()
function AirshipSimGUI (in action, in ignoredArg, in ignoredArg)
Form
 tag = AirshipSimGUI( action, modifier )
Inputs
 action          (1,:)   Action to be taken by the Airship Sim GUI
 modifier        (:)     Modifier applied to action
 data            (:)     Data passed
Outputs
 tag             (1,:)   Returns the window tag on initialization
References AirshipSim(), CloseFigure(), CreateCallback(), get(), GetH(), HelpSystem(), Initialize(), isempty(), and set().
AirshipStabConDerivatives()
function AirshipStabConDerivatives (in mdl, in h, in theta, in alpha, in V)
 The subscripts are given after an underscore. For example,
 _V is a "V" subscript. Each subscript indicates the
 variable (state or control) that the partial derivative
 is taken with respect to.
 The dimensional derivatives are named with the force or
 moment abbreviation, followed by a subscript.
 The non-dimensional derivatives are named with "C"
 then the force or moment abbreviation, followed by a
 subscript.
 For eample:
 - M_alpha is the dimensional derivative for the pitch
 moment "M" with respect to angle of attack "alpha".
 - Cm_alpha is the corresponding non-dimensional
 derivative.
Form
 [dim,nonDim] = AirshipStabConDerivatives( mdl, h, theta, alpha, V )
Inputs
Outputs
 dim     (.)   Data structure with fields for dimensional derivatives
                 - Partial derivatives of body frame forces with respect
                   to small changes in various states and controls, then
                   divided by mass.
                 - Partial derivatives of body frame moments with
                   respect to small changes in various states and
                   controls, then divided by the inertia of that axis.
 nonDim  (.)   Data structure with fields for non-dimensional
 derivatives. Each non-dimensional derivative is equal to
 the corresponding dimensional derivative, multiplied by a
 scaling factor. The following scaling factors are used:
 - FORCE_VELOCITY :      V *    mass / (qBar * S)
 - FORCE_ANGLE :                mass / (qBar * S)
 - FORCE_ANGLE-RATE:   2*V *    mass / (qBar * S * c)
 - MOMENT_VELOCITY :     V * inertia / (qBar * S * c)
 - MOMENT_ANGLE :            inertia / (qBar * S * c)
 - MOMENT_ANGLE-RATE : 2*V * inertia / (qBar * S * c * c)
 where V is the airspeed, qBar is the dynamic pressure, S
 is the reference area, c is the reference length. The
 inertia quantity used is for the corresponding axis of
 the moment, and is computed in the wind-frame.
References AirData(), AirshipInit(), AirshipState(), AlphBeta(), Altitude(), and(), ASM3(), BToW(), BuildAirshipModel(), ECIToNED(), get(), Initialize(), isempty(), length(), Mag(), Q2Eul(), QMult(), QPose(), quaternion(), vector(), and zeros().
AirshipState()
function AirshipState (in d, in latLonAlt, in vAB, in eul)
Compute state from a model data structure and initial conditions of:
 [latitude, longitude, altitude]
 [airspeed, angle of attack, sideslip]
 [roll, pitch, yaw]
Form
 x = AirshipState( d, latLonAlt, vAB, eul );
Inputs
 d              (.)    Initial aircraft data structure, generated from
                        "BuildAirshipModel", or you may supply just the
                        name of an airship model.
 latLonAlt     (4,1)   Latitude (deg), Longitude (deg), Altitude (km),
                        4th element is Julian Date (default is JD2000)
 vAB           (3,1)   Velocity (m/s), alpha (rad), beta (rad)
 eul           (3,1)   Roll, Pitch, Yaw (rad)
Outputs
 x              (.)    Initial aircraft state, class "acstate"
References acstate(), AirshipMassModel(), Altitude(), and(), ASM3(), BuildAirshipModel(), CoordinateTransform(), Cross(), IConvP(), Initialize(), JD2000(), length(), QECI(), quaternion(), set(), vector(), and zeros().
Referenced by AirshipStabConDerivatives().
AirshipStatespace()
function AirshipStatespace (in g, in useAlpha)
and lat.-dir. statespace models for an airship
Form
 [gLat,gLon] = AirshipStatespace( g )
Inputs
 g           (:)   statespace data structure
 useAlpha    (1)   Flag indicating which states were used to linearize:
                     1  -  vT, alpha, beta
                     0  -  u, v, w
Outputs
 gLat        (:)   Lateral-Directional statespace
 gLat        (:)   Lateral-Directional statespace
References and(), get(), getabcd(), and statespace().
AirshipTrim()
function AirshipTrim (in d, in h, in theta, in alpha, in V)
Form
 [T,mu,dElv] = AirshipTrim( d, h, theta, alpha, V );
Inputs
5 INPUTS:
 d           (.)       Airship model data structure
 h           (1)       Altitude                             [m]
 theta       (1)       Pitch angle                          [rad]
 alpha       (1)       Angle of attack                      [rad]
 V           (1)       Total velocity                       [m/s]
OR 2 INPUTS:
 d           (.)       Airship model data structure
 x           (.)       Aircraft state object                [m]
Outputs
 T           (1)       Trim thrust value                    [N]
 mu          (1)       Trim thrust pitch angle              [rad]
 dELV        (1)       Trim elevator deflection             [rad]
 Copyright 2003 Princeton Satellite Systems, Inc.
 All rights reserved.
References abs(), AC(), ACInit(), acstate(), AirData(), AirshipAero(), AlphBeta(), Altitude(), and(), ASM1(), BuildAirshipMassModel(), BuildAirshipModel(), ECIToNED(), get(), IConvP(), Mag(), Q2Eul(), QECI(), QMult(), QPose(), quaternion(), vector(), and zeros().
Referenced by AirshipInit().
AirshipTrimAnalysis()
function AirshipTrimAnalysis (in data)
Form
 data = AirshipTrimAnalysis( data )
Inputs
 data    (.)   Data structure generated by the function,
               "GenerateAirshipAeroMats", with fields:
                .name
                .xo:       x-location of origin                   [m]
                .h:        altitude                               [m]
                .theta:    flight path angle                      [rad]
                .alpha:    angle of attack         (1xM vector)   [rad]
                .V:        velocity                (1xN vector)   [m/s]
                .Fx:       force in x-direction    (MxN matrix)   [N]
                .Fz:       force in z-direction    (MxN matrix)   [N]
                .My:       moment about y-axis     (MxN matrix)   [Nm]
Outputs
 data    (.)   New data structure. Copy of input with additional fields:
                .T:        Trim thrust value        (MxN matrix)  [N]
                .mu:       Trim thrust pitch angle  (MxN matrix)  [rad]
                .dELV:     Trim elevator deflection (MxN matrix)  [rad]
See also
GenerateAirshipAeroMats, BuildAirshipModel
References and(), BuildAirshipModel(), GenerateAirshipAeroMats(), length(), StdAtm(), vector(), and zeros().
BalanceAirshipPayload()
function BalanceAirshipPayload (in name)
balance.
 Given the set of components that comprise the airship mass model,
 determine the x-location of the payload that provides balance, so that
 the CM is beneath the CV when the ballonets are empty.
Form
 [body,comp,xPld] = BalanceAirshipPayload( name );
Inputs
 name          (:)       Name of airship design file.
Outputs
 body          (.)       Balanced body mass data structure with fields:
                           .mass       Total mass of the airship
                           .inertia    Moment of inertia about CV
                           .cM         Center of mass position wrt CV
 comp          (.)       Component mass data structures with fields:
 .mass       Mass of the component
 .inertia    Inertia of the component about
 the local origin
 .cM         Center of mass position wrt the
 origin of the local frame
 .r0         Position of the local frame
 origin wrt the CV
 xPld          (1)       Required location of payload, measured back
 from nose, non-dimensional with hull length.
 To be used in airship design script.
References BuildAirshipMassModel(), isempty(), length(), and set().
Referenced by BuildAirshipMassModel().
BuildAirshipMassModel()
function BuildAirshipMassModel (in name, in h, in xon, in bvf)
Form
 [body,comp] = BuildAirshipMassModel( name, h, xon, bvf );
Inputs
 name          (:)       Name of airship design file.
 h             (1)       Altitude (meters)
 xon           (1)       x-location of origin, measured back from nose
                           (optional, default is to put origin at CV)
 bvf           (1)       Ballonet volume fraction, optional (default: 1)
Outputs
 body          (.)       Body mass data structure with fields:
                           .mass       Total mass of the airship
                           .inertia    Moment of inertia about CV
                           .cM         Center of mass position wrt CV
 comp          (.)       Component mass data structures with fields:
 .mass       Mass of the component
 .inertia    Inertia of the component about
 the local origin
 .cM         Center of mass position wrt the
 origin of the local frame
 .r0         Position of the local frame
 origin wrt the CV
DESCRIPTION:
The airship hull is modelled as 2 axi-symmetric ellpsoids. It has 4 symmetric tailfins, and a hanging empennage that supports the payload and 2 engines / propellers.
The total mass is given as:
 m = mS + mF + mP + mH + mA
where the individual mass components are
 mS: structure and all systems
 mF: external fabric
 mP: payload
 mH: Helium
 mA: air in ballonets (varies with altitude)
In order to compute the CG and the moment of inertia, we approximate the mass distribution of the airship. Several steps and assumptions are taken to develop the model.
 *  The structure/system mass (mS) includes the engines, internal
 structure, and tail-fins. Solar cells are ignored.
 The engine mass is assumed to be 60% mS. The tail-fins are assumed to
 be 10% mS. This leaves 30% mS for support structure.
 *  Each tail-fin is treated as a point-mass, with the CG located at the
 centroid of the surface area.
 *  The support structure is assumed to be distributed uniformly
 across the hull surface.
 *  The air in the ballonets occupies the bottom portion of the hull.
 The volume of air (and the mass) changes with altitude. We assume two
 ballonets, fore and aft, are used. Each is modeled as a
 half-ellipsoid, and they are centered at the CV location of the hull,
 which is also the center of buoyancy (CB). This is done so that, when
 the ballonets have equal volumes, the center of mass of the air lies
 directly beneath the CB, creating no moment.
 *  The payload is treated as a point mass, located at [xP;0;zP], which
 is the center point of the hanging empennage. A separate function can
 be used (BalanceAirshipPayload) to find the "xP" value that give zero
 moment when the ballonets are empty. The airship should be designed
 so that this value fits within the x-range of the empennage.
 *  The right/left engines are treated as two point-masses, located at
 [xE;+/-yE;zE]. To be practical, xE and zE should lie within the area
 occupied by the hanging empennage.
Given these assumptions, the model is composed of 7 point masses (4 fins, 2 engines, 1 payload), and 4 continuum masses (fabric shell, Helium, air, structure). Each continuum mass is split into front and rear components. This gives a total of 15 components. When the airship is above the pressure altitude, the ballonets are empty and are thus not included, leaving 13 components.
The "IntegrateMassProps" function is called to compute the mass, CG and inertia of the complete airship in body-frame coordinates. The body-frame is an orthoganal frame with x pointing through the nose, z pointing down, and y completing the right-handed system. The origin of the body-frame may be specified as an input. If not provided, it is placed at the CV.
References Altitude(), and(), ASM3(), BalanceAirshipPayload(), and length().
Referenced by Airship3DLayout(), AirshipBallonets(), AirshipTrim(), BalanceAirshipPayload(), BuildAirshipModel(), and GenerateAirshipAeroMats().
BuildAirshipModel()
function BuildAirshipModel (in name, in xoN)
Form
 model = BuildAirshipModel( name, xoN )
Inputs
 name        (1)       Name of airship design script.
 xoN         (1)       x-Location of body-frame origin (from nose)
Outputs
 model       (.)       Airship model data structure.
References AddedMass(), AirshipAero(), AirshipCoefficients(), AirshipCV(), AirshipGeometry(), AirshipInertiaFactors(), AirshipIntegrals(), AirshipMassModel(), AirshipPropeller(), AirshipSensor(), and(), ASM4(), BuildAirshipMassModel(), FinFactors(), FinGeometry(), GondolaGeometry(), IConvP(), isempty(), length(), SkewSq(), StdAtm(), and zeros().
Referenced by AirshipAeroAnalysis(), AirshipInit(), AirshipLinMod(), AirshipStabConDerivatives(), AirshipState(), AirshipTrim(), AirshipTrimAnalysis(), GenerateAirshipAeroMats(), and GenerateAirshipLinMods().
CDAirship()
function CDAirship (in alpha, in delta)
Form
 cD = CMAirship( alpha, delta )
Inputs
 alpha          (:)   Angle of attack (deg)
 delta          (:)   Elevator angle (deg)
Outputs
 cD             (:)   Drag coefficient
References and(), length(), and Plot2D().
CLAirship()
function CLAirship (in alpha)
Form
 cL = CLAirship( alpha )
Inputs
 alpha          (:)  Angle of attack (deg)
Outputs
 cL             (:)  Lift coefficient
References and(), and Plot2D().
CMAirship()
function CMAirship (in dK, in v, in alpha)
dK is a column vector.
Form
 cM = CMAirship( dK, v, alpha )
Inputs
 dK             (:,1) K2 - K1
 v              (1,1) Volume
 alpha          (:)   Angle of attack (deg)
Outputs
 cM             (:)   Lift coefficient
References and(), Plot2D(), SinD(), and vector().
DrawAirship()
function DrawAirship (in L, in D, in ratio, in n, in orientation)
Form
 DrawAirship( L, D, ratio );
Inputs
 L             (1)       Length of hull                       [m]
 D             (1)       Diameter of hull                     [m]
 ratio         (1)       Ratio of rear to front ellipsoid length
 n             (1)       Number of vertices to plot (default 25)
 orientation   (1)       Flag: 0 horizontal, 1 vertical (default 0)
Outputs
 x             (1)       x-data
 y             (1)       y-data
 z             (1)       z-data
References abs(), and(), DrawAirship(), Ellipsd(), isempty(), length(), Mag(), NewFig(), set(), and square().
Referenced by DrawAirship().
FinFactors()
function FinFactors (in J1, in Sf, in Sfh, in vol)
 Zero dihedral is assumed.
Form
 [etaK, etaF] = FinFactors( J1, Sf, Sfh, vol )
Inputs
 J1          (1)       One of Munk's integrals; see AirshipIntegrals.m
 Sf          (1)       Fin reference aera
 Sfh         (1)       Combined fin & hull cross-sectional area
 vol         (1)       Hull volume
Outputs
 etaK        (1)       Hull efficiency factor (effect of fins on the hull)
 etaF        (1)       Fin efficiency factor  (effect of hull on the fins)
Reference: Khoury, Gillett, "Airship Technology", p.53
 Copyright (c) 2003 Princeton Satellite Systems, Inc.
 All rights reserved.
References AirshipIntegrals(), and and().
Referenced by BuildAirshipModel().
FinGeometry()
function FinGeometry (in a1, in a2, in b, in xFinA, in xFinB, in xFinC, in yzFinI, in yzFinO)
 All lengths are non-dimensional. Fin lengths (x) are measured back
 from the nose. Fin widths (yz) are measured out from the hull
 center-line.
Form
 [Sf,Sfh,fC,fW] = FinGeometry( a1, a2, b, xFinA, xFinB, xFinC, yzFinI, yzFinO );
Inputs
 a1          (1)     Semi-major axis of front ellipsoid
 a2          (1)     Semi-major axis of rear ellipsoid
 b           (1)     Semi-minor axis of each ellipsoid
 xFinA       (1)     Leading-edge of fin at hull / hull length
 xFinB       (1)     Start of fin taper / hull length
 xFinC       (1)     Trailing-edge of fin / hull length
 yzFinI      (1)     Inboard fin width / hull radius
 yzFinO      (1)     Outboard fin width / hull radius
Outputs
 Sf          (1)     Fin reference area
 Sfh         (1)     Area of hull projection at fins
 fC          (1)     Mean fin chord-length
 fW          (1)     Mean fin width (span)
References AirshipCV(), and(), FinGeometry(), length(), and NewFig().
Referenced by BuildAirshipModel(), and FinGeometry().
GenerateAirshipAeroMats()
function GenerateAirshipAeroMats (in name, in xo, in h, in theta, in alpha, in V)
For a range of flight conditions. Results stored in mat-file for later analysis.
The force and torque due to buoyancy is included. No controls are applied (zero throttle, zero deflections)
Form
 data = GenerateAirshipAeroMats( name, xo, h, theta, alpha, V );
Inputs
 name        (:)       Airship model name
 xo          (1)       x-Location of body-frame origin   [m] (from nose)
 h           (1)       Altitude                          [m]
 theta       (1)       Flight path angle                 [rad]
 alpha      (1,M)      Range of Angle of attack values   [rad]
 V          (1,N)      Range of Velocity values          [m/s]
Outputs
 data        (.)       Data structure with:
                        - name
                        - xo:       x-location of origin
                        - h:        altitude
                        - theta:    flight path angle
                        - alpha:    angle of attack         (1xM vector)
                        - V:        velocity                (1xN vector)
                        - Fx:       force in x-direction    (MxN matrix)
                        - Fz:       force in z-direction    (MxN matrix)
                        - My:       moment about y-axis     (MxN matrix)
References acstate(), AirshipAero(), Altitude(), and(), ASM1(), BuildAirshipMassModel(), BuildAirshipModel(), DeleteSuffix(), GenerateAirshipAeroMats(), length(), QECI(), StdAtm(), vector(), and zeros().
Referenced by AirshipTrimAnalysis(), and GenerateAirshipAeroMats().
GenerateAirshipLinMods()
function GenerateAirshipLinMods (in d, in h, in V, in theta)
 The angle of attack is set to zero.
Form
 GenerateAirshipLinMods( d, h, V, thteta )
Inputs
 d           (.)       Airship model data structure.
 h          (1,:)      Altitude                          [m]
 V          (1,:)      Total velocity                    [m/s]
 theta      (1,:)      Pitch                             [rad]
Outputs
 none
References Altitude(), ASM1(), BuildAirshipModel(), DeleteSuffix(), length(), and set().
GetAirshipLinMod()
function GetAirshipLinMod (in name, in h, in V, in theta)
Form
 [g,gLat,gLon] = GetAirshipLinMod( name, h, V, theta )
Inputs
 name        (:)      Name of linear model mat-file.
                        (see "GenerateAirshipLinMods.m")
 h           (1)      Altitude                          [m]
 V           (1)      Total velocity                    [m/s]
 theta       (1)      Pitch                             [rad]
Outputs
 g           (.)      Full state linear model, statespace class
 Additional outputs optional: (see "AirshipStatespace.m")
 gLat        (.)      Lateral-Directional linear model
 gLon        (.)      Longitudinal linear model
References abs(), Altitude(), and statespace().
GondolaGeometry()
function GondolaGeometry (in a1, in a2, in b, in xGonA, in xGonB, in zGon)
 Assume a rectangular shaped gondola hanging from hull.
 All lengths are dimensionless. Axial lengths (x) are measured back from
 the nose. The radial length (z) is measured out from the hull
 center-line.
Form
 [Sg, xGonCM, zGonCM] = GondolaGeometry( a1, a2, b, xGonA, xGonB, zGon );
Inputs
 a1          (1,1)       Semi-major axis of front ellipsoid
 a2          (1,1)       Semi-major axis of rear ellipsoid
 b           (1,1)       Semi-minor axis of each ellipsoid  [m]
 xGonA       (1,1)       Leading-edge of gondola / hull length
 xGonB       (1,1)       Trailing-edge of gondola / hull length
 zGonB       (1,1)       Bottom edge of gondola / hull radius
Outputs
 Sg          (1,1)       Cross-sectional area of gondola
 xGonCM      (1,1)       Cross-sectional area of gondola
 zGonCM         (1,1)       Cross-sectional area of gondola
References AirshipCV(), and(), Cross(), GondolaGeometry(), length(), and NewFig().
Referenced by BuildAirshipModel(), and GondolaGeometry().
HalfEllipsoid()
function HalfEllipsoid (in a, in b)
Form
 [V,S,cSld,cShl,inrSld,inrShl] = HalfEllipsoid( a, b );
Inputs
 a          (1)   Length along axis of rotation
 b          (2)   Radius at max cross-section
                     Note: a==b is a hemisphere
Outputs
 V          (1)   Volume
 S          (1)   Surface Area
 cSld       (1)   Centroid of solid
 cShl       (1)   Centroid of shell
 inrSld     (1)   Specific inertia of solid, multiply by density for I
 inrShl     (1)   Specific inertia of shell, multiply by density for I
References and(), and Centroid().
Referenced by AirshipGeometry().
IntegrateMassProps()
function IntegrateMassProps (in comp)
The moment of inertia for each component is defined with respect to a local coordinate frame. The position of each local coordinate frame is defined with respect to the body frame origin. The local coordinate frames of the components may only be translated, not rotated, from the body frame.
Inputs
 comp      (:)     Array of component data structures, with fields:
             .mass      Mass of component
             .inertia   Inertia of component about origin of local frame
             .cM        Position of component CM wrt local frame origin
             .r0        Position of each local frame wrt body frame orig
                   NOTE: If r0 not given, all local frames are assumed
                         to coincide with the body frame.
Outputs
 body      (.)     Body data structure, with fields:
             .mass      Mass of body
             .inertia   Inertia of body about origin of body frame
             .cM        Position of body CM wrt body frame origin
References and(), length(), SkewSq(), and zeros().
LatLon()
function LatLon (in city)
city.
 Available cities:
 - New York
 - Washington D.C.
 - Miami
 - Los Angeles
 - San Francisco
 - Seattle
Form
 [lat,lon] = LatLon( city )
Inputs
 city        (:)       Name of city
Outputs
 lat         (1)       Latitude  [deg]
 lon         (1)       Longitude [deg]
References and().
SolarCellCoverage()
function SolarCellCoverage (in h, in u, in S, in Cd, in P0, in Emax, in fSun, in etaProp, in etaCell)
 hull geometry, as a function of the required power, the solar cell
 efficiency, the global irradiance, and the daily fraction of
 sun-exposure
Form
 R = SolarCellCoverage( h, u, S, Cd, P0, Emax, fSun, etaProp, etaCell );
Inputs
 h           (1)       Altitude                             [m]
 u           (1)       Velocity                             [m/s]
 S           (1)       Reference aera                       [m^2]
 Cd          (1)       Zero-incidence drag coefficient
 P0          (1)       Nominal power required for payload   [W]
 EMax        (1)       Maximum solar irradiance             [W/m^2]
 fSun        (1)       Daily fraction of sun exposure
 etaProp    (1,M)      Propeller/engine efficiency
 etaCell    (1,N)      Solar cell efficiency
Outputs
 R          (M,N)      Required solar cell coverage ratio:
                         solar cell area / hull surface area
References Altitude(), and(), length(), NewFig(), SolarCellCoverage(), StdAtm(), and zeros().
Referenced by SolarCellCoverage().
StructuralMass()
function StructuralMass (in VMax, in kSV, in rhoF, in alt, in mP)
 The lifting gas is assumed to be Helium.
Form
 [m0,mT,mH] = StructuralMass( VMax, kSV, rhoF, alt, mP );
 Example:
 [m0,mT,mH] = StructuralMass( 736310.778, 0.065, 0.5, 21300, 1814 );
Inputs
 VMax        (1)       Maximum volume                    [m^3]
 kSV         (1)       Surface area -to- volume ratio
 rhoF        (1)       Exterior fabric density           [kg/m^2]
 alt         (1)       Pressure altitude                 [m]
 mP          (1)       Payload mass                      [kg]
Outputs
 m0          (1)       Mass available for structure and systems   [kg]
 mT          (1)       Total vehicle mass, including payload      [kg]
 mH          (1)       Mass of Helium                             [kg]
References and(), length(), NewFig(), Pressure(), StdAtm(), StructuralMass(), and zeros().
Referenced by StructuralMass().
WindLatLon()
function WindLatLon (in XLAT, in XLONG, in ALT, in IDAY, in XLST)
Form
 [windMag,windDir] = WindLatLon( XLAT, XLONG, ALT, IDAY, XLST );
Inputs
 XLAT          (1,M)    Array of latitude values   [deg]
 XLONG         (1,N)    Array of longitude values  [deg]
 ALT            (1)     Altitude  (0 - 75)   [km]
 IDAY           (1)     Day of the year, 1-365 (Jan 1 - Dec 25)
 XLST           (1)     Hour of the day (0 - 24)
Outputs
 windMag       (M,N)    Wind magnitude                      [m/s]
 windDir       (M,N)    Wind heading measured north to east [deg]
References Altitude(), and(), HorizontalWind(), length(), Mag(), NewFig(), Wind(), and zeros().
Referenced by WindLatLonAlt().
WindLatLonAlt()
function WindLatLonAlt (in XLAT, in XLONG, in ALT, in IDAY, in XLST)
Form
 [windMag,windDir] = WindLatLonAlt( XLAT, XLONG, ALT, IDAY, XLST );
Inputs
 XLAT          (1,M)    Array of latitude values   [deg]
 XLONG         (1,N)    Array of longitude values  [deg]
 ALT           (1,P)    Altitude  (0 - 75)   [km]
 IDAY           (1)     Day of the year, 1-365 (Jan 1 - Dec 25)
 XLST           (1)     Hour of the day (0 - 24)
Outputs
 windMag       (M,N,P)  Wind magnitude                      [m/s]
 windDir       (M,N,P)  Wind heading measured north to east [deg]
References and(), length(), Wind(), WindLatLon(), and zeros().