PSS MATLAB Toolboxes: FormationFlying Functions
FormationFlying Functions
FormationFlying Module
The FormationFlying module functions.
Directories
directory Actuators
directory Analysis
Analyze maneuver sequences, guidance and control.
directory Analysis
directory Collision
Collision probability monitoring.
directory CommandLists
directory Control
Compute delta-V sequences for in-plane and out-of-plane maneuvers.
directory Coord
Relative coordinates and goals manipulation.
directory DataStructures
Structures for exchanging data between functions.
directory DefaultData
directory Derivatives
directory Dynamics
Discrete and closed-form relative orbital dynamics.
directory EccDynamics
Dynamics for formations in eccentric reference orbits.
directory Guidance
Goals and costs for maneuver assignments between formations.
directory Initialize
directory IntegratedSim
The integrated formation flying simulation.
directory LP
Linear programming trajectory solvers for circular and eccentric reference orbits.
directory SafeGuidance
The safe guidance method for long-term collision avoidance.
directory Sensors
directory Software
directory Transformation
Transform between state and elements representations.
directory Utility
Utilities.
directory Visual
Description
Functions
function AbsRelECI2Hills (in r0, in v0, in dr, in dv)
Compute a Hills state from a relative ECI state.
function AccelVector2ManeuverStruct (in aC, in t, in tRef, in nomAccel, in minSepTime)
Build a "maneuver" data structure from acceleration and time vectors.
function AddGoals (in e, in nu, in gA, in gBA, in n)
Add one set of geometric goals to the other.
function AlignThruster (in aH, in bTh, in bST, in r, in v, in jD, in sep, in verify)
Computes the desired Hills-to-Body frame quaternion for a thruster firing.
function AlongTrackMotion (in xSLO, in n, in varargin)
Compute attributes of along-track motion from relative state vector.
function AnalyzeVariableTimeDV (in dV1, in dV2, in dV3, in M, in N)
Analyze delta-V maneuver sequences with time between burns.
function AnimateRE (in r, in x0, in aE, in yA, in yR, in dMin, in dV)
Animate the evolution of the desired "safe ellipse" with the position.
function AutoFormGeometry (in state, in memberGoals, in minSepDist, in maxSepDist, in nS)
Autonomously update geometric goals.
function BurnData_Structure ()
Initialize a burn data structure.
function CheckDeltaVs (in state, in maneuver, in iD, in nSPO, in plotFlag)
Plot the trajectory that will result from a planned maneuver.
function CirclePhase (in beta0)
Compute the desired phase on the circle from the desired phase on the ellipse.
function CoarseProb (in rRel, in rAvoid, in sigma)
Coarse collision probability estimate.
function CollisionInit (in caseID)
Sample data for collision algorithm initialization.
function CollisionMonAlg (in y, in t, in M, in nu, in accel, in aDiff, in d)
Collision monitoring algorithm for maneuvering spacecraft.
function CollisionMonitor (in action, in d, in jD, in y)
Runs the collision monitoring algorithm.
function CollisionMonteCarlo (in d, in y0, in aC, in t, in M)
Monte-Carlo analysis of collision probability.
function CollisionSurvey (in d, in t0, in y, in mvr1, in mvr2)
Runs the collision monitoring algorithm for n maneuvering spacecraft.
function CollProbSet (in P0, in S1, in xc1, in S2, in xc2, in Ssc, in n)
Calculates the probability of collision given two ellipsoid sets.
function CollProbVol (in P1, in xc1, in P2, in xc2, in volSC)
Calculates the probability of collision given two ellipsoids using volume relations.
function Command_Structure (in n)
Command data structure for external commands supplied to DFF system.
function CompareHills (in elRef, in xH0, in nOrbits, in dT)
Compare closed form Hills equations with other methods of propagation.
function ComputeRE (in x, in z, in vz, in n, in aEMin, in dMin, in verbose)
Compute a safe 2x1 relative in-plane ellipse.
function ConjunctionPlane (in xRel)
Transformation matrix for relative conjunction geometry.
function Constraints_Structure (in nU)
Initialize a constraints data structure.
function CostEstimate_Structure (in nU)
Initialize a cost estimate data structure.
function CostMatrixRows (in teamGoals, in index)
Given the team goals, determines the starting row (a) and ending row (b)
function CostVis (in r, in cost)
Visualize the cost to achieve each target state on the trajectory.
function CrossTrackDeltaV (in xSLO, in x0, in aE, in n, in dMin, in yAMin, in timeLimited)
Compute the DV to achieve a min.
function DataSize (in data, in runningSize)
Find the size in bytes of a piece of data.
function DeltaAlfriend2El (in e, in w, in M, in dElA)
Compute standard differential elements from Alfriend differential elements.
function DeltaEl2Alfriend (in e, in w, in M, in dEl)
Compute Alfriend differential elements from standard differential elements.
function DeltaElem2Goals (in el0, in dEl, in J2)
Reconstructs the geometric goals from the element differences.
function DeltaElem2Hills (in el0, in dEl, in J2)
Computes the Hills frame state from orbital element differences.
function DeltaVAnalysis (in el0, in y0_i, in aE_i, in beta_i, in y0_f, in aE_f, in beta_f)
Compute the total delta-v assoc.
function DeltaVChart (in varargin)
Generate a stacked bar chart showing delta-v directions over time.
function DeltaVCommand_Structure (in nThrusters)
Initialize a delta-v command data structure.
function DFFAttitudeTarget (in type, in d, in t)
Generate a reference quaternion for a variety of targets.
function DFFControl (in action, in u, in iD)
The executive function that initializes and runs the DFF software modules.
function DFFRHS (in x, in jD, in ignoredArg, in control, in scData)
Right-hand-side of the spacecraft dynamic equations for the DFF system.
function DFFSim (in el0, in dEl0, in teamGoals, in dT, in planTime, in nOrbits, in J2, in dTMax, in fNom, in mass)
Simulation routine for testing DFF guidance and control laws.
function DFFSimGUI (in totalSteps, in stepsDone, in tToGoMem, in rRT, in dT, in name)
DFF simulation status GUI.
function DFFSimulation (in sim, in recordTargetState, in showTeamOrg, in showMsgQ)
Initialize and run a multiple spacecraft simulation with the DFF software.
function DiscreteGVE (in el, in dEl0, in aC, in t)
Computes the relative state trajectory in an eccentric reference orbit.
function DiscreteHills (in x0, in w0, in aC, in dT)
Compute a trajectory from discretized Hills equations.
function DisplayPlugin (in fig, in pos, in bColor, in name)
Display Plugin for the Formation Design GUI.
function DistantPtToEll (in U, in S, in xc, in x0, in laguerre)
Distance from a point to the edge of an ellipsoid.
function DistributeClusterGoals (in clusterGoals, in targetIDs, in teams, in dPhi)
Given a set of geometric goals for the cluster, with corresponding target.
function DriftRateSigma (in a, in sigma_x, in sigma_ydot, in rho_xydot)
Find the standard deviation of along-track drift per orbit due to rel nav errors.
function EccGeometry_Structure (in nU)
Initialize an eccentric geometry data structure.
function EccTeamGoals_Structure (in nU)
Initialize a team goals data structure (for eccentric geometries)
function ECI2Hills (in x0, in x1)
Compute the relative state in Hills frame given two ECI state vectors.
function ECI2LVLH (in x0, in x1)
Compute relative LVLH state from a reference ECI state and ECI state.
function ECI2MeanElements (in xRefECI, in xRelECI, in J2)
Computes mean orbital elements from reference ECI position and velocity.
function EllipseDeltaV (in r0, in v0, in n, in x0)
Compute a delta-v that will change the current relative trajectory to a.
function EllipsePatch (in aX, in bY, in n)
2D elliptical patch, with axes a along x and b along y
function EllipsePhase (in alpha0)
Compute the desired phase on the ellipse from the desired phase on the circle.
function EllipsePropCirc (in P, in Q, in DT, in wn, in hills)
Function finds the propagated state uncertainty ellipsoid.
function Ellipsoid (in s, in u, in n)
Calculate vertices for an ellipsoid.
function EstimateCost (in el0, in dEl, in teamGoals, in memID, in window, in weight)
Estimate the (weighted) cost to achieve all specified unique target states.
function FFEccAnalyzeShape (in varargin)
Interactively analyze the shape of a relative trajectory in an eccentric reference orbit.
function FFEccDeltaElem2Goals (in el0, in dEl, in type)
Convert element differences to eccentric geometric goals.
function FFEccDeltaElem2Hills (in el0, in dEl, in type, in t, in mu)
Convert element differences to Hills frame coordinates in an eccentric orbit.
function FFEccDH (in nu0, in e)
Compute integration constant dH for homogeneous solution to LTV diff eqs.
function FFEccDiscreteHills (in e, in n, in x0, in nu0, in aC, in t)
Computes the relative state trajectory in an eccentric reference orbit.
function FFEccDMatPeriodic (in xH0, in nu0, in e, in method)
Compute velocities for periodic motion in an eccentric orbit.
function FFEccEstimateCost (in el0, in xH0, in teamGoals, in memID, in window, in weight, in nSPO)
Estimate the weighted cost to achieve all specified unique target states.
function FFEccFrameCompare (in elRef0, in xH0, in nOrbits, in nS, in method)
Compare two methods of computing the relative motion in an eccentric orbit.
function FFEccFrenet2Goals (in e, in nu, in xF, in n)
Compute geometric goals given Frenet frame state and orbit info.
function FFEccGenerateTeamGoals (in el0, in fType, in fSize, in nRels, in teamID, in nu, in eul)
Generate a Team Goals data structure given the formation type and size.
function FFEccGoals (in varargin)
Compute integration constants and initial state given the geometric goals.
function FFEccGoals2Hills (in e, in nu, in g, in n)
Compute Hills frame state (time-domain) given geometric goals and orbit info.
function FFEccH (in nu, in e, in dH)
Compute the H term for the homogeneous solution to LTV diff eqs.
function FFEccHexahedronGeometry (in nu, in d, in eul)
Geometric goals for a hexahedron.
function FFEccHills2DeltaElem (in el0, in xH, in type)
Compute element differences from Hills frame state and ref.
function FFEccHills2Goals (in e, in nu, in xH, in n)
Compute geometric goals given Hills frame state and orbit info.
function FFEccIntConst (in xH0, in nu0, in e)
Integration constants for eccentric relative motion.
function FFEccLawdensEqns (in xH0, in nu0, in nu, in e, in n)
Compute Hills frame state given initial state, true anomaly, and eccentricity.
function FFEccLinOrb (in n, in nu, in e, in dT)
Linearized relative motion in an eccentric reference orbit.
function FFEccProp (in D, in nu, in e, in dH)
Compute Hills frame state at nu given integ.
function FFEccRMat (in nu, in e, in dH)
Compute the state-transition matrix, R, given the eccentricity and true anomaly.
function FFEccShapes (in xH0, in nu0, in e, in method, in n, in animate)
Compute the shape of the relative motion in the orbital plane.
function FFEccTargetTrueAnom (in e, in nu0, in nOrb)
Compute the future true anomaly (unwrapped) at the specified number of orbits.
function FFEccTetrahedronGeometry (in nu, in d, in eul, in centroid)
Goals for tetrahedron geometry in an eccentric orbit.
function FFEccYExt (in e, in D, in dH, in epsilon, in nMax)
Compute extreme y-values and associated true anomalies for given relative motion.
function FFEccZExt (in e, in D, in dH, in epsilon, in nMax)
Compute extreme x-values and associated true anomalies for given relative motion.
function FFIntegrate (in xRef0, in xRel0, in time, in aH)
Integrate two neighboring orbits, with applied relative accelerations.
function FFMaintenancePlotter (in d, in myDirectory)
Plot the results from "FFMaintenanceSim".
function FFMaintenanceSim (in simOptions)
Formation flying maintenance simulation.
function FFMaintenanceTests (in name)
Returns data associated with various test runs for "FFMaintenanceSim".
function FFSim (in simOptions)
Formation flying simulation for circular orbits.
function FFSimPlotter (in d, in myDirectory)
Plot the results from "FFSim".
function FindDriftTerm (in p, in t)
Find the drift rate term given a probability.
function FindMinSet (in mat)
Find the order of columns in a square matrix which minimizes.
function FormationDesignGUI (in action, in modifier)
Formation Design GUI.
function Frenet2Hills (in xF, in e, in nu, in n)
Rotate the Frenet frame state to the Hills frame, where x is radial.
function GenerateTeamGoals (in el0, in fType, in fSize, in nRels, in teamID, in angRes)
Generate a Team Goals data structure given the formation type and size.
function GenerateTimeVector (in d, in tF, in nPts)
Generate a time vector evenly spaced over true anomaly.
function Geometry_Structure (in nU)
Initialize a geometry data structure.
function GeometryCirc2Ecc (in w, in gCirc)
Convert a circular geometry structure to an eccentric geometry structure.
function GeometryEcc2Circ (in w, in gEcc)
Convert an eccentric geometry structure to a circular geometry structure.
function GeometryPlugin (in fig, in pos, in bColor, in name)
Geometry Plugin for the Formation Design GUI.
function GetHillsMats (in r0, in v0, in mu)
Get Hills transformation matrices from ECI state.
function GetLVLHMats (in ro, in vo)
Generate LVLH transformation matrices.
function Goals2DeltaElem (in el0, in goals, in J2)
Computes the desired orbital element differences from goals.
function Goals2Hills (in varargin)
Compute a Hills state from geometric goals.
function Hexahedron (in d, in eul)
Compute the 5 points of a regular tetrahedron, the surface area and volume.
function Hills2DeltaElem (in el0, in xH, in J2)
Computes the Hills orbital element differences.
function Hills2ECI (in x0, in xH, in mu)
Given the reference state in ECI, converts a Hills frame state to ECI.
function Hills2Frenet (in xH, in e, in nu, in n)
Rotate the Hills frame state to the Frenet frame, where x is along-track.
function Hills2Goals (in varargin)
Convert Hills state to geometric goals.
function Hills2LVLH (in xH)
Converts a state vector from the Hills to the LVLH coordinate frame.
function HillsEqns (in Xo, in w, in t, in flag)
Closed form solution of relative orbital motion using Hills equations.
function HillsEqnsSLO (in Xo, in w, in t)
Closed form solution of relative orbital motion using Hills equations.
function HillsFramePlot (in rH, in figH, in color)
Plot the trajectory in Hills frame and show the x-z, x-y projections.
function ImpulsiveLPManeuver (in state, in goals, in window, in parameters)
Computes the delta-v sequence for a relative orbit maneuver.
function ImpulsiveManeuver (in state, in goals, in window, in parameters)
Computes a delta-v sequence for a relative orbit maneuver in a circular orbit.
function InitializeCostMatrix (in teamGoals, in nRelatives)
Given the team goals, initialize the cost matrix "f" with the right size.
function InitializeFormation (in el0, in goals)
Initialize formation orbital states from geometric goals.
function InPlane (in meas_elem, in delta_elem, in accNom, in dTMin, in nOrbMin, in nOrbMax, in horizon)
Computes the delta-v's required for an in-plane maneuver.
function IsCircGeom (in geom)
Check whether the supplied data structure is for circular geometry or not.
function IsDuplicateState (in g0, in g1, in posErrTol, in velErrTol)
Determine whether two geometric goal sets are duplicates or not.
function IsEccGeom (in geom)
Check whether the supplied data structure is for eccentric geometry or not.
function ISLMessage_Structure (in n)
The ISL message data structure format.
function IterativeImpulsiveManeuver (in state, in goals, in window, in parameters)
Iterative impulsive maneuver delta-V.
function JD2SS1970 (in jD)
Converts a Julian Date to seconds since 00:00:00 GMT, Jan.
function Laguerre (in p, in xGuess)
Finds the polynomial roots using Laguerre's method.
function LargeFormationControl (in x0, in d)
Demonstrates control of a large formation of satellites.
function LFState (in d, in nSC, in order)
Leader-follower Hills state.
function LinOrbLQG (in el, in QG, in RG)
Generate an LQG controller for linearized relative orbit dynamics.
function LPCircular (in x0, in xF, in n, in duration, in dT, in constraintType, in maxConstraint)
Computes the thrust trajectory between Hill's states (circular orbit) with Simplex.
function LPCircularTimeWeight (in el0, in xH0, in goals, in window, in nSPO)
Determine the target state on the desired trajectory that gives the minimum time-weighted cost.
function LPEccentric (in e, in n, in x0, in xF, in nu0, in nuF, in nS, in cW, in constraintType, in maxConstraint)
Computes the thrust trajectory between Hill's states (eccentric orbit) with Simplex.
function LPEccentricGVE (in el0, in x0, in xF, in MF, in nS, in cW, in constraintType, in maxConstraint)
Compute trajectory between states as element differences, with Simplex.
function LPEccentricTimeWeight (in el0, in xH0, in goals, in window, in nSPO)
Eccentric trajectory solver for minimum time-weighted cost (Simplex).
function LPvsCF (in el0, in g0, in gF, in nSPO, in nOrbMvr, in nOrbSim)
Compare the delta-v and trajectory for two methods of relative orbit control.
function LVLH2ECI (in x0, in xL)
Given the reference state in ECI, converts an LVLH frame state to ECI.
function LVLH2Hills (in xL)
Converts a state vector from the LVLH to the Hills coordinate frame.
function Lyapunov (in el)
Compute a constant gain feedback controller for relative orbital motion.
function Maneuver_Structure ()
Initialize a maneuver data structure.
function ManeuverStruct2AccelVector (in mvr, in dT)
Compute a 3xN acceleration vector from a "maneuver" data structure.
function Mean2Osc (in el_mean)
Transforms mean orbital elements to osculating orbital elements.
function Mean2OscS (in el_mean)
Transforms mean orbital elements to osculating orbital elements.
function MeanAnom2TrueLat (in e, in w, in M)
Convert mean anomaly to true latitude.
function MinDEllipsoid (in P1, in xc1, in P2, in xc2, in tol)
Computes the minimum distance between two ellipsoids.
function NearestOffset (in y0, in width, in extrema, in minSepDistance, in maxSepDistance)
Determine the nearest along-track offset for a trajectory that is safe.
function NewtRaph2 (in f, in fD, in x, in epsilon, in nMax, in varargin)
Newton Raphson solver.
function NominalSafeGuidance (in inputs, in parameters, in state)
The Nominal Safe Guidance method.
function NOrbVector (in window)
Compute a vector of maneuver durations from time window data.
function Nu2TimeDomain (in x, in n, in e, in nu)
Convert a relative state from the nu-domain to the time-domain.
function NuDot (in n, in e, in nu)
Compute the time-derivative of the true anomaly.
function OptimalAssignment (in N, in P, in Pu, in Q, in f, in phi, in u)
Compute the optimal configuration for a group of objects.
function OptimalInPlaneDeltaV (in nOrbMin, in nOrbMax, in a, in th0, in th1, in delta_a, in delta_th0, in delta_q1, in delta_q2, in analyze)
Computes the delta-v's and half-orbit delays for an in-plane maneuver.
function OrbitDataPlugin (in fig, in pos, in bColor)
Orbit Data Plugin for the Formation Design GUI.
function Orientation_Structure ()
Initialize an orientation command data structure.
function Osc2Mean (in el_osc, in J2)
Transforms osculating orbital elements to mean orbital elements.
function OutOfPlane (in meas_elem, in delta_elem, in accNom, in dTMin)
Computes the delta-v's required for an out-of-plane maneuver.
function PCGoals (in R, in alpha0, in sgn, in y0)
Generate the geometric goals for a cluster in a projected circular formation.
function PCState (in d, in w0, in phi, in M, in t)
Projected circle state in Hills frame.
function PlanningParameters_Structure ()
Initialize a planning parameters data structure.
function Plot3DEllipsoids (in xhat, in Shat, in nPlot)
Plot collision ellipsoids in 3D.
function PlotRun3D (in xSet, in dVSet, in iSet, in index, in d1, in d2)
Generate a 3D plot of a relative trajectory.
function PopulateCostMatrix (in f, in costEstimate, in teamGoals, in relativeIDs)
Fill in a single column of the cost matrix.
function PositionDeltaV (in r0, in v0, in rDes, in n, in t)
Compute delta-v required to reach a target position, given pos.
function PredictCollision (in d, in jD, in y)
Predict collisions given a new state measurement.
function PrivilegedAssignment (in N, in P, in Pu, in Q, in f, in phi, in u, in method)
Assign target states to satellites using the privileged assignment method.
function ProjCirc (in aRef, in iRef, in kSats, in rF, in type)
Calculates orbital elements for projected circular formation.
function ProjLine (in aRef, in iRef, in kSats, in rF)
Calculates orbital elements for an in-line formation.
function QHillsToBody (in r, in v, in qEB)
Compute the Hills-to-Body quaternion.
function RadialOscillation (in zo, in xoDot, in zoDot, in n)
Compute the radial oscillation of the relative motion using Hills eqns.
function RE2Hills (in x, in y, in y0, in aE, in zA, in zR, in n)
Compute the Hills-frame state associated with a relative ellipse.
function RE2SLO (in x, in z, in x0, in aE, in yA, in yR, in n)
Compute the SLO-frame state associated with a relative ellipse.
function RelativeDisturb (in jD, in r, in v, in dr, in dA, in mSC, in Cd, in Cr, in iRef)
Relative disturbances for use with a relative state.
function RelativeOrbitRHS (in x, in ignoredArg, in w, in u)
Continuous-time linear model of Hills equations in the Hills frame.
function RelativeStatePlugin (in fig, in pos, in bColor, in name)
Relative State Plugin for the Formation Design GUI.
function RelativeVelocityError (in alt, in D, in t, in p, in sigma_x, in rho_xydot, in body)
Compute max.
function RestrictDeltaV (in dVSLO, in xSLO, in n, in dMin, in x0, in aE, in radVelTol, in iPTol, in dPOTol)
Restrict the in-plane and cross-track components of the delta-v.
function RestrictIDSet (in relIDs, in constraints)
Given an initial set of relative spacecraft IDs, examine the constraints.
function RotateState (in g, in phi)
Rotate a geometric state to the circular phase angle phi.
function RVOrbGenDV (in el, in t, in dV, in dVTime)
Generate an orbit by propagating Keplerian elements with impulsive delta-vs.
function SafeEllipseParams (in rSLO, in vSLO, in n)
Compute the "safe ellipse" parameters from relative SLO-frame pos & vel.
function SafeEllipsePosVel (in x0, in aE, in yA, in yR, in alpha, in n)
Compute the relative SLO-frame position and velocity that corresponds to.
function SafeGuidance (in inputs, in parameters, in state)
The Safe Guidance Mode.
function SafeGuidanceBurnData (in dV, in inside)
Find index values for separation, nominal and cross-track burns.
function SafeGuidanceParameters ()
Tunable parameters for Safe Guidance and Collison Detection algorithms.
function SafeGuidanceSim (in simOptions)
Relative dynamic simulation for two LEO satellites with safe guidance.
function SafeGuidanceSimInit (in name)
Returns input data for various test cases for SafeGuidanceSim.
function SafeGuidanceSimPlots (in d)
Plot select results from a simulation.
function SatellitePlugin (in fig, in pos, in bColor, in name)
Satellite Plugin for the Formation Design GUI.
function ScaleState (in g, in s)
Scale a relative state represented by a geometric goal set.
function SeparationGuidance (in parameters, in state)
The Separation Guidance method.
function SetupAssignmentProblem (in teamGoals, in orbFrac)
Set up the parameters for the assignment problem given the team goals struct.
function ShortArcToHills (in p, in t, in n, in qHToBody, in e, in xECI)
Convert short arc measurements to an approximate Hill's state.
function ShowTeams (in teams, in fig)
Graphically show the hierarchy of teams.
function SortTeamGoals (in teamGoals)
Sort the team goals with fixed states listed before variable states.
function SS19702JD (in s)
Converts seconds since 00:00:00 GMT, Jan.
function State_Structure ()
Initialize a state data structure.
function SubGoals (in e, in nu, in gA, in gB, in n)
Subtract one set of geometric goals from the other.
function Team_Structure (in n)
Initialize a team data structure.
function TeamGoals2Geom (in teamGoals, in offset)
Extract the geometry data from the team goals data structure.
function TeamGoals_Structure (in nU)
Initialize a team goals data structure.
function TeamLevels (in teams)
Assign a hierarchical level to each team in the array.
function TeamPlugin (in fig, in pos, in bColor, in name)
Team Plugin for the Formation Design GUI.
function TestFFEccLinOrb (in x0, in xH0, in dT, in aH)
Test the FFEccLinOrb function.
function TestLPCircular (in el0, in xH0, in xHF, in dur, in nS, in plotFlag)
Test the LPEccentric function.
function TestLPEccentric (in el0, in xH0, in nu0, in xHF, in nuF, in nS, in plotFlag)
Test the LPEccentric function.
function TestLPEccentricGVE (in el0, in xH0, in nu0, in xHF, in nuF, in nS, in plotFlag)
Test the LPEccentricGVE function.
function Tetrahedron (in d, in eul, in centroid)
Compute the 4 points of a regular tetrahedron, the surface area and volume.
function ThrusterAlignment (in r, in v, in aH, in bHET, in bST, in jD, in sep, in constrain, in analyze)
Computes body vectors to align with velocity and nadir for a thruster firing.
function Time2NuDomain (in x, in n, in e, in nu)
Convert a relative state from the time-domain to the nu-domain.
function TimeUntilTheta (in a, in w, in e, in theta0, in theta1, in mu)
Computes the time in seconds until the latitude "theta2" is reached from the.
function TransformGeom2Hills (in el, in g, in ignoredArg)
Transform geometric goals to Hills-frame coordinates.
function VerifyCollStruct (in d0)
Update computed fields in the collision data structure fields.
function ViewEllipsoid (in xhat, in Shat, in dMin)
Plot collision monitoring ellipsoids.
function ViewFormation (in el0, in g, in h, in color)
View the 3-D trajectory of a formation in Hills frame.
function ViewGeometry (in g, in angle, in e)
View the geometry created by a formation of spacecraft.
function ViewHills (in el0, in el, in timeSpan, in method)
Animation the relative motion in Hills frame.
function ViewRelativeMotion (in el0, in goals, in nOrbits)
View the relative motion for geometric goals (eccentric or circular)
function ViewRotatingHillsFrame (in rECI, in vECI, in rHills)
Animate a satellite's relative trajectory in the inertial frame.
function Window_Structure ()
Initialize a window data structure.
function WorstCasePerturbations (in h, in dR, in mSC, in Cd, in Cr)
Worst-case differential accelerations for spacecraft in formation.
function YRMax (in yA, in aE, in minDist)
Compute the maximum value of yR.
Function Documentation
AbsRelECI2Hills()
function AbsRelECI2Hills (in r0, in v0, in dr, in dv)
This function takes the absolute position and velocity in the ECI frame along with the relative position and velocity in the ECI frame, and computes the relative position and velocity in the curvilinear Hill's frame.
Form
 [rH,vH] = AbsRelECI2Hills( r0, v0, dr, dv );
Inputs
 r0              (3,1) Reference position in ECI frame
 r0              (3,1) Reference velocity in ECI frame
 dr              (3,n) Relative position in ECI frame
 dv              (3,n) Relative velocity in ECI frame
Outputs
 rH              (3,n) Curvilinear Hills frame position [dR;    r1*dTheta;                   dZ   ]
 vH              (3,n) Curvilinear Hills frame velocity [dRDot; r1*dThetaDot + r1Dot*dTheta; dZDot]
References and().
Referenced by FFSim().
AccelVector2ManeuverStruct()
function AccelVector2ManeuverStruct (in aC, in t, in tRef, in nomAccel, in minSepTime)
 Since version 7.
 Usage:
 [maneuver,dV,dT] = AccelVector2ManeuverStruct( aC, t, tRef, nomAccel, minSepTime );
Inputs
 aC           (3,N)     [x;y;z] acceleration over N time intervals            [km/sec^2]
 t            (1,N)     Time vector                                           [sec]
 tRef          (.)      Reference time (epoch)                                [sec]
 nomAccel      (1)      Magnitude of thruster's nominal acceleration output   [km/sec^2]
 minSepTime    (1)      Minimum allowable separation time between burns       [sec]
Outputs
 maneuver      (.)      Maneuver data structure
 dV           (1,k)     Absolute value of all non-zero delta-v's              [km/sec^2]
 dT           (1,N-1)   Vector of time-steps                                  [sec]
References abs(), and(), close(), isempty(), length(), Mag(), Maneuver_Structure(), Unit(), vector(), and zeros().
AddGoals()
function AddGoals (in e, in nu, in gA, in gBA, in n)
Given the geometry of A and the geometry of B with respect to A, compute the geometry of B.
Form
 gB = AddGoals( e, nu, gA, gBA, n );
Inputs
 e                (1)      Eccentricity
 nu               (1)      True anomaly   [rad]
 gA               (.)      Geometric goals of A
 gBA              (.)      Geometric goals of B with respect to A
 n                (1)      Mean orbit rate
Outputs
 gB               (.)      Geometric goals of B
                              gB = gA + gBA
References and(), FFEccGoals2Hills(), FFEccHills2Goals(), Goals2Hills(), Hills2Goals(), IsCircGeom(), IsEccGeom(), isempty(), and set().
AlignThruster()
function AlignThruster (in aH, in bTh, in bST, in r, in v, in jD, in sep, in verify)
If called with just the first 2 inputs, the quaternion is computed without regard to the rotation about the thruster axis.
If called with all inputs, the quaternion is computed such that the star tracker is pointed as far away as possible from the sun, earth and moon.
Form
 [qHB,okay] = AlignThruster( r, v, aH, bTh, bST, jD, sep, verify )
Inputs
 aH              (3,1)  Unit Hills frame vector of applied acceleration
 bTh             (3,1)  Unit body vector of Hall Effect Thruster nozzle
 bST             (3,1)  Unit body vector of star tracker bore-sight
 r               (3,1)  Position in ECI at burn time  [km]
 v               (3,1)  Velocity in ECI at burn time  [km/s]
 jD               (1)   Julian Date of burn time      [JD]
 sep              (1)   Required angular separation between bore-sight and
                         bright body horizon          [rad]
Outputs
 qHB             (4,1)  Desired ECI-to-body quaternion
 okay             (1)   Boolean flag indicating whether angular separation
                         constraints were satisfield
References AlignThruster(), and(), AnimQ(), AU2Q(), close(), Demo(), Dot(), Initialize(), JD2000(), Mag(), MoonV1(), QForm(), QHills(), QMult(), QPose(), quaternion(), SunV1(), U2Q(), Unit(), and vector().
Referenced by AlignThruster().
AlongTrackMotion()
function AlongTrackMotion (in xSLO, in n, in varargin)
Form
 [offset,drift,amp] = AlongTrackMotion(xSLO,n,varargin)
Inputs
 xSLO      (6,1)   Relative position and velocity vector
 n         (1,1)   Mean orbit rate (rad/s)
 makePlot  (1,1)   Flag to make a plot of results
Outputs
 offset    (1,1)   Along-track offset
 drift     (1,1)   Along-track drift rate
 amp       (1,1)   Amplitude of along-track oscillation
References AlongTrackMotion(), and(), HillsEqnsSLO(), Plot2D(), and vector().
Referenced by AlongTrackMotion(), and SeparationGuidance().
AnalyzeVariableTimeDV()
function AnalyzeVariableTimeDV (in dV1, in dV2, in dV3, in M, in N)
Plot the behavior of the first and third delta-v in a 3-burn sequence as the number of half-orbits allowed between burns is varied.
 Since version 7.
 Usage:
 AnalyzeVariableTimeDV( dV1, dV2, dV3, M, N );
Inputs
 dV1                   (P,P)   Square matrix first delta-v values     [kN]
 dV2                    (1)    Second delta-v                         [kN]
 dV3                   (P,P)   Square matrix third delta-v values     [kN]
 M                     (1,P)   Array of number of half-orbits between burn 1 and burn 2
 N                     (1,P)   Array of number of half-orbits between burn 1 and burn 3
Outputs
 none
References AnalyzeVariableTimeDV(), and(), Goals2DeltaElem(), OptimalInPlaneDeltaV(), and Square().
Referenced by AnalyzeVariableTimeDV().
AnimateRE()
function AnimateRE (in r, in x0, in aE, in yA, in yR, in dMin, in dV)
Form
 [x0,aE,yA,yR,alpha] = AnimateRE( r,x0,aE,yA,yR, dMin );
Inputs
 r            (3,N)  Relative position in SLO frame
 x0           (1,N)  Center of along-track motion
 aE           (1,N)  Semi-major axis of relative ellipse
 yA           (1,N)  Cross-track offset at along-track axis crossing
 yR           (1,N)  Cross-track offset at radial axis crossing
 dMin          (1)   Minimum distance parameter (optional)
 dV           (1,N)  Delta-V to move to safe ellipse. Optional.
Outputs
 NONE
References AddView(), Cross(), and zeros().
AutoFormGeometry()
function AutoFormGeometry (in state, in memberGoals, in minSepDist, in maxSepDist, in nS)
Define new geometric goals for a single satellite, such that any semi-major axis difference is eliminated, and the new trajectory maintains a minimum separation distance from all other team members trajectories in the team.
Command ONLY along-track offset, set radial oscillation to 0, and leave out-of-plane motion unchanged.
For each OTHER member, compute the extreme y-values, and determine the closest y0 whose extrema are at least minSepDist from all OTHER extrema
 Usage:
 newGoals = AutoFormGeometry( state, memberGoals, minSepDist, maxSepDist, nS, maxIter );
Inputs
 state         (.)   Orbital state data structure
 memberGoals   (.)   Geometric goals for all other members in the cluster
 minSepDist    (1)   Minimum allowable separation distance between satellites
 minSepDist    (1)   Maximum allowable separation distance between satellites
 nS            (1)   Number of samples to use in computing 1-period trajectories
Outputs
 newGoals      (.)   Goals data structure defining desired relative motion for team
References abs(), and(), AutoFormGeometry(), DeltaElem2Goals(), Demo(), El2Alfriend(), FFEccDeltaElem2Goals(), FFEccDeltaElem2Hills(), FFEccGoals(), FFEccGoals2Hills(), FFEccHills2DeltaElem(), FFEccLawdensEqns(), FFEccYExt(), Goals2Hills(), HillsEqns(), IsCircGeom(), isempty(), length(), M2Nu(), NearestOffset(), OrbRate(), Period(), set(), UnwrapPhase(), and zeros().
Referenced by AutoFormGeometry().
BurnData_Structure()
function BurnData_Structure ()
 Since version 7.
Form
 burnData = BurnData_Structure;
Inputs
 none
Outputs
 burnData         (.) Burn data structure with fields:
                        - t
                        - dT
                        - dV
                        - uX
                        - uY
                        - uZ
                        - iD
References BurnData_Structure(), and Initialize().
Referenced by BurnData_Structure(), and Maneuver_Structure().
CheckDeltaVs()
function CheckDeltaVs (in state, in maneuver, in iD, in nSPO, in plotFlag)
Given the current state & the maneuver planned using this state, plot the trajectory throughout the maneuver and for an orbit after the final burn.
Form
 [dElFinal,xHFinal] = CheckDeltaVs( state, maneuver, iD, nSPO, plotFlag );
Inputs
 state            (.)   State data structure at time of maneuver planning
 maneuver         (.)   Maneuver data structure, computed using IterativeImpulsiveManeuver
 iD               (1)   Spacecraft ID to distinguish plots
                           (optional, default is 1)
 nSPO             (1)   Number of simulation points per orbit
                           (optional, default is 250)
 plotFlag         (1)   Flag -- create plots (1) or not (0)
                           (optional, default is 1)
Outputs
 dElFinal        (:,6)   Orbital element differences
 xHFinal         (6,:)   Hills frame position and velocity
References and(), CheckDeltaVs(), El2Alfriend(), FFEccLawdensEqns(), Hills2DeltaElem(), HillsEqns(), IterativeImpulsiveManeuver(), length(), M2Nu(), NewFig(), Nu2M(), OrbRate(), Period(), RV2El(), RVOrbGen(), set(), UnwrapPhase(), and zeros().
Referenced by CheckDeltaVs().
CirclePhase()
function CirclePhase (in beta0)
Compute the angle on a circle with radius aE that has a projected x-component equal to that of the relative ellipse:
 aE*sin(alpha0) = r*sin(beta0)
Form
 alpha0 = CirclePhase( beta0 );
Inputs
 beta0            (1)      desired phase angle at equator crossing   [rad]
Outputs
 alpha0           (1)     phase angle on circle such that
                             the y-component of the circle
                             is equal to that of the ellipse        [rad]
References length(), and WrapPhase().
Referenced by GenerateTeamGoals(), GeometryCirc2Ecc(), IsDuplicateState(), RotateState(), SetupAssignmentProblem(), and ViewFormation().
CoarseProb()
function CoarseProb (in rRel, in rAvoid, in sigma)
Coarse probability estimate consisting of the integral outbound of the tangent between a circular avoidance region and the target's position probability density.
Form
 Pc = CoarseProb( dR, rAvoid, sigmaU)
 Inputs:
 rRel    (1,1) or (2,1)  Magnitude of or actual relative position vector between centers
 in the conjunction plane, where [x z] are along the major and
 minor axes of the density envelope.
 rAvoid        (1)       Radius of avoidance region
 sigma   (1,1) or (2,2)  One-sigma target probability along the relative position vector
 or full one-sigma probability ellipse in the conjunction plane
 Outputs:
 Pc           (1,1)      Coarse probability
 k            (1,1)      Incidence index
Reference: J. Russell Carpenter, 'Conservative Analytical Collision Probability for Design of Orbital Formations', 2004
References and(), and CoarseProb().
Referenced by CoarseProb().
CollisionInit()
function CollisionInit (in caseID)
See ImpulsiveManeuver for the maneuver structure. Loads SampleMvr.mat if it exists.
Form
 [d, y, mvr1, mvr2] = CollisionInit( caseID )
 Inputs:
 caseID   (1,1)  Integer for case from switch statement.
 Only a low-eccentricity case is implemented (1).
 Outputs:
 d       (.)    Algorithm data structure
 .hRef          Altitude of the reference orbit      [km]
 .eRef          Eccentricity
 .MRef          Mean anomaly                        [rad]
 .rate          Orbit rate                        [rad/s]
 .el0           Reference orbital elements (1,6)
 .dR            Reference length of Hill's orbit     [km]
 .initBounds    Error in measurement (1,6)
 .scalev        Sigma for scaling measurement noise
 .mSC           Spacecraft mass                      [kg]
 .lenSC         Spacecraft length                     [m]
 .diaSC         Spacecraft diameter                   [m]
 .Cd            Drag coefficient
 .Cr            Reflectivity of s/c: 0.0 for translucent;
 1.0 for black-body; 2.0 for flat mirror
 .Pmin
 .Ssc
 .S0
 y      (6,n)   Relative states
 mvr1    (:)    Maneuvers of self spacecraft (currently empty)
 mvr2    (n)    Maneuvers of relative spacecraft
See also
ImpulsiveManeuver
References Altitude(), El2Alfriend(), ImpulsiveManeuver(), InitializeFormation(), length(), OrbRate(), PCGoals(), and VerifyCollStruct().
Referenced by CollisionSurvey().
CollisionMonAlg()
function CollisionMonAlg (in y, in t, in M, in nu, in accel, in aDiff, in d)
Discretizes orbit according to input time and anomaly vectors. Handles high eccentricity and maneuvers input through acceleration vector.
Form
 [prob, dMin, Shat, xhat] = CollisionMonAlg( y, t, M, nu, accel, aDiff, d )
Inputs
 y      (6,m)   Relative state(s)
 t      (1,n)   Time vector [s]
 M      (1,n)   Mean anomaly vector
 nu     (1,n)   True anomaly vector
 accel   {m}    Accelerations due to maneuvers
 aDiff  (3,m)   Differential accelerations
 d       (.)    Algorithm data structure
                .el0           Initial elements
                .eRef          Eccentricity
                .MRef          Mean anomaly
                .initBounds    Error in measurement (6,1) [km, km/s]
                .scalev        Sigma for measurement noise
                .lenSC         Spacecraft length [m]
                .Pmin          Probability of scalev
                .Ssc           Spacecraft hard-body sphere
                .S0            Initial ellipsoid
Outputs
 prob   {n}(1,:)     probability of collision
 d      {n}(1,:)     minimum distance between spacecraft position ellipsoids
 xhat   {n}(6,:)     xhat, ellipsoid centers
 Shat   {n}(6,6,:)   Shat, ellipsoid size matrices
Reference: Mark Campbell, Collision Monitoring Within Satellite Clusters. IEEE Transactions on Control Systems Technology, Jan. 2005
References and(), and vector().
Referenced by CollisionMonteCarlo(), CollisionSurvey(), and PredictCollision().
CollisionMonitor()
function CollisionMonitor (in action, in d, in jD, in y)
Checks the ellipsoids for self and a neighboring spacecraft. Self "position measurement" should be [0;0;0;0;0;0] at each time if relative measurements are used. Includes options for continuous and discrete ellipsoid propagation for circular and low-eccentricity reference orbits. All propagation is performed in Hill's frame. Assumes that no maneuvers are taking place.
Form
 [prob, d, xhat, Shat] = CollisionMonitor( action, d, jD, y );
Inputs
 action  (:)    'initialize' or 'run'
 d        :     Data structure
                .hRef          Altitude of the reference orbit (km)
                .eRef          Eccentricity
                .dR            Reference length of Hill's orbit (km)
                .initBounds    Error in measurement
                .nSC           Number of S/C
                .predictTime   Total amount of time to predict for
                .nSampleTimes  Number of points in predictTime
                .scalev        Sigma for measurement noise
                .discrete      Flag for method type
                .mSC           Spacecraft mass (kg)
                .lenSC         Spacecraft length (m)
                .diaSC         Spacecraft diameter (m)
                .Cd            Drag coefficient
                .Cr            Reflectivity of s/c: 0.0 for translucent;
                                 1.0 for black-body; 2.0 for flat mirror
 jD      (1)    Epoch in Julian date
 y       (6,:)  spacecraft current position in Hill's frame
Outputs
 prob   (n)         probability of collision
 d      (n)         minimum distance between spacecraft position ellipsoids
 xhat   (6,n,2)     xhat, ellipsoid centers, for both spacecraft
 Shat   (6,6,n,2)   Shat, ellipsoid size matrices, for both spacecraft
References and(), CollProbSet(), Constant(), DistantPtToEll(), EllipsePropCirc(), FFEccLinOrb(), Gamma(), isempty(), JD2000(), length(), M2Nu(), Mag(), MinDEllipsoid(), OrbRate(), Period(), set(), vector(), WorstCasePerturbations(), and zeros().
Referenced by CollisionDemoSimStruct().
CollisionMonteCarlo()
function CollisionMonteCarlo (in d, in y0, in aC, in t, in M)
 Perform a Monte-Carlo analysis of a relative orbit dynamics simulation
 by applying random noise to the initial conditions.
 Any collisions, defines as separations within the physical dimenstion of
 the spacecraft, are counted and used to create a "true" probability.
Form
 [prob,dMin,tMin,drH] = CollisionMonteCarlo( d, y0, aC, t, M )
Inputs
 d       (:)      Data structure, see CollisionMonAlg
 y0     (6,1)     Initial relative state                       [km, km/s]
 aC     (3,N)     [x;y;z] acceleration over N time intervals   [km/sec^2]
 t      (1,:)     Propagated time vector
 M      (1,:)     Osculating mean anomaly
Outputs
References and(), C2DZOH(), CollisionMonAlg(), DeltaEl2Alfriend(), Difference(), El2Alfriend(), FFEccLinOrb(), Gamma(), GVEDynamics(), length(), M2Nu(), Mag(), Plot2D(), UnwrapPhase(), vector(), WrapPhase(), and zeros().
CollisionSurvey()
function CollisionSurvey (in d, in t0, in y, in mvr1, in mvr2)
The "self" spacecraft is at the origin. Calls CollisionMonAlg. If there are no inputs it will run a demo using CollisionInit() and SampleMvr.mat.
Form
 CollisionSurvey;   % demo
 [prob, d, xhat, Shat, tProp] = CollisionSurvey( d, t0, y, mvr1, mvr2 );
Inputs
 d        :     Algorithm data structure (see CollisionMonAlg)
 t0      (1)    Start time
 y       (6,n)  Spacecraft relative state in Hill's frame (km, km/s)
 mvr1    (1)    Maneuvers scheduled for self
 mvr2    (n)    Maneuver(s) scheduled for relative spacecraft
                .iD
                .achieve
                .nBurns
                .burnData (struct)
                .t0        [s]
                .tF        [s]
Outputs
 prob   {n}(1,:)     probability of collision
 d      {n}(1,:)     minimum distance between spacecraft position ellipsoids
 xhat   {n}(6,:)     xhat, ellipsoid centers
 Shat   {n}(6,6,:)   Shat, ellipsoid size matrices
 tProp     (1,:)     Propagated time vector
See also
CollisionInit, VerifyCollStruct, GenerateTimeVector,
ManeuverStruct2AccelVector
References and(), CollisionInit(), CollisionMonAlg(), and CollisionSurvey().
Referenced by CollisionSurvey().
CollProbSet()
function CollProbSet (in P0, in S1, in xc1, in S2, in xc2, in Ssc, in n)
For a single ellipsoid relative to the origin, pass in empty matrices for the second set of inputs. The inputs should have consistent units, i.e. either m or km.
Form
 [P] = CollProbSet( P0,S1,xc1,S2,xc2,Ssc, n )
 [P] = CollProbSet( P0,S1,xc1,[],[] ,Ssc, n )
 Inputs:
 P0          (1)   Ellipsoid probability level, i.e. 1 for one sigma
 S1, S2     (3,3)  Ellipsoid definitions
 xc1, xc2   (3,1)  Centers of ellipsoids
 Ssc        (3,3)  Definition of hard-body spacecraft (spherical)
 n           (1)   Number of scaled ellipses to use
 Outputs:
 P          (1)    Probability of collision
Reference: Mark Campbell, Collision Monitoring Within Satellite Clusters, 2004.
References and(), CollProbSet(), Ellipsoid(), isempty(), Mag(), NewFig(), set(), Unit(), Watermark(), and zeros().
Referenced by CollisionMonitor(), and CollProbSet().
CollProbVol()
function CollProbVol (in P1, in xc1, in P2, in xc2, in volSC)
Form
 [P] = CollProbVol( P1,xc1,P2,xc2,volSC )
 Inputs:
 P1, P2     (3,3)  Ellipsoid definitions
 xc1, xc2   (3,1)  Centers of ellipsoids (m)
 volSC      (1)    Volume of object in question
 Outputs:
 P          (1)    Probability of collision
References and(), CollProbVol(), Ellipsoid(), NewFig(), set(), and Watermark().
Referenced by CollProbVol().
Command_Structure()
function Command_Structure (in n)
 Since version 7.
Form
 cmd = Command_Structure( n );
Inputs
 n            (1)    Number of command structures to generate
Outputs
 cmd          (.)    Command data structure with fields:
                        - timeTag
                        - scID
                        - module
                        - command
                        - data
Referenced by AutoDualPCCommandList(), AutoFormCommandList(), ClusterGoalsDemoCommandList(), CollisionDemoCommandList(), CollisionDetectCommandList(), DefaultCommandList(), DemoManeuverCommandList(), EccentricTetrahedronCommandList(), MainDemoCommandList(), ProjCircCommandList(), SimpleManeuverCommandList(), TeamManagementCommandList(), TestADCSCommandList(), TestControlCommandList(), TestMonitoringCommandList(), and TestTeamMgtCommandList().
CompareHills()
function CompareHills (in elRef, in xH0, in nOrbits, in dT)
We have two spacecraft flying in close proximity. Their relative motion may be expressed in the Hill's frame or the LVLH frame. Each is a rotating coordinate system centered on the reference spacecraft. This function takes an initial relative state and computes their future relative trajectories using a variety of different methods. These methods are described below:
ABSOLUTE PROPAGATION ... then TRANSFORMATION
The two orbital element sets of [a i W w e M] are propogated over time using 3 different methods:
The resulting r & v ECI coordinates of the absolute orbits are then transformed to the Hills frame for comparison.
TRANSFORMATION ... then RELATIVE PROPAGATION
We first convert the initial orbital elements to absolute position and velocity in the ECI frame. We then transform the 2 absolute states to a relative state in the Hills frame. The relative position/ velocity over time is solved using 2 different methods:
The table below outlines the different methods used:
 Propagation Frame       Model                   Line Color
 ==========================================================
 Absolute          Keplerian                     Blue
 Absolute          Inverse Square Law            Green
 Absolute          Gravity Model with J2         Cyan
 Relative          Discretized state space       Red
 Relative          Hills Equations               Maroon
 Since version 7.
Usage:
[t, xAbsKepler, xAbsLoFi, xAbsHiFi, xRelDiscProp, xRelHills] = TestHillsEqns(elRef, xH0, nOrbits);
Inputs
 elRef          (1,6)   Initial reference orbit elements [a i W w e M]
 xH0            (6,1)   Initial Hill's frame state [x;y;z; Vx;Vy;Vz]
 nOrbits         (1)    Number of orbits to simulate
Outputs
 t              (1,:)   Time vector [sec]
 --- the following outputs are relative state time histories ---
 --- each state is computed in a different manner ---
 xAbsKepler     (6,:)   Orbits generated by propagating Keplerian elements
 xAbsLoFi       (6,:)   Lo-Fideltiy propagation of absolute orbits (simple inverse square law)
 xAbsHiFi       (6,:)   Hi-Fidelity propagation of absolute orbits (2 zonal and 2 tesseral harmonics)
 xRelDiscProp   (6,:)   Propagation of discretized linear equations of relative motion
 xRelHills      (6,:)   Relative motion computed using closed-form Hills equations
References and(), close(), DiscreteHills(), ECI2Hills(), FOrb(), FOrbHF(), Hills2ECI(), HillsEqns(), JD2000(), length(), LoadGravityModel(), OrbRate(), PCState(), RK4(), RV2El(), RVOrbGen(), set(), square(), vector(), and zeros().
ComputeRE()
function ComputeRE (in x, in z, in vz, in n, in aEMin, in dMin, in verbose)
The ellipse is chosen such that:
it can be reached with a single, immediate delta-v
it does not intersect with a 2x1 elliptical avoidance region
its semi-major axis is greater than the defined minimum value
it requires the lowest delta-v to meet the above constraints
NOTE: This algorithm assumes that the current relative position is ALREADY OUTISDE THE AVOIDANCE REGION.
Form
 [x0,aE] = ComputeRE( x, z, vz, n, aEMin, dMin, verbose );
Inputs
 x             (1)   Along-track position [km]
 z             (1)   Radial position      [km]
 vz            (1)   Radial velocity      [km/s]
 n             (1)   Mean orbit rate      [rad/s]
 aEMin         (1)   Minimum semi-major axis for relative ellipse [km]
 dMin          (1)   Minimum along-track separation distance      [km/s]
 verbose       (1)   Flag. Print results during execution?
Outputs
 x0            (1)   Center of along-track motion           [km]
 aE            (1)   Semi-major axis of relative ellipse    [km]
References abs(), and ComputeRE().
Referenced by ComputeRE(), and NominalSafeGuidance().
ConjunctionPlane()
function ConjunctionPlane (in xRel)
The inertial relative state is defined by:
 rRel = R2 - R1
 vRel = V2 - V1 - omega1 x rRel
Form
 C = ConjunctionPlane( xRel )
 Inputs:
 xRel  (6,1)  Relative state
 Outputs:
 C     (3,3)  Conjunction plane transformation
Reference: J. Russell Carpenter, 'Conservative Analytical Collision Probability for Design of Orbital Formations', 2004
References Cross(), and Mag().
Constraints_Structure()
function Constraints_Structure (in nU)
 Since version 7.
Form
 c = Constraints_Structure( nU );
Inputs
 nU           (1)    Number of unique states = # of structures to generate
Outputs
 c            (.)    Constraints data structure with fields:
                        - variable
                        - nRestrict
                        - restrictID
                        - nDuplicates
                        - phase
References Initialize(), length(), and set().
Referenced by EccTeamGoals_Structure(), GenerateTeamGoals(), and TeamGoals_Structure().
CostEstimate_Structure()
function CostEstimate_Structure (in nU)
 Since version 7.
Form
 cE = CostEstimate_Structure( nU );
Inputs
 nU            (1)    Number of cost estimate structures = # of unique states
Outputs
 cE            (.)    Cost estimate data structure with fields:
                        - nU
                        - memID
                        - targetIndex
                        - costLength
                        - cost
References Initialize(), length(), set(), vector(), and zeros().
Referenced by PopulateCostMatrix().
CostMatrixRows()
function CostMatrixRows (in teamGoals, in index)
 of the cost matrix associated with the supplied target state index.
 Since version 7.
Form
 [a,b] = CostMatrixRows( teamGoals, index );
Inputs
 teamGoals     (.)    Team data structure with fields:
 index         (1)    Target state index
Outputs
 a             (1)    Starting row of the cost matrix
 b             (1)    Ending row of the cost matrix
References and(), CostMatrixRows(), Demo(), and TeamGoals_Structure().
Referenced by CostMatrixRows(), and PopulateCostMatrix().
CostVis()
function CostVis (in r, in cost)
 Since version 7.
 Usage:
 CostVis( r, cost )
Inputs
 r            (3,N)  3D state vector over N time steps
 cost         (1,N)  Cost over N time steps
Outputs
 none
References length(), and vector().
Referenced by LPCircularTimeWeight(), and LPEccentricTimeWeight().
CrossTrackDeltaV()
function CrossTrackDeltaV (in xSLO, in x0, in aE, in n, in dMin, in yAMin, in timeLimited)
cross-track dist. at along-track crossing.
This is used to achieve a "safe ellipse". If the ellipse drifts in the along-track direction, it will not collide with the origin (another SC) because it will have some cross-track offset as it crosses the along-track axis.
NOTE: This algorithm assumes that the current relative state is ALREADY FOLLOWING A RELATIVE ELLIPSE in the orbital plane.
Form
 [dV,dVt,yA,yR] = CrossTrackDeltaV( xSLO, x0, aE, n, dMin, yAMin, timeLimited )
Inputs
 xSLO          (1)   Initial SLO-frame state on relative ellipse
 x0            (1)   Center of along-track motion [km]
 aE            (1)   Semi-major axis of relative ellipse [km]
 n             (1)   Mean orbit rate [rad/s]
 dMin          (1)   Minimum separation distance (along-track) [km]
 yAMin         (1)   Minimum separation distance (cross-track) [km]
 timeLimited   (1)   Flag. Must the maneuver be applied right now?
Outputs
 dV            (1)   Cross-track delta-v [km/s]
 dVt           (1)   Time to apply delta-v, measured from xSLO time [MET]
 yA            (1)   Cross-track offset at forward along-track axis crossing
 yR            (1)   Cross-track offset at high radial axis crossing
References abs(), and(), Cross(), and YRMax().
Referenced by NominalSafeGuidance().
DataSize()
function DataSize (in data, in runningSize)
 Doubles are assigned 8 bytes.
 Integers are assigned 4 bytes.
 Characters are assigned 4 bytes.
 A number is treated as an integer only if it is a whole number. In the case
 of numeric arrays, the following rules are applied. These rules are
 consistent with the C++ matrix library.
 * For 2-D arrays, all elements are considered to be doubles.
 * For 1-D arrays, if any element is not a whole number, then all of
 the elements are treated as doubles.
 Since version 7.
Form
 ds = DataSize( data, runningSize )
Inputs
 data             (.)      A piece of data. The following types are supported:
                              - single numbers and numeric arrays (up to 2-D)
                              - single characters and character arrays (up to 2-D)
                              - single structures and structure arrays (up to 2-D)
                              - single cells and cell arrays (up to 2-D )
 runningSize      (1)      The size of data already computed. Used for
 recursive implementation of this function.
Outputs
 ds               (1)      Size of the supplied data, in bytes
References and(), and DataSize().
Referenced by DataSize().
DeltaAlfriend2El()
function DeltaAlfriend2El (in e, in w, in M, in dElA)
 Since version 7.
 Usage:
 [dEl,T] = DeltaEl2Alfriend( e, w, M, dElA );
Inputs
 e           (1)  Eccentricity
 w           (1)  Argument of perigee [rad]
 M           (1)  Mean anomaly [rad]
 dElA       (1,6) Orbital element differences [a,th,i,q1,q2,W]
Outputs
 dEl        (1,6) Orbital element differences [a,i,W,w,e,M]
 T          (6,6) Transformation matrix
References M2Nu(), UnwrapPhase(), and zeros().
DeltaEl2Alfriend()
function DeltaEl2Alfriend (in e, in w, in M, in dEl)
 Since version 7.
 Usage:
 [dElA,T] = DeltaEl2Alfriend( e, w, M, dEl );
Inputs
 e           (1)  Eccentricity
 w           (1)  Argument of perigee [rad]
 M           (1)  Mean anomaly [rad]
 dEl        (1,6) Orbital element differences [a,i,W,w,e,M]
Outputs
 dElA       (1,6) Orbital element differences [a,th,i,q1,q2,W]
 T          (6,6) Transformation matrix
References M2Nu(), UnwrapPhase(), and zeros().
Referenced by CollisionMonteCarlo().
DeltaElem2Goals()
function DeltaElem2Goals (in el0, in dEl, in J2)
 The reference elements are also required.
 Since version 7.
Form
 goals = DeltaElem2Goals( el0, dEl, J2 );
Inputs
 el0       (1,6)     Measured orbital elements (Alfriend format) [a,theta,i,q1,q2,W]
 dEl       (:,6)     Desired orbital element differences
 J2         (1)      Size of the J2 perturbation (default 0)
Outputs
 goals            (.)      Geometric goals data structure with following fields:
   - y0          (1,:)        along-track offset                             [km]
   - aE          (1,:)        semi-major axis of relative ellipse            [km]
   - beta0       (1,:)        angle on ellipse at perigee                   [rad]
   - zInc        (1,:)        cross-track amplitude due to inclination diff  [km]
   - zLan        (1,:)        cross-track amplitude due to right ascen diff  [km]
References DeltaElem2Hills(), and Hills2Goals().
Referenced by AutoFormGeometry(), and GenerateTeamGoals().
DeltaElem2Hills()
function DeltaElem2Hills (in el0, in dEl, in J2)
Accounts for an optional J2 perturbation. Not valid for near-equatorial orbits. Requires the reference orbital elements in Alfriend form.
 Usage:
 [xH,m] = DeltaElem2Hills( el0, dEl, J2 );
Inputs
 el0           (1,6)  reference orbital elements:    [a,th,i,q1,q2,W]
 dEl           (:,6)  orbital element differences:   [a,th,i,q1,q2,W]
 J2             (1)   size of the J2 perturbation
Outputs
 xH            (6,:)  relative position and velocity in Hills frame [km; km/s]
 m             (6,6)  transformation matrix
Reference: D. Gim and K. Alfriend, State transition matrix of relative motion for the perturbed noncircular reference orbit, Journal of Guidance, Control, and Dynamics, vol. 26, no. 6, pp. 956971, 2003
References abs(), and(), DeltaElem2Hills(), Difference(), Hills2DeltaElem(), vector(), and zeros().
Referenced by DeltaElem2Goals(), DeltaElem2Hills(), DeltaVAnalysis(), and Hills2DeltaElem().
DeltaVAnalysis()
function DeltaVAnalysis (in el0, in y0_i, in aE_i, in beta_i, in y0_f, in aE_f, in beta_f)
w/ several types of reconfigurations.
 Usage:
 dV = DeltaVAnalysis( el0, y0_i, aE_i, beta_i, y0_f, aE_f, beta_f );
Inputs
 el0         (1,6)   Reference element set (Alfriend format) [a,theta,i,q1,q2,W]
 y0_i         (1)    Initial along-track offset
 aE_i         (1)    Initial semi-major axes of relative ellipse
 beta_i       (1)    Initial phase offset in relative ellipse
 y0_f        (1,M)   Final set of along-track offsets
 aE_f        (1,N)   Final set of semi-major axes of relative ellipse
 beta_f      (1,P)   Final set of phase offsets in relative ellipse
Outputs
 dV         (M,N,P)  3-D matrix of total delta-v's associated with each
                        different type of reconfiguration.
References DeltaElem2Hills(), Geometry_Structure(), Goals2DeltaElem(), length(), PlanningParameters_Structure(), set(), State_Structure(), and Window_Structure().
DeltaVChart()
function DeltaVChart (in varargin)
Form
 h = DeltaVChart( t, dV );
 -OR-
 h = DeltaVChart( t, dVSet, index );
Inputs
 t          (1,:)    Time vector.
 dV         (3,:)    Delta-V history.
       -OR-
 t          (1,:)    Time vector.
 dVSet      {1,N}    Set of delta-V histories, one for each run.
 index      (1,k)    Array of simulation run numbers.
Outputs
 h           (1,k)   Figure handles
References vector().
DeltaVCommand_Structure()
function DeltaVCommand_Structure (in nThrusters)
 Since version 7.
Form
 cmd = DeltaVCommand_Structure( nThrusters );
Inputs
 nThrusters   (1)    Number of thrusters
Outputs
 cmd          (.)    Delta-v command data structure with fields:
                        - tank
                        - pulsewidth
                        - jD
                        - iD
References Initialize(), JD2000(), and zeros().
DFFAttitudeTarget()
function DFFAttitudeTarget (in type, in d, in t)
There
 are six types of target
 'latlon'   - point a spacecraft vector at a specific latitude
 and longitude of the earth. The angle about
 the vector is ignored
 'sun'      - point a spacecraft vector at the sun. The angle about
 the vector is ignored
 'lvlh'     - align the spacecraft with LVLH
 'eci'      - align with respect to ECI
 'ulvlh'    - align with a unit vector defined in the lvlh frame
 'ueci'     - align with a unit vector defined in the eci frame
 'target'   - align with a target spacecraft
 The output is the target qECIToBody.
Form
 qTarget = FSWAttitudeTarget( type, d, t )
Inputs
 type    (1,:)     Type of target
 d       (1,1)     Data structure with spacecraft information
 .qECIToBody    (4,1) Current quaternion
 .rECI          (3,1) ECI position vector
 .vECI          (3,1) ECI velocity vector
 .jD            (1,1) Julian date
 t       (1,1)     Data structure with target information
 .latitude      (1,1) Geodetic latitude (rad)
 .longitude     (1,1) Longitude (rad)
 .u             (3,1) Unit vector in the body frame
 .qOffset       (4,1) Offset quaternion (lvlh and eci only)
 .uTarget       (3,1) Target vector in the reference frame
 INVALID:         .rTarget       (3,1) Target ECI position vector
Outputs
 qTarget (4,1)     Target qECIToBody
References and(), DeBlankLT(), JD2T(), LatLonToR(), QForm(), QLVLH(), QMult(), QTForm(), quaternion(), SunV1(), TruEarth(), U2Q(), Unit(), and vector().
DFFControl()
function DFFControl (in action, in u, in iD)
 Actions                     Output
 'initialize'                None
 'update'                    None
Form
 x = DFFControl( action,  u, iD )
Inputs
 action       (1,:)  Action
 u             (:)   Input data
 iD            (1)   Unique spacecraft ID
Outputs
 x            (:)    Output is dependent on the action
References and(), DFFAttitudeController(), DFFAttitudeManagement(), DFFAttitudeManeuver(), DFFCollisionMonitor(), DFFCommandProcessing(), DFFControl(), DFFControlLaw(), DFFCoordinateTransformation(), DFFDeltaVManagement(), DFFGuidanceLaw(), DFFISLManagement(), DFFParameterDatabase(), DFFRelativeNavigation(), DFFTeamManagement(), FSWClock(), get(), Initialize(), isempty(), and MessageQueue().
Referenced by CollisionDetectSimStruct(), and DFFControl().
DFFRHS()
function DFFRHS (in x, in jD, in ignoredArg, in control, in scData)
 Includes position, velocity, orientation, body rate, mass.
Inputs
 x           (:,1)     State vector
 jD          (1,1)     Time in Julian Date
 prop         (.)      Not used
 control      (.)      Data structure with force and torque
 scData       (.)      Data structure of spacecraft data
Outputs
 xDot        (:,1)     State vector derivative
References and(), Cross(), FOrbCart(), Mag(), QIToBDot(), and vector().
DFFSim()
function DFFSim (in el0, in dEl0, in teamGoals, in dT, in planTime, in nOrbits, in J2, in dTMax, in fNom, in mass)
In the built-in demo, seven spacecraft are initialized in a leader-follower formation, in a circular orbit. The desired formation is a projected circle on the cross-track / along-track plane. The act of maneuvering from the first formation (leader-follower) to the next formation (projected circle) is called a reconfiguration maneuver. The target states that form the projected circle geometry are computed and assigned to each spacecraft in order to minimize the total fuel required for the reconfiguration. Each spacecraft then uses a model predictive control algorithm to plan an impulsive transfer trajectory that will bring it to its target state.
Variables saved to base: dVMap, mp, sc
 Usage:
 DFFSim;   % demo
 [t,el,fH,xH,dEl,dElDes] = DFFSim( el0, dEl0, teamGoals, dT, planTime, nOrbits, J2, dTMax, fNom, mass );
Inputs
 el0          (1,6)  Initial reference orbital elements  (Alfriend format)
 dEl0         (:,6)  Initial orbital element differences (Alfriend format)
 teamGoals     (.)   Goals data structure defining desired relative motion for team
 dT            (1)   Time step for the simulation [sec]
 planTime      (1)   Time (into sim) to plan the reconfiguration maneuver [orbits]
 nOrbits       (1)   Number of orbits to simulate [orbits]
 J2            (1)   Flag indicating whether to simulate with J2 or not
 dTMax        (1,1)  Burn duration (s)
 fNom         (1,1)  Nominal thrust (N)
 mass         (1,1)  Spacecraft mass (kg)
Outputs
 t            (1,:)  Time vector [orbits]
 el           (:,6)  Orbital elements of the reference (Alfriend format)
 fH           (3,:)  Applied thrust in Hills frame [kN]
 xH           (6,:)  Relative position and velocity in Hills frame [km; km/s]
 dEl          (:,6)  Mean orbital element differences    (Alfriend format)
 dElDes       (:,6)  Desired orbital element differences (Alfriend format)
See also
: GenerateTeamGoals, SetupAssignmentProblem, EstimateCost,
PrivilegedAssignment, IterativeImpulsiveManeuver
References Alfriend2El(), and(), ApplyDeltaV(), DFFSim(), El2RV(), EstimateCost(), GenerateTeamGoals(), IterativeImpulsiveManeuver(), JD2000(), LoadGravityModel(), Lyapunov(), OrbElemDiff(), OrbRate(), PrivilegedAssignment(), SetupAssignmentProblem(), SortTeamGoals(), vector(), Window_Structure(), and zeros().
Referenced by DFFSim().
DFFSimGUI()
function DFFSimGUI (in totalSteps, in stepsDone, in tToGoMem, in rRT, in dT, in name)
Computes the time left to go in the simulation, the predicted finish time and the ratio of simulation time to real time. This routine should be called at regular intervals.
Similar to the TimeGUI, but with two additional buttons. You may hide/show the Message Queue window, and hide/show the Team Organization window at any time. Hiding these windows helps speed up the simulation.
Type DFFSimGUI('close') to close the GUI.
Form
 [ rRT, tToGoMem, tToGo, tDone ] = DFFSimGUI( totalSteps, stepsDone, tToGoMem, rRT, dT, name )
Inputs
 totalSteps             Total number of steps in the simulation
 stepsDone              Number of steps completed
 tToGoMem       (.)      Memory [lastJD, lastStepsDone, number of averages done]
 rRT                    Ratio of simulation time to real time
 dT                     Simulation time step (sec)
 name                   Name of simulation
Outputs
 rRT                    Ratio of simulation time to real time
 tToGoMem               Memory [lastJD, lastStepsDone, number of averages done]
 tToGo                  Time left in the simulation
 tDone                  Predicted clock time of finish
References and(), close(), CloseIfHandle(), Date2JD(), Demo(), DFFSimGUI(), get(), Initialize(), JD2Date(), set(), and TimeGUI().
Referenced by DFFSimGUI().
DFFSimulation()
function DFFSimulation (in sim, in recordTargetState, in showTeamOrg, in showMsgQ)
Form
 d = DFFSimulation( sim )
Inputs
 sim                 (.)    Simulation data structure, containing simulation
                              parameters and spacecraft data
 recordTargetState   (1)    Record the target state or not?    (optional)
 showTeamOrg         (1)    Show the team organization or not? (optional)
 showMsgQ            (1)    Show the Message Queue or not?     (optional)
Outputs
 d            (.)    Output data structure, containing time histories of
                        all states and controls
References and(), DFFSimStruct(), and Initialize().
Referenced by AutoDualPCSimStruct(), AutoFormSimStruct(), ClusterGoalsDemoSimStruct(), CollisionDemoSimStruct(), CollisionDetectSimStruct(), CollisionSimStruct(), DemoManeuverSimStruct(), DFFSimStruct(), EccentricTetrahedronSimStruct(), MainDemoSimStruct(), MessageAnalysis(), ProjCircSimStruct(), SimpleManeuverSimStruct(), TeamManagementSimStruct(), TestADCSSimStruct(), TestCollisionSimStruct(), TestControlSimStruct(), and TestTeamMgtSimStruct().
DiscreteGVE()
function DiscreteGVE (in el, in dEl0, in aC, in t)
 A discretized state space model of Gauss' variational equations is used,
 which is defined by the reference orbital elements.
 The "GVEDynamics" function is called to get the continuous matrices,
 and the discretization is done using "C2DZOH.m".
 Since version 7.
Form
 [dEl,M] = DiscreteGVE( el, dEl0, aC, t )
Inputs
 el                (1,6)   Reference orbital elements [a,i,W,w,e,M]
 dEl0              (1,6)   Initial relative state
 aC                (3,n)   Commanded accelerations [km/s/s]
 t                (1,n+1)  Time vector (final time corresponds to final state)
Outputs
 dEl              (n+1,6)  State trajectory of the satellite in Hill's frame
 M                (n+1,1)  Mean anomaly over time t
References C2DZOH(), GVEDynamics(), Initialize(), OrbRate(), Period(), vector(), and zeros().
Referenced by TestLPEccentricGVE().
DiscreteHills()
function DiscreteHills (in x0, in w0, in aC, in dT)
Computes the state trajectory (xS) of a satellite given the initial state (x0) and the commanded accelerations (aC). Uses a discretized state space model of Hills equations, which is defined by the orbit rate (w0). "LinOrb.m" is called with w0 to generate the plant, and the discretization is done using "CDZOH.m".
Form
 xS = DiscreteHills( x0, w0, aC, dT );
Inputs
 x0                (6,1)   Initial state
 w0                 (1)    Reference orbit rate (rad/sec)
 aC                (3,n)   Commanded accelerations
 dT                 (1)    Sampling time for zero-order hold
Outputs
 xS                (6,n+1)  State trajectory of the satellite in Hill's frame
See also
LinOrb, CDZOH
References and().
Referenced by CompareHills(), LPvsCF(), and TestLPCircular().
DisplayPlugin()
function DisplayPlugin (in fig, in pos, in bColor, in name)
 This function is called while initializing the Formation Design GUI.
Form
 d = DisplayPlugin( fig, pos, bColor, name );
Inputs
 fig              (1)   Handle to Formation Design GUI figure
 pos             (1,2)  Position data of GUI
 bColor          (1,3)  Background color of GUI
 name            (1,:)  m-file name of GUI for callbacks
Outputs
 d                (.)   Data structure of handles to "Display" panel controls
References DisplayPlugin(), and NewFig().
Referenced by DisplayPlugin(), and OrbitDataPlugin().
DistantPtToEll()
function DistantPtToEll (in U, in S, in xc, in x0, in laguerre)
Finds the distance (and the corresponding point) from a distant point to the closest point on an ellipsoid.
An ellipsoid is defined as (x-xc)'inv(P)(x-xc), where
 x  - point on the ellipsoid
 P  - ellipsoid definition
 xc - center of ellipsoid
 d  - distance from x0 to x
 x0 - outside point
 This form accepts the singular value decomposition of P.
Form
 [d,x] = DistantPtToEll(U,S,xc,x0,laguerre)
Inputs
 U         (3,3)      Unitary matrix from SVD of P
 S         (3,3)      Singular value matrix from SVD of P
 xc        (3,1)      Ellipsoid center
 x0        (3,1)      Outside point
 laguerre  (1,1)      Flag to use Laguerre for roots instead of eig
Outputs
 d        (1)        Distance
 x        (3,1)      Point on the ellipsoid
References and(), DistantPtToEll(), and Laguerre().
Referenced by CollisionMonitor(), DistantPtToEll(), and MinDEllipsoid().
DistributeClusterGoals()
function DistributeClusterGoals (in clusterGoals, in targetIDs, in teams, in dPhi)
 IDs and a desired team structure mapping those IDs into various teams, this
 function returns a set of "teamGoals" structures as well as the relative
 geometry of each team's reference with respect to the cluster origin.
 Only valid for circular orbits.
 Since version 7.
Form
 [teamGoals,refGoals] = DistributeClusterGoals( clusterGoals, targetIDs, teams, dPhi );
Inputs
 clusterGoals   (.)     Set of all geometric goals for the cluster
 targetIDs     (1,:)    Set of unique ID numbers for the cluster goals
 teams          (.)     Data structure array of team info, where all
                          member and reference IDs correspond to the
                          "targetIDs" set.
 dPhi           (1)     Angular resolution for variable state discretization
Outputs
 teamGoals      (.)     Array of team goals data structures
 refGoals       (.)     Array of geometric goal structures, describing
                           relative geometry of each reference with
                           respect to the cluster origin.
References and(), and set().
DriftRateSigma()
function DriftRateSigma (in a, in sigma_x, in sigma_ydot, in rho_xydot)
Type DriftRateSigma for a demo.
Form
 sigma_d = DriftRateSigma( a, sigma_x, sigma_ydot, rho_xydot );
Inputs
 a          (1)     Semi-major axis of orbit [km]
 sigma_x    (1)     Standard deviation of relative radial position error
 sigma_ydot (1)     Standard deviation of relative along-track velocity error
 rho_xydot  (1)     Correlation coefficient (between -1 and +1)
Outputs
 sigma_d    (1)     Standard deviation of the along-track drift per orbit
References and(), Constant(), Demo(), DriftRateSigma(), isempty(), length(), and zeros().
Referenced by DriftRateSigma().
EccGeometry_Structure()
function EccGeometry_Structure (in nU)
Form
 g = EccGeometry_Structure( n )
Inputs
 n            (1)    Number of geometry structures
Outputs
 g            (.)    Geometry data structure with fields:
                        - y0,      along-track offset (km)
                        - xMax,    maximum radial amplitude (km)
                        - nu_xMax, true anomaly of xMax (rad)
                        - zMax,    maximum cross-track amplitude (km)
                        - nu_zMax, true anomaly of zMax (rad)
References Initialize().
Referenced by DemoManeuverCommandList(), EccTeamGoals_Structure(), FFEccGenerateTeamGoals(), FFEccTetrahedronGeometry(), GeometryCirc2Ecc(), IsEccGeom(), and TestControlCommandList().
EccTeamGoals_Structure()
function EccTeamGoals_Structure (in nU)
 Since version 7.
Form
 tG = EccTeamGoals_Structure( nU );
Inputs
 nU            (1)    Number of unique states
                      (also equal to number of geometric goal structures
                      and number of constraint structures)
Outputs
 tG           (.)    Eccentric team goals data structure with fields:
                        - teamID
                        - nU
                        - geometry
                        - constraints
                        - dPhi
References and(), Constraints_Structure(), EccGeometry_Structure(), and Initialize().
Referenced by ClusterGoalsDemoCommandList(), and FFEccGenerateTeamGoals().
ECI2Hills()
function ECI2Hills (in x0, in x1)
The first input is treated as the reference state.
Form
 xH = ECI2Hills( x0, x1 )
Inputs
 x0  (6,1) [r;v] ECI frame (reference)
 x1  (6,n) [r;v] ECI frame
Outputs
 xH  (6,n) [r; v] Hills frame
                       [dR; r0*dTheta; dZ; dRDot; r0*dThetaDot; dZDot]
Referenced by CompareHills(), ECI2LVLH(), FFEccDeltaElem2Hills(), FFIntegrate(), ProjCirc(), ProjLine(), and TestFFEccLinOrb().
ECI2LVLH()
function ECI2LVLH (in x0, in x1)
This function takes two ECI state vectors, and returns the relative state in the LVLH frame. It treats the first input as the reference state.
Form
 xL = ECI2LVLH( x0, x1 )
Inputs
 x0              (6,1) [r;v] ECI frame (reference)
 x1              (6,n) [r;v] ECI frame
Outputs
 xL              (6,n) [r; v] LVLH frame
See also
ECI2Hills, Hills2LVLH
References and(), ECI2Hills(), and Hills2LVLH().
ECI2MeanElements()
function ECI2MeanElements (in xRefECI, in xRelECI, in J2)
 Since version 7.
Form
 [elRefMean, dElMean] = ECI2MeanElements(xRefECI, xRelECI, J2);
 Note: it is assumed that all inputs have the same time-tag.
Inputs
 xRefECI          (6,1)    reference position & velocity in ECI frame
 xRelECI          (6,:)    relative positions & velocities in ECI frame
 J2                (1)     size of J2 perturbation
Outputs
 elRefMean        (1,6)    mean orbital elements of the reference orbit
 dElMean          (:,6)    mean orbital element differences
 NOTE: Both element sets are in Alfriend format [a,theta,i,q1,q2,W]
References: Terry Alfriend, Texas A&M University Joe Mueller, Princeton Satellite Systems
References and(), Demo(), ECI2MeanElements(), El2Alfriend(), OrbElemDiff(), Osc2Mean(), RV2El(), and zeros().
Referenced by ECI2MeanElements(), and FFSim().
EllipseDeltaV()
function EllipseDeltaV (in r0, in v0, in n, in x0)
2x1 ellipse centered about the TARGET. The delta-v should be applied at the same time that corresponds to the supplied state.
Form
 dV = EllipseDeltaV( r0, v0, n, x0 );
Inputs
 r0           (6,1)  Initial SLO-frame relative position [km]
 v0           (6,1)  Initial SLO-frame relative velocity [km/s]
 n             (1)   Mean orbit rate (rad/s)
 x0            (1)   Desired along-track offset of ellipse [km]
Outputs
 dV           (3,1)  SLO-frame delta-v  [km/s]
References HillsEqnsSLO().
Referenced by NominalSafeGuidance().
EllipsePatch()
function EllipsePatch (in aX, in bY, in n)
 Since version 7.
Form
 [v,f] = EllipsePatch( aX, bY, n )
Inputs
 aX      (1,1)      X-axis dimension
 bY      (1,1)      Y-axis dimension
 n       (1,1)      Number of facets
Outputs
 v (n,2)   Vertices
 f (n,3)   Faces
References and(), EllipsePatch(), NewFig(), and zeros().
Referenced by EllipsePatch().
EllipsePhase()
function EllipsePhase (in alpha0)
This is the angle on a circle with radius aE that has a projected x-component equal to that of the relative ellipse:
 aE*sin(alpha0) = r*sin(beta0)
Form
 beta0 = EllipsePhase( alpha0 )
Inputs
 alpha0 (1,1)   Desired phase angle at equator crossing (rad)
Outputs
 beta0   (1,1) Phase angle on ellipse such that the y-component of
               the circle is equal to that of the ellipse [rad]
References length(), and WrapPhase().
Referenced by GenerateTeamGoals(), GeometryEcc2Circ(), PCGoals(), and RotateState().
EllipsePropCirc()
function EllipsePropCirc (in P, in Q, in DT, in wn, in hills)
 and the disturbance ellipsoid. For circular orbits.
Note: The state is in the form [X;Y;Z;Xdot;Ydot;Zdot] where true Hills
 X,Xdot - radial direction
 Y,Ydot - velocity direction
 Z,Zdot - cross-track
Form
 [StateQ,DistQ,Phi,Binput] = EllipsePropCirc(P,Q,DT,wn,hills);
Inputs
 P      (6,6)   Initial state uncertainty ellipsoid
 Q      (3,3)   Initial disturbance uncertainty ellipsoid
 DT      (1)    Time horizon of the prediction (DT = Tf - T0)
 wn      (1)    Orbit rate (rad/sec)
 hills   (1)    Flag for state type, 1 = true Hills
Outputs
 StateQ   (6,6)  Propagated state uncertainty over DT
 DistQ    (6,6)  Propagated dynamics uncertainty over DT
 Phi      (6,6)  Transition matrix, expm(A*DT)
 Binput   (6,3)  Input matrix
Reference: M. Campbell and B. Udrea, "Collision Avoidance in Satellite Clusters", IEEE American Control Conference, 2002.
References and().
Referenced by CollisionMonitor().
Ellipsoid()
function Ellipsoid (in s, in u, in n)
Calculates an ellipsoid given the ellipsoid matrix, semimajor axes, the unit vectors along the axes and the number of patches It is similar to the sphere function from MATLAB.
Form
 [x, y, z] = Ellipsoid( s, u, n )
Inputs
s (3,1) semi-major axes, [a;b;c] u (3,3) principal axes n (1) number of patches
Outputs
 x         (n+1,n+1)  x-component of vertices of patch
 y         (n+1,n+1)  y-component of vertices of patch
 z         (n+1,n+1)  z-component of vertices of patch
References and(), Ellipsoid(), Eul2Mat(), Initialize(), NewFig(), set(), and Watermark().
Referenced by CollProbSet(), CollProbVol(), Ellipsd(), Ellipsoid(), GeomPatch(), and MinDEllipsoid().
EstimateCost()
function EstimateCost (in el0, in dEl, in teamGoals, in memID, in window, in weight)
 Since version 7.
 Usage:
 costEstimate = EstimateCost( el0, dEl, teamGoals, memID, window, weight );
Inputs
 el0          (1,6)  Initial reference orbital elements  (Alfriend format) [a,theta,i,q1,q2,W]
 dEl          (1,6)  Initial orbital element differences (Alfriend format)
 teamGoals     (.)   Team goals data structure defining desired relative motion for team
 memID         (1)   Unique member ID
 window        (1)   Time window data structure
 weight        (1)   Scalar weight to be applied to all costs for this spacecraft
Outputs
 costEstimate  (.)   Data structure including weighted cost to achieve
                        all specified unique target states.
References abs(), and(), Demo(), EstimateCost(), Goals2DeltaElem(), length(), OptimalInPlaneDeltaV(), RotateState(), set(), SetupAssignmentProblem(), vector(), and zeros().
Referenced by DFFSim(), and EstimateCost().
FFEccAnalyzeShape()
function FFEccAnalyzeShape (in varargin)
 Creates a GUI of the trajectory and allows you to select points using
 the mouse. Has a built-in demo.
 Since version 7.
Form
 FFEccAnalyzeShape( xH, nu );
Inputs
 xH              (6,n)  State trajectory in Hills frame
 nu              (1,n)  True anomaly (independent variable) [rad]
Outputs
 none
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
References and().
Referenced by FFEccYExt().
FFEccDeltaElem2Goals()
function FFEccDeltaElem2Goals (in el0, in dEl, in type)
 Since version 7.
 Usage:
 g = FFEccDeltaElem2Goals( el0, dEl, type );
Inputs
 el0          (1,6)  Initial reference orbital elements
 dEl          (1,6)  Initial orbital element differences
 type          (1)   Element set type
                        - 1   [a,theta,i,q1,q2,W]  (Alfriend format)
                        - 2   [a,i,W,w,e,M]        (standard format)
Outputs
 g             (.)   Geometric goals data structure
References FFEccDeltaElem2Hills(), FFEccHills2Goals(), M2Nu(), OrbRate(), and set().
Referenced by AutoFormGeometry().
FFEccDeltaElem2Hills()
function FFEccDeltaElem2Hills (in el0, in dEl, in type, in t, in mu)
 Since version 7.
 Usage:
 xH = FFEccDeltaElem2Hills(el0,dEl,type);
Inputs
 el0          (1,6)  Initial reference orbital elements
 dEl          (1,6)  Initial orbital element differences
 type          (1)   Element set type
                        - 1   [a,theta,i,q1,q2,W]  (Alfriend format)
                        - 2   [a,i,W,w,e,M]        (standard format)
Outputs
 xH           (6,1)  Hills frame state [x;y;z;dx/dt;dy/dt;dz/dt]
References Alfriend2El(), Constant(), ECI2Hills(), El2RV(), FFEccDeltaElem2Hills(), length(), OrbRate(), set(), and zeros().
Referenced by AutoFormGeometry(), FFEccDeltaElem2Goals(), FFEccDeltaElem2Hills(), and TestLPEccentricGVE().
FFEccDH()
function FFEccDH (in nu0, in e)
 of relative orbit motion.
 Since version 7.
Form
 dH = FFEccDH( nu0, e );
Inputs
 nu0             (1,N)  True anomaly (at initial state) [rad]
 e                (1)   Eccentricity
Outputs
 dH              (1,N)  Integration constant found by setting H = 0 at nu0
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
Referenced by FFEccDMatPeriodic(), FFEccGenerateTeamGoals(), FFEccGoals2Hills(), FFEccProp(), FFEccShapes(), and FFEccYExt().
FFEccDiscreteHills()
function FFEccDiscreteHills (in e, in n, in x0, in nu0, in aC, in t)
 A discretized state space model of Hills equations is used, which is defined
 by the mean orbit rate (n), eccentricity (e), and true anomaly history.
 The "FFEccLinOrb" function is called, and the discretization is done using
 "C2DZOH.m".
 Since version 7.
Form
 [xS,nu] = FFEccDiscreteHills( e, n, x0, nu0, aC, t )
Inputs
 e                  (1)    Eccentricity
 n                  (1)    Mean orbit rate (rad/sec)
 x0                (6,1)   Initial relative state
 nu0                (1)    Initial true anomaly
 aC                (3,n)   Commanded accelerations
 t                 (1,n+1) Time vector (final time corresponds to final state)
Outputs
 xS                (6,n+1)  State trajectory of the satellite in Hill's frame
References and(), FFEccLinOrb(), Initialize(), M2Nu(), Nu2M(), UnwrapPhase(), vector(), and zeros().
Referenced by TestFFEccLinOrb(), TestLPEccentric(), and TestLPEccentricGVE().
FFEccDMatPeriodic()
function FFEccDMatPeriodic (in xH0, in nu0, in e, in method)
Given an initial Hills state (xH0) at a particular true anomaly (nu0) of an eccentric orbit (e), compute the in-plane velocities (dx and dy) required for periodic motion.
Use any of the following methods:
 1) symmetric              - Motion is symmetric in-track about the origin
 2) fuel optimized         - Use LP to find minimum of abs(dx) + abs(dy)
 3) velocity constraint    - Leave dx = dx0, solve for new dy
Form
 [D, dx, dy] = FFEccDMatPeriodic( xH0, nu0, e, method );
Inputs
 xH0             (6,1)   Initial state in Hills frame
 nu0            (1,1)   True anomaly (at initial state) [rad]
 e              (1,1)   Eccentricity
 method         (1,1)   Indicate which method to use
                           1 - symmetric
                           2 - fuel optimization
                           3 - velocity constraint
Outputs
 D               (6,1)  Vector of integration constants
 dx                 (1,1)   Scaled radial velocity required for periodic motion
 dy                 (1, )   Scaled along-track velocity required for periodic motion
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
References and(), FFEccDH(), FFEccDMatPeriodic(), FFEccRMat(), length(), Plot2D(), vector(), and zeros().
Referenced by FFEccDMatPeriodic(), and FFEccShapes().
FFEccEstimateCost()
function FFEccEstimateCost (in el0, in xH0, in teamGoals, in memID, in window, in weight, in nSPO)
 Since version 7.
 Usage:
 costEstimate = FFEccEstimateCost( el0, xH0, teamGoals, memID, window, weight, nSPO );
Inputs
 el0          (1,6)  Initial elements of reference orbit [a,i,W,w,e,M]
 xH0          (6,1)  Initial relative state in Hills frame
 teamGoals     (.)   Team goals data structure defining desired relative motion for team
 memID         (1)   Unique member ID
 window        (1)   Time window data structure
 weight        (1)   Scalar weight to be applied to all costs for this spacecraft
 nSPO          (1)   Number of samples to use per orbit for LP algorithm
Outputs
 costEstimate  (.)   Data structure including weighted cost to achieve
                        all specified unique target states.
 nuOpt         (M)   True anomaly at maneuver end time corresponding to
                        the minimum cost solution. One for each fixed state.
References and(), Demo(), FFEccEstimateCost(), FFEccGoals(), FFEccGoals2Hills(), FFEccProp(), length(), LPEccentric(), M2Nu(), Mag(), NuDot(), OrbRate(), set(), SetupAssignmentProblem(), Simplex(), TeamGoals_Structure(), vector(), and zeros().
Referenced by FFEccEstimateCost().
FFEccFrameCompare()
function FFEccFrameCompare (in elRef0, in xH0, in nOrbits, in nS, in method)
The first case uses the homogenous LTV solution to Lawden's equations.
The second case computes the absolute trajectories of both orbits in the ECI frame, then transforms into the relative Hill's frame.
 Note: The reference elements are provided, defining one orbit. The initial
 relative state is also provided, which is added to the initial
 reference state to define the second orbit.
Form
 [xH1,xH2] = FFEccFrameCompare( elRef0, xH0, nOrbits, nS, method );
Inputs
 elRef0          (1,6)  Initial elements of reference orbit
 xH0             (6,1)  Initial state in Hills frame
 nOrbits          (1)   Number of orbits to simulate
 nS               (1)   Number of samples to use
 method           (1)   Indicate which method to use for initialization
                           0 - do not enforce periodic motion, use supplied xH0 exactly
                           1 - enforce periodic, symmetric motion about origin
                           2 - enforce periodic motion via fuel optimization
                           3 - enforce periodic motion using the velocity constraint
                               (only change y-velocity)
Outputs
 xH1             (6,nS) Relative state trajectory from first case
 xH2             (6,nS) Relative state trajectory from second case
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
References and(), El2RV(), FFEccLawdensEqns(), length(), M2Nu(), OrbRate(), Period(), RV2El(), RVOrbGen(), and zeros().
FFEccFrenet2Goals()
function FFEccFrenet2Goals (in e, in nu, in xF, in n)
Form
 [g,D] = FFEccFrenet2Goals( e, nu, xF, n );
Inputs
 e     (1,1)    Eccentricity
 nu    (1,1)    True anomaly [rad]
 xF    (6,1)    Frenet frame state at nu (time-domain)
 n     (1,1)    Mean orbit rate [rad/s] (optional)
                         * uses time-derivatives if provided
                         * uses nu-derivatives if NOT provided
Outputs
 g     (.)   Data structure of geometric goals
Copyright (c) 2007 Princeton Satellite Systems, Inc.
All rights reserved.
 Since version 7.
 2019.1 Fixed bug in second path
References and(), FFEccHills2Goals(), and Frenet2Hills().
FFEccGenerateTeamGoals()
function FFEccGenerateTeamGoals (in el0, in fType, in fSize, in nRels, in teamID, in nu, in eul)
 Enter a single input, 'list', to see a list of all supported types.
 This function:
 + supports all 10 formation types for circular orbits
 - circular based trajectories found with GenerateTeamGoals
 - desired x,y,z position of each trajectory is used
 - each eccentric trajectory defined by the constraint that
 they intersect the desired position at the given
 true anomaly "nu"
 + supports new formation types designed explicitly for eccentric orbits
 - tetrahedron at true anomaly "nu", with orientation "eul" (requires that nRels = 3 )
 - others ?
 Since version 7.
 Usage:
 teamGoals = FFEccGenerateTeamGoals( el0, fType, fSize, nRels, teamID, nu, eul );
Inputs
 el0           (1,6)  reference orbital elements   [a,th,i,q1,q2,W]
 fType          (1)   formation type
 fSize          (1)   formation size
 nRels          (1)   number of relatives in the team
 teamID         (1)   unique integer team ID
 nu             (1)   true anomaly at which specified geometry occurs [rad]
 eul           (3,1)  Euler angles to define orientation of geometry (optional)
Outputs
 teamGoals      (.)   Team Goals data structure, with geometric goals
                      for all unique states, and corresponding constraints
References and(), AnimationGUI(), Demo(), DupVect(), EccGeometry_Structure(), EccTeamGoals_Structure(), El2Alfriend(), Euler(), FFEccDH(), FFEccGenerateTeamGoals(), FFEccGoals(), FFEccGoals2Hills(), FFEccHexahedronGeometry(), FFEccHills2Goals(), FFEccProp(), FFEccTetrahedronGeometry(), GenerateTeamGoals(), Geometry_Structure(), get(), Goals2Hills(), isempty(), M2Nu(), OrbRate(), RotateState(), set(), and zeros().
Referenced by FFEccGenerateTeamGoals().
FFEccGoals()
function FFEccGoals (in varargin)
 Since version 7.
Form
 [D,xH0] = FFEccGoals( e, goals );                             % (2 inputs)
 -or-
 [D,xH0] = FFEccGoals( e, y0, xMax, nu_xMax, zMax, nu_zMax );  % (6 inputs)
 -or-
 [D,xH0] = FFEccGoals( e, y0, x, y, nu_xy,   zMax, nu_zMax );  % (7 inputs)
Inputs
 e                (1)   Eccentricity
 goals            (.)   Geometric goal data structure
                           * Two different sets of in-plane parameters supported
                              - { y0, xMax, nu_xMax }
                              - { y0, x, y, nu_xy   }
                           * Two different sets of out-of-plane parameters supported
 -or-
 e                (1)   Eccentricity
 y0               (1)   Along-track offset [km]
 xMax             (1)   Maximum radial offset [km]
 nu_xMax          (1)   True anomaly where maximum radial offset occurs [rad]
 zMax             (1)   Maximum cross-track amplitude [km]
 nu_xMax          (1)   True anomaly where maximum cross-track amplitude occurs [rad]
 -or-
 e                (1)   Eccentricity
 y0               (1)   Along-track offset [km]
 x                (1)   Radial position at true anomaly "nu_xy"      [km]
 y                (1)   Along-track position at true anomaly "nu_xy" [km]
 nu_xy            (1)   True anomaly where <x,y> position occurs     [rad]
 zMax             (1)   Maximum cross-track amplitude [km]
 nu_xMax          (1)   True anomaly where maximum cross-track amplitude occurs [rad]
Outputs
 D               (6,1)  Integration constants computed from i.c.'s
 xH0             (6,1)  Hills frame state at nu = 0
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
References and().
Referenced by AutoFormGeometry(), FFEccEstimateCost(), FFEccGenerateTeamGoals(), FFEccGoals2Hills(), FFEccHexahedronGeometry(), FFEccHills2Goals(), FFEccTetrahedronGeometry(), FFEccYExt(), FFEccZExt(), TestFFEccLinOrb(), TestLPEccentric(), and TestLPEccentricGVE().
FFEccGoals2Hills()
function FFEccGoals2Hills (in e, in nu, in g, in n)
 Since version 7.
Form
 [xH,D] = FFEccGoals2Hills( e, nu, g, n );
Inputs
 e                (1)   Eccentricity
 nu               (1)   True anomaly [rad]
 g                (.)   Data structure of geometric goals
 n                (1)   Mean orbit rate [rad/s] (optional)
                         * time-derivatives returned if provided
                         * nu-derivatives returned if NOT provided
Outputs
 xH              (6,1)  Hills frame state at nu (time-domain)
 D               (6,1)  Integration constants for trajectory
 dH               (1)   Integration constant found by setting H = 0 at nu
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
References and(), FFEccDH(), FFEccGoals(), FFEccProp(), isempty(), and Nu2TimeDomain().
Referenced by AddGoals(), AutoFormGeometry(), FFEccEstimateCost(), FFEccGenerateTeamGoals(), FFEccHexahedronGeometry(), FFEccTetrahedronGeometry(), Goals2Hills(), ImpulsiveLPManeuver(), IterativeImpulsiveManeuver(), LPEccentricTimeWeight(), SubGoals(), and TransformGeom2Hills().
FFEccH()
function FFEccH (in nu, in e, in dH)
 of relative orbit motion.
Form
 H = FFEccH( nu, e, dH )
Inputs
 nu              (1,:)  True anomaly [rad]
 e              (1,1) Eccentricity
 dH              (1,:)  Integration constant found by setting H = 0 at nu0
Outputs
 H               (1,:)  Value of H term at nu0
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
 Since version 7.
References length().
FFEccHexahedronGeometry()
function FFEccHexahedronGeometry (in nu, in d, in eul)
Compute the geometric goals for a formation that achieves a hexahedron shape at a given true anomaly in an eccentric reference orbit. The hexahedral configuration has 5 points and forms two stacked tetrahedra – one pointing up, the other pointing down.
Form
 g = FFEccHexahedronGeometry( nu, d, eul )
Inputs
 nu          (1)  True anomaly where hexahedron occurs
 d           (1)  Length of each side
 eul        (3,1) Euler angles defining the orientation
Outputs
 g           (.)  Geometric goals data structure
References and(), AnimationGUI(), Demo(), DupVect(), Euler(), FFEccGoals(), FFEccGoals2Hills(), FFEccHexahedronGeometry(), FFEccProp(), Hexahedron(), Mag(), NewFig(), set(), and zeros().
Referenced by FFEccGenerateTeamGoals(), FFEccHexahedronGeometry(), and ViewGeometry().
FFEccHills2DeltaElem()
function FFEccHills2DeltaElem (in el0, in xH, in type)
elements
 Since version 7.
Inputs
 el0           (1,6)  reference orbital elements
 xH            (6,:)  relative position and velocity in Hills frame [km; km/s]
 type           (1)   type of orbital element set
                        1 -- [a,th,i,q1,q2,W]
                        2 -- [a,i,W,w,e,M]
Outputs
 dEl           (:,6)  Orbital Element differences
                        if type 1 -- delta [a,th,i,q1,q2,W]
                        if type 2 -- delta [a,i,W,w,e,M]
References Alfriend2El(), and(), El2Alfriend(), El2RV(), Hills2ECI(), OrbElemDiff(), RV2El(), and set().
Referenced by AutoFormGeometry(), and TestLPEccentricGVE().
FFEccHills2Goals()
function FFEccHills2Goals (in e, in nu, in xH, in n)
 Since version 7.
Form
 [g,D] = FFEccHills2Goals( e, nu, xH, n );
Inputs
 e                (1)   Eccentricity
 nu               (1)   True anomaly [rad]
 xH              (6,1)  Hills frame state at nu (time-domain)
 n                (1)   Mean orbit rate [rad/s] (optional)
                         * uses time-derivatives if provided
                         * uses nu-derivatives if NOT provided
Outputs
 g                (.)   Data structure of geometric goals
 D               (6,1)  Integration constants for trajectory
 dH               (1)   Integration constant found by setting H = 0 at nu
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
Copyright (c) 2004 Princeton Satellite Systems, Inc.
All rights reserved.
References abs(), and(), FFEccGoals(), FFEccHills2Goals(), FFEccProp(), FFEccRMat(), FFEccYExt(), FFEccZExt(), isempty(), Time2NuDomain(), vector(), and WrapPhase().
Referenced by AddGoals(), FFEccDeltaElem2Goals(), FFEccFrenet2Goals(), FFEccGenerateTeamGoals(), FFEccHills2Goals(), IterativeImpulsiveManeuver(), and SubGoals().
FFEccIntConst()
function FFEccIntConst (in xH0, in nu0, in e)
Compute integration constants for homogeneous solution to LTV diff eqs of relative orbit motion.
Form
 [D,dH,R] = FFEccIntConst( xH0, nu0, e );
Inputs
 xH0             (6,1)  Initial state in Hills frame. Velocity terms
                           are expressed as derivatives with respect to
                           true anomaly, rather than time.
 nu0              (1)   True anomaly (at initial state) [rad]
 e                (1)   Eccentricity
Outputs
 D               (6,1)  Vector of integration constants
 dH               (1)   Integration constant found by setting H = 0 at nu0
 R               (6,6)  State transition matrix
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
References FFEccRMat().
Referenced by FFEccShapes().
FFEccLawdensEqns()
function FFEccLawdensEqns (in xH0, in nu0, in nu, in e, in n)
 This method uses a closed-form solution to Lawden's equations.
 Since version 7.
Form
 xH = FFEccLawdensEqns( xH0, nu0, nu, e, n );
Inputs
 xH0             (6,1)  Initial Hills frame state
 nu0              (1)   True anomaly (at initial state) [rad]
 nu              (1,n)  True anomaly (at new state) [rad]
 e                (1)   Eccentricity
 n                (1)   Mean orbit rate [rad/s] (optional)
                         * if provided, state must have time-derivatives
                         * if NOT provided, state must have nu-derivatives
Outputs
 xH              (6,n)  New Hills frame state at nu (with nu-derivatives)
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
References and().
Referenced by AutoFormGeometry(), CheckDeltaVs(), and FFEccFrameCompare().
FFEccLinOrb()
function FFEccLinOrb (in n, in nu, in e, in dT)
Compute the continous A,B matrices for linearized relative motion in an eccentric reference orbit. Discretizes with a zero-order hold if dT provided.
 xDot = a*x + b*u
Form
 [a,b] = FFEccLinOrb( n, nu, e, dT );
Inputs
 n                (1)   Mean orbit rate [rad/s]
 nu               (1)   True anomaly [rad]
 e                (1)   Eccentricity
 dT               (1)   Time-step for discretization (optional)
Outputs
 a               (6,6)  Plant matrix
 b               (6,3)  Input matrix
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
References C2DZOH(), NuDot(), and zeros().
Referenced by CollisionMonitor(), CollisionMonteCarlo(), FFEccDiscreteHills(), LinOrbLQG(), LPEccentric(), and TestFFEccLinOrb().
FFEccProp()
function FFEccProp (in D, in nu, in e, in dH)
constants and eccentricity.
 Since version 7.
Form
 xH = FFEccProp( D, nu, e, dH )
Inputs
 D               (6,1)  Integration constants computed from i.c.'s
 nu              (1,n)  True anomaly [rad]
 e                (1)   Eccentricity
 dH               (1)   Integration constant found by setting H = 0 at nu0
                        (Optional. If not provided, it will be computed
                        using the first nu supplied)
Outputs
 xH              (6,n)  Hills frame state at nu. Velocity terms
                           are expressed as derivatives with respect to
                           true anomaly, rather than time.
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
References and(), FFEccDH(), FFEccRMat(), length(), vector(), and zeros().
Referenced by FFEccEstimateCost(), FFEccGenerateTeamGoals(), FFEccGoals2Hills(), FFEccHexahedronGeometry(), FFEccHills2Goals(), FFEccTetrahedronGeometry(), FFEccYExt(), FFEccZExt(), TestLPEccentric(), and TestLPEccentricGVE().
FFEccRMat()
function FFEccRMat (in nu, in e, in dH)
 xH = R*D
 where D is the vector of integration constants found from initial conditions.
 Since version 7.
Form
 R      = FFEccRMat( nu, e, dH );
 [R,dH] = FFEccRMat( nu, e );
Inputs
 nu              (1,N)  True anomaly [rad]
 e                (1)   Eccentricity
 dH               (1)   Integration constant found by setting H = 0 at nu0
                        (Optional. If not provided, it will be computed
                        using the first nu supplied)
Outputs
 R             (6*N,6)  Transformation matrix for equation xH = R*D
                        where D is the integration constant vector.
 dH               (1)   Integration constant found by setting H = 0 at nu0
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
References and(), length(), vector(), and zeros().
Referenced by FFEccDDX(), FFEccDDY(), FFEccDDZ(), FFEccDMatPeriodic(), FFEccDX(), FFEccDY(), FFEccDZ(), FFEccHills2Goals(), FFEccIntConst(), FFEccProp(), FFEccShapes(), FFEccYExt(), FFEccZExt(), and TestFFEccLinOrb().
FFEccShapes()
function FFEccShapes (in xH0, in nu0, in e, in method, in n, in animate)
Requires an initial Hills state, true anomaly, and eccentricity.
The motion is forced to be periodic by using the FFEccDMatPeriodic function. This keeps the same initial position and the same initial cross-track velocity. The along-track velocity and/or radial velocity is changed to ensure periodic relative motion.
 A vector of nu0 values can be provided, causing the shapes that correspond
 to each nu0 to be animated.
 Since version 7.
Form
 [x,y] = FFEccShapes( xH0, nu0, e, method, n, animate );
Inputs
 xH0             (6,1)  Initial state in Hills frame. Velocity terms
                           are expressed as derivatives with respect to
                           true anomaly, rather than time.
 nu0             (1,m)  True anomaly (at initial state) [rad]
 e                (1)   Eccentricity
 method           (1)   Indicate which method to use
                           1 - symmetric
                           2 - fuel optimization
                           3 - velocity constraint
 n                (1)   Number of samples to use when computing trajectory
 animate          (1)   Flag indicating whether to animate (1) or not (0)
Outputs
 x               (m,n)   m 1xn vectors of x (radial offset)
 y               (m,n)   n 1xn vectors of y (along-track offset)
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
References and(), FFEccDH(), FFEccDMatPeriodic(), FFEccIntConst(), FFEccRMat(), length(), set(), vector(), and zeros().
FFEccTargetTrueAnom()
function FFEccTargetTrueAnom (in e, in nu0, in nOrb)
 after the initial true anomaly.
 Since version 7.
Inputs
 e             (1)  Eccentricity
 nu0           (1)  Initial true anomaly  [rad]
 nOrb         (1,:) Time vector from initial true anomay [orbit periods]
Outputs
 nuF          (1,:)  Vector of final true anomalies
References M2Nu(), Nu2M(), vector(), and WrapPhase().
Referenced by LPEccentricTimeWeight().
FFEccTetrahedronGeometry()
function FFEccTetrahedronGeometry (in nu, in d, in eul, in centroid)
Compute the geometric goals for a formation that achieves a tetrahedron shape at a given true anomaly in an eccentric reference orbit.
 Usage:
 g = FFEccTetrahedronGeometry( nu, d, eul );
Inputs
 nu          (1)  True anomaly where tetrahedron occurs
 d           (1)  Length of each side
 eul        (3,1) Euler angles defining the orientation
 centroid    (1)  Flag. If 1, centroid of first 3 points of tetrahedron
                   is at the origin. Otherwise (default) the first point
                   is at the origin.
Outputs
 g           (.)  Geometric goals data structure
References and(), AnimationGUI(), Demo(), DupVect(), EccGeometry_Structure(), Euler(), FFEccGoals(), FFEccGoals2Hills(), FFEccProp(), FFEccTetrahedronGeometry(), Mag(), NewFig(), set(), Tetrahedron(), and zeros().
Referenced by FFEccGenerateTeamGoals(), and FFEccTetrahedronGeometry().
FFEccYExt()
function FFEccYExt (in e, in D, in dH, in epsilon, in nMax)
Form
 [y,nu] = FFEccYExt( e, D, dH, epsilon, nMax )
Inputs
 e                (1)   Eccentricity
 D               (6,1)  Integration constants computed from i.c.'s
 dH               (1)   Integration constant found by setting H = 0 at nu0
 epsilon          (1)   Angular tolerance [rad]
 nMax             (1)   Maximum number of iterations
Outputs
 y               (1,#)  Extreme values of along-track offsets [km]
 nu              (1,#)  True anomaly where extreme along-track offsets occur [rad]
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
 Since version 7.
References abs(), and(), FFEccAnalyzeShape(), FFEccDDY(), FFEccDH(), FFEccDY(), FFEccGoals(), FFEccProp(), FFEccRMat(), isempty(), length(), Mag(), NewtRaph(), WrapPhase(), and zeros().
Referenced by AutoFormGeometry(), FFEccDDY(), FFEccDY(), and FFEccHills2Goals().
FFEccZExt()
function FFEccZExt (in e, in D, in dH, in epsilon, in nMax)
Compute extreme z-values and associated true anomalies for given relative motion.
 Since version 7.
Form
 [x,nu] = FFEccXExt( e, D, dH, epsilon, nMax );
Inputs
 e                (1)   Eccentricity
 D               (6,1)  Integration constants computed from i.c.'s
 dH               (1)   Integration constant found by setting H = 0 at nu0
 epsilon          (1)   Angular tolerance [rad]
 nMax             (1)   Maximum number of iterations
Outputs
 x               (1,#)  Extreme values of radial oscillation [km]
 nu              (1,#)  True anomaly where extreme values occur [rad]
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
 Since version 7.
Form
 [z,nu] = FFEccZExt( e, D, dH, epsilon, nMax );
Inputs
 e                (1)   Eccentricity
 D               (6,1)  Integration constants computed from i.c.'s
 dH               (1)   Integration constant found by setting H = 0 at nu0
 epsilon          (1)   Angular tolerance [rad]
 nMax             (1)   Maximum number of iterations
Outputs
 z               (1,#)  Extreme values of cross-track amplitudes [km]
 nu              (1,#)  True anomaly where extreme amplitudes occur [rad]
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
References abs(), and(), FFEccDDX(), FFEccDX(), FFEccGoals(), FFEccProp(), FFEccRMat(), isempty(), length(), NewtRaph(), WrapPhase(), and zeros().
Referenced by FFEccDDZ(), FFEccDZ(), and FFEccHills2Goals().
FFIntegrate()
function FFIntegrate (in xRef0, in xRel0, in time, in aH)
 Since version 7.
Form
 [xRef,xRel,xH] = FFIntegrate( xRef0, xRel0, time, aH );
Inputs
 xRef0           (6,1)  Initial ECI position & velocity of reference sat
 xRel0           (6,1)  Initial ECI position & velocity of relative sat
 time            (1,N)  Time vector (seconds)
 aH              (3,N)  Relative accel. in Hill's frame over time [km/s/s]
Outputs
 xRef            (6,N)  Integrated ECI position and velocity of reference
 xRel            (6,N)  Integrated ECI position and velocity of relative
 xH              (6,N)  Relative Hill's frame position and velocity
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
References and(), ECI2Hills(), GetHillsMats(), length(), Mag(), RK4TI(), vector(), and zeros().
Referenced by TestLPCircular(), TestLPEccentric(), and TestLPEccentricGVE().
FFMaintenancePlotter()
function FFMaintenancePlotter (in d, in myDirectory)
 1) First, generate the inputs to "FFMaintenanceSim" by using "FFMaintenanceTests".
 2) Next, run "FFMaintenanceSim" to simulate the formation flying of two spacecraft.
 3) Finally, use this function to plot the results.
 Usage:
 FFMaintenancePlotter( d, myDirectory )
Inputs
 d             (.)   Data structure output from FFMaintenanceSim
 myDirectory   (:)   String name of directory to save figures to
Outputs
 none
References and(), Cross(), FFMaintenancePlotter(), and FFMaintenanceSim().
Referenced by FFMaintenancePlotter().
FFMaintenanceSim()
function FFMaintenanceSim (in simOptions)
*** Notes on Usage ***
 The input data for this function can be created automatically for
 different test cases, using the "FFMaintenanceTests" function.
 To generate a default data structure:
 >> simOptions = FFMaintenanceTests;
 Once this function has run and the outputs have been created, use the
 "FFMaintenancePlotter" function to plot the data.
*** Inputs ***
 Supply the initial state of the reference (el0) and the initial relative
 state (dEl0), define the desired relative motion (goals), the maneuver
 window (window), maneuver parameters (params), the error deadband (deadband),
 the noise (noise), how many orbits to simulate (nOrbits), the number of
 simulation points per orbit (nSPO), the disturbance options (distOpt), the
 cross-sectional area, mass, and the control method to use.
*** Estimated Absolute and Relative States (ECI) ***
 The estimated absolute and relative ECI position and velocity are provided
 by adding noise to the true state. This emulates the data provided by a
 relative navigation unit.
*** Estimated Relative State (Hills) ***
 The estimated relative position and velocity in the Hill's frame is
 computed via a transformation from the estimated absolute and relative
 ECI position and velocity. This computation is performed in the
 "AbsRelECI2Hills" function.
*** Estimated Orbital Elements ***
 The estimated mean orbital elements and mean orbital element differences
 are computed from the estimated absolute and relative ECI position and
 velocity. This computation is performed in the "ECI2MeanElements" function.
*** Desired Orbital Elements ***
 At each step in the simulation, the initial goals are used along with the
 current estimate of the mean orbital elements to compute the desired
 orbital element differences.
*** Desired Relative State (Hills) ***
 The desired element differences are transformed to the Hill's frame,
 defining the desired relative position and velocity.
*** Relative State Error (Hills) ***
 The relative position errors and relative velocity errors are computed by
 comparing the desired and estimated states.
*** Deadband ***
 A constant position deadband is defined in the relative Hill's frame. It
 is a parallelapiped, for each side may have different lengths. If the
 relative state error exceeds 75%% of the deadband "box" in any axis, a
 maintenance maneuver is planned.
*** Maneuver Planning ***
 The "ImpulsiveManeuver" function is called when the deadband is exceeded, and
 when no other maneuver is pending. It is supplied with the current estimate
 of the orbital elements, the formation goals, and a set of parameters.
 It solves for a burn sequence, consisting of the in-plane and out-of-plane
 delta-v's required to eliminate the error in the mean element differences,
 as well as the times at which to apply the delta-v's.
*** Delta-V ***
 A delta-v is introduced by applying a constant thrust over a
 finite amount of time. The times at which thrust is applied is determined
 by the burn sequence, which is provided by the ImpulsiveManeuver function.
Form
 simData = FFMaintenanceSim( simOptions );
Inputs
 simOptions    (.)   Data structure with the following fields:
   - el0            (1,6)  Initial reference orbital elements  (Alfriend format) [a,theta,i,q1,q2,W]
   - dEl0           (1,6)  Initial orbital element differences (Alfriend format)
   - goals           (.)   Goals data structure defining desired relative motion
   - window          (.)   Data structure defining the desired maneuver window
   - params          (.)   Data structure defining several maneuver parameters
   - deadband       (1,3)  x,y,z dimensions of the position error deadband "box"
   - noise          (1,4)  Standard deviation of noise for the following sources:
                        noise(1) - absolute position [m]
                        noise(2) - absolute velocity [m/s]
                        noise(3) - relative position [m]
                        noise(4) - relative velocity [m/s]
   - nOrbits         (1)   Number of orbits to simulate
   - nSPO            (1)   Number of simulation points per orbit
   - distOpt        (1,3)  Disturbance options (flags)
                        (1) solar:  whether to simulate with solar pressure or not
                        (2) drag:   whether to simulate with drag or not
                        (3) J2:     whether to simulate with J2 or not
   - mass           (1,2)  Mass of reference and relative [kg]
   - aera           (1,2)  Cross-sectional area of reference and relative [m^2]
   - controlMethod   (1)   Which control method to use:
                         - closed form solution (1)
                         - linear programming (2)
Outputs
 simData       (.)   Simulation output data structure with the following fields
   - time          (1,:)   Time vector [orbits]
   - fH            (3,:)   Applied thrust in Hills frame [kN]
   - rE            (3,:)   True ECI position of reference
   - vE            (3,:)   True ECI velocity of reference
   - rE_est        (3,:)   Estimated ECI position of reference
   - vE_est        (3,:)   Estimated ECI velocity of reference
   - rH            (3,:)   True Hills-frame relative position
   - vH            (3,:)   True Hills-frame relative velocity
   - rH_est        (3,:)   Estimated Hills-frame relative position
   - vH_est        (3,:)   Estimated Hills-frame relative velocity
   - rH_des        (3,:)   Desired Hills-frame relative position
   - vH_des        (3,:)   Desired Hills-frame relative velocity
   - dElMean       (6,:)   True mean element differences
   - dElMean_est   (6,:)   Estimated mean element differences
   - dElMean_des   (6,:)   Desired mean element differences
   - elRefMean_est (6,:)   Estimated mean elements of reference
   - fDiffDragH    (3,:)   Hills-frame differential drag force
   - fDiffDragE    (3,:)   ECI-frame differential drag force
   - fDiffSolarH   (3,:)   Hills-frame differential solar force
   - fDiffSolarE   (3,:)   ECI-frame differential solar force
   - fDiffJ2H      (3,:)   Hills-frame differential J2 force (apparent)
   - fDiffJ2E      (3,:)   ECI-frame differential J2 force (apparent)
   - deadband      (1,3)   Size of the position error deadband "box" (same as input)
References and(), FFMaintenanceTests(), and RHS().
Referenced by FFMaintenancePlotter(), and FFSimPlotter().
FFMaintenanceTests()
function FFMaintenanceTests (in name)
 Each case has specific data associated with it. You may add new cases
 to this function. This enables you to reproduce specific scenarios.
 Use the output of this function as the input to "FFMaintenanceSim".
 Since version 7.
 Usage:
 simOptions = FFMaintenanceTests( name );
 simOptions = FFMaintenanceTests; %% print cases, return default options
Inputs
 name          (:)   Name of the stored test case
Outputs
 simOptions    (.)   Data structure with the following fields:
   - el0            (1,6)  Initial reference orbital elements  (Alfriend format) [a,theta,i,q1,q2,W]
   - dEl0           (1,6)  Initial orbital element differences (Alfriend format) [a,theta,i,q1,q2,W]
   - goals           (.)   Goals data structure defining desired relative motion
   - window          (.)   Data structure defining the desired maneuver window
   - params          (.)   Data structure defining the several maneuver parameters
   - deadband       (1,3)  x,y,z dimensions of the position error deadband "box"
   - noise          (1,4)  Standard deviation of noise for the following sources:
                        noise(1) - absolute position [m]
                        noise(2) - absolute velocity [m/s]
                        noise(3) - relative position [m]
                        noise(4) - relative velocity [m/s]
   - nOrbits         (1)   Number of orbits to simulate
   - nSPO            (1)   Number of simulation points per orbit
   - distOpt        (1,3)  Disturbance options (flags)
                        (1) solar:  whether to simulate with solar pressure or not
                        (2) drag:   whether to simulate with drag or not
                        (3) J2:     whether to simulate with J2 or not
   - mass           (1,2)  Mass of reference and relative [kg]
   - aera           (1,2)  Cross-sectional area of reference and relative [m^2]
   - controlMethod   (1)   Which control method to use:
                         - closed form solution (1)
                         - linear programming (2)
References and(), Cross(), FFMaintenanceTests(), Geometry_Structure(), Goals2DeltaElem(), PlanningParameters_Structure(), Window_Structure(), and zeros().
Referenced by FFMaintenanceSim(), and FFMaintenanceTests().
FFSim()
function FFSim (in simOptions)
*** Notes on Usage ***
Once this function has run and the outputs have been created, use the "FFSimPlotter" function to plot the data.
*** Inputs ***
 Supply the initial state of the reference (el0) and the initial relative
 state (dEl0), define the desired relative motion (goals), how many
 orbits to simulate (nOrbits), the number of simulation points per orbit
 (nSPO), the disturbance options (distOpt), the cross-sectional area, mass.
*** Estimated Absolute and Relative States (ECI) ***
 The estimated absolute and relative ECI position and velocity are provided
 by adding noise to the true state. This emulates the data provided by a
 relative navigation unit.
*** Estimated Relative State (Hills) ***
 The estimated relative position and velocity in the Hill's frame is
 computed via a transformation from the estimated absolute and relative
 ECI position and velocity. This computation is performed in the
 "AbsRelECI2Hills" function.
*** Estimated Orbital Elements ***
 The estimated mean orbital elements and mean orbital element differences
 are computed from the estimated absolute and relative ECI position and
 velocity. This computation is performed in the "ECI2MeanElements" function.
*** Desired Orbital Elements ***
 At each step in the simulation, the initial goals are used along with the
 current estimate of the mean orbital elements to compute the desired
 orbital element differences.
*** Desired Relative State (Hills) ***
 The desired element differences are transformed to the Hill's frame,
 defining the desired relative position and velocity.
*** Relative State Error (Hills) ***
 The relative position errors and relative velocity errors are computed by
 comparing the desired and estimated states.
 Usage:
 simData = FFSim( simOptions );
Inputs
 simOptions    (.)   Data structure with the following fields:
   - el0            (1,6)  Initial reference orbital elements  (Alfriend format) [a,theta,i,q1,q2,W]
   - dEl0           (1,6)  Initial orbital element differences (Alfriend format)
   - goals           (.)   Goals data structure defining desired relative motion
   - nOrbits         (1)   Number of orbits to simulate
   - nSPO            (1)   Number of simulation points per orbit
   - distOpt        (1,3)  Disturbance options (flags)
                        (1) solar:  whether to simulate with solar pressure or not
                        (2) drag:   whether to simulate with drag or not
                        (3) J2:     whether to simulate with J2 or not
   - mass           (1,2)  Mass of reference and relative [kg]
   - area           (1,2)  Cross-sectional area of reference and relative [m^2]
Outputs
 simData       (.)   Simulation output data structure with the following fields
   - time          (1,:)   Time vector [orbits]
   - rE            (3,:)   True ECI position of reference
   - vE            (3,:)   True ECI velocity of reference
   - rE_est        (3,:)   Estimated ECI position of reference
   - vE_est        (3,:)   Estimated ECI velocity of reference
   - rH            (3,:)   True Hills-frame relative position
   - vH            (3,:)   True Hills-frame relative velocity
   - rH_est        (3,:)   Estimated Hills-frame relative position
   - vH_est        (3,:)   Estimated Hills-frame relative velocity
   - rH_des        (3,:)   Desired Hills-frame relative position
   - vH_des        (3,:)   Desired Hills-frame relative velocity
   - dElMean       (6,:)   True mean element differences
   - dElMean_est   (6,:)   Estimated mean element differences
   - dElMean_des   (6,:)   Desired mean element differences
   - elRefMean_est (6,:)   Estimated mean elements of reference
   - fDiffDragH    (3,:)   Hills-frame differential drag force
   - fDiffDragE    (3,:)   ECI-frame differential drag force
   - fDiffSolarH   (3,:)   Hills-frame differential solar force
   - fDiffSolarE   (3,:)   ECI-frame differential solar force
   - fDiffJ2H      (3,:)   Hills-frame differential J2 force (apparent)
   - fDiffJ2E      (3,:)   ECI-frame differential J2 force (apparent)
See also
FFSimPlotter, AbsRelECI2Hills, ECI2MeanElements, Alfriend2El
References AbsRelECI2Hills(), Alfriend2El(), and(), Cross(), ECI2MeanElements(), FFSimPlotter(), Geometry_Structure(), get(), Goals2DeltaElem(), length(), vector(), and zeros().
Referenced by FFSimPlotter().
FFSimPlotter()
function FFSimPlotter (in d, in myDirectory)
Finishes by setting up an animation.
 Usage:
 FFSimPlotter( d, myDirectory );
Inputs
 d             (.)   Data structure output from FFMaintenanceSim
 myDirectory   (:)   String name of directory to save figures to
Outputs
 none
References and(), Cross(), FFMaintenanceSim(), FFSim(), NewFig(), and set().
Referenced by FFSim().
FindDriftTerm()
function FindDriftTerm (in p, in t)
Find the "deadband over drift rate sigma" term that results in the specified probability "p" of NOT reaching the deadband by time "t".
Form
 [n,foundSoln] = FindDriftTerm( p, t )
Inputs
 p          (1)      Probability that the deadband will NOT be reached
 t          (1)      Time horizon [orbits]
Outputs
 n           (1)     Deadband over drift rate sigma term
 foundSoln   (1)     Flag indicating whether a solution was found or not
References abs(), and(), Demo(), vector(), and zeros().
Referenced by RelativeVelocityError().
FindMinSet()
function FindMinSet (in mat)
 the diagonal sum.
 This function is valid only up to size 8x8 matrices.
 Since version 7.
Form
 [order,minSum] = FindMinSet( mat )
Inputs
 mat           (n,n)     Square matrix
Outputs
 order         (1,n)     Order of columns (assuming rows go 1 - n)
 minSum         (1)      Minimum total cost
References Demo(), FindMinSet(), Square(), square(), and zeros().
Referenced by FindMinSet(), and OptimalAssignment().
FormationDesignGUI()
function FormationDesignGUI (in action, in modifier)
Use this tool to design the trajectories and the team organization of multiple spacecraft formations.
Initialize the GUI by typing its name:
 FormationDesignGUI
For detailed instructions on how to use the GUI, click on "Help" from the figure menu, or type:
 FormationDesignGUI('help')
You may load the reference orbital elements from the command line by typing:
 FormationDesignGUI( 'load orbit', el )
 where "el" is a 1x6 vector of orbital elements: [a, i, W, w, e, M]
 a  -  semi-major axis   [km]
 i  -  inclination       [deg]
 W  -  right ascension   [deg]
 w  -  perigee           [deg]
 e  -  eccentricity
 M  -  mean anomaly      [deg]
Form
 FormationDesignGUI( action, modifier );
Inputs
 action           (:)  Action to be taken by the GUI
 modifier         (:)  Accompnying data
Outputs
 none
References and(), FormationDesignGUI(), Initialize(), and vector().
Referenced by FormationDesignGUI().
Frenet2Hills()
function Frenet2Hills (in xF, in e, in nu, in n)
Form
 xH = Frenet2Hills( xF, e, nu, n );
 Note: The number of columns of "nu" and "xF" must be equal if they both
 have more than ONE column.
Inputs
 xF            (M,:)  Relative state in Frenet frame [km] (M = 3 or 6)
 e             (1,1)  Eccentricity
 nu            (1,:)  True anomaly [rad]
 n             (1,1)  Orbit rate [rad/s]. Optional.
                        Uses time-derivatives if rate provided.
                        Uses nu-derivatives is NOT provided.
Outputs
 xH            (M,N)   Hills frame state
                          N = number of columns of nu or xF, whichever
                              is greater
References and(), Cross(), length(), NuDot(), RotMat(), and zeros().
Referenced by FFEccFrenet2Goals().
GenerateTeamGoals()
function GenerateTeamGoals (in el0, in fType, in fSize, in nRels, in teamID, in angRes)
Enter a single input, 'list', to see a list of all supported types.
 Usage:
 GenerateTeamGoals('list')
 teamGoals = GenerateTeamGoals( el0, fType, fSize, nRels, teamID, angRes );
Inputs
 el0           (1,6)  reference orbital elements   [a,th,i,q1,q2,W]
 fType          (1)   formation type
 fSize          (1)   formation size
 nRels          (1)   number of relatives in the team
 teamID         (1)   unique integer team ID
 angRes         (1)   angular resolution for discretized search with variable states [rad]
Outputs
 teamGoals      (.)   Team Goals data structure, with geometric goals
                      for all unique states, and corresponding constraints
See also
: TeamGoals_Structure
References and(), CirclePhase(), Constraints_Structure(), DeltaElem2Goals(), Demo(), EllipsePhase(), GenerateTeamGoals(), Geometry_Structure(), get(), Goals2DeltaElem(), isempty(), PCGoals(), set(), TeamGoals2Geom(), TeamGoals_Structure(), ViewRelativeMotion(), WrapPhase(), and zeros().
Referenced by DFFSim(), FFEccGenerateTeamGoals(), and GenerateTeamGoals().
GenerateTimeVector()
function GenerateTimeVector (in d, in tF, in nPts)
 (for an eccentric orbit)
Form
 [t,M,nu] = GenerateTimeVector(d,tF,nPts)
Inputs
 d          (:)    Collision data structure
 tF        (1,1)   Final propagated time
 nPts      (1,1)   Number of discretization points per orbit
Outputs
 t         (1,n)   Time vector
 M         (1,n)   Mean anomaly vector
 nu        (1,n)   True anomaly vector
References GenerateTimeVector(), and vector().
Referenced by GenerateTimeVector().
Geometry_Structure()
function Geometry_Structure (in nU)
Form
 g = Geometry_Structure( nU )
Inputs
 nU           (1)    Number of geometry structures = # of unique states
Outputs
 g            (.)    Geometry data structure with fields:
                        - y0,   along-track offset
                        - aE,   semi-major axis of relative ellipse
                        - beta, phase on relative ellipse
                        - zInc, cross-track amplitude - inclination
                        - zLan, cross-track amplitude - long. of asc. node
References Initialize().
Referenced by CollisionDemoSimStruct(), CollisionSimStruct(), DeltaVAnalysis(), DemoManeuverCommandList(), FFEccGenerateTeamGoals(), FFMaintenanceTests(), FFSim(), GenerateTeamGoals(), GeometryEcc2Circ(), IsCircGeom(), RotateState(), ScaleState(), SimpleManeuverCommandList(), TeamGoals_Structure(), TestControlCommandList(), and ViewRelativeMotion().
GeometryCirc2Ecc()
function GeometryCirc2Ecc (in w, in gCirc)
 Usage:
 gEcc = GeometryCirc2Ecc( w, gCirc )
Inputs
 w             (1)   Argument of perigee [rad]
 gCirc         (.)   Geometric goals data structure, for circular orbits
                     .y0
                     .aE
                     .beta
                     .zInc
                     .zLan
Outputs
 gEcc          (.)   Geometric goals data structure, for eccentric orbits
                     .y0
                     .xMax      (aE/2)
                     .nu_xMax
                     .zMax
                     .nu_zMax   (sqrt(zInc^2+zLan^2))
See also
: CirclePhase
References CirclePhase(), and EccGeometry_Structure().
GeometryEcc2Circ()
function GeometryEcc2Circ (in w, in gEcc)
 Since version 7.
 Usage:
 gCirc = GeometryEcc2Circ( w, gEcc );
Inputs
 w             (1)   Argument of perigee [rad]
 gEcc          (.)   Geometric goals data structure, for eccentric orbits
Outputs
 gCirc         (.)   Geometric goals data structure, for circular orbits
References EllipsePhase(), and Geometry_Structure().
GeometryPlugin()
function GeometryPlugin (in fig, in pos, in bColor, in name)
 This function is called while initializing the Formation Design GUI.
Form
 d = GeometryPlugin( fig, pos, bColor, name );
Inputs
 fig              (1)   Handle to Formation Design GUI figure
 pos             (1,2)  Position data of GUI
 bColor          (1,3)  Background color of GUI
 name            (1,3)  m-file name of GUI for callbacks
Outputs
 d                (.)   Data structure of handles to "Geometry" panel controls
References GeometryPlugin(), and NewFig().
Referenced by GeometryPlugin().
GetHillsMats()
function GetHillsMats (in r0, in v0, in mu)
This function takes the position and velocity of a satellite in the ECI frame, and returns the A and Adot matrices used for transformation to the Hills frame. mu is needed to compute Adot but not for A. The matrices are used in the following equations:
 rH = A*(r1-r0);
 vH = A*(v1-v0) + Adot*(r1-r0);
Form
 [A, Adot] = GetHillsMats( r0, v0, mu )
Inputs
 r0      (3,1)   Position ECI frame
 v0      (3,1)   Velocity ECI frame
 mu      (1,1)   Gravitational parameter (default Earth)
Outputs
 A       (3,3)   Rotation matrix (position)
 Adot    (3,3)   Rotation matrix (velocity)
                 Equal to -Cross( OrbRate(Mag(r0)), A )
References and(), Cross(), Equal(), Mag(), OrbRate(), RHS(), and RV2El().
Referenced by FFIntegrate(), RVOrbGenDV(), SafeGuidanceSim(), and TestFFEccLinOrb().
GetLVLHMats()
function GetLVLHMats (in ro, in vo)
This function takes the position and velocity of a satellite in the ECI frame, and returns the A and Adot matrices used for transformation to the LVLH frame. They are used in the following equations:
 rL = A*(r1-r0);
 vL = A*(v1-v0) + Adot*(r1-r0);
Form
 [A, Adot] = GetLVLHMats( ro, vo )
Inputs
 ro              (3,1) r, ECI frame
 vo              (3,1) v, ECI frame
Outputs
 A               (3,3) Rotation matrix (position)
 Adot            (3,3) Rotation matrix (velocity)
                         Equal to -cross( orbrate(mag(ro), A )
References and(), Cross(), Equal(), RHS(), RV2El(), and Unit().
Goals2DeltaElem()
function Goals2DeltaElem (in el0, in goals, in J2)
Computes differences given the formation flying "goals" and the measured orbital elements.
Form
 dEl = Goals2DeltaElem( el0, goals, J2 );
Inputs
 el0             (1,6)     Measured orbital elements (Alfriend format) [a,theta,i,q1,q2,W]
 goals            (.)      Geometric goals data structure with following fields:
   - y0          (1,:)        along-track offset                             [km]
   - aE          (1,:)        semi-major axis of relative ellipse            [km]
   - beta0       (1,:)        angle on ellipse at perigee                   [rad]
   - zInc        (1,:)        cross-track amplitude due to inclination diff  [km]
   - zLan        (1,:)        cross-track amplitude due to right ascen diff  [km]
 J2               (1)      Size of the J2 perturbation (default 0)
Outputs
 dEl   (:,6)     desired orbital element differences
References and(), Goals2Hills(), and Hills2DeltaElem().
Referenced by AnalyzeVariableTimeDV(), DeltaVAnalysis(), EstimateCost(), FFMaintenanceTests(), FFSim(), GenerateTeamGoals(), LPvsCF(), and SafeGuidanceSimInit().
Goals2Hills()
function Goals2Hills (in varargin)
Computes the desired relative position and velocity in Hills frame, given the formation flying geometric "goals" and the reference orbital elements.
Form
 xH = Goals2Hills( el0, goals )
 xH = Goals2Hills( n, theta, goals )
Inputs
 el0             (1,6)     Reference orbital elements (Alfriend format) [a,th,i,q1,q2,W]
   -or-
 n                (1)      Mean orbit rate [rad/sec]
 theta            (1)      True latitude   [rad]
 goals            (.)      Geometric goals data structure with following fields:
 - y0          (1,:)        along-track offset                             [km]
 - aE          (1,:)        semi-major axis of relative ellipse            [km]
 - beta        (1,:)        angle on ellipse at perigee                   [rad]
 - zInc        (1,:)        cross-track amplitude due to inclination diff  [km]
 - zLan        (1,:)        cross-track amplitude due to right ascen diff  [km]
Outputs
 xH              (6,:)     Hills frame position and velocity
                              [km; km; km; km/s; km/s; km/s]
                              [ x;  y;  z;   Vx;   Vy;   Vz]
See also
: FFEccGoals2Hills, TransformGeom2Hills
References: Mueller, J. and M. Brito,"A Distributed Flight Software Design for Satellite Formation Flying Control," presented at the AIAA Space 2003 Conference, Long Beach, CA, September 2003.
References and(), FFEccGoals2Hills(), and TransformGeom2Hills().
Referenced by AddGoals(), AutoFormGeometry(), FFEccGenerateTeamGoals(), Goals2DeltaElem(), HillsFramePlot(), InitializeFormation(), IsDuplicateState(), IterativeImpulsiveManeuver(), LPCircularTimeWeight(), LPvsCF(), SubGoals(), TestLPCircular(), TransformGeom2Hills(), and ViewFormation().
Hexahedron()
function Hexahedron (in d, in eul)
 Call with no outputs to see a picture in 3D.
 Since version 7.
 Usage:
 p = Hexahedron( d, eul )
Inputs
 d           (1)  Length of each side  [length]
 eul        (1,3) Euler angles defining orientation
Outputs
 p          (3,5)  [x;y;z] coordinates of the five corners
References and(), Eul2Q(), Euler(), Hexahedron(), length(), QForm(), set(), and zeros().
Referenced by FFEccHexahedronGeometry(), and Hexahedron().
Hills2DeltaElem()
function Hills2DeltaElem (in el0, in xH, in J2)
Compute differences from the Hills frame state and the reference orbital elements accounting for the J2 perturbation. Not valid for near-equatorial orbits.
Inputs
 el0           (1,6)  chief orbital elements         [a,th,i,q1,q2,W]
 xH            (6,:)  relative position and velocity in Hills frame [km; km/s]
 J2             (1)   size of the J2 perturbation
Outputs
 dEl           (:,6)  orbital element differences:   [a,th,i,q1,q2,W]
 m             (6,6)  transformation matrix
Reference: D. Gim and K. Alfriend, State transition matrix of relative motion for the perturbed noncircular reference orbit, Journal of Guidance, Control, and Dynamics, vol. 26, no. 6, pp. 956971, 2003
References abs(), and(), DeltaElem2Hills(), Demo(), Hills2DeltaElem(), vector(), and zeros().
Referenced by CheckDeltaVs(), DeltaElem2Hills(), Goals2DeltaElem(), Hills2DeltaElem(), and InitializeFormation().
Hills2ECI()
function Hills2ECI (in x0, in xH, in mu)
Form
 x1 = Hills2ECI( x0, xH )
Inputs
 x0  (6,1) [r;v] ECI frame
 xH  (6,n) [r;v] Hills frame
Outputs
 x1  (6,n) [r;v] ECI frame
Referenced by CompareHills(), FFEccHills2DeltaElem(), ProjCirc(), SafeGuidanceSim(), TestFFEccLinOrb(), TestLPCircular(), TestLPEccentric(), and TestLPEccentricGVE().
Hills2Frenet()
function Hills2Frenet (in xH, in e, in nu, in n)
 Since version 7.
 Usage:
 xF = Hills2Frenet( xH, e, nu );
 Note: The number of columns of "nu" and "xH" must be equal if they both
 have more than ONE column.
Inputs
 xH            (M,:)  Relative state in Hills frame [km] (M = 3 or 6)
 e             (1,1)  Eccentricity
 nu            (1,:)  True anomaly [rad]
 n             (1,1)  Orbit rate [rad/s]. Optional.
                        Uses time-derivatives if provided.
                        Uses nu-derivatives is NOT provided.
Outputs
 xF            (M,N)   Local-vertical / Local-horizontal
                          N = number of columns of nu or xH, whichever
                              is greater
References and(), Cross(), length(), NuDot(), RotMat(), and zeros().
Hills2Goals()
function Hills2Goals (in varargin)
Reconstructs the geometric goals from the relative position and velocity in Hills frame. The reference orbital elements are also required.
Form
 goals = Hills2Goals( el0, xH );
 -or-
 goals = Hills2Goals( n, theta, xH );
Inputs
 el0             (1,6)     Reference orbital elements (Alfriend format) [a,theta,i,q1,q2,W]
 xH              (6,:)     Hills frame position and velocity  [km;km;km; km/s;km/s;km/s]
                              [x;y;z;Vx;Vy;Vz]
Outputs
 goals            (.)      Geometric goals data structure with following fields:
   - y0          (1,:)        along-track offset                             [km]
   - aE          (1,:)        semi-major axis of relative ellipse            [km]
   - beta0       (1,:)        angle on ellipse at perigee                   [rad]
   - zInc        (1,:)        cross-track amplitude due to inclination diff  [km]
   - zLan        (1,:)        cross-track amplitude due to right ascen diff  [km]
References: Mueller, J. and M. Brito,"A Distributed Flight Software Design for Satellite Formation Flying Control," presented at the AIAA Space 2003 Conference, Long Beach, CA, September 2003.
References and().
Referenced by AddGoals(), DeltaElem2Goals(), IterativeImpulsiveManeuver(), and SubGoals().
Hills2LVLH()
function Hills2LVLH (in xH)
 Since version 7.
Form
 xL = Hills2LVLH( xH )
Inputs
 xH               (6,:) [r;v] Hills frame
Outputs
 xL               (6,:) [r; v] LVLH frame
References vector().
Referenced by ECI2LVLH().
HillsEqns()
function HillsEqns (in Xo, in w, in t, in flag)
Form
 X = HillsEqns( Xo, w, t, flag )
Inputs
 Xo              (6,nSC)     Initial state in Hills frame, length unit [L], velocity unit [L/sec]
                              * each column is the state of a s/c, [x; y; z; xdot; ydot; zdot]
 w                 (1)      Orbital Rate (rad/s)
 t                 (:)      time vector (sec)
 flag             (1,1)     If entered, the output is formatted as a (6,nSC) matrix.
Outputs
 X               (nSC).r    Position field, (3,:) matrix
                      .v    Velocity field, (3,:) matrix
                      .t    Time field, (1,:) vector
References length(), vector(), and zeros().
Referenced by AutoFormGeometry(), CheckDeltaVs(), CompareHills(), ImpulsiveLPManeuver(), PositionDeltaV(), TestLPCircular(), and ViewRelativeMotion().
HillsEqnsSLO()
function HillsEqnsSLO (in Xo, in w, in t)
 Relative state expressed in Spacecraft-Local-Orbit (SLO) coordinate frame.
 Since version 10.
Form
 X = HillsEqnsSLO( Xo, w, t )
Inputs
 Xo              (6,nSC)    Initial state in SLO frame, length unit [L], velocity unit [L/sec]
                              * each column is the state of a s/c, [x; y; z; xdot; ydot; zdot]
 w                 (1)      Orbital Rate (rad/s)
 t                 (:)      time vector (sec)
 flag             (1,1)     If entered, the output is formatted as a (6,nSC) matrix.
Outputs
 X               (6*nSC,:)  Position and velocity over time
References and(), length(), vector(), and zeros().
Referenced by AlongTrackMotion(), EllipseDeltaV(), and SafeGuidance().
HillsFramePlot()
function HillsFramePlot (in rH, in figH, in color)
 Usage:
 figH = HillsFramePlot( geom );
 figH = HillsFramePlot( rH );
 figH = HillsFramePlot( rH, [], color );
 HillsFramePlot( rH, figH );
 HillsFramePlot( rH, figH, color );
Inputs
 rH            (3,:)  Relative position in Hills frame [km]
    - OR -
 geom           (.)   Geometry data structure
 figH           (1)   Figure handle (optional)
 color          (:)   Color of projection area
Outputs
 figH           (1)   Figure handle
References AddView(), AddZoom(), and(), Goals2Hills(), IsCircGeom(), isempty(), RotateState(), set(), and zeros().
Referenced by ImpulsiveManeuver().
ImpulsiveLPManeuver()
function ImpulsiveLPManeuver (in state, in goals, in window, in parameters)
 Format:
 [maneuver,maxDV] = ImpulsiveLPManeuver( state, goals, window, parameters );
Inputs
 state       (.)  Data structure of the orbit state with following fields
                    - el     Measured mean orbital elements of reference
                    - xH     Measured Hills-frame state: [x;y;z;xdot;ydot;zdot]
                    - mass   Spacecraft mass             [kg]
                    - tM     Timetag of measurement      [sec]
 goals       (.)  Data structure of geometric goal information.
 Describes the desired trajectory.
 window      (.)  Data structure of commanded time window with following fields
 - startTime      Earliest possible start time                [sec since 1970]
 - nOrbMin        Minimum number of orbits maneuver may last  [orbits]
 - nOrbMax        Maximum number of orbits maneuver may last  [orbits]
 - nManeuvers     Number of maneuvers to search over
 - timeWeightExp  Time-weighting exponent (greater than 0)
 parameters  (.)  Data structure of planning parameters with following fields
 - fNom         Nominal Thruster force                             [kN]
 - dTMax        Maximum allowable burn duration                    [sec]
 - horizon      Minimum time between planning and first burn       [sec]
 - tDelayOOP    Minimum time between final IP burn and OOP burn    [sec]
 - nSPOCoarse   Number of samples per orbit for LP (coarse computation)
 - nSPOFine     Number of samples per orbit for LP (fine computation)
Outputs
 maneuver    (.)  Maneuver data structure with following fields
                    - t0           Earliest burn start time
                    - tF           Latest burn finish time
                    - nBurns       Number of burns required
                    + burnData[]   Array of burn data structures with following fields
                         - t   Burn start time   [sec since 1970]
                         - dT  Burn duration     [sec]
                         - dV  Delta-V           [km/s]
                         - uX  unit x Hills direction
                         - uY  unit y Hills direction
                        - uZ  unit z Hills direction
 maxDV       (1)  The maximum delta-v of the sequence
References and(), Demo(), FFEccGoals2Hills(), HillsEqns(), ImpulsiveLPManeuver(), Initialize(), IsEccGeom(), LPCircularTimeWeight(), M2Nu(), Mag(), Maneuver_Structure(), OrbRate(), Parameter(), Period(), PlanningParameters_Structure(), set(), Trajectory(), and Window_Structure().
Referenced by ImpulsiveLPManeuver(), and IterativeImpulsiveManeuver().
ImpulsiveManeuver()
function ImpulsiveManeuver (in state, in goals, in window, in parameters)
 Gauss' variational equations.
Inputs
 state         (.)  Data structure of the orbit state with following fields
                    - el           Measured mean orbital elements of reference [a,i,W,w,e,M]
                    - elA          Alfriend format of elements                 [a,lat,i,q1,q2,W]
                    - xH           Measured Hills-frame state: [x;y;z;xdot;ydot;zdot]
                    - mass         Spacecraft mass             [kg]
                    - tM           Timetag of measurement      [sec]
 goals         (.)  Data structure of geometric goal information.
 Describes the desired trajectory.
 window        (.)  Data structure of commanded time window with following fields
 - startTime       Earliest possible start time                    [sec since 1970]
 - nOrbMin         Minimum number of orbits maneuver may last      [orbits]
 - nOrbMax         Maximum number of orbits maneuver may last      [orbits]
 - nManeuvers      Number of maneuvers to search over
 - timeWeightExp   Time-weighting exponent (greater than 0)
 parameters    (.)  Data structure of planning parameters with following fields
 - fNom         Nominal Thruster force                             [kN]
 - dTMax        Maximum allowable burn duration                    [sec]
 - horizon      Minimum time between planning and first burn       [sec]
 - tDelayOOP    Minimum time between final IP burn and OOP burn    [sec]
 - nSPOCoarse   Number of samples per orbit for LP (coarse computation)
 - nSPOFine     Number of samples per orbit for LP (fine computation)
Outputs
 maneuver          (.)  Maneuver data structure with following fields
                        - t0           Earliest burn start time
                        - tF           Latest burn finish time
                        - nBurns       Number of burns required
                        + burnData[]   Array of burn data structures with following fields
                           - t   Burn start time   [sec since 1970]
                           - dT  Burn duration     [sec]
                           - dV  Delta-V           [km/s]
                           - uX  unit x Hills direction
                           - uY  unit y Hills direction
                           - uZ  unit z Hills direction
 maxDV             (1)  The maximum delta-v of the sequence
References: Mueller, J. and M. Brito,"A Distributed Flight Software Design for Satellite Formation Flying Control," presented at the AIAA Space 2003 Conference, Long Beach, CA, September 2003.
References and(), Demo(), El2Alfriend(), HillsFramePlot(), ImpulsiveManeuver(), InitializeFormation(), Mag(), Parameter(), PCGoals(), and Trajectory().
Referenced by CollisionInit(), ImpulsiveManeuver(), and IterativeImpulsiveManeuver().
InitializeCostMatrix()
function InitializeCostMatrix (in teamGoals, in nRelatives)
 Since version 7.
Form
 f = InitializeCostMatrix( teamGoals, nRelatives );
Inputs
 teamGoals       (.)    Data structure of team goals
 nRelatives      (1)    Number of relatives in the team
Outputs
 f              (:,N)   Blank cost matrix, where N = nRelatives
References Demo(), InitializeCostMatrix(), TeamGoals_Structure(), and zeros().
Referenced by InitializeCostMatrix(), and PopulateCostMatrix().
InitializeFormation()
function InitializeFormation (in el0, in goals)
Generate the initial orbital elements for a cluster of spacecraft given the geometric goals and the reference orbital elements.
Form
 [el, dEl, xH] = InitializeFormation( el0, goals )
Inputs
 el0              (1)      Initial  elments of the reference [Alfriend format]
 goals            (.)      Geometric goals data structure of all relative
                            spacecraft with the following fields:
   - y0          (1,N)        along-track offset                             [km]
   - aE          (1,N)        semi-major axis of relative ellipse            [km]
   - beta0       (1,N)        angle on ellipse at perigee                   [rad]
   - zInc        (1,N)        cross-track amplitude due to inclination diff  [km]
   - zLan        (1,N)        cross-track amplitude due to right ascen diff  [km]
Outputs
 el           (N+1,6)    Orbital elements of all spacecraft [Alfriend format]
                          NOTE: First row is the reference element set
 dEl           (N,6)     Orbital element differences of all relative spacecraft
 xH            (6,N)     Hill's frame position and velocity of all relative
                          spacecraft [x;y;z; Vx;Vy;Vz]      [km; km/s]
References and(), Demo(), El2Alfriend(), Goals2Hills(), Hills2DeltaElem(), Initialize(), InitializeFormation(), length(), OrbElemDiff(), set(), and zeros().
Referenced by CollisionDemoSimStruct(), CollisionInit(), CollisionSimStruct(), ImpulsiveManeuver(), and InitializeFormation().
InPlane()
function InPlane (in meas_elem, in delta_elem, in accNom, in dTMin, in nOrbMin, in nOrbMax, in horizon)
 Since version 7.
Inputs
 meas_elem             (1,6)  Reference orbital elements             (Alfriend format)
                                                                     [a,theta,i,q1,q2,W]
 delta_elem            (:,6)  Error in orbital element differences   (Alfriend format)
 accNom                 (1)   Nominal acceleration                   [km/s/s]
 dTMin                  (1)   Minimum achievable burn duration       [sec]
 nOrbMin                (1)   Minimum number of orbits maneuver may last
 nOrbMax                (1)   Maximum number of orbits maneuver may last
 horizon                (1)   Minimum amount of time required prior to first burn [sec]
Outputs
 burnData               (.)   Array of burn data structures with burn times,
                                 durations, magnitudes and directions.
 t0                     (1)   First burn time               [sec from meas time]
 tF                     (1)   Final burn time               [sec from meas time]
 nBurns                 (1)   Number of burns required
Referenced by LPvsCF().
IsCircGeom()
function IsCircGeom (in geom)
 Note:   Not necessary in C++, as overloaded functions with different data
 structure inputs will be used.
 Usage:
 a = IsCircGeom( geom );
Inputs
 geom          (.)   Geometry data structure
Outputs
 a             (1)   Flag (1 if circular geometric struct, 0 if not)
References Geometry_Structure(), isempty(), length(), and StringMatch().
Referenced by AddGoals(), AutoFormGeometry(), HillsFramePlot(), SubGoals(), TransformGeom2Hills(), and ViewGeometry().
IsDuplicateState()
function IsDuplicateState (in g0, in g1, in posErrTol, in velErrTol)
Form
 isDup = IsDuplicateState( g0, g1, posErrTol, velErrTol );
Inputs
 g0             (.)     First set of geometric goals
 g1             (.)     Second set of geometric goals
 posErrTol      (1)     Position error tolerance [m]
 velErrTol      (1)     Velocity error tolerance [m/s]
Outputs
 isDup          (1)     Flag indicating whether the states are duplicates (1) or not (0)
References CirclePhase(), Goals2Hills(), Mag(), RotateState(), and set().
IsEccGeom()
function IsEccGeom (in geom)
 Note:   Not necessary in C++, as overloaded functions with different data
 structure inputs will be used.
 Since version 7.
 Usage:
 a = IsEccGeom( geom );
Inputs
 geom          (.)   Geometry data structure
Outputs
 a             (1)   Flag (1 if eccentric geometric struct, 0 if not)
References EccGeometry_Structure(), isempty(), and length().
Referenced by AddGoals(), ImpulsiveLPManeuver(), SubGoals(), and TransformGeom2Hills().
ISLMessage_Structure()
function ISLMessage_Structure (in n)
 Since version 7.
Form
 msg = ISLMessage_Structure( n );
Inputs
 n              (1)      Number of messages (default is 1)
Outputs
 msg            (.)      Message data structure
IterativeImpulsiveManeuver()
function IterativeImpulsiveManeuver (in state, in goals, in window, in parameters)
Computes the delta-v's required to implement a formation flying maneuver for a single spacecraft. The desired relative state is iteratively recomputed, bringing the desired state closer to the current state, until the largest single delta-v in the maneuver is under the maximum limit.
A fixed thrust actuator is assumed when converting delta-v to burn duration. Algorithms do not account for gravitational perturbations or disturbances.
 Usage:
 [maneuver, foundSoln, resetGoals] = IterativeImpulsiveManeuver( state, goals, window, parameters );
Inputs
 state             (.)  Data structure of the orbit state with following fields
                        - el           Measured mean orbital elements of reference, Alfriend format: [a,i,W,w,e,M]
                        - xH           Measured relative state in Hills frame
                        - mass         Spacecraft mass                              [kg]
                        - tM           Timetag of measurement                       [sec]
 goals             (.)  Geometric goals describing desired relative periodic trajectory
 window            (.)  Data structure of commanded time window with following fields
 - startTime       Earliest possible start time                    [sec since 1970]
 - nOrbMin         Minimum number of orbits maneuver may last      [orbits]
 - nOrbMax         Maximum number of orbits maneuver may last      [orbits]
 - nManeuvers      Number of maneuvers to search over
 - timeWeightExp   Time-weighting exponent (greater than 0)
 parameters        (.)  Data structure of planning parameters with following fields
 - fNom         Nominal Thruster force                             [kN]
 - dTMax        Maximum allowable burn duration                    [sec]
 - horizon      Minimum time between planning and first burn       [sec]
 - tDelayOOP    Minimum time between final IP burn and OOP burn    [sec]
 - nSPOCoarse   Number of samples per orbit for LP (coarse computation)
 - nSPOFine     Number of samples per orbit for LP (fine computation)
 - maxDeltaV    Maximum delta-v
Outputs
 maneuver          (.)  Maneuver data structure with following fields
                        - t0           Earliest burn start time
                        - tF           Latest burn finish time
                        - nBurns       Number of burns required
                        + burnData[]   Array of burn data structures with following fields
                           - t   Burn start time   [sec since 1970]
                           - dT  Burn duration     [sec]
                           - dV  Delta-V           [km/s]
                           - uX  unit x Hills direction
                           - uY  unit y Hills direction
                           - uZ  unit z Hills direction
 foundSoln         (1)  Flag indicating whether a solution was found or not
 resetGoals        (1)  Flag indicating whether the goals were reset or not
References abs(), and(), Demo(), El2Alfriend(), FFEccGoals2Hills(), FFEccHills2Goals(), Goals2Hills(), Hills2Goals(), ImpulsiveLPManeuver(), ImpulsiveManeuver(), IterativeImpulsiveManeuver(), length(), Parameter(), PCGoals(), PlanningParameters_Structure(), and Window_Structure().
Referenced by CheckDeltaVs(), DFFSim(), and IterativeImpulsiveManeuver().
JD2SS1970()
function JD2SS1970 (in jD)
1, 1970.
 Since version 7.
Form
 s = JD2UTC( jD );
Inputs
 jD         Julian date
Outputs
 s          Seconds since 00:00:00 GMT, Jan. 1, 1970.
Laguerre()
function Laguerre (in p, in xGuess)
There is a fix in place to force the return of real roots as Laguerre finds any root, real or imaginary.
Form
 x = Laguerre(p, xGuess)
Inputs
p (1,7) Vector containing the coefficients of the polynomial. The coefficients are ordered as follows Sum p[i] x^i, i=0...mP xGuess (1) Initial guess for the root
Outputs
 x         (1)        root
Reference: http://mathworld.wolfram.com/LaguerresMethod.html
References Laguerre().
Referenced by DistantPtToEll(), Laguerre(), and MinDEllipsoid().
LargeFormationControl()
function LargeFormationControl (in x0, in d)
LargeFormationControl computes the control for a large formation. Control is respect to the origin
LargeFormationControt for a demo.
Form
 [x,a] = LargeFormationControl( x0, d )
Inputs
 r   (6,1)   Initial state of the center
 d   (.)     Input data structure
Outputs
 xP  (6*n,:) States for each spacecraft
 aP  (3*n,:) Acceleration each spacecraft
 t   (1,:)   Corresponding times (s)
References close(), DefaultDataStructure(), Demo(), LargeFormationControl(), Plot2D(), Plot3DOrbit(), RHS(), RK4(), TimeDisplay(), TimeLabl(), and zeros().
Referenced by LargeFormationControl().
LFState()
function LFState (in d, in nSC, in order)
Computes the position and velocity of a satellite in the Hills frame for a leader/follower formation given the distance from the center (d), the number of spacecraft (nSC), and the order in the line.
Form
 state = LFState( d, nSC, order )
Inputs
 d      (1,1)     Distance from reference point (km)
 nSC     (1,1)     Number of spacecraft
 order   (1,1)     Order in the line
Outputs
 state  (6,1)    Final state for the spacecraft in Hill's frame
References and(), and zeros().
LinOrbLQG()
function LinOrbLQG (in el, in QG, in RG)
Outputs
6 states
6 inputs (Hills frame pos & vel)
3 outputs (Hills frame acceleration)
Form
 [aK,bK,cK,dK] = LinOrbLQG( el, QG, RG )
Inputs
 el     (1,6)    Orbital Elements
 QG       (1)     Scalar estimator gain (make small)
 RG       (1)     Scalar regulator gain (make big)
Outputs
 aK     (6,6)
 bK    (6,12)
 cK     (3,6)
 dK    (3,12)
References and(), FFEccLinOrb(), LinOrb(), M2Nu(), OrbRate(), QCE(), QCR(), statespace(), and zeros().
Referenced by DFFControlLaw().
LPCircular()
function LPCircular (in x0, in xF, in n, in duration, in dT, in constraintType, in maxConstraint)
Compute thrust to go from an initial state x0 to a final state xF in the Hill's frame. Simplex is used to optimize the thrust. Algorithm assumes a circular reference orbit and does not account for disturbances.
A control system can be expressed in its discrete state-space form as:
 X(k+1)      = AX(k) + BU(k)
 Y(k)        = CX(k)
where X is state , U is control, Y is output. For the nth timestep, this can be rewritten as:
 X(n)        = A^n*X(0) + [A^(n-1)B   A^(n-2)B ..... B]u
 where u     = [ U(0)' U(1)' ..... U(n-1)']'
For a fully controllable and observable system,
 Y(n) = X(n) = A^n*X(0) + pu where p = [A^(n-1)B A^(n-2)B ... B]
 error       >= |Y(n) - Y(desired)|  = A^n*X(0) + pu - Y(desired)
The Simplex problem (minimise cu(cost) such that au <= b) and u >= 0 can now be posed as
 [-p; p]u    <= [error + A^n*X(0) - Y(desired); error - A^n*X(0) + Y(desired)]
In case of an Equality Constraint with 0 error, this reduces to
 [-p]u        =  A^n*X(0) - Y(desired)
Note: The constraintType determines whether it is an equality technological constraint(au = b, flag: 0) or an inequality technological constraint(au <= b, flag: 1)
u are called 'decision variables', in this case thrust vector. Since u is unrestricted in sign (u can be positive and negative), we split u into two parts: u=up-um, where up>=0 and um>=0.
Form
 [aC,t,exitFlag] = LPCircular(x0, xF, n, duration, dT, constraintType, maxConstraint)
Inputs
 x0               (6,1) Initial state in Hill's frame
 xF               (6,1) Final state in Hill's frame
 n                 (1)  Reference orbit rate (rad/sec)
 duration          (1)  Maneuver duration (secs)
 dT                (1)  Thruster time step
 constraintType    (1)  Flag with value 0 or 1
                             0 : Equality Constraint on the Linear program formulation
                             1 : Inequality Constraint on the Linear program
                                 formulation
 maxConstraint     (1)  Maximum constraint on u
Outputs
 aC               (3,:) Commanded acceleration in Hill's frame
 t                (1,:) Time vector (secs)
 exitFlag          1    Feasible solution = 1, No feasible solution = 0
See also
: LinOrb, C2DZOH, Simplex
References and(), C2DZOH(), LinOrb(), LPCircular(), OrbRate(), Simplex(), vector(), and zeros().
Referenced by LPCircular(), LPCircularTimeWeight(), LPEccentric(), LPvsCF(), and TestLPCircular().
LPCircularTimeWeight()
function LPCircularTimeWeight (in el0, in xH0, in goals, in window, in nSPO)
Use the LPCircular control algorithm to compute the delta-v's associated with maneuvering from an initial state (x0) to a series of target states, which lie on a trajectory defined by the geometric goals (g). The target state associated with the minimum time-weighted cost is returned.
Form
 [xHF,nOrbMvr] = LPCircularTimeWeight( el0, xH0, goals, window, nSPO );
Inputs
 el0               (1)  Initial orbital element set   [a,i,W,w,e,M]
 xH0              (6,1) Initial state in Hill's frame
 goals             (.)  Geometric goals data structure
 window            (.)  Maneuver time window data structure, containing:
                           - nOrbMin         Minimum number of orbits
                           - nOrbMax         Maximum number of orbits
                           - nManeuvers      Number of maneuvers to search over
                           - timeWeightExp   Time-weighting exponent
 nSPO              (1)  Number of samples to use for control vector
 (per orbit of maneuver duration)
Outputs
 xHF              (6,1) Target Hills-frame state (at maneuver completion)
 nOrbMvr           (1)  Chosen maneuver duration (in orbits)
See also
: NOrbVector, El2Alfriend, Goals2Hills, LPCircular
References CostVis(), Demo(), El2Alfriend(), Goals2Hills(), length(), LPCircular(), LPCircularTimeWeight(), Mag(), MeanAnom2TrueLat(), NOrbVector(), OrbRate(), Simplex(), vector(), and zeros().
Referenced by ImpulsiveLPManeuver(), and LPCircularTimeWeight().
LPEccentric()
function LPEccentric (in e, in n, in x0, in xF, in nu0, in nuF, in nS, in cW, in constraintType, in maxConstraint)
Computes the thrust trajectory to go from an initial state x0 to a final state xF in the Hill's frame. Simplex is used to optimize the thrust. Algorithm works for an eccentric reference orbit. It does not however account for disturbances. In case eccentricity = 0, the solution obtained is the same as that obtained for a circular reference frame using LPCircular.
A control system can be expressed in its discrete state-space form as:
 X(k+1)      = A(k)X(k) + B(k)U(k)
 Y(k)        = C(k)X(k)
where X is state , U is control, Y is output. For the nth timestep, this can be rewritten as:
 X(n)        = A(n-1)*A(n-2)...A(n-n)*X(0) + [A(n-1)*A(n-2)...A(n-(n-1))*B   A(n-1)*A(n-2)...A(n-(n-2))*B ..... B]u
 where u     = [ U(0)' U(1)' ..... U(n-1)']'
For a fully controllable and observable system,
 Y(n) = X(n) = A(n-1)*A(n-2)...A(n-n)*X(0) + pu where p = [A(n-1)*A(n-2)...A(n-(n-1))*B   A(n-1)*A(n-2)...A(n-(n-2))*B ..... B]
 error       >= |Y(n) - Y(desired)| = A(n-1)*A(n-2)...A(n-n)*X(0) + pu - Y(desired)
The Simplex problem (minimise cu(cost) such that au <= b) and u >= 0 can now be posed as
 [-p; p]u    <= [error + A(n-1)*A(n-2)...A(n-n)*X(0) - Y(desired); error - A(n-1)*A(n-2)...A(n-n)*X(0) + Y(desired)]
In case of an Equality Constraint with 0 error, this reduces to
 [-p]u        =  A(n-1)*A(n-2)...A(n-n)*X(0) - Y(desired)
Note: The constraintType determines whether it is an equality technological constraint(au = b, flag: 0) or an inequality technological constraint(au <= b, flag: 1)
u are called 'decision variables', in this case thrust vector. Since u is unrestricted in sign (u can be positive and negative), we split u into two parts: u=up-um, where up>=0 and um>=0.
Form
 [aC,t,exitFlag] = LPEccentric( e, n, x0, xF, nu0, nuF, nS, cW, cType, maxC )
Inputs
 e                 (1)  Orbit eccentricity
 n                 (1)  Mean orbit rate (rad/sec)
 x0               (6,1) Initial state in Hill's frame
 xF               (6,1) Final state in Hill's frame
 nu0               (1)  Initial true anomaly (rad)
 nuF               (1)  Final true anomaly (rad)
 nS                (1)  Number of samples to use for control vector
 cW                (:)  Cost weighting vector (optional)
 cType             (1)  Flag with value 0 or 1 (optional, default: 0)
                             0 : Equality Constraint on the Linear program formulation
                             1 : Inequality Constraint on the Linear program
                                 formulation
 maxC              (1)  Maximum constraint on u (optional, default: 1e25)
Outputs
 aC               (3,nS)   Commanded acceleration in Hill's frame
 t                (1,nS+1) Time vector (sec)
 exitFlag          (1)     Feasible solution = 1, No feasible solution = 0
References and(), FFEccLinOrb(), isempty(), length(), LPCircular(), Mag(), Nu2M(), OrbRate(), Simplex(), UnwrapPhase(), vector(), and zeros().
Referenced by FFEccEstimateCost(), LPEccentricTimeWeight(), TestLPCircular(), TestLPEccentric(), and TestLPEccentricGVE().
LPEccentricGVE()
function LPEccentricGVE (in el0, in x0, in xF, in MF, in nS, in cW, in constraintType, in maxConstraint)
Computes the thrust trajectory to go from an initial state x0 to a final state xF (relative states defined as element differences). Simplex is used to optimize the thrust. This algorithm is valid for circular or eccentric reference orbits. It does not however account for disturbances or gravity perturbations.
A control system can be expressed in its discrete state-space form as: X(k+1) = A(k)X(k) + B(k)U(k) Y(k) = C(k)X(k) where X is state , U is control, Y is output
For the nth timestep, this can be rewritten as:
 X(n)    = A(n-1)*A(n-2)...A(n-n)*X(0) + [A(n-1)*A(n-2)...A(n-(n-1))*B   A(n-1)*A(n-2)...A(n-(n-2))*B ..... B]u
 where u = [ U(0)' U(1)' ..... U(n-1)']'
For a fully controllable and observable system,
 Y(n) = X(n) = A(n-1)*A(n-2)...A(n-n)*X(0) + pu where p = [A(n-1)*A(n-2)...A(n-(n-1))*B   A(n-1)*A(n-2)...A(n-(n-2))*B ..... B]
 error       >= |Y(n) - Y(desired)| = A(n-1)*A(n-2)...A(n-n)*X(0) + pu - Y(desired)
The Simplex problem (minimise cu(cost) such that au <= b) and u >= 0 can now be posed as
 [-p; p]u <= [error + A(n-1)*A(n-2)...A(n-n)*X(0) - Y(desired); error - A(n-1)*A(n-2)...A(n-n)*X(0) + Y(desired)]
In case of an Equality Constraint with 0 error, this reduces to
 [-p]u  =  A(n-1)*A(n-2)...A(n-n)*X(0) - Y(desired)
Note: The constraintType determines whether it is an equality technological constraint(au = b, flag: 0) or an inequality technological constraint(au <= b, flag: 1)
u are called 'decision variables', in this case thrust vector Since u is unrestricted in sign (u can be positive and negative), we split u into two parts: u=up-um, where up>=0 and um>=0.
Form
 [aC,t,exitFlag] = LPEccentricGVE( el0, x0, xF, MF, nS, cW, cType, maxC);
Inputs
 el0              (1,6)  Initial orbital elements [a,i,W,w,e,M]
 x0               (6,1) Initial relative state, as element differences
 xF               (6,1) Final relative state, as element differences
 MF                (1)  Final mean anomaly (rad)
 nS                (1)  Number of samples to use for control vector
 cW                (:)  Cost weighting vector (optional)
 cType             (1)  Flag with value 0 or 1 (optional, default: 0)
                             0 : Equality Constraint on the Linear program formulation
                             1 : Inequality Constraint on the Linear program
                                 formulation
 maxC              (1)  Maximum constraint on u (optional, default: 1e25)
Outputs
 aC               (3,nS)   Commanded acceleration in Hill's frame
 t                (1,nS+1) Time vector (sec)
 exitFlag          (1)     Feasible solution = 1, No feasible solution = 0
See also
: GVEDynamics, C2DZOH, Simplex
References and(), C2DZOH(), GVEDynamics(), isempty(), length(), M2Nu(), M2NuAbs(), Mag(), Nu2M(), OrbRate(), Simplex(), UnwrapPhase(), vector(), and zeros().
Referenced by TestLPEccentricGVE().
LPEccentricTimeWeight()
function LPEccentricTimeWeight (in el0, in xH0, in goals, in window, in nSPO)
Determine the target state on the desired trajectory that gives the minimum time-weighted cost. Use the LPEccentric control algorithm to compute the delta-v's associated with maneuvering from an initial state (x0) to a series of target states, which lie on a trajectory defined by the geometric goals (g). The target state associated with the minimum time-weighted cost is returned.
Form
 LPEccentricTimeWeight;  % demo
 [xHF,nOrbMvr] = LPEccentricTimeWeight( e, n, nu0, xH0, goals, window, nSPO );
Inputs
 el0               (1)  Initial orbital element set   [a,i,W,w,e,M]
 xH0              (6,1) Initial state in Hill's frame
 goals             (.)  Geometric goals data structure
 window            (.)  Maneuver time window data structure, containing:
                           - nOrbMin         Minimum number of orbits
                           - nOrbMax         Maximum number of orbits
                           - nManeuvers      Number of maneuvers to search over
                           - timeWeightExp   Time-weighting exponent
 nSPO              (1)  Number of samples to use for control vector
                         (per orbit of maneuver duration)
Outputs
 xHF              (6,1) Target Hills-frame state (at maneuver completion)
 nOrbMvr           (1)  Chosen maneuver duration (in orbits)
See also
: FFEccTargetTrueAnom, FFEccGoals2Hills, LPEccentric
References CostVis(), Demo(), FFEccGoals2Hills(), FFEccTargetTrueAnom(), length(), LPEccentric(), LPEccentricTimeWeight(), M2Nu(), Mag(), NOrbVector(), Nu2M(), OrbRate(), Simplex(), vector(), and zeros().
Referenced by LPEccentricTimeWeight().
LPvsCF()
function LPvsCF (in el0, in g0, in gF, in nSPO, in nOrbMvr, in nOrbSim)
 half-orbit increments
Form
 [uLP,uCF,xLP,xCF] = LPvsCF( el0, g0, gF, nSPO, nOrbMvr, nOrbSim );
Inputs
 el0             (1,6)  Reference orbital elements
 g0               (.)   Initial state, expressed in geometric goal format
 gF               (.)   Final state, expressed in geometric goal format
 nSPO             (1)   Time step [sec]
 nOrbMvr          (1)   Number of orbits to allow for maneuver
 nOrbSim          (1)   Number of orbits to simulate (must be >= nOrbMvr)
Outputs
 uLP              (3,N)  Acceleration vector from Linear Program method [m/s]
 uCF              (3,N)  Acceleration vector from closed-form method    [m/s]
 xLP              (6,N)  State vector from Linear Program method        [km; km/s]
 xCF              (6,N)  State vector from closed-form method           [km; km/s]
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
References abs(), and(), Difference(), DiscreteHills(), get(), Goals2DeltaElem(), Goals2Hills(), InPlane(), length(), LPCircular(), Mag(), NewFig(), Period(), set(), Simplex(), vector(), and zeros().
LVLH2ECI()
function LVLH2ECI (in x0, in xL)
Form
 x1 = LVLH2ECI( x0, xL )
Inputs
 x0              (6,1) [r;v] ECI frame (reference)
 xL              (6,n) [r;v] LVLH frame
Outputs
 x1              (6,n) [r; v] ECI frame
References QLVLH().
LVLH2Hills()
function LVLH2Hills (in xL)
This is a fixed transformation i.e. Hill's x is LVLH -z Hill's y is LVLH x Hill's z is LVLH -y
Form
 xH = LVLH2Hills( xL )
Inputs
 xL               (6,:) [r;v] LVLH frame
Outputs
 xH               (6,:) [r;v] Hills frame
References vector().
Lyapunov()
function Lyapunov (in el)
 Takes the orbital elements "el", constructs a linearized plant for the
 relative motion, and finds a constant gain feedback controller such that
 the linear, closed-loop system is asymptotically stable.
 Use "k" to compute the control acceleration "acc" as follows:
 acc = k*(xD - xM)
 where "xM" is the measured relative state, and "xD" is the desired
 relative state. Each state is a 6x1
 vector of the form: [x; y; z; Vx; Vy; Vz]
Form
 k = Lyapunov( el );    % where "el" is element vector: [a,i,W,w,e,M]
 -or-
 k = Lyapunov( a );     % where "a" is semi-major axis. assumes e = 0
Inputs
 el               (1,6) Reference orbital elements [a,i,W,w,e,M]
Outputs
 k                (3,6) Constant gain feedback controller
References: This is based on Terry Alfriend's paper, AIAA 2000-4131.
References and(), Constant(), length(), Lyapunov(), M2Nu(), OrbRate(), vector(), and zeros().
Referenced by DFFSim(), DLyapG(), LyapG(), Lyapunov(), LyapunovFamily(), LyapunovInit(), and NonlinearEstimator().
Maneuver_Structure()
function Maneuver_Structure ()
 Since version 7.
Form
 mvr = Maneuver_Structure( n );
Inputs
 none
Outputs
 mvr          (.)    Maneuver data structure with fields:
                        - achieve
                        - nBurns
                        - burnData
                        - t0
                        - tF
                        - iD
References BurnData_Structure(), Initialize(), and Maneuver_Structure().
Referenced by AccelVector2ManeuverStruct(), ImpulsiveLPManeuver(), and Maneuver_Structure().
ManeuverStruct2AccelVector()
function ManeuverStruct2AccelVector (in mvr, in dT)
 A constant timestep is used.
 Since version 7.
 Usage:
 [aC,t] = ManeuverStruct2AccelVector( mvr, dT );
 [aC]   = ManeuverStruct2AccelVector( mvr, t );
Inputs
 mvr           (.)      Maneuver data structure
 dT        (1) or (N)   Time-step or time vector                     [sec]
Outputs
 aC           (3,N)     [x;y;z] acceleration over N time intervals   [km/sec^2]
 t            (1,N)     Time vector                                  [sec]
References abs(), length(), Mag(), Unit(), vector(), and zeros().
Mean2Osc()
function Mean2Osc (in el_mean)
 Element vector in Alfriend form: [a,theta,i,q1,q2,W]
Form
 el_mean = Mean2Osc(el_osc);
Inputs
 el_mean          (1,6)    mean orbital elements
Outputs
 el_osc           (1,6)    osculating orbital elements
References: Terry Alfriend, Texas A&M University, 2001 Rich Burns, 1999
References Alfriend2El(), El2Alfriend(), Mean2OscS(), and vector().
Mean2OscS()
function Mean2OscS (in el_mean)
 Element vector in standard form: [a,i,W,w,e,M]
Form
 el_mean = Mean2Osc(el_osc);
Inputs
 el_mean          (1,6)    mean orbital elements
Outputs
 el_osc           (1,6)    osculating orbital elements
References: Terry Alfriend, Texas A&M University, 2001 Rich Burns, 1999
References E2Nu(), M2E(), and vector().
Referenced by Mean2Osc().
MeanAnom2TrueLat()
function MeanAnom2TrueLat (in e, in w, in M)
 True latitude, or argument of latitude, is the angle measured between the
 ascending node and the orbit position vector. This quantity is useful for
 circular, inclined orbits where there is no periapsis from which w and M
 can be measured.
 Since version 7.
 Usage:
 theta = MeanAnom2TrueLat( e, w, M );
Inputs
 e             (1)   Eccentricity
 w             (1)   Argument of perigee  [rad]
 M            (1,:)  Mean anomaly         [rad]
Outputs
 theta        (1,:)  True latitude        [rad]
References and(), M2Nu(), vector(), and WrapPhase().
Referenced by LPCircularTimeWeight().
MinDEllipsoid()
function MinDEllipsoid (in P1, in xc1, in P2, in xc2, in tol)
Performs an SVD of the ellipsoid matrix.
Form
 [d,x1,x2,iter,di,x1i,x2i,iter] = MinDEllipsoid(P1,xc1,P2,xc2);
Inputs
 P1         (3,3)      Ellipsoid #1 matrix
 xc1        (3,1)      Ellipsoid #1 center
 P2         (3,3)      Ellipsoid #2 matrix
 xc2        (3,1)      Ellipsoid #2 center
Outputs
 d          (1)        Minimum distance
 x1         (3,1)      Closest point on ellipsoid #1
 x2         (3,1)      Closest point on ellipsoid #2
 iter       (1)        Number of iterations
 di         (1,iter)   Minimum distance at each iteration
 x1i        (3,iter)   Ellipsoid #1 point at each iteration
 x2i        (3,iter)   Ellipsoid #2 point at each iteration
 err        (1)        Error in the slope differential at x1 and x2
References abs(), and(), DistantPtToEll(), Ellipsoid(), Eul2Mat(), Laguerre(), MinDEllipsoid(), NewFig(), set(), and zeros().
Referenced by CollisionMonitor(), and MinDEllipsoid().
NearestOffset()
function NearestOffset (in y0, in width, in extrema, in minSepDistance, in maxSepDistance)
Given the current along-track offset and the y-extrema for all other members, compute the closest offset such that the minimum and maximum required separation distances are respected.
 Usage:
 y0 = NearestOffset( y0, width, extrema, minSepDistance, maxSepDistance )
Inputs
 y0               (1)    Original along-track offset (on y-axis)
 width            (1)    Width of trajectory on y-axis
 extrema          (1,2N) Extrema pairs (min, max) on y-axis for N other
                           trajectories
 minSepDistance   (1)    Minimum separation distance between trajectories
 maxSepDistance   (1)    Maximum separation distance between trajectories
Outputs
 y0         (1)   Nearest along-track offset that meets separation objectives
References abs(), and and().
Referenced by AutoFormGeometry().
NewtRaph2()
function NewtRaph2 (in f, in fD, in x, in epsilon, in nMax, in varargin)
Finds the solution to f(x) = 0 given df(x)/dx when only one root is possible. If there are multiple roots, x should be in the vicinity of the desired root. Accepts optional arguments that are passed through to f and fD.
Form
 [x, n] = NewtRaph( f, fD, x, epsilon, nMax, p1, ... pN )
Inputs
 f                     Function handle for f(x),    i.e. @f
 fD                    Function handle for df(x)/dx i.e. @dfdx
 x                     Initial guess
 epsilon               Tolerance
 nMax                  Max number of iterations (can be inf)
 p1 ... pN             Optional arguments
Outputs
 x                     Result
 n                     Number of iterations
References: Hornbeck, R., Numerical Methods, Quantum, 1975, pp. 66-67.
References and(), and Initialize().
NominalSafeGuidance()
function NominalSafeGuidance (in inputs, in parameters, in state)
Define a safe relative orbit and plan a 1-2 burn maneuver to reach it. The safe relative orbit is a 2x1 relative in-plane ellipse, with a cross-track oscillation that provides a minimum cross-track separation where the ellipse intersects the along-track axis. The relative ellipse is chosen such that:
it can be reached with a single, immediate delta-v
it does not intersect with a 2x1 elliptical avoidance region
its semi-major axis is greater than the defined minimum value
it requires the lowest delta-v to meet the above constraints
Form
 [deltaV,desTraj,inside] = NominalSafeGuidance( inputs, parameters, state );
Inputs
 inputs        (.)    Input data from other modules
 parameters    (.)    Parameters that may be adjusted
 state         (.)    Absolute and relative state information
Outputs
 deltaV        (.)   Delta-V sequence data structure
                        .dV  (3,N) Set of N Hills-frame delta-v's [km/s]
                        .t   (1,N) Time for each delta-v's [MET]
 desTraj       (.)   Desired relative trajectory
                        .y0   Along-track offset of relative ellipse
                        .aE   Semi-major axis of relative ellipse
                        .zA   Cross-track value at along-track axis crossing
                        .zR   Cross-track value at radial axis crossing
 tracking      (.)   Tracking performance of current trajectory
 .drift   Along-track drift per orbit [km]
 .yA      Cross-track offset at along-track crossing [km]
 .zOsc    Smallest radial oscillation [km]
References and(), close(), ComputeRE(), Cross(), CrossTrackDeltaV(), EllipseDeltaV(), RadialOscillation(), set(), and zeros().
Referenced by SafeGuidance().
NOrbVector()
function NOrbVector (in window)
 Since version 7.
Form
 nOrb = NOrbVector( window );
Inputs
 window           (.)  Time window data structure with following fields
                        - nOrbMin
                        - nOrbMax
                        - nManeuvers
Outputs
 nOrb
References vector().
Referenced by LPCircularTimeWeight(), and LPEccentricTimeWeight().
Nu2TimeDomain()
function Nu2TimeDomain (in x, in n, in e, in nu)
 This changes only the relative velocity portion (elements 4 thru 6) of
 the state vector.
 For this conversion, the velocity terms are multiplied by the
 time-derivative of the true anomaly.
 Since version 7.
Form
 x = Nu2TimeDomain( x, n, e, nu )
Inputs
 x               (6,1)  Relative State in nu-domain, 6x1 vector, [position;velocity]
 n                (1)   Mean orbit rate [rad/s]
 e                (1)   Eccentricity
 nu               (1)   True anomaly [rad]
Outputs
 x               (6,1)  Relative State in time-domain, 6x1 vector, [position;velocity]
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
References NuDot(), and vector().
Referenced by FFEccGoals2Hills().
NuDot()
function NuDot (in n, in e, in nu)
 Since version 7.
Form
 [nuDot,nuDotDot] = NuDot( n, e, nu );
Inputs
 n                (1)   Mean orbit rate [rad/s]
 e                (1)   Eccentricity
 nu              (1,N)  True anomaly [rad]
Outputs
 nuDot           (1,N)  Time-derivative of true anomaly [rad/s]
 nuDotDot        (1,N)  Second Time-derivative of true anomaly [rad/s/s]
Copyright 2004 Princeton Satellite Systems, Inc.
All rights reserved.
Referenced by FFEccEstimateCost(), FFEccLinOrb(), Frenet2Hills(), Hills2Frenet(), Nu2TimeDomain(), TestFFEccLinOrb(), TestLPEccentric(), TestLPEccentricGVE(), and Time2NuDomain().
OptimalAssignment()
function OptimalAssignment (in N, in P, in Pu, in Q, in f, in phi, in u)
Form
 [optOrder, optPhi, optCost] = OptimalAssignment( N, P, Pu, Q, f, phi, u );
Inputs
 N                (1)      Number of objects
 P                (1)      Number of variable states
 Pu               (1)      Number of unique variable states
 Q                (1)      Number of points over which variable states are discretized
 f            (M+Pu*Q,N)   Set of weighted cost vectors, where M is number of fixed states
 phi             (1,P)     Array of initial phase offsets for variable states
 u               (1,P)     Array of indeces matching phase offsets with
                             unique variable states
Outputs
 optOrder        (1,N)     Optimal order of the target states
 optPhi          (1,N)     Optimal phases for variable states
 optCost          (1)      Total cost to achieve the optimal configuration
References abs(), and(), Demo(), FindMinSet(), length(), OptimalAssignment(), set(), square(), vector(), and zeros().
Referenced by OptimalAssignment(), and PrivilegedAssignment().
OptimalInPlaneDeltaV()
function OptimalInPlaneDeltaV (in nOrbMin, in nOrbMax, in a, in th0, in th1, in delta_a, in delta_th0, in delta_q1, in delta_q2, in analyze)
 Since version 7.
 Usage:
 [dV1,dV2,dV3,M,N] = OptimalInPlaneDeltaV( nOrbMin, nOrbMax, a, th0, th1, ...
 delta_a, delta_th0, delta_q1, delta_q2 );
Inputs
 nOrbMin                (1)   Minimum number of orbits the maneuver may last
 nOrbMax                (1)   Maximum number of orbits the maneuver may last
 a                      (1)   Mean semi-major axis of reference      [km]
 th0                    (1)   Latitude of reference at measurement   [rad]
 th1                    (1)   Latitude at first burn                 [rad]
 delta_a                (1)   Error in semi-major axis difference    [km]
 delta_th0              (1)   Error in latitude difference           [rad]
 delta_q1               (1)   Error in q1 difference
 delta_q2               (1)   Error in q2 difference
 analyze                (1)   Flag indicating whether to analyze the
                              performance of this optimization (optional)
Outputs
 dV1                    (1)   First delta-v                          [km/s]
 dV2                    (1)   Second delta-v                         [km/s]
 dV3                    (1)   Third delta-v                          [km/s]
 M                      (1)   Number of half-orbits between burn 1 and burn 2
 N                      (1)   Number of half-orbits between burn 1 and burn 3
Referenced by AnalyzeVariableTimeDV(), and EstimateCost().
OrbitDataPlugin()
function OrbitDataPlugin (in fig, in pos, in bColor)
 This function is called while initializing the Formation Design GUI.
Form
 d = OrbitDataPlugin( fig, pos, bColor, name );
Inputs
 fig              (1)   Handle to Formation Design GUI figure
 pos             (1,2)  Position data of GUI
 bColor          (1,3)  Background color of GUI
Outputs
 d                (.)   Data structure of handles to "Orbit Data" panel controls
References DisplayPlugin(), and NewFig().
Orientation_Structure()
function Orientation_Structure ()
 Since version 7.
Form
 orientation = Orientation_Structure;
Inputs
 none
Outputs
 orientation  (.)    Orientation command data structure with fields:
                        - qHB
                        - jD
                        - dT
                        - iD
References Initialize(), JD2000(), length(), Orientation_Structure(), quaternion(), and zeros().
Referenced by Orientation_Structure().
Osc2Mean()
function Osc2Mean (in el_osc, in J2)
Form
 el_mean = Osc2Mean(el_osc,J2);
Inputs
 el_osc           (1,6)    osculating orbital elements
 J2               (1,1)    Magnitude of J2 term
Outputs
 el_mean          (1,6)    mean orbital elements
References: Terry Alfriend, Texas A&M University
References Initialize(), Period(), and zeros().
Referenced by ECI2MeanElements().
OutOfPlane()
function OutOfPlane (in meas_elem, in delta_elem, in accNom, in dTMin)
 Since version 7.
Inputs
 meas_elem             (1,6)  Reference orbital elements             (Alfriend format)
                                                                     [a,theta,i,q1,q2,W]
 delta_elem            (:,6)  Error in orbital element differences   (Alfriend format)
 accNom                 (1)   Nominal acceleration                   [km/s/s]
 dTMin                  (1)   Minimum achievable burn duration       [sec]
Outputs
 burnData               (.)  Burn data structure with burn time,
                              duration, magnitude and direction.
 nBurns                 (1)  Number of burns required
 th1                    (1)  Argument of latitude at which burn is applied
                              (req'd for in-plane delta-v calculations)
References and(), and Constant().
PCGoals()
function PCGoals (in R, in alpha0, in sgn, in y0)
The phase on the relative ellipse is computed from EllipsePhase.
Form
 g = PCGoals( R, alpha0, sgn, y0 )
Inputs
 R               (1,n)  radius of the projected circle   [km]
 alpha0          (1,n)  angular offset around circle     [rad]
 sgn             (1,n)  orientation of plane (+/-1)
 y0              (1,n)  along-track offset               [km]
                        (optional, default is y0 = 0)
Outputs
 g                (.)   array of geomtric goals data structures
 Note: Each input must either be an array of length n, or a single number.
References EllipsePhase(), and length().
Referenced by CollisionInit(), GenerateTeamGoals(), ImpulsiveManeuver(), and IterativeImpulsiveManeuver().
PCState()
function PCState (in d, in w0, in phi, in M, in t)
Computes the position and velocity of a satellite on the local ellipse (Hills/Clohessy-Wiltshire) given the distance from the center (d), the orbital rate (w0), and the phasing angle (phi).
NOTE: Calling PCState with the M and t arguments will cause the state at time t to be computed as follows:
 state(t) = PCState( d, w0, M(t)+phi )
A circular chief orbit is assumed.
Form
 state = PCState( d, w0, phi, M, t )
Inputs
 d          (1,1)     distance from reference point (km)
 w0         (1,1)     orbital rate (rad/s)
 phi    (1,1)     phase angle, CW from y direction (deg)
 M      (1,1)     current mean anomoly of chief orbit (deg)
 t          (1,1)     elapsed time (sec)
Outputs
 state  (6,1)    final state for the spacecraft in Hill's frame
References abs(), and(), and PCState().
Referenced by CompareHills(), PCState(), and ProjCirc().
PlanningParameters_Structure()
function PlanningParameters_Structure ()
 Since version 7.
Form
 p = PlanningParameters_Structure;
Inputs
 none
Outputs
 p            (.)    Planning parameters data structure with fields:
                        - fNom
                        - horizon
                        - dTMin
                        - maxDeltaV
References and(), Initialize(), and PlanningParameters_Structure().
Referenced by DeltaVAnalysis(), FFMaintenanceTests(), ImpulsiveLPManeuver(), IterativeImpulsiveManeuver(), and PlanningParameters_Structure().
Plot3DEllipsoids()
function Plot3DEllipsoids (in xhat, in Shat, in nPlot)
Plots ellipsoids given the ellipsoid centers and matrices for 1 or 2 spacecraft. Selects nPlot points from the trajectory. Has a built-in demo. Ellipsoids are created with the same dimenensions in X and Z but elongating with time along Z.
Form
 Plot3DEllipsoids( xhat, Shat, nPlot )
Inputs
xhat {m}(3,n) Ellipsoid centers, for both spacecraft Shat {m}(3,3,n) Ellipsoid size matrices, for both spacecraft nPlot (p) Number of ellipsoids to plot, defaults to 50
References and().
PlotRun3D()
function PlotRun3D (in xSet, in dVSet, in iSet, in index, in d1, in d2)
This is meant to be called after FFSeparationDemo or FSafeGuidanceDemo has been run.
It requires certain variables to be present in the workspace.
Inputs
 xSet      {1,N}     Set of relative frame time histories.
 dVSet     {1,N}     Set of delta-V histories, one for each run.
 iSet      {1,N}     Set of inside logical arrays.
 index     (1,m)     Array of simulation run numbers.
 d1        (1,1)     Nominal ellispoid semi-major axis.
 d2        (1,1)     Nominal ellispoid + margin semi-major axis.
Outputs
 h         (1,m)     Handles to figures
PopulateCostMatrix()
function PopulateCostMatrix (in f, in costEstimate, in teamGoals, in relativeIDs)
 Since version 7.
 Usage:
 [f,col] = PopulateCostMatrix( f, costEstimate, teamGoals, relativeIDs );
Inputs
 f            (N,X)  Cost matrix (N target states, X spacecraaft)
 costEstimate  (.)   Data structure of cost information for a single spacecraft
 teamGoals     (.)   Goals data structure defining desired relative motion for team
 relativeIDs   (1)   Unique IDs for all relative spacecraft in the team
Outputs
 f            (N,X)  Cost matrix (N target states, X spacecraaft)
 col           (1)   column of the "f" matrix where the cost vector was inserted
References and(), CostEstimate_Structure(), CostMatrixRows(), Demo(), Initialize(), InitializeCostMatrix(), isempty(), length(), PopulateCostMatrix(), TeamGoals_Structure(), and vector().
Referenced by PopulateCostMatrix().
PositionDeltaV()
function PositionDeltaV (in r0, in v0, in rDes, in n, in t)
and vel.
Note: do not supply a time of t = 2*pi/n, as it results in a singularity!
Form
 dV = PositionDeltaV( r0, v0, rDes, n, t )
Inputs
 r0    (3,1)  initial relative position Hills
 v0    (3,1)  initial relative velocity Hills
 rDes  (3,1)  desired relative position Hills
 n     (1,1)  mean orbit rate
 t     (1,1)  time span from now until desired position
Outputs
 dV   (3,1)   required delta-V
References and(), HillsEqns(), and length().
PredictCollision()
function PredictCollision (in d, in jD, in y)
Runs the collision monitoring algorithm. Propagates forward for a fixed time assuming no maneuvers. Calls CollisionMonAlg. Has a built-in set of default parameters.
Form
 [prob, dMin, xhat, Shat, t] = PredictCollision( d, jD, y )
Inputs
 d        :     Algorithm data structure
                .hRef          Altitude of the reference orbit (km)
                .eRef          Eccentricity
                .MRef          Mean anomaly
                .dR            Reference length of Hill's orbit (km)
                .initBounds    Error in measurement (6,1)
                .scalev        Sigma for measurement noise
                .mSC           Spacecraft mass (kg)
                .lenSC         Spacecraft length (m)
                .diaSC         Spacecraft diameter (m)
                .Cd            Drag coefficient
                .Cr            Reflectivity of s/c: 0.0 for translucent;
                                 1.0 for black-body; 2.0 for flat mirror
 jD      (1)    Epoch in Julian date
 y       (6,n)  Spacecraft relative state in Hill's frame (km, km/s)
Outputs
 prob   {n}(1,:)     probability of collision
 d      {n}(1,:)     minimum distance between spacecraft position ellipsoids
 xhat   {n}(6,:)     xhat, ellipsoid centers
 Shat   {n}(6,6,:)   Shat, ellipsoid size matrices
 t
Reference: Mark Campbell, "Collision Monitoring Within Satellite Clusters". IEEE Transactions on Control Systems Technology, Jan. 2005
References Altitude(), CollisionMonAlg(), length(), and set().
PrivilegedAssignment()
function PrivilegedAssignment (in N, in P, in Pu, in Q, in f, in phi, in u, in method)
Form
 [optOrder, optPhi, optCost] = PrivilegedAssignment( N, P, Pu, Q, f, phi, u );
Inputs
 N                (1)      Number of objects
 P                (1)      Number of variable states
 Pu               (1)      Number of unique variable states
 Q                (1)      Number of points over which variable states are
                              discretized
 f            (M+Pu*Q,N)   Set of weighted cost vectors, where M is number of
                              fixed states
 phi             (1,P)     Array of initial phase offsets for variable states
 u               (1,P)     Array of indeces that map phase offsets to unique
                             variable states
 method           (1)      Flag indicating which method to use.
                             (1) prioritize based on the highest minimum cost
                             (2) prioritize based on the highest average cost
Outputs
 optOrder        (1,N)     Optimal order of the target states
 optPhi          (1,N)     Optimal phases for variable states
 optCost          (1)      Total cost to achieve the optimal configuration
References and(), Demo(), length(), OptimalAssignment(), PrivilegedAssignment(), vector(), and zeros().
Referenced by DFFSim(), and PrivilegedAssignment().
ProjCirc()
function ProjCirc (in aRef, in iRef, in kSats, in rF, in type)
 Since version 7.
Form
 [el,rhill,vhill] = ProjCirc(aRef,iRef,kSats,rF,type)
Inputs
 aRef           (1)      semi-major axis of reference orbit [km]
 iRef           (1)      inclination of reference orbit     [rad]
 kSats          (1)      number of satellites
 rF             (1)      formation radius                   [km]
 type           (1)      formation type
                              1 = equally phased (default)
                              2 = equal inclinations
Outputs
 el            (kSats,6)     orbital elements of all spacecraft
 rhill         (3,kSats)     position vectors in Hill's frame  [km]
 vhill         (3,kSats)     velocity vectors in Hill's frame  [km/s]
 ref:Satellite Formation Flying Design & Evolution
 AAS 99-121, Sabol, Burns, McLaughlin
References and(), ECI2Hills(), El2RV(), Hills2ECI(), OrbRate(), PCState(), RV2El(), and vector().
ProjLine()
function ProjLine (in aRef, in iRef, in kSats, in rF)
Form
 elSet = ProjLine( aRef, iRef, kSats, rF )
Inputs
 aRef           (1,1)     Semi-major axis of reference orbit [km]
 iRef           (1,1)     Inclination of reference orbit [rad]
 kSats          (1,1)     Number of satellites
 rF             (1,1)     Distance between satellites [km]
Outputs
 elSet         (kSats,6)     Orbital elements of all spacecraft
 rH            (3,kSats)     Radius vector in Hills frame   [km]
 vH            (3,kSats)     Velocity vector in Hills frame [km/s]
References ECI2Hills(), El2RV(), vector(), and zeros().
QHillsToBody()
function QHillsToBody (in r, in v, in qEB)
Compute the Hills-to-Body quaternion given the ECI position and velocity, and the ECI-to-Body quaternion.
Form
 qHB = QHillsToBody( r, v, qEB )
Inputs
 r                (3,:)     ECI position [km]
 v                (3,:)     ECI velocity [km/s]
 qEB              (4,:)     ECI-to-Body quaternion
Outputs
 qHB              (4,:)     Hills-to-Body quaternion
References and(), Mat2Q(), QHills(), QLVLH(), QMult(), QPose(), and quaternion().
RadialOscillation()
function RadialOscillation (in zo, in xoDot, in zoDot, in n)
Inputs
 z0      (1,1)   Initial relative cross-track position
 x0Dot   (1,1)   Initial relative velocity (radial direction)
 z0Dot   (1,1)   Initial relative velocity (cross-track direction)
 n       (1,1)   Mean orbit rate
Outputs
 r       (1,1)   Radial amplitude of oscillation
References abs().
Referenced by NominalSafeGuidance().
RE2Hills()
function RE2Hills (in x, in y, in y0, in aE, in zA, in zR, in n)
Form
 xH = RE2Hills( x, y, y0, aE, zA, zR, n );
Inputs
 x             (1)   Radial position
 y             (1)   Along-track position
 y0            (1)   Center of along-track motion
 aE            (1)   Semi-major axis of relative ellipse
 zA            (1)   Cross-track offset at forward along-track axis crossing
 zR            (1)   Cross-track offset at high radial axis crossing
 n             (1)   Mean orbit rate [rad/s]
Outputs
 xH            (1)   Hills-frame state on relative ellipse
References Cross(), and zeros().
RE2SLO()
function RE2SLO (in x, in z, in x0, in aE, in yA, in yR, in n)
SLO is spacecraft local orbit, equivalent to LVLH frame
Form
 xSLO = RE2SLO( x, z, x0, aE, yA, yR, n );
Inputs
 x             (1)   Along-track position
 z             (1)   Radial position
 x0            (1)   Center of along-track motion
 aE            (1)   Semi-major axis of relative ellipse
 yA            (1)   Cross-track offset at forward along-track axis crossing
 yR            (1)   Cross-track offset at high radial axis crossing
 n             (1)   Mean orbit rate [rad/s]
Outputs
 xSLO          (1)   SLO-frame state on relative ellipse
References Cross(), and zeros().
RelativeDisturb()
function RelativeDisturb (in jD, in r, in v, in dr, in dA, in mSC, in Cd, in Cr, in iRef)
Form
 aDiff = RelativeDisturb( jD, r, v, dr, dA, mSC, Cd, Cr, iRef )
 Inputs:
 jD       (1,1)  Epoch (Julian date)
 r        (3,1)  Reference position in ECI frame (km)
 v        (3,1)  Reference velocity in ECI frame (km/s)
 dr       (3,1)  Relative position between the spacecraft (km)
 dA       (1,1)  Differential area between the spacecraft (m2)
 mSC      (1,1)  Mass spacecraft (kg)
 Cd       (1,1)  Drag coefficient
 Cr       (1,1)  Reflection coefficient
 iRef     (1,1)  Reference inclination (rad)
 Outputs:
 aDiff      (3,1)  sum of all the terms (m/s/s)
References AtmDens1(), Constant(), Mag(), SunV1(), and Unit().
RelativeOrbitRHS()
function RelativeOrbitRHS (in x, in ignoredArg, in w, in u)
Valid for circular orbits only. x - radial, aligned with position vector; y - in the direction of the velocity vector; z - normal to the orbit plane. This frame is consistent with Kaplan's convention. Note: Previously named "HillsPropagationH". Renamed for clarity.
Form
 xDot = RelativeOrbitRHS( x, t, w, u )
Inputs
 x     (6,1)     [r;v] Spacecraft state in the Hills frame
 t     (1,1)     Current time (unused) (sec)
 w     (1,1)     Orbital Rate (rad/s)
 u     (3,1)     Thrust vector
Outputs
 xDot   (6,1)     d[r;v]/dt
Reference: Vallado, D.A. "Fundamentals of Astrodynamics and Applications", pp. 372-377, 2nd Edition.
References vector().
RelativeStatePlugin()
function RelativeStatePlugin (in fig, in pos, in bColor, in name)
 This function is called while initializing the Formation Design GUI.
Form
 d = RelativeStatePlugin( fig, pos, bColor, name );
Inputs
 fig              (1)   Handle to Formation Design GUI figure
 pos             (1,2)  Position data of GUI
 bColor          (1,3)  Background color of GUI
 name            (1,3)  m-file name of GUI for callbacks
Outputs
 d                (.)   Data structure of handles to "Relative State" panel controls
References NewFig(), and RelativeStatePlugin().
Referenced by RelativeStatePlugin().
RelativeVelocityError()
function RelativeVelocityError (in alt, in D, in t, in p, in sigma_x, in rho_xydot, in body)
navigation error that maintains the specified performance.
 Find the maximum possible navigation error in relative velocity so that
 the specified deadband will NOT be reached in the specified time, with
 a specified probability.
Form
 [sigma_ydot, sigma_d] = RelativeVelocityError( alt, D, t, p, sigma_x, rho_xydot, body );
Inputs
 alt        (1)      Altitude of the orbit [km]
 D          (1)      Deadband in the along-track axis
 t          (1)      Time horizon [orbits]
 p          (1)      Probability that the deadband will NOT be reached
 sigma_x   (1,m)     Standard deviation of relative navigation
                        radial position error
 rho_xydot (1,n)     Correlation coefficient
 body       (:)      String name of moon or planet ('earth' is default)
Outputs
 sigma_ydot (m,n)    Maximum standard deviation of the relative navigation
                        along-track velocity error
 sigma_d     (1)     Maximum standard deviation of the along-track drift rate
References Altitude(), and(), Constant(), Demo(), FindDriftTerm(), length(), and zeros().
RestrictDeltaV()
function RestrictDeltaV (in dVSLO, in xSLO, in n, in dMin, in x0, in aE, in radVelTol, in iPTol, in dPOTol)
Form
 dVSLO = RestrictDeltaV( dVSLO, xSLO, n, dMin, x0, aE )
Inputs
 dVSLO    (3,1)    Intended delta-v in SLO frame
 xSLO     (6,1)    Relative state, SLO-frame
 n         (1)     Mean orbit rate   [rad/s]
 dMin      (1)     Min. separation distance [km]
 x0        (1)     Desired along-track offset [km]
 aE        (1)     Desired Semi-major axis of relative ellipse [km]
Outputs
 dVSLO    (3,1)    Restricted delta-v in SLO frame
References abs(), and and().
Referenced by SafeGuidance().
RestrictIDSet()
function RestrictIDSet (in relIDs, in constraints)
 to determine which of these IDs should be included.
 Since version 7.
Form
 relIDs = RestrictIDSet( relIDs, constraints );
Inputs
 relIDs       (1,:)     Complete relative ID set
 constraints   (.)      Constraints data structure array
Outputs
 relIDs        (.)      Relative ID set to consider
References isempty(), length(), set(), and zeros().
RotateState()
function RotateState (in g, in phi)
Form
 g = RotateState( g, phi )
Inputs
 g            (.)    Geometric goals data structure (see Geometry_Structure)
 phi          (1)    Circular phase angle (see CirclePhase)
Outputs
 g            (.)    New geoemtric goals data structure, rotated to phi
See also
: CirclePhase, EllipsePhase
References CirclePhase(), EllipsePhase(), Geometry_Structure(), and set().
Referenced by EstimateCost(), FFEccGenerateTeamGoals(), HillsFramePlot(), IsDuplicateState(), TeamGoals2Geom(), and ViewFormation().
RVOrbGenDV()
function RVOrbGenDV (in el, in t, in dV, in dVTime)
Form
 [r, v] = RVOrbGenDV( el, t, dV, dVTime )
Inputs
 elI        Elements vector [a,i,W,w,e,M] or structure
 t          Times from 0 to ? (sec)
 dV         Array of 3xN delta-v's to be applied (Hills frame)  [km/sec]
 dVTime     Array of 1xN times at which delta-v's are applied   [sec]
Outputs
 r          Position vectors for times t
 v          Velocity vectors for times t
 el         Times at which r and v are calculated
References and(), GetHillsMats(), length(), RV2El(), RVOrbGen(), and vector().
SafeEllipseParams()
function SafeEllipseParams (in rSLO, in vSLO, in n)
Usage:
 [x0,aE,yA,yR,alpha] = SafeEllipseParams( rSLO,vSLO,n );
Inputs
 rSLO         (3,1)  Relative position in SLO frame
 vSLO         (3,1)  Relative velocity in SLO frame
 n             (1)   Mean orbit rate [rad/s]
Outputs
 x0            (1)   Center of along-track motion
 aE            (1)   Semi-major axis of relative ellipse
 yA            (1)   Cross-track offset at along-track axis crossing
 yR            (1)   Cross-track offset at radial axis crossing
 alpha         (1)   Center of along-track motion [rad]
References Cross().
SafeEllipsePosVel()
function SafeEllipsePosVel (in x0, in aE, in yA, in yR, in alpha, in n)
 a "safe ellipse" trajectory at a phase angle of alpha.
Usage:
 [rSLO,vSLO] = SafeEllipsePosVel( x0, aE, yA, yR, alpha, n );
Inputs
 x0            (1)   Center of along-track motion
 aE            (1)   Semi-major axis of relative ellipse
 yA            (1)   Cross-track offset at along-track axis crossing
 yR            (1)   Cross-track offset at radial axis crossing
 alpha         (1)   Center of along-track motion [rad]
 n             (1)   Mean orbit rate [rad/s]
Outputs
 rSLO         (3,1)  Relative position in SLO frame
 vSLO         (3,1)  Relative velocity in SLO frame
References and(), and Cross().
SafeGuidance()
function SafeGuidance (in inputs, in parameters, in state)
The desired relative trajectory and the delta-v sequence to achieve it will be computed each cycle. The results will be made available as telemetry at all times.
The delta-v command will be executed only when safe mode has been entered and the appropriate conditions have been met.
Conditions for commanding ANY delta-v (nominal OR immediate separation) 1 SAFE MODE has been entered 2 either: a) the thruster is ready to fire (heated to nominal conditions) OR b) there is a high probability of collision within the next 20-30 minutes (this based on the time required to heat the thrusters) 3 we are NOT waiting for a previous maneuver to complete
Further conditions for executing an immediate separation maneuver: 1 the MAIN is inside the PASSIVE avoidance region
Further conditions for executing a nominal safe guidance maneuver: 1 the MAIN is outside the PASSIVE avoidance region
 2 we have exceeded the deadband
 Since version 10.
Form
 [out,telem] = SafeGuidance( inputs, parameters );        % w/ full sim
 [out,telem] = SafeGuidance( inputs, parameters, state ); % w/ rel sim
Inputs
 inputs        (.)    Input data from other modules
                .t                     (1)   Time [MET]
                .mass                  (1)   Current spacecraft mass [kg]
                .safeMode              (1)   Flag. Are we in safe mode?
                .maneuverImmediately   (1)
                .thrusterHeatNominal   (1)
                .thrusterHeatEmergency (1)
 parameters    (.)    Tunable parameters
 .dTMin              (1)   Minimum impulse bit              [sec]
 .dVMax              (1)   Maximum delta-v                  [km/s]
 .margin             (1)   Distance margin around avoidance region [km]
 .fNom               (1)   Nominal force of thruster        [kN]
 .dMin               (1)   Min. sep. dist. (passive orbit)  [km]
 .minTimeBtwnDeltaVs (1)   Min. time between delta-v's      [sec]
 .mvrHorizon         (1)   Time between planning and burn   [sec]
 state         (.)    Absolute and relative state information
 .el           (1,6) Orbital elements (standard)
 .xSLO         (6,1) Relative state, SLO-frame
 .n            (1)   Mean orbit rate   [rad/s]
Outputs
 outputs       (.)    Output data to other modules
                .deltaV       (.)   Data strucutre of delta-vs and times
 telemetry     (.)    Telemetry data
 .immediate    (1)   Algorithm branch: inside avoidance region
 .nominal      (1)   Algorithm branch: outside avoidance region
 .x0           (1)   Along-track offset of relative ellipse
 .aE           (1)   Semi-major axis of relative ellipse
 .yA           (1)   Cross-track value at along-track axis crossing
 .yR           (1)   Cross-track value at radial axis crossing
References abs(), and(), Cross(), HillsEqnsSLO(), isempty(), Mag(), NominalSafeGuidance(), RestrictDeltaV(), SeparationGuidance(), Telemetry(), and zeros().
Referenced by SafeGuidanceSim().
SafeGuidanceBurnData()
function SafeGuidanceBurnData (in dV, in inside)
Usage:
 [kSep,kNom,kCT] = SafeGuidanceBurnData( dV, inside );
Inputs
 dV           (3,N)  Applied delta-v in SLO frame
 inside       (1,N)  Flag indicating whether the MAIN is inside region
Outputs
 kSep         (1,:)  Indices where separation burn is applied
 kNom         (1,:)  Indices where nominal burn is applied
 kCT          (1,:)  Indices where nominal burn w/ cross-track is applied
References abs(), and(), and Mag().
SafeGuidanceParameters()
function SafeGuidanceParameters ()
 Since version 10.
Inputs
 none
Outputs
 params          (.)  Parameter data structure.
References and(), Parameter(), and SafeGuidanceParameters().
Referenced by SafeGuidanceParameters(), and SafeGuidanceSimInit().
SafeGuidanceSim()
function SafeGuidanceSim (in simOptions)
Includes differential disturbance forces for J2, drag and solar. Explicitly calls SafeGuidance maneuver planning algorithm.
Assumptions:
Form
 simData = FFRelSim( simOptions )
 Sim options fields:
 elRef  [a,i,W,w,e,M]
 nOrbits
 nPts     Discretization points per orbit
 distOpt  Flags for [solar drag J2]
 harmonicOrder
 control
 params
 noise
 flags
References AGravityC(), Altitude(), and(), ApplyDeltaV(), AtmDens2(), Cross(), EarthRot(), Eclipse(), get(), GetHillsMats(), Hills2ECI(), Initialize(), isempty(), JD2000(), JD2T(), LinOrb(), Mag(), RHS(), RV2El(), SafeGuidance(), SunV2(), and Unit().
Referenced by SafeGuidanceSimInit(), and SafeGuidanceSimPlots().
SafeGuidanceSimInit()
function SafeGuidanceSimInit (in name)
Each case has specific data associated with it. You may add new cases with unique names to this function. This enables you to reproduce specific scenarios easily as time goes on and the algorithms evolve.
Use the output of this function as input to SafeGuidanceSim
Form
 simOptions = SafeGuidanceSimInit( name )
Inputs
 name          (:)   Name of the stored test case
Outputs
 simOptions    (.)   Data structure with the following fields:
   - el0            (1,6)  Initial reference orbital elements  (Alfriend)
   - dEl0           (1,6)  Initial orbital element differences (Alfriend)
   - xH0            (6,1)  Initial relative Hills-frame state [km; km/s]
   - params          (.)   Data structure defining the several maneuver parameters
   - noise          (1,4)  Standard deviation of noise for the following sources:
                        noise(1) - absolute position [m]
                        noise(2) - absolute velocity [m/s]
                        noise(3) - relative position [m]
                        noise(4) - relative velocity [m/s]
   - nOrbits         (1)   Number of orbits to simulate
   - nSPO            (1)   Number of simulation points per orbit
   - distOpt        (1,2)  Disturbance options (flags)
                        (1) solar:  whether to simulate with solar pressure or not
                        (2) drag:   whether to simulate with drag or not
   - harmonicOrder   (1)   Gravity perturbation harmonic (J0 - J36)
   - area           (1,2)  Area for solar or drag cases  [m^2]
                        (1) area(1) - Main spacecraft
                        (2) area(2) - Target spacecraft
References and(), El2Alfriend(), Goals2DeltaElem(), SafeGuidanceParameters(), SafeGuidanceSim(), and set().
SafeGuidanceSimPlots()
function SafeGuidanceSimPlots (in d)
Inputs
 d            (.)  Data structure output from SafeGuidanceSim
Outputs
 none
References AddView(), Figui(), length(), Mag(), SafeGuidanceSim(), set(), Telemetry(), Trajectory(), and zeros().
SatellitePlugin()
function SatellitePlugin (in fig, in pos, in bColor, in name)
 This function is called while initializing the Formation Design GUI.
Form
 d = SatellitePlugin( fig, pos, bColor, name );
Inputs
 fig              (1)   Handle to Formation Design GUI figure
 pos             (1,2)  Position data of GUI
 bColor          (1,3)  Background color of GUI
 name            (1,3)  m-file name of GUI for callbacks
Outputs
 d                (.)   Data structure of handles to "Satellite" panel controls
References NewFig(), and SatellitePlugin().
Referenced by SatellitePlugin().
ScaleState()
function ScaleState (in g, in s)
This
 changes the size of the relative state, but not the phase.
 Since version 7.
Form
 g = ScaleState( g, s );
Inputs
 g            (.)    Geoemtric goals data structure (see Geometry_Structure)
 s            (1)    Desired scale factor. Existing state will be scaled
                     up (>1) or down (<1) by this amount. Only the
                     real absolute value of this number is used.
Outputs
 g            (.)    New geoemtric goals data structure, scaled by "s".
References abs(), Geometry_Structure(), and set().
SeparationGuidance()
function SeparationGuidance (in parameters, in state)
 Maneuver immediately to separate spacecraft and exit avoidance region.
Desired relative velocity along in-plane projection of pos. vector
 Direction is AWAY from TARGET, with minimum along-track component
 Magnitude is inversely proportional to distance from ellipse
Correction made to along-track component to ensure sufficient drift such
 that the avoidance region is not reentered.
 Since version 10.
Form
 deltaV = SeparationGuidance( parameters, state );
Inputs
 parameters    (.)    Parameters that may be adjusted
 state         (.)    Absolute and relative state information
Outputs
 deltaV        (.)    Delta-V sequence data structure
                        .dV  (3,N) Set of N Hills-frame delta-v's [km/s]
                        .t   (1,N) Time for each delta-v's [MET]
References abs(), AlongTrackMotion(), and(), and vector().
Referenced by SafeGuidance().
SetupAssignmentProblem()
function SetupAssignmentProblem (in teamGoals, in orbFrac)
This utilizes the variable, nDuplicates, and phase fields of the constraints. For circular goals, the phase offset for the unique state is computed with CirclePhase. For eccentric goals, it is nu_xMax.
 Usage:
 [N,M,P,Pu,Q,phi,u] = SetupAssignmentProblem( teamGoals );
Inputs
 teamGoals     (.)   Goals data structure defining desired relative motion for team
 orbFrac       (1)   Fraction of orbit (may be >1) over which variable states are defined
Outputs
 N             (1)   Number of objects
 M             (1)   Number of fixed states
 P             (1)   Number of variable states
 Pu            (1)   Number of unique variable states
 Q             (1)   Number of points over which variable states are discretized
 phi          (1,P)  Array of desired phase offsets for variable states
 u            (1,P)  Array of indices matching phase offsets with unique variable states
References and(), CirclePhase(), and vector().
Referenced by DFFSim(), EstimateCost(), FFEccEstimateCost(), and TeamGoals2Geom().
ShortArcToHills()
function ShortArcToHills (in p, in t, in n, in qHToBody, in e, in xECI)
 Calls fminsearch on PinholeCamera to find an approximate Hills state.
 Type ShortArcToHills for a demo. The demo calls PinholeCamera to
 compute pixel locations.
 Since version 11.
Form
 x = ShortArcToHills( p, t, n, qHToBody, e )
Inputs
 p         (2,n) Pixel locations - at least 3
 t         (1,n) Times (sec)
 n         (1,1) Orbit rate of observing spacecraft (rad/s)
 qHToBody  (4,1) Quaternion from Hills to Body
 e         (1,1) Camera data structure
                 .f            (1,1) Focal length (mm)
                 .w            (1,1) Pixel width (micro-m)
                 .bodyToCamera (3,3) Transformation from body to camera
 xECI      (6,1) ECI state of imager
Outputs
 x         (6,1) Initial Hills state [r;v]
ShowTeams()
function ShowTeams (in teams, in fig)
 Since version 7.
Form
 [levels,fig] = ShowTeams( teams, fig )
Inputs
 teams           (.)  Data structure array of teams, with the following fields:
                        - name:           name of team (string)
                        - memID:          member ID numbers (1-D numeric array)
                        - refID:          reference ID number
 fig             (1)  Handle to figure (optional). Default is to generate new figure.
Outputs
 levels         (1,N)   Level of each team. (Level 1 is at top of hierarchy).
 fig             (1)    Handle to figure.
References isempty(), length(), and TeamLevels().
SortTeamGoals()
function SortTeamGoals (in teamGoals)
The team goals structure consists of an array of geometric and constraint data structures, corresponding to a set of unique target states.
The ground may supply goals with the target states listed in any order. The software, however, must have them sorted in a particular order. Thus, as soon as the team goals are received by the captain, they are sorted such that all fixed states are listed before any variable states.
Form
 teamGoalsSorted = SortTeamGoals( teamGoals );
Inputs
 teamGoals        (.)   Team goals data structure, supplied from ground.
Outputs
 teamGoalsSorted  (.)   Sorted team goals data structure, with fixed
                           states listed before variables states.
References and(), set(), and zeros().
Referenced by DFFSim().
SS19702JD()
function SS19702JD (in s)
1, 1970 to a Julian date.
 Since version 7.
Form
 jD = SS19702JD( s );
Inputs
 s          Seconds since 00:00:00 GMT, Jan. 1, 1970
Outputs
 jD         Julian date
State_Structure()
function State_Structure ()
 Since version 7.
Form
 state = State_Structure( n );
Inputs
 none
Outputs
 state        (.)    State data structure with fields:
                        - el     Standard elements [a,i,W,w,e,M]
                        - elA    Alfriend elements [a,theta,i,q1,q2,W]
                        - dEl    Alfriend element differences
                        - xH     Hills-frame relative state [km;km/s]
                        - mass   Mass [kg]
                        - tM     Measurement epoch [sec]
References Initialize(), set(), State_Structure(), and zeros().
Referenced by DeltaVAnalysis(), and State_Structure().
SubGoals()
function SubGoals (in e, in nu, in gA, in gB, in n)
 Given the geometry of A and the geometry of B, compute the geometry
 of B with respect to A.
 Since version 7.
Form
 gBA = SubGoals( e, nu, gA, gB, n );
Inputs
 e                (1)      Eccentricity
 nu               (1)      True anomaly   [rad]
 gA               (.)      Geometric goals of A
 gB               (.)      Geometric goals of B
 n                (1)      Mean orbit rate
Outputs
 gBA              (.)      Geometric goals of B with respect to A
                              gBA = gB - gA
References and(), FFEccGoals2Hills(), FFEccHills2Goals(), Goals2Hills(), Hills2Goals(), IsCircGeom(), IsEccGeom(), isempty(), and set().
Team_Structure()
function Team_Structure (in n)
 Since version 7.
Form
 team = Team_Structure( n );
Inputs
 n            (1)    Number of team structures to generate
Outputs
 team         (.)    Team data structure with fields:
                        - teamID
                        - nMembers
                        - memID
                        - refID
                        - captainID
References Initialize().
Referenced by DefaultCommandList(), DemoManeuverCommandList(), EccentricTetrahedronCommandList(), SimpleManeuverCommandList(), and TestControlCommandList().
TeamGoals2Geom()
function TeamGoals2Geom (in teamGoals, in offset)
 Usage:
 g = TeamGoals2Geom( tG, offset )
Inputs
 teamGoals      (.)   Team goals data structure
Outputs
 geom           (:)   Array of Geometry data structures
References isempty(), RotateState(), and SetupAssignmentProblem().
Referenced by GenerateTeamGoals().
TeamGoals_Structure()
function TeamGoals_Structure (in nU)
Form
 tG = TeamGoals_Structure( nU );
Inputs
 nU            (1)    Number of unique states
                      (also equal to number of geometric goal structures
                      and number of constraint structures)
Outputs
 tG           (.)    Team goals data structure with fields:
                        - teamID
                        - nU
                        - geometry
                        - constraints
                        - dPhi
References and(), Constraints_Structure(), Geometry_Structure(), and Initialize().
Referenced by CostMatrixRows(), DefaultCommandList(), FFEccEstimateCost(), GenerateTeamGoals(), InitializeCostMatrix(), and PopulateCostMatrix().
TeamLevels()
function TeamLevels (in teams)
 Since version 7.
Form
 [levels,teams] = TeamLevels(teams)
Inputs
 teams           (.)  Data structure array of N teams, with the following fields:
                        - name:           name of team (string)
                        - memID:          member ID numbers (1-D numeric array)
                        - refID:          reference ID number
Outputs
 levels         (1,N)   Level of each team. (Level 1 is at top of hierarchy).
 team            (.)    Original team data structure array, with levels updated
References length().
Referenced by ShowTeams(), and TeamManagementCommandList().
TeamPlugin()
function TeamPlugin (in fig, in pos, in bColor, in name)
 This function is called while initializing the Formation Design GUI.
Form
 d = TeamPlugin( fig, pos, bColor, name );
Inputs
 fig              (1)   Handle to Formation Design GUI figure
 pos             (1,2)  Position data of GUI
 bColor          (1,3)  Background color of GUI
 name            (1,3)  m-file name of GUI for callbacks
Outputs
 d                (.)   Data structure of handles to "Team" panel controls
References NewFig(), and TeamPlugin().
Referenced by TeamPlugin().
TestFFEccLinOrb()
function TestFFEccLinOrb (in x0, in xH0, in dT, in aH)
An initial reference state in the ECI frame is provided, along with an initial relative state in Hill's frame.
First, the relative state is propagated one time-step dT using FFEccLinOrb, with the given acceleration in Hill's frame applied.
Next, we integrate the reference and secondary states in the ECI frame, applying the given accleration (now transformed to ECI). We then transform the two resulting ECI states back to the Hill's frame and compare.
Form
 [xH_int,xH_lin] = TestFFEccLinOrb( x0, xH0, dT, aH );
Inputs
 x0              (6,1)  ECI position and velocity of reference
                        [km; km/s]
 xH0             (6,1)  Hill's-frame position and velocity of relative sat
                        [km; km/s]
 dT               (1)   Time-step to integrate over [sec]
 aH              (3,1)  Acceleration to be applied (in Hill's frame)
                        [km/s/s]
Outputs
 xH_int          (6,1)  Hill's-frame state from integrating inertial states
 xH_lin          (6,1)  Hill's-frame state from propagating linear system
References and(), ECI2Hills(), El2RV(), FFEccDiscreteHills(), FFEccGoals(), FFEccLinOrb(), FFEccRMat(), GetHillsMats(), Hills2ECI(), isempty(), M2Nu(), NuDot(), OrbRate(), RHS(), RK4TI(), and RV2El().
TestLPCircular()
function TestLPCircular (in el0, in xH0, in xHF, in dur, in nS, in plotFlag)
Provide the reference orbital elements, an initial relative state and initial true anomaly, a desired/final relative state and final true anomaly, and the number of samples to discretize over.
Two validation methods are used. In the first, we propagate the initial state over nS samples, applying the control acceleration found by LPEccentric. In the second, we integrate the two inertial states, applying the same control acceleration, but in the ECI frame. We then transform back to the Hill's frame for comparison.
Form
 [xH_int,xH_lin,dVTot,eT,err] = TestLPCircular( el0, xH0, xHF, dur, nS, plotFlag )
Inputs
 el0             (6,1)  Initial orbital elements [a, i, W, w, e, M]
 xH0             (6,1)  Initial Hill's-frame state
 xHF             (6,1)  Final/desired Hill's-frame state
 dur              (1)   Maneuver duration [sec]
 nS               (1)   Number of samples to discretize over
 plotFlag         (1)   Create plots or not (0|1)
Outputs
 xH_int          (6,1)  Hill's-frame state from integrating inertial states
 xH_lin          (6,1)  Hill's-frame state from propagating linear system
 dVTot            (1)   Total Delta-V for maneuver [m/s]
 eT               (1)   Time elapsed during call to LPEccentric [sec]
 err             (6,1)  State error at end of maneuver. Found by integrating
                        the inertial states from t=0 and applying control,
                        then comparing the final state with the target state.
References and(), DiscreteHills(), El2Alfriend(), El2RV(), FFIntegrate(), get(), Goals2Hills(), Hills2ECI(), HillsEqns(), length(), LPCircular(), LPEccentric(), Mag(), NewFig(), OrbRate(), Period(), set(), TestLPCircular(), and zeros().
Referenced by TestLPCircular().
TestLPEccentric()
function TestLPEccentric (in el0, in xH0, in nu0, in xHF, in nuF, in nS, in plotFlag)
Provide the reference orbital elements, an initial relative state and initial true anomaly, a desired/final relative state and final true anomaly, and the number of samples to discretize over.
Two validation methods are used. In the first, we propagate the initial state over nS samples, applying the control acceleration found by LPEccentric. In the second, we integrate the two inertial states, applying the same control acceleration, but in the ECI frame. We then transform back to the Hill's frame for comparison.
Form
 [xH_int,xH_lin,dVTot,eT,err] = TestLPEccentric( el0, xH0, nu0, xHF, nuF, nS, plotFlag );
Inputs
 el0             (6,1)  Initial orbital elements
                        [a, i, W, w, e, M]
 xH0             (6,1)  Initial Hill's-frame state
 nu0              (1)   Initial true anomaly
 xHF             (6,1)  Final/desired Hill's-frame state
 nuF              (1)   Final true anomaly
 nS               (1)   Number of samples to discretize over
 plotFlag         (1)   Create plots or not (0|1)
Outputs
 xH_int          (6,1)  Hill's-frame state from integrating inertial states
 xH_lin          (6,1)  Hill's-frame state from propagating linear system
 dVTot            (1)   Total Delta-V for maneuver [m/s]
 eT               (1)   Time elapsed during call to LPEccentric [sec]
 err             (6,1)  State error at end of maneuver. Found by integrating
                        the inertial states from t=0 and applying control,
                        then comparing the final state with the target state.
References and(), El2RV(), FFEccDiscreteHills(), FFEccGoals(), FFEccProp(), FFIntegrate(), get(), Hills2ECI(), length(), LPEccentric(), M2Nu(), Mag(), NewFig(), NuDot(), OrbRate(), Period(), set(), TestLPEccentric(), and zeros().
Referenced by TestLPEccentric().
TestLPEccentricGVE()
function TestLPEccentricGVE (in el0, in xH0, in nu0, in xHF, in nuF, in nS, in plotFlag)
Provide the reference orbital elements, an initial relative state and initial true anomaly, a desired/final relative state and final true anomaly, and the number of samples to discretize over.
Two validation methods are used. In the first, we propagate the initial state over nS samples, applying the control acceleration found by LPEccentric. In the second, we integrate the two inertial states, applying the same control acceleration, but in the ECI frame. We then transform back to the Hill's frame for comparison.
Form
 [xH_int,xH_lin,dVTot,eT,err] = TestLPEccentricGVE( el0, xH0, nu0, xHF, nuF, nS, plotFlag );
Inputs
 el0             (6,1)  Initial orbital elements
                        [a, i, W, w, e, M]
 xH0             (6,1)  Initial Hill's-frame state
 nu0              (1)   Initial true anomaly
 xHF             (6,1)  Final/desired Hill's-frame state
 nuF              (1)   Final true anomaly
 nS               (1)   Number of samples to discretize over
 plotFlag         (1)   Create plots or not (0|1)
Outputs
 xH_int          (6,1)  Hill's-frame state from integrating inertial states
 xH_lin          (6,1)  Hill's-frame state from propagating linear system
 dVTot            (1)   Total Delta-V for maneuver [m/s]
 eT               (1)   Time elapsed during call to LPEccentric [sec]
 err             (6,1)  State error at end of maneuver. Found by integrating
                        the inertial states from t=0 and applying control,
                        then comparing the final state with the target state.
References and(), DiscreteGVE(), El2RV(), FFEccDeltaElem2Hills(), FFEccDiscreteHills(), FFEccGoals(), FFEccHills2DeltaElem(), FFEccProp(), FFIntegrate(), get(), Hills2ECI(), length(), LPEccentric(), LPEccentricGVE(), M2Nu(), Mag(), NewFig(), Nu2MAbs(), NuDot(), OrbRate(), Period(), RV2El(), set(), TestLPEccentricGVE(), and zeros().
Referenced by TestLPEccentricGVE().
Tetrahedron()
function Tetrahedron (in d, in eul, in centroid)
 The first point is at the origin by default. Setting centroid=1 will
 put the centroid of the first 3 points at the origin.
 Call with no outputs to see a picture in 3D.
 Since version 7.
 Usage:
 [p,a,v] = Tetrahedron( d, eul, centroid )
Inputs
 d           (1)  Length of each side  [length]
 eul        (1,3) Euler angles defining orientation
 centroid    (1)  Flag. If 1, puts the centroid of the first 3 points at
                  the origin. Otherwise (default) the first point is at
                  the origin.
Outputs
 p          (3,4)  [x;y;z] coordinates of the four corners
 a           (1)   Surface area  [length^2]
 v           (1)   Volume        [length^3]
References and(), Eul2Q(), Euler(), length(), QForm(), set(), Tetrahedron(), and zeros().
Referenced by FFEccTetrahedronGeometry(), and Tetrahedron().
ThrusterAlignment()
function ThrusterAlignment (in r, in v, in aH, in bHET, in bST, in jD, in sep, in constrain, in analyze)
 The constraint is to keep the star tracker pointed as far away from the sun,
 earth and moon as possible.
 Since version 7.
Form
 [uBVelocity, uBNadir, qEB] = ThrusterAlignment( r, v, aH, bHET, bST, jD, sep, constrain );
Inputs
 r               (3,1)  Position in ECI at burn time  [km]
 v               (3,1)  Velocity in ECI at burn time  [km/s]
 aH              (3,1)  Unit Hills frame vector of applied acceleration
 bHET            (3,1)  Unit body vector of Hall Effect Thruster nozzle
 bST             (3,1)  Unit body vector of star tracker bore-sight
 jD               (1)   Julian Date of burn time      [JD]
 sep              (1)   Required angular separation between bore-sight and
                         bright body horizon          [rad]
 constrain        (1)   Flag to indicate whether to consider bright-body constraint
                        Optional. Default is 1 (constraint considered)
Outputs
 uBVelocity      (3,1)  Unit body vector to align with velocity direction
 uBNadir         (3,1)  Unit body vector to align with nadir direction
 qEB             (4,1)  Desired ECI-to-body quaternion
 okay             (1)   Boolean flag indicating whether angular separation
                         constraints were satisfield
References and(), AnimQ(), AU2Q(), close(), Demo(), Dot(), Initialize(), JD2000(), Mag(), MoonV1(), Nadir(), QForm(), QHills(), QMult(), QPose(), quaternion(), SunV1(), ThrusterAlignment(), U2Q(), Unit(), and vector().
Referenced by ThrusterAlignment().
Time2NuDomain()
function Time2NuDomain (in x, in n, in e, in nu)
 This changes only the relative velocity portion (elements 4 thru 6) of
 the state vector.
 For this conversion, the velocity terms are divided by the
 time-derivative of the true anomaly (nu).
 Since version 7.
Form
 x = Time2NuDomain( x, n, e, nu )
Inputs
 x               (6,1)  Relative State in time-domain, 6x1 vector,
                         [position;velocity]
 n                (1)   Mean orbit rate [rad/s]
 e                (1)   Eccentricity
 nu               (1)   True anomaly [rad]
Outputs
 x               (6,1)  Relative State in nu-domain, 6x1 vector,
                         [position;velocity]
References: Inalhan, Tillerson, How, "Relative Dynamics and Control of Spacecraft Formations in Eccentric Orbits", Journal of Guidance, Control & Dynamics, Vol.25, No.1, Jan-Feb 2002.
References NuDot(), and vector().
Referenced by FFEccHills2Goals().
TimeUntilTheta()
function TimeUntilTheta (in a, in w, in e, in theta0, in theta1, in mu)
 original latitude, "theta1".
 Since version 7.
Inputs
 a              (1)  Semimajor axis                   [km]
 w              (1)  Argument of perigee              [rad]
 e              (1)  Eccentricity
 theta0         (1)  Initial argument of latitude     [rad]
 theta1         (1)  Final argument of latitude       [rad]
 mu             (1)  Gravitational constant           [km^3/sec^2] (optional)
Outputs
 dT             (1)  Time until next theta is reached [sec]
References Constant(), Nu2M(), and WrapPhase().
TransformGeom2Hills()
function TransformGeom2Hills (in el, in g, in ignoredArg)
Works for either circular or eccentric orbits.
Form
 xH = TransformGeom2Hills( el, g, nu );
Inputs
 el           (1,6)  Reference orbital elements [a,i,W,w,e,M]
 g             (.)   Geometric goals data structure
 nu            (1)   Time step for the simulation [sec] (not used)
Outputs
 xH           (6,1)  Relative position and velocity in Hills frame [km; km/s]
See also
: Goals2Hills, FFEccGoals2Hills
References and(), El2Alfriend(), FFEccGoals2Hills(), Goals2Hills(), IsCircGeom(), IsEccGeom(), M2Nu(), and OrbRate().
Referenced by Goals2Hills(), and ViewRelativeMotion().
VerifyCollStruct()
function VerifyCollStruct (in d0)
 Pmin is a function of scalev.
 Ssc is a function of lenSC.
 S0 is a function of initBounds and scalev.
 Since version 7.
Form
 dV = VerifyCollStruct( d0 )
Inputs
 d0         (1)    Initial structure
                   .scalev      Number of sigma of initBounds
                   .initBounds  Initial bounds on relative state (km)
                   .lenSC       Spacecraft length (m)
Outputs
 dV         (1)    Verified structure with computed fields
                   .Pmin   Minimum probability if outside
                   .Ssc    Spacecraft bounding sphere (km)
                   .S0     Initial ellipsoid
References and(), and length().
Referenced by CollisionInit().
ViewEllipsoid()
function ViewEllipsoid (in xhat, in Shat, in dMin)
Plots ellipsoids for Collision Monitoring given the ellipsoid centers and matrices for 1 or 2 spacecraft.
Form
 ViewEllipsoid( xhat, Shat, dMin )
Inputs
xhat {2}(6,n) Ellipsoid centers, for both spacecraft Shat {2}(6,6,n) Ellipsoid size matrices, for both spacecraft dMin {}(1,n) Minimum distance between Ellipsoids predicted
References and().
ViewFormation()
function ViewFormation (in el0, in g, in h, in color)
Form
 h = ViewFormation( el0, g, h, color )
Inputs
 el0             (1,6)     Reference orbital elements (Alfriend format) [a,th,i,q1,q2,W]
 g                (.)      Geometric goals data structure with following fields:
                              - y0     along-track offset                       [km]
                              - aE     semi-major axis of relative ellipse      [km]
                              - beta   angle on ellipse at perigee              [rad]
                              - zInc   cross-track amp. due to inc. diff        [km]
                              - zLan   cross-track amp. due to right ascen diff [km]
 h                (1)      Figure handle (optional)
 color            (:)      Color to display the trajectory in (optional)
                              - can be a string (ie, 'r') or a 3x1 vector
Outputs
 h                (1)     Figure handle
See also
: RotateState, Goals2Hills
References AddAxes(), CirclePhase(), Goals2Hills(), isempty(), IsVersionAfter(), length(), Mag(), RotateState(), set(), vector(), and zeros().
ViewGeometry()
function ViewGeometry (in g, in angle, in e)
Draws the trajectory and the shape of the formation, via connection lines and patches, at the desired angle. If angle is empty, it will mark the initial conditions. The reference state (at the origin) is included.
Form
 ViewGeometry;   % demo
 ViewGeometry( g, angle, e )
Inputs
 g             (.)   Geometry data structure (Circular or eccentric)
 angle         (1)   Angle at which to draw connections; can be empty
                        If eccentric, true anomaly is used.
                        If circular, true latitude is used.
 e             (1)   Eccentricity. If circular geometry, e is set to 0.
Outputs
 none
References and(), FFEccHexahedronGeometry(), IsCircGeom(), isempty(), length(), NewFig(), set(), ViewGeometry(), and zeros().
Referenced by ViewGeometry().
ViewHills()
function ViewHills (in el0, in el, in timeSpan, in method)
Given the reference orbital elements, a time span, and the spacecrafts' orbital elements, animate the relative motion. If a Hills state is available it may be input directly.
Form
 ViewHills( el0, el, timeSpan, method )
 ViewHills( w0, xH, timeSpan, 1 )        % relative via Hills
Inputs
 el0             (1,6) reference orbital elements [a i W w e M]
 el              (k,6) orbital elements of each spacecraft
 timeSpan         (1)  length of time to propagate
 method           (:)  method of propagation ('relative','keplerian','hi-fi')
                                             (    1           2         3   )
 - for method 1, first 3 inputs are: -
 w0              (1,1) orbital rate [rad/s]
 xH              (6,k) initial Hills state [km; km/s]
 timeSpan         (1)
Outputs
 sc               data structure of relative positions over time
See also
AnimationGUI, HillsEqns, RVOrbGen, ECI2Hills, J2Prop
References and().
ViewRelativeMotion()
function ViewRelativeMotion (in el0, in goals, in nOrbits)
View the relative motion associated with a set of geometric goals and a given reference orbit.
 sc = ViewRelativeMotion( el0, goals, nOrbits );
Inputs
 el0          (1,6)     Reference orbital elements (Alfriend format) [a,th,i,q1,q2,W]
 g             (.)      Geometric goals data structure with following fields:
                           - y0     along-track offset                       [km]
                           - aE     semi-major axis of relative ellipse      [km]
                           - beta   angle on ellipse at perigee              [rad]
                           - zInc   cross-track amp. due to inc. diff        [km]
                           - zLan   cross-track amp. due to right ascen diff [km]
                        OR eccentric goals
 nOrbits       (1)      Number of orbits to simulate  [orbits]
Outputs
 sc            (.)      Data structure array of position, velocity, time data
                             for each spacecraft
   - r        (3,:)     Relative Hills frame position [km]
   - v        (3,:)     Relative Hills frame velocity [km/s]
   - t        (1,:)     Time [sec]
See also
TransformGeom2Hills, HillsEqns, AnimationGUI
References Alfriend2El(), and(), AnimationGUI(), Geometry_Structure(), HillsEqns(), length(), OrbRate(), set(), TransformGeom2Hills(), ViewRelativeMotion(), and zeros().
Referenced by GenerateTeamGoals(), and ViewRelativeMotion().
ViewRotatingHillsFrame()
function ViewRotatingHillsFrame (in rECI, in vECI, in rHills)
 Show the satellite traverse the relative trajectory while the trajectory
 is shown rotating around the orbit path.
 Since version 7.
 Usage:
 h = ViewRotatingHillsFrame( rECI, vECI, rHills )
Inputs
 rECI         (3,:)  Inertial position over time
 vECI         (3,:)  Inertial velocity over time
 rHills       (3,:)  Hills-frame position over time
Outputs
 h             (1)   Handle to figure
Window_Structure()
function Window_Structure ()
 Since version 7.
Form
 window = Window_Structure;
Inputs
 none
Outputs
 window       (.)    Window data structure with fields:
                    - startTime       Earliest possible start time                    [sec since 1970]
                    - nOrbMin         Minimum number of orbits maneuver may last      [orbits]
                    - nOrbMax         Maximum number of orbits maneuver may last      [orbits]
                    - nManeuvers      Number of maneuvers to search over
                    - timeWeightExp   Time-weighting exponent (greater than 0)
References Initialize(), and Window_Structure().
Referenced by AutoDualPCCommandList(), AutoFormCommandList(), ClusterGoalsDemoCommandList(), CollisionDemoCommandList(), DeltaVAnalysis(), DemoManeuverCommandList(), DFFSim(), EccentricTetrahedronCommandList(), FFMaintenanceTests(), ImpulsiveLPManeuver(), IterativeImpulsiveManeuver(), MainDemoCommandList(), ProjCircCommandList(), SimpleManeuverCommandList(), TestControlCommandList(), and Window_Structure().
WorstCasePerturbations()
function WorstCasePerturbations (in h, in dR, in mSC, in Cd, in Cr)
Assumes fixed maximum and minimum area differences, which could in practice be different for drag and solar pressure based on mission attitude profiles.
The relative accelerations are due to:
1) Earth's Gravitational potential (geopotential)
2) Atmospheric drag
3) Sun
4) Moon
4) Solar radiation pressure
5) Linearization of equations of motion
Form
 [aDiff, aTerms] = WorstCasePerturbations( h, dR, mSC, Cd, Cr );
 Inputs:
 h         (1)  altitude of (circular) orbit (km)
 dR        (1)  distance between the spacecraft (km)
 mSC       (1)  spacecraft mass (kg)
 Cd        (1)  drag coefficient
 Cr        (1)  reflectivity of s/c: 0.0 for translucent; 1.0 for black-body;
 2.0 for flat mirror
 Outputs:
 aDiff   (3,2)  sum of all the terms (m/s/s)
 aTerms    (.)  data structure containing the individual differential
 accelerations
 - J2     (3,1)  earth's oblateness
 - drag   (3,1)  drag
 - sun    (3,1)  effect of sun
 - moon   (3,1)  effect of moon
 - solar  (3,1)  solar radiation
 - linear (3,1)  linearization approximation error
References abs(), and(), AtmDens2(), Constant(), length(), and zeros().
Referenced by CollisionMonitor().
YRMax()
function YRMax (in yA, in aE, in minDist)
Such that the trajectory does not intersect avoidance region.
The inputs should observe the following constraints which are enforced in the safe guidance aglorithm:
aE >= minDist + margin yA >= aE / 2
Usage:
 [yRMax,aMin] = YRMax( yA, aE, minDist );
 Example:
 [yRMax,aMin] = YRMax( 45, 90, 60 );
Inputs
 yA            (1)   Current value of yA [m]
                            (yA: cross-track offset at along-track axis crossing)
 aE            (1)   Current value of aE [m]
                            (aE: semi-major axis of 2x1 in-plane ellipse)
 minDist       (1)   Minimum desired separation distance (in along-track) [m]
Outputs
 yRMax         (1)   Maximum allowable value of yR [m]
                            (yR: cross-track offset at radial-track axis crossing)
 aMin               (1)     Phase angle where minimum distance ocurs [rad]
References abs(), Circle(), Cross(), get(), and zeros().
Referenced by CrossTrackDeltaV().