PSS MATLAB Toolboxes: SC Functions
SC Functions
SC Module
The SC module functions.
Directories
directory Actuator
Actuator models.
directory Attitude
Attitude analysis including pointing budgets.
directory Control
Controller functions.
directory DemoFuns
Functions needed by demos.
directory Disturbances
Compute disturbance forces and torques.
directory Dynamics
Attitude dynamics.
directory Environs
Space environment models.
directory Ephem
Ephemeris functions.
directory GOESRead
GOES reading functions.
directory GUIPlugIn
Plug-in GUI modules.
directory Hardware
Hardware models.
directory MagneticControl
Magnetic control functions.
directory MannedVehicle
Functions applicable to manned vehicles like ISS.
directory SCData
Data for the SC module.
directory SCDatabase
Spacecraft database utility.
directory SCMat
Stored mat-files.
directory SCModels
Saved spacecraft models.
directory Sensor
Sensor and measurement models.
directory SystemDesign
Subsystem design.
directory Tools
Tools and utilities.
directory Visualization
Visualization utilities.
Description
Functions
function Accel (in x, in d)
Models accelerometers.
function ACSRWAAndTorquers (in x, in d)
Control system.
function AddMassDot (in mADot, in mA, in mBDot, in mB, in u)
Add mass and mass derivatives using the mass data structure.
function AddRobotArm (in action, in previousBody, in firstBody, in rBase, in link)
Add a multi-element arm to a CAD models.
function AddSurf (in id, in name, in area, in cP, in normal, in rhoAbsp, in rhoSpec, in rhoDiff, in x)
Add a surface to the data structure.
function AeroDragForce (in x, in area, in cD, in jD)
Calculate the drag force in the ECI frame assuming constant area.
function AeroF (in rho, in cD, in v, in normals, in area)
Compute the aerodynamic forces on a set of elemental areas.
function AI2Rate (in a, in dT, in m, in aOld)
Converts attitude increments to rate.
function AirCoreMagneticTorquerDesign (in d)
Design a minimum mass air core magnetic torquer.
function AiryDisk (in lambda, in F, in Ld)
Computes the diameter of the Airy Disk.
function AlbedoFromTextureMap (in planetFile, in cloudFile, in planetFun, in cloudFun, in alphaAve)
Creates an albedo map from a texture map.
function AlphaBetaToU (in alpha, in beta, in r, in v)
Compute a unit vector given alpha and beta angles.
function AltitudeHold (in x, in kH, in tauH, in g, in mass, in xSet)
Altitude hold for a lander.
function AltitudeSH (in r, in s, in c, in nH)
Computes the altitude over a spherical harmonic terrain map.
function AngleDetermination (in r, in v, in n, in b, in jD)
Model to produce roll, pitch and yaw from nadir and magnetic field.
function AngRate (in angMomentumVector, in torqueVector)
Computes the magnitude of the angular rate of the momentum vector.
function AnimateSpacecraft (in action, in varargin)
Animate spacecraft CAD models in a relative frame.
function ArcEff (in spinrate, in pulsewidth)
Arc efficiency from spin rate and pulsewidth.
function AreaOfRectCircInt (in v, in r)
Computes the area of intersection of a rectangle and a circle.
function ASim (in x, in t, in inertia, in torque)
Attitude simulation of a rigid body.
function AStarAttitudeTrajectory (in q, in qTarget, in uBody, in rA, in dec, in radius, in nGrid)
Compute a trajectory to avoid stayout zones using AStar.
function AtmJ70ToGround (in h, in d)
Computes the atmospheric density using Jacchia's 1970 model or scale heights.
function AtmNRLMSISE (in rECI, in jD, in varargin)
NRLMSISE-00 Model 2001 for atmospheric density.
function AtmScaleHeightsStdAtm (in h, in atmData)
Computes the atmospheric density using scale heights above 80 km.
function AttitudeProfilePlots (in d)
Make time history plots of an attitude profile.
function AttitudeProfilePlugIn (in action, in modifier, in hFig, in position, in callback)
Generate attitude profiles.
function AttitudeProfileVis (in d, in gCAD, in cone)
Visualize an attitude profile with constraints.
function AttitudeProfileWithCon (in d, in varargin)
Build a constrained attitude profile consisting of multiple overlapping modes.
function AttitudeTarget (in type, in s, in t, in d)
Generate a reference quaternion for a variety of targets.
function AutoPoint (in mode, in camera, in gTarget, in rBody)
Compute the parameters necessary to place a camera at a target.
function BathtubCurve (in beta, in t, in alpha)
Generates a failure bathtub curve.
function BatteryDesign (in type, in el, in planet, in jD, in powerMax)
Size a battery given an orbit and planet.
function BatterySize (in sma, in inc, in power, in jD0, in dOD, in rhoM, in rhoV)
BatterySize Battery sizing for a given orbit and array power.
function BDDesign (in mF, in rhoF, in tNom, in pI, in pF, in rP)
Designs a blowdown system.
function BDipole (in r, in jD, in v, in c)
Computes the geocentric magnetic field based on a tilted dipole model.
function BDipoleCoeff (in file)
Computes the geocentric magnetic coefficients for BDipole.
function BFromHHysteresis (in h, in hDot, in d)
Flux density from the magnetic field due to hysteresis.
function BHarm (in n, in aS, in file)
Computes a sine/cosine harmonic series for the magnetic field.
function BLDCMFlux (in theta, in d)
Brushless DC Motor back emf.
function BLDCMFriction (in omega, in d)
Brushless DC Motor friction.
function BLDCMInverter (in e, in d)
Brushless DC Motor commutation using a 6 switch inverter.
function BLDCMRHS (in x, in t, in d)
Brushless DC Motor simulation.
function BloDown (in mPress, in rhoFuel, in vTank, in rPress, in T, in mFuel)
Generates a blowdown curve.
function BMF (in r, in jD, in kP)
Magnetic field based on the Mead-Fairfield Model.
function BTrans (in b, in aS)
Transforms the GOES data into popular earth pointing frames.
function CalibrateSunSensor (in n, in f, in angle)
Calibrate a sun sensor.
function Callmkspk (in ignoredArg, in ignoredArg)
Creates an SPK file from two text files.
function CameraDatabase (in modelName)
Get default camera properties for different camera models.
function CameraImage (in d, in qECIToBody, in rECI, in p, in qECIToTarget, in rTarget)
Generates the 2D coordinates in the focal plane for a camera.
function CameraResolution (in h, in f, in l, in d, in lambda)
Resolution of an optical sensor.
function CameraTransform (in type, in d, in p)
Generate a camera transformation.
function CEcl2Eq (in jD)
Transformation matrix from ecliptic to Earth equatorial planes.
function CentroidNoise (in d)
Compute centroid noise terms for an optical sensor.
function CMG (in action, in u)
Simple CMG model.
function CMGAMatrix (in u)
Computes the transfer matrix from gimbal rates to torques.
function CommandPlugIn (in action, in modifier, in hFig, in position, in callback)
Create a command interface for a simulation.
function ConstraintForceAndTorque (in action, in varargin)
Computes the constraint forces and torques.
function Counter (in action, in d)
Simulate a counter.
function CreateVCDisturbanceFile (in g, in fileName)
Create a VisualCommander disturbance file from a cad model.
function CW2Roll (in scanAngle, in cant, in uSpin, in uPitch, in earthRadius, in chordwidth)
Converts the output from a conical scanning sensor to roll.
function DblPivot (in p1, in p2, in p3)
Computes the unit normal for a double pivoted assembly.
function DeltaML (in L1, in L2, in t1, in t2, in n)
Compute total change in longitude between two orbits.
function DeltaQTarget (in qCommand, in qIToB, in qOld, in deltaAngle)
Generate a target quaternion by limiting the total angular change.
function DeltaRate (in ignoredArg, in ignoredArg, in omega)
Computes the new angular rate when the inertia changes.
function Demo ()
Static Earth sensor model.
function DIModel (in inr, in tSamp, in sType)
Double integrator model.
function Dipole (in m, in xD, in x)
Compute the magnetic field of a dipole.
function DipoleFromField (in b, in h)
Computes the dipole for a solid magnet.
function DistAero (in r, in q, in v, in n, in a, in p, in rho, in shadowFun)
Computes the aerodynamic disturbance using a Newtonian model.
function DistAlbedo (in r, in q, in uSun, in n, in a, in p, in optical, in alpha, in rPlanet, in qSun, in shadowFun)
Computes the albedo disturbance.
function DistRadiation (in r, in q, in n, in a, in p, in optical, in rPlanet, in qPlanet, in shadowFun)
Computes the radiation disturbance from the central body.
function DistributedAlbedo (in action, in d)
Computes albedo from a texture map.
function DistSolar (in r, in q, in uSun, in n, in a, in p, in optical, in rPlanet, in rSun, in shadowFun)
Computes the albedo disturbance.
function Disturbances (in mode, in g, in e, in h, in doPlots)
Compute the total force and torque on a spacecraft generated by the CAD package.
function DrawFieldLines (in r, in n, in fun, in jD)
Draw field lines on a sphere.
function DrawSCPlugIn (in action, in modifier, in hFig, in position, in planet, in jD)
Draw spacecraft in orbit about a planet.
function DSpnStab (in iR, in iP, in iT1, in iT2, in wR, in wP)
Computes the dual spin stability.
function DSTCrit (in iWheel, in iPitch, in iRoll, in iYaw, in hW)
Compute dual spin turn rates.
function DWheel (in iT, in iS, in wS, in tau, in e)
Computes the damping coefficient ratio for a damper wheel.
function Dyn (in ignoredArg, in ignoredArg, in dynData)
Returns the mass and right hand side of the dynamics equations.
function DynP (in ignoredArg, in ignoredArg, in dynData)
Returns the mass and right hand side of the dynamics equations.
function EarthAlb (in r, in u, in uS, in alpha, in aF, in w)
Computes the heat absorbed per unit area due to albedo.
function EarthEclipseDuration (in el, in jD)
Compute the eclipse duration in earth orbit.
function EarthEnvironment (in rECI, in vECI, in jD, in e)
Compute the environment parameters for the Earth.
function EarthNut (in T)
The matrix that rotates from the Earth mean axes to the true axes.
function EarthPre (in T)
Computes the earth precession matrix.
function EarthRad (in r, in alpha, in w)
Computes the heat absorbed due to earth radiation.
function EarthRot (in T, in ignoredArg)
Computes the Earth greenwich matrix that transforms from ECI to EF.
function EarthRotationZero (in jD, in eOfECalc)
Determine jD for when the earth-fixed frame is aligned with the ECI frame.
function EarthRte (in jD)
Computes the mean earth rate.
function ECIToECIR (in jD, in eOfECalc)
Computes the transformation form ECI to ECIR.
function ECIToPlanet (in jD, in planet, in kEarth)
Computes the matrix from mean of Aries 2000 to planet fixed frame.
function Eclipse (in rSC, in rSource, in rPlanet, in radiusPlanet, in radiusSource)
Computes eclipses.
function EclipseDuration (in rSC, in rPlanet, in beta)
Computes eclipse orbit fraction.
function EclipseFill (in aX, in e, in t)
Puts a fill in to show when the spacecraft is eclipsed.
function EclipseFromECI (in r, in t, in jD0, in a)
Computes eclipses from time and ECI position.
function ECLSSSizing (in nCrew, in nDays, in type)
Sizes an Environmental Control and Life Support subsystem (ECLSS).
function EffPw (in tauRise, in tauFall, in pulsewidth, in tauMax)
Computes the effective pulsewidth given the rise and fall times.
function ElementsPlugIn (in action, in modifier, in hFig, in position, in callback)
Create an orbit elements GUI plug in.
function EnergyPerRing (in w, in x)
Energy per ring for a diffraction limited circular aperture.
function EOfE (in T)
Computes the equation of the equinoxes.
function EquatorialToGalactic ()
Returns the equatorial to Galactic transformation matrix.
function ESA (in qIToB, in uBS, in uPitch, in nadir, in limit, in noise)
Simulates an ideal earth sensor measuring roll and pitch.
function ESAChord (in rho, in delta, in roll)
Compute the delta earth chord for a scanning earth sensor.
function ESACS (in qIToB, in rNadir, in u, in cant, in pitchAxis, in refAxis, in noise, in quant)
Models a conical scanning earth sensor.
function FAeroSurfaceAccommodation (in u, in rho, in t, in m, in d, in sigmaN, in sigmaT)
Computes the aerodynamic force using surface accommodation coefficients.
function FAKM (in x, in t, in inr, in inrDot, in mRDot, in hMWA, in inrDamper, in cDamper, in uDamper, in tAKM, in tBurn)
AKM Burn right-hand-side.
function FDC (in x, in t, in fDyn, in fConstraint, in dynData, in constData, in penalty, in nIts)
The right hand side of equations formulated using Lagrange multipliers.
function FGravityGradientStiffness (in x, in ignoredArg, in inertia, in orbitRate)
Gravity gradient for a rigid body with small offsets from LVLH.
function FGs (in x, in t, in inr, in invInr, in torque, in inrWheel, in uWheel, in tWheel, in cDamp)
Gyrostat right-hand-side.
function FIC (in q, in ignoredArg, in m1, in m2, in L, in g)
Sliding mass on a pendulum using independent coordinates.
function FICP (in q, in ignoredArg, in L, in g)
Single pendulum using independent coordinates.
function FloatToWord (in f, in kMax, in kMin, in resolution)
Convert floating point to word.
function FMagSim (in x, in ignoredArg, in inr, in invInr, in tExt, in inrW, in uW, in tW, in ignoredArg)
Dynamics of spacecraft with one reaction wheel.
function FP2RADec (in rAC, in decC, in x, in y, in f)
Converts focal plane coordinates into right ascension/declination of the targets.
function FPB (in theta, in rho, in sig1, in sig2, in f)
Integrand for pointing budgets.
function FPivot (in x, in ignoredArg, in jW, in jP, in iS, in tS, in tW, in tP, in uW, in uP)
Computes the right hand side of the spacecraft with pivot eofm.
function FPSensors (in qECIToB, in qBToS, in catalog, in fov, in fScale)
Computes the output of focal plane sensors.
function FRB (in x, in ignoredArg, in inr, in invInr, in tExt)
Rigid body right-hand-side.
function FRBWithMag (in x, in ignoredArg, in d)
Rigid body right-hand-side with magnetic torque computed internally.
function Friction (in tC, in w, in c, in wC, in d)
Computes friction torques based on a model with an exponential term.
function FrictionBristle (in z, in t, in d)
Friction model.
function FrictionSmooth (in x, in d)
Rotary wheel friction model using differentiable functions.
function FRWA (in x, in ignoredArg)
Simulate a reaction wheel.
function FRWABristle (in x, in ignoredArg)
RWA model.
function FRY (in x, in ignoredArg, in d)
Roll/yaw simulation RHS.
function FRYSim (in x, in ignoredArg, in d)
Roll/yaw simulation right hand sidd.
function FSDG (in x, in t, in u, in h, in cD, in k, in kF, in w, in bias, in nU, in nV, in nE)
Gyro right-hand-side.
function FSolstice (in jD, in type)
RHS for computing solstice.
function FSRHS (in x, in t, in d)
Compute smooth friction RHS.
function FTB (in x, in ignoredArg, in r0, in r1, in lam1, in iner0, in iner1, in m0, in m1, in torque, in force, in iAxis)
Two body spacecraft model right-hand-side.
function FTBRef (in x, in ignoredArg, in tBDS)
Right hand side of the two body equations.
function FXModel (in inr, in h, in wo, in m, in r, in wF, in zF, in fT, in mT, in v, in x)
Plant for a momentum bias spacecraft with flexible solar arrays.
function GASTime (in jD, in eOfECalc)
Compute Greenwich apparent sidereal time.
function Geo ()
Computes parameters for a geosynchronous orbit.
function GeoEclps (in alpha, in beta, in dEarth)
Computes the normalized sun intensity for an earth geosynchronous orbit.
function GetFlex (in file, in path, in name)
Reads in flex data from a formatted text file.
function GetModes (in phi, in omega, in useModes, in nNodes)
Extract flex modes from a finite element modal transformation matrix.
function GimbalC (in a, in b, in c, in d, in psInv, in x, in att)
Generate gimbal commands for a gimbal stationkeeping system.
function Glitch (in b, in bMax, in ifLT)
Removes glitches from data.
function GMSTime (in jd)
Compute Greenwich mean sidereal time from Julian date.
function GOESLeg (in l, in box, in hK)
Draws the GOES Legend.
function GOESLon (in sc, in dateTime, in file)
Computes the west longitude of a GOES spacecraft.
function GPSOrbit (in d, in t)
Position and velocity of a GPS satellite in the earth-fixed reference frame.
function GPSReceiver (in action, in d)
GPS receiver model.
function GPSReceiverNav (in action, in d)
GPS receiver model with navigation message model.
function GPSSatellite (in jD, in coord)
Gives the location of the GPS satellites at JD.
function GravitationalConstantEarth ()
Returns the Earth's gravitational constant.
function GravitationalTimeDilation (in mu, in r)
Gravitational time dilation.
function GravityGradientAnalytical (in n, in iXX, in iYY, in iZZ)
Analytical eigenvalues for gravity gradient stabilization.
function GravityGradientBoom (in i0, in n, in r, in m)
Compute frequencies for a boom.
function GravityGradientEigenvalues (in inr, in r, in v, in mu)
Compute the eigenvalues for a gravity gradient stabilized spacecraft.
function GravityGradientFrequency (in inertia, in n)
Gravity gradient frequencies.
function GravityGradientFromR (in q, in inr, in r, in mu)
Computes a gravity gradient torque from r and mu.
function GravityGradientStiffness (in inertia, in orbitRate)
Computes gravity gradient stiffness from inertia and orbit rate.
function GroundTrackErrorBudget (in fileName, in varargin)
Generate a ground track error budget.
function GSModel (in inr, in inrinv, in T, in w, in inrwheel, in uwheel, in Twheel, in wwheel, in dT)
Gyrostat dynamics model which computes acceleration or plant matrices.
function GTrack (in r, in a, in f)
Calculate a ground track on an ellipsoid.
function GUICounter (in action, in modifier, in u)
This gui displays a counter.
function Gyro (in action, in input)
Models a gyro.
function GyroData (in type, in class)
Typical gyro noise data.
function HMagEl (in p, in a, in type)
Computes the magnetic field for a filament or loop magnetic element.
function HMS2S (in h, in m, in s)
Converts hours, minutes and seconds into seconds.
function HorizonUnitVectors (in r, in v, in a, in theta)
Compute horizon unit vectors.
function HRG (in hRGDS, in w, in dT)
Model a hemispherical resonating gyro.
function HRY (in x, in ignoredArg, in ignoredArg, in ignoredArg)
Measurement equation for a roll/yaw controller.
function HSAData (in us, in un, in eradius, in ua, in spinrate, in cant, in dihedral, in quant, in qtype, in onesigma, in delay)
Computes the hsa (horizon) sensor data for a spinning spacecraft.
function HSAPlot (in ra, in dec, in tle1, in tte1, in tle2, in tte2, in t, in dt)
Plots the HSA sensor data.
function HydrazineThruster (in d, in pressure, in pulsewidth, in dT)
Computes the thrust and fuel consumed for thrusters.
function HysteresisOutput (in t, in y, in flag, in d)
Gather output from the hysteresis damping simulation.
function IC3X326 (in x)
Convert 3x3 inertia matrix to [Ixx Iyy Izz Ixy Ixz Iyz].
function IFOV (in altitude, in f, in a, in d, in lambda)
Instantaneous field of view of an optical sensor.
function Illumination (in rS, in rC, in uS, in uC, in rho, in iL, in fNumber)
Camera illumination model.
function IMU (in action, in varargin)
Inertial measurement unit model.
function InertiaTotal (in inertia, in mass, in rCM, in rHinge, in u, in angle, in omega, in inertiaTotal)
Computes the new inertia and body rate when appendages change discretely.
function IntensityDistribution (in action, in varargin)
Computes the pixel map intensity.
function ISSCoord (in r, in jD)
Computes the coordinates in the ISS frame.
function ISSOrbit (in set)
Generate Keplerian elements for the ISS.
function JDToFirstOfMonth (in jD)
Finds first day of month for a Julian date.
function JHAPLSatelliteMass (in s, in p)
Mass breakdown of JHU APL satellites.
function KConst (in x, in ignoredArg, in constData)
The constraint equations and Jacobians.
function KConstP (in q, in ignoredArg, in constData)
The constraint equations and Jacobians.
function KConstQ (in q, in ignoredArg, in omega)
The constraint equations and Jacobians.
function LagrangePointsL1ToL5 (in mu)
Computes the position of Lagrange points in normalized rotating.
function LibrationFrequency (in inertia, in n)
Compute the libration frequency from inertia and orbit rate.
function LightDetectorIntegrals (in starType, in detector)
Normalized stellar-light detector integral given a star type and detector.
function LinOrbNormalized ()
Computes the normalized linearized orbit state equations.
function LoadEarthMap (in name)
Creates a figure with Earth texturemap, political boundaries, and lat/lon.
function LoadFK5 (in catName, in VMMin)
Reads in the FK5 catalog in MICA format.
function LoadFlex (in file, in path)
Reads in flex data from a formatted text file.
function LoadGOES (in tS, in file)
Loads GOES binary data.
function LoadMag (in sc, in CDROM, in mmS, in yyS, in mmF, in yyF, in suffix)
Loads GOES magnetometer data.
function LoadSatP (in file)
Loads in GOES Satellite Positions.
function LoadSers (in sc, in fT, in CDROM, in mmS, in yyS, in mmF, in yyF, in suffix)
Loads GOES data from multiple files.
function LoadSolarFluxHistory ()
Load the solar flux history and save a new mat-file.
function LocalSolarTime (in jD, in rECI)
Computes local solar time.
function LocalStarMap (in lY, in filename)
Generates a local star map.
function MagAirC (in dipole, in dim, in weight, in wire)
Designs an air coil by minimizing a weighted combination of power and mass.
function MagControlThreeAxis (in t, in b, in time)
Dipole vector needed to produce a torque given the magnetic field over time.
function MagControlTwoAxis (in t, in b, in a)
Two axis magnetic control dipole.
function MagField (in position, in jD, in nMax, in varargin)
Computes the Earth magnetic field using the DGRF/IGRF model.
function MagFieldData (in planet)
Data for planet magnetic fields.
function MagFieldPlanet (in r, in g, in h, in a, in nMax)
Computes the magnetic field using Schmidt normalized coefficients.
function MagneticDipole (in m, in theta, in r)
Computes the magnetic field of a dipole along the z axis.
function MagneticDipoleCart (in m, in p)
Computes the magnetic field of a dipole along m.
function MagneticFieldDipole (in m, in r)
Computes the magnetic field of a dipole.
function MagneticHysteresis (in b, in ignoredArg, in h, in hDot, in d)
Right hand side for a dynamical model of magnetic hysteresis.
function MagneticTorquer (in action, in d)
Simple MagneticTorquer model.
function MagneticTorquerDesign (in d)
Design a minimum mass magnetic torquer.
function MagneticTorquerDipoleMoment (in l, in r, in muR, in n, in i)
Compute the moment for a magnetic torquer.
function MagTComp (in Isp, in r, in bMedian)
Performs a tradeoff of magnetic torquers versus thrusters.
function MagTorquer (in action, in input)
Models a magnetic torquer.
function ManeuverCostSphere (in startNode, in nextNode, in d)
Maneuver cost on a sphere.
function MBModel (in inr, in h, in wo, in dT)
Momentum bias spacecraft model.
function MeasEarthSensor (in x, in d)
Returns roll and pitch for a generic earth sensor.
function MeasMagnetometerEarth (in x, in d)
Returns magnetic field measurement in Earth orbit.
function MeasRateGyro (in x, in d)
Returns body rate information.
function MeasRateIntegratingGyro (in x, in varargin)
Model of a rate integrating gyro measurement.
function MeasRelativePosition (in x, in d)
Returns relative position information.
function MeasStarTracker (in x, in d)
Returns the output of a star tracker.
function MeasState (in x, in d)
Returns elements of a state vector as a measurement.
function MeasSunSensorAnalog (in x, in d)
Returns analog sun sensor measurements.
function MeasSunSensorDigital (in x, in d)
Returns digital sun sensor measurements.
function MolWt2R (in molWt)
Computes R given the molecular weight.
function MomArm (in r, in u, in c)
Computes the moment arms for a set of thrusters.
function MoonEl (in jD)
Computes the moon orbital elements with respect to the earth inertial frame.
function Moons (in name)
Lists moons of a planet or planet center about which a moon orbits.
function MoonV1 (in jd, in rSc)
Generate the moon vector in an earth or spacecraft centered frame.
function MoonV2 (in jD, in rSc)
Generate the moon vector in an earth or spacecraft centered frame.
function MSidDay (in jD)
Computes a mean sidereal day.
function MSolDay (in jD)
Computes a mean solar day.
function Nadir (in cant, in rho, in chordwidth)
Computes nadir angle from a cant angle, earth angle and chordwidth.
function NavigationCamera (in x, in d)
Returns the planet centroid and the local stars locations.
function NavigationMeasurement (in r, in q, in jD, in d)
Navigation measurement model.
function NavObservables (in r, in rP, in radiusP, in jD, in nameP, in nameM, in alb)
Computes optical navigation observables.
function NewtonianForceECI (in qECIToBody, in nBody, in a, in uECI, in rho)
Computes the Newtonian force in ECI coordinates.
function NPSPM (in pulsewidth, in t, in h, in s, in spinRate, in uSun, in rAI, in decI, in rAF, in decF, in tauRise, in tauFall)
Computes a spin precession maneuver using a rhumb line precession.
function NRLArray (in variant, in display, in d)
Generates data for the NRL SolarCon solar array.
function NutationMWA (in iX, in iZ, in hMWA)
Nutation with a momentum wheel.
function NutDelta (in T)
The changes in longitude and obliquity due to earth nutation.
function ObOfE (in T)
Computes the mean obliquity of the ecliptic of date.
function Optic2D (in h, in u)
Models a generic 2 dimensional optical sensor.
function OpticalSurfaceProperties (in s)
Returns optical surface properties for selected materials.
function OrbitDisplayPlugIn (in action, in modifier, in hFig, in position, in planet)
Create an orbit display.
function Parallax (in rT, in rO)
Calculate the parallax.
function ParseCommand (in s, in d)
Parse a command string.
function PBudget (in errors, in desc, in categ, in aZ, in eL, in file)
Computes a pointing budget over n categories.
function PCentr (in taur, in tauf, in pulsewidth)
Calculates the time from pulse start to the centroid.
function PermanentMagnetRHS (in x, in t, in d)
Right-hand-side for attitude dynamics with a permanent magent.
function PID3Axis (in q_ECI_body, in d)
A PID-based 3 axis controller for rigid body.
function PivotMch (in k, in b, in l, in x0, in steps)
Models a pivot mechanism and converts stepping motor steps to pivot angle.
function PlanetPosition (in action, in d)
The position vectors, gravitational parameters and velocity for the planets.
function PlanetRotation (in planet)
Computes the mean planet rotation rates from their rotation periods.
function Planets (in units, in k)
Simplified planet ephemerides from the almanac.
function PlanetSensorDualScan (in r, in q, in d)
A dual scan Earth Sensor model.
function PlanetYear (in k)
Length of year of planets in terms of Earth years.
function PlotHysteresis (in B, in H)
Create hysteresis plots.
function PlotPlanet (in r, in radius, in color, in noLines, in n)
Add planet to the current axes.
function PlotPlanetOrbit (in xECI, in jD, in objName, in planet, in eCIFlag)
Plot a 3D orbit around a planet in the ECI or planet fixed frame.
function PltOrbit (in el, in jD, in uSpin, in planet)
Plots one orbit and the sun vector looking down on the ECI Plane.
function PlugInDemo (in action)
Demonstrate using the GUI plug ins with an orbit simulation.
function PointCameraModel (in camera, in rBody, in qBody, in distance)
Compute the MATLAB camera pointing parameters from the camera model.
function PointingBudgetGUI (in action, in tag)
Creates pointing budgets using a GUI.
function PointingBudgetLatex (in errors, in desc, in categ, in aZ, in eL, in file)
Computes a pointing budget over n categories.
function PointSpreadFunction (in u)
Point spread function for a circular aperture.
function PowerDesign (in el, in jD, in power, in battery, in solarArray)
Sizes the battery and solar array.
function PPDelay (in azimuth, in pulsewidth, in t, in h, in s, in spinRate, in tauRise, in tauFall)
Compute the pulse pair delay for a Spin Precession Maneuver.
function PropellantMass (in V, in R, in T, in rhoFuel, in pMax, in pMin)
Compute the propellant mass and pressurant mass for a tank.
function PWMSeq (in m, in dT, in x, in dTSeq, in wDither)
Generate a pulsewidth modulated sequence given x.
function QAlignWithCon ()
Rotate about a body axis to align a body vector with an inertial vector.
function QMultJPL (in Q2, in Q1)
Q2 transforms from A to B and Q1 transforms from B to C.
function QProp (in qLast, in theta, in n)
Propagates a quaternion based on updated angular increment measurements.
function QRotateToAlignWithCon ()
Calculate the alignment quaternion while applying constraints.
function QSpin (in x, in u, in angle)
Creates a series of quaternions with its x axis spinning about u.
function QSunNadir (in rECI, in vECI, in uSunECI, in xNoSun, in alphaLimit)
Compute the sun-nadir quaternion and other quantities.
function QSunPointing (in uSun)
Creates a sun reference frame with +x pointing at the sun.
function RADec2FP (in rAC, in decC, in rA, in dec, in f)
Converts right ascension and declination into focal plane coordinates.
function RadiationBelts (in r, in t, in jD, in ignoredArg)
Plots the radiation belts.
function RangeMeasurement (in r, in v, in c, in rSource, in vSource)
Computes range and range rate measurements.
function RateGyro (in h, in w, in dT, in a)
Model a rate gyro.
function RBModel (in inr, in w, in t, in invInr, in dT)
Computes the angular acceleration of a rigid body.
function ReactionWheel (in action, in u)
RWA model.
function ReactionWheelFriction (in omega, in d)
Computes the friction for a reaction wheel.
function ReactionWheelStress (in rO, in rI, in omega, in nu, in rho, in t)
Reaction wheel strength and momentum.
function ReadBSPFile (in varargin)
Read a bsp file.
function ReadMagField (in fileName)
Read in the magnetic field from a file.
function RHSClockDrift (in t, in tau, in d)
Gravitational and velocity clock drift.
function RHSCMG (in x, in t, in d)
Spacecraft attitude and orbit dynamics with a disturbance function.
function RHSFriction (in x, in ignoredArg, in d)
Computes dynamics with friction for two different models.
function RHSGGRotational (in x, in t, in d)
Right-hand-side for spacecraft attitude dynamics with gravity gradient.
function RHSGyroNBody (in x, in ignoredArg, in g)
Right hand side for n bodies and a central hub with reaction wheels.
function RHSGyrostat (in x, in ignoredArg, in d)
Gyrostat right-hand-side with a wheel friction function.
function RHSGyrostatNoFriction (in x, in ignoredArg, in d)
Gyrostat right-hand-side with no wheel friction.
function RHSGyroWithOrbit (in x, in ignoredArg, in d)
Right-hand-side for spacecraft attitude and orbit with a gyro.
function RHSHysteresisDamper (in x, in bECI, in bDotECI, in d)
Right hand side for a dynamical model of magnetic hysteresis.
function RHSMEMSGyro (in x, in ignoredArg, in d)
Simulate a MEMS gyro.
function RHSNBodyCentralHub (in x, in ignoredArg, in g)
Right-hand-side for n rigid bodies attached to a central hub.
function RHSNBodySH (in x, in ignoredArg, in g)
Right-hand-side for n rotating bodies attached to a central hub.
function RHSNSpacecraft (in x, in ignoredArg, in d)
Computes the time derivative of n spacecraft.
function RHSPlanetTakeoff (in x, in ignoredArg, in a, in g, in beta, in signX)
Right-hand-side for a 2 dimensional planet takeoff.
function RHSPointMass (in x, in t, in d)
Spacecraft orbit dynamics with time-varying mass.
function RHSReactionWheel (in x, in ignoredArg, in d)
Right-hand-side for spacecraft attitude with reaction wheels.
function RHSReactionWheelWithOrbit (in x, in ignoredArg, in d)
Right-hand-side for spacecraft attitude and orbit with reaction wheels and gyros.
function RHSRigidBody (in x, in t, in d)
Spacecraft attitude and orbit dynamics with a disturbance function.
function RHSRigidBody6DOF (in x, in ignoredArg, in d)
6 DOF spacecraft dynamics with a double integrator position model.
function RHSRigidBodyLinear (in x, in ignoredArg, in d)
Linearized attitude dynamics for a rigid body.
function RHSRigidBodyMass (in x, in t, in d)
Spacecraft attitude and orbit dynamics with time-varying mass.
function RHSRigidBodyOffsetCM (in x, in ignoredArg, in d)
Right hand side of a rigid body with offset CM.
function RHSRigidBodyWithDamping (in x, in t, in d)
Rigid body dynamics with damping.
function RHSRigidBodyWithTarget (in x, in ignoredArg, in d)
Right-hand-side of spacecraft dynamical equations with a second spacecraft.
function RHSRWA (in x, in t, in d)
6 DOF right-hand-side for spacecraft with reaction wheels and a disturbance function.
function RHSRWAIDotSC (in x, in t, in d)
Right-hand-side with attitude, orbit, wheels, and time-varying inertia.
function RHSRWAOrbit (in x, in ignoredArg, in d)
Computes the right hand side for a spacecraft with reaction wheels.
function RHSRWASC (in x, in t, in d)
Right-hand-side of the dynamical equations with three ReactionWheels.
function RHSSlosh (in x, in ignoredArg, in g)
Right hand side for a n bodies attached to a central hub.
function RHSSNP (in x, in ignoredArg, in d)
Spacecraft sun-nadir RHS with 4 RWA's and 2 solar arrays.
function RHSSpacecraftWithIMU (in x, in ignoredArg, in d)
Right-hand-side for a spacecraft with an IMU.
function RHSSpacecraftWithRWA (in x, in ignoredArg, in d)
Right-hand-side for attitude and orbit of spacecraft with reaction wheels.
function RHSThreeBody (in x, in ignoredArg, in d)
Right hand side for a three body system.
function RIGModel (in u, in w, in b, in nRW, in nB, in beta)
Computes the output of a rate integrating gyro package.
function RIGOut (in intRate, in intRateOld, in n)
RIG output.
function RLP (in uSun, in rAI, in decI, in rAF, in decF)
Rhumb line precession.
function RLPMnvr (in uSun, in rAI, in decI, in azimuth, in prec, in n)
Simulate a rhumb line precession.
function RMoonECI (in jD)
Generate the moon position in the earth-centered inertial frame.
function RocketEquation (in deltaU, in massInitial, in uExhaust)
Compute the final mass from the rocket equation.
function RSunECI (in jD)
Generate the sun position in the earth-centered inertial frame.
function RW2SDev (in randomWalk)
Converts random walk measured over dT to standard deviation.
function RWA (in action, in y, in k)
A reaction wheel model using FrictionSmooth.
function RWABristle (in action, in y, in k)
A RWA model using FrictionBristle to model the wheel friction.
function RWACountToRate (in tachWord, in d)
Converts RWA tachometer count to rate.
function RWAMnvrSizing (in inr, in theta, in tau)
Size a reaction wheel using maneuver requirements.
function RWASizing (in inr, in omega, in omegaDot, in omegaRWAMax)
Size a reaction wheel using maneuver requirements.
function RWASmart (in action, in u)
Smart RWA model.
function RWASpec (in input)
Calculates RWA parameters from spec sheet parameters.
function RWAWithPower (in omega, in d)
RWA with power and heat.
function RYDyn (in inr, in hw, in wo, in iAxis)
Generates open loop four channel magnitude plots for roll/yaw dynamics.
function S2HMS (in s)
Converts seconds into hours, minutes and seconds.
function SatelliteSubsystemMass (in subsystem, in mSc, in param)
Create masses for a satellite from scaling laws.
function SaveSurfacePropertiesDSim (in file, in v, in f, in cD, in rho)
Save surface properties to the file.
function SCClock (in action, in d)
Models a spacecraft clock.
function ScDB (in q, in gUICode)
GUI to output the value of a constant for a spacecraft.
function SCWithRollPivot (in x, in t, in d, in action)
Model for a spacecraft with a roll pivot.
function SCwPivot (in x, in jW, in jP, in iS, in t, in tW, in tP, in uW, in uP)
Model for a spacecraft with a single pivoted momentum wheel.
function SDG (in u, in h, in cD, in k, in kF, in w, in x, in bias, in nU, in nV, in nE)
Single degree of freedom mechanical gyros.
function SeparationSim (in x0, in dT, in tEnd, in d)
Simulate separation of multiple satellites from a carrier.
function SingleAxisDrive (in action, in d)
Model a stepping motor drive.
function SingleAxisLinearDrive (in action, in d)
Model a single axis drive with the motor dynamics modeled by a lag.
function SkewDipl (in b, in tRoll, in tYaw)
Computes the skew angle for a single dipole used to control yaw and roll.
function SolarF (in p, in rho, in normal, in source, in area)
Compute the solar force on a set of elemental areas.
function SolarFlux (in r, in n)
Solar flux from the sun as a function of distance including sunspots.
function SolarFluxFromPlateECI (in r, in rP, in n, in a, in rho, in b, in fNum, in jD)
Computes the flux from a flat plate.
function SolarFluxHistorical (in jD)
Computes the solar flux prediction based on Julian date.
function SolarFluxPrediction (in jD, in timing, in dateForm)
Computes the solar flux prediction based on Julian date.
function SolarFlx (in au)
Solar flux from the sun as a function of distance in AU.
function SolarSys (in iv, in Wv, in wv, in av, in ev, in Lv, in name, in jdref, in T)
Computes the position vectors of the planets as a function of time.
function SolarSystemElements (in iv, in Wv, in wv, in av, in ev, in Lv, in jD)
Computes the solar system elements on a given Julian Date.
function SolarSystemProperties (in name)
Look up a moon or planet and return its properties.
function SolarVisibility (in rECI, in jD, in animate, in centralBody, in fov, in map3d)
Compute the solar intensity experienced by a spacecraft.
function SortFK5 (in catName, in newCat, in lYMax)
Sort FK5 by distance in light years and save in a new file.
function SpacecraftStatePlugIn (in action, in modifier, in hFig, in position, in callback)
Create an spacecraft state GUI plug in.
function Spectrum (in band, in n)
Gives the spectrum for radiation using conventional names.
function SSA (in)
Simulates a single axis suns sensor.
function SSEye (in m, in a)
Power series model for the output of an analog sun sensor.
function StarCameraViewer (in action, in y, in n, in h, in d, in k)
Views the output from NavigationCamera.
function StarMap (in catName, in lYMax)
Draws a star map.
function StarTexture (in starFile, in textureFile, in size, in width)
Create a star texture for use in other programs.
function StellarIrradiance (in m, in starType, in detectorType)
Computes the stellar irradiance.
function StepSim (in x, in t, in dS)
Simulates a two phase stepper motor.
function StepTorque (in ignoredArg, in ignoredArg, in d)
Produces a step torque.
function StructureAnalysis (in cADModel)
Analyze the structure of a small agile satellite.
function SumRXF (in r, in f, in cM)
Sum a set of torques produced by summing T = rxF.
function SunBeta (in i, in uSun, in rA)
Compute the sun beta angle from the sun vector and orbit.
function SunNadir (in xNoSun, in orbitRate, in beta, in alpha, in alphaLimit)
Compute the sun-nadir angles and yaw rate.
function SunSensor (in t1, in t2, in alpha1, in alpha2, in f1, in f2, in angle)
Two detector sun sensor.
function SunV1 (in jD, in rSc)
Generate the sun vector in the earth-centered inertial frame.
function SunV2 (in jD, in rSc)
Moderate precision sun model.
function SunVectorECI (in action, in varargin)
Finds the sun vector any place in the solar system.
function SunVectorPointing (in uECI, in uSunECI)
Compute the angles to align the solar wing normal with the sun.
function TankVolume (in vT, in rhoF, in tNom, in pI, in pF, in rP)
Computes fuel mass from tank volume.
function TargetSlew (in altitude, in rTarget, in mu, in inertia)
Compute a slew to a target.
function TBModel (in w0, in w1, in q0to1, in r0, in r1, in lam1, in iner0, in iner1, in)
Models two rigid bodies attached by a 1 to 3-dof hinge.
function TerminatorLine (in jD, in n)
Compute the terminator line on the Earth that defines day/night.
function TerminatorPlanet (in r, in radius, in n)
Computes the terminator circle on a planet.
function TerrestrialSolarFlux (in jD)
Solar flux and direction from the sun with seasonal variation.
function TGG (in inr, in u, in wO)
Computes a gravity gradient torque.
function ThreeAxisControlDisturb (in ignoredArg, in d, in x)
Computes solar disturbances for ThreeAxisControl.m.
function ThrusterAndRWACommand (in t, in pOn, in kACS, in kRWA, in d)
Computes forces and torques for RWAs and thrusters using off-pulsing.
function ThrusterColdGas (in mass, in t0, in c, in d)
Cold gas thruster propulsion system.
function ThrusterCommand (in t, in pOn, in kACS, in d)
Computes forces and torques for a set a thrusters using off-pulsing.
function TileOBJSphere (in d, in fileName, in nLat, in nLon)
Creates a segmented unit sphere Wavefront obj and mtl files.
function TorqueHysteresisDamper (in u, in b, in v, in bE)
Torque from a hysteresis damper.
function TorqueRod (in action, in u)
Torque rod model using tanh.
function TransformLagrangePoints (in p, in jD)
Computes the position and velocity of stable Lagrange points (Earth/moon).
function TRD (in m, in b)
Computes residual dipole torques.
function Tree (in x, in t, in treeDS, in bodyData, in mu)
Right hand side of the equations of motion for a topological tree.
function TreeAdd (in inertia, in r, in lambda, in mass, in kPrev, in dOF, in w, in q, in b, in kSpring, in cSpring, in name)
Add a body to the tree data structure.
function TreeH (in x, in t, in treeDS, in bodyData)
Computes the momentum for the topological tree dynamics.
function TreeInit (in body, in r, in v, in gGOn)
Create the tree data structure.
function TreePlot (in tPlot, in xPlot, in treeDS, in body, in hPlot)
Plot the output of tree.
function TreePrnt (in body, in treeDS)
Print out the body information for the tree model.
function TRF (in u, in r, in p)
Computes an RF torque for a set of antenna.
function TruEarth (in T, in useEofE)
Computes the matrix from mean of Aries 2000 to earth fixed frame.
function TSolarP (in x, in uSource, in sourceIntensity, in doShadowing)
Generates solar pressure torques with shadowing.
function TwoC2F (in hi, in lo, in b)
Converts two's complement of length 2b to a floating point number.
function TwoUToQ (in u1, in u2, in u1T, in u2T)
Finds the quaternion that transforms u1 and u2 to u1T and u2T.
function U2FP (in u, in uB, in uY, in f)
Computes the location in the focal plane of unit vectors.
function U2Pix (in u, in f, in offset)
Converts a unit vector into a pixel location.
function UDipole (in jD)
Computes the geocentric magnetic field based on a tilted dipole model.
function URWAPyramid (in n, in uC, in cant)
Generate unit vectors for a RWA pyramid.
function UVAA (in hRA, in mRA, in sRA, in dDec, in mDec, in sDec)
Apparent sun vector from quantities tabulated in the astronomical almanac.
function VAtm (in r, in wP)
Atmospheric velocity from position and planetary rate.
function VelocityTimeDilation (in v)
Velocity time dilation.
function VIModel (in inr, in dinrdt, in w, in t, in dT)
Computes the angular acceleration of a body with time varying inertia.
function VXPhi (in v, in phi)
Take the cross product a matrix of vectors times a flex transformation matrix.
function Water (in t)
Properties of water.
function Weather (in tS, in file)
Loads GOES binary data.
function WeathLeg (in l, in box, in hK)
Draws the Weather Legends.
function WheelSpeed (in inrSc, in wSc, in inrWheel, in uWheel)
Compute the wheel speeds for a set of reaction wheels.
function WireC (in x, in t, in s, in mu, in torque, in force, in penalty)
The right hand side of the wire equations formulated using Lagrange multipliers.
function WireDMch (in s, in x, in time)
Models the deployment mechanism.
function WireFRB (in x, in t, in s, in mu, in torque, in force)
Spacecraft with multiple wires.
function WireH (in x, in s)
Magnitude of the angular momentum.
function WireInit (in nNodes, in mass, in massWire, in lWireMax, in kSpring, in cSpring, in vDeploy, in)
Initialize the wire model data structures.
function WirePlot (in xPlot, in t, in s)
Plot the wires.
function WMM (in action, in r, in jD)
Loads in the WMM.COF file.
function WordToFloat (in k, in kMax, in kMin, in resolution)
Convert an integer word to a floating point number.
function WorstEclipseFraction (in el0, in rP)
Worst-case eclipse fraction.
function WriteBSPFile (in varargin)
Create a bsp file.
Function Documentation
Accel()
function Accel (in x, in d)
This model includes quantization, noise and a bias.
 Since version 11.
Form
 y = Accel( x, d )
Inputs
 x         (:,1)  State vector
 d         (1,1)  Data structure
                  .kO       (3,1) Angular rates in body frame state
                  .omegaDot (3,1) Inertial angular acceleration
                  .accel    (3,1) Sum of all forces (except gravity)
                                         in the body frame
                  .r        (3,1) Position wrt c.m.
                  .u        (3,:) Unit vectors for the accelerometers
                  .noise    (:,1) One sigma noise
                  .bias     (:,1) Bias
                  .scale    (:)   Scale factor
                  .lSB      (1,1) Least significant bit
Outputs
 y         (3,1)   Accelerations
References and(), Cross(), DefaultData(), length(), SkewSq(), Unit(), and vector().
Referenced by LocallyOptimalConeClock3D(), LunarHalo(), NonKeplerianPlanet(), RHSHelio2DOrbit(), SEMGravAcc(), and StraightLineDataStructure().
ACSRWAAndTorquers()
function ACSRWAAndTorquers (in x, in d)
This control system does small angle attitude control using reaction wheels and momentum unloading using thrusters. Momentum unloading is a PI controller. Attitude control is a PID controller.
 d = ACS;
 [d,tREA,tRWA] = ACSRWAAndTorquers(x,d)
Inputs
 x (:,1)    State vector [r;v;q;omega;omegaRWA;angleGyro]
 d (.)      Data structure
            .dT        (1,1) Time step (s)
            .inr       (3,3) Inertia matrix (kg-m^2)
            .kM        (1,1) Momentum unloading forward gain (Nm/Nms)
            .tauI      (1,1) Momentum unloading integral time constant (s)
            .inrRWA    (1,1) Reaction wheel inertia (kg-m^2)
            .angleOld  (3,1) Stored gyro angle (rad)
            .hI        (3,1) Integral of the ECI momentum (Nms^2)
            .ECIToBody (4,1) Quaternion from ECI to body
Outputs
 d    (.)   Data structure
 tREA (3,1) Torque demand for the thrusters (Rocket Engine Assemblies)
 tRWA (3,1) Torque demand for the thrusters (Reaction wheel Assemblies)
 Copyright (c) 2022 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since version 2022.1
References ACSRWAAndTorquers(), and(), Integral(), PID(), QForm(), QTForm(), and vector().
Referenced by ACSRWAAndTorquers().
AddMassDot()
function AddMassDot (in mADot, in mA, in mBDot, in mB, in u)
 mB is optional. mA and/or mB may be arrays
 of data structures. This assumes the mass is constant.
Form
 [m, mDot] = AddMassDot( mADot, mA, mB, mBDot, u )
Inputs
 mADot      (:)    Mass dot data structure
                    .mass    (1,1) Mass
                    .cM      (3,1) Center-of-mass
                    .inertia (3,3) Inertia matrix
 mA         (:)    Mass data structure
                    .mass    (1,1) Mass
                    .cM      (3,1) Center-of-mass
                    .inertia (3,3) Inertia matrix
 mBDot      (:)    Mass dot data structure
                    .mass    (1,1) Mass
                    .cM      (3,1) Center-of-mass
                    .inertia (3,3) Inertia matrix
 mB         (:)    Mass data structure
                    .mass    (1,1) Mass
                    .cM      (3,1) Center-of-mass
                    .inertia (3,3) Inertia matrix
 u          (1,:)  Units
Outputs
 m          (:)    Mass data structure
                    .mass    (1,1) Mass
                    .cM      (3,1) Center-of-mass
                    .inertia (3,3) Inertia matrix
 mDot       (:)    Mass dot data structure
                    .mass    (1,1) Mass
                    .cM      (3,1) Center-of-mass
                    .inertia (3,3) Inertia matrix
References AddMassDot(), and(), isempty(), length(), Skew(), and zeros().
Referenced by AddMassDot().
AddRobotArm()
function AddRobotArm (in action, in previousBody, in firstBody, in rBase, in link)
 Adds one body per linke an one cylinder per link. Each joint may
 have multiple one degree of freedom joints represented by unit vectors
 and angles
 As an example
 link(k).u       = [1;0;0];
 link(k).r       = [0;0;0.02];
 link(k).angle   = pi/4;
 link(k).mass    = 0.02;
 link(k).radius = 0.01;
 link(k).b       = eye(3);
 link(k).power   = 1;
 link(k).name    = 'wrist';
 AddRobotArm( 'add bodies', 1, 4, [0;0;zBox], link );
 BuildCADModel( 'compute paths' );
 AddRobotArm( 'add components', 1, 4, [0;0;zBox/2], link );
 Since version 10.
Form
 AddRobotArm( action, previousBody, firstBody, rBase, link )
Inputs
 action          (1,:)  'initialize' or 'update'
 previousBody    (1,1)  Body to which the arm is attached
 firstBody       (1,1)  First body in the robot chain
 rBase           (3,1)  Location of the base on the previous body
 link            (:)    Data structure
                        .u      (3,:) Joint unit vectors
                        .r      (3,1) Vector from the joint to the link end
                        .angle  (1,:) Joint angles   = pi/4;
                        .mass   (1,1) Link mass
                        .radius (1,1) Link radius
                        .power  (1,1) Link motor power consumption
                        .name   (1,:) Link name
Outputs
 None
References AddRobotArm(), and(), AU2Q(), BuildCADModel(), CreateBody(), CreateComponent(), length(), Mag(), Q2Mat(), and QMult().
Referenced by AddRobotArm().
AddSurf()
function AddSurf (in id, in name, in area, in cP, in normal, in rhoAbsp, in rhoSpec, in rhoDiff, in x)
Form
 x = AddSurf( id, name, area, cP, normal, rhoAbsp, rhoSpec, rhoDiff, x  )
Inputs
 id              (1,1)   Identification number
 area            (1,1)   Surface area
 normal          (3,1)   Surface outward unit normal
 rhoAbsp         (1,1)   Absorption coefficient
 rhoSpec         (1,1)   Specular reflection coefficient
 rhoDiff         (1,1)   Diffuse reflection coefficient
 x               (:,:)   Element data structure
                         x.id       (1,1)     Surface id number
                         x.name     (1,:)     Surface name
                         x.area     (1,1)     Surface area
                         x.cP       (3,1)     Center-of-pressure
                         x.normal   (3,1)     Outward normal
                         x.rhoAbsp  (1,1)     Absorption coefficient
                         x.rhoSpec  (1,1)     Specular reflection coefficient
                         x.rhoDiff  (1,1)     Diffuse reflection coefficient
Outputs
 x               (:,:)   Updated data structure (with individual forces
                         and torques)
References and(), isempty(), length(), and Unit().
AeroDragForce()
function AeroDragForce (in x, in area, in cD, in jD)
Uses the scale height atmosphere model (AtmDens2). Assumes the area is pointed along the velocity vector at all times. If a Julian date is entered it will account for the effect of Earth rotation on the relative velocity.
This is the simplest drag force model. For a simple model that takes attitude into account, see CubeSatAero. For the full model using the CAD tools see Disturbances.
Form
 force = AeroDragForce( x, area, cD, jD )
Inputs
 x      (6,1)     State [r;v]
 area   (1,1)     Area (m2), default 1.0
 cD     (1,1)     Coefficient of drag, default 2.2
 jD     (1,1)     Julian date
Outputs
 force    (N)     Force in the ECI frame
See also
: AeroF, AtmDens2, Disturbances
References AeroDragForce(), AeroF(), Altitude(), AtmDens2(), CubeSatAero(), Date2JD(), Demo(), Disturbances(), ECIToEF(), isempty(), JD2Array(), JD2T(), length(), Mag(), Plot2D(), Rename(), RVFromKepler(), Skew(), TimeLabl(), Unit(), vector(), and zeros().
Referenced by AeroDragForce().
AeroF()
function AeroF (in rho, in cD, in v, in normals, in area)
The velocity vector and normal vectors must be in the same frame.
Form
 [f,fT] = AeroF( rho, cD, v, normal, area )
Inputs
 rho           (1,1) Atmospheric density (kg/m3)
 cD            (1,1) Coefficient of drag
 v             (3,1) Velocity relative to the atmosphere (km/s)
 normal        (3,n) Surface normal vectors
 area          (n)   Elemental area (m2)
Outputs
 f             (3,n) Aero force on elements (N)
 fT            (3,1) Total force on body
Reference: Hughes, P. C., "Spacecraft Attitude Dynamics" John Wiley and Sons, 1986, pp. 251.
References and(), get(), Mag(), set(), and vector().
Referenced by AeroDragForce().
AI2Rate()
function AI2Rate (in a, in dT, in m, in aOld)
 To prevent transients set aOld = DupVect(a,m) upon initialization. You can
 initialize by passing AI2Rate only 2 or 3 arguments.
Form
 [w, aOld] = AI2Rate( a, dT, m, aOld )
Inputs
 a              (n,:)     Attitude increments
 dT             (1,1)     Time between increments
 m              (1,1)     Order (0, 1 or 2)
 aOld           (n,m)     Last m attitude increments
Outputs
 w              (n,:)     Estimated rate
 aOld           (n,m)     Last m attitude increments
References: Wong, E.C. and Breckenridge, W.G. (1983). Inertial Attitude Determination for Dual-Spin Planetary Spacecraft. J. Guidance 6(6), 491-498.
References AI2Rate(), and(), DupVect(), Plot2D(), set(), and zeros().
Referenced by AI2Rate().
AirCoreMagneticTorquerDesign()
function AirCoreMagneticTorquerDesign (in d)
 You pass in the dipole, wire physical parameters and wire dimensions.
 It minimizes the weighted cost:
 cost = alpha*mass + power
 The voltage is determined by the dimensions, resistivity and dipole.
 As an alternative you can input the voltage and it will return the
 dipole.
 Type AirCoreMagneticTorquerDesign for a demo using copper wire.
 Since version 11.
Form
 d = AirCoreMagneticTorquerDesign( d )
Inputs
 d           (1,1)   Data structure
                     .aWG              (1,1) Wire gauge 0000 is -3
                     .dipole or .v     (1,1) Dipole (ATM^2) or Voltage (V)
                     .densityConductor (1,1) Conductor density (kg/m^3)
                     .conductivity     (1,1) Conductivity (S/m)
                     .dim              (1,2) Dimensions of the coil (m)
                     .alpha            (1,1) Weight for mass (W/kg)
Outputs
 d           (1,1)   Data structure with additions
                     .rWire            (1,1) Wire radius (m)
                     .i                (1,1) Current (A)
                     .rhoWire          (1,1) Resistance (Ohm/m)
                     .lWire            (1,1) Wire length (m)
                     .mWire            (1,1) Mass wire (kg)
                     .R                (1,1) Coil resistance (Ohm)
                     .nTurns           (1,1) Wire turns
                     .v                (1,1) Voltage (V)
                     .power            (1,1) Power (W)
See also
DiameterAWG, ResistanceAWG
References AirCoreMagneticTorquerDesign(), and(), Demo(), DiameterAWG(), Dipole(), length(), and ResistanceAWG().
Referenced by AirCoreMagneticTorquerDesign().
AiryDisk()
function AiryDisk (in lambda, in F, in Ld)
 Type AiryDisk for a demo of a F 2 lens with visible light and a 0.2 mm
 focal plane offset to blur the image. The Airy pattern has a small
 effect on the disk size even with a 0.2 mm displacement of the focal
 point.
Form
 d = AiryDisk( lambda, F, Ld )
Inputs
 lambda         (1,:) Wavelength
 F              (1,1) F stop
 Ld             (1,1) Defocus
Outputs
 d              (1,:)  Radius
References AiryDisk(), and(), Demo(), Disk(), Plot2D(), set(), and Wavelength().
Referenced by AiryDisk().
AlbedoFromTextureMap()
function AlbedoFromTextureMap (in planetFile, in cloudFile, in planetFun, in cloudFun, in alphaAve)
 Works with any Matlab compatible file format. Has a built-in demo.
 Functions to convert texture maps to albedo may be supplied in the form
 alpha      = fun( textureMap );
 textureMap is a Matlab generated format using the Matlab imread function.
 textureMap = imread( fileName );
 The default functions assume value of:
 blue - 0.14, green - 0.3, brown - 0.45, white - 0.87, clouds - 0.8
Form
 [alpha, alphaMean] = AlbedoFromTextureMap( planetFile, cloudFile, planetFun,...
 cloudFun, alphaAve )
Inputs
 planetFile  (1,:) Name of the planet file, see EarthMid.jpg
 cloudFile   (1,:) Name of the cloud file, see cloudsMid.jpg
 planetFun   (1,:) Name of the planet function*
 cloudFun    (1,:) Name of the cloud cloud function*
 alphaAve    (1,1) Default alpha (0.34 is the default )
                    * Default functions are provided.
Outputs
 alpha       (:,:) Albedo map
 alphaMean   (1,1) Mean alpha
References AlbedoFromTextureMap(), and(), Demo(), get(), isempty(), NewFig(), set(), and zeros().
Referenced by AlbedoFromTextureMap(), and DistributedAlbedo().
AlphaBetaToU()
function AlphaBetaToU (in alpha, in beta, in r, in v)
The unit vector is in the same coordinates as r and v. beta is the angle from x to y in the x-y plane which is the position velocity plane. beta = 0 is the local horizontal. alpha is out of that plane.
Type AlphaBetaToU for a demo in a polar orbit with the velocity vector along +z and the position vector along +x. Beta is fixed and alpha varies from -1 to +1. A second demo holds beta = 0 and alpha = 0 for a quarter polar orbit.
Form
 u = AlphaBetaToU( alpha, beta, r, v )
Inputs
 alpha   (1,1)   Angle out of the rv plane
 beta    (1,1)   Angle in the rv plane
 r       (3,1)   Position vector
 v       (3,1)   Velocity vector
 mu      (1,1)   Gravity constant
Outputs
 u       (3,1)   Unit vector
References AlphaBetaToU(), and(), Demo(), length(), Plot2D(), Q2Mat(), QLVLH(), Unit(), vector(), and zeros().
Referenced by AlphaBetaToU().
AltitudeHold()
function AltitudeHold (in x, in kH, in tauH, in g, in mass, in xSet)
 [u,thrust,angle] = AltitudeHold(x,kH,tauH,g,mass,xSet)
Inputs
 x (:,1)    State vector [r;v]
 d (.)      Data structure
            .tauH (1,1) Damping time constant (s)
            .kH   (1,1) Forward gain (N/km^3)
            .g    (1,1) Acceleration of gravity (N/km^2)
            .mass (1,1) Mass (kg)
            .xSet (6,1) State vector set point [r;v]
Outputs
 u      (3,1) Thrust unit vector
 thrust (1,1) Thrust (N)
 angle  (1,1) Thrust angle (rad)
 Copyright (c) 2022 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since version 2022.1
References Altitude(), AltitudeHold(), Mag(), QTForm(), set(), U2Q(), and vector().
Referenced by AltitudeHold().
AltitudeSH()
function AltitudeSH (in r, in s, in c, in nH)
Type AltitudeSH for a demo flying in a polar orbit over the moon.
Form
 h = AltitudeSH( r, s, c, nH )
Inputs
 r       (3,:) Position planet fixed (km)
 s       (:,:) Normalized sine coefficients (m)
 c       (:,:) Normalized cosine coefficients (m)
 nH      (1,1) Number of harmonics to use
Outputs
 h       (1,:) Altitude (km)
References Altitude(), AltitudeSH(), and(), Demo(), DupVect(), length(), LoadLunarTopography(), Mag(), PAL(), SCHarm(), and zeros().
Referenced by AltitudeSH().
AngleDetermination()
function AngleDetermination (in r, in v, in n, in b, in jD)
Returns roll, pitch and yaw relative to local vertical.
Type:
 AngleDetermination
The demo does single angles, and then three angles.
Form
angle = AngleDetermination(r,v,b,jD)
Inputs
 r          (3,1)    ECI orbit position (m)
 v          (3,1)    ECI orbit velocity (km/s)
 n          (3,1)    Nadir vector
 b          (3,1)    Measured magnetic field
 jD         (3,1)    Julian date
Outputs
 angle     (3,1)    [roll;pitch] angle (rad)
 Copyright (c) 2022 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since version 2022.1
References and(), AngleDetermination(), BDipole(), Date2JD(), Demo(), Nadir(), Q2Eul(), QForm(), QLVLH(), TwoUToQ(), Unit(), and vector().
Referenced by AngleDetermination().
AngRate()
function AngRate (in angMomentumVector, in torqueVector)
 given the angular momentum and a matrix of torque vectors
Form
 angRateMagnitude = AngRate( angMomentumVector, torqueVector )
Inputs
 angMomentumVector (3,1)  Angular momentum vector
 torqueVector      (3,:)  Matrix of torque vectors
Outputs
 angRateMagnitude  (:)    Magnitude of the angular rate generated
                          by each torque in torqueVector
References and(), Cross(), length(), Plot2D(), vector(), and zeros().
AnimateSpacecraft()
function AnimateSpacecraft (in action, in varargin)
You can add as may spacecraft as you like by adding more g's, r's and q's. The window will be updated for each position/quaternion pair with a pause of 0.1 seconds in between (or set a different pause dT). Call 'initialize' before calling the other actions to set additional features.
The orange vectors are velocity, the yellow are sun and the blue-green is nadir. Nadir is only shown for the central satellite.
If you ask for the output m the animation will return movie frames. If you are making a movie you cannot change the window size while you are generating the frames.
Type AnimateSpacecraft for a demo.
Form
 AnimateSpacecraft( 'initialize', g1, g2, r1, v1, q1, r2, v2, q2 )
 After initialize:
 AnimateSpacecraft( 'add nadir' )             % draw the nadir vector
 AnimateSpacecraft( 'add sun', jD0 )          % draw the sun vector
 AnimateSpacecraft( 'add velocity', v1, v2 )  % draw the velocity vectors
 AnimateSpacecraft( 'use lvlh', v1, v2 )      % tie camera to LVLH
 AnimateSpacecraft( 'set pause', dt )         % change the pause time
 AnimateSpacecraft( 'max axes' )              % set the axes limits apriori
 AnimateSpacecraft( 'add planet', p)          % Add a planet and use planet fixed coordinates
 AnimateSpacecraft( 'track with camera', target, offset, viewAngle )
 AnimateSpacecraft( 'update', t, r1, v1, q1, r2, v2, q2 ) % run the animation
 m = AnimateSpacecraft( 'update', t, r1, v1, q1, r2, v2, q2 ) % run and make movie
Inputs
 action  (1,:) 'initialize' or 'update'
 t       (1,:) Time vector
 g       (.)   CAD data structures
 q1      (4,:) Quaternion from ECI to body
 r1      (3,:) ECI position vectors
 v1      (3,:) Velocity vectors
 jD0     (1,1) Initial epoch, Julian date
 target  (1,1) Index of target, object 1 or 2
 offset  (1,1) Camera offset distance (m)
Outputs
 m       (1,:) Movie file (optional)
References and(), AnimateSpacecraft(), close(), get(), QTForm(), and set().
Referenced by AnimateSpacecraft().
ArcEff()
function ArcEff (in spinrate, in pulsewidth)
 Since version 1.
Form
 eff = ArcEff( spinrate, pulsewidth )
Inputs
 spinrate         (1,1) Spin rate (rad/sec)
 pulsewidth       (1,:) Pulsewidth
Outputs
 eff              (1,:) Efficiency
References and(), ArcEff(), Constant(), and Plot2D().
Referenced by ArcEff(), and NPSPM().
AreaOfRectCircInt()
function AreaOfRectCircInt (in v, in r)
Form
 a = AreaOfRectCircInt( v, r )
Inputs
 v              (2,4)  Vector
 r              (1,1)  Radius of the circle
Outputs
 a              (1,1)  Area
 n              (1,1)  Number of intersections
 intC           (1,1)  Integral of the line segments
References and(), AreaOfRectCircInt(), Integral(), isempty(), Mag(), Polygon(), Unit(), and zeros().
Referenced by AreaOfRectCircInt().
ASim()
function ASim (in x, in t, in inertia, in torque)
 Since version 1.
Form
 xDot = ASim( x, t, inertia, torque )
Inputs
 x           (7,1)     [Attitude quaternion; attitude rate]
 t                     Time
 inertia     (3,3)     Inertia matrix
 torque      (3,1)     External torque
Outputs
 xDot        (7,1)     Derivative of the state, x
References QIToBDot(), quaternion(), and RBModel().
AStarAttitudeTrajectory()
function AStarAttitudeTrajectory (in q, in qTarget, in uBody, in rA, in dec, in radius, in nGrid)
Type AStarAttitudeTrajectory for a demo
Form
 qPath = AStarAttitudeTrajectory( qNow, qTarget, uBody, lat, lon, radius, nGrid )
Inputs
 q         (4,1) Current quaternion
 qTarget   (4,1) Target quaternion
 uBody     (3,1) Body vector to keep out of stayout zones
 lat       (1,:) Latitude of stayout zone
 lon       (1,:) Longitude of stayout zone
 radius    (1,:) Radius of stayout zone
Outputs
 qPath    (4,n) Quaternions for path
References AStarAttitudeTrajectory(), AStarSearch(), Dot(), GenerateGrid(), length(), ManeuverCostSphere(), ManeuverSuccessorNodes3D(), QForm(), quaternion(), RaDec2Q(), RaDec2U(), vector(), and zeros().
Referenced by AStarAttitudeTrajectory().
AtmJ70ToGround()
function AtmJ70ToGround (in h, in d)
Jacchia is only valid above 80 km, so this function switches to scale heights at 80 km to give a smooth curve.
Type AtmJ70ToGround for a demo.
See also
AtmJ70, AtmDens2, and SolarFluxPrediction. With one argument d.jD and d.rECI may be arrays.
Form
 rho = AtmJ70ToGround( d );
 rho = AtmJ70ToGround( h, d )
Inputs
 h    (1,:) Altitude
 d    (:) Data structure
          .aP        (1,1)   Geomagnetic index 6.7 hours before the computation
          .dd        (1,1)   Day number since Jan 1., days
          .f         (1,1)   Daily 10.7 cm solar flux (e-22 watts/m^2/cycle/sec)
          .fHat      (1,1)   81-day mean of f (e-22 watts/m^2/cycle/sec)
          .fHat400   (1,1)   fHat 400 days before computation date
          .lat       (1,1)   Latitude of computation point + north (deg)
          .lng       (1,1)   Longitude of computation point + east (deg)
          .mm        (1,1)   Greenwich mean time from 0000 GMT, minutes
          .yr        (1,1)   Year
          .z         (1,1)   Geometric altitude (km)
 or
 .jD        (:)     Julian date
 .rECI      (3,:)   ECI position vector
 .aP        (1,1)   Geomagnetic index 6.7 hours before the computation
 .f         (1,1)   Daily 10.7 cm solar flux (e-22 watts/m^2/cycle/sec)
 .fHat      (1,1)   81-day mean of f (e-22 watts/m^2/cycle/sec)
 .fHat400   (1,1)   fHat 400 days before computation date
Outputs
 rho  (1,:) Density (kg/m^3)
References Demo().
AtmNRLMSISE()
function AtmNRLMSISE (in rECI, in jD, in varargin)
The NRLMSISE-00 model was developed by Mike Picone, Alan Hedin, and Doug Drob. They also wrote a NRLMSISE-00 distribution package in FORTRAN which is available at http://uap-www.nrl.navy.mil/models_web/msis/msis_home.htm
This code is based on the C Code by Dominik Brodowski who implemented and maintains the C code. You can reach him at mail@.nosp@m.brod.nosp@m.o.de. and check http://www.brodo.de/english/pub/nrlmsise/index.html for updated releases of this package.
You can input the ECI position vector or latitude, longitude and altitude. By default, all of the solar flux parameters are computed by SolarFluxPrediction, so you only need enter rECI and JD. To use specific flux data enter it using the variable arguments. Alternatively, you can enter latLonAlt and JD.
Variable arguments:
 'f107a'           81 day average of F10.7 flux
 'f107'            Daily F10.7 flux for previous day
 'aP'              Geomagnetic index (daily)
 'ap_a'            Array of daily and hourly indices, (1,7)
 'units'           'mks' otherwise will be cgs
 'plot x value'    'orbit angle' 'time' 'sun angle' 'JD from Start'
 'altitude' index'
 'flags'           24 switches
 'pressure'
 'solar magnitude' 'prediction', 'low', 'high'
Type AtmNRLMSISE for a demo in an ISS orbit.
You can use the C interface by calling:
 output = AtmNRLMSISE( 'gtd7', [], input, flags )
This is used in the script NRLMSISTest.m and reproduces the test case that accompanies the C software. Globals are loaded from NRLMSIS.mat.
Form
 p = AtmNRLMSISE(rECI,jD,varargin)
Inputs
 rECI      (3,:) ECI position vector (km)
 jD        (1,:) Julian day number
 input      (.)  Input data structure, C-interface
 flags    (1,24) Flags, C-interface
Outputs
 pOut      (.) Output data structure
               .heNumberDensity    (1,:) He number density
               .oNumberDensity     (1,:) O number density
               .n2NumberDensity    (1,:) N2 number density
               .o2NumberDensity    (1,:) O2 number density
               .arNumberDensity    (1,:) AR number density
               .density            (1,:) Density
               .hNumberDensity      (1,:) H number density
               .nNumberDensity      (1,:) N number density
               .anomONumberDensity  (1,:) Anomalous O number density
               .exoTemp             (1,:) Exoatmospheric temperature
               .temperature         (1,:) Temperature
               .latitude            (1,:) Latitude (rad)
               .longitude           (1,:) Longitude (Rad)
               .altitude            (1,:) Altitude (km)
 qOut     (.) Alternative output  data structure
               .d (10,:) Densities
               .t (2,:) Temperatures
See also
SolarFluxPrediction, ECIToEF
References abs(), and(), AtmNRLMSISE(), DefaultDataStructure(), Demo(), ECIToEF(), EFToLatLonAlt(), ISSOrbit(), JD2Date(), JD2DN(), JD2T(), length(), LocalSolarTime(), Plot2D(), RVOrbGen(), set(), SolarFluxHistorical(), SolarFluxPrediction(), TimeLabl(), and zeros().
Referenced by AtmNRLMSISE().
AtmScaleHeightsStdAtm()
function AtmScaleHeightsStdAtm (in h, in atmData)
 Type AtmScaleHeightsStdAtm for a demo.
 Since version 8.
Form
 [rho, a, nu, p, t] = AtmScaleHeightsStdAtm( h, atmData )
Inputs
 h       (1,:) Altitude (km)
 atmData     (.)  Atmosphere data, see AtmData.txt
Outputs
 rho     (1,:) Density (kg/m^3)
 a       (1,:) Speed of sound (m/s)
 nu      (1,:) Kinematic viscosity (N-s/m^2)
 p       (1,:) Pressure (N/m^2)
 t       (1,:) Temperature
References Altitude(), AtmDens2(), AtmScaleHeightsStdAtm(), Demo(), isempty(), Plot2D(), Pressure(), StdAtm(), and zeros().
Referenced by AtmScaleHeightsStdAtm(), and LiftAndDragSeaLevelToOrbit().
AttitudeProfilePlots()
function AttitudeProfilePlots (in d)
See AttitudeProfileWithCon.m
Type AttitudeProfilePlots for a demo.
 Since version 11.
Form
 AttitudeProfilePlots( d )
Inputs
 d          (.)         Data structure generated from AttitudeProfileWithCon.m
Outputs
 None
References AddFillToPlots(), and(), AttitudeProfilePlots(), AttitudeProfileWithCon(), isempty(), NewFig(), set(), and TimeLabl().
Referenced by AttitudeProfilePlots().
AttitudeProfilePlugIn()
function AttitudeProfilePlugIn (in action, in modifier, in hFig, in position, in callback)
Form
 x = AttitudeProfilePlugIn( action, modifier, hFig, position, callback )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifier    (1,:)  Modifier to the action or data structure if intialization
 hFig        (1,1)  Handle to the figure or if 'update' radio button handles
 position    (1,4)  [left bottom width height]
 callback    (1,:)  Callback string when something has changed in this gui
Outputs
 x           (1,1)  The tag if action is 'initialize' else
                    .nSamp      (1,1)     Number of samples
                    .time       (1,nSamp) Time from start
                    .jD         (1,nSamp) Julian date
                    .rECI       (3,nSamp) Position vector
                    .vECI       (3,nSamp) Velocity vector
                    .angle      (1,nSamp) Time from start
                    .planet     (1,:)     Planet name
                    .qECIToBody (4,nSamp) Quaternion
                    .omega      (3,nSamp) Angular rate
 Notes:
 There are six choices of attitude profile in the GUI: LVLH, ECI, sun-nadir,
 spinning, sun, and user-defined. The user-defined function takes two
 optional parameters and must have the following form:
 [qECIToBody,omega] = f( [rECI; vECI], jD, p1, p2 );
 where rECI, vECI, and jD are arrays of length nSamp.
References and(), AttitudeProfile(), AttitudeProfilePlugIn(), CloseFigure(), get(), GetH(), HelpSystem(), Initialize(), isempty(), length(), and vector().
Referenced by AttitudeProfilePlugIn().
AttitudeProfileVis()
function AttitudeProfileVis (in d, in gCAD, in cone)
Draws the following:
 + reference inertial vector and body vector
 + sector for separation angle
Labels the separation angle for alignment and constraints, the date, elapsed time, and the current pointing mode at the top of the window. Uses PlaybackControls to control animation over time.
Type AttitudeProfileVis for a demo
Form
 AttitudeProfileVis( d )
Inputs
 d          (.)         Data structure generated from AttitudeProfileWithCon.m
 gCAD       (.)      CAD data structure
                      .name       (1,:) Name
                      .component   (:)  Component structure array
                           .v
                           .f
                           .edgeColor
                           .faceColor
                      .color      (1,:) Name
                      .alpha      (1,:) Name
 cone       (:)      Cone data structure array
                      .name  (1,:) Name
                      .uB    (3,1) Unit vector in the body frame
                      .fov   (1,1) Field of view (rad)
                      .alpha (1,1) Transparency
                      .color (1,3) Color
Outputs
 None
See also
: EarthHR, AttitudeProfileWithCon
References and(), AttitudeProfileVis(), AttitudeProfileWithCon(), Cone(), CubeSatModel(), Demo(), ECIToEF(), get(), GetCADVF(), Initialize(), isempty(), JD2T(), length(), LLAToECEF(), Mag(), Map(), Mat2Q(), MoonV1(), PlaybackControls(), Q2Mat(), QTForm(), quaternion(), SectorPatch(), Sep(), set(), SunV1(), TerminatorLine(), Unit(), vector(), and zeros().
Referenced by AttitudeProfileVis().
AttitudeProfileWithCon()
function AttitudeProfileWithCon (in d, in varargin)
Each mode defines the ECI-to-Body quaternion through the combination of primary and secondary alignments. The primary alignment directly aligns a body vector with an inertial target. The secondary alginment rotates about that primary body vector to align a second body vector with a second inertial vector as closely as possible.
Each alignment can be defined as one of the following types, with the associated target data.
 #  Alignment type      Target data
 ====================================================================
 1    'sun'                -
 2    'nadir'              -
 3    'orbitnormal'        -
 4    'latlon'             [lat;lon]   Target latitude and longitude
 5    'lvlh'               [x;y;z]     Target LVLH direction
 6    'ueci'               [x;y;z]     Target ECI direction
 7    'reci'               [x;y;z]     Target ECI point
Form
 d = AttitudeProfileWithCon( d, mode1, mode2, mode3, ... );
Inputs
 d       (.)   Data structure with orbit and time information
                  .jD0        (1,1)    Epoch Julian date
                  .t          (1,:)    Time vector from jD0 (sec)
                  .r          (3,:)    ECI position  (km)
                  .v          (3,:)    ECI velocity (km/s)
 mode1   (.)   Nominal Attitude Mode with fields:
 .type1      '...'    Primary alignment type
 .body1      (3,1)    Primary body vector to align
 .target1    (:,1)    Primary Target
 .type2      '...'    Secondary alignment type
 .body2      (3,1)    Secondary body vector to align
 .target2    (:,1)    Secondary target
 .nCon       (1,1)
 .typeCon    '...'    Constraint type
 .bodyCon    (3,:,N)
 .targetCon  (3,N)
 .minSepCon
 mode2   (.)   Same as nominal mode but with additional field:
 .window     (:,2)    Time windows to use this mode
 mode3
 mode4
 ...
Outputs
 d       (.)   Data structure with added quaternion, and alignment info
                  .jD0        (1,1)    Epoch Julian date
                  .t          (1,:)    Time vector from jD0 (sec)
                  .r          (3,:)    ECI position  (km)
                  .v          (3,:)    ECI velocity (km/s)
                  .el         (1,6)    Initial orbital elements
                  .q          (4,:)    ECI-to-body quaternion
                  .type1      (1,:)    # for primary alignment type
                  .type2      (1,:)    # for secondary alignment type
                  .rot        (1,:)    Rotation angle about primary body axis
                  .sep        (1,:)    Separation angle from secondary target
See also
: AttitudeProfileConstraintsDemo, AttitudeProfile, QAlignWithCon
References and(), AttitudeProfile(), AttitudeProfileWithCon(), Date2JD(), ObservationTimeWindows(), QAlignWithCon(), quaternion(), RVFromKepler(), and vector().
Referenced by AttitudeProfilePlots(), AttitudeProfileVis(), and AttitudeProfileWithCon().
AttitudeTarget()
function AttitudeTarget (in type, in s, in t, in d)
There are six types of target:
 'sun'     - point a spacecraft vector (u) at the sun. The angle about
 the vector is ignored
 'lvlh'    - align the spacecraft with LVLH, with optional offset
 'eci'     - align with respect to ECI
 'ulvlh'   - align (u) with a unit vector (uTarget) defined in the lvlh frame
 'ueci'    - align (u) with a unit vector (uTarget) defined in the eci frame
 'latlon'  - point a spacecraft vector (u) at a specific latitude
 and longitude of the earth. The angle about
 the vector is ignored
 'target'  - align with a target spacecraft (at rTarget)
The output is the target qECIToBody.
This is compatible with PID3Axis data in which case the mode will be 'quat'. The target data t is required for 'target' or 'latlon' modes, otherwise the parameters from d will be used. If angle is nonzero than the axis rotation will be appended.
Form
 t = AttitudeTarget;   % data structure
 [qTarget,d] = AttitudeTarget( type, s, t, d )
 [qTarget,d] = AttitudeTarget( type, s, [], d )
Inputs
 type     ''     Type of target
                   'latlon'
                   'sun'
                   'lvlh'
 s       (.)      Data structure with spacecraft state information
 .qECIToBody    (4,1) Current quaternion
 .rECI          (3,1) ECI position vector
 .vECI          (3,1) ECI velocity vector
 .jD            (1,1) Julian date
 t       (.)      Data structure with target information
 .qOffset       (4,1) Offset quaternion (lvlh and eci only)
 .u             (3,1) Unit vector in the body frame
 .uTarget       (3,1) Target vector in the reference frame
 .rTarget       (3,1) Target ECI position vector
 .latitude      (1,1) Geodetic latitude (rad)
 .longitude     (1,1) Longitude (rad)
 d       (.)     Data for PID3Axis control function
 .q_desired_state (4,1) Offset quaternion
 .body_vector     (3,1) Unit vector in body frame
 .eci_vector      (3,1) Target vector
 .angle           (1,1) Angle of rotation
 .axis            (3,1) Axis of rotation
Outputs
 qTarget (4,1)   Target qECIToBody
 d        (.)    Updated PID3Axis data
                  .q_desired_state (4,1) Target quaternion
                  .mode, set to 'quat'
See also
: PID3Axis
References and(), AttitudeTarget(), AU2Q(), DeBlankLT(), isempty(), JD2T(), LatLonToR(), PID3Axis(), QForm(), QLVLH(), QMult(), QTForm(), quat(), quaternion(), QZero(), set(), SunV1(), TruEarth(), U2Q(), Unit(), and vector().
Referenced by AttitudeTarget().
AutoPoint()
function AutoPoint (in mode, in camera, in gTarget, in rBody)
 Units: rECI, rBody are generally in km while radius is in m.
 If camera is empty will use a default 10 degree FOV camera.
Form
 [qCamera,rCamera,distance] = AutoPoint( mode, camera, gTarget, rBody )
Inputs
 mode          (:)      Mode, 'above', 'lvlh', 'fixed'
 camera        (:)      Camera model from CameraDatabase
 gTarget       (:)      CAD model of the target spacecraft
                           or structure with fields rECI, vECI, radius
 rBody        (3,1)     Location of body for fixed mode (km)
Outputs
 qCamera      (4,1)     World to body quaternion
 rCamera      (3,1)     Locaton of camera in world (m)
 distance     (1,1)     Distance between camera and target
References and(), AngleOfView(), AutoPoint(), CameraDatabase(), isempty(), length(), Mag(), QAlign(), QLVLH(), QTForm(), quaternion(), square(), U2AzEl(), U2Q(), Unit(), and vector().
Referenced by AutoPoint().
BathtubCurve()
function BathtubCurve (in beta, in t, in alpha)
Alpha fits the three parts of the bathtub together. It is recomputed internally.
Form
 BathtubCurve;   % demo
 z = BathtubCurve(beta,t,alpha)
Inputs
 beta       (1,1)    Time exponent
 t          (1,:)    Time (s)
 alpha      (1,1)    Scaling
Outputs
 z          (1,:)    Bathtub curve
Reference: Thomas Heiser and James P. Hofmeister, "BATHTUB, FAILURE DISTRIBUTION, MTBF, MTTF, AND MORE: THEY ARE RELATED," Society for Machinery Failure Prevention Technology, 2019
References and(), BathtubCurve(), Constant(), Demo(), and Plot2D().
Referenced by BathtubCurve().
BatteryDesign()
function BatteryDesign (in type, in el, in planet, in jD, in powerMax)
 Effectively sizes the battery to account for eclipses.
Form
 BatteryDesign;
 [mass, vol, powerAve] = BatteryDesign( type, el, planet, jD, powerMax )
Inputs
 type     (1,:) Battery type 'lion' only
 el       (1,6) Elements vector [a,i,W,w,e,M] or structure
 planet   (1,:) Name of planet
 jD       (1,1) Julian date (days)
 powerMax (1,1) Maximum power from the solar panels (W)
Outputs
 mass     (1,1) Mass
 vol      (1,1) Volume
 powerAve (1,1) Average power
References and(), BatteryDesign(), Demo(), JD2000(), and vector().
Referenced by BatteryDesign().
BatterySize()
function BatterySize (in sma, in inc, in power, in jD0, in dOD, in rhoM, in rhoV)
Type BatterySize for a demo.
Form
 [m, v, b] = BatterySize( sma, inc, power, jD0, dOD, rhoM, rhoV )
Inputs
 sma      (1,1) Semi-major axis (km)
 inc      (1,1) Inclination (rad)
 power    (1,1) Solar array power (W)
 jD0      (1,1) Start Julian day number (day)
 dOD      (1,1) Depth of discharge (0 to 1)
 rhoM     (1,1) Specific power (W-h/kg)
 rhoV     (1,1) Energy density (W-h/L)
Outputs
 m        (1,1) Mass (kg)
 v        (1,1) Volume (L)
 b        (1,1) Battery capacity (W-h)
References and(), BatterySize(), Date2JD(), Demo(), Eclipse(), Energy(), isempty(), length(), RVOrbGen(), SunV1(), TimeHistory(), and zeros().
Referenced by BatterySize().
BDDesign()
function BDDesign (in mF, in rhoF, in tNom, in pI, in pF, in rP)
If gas constant is omitted, Helium will be assumed. Typical tank pressures are 300-400 psi BOL and 100 psi EOL.
Form
 [vP, mP] = BDDesign( mF, rhoF, tNom, pI, pF, rP )
Inputs
 mF            (1,:)    Mass of fuel (kg)
 rhoF          (1,1)    Density of fuel (kg/m^3)
 tNom          (1,1)    Nominal temperature (K)
 pI            (1,1)    Initial pressure (N/m^2)
 pF            (1,1)    Final pressure (N/m^2)
 rP            (1,1)    Gas constant of pressurant
Outputs
 vP            (1,:)    Volume of pressurant (m^3)
 mP            (1,:)    Required mass of pressurant (kg)
References: Larson and Wertz, Space Mission Analysis and Design, Second Edition, Space Technology Library, Microcosm, Inc.,
Section 17.4, p. 654-660.
References and(), and Plot2D().
Referenced by BloDown().
BDipole()
function BDipole (in r, in jD, in v, in c)
The output is in geocentric inertial coordinates (ECI). This function includes the effect of dipole motion on the earth.
Includes 1995 IGRF coefficients as of Jan. 1999.
Type BDipole for a demonstration of a satellite in a low earth inclined orbit.
Form
 [b, bDot] = BDipole( r, jD, v, c )
Inputs
 r           (3,:)   Position vector in the ECI frame (km)
 jD          (1,:)   Julian days
 v           (3,:)   Velocity (km/s)
 c           (.)     Coefficients for field model
                     .coeff  (3,1) Base coefficents
                     .dCoeff (3,1) Deltas
                     .jD0    (1,1) Epoch
Outputs
 b           (3,:)   Magnetic field in the ECI frame (T)
 bDot        (3,:)   Derivative of b in the ECI frame (T/s)
Reference: Wertz, J., ed. "Spacecraft Attitude Determination and Control," Kluwer, 1976, 783-784.
References BDipole(), Demo(), ECIToEF(), isempty(), JD2000(), JD2T(), length(), Mag(), Period(), Plot2D(), RVFromKepler(), vector(), and zeros().
Referenced by AngleDetermination(), BDipole(), BDipoleCoeff(), BDipolePlanet(), CubeSatDisturbanceAnalysis(), CubeSatEnvironment(), CubeSatLunarEnvironment(), Disturbances(), DrawFieldLines(), EarthEnvironment(), EnvironmentStruct(), FOrbitMultiSpacecraft(), MagControlTwoAxis(), MeasMagnetometerEarth(), MeasurementsSunMagUKF(), MomentumUnloading(), PermanentMagnetRHS(), RHSGGRotational(), RHSRigidBodyWithDamping(), SailEnvironment(), TwoUToQ(), and UDipole().
BDipoleCoeff()
function BDipoleCoeff (in file)
The output is in geocentric inertial coordinates (ECI). This function includes the effect of dipole motion on the earth.
Includes 1995 IGRF coefficients as of Jan. 1999.
Type BDipoleCoeff for a demonstration using WMM. You will need WMM.mat for this demo.
Form
 c = BDipoleCoeff( file )
Inputs
 file (1,:) Matfile
Outputs
 c   (.)     Coefficients for gravity model
             .coeff  (3,1) Base coefficents
             .dCoeff (3,1) Deltas
             .jD0    (1,1) Epoch
References and(), BDipole(), BDipoleCoeff(), Date2JD(), Demo(), JD2000(), Period(), RVFromKepler(), and WMM().
Referenced by BDipoleCoeff().
BFromHHysteresis()
function BFromHHysteresis (in h, in hDot, in d)
 Unlike Flatley, we use a tanh curve for the hysteresis boundaries.
 Since version 10.
Form
 b = BFromHHysteresis( h, hDot, d )
Inputs
 h                  (1,:) Magnetic field in each bar
 hDot               (1,:) Magnetic field rate in each bar
 d                  (1,1) Data structure
                          .bS (1,1) Saturation flux density
                          .hC (1,1) Coercive force
                          .bR (1,1) Remnance
Outputs
 b                  (1,:) Flux density
Reference: Flatley, T. W. and Henretty, D. A., "A Magnetic Hysteresis Model."
References and(), BFromHHysteresis(), Demo(), length(), Plot2D(), and zeros().
Referenced by BFromHHysteresis(), and MagneticHysteresis().
BHarm()
function BHarm (in n, in aS, in file)
 Since version 3.
Form
 [b, bM, bErr] = BHarm( n, aS, file )
Inputs
 n                (1,1)   Number of terms
 aS               (1,:)   Axis system:
                            'GEOC'  z North, x Zenith
                            'NASA'  y South  z Nadir
                            Default is 'NASA'
 file            (1,:)    GOES binary data file name (optional)
Outputs
 b               (3,n)    Harmonic cofficients [bias sine cosine]
 bM              (3,n)    Magnitude harmonic cofficients [bias sine cosine]
 bErr            (3,1)    Error
References abs(), BTrans(), isempty(), length(), LoadGOES(), Nadir(), NewFig(), SCSeries(), series(), TitleS(), XLabelS(), and YLabelS().
BLDCMFlux()
function BLDCMFlux (in theta, in d)
 The input is electrical angles effectively creating one pole pair.
 This function assumes a trapezoidal flux distribution. The output
 will be either +flux or -flux.
Form
 e = BLDCMFlux( theta, d )
Inputs
 theta         (1,1)     Electrical angle (rad)
 d             (1,1)     Data structure
                         .flux (1,1) Flux (T)
Outputs
 e             (1,1)     Flux
References BLDCMFlux().
Referenced by BLDCMFlux().
BLDCMFriction()
function BLDCMFriction (in omega, in d)
Form
 f = BLDCMFriction( omega, d )
Inputs
 omega         (1,1)     Mechanical angular rate
 d             (1,1)     Data structure
Outputs
 f             (1,1)     Friction torque (Nm)
References BLDCMFriction(), and Friction().
Referenced by BLDCMFriction().
BLDCMInverter()
function BLDCMInverter (in e, in d)
Form
 [v, h] = BLDCMInverter( e, d )
Inputs
 e             (3,1)     Back emf for each phase
 d             (1,1)     Data structure
                         .dir (1,1) Direction (1 position, -1 negative)
                         .vS  (1,1) Source voltage (V)
Outputs
 v             (3,1)     Phase voltages [A;B;C]
 h             (3,1)     Hall sensor values
References BLDCMInverter().
Referenced by BLDCMInverter().
BLDCMRHS()
function BLDCMRHS (in x, in t, in d)
Form
 [xDot, tE, v] = BLDCMRHS( x, t, d )
Inputs
 x             (4,1)     State [theta;omega;iA;iB;iC]
 t             (1,1)     Time (sec)
 d             (1,1)     Data structure
Outputs
 xDot          (4,1)     State [theta;omega;iA;iB]
 tE            (1,1)     Electrical torque (Nm)
 v             (3,1)     Phase voltages (V)
Reference: S. Lee, "A Comparison Study of the Commutation Methods for the Three-Phase Permanent Magnet Brushless DC Motor," Pennsylvania State University.
 Copyright (c) 2012 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since version 11.
References BLDCMRHS().
Referenced by BLDCMRHS().
BloDown()
function BloDown (in mPress, in rhoFuel, in vTank, in rPress, in T, in mFuel)
Form
 p = BloDown( mPress, rhoFuel, vTank, rPress, T, mFuel )
Inputs
 mPress         (1,1) Mass of pressurant
 rhofuel        (1,1) Density of the fuel
 vTank          (1,1) Pressurant volume
 rPress         (1,1) Gas constant of pressurant (default is helium)
 T              (1,1) Temperature (deg-K)
 mFuel          (1,:) Mass of the fuel
Outputs
 p              (1,:) Pressure
See also
BDDesign.
References BDDesign(), BloDown(), isempty(), MolWt2R(), Plot2D(), and Pressure().
Referenced by BloDown(), GPressure(), and Pressure().
BMF()
function BMF (in r, in jD, in kP)
Computes the field as a dipole with deviations. Has a built-in demo for geo orbit.
Form
 [bT, dB] = BMF( r, jD, kP )
Inputs
 r               (3,n)  Location in ECI Frame.
 jD              (1,n)  Julian dates
 kP              (1,1)  Solar activity index ( Typically 0 to 3 )
Outputs
 bT              (3,n)  Magnetic field ECI (T)
 dB              (3,n)  Delta magnetic field ECI (T)
Reference: Mead, G.D., Fairfield, D.H. "A Quantitative Magnetosphere Model Derived From Spacecraft Magnetometer Data", Journal of Geophysical Research, Vol. 80, No.4 February 1, 1975, pp 523-534.
Includes 1995 IGRF coefficients as of Jan. 99
See also
: SunV1, ECIToEF
References and(), BMF(), Cross(), Dipole(), ECIToEF(), JD2000(), JD2T(), Mag(), Plot2D(), SunV1(), Unit(), vector(), and zeros().
Referenced by BMF(), and OrbView().
BTrans()
function BTrans (in b, in aS)
 Since version 3.
Form
 bT = BTrans( b, aS )
Inputs
 b                (3,:)   GOES Field Data
 aS               (1,:)   Axis system:
                            'GEOC'  z North, x Zenith
                            'NASA'  y South  z Nadir
                            Default is 'NASA'
Outputs
 bT               (3,:)   Transformed data
References BTrans(), isempty(), and Nadir().
Referenced by BHarm(), and BTrans().
CalibrateSunSensor()
function CalibrateSunSensor (in n, in f, in angle)
find coefficients assuming a power law calibration.
The detector 1 measurement is assumed of the form:
f1 = t1(1) + t1(2)*cos(angle+alpha1)+ t1(3)*cos(angle+alpha1)^2 + ...
Type CalibrateSunSensor for a demo.
Form
 [t, err] = CalibrateSunSensor( n, f, angle )
Inputs
 n     (1,1)     Number of terms
 f      (1,:)     Detector measurements
 angle  (1,:)     Angle of measurements from the normal (rad)
Outputs
 t     (1,n+1)   Detector coefficients [constant linear square ...]
 err   (1,1)     Mean errro
References CalibrateSunSensor(), Demo(), length(), Plot2D(), square(), and zeros().
Referenced by CalibrateSunSensor(), and SunSensor().
Callmkspk()
function Callmkspk (in ignoredArg, in ignoredArg)
This is the equivalent of the command line call
mkspk -setup filenameSetup -input fileNameInput
  -output filename.bsp
CameraDatabase()
function CameraDatabase (in modelName)
 The model specifies the size of the chip and the size of the pixels.
 The camera location and orientation is also defined.
 Several properties are derived from others.
 To update the derived properties or substitute a default for an empty
 field, pass in the updated structure instead of a model name.
 When called with no inputs, displays or returns a list of models.
 Since version 8.
Form
 CameraDatabase                    % Print list of available models.
 d = CameraDatabase( modelName )   % Return a model
 d = CameraDatabase( d )           % Update a model
Inputs
 modelName     (:)     String of model name.
Outputs
 d
                     .xPixels       (1,1) Number of pixels along x axis (n)
                     .yPixels       (1,1) Number of pixels along y axis (m)
                     .focalLength   (1,1) Focal length (m)
                     .aperture      (1,1) Aperture diameter (m)
                     .xLength       (1,1) Length of pixel along x axis (micro m)
                     .yLength       (1,1) Length of pixel along y axis(micro m)
                     .gain          (n,m) Gain of each pixel
                     .up            (2,1) Up vector in camera frame, usually +Y
                     .boresight     (3,1) Boresight in camera frame, usually +Z
                     .position      (3,1) Location of camera imager in body frame (m)
                     .bBodyToCamera (3,3) Transformation matrix to camera frame
                     .xWidth        (1,1) X focal plane width (derived)
                     .yWidth        (1,1) Y focal plane width (derived)
                     .rho           (1,1) Imaging element diameter (derived)
References and(), CameraDatabase(), isempty(), length(), PinholeStarCamera(), square(), and vector().
Referenced by AutoPoint(), CameraDatabase(), CameraImage(), PointCameraModel(), and SpaceCamera().
CameraImage()
function CameraImage (in d, in qECIToBody, in rECI, in p, in qECIToTarget, in rTarget)
 The camera boresight is the z-axis in the camera frame.
 d.r is the position of the lens.
 The pixel measure may be physical pixels or may include interpolation
 (generally giving a 10x improvement.)
Form
 [x, xPixel] = CameraImage( d, qECIToBody, rECI, p, qECIToTarget, rTarget )
Inputs
 d              (1,1)  Camera data structure
                       .bBodyToCamera  (3,3) Transformation from body to
                                             camera frame
                       .r              (3,1) Location of the camera
                       .focalLength    (1,1) Focal length
                       .xWidth         (1,1) X focal plane width
                       .yWidth         (1,1) Y focal plane width
                       .xPixels        (1,1) X focal plane width in pixels
                       .yPixels        (1,1) Y focal plane width in pixels
 qECIToBody     (4,1)  Spacecraft quaternion
 rECI           (3,1)  Spacecraft position
 p              (3,:)  Points on the target
 qECIToTarget   (4,1)  Target quaternion
 rTarget        (3,1)  Target Position
Outputs
 x              (2,:)  Points (units of measure)
 xPixel         (2,:)  Points (pixels)
References abs(), CameraDatabase(), CameraImage(), Demo(), DupVect(), length(), NewFig(), QForm(), QTForm(), quaternion(), square(), XLabelS(), and YLabelS().
Referenced by CameraImage().
CameraResolution()
function CameraResolution (in h, in f, in l, in d, in lambda)
Form
 r = CameraResolution( h, f, l, d, lambda )
Inputs
 h              (1,n) Range
 f              (1,1) Focal length
 l              (1,1) Lines or pixels/meter
 d              (1,1) Aperture
 lambda         (1,m) Wavelength, numbers or 'visible', 'near infrared'
                      'far infrared'
Outputs
 r              (n,m) Resolution
Reference: Rees, W.G. "Physical Principles of Remote Sensing." Cambridge. pp. 80-81
References CameraResolution(), Demo(), DupVect(), length(), Mesh2(), Plot2D(), Spectrum(), and Wavelength().
Referenced by CameraResolution().
CameraTransform()
function CameraTransform (in type, in d, in p)
 Transforms from the scene frame to the pixel frame. Does not do
 depth buffering. The points you give it must be visible to the camera
 This outputs the transformed points and the transformation matrix.
 types are 'perspective', 'affine', 'infinite' and 'weak perspective'.
 With 'infinite' the input points should be unit vectors. They are
 unitized internally.
 The radial distortion model is xd = x*(1 + k(1)r^2 + k(2)r^4)
 where r^2 = x^2 + y^2
 Type CameraTransform for a demo. The first three apply the
 'perspective', 'affine' and 'weak perspective' transforms to the
 vertices of a triangle. The last applies the infinite transform
 to a point on the boresight.
Form
 [pT, m] = CameraTransform( type, d, p )
 or
 m = CameraTransform( type, d )
Inputs
 type           (1,:) Transformation type
 d              (1,1) Data structure
                      .t (3,1) Location of camera
                      .r (3,3) Rotation matrix from scene to camera frame
                      .o (2,1) Origin of the pixel frame (pixels)
                      .n (2,1) Dimensions of the pixel array
                      .f (1,1) Focal length (m)
                      .s (2,1) Scaling (m/pixel)
                      .k (1,2) Distortion coefficients
 p              (3,:) Points to transform
Outputs
 pT             (2,:) Transformed points or m if p not entered
 m              (3,3) Transformation matrix
 j              (1,m) Removed points
Reference: E. Trucco and A. Verri, "Introductory Techniques for 3-D Computer Vision, Prentice-Hall, 1998.
References and(), CameraTransform(), and length().
Referenced by CameraTransform().
CEcl2Eq()
function CEcl2Eq (in jD)
 This is a single rotation about the x-axis. If the jd is not input it will
 use the mean obliquity for J2000.0.
Form
 c = CEcl2Eq( jD )
Inputs
 jD            (1,1)    Julian date
Outputs
 c             (3,3)    Transformation matrix from the ecliptic plane
                        to the equatorial plane
References: Montenbruck, O., T.Pfleger, Astronomy on the Personal Computer, Springer-Verlag, Berlin, 1991, p. 15.
Referenced by ClockConversion(), EarthEscape(), EarthHelioState(), EclipticInjectionPlane(), HelioFromPlanetInit(), Isothermal(), ProfileStruct(), SailEnvironment(), SailEphemEarth(), SolarSysJPL(), SunVectorECI(), TransformECIToSEMR(), and TransformSEMRToECI().
CentroidNoise()
function CentroidNoise (in d)
 Type CentroidNoise for a demo.
 d = CentroidNoise returns the data structure.
Form
 CentroidNoise;
 sigma = CentroidNoise( d )
Inputs
 d              (1,1)        Data structure
                             .sigmaPFPN (1,1) Pixel fixed pattern noise 1 sigma
                             .sigmaCFPN (1,1) Column fixed pattern noise 1 sigma
                             .sigmaRN   (1,1) Read noise 1 sigma
                             .sigmaDCNU (1,1) Dark current non uniformity 1 sigma
                             .sigmaDCSN (1,1) Dark current shot noise 1 sigma
                             .sigmaPRNU (1,1) Photo response non uniformity 1 sigma
                             .iDark     (1,1) Dark current
                             .sigmaBG   (1,1) Background noise 1 sigma
                             .sigmaPSF  (1,1) Sigma point spread function
                             .tInt      (1,1) Integration time
                             .sigmaQnt  (1,1) Quantization noise
                             .l         (m,m) Mask of intensities (must be square)
Outputs
 sigma          (1,1)       Data structure
                             .rN   (1,1) Read noise 1 sigma
                             .fFPN (1,1) Pixel fixed pattern noise 1 sigma
                             .cFPN (1,1) Column fixed pattern noise 1 sigma
                             .dCNU (1,1) Dark current non uniformity 1 sigma
                             .dCSN (1,1) Dark current shot noise 1 sigma
                             .pRNU (1,1) Photo response non uniformity 1 sigma
                             .pSN  (1,1) Photon shot noise
                             .bG   (1,1) Background subtraction
                             .l0   (1,1) Total response
Reference: Bruce R. Hancock, Robert C. Stirbl, Thomas J. Cunningham, Bebrata Pain,Chris J. Wrigley, Peter G. Ringold Jet, "CMOS Active Pixel Sensor Specific Performance Effects on Star Tracker Imager Position Accuracy", Jet Propulsion Laboratory, California Institute of Technology, Pasadena, CA 91109
References CentroidNoise(), Demo(), length(), PointSpreadFunction2DGaussian(), and square().
Referenced by CentroidNoise(), and GroundTrackErrorBudget().
CMG()
function CMG (in action, in u)
Assumes a tach loop controls the CMG momentum.
 When the alpha and beta angles are zero the CMG momentum vector is
 hCMGBase = [0;H;0];
 The model can accommodate any  number of CMGs. To simulate single gimbal
 CMGs just set one angle and one rate to zero.
 The torque and momentum units are the same as the input momentum units.
 action                  u
 initialize           u.h        (n)      Scalar momentum
 u.b        {n}(3,3) Transforms from CMG base to body
 u.alpha    (n)      Inner gimbal angles (rad)
 u.beta     (n)      Outer gimbal angles (rad)
 u.alphaDot (n)      Inner gimbal angles rates (rad/sec)
 u.betaDot  (n)      Outer gimbal angles rates (rad/sec)
 Only the .h field is required.
 set gimbal rates     u.alphaDot (n)      Inner gimbal angle rates (rad/sec)
 u.betaDot  (n)      Outer gimbal angle rates (rad/sec)
 set gimbal angles    u.alpha    (n)      Inner gimbal angles (rad)
 u.beta     (n)      Outer gimbal angles (rad)
 action                  y
 get torque           torque     (3,1)    Torque in body frame
 get momentum         momentum   (3,1)    Momentum in body frame
Form
 y = CMG( action, u )
Inputs
 action        (1,:)   Actions
 u             (1,1)   Input depends on action
Outputs
 y             (1,:)   Output depends on action
References and(), CMG(), set(), and vector().
Referenced by CMG(), CMGAMatrix(), and RHSSGCMG().
CMGAMatrix()
function CMGAMatrix (in u)
 t = a*[alphaDot(1);betaDot(1);...alphaDot(k);betaDot(k)]
 In the base frame the CMG momentum vector is [0;h;0]
 initialize           u.h        (n)      Scalar momentum
 u.b        {n}(3,3) Transforms from CMG base to body
 u.alpha    (n)      Inner gimbal angles (rad)
 u.beta     (n)      Outer gimbal angles (rad)
Form
 y = CMGAMatrix( u )
Inputs
 u             (1,1)   Data Structure
Outputs
 y             (3,:)   Torque matrix
References CMG(), and vector().
CommandPlugIn()
function CommandPlugIn (in action, in modifier, in hFig, in position, in callback)
 The two actions you send to CommandPlugIn are:
 tag = CommandPlugIn( 'initialize', modifier )
 and
 CommandPlugIn( 'set jd', tag, jD );
 On initialization, modifier has the form
 modifier.function             String with name of function to receive commands
 modifier.commandListDirectory String with path to command list directory
 modifier.helpFile             Help file
 modifier.commandFile          Command file
 The function must accept commands using the format
 Function( 'load command list', d );
 where d is a data structure:
 d.startTime
 d.list
 The command file is a text file with commands in the form
 commandName # &
 The # indicates the command has an index
 The & indicates the command has data
 Either may be omitted.
 The data in the data field may be any Matlab string. An eval is
 performed prior to sending the data to the function.
 Three default commands are
 'none'
 'deactivate'
 'activate'
 How you handle commands is up to you. However, the default meaning for
 the default commands should be:
 'none'       no command
 'deactivate' deactivate command processing
 'activate'   activate   command processing
 Start time may by a string 'xx/xx/xxxx 00:00:00' or 'now'
Form
 x = CommandPlugIn( action, modifier, hFig, position, callback )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifier    (1,:)  Modifier to the action or data structure if intialization
 hFig        (1,1)  Handle to the figure or if 'update' radio button handles
 position    (1,4)  [left bottom width height]
 callback    (1,:)  Callback string when something has changed in this gui
Outputs
 x           (1,1)  The tag if action is 'initialize'
See also
CommandPlugInDemo
References and(), CommandPlugIn(), get(), GetH(), HelpSystem(), Initialize(), and set().
Referenced by CommandPlugIn().
ConstraintForceAndTorque()
function ConstraintForceAndTorque (in action, in varargin)
 It computes the separation forces and torques needed to keep
 the relative velocity between the first vehicle and the rest zero.
 Type ConstraintForceAndTorque for a simulation of two attached
 spacecraft.
 The 2nd spacecraft should rotate around the first one.
 Note that for all arrays body 0 is the first column or element except
 for lambda and kappa where the columns correspond to the hinge vectors.
 hinge 1 is between body 0 and body 1, hinge 2 is between body 0 and
 body 2, etc.
Form
 varargout = ConstraintForceAndTorque( action, varargin )
Inputs
 action           (1,:)    'initialize' or 'update'
 'initialize'
 xA               (13,1)   Aggregate vehicle state
 e                ( 3,:)   Positions of individual body cms in 0
 d                (1, 1)   Data structure
 'update'
 x                (13*n,1) Vehicle state
 d                (1,1)    Data structure
                           .t      (3,n)   Disturbance torques in body k frame
                           .f      (3,n)   Disturbance forces in ECI frame (kN)
                           .inr    {n}     Inertia matrix in body k frame
                           .m      (n)     Mass (kg)
                           .mu     (1,1)   Gravitational parameter
                           .lambda (:,n-1) Vectors from hinge to cm in k frame
                           .kappa  (:,n-1) Vectors from body 0 cm to hinges
                           .b      {n }    Transformation matrix from k to 1
                           .e0     (3,1)   Location of body 0 cm
Outputs
 'initialize'
 x                (13*n,1) State vector
 'update'
 fC               (3,n)    Constraint forces in ECI frame
 tC               (3,n)    Constraint torques in ECI frame
References and(), and ConstraintForceAndTorque().
Referenced by ConstraintForceAndTorque().
Counter()
function Counter (in action, in d)
Form
 count = Counter( action, d )
Inputs
 action       (1,:)     'initialize', or 'update'
 d            (1,1)     action == 'initialize'
                        .nBits   (n,1) number of bits
                        .id      (1,1) id
                        action == 'update'
                        .counts  (n,1)
                        .id      (1,1) id
Outputs
 count        (1,1)     Counts
References get(), length(), and zeros().
Referenced by GUICounter(), and Gyro().
CreateVCDisturbanceFile()
function CreateVCDisturbanceFile (in g, in fileName)
Each line is
 componentID v1 v2 v3 {cDF alphaF epsF rhoSF rhoDF rhoAF}...
 rhoT {repeat back}
The repeat is for 2 sided faces. Each face is a triangle.
 alpha   thermal absorptivity
 eps     thermal emissivity
 cD      drag coefficient
 rhoS    specular optical coefficient
 rhoD    diffuse optical coefficient
 rhoA    absorption optical coefficient
 rhoT    transmissivity (the same for the back)
 id      the component
F means front, B back. The fron normal is found by going v1->v2->v3 Type
 CreateVCDisturbanceFile
to create a cube spacecraft.
Form
 CreateVCDisturbanceFile;   % demo
 CreateVCDisturbanceFile( g, fileName )
Inputs
 g         (:)    CAD model
 fileName  (1,:)  File anme
Outputs
 None
CW2Roll()
function CW2Roll (in scanAngle, in cant, in uSpin, in uPitch, in earthRadius, in chordwidth)
Gives two outputs to account for the nadir angle ambiguity.
Form
 roll = CW2Roll( scanAngle, cant, uSpin, uPitch, earthRadius, chordwidth  )
Inputs
 scanAngle     (:)  Measured scan angle (rad)
 cant          (1,1)    Sensor element cant angle from the spin-axis (rad)
 uSpin         (3,1)    Sensor spin-axis
 uPitch        (3,1)    Pitch axis
 earthRadius   (1,1)    Angular radius of the earth (rad)
 chordwidth    (:)      Measured chordwidth (rad)
Outputs
 roll          (2,:)  Roll angle (rad)
References abs(), isempty(), length(), Nadir(), Plot2D(), and zeros().
DblPivot()
function DblPivot (in p1, in p2, in p3)
 The three pivot positions are given as p1, p2 and p3 all with respect to a
 common reference plane. Positive is taken using the right hand rule
 going from point 1 to 2 to 3.
 Since version 1.
Form
 n = DblPivot( p1, p2, p3 )
Inputs
 p1            (3,1) Pivot point 1
 p2            (3,1) Pivot point 2
 p3            (3,1) Pivot point 3
Outputs
 n             (3,1) The normal
References and().
DeltaML()
function DeltaML (in L1, in L2, in t1, in t2, in n)
 Computes the change in longitude accounting for multiple revolutions in
 between the first and second values based on the mean motion.
 Since version 1.
Form
 dL = DeltaML( L1, L2, t1, t2, n )
Inputs
 L1            (1,:)   Initial Longitude (deg)
 L2            (1,:)   Final Longitude (deg)
 t1            (1,:)   Initial Time (days)
 t2            (1,:)   Final Time (days)
 n             (1,:)   Daily motion (deg/day)
Outputs
 dL            (1,:)   Change in longitude (deg)
References and(), and length().
DeltaQTarget()
function DeltaQTarget (in qCommand, in qIToB, in qOld, in deltaAngle)
Form
 [qTargetToBody,qOld] = DeltaQTarget(qCommand,qIToB,qOld,deltaAngle)
Inputs
 qCommand    (4,1)   Commanded inertial quaternion
 qIToB       (4,1)   Current body quaternion
 qOld        (4,1)   Previous inertial target
 deltaAngle  (1,1)   Maximum angular change for new target
Outputs
 qTargetToBody (4,1) Target to body quaternion
 qOld          (4,1) Memory of inertial target
References abs(), AU2Q(), DeltaQTarget(), DeltCirc(), Q2AU(), QMult(), QPose(), quaternion(), and QUnit().
Referenced by DeltaQTarget().
DeltaRate()
function DeltaRate (in ignoredArg, in ignoredArg, in omega)
Form
 omega = DeltaRate( InertiaOld, InertiaNew, omega )
Inputs
 inertiaOld     (3,3)  Old inertia
 inertiaOld     (3,3)  New inertia
 omega          (3,1)  Angular rate
Outputs
 omegaNew       (3,1)  Angular rate
Demo()
function Demo ()
The boresight is along +z. It will draw a picture if there are no outputs.
Type StaticEarthSensor for a demo.
Form
 y = StaticEarthSensor(q,r,d)
Inputs
q   (4,1)  ECI to Body
r   (3,1)  Vector from planet center to spacecraft
d   (.)   Data structure
.n              (1,1) Number of segments in the planet circle
.p              (2,:) Vertices for the detector
.pAng           (2,:) Vertices in angles (deg)
.az             (1,n) Azimuth of the detector elements
.el             (1,n) Elevation of the detector elements
.rPlanet        (1,1) Planet radius
.fL             (1,1) Focal length
.qBodyToSensor (4,1) Quaternion from body to sensor frame
.scale          (1,1) Output/detector area intersecting
Outputs
y   (:,1)  Detector outputs
Copyright (c) 2022 Princeton Satellite Systems, Inc. All rights reserved.
Since version 2022.1 Demo Quaternion from ECI to the sensor frame Planet angular width Cycle through all the elements Convert from area to output Default output < StaticEarthSensor>Demo
References StaticEarthSensor().
DIModel()
function DIModel (in inr, in tSamp, in sType)
 The equations have the form
 [ x ]   [ 0  1 ] [ x ]   [ 0 ]
 [   ] = [      ] [   ] + [   ] u/inr
 [ v ]   [ 0  0 ] [ v ]   [ 1 ]
 The function can return state space matrices or a state derivative.
 Since version 1.
Form
 [a, b, c, d] = DIModel( inr, tSamp, sType )
 [dxdt   ] = DIModel( inr, x, u )
Inputs
 inr            (1,1) Inertia
 tSamp or x     (1,1) Sampling frequency or state
 sType or u     (1,:) State equation type ('Delta' or 'Z') or input
Outputs
 a or dxdt      (2,2) Plant matrix or state derivative
 b              (2,1) Input matrix
 c              (1,1) Measurement matrix
 d              (1,1) Feedthrough matrix
References C2DelZOH(), C2DZOH(), and FResp().
Dipole()
function Dipole (in m, in xD, in x)
Form
 b = Dipole( m, xD, x )
Inputs
 m             (3,1)   Magnetic dipole vector (ATM^2)
 xD            (3,1)   Location of the dipole (m)
 x             (3,:)   Points of interest (m)
Outputs
 b             (3,:)   Magnetic field (T)
References abs(), Constant(), Cross(), Dipole(), Dot(), isempty(), Mag(), Plot2D(), Unit(), vector(), and zeros().
Referenced by AirCoreMagneticTorquerDesign(), BDipolePlanet(), BMF(), Dipole(), DipoleFromField(), Disturbances(), HalbachField(), MagAirC(), MagControlThreeAxis(), MagControlTwoAxis(), MagneticControl(), MagneticDipole(), MagneticDipoleCart(), MagneticFieldDipole(), MagneticTorquerDesign(), MagneticTorquerDipoleMoment(), MagTComp(), MomentumUnloading(), RHSRigidBodyWithDamping(), SkewDipl(), and UDipole().
DipoleFromField()
function DipoleFromField (in b, in h)
 Assumes b is measured at the end in Tesla. 1 Tesla is 10000 gauss.
 Since version 2014.1
Form
 m = DipoleFromField( b, h )
Inputs
 b         (1,:)   Magnetic field (T)
 h         (1,1)   Length (m)
Outputs
 m         (1,:)   Dipole moment (ATM^2)
References Dipole(), DipoleFromField(), and Plot2D().
Referenced by DipoleFromField().
DistAero()
function DistAero (in r, in q, in v, in n, in a, in p, in rho, in shadowFun)
The optional shadowing function has the form
 [a,p] = ShadowFun(u, n, a, p)
and serves to elimate shadowed surfaces from further calculation.
Form
 [f, t] = DistAero( r, q, v, n, a, p, rho, shadowFun )
Inputs
 r         (3,:) Position vectors
 q         (4,:) Quaternion from ECI to body
 v         (3,:) Velocity vector (km/s)
 n         (3,m) Unit surface outward normals
 a         (1,m) Areas for each surface (m^2)
 p         (3,m) Location of each surface
 rho       (1,:) Density
 shadowFun  (:)  Handle for shadowing function
Outputs
 f         (3,:) Aero force
 t         (3,:) Aero torque
References and(), Cross(), Demo(), DistAero(), length(), Mag(), Period(), QForm(), QTForm(), RVOrbGen(), Unit(), vector(), and zeros().
Referenced by DistAero().
DistAlbedo()
function DistAlbedo (in r, in q, in uSun, in n, in a, in p, in optical, in alpha, in rPlanet, in qSun, in shadowFun)
The optional shadowing function has the form [a,p] = ShadowFun(u, n, a, p) and serves to elimate shadowed surfaces from further calculation.
Form
 [f, t] = DistAlbedo( r, q, uSun, n, a, p, optical, alpha, rPlanet, qSun, shadowFun )
Inputs
 r         (3,:) Position vectors
 q         (4,:) Quaternion from ECI to body
 uSun      (3,:) Unit sun vector
 n         (3,m) Unit surface outward normals
 a         (1,m) Areas for each surface
 optical   (4,m) Optical coefficients
 p         (3,m) Location of each surface
 alpha     (1,1) Albedo coefficient
 rPlanet   (1,1) Planet radius
 qSun      (1,1) Solar flux
 shadowFun  (:)  Handle for shadowing function
Outputs
 f       (3,:) Albedo force
 t       (3,:) Albedo torque
 flux    (1,:) Albedo flux
References and(), Cross(), Date2JD(), Demo(), DistAlbedo(), isempty(), Mag(), Period(), QForm(), QTForm(), RVOrbGen(), SunV1(), Unit(), vector(), and zeros().
Referenced by DistAlbedo().
DistRadiation()
function DistRadiation (in r, in q, in n, in a, in p, in optical, in rPlanet, in qPlanet, in shadowFun)
The optional shadowing function has the form [a,p] = ShadowFun(u, n, a, p) and serves to elimate shadowed surfaces from further calculation.
Form
 [f, t, flux] = DistRadiation( r, q, n, a, p, optical, rPlanet,
 qPlanet, shadowFun )
Inputs
 r         (3,:) Position vectors
 q         (4,:) Quaternion from ECI to body
 n         (3,m) Unit surface outward normals
 a         (1,m) Areas for each surface
 p         (3,m) Location of each surface
 optical   (4,m) Optical coefficients
 rPlanet   (1,1) Radius of the planet
 qPlanet   (1,1) Flux from the planet
 shadowFun  (:)  Function handle for a shadowing function, optional
Outputs
 f         (3,:) Radiation force
 t         (3,:) Radiation torque
 flux      (1,:) Radiation flux
References and(), Cross(), Demo(), DistRadiation(), isempty(), Mag(), Period(), QForm(), QTForm(), RVOrbGen(), Unit(), vector(), and zeros().
Referenced by DistRadiation().
DistributedAlbedo()
function DistributedAlbedo (in action, in d)
 Works with any Matlab compatible image file format.
 Functions to convert texture maps to albedo may be supplied in the form
 alpha      = fun( textureMap );
 textureMap is a Matlab generated format using the Matlab imread function.
 textureMap = imread( fileName );
 Type DistributedAlbedo for a demo of an Earth orbiting satellite. It
 compares the results with EarthAlb.
See also
AlbedoFromTextureMap.
Form
 q = DistributedAlbedo( action, d )
Inputs
 action      (1,:) 'initialize' or 'update'
 d           (1,1)  If 'initialize'
                    .planetFile  (1,:) Name of the planet file
                    .cloudFile   (1,:) Name of the cloud file
                    .planetFun   (1,:) Name of the planet function
                    .cloudFun    (1,:) Name of the cloud cloud function
                    .alphaAve    (1,1) Default alpha (0.34 is the default );
                    .radius      (1,1) Planet radiust
                    .planet      (1,:) Planet name
 If 'update'
 .r           (3,:) Satellite position
 .jD          (1,:) Julian date
 .flux        (1,:) Solar flux (W/m^2)
Outputs
 q            (1,:) Flux (W/m^2)
References AlbedoFromTextureMap(), DistributedAlbedo(), EarthAlb(), FindSolsticeOrEquinox(), length(), Mag(), Period(), RVFromKepler(), SunV1(), and Unit().
Referenced by DistributedAlbedo().
DistSolar()
function DistSolar (in r, in q, in uSun, in n, in a, in p, in optical, in rPlanet, in rSun, in shadowFun)
The optional shadowing function has the form a,p] = ShadowFun(u, n, a, p) and serves to elimate shadowed surfaces from further calculation.
Form
 [f, t] = DistSolar( r, q, uSun, n, a, p, optical, rPlanet, rSun, shadowFun )
Inputs
 r         (3,:) Position vectors
 q         (4,:) Quaternion from ECI to body
 uSun      (3,:) Unit sun vector
 n         (3,m) Unit surface outward normals
 a         (1,m) Areas for each surface
 p         (3,m) Location of each surface
 optical   (4,m) Optical coefficients
 rPlanet   (1,1) Planet radius
 rSun      (1,:) Distance to sun
 shadowFun  (:)  Handle for shadowing function
Outputs
 f         (3,:) Solar force
 t         (3,:) Solar torque
 flux      (1,:) Solar flux
References and(), Cross(), Date2JD(), Demo(), DistSolar(), Eclipse(), isempty(), Period(), QForm(), QTForm(), RVOrbGen(), SunV1(), Unit(), vector(), and zeros().
Referenced by DistSolar().
Disturbances()
function Disturbances (in mode, in g, in e, in h, in doPlots)
Environment inputs are given in e.
The number of points generated will equal the length of the longest transformation matrix in g or the longest member of e. If the number of points is > 1 all other members of e and transformation matrices in g must equal that number or 1.
The optical input is a flux vector with magnitude in watts. The aerodynamic and optical computations optionally use shadowing. To get shadowing you must enter the shadow and scanLines fields. Planetary radiation assumes that the optical coefficients are zero except for the diffuse coefficient which is 1.
The defaults are:
 - AtmDens2 for the Earth, if atmosphericDensity is not entered
 - AtmDens1 for the other planets, if atmosphericDensity is not entered
 - Constant(['bond albedo ',e.planet]) for albedo fraction, if not entered
 - Constant(['mu ',e.planet]) for mu, if not entered
 - Constant(['equatorial radius ',e.planet]), if planetRadius not entered
 - Constant(['black body radiation ',e.planet]) if radiation is not entered
 - No aerodynamic disturbances unless v is entered
 - No planetary radiation unless r is entered
 - Flags computeAero and computePR override defaults
 - No shadowing
 - No scan display and 0 scanLines
 - No plots
 The output units are determined by e.units as follows:
 e.units        force      torque
 'm'            N          Nm
 'in'           lbf        in-lbf
 'ft'           lbf        ft-lbf
 Your first call
 h = Disturbances( 'init', g, e );
 This returns a handle, h, to the display. You can then call this
 [f, t, m, harm, angMom] = Disturbances( 'run', g, e, h, doPlots )
 multiple times.
 Forms:
 e = Disturbances( 'defaults' )
 h = Disturbances( 'init', g, e )  % with display
 [f, t, m, harm, angMom] = Disturbances( 'run', g, e, h, doPlots )
 [f, t] = Disturbances( 'run', g, e )   % no display
Inputs
 mode     ''     'init', 'defaults' or 'run'
 g       (.)     Spacecraft data structure
 e       (.)     Disturbances data structure
                  .units              (1,:) 'm', 'in', 'ft'
                  .r                  (3,:) Distance from gravity center (km)
                  .v                  (3,:) Velocity vector in the inertial frame (km/sec)
                                            - should include planetary rotation
                  .s                  (3,:) Solar optical radiation flux vector (watts)
                  .b                  (3,:) Magnetic field vector (T)
                  .planet             (1,:) Will compute density and mu for various
                                            planets
                  .planetRadius*       (1,:) Radius of the planet (km)
                  .atmosphericDensity* (1,:) Density
                  .mu*                 (1,1) Gravitational parameter (km^3/sec^2)
                  .albedo*             (1,1) Albedo fraction
                  .radiation*          (1,1) Planet radiation (W/m^2)
                                             * looked up by planet if not entered or 0
                  .tGas               (1,1) Gas temperature (deg-K)
                  .mGas               (1,1) Gas molecular weight (kg/mol)
                  .tSamp              (1,1) Sample time between transformation matrices in g or
                                            (1,:) time vector if irregular
                  .shadow             (1,1) 1 for on, 0 for off - optical/thermal
                  .nScanLines         (1,1) Number of scan lines for shadowing
                  .showScans          (1,1) True means show the HSRCAD scan display
                  .computeAero**      (1,1) True means compute aerodynamic torques
                  .computePR**        (1,1) True means compute planetary radiation torques
                  .computeRF**        (1,1) True means compute RF torques
                  .computeGG**        (1,1) True means compute gravity gradient torques
                  .computeMag**       (1,1) True means compute magnetic torques
                                                ** optional fields
 h        (1)     Handle to display (optional)
 doPlots  (1)     If true, will plot outputs
Outputs
 f         (:)    Force structure or handle to display if mode is 'init'
                  .total    (3,:)   Force in ECI frame
                  .aero             Aerodynamic
                  .optical          Optical
                  .thermal          Thermal
                  .rF               Radio Frequency
                  .pR               Planetary radiation
                  .al               Planetary albedo
 t         (:)    Torque structure
                  .total   (3,:)   Torque in body frame
                  .aero
                  .magnetic
                  .optical
                  .thermal
                  .rF
                  .pR
                  .al
                  .gravityGradient
 m         (:)    Mass properties
                  .mass
                  .inertia
                  .cM
 harm      (:)    Harmonic coefficients
 .wf(3,:) Harmonic frequencies for force
                               .wt(3,:) Harmonic frequencies for torque
 .f (3,:) Harmonic coefficents
 .sin
 .cos
 .dC
 .t (3,:) Harmonic coefficents
 .sin
 .cos
 .dC
 angMom   (:)    Angular momentum
 .eCI  (3,:) In the inertial frame
 .body (3,:) In the body frame
References and(), AtmDens1(), AtmDens2(), BDipole(), BHinge(), close(), Constant(), Dipole(), Disturbances(), DupVect(), FAeroSurfaceAccommodation(), Figui(), FourierSeries(), Frequency(), get(), HSRCAD(), Initialize(), isempty(), JD2000(), length(), Mag(), Plot2D(), series(), set(), SolarFlx(), SunV1(), TimeLabl(), Unit(), vector(), VOrbit(), and zeros().
Referenced by AeroDragForce(), Disturbances(), EarthEnvironment(), PlanetEnvironment(), RHSCubeSat(), RHSRWA(), RHSRWAIDotSC(), S4DeployTorque(), and SpacecraftThermal().
DrawFieldLines()
function DrawFieldLines (in r, in n, in fun, in jD)
You pass it a function that outputs the vectors. The function must be of the form
 fun( x(3,:), jD )
x is generated internally from latitude, longitude and r.
Form
 DrawFieldLines( r, n, fun, jD )
Inputs
 r           (1,1)      Radius
 n           (1,1)      Number of latitude and longitude points
 fun         (1,:)      Name of function
 jD          (1,1)      Julian date (days)
Outputs
 None
References and(), BDipole(), DrawFieldLines(), JD2000(), length(), NewFig(), Watermark(), and zeros().
Referenced by DrawFieldLines().
DrawSCPlugIn()
function DrawSCPlugIn (in action, in modifier, in hFig, in position, in planet, in jD)
Includes a separate controls window.
The controls window allows for zooming and orbiting the camera, adjusting the ambient light, and changing renderer or camera target. Only external surfaces, as identified by the 'inside' component parameter, will be drawn. ]
There are three calls you need to make when using this plugin.
(1) Initialize:
 tag = DrawSCPlugIn( 'initialize', g, hFig, position, planet, jD )
 g        is the spacecraft CAD data structure. It must have the following
 fields:
 .rECI, ECI orbit position of the spacecraft (km).
 .qLVLH, needed for camera pointing
 The inertial quaternion (body to ECI) should be stored with the first body.
 The spacecraft model must be in meters.
 hFig     is the handle to the figure window
 position is an array [left bottom width height] which gives the position
 of the plugin in the window
 planet   is the name of any planet in the toolbox, the default is 'earth'
 jD       is the Julian date; passed to SunV1 for solar lighting
 If hFig is not entered it will create a new window. You need to save tag
 to call the function in subsequent calls.
(2) Update with new state or attitude information
 When passing new information to the plugin use
 DrawSCPlugIn( 'update spacecraft', tag, g, jD )
(3) Close the windows
 To close the display type
 DrawSCPlugIn( 'quit', tag )
 The plugin will scale the spacecraft model up to 5% of the ECI position
 vector in order for the spacecraft to be rendered by MATLAB.
Form
 DrawSCPlugIn( action, modifier, hFig, position, planet, jD )
Inputs
 action      (1,:)  Action
 modifier    (1,:)  Modifier to the action
 hFig        (1,1)  Handle to the figure or if 'update' is jD
 position    (1,4)  [left bottom width height]
 planet      (1,:)  Planet name (corresponding to a mat-file)
 jD          (1,1)  Julian Date
Outputs
 tag         (1,:)  The tag that identifies the display
References and(), close(), Date2JD(), DrawSCPlugIn(), El2RV(), get(), GetH(), HelpSystem(), Initialize(), length(), quaternion(), QZero(), SunV1(), and vector().
Referenced by DrawSCPlugIn(), and SpacecraftPlugIn().
DSpnStab()
function DSpnStab (in iR, in iP, in iT1, in iT2, in wR, in wP)
 Since version 1.
Form
 dSS = DSpnStab( iR, iP, iT1, iT2, wR, wP )
Inputs
 iR         (1,1)  Rotor inertia
 iP         (1,1)  Platform inertia about same axis as rotor
 iT1        (1,1)  Transverse axis platform inertia 1
 iT2        (1,1)  Transverse axis platform inertia 2
 wR         (:)    Angular velocity of rotor
 wP         (:)    Angular velocity of platform
Outputs
 dSS        (:)    1 = stable, 0 = unstable
References and(), DupVect(), length(), Mesh2(), and zeros().
DSTCrit()
function DSTCrit (in iWheel, in iPitch, in iRoll, in iYaw, in hW)
Compute range of allowable initial rates for the dual spin turn given a momentum wheel aligned with pitch and the initial rate about yaw.
Form
 [wIMax, wIMin, wFMax] = DSTCrit( iWheel, iPitch, iRoll, iYaw, hW )
Inputs
 iWheel      (1,1) Wheel inertia
 iPitch      (1,1) Pitch axis inertia
 iRoll       (1,1) Roll axis inertia
 iYaw        (1,1) Yaw axis inertia
 hW          (1,1) Final momentum wheel momentum
Outputs
 wIMax       (1,1) Maximum allowable yaw rate
 wIMin       (1,1) Minimum allowable yaw rate
 wFMax       (1,1) Final pitch axis rate
References: Hubert, C., Attitude Acquisition from a Spinning or Tumbling State, J. Guidance and Control 4(2), 164-170.
References abs(), and and().
Referenced by DST().
DWheel()
function DWheel (in iT, in iS, in wS, in tau, in e)
Assumes a symmetric spinning spacecraft with a damper wheel about one of its transverse axes. The damping is assumed to have minimal effect on the spin rate. This function is useful for studying the behavior of rigid bodies with damping and for setting the damper wheel parameters when a damper wheel is used to model damping from other sources such as slosh or magnetic eddy currents. The damped natural frequency is constrained to be equal to the undamped nutation frequency.
Form
 [D1, D2] = DWheel( iT, iS, wS, tau, e )
Inputs
 iT          (1,1)   Transverse inertia
 iS          (1,1)   Spin-axis inertia
 wS          (1,1)   Spin rate (rad/sec)
 tau         (n)     Time constant
 e           (m)     Ratio of damper wheel inertia to transverse
                     inertia
Outputs
 D1         (1,1)   Ratio of damping coefficient to damper wheel
                     inertia
 D2         (1,1)   Ratio of damping coefficient to damper wheel
                     inertia
References abs(), and(), Constant(), length(), NewFig(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Dyn()
function Dyn (in ignoredArg, in ignoredArg, in dynData)
Form
 [M, Q] = Dyn( x, t, dynData )
Inputs
 x            (8,1)     The state vector [x1;y1;x2;y2;x1Dot..]
 t                      Time
 dynData      (1,3)     [m1 m2 g]
Outputs
 M            (4,4)     The mass matrix
 Q            (4,1)     The right hand side
References and(), and vector().
Referenced by DynP().
DynP()
function DynP (in ignoredArg, in ignoredArg, in dynData)
Similar to Dyn but without g
Form
 [M, Q] = DynP( x, t, dynData )
Inputs
 x            (4,1)     The state vector [x;y;xDot;yDot]
 t                      Time
 dynData      (1,3)     [m g]
Outputs
 M            (2,2)     The mass matrix
 Q            (2,1)     The right hand side
References and(), Dyn(), and vector().
EarthAlb()
function EarthAlb (in r, in u, in uS, in alpha, in aF, in w)
aF and w can be scalars even if r is not.
Form
 q = EarthAlb( r, u, uS, alpha, aF, w )
Inputs
 r         (:)     Ratio of satellite radius to planet radius
 u         (3,:)   Unit vector to satellite
 uS        (3,1)   Unit vector to sun
 alpha     (1,:)   Absorptivity (should be specific for albedo)*
 aF        (1,:)   Albedo fraction (uses 0.34 if no input)*
 w         (1,:)   Flux (uses 1367 w/m^2 if no input)*
                      *optional
Outputs
 q         (1,:)   Absorbed flux (watts/m^2)
References: Van Vliet, R. M., Passive Temperature Control in the Space Environment, MacMillan, 1965, pp. 10-13.
References and(), Demo(), Dot(), EarthAlb(), FindSolsticeOrEquinox(), isempty(), length(), Mag(), Period(), Plot2D(), RVFromKepler(), SunV1(), Unit(), vector(), and zeros().
Referenced by DistributedAlbedo(), EarthAlb(), Isothermal(), IsothermalLunar(), PlanetaryRadiationAndAlbedo(), RHSIsothermal(), and SailEnvironment().
EarthEclipseDuration()
function EarthEclipseDuration (in el, in jD)
Uses the orbit radius at perigee for the computation. The orbital elements are:
 [Semi-major axis, Inclination, Right ascension of the ascending node,
 Argument of perigee, Eccentricity, Mean Anomaly]
Type EarthEclipseDuration for a demo in a 7000 km 85 deg orbit. Uses SunBeta and EclipseDuration.
Form
 [d, dMax] = EarthEclipseDuration( el, jD )
Inputs
 el          (1,6) [a i W w e M]
 jD          (1,:) Julian date (days)
Outputs
 d           (1,:) Eclipse duration (sec)
 dMax        (1,1) Maximum eclipse duration (sec)
References A2Perige(), and(), Date2JD(), Demo(), EarthEclipseDuration(), Eclipse(), EclipseDuration(), length(), Period(), Plot2D(), SunBeta(), SunV1(), vector(), and zeros().
Referenced by EarthEclipseDuration().
EarthEnvironment()
function EarthEnvironment (in rECI, in vECI, in jD, in e)
This data is required by the disturbance model. In order to calculate drag, the velocity must be computed relative to the atmosphere; this routine uses a simplified calculation that ignores Earth nutation.
This routine calculates eclipses. A simple dipole model is used for the magnetic field.
 Forms:
 e = EarthEnvironment( rECI, vECI, jD, e )
Inputs
 rECI   (3,:)    Position vectors in ECI frame
 vECI   (3,:)    Velocity vectors
 jD     (1,:)    Time scalar or array in Julian date
 e       (.)     Initial structure
Outputs
 e       (.)     Environment data with updated data, see Disturbances
See also
: AtmDens2, SunV2, Eclipse, BDipole, VAtm, Disturbances
References and(), AtmDens2(), BDipole(), Constant(), DefaultDataStructure(), Disturbances(), EarthEnvironment(), Eclipse(), isempty(), JD2000(), JD2T(), length(), Mag(), Plot2D(), PlotPlanetOrbit(), RVOrbGen(), scalar(), SunV2(), TimeLabel(), TruEarth(), VAtm(), and zeros().
Referenced by EarthEnvironment().
EarthNut()
function EarthNut (in T)
See also
NutDelta, ObOfE.
 Default is today's date.
Form
 [n, eps0, epsT, deltaPsi, deltaEps] = EarthNut( T )
Inputs
 T          (1,1) Julian centuries of 86400s dynamical time from j2000.0
Outputs
 n          (3,3) Nutation matrix (transforms from mean to true)
 eps0       (1,1) Mean obliquity     (deg)
 epsT       (1,1) True obliquity     (deg)
 deltaPsi   (1,1) Delta in longitude (deg)
 deltaEps   (1,1) Delta in obliquity (deg)
References: Seidelmann, P., ed. The Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992, p. 115.
References NutDelta(), and ObOfE().
Referenced by ProcessCatalog(), SReduce(), and TruEarth().
EarthPre()
function EarthPre (in T)
Form
 p = EarthPre( T )
Inputs
 T  (1,1) Julian centuries of 86400s dynamical time from j2000.0
Outputs
 p  (3,3) Precession matrix
References: Seidelmann, The Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992, p. 103.
References Date2JD(), and JD2T().
Referenced by ProcessCatalog(), SReduce(), and TruEarth().
EarthRad()
function EarthRad (in r, in alpha, in w)
Form
 q = EarthRad( r, alpha, w )
Inputs
 r           (1,:) Distance from center of the planet in radii
 alpha       (1,1) Absorptivity (should be specific for infrared)
 w           (1,1) Flux (uses 250 w/m^2 if no input)
                   Cloudy sky is 140 w/m^2, with no clouds = 320 w/m^2
Outputs
 q           (1,:) Absorbed flux per unit area
References isempty(), and Plot2D().
Referenced by Isothermal(), IsothermalLunar(), PlanetaryRadiationAndAlbedo(), RHSIsothermal(), and SailEnvironment().
EarthRot()
function EarthRot (in T, in ignoredArg)
 Any input of eOfECalc will cause it to include the equation of the
 equinoxes.
 Type EarthRot for a demo.
Form
 [g, gMST, gAST] = EarthRot( T, eOfECalc )
Inputs
 T           (1,1) Julian centuries of 86400s dynamical time from j2000.0
 eOfECalc    (1,1) Calculate the equation of the equinoxes
Outputs
 g           (3,3) Greenwich matrix
 gMST        (1,1) Greenwich mean sidereal time (deg)
 gAST        (1,1) Greenwich apparent sidereal time (deg)
See also
: GMSTime, EOfE, JD2T
References: Seidelmann, P. K., The Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992, p. 20.
References Date2JD(), EarthRot(), EOfE(), get(), GMSTime(), isempty(), and JD2T().
Referenced by EarthRot(), ECIToECIR(), FEarthMoonSun(), MeasDoris(), MeasEarthTarget(), MeasGPS(), MeasRangeGroundStation(), MeasRangeGroundStationEF(), PlanetRot(), SafeGuidanceSim(), TelescopeUKF(), and TruEarth().
EarthRotationZero()
function EarthRotationZero (in jD, in eOfECalc)
 The input JD gives the day of interest.
Form
 jD0 = EarthRotationZero( jD, eOfECalc )
Inputs
 jD          (1,1 Julian date
 eOfECalc    (1,1 Calculate the equation of the equinoxes
Outputs
 jD0         (1,1 Julian date at which theta is zero
References: Seidelmann, P. K., Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992, p. 20.
EarthRte()
function EarthRte (in jD)
See also
MSidDay.
 Since version 1.
Form
 w = EarthRte( jD )
Inputs
 jD              (1,1)   Julian date (day)
Outputs
 w               (1,1)    Mean earth rate (rad/sec)
References: The Astronomical Almanac for the Year 1993, U.S. Government Printing Office, 1993, p. B6.
References Date2JD(), and MSidDay().
Referenced by GPSSatellite(), and MeasRangeGroundStation().
ECIToECIR()
function ECIToECIR (in jD, in eOfECalc)
 ECIR is an inertially fixed frame that coincides with EF at jD.
Form
 m = ECIToECIR( jD, eOfECalc )
Inputs
 jD          (1,1) Julian date
 eOfECalc    (1,1) Calculate the equation of the equinoxes
Outputs
 m           (3,3) Julian date at which theta is zero
References: Seidelmann, P. K., ed., The Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992, p. 20.
References EarthRot(), and JD2T().
ECIToPlanet()
function ECIToPlanet (in jD, in planet, in kEarth)
Includes all of the planets and many of the moons. Returns the identity matrix if the moon is unknown. For the Earth's moon it returns the true rotation matrix. All rotations are from the astronomical almanac.
Form
 c = ECIToPlanet( jD, planet, kEarth )
Inputs
 jD         (1,1)  Julian date
 planet     (1,:)  Name of the planet
 kEarth     (1,1)  If 0 use TruEarth, if 1 is TruEarth with eofe,
                   if <0 use Montenbruck (see also ECIToEF)
Outputs
 c         (3,3)  Matrix from Mean of 2000.0 to planet fixed
References: Seidelmann, ed. The Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992, p. 705.
References and().
Referenced by BDipolePlanet(), FOrbHFOP(), FOrbitMultiSpacecraft(), FOrbKF(), GroundTrack(), OrbTrack(), PlanetEnvironment(), PlanetRot(), SpaceCamera(), and StoppingConditions().
Eclipse()
function Eclipse (in rSC, in rSource, in rPlanet, in radiusPlanet, in radiusSource)
Form
 [n, eclipseType] = Eclipse( rSC, rSource, rPlanet, radiusPlanet, radiusSource )
Inputs
 rSC             (3,:)      Position vector of the spacecraft with
                            respect to the planet
 rSource         (3,: or 1) Position vector of the light source
 rPlanet         (3,: or 1) Position vector of the planet causing the eclipse
                            (default is zeros)
 radiusPlanet    (1,1)      Radius of the planet causing the eclipse
                            (default is the Earth)
 radiusSource    (1,1)      Radius of the light source (default is the sun)
Outputs
 n               (1,:)      Normalized Source intensity ( 0 < n < 1 )
 eclipseType     (1,:)      0 = none 1 = partial, 2 = annular 3 = total
References abs(), and(), Dot(), DupVect(), Eclipse(), isempty(), length(), Mag(), NPlot(), Plot2D(), vector(), and zeros().
Referenced by BatterySize(), CubeSatEnvironment(), CubeSatLunarEnvironment(), CubeSatPowerAnalysis(), CubeSatRadiationPressure(), DistSolar(), EarthEclipseDuration(), EarthEnvironment(), Eclipse(), EclipseFill(), EclipseFromECI(), EclipseHelio(), FOrbitMultiSpacecraft(), GeoEclps(), Isothermal(), IsothermalHelio(), IsothermalLunar(), PanelThermalModel(), PlanetEnvironment(), PowerDesign(), RHSIsothermal(), SafeGuidanceSim(), SailEnvironment(), SolarFluxFromPlateECI(), SolarVisibility(), and WorstEclipseFraction().
EclipseDuration()
function EclipseDuration (in rSC, in rPlanet, in beta)
 This assumes that orbit radius is constant for the duration of the
 eclipse. This will  be true for low eccentricity orbits at apogee.
 Type EclipseDuration for a demo
Form
 fractionOfOrbit = EclipseDuration( rSC, rPlanet, beta )
Inputs
 rSC             (1,n)      Radius of the spacecraft's orbit
 rPlanet         (1,1)      Radius of the planet
 beta            (1,m)      Angle between the source and the orbit plane
Outputs
 fractionOfOrbit (n,m)      Eclipse orbit fraction
References EclipseDuration().
Referenced by EarthEclipseDuration(), and EclipseDuration().
EclipseFill()
function EclipseFill (in aX, in e, in t)
Form
 EclipseFill(aX,e,t)
Inputs
 aX  (1,1) Handle axes
 e   (1,:) Eclipse array
 t   (1,:) Time array
Outputs
 None
References Eclipse(), EclipseFill(), and length().
Referenced by EclipseFill().
EclipseFromECI()
function EclipseFromECI (in r, in t, in jD0, in a)
Utilizes the low-precision sun ephemeris in SunV1.
Form
 n = EclipseFromECI(r, t, jD0, a)
Inputs
 r      (3,:) Position vector of the spacecraft
 t     (1,:) Time vector
 jD0   (1,1) Initial Julian date
 a     (1,:) Auxiliary input to plot
Outputs
 n     (1,:) Normalized sun intensity ( 0 < n < 1 )
See also
: SunV1, Eclipse
References and(), Demo(), Eclipse(), EclipseFromECI(), JD2000(), Plot2D(), RVOrbGen(), SunV1(), TimeLabl(), and vector().
Referenced by EclipseFromECI().
ECLSSSizing()
function ECLSSSizing (in nCrew, in nDays, in type)
 Has a demo comparing the three types.
Form
 p = ECLSSSizing( nCrew, nDays, type )
Inputs
 nCrew            (1,:) Number of crew
 nDays            (1,:) Number of days
 type             (1,:) 'open', 'closed', 'partially closed'
Outputs
 p                (1,1) Data structure
                        .PR    (1,:) Power required (kW)
                        .WH    (1,:) Waste heat generated (kW)
                        .SCM   (1,:) Mass of spare parts and consumables (kg)
                        .SCV   (1,:) Volume of spare parts and consumables (m^3)
                        .HWM   (1,:) Mass of system hardware (kg)
                        .HWV   (1,:) Volume of system hardware( m^3)
                        .TOTSM (1,:) Total system mass (kg)
                        .TOTSV (1,:) Total system volume (m^3)
                        .PI    (1,:) Power impact penalty (kg)
                        .HI    (1,:) Waste heat impact penalty (kg)
Reference: Miller, S., "Environmental Control and Life Support System"
References and(), and ECLSSSizing().
Referenced by ECLSSSizing().
EffPw()
function EffPw (in tauRise, in tauFall, in pulsewidth, in tauMax)
 If pulsewidth is not entered, it will use a range from 0.02 to 1 sec.
 If tauMax is not entered it will assume an infinite control period.
 Since version 1.
Form
 effPw = EffPw( tauRise, tauFall, pulsewidth, tauMax )
Inputs
 tauRise          (1,1) Rise time constant
 tauFall          (1,1) Fall time constant
 pulsewidth       (1,:) Pulsewidths
 tauMax           (1,1) Control period
Outputs
 effPw            (1,:) Effective pulsewidth
References abs(), and(), isempty(), LeastSq(), and Plot2D().
Referenced by NPSPM().
ElementsPlugIn()
function ElementsPlugIn (in action, in modifier, in hFig, in position, in callback)
Form
 x =  ElementsPlugIn( action, modifier, hFig, position, callback )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifer     (1,:)  Modifier to the action or data structure if intialization
 hFig        (1,1)  Handle to the figure or if 'update' radio button handles
 position    (1,4)  [left bottom width height]
 callback    (1,:)  Callback string when something has changed in this gui
Outputs
 x           (1,1)  The tag if action is 'initialize'
References Initialize().
EnergyPerRing()
function EnergyPerRing (in w, in x)
Gives the energy per ring and diameter of each ring for a diffraction limited circular aperture.
 The default telescope data is for the Corning OCA Star Camera.
Form
 [e, d] = EnergyPerRing( w, x )
Inputs
 w             (1,:)   wavelength (default is visible spectrum)
 x             (:)     .focalLength (1,1) focal length
                       .aperture    (1,1) aperture diameter
Outputs
 e             (1,4)    Energy per ring (fraction)
 d             (1,4)    Diameter
References: Kayton, M. and W. R. Fried, "Avionics Navigation Systems. Second Edition." Wiley. pp. 565-566.
References and(), Energy(), isempty(), length(), Plot2D(), Ring(), and Wavelength().
EOfE()
function EOfE (in T)
 Since version 1.
Form
 [e, eps0, epsT, deltaPsi, deltaEps] = EOfE( T )
Inputs
 T           (1,1) Julian centuries of 86400s dynamical time from j2000.0
Outputs
 e           (1,1) Equation of the equinoxes (deg)
 eps0        (1,1) Mean obliquity     (deg)
 epsT        (1,1) True obliquity     (deg)
 deltaPsi    (1,1) Delta in longitude (deg)
 deltaEps    (1,1) Delta in obliquity (deg)
References: The Astronomical Almanac for the Year 1993, U.S. Government Printing Office, 1993, p. B6.
References CosD(), Date2JD(), JD2T(), NutDelta(), and ObOfE().
Referenced by EarthRot(), and GASTime().
EquatorialToGalactic()
function EquatorialToGalactic ()
 Since version 10.
Form
 m = EquatorialToGalactic
Inputs
Outputs
 m        (3,3)  ECI to Galactic
References EquatorialToGalactic().
Referenced by EquatorialToGalactic().
ESA()
function ESA (in qIToB, in uBS, in uPitch, in nadir, in limit, in noise)
 This generates roll and pitch angles based on the angle between the
 boresight and nadir. It does not model the physical mechanisms in earth
 sensors.
 Since version 1.
Form
 [roll, pitch] = ESA( qIToB, uBS, uPitch, nadir, limit, noise )
Inputs
 qIToB       (4,1)  Quaternion from the inertial to the body frame
 uBS         (3,1)  Boresight unit vector
 uPitch      (3,1)  Pitch Axis unit vector
 nadir       (3,1)  Nadir vector (ECI)
 limit       (2,1)  [roll;pitch] limits (rad)
 noise       (2,1)  [roll;pitch] noise (rad)
Outputs
 roll               Roll angle
 pitch              Pitch angle
References abs(), and(), Cross(), isempty(), Nadir(), QForm(), Unit(), and vector().
Referenced by PowerDesign().
ESAChord()
function ESAChord (in rho, in delta, in roll)
 Will plot dW versus roll if there are no outputs.
 Will automatically set scans off the earth to zero.
Form
 dW = ESAChord( rho, delta, roll )
Inputs
 rho        (1,1)  Earth angular width (rad)
 delta      (1,1)  Scan cant angle (must be less than rho) (rad)
 roll       (:)    Roll angle (rad)
Outputs
 dW         (1,:)  Delta earth chord (rad)
References abs(), and(), isempty(), Plot2D(), set(), and zeros().
ESACS()
function ESACS (in qIToB, in rNadir, in u, in cant, in pitchAxis, in refAxis, in noise, in quant)
 The noise is added to the chordwidth and dihedral angle outputs. If the
 scan is off the earth both are output as zero and the noTarget flag is
 set to 1. The output is discretized only if quant is provided.
 Since version 1.
Form
 [chordWidth, dihedralAngle, noTarget] = ESACS( qIToB, rNadir, u, cant, pitchAxis, refAxis, noise, quant )
Inputs
 qIToB         (4,1)  Quaternion from the inertial to the body frame
 rNadir        (3,1)  Nadir vector in the inertial frame (km)
 u             (3,1)  Sensor spin-axis
 cant          (1,1)  Sensor element cant angle from the spin-axis (rad)
 pitchAxis     (1,1)  Pitch axis (1, 2 or 3 )*              Default == 2
 refAxis       (1,1)  Reference axis for pitch (1, 2 or 3)* Default == 3
 noise         (1,1)  Noise 1 sigma*                        Default == 0
 quant         (1,1)  Quantization*                      Default is none
Outputs
 chordwidth    (1,1)  Measured chordwidth, or counts
 dihedralAngle (1,1)  Measured dihedral angle, or counts
 noTarget      (1,1)  1 = off the earth, 0 = on the earth
References abs(), and(), isempty(), Nadir(), QForm(), set(), vector(), and zeros().
FAeroSurfaceAccommodation()
function FAeroSurfaceAccommodation (in u, in rho, in t, in m, in d, in sigmaN, in sigmaT)
User inputs a data structure specifying a set of planar areas. The coefficients may be scalars, a function, or provided by a built-in function which is a fit to experimental data for N2 on aluminum (Fredo).
A coefficient function should have the form:
 [sigmaN,sigmaT] = FCoeff( cosAlpha )
where cosAlpha is the dot product of the velocity vector and the area normal vector. The sign convention is for outward normals and velocity is that of the spacecraft or object.
Form
 FAeroSurfaceAccommodation; % demo of a cube
 [f,cD,cL] = FAeroSurfaceAccommodation( u, rho, t, m, d ) % built-in
 [f,cD,cL] = FAeroSurfaceAccommodation( u, rho, t, m, d, sigmaN, sigmaT )
 [f,cD,cL] = FAeroSurfaceAccommodation( u, rho, t, m, d, fSigma )
Inputs
 u              (3,:)  Velocity vector (m/sec)
 rho            (1,1)  Atmospheric Density (kg/m^3)
 t              (1,1)  Atmospheric Temperature (K)
 m              (1,1)  Mean molecular weight (kg/mol)
 d               (.)   Plate data structure
                        .area        (1,:) Areas
                        .normal      (3,:) Normals
                        .temperature (1,:) Temperatures
 sigmaN        (1,1)   Normal coefficient
 sigmaT        (1,1)   Tangential coefficient
   -- or --
 fSigma        (*)     Function handle, optional
Outputs
 force          (3,1)  Total force (N)
 cD             (1,1)  Equivalent coefficent of drag
 cL             (1,1)  Equivalent coefficent of lift
 f              (3,:)  Element forces
References: Richard Michael Fredo, "A Numerical Procedure for Calculating the Aerodynamic Coefficients for Complex Spacecraft Configurations in Free-Molecular Flow," Pennsylvania State University, Masters thesis, 1980.
 Fredo and Kaplan, "Procedure for Obtaining Aerodynamic
 Properties of Spacecraft," J. Spacecraft Vol. 18 No. 4,
 July-August 1981.
See also
FAeroSurfaceAccommodation>AccommodationCoefficients
References AccommodationCoefficients(), and(), Demo(), DupVect(), FAeroSurfaceAccommodation(), length(), Mag(), MolWt2R(), Normal(), Plot2D(), set(), Unit(), vector(), and zeros().
Referenced by Disturbances(), and FAeroSurfaceAccommodation().
FAKM()
function FAKM (in x, in t, in inr, in inrDot, in mRDot, in hMWA, in inrDamper, in cDamper, in uDamper, in tAKM, in tBurn)
 Since version 1.
Form
 xDot = FAKM( x, t, inr, inrDot, mRDot, hMWA, inrDamper, cDamper, uDamper, tAKM, tBurn )
Inputs
 x            (8,1)     The state vector
 t            (1,1)     Time
 inr          (3,3)     Inertia
 inrDot       (3,3)     Inertia derivative
 mRDot        (3,3)     Jet damping term
 hMWA         (3,1)     Wheel momentum vector
 inrDamper    (1,1)     Damper wheel inertia
 cDamper      (1,1)     Damper damping coefficient
 uDamper      (3,1)     Damper unit vector
 tAKM         (3,1)     AKM torque
 tBurn        (1,1)     Burn duration
Outputs
 xDot         (8,1)     The derivative of the state state vector
References Cross(), QIToBDot(), vector(), and zeros().
FDC()
function FDC (in x, in t, in fDyn, in fConstraint, in dynData, in constData, in penalty, in nIts)
 [M, Q] = fDyn( x, t, dynData );
 [phi, phiQ, phiTDot, phiDot, phiQDot] = fConstraint( x, t, constData )
 2    2
 The equations of motion are   M d x/dt  = Q
 The constraints are                phi  = 0
If nIts > 0 it will use the iterative formulation.
 Since version 2.
Form
 xDot = FDC( x, t, fDyn, fConstraint, dynData, constData, penalty, nIts )
Inputs
 x            (:,1)     The state vector [x;xDot]
 t                      Time
 fDyn         (1,:)     Name of the dynamics function
 fConstraint  (1,:)     Name of the constraint function
 dynData      (:,:)     Data to be passed to the dynamics function
 constData    (:,:)     Data to be passed to the constraint function
 penalty      (1,3)     Penalty function scalars [alpha, mu, omega]
 nIts         (1,1)     Number of iterations
Outputs
 xDot         (:,1)     The derivative of the state vector
References length(), and vector().
FGravityGradientStiffness()
function FGravityGradientStiffness (in x, in ignoredArg, in inertia, in orbitRate)
 The spacecraft is aligned with LVLH with orbit rate is about the -y axis.
 This model is valid only for small angles about LVLH.
Form
 [xDot, tGG] = FGravityGradientStiffness( x, t, inertia, orbitRate )
Inputs
 x          (6,1)  [roll;pitch;yaw;xRate;yRate;zRate]
 t          (1,1)  Time (not used)
 inertia    (3,3)  Inertia matrix
 orbitRate  (:,1)  Orbit rate may be a scalar or vector
Outputs
 xDot       (6,1)  State derivative
 tGG        (3,1)  Gravity gradient torque
References Cross(), length(), Mag(), scalar(), Skew(), and vector().
Referenced by GravityGradientStiffness().
FGs()
function FGs (in x, in t, in inr, in invInr, in torque, in inrWheel, in uWheel, in tWheel, in cDamp)
See also
GSModel.
Form
 xDot = FGs( x, t, inr, invInr, torque, inrWheel, uWheel, tWheel, cDamp )
Inputs
 x            (7+n,1)   The state vector
 t                      Time
 inr          (  3,3)   Inertia
 invInr       (  3,3)   Inverse inertia
 torque       (  3,1)   External torque
 inrWheel     (  1,n)   Wheel inertia
 uWheel       (  3,n)   Wheel unit vectors
 tWheel       (  1,n)   Wheel control torque
 cDamp        (  1,n)   Damping coefficient
Outputs
 xDot         (7+n,1)     The derivative of the state vector
References GSModel(), length(), QIToBDot(), and vector().
Referenced by DST(), and RHSGyrostat().
FIC()
function FIC (in q, in ignoredArg, in m1, in m2, in L, in g)
q are angles.
Form
 qDot = FIC( q, t, m1, m2, L, g )
Inputs
 q            (4,1)     The state vector [q1;q2;q1Dot;q2Dot]
 t            (1,1)     Time
 m1           (1,1)     Mass 1
 m2           (1,1)     Mass 2
 L            (1,1)     Pendulum length
 g            (1,1)     Acceleration of gravity
Outputs
 qDot         (4,1)     The derivative of the state vector
References length(), and vector().
FICP()
function FICP (in q, in ignoredArg, in L, in g)
Form
 qDot = FICP( q, t, L, g )
Inputs
 q            (2,1)     The state vector [q;qDot]
 t            (1,1)     Time
 L            (1,1)     Pendulum length
 g            (1,1)     Acceleration of gravity
Outputs
 qDot         (2,1)     The derivative of the state vector
References length(), and vector().
FloatToWord()
function FloatToWord (in f, in kMax, in kMin, in resolution)
 Numbers are assumed to be in standard integer format with kMax <= k <= kMax.
Form
 k = FloatToWord( f, kMax, kMin, resolution )
Inputs
 f            (:)    Floating point value
 kMax          (1,1)  Maximum integer
 kMin          (1,1)  Minimum integer
 resolution    (1,1)  Floating point value of a 1.
Outputs
 k            (:)    Integer
Referenced by RWA(), and RWABristle().
FMagSim()
function FMagSim (in x, in ignoredArg, in inr, in invInr, in tExt, in inrW, in uW, in tW, in ignoredArg)
Used by FMagSim2 and FMagSimWithEstimator.
Form
 xDot = FMagSim( x, t, inr, invInr, tExt, inrW, uW, tW, eSAC )
Inputs
 x            (8,1)     The state vector [q;w;wW]
 t            (1,1)     Time (unused)
 inr          (3,3)     Inertia
 invInr       (3,3)     Inverse inertia
 tExt         (3,1)     External torque
 inrW         (1,1)     RWA inertia
 uW           (3,1)     RWA unit vector
 tW           (1,1)     RWA torque
Outputs
 xDot         (15,1)    The derivative of the state vector
See also
QIToBDot, GSModel
References and(), GSModel(), QIToBDot(), RWA(), and vector().
FP2RADec()
function FP2RADec (in rAC, in decC, in x, in y, in f)
If no outputs are specified it will create a 3D plot of the unit vectors for the inputs. In the focal plane the vectors x = [0;1;0] and y = [sin(decC);0;-cos(decC)] define the sysstem of coordinates that is used to measure the plate and which is oriented North-SOutha and East-West.
Form
 [ra, dec] = FP2RADec( rAC, decC, x, y, f )
Inputs
 rAC       (1,1)   Right ascension of the camera axis (rad)
 decC      (1,1)   Declination of the camera axis (rad)
 x         (n)     X coordinate
 y         (n)     Y Coordinate
 f         (1,1)   Focal length
Outputs
 rA         (n)    Right ascension ( 0 to 2*pi) (rad)
 dec        (n)    Declination (rad)
References: Montenbruck, O. and T. Fleger, "Astronomy on the Personal Computer", Spring-Verlag, 1994, p 255.
References and(), FP2RADec(), length(), Map(), NewFig(), RaDec2U(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by FP2RADec().
FPB()
function FPB (in theta, in rho, in sig1, in sig2, in f)
 Since version 1.
Form
 y = FPB( theta, rho, sig1, sig2, f )
Inputs
 theta          (1,:)   Angle
 rho            (1,1)   Correlation
 sig1           (1,1)   Standard deviation
 sig2           (1,1)   Standard deviation
 f              (1,1)   Coefficient of exponent term
Outputs
 y              (1,:)   Output
FPivot()
function FPivot (in x, in ignoredArg, in jW, in jP, in iS, in tS, in tW, in tP, in uW, in uP)
Form
 xDot = FPivot( x, t, jW, jP, iS, tS, tW, tP, uW, uP )
Inputs
 x           (10,1)  State vector [q;theta;w(3,1);wP;wW]
 t           (1,1)   Time (Unused)
 jW          (3,3)   Wheel inertia (must be symmetric)
 jP          (3,3)   Pivot assembly inertia
 iS          (3,3)   Spacecraft inertia
 tS          (3,1)   Body torque
 tW          (1,1)   Wheel torque
 tP          (1,1)   Pivot torque
 uW          (3,1)   Wheel axis
 uP          (3,1)   Pivot axis
Outputs
 xDot        (10,1)  Time derivative
References QIToBDot(), SCwPivot(), and vector().
FPSensors()
function FPSensors (in qECIToB, in qBToS, in catalog, in fov, in fScale)
Just checks the field-of-view and projects it into the focal plane. The focal plane is always the xy-plane of the sensor.
Form
 sensorData = FPSensors( qECIToB, qBToS, catalog, fov, fScale )
Inputs
 qECIToB      (4,1)     Quaternion from body to ECI axes
 qBToS        (4,:)     Quaternion from body to sensor axes
 catalog      (3,:)     Target catalog u.
 fov          (1,1)     Square field-of-view
 fScale       (1,1)     Sensor scale factor
Outputs
 sensorData   (:)       Structure
                        .xy    Pixel values in the xy focal plane
                        .valid 1 = valid measurement
References abs(), and(), QForm(), QMult(), Square(), U2Pix(), and Unit().
FRB()
function FRB (in x, in ignoredArg, in inr, in invInr, in tExt)
Form
 xDot = FRB( x, t, inr, invInr, tExt )
Inputs
 x            (7,1)     The state vector [q;w]
 t            (1,1)     Time (unused)
 inr          (3,3)     Inertia
 invInr       (3,3)     Inverse inertia
 tExt         (3,1)     External torque
Outputs
 xDot         (7,1)     The derivative of the state vector
See also
RBModel
References QIToBDot(), RBModel(), and vector().
Referenced by AttitudeControlSimRWA(), FSailRB(), SpinChange(), and SPMMnvr().
FRBWithMag()
function FRBWithMag (in x, in ignoredArg, in d)
Models a point-mass orbit. This function is called by RK4. See also MagneticControlSim.
Form
 xDot = FRBWithMag( x, t, d )
Inputs
 x            (13,1)    The state vector [r;v;q;w]
 t                      Time
 d             (.)      Data structure
                        .mu     (1,1) Gravitational parameter
                        .inr    (3,3) Inertia
                        .invInr (3,3) Inverse inertia
                        .tExt   (3,1) External torque
                        .bECI   (3,1) Magnetic field in ECI frame
                        .dipole (3,1) Magnetic dipole in spacecraft frame
Outputs
 xDot         (13,1)    The derivative of the state vector
References Constant(), Cross(), Mag(), plus(), QForm(), QIToBDot(), quaternion(), RBModel(), RK4(), and vector().
Friction()
function Friction (in tC, in w, in c, in wC, in d)
 t = -(sign(w)*tC*(1 - exp(-abs(w)/wC)) + c*w + sign(w)*d*w^2)
 The exponential term prevents jitter due to finite integration time steps.
 Since version 2.
Form
 t = Friction( tC, w, c, wC, d )
Inputs
 tC       (n,1)   Coulomb friction
 w         (n,:)   Angular rates
 c         (n,1)   Viscous friction coefficient
 wC        (n,1)   Low frequency cutoff
 d         (n,1)   Turbulent damping
Outputs
 t         (n,:)   Torque
References Friction().
Referenced by AutomobileLaneChange(), AutomobilePassing(), BLDCMFriction(), CDSkinFriction(), Friction(), FrictionBristle(), FrictionLaminar(), FrictionSmooth(), FSRHS(), PrandtlNikuradse(), ReactionWheelFriction(), ReluctanceMachineRHS(), ReluctanceMachineRHS(), RHSAutomobile(), RHSFriction(), RHSGyrostat(), RHSReactionWheel(), RHSReactionWheelWithOrbit(), RHSRobot(), RHSRobotInitialize(), RHSRWAOrbit(), and RHSSpacecraftWithRWA().
FrictionBristle()
function FrictionBristle (in z, in t, in d)
This model uses a bristle state.
 F    = sigma0*z + sigma1*zDot + sigma2*v
 zDot = v - |v|*z/g(v)
 g(v) = (fC + (fS - fC)*exp(-(v/vS)^2))/sigma0;
 The maximum damping coefficient |v|/g(v) is an input. This prevents
 numerical instabilities. When the damping coefficient is set to the
 maximum value and
 zDot = max(|v|/g(v))*(zSS - z)
 so it damps to the equilibrium value which is
 zSS = sign(v)*g(v)/sigma0
 The maximum damping constant should be set to a number that is
 consistent with the time step. For example: 1/dT.
Form
 [zDot, f, cDamp] = FrictionBristle( z, t, d )
Inputs
 z            (:)     State
 t       (1,1)   Time (not used)
 d            (:)     Data structure
                 .v         - velocity
                 .fStatic   - Static friction
                 .fCoulomb  - Coulomb friction maximum
                 .vStribeck - Stribeck velocity
                 .sigma0    - Bristle stiffness
                 .sigma1    - Bristle damping
                 .sigma2    - Viscous friction coefficient
                 .maxC      - Maximum damping constant
Outputs
 zDot          (:)    Bristle state derivative
 f             (:)    Friction
 cDamp         (:)    The damping coefficient
References abs(), and(), Friction(), length(), set(), and zeros().
Referenced by ReactionWheel(), RHSFriction(), RWABristle(), and RWASmart().
FrictionSmooth()
function FrictionSmooth (in x, in d)
This model uses functions that are differentiable making it suitable for numerical simulations.
Form
 f = FrictionSmooth;
 f = FrictionSmooth( x, d )
Inputs
 x             (:)     Rates
 d             (:)     .fStatic   - Static friction maximum
                       .kStatic   - Static friction scaling coefficient
                       .fCoulomb  - Coulomb friction maximum
                       .kCoulomb  - Coulomb friction scaling coefficient
                                      (higher means a faster rise)
                       .bViscous  - Viscous friction coefficient
Outputs
 f             (:)    Friction
See also
RWA.m and SmoothFrictionDemo.
References and(), Friction(), FrictionSmooth(), length(), Plot2D(), and RWA().
Referenced by FrictionSmooth(), FSRHS(), and RWA().
FRWA()
function FRWA (in x, in ignoredArg)
Form
 xDot = FRWA( x, t )
Inputs
 x            (1,1)     The state vector
 t            (1,1)     Time
Outputs
 xDot         (1,1)    The derivative of the state vector
References get(), RWA(), and vector().
FRWABristle()
function FRWABristle (in x, in ignoredArg)
Form
 x = FRWABristle( x, t )
Inputs
 x        (2,1)  [omega;bristle state]
 t      (1,1)  Time (unused)
Outputs
 xDot       (2,1)    Output
References get(), RWA(), and RWABristle().
FRY()
function FRY (in x, in ignoredArg, in d)
Form
 xDot = FRY( x, t, d )
Inputs
 x            (3,1)   Input [roll; yaw; roll rate]
 t            (1,1)   Time
 d            (:)     .h   momentum
                .wo  orbit rate
Outputs
 xDot       (3,1)   State derivative
 d            (:)     .h   momentum
                       .wo  orbit rate
References RHS().
FRYSim()
function FRYSim (in x, in ignoredArg, in d)
Form
 xDot = FRYSim( x, t, d )
Inputs
 x            (2,1)   Input [roll;yaw] (rad)
 t            (1,1)   Time (not used)
 d            (:)     .h  (1,1) momentum
                 .wo (1,1) orbit rate
                 .tX (1,1) Roll torque
                    .tZ (1,1) Yaw torque
Outputs
 xDot         (2,1)   State derivative
FSDG()
function FSDG (in x, in t, in u, in h, in cD, in k, in kF, in w, in bias, in nU, in nV, in nE)
Form
 xDot = FSDG( x, t, u, h, cD, k, kF, w, bias, nU, nV, nE )
Inputs
 x            (3n,1)    State vector [Random Walk
                                      Integral of inputs
                                      Integral of outputs]
 t                      Time (not used)
 u            (3,n)     Gyro unit vectors
 h            (1,n)     Angular momentum
 cD           (1,n)     Damping
 k            (1,n)     Forward gain
 kF           (1,n)     Torque rebalance gain
 w            (3,1)     Input rate vector
 bias         (1,n)     Biases
 nU           (1,n)     Bias drift noise
 nV           (1,n)     Rate noise
 nE           (1,n)     Output noise
Outputs
 xDot         (3n,1)     The derivative of the state vector
References Gyro(), Integral(), Random(), SDG(), and vector().
FSolstice()
function FSolstice (in jD, in type)
 Used by FindSolsticeOrEquinox.
Form
 y = FSolstice( jD, type )
Inputs
 jD        (1,1)  Julian Date
 type      (1,:)  'fall equinox', 'winter solstice'
                  'spring equinox', 'summer solstice'
Outputs
 y         (1,:)  Output to be minimized
References FindSolsticeOrEquinox(), RHS(), and SunV1().
Referenced by FindSolsticeOrEquinox().
FSRHS()
function FSRHS (in x, in t, in d)
Form
 xDot = FSRHS( x, t, d )
Inputs
 x           (1,1)  State See Friction Smooth
 t           (1,1)  Timed
 d           (1,1)  Smooth friction parameters See Friction Smooth
Outputs
 xDot        (1,1)   Derivative
References Friction(), FrictionSmooth(), and RHS().
FTB()
function FTB (in x, in ignoredArg, in r0, in r1, in lam1, in iner0, in iner1, in m0, in m1, in torque, in force, in iAxis)
 This calls the two body dynamics model, TBModel. It is usually called by a
 numerical integration routine.
See also
TBModel.
Form
 xDot = FTB( x, t, r0, r1, lam1, iner0, iner1, m0, m1, torque, force, iAxis )
Inputs
 x            (14,1)    The state vector [q0;q0to1;w0;w1;....]
 t            (1,1)     The time vector
 r0           (3,1)     The vector from the origin to the body 0 cm in the body 0 frame
 r1           (3,1)     The vector from the origin to the hinge in the body 0 frame
 lam1         (3,1)     The vector from the hinge to the body 1 cm in the body 1 frame
 iner0        (3,3)     The body 0 inertia in the body 0 frame
 iner1        (3,3)     The body 1 inertia in the body 1 frame
 m0                     The body 0 mass
 m1                     The body 1 mass
 torque       (6,1)     [totalExternalTorque(3); hingeTorque(3)]
 force        (6,1)     [body0ExternalForce(3); body1ExternalForce(3)] at their cms
 iAxis        (1,:)     The axes of the second body that are not constrained.
Outputs
 xDot         (14,1)    The derivative of the state vector
References length(), QIToBDot(), TBModel(), vector(), and zeros().
Referenced by FSailTB().
FTBRef()
function FTBRef (in x, in ignoredArg, in tBDS)
Form
 xDot = FTBRef( x, t, tBDS )
Inputs
 t         (1,1)    Time
 xDot      (14,1)   State
 tBDS      (:)      Two body data structure see TBModel
Outputs
 xDot      (14,1)   State derivative
References QIToBDot(), quaternion(), TBModel(), vector(), and zeros().
FXModel()
function FXModel (in inr, in h, in wo, in m, in r, in wF, in zF, in fT, in mT, in v, in x)
 Computes the state space description of a spacecraft
 with two flexible appendages where the internal momentum is fixed.
 If dT is not input it returns the continuous time plant.
 If dT is input it returns the discrete time plant.
 In either case, the plant is linearized.
 The state vector is
 [thetax;thetay;thetaz;x1;...xN;omegax;omegay;omegaz;v1;...vN]
 Where the state vector is with respect to the rotating frame
 defined by wo.
 The outputs are the angles, i.e. the first three elements in the
 state vector. The flex model is in the physical frame with each
 mass having a vector stiffness and damping
 If h and wo are not in the same direction or inr is not diagonal,
 dxdt will be nonzero and you will get constant disturbance torques.
 If only one output is specified it gives the right hand side
 of the nonlinear dynamical equations of motion. You need to use
 the kinematics routines to get the nonlinear kinematics equations.
 Since version 1.
Form
 [a,b,c,d,dxdt] = FXModel(inr,h,wo,m,r,wF,zF)
 [a,b,c,d,dxdt] = FXModel(inr,h,wo,m,r,wF,zF,dT)
 [wDot]         = FXModel(inr,h,w,m,r,wF,zF,fT,mT,v,x)
Inputs
 inr           (3,3)          Inertia matrix
 h             (3,1)          Internal momentum vector
 wo            (3,1)          Orbit rate vector
 m             (1,n)          Mass of the flex masses
 r             (3,n)          Positions of the flex masses
 wF            (3,n)          Frequencies of the flex masses
 zF            (3,n)          Damping ratios of the flex masses
 dT            (1,1)          Sampling period
 or
 fT            (3,1)          Total external force on the spacecraft c.m.
 mT            (1,1)          Total spacecraft mass
 v             (3,n)          Flex mass velocity
 x             (3,n)          Flex mass position
Outputs
 a             (6+6*n,6+6*n)  Plant matrix
 b             (6+6*n,3)      Input matrix
 c             (3,6+6*n)      Output matrix
 d             (3,3)          Feedthrough matrix
 dxdt          (6+6*n,1)      Steady state derivative
 or
 wDot          (3,1)          State derivative of rates
References and(), C2DZOH(), get(), length(), SkewSymm(), vector(), and zeros().
GASTime()
function GASTime (in jD, in eOfECalc)
Form
 gAST = GASTime( jD, eOfECalc )
Inputs
 jD          (1,1) Julian date
 eOfECalc    (1,1) Calculate the equation of the equinoxes
Outputs
 gAST        (1,1) Earth angle for JD (deg)
References: Seidelmann, P. K., The Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992, p. 20.
References EOfE(), get(), GMSTime(), and JD2T().
Geo()
function Geo ()
 Returns the semi-major axis, period, orbital velocity and mean orbit rate.
 Since version 1.
Form
 [n, a, p, v] = Geo()
Inputs
 none
Outputs
 n             (1,1)   Mean orbit rate
 a             (1,1)   Semi-major axis
 p             (1,1)   Period in seconds
 v             (1,1)   Velocity
References and(), and Period().
Referenced by DVGeoTrx().
GeoEclps()
function GeoEclps (in alpha, in beta, in dEarth)
Form
 [n, eclipseType] = GeoEclps( alpha, beta, dEarth )
Inputs
 alpha          (1,1)  Angle in the orbit plane between the sun and
                       the spacecraft ( 0 to 2 pi radians )
 beta           (1,1)  Angle between the sun vector and the orbit
                       plane ( -0.409 < beta < 0.409 radians for
                       zero inclination )
 dEarth         (1,1)  Distance to the earth. If not entered assumes 42167 km
Outputs
 n              (1,1)  Normalized sun intensity ( 0 < n < 1 )
 eclipseType    (1,1)  0 = none, 1 = partial, 2 = annular, 3 = total
References abs(), and(), Demo(), Eclipse(), GeoEclps(), and vector().
Referenced by GeoEclps().
GetFlex()
function GetFlex (in file, in path, in name)
The flex data is in the following format. The inertia and rotational modes are optional. If the inertia is not included it will ignore PhiQX, PhiQY and PhiQz if they are present. See also LoadFlex.
 # Nodes
 NodeID rX rY rZ mass inertia     (one line for each node, inertia is [ixx iyy izz ixy ixz iyz])
 ModeID omega                     (one line for each mode)
 NodeID PhiX PhiY PhiZ PhiQX PhiQY PhQiZ (one block for each mode and within each block
 one line for each node)
Form
 g = GetFlex( file, path, name )
Inputs
 file    (:)    File names
 path           Name of path
 name    (1,:)  Name of model
Outputs
 g      (:)     Flex model data structure
                .name   (1,:)   Name of the component
                .nNodes (1,1)   Number of nodes
                .nModes (1,1)   Number of modes
                .node   (n)     Node data structure
                                .r       (3,1)  Location of each node
                                                with respect to the origin
                                .mass    (1,1)  Mass of each node
                                .inertia (3,3)  Inertia of each node
                                .nodeID  (1,1)  Node id
                .mode   (m)     Mode data structure
                                .modeID  (1,1)  Mode id
                                .phi     (6,n)  x = phi*eta where
                                                eta is the mode displacement
                                .omega   (1,1)  Modal frequency
References and(), GetFlex(), isempty(), length(), LoadFlex(), PlotFlex(), and zeros().
Referenced by AC(), GetFlex(), and PlotFlex().
GetModes()
function GetModes (in phi, in omega, in useModes, in nNodes)
 The transformation matrix Phi is organized as
 [3-by-nNodes mode 1,3-by-nNodes mode 2,...]
 Since version 1.
Form
 [phiTrunc, omega] = GetModes( phi, omega, useModes, nNodes )
Inputs
 phi              (3,n*m) Nodal displacements per modal displacement
 omega            (m)     Modal frequencies
 useModes         (1,:)   Modes to use
 nNodes           (1,1)   Number of nodes
Outputs
 phiTrunc         (3,n*:) Nodal displacements per modal displacement
 omega            (m)     Modal frequencies
References length().
GimbalC()
function GimbalC (in a, in b, in c, in d, in psInv, in x, in att)
 Requires two thrusters with double gimbals.
Form
 [u, x, y] = GimbalC( a, b, c, d, psInv, x, att )
Inputs
 a             (n,n) Three axis controller plant matrix in delta form, x = x + a*x
 b             (n,3) Three axis controller input matrix
 c             (3,n) Three axis controller output matrix
 d             (3,3) Three axis controller feedthrough matrix
 psInv         (2,3) Pseudoinverse to convert torque to angle
 x             (n,1) Controller state
 att           (3,1) Attitude errors
Outputs
 u             (2,1) Gimbal commands
 x             (n,1) Controller state
 y             (3,1) Torque command
References and().
Glitch()
function Glitch (in b, in bMax, in ifLT)
If bMax is omitted it will look for zeros. It linearly interpolates gaps with glitch data using the valid values on the edges of the glitch regions.
Form
 bD = Glitch( b, bMax, ifLT )
Inputs
 b                (:,:)   Data to be deglitched
 bMax             (1,1)   Threshold indicating bad data   > bMax
 ifLT             (1,1)   Any argument will have it check < bMax
Outputs
 bD               (:,:)   Deglitched data
References isempty(), length(), and zeros().
Referenced by LoadMag(), and Weather().
GMSTime()
function GMSTime (in jd)
 This is the angle between the Greenwich Meridian and the Vernal Equinox.
 Since version 1.
Form
 gmst = GMSTime( jd )
Inputs
 jd              (1,1)   Julian date UT (day)
Outputs
 gmst            (1,1)   Greenwich mean sidereal time (deg)
References: The Astronomical Almanac for the Year 1993, U.S. Government Printing Office, 1993, p. B6.
References and(), Date2JD(), JDToMidnight(), Limit(), and MSidDay().
Referenced by EarthRot(), GASTime(), LaunchTime(), and OrbitalPlane().
GOESLeg()
function GOESLeg (in l, in box, in hK)
 Since version 3.
Form
 GOESLeg( l, box, hK )
Inputs
 l               (n,:)    Text strings
 box             (1,4)    Where the legend should fit
 hK              (1,n)    Handles to the lines
Outputs
 none
References and(), get(), GOESLeg(), length(), set(), and zeros().
Referenced by GOESLeg().
GOESLon()
function GOESLon (in sc, in dateTime, in file)
See also
LoadSatP.
 Since version 3.
Form
 l = GOESLon( sc, dateTime, file )
Inputs
 sc               (1,1)   GOES spacecraft ID
 dateTime         (1,6)   [year month day hour minute second]
 file             (1,:)   File name for position data
Outputs
 l                (1,1)   Longitude
References Date2JD(), GOESLon(), and LoadSatP().
Referenced by GOESLon(), and Weather().
GPSOrbit()
function GPSOrbit (in d, in t)
 The input data structure is data found in the GPS navigation message.
 The GPS message has 5 subframes. The first contains the GPS week number,
 a prediction of  the user range accuracy, indicators of satellite health
 and of the age of the data, an estimation of ths signal group delay, the
 clock reference time and three coefficients for a quadratic polynomial
 to model the satellite clock correction.
 Each subframe consists of 10 30 bit words. Each has a header with the
 telemetry word containing a synchronization pattern, and diagnostic
 messages. The second word is the handover word containing the
 time-of-week count for the epoch at the start of the next subframe.
 The time-of-week count is a multiple of 1.5 second intervals since the
 beginning of the current GPS week.
 The second and third subframes transmit the broadcast ephemerides used in
 this function.
 It takes 30 seconds to transmit all five subframes, thus the broadcast
 ephemerides are updated every 30 seconds.
 The fourth and fifth subframes are change every message and have a
 repetition rate of 25. Thus the total information takes 25 pages. The
 fourth and fifth subframes contain the low-precision almanac for all of
 the satellites in the GPS constellation. Thus every 12.5 minutes the
 satellite gets an update for all 24 GPS satellites.
 This routine can handle either the broadcast ephemerides or almanac.
 The almanac angles are in semicircles (e.g. 0.1 = 18 deg.)
Form
 [r, v, delta] = GPSOrbit( d, t )
Inputs
 d              (1,1)  GPS Ephemerides
                       .tC       (1,1) Satellite clock reference epoch
                       .a0       (1,1) Satellite clock offset
                       .a1       (1,1) Satellite clock drift
                       .a2       (1,1) Satellite clock frequency drift
                       .tE       (1,1) Ephemerides reference epoch
                       .t0       (1,1) Sidereal time reference epoch
                       .e        (1,1) Eccentricity
                       .sqrtA    (1,1) Square root of semimajor axis (sqrt(m))
                       .m0       (1,1) Mean anomaly at reference epoch (rad)
                       .w0       (1,1) Argument of perigee (rad)
                       .i0       (1,1) Inclination (rad)
                       .l0       (1,1) Longitude of the node at the weekly epoch  (rad)
                       .deltaN   (1,1) Mean motion difference
                       .iDot     (1,1) Rate of inclination angle (rad/s)
                       .omegaDot (1,1) Rate of note's right ascension
                       .cUC      (1,1) Correction coefficient (argument of perigee)
                       .cUS      (1,1) Correction coefficient (argument of perigee)
                       .cRC      (1,1) Correction coefficient (radius)
                       .cRS      (1,1) Correction coefficient (radius)
                       .cIC      (1,1) Correction coefficient (inclination)
                       .cIS      (1,1) Correction coefficient (inclination)
 or
 d              (1,1)  GPS Almanac
 .e        (1,1) Eccentricity
 .tA       (1,1) Ephemerides reference epoch
 .t0       (1,1) Sidereal time reference epoch
 .sqrtA    (1,1) Square root of semimajor axis (sqrt(m))
 .m0       (1,1) Mean anomaly at reference epoch (semicircles)
 .w        (1,1) Argument of perigee (semicircles)
 .deltaI   (1,1) Inclination delta (semicircles)
 .l0       (1,1) Longitude of the node at the weekly epoch  (semicircles)
 .deltaN   (1,1) Mean motion difference
 .omegaDot (1,1) Rate of note's right ascension (semicircles/sec)
 .a0       (1,1) Satellite clock offset
 .a1       (1,1) Satellite clock drift
 t              (1,:)  Observation epoch (sec)
Outputs
 r              (3,:)  Earth-fixed Position vector (m)
 v              (3,:)  Earth-fixed Velocity vector (m/s)
 delta          (1,:)  Clock error
Reference: Hofmann-Wellenhof, B., Lichtenegger, H. and J. Collins, "GPS: Theory and Practice 4th Edition," Springer-Verlag.
References and(), CP2I(), length(), M2Nu(), Plot2D(), Square(), vector(), and zeros().
Referenced by GPSReceiverNav().
GPSReceiver()
function GPSReceiver (in action, in d)
Models the GPS constellation.
 The satellite locations are determined using GPSSatellite.
 The model can output a set of default data.
 Failure mode is zero output. The regular output is a structure:
 .rGPS        (3,n)   Position of GPS satellites in view
 .vGPS        (3,n)   Velocity of satellites
 .range       (1,n)   Range to the satellites (km)
 .rangeRate   (1,n)   Range rate (km/s)
 .iD          (1,n)   ID of satellites in view
 .nSatellites (1,1)   Number of satellites in view
See also
GPSReceiverNav.
Form
 y = GPSReceiver( action, d )
Inputs
 action      (1,:)     'initialize', 'update', 'output', 'set failure', or
                       'get default datastructure'
 d           (1,1)     Depends on the action
Outputs
 y           (1,1)     Depends on the action
References get(), GPSReceiverNav(), GPSSatellite(), and set().
GPSReceiverNav()
function GPSReceiverNav (in action, in d)
 Failure mode is zero output.
See also
GPSOrbit and RangeMeasurement.
Form
 y = GPSReceiverNav( action, d )
Inputs
 action      (1,:)     'initialize' 'update' 'output' 'set failure'
                       'get default datastructure'
 d           (1,1)     Depends on the action
Outputs
 y           (1,1)     Depends on the action
 The regular output is a structure:
 .rGPS        (3,n)   Position of GPS satellites in view
 .vGPS        (3,n)   Velocity of satellites
 .range       (1,n)   Range to the satellites (km)
 .rangeRate   (1,n)   Range rate (km/s)
 .iD          (1,n)   ID of satellites in view
 .nSatellites (1,1)   Number of satellites in view
 .message      (:)    GPS ephemeris message
References and(), get(), GPSOrbit(), and RangeMeasurement().
Referenced by GPSReceiver().
GPSSatellite()
function GPSSatellite (in jD, in coord)
Choice of Earth-fixed or ECI reference frames.
Type GPSSatellite for a demo.
 Forms:
 [r, v] = GPSSatellite( jD )
 [r, v] = GPSSatellite( jD, coord )
Inputs
 jD            (1,1)   Julian Date
 coord         (1,:)   'ef' or 'eci' (eci is the default)
Outputs
 r             (3,24)  Satellite locations
 v             (3,24)  Satellite velocity
Reference: Kayton, M. and W. R. Fried. (1997.) "Avionics Navigation Systems," John Wiley & Sons.
References and(), Axis3D(), CP2I(), Cross(), Date2JD(), EarthRte(), Equal(), GPSSatellite(), isempty(), JD2T(), Map(), NewFig(), OrbRate(), PlotPlanet(), RVFromKepler(), square(), TitleS(), TruEarth(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by GPSReceiver(), GPSSatellite(), and MeasGPS().
GravitationalConstantEarth()
function GravitationalConstantEarth ()
Form
 mu = GravitationalConstantEarth
Inputs
 None
Outputs
 mu  (1,1)  Earth's gravitational constant (km^3/s^2)
References GravitationalConstantEarth().
Referenced by GravitationalConstantEarth().
GravitationalTimeDilation()
function GravitationalTimeDilation (in mu, in r)
Form
 tR = GravitationalTimeDilation( mu, r )
Inputs
 mu             (1,1) Gravitational constant (m^3/s^2)
 r              (1,:) Position of observer
Outputs
 tR             (1,1) Ratio of proper time at r to proper time at infinity
Reference: http://en.wikipedia.org/wiki/Gravitational_time_dilation
References Demo(), GravitationalTimeDilation(), and TextS().
Referenced by GravitationalTimeDilation(), and RHSClockDrift().
GravityGradientAnalytical()
function GravityGradientAnalytical (in n, in iXX, in iYY, in iZZ)
r is along -z. This is only valid for a circular orbit.
Form
 [e, a] = GravityGradientAnalytical( n, iXX, iYY, iZZ )
Inputs
 n                  (1,1) Orbit rate
 iXX                (1,1) Ixx inertia term
 iYY                (1,1) Iyy inertia term
 iZZ                (1,1) Izz inertia term
Outputs
 e                  (6,1) Eigenvalues
 a                  (6,6) State matrix
References Demo(), eig(), and GravityGradientAnalytical().
Referenced by GravityGradientAnalytical().
GravityGradientBoom()
function GravityGradientBoom (in i0, in n, in r, in m)
Typically the boom needs to have a z and x component to get a gravity gradient stable configuration.
Type GravityGradientFrequency for a demo.
Form
 omega = GravityGradientBoom( i0, n, r, m )
Inputs
 i0 (3,3) Base inertia (kg-m^2)
 n      (1,1) Orbit Rate
 r   (3,:) Boom vector (m)
 m   (1,1) Masses (kg)
Outputs
 omega   (3,:) Gravity gradient frequencies (rad/s)
References and(), Demo(), Frequency(), get(), GravityGradientBoom(), GravityGradientFrequency(), Inertias(), Plot2D(), Skew(), vector(), and zeros().
Referenced by GravityGradientBoom().
GravityGradientEigenvalues()
function GravityGradientEigenvalues (in inr, in r, in v, in mu)
 We assume it is in the LVLH orientation.
Form
 [e, a] = GravityGradientEigenvalues( inr, r, v, mu )
Inputs
 inr                (3,3) Inertia matrix
 r                  (3,1) r in ECI
 v                  (3,1) v in ECI
 mu                 (1,1) Gravitational Parameter
Outputs
 e                  (6,1) Eigenvalues
 a                  (6,6) State matrix
References Cross(), Demo(), eig(), GravityGradientEigenvalues(), GravityGradientFromR(), Jacobian(), OmegaLVLH(), Parameter(), QForm(), QLVLH(), Sa2Q(), Skew(), and zeros().
Referenced by GravityGradientEigenvalues().
GravityGradientFrequency()
function GravityGradientFrequency (in inertia, in n)
The spacecraft is aligned with LVLH with orbit rate is about the -y axis. This model is valid only for small angles about LVLH. Computes it for the entire orbit.
Type GravityGradientFrequency for a demo.
Form
 [omega, e] = GravityGradientFrequency( inertia, n )
Inputs
 inertia    (3,3)  Inertia matrix (kg-m^2)
 n          (1,1)  Orbit Rate
Outputs
 omega   (3,:) Gravity gradient frequencies (rad/s)
 e       (6,:) Eigenvalues
References Demo(), eig(), Frequency(), GravityGradientFrequency(), length(), Period(), Plot2D(), Skew(), and zeros().
Referenced by GravityGradientBoom(), and GravityGradientFrequency().
GravityGradientFromR()
function GravityGradientFromR (in q, in inr, in r, in mu)
 q transforms from the frame in which r is defined to the body frame.
 Since version 10.
Form
 t = GravityGradientFromR( q, inr, r, mu )
Inputs
 q                  (4,1) Quaternion from the r frame to Body
 inr                (3,3) Inertia matrix
 r                  (3,:) Orbit from the earth to the spacecraft
                          in the spacecraft body frame (the same frame as
                          the inertia matrix.)
 mu                 (1,1) Gravitational Parameter
Outputs
 t                  (3,:) Torque (units will be consistent with inertia)
References and(), Constant(), Cross(), Demo(), GravityGradientFromR(), Mag(), Parameter(), Plot2D(), QForm(), Step(), and zeros().
Referenced by CubeSatDisturbanceAnalysis(), GravityGradientEigenvalues(), GravityGradientFromR(), PermanentMagnetRHS(), RHSCubeSat(), and RHSGGRotational().
GravityGradientStiffness()
function GravityGradientStiffness (in inertia, in orbitRate)
 This is equivalent to the spring constant.
Form
 s = GravityGradientStiffness( inertia, orbitRate )
Inputs
 inertia    (3,3)  Inertia matrix
 orbitRate  (1,1)  Orbit rate
Outputs
 s          (2,1)  Stiffness [roll,pitch] (Nm/rad)
See also
FGravityGradientStiffness
References and(), FGravityGradientStiffness(), isempty(), and VOrbit().
GroundTrackErrorBudget()
function GroundTrackErrorBudget (in fileName, in varargin)
 This function uses parameter pairs. It root sum squares within
 temporal categories and adds temporal categories.
 Units for altitude and planet radius are in km. Focal length is mm
 and pixel size is micro-m. Orbit position error is in km.
 Type GroundTrackErrorBudget for a demo which uses only defaults.
 Since version 2014.1
Form
 s = GroundTrackErrorBudget( fileName, varargin )
Inputs
 fileName    (1,:)   File name
Outputs
 q           {:,3)   Budget {term type category}
References and(), CentroidNoise(), Constant(), CreateLatexTable(), Demo(), get(), GroundTrackErrorBudget(), isempty(), length(), Planets(), PointSpreadFunction2DGaussian(), and zeros().
Referenced by GroundTrackErrorBudget().
GSModel()
function GSModel (in inr, in inrinv, in T, in w, in inrwheel, in uwheel, in Twheel, in wwheel, in dT)
 Computes angular acceleration of a body with n wheels. Can also be
 used as a rigid body model by giving it only 4 inputs. Will return
 the linearized statespace model if 4 outputs are used.
Form
 [wdot,h]       = GSModel(inr,inrinv,T,w,inrwheel,uwheel,Twheel,wwheel)
 [a,b,c,d,dwdt] = GSModel(inr,inrinv,T,w,inrwheel,uwheel,Twheel,wwheel,dT)
Inputs
 inrinv       (3,3)     Inverse inertia matrix
 inr          (3,3)     Inertia matrix
 T            (3,1)     External torque on the body
 w            (3,1)     Body rate in the body frame
 inrwheel     (n,1)     Wheel inertia
 uwheel       (3,n)     Wheel orientation vector in the body frame
 Twheel       (n,1)     Torque on the wheel
 wwheel       (n,1)     Angular rate of the wheel
 dT                     Time step
Outputs
 wdot         (3+n,1)   Acceleration
 h            (3,1)     Angular momentum in the body frame
 or
 a            (3+n,3+n) State matrix
 b            (3+n,3+n) Input matrix
 c            (3+n,3+n) Output matrix
 d            (3+n,3+n) Feedthrough matrix
 dwdt         (3+n)     State acceleration
 im           (3+n,3+n) Generalized inertia matrix
References C2DZOH(), Cross(), length(), SkewSymm(), statespace(), vector(), and zeros().
Referenced by FGs(), FMagSim(), and RHSGyrostat().
GTrack()
function GTrack (in r, in a, in f)
Computes the locus of points on an ellipsoid for which the line from the spacecraft to the point on the surface is normal to the surface.
Type GTrack for a demo.
Form
 [rG, h] = GTrack( r, a, f )
 [rG, h] = GTrack( r )
Inputs
 r             (3,:)   Spacecraft position vectors
 a             (1,1)   Equatorial radius of the ellipsoid
 f             (1,1)   Flattening factor
Outputs
 rG            (3,:)   Ground track on the ellipsoid
 h             (1,:)   Altitude
References abs(), Altitude(), Constant(), GTrack(), isempty(), length(), NewFig(), Plot2D(), Watermark(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by GTrack().
GUICounter()
function GUICounter (in action, in modifier, in u)
Form
 tag = GUICounter( action, modifier, u )
Inputs
 action          (1,:)   Action to be taken by the message center
 modifier        (:)     Modifier to the message
 u               (1,1)   Count
Outputs
 tag             (1,:)   Returns the window tag on initialization
References CloseFigure(), Counter(), CreateCallback(), GetH(), GetNewTag(), Initialize(), and set().
Gyro()
function Gyro (in action, in input)
Input is a data structure with, at a minimum,
 input.type  'hrg default'  (for a default Hemispherical Resonating Gyro)
 input.u     eye(3) (for three orthogonal gyros)
You may fill in the rest of the data structure or use the built in defaults.
Optical and other solid-state gyros have the equations
 dangle/dt = w + b      + d.angleRandomWalk1Sigma*randn
 db/dt   =  -d.beta*b + d.biasRandomWalk1Sigma *randn
 y   = angle      + d.outputNoise1Sigma    *randn
 c   = fix(d.scaleFactor*y/d.lSB)
Mechanical gyros have the equation terms in the output equation
 y   = (d.forwardGain/d.damping)(d.angularMomentum*angle
 - d.torqueRebalanceGain*z)
 + d.outputNoise1Sigma*randn
and the additional state
 dz/dt   = y;
where beta is the correlation time constant for the bias drift.
On initialization, the scale factor and bias are set using
 d.scaleFactor = d.scaleFactor + d.scaleFactor1Sigma*randn
 d.bias        = d.bias1Sigma*randn
Valid types are:
 hrg default
 fog default
 Mechanical RIG default
 Mechanical RG default
For failures the input is the index of the failed gyro.
Form
 output = Gyro( action, input )
 Arguments
 action      (1,:)    Action
 action is 'initialize'
 input       (1,1)    Data structure
 .type        (1,:) Same as input string described above
 .u           (3,n) Unit vectors for the gyros
 .lSB         (1)   LSB for the gyros (quantization)
References: Farrenkopf, R.L., (1974). Generalized Results for Precision Attitude Reference Systems Using Gyros. AIAA Paper 74-903.
References and(), Counter(), get(), Gyro(), Initialize(), isempty(), RW2SDev(), set(), Unit(), and zeros().
Referenced by AirshipControlSim(), FSDG(), Gyro(), GyroKalmanFilter(), KFSunAndEarth2(), RHSGyroWithOrbit(), RHSReactionWheelWithOrbit(), RYGCAttDet(), SDG(), and StellarAttDetUKF().
GyroData()
function GyroData (in type, in class)
The gyro noise model is:
 y                  =  IntegratedRate    + nOutput
 dIntegratedRate/dt =  bias              + nRandomWalk
 dbias/dt           = -biasCoeff * (bias + nBiasDrift)
 bias(0)            =  mbias             + nBias
The bias drift model is for short term drift and is modeled as a Markov process. The random bias includes day to day variations.
Form
 [nRandomWalk,nBiasDrift,biasCoeff,nOutput,nBias,mBias] = GyroData (type,class)
Inputs
 type            (1,:)   Type of gyro:
                             'SDG'      single dof mechanical
                             'DTG'      dry tuned gyro
                             'RLG'      ring laser
                             'HRG'      hemispherical resonating gyro
 class           (1,:)   Class of gyro. Class defaults to 'High'
                             'High'     High accuracy
                             'Medium'   Medium accuracy
                             'Low'      Low accuracy
Outputs
 nRandomWalk     (1,1)    One sigma random walk  (rad/sec)
 nBiasDrift      (1,1)    One sigma bias drift   (rad/sec^2)
 biasCoeff       (1,1)    Bias coefficient       (1/sec)
 nOutput         (1,1)    One sigma output noise (rad)
 nBias           (1,1)    One sigma bias error   (rad/sec)
 mBias           (1,1)    Mean bias              (rad/sec)
References and(), GyroData(), HRG(), Markov(), RW2SDev(), and SDG().
Referenced by GyroData().
HMagEl()
function HMagEl (in p, in a, in type)
 One element is a current filament of finite length a, 'fila' and
 the other is a a current loop of radius a, 'loop'. h is for a unit current.
 The filament is aligned with the z-axis and goes from 0 to +a. The
 loop is in the xy-plane centered around the z-axis.
 Since version 2.
Form
 h = HMagEl( p, a, type )
Inputs
 p             (3,:)   Points at which to compute the magnetic field
 a                          Physical dimension
 type                  Either 'fila' or 'loop'
Outputs
 h             (3,:)   The magnetic field
References: Thome, J. R., J. M. Tarrh, "MHD and Fusion Magnets", John Wiley & Sons, 1982.
References and(), HMagEl(), isempty(), length(), Plot2D(), and zeros().
Referenced by HMagEl().
HMS2S()
function HMS2S (in h, in m, in s)
 Since version 1.
Form
 s = HMS2S( h, m, s )
Inputs
 h           (1,:) Hours
 m           (1,:) Minutes
 s           (1,:) Seconds
 or
 h           (3,:) [Hours; Minutes; Seconds]
Outputs
 s           (1,:) Seconds
References and().
HorizonUnitVectors()
function HorizonUnitVectors (in r, in v, in a, in theta)
This generates unit vectors that go from r to the horizon of a spherical planet. theta is about about the LVLH z-axis. It draws an image of the cone. Theta starts at -y LVLH.
Type HorizonUnitVectors for a demo.
Form
 u = HorizonUnitVectors(r,v,a,theta)
Inputs
 r      (3,1)   Spacecraft position vector (km)
 v      (3,1)   Spacecraft velocity vector
 a      (1,1) Planet radius (km) (Default Earth)
 theta  (1,:)   Angle from LVLH +x around +z
Outputs
 uH     (3,:) Horizon unit vectors
 rH     (3,:) Horizon vectors (km)
References Demo(), HorizonUnitVectors(), isempty(), length(), Mag(), NewFig(), QLVLH(), QTForm(), set(), Unit(), vector(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by HorizonUnitVectors(), and MeasStarAngleAndChord().
HRG()
function HRG (in hRGDS, in w, in dT)
Includes all noise sources
 and temperature dependence.  The data structure is:
 hRGDS(1) = struct('angle'          ,  0,...
 'measurement'    ,  0,...
 'temp'           ,300,...
 'tempNom'        ,300,...
 'unitVector'     , [1;0;0],...
 'biasDrift'      , 0.006*degToRad,...
 'biasDriftT'     , 0.044*degToRad,...
 'biasDriftU'     , 0.00028*degToRad,...
 'angleDepDrift'  , 0.37*degToRad,...
 'angleDepDriftT' , 0.0044*degToRad,...
 'angleDepDriftU' , 0.0045*degToRad,...
 'angleRandomWalk', 0.000065*degToRad/60,...
 'scaleFactor'    , 1.0,...
 'scaleFactorU'   , 0.02,...
 'scaleFactorT'   , 0.11,...
 'resolution'     , degToRad/3600,...
 'initialize'     , 0 );
 Since version 2.
Form
 hRGDS = HRG( hRGDS, w, dT )
Inputs
 hRGDS         (:,:)  Data structure for the gyros
 w             (3,1)  Inertial body rate
 dT            (1,1)  Time step (sec)
Outputs
 hRGDS         (:,:)  Data structure for the gyros
References and(), Euler(), HRG(), Initialize(), and length().
Referenced by GyroData(), and HRG().
HRY()
function HRY (in x, in ignoredArg, in ignoredArg, in ignoredArg)
Form
 z = HRY( x, t, d, k )
Inputs
 x            (4,1)   Input
 t       (1,1)   Not used
 d            (:)     Not used
 k      (:)     Not used
Outputs
 z            (1,1)   Measurement
HSAData()
function HSAData (in us, in un, in eradius, in ua, in spinrate, in cant, in dihedral, in quant, in qtype, in onesigma, in delay)
This computes the time tags for a single sensor. You should include biases on the cant angle, dihedral angle and earth width. A time delay can also be entered. HSA is horizon sensor assembly.
Form
 [tle,tte,hew,sm] = HSAData(us, un, eradius, ua, spinrate, cant, dihedral,
 quant, qtype, onesigma, delay)
Inputs
 us           (3,n)     Unit sun vectors
 un           (3,n)     Unit nadir vectors
 eradius      (n)       Angular radius of the earth
 ua           (3,1)     Unit spin axis vector
 spinrate     (1,1)     Spin rate
 cant         (1,1)     Cant angle (rad)
 dihedral     (1,1)     Dihedral angle - between sun sensor and HSA (rad)
 quant        (1,1)     Quantization
 qtype        (1,1)     Type of quantization-either 'round' or 'truncate'
 onesigma     (1,1)     One sigma noise (rad)
 delay        (1,1)     Time delay
Outputs
 tle          (n)       Leading edge times
 tte          (n)       Trailing edge time
 hew          (n)       Half chord width (rad)
 sm           (n)       Dihedral angle (rad)
References abs(), and(), Cross(), HSAData(), isempty(), length(), Mag(), Plot2D(), RVFromKepler(), SunV1(), Unit(), vector(), and zeros().
Referenced by ADComp(), ADCull(), ADGen(), GetHSA(), and HSAData().
HSAPlot()
function HSAPlot (in ra, in dec, in tle1, in tte1, in tle2, in tte2, in t, in dt)
 Since version 1.
Form
 HSAPlot( ra, dec, tle1, tte1, tle2, tte2, t, dt )
Inputs
 ra       (1,:) Right ascension
 dec      (1,:) Declination
 tle1     (1,:) Leading edge time
 tte1     (1,:) Trailing edge time
 tle2     (1,:) Leading edge time
 tte2     (1,:) Trailing edge time
 t        (1,:) Time array
 dt       (1,1) Spin Period
Outputs
 None
References NewFig(), Period(), XLabelS(), and YLabelS().
Referenced by GetHSA().
HydrazineThruster()
function HydrazineThruster (in d, in pressure, in pulsewidth, in dT)
The thrust is dependent on the pressure of the propellant. The exhaust velocity is dependent on the pulsewidth, it increases from a minimum to a maximum.
The data structure and default values of the properties can be found from
 p = DeviceProperties( 'hydrazine thruster' )
Form
 d = HydrazineThruster;   % data structure
 [thrust, dF, impulse, pulsewidth] = HydrazineThruster( d, pressure, pulsewidth, dT )
Inputs
 d               (.)    Thruster model data structure
 pressure        (:)    Pressure, can also be a scalar
 pulsewidth     (1,n)   Pulsewidth (sec)
 dT             (1,1)   Simulation timestep, for scaling (optional)
Outputs
 thrust          (:)    Thrust
 dF              (:)    Fuel consumed
 impulse         (:)    Total impulse per thruster
 pulsewidth      (:)    Remaining pulsewidth
References and(), DeviceProperties(), HydrazineThruster(), length(), Limit(), Pressure(), scalar(), vector(), and zeros().
Referenced by HydrazineThruster().
HysteresisOutput()
function HysteresisOutput (in t, in y, in flag, in d)
Form
 d = HysteresisOutput;
 status = HysteresisOutput(t,y,flag,d)
Inputs
 t      (1,1)     Time
 y      (13+n,:)  [r;v;q;omega;z]
 flag  (1,:)     Operation to be performed.
 d     (.)       Data structure see RHSRigidBodyWithDamping
Outputs
 status (1,1)    Result
See also
RHSRigidBodyWithDamping
References Dot(), HysteresisOutput(), isempty(), length(), QTForm(), RHSRigidBodyWithDamping(), Unit(), and zeros().
Referenced by HysteresisOutput().
IC3X326()
function IC3X326 (in x)
 The initial 3x3 form is
 [Ixx Ixy Ixz
 Ixy Iyy Iyz
 Ixz Iyz Izz]
 and the final 1x6 form is
 [Ixx Iyy Izz Ixy Ixz Iyz]
 Since version 1.
Form
 y = IC3X326( x )
Inputs
 x           (3,3)     Inertia matrix
Outputs
 y           (1,6)     [Ixx Iyy Izz Ixy Ixz Iyz]
 Copyright (c) 1995 Princeton Satellite Systems, Inc.
 All rights reserved.
References and().
IFOV()
function IFOV (in altitude, in f, in a, in d, in lambda)
Form
 iFOV = IFOV( altitude, f, a, d, lambda )
Inputs
 altitude       (1,n) Altitude
 f              (1,1) Focal length
 a              (1,1) Detector size
 d              (1,1) Aperture
 lambda         (1,m) Wavelength, numbers or 'visible', 'near infrared'
                      'far infrared'
Outputs
 iFOV           (1,1)  Output data structure
References Altitude(), IFOV(), length(), Mesh2(), Spectrum(), and Wavelength().
Referenced by IFOV().
Illumination()
function Illumination (in rS, in rC, in uS, in uC, in rho, in iL, in fNumber)
 You input the source position and unit vector along with the camera
 location and boresight vector. rho is the albedo of the source
 and iL is the vector to the illumination source.
 Type Illumination for a demo.
Form
 m = Illumination( rS, rC, uS, uC, rho, iL, fNumber )
Inputs
 rS          (3,:)     Source position
 rC          (3,1)     Camera position
 uS          (3,:)     Source unit vector
 uC          (3,1)     Camera unit vector
 rho         (1,1)     Source albedo
 iL          (3,1)     Illumination vector
 fNumber     (1,1)     F Number of camera
Outputs
 E           (1,:)     Illumination
References and(), Demo(), DupVect(), Illumination(), Plot2D(), Unit(), vector(), and zeros().
Referenced by AntennaGain(), Beamwidth3dB(), ConvertOBJFileColorToMatlab(), Gain3dB(), Illumination(), and LinkBudget().
IMU()
function IMU (in action, in varargin)
Assumes the input acceleration is in the inertial frame. It transforms it into the body frame. It accounts for the accelerometer offset from the center of mass.
Form
 d             = IMU;
 d             = IMU( 'initialize', d );
 output        = IMU( 'output', vDot, omegaDot, q, omega, integratedRate, randomWalk, d )
 randomWalkDot  = IMU( 'rhs', randomWalk, d )
Inputs
 action      (1,:) 'initialize', 'rhs', 'output'
 accel       (3,1) Acceleration vector
 omegaDot    (3,1) Angular acceleration vector
 omega       (3,1) Angular rate vector
 q           (4,1) Quaternion from ECI to Body
 randomWalk (6,1) Random walk vector [accel;rate]
 d           (.)   Data structure
Outputs
 d           (.)   Data structure
 output      (6,1) Output vector [accel;rate]
References IMU(), Random(), vector(), and zeros().
Referenced by GyroKalmanFilter(), IMU(), RHSLunarMission(), RHSSpacecraftWithIMU(), and SunEarthMagAttDet().
InertiaTotal()
function InertiaTotal (in inertia, in mass, in rCM, in rHinge, in u, in angle, in omega, in inertiaTotal)
 Assumes a core with n appendages directly attached, i.e. solar arrays.
Form
 [omega, inertiaTotal] = InertiaTotal( inertia, mass, rCM, rHinge, u,
 omega, angle, inertiaTotal )
Inputs
 inertia        {:}   3-by-3 Inertia matrices {core array1 array2 ...}
 mass           (1,:) Masses
 rCM            (3,:) Reference vector to cm of each body from the hinge
 rHinge         (3,:) Hinge vectors
 u              (3,:) Unit vectors of rotation for {array1 ...
 angle          (1,:) Array angle
 omega          (3,1) Angular rate
 inertiaTotal   (3,3) Old 3-by-3 Inertia matrix
Outputs
 omega          (3,1) Angular rate
 inertiaTotal   (3,3) 3-by-3 Inertia matrix
References and().
IntensityDistribution()
function IntensityDistribution (in action, in varargin)
The default intensity is 1/(1 + s*r^2) where r is the distance from the point source center. The output is normalized so that the sum of all pixels is 1. You can supply your own function.
The intensity function is called as
 @intensityFun( r, s ) where s is scale factor
Type IntensityDistribution for a demo
Form
 m = IntensityDistribution( 'initialize', n, m, w, s, fun )
 m = IntensityDistribution( 'update', p )
Inputs
 action         (1,:)  'initialize' or 'update'
 'initialize'
 n              (1,1)   Rows
 m              (1,1)   Columns
 w              (1,1)   Pixel width
 s              (1,1)   Scale factor
 @intensityFun  (1,1)   Pointer to the intensity function
 'update'
 p              (2,:)   Points
Outputs
 'initialize'
 none
 'update'
 m              (n,m)  Pixel array
References IntensityDistribution().
Referenced by IntensityDistribution().
ISSCoord()
function ISSCoord (in r, in jD)
The ISS frame is defined as:
 +X Along the velocity vector (Forward)
 +Y -Orbit Normal (Starboard)
 +Z Zenith (Deck)
This is the same as LVLH. Julian date propagates the initial ISS coordinate set. If there are no outputs the function draws a 3D view of the scene using the CAD model in ISS.mat.
Type ISSCoord for a demo for a position offset from the ISS by a few tens of meters.
Form
 rISS = ISSCoord(r,jD)
Inputs
 r   (3,:)   ECI coordinates
 jD  (1,1)  Julian date
Outputs
 rL  (3,:)  Position in ISS Coordinates
References: https://www.nasa.gov/mission_pages/station/multimedia/ iss_labs_guide.html
References abs(), AggregateComponents(), Arrow3D(), Coordinates(), Demo(), DrawVertices(), El2RV(), ISSCoord(), ISSOrbit(), QForm(), QLVLH(), and set().
Referenced by ISSCoord().
ISSOrbit()
function ISSOrbit (in set)
Generates elements for the International Space Station from a two-element set from Celestrak, https://celestrak.com. Type ISSOrbit for a demo with a plot of the ISS ground track. If there are no outputs it will plot the elements using sgp as a propagator.
Fixed elements are from 07/16/2020. 'latest' is the default set. These are saved in a persistent variable and updated only if more than 2 hours has elapsed since the last call, to avoid server errors. Elements are only updated on Celetrak once or twice per day.
Form
 ISSOrbit;   % demo
 [el, jD0, s] = ISSOrbit( set )
Inputs
 set   (1,:)   'high' 'low' 'latest' 'fixed'
Outputs
 el    (1,6)   Elements vector [a,i,W,w,e,M]
 jD0   (1,1)   Julian date of epoch
 s     (1,166) The two line elements
References and(), Demo(), ISSOrbit(), set(), and vector().
Referenced by AdjustMeanAnomaly(), AtmNRLMSISE(), DataRateOrbit(), ISSCoord(), ISSOrbit(), TwoUToQ(), and WMM().
JDToFirstOfMonth()
function JDToFirstOfMonth (in jD)
Type JDToFirstOfMonth for a demo.
 Usage:
 jDFoM = JDToFirstOfMonth(jD)
Inputs
 jD   (1,:) Julian dates
Outputs
 jDF  (1,:)  Julian dates for 1st of month
References Date2JD(), Demo(), JD2000(), JD2Date(), JDToFirstOfMonth(), length(), and zeros().
Referenced by JDToFirstOfMonth().
JHAPLSatelliteMass()
function JHAPLSatelliteMass (in s, in p)
Provides a subsystem mass breakdown for four representative satellites. The last column is the fraction of the total mass, for rows that are subsystem masses.
Form
 JHAPLSatelliteMass;   % demo
 m = JHAPLSatelliteMass( s, 'all' )  % table
 m = JHAPLSatelliteMass( s, p )      % subsystem mass
Inputs
 s         ''   Satellite, 'messenger' 'stereo a' 'stereo b' 'new horizons'
 p        (1,1) Parameter, 'all' or a named parameter from the list:
                 'total power' 'vol' 'mass' 'payload' 'structure'
                 'propulsion' 'fuel' 'power' 'comm' 'cdh' 'acs'
                 'thermal' 'harness'
Outputs
 m        {:,3} [name value fraction (if mass)]
  - or -
 m        (1,1) if not 'all' for p
References: Schaefer, E.D., et. al.,"Spacecraft Packaging", Johns Hopkins APL Technical Digest, Vol. 28, No. 1 2008.
References JHAPLSatelliteMass(), and Parameter().
Referenced by JHAPLSatelliteMass().
KConst()
function KConst (in x, in ignoredArg, in constData)
The outputs are
 Holonomic         Non Holonomic
 phi               phi
 phiQ              A
 phiTDot           0
 phiDot            BDot
 phiQDot           ADot
 where the holonomic constraints are of the form
 phi(q,t) = 0
 and the non holonomic constraints are of the form
 A(q,t)qDot + B(q,t) = 0
Form
 [phi, phiQ, phiTDot, phiDot, phiQDot] = KConst( x, t, constData )
Inputs
 x            (2n,1)    The state vector [x;xDot]
 t            (1,1)     Time
 constData    (:,:)     Data to be passed to the constraint function [ L^2 ]
Outputs
 phi          (n,1)    The constraint vector
 phiQ         (n,n)    The Jacobian of the constraint vector with respect to the state
 phiT         (n,1)    The Jacobian of the constraint vector with respect to time
 phiDot       (n,1)    The derivative of the state vector with respect to time
 phiQDot      (n,n)    The time derivative of the Jacobian marix
Reference: Jalon, J.G., E. Bayo, "Kinematic and Dynamic Simulation of Multibody Systems, The Real-Time Challenge," Springer-Verlag, 1993, pp. 164-170.
References and(), Jacobian(), and vector().
KConstP()
function KConstP (in q, in ignoredArg, in constData)
The outputs are
Holonomic Non Holonomic
 phi               phi
 phiQ              A
 phiT              0
 phiDot            BDot
 phiQDot           ADot
 where the holonomic constraints are of the form
 phi(q,t) = 0
 and the non holonomic constraints are of the form
 A(q,t)qDot + B(q,t) = 0
 Since version 2.
Form
 [phi, phiQ, phiT, phiDot, phiQDot] = KConstP( q, t, constData )
Inputs
 q            (2n,1)    The state vector [q;qDot]
 t            (1,1)     Time
 constData    (:,:)     Data to be passed to the constraint function [ L^2 ]
Outputs
 phi          (n,1)    The constraint vector
 phiQ         (n,n)    The Jacobian of the constraint vector with respect to the state
 phiT         (n,1)    The Jacobian of the constraint vector with respect to time
 phiDot       (n,1)    The derivative of the state vector with respect to time
 phiQDot      (n,n)    The time derivative of the Jacobian marix
References and(), Jacobian(), and vector().
KConstQ()
function KConstQ (in q, in ignoredArg, in omega)
The outputs are
 Holonomic         Non Holonomic
 phi               phi
 phiQ              A
 phiT              0
 phiDot            BDot
 phiQDot           ADot
where the holonomic constraints are of the form
 phi(q,t) = 0
and the non holonomic constraints are of the form
 A(q,t)qDot + B(q,t) = 0
Form
 [phi, phiQ, phiT, phiDot, phiQDot] = KConstQ( q, t, omega )
Inputs
 q            (4,1)     The quaternion
 t            (1,1)     Time
 omega        (3,1)     Body rates
Outputs
 phi          (n,1)    The constraint vector
 phiQ         (n,n)    The Jacobian of the constraint vector with respect to the state
 phiT         (n,1)    The Jacobian of the constraint vector with respect to time
 phiDot       (n,1)    The derivative of the state vector with respect to time
 phiQDot      (n,n)    The time derivative of the Jacobian marix
References and(), Jacobian(), QIToBDot(), quaternion(), and vector().
LagrangePointsL1ToL5()
function LagrangePointsL1ToL5 (in mu)
 coordinates with the origin at the joint center-of-mass.
 For a demo of the Earth Moon system type LagrangePointsL1ToL5
Form
 p = LagrangePointsL1ToL5( mu )
Inputs
 mu             (1,1)  Ratio of smaller mass to total mass
Outputs
 p              (2,5)  [L1, L2, L3, L4, L5]
Reference: Szebehely, V., "Theory of Orbits", Academic Press, 1967, pp. 134-138.
References abs(), Demo(), and LagrangePointsL1ToL5().
Referenced by EarthMoonRotFrame(), LagrangePointsL1ToL5(), LowEnergyEarthToMoonTransfer(), LunarDisplacement(), LunarHalo(), and TransformLagrangePoints().
LibrationFrequency()
function LibrationFrequency (in inertia, in n)
Type LibrationFrequency for a demo of a gravity gradient stable spacecraft.
Form
 omega = LibrationFrequency( inertia, n )
Inputs
 inertia   (3,3)  Inertia matrix
 n         (1,1)  Orbit rate
Outputs
 omega     (3,1)  Frequencies
References and(), eig(), LibrationFrequency(), Skew(), VOrbit(), and zeros().
Referenced by LibrationFrequency().
LightDetectorIntegrals()
function LightDetectorIntegrals (in starType, in detector)
Form
 e = LightDetectorIntegrals( starType, detector )
Inputs
 starType      {}      'B1' ... 'M2'
 detector      (1,:)   'Si' or 'visual'
Outputs
 e             (1,1)    Integral
References: Kayton, M. and W. R. Fried, "Avionics Navigation Systems. Second Edition." Wiley. pp. 569.
References and().
LinOrbNormalized()
function LinOrbNormalized ()
 y      = c*x[k] + d*u[k]
 x[k+1] = a*x[k] + b*u[k]
 otherwise
 y      = c*x + d*u
 dx/dt  = a*x + b*u
Form
 [a, b, c, d] = LinOrbNormalized
Inputs
 None
Outputs
 a                (6,6) State transition matrix or (6,1) state derivative
 b                (6,3) Input matrix
 c                (3,6) Output matrix (position)
 d                (3,3) Feedthrough matrix
References and(), LinOrbNormalized(), and zeros().
Referenced by LinOrbNormalized().
LoadEarthMap()
function LoadEarthMap (in name)
Loads the file EarthMapData.mat. The figure has a black background.
Form
 h = LoadEarthMap( name )
Inputs
 name       (1,:) Figure title
Outputs
 h           Handle to the figure
References and(), Map(), set(), and Watermark().
Referenced by OverArea().
LoadFK5()
function LoadFK5 (in catName, in VMMin)
 If only one output is requested it will output a data structure.
 Since version 1.
Form
 d = LoadFK5( catName, VMMin )
 [name1, name2, name3, RA, Dec, PMRA, PMDec, Parallax, RV, VM] = LoadFK5( catName, VMMin )
Inputs
 catName   (1,:)        Catalog name                      (string)
 VMMin     (1,1)        Minimum visual magnitude          (magnitude)
Outputs
 name1      {:}         First name
 name2      {:}         Second name
 name3      {:}         Third name
 RA         (:)         Right ascension J2000.0 (rad)
 Dec        (:)         Declination     at J2000.0 (rad)
 PMRA       (:)         Proper motion in R.A.  at J2000.0 (rad/cent)
 PMDec      (:)         Proper motion in Dec.  at J2000.0 (rad/cent)
 Parallax   (:)         Parallax                          (rad)
 RV         (:)         Radial velocity                   (km/sec)
 VM         (:)         Visual magnitude                  (magnitude)
References: MICA User's Guide, Astronomical Applications Department U.S. Naval Observatory, Washington, D.C.
References Parallax().
Referenced by LoadCatalog().
LoadFlex()
function LoadFlex (in file, in path)
The flex data is in the format:
 # Nodes
 Node ID rX rY rZ mass (one line for each node)
 Mode ID omega         (one line for each mode)
 PhiX PhiY PhiZ        (one block for each mode and within each block
 one line for each node)
Form
 [phi, omega, rNode, mNode, nodeID, nNodes, nModes] = LoadFlex( file, path )
Inputs
 file             (:)     File names
 path                     Name of path
Outputs
 phi              (3,n*m) Nodal displacements per modal displacement
 omega            (m)     Modal frequencies
 rNode            (3,n)   Location of each node with respect to the origin
 mNode            (n)     Mass of each node
 nodeID           (n)     Node id
 nNodes           (1)     Number of nodes
 nModes           (1)     Number of modes
See ComstarSA.txt
References and(), Axis3D(), isempty(), length(), LoadFlex(), NewFig(), vector(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by GetFlex(), and LoadFlex().
LoadGOES()
function LoadGOES (in tS, in file)
Will edit out magnetometer glitches.
 If not inputs are given it will display a file open dialog
 box.
Form
 [b, t, bMag, x, e, p, header, a] = LoadGOES( tS, file )
Inputs
 tS                (1,2)  Time standard ('UT' or 'SC')
 file              (1,:)  File name
Outputs
 b                 (3,:)  Magnetic field
 t                 (1,:)  Time in seconds from beginning of data or
                          local spacecraft time.
 bMag              (1,:)  Magnetic field magnitude
 x                 (1,:)  X-rays
 e                 (1,:)  Electrons
 p                 (1,:)  Particles
 header            (1,6) [satID,year,dataType,AverageType,Month,jD]
 a                 (1,:)  Data
References FindDirectory(), isempty(), and IsVersionAfter().
Referenced by BHarm().
LoadMag()
function LoadMag (in sc, in CDROM, in mmS, in yyS, in mmF, in yyF, in suffix)
This can take a lot of data.
 It uses the A files because they are small.
 Since version 3.
Form
 [b, filesUsed] = LoadMag( sc, CDROM, mmS, yyS, mmF, yyF, suffix )
Inputs
 sc                 (1,1) Spacecraft id
 CDROM              (1,:) CD-ROM name including complete path
 mmS                (1,1) Month of start
 yyS                (1,1) Year of start (e.g. 88)
 mmF                (1,1) Month of finish
 yyF                (1,1) Year of finish (e.g. 89)
 suffix             (1,1) If any input append ';1' to the file names
Outputs
 b                 (3,:)  Magnetic field
 filesUsed         (:,:)  Files used-each row a file name
References Glitch(), LoadMag(), and TwoC2F().
Referenced by LoadMag().
LoadSatP()
function LoadSatP (in file)
Form
 p = LoadSatP( file )
Inputs
 file             (1,:)   File name
Outputs
 p                (6,n)   GOES Satellite position
References FindDirectory(), isempty(), and IsVersionAfter().
Referenced by GOESLon().
LoadSers()
function LoadSers (in sc, in fT, in CDROM, in mmS, in yyS, in mmF, in yyF, in suffix)
Similar to LoadMap only returns all of the data.
Form
 [b, e, x, p, filesUsed] = LoadSers( sc, fT, CDROM, mmS, yyS, mmF, yyF, suffix )
Inputs
 sc                 (1,1) Spacecraft
 fT                 (1,1) File type {'H','I','G','Z','A'}
 CDROM              (1,:) CD-ROM name
 mmS                (1,1) Month of start
 yyS                (1,1) Year of start
 mmF                (1,1) Month of finish
 yyF                (1,1) Year of finish
 suffix             (1,1) If any input append ';1' to the file names
Outputs
 b                  (1,1)  Magnetic field
 e                  (1,1)  Electrons
 x                  (1,1)  X-rays
 p                  (1,1)  particles
 fileUsed           (:,:)  Files used-each row a file name
LoadSolarFluxHistory()
function LoadSolarFluxHistory ()
The data history is in the file 'Kp_ap_Ap_SN_F107_since_1932.txt'. Remove any trailing lines that have Ap data but where the solar index is -1 before running this function on the file.
Download the latest from: https://www.gfz-potsdam.de/en/kp-index/ https://www-app3.gfz-potsdam.de/kp_index/Kp_ap_Ap_SN_F107_since_1932.txt
Saves the file 'Kp_ap_Ap_SN_F107_since_1932.mat'
TODO: specify mat-file location
Inputs
 None.
Outputs
 None.
References and(), and LoadSolarFluxHistory().
Referenced by LoadSolarFluxHistory(), and SolarFluxHistorical().
LocalSolarTime()
function LocalSolarTime (in jD, in rECI)
Compute local solar time from Julian date and inertial position.
Form
 hRA = LocalSolarTime( jD, rECI )
Inputs
 jD   (1,:) Julian date
 rECI (3,:) ECI position vector
Outputs
 hRA    (1,1) Local solar time
References and(), SunV1(), and vector().
Referenced by AtmNRLMSISE().
LocalStarMap()
function LocalStarMap (in lY, in filename)
Epoch is J2000.
 Since version 10.
Form
 s = LocalStarMap( lY,filename )
Inputs
 lY       (1,1) light year range
 fileName (1,:) Filename
Outputs
 s      (1,1) Data structure
              .d    (1,1) Distance (Light years)
              .name (1,:) Name
              .type (1,:) Star type
              .u    (3,1) Unit vector
              .pm   (1,2) Proper motion [ra dec] mill arc sec/yr
References: http://www.essex1.com/people/speer/stars.html
References Demo(), HMS2Rad(), length(), LocalStarMap(), Mag(), Map(), NewFig(), RaDec2U(), set(), StringToTokens(), Unit(), vector(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by LocalStarMap().
MagAirC()
function MagAirC (in dipole, in dim, in weight, in wire)
 If wire is not input it will use #24 aluminum.
 If the dipole is a vector it will plot mass and power vs. dipole
 if no output arguments are entered. Otherwise it will plot mass and
 power vs. current.
Form
 [power, mass, nTurns, current] = MagAirC( dipole, dim, weight, wire )
Inputs
 dipole         (n)       Desired dipole (ATM^2)
 dim            (2 or 1)  [l,w] or [r] (m)
 weight         (2)       [weight constraint] if weight == 0   constraint = power
                                              if weight == inf constraint = mass
                          e.g. [inf 4] will constrain the coil to 4 kg
                               [0   4] will constrain the coil to dissipate 4 watts.
                          weight(1) is the ratio of the (weight of coil mass/weight of coil power)
 wire           (3)       [resistivity, density, area]
Outputs
 power                    Required power (watts)
 mass                     Total mass
 nTurns                   Number of turns
 current                  Current (A)
References abs(), and(), Dipole(), isempty(), length(), MagAirC(), NewFig(), Plot2D(), TextS(), vector(), XLabelS(), YLabelS(), and zeros().
Referenced by MagAirC().
MagControlThreeAxis()
function MagControlThreeAxis (in t, in b, in time)
This minimizes the weighted sum of the following cost functional:
 J = (t + Cross(b,m))'(t + Cross(b,m))' + m'm
where t is constant over the period of time for which b is entered.
If b is not entered it computes the magnetic field for an orbit whose radius is 7000 km and inclination is 28.4 deg. The default t is [1e-5;-1e-5;2.e-5]. The demo is run by typing:
 MagControlThreeAxis
The dipole results are in ATM^2. If there are no outputs, the function will make plots of the user inputs.
Form
 [m, lambda, e] = MagControlThreeAxis( t, b, time )
Inputs
 t               (3,1)   Torque
 b               (3,:)   Magnetic field vector in the torque frame
 time            (1,:)   Time vector corresponding to b
Outputs
 m               (3,:)   Magnetic dipole vector needed
 lambda          (3,1)   Costates
 e               (3,1)   Torque error
References Dipole(), Step(), and vector().
MagControlTwoAxis()
function MagControlTwoAxis (in t, in b, in a)
Computes the dipole vector needed to produce a torque t given the magnetic field b. This minimizes the weighted sum of the following cost functional:
 J = (t + Cross(b,m))'(t + Cross(b,m)) + m'm
Only two elements of t can be constrained. These axes are selected using the vector a. The other component of t will be uncontrolled. Any time the components of b corresponding to the constrained components of t are aligned this algorithm will demand very large dipoles.
If b is not entered it computes the magnetic field for an orbit whose radius is 7000 km and inclination is 28.4 deg. The default t is [1e-5;1e-5] and the default a is [1;2]. The demo is run by typing:
 MagControlTwoAxis
The dipole results are in ATM^2.
Form
 [m, e] = MagControlTwoAxis( t, b, a )
Inputs
 t               (2,1)   Torque
 b               (3,:)   Magnetic field vector in the torque frame
 a               (2,1)   Axes corresponding to the values in t
Outputs
 m               (3,:)   Magnetic dipole vector needed
 e               (3,:)   Torque error
References and(), BDipole(), Dipole(), isempty(), JD2000(), length(), MagControlTwoAxis(), Plot2D(), QForm(), QLVLH(), RVFromKepler(), Skew(), Step(), vector(), and zeros().
Referenced by MagControlTwoAxis().
MagField()
function MagField (in position, in jD, in nMax, in varargin)
This model only is valid for the Earth. Use MagFieldPlanet for all other planets. The model is loaded from IGRF11.mat if no dataFile or coefficients are given.
Form
 [b, g, h] = MagField( position, jD, nMax, dataFile)
 b         = MagField( position, jD, nMax, g, h )
Inputs
 position    (3,:)  Position in ECI (km)
 jD          (1,1) Julian date
 nMax        (1,1) Maximum number of terms used. Enter an empty matrix
                     to use all available terms
 dataFile    (1,:) Optional, The file name of a .mat file
                     which contains the magnetic field data.
                     The variables which must be stored in
                     dataFile are: dateOfModel, g, gDot, h,
                     and hDot. This may also be the name of
                     a structure with fields .h, .g, .gDot, .hDot
                     and .dateOfModel
    - or -
 g                  Optional, but speeds execution
 h                  Optional, but speeds execution
Outputs
 b           (3,:)  The magnetic field in ECI (T)
 g                  The (full) g coefficient matrix for dateTime
 h                  The (full) h coefficient matrix for dateTime
References: Wertz, J., Spacecraft Attitude Determination and Control, Kluwer, 1976, pp. 779-781.
See also
: ECIToEF, MagFieldPlanet
References and(), Date2JD(), ECIToEF(), JD2000(), length(), MagField(), MagFieldPlanet(), Plot2D(), and RVFromKepler().
Referenced by MagField(), and WMM().
MagFieldData()
function MagFieldData (in planet)
See IGRF11.mat for Earth data and NeptuneMagField.txt for Neptune data. Data for Jupiter and Saturn are defined in the function.
 Forms:
 [g,h,a] = MagFieldData( planet )
Inputs
 planet   (1,:)    Planet name
Outputs
 g        (n,n)    g Schmidt normalized coefficents (nT)
 h        (n,n)    h Schmidt normalized coefficients (nT)
 a        (1,1)    Planet radius (km)
References: http://www.nature.com/nature/journal/v298/n5869/abs/298044a0.html http://www.nature.com/nature/journal/v298/n5869/abs/298044a0.html http://www.igpp.ucla.edu/cache1/VG_1001/CATALOG/VG2_NEP_MAG_NLS_12SEC_DS.CAT
References and(), Constant(), ListCases(), MagFieldData(), ReadMagField(), and zeros().
Referenced by MagFieldData(), MagFieldPlanet(), and PlanetEnvironment().
MagFieldPlanet()
function MagFieldPlanet (in r, in g, in h, in a, in nMax)
 This only uses g and h and does not handle time derivatives of g or h.
 For Neptune it is best to call this function with an array of r
 since every time it is called it reads in a text file of g and h
 coefficients.
 For a demo of the magnetic field of Neptune, Jupiter and Saturn,
 type MagFieldPlanet.
Form
 b = MagFieldPlanet( r, g, h, a, nMax )
 or
 b = MagFieldPlanet( r, planet, nMax )
Inputs
 r           (3,:)  Position in planet fixed coordinates (km)
 g           (n,n)  g Schmidt normalized coefficents (nT)
 h           (n,n)  h Schmidt normalized coefficients (nT)
 a           (1,1)  Planet radius (km)
 nMax        (1,1)  Order of model (optional)
 or
 r           (3,:)  Position in planet fixed coordinates (km)
 planet      (1,:)  Planet name
 nMax        (1,1)  Order of model (optional)
Outputs
 b           (3,:)  The magnetic field  (T)
References: Wertz, J., Spacecraft Attitude Determination and Control, Kluwer, 1976, pp. 779-781. Jursa, Adolph S., ed., Handbook of Geophysics and the Space Environment, Air Force Geophysics Laboratory, 1985, p. 4-28.
See also
: MagFieldData, SCHarm, PGauss, Cart2Sph
References and(), Cart2Sph(), Constant(), Cross(), isempty(), length(), MagFieldData(), MagFieldPlanet(), PGauss(), Plot2D(), RPhiTheta2Cart(), SCHarm(), Unit(), and zeros().
Referenced by MagField(), MagFieldPlanet(), and PlanetEnvironment().
MagneticDipole()
function MagneticDipole (in m, in theta, in r)
 Calculates the z and radial components of the field.
 Type MagneticDipole for a demo.
Form
 [bZ, bR] = MagneticDipole( m, theta, r )
Inputs
 m           (1,1)   Dipole moment (ATM^2)
 theta       (1,:)   Angle from the z-axis
 r           (1,1)   Radial distance
Outputs
 bZ          (1,:)   Magnetic field along Z (T)
 bR          (1,:)   Magnetic field along R (T)
References and(), Demo(), Dipole(), length(), MagneticDipole(), Plot2D(), and zeros().
Referenced by MagneticDipole(), and MagneticDipoleCart().
MagneticDipoleCart()
function MagneticDipoleCart (in m, in p)
 m is the dipole vector.
 Type MagneticDipoleCart for a demo.
Form
 b = MagneticDipoleCart( m, p )
Inputs
 m           (3,1)   Dipole moment (ATM^2)
 p           (3,:)   Points (m)
Outputs
 b           (3,:)   Magnetic field (T)
References Cross(), Demo(), Dipole(), Mag(), MagneticDipole(), MagneticDipoleCart(), Plot2D(), Unit(), vector(), and zeros().
Referenced by MagneticDipoleCart().
MagneticFieldDipole()
function MagneticFieldDipole (in m, in r)
 Calculates the magnetic field for a dipole at the origin
 Type MagneticFieldDipole for a demo.
Form
 b = MagneticFieldDipole( m, r )
Inputs
 m  (3,1)   Dipole vector (ATM^2)
 r  (3,:)   Vector to the points
Outputs
 b  (3,:)   Magnetic field (T)
References Arrow3D(), Demo(), Dipole(), Mag(), MagneticFieldDipole(), NewFig(), Unit(), vector(), and zeros().
Referenced by MagneticFieldDipole().
MagneticHysteresis()
function MagneticHysteresis (in b, in ignoredArg, in h, in hDot, in d)
 Unlike Flatley we use a tanh function. Tellinen gives the slope
 fractions for the increasing and decreasing curves.
 Type MagneticHysteresis for a demo
Form
 bDot = MagneticHysteresis( b, t, h, hDot, d )
Inputs
 b                  (1,1) Magnetic flux density (T)
 t                  (1,1) Time - unused
 h                  (1,1) Magnetic field (A/m)
 hDot               (1,1) Magnetic field time derivative (A/m/s)
 d                  (1,1) Data structure
                          .bS (1,1) Saturation flux density (T)
                          .hC (1,1) Coercive force (A/m)
                          .bR (1,1) Remnance (T)
Outputs
 bDot               (1,1) Derivative of the flux density.
Reference: Flatley, T. W. and Henretty, D. A., "A Magnetic Hysteresis Model," N95-27081. Kumar R., Mazanek, D. and Heck, M., "Simulation and Shuttle Hitchhiker Validation of Passive Satellite Aerostabilization," Journal of Spacecraft and Rockets, Vol. 32, No. 5, September-October 1995. J. Tellinen, "A Simple Scalar Model for Magnetic Hysteresis", IEEE Transactions on Magnetics, vol. 24, no. 4, pp.2200-2206, July 1998.
References and(), BFromHHysteresis(), Demo(), length(), MagneticHysteresis(), Plot2D(), RK4(), TimeLabl(), and zeros().
Referenced by MagneticHysteresis(), RHSGGRotational(), RHSHysteresisDamper(), and TorqueHysteresisDamper().
MagneticTorquer()
function MagneticTorquer (in action, in d)
Outputs the torque in body coordinates.
Inputs
 d.powerConsumption (1,1)  Watts
 d.dipole           (3,n)  ATM^2
 The magnetic field needs to be set for the output to be nonzero. The field
 should be in body coordinates.
 Failure mode is zero output. Commands anf failures are input using a matrix
 of logical values.
 Forms:
 MagneticTorquer( 'initialize', d )
 MagneticTorquer( 'update' )
 MagneticTorquer( 'set bfield', b )
 MagneticTorquer( 'set failure', f )
 MagneticTorquer( 'set command', c )
 power  = MagneticTorquer( 'get power consumption' )
 torque = MagneticTorquer( 'output' )
 d      = MagneticTorquer( 'get default datastructure' )
Inputs
 action      (1,:)     'initialize' 'update'  'output'
                       'set bfield' 'set failure'
 d           (1,1)     Depends on the action
Outputs
 y           (1,1)     Depends on the action
References Cross(), get(), length(), MagneticTorquer(), set(), and zeros().
Referenced by MagneticTorquer().
MagneticTorquerDesign()
function MagneticTorquerDesign (in d)
 You pass in the desired power, the voltage, wire gauge and dipole.
 Type MagneticTorquerDesign for a demo.
 It is possible that the selected parameters will not produce a
 torquer coil. If so change the wire size or power consumption.
 Default conductivity, relative permeability
 and density are for copper and steel.
 If your bar is too long, or the power too high you can get
 torquer bars that have circumferences longer than the length of
 one turn of wire. If that happens you will get an error.
 If l is entered it designs the torquer based on that length.
Form
 d = MagneticTorquerDesign( d )
Inputs
 d           (1,1)   Data structure
                     .aWG              (1,1) Wire gauge 0000 is -3
                     .power            (1,1) Power (W)
                     .v                (1,1) Voltage (V)
                     .dipole           (1,1) Dipole (ATM^2)
                     .densityConductor (1,1) Material density (kg/m^3)
                     .conductivity     (1,1) Conductivity (S/m)
                     .densitySteel     (1,1) Material density (kg/m^3)
                     .muR              (1,1) Relative permeability
                     .l                (1,1) Length (m)
Outputs
 d           (1,1)   Data structure with additions
                     .rWire            (1,1) Wire radius (m)
                     .i                (1,1) Current (A)
                     .rhoWire          (1,1) Resistance (Ohm/m)
                     .lWire            (1,1) Wire length (m)
                     .rBar             (1,1) Radius of the metal bar (Ohm/m)
                     .mWire            (1,1) Mass wire (kg)
                     .R                (1,1) Coil resistance (Ohm)
                     .l                (1,1) Length of the torquer (m)
                     .mSteel           (1,1) Mass steel (kg)
                     .m                (1,1) Total mass (kg)
                     .n                (1,1) Wire turns
                     .rTorquer         (1,1) Radius of the torquer
References and(), Demo(), DiameterAWG(), Dipole(), get(), length(), MagneticTorquerDesign(), MagneticTorquerDipoleMoment(), ResistanceAWG(), and zeros().
Referenced by MagneticTorquerDesign().
MagneticTorquerDipoleMoment()
function MagneticTorquerDipoleMoment (in l, in r, in muR, in n, in i)
 For an air coil set muR = 1.
 Type MagneticTorquerDipoleMoment for a demo.
 Since version 9.
Form
 m = MagneticTorquerDipoleMoment( l, r, muR, n, i )
Inputs
 l           (1,1)   Torquer length (m)
 r           (1,1)   Torquer radius (m)
 muR         (1,1)   Relative permeability
 n           (1,1)   Number of turns of wire
 i           (1,1)   Current (A)
Outputs
 m           (1,1)   Dipole moment (Amp-turns m^2);
Reference: http://mac6.ma.psu.edu/lionsat/TorquerCDRv5.html
References Demo(), Dipole(), isempty(), length(), MagneticTorquerDipoleMoment(), Plot2D(), and set().
Referenced by MagneticTorquerDesign(), and MagneticTorquerDipoleMoment().
MagTComp()
function MagTComp (in Isp, in r, in bMedian)
 Uses Ithaco data. This gives you and idea of when to use thrusters.
Form
 [massPerUnitTorque, massFlowPerUnitTorque, cTorquer] = MagTComp( Isp, r, bMedian )
Inputs
 Isp              (1,1)   Average specific impulse of the thrusters (sec)
 r                (1,1)   Average moment arm of the thrusters (m)
 bMedian          (1,1)   Median field (T)
Outputs
 massPerUnitTorque     (1,1)   Mass per unit torquer torque (kg/Nm)
 massFlowPerUnitTorque (1,1)   Fuel mass flow per unit torque (kg/year/Nm)
 cTorquer              (1,1)   Coefficients for the equation m = c0 + c1*torque + c2*torque^2 (Nm)
References and(), Dipole(), LeastSq(), MagTComp(), NewFig(), Plot2D(), XLabelS(), and YLabelS().
Referenced by MagTComp().
MagTorquer()
function MagTorquer (in action, in input)
Form
 output = MagTorquer( action, input )
 Arguments
 action         (1,:)    Action, 'initialize' or 'getTorque'
 action is 'getTorque'
 input          (.)    Data structure - each field is described below; the following sets of
 fields are allowed:
 {.bField},
 {.position, {.date OR .julianDate}, {.qECIToBody OR .mECIToBody} }
 {.position, {.date OR .julianDate}, .model, {.qECIToBody OR .mECIToBody}}
 {.position, {.date OR .julianDate}, .model, .modelInputs, {.qECIToBody OR .mECIToBody}}
 {.model, .modelInputs, {.qECIToBody OR .mECIToBody}}
 In addition, the fields .dipoleSign and/or {.current OR .curFunInputs} may be included
 for the input with any of the above combinations.
 .bField         (3,n)    Earth's magnetic field in the spacecraft body
 frame. If this field exists, then all others
 are ignored. (T)
 .position       (3,n)    Position in ECI (km)
 .date   (n,6) or structure  Date Time Array or Structure (see DTSToDTA for formats)
 .julianDate     (1,n)    Julian date
 .qECIToBody     (4,n)    Quaternion from ECI to spacecraft body frame
 .mECIToBody    (3,3,n)   Transformation matrix from ECI to spacecraft body frame
 .model         string    Name of the function that will compute the
 magnetic field. SCT functions that can be
 used are: 'BDipole', 'BMF', 'MagField'
 (function names are case sensative). User
 supplied models may also be specified.
 .modelInputs    {:}      Cell array containing any additional inputs
 needed for MagField or BMF, or all inputs for a
 custom model
 .dipoleSign     (m,1)    Sign of the dipole for each torquer initialized
 Can also be a non-unity constant to indicate
 a change in the magnitude of the dipole from
 value set at initialization
 .current        (m,1)    Current for each toruqer (A)
 .curFunInputs   {:}      Inputs for the current calculation function
 output        (3,n,m)   Magnetic torque in spacecraft body frame. n is the number of
 position vectors entered, m is the number of torquers that have
 been initialized. If n=1 but m>1, the output will be sqeezed to
 remove the middle dimension. Units depend on the units of the
 dipoles entered.
 action is 'initialize'
 input         (1,1)    Data structure - each field is described below; the following sets of
 fields are allowed:
 {.dipole},
 {.n, .area, .nTurns }
 {.n, .area, .nTurns, .mu }
 {.n, .area, .nTurns, {.current OR .currentFunction} }
 {.n, .area, .nTurns, {.current OR .currentFunction}, .mu }
 .dipole          (3,m)   Dipole moment for each torquer (Atm^2)
 .n               (3,m)   Unit vector in the direction of the
 dipole when positive current is applied
 .area            (1,m)   Coil area for each torquer (m^2)
 .nTurns          (1,m)   Number of turns for each torquer
 .mu              (1,m)   Core permeability for each torquer
 (default=1, is vaccuum) (dimensionless)
 .current         (1,m)   Current for each torquer (A)
 .currentFunction string  Name of a function to be called to
 calculate the current
 output        (1)      Number of dipoles initialized
ManeuverCostSphere()
function ManeuverCostSphere (in startNode, in nextNode, in d)
Finds the angular distance.
Form
 cost = ManeuverCostSphere( startNode, nextNode, d )
Inputs
 startNode (1,1) Id of start location
 nextNode  (1,1) Id of next location
 d         (1,1) Data structure
                 .rA    (1,:) Node right ascension (rad)
                 .dec   (1,:) Node declination  (rad)
Outputs
 cost      (1,1)  Angular distance
References Dot(), ManeuverCostSphere(), and RaDec2U().
Referenced by AStarAttitudeTrajectory(), and ManeuverCostSphere().
MBModel()
function MBModel (in inr, in h, in wo, in dT)
Computes the state space description of a momentum bias spacecraft where the internal momentum is fixed. If dT is not input it returns the continuous time plant. If dT is input it returns the discrete time plant. In either case, the plant is linearized about wo. The state vector is
 [thetax;thetay;thetaz;omegax;omegay;omegaz]
Where the state vector is with respect to the rotating frame defined by wo.
The outputs are the angles, i.e. the first three elements in the state vector.
If h and wo are not in the same direction or inr is not diagonal, dxdt will be nonzero and you will get constant disturbance torques.
If only one output is specified it gives the right hand side of the nonlinear dynamical equations of motion. You need to use the kinematics routines to get the nonlinear kinematics equations.
Form
 [a,b,c,d,dxdt] = MBModel(inr,h,wo)
 [a,b,c,d,dxdt] = MBModel(inr,h,wo,dT)
 [wDot]         = MBModel(inr,h,w,torque)
Inputs
 inr           (3,3)  Inertia matrix
 h             (3,1)  Internal momentum vector
 wo            (3,1)  Orbit rate vector
 dT            (*,1)  Sampling period (1) or torque vector (3)
Outputs
 a             (6,6)  Plant matrix
 b             (6,3)  Input matrix
 c             (3,6)  Output matrix
 d             (3,3)  Feedthrough matrix
 dxdt          (3,1)  Steady state derivative
 or
 wDot          (3,1)  State derivative
References and(), C2DZOH(), get(), isempty(), SkewSymm(), vector(), and zeros().
MeasEarthSensor()
function MeasEarthSensor (in x, in d)
The sensor frame assumes that z is normal to the focal plane.
The field "kQ" selects the quaternion from the state vector x. The field "kR" selects the spacecraft position. The outputs are angle about x (roll) and y (pitch) in the sensor frame.
If no inputs are given it will return the default data structure.
Form
 [y,valid] = MeasEarthSensor( x, d )
 d = MeasEarthSensor
Inputs
 x         (:,:)  State vector
 d         (1,1)  Data structure
                  .kQ            (1,4) Quaternion state
                  .kR            (1,3) Position state
                  .qBToS         (4,n) Body to earth sensor quaternion
                  .bias          (2,n) Bias
                  .scale         (2,n) Scale
                  .noise         (2,n) 1 sigma noise
                  .fOV           (1,1) Field of view
                  .quantization (1,1) Least significant bit
Outputs
 y         (n,1)   Measurements in counts
 valid     (1,n)   Data valid flag
References abs(), and(), MeasEarthSensor(), Measurements(), QForm(), quaternion(), U2AzEl(), Unit(), vector(), and zeros().
Referenced by MeasEarthSensor().
MeasMagnetometerEarth()
function MeasMagnetometerEarth (in x, in d)
 You enter a scale factor and a bias in the data structure.
 The noise field should be set to zero when this is used a part of a
 Kalman filter.
 The field "kR" selects the position, kQ selects the quaternion.
 It returns the body frame components of the magnetometer.
 qB transforms from the body to the sensor frame. There can be multiple
 sensors and multiple columns of qB, scale, bias and noise.
 This function uses BDipole
 If no inputs are given it will return the default data structure.
 Since version 11.
Form
 y = MeasMagnetometerEarth( x, d )
 d = MeasMagnetometerEarth
Inputs
 x         (n,1)  State vector
 d         (1,1)  Data structure
                  .kR            (1,3) Orbit ECI states
                  .kQ            (1,4) Quaternion
                  .qBToS         (4,n) Quaternion from body to Sensor
                  .jD            (1,1) Julian date
                  .scale         (3,n) Scale factor
                  .bias          (3,n) Bias
                  .noise         (3,n) 1 sigma noise
                  .quantization (1,1) LSB
Outputs
 y         (3*n,1)   Measurements in counts
References abs(), and(), BDipole(), JD2000(), MeasMagnetometerEarth(), Measurements(), QForm(), quaternion(), set(), vector(), and zeros().
Referenced by MeasMagnetometerEarth().
MeasRateGyro()
function MeasRateGyro (in x, in d)
 You enter a scale factor and a bias in the data structure.
 The noise field should be set to zero when this is used a part of a
 Kalman filter.
 The field "kW" selects the body rate from the state vector.
 qB transforms from the body to the sensor frame. There can be multiple
 sensors and multiple columns of qB, scale, bias and noise.
 If no inputs are given it will return the default data structure.
 Since version 11.
Form
 y = MeasRateGyro( x, d )
 d = MeasRateGyro
Inputs
 x         (n,1)  State vector
 d         (1,1)  Data structure
                  .kW            (1,3) Body rate
                  .qBToS         (4,n) Quaternion from body to Sensor
                  .scale         (3,n) Scale factor
                  .bias          (3,n) Bias
                  .noise         (3,n) 1 sigma noise
                  .quantization (1,1) LSB
Outputs
 y         (3*n,1)   Measurements in counts
References abs(), and(), MeasRateGyro(), Measurements(), QForm(), set(), vector(), and zeros().
Referenced by MeasRateGyro().
MeasRateIntegratingGyro()
function MeasRateIntegratingGyro (in x, in varargin)
 This can model a wide variety of rate integrating gyros.
 This must be called by the integrator as
 xDot = MeasRateIntegratingGyro( x, t, d )
 and to get the measurements
 y    = MeasRateIntegratingGyro( x, d )
 When called as a right hand side it only updates those states that are
 gyro states.
 You enter a scale factor in the data structure.
 The noise parameters should be set to zero if used as part of a
 Kalman filter.
 If no inputs are given it will return the default data structure.
 Since version 11.
Form
 xDot = MeasRateIntegratingGyro( x, t, d )
 y    = MeasRateIntegratingGyro( x, d )
 d    = MeasRateIntegratingGyro
Inputs
 x         (n,1)  State vector
 t         (1,1)  Time
 d         (1,1)  Data structure
                  .kRate         (1,m) Rate states
                  .kAngle        (1,m) Angle states
                  .kBias         (1,m) Bias states
                  .scale         (m,1) Scale factor
                  .noiseAngle     (m,1) 1 sigma angle noise
                  .noiseRate     (m,1) 1 sigma rate noise
                  .noiseBias     (m,1) 1 sigma bias noise
Outputs
 y         (m,1)   Measurements
 xDot      (m,1)   Derivatives
References and(), get(), length(), MeasRateIntegratingGyro(), Measurements(), set(), and vector().
Referenced by MeasRateIntegratingGyro().
MeasRelativePosition()
function MeasRelativePosition (in x, in d)
 You enter a scale factor and a bias in the data structure.
 The noise field should be set to zero when this is used a part of a
 Kalman filter.
 The field "k" selects the spacecraft position vector
 Each column of kT selects a target spacecraft.
 It returns the ECI relative position.
 If no inputs are given it will return the default data structure.
 Since version 11.
Form
 y = MeasRelativePosition( x, d )
 d = MeasRelativePosition
Inputs
 x         (n,1)  State vector
 d         (1,1)  Data structure
                  .k     (1,3) Position
                  .kT    (3,n) Target spacecraft
                  .scale (3,n) Scale factor
                  .bias  (3,n) Bias
                  .noise (3,n) 1 sigma noise
Outputs
 y         (3*n,1)   Measurements
References abs(), and(), MeasRelativePosition(), Measurements(), set(), vector(), and zeros().
Referenced by MeasRelativePosition().
MeasStarTracker()
function MeasStarTracker (in x, in d)
 The field "kQ" selects the quaternion from the state vector x.
 The output is the noisy ECI to body quaternion.
 This does not check for sun interference or eclipses.
 If no inputs are given it will return the default data structure.
 Since version 11.
Form
 y = MeasStarTracker( x, d )
 d = MeasStarTracker
Inputs
 x         (n,1)  State vector
 d         (1,1)  Data structure
                  .kQ    (1,4) Quaternion indices
                  .noise (3,1) 1 sigma noise in the sensor frame
                  .qBToS (4,n) Body to sensor quaternion
Outputs
 y         (4,n)   Measurements
References abs(), Eul2Q(), MeasStarTracker(), Measurements(), QMult(), QTForm(), quaternion(), QUnit(), vector(), and zeros().
Referenced by MeasStarTracker().
MeasState()
function MeasState (in x, in d)
 You enter a scale factor and a bias in the data structure.
 The noise field should be set to zero when this is used a part of a
 Kalman filter.
 The field "k" selects elements of the state vector x.
 This is useful for initial tests of control algorithms or estimators.
 The state vector can be any state vector of interest.
 If no inputs are given it will return the default data structure.
 Since version 11.
Form
 y = MeasState( x, d )
 d = MeasState
Inputs
 x         (n,1)  State vector
 d         (1,1)  Data structure
                  .k     (1,m) States to return
                  .scale (m,1) Scale factor
                  .bias  (m,1) Bias
                  .noise (m,1) 1 sigma noise
Outputs
 y         (m,1)   Measurements
References abs(), and(), length(), MeasState(), Measurements(), set(), vector(), and zeros().
Referenced by MeasState().
MeasSunSensorAnalog()
function MeasSunSensorAnalog (in x, in d)
 The output is modeled as
 m(1,1) + m(1,2)*cos(theta) + ... + m(1,n)*cos(theta)^(n-1)
 The field "kQ" selects the quaternion from the state vector x.
 If no inputs are given it will return the default data structure.
 Since version 11.
Form
 y = MeasSunSensorAnalog( x, d )
 d = MeasSunSensorAnalog
Inputs
 x         (:,1)  State vector
 d         (1,1)  Data structure
                  .kQ        (1,4) Quaternion state
                  .u         (3,n) Sun sensor eyes unit vectors
                  .m         (n,:) Sun sensor coefficients
                  .noise     (1,n) 1 sigma noise
                  .uSunECI    (3,1) Sun unit vector
Outputs
 y         (n,1)   Measurements
References MeasSunSensorAnalog(), Measurements(), quaternion(), and vector().
Referenced by MeasSunSensorAnalog().
MeasSunSensorDigital()
function MeasSunSensorDigital (in x, in d)
 The sensor frame assumes that z is normal to the focal plane.
 The field "kQ" selects the quaternion from the state vector x.
 The outputs are angle about x (roll) and y (pitch) in the sensor frame.
 The sun must be in the +z hemisphere.
 If no inputs are given it will return the default data structure.
Form
 y = MeasSunSensorDigital( x, d )
 d = MeasSunSensorDigital
Inputs
 x         (:,1)  State vector
 d         (1,1)  Data structure
                  .kQ            (1,4) Quaternion indices
                  .qBToS         (4,n) Body to sun sensor quaternion
                  .bias          (2,n) Bias
                  .scale         (2,n) Scale factor
                  .noise         (2,n) 1 sigma noise
                  .fOV           (1,1) Field of view
                  .quantization (1,1) Least significant bit
                  .uSunECI       (3,1) Sun unit vector
Outputs
 y         (n,1)   Measurements
 valid     (1,1)   True or vales
References abs(), and(), MeasSunSensorDigital(), Measurements(), QForm(), quaternion(), vector(), and zeros().
Referenced by MeasSunSensorDigital().
MolWt2R()
function MolWt2R (in molWt)
 Type MolWt2R for a demo.
 Since version 1.
Form
 r = MolWt2R( molWt )
Inputs
 molWt      (1,:)   Molecular weight (kg/mole). This can be read
                    directly from a periodic table. For example
                    H2 has a molecular weight of 0.002. He has a
                    molecular weight of 0.004.
Outputs
 r          (1,:)   Specific gas constant
References Constant(), Demo(), MolWt2R(), and Plot2D().
Referenced by AtmDens1(), AtmDensUranus(), BloDown(), BloDownMass(), CentrifugalCompressor(), CLCDFreeMolecular(), FAeroSurfaceAccommodation(), GasMass(), HeatTransferCoeffTaylor(), IdealRkt(), MolWt2R(), Pressure(), RamjetExternalHeatSource(), SpeedSnd(), TElec(), ThrusterColdGas(), and UE().
MomArm()
function MomArm (in r, in u, in c)
Form
 m = MomArm( r, u, c )
Inputs
 r                (3,:)   Position vectors
 u                (3,:)   Unit vectors in the force direction
 c                (3,1)   Center-of-mass location
Outputs
 m                (3,:)   Moment arms
References Cross(), set(), and Unit().
Referenced by SpinChange(), and SPMMnvr().
MoonEl()
function MoonEl (in jD)
These elements are only valid for short term use.
Form
 el = MoonEl( jD )
Inputs
 jD            (1,1)  Julian Date
Outputs
 el            (1,6)  Keplerian elements [a,i,L,w,e,M] (km,rad)
Reference: Montenbruck, O., T. Fleger, "Astronomy on the Personal Computer", Springer-Verlag, p 155. http://ssd.jpl.nasa.gov/?sat_elem
References JD2T().
Referenced by EarthMoon(), EarthMoonRotFrame(), and TransformLagrangePoints().
Moons()
function Moons (in name)
Form
 moons  = Moons( planetName )
 center = Moons( moonName )
Inputs
 name       (1,:)  Name of planet or moon
Outputs
 s       {:} or (1,:)  Cell array of moons or string name of planet center
References: Seidelmann, The Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992, pp.708-709.
Referenced by PlotLET(), PlotLET3BP(), SolarSystemProperties(), and SunVectorECI().
MoonV1()
function MoonV1 (in jd, in rSc)
 The earth-centered inertial frame is default or, if a spacecraft vector is
 input, the vector is in the spacecraft centered frame.
 This is the low precision model.
See also
MoonV2.
Form
 [u, r] = MoonV1( jd, rSc )
Inputs
 jd        (:)     Julian date
 rsc       (:)     Spacecraft vector in the ECI frame (km)
Outputs
 u         (3,:)   Unit moon vector
 r         (:)     Distance from origin to moon (km)
References: The 1993 Astronomical Almanac, U.S. Government Printing Office, p. D46.
References CosD(), Date2JD(), Mag(), MoonV2(), SinD(), Unit(), and vector().
Referenced by AlignThruster(), AttitudeProfileVis(), BarycenterEarthMoon(), EarthMoon(), EarthMoonRotFrame(), ECIToEarthMoonRot(), ECIToRLP(), FEarthMoon(), FEarthMoonSun(), FOrbitMultiSpacecraft(), FSailEarthMoon(), IsothermalLunar(), MoonECIElements(), MoonV2(), PlanetaryAccelerations(), PlotEMTraj(), RLagrange(), RMoonECI(), SailEphemAlmanac(), ThrusterAlignment(), TransformECIToEMBR(), TransformEMBRToECI(), and TransformLagrangePoints().
MoonV2()
function MoonV2 (in jD, in rSc)
 The earth-centered inertial frame is default or, if a spacecraft vector is
 input, the vector is in the spacecraft centered frame.
 This is the moderate precision model.
See also
MoonV1.
 Since version 1.
Form
 [u, r] = MoonV2( jD, rSc )
Inputs
 jd        (:)     Julian date
 rsc       (:)     Spacecraft vector in the ECI frame (km)
Outputs
 u         (3,:)   Unit moon vector
 r         (:)     Distance from origin to moon (km)
References: Montenbruck, O., T.Pfleger, Astronomy on the Personal Computer, Springer-Verlag, Berlin, 1991, pp. 103-111.
References Date2JD(), MoonV1(), Unit(), and vector().
Referenced by ECIToRLP(), MoonECIElements(), MoonV1(), NavTargetTrackingLunar(), OpticalNavLunarLandmarkStar(), and PropEph().
MSidDay()
function MSidDay (in jD)
 Since version 1.
Form
 d = MSidDay( jD )
Inputs
 jD              (1,:) Julian date (day)
Outputs
 d               (1,:) Mean sidereal day (solar days)
References: The Astronomical Almanac for the Year 1993, U.S. Government Printing Office,1993, p. B6.
References Date2JD(), and R2P5().
Referenced by EarthRte(), and GMSTime().
MSolDay()
function MSolDay (in jD)
 Since version 1.
Form
 d = MSolDay( jD )
Inputs
 jD             (1,:)    Julian date (day)
Outputs
 d              (1,:)    Mean solar day (sidereal days)
References: The Astronomical Almanac for the Year 1993, U.S. Government Printing Office, 1993, p. B6.
References Date2JD(), and R2P5().
Nadir()
function Nadir (in cant, in rho, in chordwidth)
 Since version 2.
Form
 n = Nadir( cant, rho, chordwidth )
Inputs
 cant       (1,1)   Sensor element cant angle from the spin-axis (rad)
 rho        (1,1)   Earth radius
 chordwidth (:)     Measured chordwidth (rad)
Outputs
 n          (2,:)   Nadir angles (rad)
 k          (1,:)   Valid chordwidths cooresponding to n
References and(), Nadir(), and Plot2D().
Referenced by ADGen(), AngleDetermination(), BHarm(), BTrans(), CW2Roll(), CwValid(), DHCWDX(), ESA(), ESACS(), HCw(), HCw2R(), KFSAAD(), MeasNadirStar(), NadGen(), Nadir(), PropEph(), ThrusterAlignment(), and ZCull().
NavigationCamera()
function NavigationCamera (in x, in d)
Assumes a pinhole camera model. It returns the pixel locations for the planet/moon/asteroid and any stars in the field of view. It also returns the chordwidth (diameter) of the planet/moon/asteroid.
You pass it the ECI vectors for the planets, moons or asteroids of interest. You load the star catalog data structure using LoadCatalog.
 d.starCatalog = LoadCatalog( 'Hipparcos' ); Hipparcos is the default.
 d.camera      = PinholeCameraStruct;
q may be an array of quaternions. It will animate the star field. You can use this as a star camera by setting d.xPlanet = [];
Type NavigationCamera to see a movie of stars changing as the camera rotates. The demo has the spacecraft at a distance of 50000 km from the center of the Earth. It is first looking at the moon then rotates to see the Earth.
Form
 d = NavigationCamera;  % data structure
 y = NavigationCamera( x, d )
Inputs
 x     (3,1) ECI position of sensor
 d      (.)  Data structure
             .xPlanet        (3,:)   Planet locations (km)
             .radiusPlanet   (1,:)   Planet radius (km)
             .namePlanet     {:}     Name of the planet
             .starCatalog       (.)     Star catalog data structure
             .camera         (.)     See PinholeStarCamera
             .q              (4,:)   Quaternion from ECI to the navigation camera
Outputs
 y     (.)   Measurement data structure
             .star     (.)   Star measurement data structure
             .planet   (2,:) Planet centroid
             .radius   (1,:) Planet radius (km)
             .ang      (1,:) Planet angular radius (rad)
             .uPlanet  (3,:) Unit vectors for the planets
             .outside  (1,1) 2 means planet visible, 1 means planet not
                             in camera fov
References and(), LoadCatalog(), NavigationCamera(), and PinholeCameraStruct().
Referenced by NavigationCamera(), and StarCameraViewer().
NavigationMeasurement()
function NavigationMeasurement (in r, in q, in jD, in d)
 frames are 'eci' and 'helio'
 type is 'chordwidth' 'star and center' 'star and horizon'
 'landmark' 'range' 'range rate'
 Type NavigationMeasurement for a demo.
Form
 [m, u] = NavigationMeasurement( r, q, jD, d )
Inputs
 r           (3,n)     Position (km)
 q           (4,n)     Quaternion from ECI to body
 jD          (1,n)     Julian date (day)
 d           (1,1)     Data structure
                       .rSensor       (3,1) Position of sensor (m)
                       .bBodyToSensor (3,3) Transforms from body frame
                                            to sensor frame
                       .bPlanetToECI  {n}   Transforms from planet frame
                                            to ECI frame
                       .radiusP       (3,1) Radius of planet (km)
                       .rCM           (3,1) Center of mass (m)
                       .omega         (3,1) Body rotation
                       .f             (1,1) Focal length(mm)
                       .v             (3,n) Velocity (km/s)
                       .rP            (3,n) Planet position (km)
                       .vP            (3,n) Planet velocity (km/s)
                       .omegaP        (3,1) Planet rotation vector
                       .uStar         (3,1) Star unit vector in ECI frame
                       .frame         (1,:) Sting for frame
                       .type          (1,:) String for type
Outputs
 m           (:,n)     Measurements
 u           (1,:)     Units
References and(), and NavigationMeasurement().
Referenced by NavigationMeasurement().
NavObservables()
function NavObservables (in r, in rP, in radiusP, in jD, in nameP, in nameM, in alb)
Form
 NavObservables;
 [c, a, f, m] = NavObservables( r, rP, radiusP, jD, nameP, nameM, alb )
Inputs
 r                 (3,:)   Trajectory (au)
 rP                (3,:,m) Planet trajectories (au)
 radiusP           (1,m)   Radius of the planets
 jD                (1,:)   Julian dates of trajectory points
 nameP             {1,m}   Planet names
 nameM             (1,:)   Mission name for plot titles
 alb               (1,m)   Albedo fractions for planets
 albF              (1,m)   Albedo fraction
Outputs
 c                 (m,:)   Chordwidths of planets and sun (rad)
 a                 (1,:)   Minimum planet angular separation (rad)
 f                 (m,:)   Power flux (W/m^2)
 m                 (1,:)   Range to nearest target (au)
References NavObservables(), and Trajectory().
Referenced by NavObservables().
NewtonianForceECI()
function NewtonianForceECI (in qECIToBody, in nBody, in a, in uECI, in rho)
The body is represented as unit outward normals and corresponding areas.
Form
 f = NewtonianForceECI( qECIToBody, nBody, a, uECI, rho )
Inputs
 qECIToBody      (4,:)  Quaternion from ECI to Body
 nBody           (3,n)  Normals in the body frame
 a               (1,n)   Corresponding areas (m^2)
 uECI            (3,:)   Velocity vector (km/s)
 rho             (1,:)   Atmospheric density (kg/m^3)
Outputs
 force           (3,:)  Force (N)
References and(), AU2Q(), Demo(), length(), Mag(), NewtonianForceECI(), Plot2D(), StdAtm(), vector(), and zeros().
Referenced by NewtonianForceECI().
NPSPM()
function NPSPM (in pulsewidth, in t, in h, in s, in spinRate, in uSun, in rAI, in decI, in rAF, in decF, in tauRise, in tauFall)
 Includes arc efficiency.
 Since version 1.
Form
 [delay, pulses, prec, azimuth, dTheta] = NPSPM(pulsewidth,t,h,s,spinRate,
 uSun,rAI,decI,rAF,decF,tauRise,tauFall)
Inputs
 pulsewidth   (1,1)     Pulsewidth (sec)
 t            (3,n)     Torque vectors of thrusters
 h            (3,1)     Momentum vector
 s            (3,1)     Sensor pulse axis
 spinRate     (1,1)     Spin rate (rad/sec)
 uSun         (3,1)     Sun Vector
 rAI          (1,1)     Initial right ascension (rad)
 decI         (1,1)     Initial declination (rad)
 rAF          (1,1)     Final right ascension (rad)
 decF         (1,1)     Final declination (rad)
 tauRise      (1,1)     Rise time constant
 tauFall      (1,1)     Fall time constant
Outputs
 delay        (1,1)     Delay (sec)
 pulses       (1,1)     Number of pulses
 prec         (1,1)     Precession angle
 azimuth      (1,1)     Maneuver azimuth (rad)
 dTheta       (1,1)     Precession per pulse (rad)
References abs(), ArcEff(), Delay(), EffPw(), PPDelay(), RLP(), vector(), and zeros().
Referenced by SPMMnvr().
NRLArray()
function NRLArray (in variant, in display, in d)
Has two variants. Array A has 2 panels while B has 4.
Form
 d = NRLArray( variant, display, d )
Inputs
 variant     (1,1)      'A', 'B'
 display     (1,1)      1 or 0
 d           (1,1)
                       .panelLength (1,1) Length of each panel
                       .panelWidth  (1,1) Width of each panel
                       .nPanels     (1,1) Number of panels
Outputs
 d           (1,1)
                       .panelLength  (1,1) Length of each panel
                       .panelWidth   (1,1) Width of each panel
                       .nPanels      (1,1) Number of panels
                       .arrayLength  (1,1) Array total length
                       .arrayWidth   (1,1) Array total width
                       .LReflect     (1,1) Reflector length
                       .LOverS       (1,1) Reflector length/panel width
                       .reflectRatio (1,1) Ratio of relflector to panel
                       .alpha        (1,1) Reflector angle
                       .effSolar     (1,1) Solar conversion efficienty
                       .cellPack     (1,1) Cell packing density
                       .reflectEff   (1,1) Reflector efficiency
                       .area         (1,1) Total area
                       .power        (1,1) Total power
                       .wattsPerMSq  (1,1) W/m^2
                       .kgPerWatt    (1,1) kg/W
                       .mass         (1,1) Total mass
See also
SASCAD
References and(), length(), NRLArray(), and Panel().
Referenced by NRLArray().
NutationMWA()
function NutationMWA (in iX, in iZ, in hMWA)
This is based on the assumption that wheel is aligned with Y, though you can use any combination. The body rates are assumed zero.
Form
 omega = NutationMWA( iX, iZ, hMWA )
Inputs
 iX    (1,1) X inertia (kg-m^2)
 iZ    (1,1) Z inertia (kg-m^2)
 hMWA  (1,1) Momentum wheel momentum (Nms)
Outputs
 omega  (1,:) Nutation frequency (rad/s)
References Demo(), Frequency(), NutationMWA(), and Plot2D().
Referenced by NutationMWA().
NutDelta()
function NutDelta (in T)
 From the 1980 IAU Nutation series.
 Since version 1.
Form
 [deltaPsi, deltaEps] = NutDelta( T )
Inputs
 T           (1,1) Julian centuries of 86400s dynamical time from j2000.0
Outputs
 deltaPsi    (1,1) The change in longitude due to nutation (degrees)
 deltaEps    (1,1) The change in obliquity due to nutation (degrees)
References: Seidelmann, The Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992. Sec. 3.222, "1980 IAU Theory of Nutation and Reduction", p. 111
References and(), CosD(), Date2JD(), JD2T(), series(), and SinD().
Referenced by EarthNut(), and EOfE().
ObOfE()
function ObOfE (in T)
 (with respect to the mean equator of date)
 Rounds to 6 decimal places.
Form
 x = ObOfE( T )
Inputs
 T  (1,:)  Julian centuries of 86400s dynamical time from j2000.0
Outputs
 x  (1,:)  The obliquity of the ecliptic (degrees)
References: The Astronomical Almanac for the Year 1993, U.S. Government Printing Office, 1993, p. B18.
References Date2JD(), JD2T(), and ObOfE().
Referenced by EarthNut(), EOfE(), and ObOfE().
Optic2D()
function Optic2D (in h, in u)
 h.boresight     (3,1)    Boresight axis in the body frame
 h.yAxis         (3,1)    yAxis of the focal plane in the body frame
 h.xWidth        (1,1)    X width of the focal plane
 h.yWidth        (1,1)    Y width of the focal plane
 h.focalLength   (1,1)    Focal length
 h.noise1Sigma   (1,1)    1 sigma noise
 h.xBias         (1,1)    Bias
 h.yBias         (1,1)    Bias
 Since version 2.
Form
 x = Optic2D( h, u )
Inputs
 h             (:,:)  Data structure for the sensor
 u             (3,:)  Unit vectors for the targets
Outputs
 x             (:,:)  Focal plane coordinates
References abs(), isempty(), length(), U2FP(), and Unit().
OpticalSurfaceProperties()
function OpticalSurfaceProperties (in s)
s is a cell array of strings. It returns a cell array of data structures. For example:
 struct( 'sigmaT', 0, 'sigmaA', 0.00, 'sigmaD', 0.71 , 'sigmaS', 0.29 )
Available materials are found by typing OpticalSurfaceProperties
Form
 p = OpticalSurfaceProperties( s )
Inputs
 s                 {:} Cell array of materials
Outputs
 p                 (:) Data structure array
                       .sigmaT (1,1) Transmitted
                       .sigmaA (1,1) Absorbed
                       .sigmaD (1,1) Diffuse reflection
                       .sigmaS (1,1) Specular reflection
References and(), length(), ListCases(), and OpticalSurfaceProperties().
Referenced by CreateComponent(), CubeSatDisturbanceAnalysis(), OpticalSurfaceProperties(), and TubeSatDefaultDataStructure().
OrbitDisplayPlugIn()
function OrbitDisplayPlugIn (in action, in modifier, in hFig, in position, in planet)
To initialize type:
 x = OrbitDisplayPlugIn;
Select the type of plot and then type
 OrbitDisplayPlugIn( 'draw', get( h, 'tag' ), r, jD, planet );
where r is a cell array of orbit runs, each (3,:), and jD is a (1,:). If planet is omitted the Earth will be used.
Form
 x = OrbitDisplayPlugIn( action, modifier, hFig, position, planet )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifer     (1,:)  Modifier to the action
 hFig        (1,1)  Handle to the figure or if 'draw' is r (cell array)
 position    (1,4)  [left bottom width height] or if 'draw' is jD
 planet      (1,:)  Planet name (optional).
Outputs
 x           (1,1)  Output. On 'initialize' this is the tag
References and(), CloseFigure(), get(), GetH(), Initialize(), isempty(), OrbitDisplayPlugIn(), and PutH().
Referenced by OrbitDisplayPlugIn().
Parallax()
function Parallax (in rT, in rO)
Computes the parallax of a target when viewed by an observer offset from the origin of the reference frame.
Form
 [u, parallax] = Parallax( rT, rO )
Inputs
 rT        (3,1)   Position vector of the target
 rO        (3,1)   Position vector of the observer
Outputs
 u         (3,1)   Unit vector to the target
 parallax  (1,1)   Parallax (rad)
References Parallax(), Unit(), and vector().
Referenced by DisplayCatalog(), LoadCatalog(), LoadFK5(), Parallax(), SortFK5(), and StarMap().
ParseCommand()
function ParseCommand (in s, in d)
The command string is 'timetag command modifier data' A command can have a modifer with data or just data
Form
 [timeTag, command, index, data] = ParseCommand( s, d )
Inputs
 s      (1,:)   Command string
 d      (1,1)   Data structure describing the commands
                 .command        {:}   List of commands
                 .commandModifer (1,:) 1 if there is a modifier
                 .commandData    (1,:) 1 if there is data
Outputs
 timeTag (1,:)   Command time tag
 command    (1,:)   Command
 index   (1,1)   Command index
 data    (1,1)   Command data
PBudget()
function PBudget (in errors, in desc, in categ, in aZ, in eL, in file)
 Terms will be RSS'd within categories and categories will be added.
 Since version 1.
Form
 [cep, r, s, t, cList] = PBudget( errors, desc, categ, aZ, eL, file )
Inputs
 errors          (n,3)  Error contributions [roll,pitch,yaw] (3 sigma)
 desc            {n}    Descriptions of the error contributions
 categ           {n}    Categories
 aZ                     Azimuth of beam (deg)
 eL                     Elevation of beam (deg)
 file                   File name for printed budget
Outputs
 cep             (1,1)  Circular error (0.99865)
 r               (2,1)  Azimuth and elevation errors
 s               (m,3)  Summary by category (m = number of categories)
 t               (1,3)  Totals
 cList            {m}  Categories corresponding to s
Reference: Brown and Hwang, Introduction to Random Signals and Applied Kalman Filtering, 2nd Edition. Page 30, 3 sigma. Page 54, Rayleigh distribution.
References and(), and PBudget().
Referenced by PBudget().
PCentr()
function PCentr (in taur, in tauf, in pulsewidth)
If there are no outputs it creates a plot.
Form
 [tc, u] = PCentr( taur, tauf, pulsewidth )
Inputs
 taur             (1,1) Rise time constant (sec)
 tauf             (1,1) Fall time constant (sec)
 pulsewidth       (1,1) Pulsewidth (sec)
Outputs
 tc               (1,1) Time from start of pulse to centroid (sec)
 u                (1,1) Effective pulsewidth (sec)
References Centroid(), and Plot2D().
Referenced by PPDelay().
PermanentMagnetRHS()
function PermanentMagnetRHS (in x, in t, in d)
Form
 [xDot,torque,bFBody] = PermanentMagnetRHS( x, t, d )
Inputs
 x             (7,1)   State vector [qEB; wB]
 t             (1,1)   Time (seconds from Julian date epoch d.jD0)
 d              (.)    Data structure with jD0, inertia, mu, t, r
Outputs
 xDot          (7,1)   State derivatives
 torque        (3,1)   Torque applied
 bFBody        (3,1)   Earth magnetic field in body frame
References BDipole(), Cross(), Date2JD(), GravityGradientFromR(), QForm(), QIToBDot(), RVOrbGen(), and vector().
PID3Axis()
function PID3Axis (in q_ECI_body, in d)
Includes windup compensation. Use the reset flag to reset the controller states stored in the data structure. This is an incremental controller limited to the specific maximum angle per step. The torque output is computed from the inertia matrix and acceleration vector, T = -I*a
This has 4 modes:
 0 - steady rotation about an axis ('axis')
 1 - align two vectors ('align')
 2 - align with a quaternion ('quat')
 3 - point vector and steady rotation ('point')
Use the call with one output to get the default data structure. Type PID3Axis for a demo. See also PIDMIMO for computing the gains.
 Forms:
 PID3Axis;   % demo
 d = PID3Axis;   % data structure, uses PIDMIMO
 [torque, d] = PID3Axis( q_ECI_body, d )
Inputs
 q_ECI_body (4,1) ECI to body quaternion
 d           (.)  Data structure
                  .a               (2,2) PID A Matrix
                  .b               (2,1) PID B Matrix
                  .c               (1,2) PID C Matrix
                  .d               (1,1) PID D Matrix
                  .inertia         (3,3) Inertia matrix
                  .x_roll          (2,1) PID roll state
                  .x_yaw           (2,1) PID yaw state
                  .x_pitch         (2,1) PID pitch stage
                  .reset           (1,1) Reset flag (T/F)
                  .mode      (1,1) or '' Four options:
                                         Mode 0 = rotate about an axis, 'axis'
                                         -requires d.q_desired_state
                                                   d.angle / d.axis
                                         Mode 1 = align two vectors, 'align'
                                         -requires d.eci_vector
                                                   d.body_vector
                                         Mode 2 = quaternion, 'quat'
                                         -requires d.q_desired_state
                                         Mode 3 = point with rotation, 'point'
                                         -requires d.eci_vector
                                                   d.angle / d.axis
                                                   d.body_vector
                  .l               (2,1) Windup compensation matrix
                  .accel_sat       (1,1) Saturation acceleration
                  .max_angle       (1,1) Maximum incremental angle
        .         .q_target_last   (4,1) Last target
                  .q_desired_state (4,1) Target quaternion  (mode 0 and 2)
                  .body_vector     (3,1) Axis in body frame (mode 1 and 3)
                  .eci_vector      (3,1) Axis in ECI frame  (mode 1 and 3)
                  .angle           (1,1) Angle of rotation  (mode 0 and 3)
                  .axis            (3,1) Axis of rotation   (mode 0 and 3)
Outputs
 torque     (3,1) Control torque
 d           (.)  Data structure with control states
See also
: AU2Q, U2Q, PIDMIMO
References and(), AU2Q(), DefaultData(), Demo(), get(), PID(), PID3Axis(), PIDMIMO(), quat(), quaternion(), U2Q(), vector(), and Windup().
Referenced by AttitudeTarget(), LandingControlBilinear(), LunarLandingControl(), PID3Axis(), and SailACS().
PivotMch()
function PivotMch (in k, in b, in l, in x0, in steps)
 The pivot has a stepping motor with a gear train that drives a lead screw.
 The lead screw is attached to the pivot platform be means of an arm. The
 resulting curve is nonlinear so the designer should pick zero to be in the
 most linear region.
 If no inputs are entered the routine will design a pivot mechanism.
 Since version 1.
Form
 [theta,k,b,l,x0] = PivotMch(k,b,l,x0,steps)
Inputs
 k            (1,1)  Steps to meters of lead screw movement
 b            (1,1)  Arm length
 l            (1,1)  Pivot platform length
 x0           (1,1)  Initial height of b attachment to lead screw
 steps        (1,1)  Number of steps
Outputs
 theta       (1,1)  Pivot angles
 k            (1,1)  Steps to meters of lead screw movement
 b            (1,1)  Arm length
 l            (1,1)  Pivot platform length
 x0           (1,1)  Initial height of b attachment to lead screw
References and(), length(), and Plot2D().
PlanetPosition()
function PlanetPosition (in action, in d)
The frame is heliocentric, i.e. xy-plane is the mean earth's orbital plane. This function uses persistent variables to store the planet elements obtained from Planets during the initialization call.
You may use EITHER multiple planet IDs OR multiple dates when using this function, but not both.
Form
 [r, mu, v] = PlanetPosition( action, d )
 PlanetPosition( 'initialize', ids )
 [r, mu, v] = PlanetPosition( 'update', jD )
Inputs
 action    (1,:)       'initialize' or 'update'
 d         (1,n)       Julian date (days) for update or planet ids (1-9) for
                       initialize
Outputs
 r         (3,n)       Planetary position vectors
 mu        (1,n)       Corresponding gravitational parameters
 v         (3,n)       Velocity vectors
See also
: Planets, SolarSys
References and(), and PlanetPosition().
Referenced by PlanetPosition(), SailEphemAlmanac(), and TerrestrialSolarFlux().
PlanetRotation()
function PlanetRotation (in planet)
Note that Venus, Uranus, and Pluto have retrograde (negative) rotations.
 Forms:
 wP = PlanetRotation( planet )
Inputs
 planet   (1,:)    Name of planet
Outputs
 wP       (1,1)    Rotation rate, rad/s
Reference: Clabon Walter Allen and Arthur N. Cox (2000). Allen's Astrophysical Quantities. Springer. p. 296. via Wikipedia
References and(), ListCases(), and PlanetRotation().
Referenced by PlanetEnvironment(), and PlanetRotation().
Planets()
function Planets (in units, in k)
Has functions for the orbital elements of the planets in the heliocentric frame (ecliptic plane). The elements are row vectors as follows:
 a = [   a1 a0] semi-major axis
 e = [   e1 e0] eccentricity
 i = [   i1 i0] inclination
 W = [   W1 W0] longitude of the ascending node
 w = [   w1 w0] argument of perigee
 L = [L2 L1 L0] mean longitude: L2 is revolutions per century
where
 x = b1*T + b0 where T is Julian Centuries from J2000.0
and bi is a coefficient. Output of the angular quantities is either in degrees or radians.
If one output is specified it will be a data structure containing the planet information.
Type Planets for a demo. See SolarSys for computing planet locations.
Form
 Planets;               % demo
 planetList = Planets;  % list of planets
 [name, a, e, i, W, w, L, jDRef, mu, m, radius] = Planets( units, k )
 d = Planets( units, k )  % output a data structure array
Inputs
 units           (1,3) Angular units ('deg' or 'rad')
 k         (1,1) or {} Planet IDs, if not input get all nine;
                       can be a cell array
Outputs
 name            (n,:) Name of planet
 a               (n,2) Mean distance (au)
 e               (n,2) Eccentricity
 i               (n,2) Inclination wrt ecliptic plane (units)
 W               (n,2) Longitude of ascending node wrt vernal equinox (units)
 w               (n,2) Argument of perhelion (units)
 L               (n,3) Mean longitude (units)
 jDRef           (1,1) Reference Julian date
 mu              (n,2) Gravitational parameter (km^3/s^2)
 m               (n,1) Mass  (kg)
 radius          (n,1) Radius (km)
   - OR -
 d                (:)  Data structure array with above fields
 n is the number of planets
References: Seidelmann, P. K., ed., Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992. Table 5.8.1. p. 316.
References and(), Planets(), and SolarSys().
Referenced by CostLowThrust2D(), CostSail3D(), GroundTrackErrorBudget(), HelioFromPlanetInit(), HelioPlot(), Isothermal(), JDStartTransfer(), NavTargetTrackingPlanetary(), OpticalNavAccuracy(), OpticalNavPlanetStarNoiseMatrix(), PlanetAlignments(), PlanetaryRadiationAndAlbedo(), PlanetHelioPhase(), PlanetOpposition(), Planets(), PlanetTransferLambert(), PlanetYear(), PorkChopTOF(), PorkChopTOFKepler(), PropagateLowThrust(), RHSHelioWithPlanets(), RHSTrajectory(), SolarSysState(), SolarSystemElements(), SunVectorECI(), SynodicPlanets(), and VDA().
PlanetSensorDualScan()
function PlanetSensorDualScan (in r, in q, in d)
This function models a dual scan earth sensor. It has two sensors at different roll angles. It measures the chordwidth given by the two scans and then uses that to compute roll and pitch. The offset of the scan from vertical axis determines pitch. It also computes a standard, the average of the two so that if one scan is off the Earth it can still produce roll and pitch angles. It updates d each time it is called. The standard chord is updated sequentially wih each sample.
Type PlanetSensorDualScan for a demonstration of a spacecraft in geosynchronous orbit.
Form
 d =  PlanetSensorDualScan;
 [roll, pitch, d] = PlanetSensorDualScan(r, q, d)
Inputs
 r         (3,:)   Position vector in the ECI frame (km)
 q         (4,:)   Quaternion ECI to Body
 d         (.)     Sensor data structure
                   .cant     (2,1) Cant angle from rotation axis (rad)
                   .sC       (1,1) Standard chord  (rad)
                   .uB       (3,1) Boresight vector
                   .uS       (3,1) Scan vector
                   .aP       (1,1) Planet radius
                   .sig      (1,1) 1 sigma chordwidth noise
                   .useScan  (2,1) true if use that scan
                   .valid    (1,:) true if data is valid
Outputs
 roll      (1,:)   Roll (rad)
 pitch     (1,:)   Pitch (rad)
 d         (.)     Sensor data structure
References and(), Cross(), DefaultDataStructure(), Demo(), Mag(), PlanetSensorDualScan(), QForm(), Unit(), vector(), and zeros().
Referenced by PlanetSensorDualScan().
PlanetYear()
function PlanetYear (in k)
Uses Planets for the semi-major axes, which uses the Astronomical Almanac.
Type PlanetYear for a demo.
Form
 y = PlanetYear( k )
Inputs
 k       (1,:) Planet id
Outputs
 y       (1,1) Fraction of Earth year
References Constant(), Demo(), DispWithTitle(), length(), Period(), Planets(), PlanetYear(), and zeros().
Referenced by PlanetTrajectoryPlot(), and PlanetYear().
PlotHysteresis()
function PlotHysteresis (in B, in H)
 Minor loops are dotted. H may have the same number of rows as B
 or have only one row.
Form
 PlotHysteresis( B, H )
Inputs
 B        (m,n)   B Field 1 major loop, m-1 minor loops
 H        (m,n)   H Field 1 major loop, m-1 minor loops
Outputs
 None
References Demo(), PlotHysteresis(), XLabelS(), and YLabelS().
Referenced by PlotHysteresis().
PlotPlanet()
function PlotPlanet (in r, in radius, in color, in noLines, in n)
The planet will be a solid color sphere. The color may be input as a structure with color data and a texture map, see Earth.mat
Form
 hSurf = PlotPlanet( r, radius, color, noLines )
Inputs
 r        (3,1)     Location of planet in figure frame
 radius   (1,1)     Planet radius
 color    (1,1)     Color, i.e. 'y', 'b' or [R G B], OR structure
                      .planetMap
                      .planetColorMap
 noLines  (1,1)     Flag to skip the lat/lon lines
 n        (1,1)     Number of divisions
Outputs
 hSurf    (1,1)     Handle to surface object
See also
Map
References and(), isempty(), Map(), NewFig(), PlotPlanet(), set(), and Watermark().
Referenced by CubeSatDisturbanceAnalysis(), DrawPatch(), DrawSailAttitude(), GPSSatellite(), LowThrustSim(), LunarHalo(), OrbTrack(), OrbTrackECI3D(), PlotPlanet(), PltOrbit(), SpaceCamera(), ThermalImager(), and WalkerConstellation().
PlotPlanetOrbit()
function PlotPlanetOrbit (in xECI, in jD, in objName, in planet, in eCIFlag)
Adds time tags to the trajectory at suitable intervals. Planet must be match a mat-file on the path. If the .mat file does not exist it will not draw the planet. For example, for a planet-fixed plot around Mars:
 PlotPlanetOrbit( [rECI;vECI], jD, 'Spacecraft', 'Mars' )
For a time-tagged ECI plot around Earth:
 PlotPlanetOrbit( [rECI;vECI], jD, 'Spacecraft', 'Earth', true )
For a simple multi-spacecraft ECI plot:
 PlotPlanetOrbit( {r1,r2} )
Type PlotPlanetOrbit for a Mars planet-fixed demo.
Form
 PlotPlanetOrbit( xECI, jD, objName, planet, eCIFlag )
Inputs
 xECI      (6*n,:)  [r;v;r;v;...] ECI frame orbits (km,km/s)
        or
            {n}     Cell array of state matrices for multiple satellites
 jD        (1,:)    Julian date array (days)
 objName   {n}      Object names, if empty Spacecraft 1, etc
 planet    (1,:)    Planet name, corresponding to a mat-file ('mars')
 eCIFlag   (1,1)    If true plot in ECI coordinates (default false)
Outputs
 None
See also
ECIToPlanet, PlotPlanet, TimeLabl
References PlotPlanetOrbit().
Referenced by EarthEnvironment(), PlotPlanetaryOrbit(), and PlotPlanetOrbit().
PltOrbit()
function PltOrbit (in el, in jD, in uSpin, in planet)
The input is a set of Kepler elements and a Julian date. It also plots the line of nodes and the line between apogee and perigee, and, optionally, a spin axis located at the beginning of the orbit.
Specify a planet name to use SunVectorECI instead of SunV1.
Has two built-in demos, one for an Earth orbit and one for Mars.
Form
 h = PltOrbit( el, jD, uSpin, planet )
Inputs
 el            (1,6)   Orbital elements [a i W w e M]
 jD            (1,1)   Julian date
 uSpin         (3,1)   Spin axis (optional)
 planet        (1,:)   Planet name (optional)
Outputs
 h             (1,1)   Figure handle
See also
: SunV1, SunVectorECI, PlotPlanet, AxesCart, Axis3D
References abs(), and(), AxesCart(), Axis3D(), Constant(), CP2I(), Date2JD(), E2Nu(), El2RV(), Equal(), isempty(), M2EEl(), NewFig(), PlotPlanet(), PltOrbit(), set(), square(), SunV1(), SunVectorECI(), vector(), Watermark(), and zeros().
Referenced by PlanetEnvironment(), PlanetOptimalTraj(), PltOrbit(), and TransferOrbit().
PlugInDemo()
function PlugInDemo (in action)
Inputs
 action      GUI callback action
Outputs
 None
References GetH(), and Initialize().
PointCameraModel()
function PointCameraModel (in camera, in rBody, in qBody, in distance)
 The distance to the viewed object is required.
 Uses the camera boresight and position in the body frame.
 All vectors must be in the same units, i.e. m.
See also
CameraDatabase, PointCameraDemo.
 Since version 8.
Form
 [position,target,up,angle] = PointCameraModel(camera,rBody,qBody,distance)
Inputs
 camera        (:)       Camera model constructed using the database
 rBody        (3,1)      Location of body (with camera attached) in scene
 qBody        (4,1)      Quaternion from scene to body frame
 distance     (1,1)      Distance from camera to scene
Outputs
 position     (1,3)      Position for axes CameraPosition property
 target       (1,3)      Target direction for axes CameraTarget property
 up           (1,3)      Up for axes CameraUpVector property
 angle        (1,1)      Angle in deg for axes CameraViewAngle property
References and(), AngleOfView(), CameraDatabase(), isempty(), length(), PointCameraModel(), QTForm(), quaternion(), and square().
Referenced by PointCameraModel().
PointingBudgetGUI()
function PointingBudgetGUI (in action, in tag)
 Simply type PointingBudgetGUI to initialize the interface.
Form
 PointingBudgetGUI( action, tag )
Inputs
 action                 Code from the graphical user interface
 tag                    Tag identifying the GUI
Outputs
 None
References CreateCallback(), get(), Initialize(), Parameter(), and PointingBudgetGUI().
Referenced by PointingBudgetGUI().
PointingBudgetLatex()
function PointingBudgetLatex (in errors, in desc, in categ, in aZ, in eL, in file)
 Terms will be RSS'd within categories and categories will be added.
 Since version 10.
Form
 [cep, r, s, t, cList] = PointingBudgetLatex( errors, desc, categ,
 aZ, eL, file )
Inputs
 errors          (n,3)  Error contributions [roll,pitch,yaw] (3 sigma)
 desc            {n}    Descriptions of the error contributions
 categ           {n}    Categories
 aZ                     Azimuth of beam (deg)
 eL                     Elevation of beam (deg)
 file                   File name for printed budget
Outputs
 cep                    Circular error (0.99865)
 r               (2,1)  Azimuth and elevation errors
 s               (m,3)  Summary by category (m = number of categories)
 t               (1,3)  Totals
 cList           (m,:)  Categories corresponding to s
See also
: PBudget
PointSpreadFunction()
function PointSpreadFunction (in u)
Computes the point spread function as a function of u for a circular aperture where u is kar/R and a is the aperture radius, k is the wave number (2pi/lambda) and R is the distance between the projection and the aperture.
Form
 i = PointSpreadFunction( u )
Inputs
 u         (:)     Argument
Outputs
 i            (:)     Intensity
References: Hecht, E. Optics, p. 419.
References and(), and PointSpreadFunction().
Referenced by PointSpreadFunction().
PowerDesign()
function PowerDesign (in el, in jD, in power, in battery, in solarArray)
Only the type fields are needed on input. Type PowerDesign for a demo. Creates a plot and prints output data to the command window.
Form
 PowerDesign;     % demo
 [battery, solarArray] = PowerDesign( el, jD, power, battery, solarArray )
Inputs
 el              (1,6)   Orbital elements
 jD              (1,1)   Julian date
 power           (1,1)   Average power
 battery         (.)     Battery data structure
                          .type     (1,:) Battery type
                          .capacity (1,1) Capacity
                          .mass     (1,1) Mass of the battery
                          .volume   (1,1) Volume of the battery
 solarArray      (.)     Solar array datastructure
                          .tracking (1,:) '1 DOF' '2 DOF' 'fixed'
                          .type     (1,:) Array type
                          .power    (1,1) Required power
                          .area     (1,1) Solar array area
Outputs
 battery         (.)      Battery data structure
 solarArray      (.)      Solar array data structure
References and(), Dot(), Eclipse(), ESA(), FindSolsticeOrEquinox(), length(), Period(), Plot2D(), PowerDesign(), Product(), QForm(), QLVLH(), RVFromKepler(), SunV1(), and zeros().
Referenced by PowerDesign().
PPDelay()
function PPDelay (in azimuth, in pulsewidth, in t, in h, in s, in spinRate, in tauRise, in tauFall)
 Computes the delay from the sun sensor pulse given the spin-axis,
 sensor boresight and the thruster torque axis. The delay is measured
 from the time the sensor sees the sun to the time the thruster must
 fire.
Form
 [delay, w] = PPDelay( azimuth, pulsewidth, t, h, s, spinRate, tauRise, tauFall )
Inputs
 azimuth        (1,1)   Azimuth of maneuver
 pulsewidth     (1,1)   Pulsewidth (sec)
 t              (3,1)   Torque vector
 h              (3,1)   Momentum vector
 s              (3,1)   Sensor pulse axis
 spinRate       (1,1)   Spin rate (rad/sec)
 tauRise        (1,1)   Rise time constant
 tauFall        (1,1)   Fall time constant
Outputs
 delay          (1,1)   Delay (sec)
 w              (1,1)   Angular rate vector (rad/sec)
References abs(), and(), Cross(), Delay(), PCentr(), and vector().
Referenced by NPSPM().
PropellantMass()
function PropellantMass (in V, in R, in T, in rhoFuel, in pMax, in pMin)
The following equation is used: p = R*(mPressurant*T)/(V-mFuel/rhoFuel)
 where p is the pressure, R is the gas constant of the pressurant, V is the
 tank volume, and rhoFuel is the density of the fuel.
 The mass of the pressurant is found by setting p=pMin and mFuel=0.
 The total mass of the fuel is then found by solving the above equation
 for "mFuel".
 Helium gas constant:       2079 J/(kg*K)
 Hydrazine density:         1010 kg/m^3
 Convert PSI-to-metric:     1 PSI = 6895 N/m^2
Form
 [mFuel,mPressurant] = PropellantMass( V, R, T, rhoF, pMax, pMin );
Inputs
 V             (1,1) Tank volume (m^3)
 R             (1,1)    Gas constant of pressurant (J/kg/K)
 T             (1,1) Temperature (K)
 rhoFuel       (1,1) Density of fuel (kg/m^3)
 pMax          (1,1) Maximum pressure (N/m^2)
 pMin          (1,1) Minimum pressure (N/m^2)
Outputs
 mFuel         (1,1) Mass of the propellant (kg)
 mPressurant   (1,1)    Mass of the pressurant (kg)
References and(), isempty(), and PropellantMass().
Referenced by PropellantMass().
PWMSeq()
function PWMSeq (in m, in dT, in x, in dTSeq, in wDither)
If no outputs are specified it will plot the sequence.
Form
 [tPWM, tSign, xPWM] = PWMSeq( m, dT, x, dTSeq, wDither )
Inputs
 m         (1,1)   Magnitude
 dT        (1,1)   Sampling rate
 x         (n)     Input sequence
 dTSeq     (1,1)   Sampling time for the input sequence
 wDither   (1,1)   If add triangle wave dither to the output
Outputs
 tPWM      (n)     Times for each pulse at each dTSeq
 tSign     (n)     Sign of the command
 xPWM      (n)     Value at each dTSeq (only available if dTSeq input)
References abs(), Energy(), FFTEngy(), Frequency(), length(), NewFig(), Plot2D(), PWMSeq(), set(), TriangleWave(), XLabelS(), YLabelS(), and zeros().
Referenced by PWMSeq().
QAlignWithCon()
function QAlignWithCon ()
 1. Begin with an initial quaternion
 2. Rotate about a body-frame axis to align a body-frame vector with an
 inertial target vector
 3. Return the new quaternion
Form
 [q,rotAngle,sepAngle,angleRange,sepCon] = QAlignWithCon( q0, uBAxis, uBVec,...
 uITarget, u1B, u2I, minSep )
Inputs
 q0          (4,:)   Beginning inertial to body quaternion
 uBAxis      (3,1)   Body-frame axis to rotate about
 uBVec       (3,1)   Body-frame vector to align
 uITarget    (3,:)   Inertial-frame vector to point at
 u1B         (3,N)   Vector u1 in body frame. Constraint is:
                         acos( Dot(u1,u2) ) >= minSep
 u2I         (3,:,N) Vector u2 in inertial frame.
 minSep      (1,N)   Keep angle between u1 and u2 greater than minSep.
Outputs
 q           (4,:)  Resulting Inertial-to-Body quaternion after rotation
 rotAngle    (1,:)  Angle of rotation [rad]
 sepAngle    (1,:)  Separation angle between body vector and target [rad]
 angleRange  (:,4)  Range of valid rotation angles
 sepCon      (1,N)  Separation angle between u1 and u2
References and(), Dot(), NewFig(), QAlignWithCon(), QForm(), QMult(), QPose(), QRotateToAlignWithCon(), QTForm(), quaternion(), vector(), and zeros().
Referenced by AttitudeProfileWithCon(), and QAlignWithCon().
QMultJPL()
function QMultJPL (in Q2, in Q1)
 so Q3 transforms from A to C. If only one argument is input
 it produces the 4x4 matrix equivalent:
 q3 = Q2*q1;
 This uses the JPL convention (as opposed to Apollo)
Form
 Q3 = QMultJPL( Q2 ,Q1 )
Inputs
 Q2              (4,1)  Quaternion from a to b
 Q1              (4,1)  Quaternion from b to c
Outputs
 Q3              (4,1)  Quaternion from a to c or 4x4 version of q
References and().
QProp()
function QProp (in qLast, in theta, in n)
 The integration order can be specified but only correction terms up to and
 including the fourth order terms are included. The third order correction
 terms require the measurements from the previous time step. The fourth order
 correction terms require the measurements from the two previous time steps.
 Note that the sign of all correction terms is opposite that given in the
 Wong and Breckenridge reference. Testing has not shown this to be an issue.
 Since version 3.
Form
 q = QProp( qLast, theta, n )
Inputs
 qLast           (4,1)  Quaternion at last time step
 theta           (3,k)  Angular increments from gyro
                          The first column is the most recent output.
                          The second column is the previous output.
                          The third column is the output from 2 time steps ago.
 n               (1,1)  The order of the propagator. Terms up to theta^n
                          will be included.
Outputs
 Q3              (4,1)  Updated quaternion
References: Wong, E.C. and W.G. Breckenridge, "Inertial Attitude Determination for a Dual-Spin Planetary Spacecraft", AIAA Journal of Guidance Navigation, and Control Vol. 6, No. 6, Nov-Dec 1983, pp. 491-8.
 Iwens, R.P. and R.L. Farrenkopf, "Performance Evaluation of a
 Precision Attitude Determination System", AIAA Paper 71-964, 1971.
References and(), Factorl(), isempty(), QMult(), QPose(), quaternion(), Unit(), vector(), and zeros().
QRotateToAlignWithCon()
function QRotateToAlignWithCon ()
Rotate about an axis to align "ua" as close as possible to target "ut" with constraint that the angle between a rotated u1 vector and a fixed u2 vector be greater than minSep
Type QRotateToAlignWithCon for a demo
Form
 [qRot,ub,rotAngle,sepAngle,angleRange,sepCon,sepBnd,sep0,rot0] = ...
 QRotateToAlignWithCon( axis, ua, ut, u1, u2, minSep )
Inputs
 axis       (3,1)  Axis of rotation
 ua         (3,1)  Vector to align
 ut         (3,:)  Target vector to be aligned with
 u1         (3,N)  Vector u1. Constraint is:
                     acos( Dot(u1,u2) ) >= minSep
 u2         (3,:,N)  Vector u2.
 minSep     (1,N)  Keep angle between u1 and u2 greater than minSep.
Outputs
 qRot       (4,:)  Quaternion that rotates ua to ub about axis
 ub         (3,:)  Vector achieved after rotation
 rotAngle   (1,:)  Angular rotation about the axis
 sepAngle   (1,:)  Separation angle between ub and ut
 angleRange (:,2)  Range of valid rotation angles
 sepCon     (1,N)  Separation angle between u1 and u2
References abs(), and(), AngleSepFromRotation(), close(), Coordinates(), Cross(), Demo(), Dot(), FindValidAngleRange(), InsideAngleRange(), QForm(), QRotateToAlignWithCon(), quaternion(), Unit(), vector(), and zeros().
Referenced by QAlignWithCon(), and QRotateToAlignWithCon().
QSpin()
function QSpin (in x, in u, in angle)
Form
 q = QSpin( x, u, angle )
Inputs
 x            (3,1)   Vector to rotate about u
 u            (3,1)   Rotation vector
 angle         (1,:)   Angles at which to compute q (rad)
Outputs
 q            (4,:)   Quaternion
References and(), AU2Q(), Cross(), Demo(), length(), Normal(), Plot2D(), QMult(), QSpin(), QTForm(), series(), U2Q(), Unit(), vector(), and zeros().
Referenced by QSpin().
QSunNadir()
function QSunNadir (in rECI, in vECI, in uSunECI, in xNoSun, in alphaLimit)
If less than three inputs are given, it will run a demo for a GPS orbit.
Form
 [qECIToBody, sAAngle, alpha, beta, yawRate, sARate] =
 QSunNadir( rECI, vECI, uSunECI, xNoSun, alphaLimit )
Inputs
 rECI         (3,:)  Spacecraft position in ECI frame
 vECI         (3,:)  Spacecraft velocity in ECI frame
 uSunECI      (3,:)  Sun position in ECI frame
 xNoSun       (1,1)  Either +1 for +x or -1 for -x
 alphaLimit   (1,1)  Range of alpha within which the rate limit is to
                     be enforced
Outputs
 qECIToBody   (4,:)  Quaternion from ECI to body
 saAngle      (1,:)  Solar array angle
 alpha        (1,:)  Angle from the sun line in the orbit plane
 beta         (1,:)  Beta angle
 yawRate      (1,:)  Yaw rate
 sARate       (1,:)  Solar array rate
References and(), Cross(), JD2000(), Mat2Q(), Period(), Plot2D(), QLVLH(), QMult(), quaternion(), RV2El(), RVFromKepler(), Step(), SunNadir(), SunV1(), Unit(), and zeros().
QSunPointing()
function QSunPointing (in uSun)
 +y is as close to +z as possible and +z completes the set.
Form
 q = QSunPointing( uSun )
Inputs
 uSun         (3,:)   Sun unit vector
Outputs
 q            (4,:)   Quaternion
References and(), close(), Cross(), Mat2Q(), set(), Unit(), vector(), and zeros().
RADec2FP()
function RADec2FP (in rAC, in decC, in rA, in dec, in f)
 The outputs will only be for valid inputs, i.e. inputs in the visible
 hemisphere. In the focal plane the vectors
 x = [0;1;0] and y = [sin(decC);0;-cos(decC)] define the sysstem
 of coordinates that is used to measure the plate and which is
 oriented North-SOutha and East-West.
 Since version 2.
Form
 [x, y, k] = RADec2FP( rAC, decC, rA, dec, f )
Inputs
 rAC       (1,1)   Right ascension of the camera axis (rad)
 decC      (1,1)   Declination of the camera axis (rad)
 rA         (n)    Right ascension (rad)
 dec        (n)    Declination (rad)
 f         (1,1)   Focal length
Outputs
 x         (n)     X coordinate
 y         (n)     Y Coordinate
 k         (:)     Valid inputs
References: Montenbruck, O. and T. Fleger, "Astronomy on the Personal Computer", Spring-Verlag, 1994, p 255.
References and(), Dot(), length(), NewFig(), RADec2FP(), RaDec2U(), XLabelS(), and YLabelS().
Referenced by RADec2FP().
RadiationBelts()
function RadiationBelts (in r, in t, in jD, in ignoredArg)
Treat the problem as planar. Creates a plot of the simulated spiral and a time history plot of the delta-V, fuel consumed, and orbit eccentricity. This functions uses toruses that approximate the radiation belts.
Form
 RadiationBelts( r, ~, jD )
Inputs
 r         (3,:) ECI position vector
 t         (1,:) Time vecot
 jD        (1,:) Corresponding Julian dates
 innerOnly (1,1) Show only the inner belts
Outputs
 None
References and(), Demo(), JD2000(), PlotOrbit(), Q2Mat(), RadiationBelts(), RPRA2AE(), RVOrbGen(), Torus(), U2Q(), UDipole(), and vector().
Referenced by RadiationBelts().
RangeMeasurement()
function RangeMeasurement (in r, in v, in c, in rSource, in vSource)
Form
 [r, rRate] = RangeMeasurement( r, v, c, rSource, vSource )
Inputs
 r           (3,:)  Position
 v           (3,:)  Velocity
 c           (2,:)  Clock errors [bias;bias drift]
 rSource     (3,1)  Position of source
 vSource     (3,1)  Velocity of source
Outputs
 range       (1,:)  Range
 rangeRate   (1,:)  Range rate
References and(), Dot(), DupVect(), Mag(), and RangeMeasurement().
Referenced by GPSReceiverNav(), and RangeMeasurement().
RateGyro()
function RateGyro (in h, in w, in dT, in a)
Includes all noise sources
 and temperature dependence.  The data structure is:
 h.measurement
 h.scaleFactor
 h.bias
 h.temp
 h.tempNominal
 h.maxRate
 h.unitVector(3)
 h.resolution
 h.deadband
 h.accelCoeff(2)               [g g^2]
 h.biasTempCoeff(n)            [(temp - tempNominal) (temp - tempNominal)^2 ... ]
 h.biasDayToDay
 h.biasRandomDrift
 h.biasRandomWalk              (Optical Gyros)
 h.scaleFactorDayToDay
 h.scaleFactorTempCoeff(n)     [(temp - tempNominal) (temp - tempNominal)^2 ... ]
 h.scaleFactorPositiveCoeff(n) [omega omega^2 ... ]
 h.scaleFactorNegativeCoeff(n) [omega omega^2 ... ]
 h.initialize (0 means initialize and apply the day-to-day uncertainties)
 Since version 2.
Form
 h = RateGyro( h, w, dT, a )
Inputs
 h             (n)    Data structure for the gyros
 w             3,1)   Inertial body rate
 a             (3,1)  Inertial acceleration
 dT            (1,1)  Time step
Outputs
 h             (n)    Data structure for the gyros
References: 1. Lawrence, A., Modern Inertial Technology, Spring-Verlag,1992.
Merhav, S., Aerospace Sensor Systems and Appliations,
Spring-Verlag,1996.
References abs(), and(), Initialize(), length(), and RateGyro().
Referenced by RateGyro().
RBModel()
function RBModel (in inr, in w, in t, in invInr, in dT)
 invInr and t are not used when computing the state-space model. invInr is
 optional when computing the right-hand-side but will speed up the routine.
 Since version 1.
Form
 wdot               = RBModel( inr, w, t, invInr )
 [a, b, c, d, dwdt] = RBModel( inr, w, t, invInr, dT )
Inputs
 inr          (3,3)     Inertia matrix
 w            (3,1)     Body rate in the body frame
 t            (3,1)     External torque on the body
 invInr       (3,3)     Inverse inertia matrix (Optional)
 dT                     Time step
Outputs
 wdot         (3,1)     Angular acceleration
 or
 a            (3,3)     State matrix
 b            (3,3)     Input matrix
 c            (3,3)     Output matrix
 d            (3,3)     Feedthrough matrix
 dwdt         (3)       State acceleration
References and(), C2DZOH(), Cross(), SkewSymm(), and zeros().
Referenced by ASim(), FRB(), FRBWithMag(), and FRBwRIG().
ReactionWheel()
function ReactionWheel (in action, in u)
This models an RWA using Hall sensors.
 The model has three states. They are:
 [Wheel angle;...
 Omega;...
 Bristle];
See also
RWAResponse.
Form
 y = ReactionWheel( action, u )
 Actions with only inputs:
 ReactionWheel( 'initialize', rWADatastructure );
 ReactionWheel( 'set command', rWATorqueCommand );
 ReactionWheel( 'set failure', failedRWAID );
 ReactionWheel( 'set data', rWADatastructure );
 ReactionWheel( 'set tachometer states', struct( 'omega', reactionWheelRate, 'angle', reactionWheelAngle ) );
 Actions with output:
 tachometerWord          = ReactionWheel( 'GetTachometerWord ' );
 frictionTorque          = ReactionWheel( 'get friction torque' );
 reactionTorque          = ReactionWheel( 'compute reaction torque', reactionWheelState );
 electricalPower         = ReactionWheel( 'get power consumption' );
 motorCurrent            = ReactionWheel( 'get motor current' );
 motorVoltage            = ReactionWheel( 'get motor voltage' );
 xDot                    = ReactionWheel( 'get state derivative', omegaBase );
 d                       = ReactionWheel( 'get default datastructure' );
Inputs
 action   (:)    Action or state
 u         (1,1)  Input depends on action
Outputs
 y        (:)    Output depends on action
References abs(), and(), CloseIfHandle(), FrictionBristle(), get(), GetH(), isempty(), length(), PutH(), ReactionWheel(), RWA(), set(), and zeros().
Referenced by ReactionWheel(), and RHSRWASC().
ReactionWheelFriction()
function ReactionWheelFriction (in omega, in d)
The wheels can have damping and Coulomb friction and stiction. If you call it with 'struct' it will return the default data structure.
Type ReactionWheelFriction for a demo.
Form
 d = ReactionWheelFriction('struct');
 f = ReactionWheelFriction( omega, d )
Inputs
 omega (:,:)    Angular rate
 d     (.)    Data structure
             .cDampingRWA        (n,1) Damping coefficient
             .torqueCoulombRWA   (n,1) Coulomb friction torque
             .torqueStictionRWA  (n,1) Stiction friction torque
             .alphaStictionRWA   (n,1) Stiction velocity damping
             .betaSigmoid        (1,1)
             .useSigmoid         (1,1) Flag for sigmoid
Outputs
 f      (:,:) Friction
References abs(), and(), DefaultDataStructure(), Demo(), Friction(), length(), Plot2D(), ReactionWheelFriction(), and zeros().
Referenced by ReactionWheelFriction(), RHSFriction(), RHSReactionWheel(), RHSSpacecraftWithRWA(), and RWAWithPower().
ReactionWheelStress()
function ReactionWheelStress (in rO, in rI, in omega, in nu, in rho, in t)
 This is for a wheel hoop.
 Enter ReactionWheelStress for a demo
 omega, rO or rI may be vectors. If more than one are vectors they
 must be the same length.
Form
 ReactionWheelStress
 [sigma, h] = ReactionWheelStress( rO, rI, omega, nu, rho, t )
Inputs
 rO       (1,:) Outer radius (m)
 rI       (1,:) Inner radius (m)
 omega    (1,:) Angular rate (rad/s)
 nu       (1,:) Poisson's ratio may be a numnber of string
 rho      (1,:) Density (kg/m^3)
 t        (1,1) Thickness (m)
Outputs
 sigma    (1,:) Stress (N/m^2)
 h        (1,:) Momentum (Nms)
References and(), length(), Plot2D(), PoissonsRatio(), and ReactionWheelStress().
Referenced by ReactionWheelStress().
ReadBSPFile()
function ReadBSPFile (in varargin)
If no outputs are requested it will display the trajectory in 3D and the position and velocity in 2D plots.
Type ReadBSPFile for a demo for Cassini. You must have '030201AP_SK_SM546_T45.bsp' and 'naif0008.tls' in the directory.
Form
 [r,v,t] = ReadBSPFile( varargin )
Inputs
 varargin
 'name'                  (1,:) Name of the spacecraft
 'bsp'                   (1,:) BSP file (need not have .bsp at the end)
 'frame'                 (1,:) Frame name (like 'J2000')
 'center'                (1,:) Center string name (like 'SATURN BARYCENTER')
 'jd start'              (1,1) Start Julian date
 'jd end'                (1,1) End Julian date
 'leap seconds'          (1,:) Leap second file (like naif0008.tls);
 'n steps'               (1,1) Number of time steps
 'aberration correction' (1,:) Aberration correction type
Outputs
 r (3,:) Position (km)
 v (3,:) Velocity (km/s)
 t (1,:) Time vector (s)
References and(), Date2JD(), Demo(), length(), ReadBSPFile(), and vector().
Referenced by ReadBSPFile().
ReadMagField()
function ReadMagField (in fileName)
 The file should be in the form:
 n         m        g(n,m)        h(n,m)
 -------------------------------------------------------------------
 1         0       0.09732       0.0
 1         1       0.03220      -0.09889
 2         0       0.07448       0.0
 2         1       0.00664       0.11230
 The function assumes that there isn't a header. There is a demo that
 loads the field of Neptune from 'NeptuneMagField.txt.
Form
 [g, h] = ReadMagField( fileName )
Inputs
 fileName   (1,:)   Text file
Outputs
 g           (n,n)  G coefficients
 h           (n,n)  H coefficients
References ReadMagField(), and zeros().
Referenced by MagFieldData(), and ReadMagField().
RHSClockDrift()
function RHSClockDrift (in t, in tau, in d)
 If no arguments are entered in will integrate this for a circular
 orbit.
Form
 dT = RHSClockDrift( x, v, t, d )
Inputs
 t              (1,1) Local time
 tau            (1,1) Reference time
 d              (1,1) Data structure
                      .r  (3,1) Position
                      .v  (3,1) Velocity
                      .rS (3,1) Position of station
                      .vS (3,1) Velocity of station
                      .mu (1,1) Gravitational potential
Outputs
 dT             (1,1) Time derivative
References and(), Demo(), Difference(), GravitationalTimeDilation(), length(), Mag(), Plot2D(), RHSClockDrift(), RK4(), TimeLabl(), Unit(), VelocityTimeDilation(), and zeros().
Referenced by RHSClockDrift().
RHSCMG()
function RHSCMG (in x, in t, in d)
This is a rigid body with single axis CMGs. It has an external force and torque input. The torque are constant across the integration time step.
The function fDist (which should be a pointer) is of the form
 torque = MyFun( x, t, d )
d can contain additional parameters for the model
You can add additional fields to d. torque in Nm in the body frame. This function allows you to add torques within the integration loop. This is required for torques that are functions of time or the state vector.
Form
 [xDot,inr,hECI] = RHSCMG( x, t, d )
Inputs
 x      (:,1)   State vector [q;phi;w;omegaG;omegaW]
 t      (1,1)   Time  (s)
 d      (1,1)   Data structure for the simulation
                 .torque   (3,1)     External torque (Nm)
                 .force    (3,1)     External force (N)
                 .inr0     (3,3)     Core inertia (kg-m^2)
                 .inrG     {3}(3,3) Gimbal inertia (kg-m^2)
                 .inrW     {3}(3,3)  Wheelinertia (kg-m^2)
                 .torqueG  (1,:)     Gimbal torque (Nm)
                 .torqueW  (1,:)     Wheel torque (Nm)
                 .fDist    (1,:)     Disturbance function pointer
                 .x0       (15,1)    Default data structure with 3 CMGs
                 .states   {15}      Corresponding state names
Outputs
 xDot   (:,1) d[q;phi;w;omegaG;omegaW]/dt
 inr   (:,:) The generalized inertia matrix
 hECI  (3,:) The ECI momentum
References and(), and vector().
RHSFriction()
function RHSFriction (in x, in ignoredArg, in d)
The first model is the standard model with damping, Coulomb and static friction. The second uses a bristle friction model with an additional bristle state.
Form
 d  = RHSFriction;
 [xDot, fS, fB] = RHSFriction( x, ~, d )
Inputs
 x     (3,1)   [omega standard;omega bristle;bristle state]
 d     (1,1)   Data structure
               .inertia  (1,1)   Polar inertia
               .torque   (1,1)   Torque
               .friction (.)     See ReactionWheelFriction
               .bristle  (.)     See FrictionBristle);
Outputs
 xDot   (3,1)   d[omega standard;omega bristle;bristle state]/dt
 fS    (1,1)   Friction standard
 fB    (1,1)   Friction bristle
References and(), Friction(), FrictionBristle(), ReactionWheelFriction(), and RHSFriction().
Referenced by RHSFriction().
RHSGGRotational()
function RHSGGRotational (in x, in t, in d)
Includes hysteresis states.
Form
 [xDot, tDamp] = RHSGGRotational( x, t, d )
Inputs
 x  (7+n,1) [q;omega;z] z are hysteresis damper states
 t   (1,1)   Time (s)
 d   (.)     Data structure
             .inertia   (3,3) Inertia matrix (kg-m^2)
             .torque   (3,1) Torque in the body frame (Nm)
             .r        (3,1) Position vector (km)
             .mu       (1,1) Gravitational constant (km^3/s^2)
Outputs
 x     (7+n,1)  d[q;omega]/dt
 tDamp (3,1)   Damping torque (Nm)
References BDipole(), Constant(), Cross(), DefaultDataStructure(), Dot(), GravityGradientFromR(), InertiaCubeSat(), JD2000(), length(), Mag(), MagneticHysteresis(), Q2Mat(), QIToBDot(), RHSGGRotational(), Skew(), TorqueHysteresisDamper(), vector(), and zeros().
Referenced by RHSGGRotational().
RHSGyroNBody()
function RHSGyroNBody (in x, in ignoredArg, in g)
Each of the appendages has three degrees of rotational freedom connected to the hub. The spacecraft also has m reaction wheels that have only a polar moment of inertia. The center-of-mass is assumed not to move.
If nB is set to 1, you will get a gyrostat model. Body 1 is the core.
Type d = RHSGyroNBody to get a default data structure for a one appendage, 3 orthogonal reaction wheel spacecraft.
Form
 g = RHSGyroNBody;
 [xDot, h, gInr, rhs] = RHSGyroNBody( x, t, g )
Inputs
 x     (7+7n+m,1)[q1;q2;q3;omega1;omega2;omega3;omegaW1;omegaW2;omegaW3]
 t     (1,1)     Time - unused
 g     (1,1)     Data structure
                .inr      {n+1}   n+1 3x3 inertia matrices
                 .m        (1,n+1) Masses
                 .lambda   (3,n+1) Location of the body hinge
                 .u        (3,n+1) Body n hinge unit vector
                 .rho      (3,n+1) Location of body center of mass
                    .torque   (3,n+1) Torques
                 .nB       (1,1)   Number of appendages. [] if to be
                                   determined by the size of rho
                 .x0       (24,1)  Default state vector
Outputs
 xDot   (7+7n+m,1) State derivative
 h      (3,1)      Angular momentum in the inertial frame
 gInr  (:,:)      Generalized inertia
 rhs   (3+n,1)    Right hand side of the dynamical equations
References and(), get(), RHSGyroNBody(), and set().
Referenced by RHSGyroNBody().
RHSGyrostat()
function RHSGyrostat (in x, in ignoredArg, in d)
This has all of the parameters in a data structure. The states field includes suggested state names for a gyrostat with 3 wheels. It also includes a usable initial state assuming 3 wheels.
The built-in friction model available from the default data structure is a smooth model of the form:
 f = coulomb/(1+exp(-kCoulomb*omega)) - damping*omega
d.torque should include all external torques. If you want to include back emf you can include it in the Friction model.
See also
FGs, GSModel, RHSGyrostat>Friction
Form
 d     = RHSGyrostat   % default data structure
 [xDot,hECI] = RHSGyrostat( x, ~, d )
Inputs
 x     (7+n,1) The state vector [q;omega;omegaWheel]
 t     (1,1)   Time (s) (not used)
 d     (.)     Data structure
               .inr          (3,3)   Inertia (kg-m^2)
               .torque       (3,1)   Torque in body frame (Nm)
               .inrWheel     (3,n)   Wheel inertia (kg-m^2)
               .uWheel       (3,n)   Wheel unit vectors
               .torqueWheel (1,n)   Wheel control torque (Nm)
               .funFriction  (@)     Pointer to friction function
               .friction     (.)     Data structure for friction model
               .x0           (10,1)  Suggested initial state (3 wheels)
               .states       {:}     State names (names for 3 wheels)
Outputs
 xDot  (7+n,1) The derivative of the state vector
 hECI  (3,1)   ECI momentum (Nm)
References FGs(), Friction(), GSModel(), RHSGyrostat(), and vector().
Referenced by RHSGyrostat().
RHSGyrostatNoFriction()
function RHSGyrostatNoFriction (in x, in ignoredArg, in d)
This has all of the parameters in a data structure. The states field includes suggested state names for a gyrostat with 3 wheels. It also includes a usable initial state assuming 3 wheels.
d.torque should include all external torques.
Form
 d     = RHSGyrostatNoFriction
 xDot  = RHSGyrostatNoFriction( x, ~, d )
Inputs
 x     (7+n,1)  The state vector [q;omega;omegaWheel]
 t     (1,1)   Time (s) (not used)
 d     (.)     Data structure
               .inr          (3,3)   Inertia (kg-m^2)
               .torque       (3,1)   Torque in body frame (Nm)
               .inrWheel     (3,n)   Wheel inertia (kg-m^2)
               .uWheel       (3,n)   Wheel unit vectors
               .torqueWheel (1,n)   Wheel control torque (Nm)
               .x0           (10,1)  Suggested initial state (3 wheels)
               .states       {:}     State names (names for 3 wheels)
Outputs
 xDot  (7+n,1)  The derivative of the state vector
References RHSGyrostatNoFriction(), and vector().
Referenced by RHSGyrostatNoFriction().
RHSGyroWithOrbit()
function RHSGyroWithOrbit (in x, in ignoredArg, in d)
Angular rate is an input. Point mass orbit model.
Form
 d    = RHSGyroWithOrbit; % To get the data structure
 xDot = RHSGyroWithOrbit( x, t, d )
Inputs
 x     (16,1)    State vector [r;v;q;imuAng;imuBias]
 t     (1,1)     Time (unused)
 d      (.)      Data structure
                 .mu        (1,1) Gravitational constant
                 .b1Sig     (1,1) Bias random walk
                 .ang1Sig   (1,1) Angle noise
                 .omega     (3,1) Angular rate
Outputs
 xDot   (16,1)    State vector derivative d[r;v;q;imuAng;imuBias]/dt
References and(), get(), Gyro(), Mag(), QIToBDot(), RHSGyroWithOrbit(), and vector().
Referenced by RHSGyroWithOrbit().
RHSHysteresisDamper()
function RHSHysteresisDamper (in x, in bECI, in bDotECI, in d)
 In Kumar p = 1 and q0 = 0. This can be called by RK4 directly.
Form
 [zDot, p] = RHSHysteresisDamper( x, bECI, bDotECI, d )
Inputs
 x                  (:,1) States [r;v;q;w;z]
 bECI               (3,1) Magnetic field ECI (T)
 bDotECI            (3,1) Magnetic field derivative (T/s)
 d                  (1,1) Data structure
                          .bS (1,1) Saturation flux density (T)
                          .hC (1,1) Coercive force (A/m)
                          .bR (1,1) Remanance (T)
                          .v  (1,:) Volume (m^3)
                          .u  (3,:) Unit vectors
Outputs
 zDot               (:,1) Derivative of the flux density
 p                  (1,1) Data structure
                          .torqueDamper (3,1) Torque (N)
                          .hMag         (:,1) Magnitude of h in each bar
                          .hDotMag       (:,1) Magnitude of h dot in each bar
See also
MagneticHysteresis, TorqueHysteresisDamper
References and(), Cross(), Dot(), length(), MagneticHysteresis(), Q2Mat(), RK4(), TorqueHysteresisDamper(), Unit(), and zeros().
RHSMEMSGyro()
function RHSMEMSGyro (in x, in ignoredArg, in d)
This is the right hand side for the gyro. It also returns rate and angle. You can have any number of gyros. Flicker is a Markov process. The bias random walks. The constants can be the same for each gyro or different.
Form
 [xDot,rate] = RHSMEMSGyro(x,t,d)
Inputs
 x     (3*n,1) [angle;bias;flicker]
 t     (1,1)   Time (s) (not used)
 d     (.)     Data structure
               .angleNoise   (1 or n,1) Angle noise
               .biasNoise    (1 or n,1) Bias noise
               .flickerNoise (1 or n,1) Flicker noise
               .flickerTau   (1 or n,1) Flicker time constant
               .rate         (n,1)      Angular rate (rad/s)
Outputs
 xDot  (3*n,1) d[angle;bias;flicker]/dt
 rate  (3*n,1) Angular rate
References and(), DefaultDataStructure(), length(), Markov(), RHSMEMSGyro(), and zeros().
Referenced by RHSMEMSGyro().
RHSNBodyCentralHub()
function RHSNBodyCentralHub (in x, in ignoredArg, in g)
Each of the appendages has one degree of rotational freedom connected to the hub. This is defined as around the specified unit vector.
The axis of rotation for each appendage is defined by u in the data structure.
Type d = RHSNBodyCentralHub to get a default data structure for a single appendage.
Form
 [xDot, h] = RHSNBodyCentralHub( x, t, g )
Inputs
 x     (7+2n,1)  [q;omega0;theta1;...;omega1...]
 t     (1,1)     Time - unused
 g     (.)       Data structure
                .inr      {n+1}   n+1 3x3 inertia matrices
                 .m        (1,n+1) Masses
                 .lambda   (3,n+1) Location of the body hinge
                 .u        (3,n+1) Body n hinge unit vector
                 .rho      (3,n+1) Location of body center of mass
                    .torque   (3,n+1) Torques
Outputs
 xDot   (7+2n,1) State derivative
 h      (3,1)    Angular momentum in the inertial frame
 gInr  (:,:)    Generalized inertia
 rhs   (3+n,1)  Right hand side of the dynamical equations
Reference: Spacecraft Attitude and Orbit Control, "Multibody Dynamics", PSS. In Vol. 2, Special Topics, 3rd edition.
References get(), RHSNBodyCentralHub(), and vector().
Referenced by RHSNBodyCentralHub().
RHSNBodySH()
function RHSNBodySH (in x, in ignoredArg, in g)
Each of the appendages has three degrees of rotational freedom connected to the hub.
Type d = RHSNBodySH to get a default data structure for a rigid body.
Form
 [xDot, h, gInr] = RHSNBodySH( x, t, g )
Inputs
 x     (7*(n+1),1)  [q1;q2;...;omega1;omega2;...]
 t     (1,1)         Time - unused
 g     (1,1)         Data structure
                     .inr      {n+1}   3x3 inertia matrices
                     .m        (1,n+1) Masses
                     .lambda   (3,n+1) Location of the body hinge j
                     .rho      (3,n+1) Location of body j center of mass
                    .torque   (3,n+1) Torques
Outputs
 xDot   (7*(n+1),1) State derivative
 h      (3,1)       Angular momentum in the inertial frame
 gInr  (:,:)       Generalized inertia
 rhs   (3*(n+1),1) Right hand side of the dynamical equations
References get(), and RHSNBodySH().
Referenced by RHSNBodySH().
RHSNSpacecraft()
function RHSNSpacecraft (in x, in ignoredArg, in d)
 Employs a simple central force model for gravity.
 The first state vector is the reference point
Form
 xDot = RHSNSpacecraft( x, t, d )
Inputs
 x              (13*n,1) [R;V;Q;W;r0;v0;q0;w0;...rk;vk;qk;wk]
 t              (1,1)    Time (not used)
 d              (1,1)    Data structure
                        .mu     (1,1)   Gravitational parameter
                        .f      (3,n)   Force vectors in ECI frame
                        .t      (3,n)   Torque vectors in body frame
                        .lambda (3,n-1) Hinge vectors on body k
                        .kappa  (3,n-1) Hinge vectors on body 1
                        .inr    {n}     Inertia matrices
Outputs
 xDot           (13*n,1) d[R;V;Q;W;r0;v0;q0;w0;...rk;vk;qk;wk]/dt
References vector().
RHSPlanetTakeoff()
function RHSPlanetTakeoff (in x, in ignoredArg, in a, in g, in beta, in signX)
This function is compatible with RK2, RK4 and RK45.
Form
 xDot = RHSPlanetTakeoff( x, ~, a, g, beta, signX )
Inputs
 x       (4,1)  State vector [x;y;vX;vY]
 t       (1,1)  Time (s) (unused)
 a       (1,1)  Thruster acceleration
 g       (1,1) Gravitational acceleration along -y
 beta    (1,1) Thrust angle from the horizontal (rad)
 signX   (1,1) Account for desired x acceleration direction (default 1)
Outputs
 xDot     (:,1) d[x;y;vX;vY]/dt
References and(), RHSPlanetTakeoff(), RK2(), RK4(), RK45(), and vector().
Referenced by LandingConst2D(), PropagateState(), and RHSPlanetTakeoff().
RHSPointMass()
function RHSPointMass (in x, in t, in d)
 This is a point mass with an external force input.
 The position is in km. The gravity model is for a point mass.
 The force are constant across the integration time step.
 The body has time varying mass.
 In this function d.mass is the dry mass. The fuel mass is in the state
 vector x. If m is less than zero mDot is set to zero.
 The function fDist (which should be a handle) is of the form
 force = MyFun( x, t, d )
 You can add additional fields to d. force must be in N in the body
 frame and torque in Nm in the body frame. This function allows you
 to add forces and torques within the integration loop. This is
 required for forces and torques that are functions of time or the
 state vector.
Form
 d = RHSPointMass;
 xDot = RHSPointMass( x, t, d )
Inputs
 x       (7,1)   State vector [r;v;m] (km, km/s, kg)
 t       (1,1)    Time (unused) (s)
 d       (1,1)    Data structure for the simulation
                 .force    (3,1) External force (N)
                 .mass     (1,1) Vehicle dry mass (kg)
                 .mu       (1,1) Gravitational parameter (km^3/s^2)
                 .fDist    (1,:) Disturbance function handle
                 .mDot     (1,1) Mass rate (kg/s)
Outputs
 xDot   (14,1)     d[r;v;;m]/dt
References and(), Constant(), isempty(), Mag(), RHSPointMass(), set(), vector(), and zeros().
Referenced by RHSPointMass().
RHSReactionWheel()
function RHSReactionWheel (in x, in ignoredArg, in d)
The wheels can have damping and Coulomb friction and stiction. If you call it without any arguments it will return the default data structure.
The inertia of the body does not include the RWA polar inertia.
RWA stands for reaction wheel assembly.
The default data structure is for 3 orthogonal reaction wheels.
Uses ReactionWheelFriction.m
Form
 d = RHSReactionWheel; % To get the data structure
 [xDot,hECI] = RHSReactionWheel x, t, d )
Inputs
 x     (7+n,1)   State vector [q;omega;omegaRWA]
 t     (1,1)     Time (unused)
 d      (.)      Data structure
                 .inr                (3,3) Body inertia matrix
                 .torque             (3,1) External torque in the body frame
                 .inrRWA             (n,1) Polar inertia of each wheel
                 .torqueRWA          (n,1) Torques on each wheel
                 .uRWA               (3,n) Unit vectors for the RWA
                 .friction           (.)   Friction data structure
                 .useFriction        (1,1) true means use friction
Outputs
 xDot   (7+n,1)   State vector derivative d[q;omega;omegaRWA]/dt
 hECI   (3,1)     Inertial angular momentum
References and(), Friction(), get(), length(), QIToBDot(), QTForm(), ReactionWheelFriction(), RHSReactionWheel(), RWA(), Unit(), vector(), and zeros().
Referenced by RHSReactionWheel(), RHSReactionWheelWithOrbit(), and RHSRWAOrbit().
RHSReactionWheelWithOrbit()
function RHSReactionWheelWithOrbit (in x, in ignoredArg, in d)
Uses RHSReactionWheel for the spacecraft attitude dynamics. Allows for only three reaction wheels. Assumes a point mass gravity model. Includes gyros.
Form
 d    = RHSReactionWheelWithOrbit; % To get the data structure
 [xDot,hECI] = RHSReactionWheelWithOrbit x, t, d )
Inputs
 x     (22,1)    State vector [r;v;q;omega;omegaRWA;imuAng;imuBias]
 t     (1,1)     Time (unused)
 d      (.)      Data structure
                 .inr       (3,3) Body inertia matrix
                 .m         (1,1) Spacecraft mass
                 .mu        (1,1) Gravitational constant
                 .force     (3,1) External force in the ECI frame (kN)
                 .torque    (3,1) External torque in the body frame
                 .inrRWA    (n,1) Polar inertia of each wheel
                 .torqueRWA (n,1) Torques on each wheel
                 .uRWA      (3,n) Unit vectors for the RWA
                 .friction  (.) Friction data structure
                 .b1Sig     (1,1) Bias random walk
                 .ang1Sig   (1,1) Angle noise
Outputs
 xDot   (22,1)    State vector derivative d[r;v;q;omega;omegaRWA]/dt
 hECI   (3,1)     Inertial angular momentum
References and(), Friction(), get(), Gyro(), Mag(), RHSReactionWheel(), RHSReactionWheelWithOrbit(), RWA(), Unit(), and vector().
Referenced by RHSReactionWheelWithOrbit().
RHSRigidBody()
function RHSRigidBody (in x, in t, in d)
 This is a rigid body with an external force and torque input.
 The position is in km. The gravity model is for a point mass.
 The force and torque area constant across the integration time step.
 The function fDist (which should be a pointer) is of the form
 [force, torque] = MyFun( x, t, d )
 You can add additional fields to d. force must be in N in the body
 frame and torque in Nm in the body frame. This function allows you
 to add forces and torques within the integration loop. This is
 required for forces and torques that are functions of time or the
 state vector.
Form
 xDot = RHSRigidBody( x, t, d )
Inputs
 x       (:,1)  State vector [r;v;q;w] (km,km/s,,rad/s)
 t       (1,1)  Time (unused) (s)
 d       (1,1)  Data structure for the simulation
                 .torque   (3,1) External torque (Nm)
                 .force    (3,1) External force (N)
                 .inertia  (3,3) Vehicle inertia (kg-m^2)
                 .mass     (1,1) Vehicle mass (kg)
                 .mu       (1,1) Gravitational parameter (km^3/s^2)
                 .fDist    (1,:) Disturbance function pointer
Outputs
 xDot   (:,1)     d[r;v;q;w]/dt
References and(), Constant(), Euler(), isempty(), Mag(), QIToBDot(), QTForm(), Skew(), vector(), and zeros().
RHSRigidBody6DOF()
function RHSRigidBody6DOF (in x, in ignoredArg, in d)
 This is a rigid body with an external force and torque input.
 The position is in km. The position model is for a double integrator.
 This is useful when the duration of the simulations are short
 compared to the orbit period.
 The force and torque are constant across the integration time step.
Form
 d = RHSRigidBody6DOF
 xDot = RHSRigidBody6DOF( x, t, d )
Inputs
 x       (:,1)  State vector [r;v;q;w] (m,m/s,,rad/s)
 t       (1,1)  Time (unused) (s)
 d       (1,1)  Data structure for the simulation
                 .torque   (3,1) External torque (Nm)
                 .force    (3,1) External force in ECI (N)
                 .inertia  (3,3) Vehicle inertia (kg-m^2)
                 .mass     (1,1) Vehicle mass (kg)
                 .mu       (1,1) Gravitational parameter (km^3/s^2)
Outputs
 xDot   (:,1)     d[r;v;q;w]/dt
References and(), Constant(), Euler(), QIToBDot(), RHSRigidBody6DOF(), Skew(), and vector().
Referenced by RHSRigidBody6DOF().
RHSRigidBodyLinear()
function RHSRigidBodyLinear (in x, in ignoredArg, in d)
Form
 d = RHSRigidBodyLinear
 xDot = RHSRigidBodyLinear( x, t, d )
Inputs
 x       (7,1) State vector [q;omega]
 t       (1,1) Time (s) (unused)
 d       (1,1) Data structure
                 .inertia    (3,3) Inertia matrix
                 .torque     (3,1) Torque vector
Outputs
 xDot   (:,1)   d[q;omega]/dt
References QIToBDot(), RHSRigidBodyLinear(), and vector().
Referenced by RHSRigidBodyLinear().
RHSRigidBodyMass()
function RHSRigidBodyMass (in x, in t, in d)
 This is a rigid body with an external force and torque input.
 The position is in km. The gravity model is for a point mass.
 The force and torque area constant across the integration time step.
 The body has time varying mass but not inertia.
 In this function d.mass is the dry mass. The fuel mass is in the state
 vector x. If m is less than zero mDot is set to zero.
 The function fDist (which should be a handle) is of the form
 [force, torque] = MyFun( x, t, d )
 You can add additional fields to d. force must be in N in the body
 frame and torque in Nm in the body frame. This function allows you
 to add forces and torques within the integration loop. This is
 required for forces and torques that are functions of time or the
 state vector.
Form
 d = RHSRigidBodyMass
 [xDot, force, torque] = RHSRigidBodyMass( x, t, d )
Inputs
 x       (14,1) State vector [r;v;q;w;m] (km,km/s,,rad/s,kg)
 t       (1,1)    Time (unused) (s)
 d       (1,1)    Data structure for the simulation
                 .torque     (3,1) External torque (Nm)
                 .force      (3,1) External force (N)
                 .inertia    (3,3) Vehicle inertia (kg-m^2)
                 .mass       (1,1) Vehicle dry mass (kg)
                 .mu         (1,1) Gravitational parameter (km^3/s^2)
                 .fDist      (1,:) Disturbance function handle
                 .fDistData  (1,1) Data structure for the disturbance
                                   function
                 .mDot       (1,1) Mass rate (kg/s)
Outputs
 xDot    (14,1)    d[r;v;q;w;m]/ (km/s,km/s^2,,rad/s^2,kg/s)
 force   (3,1)     Disturbance force (N)
 torque (3,1)     Disturbance torque (Nm)
References and(), Constant(), Euler(), isempty(), Mag(), QIToBDot(), QTForm(), RHSRigidBodyMass(), set(), Skew(), vector(), and zeros().
Referenced by RHSRigidBodyMass().
RHSRigidBodyOffsetCM()
function RHSRigidBodyOffsetCM (in x, in ignoredArg, in d)
The reference center is not the center of mass. The state vector is
 [position;velocity;quaternion;angular rate]
Form
 d = RHSRigidBodyOffsetCM
 xDot = RHSRigidBodyOffsetCM( x, t, d )
Inputs
 x              (13,1)  [r;v;q;w]
 t              (1,1)   Time (not used)
 d              (1,1)   Data structure
                        .mu     (1,1)   Gravitational parameter
                        .f      (3,1)   Force vectors in ECI frame
                        .t      (3,1)   Torque vectors in body frame
                        .c      (3,1)   Vector from center to cm
                        .inr    (3,3)   Inertia matrix
                        .m      (1,1)   Mass
Outputs
 xDot           (13,1)  d[r;v;q;w]/dt
References Constant(), Cross(), Mag(), Q2Mat(), QIToBDot(), quaternion(), RHSRigidBodyOffsetCM(), Skew(), vector(), and zeros().
Referenced by RHSRigidBodyOffsetCM().
RHSRigidBodyWithDamping()
function RHSRigidBodyWithDamping (in x, in t, in d)
 d.dampingFun is of the form
 DampingFun( x, jD, bFieldBody, d )
 where d is the damping data.
Form
 d = RHSRigidBodyWithDamping;
 [xDot, p] = RHSRigidBodyWithDamping( x, t, d )
Inputs
 x       (13+n,1)    [r;v;q;omega;z]
 t       (1,1)       Time since start (s)
 d       (1,1)       Data structure
                     .inertia        (3,3) Spacecraft inertia (kg-m^2)
                     .dampingFun     (1,1) Handle to the damping function
                     .dampingData    (1,1) Damping function data
                     .dipole         (3,1) Fixed dipole
                     .dampingType    (1,1) 1 is used constant, 2 use fun
                     .jD0            (1,1) Julian date
                     .mu             (1,1) Gravitational constant
Outputs
 xDot    (13+n,1)   Right hand side
 p       (1,1)     Data structure
                     .torqueDamper   (3,1) Damper torque   (Nm)
                     .torqueDipole   (3,1) Dipole torque    (Nm)
                     .bfieldBody     (3,1) Magnetic field  (T)
                     .bfieldECI      (3,1) Magnetic field  (T)
References BDipole(), Constant(), Cross(), Date2JD(), DefaultDataStructure(), Dipole(), length(), Mag(), QForm(), QIToBDot(), RHSRigidBodyWithDamping(), vector(), and zeros().
Referenced by HysteresisOutput(), and RHSRigidBodyWithDamping().
RHSRigidBodyWithTarget()
function RHSRigidBodyWithTarget (in x, in ignoredArg, in d)
 This is a rigid body with an external force and torque input.
 The position is in km. The gravity model is for a point mass.
 The prime spacecraft has attitude dynamics, the target has only
 point mass dynamics (position and velocity.)
 The force and torque are constant across the integration time step.
Form
 d = RHSRigidBodyWithTarget;
 xDot = RHSRigidBodyWithTarget( x, t, d )
Inputs
 x       (:,1)  State vector [r;v;q;w;rT;vT] (km,km/s,,rad/s)
 t       (1,1)  Time (unused) (s)
 d       (1,1)  Data structure for the simulation
                 .torque   (3,1) External torque (Nm)
                 .force    (3,1) External force (N)
                 .inertia  (3,3) Vehicle inertia (kg-m^2)
                 .mass     (1,1) Vehicle mass (kg)
                 .mu       (1,1) Gravitational parameter (km^3/s^2)
Outputs
 xDot   (:,1)     d[r;v;q;w;rT;vT]/dt
References and(), Constant(), Euler(), Mag(), QIToBDot(), QTForm(), RHSRigidBodyWithTarget(), Skew(), and vector().
Referenced by RHSRigidBodyWithTarget().
RHSRWA()
function RHSRWA (in x, in t, in d)
This function includes position, orientation, and wheel speed. The disturbance function returns the body torque in Nm and the inertial force in N. It can handle any number of reaction wheels.
 [torque, force] = funDist( t, d, x )
Form
 d =  RHSRWA;
 xDot =  RHSRWA( x, t, d )
Inputs
 x           (:,1)  State vector [r;v;q;w;wRWA]
 t           (1,1)  Time
 d           (.)    Data structure for the simulation
                       .uWheel   (3,n) Reaction wheel unit vectors
                       .inrWheel (1,1) Wheel inertia
                       .tRWA     (n,1) Reaction wheel torque
                       .tDist    (3,1) Other external torques
                       .funDist   (@)  Disturbance function handle
                       .dist      (:)  Disturbance model data
                       .inertia  (3,3) Vehicle inertia
                       .mass     (1,1) Vehicle mass
                       .mu       (1,1) Gravitational parameter
Outputs
 xDot        (:,1)     State vector derivative
See also
: ThreeAxisControlDisturb
References and(), Constant(), Cross(), Disturbances(), FOrbCart(), QIToBDot(), RHSRWA(), ThreeAxisControlDisturb(), and vector().
Referenced by RHSRWA().
RHSRWAIDotSC()
function RHSRWAIDotSC (in x, in t, in d)
This function includes position, orientation and 4 reaction wheels. It also includes time varying inertia. This right hand side is primarily to analyze control during deployment.
Inputs
 x      (:,1)   State vector [r;v;q;w;wRWA;I]
 t      (1,1)   Time
 d      (.)     Data structure for the simulation
             .uRWA     (3,4) Reaction wheel unit vectors
             .inrRWA   (1,1) Reaction wheel inertia
            .tRWA     (4,1) Reaction wheel torque
             .tDist    (3,1) Additional external torques
            .funIandD  (@)  Disturbance and inertia model function
             .dist      (.)  Disturbance data structure
                .mass     (1,1) Spacecraft mass
             .mu       (1,1) Gravitational parameter
Outputs
 xDot   (:,1)     State vector derivative
References and(), Constant(), Cross(), Disturbances(), FOrbCart(), QIToBDot(), RHSRWAIDotSC(), and vector().
Referenced by RHSRWAIDotSC().
RHSRWAOrbit()
function RHSRWAOrbit (in x, in ignoredArg, in d)
Uses RHSReactionWheel for the spacecraft attitude dynamic. Allows for only 3 reaction wheels. Assumes a point mass gravity model
Form
 d    = RHSRWAOrbit; % To get the data structure
 [xDot, hECI] = RHSRWAOrbit(x,~,d)
Inputs
 x     (16,1)    State vector [r;v;q;omega;omegaRWA]
 t     (1,1)     Time (unused)
 d      (.)      Data structure
                 .inr       (3,3) Body inertia matrix
                 .m         (1,1) Spacecraft mass
                 .mu        (1,1) Gravitational constant
                 .force     (3,1) External force in the ECI frame (kN)
                 .torque    (3,1) External torque in the body frame
                 .inrRWA    (n,1) Polar inertia of each wheel
                 .torqueRWA (n,1) Torques on each wheel
                 .uRWA      (3,n) Unit vectors for the RWA
                 .friction  (.) Friction data structure
Outputs
 xDot   (16,1)    State vector derivative d[r;v;q;omega;omegaRWA]/dt
 hECI   (3,1)     Inertial angular momentum
References Friction(), get(), Mag(), RHSReactionWheel(), RHSRWAOrbit(), RWA(), Unit(), and vector().
Referenced by RHSRWAOrbit().
RHSRWASC()
function RHSRWASC (in x, in t, in d)
This function includes position, orientation and 3 reaction wheels modeled with the ReactionWheel function. This includes friction.
Form
 d = RHSRWASC;  % data structure
 xDot = RHSRWASC( t, x, d )
Inputs
 x           (22,1)    State vector [r;v;q;w;angleRWA;wRWA;frictionRWA]
 t           (1,1)     Time
 d            (.)      Data structure for the simulation
                       .inrRWA
                       .tDist
                       .inertia
                       .mu
Outputs
 xDot        (:,1)     State vector derivative
See also
ReactionWheel and RWAResponse.
References and(), Constant(), Cross(), FOrbCart(), get(), QIToBDot(), ReactionWheel(), RHSRWASC(), and vector().
Referenced by RHSRWASC().
RHSSlosh()
function RHSSlosh (in x, in ignoredArg, in g)
Each of the appendages has three degrees of rotational freedom connected to the hub.
Type d = RHSSlosh to get a default data structure for a rigid body.
Form
 [xDot, h] = RHSSlosh( x, t, g )
Inputs
 x     (7*(n+1),1)  [q1;q2;...;omega1;omega2;...]
 t     (1,1)         Time - unused
 g     (1,1)         Data structure
                     .inr      {n}   n 3x3 inertia matrices
                     .m        (1,n) Masses
                     .lambda   (3,n) Location of the body hinge j
                     .rho      (3,n) Location of body j center of mass
                    .torque   (3,n) Torques
Outputs
 xDot   (7*(n+1),1) State derivative
 h      (3,1)       Angular momentum in the inertial frame
References get(), and RHSSlosh().
Referenced by RHSSlosh().
RHSSNP()
function RHSSNP (in x, in ignoredArg, in d)
Form
 xDot = RHSSNP( x, t, inr, invInr, tExt, inrW, uW, tW, eSAC )
Inputs
 x            (15,1)    The state vector [q;solar array;body
                        rates;solar array rates;wheel rates]
 t                      Time
 d            (.)       Data structure
                        .inr  (3,3) Inertia
                        .tExt (3,1) External torque
                        .inrW (6,1) [SA,RWA] inertias
                        .uW   (3,6) [SA,RWA] unit vectors
                        .tW   (6,1) [SA,RWA] torque
                        .eSAC (2,1) Solar array commanded angle
                                    (always one step)
Outputs
 xDot         (15,1)    The derivative of the state vector
References RHS(), RHSSNP(), and RWA().
RHSSpacecraftWithIMU()
function RHSSpacecraftWithIMU (in x, in ignoredArg, in d)
Right hand side for a spacecraft with an inertial measurement unit. The spacecraft is a rigid body orbiting around a point mass.
d = RHSSpacecraftWithIMU
returns the default data structure. Uses the IMU function.
Form
 xDot = RHSSpacecraftWithIMU( x, ~, d )
Inputs
 x           (19,1)   [r;v;q;omega;randomWalk]
 t           (1,1)    Time (unused)
 d           (.)      Data structure
                      .inr         (3,3) Inertia matrix (kg-m^2)
                      .torque      (3,1) Torque (Nm)
                      .accel       (3,1) Acceleration ECI (km/s^2)
                      .mu          (1,1) Gravity constant (km^3/s^2)
                      .iMU          (.)   See IMU
Outputs
 x           (19,1)   d[r;v;q;omega;randomWalk]/dt
References Cross(), IMU(), Mag(), QIToBDot(), and RHSSpacecraftWithIMU().
Referenced by RHSSpacecraftWithIMU().
RHSSpacecraftWithRWA()
function RHSSpacecraftWithRWA (in x, in ignoredArg, in d)
The wheels can have damping and Coulomb friction and stiction. If you call it without any arguments it will return the default data structure.
The gravity model is a point mass planet. The inertia of the body does not include the RWA polar inertia.
RWA stands for reaction wheel assembly.
The default data structure is for 3 orthogonal reaction wheels but the model allows for any number of wheels. Uses ReactionWheelFriction.m
No demo.
Form
 d    = RHSSpacecraftWithRWA;
 [xDot,hECI] = RHSSpacecraftWithRWA( x, t, d )
Inputs
 x     (13+n,1)  State vector [r;v;q;omega;omegaRWA]
 t     (1,1)     Time (unused)
 d      (.)      Data structure
                 .inr                (3,3) Body inertia matrix
                 .m                  (1,1) Spacecraft mass
                 .mu                 (1,1) Gravitational constant
                 .force              (3,1) External force in the ECI frame
                 .torque             (3,1) External torque in the body frame
                 .inrRWA             (n,1) Polar inertia of each wheel
                 .torqueRWA          (n,1) Torques on each wheel
                 .uRWA               (3,n) Unit vectors for the RWA
                 .friction            (.) Friction data structure
Outputs
 xDot   (13+n,1)  State vector derivative d[r;v;q;omega;omegaRWA]/dt
 hECI   (3,1)     Inertial angular momentum
See also
: ReactionWheelFriction
References and(), Cross(), Friction(), Mag(), QIToBDot(), QTForm(), ReactionWheelFriction(), RHSSpacecraftWithRWA(), RWA(), Unit(), and vector().
Referenced by RHSSpacecraftWithRWA().
RHSThreeBody()
function RHSThreeBody (in x, in ignoredArg, in d)
 Each of the two appendages have one degree of freedom.
Form
 d = RHSThreeBody;
 [xDot, h] = RHSThreeBody( x, t, d )
Inputs
 x             (11,1)  [q;omega0;theta1;theta2;omega1;omega2]
 t             (1,1)   Time - unused
 d             (1,1)   Data structure
                       .inr0     (3,3) Inertia matrix core body
                       .inr1     (3,3) Inertia matrix body 1
                       .inr2     (3,3) Inertia matrix body 2
                       .m0       (1,1) Mass core body
                       .m1       (1,1) Mass matrix body 1
                       .m2       (1,1) Mass matrix body 2
                       .lambda1  (3,1) Location of body 1 hinge
                       .lambda2  (3,1) Location of body 2 hinge
                       .u1       (3,1) Body 1 hinge unit vector
                       .u2       (3,1) Body 2 hinge unit vector
                       .rho0     (3,1) Location of body 0 center of mass
                       .rho1     (3,1) Location of body 1 center of mass
                       .rho2     (3,1) Location of body 2 center of mass
Outputs
 xDot           (11,1)  State derivative
 h              (3,1)   Angular momentum in the inertial frame
References AU2M(), DefaultDataStructure(), QIToBDot(), QTForm(), RHSThreeBody(), set(), Skew(), SkewSq(), and vector().
Referenced by RHSThreeBody().
RIGModel()
function RIGModel (in u, in w, in b, in nRW, in nB, in beta)
 dang/dt = w + b + nRW*randn
 db/dt = -beta*b +  nb*randn
 Includes a random walk and bias drift model.
 The drift noise can be correlation
 This routine does not check inputs.
 The state vector is [angle; bias]
 Since version 1.
Form
 dxdt = RIGModel( u, w, b, nRW, nB, beta )
Inputs
 u            (3,n)     Unit vectors for the gyro axes in body axes
 w            (3,1)     Body rates
 b            (n)       Bias rate
 nRW          (n)       Bias 1 sigma noise (random walk)
 nB           (n)       Bias 1 sigma drift noise
 beta         (n)       Bias correlation time constant
Outputs
 dxdt         (2n)      [AngularRate dBias/dt]
References and(), Unit(), and vector().
Referenced by FRBwRIG().
RIGOut()
function RIGOut (in intRate, in intRateOld, in n)
 Since version 1.
Form
 [angInc, intRateOld] = RIGOut( intRate, intRateOld, n )
Inputs
 intRate      (n,1)     Integrated rate
 intRateOld   (n,1)     Old integrated rate
 n            (n,1)     Noise vector
Outputs
 angInc       (n,1)     Angular increments
 intRateOld   (n,1)     Old integrated rate
References vector().
RLP()
function RLP (in uSun, in rAI, in decI, in rAF, in decF)
Form
 [azimuth, prec] = RLP( uSun, rAI, decI, rAF, decF )
Inputs
 uSun         (3,1)     Sun Vector
 rAI          (1,1)     Initial right ascension (rad)
 decI         (1,1)     Initial declination (rad)
 rAF          (1,1)     Final right ascension (rad)
 decF         (1,1)     Final declination (rad)
Outputs
 azimuth      (1,1)     Maneuver azimuth (rad)
 prec         (1,1)     Required precession (rad)
References abs(), and(), Cross(), RaDec2U(), and Unit().
Referenced by ECIToRLP(), NPSPM(), and SPMDataF().
RLPMnvr()
function RLPMnvr (in uSun, in rAI, in decI, in azimuth, in prec, in n)
 Since version 1.
Form
 [rA, dec, beta] = RLPMnvr( uSun, rAI, decI, azimuth, prec, n )
Inputs
 uSun         (3,1)     Sun Vector
 rAI          (1,1)     Initial right ascension (rad)
 decI         (1,1)     Initial declination (rad)
 azimuth      (1,1)     Maneuver azimuth (rad)
 prec         (1,1)     Precession/pulse (rad)
 n            (1,1)     Number of pulses
Outputs
 rA            (n+1)     Right Ascension (rad)
 dec           (n+1)     Declination  (rad)
 beta          (n+1)     Sun angles (rad)
References abs(), Cross(), Dot(), length(), NewFig(), Plot2D(), RaDec2U(), RLPMnvr(), set(), U2RADec(), Unit(), vector(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by RLPMnvr().
RMoonECI()
function RMoonECI (in jD)
 Uses SunV1
Form
 r = RMoonECI( jD )
Inputs
 jD        (1,:)   Julian date
Outputs
 r         (3,:)   Moon vector
References Date2JD(), length(), MoonV1(), SunV1(), vector(), and zeros().
RocketEquation()
function RocketEquation (in deltaU, in massInitial, in uExhaust)
You use any combination of inputs as vectors that make sense. However, if you want internal plots you should only have one be an array. Otherwise it will always plot with x being the first input that is > length 1. The delta-V and exhaust velocity must have the same units.
Form
 massFinal = RocketEquation( deltaU, massInitial, uExhaust )
Inputs
 deltaU       (1,:)   Required delta-v
 massInitial  (1,:)   Initial mass
 uExhaust     (1,:)   Exhaust velocity
Outputs
 massFinal    (1,:)   Final mass
References and(), length(), NewFig(), Plot2D(), RocketEquation(), and Watermark().
Referenced by RocketEquation().
RSunECI()
function RSunECI (in jD)
 Uses SunV1
Form
 r = RSunECI( jD )
Inputs
 jD        (1,:)   Julian date
Outputs
 r         (3,:)   Sun vector
References Date2JD(), length(), SunV1(), vector(), and zeros().
RW2SDev()
function RW2SDev (in randomWalk)
Form
 n = RW2SDev( randomWalk )
Inputs
 randomWalk       (:)     Random walk (deg/sqrt(hour))
Outputs
 n                (:)     Standard deviation (rad/sec)
References Random().
Referenced by Gyro(), and GyroData().
RWA()
function RWA (in action, in y, in k)
You will initialize to a Honeywell HR0610 model. Only marketing sheet data is used. This model uses FrictionSmooth to model the friction.
 k      = RWA( 'initialize' );                         Initializes the wheel
 k      = RWA( 'initialize',                 [], k );  Initializes the wheel(s)
 x      = RWA( 'get tachometer measurement', [], k );  Gets the wheel speed
 d      = RWA( 'get default datastructure',  [], k );  Gets the default RWA data
 d      = RWA( 'get datastructure',          [], k );  Gets the RWA data
 x      = RWA( 'get power',                  [], k );  Gets the power.
 x      = RWA( 'get current',                [], k );  Gets the power from d
 x      = RWA( 'get motor voltage',          [], k );  Gets the motor voltage.
 RWA( 'put voltage',               vIn, k );  Puts the voltage into d
 x      = RWA( 'compute torque',             [], k );  Computes torque
 RWA( 'torque speed curve',      omega, k );  Plots the torque speed curve
 if omega is [] it will use a
 default rate vector. Omega
 must be a 1-by-n array.
k can be a number or a tag. A typical calling sequence is:
 RWA;
 loop:
 d           = RWA( 'put voltage',       voltageIn, k );
 [torque, d] = RWA( 'compute torque',    omega,     k );
 power       = RWA( 'get power',         [],        k );
 current     = RWA( 'get current',       [],        k );
 voltage     = RWA( 'get motor voltage', [],        k );
 end loop;
Form
 x = RWA( action, y, k )
Inputs
 action    (:)    Action
 y         (1,1)  See above
           (.)    Datastructure for the wheels
                  .kT          (1,1) Torque constant (N/A)
                  .kV          (1,1) Voltage Gain (N/rad/sec)
                  .kW
                  .friction    = struct( 'fStatic',  (1,1), 'kStatic',  (1,1),
                                         'fCoulomb', (1,1), 'kCoulomb', (1,1),
                                         'bViscous', (1,1) );
                  .currentMax  (1,1) Upper current limit (A)
                  .currentMin  (1,1) Lower current limit (A)
                  .busVoltage  (1,1) Bus voltage
                  .r           (1,1) Motor resistance (Ohms)
                  .kMaxTach    (1,1) Maximum tach count
                  .kMinTach    (1,1) Minimum tach count
                  .resTach     (1,1) Tach resolution
                  .kMaxVoltage (1,1) Maximum voltage count
                  .kMinVoltage (1,1) Minimum voltage count
                  .resVoltage  (1,1) D/A resolution
                  .kMinVoltage (1,1) Minimum voltage count
                  .voltageWord (1,1) Voltage word
                  .omega       (1,1) Wheel speed
                  .power       (1,1) Electrical power
                  .current     (1,1) Motor current
                  .voltage     (1,1) Motor voltage
                  .inertia
Outputs
 x        (:)    Output
 k        (1,1)  Index
References abs(), and(), FloatToWord(), FrictionSmooth(), get(), isempty(), length(), Plot2D(), ProcessTag(), RWA(), vector(), WordToFloat(), and zeros().
Referenced by DFFAttitudeController(), FMagSim(), FrictionSmooth(), FRWA(), FRWABristle(), ReactionWheel(), RHSReactionWheel(), RHSReactionWheelWithOrbit(), RHSRWAOrbit(), RHSSNP(), RHSSNP(), RHSSpacecraftWithRWA(), RWA(), RWAArray(), RWABristle(), RWACountToRate(), RWAModel(), RWAPatch(), RWASizing(), RWASmart(), RWASpec(), RWAWithPower(), ThrusterAndRWACommand(), and URWAPyramid().
RWABristle()
function RWABristle (in action, in y, in k)
Initializes to a Honeywell HR0610 model. A typical calling sequence is
 RWA;
 or k = RWABristle( 'initialize' );
 or k = RWABristle( 'initialize', y, k );
 loop:
 tachMeas    = RWABristle( 'get tachometer measurement',  [],           k );
 RWABristle( 'put omega',                   omega,        k );
 RWABristle( 'put bristle state',           bristleState, k );
 RWABristle( 'put omega dot',               omegaDot,     k );
 RWABristle( 'put voltage',                 voltageIn,    k );
 RWABristle( 'update',                      [],           k );
 torque      = RWABristle( 'get torque',                  [],           k );
 xDot        = RWABristle( 'get state derivative',        [],           k );
 power       = RWABristle( 'get power',                   [],           k );
 current     = RWABristle( 'get current',                 [],           k );
 voltage     = RWABristle( 'get motor voltage',           [],           k );
 end loop;
Form
 x = RWABristle( action, y, k )
Inputs
 action   (:)    Action
 y         (1,1)  See above
           (1,1)  Datastructure for the wheels
                  .kT           (1,1) Torque constant (N/A)
                  .kV           (1,1) Voltage Gain (N/rad/sec)
                  .friction           .fStatic   - Static friction scaling coefficient
                                      .fCoulomb  - Coulomb friction maximum
                                      .vStribeck - Stribeck velocity
                                      .bViscous  - Viscous friction coefficient
                                      .sigma0    - Bristle friction coefficient
                                      .sigma1    - Bristle derivative coefficient
                  .currentMax   (1,1) Upper current limit (A)
                  .currentMin   (1,1) Lower current limit (A)
                  .busVoltage   (1,1) Bus voltage
                  .r            (1,1) Motor resistance (Ohms)
                  .kMaxTach     (1,1) Maximum tach count
                  .kMinTach     (1,1) Minimum tach count
                  .resTach      (1,1) Tach resolution
                  .kMaxVoltage  (1,1) Maximum voltage count
                  .kMinVoltage  (1,1) Minimum voltage count
                  .resVoltage   (1,1) D/A resolution
                  .voltageWord  (1,1) Voltage word
                  .omega        (1,1) Wheel speed
                  .power        (1,1) Electrical power
                  .current      (1,1) Motor current
                  .voltage      (1,1) Motor voltage
                  .failure      (1,1) 1 means failed
 k        (1,:)  Tag see ProcessTag
Outputs
 x        (:)    Output
References abs(), and(), FloatToWord(), FrictionBristle(), get(), isempty(), length(), ProcessTag(), RWA(), set(), WordToFloat(), and zeros().
Referenced by FRWABristle().
RWACountToRate()
function RWACountToRate (in tachWord, in d)
Form
 omega = RWACountToRate( tachWord, d )
Inputs
 tachWord         (:)   Tach word from RWASmart
 d                (:)   Data structure from RWASmart
References length(), RWA(), and RWASmart().
RWAMnvrSizing()
function RWAMnvrSizing (in inr, in theta, in tau)
Type RWAMnvrSizing for a demo of a 3U CubeSat
Form
 [t, h] = RWAMnvrSizing( inr, theta, tau )
Inputs
 inr         (1,1)  Spacecraft inertia (kg-m^2)
 theta       (1,1)  Maneuver angle (rad)
 tau         (1,:)  Maneuver duration (s)
Outputs
 t           (1,:)  Torque (Nm)
 h           (1,:)  Momentum storage (Nms)
References Demo(), InertiaCubeSat(), and RWAMnvrSizing().
Referenced by RWAMnvrSizing().
RWASizing()
function RWASizing (in inr, in omega, in omegaDot, in omegaRWAMax)
Type RWASizing for a demo of a 3U CubeSat going 5 deg/s and accelerating to that in 5 seconds.
Momentum storage will also be a function of how much momentum you want to absorb from disturbances. The reaction wheel inertia is computed using a default angular rate for the wheel of 628 rad/s.
Form
 [t, h, inrRWA] = RWASizing( inr, omega, omegaDot, omegaRWAMax )
Inputs
 inr         (1,1)  Spacecraft inertia (kg-m^2)
 omega       (1,1)  Angular rate (rad/s)
 omegaDot    (1,1)  Angular acceleration (rad/s^2)
 omegaRWAMax (1,1)  Maximum angular rate (rad/s), default 628
Outputs
 t           (1,1)  Torque (Nm)
 h           (1,1)  Momentum storage (Nms)
 inrRWA      (1,1)  Inertia rwa
References and(), Demo(), Dot(), InertiaCubeSat(), RWA(), and RWASizing().
Referenced by RWASizing().
RWASmart()
function RWASmart (in action, in u)
This models an RWA using Hall sensors.
 The model has four states. They are:
 [Omega;...
 Integral of current error;...
 Bristle;...
 Wheel angle];
 The second is used if kA is non zero and the model bandwidth is high.
 The last is used only at small rates and only for the tachometer model.
 The GUI allows you to set the electrical dynamics on or off.
Form
 y = RWASmart( action, u )
 When numerically integrating
 xDot = RWASmart( t, u );
 Actions with only inputs:
 RWASmart( 'initialize', rWADatastructure );
 RWASmart( 'put data word', rWATorqueCommand );
 RWASmart( 'set failure', failedRWAID );
 RWASmart( 'set data', rWADatastructure );
 RWASmart( 'set tachometer states', struct( 'omega', rWARate, 'angle', rWAAngle ) );
 Actions with output:
 rWADatastructure        = RWASmart( 'get datastructure' );
 defaultRWADatastructure = RWASmart( 'get default datastructure' );
 tachometerWord          = RWASmart( 'GetTachometerWord ' );
 frictionTorque          = RWASmart( 'get friction torque' );
 reactionTorque          = RWASmart( 'get torque' );
 electricalPower         = RWASmart( 'get power' );
 motorCurrent            = RWASmart( 'get motor current' );
 motorVoltage            = RWASmart( 'get motor voltage' );
 y                       = RWASmart( 'update' );
 xDot                    = RWASmart( x, u );
 xDot                    = RWASmart( 'get state derivative', x );
Inputs
 action   (:)    Action or state
 u         (1,1)  Input depends on action
Outputs
 y        (:)    Output depends on action
References abs(), and(), CloseIfHandle(), FrictionBristle(), get(), GetH(), Initialize(), Integral(), isempty(), length(), PutH(), RadioButtons(), RHS(), RWA(), RWASmart(), set(), and zeros().
Referenced by RWACountToRate(), and RWASmart().
RWASpec()
function RWASpec (in input)
If all spec sheet info is not entered, then a GUI will come up with entry blocks for the needed info. Not all parameters can be found from spec sheets.
Form
 d = RWASpec( input )
Inputs
 input    (.)      Data structure. Any or all of the following field
                  can be included. Those marked with * must be entered
                  to prevent the GUI from being drawn. Default values
                  are shown in [].
 .voltageRange    Max voltage counts * voltage resolution [5]
 .kMaxVoltage     Max voltage count [128]
 .kMinVoltage     Min voltage count [-127]
 .resVoltage      Voltage resolution [10/256]
 .kMaxTach        Maximum tach count [2048]
 .kMinTach        Minimum tach count [-2047]
 .resTach         Tach resolution   [410*pi/4096]
 .tC              Coulomb friction (N) [0]
 *   .busVoltage      Bus voltage (V) [23]
 *   .holdingPower    Power holding max speed (W) [33]
 *   .peakPower       Peak power (W)  [80]
 *   .maxSpeed        Maximum wheel speed (rad/sec)  [628]
 *   .torque          Max output torque (Nm)  [0.075]
Outputs
 d       (.)       Data structure
           .kT          (n,1) Torque constant (N/A)
           .kV          (n,1) Voltage gain (V/V)
           .kW          (n,1) Viscous friction (N/rad/sec)
           .tC          (n,1) Coulomb friction (N)
           .iMax        (n,1) Current Limit (A)
           .iMin        (n,1) Current Limit (A)
           .r           (n,1) Resistance (Ohms)
           .kMaxTach    (1,1) Maximum tach count
           .kMinTach    (1,1) Minimum tach count
           .resTach     (1,1) Tach resolution
           .kMaxVoltage (1,1) Maximum voltage count
           .kMinVoltage (1,1) Minimum voltage count
           .resVoltage  (1,1) D/A resolution
           .kBusVoltage (1,1) Bus voltage
References get(), Limit(), RWA(), and RWASpec().
Referenced by RWASpec().
RWAWithPower()
function RWAWithPower (in omega, in d)
The friction function should have the form
 f = ReactionWheelFriction( omega, d )
Form
 [torque, power, heat] = RWAWithPower( omega, d )
Inputs
 omega   (3,1) RWA angular rate (rad/s)
 d       (.)   Data structure
               .kT         (1,1) Torque to voltage gain
               .friction    (.)  Data structure
                   .fun          (*)  Function handle
                   .data         (.)  Data structure for fun
               .voltage    (3,1) Command voltage
               .inertia    (3,1) Wheel inertias
               .u          (3,3)
               .voltageMax (1,1)
Outputs
 torque  (3,1) RWA torque (Nm)
 power   (1,1) Total power (W)
 heat    (1,1) Heat output (W)
See also
ReactionWheelFriction
References abs(), and(), DefaultDataStructure(), ReactionWheelFriction(), RWA(), and RWAWithPower().
Referenced by RWAWithPower().
RYDyn()
function RYDyn (in inr, in hw, in wo, in iAxis)
 Automatically plots double integrator and the low-order plants too. Since
 the plant is minimum phase you don't need the phase plots. The full
 order plant includes the nutation mode. The low order plant includes
 only the orbit rate mode. The frequency vector gives the frequencies
 used in the plots.
 Since version 1.
Form
[a, b, c, d, aL, bL, cL, dL, w] = RYDyn(inr, hw, wo, iAxis)
Inputs
 inr           (3,1) Inertia matrix
 hw            (3,1) Momentum vector
 wo            (3,1) Angular velocity vector
 iAxis         (1,2) Axes of interest (any two transverse to wo)
Outputs
 a             (4,4) Full order roll/yaw plant matrix
 b             (4,2) Full order roll/yaw input matrix
 c             (2,4) Full order roll/yaw output matrix
 d             (2,2) Full order roll/yaw feedthrough matrix
 aL            (2,2) Low order roll/yaw plant matrix
 bL            (2,2) Low order roll/yaw input matrix
 cL            (2,2) Low order roll/yaw output matrix
 dL            (2,2) Low order roll/yaw feedthrough matrix
 w             (1,:) Frequency vector used
References and(), and RYDyn().
Referenced by RYDyn().
S2HMS()
function S2HMS (in s)
 Since version 1.
Form
 [h, m, s] = S2HMS( s )
Inputs
 s              (1,:) Seconds
Outputs
 h              (1,:)  hours
 m              (1,:)  minutes
 s              (1,:)  seconds
 or
 h              (3,:)  [hours;minutes;seconds]
References and().
SatelliteSubsystemMass()
function SatelliteSubsystemMass (in subsystem, in mSc, in param)
You pass in the subsystem name and the BOL spacecraft mass. The data is based on the Intelsat V satellite and other communications satellites.
 Subsystem                 param
 'acs'
 'thermal'
 'propulsion insertion'    fuel mass
 'propulsion rcs'          life in years
 'structure'
 'power'                   communications system power (W)
 'electrical integration'
 'mechanical integration'
 'payload'                 communications system power (W)
As shown in the built-in demo, you need to iterate on the function as you build up the satellite mass.
Form
 SatelliteSubsystemMass;   % demo
 m = SatelliteSubsystemMass( subsystem, mSc, param )
Inputs
 subsystem (1,:) Subsystem name
 mSc       (1,1) Beginning of life mass (kg)
 param     (1,1) Insertion fuel mass, life in years or comm power
Outputs
 m        (1,1) Mass (kg)
References: Agrawal, B. ,"Design of Geosynchronous Spacecraft," Prentice-Hall, 1986.
References and(), Demo(), SatelliteSubsystemMass(), and zeros().
Referenced by MassBudget(), and SatelliteSubsystemMass().
SaveSurfacePropertiesDSim()
function SaveSurfacePropertiesDSim (in file, in v, in f, in cD, in rho)
You need to open and close the file externally. rho is optional. The calling sequence is
 file = fopen('myfile.txt','wt');
 fprintf(file,'[\n');
 SaveSurfacePropertiesDSim( file, v, f, cD, rho );
 fprintf(file,']\n');
 fclose(file);
This creates a DSim matrix.
Form
 SaveSurfacePropertiesDSim( file, v, f, cD, rho )
Inputs
 file        (1,1) File id
 v           (n,1) Vertices
 f           (m,1) Faces
 cD          (1,1) Drag coefficient
 rho         (1,4) Optical properties
Outputs
 None
References and(), and close().
SCClock()
function SCClock (in action, in d)
Form
 y = SCClock( action, d )
Inputs
 action      (1,:)     'initialize' 'get power' 'set failure' 'derivative'
 d           (1,1)     Depends on the action
Outputs
 y           (1,1)     Depends on the action
References get(), and set().
ScDB()
function ScDB (in q, in gUICode)
This function has a sample database.
 To make one for your vehicle you edit the internal functions Catalog()
 and Database()
 1. Make a list of parameters, their values and units.
 2. Enter the list in the Database() function
 3. Add the list to Catalog() function
 To use the GUI just type ScDB and an interactive GUI will appear. The list
 will include everything in the database. Type
 a string into search string to search for a parameter. Click on the
 parameter that appears to get its value and units. If you type 'all'
 then all parameters will appear.
 When you click on a parameter it will appear in the GUI and in the
 workspace.
 Searches are NOT case sensitive.
 To access a parameter without the GUI type
 [x, u] = ScDB( 'my parameter' );
 Since version 1.
Form
 [x, u] = ScDB( q, gUICode )
Inputs
 q             (1,:)   String describing the constant
 gUICode       (1,:)   You don't use this.
Outputs
 x             (:)     The value
 u             (1,:)   Units (if applicable)
References and(), Database(), get(), isempty(), length(), ScDB(), and set().
Referenced by ScDB().
SCWithRollPivot()
function SCWithRollPivot (in x, in t, in d, in action)
 The  wheel spins about the -y axis in the pivot frame. The wheel is forced
 to be symmetric so that we do not have to account for a wheel angle.
Form
 [xDot, h1, inr, p] = SCWithRollPivot( x, t, d, action )
Inputs
 x           (10,1)  State vector [q;theta,w,wP,wW]
 d           (:,:)   .scInertia           (3,3) Spacecraft inertia
                     .bWheelAlignment     (3,3) Wheel alignment
                     .pivotInertia        (3,3) Pivot inertia
                     .wheelInertia        (1,2) [ Wheel polar inertia, transverse inertia]
                     .commandedPivotAngle (1,1) Commanded angle
                     .pivotRateGain       (1,1) Pivot rate gain
                     .pivotAngleGain      (1,1) Pivot angle gain
                     .torque              (3,1) Torque on the spacecraft
                     .torqueWheel         (1,1) Torque on the wheel
 action      (1,:)   Any input returns h
Outputs
 xDot        (10,1)  State vector derivative [theta,w(3,1),wP,wW] or body
                     angular momentum
 h           (3,1)   Angular momentum in the body frame
 iner        (5,5)   Generalized inertia matrix
References and(), Euler(), Inertias(), QIToBDot(), Skew(), and vector().
SCwPivot()
function SCwPivot (in x, in jW, in jP, in iS, in t, in tW, in tP, in uW, in uP)
 The pivot has one degree of freedom of rotation about the axis uP. The wheel
 has one degree of rotation about the axis uW. The wheel is assumed to be
 symmetric.
Form
 [xDot, h, i, p] = SCwPivot( x, jW, jP, iS, t, tW, tP, uW, uP )
Inputs
 x           (6,1)   State vector [theta,w(3,1),wP,wW]
 jW          (3,3)   Wheel inertia (must be symmetric)
 jP          (3,3)   Pivot assembly inertia
 iS          (3,3)   Spacecraft inertia
 t           (3,1)   Body torque
 tW          (1,1)   Wheel torque
 tP          (1,1)   Pivot torque
 uW          (3,1)   Wheel axis
 uP          (3,1)   Pivot axis
Outputs
 xDot        (6,1)   State vector [theta,w(3,1),wP,wW]
 h           (3,1)   Momentum
 i           (5,5)   Generalized inertia matrix
 p           (5,1)   Dynamical coupling terms
References and(), AU2Q(), Cross(), Q2Mat(), SkewSymm(), vector(), and zeros().
Referenced by FPivot().
SDG()
function SDG (in u, in h, in cD, in k, in kF, in w, in x, in bias, in nU, in nV, in nE)
 To make a rate gyro             set kF = h    and k.*kF./cD >> 1
 To make a rate integrating gyro set k  = cD/h and k.*kF./cD << 1
 Since version 1.
Form
 [dxdt,y]     = SDG( u, h, cD, k, kF, w, x, bias, nU, nV, nE )
 [a, b, c, d] = SDG( u, h, cD, k, kF )
Inputs
 u            (3,n)     Gyro unit vectors
 h            (1,n)     Angular momentum
 cD           (1,n)     Damping
 k            (1,n)     Forward gain
 kF           (1,n)     Torque rebalance gain
 w            (3,1)     Input rate vector
 x            (3n,1)    State vector [Random Walk
                                      Integral of inputs
                                      Integral of outputs]
 bias         (1,n)     Biases
 nU           (1,n)     Bias drift noise
 nV           (1,n)     Rate noise
 nE           (1,n)     Output noise
Outputs
 dxdt         (3n,1)    State derivatives
 y            ( n,1)    Gyro output
 or
 a            (3n,3n)   State matrix
 b            (3n,3n)   Input matrix
 c            ( n,3n)   Measurement matrix
 d            ( n,3n)   Feedthrough matrix
References and(), Gyro(), Integral(), length(), Random(), set(), vector(), and zeros().
Referenced by FSDG(), and GyroData().
SeparationSim()
function SeparationSim (in x0, in dT, in tEnd, in d)
Form
 x = SeparationSim( x0, dT, tEnd, d )
Inputs
 x0               (13,1)   Core vehicle state
 dT               (1,1)    Time step (sec)
 tEnd             (1,1)    End time (sec)
 d                (1,1)    Data structure
                           .t      (3,n)   Disturbance torques in body k frame
                           .f      (3,n)   Disturbance forces in ECI frame (kN)
                           .inr    {n}     Inertia matrix in body k frame
                           .m      (n)     Mass (kg)
                           .mu     (1,1)   Gravitational parameter
                           .lambda (:,n )  Vectors from hinge to cm in k frame
                           .kappa  (:,n)   Vectors from body 0 cm to hinges
                           .b      {n }    Transformation matrix from k to 1
                           .e0     (3,1)   Location of body 0 cm (m)
                           .k      (n,1)   Spring Constant (N/m)
                           .u      (3,n)   Spring unit vectors
                           .lS     (n,1)   Spring lengths (m)
Outputs
 x                (13*n,nSim) State vector
SingleAxisDrive()
function SingleAxisDrive (in action, in d)
Inputs
 action      (1,:)     'initialize' 'set failure' 'get power consumption'
                       'set steps' 'set direction' 'get angle'
                       'set angle'  'update' 'get default datastructure'
 d           (1,1)     Depends on the action
Outputs
 y           (1,1)     Depends on the action
References abs(), get(), and set().
SingleAxisLinearDrive()
function SingleAxisLinearDrive (in action, in d)
Typing SingleAxisLinearDrive is the same as SingleAxisLinearDrive('initialize')
Inputs
 action      (1,:)     'initialize' 'get power consumption'
                       'set torque'  'get torque'
                       'get state derivative' 'update'
                       'set failure' 'get default datastructure'
 d           (1,1)     Depends on the action
Outputs
 y           (1,1)     Depends on the action
References get(), set(), and SingleAxisLinearDrive().
Referenced by SingleAxisLinearDrive().
SkewDipl()
function SkewDipl (in b, in tRoll, in tYaw)
 The x-axis is assumed to be the roll axis and the z-axis is assumed to be
 the yaw axis. The y-axis is along orbit anti-normal.
 Since version 1.
Form
 [theta, mDipole, m] = SkewDipl( b, tRoll, tYaw )
Inputs
 b             (3,1) Magnetic field vector (T)
 tRoll         (1,1) Maximum roll torque   (N)
 tYaw          (1,1) Maximum yaw torque    (N)
Outputs
 theta         (1,1) Positive angle (about +y)
                     of the dipole taken from +x (deg)
 mDipole       (1,1) Dipole magnitude (ATM^2)
 m             (3,1) Dipole unit vector
References and(), Dipole(), Unit(), vector(), and zeros().
SolarF()
function SolarF (in p, in rho, in normal, in source, in area)
 Since version 1.
Form
 f = SolarF( p, rho, normal, source, area )
Inputs
 p             (1,1) Solar pressure (flux/speed of light)
 rho           (3,n) Coefficient fraction, may also be (3,1)
                     [absorbed;specular;diffuse]
 normal        (3,n) Surface normal vector
 source        (3,1) Unit vector to source
 area          (n)   Elemental area
Outputs
 f             (3,n) Solar force
Reference: Hughes, P. C., "Spacecraft Attitude Dynamics" John Wiley and Sons, 1986, pp. 260-263.
References and(), Initialize(), length(), set(), Unit(), vector(), and zeros().
Referenced by CubeSatRadiationPressure(), and ThreeAxisControlDisturb().
SolarFlux()
function SolarFlux (in r, in n)
Inverse quadratic formula scales anywhere in the solar system. The nominal value at 1 AU is 1367 W/m2. Either n or r can be arrays but if either is
length(1) they must have the same length.
Type SolarFlux for a demo.
Form
 flux = SolarFlux( r, n )
Inputs
 r     (1,:) Astronomical units from the sun (AU)
 n     (1,:) Number of sunspots (default is 0)
Outputs
 flux   (1,:) Solar flux (watts/m^2)
See also
SolarFlx and TerrestrialSolarFlux.
Reference: Ambelu T, Falayi E.O., Elemo, E.O., Oladosu O., "Estimation of total solar irradiance from sunspot number," Lat. Am. J. Phys. Educ. Vol. 5, No. 4, Dec. 2011.
References and(), Demo(), length(), Plot2D(), SolarFlux(), SolarFlx(), and TerrestrialSolarFlux().
Referenced by SolarFlux().
SolarFluxFromPlateECI()
function SolarFluxFromPlateECI (in r, in rP, in n, in a, in rho, in b, in fNum, in jD)
Assumes a single sided Lambertian radiator. Includes eclipses. This function assumes that the spacecraft are in earth orbit. The function does not handle blockage from the earth since the distance would be too great for any flux to reach the spacecraft from the target.
Type SolarFluxFromPlateECI for a demo of two spacecraft about 7 km apart. The camera in the demo points at the target and the flat plate points at the camera. The flate plate is in a slightly elliptical orbit.
Form
 e = SolarFluxFromPlateECI( r, rP, n, a, rho, b, fNum, jD )
Inputs
 r         (3,:)   Spacecraft position in ECI (km)
 rP        (3,:)   Plate position in ECI (km)
 n         (3,:)   Plate outward normal vector in ECI
 a         (1,1)   Plate area (m^2)
 rho       (1,1)   Surface albedo (0 to 1)
 b         (3,1)   Boresight (ECI)
 fNum      (1,1)   f# = focal length/aperture
 jD        (1,:)   Julian Date (day)
Outputs
 e         (1,:)   Flux (W/m^2)
Reference: Trucco, E. and A. Verri, "Introductory Techniques for 3-D Computer, Vision," Prentice-Hall, 1998, pp. 22-25.
References and(), Date2JD(), Demo(), Dot(), Eclipse(), length(), Mag(), RVOrbGen(), SolarFluxFromPlateECI(), SunV1(), Unit(), and vector().
Referenced by MeasCamera(), and SolarFluxFromPlateECI().
SolarFluxHistorical()
function SolarFluxHistorical (in jD)
The outputs of this function may be used by AtmJ70. Stores the data in a persistent variable. Clear the function to reload.
The database may be updated from a new history file using LoadSolarFluxHistory.
Has a built-in demo that plots for no outputs.
Form
 jDend = SolarFluxHistorical; % last valid date
 d = SolarFluxHistorical( jD )
 [aP, f, fHat, fHat400] = SolarFluxHistorical( jD )
Inputs
 jD          (1,1) Julian date
Outputs
 aP          (1,1) Geomagnetic index 6.7 hours before the computation
 f           (3,1) Daily 10.7 cm solar flux (e-22 watts/m^2/cycle/sec)
 fHat        (3,1) 81-day mean of f (e-22 watts/m^2/cycle/sec)
 fHat400     (3,1) fHat 400 days before computation date
   - or -
 d            (.)  Data structure for ingestion by AtmJ70. JD form:
                   .jD      (1)   Input Julian date
                   .rECI    (3,1) ECI position
                   .aP      (1,1) Geomagnetic index
                   .f       (1,1) Daily 10.7 cm solar flux
                   .fHat    (1,1) 81-day mean of f
                   .fHat400 (1,1) fHat 400 days before
References AtmJ70(), Date2JD(), isempty(), length(), LoadSolarFluxHistory(), SolarFluxHistorical(), and zeros().
Referenced by AtmNRLMSISE(), and SolarFluxHistorical().
SolarFluxPrediction()
function SolarFluxPrediction (in jD, in timing, in dateForm)
This function requires the mat files "SolarFluxPredictions" and "Kp_ap_Ap_SN_F107_since_1932". Returns historical flux data when available and otherwise loads prediction data. Prediction data through 2040 includes error bars on the daily 10.7 cm flux (predicted/high/low) and does NOT include the geomagnetic idnex aP. The outputs of this function are used by AtmJ70. Give a single output to get a struct, use a third input to specify which date/location format.
Earlier prediction data had early, nominal, and late timing of the solar cycle, which shifted the model on the order of a few months. The latest prediction data from NOAA does not have this timing but the input is left for backwards compatibility.
The database is good until 2040. Historical data has been loaded through November, 2021. Databases are stored as persistent variables for faster funtion calls.
Has a built-in demo that plots for no outputs.
Form
 SolarFluxPrediction;   % Plot the available data
 d = SolarFluxPrediction( jD, timing, dateForm )
 [aP, f, fHat, fHat400] = SolarFluxPrediction( jD, timing )
Inputs
 jD          (1,1) Julian date
 timing       ''   'nominal', 'early', or 'late'
 dateForm     (1)  True: lat/lon datenum struct. False: jD / rECI struct.
Outputs
 aP          (1,1) Geomagnetic index 6.7 hours before the computation
 f           (3,1) Daily 10.7 cm solar flux (e-22 watts/m^2/cycle/sec)
 fHat        (3,1) 81-day mean of f (e-22 watts/m^2/cycle/sec)
 fHat400     (3,1) fHat 400 days before computation date
   - or -
 d            (.)  Data structure for ingestion by AtmJ70. JD form:
                   .jD      (1)   Input Julian date
                   .rECI    (3,1) ECI position
                   .aP      (1,1) Geomagnetic index
                   .f       (1,1) Daily 10.7 cm solar flux
                   .fHat    (1,1) 81-day mean of f
                   .fHat400 (1,1) fHat 400 days before
References and(), AtmJ70(), Date2JD(), get(), isempty(), length(), Plot2D(), SolarFluxPrediction(), and zeros().
Referenced by AtmNRLMSISE(), RHSCubeSat(), SailEnvironment(), SolarFluxPrediction(), and TubeSatDefaultDataStructure().
SolarFlx()
function SolarFlx (in au)
Inverse quadratic formula scales anywhere in the solar system. The nominal value at 1 AU is 1367 W/m2.
Type SolarFlx for a demo.
Form
 flux = SolarFlx( au )
Inputs
 au      (1,:) Astronomical units from the sun
Outputs
 flux    (1,:) Solar flux (watts/m^2)
References Demo(), Plot2D(), and SolarFlx().
Referenced by Disturbances(), DrawSailMeshVectors(), Isothermal(), PlanetaryRadiationAndAlbedo(), RHSIsothermal(), SolarFlux(), SolarFlx(), and SolarPressureForce().
SolarSys()
function SolarSys (in iv, in Wv, in wv, in av, in ev, in Lv, in name, in jdref, in T)
 If no outputs are given will plot the positions of the input planets.
 If no inputs are given it will compute the vectors for the entire
 solar system. If T is not input, it will compute a vector of T's
 long enough to show the complete orbit of the outermost planet.
Inputs
 If T is omitted in either form it will generate a T to cover the
 orbital period of all of the planets. The second form handles the data
 structure output of Planets which is d.iv, ...
Form
 [rx0, ry0, rz0, vx, vy, vz] = SolarSys( iv, Wv, wv, av, ev, Lv, name, jdref, T )
 [rx0, ry0, rz0, vx, vy, vz] = SolarSys( d, T )
Inputs
 iv            (n,2)   Inclination wrt ecliptic plane     (rad)
 Wv            (n,2)   Longitude of ascending node wrt vernal equinox  (rad)
 wv            (n,2)   Argument of perhelion      (rad)
 av            (n,2)   Mean distance (au)
 ev            (n,2)   Eccentricity
 Lv            (n,3)   Mean longitude (rad)
 name          (n,:)   Name of planet
 jdref         (1,1)   Reference Julian date
   - OR -
 d              (:)    Data structure with above fields
 T             (1,:)   Julian centuries from J2000.0   (centuries)
Outputs
 rx0           (n,:)   x component,  one row per planet (au)
 ry0           (n,:)   y component,  one row per planet (au)
 rz0           (n,:)   z component,  one row per planet (au)
 vx            (n,:)   vx component, one row per planet (km/s)
 vy            (n,:)   vy component, one row per planet (km/s)
 vz            (n,:)   vz component, one row per planet (km/s)
 n is the number of planets
See also
: Planets, PlanetPosition
References vector().
Referenced by HelioFromPlanetInit(), Isothermal(), NavTargetTrackingPlanetary(), OpticalNavAccuracy(), OpticalNavPlanetStarNoiseMatrix(), PlanetOpposition(), Planets(), SolarSysJPL(), SolarSysState(), SunVectorECI(), and VDA().
SolarSystemElements()
function SolarSystemElements (in iv, in Wv, in wv, in av, in ev, in Lv, in jD)
The input elements are referenced to JD2000. If the output requested is Kepler elements a will be in km.
Form
 [i, W, w, a, e, L] = SolarSystemElements( iv, Wv, wv, av, ev, Lv, jD )
 [i, W, w, a, e, L] = SolarSystemElements( d, jD )
 el = SolarSystemElements( d, jD )
Inputs
 iv            (1,2)   Inclination wrt ecliptic plane     (rad)
 Wv            (1,2)   Longitude of ascending node wrt vernal equinox  (rad)
 wv            (1,2)   Argument of perhelion      (rad)
 av            (1,2)   Mean distance (au)
 ev            (1,2)   Eccentricity
 Lv            (1,3)   Mean longitude (rad)
 name          (1,:)   Name of planet
    - OR -
 d              (:)    Data structure array with above fields
 jD            (1,1)   Julian date     (days)
Outputs
 i             (1,n)   Inclination     (rad)
 W             (1,n)   Ascending node  (rad)
 w             (1,n)   Perihelion      (rad)
 a             (1,n)   Semi-major axis (au)
 e             (1,n)   Eccentricity
 L             (1,n)   Mean longitude  (rad)
    - OR -
 el            (n,6)   Kepler elements, [a i W w e M]
See also
Planets, SolarSysState.
References and(), Constant(), Date2JD(), Demo(), JD2000(), JD2T(), Planets(), SolarSysState(), SolarSystemElements(), and zeros().
Referenced by PlanetAlignments(), PlanetTransferLambert(), SolarSystemElements(), and SynodicPlanets().
SolarSystemProperties()
function SolarSystemProperties (in name)
See also
Moons.
Form
 d = SolarSystemProperties( name )
Inputs
 name        (1,:) Name of moon or planet
Outputs
 d           (1,1) Properties of a planet
                  .planet            (1,:) Planet name
                  .moons             {}   Moon names
                  .equatorialRadius  (1,1) Radius (km)
                  .flatteningFactor  (1,1) Flattening factor
                  .rotationRate      (1,1) Axial rotation rate
    OR
 d           (1,1) Properties of a moon
                  .moon              (1,:) Moon name
                  .center            (1,:) Name of planet center
                  .radius            (1,1) Radius
                  .mass              (1,1) Mass (kg)
References: Seidelmann, ed. The Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992, pp.708-709.
References and(), and Moons().
SolarVisibility()
function SolarVisibility (in rECI, in jD, in animate, in centralBody, in fov, in map3d)
 This accounts for eclipses by the Earth and Moon.
 Usage:
 [sI,eE,eM,rSEs,rMEs] = ...
 SolarVisibility( rECI, jD, animate, centralBody, ...fov, map3d )
Inputs
 rECI       (3,n)    Position vectors in ECI frame
 jD         (1,n)    Julian date for each position
 animate     (1)     Animation setting.
                        0  No animation.
                        1  Field-of-view animation of Earth & moon with
                              sun at (0,0)
                        2  Orbit animation with line-of-sight vectors to
                              sun, Earth and moon.
                        3  Both animations in one window.
 centralBody (:)     Name of central body. Can be Earth, Sun, or Moon.
 fov         (1)     Sets the angular field of view for the animation
 window. Units are degrees. 360 is full sky. 180
 is frontal view.
 map3d       (1)     Flag. Indicates whether to display a 3D map of the
 central body in the orbit animation or not.
Outputs
 sI         (1,n)   Solar intensity at each time. [W/m^2]
 eE         (1,n)    Binary. Eclipse from Earth (1) or not (0).
 eM         (1,n)    Binary. Eclipse from Moon  (1) or not (0).
 rSEs       (3,n)    Position of sun with respect to Earth in ECI. [km]
 rMEs       (3,n)    Position of moon with respect to Earth in ECI. [km]
References and(), Eclipse(), isempty(), RVFromKepler(), and SolarVisibility().
Referenced by SolarVisibility().
SortFK5()
function SortFK5 (in catName, in newCat, in lYMax)
 Since version 1.
Form
 SortFK5( catName, newCat, lYMax )
Inputs
 catName      (1,:)     Catalog name                 (string)
 newCat       (1,:)     New Catalog name             (string)
 lYMax        (1,1)     Maximum light years          (light Years)
Outputs
 None
References and(), isempty(), length(), Parallax(), and SortFK5().
Referenced by SortFK5().
SpacecraftStatePlugIn()
function SpacecraftStatePlugIn (in action, in modifier, in hFig, in position, in callback)
Form
 x =  SpacecraftStatePlugIn( action, modifier, hFig, position, callback )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifer     (1,:)  Modifier to the action or data structure if intialization
 hFig        (1,1)  Handle to the figure or if 'update' radio button handles
 position    (1,4)  [left bottom width height]
 callback    (1,:)  Callback string when something has changed in this gui
Outputs
 x           (1,1)  The tag if action is 'initialize'
References CloseFigure(), Constant(), get(), GetH(), Initialize(), isempty(), PutH(), and set().
Spectrum()
function Spectrum (in band, in n)
 If you enter no inputs it will give you a table of the names and wavelength
 ranges.
Form
 lambda = Spectrum( band, n )
Inputs
 band           (1,;) Name of band
 n              (1,1) Number of elements, default is 100
Outputs
 lambda         (1,:)  Wavelengths
References and().
Referenced by CameraResolution(), and IFOV().
SSA()
function SSA (in)
Form
 [cEP, dTCEP, uSunBodyOld, angleSSA] = SSA( qECIToBody, uSunECI,
 uSunBodyOld, dT )
 [cEP, dTCEP, uSunBodyOld, angleSSA] = SSA( qECIToBody, uSunECI,
 uSunBodyOld, dT, boresight,
 aperture, aperXBore, cosFOV,
 angleSSAOld )
Inputs
 qECIToBody       (4,1)  Quaternion from the inertial to the body frame
 uSunECI          (3,1)  Sun unit vector in the ECI frame
 uSunBodyOld      (3,1)  Last value of the sun in the body frame
 dT                      Time step
 boresight        (3,1)  Sensor boresight axis
 aperture         (3,1)  Sensor aperture axis
 aperXBore        (3,1)  Aperture X boresight
 cosFOV           (1,1)  Cosine of the field of view angle
 angleSSAOld      (1,1)  Last sun sensor angle
Outputs
 cEP              (1,1)  1 if sun just passed through the sensor boresight/
                         spin-axis plane
 dTCEP            (1,1)  Time since the CEP
 uSunBodyOld      (3,1)  Last value of the sun in the body frame
 angleSSA         (1,1)  Angle between the boresight axis and the sun vector
References and(), Dot(), get(), Initialize(), QForm(), and vector().
Referenced by GetHSA(), and SPMMnvr().
SSEye()
function SSEye (in m, in a)
 Given the equation m = a(1)*x^1 + a(2)*x^2 +...
 solves for x using a Newton-Raphson method. Assumes that
 x  m/a(1), i.e. the other coefficients are small.
 Since version 1.
Form
 [x, e] = SSEye( m, a )
Inputs
 m            (n)       Magnitude of each sun sensor output
 a            (m)       Eye coefficients where m = a[1]*x^1 + a[2]*x^2 +...
Outputs
 x             (n)      Ideal output (cosine of angle)
 e             (n)      Error
References series().
Referenced by SSAD().
StarCameraViewer()
function StarCameraViewer (in action, in y, in n, in h, in d, in k)
This function returns a data structure on initialize that then must be passed in on update.
Type StarCameraViewer for a demo which just calls NavigationCamera and runs its demo.
Form
 h = StarCameraViewer( 'initialize', name )
 StarCameraViewer( 'update', y, h, d, k, n )
Inputs
 action  (1,:) 'initialize' or 'update'
 y       (.)   Measurement data structure
               .star     (.)   Star measurement data structure
               .planet   (2,:) Planet centroid
               .ang      (1,:) Planet angular radius (rad)
               .outside  (1,2) 2 means planet visible, 1 means planet not
                               in camera fov
 h       (.)   Structure for figure
 d       (1,1) Data structure
               .xPlanet        (3,:)   Planet locations (km)
               .radiusPlanet   (1,:)   Planet radius (km)
               .namePlanet     {:}     Name of the planet
               .starCatalog     (.)     Star catalog data structure
               .camera         (.)     See PinholeStarCamera
               .useImage       (1,1)   true use a planet image
 k      (1,1) Step
 n      (1,1) Total number of steps
Outputs
 h      (.)   Figure data structure.
References and(), NavigationCamera(), and StarCameraViewer().
Referenced by NavigationCameraSunStar(), and StarCameraViewer().
StarMap()
function StarMap (in catName, in lYMax)
 Since version 1.
Form
 StarMap( catName, lYMax )
Inputs
 catName       (1,:)    Catalog name                      (string)
 lYMax         (1,1)    Maximum light years          (light Years)
Outputs
 None
References isempty(), Map(), NewFig(), Parallax(), StarMap(), TitleS(), Watermark(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by StarMap().
StarTexture()
function StarTexture (in starFile, in textureFile, in size, in width)
 The output will be .pgm. The starFile can be a catalog data structure
 from LoadCatalog or a file name in which case it will call LoadCatalog.
Form
 StarTexture( starFile, textureFile, width )
Inputs
 starFile    (1,:) Name of star data file or catalog data structure
 textureFile (1,:) Name of image file
 size        (1,1) X size of image
 width       (1,1) Nominal star width in pixels
Outputs
 None
References Demo(), length(), LoadCatalog(), NewFig(), Odd(), StarTexture(), VM2Int(), and zeros().
Referenced by StarTexture().
StellarIrradiance()
function StellarIrradiance (in m, in starType, in detectorType)
Form
 h = StellarIrradiance( m, starType, detectorType )
Inputs
 m            (1,n)     Bolometric magnitude
 starType     {n}       Star type
 detectorType {n}       Detector type
Outputs
 h            (1,n)     Irradiance (W/cm^2)
StepSim()
function StepSim (in x, in t, in dS)
 State 'AB' [theta;omega;iA,iB]
 'DQ' [theta;omega;iD,iQ]
 'FI' [theta;omega]
 The AB and DQ models are just coordinate transformations of one another.
 The FI model only computes the torque assuming that the currents reach
 steady state instantaneously.
 This model neglects magnetic coupling between the phases and variations
 in the inductance as a function of rotor position, the detent torque
 and magnetic saturation.
 The data structure:
 dS.l       - inductance of the phase winding
 dS.nR      - number of rotor teeth
 dS.r       - resistance of the phase winding
 dS.kM      - motor torque constant
 dS.kD      - detente load torque
 dS.tM      - mechanical torques on the shaft
 dS.coulomb - Coulomb friction
 dS.inertia - rotor inertia
 dS.damping - damping coefficient
 dS.uA      - phase a voltage
 dS.uB      - phase b voltage
 dS.uD      - direct voltage
 dS.uQ      - Quadrature voltage
 dS.mode    - 'ab', 'dq', 'fi'  The last only computes the torque
 and assumes that the currents reach steady state instantaneously
 Since version 2.
Form
 [xDot, tTotal, m] = StepSim( x, t, dS )
Inputs
 x             (:)        State
 t             (1,1)      Time
 dS            (:)        Data structure
Outputs
 xDot          (:)        State derivative
 tTotal        (1,1)      Total torque
 m             (2,2)      Transformation from a,b to d,q
References:
 1. Bodson, M., J. Chiasson, R. Novotnak, R. Rekowski "High-Performance
 Nonlinear Feedback Control of a Permanent Magnet Stepper Motor,"
 IEEE Transactions on Control Systems Technology, Vol. 1, No. 1.,
 March 1993, pp. 5-14.
References and(), and StepSim().
Referenced by StepSim().
StepTorque()
function StepTorque (in ignoredArg, in ignoredArg, in d)
This is the standard format for an disturbance torque functions.
Form
 t = StepTorque( ~, ~, d )
Inputs
 x   (:,1)  State (unused)
 t   (1,1)  Time (unused)
 d  (.)   Data structure
           .torqueDisturbance
Outputs
 t   (3,1)       Torque
References StepTorque().
Referenced by StepTorque().
StructureAnalysis()
function StructureAnalysis (in cADModel)
The spacecraft frame is cantilevered to the base cylinder. The cylinder must handle axial loads from the fuel tank and distributed loads from the rest of the spacecraft. The frame is a rectangular cross section.
Loads TwoArraySC.mat if a model is not specified.
Form
 StructureAnalysis( cADModel )
Inputs
 cADModel      (:)      CAD data structure.
Outputs
 None
References and().
SumRXF()
function SumRXF (in r, in f, in cM)
 Since version 1.
Form
 t = SumRXF( r, f, cM )
Inputs
 r             (3,n) Position vectors
 f             (3,n) Force vectors
 cM            (3,1) Center of mass
Outputs
 t             (3,1) Total torque
References Cross(), and set().
SunBeta()
function SunBeta (in i, in uSun, in rA)
Computes the sun beta angle (i.e. elevation out of the orbit plane) given the sun unit vector (or right ascension and declination), the right ascension of the ascending node and the inclination of the orbit.
Type SunBeta for a demo.
Form
 beta = SunBeta( i, uSun, rA )
Inputs
 i            (1,1)  Inclination (rad)
 uSun         (3,1)  Sun Vector or [rASun (rad);decSun (rad)];
 rA           (1,n)  Right ascension of the ascending node (rad)
Outputs
 beta        (1,n)  Beta angles
References and(), Demo(), length(), Plot2D(), SunBeta(), U2RADec(), and vector().
Referenced by EarthEclipseDuration(), and SunBeta().
SunNadir()
function SunNadir (in xNoSun, in orbitRate, in beta, in alpha, in alphaLimit)
 The sun is defined in a coordinate frame with the orbit in the xy-plane and
 z along the +normal. The sun lies in the xz-plane. The spacecraft frame is
 defined with +z in the orbit plane and +y along the orbit anti-normal.
Form
 [yaw, saAngle, yawRate, sARate] = SunNadir( xNoSun, orbitRate, beta, alpha, alphaLimit )
 [yaw, saAngle, yawRate, sARate] = SunNadir( xNoSun, orbitRate, beta )
 [yaw, saAngle, yawRate, sARate] = SunNadir( xNoSun, orbitRate )
 SunNadir( xNoSun, orbitRate, beta, alpha, alphaLimit )
 SunNadir( xNoSun, orbitRate, beta )
 SunNadir( xNoSun, orbitRate )
 SunNadir
Inputs
 xNoSun         (1,1) Either +1 for +x or -1 for -x
 orbitRate      (1,1) Orbit rate
 beta           (1,n) Angle from orbit plane to the sun (rad)
 alpha          (1,m) Angle from the sun line in the orbit plane
 alphaLimit     (1,1) Range of alpha within which the rate limit is to be enforced
Outputs
 yaw            (n,m) Yaw angle
 saAngle        (n,m) Solar array angle
 yawRate        (n,m) Yaw rate
 sARate         (n,m) Solar array rate
References abs(), and(), isempty(), length(), SunNadir(), and zeros().
Referenced by ICSN(), QSunNadir(), SunNadir(), and WheelSpeed().
SunSensor()
function SunSensor (in t1, in t2, in alpha1, in alpha2, in f1, in f2, in angle)
The two detectors are at an angle of alpha1 and alpha2 with respect to vertical. You get t1 and t2 from running CalibrateSunSensor.
The detector 1 measurement is assumed of the form:
f1 = t1(1) + t1(2)*cos(angle+alpha1)+ t1(3)*cos(angle+alpha1)^2
Type SunSensor for a demo.
Form
 angleMeas = SunSensor( t1, t2, alpha1, alpha2, f1, f2, angle )
Inputs
 t1          (1,3) Detector 1 coefficients [constant linear square]
 t2          (1,3) Detector 2 coefficients [constant linear square]
 alpha1      (1,1) Offset angle sensor 1 (rad)
 alpha2      (1,1) Offset angle sensor 2 (rad)
 f1          (1,:) Detector 1 measurements
 f2          (1,:) Detector 2 measurements
 angle       (1,:) Angle of measurements from the normal (rad)
Outputs
 angleMeas   (1,:) Measured sun angle (rad)
References and(), CalibrateSunSensor(), Demo(), get(), length(), Plot2D(), square(), SunSensor(), and zeros().
Referenced by SunSensor().
SunV1()
function SunV1 (in jD, in rSc)
 Low precision formula. Will output the distance to the sun from the
 earth if two output arguments are given.
Form
 [u, r] = SunV1( jD, rSc )
Inputs
 jD        (1,:)   Julian date
 rSc       (3,:)   Spacecraft vector in the ECI frame (km)
Outputs
 u         (3,:)   Unit sun vector (vector TO the sun)
 r         (1,:)   Distance from origin to sun (km)
References: The 1993 Astronomical Almanac, U.S. Government Printing Office, p. C24. The 2015 Astronomical Almanac, p. C5
References CosD(), Date2JD(), isempty(), Mag(), SinD(), Unit(), and vector().
Referenced by ADPartls(), AlignThruster(), AttitudeFrames(), AttitudeProfileVis(), AttitudeTarget(), BatterySize(), BMF(), CubeSatDisturbanceAnalysis(), CubeSatEnvironment(), CubeSatLunarEnvironment(), CubeSatPowerAnalysis(), DFFAttitudeTarget(), DistAlbedo(), DistributedAlbedo(), DistSolar(), Disturbances(), DrawSCPlugIn(), DrawSpacecraftInOrbit(), EarthAlb(), EarthEclipseDuration(), EarthHelioState(), ECIToSunEarthRot(), EclipseFromECI(), EclipticInjectionPlane(), FEarthMoonSun(), FOrbitMultiSpacecraft(), FSailEarthMoon(), FSailEarthSun(), FSolstice(), GeoOptimalMission(), GetHSA(), HSAData(), IsothermalLunar(), JacchiaLineberry(), LocalSolarTime(), NadGen(), PlanetaryAccelerations(), PlanetOptimalTraj(), PltOrbit(), PowerDesign(), ProfileStruct(), PropEph(), QSunNadir(), RelativeDisturb(), RHSAlphaCentauriMission(), RHSCubeSat(), RHSIsothermal(), RMoonECI(), RSunECI(), RVOrbHF(), SailEnvironment(), SolarFluxFromPlateECI(), SPMDataF(), SPMMnvr(), SunV2(), TerminatorLine(), TerrestrialSolarFlux(), and ThrusterAlignment().
SunV2()
function SunV2 (in jD, in rSc)
 Generates the sun vector in the earth-centered inertial frame. Will
 output the distance to the sun from the earth if two output
 arguments are given.
 SunV2 is computationally a little more intensive and gives more
 accurate results than SunV1
Form
 [u, r] = SunV2( jD, rSc )
Inputs
 jD        (:)     Julian date
 rSc       (3,:)   Spacecraft vector in the ECI frame (km)
Outputs
 u         (3,:)   Unit sun vector
 r         (:)     Distance from origin to sun (km)
References and(), CosD(), Date2JD(), isempty(), Mag(), SunV1(), SunV2(), Unit(), and vector().
Referenced by EarthEnvironment(), ProfileStruct(), SafeGuidanceSim(), SailEphemEarth(), SunV2(), and TransformSEMRToHelio().
SunVectorECI()
function SunVectorECI (in action, in varargin)
 Utilizes Planets and SolarSys to look up the planet ephemeris. If the
 input is a moon, the nearest planetary center is used.
Form
 SunVectorECI( 'initialize', center )
 rSunECI = SunVectorECI( 'update', jD, rSc )
Inputs
 action       (1,:)     'initialize' or 'update'
 'initialize'
 planetName   (1,:)     Center of spacecraft coordinates
 'update'
 jD           (1,1)     Julian date
 rSC          (3,1)     Spacecraft ECI position vector (km)
Outputs
 rSunECI      (3,1)     Sun ECI position vector
See also
: Planets, SolarSys, CEcl2Eq, Moons
References and(), CEcl2Eq(), JD2000(), Moons(), Planets(), SolarSys(), SunVectorECI(), and vector().
Referenced by PlanetEnvironment(), PltOrbit(), and SunVectorECI().
SunVectorPointing()
function SunVectorPointing (in uECI, in uSunECI)
The solar wing is assumed to be along the y-axis and the thrust vector along the x-axis. We roll (about) x and rotate the normal until it is aligned with the sun. The zero solar array angle is with the solar array normal aligned with +x.
Type SunVectorPointing for a demo
Form
 [qECIToBodyTarget, sAAngle] = SunVectorPointing( uECI, uSunECI )
Inputs
 uECI              (3,1) Desired pointing vector
 uSunECI           (3,:) Sun vector in the ECI frame
Outputs
 qECIToBodyTarget   (4,:) Angle about unit vector (rad)
 sAAngle           (1,:) Angle about wing normal vector (rad)
References and(), Demo(), Mat2Q(), Q2Mat(), QForm(), SunVectorPointing(), U2Q(), vector(), and zeros().
Referenced by SunVectorPointing().
TankVolume()
function TankVolume (in vT, in rhoF, in tNom, in pI, in pF, in rP)
If gas constant is omitted, Helium will be assumed. Typical tank pressures are 300-400 psi BOL and 100 psi EOL. This is for a tank that has both fuel and pressurant. The default pressurant is helium.
Type TankVolume for a demo.
Form
 [mF, mP, vP] = TankVolume( vT, rhoF, tNom, pI, pF, rP )
Inputs
 vT            (1,:)    Total volume available (m^3)
 rhoF          (1,1)    Density of fuel (kg/m^3)
 tNom          (1,1)    Nominal temperature (K)
 pI            (1,1)    Initial pressure (N/m^2)
 pF            (1,1)    Final pressure (N/m^2)
 rP            (1,1)    Gas constant of pressurant
Outputs
 mF            (1,:)    Mass of fuel (kg)
 mP            (1,:)    Mass of pressurant (kg)
 vP            (1,:)    Pressurant volume (m^3)
References and(), Plot2D(), and TankVolume().
Referenced by TankVolume().
TargetSlew()
function TargetSlew (in altitude, in rTarget, in mu, in inertia)
Computes the angle, angular rate and angular acceleration for a spacecraft in a circular orbit that is pointing at a target on the ground. If inertia is not entered units are rad/sec^2 and rad/sec otherwise they are Nm and Nms
Form
 varargout = TargetSlew( altitude, rTarget, mu, inertia )
Inputs
 altitude       (1,:)  Apogee radius
 rTarget        (1,1)  Target radius from center (defaullt 6378)
 mu             (1,1)  Planet gravitational parameter (default Earth)
 inertia        (1,1)  Inertia (kg-m^2) (default is 1)
Outputs
 if length(altitude) == 1
   psiDot         (1,:)  Spacecraft angular rate
   psiDDot        (1,:)  Spacecraft angular acceleration
   psi            (1,:)  Spacecraft angle
 else
   psiDDotMax     (1,:)  Required maximum torque
   momentum       (1,:)  Required momentum storage
References and(), Demo(), isempty(), length(), and TargetSlew().
Referenced by TargetSlew().
TBModel()
function TBModel (in w0, in w1, in q0to1, in r0, in r1, in lam1, in iner0, in iner1, in)
Form
 [wDot, h, iner] = TBModel( w0, w1, q0to1, r0, r1, lam1, iner0, iner1,
 m0, m1, torque, force, iAxis )
Inputs
 w0     (3,1)   The angular velocity of body 0 with respect to the inertial
 w1     (3,1)   The angular velocity of body 1 with respect to body 0
 q0to1   (4,1)  The quaternion from body 0 to 1
 r0         (3,1)   The vector from the origin to the body 0 cm in the body 0 frame
 r1         (3,1)   The vector from the origin to the hinge in the body 0 frame
 lam1    (3,1)  The vector from the hinge to the body 1 cm in the body 1 frame
 iner0   (3,3)  The body 0 inertia in the body 0 frame
 iner1   (3,3)  The body 1 inertia in the body 1 frame
 m0      (1,1)  The body 0 mass
 m1      (1,1)  The body 1 mass
 torque (6,1)   [totalExternalTorque(3); hingeTorque]
 force   (6,1)  [body0ExternalForce(3); body1ExternalForce(3)] at their cms
 iAxis      (1,:)   The axes of the second body that are not constrained.
Outputs
 wDot    (6,1)  The angular acceleration vector
 h       (3,1)  The angular momentum in the body frame
 iner    (6,6)  The generalized inertia matrix
References and(), Cross(), Q2Mat(), quaternion(), SkewSymm(), vector(), and zeros().
Referenced by FTB(), and FTBRef().
TerminatorLine()
function TerminatorLine (in jD, in n)
 Since version 8.
Form
 [termLat,long] = Terminator( jD );
 [termLat,long] = Terminator( jD, n );
Inputs
 jD          (1,1) Julian date
 n           (1,1) Number of points to use for the line. Optional.
Outputs
 termLat     (1,n) Terminal latitudes (deg)
 long        (1,n) Longitude from -180 to 180 (deg)
 sunLatLon   (2,1) Latitude and longitude of normal vector to sun (deg)
References abs(), and(), CoordinateTransform(), Date2JD(), isempty(), JD2Date(), JDToDateString(), Map(), set(), SunV1(), TerminatorLine(), and vector().
Referenced by AttitudeProfileVis(), DrawSpacecraftInOrbit(), and TerminatorLine().
TerminatorPlanet()
function TerminatorPlanet (in r, in radius, in n)
 The input is the radius of the planet. The output
 is in the inertial frame but centered around the planet.
 Since version 8.
Form
 TerminatorPlanet;
 [lat, lon] = TerminatorPlanet( r, radius )
 [lat, lon] = TerminatorPlanet( r, radius, n )
Inputs
 r              (3,1)     Vector from the sun to the planet center
 radius         (1,1)     Planet radius
 n              (1,1)     Number of points
Outputs
 rT             (3,n)     Terminator vectors from the planet center
References and(), Cone(), Constant(), Cross(), Demo(), Mag(), Plot2D(), TerminatorPlanet(), Unit(), vector(), and zeros().
Referenced by TerminatorPlanet().
TerrestrialSolarFlux()
function TerrestrialSolarFlux (in jD)
Uses SunV1 to locate the sun in the Eart-centered inertial (ECI) frame. The nominal solar flux at 1 AU is 1367 W/m2.
The same scaling law is used by SolarFluxDemo, which also returns the sun unit vector in the Earth-centered (ECI) frame, but using the PlanetPosition to compute the sun vector instead of Almanac function SunV1. The results are therefore slightly different.
Form
 [flux,u] = TerrestrialSolarFlux( jD )
Inputs
 jD      (1,:) Julian Date
Outputs
 flux    (1,:) Solar flux (watts/m^2)
 u       (3,:) Sun unit vector
References and(), JD2000(), PlanetPosition(), Plot2D(), SunV1(), TerrestrialSolarFlux(), and vector().
Referenced by SolarFlux(), and TerrestrialSolarFlux().
TGG()
function TGG (in inr, in u, in wO)
 Since version 1.
Form
 t = TGG( inr, u, wO )
Inputs
 inr                (3,3) Inertia matrix
 u                  (3,:) Unit vector from the earth to the spacecraft
                          in the spacecraft body frame (the same frame as
                          the inertia matrix.)
 wO                 (1,1) Orbit rate (rad/sec)
Outputs
 t                  (3,:) Torque (units will be consistent with inertia)
References Constant(), Cross(), Demo(), Mag(), PlotV(), Unit(), and vector().
ThreeAxisControlDisturb()
function ThreeAxisControlDisturb (in ignoredArg, in d, in x)
Computes the solar pressure disturbance with SolarF. This is suitable for geostationary orbit where solar pressure is the main disturbance.
Form
 d = ThreeAxisControlDisturb;
 [torque, force] = ThreeAxisControlDisturb( t, d, x )
Inputs
 t           (1,1)     Time (unused)
 d             (.)     Data structure for the simulation
                         .areaArray  (1,1) Area of solar array
                         .areaBox    (1,1) Area of the box face
                         .cM         (3,1) Center-of-mass
                         .sigmaArray (1,4) [absorbed specular diffuse transmitted]
                         .sigmaBox   (1,4) [absorbed specular diffuse transmitted]
                         .uSun       (3,1) Sun unit vector in ECI frame
                         .force      (3,1) Other force in body frame
                         .torque     (3,1) Other torque in body frame
 x           (:,1)      State [ECI position;ECI Velocity;quaternion;rate];
Outputs
 force       (3,1)      Total force in ECI frame (N)
 torque      (3,1)      Total torque in body frame (Nm)
References Cross(), DefaultDataStructure(), DupVect(), QForm(), QTForm(), quaternion(), SolarF(), ThreeAxisControlDisturb(), Unit(), and vector().
Referenced by RHSRWA(), and ThreeAxisControlDisturb().
ThrusterAndRWACommand()
function ThrusterAndRWACommand (in t, in pOn, in kACS, in kRWA, in d)
Off-pulsing is used to produce delta-v and attitude control at the same time.
Inputs are a torque vector, the desired fraction of the time each thruster is on for delta-v, the set of thrusters to be used for attitude control and a data structure. If a feasible solution is not reached the control is not possible.
Type ThrusterAndRWACommand
for a demo that shows pure attitude control and also off-pulsing for delta-v and attitude control.
Inputs
 t       (3,1)  Desired torque vector
 pOn     (1,:)  Fraction of time thruster is on for delta-v
 kACS       (1,n)   Set of ACS thrusters
 kRWA    (1,m)  Set of RWA to use
 d       (1,1)  Data structure
               .uT     (3,n) Thruster unit force vectors
                .rT     (3,n) Thruster locations
                .thrust (1,:) Thrust magnitude
               .uRWA   (3,m) RWA unit torque vectors
                .tRWA   (1,m) Maximum RWA torque
               .cM     (3,1) Spacecraft center of mass
               .cT     (1,n) Thruster cost
                .cRWA   (1,m) RWA cost
Outputs
 force   (3,1)  Net force vector
 torque (3,1)   Net torque vector (should = t)
 uT     (1,n)   Fraction of time thruster is on
 uRWA       (1,m)   Fraction of maximum RWA torque
 f       (1,1)  1 means a feasible solution was reached
References and(), Cross(), DefaultDataStructure(), Demo(), DispWithTitle(), DupVect(), length(), RWA(), set(), Simplex(), ThrusterAndRWACommand(), Unit(), vector(), and zeros().
Referenced by ThrusterAndRWACommand().
ThrusterColdGas()
function ThrusterColdGas (in mass, in t0, in c, in d)
Form
 [force, torque, mDot, uE] = ThrusterColdGas( mass, t0, c, d )
Inputs
 mass    (1,1) Fuel mass        (kg)
 t0      (1,1) Tank temperature (deg-K)
 c       (3,1) Center of mass   (m)
 d       (.)   Data structure
               .fuel  (1,:) Type of fuel (see ColdGas)
               .aStar (1,1) Throat area (m^2)
               .v     (1,1) Tank volume (m^3)
               .on    (1,n) True (1) if thruster is on
               .r     (3,n) Position of the thruster (m)
               .u     (3,n) Unit vector of the thruster
Outputs
 force   (3,1) Body force vector  (N)
 torque  (3,1) Body torque vector (Nm)
 mDot    (1,1) Mass flow          (kg/s)
 uE      (1,1) Exhaust velocity   (m/s)
References and(), ColdGas(), Cross(), DefaultDataStructure(), GasProperties(), IdealRkt(), MolWt2R(), Unit(), vector(), and zeros().
ThrusterCommand()
function ThrusterCommand (in t, in pOn, in kACS, in d)
 Off-pulsing is used to produce delta-v and attitude control at the same
 time.
Inputs
thruster is on for delta-v, the set of thrusters to be used for attitude control and a data structure. If a feasible solution is not reached the control is not possible.
 Type
 ThrusterCommand
 for a demo that shows pure attitude control and also off-pulsing for
 delta-v and attitude control.
 Note that some options to simplex are hard coded:
 All thruster costs are the same
 The maximum constraint is not applied
Inputs
 t           (3,1)     Desired torque vector
 pOn         (1,:)     Fraction of time thruster is on for delta-v
 kACS        (1,n)     Set of ACS thrusters
 d           (1,1)     Data structure
                       .uT     (3,:) Thruster unit force vectors
                       .rT     (3,:) Thruster locations
                       .thrust (1,:) Thrust magnitude
Outputs
 force       (3,1)     Net force vector
 torque      (3,1)     Net torque vector (should = t)
 u           (1,n)     Fraction of time thruster is on
 f           (1,1)     1 means a feasible solution was reached
References and(), Cross(), Demo(), length(), set(), Simplex(), ThrusterCommand(), Unit(), vector(), and zeros().
Referenced by ThrusterCommand().
TileOBJSphere()
function TileOBJSphere (in d, in fileName, in nLat, in nLon)
 The texture files must be in directory d and must be of the form
 name- n longitude- n latititude .xxx
 xxx may be any graphics file format.  The folder should not have any
 files in it aside from the images but it will know that .m, .mat, .obj
 and .mtl are not graphics file. These will become texture files
 in the .mtl file.
 The resulting files will be name.obj and name.mtl. It will put the
 resulting file in the same folder as the images.
 Type TileOBJSphere for a demo with four panels. Make certain that
 TerrainFiles is in the search path.
 OBJ files are used in many graphics packages.
Form
 TileOBJSphere( d, nLat, nLon )
Inputs
 d         (1,:)  Target directory
 fileName  (1,:)  Name for the obj and mtl files
 nLat      (1,1)  Number of latitude points per segment
 nLon      (1,1)  Number of longitude points per segment
Outputs
 None
References and(), Demo(), length(), and TileOBJSphere().
Referenced by TileOBJSphere().
TorqueHysteresisDamper()
function TorqueHysteresisDamper (in u, in b, in v, in bE)
 See MagneticHysteresis.
Form
 t = TorqueHysteresisDamper( u, b, v, bE )
Inputs
 u                  (3,1) Damper unit vector in the body frame
 b                  (1,1) Damper axial flux density (T)
 v                  (1,1) Volume of damper (m^3)
 bE                 (3,1) Earth's magnetic field in the body frame (T)
Outputs
 t                  (3,1) Torque
Reference: Kumar R., Mazanek, D. and Heck, M., "Simulation and Shuttle Hitchhiker Validation of Passive Satellite Aerostabilization," Journal of Spacecraft and Rockets, Vol. 32, No. 5, September-October 1995.
References and(), Cross(), MagneticHysteresis(), and vector().
Referenced by RHSGGRotational(), and RHSHysteresisDamper().
TorqueRod()
function TorqueRod (in action, in u)
A simple Torque rod model that uses a tanh function to model the dipole curve for a typical torque rod. The initialization data is
d.mSaturation - dipole at saturation d.saturationVoltage - the voltage at saturation d.mResidual - the residual dipole
To demo the model type TorqueRod.
Form
 d = TorqueRod( 'data structure' )
 TorqueRod( 'initialize', d )
 TorqueRod( 'set voltage', v )
 m = TorqueRod( 'get moment' )
Inputs
 action        (1,:)   Actions
 u             (1,1)   Input depends on action
Outputs
 x             (1,:)   Output depends on action
References DispWithTitle(), get(), Initialize(), set(), and TorqueRod().
Referenced by TorqueRod().
TransformLagrangePoints()
function TransformLagrangePoints (in p, in jD)
Assumes thes positive x axis in the rotating frame is towards the moon from the Earth.
Form
 [r, v, mLEToECI] = TransformLagrangePoints( p, jD )
Inputs
 p              (2,:)  Points
 jD             (1,1)  Date of interest
Outputs
 r              (3,1)  Position of stable point in ECI frame
 v              (3,1)  Velocity of stable point in ECI frame
 mLEToECI       (3,3)  Transformation matrix from Lunar-Earth to ECI
                       frame
See also
LagrangePointsL1ToL5 and MoonV1.
References and(), Axis3D(), Cross(), DateStringToJD(), Equal(), LagrangePointsL1ToL5(), Mag(), Map(), MoonEl(), MoonV1(), NewFig(), TransformLagrangePoints(), Unit(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by TransformLagrangePoints().
TRD()
function TRD (in m, in b)
 Since version 1.
Form
 t = TRD( m, b )
Inputs
 m                  (3,n or 1) Dipoles (ATM^2)
 b                  (3,n or 1) Magnetic field (T)
Outputs
 t                  (3,1)      Torque (Nm)
References Cross(), PlotV(), and Residual().
Tree()
function Tree (in x, in t, in treeDS, in bodyData, in mu)
 No closed loops are permitted. All the bodies are rigid.
 Since version 2.
Form
 [xDot, gInertia, body, rHS] = Tree( x, t, treeDS, bodyData, mu )
Inputs
 x               (:,1)   State vector [rCM;vCM;[q;w]]
 t               (1,1)   Time
 treeDS          (:,:)   Tree connection data structure
 bodyData        (:,:)   Body data structure
 mu              (1,1)   Planet gravitational parameter
Outputs
 xDot            (:,1)   State derivative vector
 gInertia        (:,:)   Generalized inertia matrix
 body            (:)     Internal data structure
 rHS             (:,:).v Right hand side of the equations of motion
References and(), Cross(), Euler(), isempty(), length(), Mag(), Q2Mat(), QForm(), QIToBDot(), QPose(), QTForm(), quaternion(), SkewSq(), SkewSymm(), Tree(), vector(), and zeros().
Referenced by MHTHypothesisDisplay(), MHTInitializeTrk(), Tree(), TreeBldCAD(), TreeDraw(), TreeH(), TreeInit(), TreePlot(), and TreePrnt().
TreeAdd()
function TreeAdd (in inertia, in r, in lambda, in mass, in kPrev, in dOF, in w, in q, in b, in kSpring, in cSpring, in name)
 Since version 2.
Form
 x = TreeAdd( inertia, r, lambda, mass, kPrev, dOF, w, q, b, kSpring, cSpring, name )
Inputs
 inertia         (3,3) Inertia with respect to the body c.m.
 r               (3,1) Vector from the reference for the body to the c.m.
 lambda          (3,1) Vector from the reference for the previous
                       body in the chain to the hinge point for the body
 mass            (1,1) Body mass
 kPrev           (1,1) ID for the previous body in the chain
 dOF             (1,1) Active degree of freedom. If 0 all DOF are
                       active. Otherwise only dOF is active
 w               (:,1) Initial rate
 q               (:,1) Initial attitude
 b               (3,3) Transformation matrix from the previous body
                       frame to the hinge between the bodies.
 kSpring         (3,3) General stiffness matrix
 cSpring         (3,3) General damping matrix
 name            (1,:) Name of the component
Outputs
 x               (:,:) Data structure
References and(), isempty(), length(), QUnit(), TreeAdd(), and zeros().
Referenced by TreeAdd().
TreeH()
function TreeH (in x, in t, in treeDS, in bodyData)
 Since version 2.
Form
 [h, hI, hMag] = TreeH( x, t, treeDS, bodyData )
Inputs
 x               (:,1)   State vector [rCM;vCM;[q;w]]
 t               (1,1)   Time
 treeDS          (:,:)   Tree connection data structure
 bodyData        (:,:)   Body data structure
Inputs
 h               (3,1)   Angular momentum in the body frame
 hI              (3,1)   Angular momentum in the inertial frame
 hMag            (1,1)   Magnitude of the angular momentum
References and(), Cross(), length(), Mag(), Q2Mat(), QForm(), QPose(), quaternion(), SkewSymm(), Tree(), TreeH(), vector(), and zeros().
Referenced by TreeH().
TreeInit()
function TreeInit (in body, in r, in v, in gGOn)
 Since version 2.
Form
 [x, y] = TreeInit( body, r, v, gGOn )
Inputs
 body            (:,:) Body data structure
 r               (3,1) Orbit position vector
 v               (3,1) Orbit velocity vector
 gGOn            (1,1) If true gravity gradient is on
Outputs
 x               (:,:) Tree data structure
 y               (:,1) State vector [attitude;rate]
References and(), DupVect(), isempty(), length(), Tree(), vector(), and zeros().
TreePlot()
function TreePlot (in tPlot, in xPlot, in treeDS, in body, in hPlot)
 Since version 2.
Form
 TreePlot( tPlot, xPlot, treeDS, body, hPlot )
Inputs
 tPlot        (1,:) Time
 xPlot        (:,:) States
 treeDS       (:)   Tree data structure
 body         (:,:) Body data structure
 hPlot        (1,:) Momentum magnitude
Outputs
 None
References abs(), isempty(), length(), Plot2D(), and Tree().
TreePrnt()
function TreePrnt (in body, in treeDS)
Form
 TreePrnt( body, treeDS )
Inputs
 body         (:,:) Body data structure
 treeDS       (:,:) Tree data structure
Outputs
 None
References Constant(), length(), and Tree().
TRF()
function TRF (in u, in r, in p)
 Since version 1.
Form
 t = TRF( u, r, p )
Inputs
 u                  (3,n or 1) Antenna unit vectors
 r                  (3,n or 1) Moment arms (m)
 p                  (1,1)      Power (watts)
Outputs
 t                  (3,1)      Torque (Nm)
References Cross(), PlotV(), and set().
TruEarth()
function TruEarth (in T, in useEofE)
 Uses EarthRot, EarthNut, and EarthPre in sequence.
Form
 [c, g, n, p] = TruEarth( T, useEofE )
Inputs
 T           (1,1) Julian centuries of 86400s dynamical time from j2000.0
 useEofE     (1,1) If entered will use the equation of the equinoxes
                   for the earth rotation matrix
Outputs
 c           (3,3) Matrix from Mean of 2000.0 to earth fixed
 g           (3,3) Greenwich matrix
 n           (3,3) Nutation matrix
 p           (3,3) Precession matrix
References: Seidelmann, ed. The Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992, p. 20.
References and(), Date2JD(), EarthNut(), EarthPre(), EarthRot(), isempty(), and JD2T().
Referenced by AttitudeTarget(), ConstellationGroundContact(), DFFAttitudeTarget(), EarthEnvironment(), FOrbHFOP(), GPSSatellite(), GroundCoverage(), LinkAnalysisTool(), OrbitClosestPoint(), QToPFTarget(), and RHSGeoHarm().
TSolarP()
function TSolarP (in x, in uSource, in sourceIntensity, in doShadowing)
Models a spacecraft as a collection of areas. Shadowing is done by a zbuffer algorithm. Each component is modeled as a circular area with a normal and surface properties. All units are metric.
All outward normals must be expressed in the same coordinate frame.
The shadowing works by comparing the location of the center-of-pressure of each area with respect to the radius of each area that is closer to the source. If it is within that area it is eliminated from the calculation. This will work well if the areas are small or if the largest area is closest to the source.
Only one source is allowed.
Form
 [torque, force, x] = TSolarP( x, uSource, sunIntensity, shadowing )
Inputs
 x              (:)           Element data structure array
                          .area     (1,1)     Surface area
                          .name     (1,:)     Surface name
                          .cP       (3,1)     Center-of-pressure
                          .normal   (3,1)     Outward normal
                          .rhoAbsp  (1,1)     Absorption coefficient
                          .rhoSpec  (1,1)     Specular reflection coefficient
                          .rhoDiff  (1,1)     Diffuse reflection coefficient
                          .rhoTrns  (1,1)     Transmissivity coefficient
                          .torque   (3,1)     Elemental torque
                          .force    (3,1)     Elemental force
                          .shadowed (1,1)     0 = shadowed 1 = unshadowed
 uSource         (3,1)   Source unit vector
 sourceIntensity (1,1)   Intensity (watts/m^2) default is 1353 watts/m^2
 doShadowing     (1,1)   Any input will cause shadowing to be computed
Outputs
 torque             (3,1)   Total solar pressure torque
 force          (3,1)   Total solar pressure force
 x               (:,:)   Updated data structure (with individual forces
                         and torques)
References abs(), and(), Cross(), isempty(), length(), TSolarP(), Unit(), vector(), and zeros().
Referenced by TSolarP().
TwoC2F()
function TwoC2F (in hi, in lo, in b)
 Since version 3.
Form
 f = TwoC2F( hi, lo, b )
Inputs
 hi              (1,:)   High bits
 lo              (1,:)   Low bits
 b               (1,1)   Bits per word
Outputs
 f               (1,:)    Floating point
Referenced by LoadMag(), and Weather().
TwoUToQ()
function TwoUToQ (in u1, in u2, in u1T, in u2T)
Type TwoUToQ for a demo of a spacecraft in LEO using the magnetic field and nadir vectors for a spacecraft in LVLH.
Form
 q = TwoUToQ(u1,u2,u1T,u2T)
Inputs
 u1  (3,:) Unit vector 1
 u2  (3,:) Unit vector 2
 u1T (3,:) Unit vector 1 transformed
 u2T (3,:) Unit vector 2 transformed
Outputs
 q   (4,:)  Quaternion from the u1/u2 frame to the u1T/u2T frame
See also
U2Q.m
References and(), BDipole(), Cross(), Demo(), ISSOrbit(), Plot2D(), QForm(), QLVLH(), QMult(), quaternion(), RVOrbGen(), TimeLabl(), TwoUToQ(), U2Q(), Unit(), and vector().
Referenced by AngleDetermination(), and TwoUToQ().
U2FP()
function U2FP (in u, in uB, in uY, in f)
 Since version 2.
Form
 [x, y, k] = U2FP( u, uB, uY, f )
Inputs
 u         (3,:)   Unit vectors of target
 uB        (3,1)   Boresight
 uY        (3,1)   Y-Axis
 f         (1,1)   Focal length
Outputs
 x         (n)     X coordinate
 y         (n)     Y Coordinate
 k         (:)     Valid inputs
References Cross(), length(), NewFig(), Unit(), XLabelS(), and YLabelS().
Referenced by Optic2D().
U2Pix()
function U2Pix (in u, in f, in offset)
u(3) must be > 0 to be consistent with Pix2U. The scale factor is the focal length in pixel units. The offset allows you to specify an origin for the pixelmap other than the center. If there are no outputs a plot will be generated. The unit vector cannot have z < 0.
 \
 \
 f |\
 ----- focal plane
Form
 p = U2Pix( u, f, offset )
Inputs
 u            (3,:)   Unit vectors
 f   (2,1) or (1,1)   Scale factor (focal length in pixels)
 offset       (1,2)   Pixel offset in [x y]
Outputs
 p            (2,:)    [x;y]  (units of f)
References isempty(), length(), NewFig(), Pix2U(), TitleS(), U2Pix(), Unit(), vector(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by DisplayStars(), FPSensors(), GStarUKFNL(), Measurements(), MeasurementsSunMagUKF(), PinholeStarCamera(), RADecToPix(), StarMeasurement(), StarPrediction(), StarSensor(), and U2Pix().
UDipole()
function UDipole (in jD)
The output is in geocentric inertial coordinates (ECI). This function includes the effect of dipole motion on the earth.
Type BDipole for a demonstration of a satellite in a low earth inclined orbit.
Form
 uDipoleEF = UDipole( jD )
Inputs
 jD        (1,:)   Julian days
Outputs
 uDipole  (3,:)  Dipole
Reference: Wertz, J., ed. "Spacecraft Attitude Determination and Control," Kluwer, 1976, 783-784.
 Includes 1995 IGRF coefficients as of Jan. 1999
References BDipole(), Demo(), Dipole(), JD2000(), Period(), Plot2D(), and UDipole().
Referenced by RadiationBelts(), and UDipole().
URWAPyramid()
function URWAPyramid (in n, in uC, in cant)
 They are evenly spaced around the apex.
 Type URWAPyramid for a demo.
 Since version 2014.1
Form
 uRWA = URWAPyramid( n, uC, cant )
Inputs
 n       (1,1) Number of wheels
 uC      (3,1) Axis for the pyramid apex
 cant   (1,1) Cant angle from the apex
Outputs
 uRWA    (3,n) Unit vectors
References Demo(), NewFig(), QForm(), RWA(), U2Q(), Unit(), URWAPyramid(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by URWAPyramid().
UVAA()
function UVAA (in hRA, in mRA, in sRA, in dDec, in mDec, in sDec)
 If the sign of hRA or dDec is - make the sign of the other elements negative
 also.
 Since version 1.
Form
 [u] = UVAA( hRA,mRA,sRA,dDec,mDec,sDec )
Inputs
 hRA       (1,1)  Right ascension in (hours)
 mRA       (1,1)  Right ascension in (minutes)
 sRA       (1,1)  Right ascension in (seconds)
 dDec      (1,1)  Declination in (deg)
 mDec      (1,1)  Declination in (minutes)
 sDec      (1,1)  Declination in (seconds)
Outputs
 u         (3,1)   Unit sun vector
References DMS2Rad(), HMS2Rad(), RaDec2U(), Unit(), and vector().
VAtm()
function VAtm (in r, in wP)
This routine assumes the Earth rotates perfectly around its z axis. For a higher fidelity result you must compute the Earth-fixed tranformation for a particular date.
Has a built-in demo.
Form
 [v, vMag] = VAtm( r, wP )
Inputs
 r          (3,:)     r in the ECI frame
 wP         (1,1)     Planetary rotation rate (rad/sec), default is Earth
Outputs
 v          (3,:)     v in the ECI frame
 vMag       (1,:)     Magnitude
References: Escobal, P.R., Methods of Orbit Determination, 1976, p. 60.
References and(), Cross(), length(), Mag(), Plot2D(), VAtm(), and zeros().
Referenced by EarthEnvironment(), PlanetEnvironment(), and VAtm().
VelocityTimeDilation()
function VelocityTimeDilation (in v)
Form
 tR = VelocityTimeDilation( mu, r )
Inputs
 v              (1,:) Velocity of observer with respect to the source (km/s)
Outputs
 tR             (1,1)  Ratio of proper time at r to proper time at v = 0
Reference: http://en.wikipedia.org/wiki/Gravitational_time_dilation
References Demo(), Plot2D(), and VelocityTimeDilation().
Referenced by RHSClockDrift(), and VelocityTimeDilation().
VIModel()
function VIModel (in inr, in dinrdt, in w, in t, in dT)
 t is not used when computing the state-space model.
 Since version 1.
Form
 wdot               = VIModel(inr,dinrdt,w,t)
 [a, b, c, d, dwdt] = VIModel( inr, dinrdt, w, t, dT )
Inputs
 inr          (3,3)     Inertia matrix
 dinrdt       (3,3)     Time derivative of the inertia matrix
 w            (3,1)     Body rate vector in the body frame
 t            (3,1)     External torque on the body
Outputs
 wdot         (3,1)     Angular acceleration
 or
 a            (3,3)     State matrix
 b            (3,3)     Input matrix
 c            (3,3)     Output matrix
 d            (3,3)     Feedthrough matrix
 dwdt         (3)       State acceleration
References C2DZOH(), Cross(), SkewSymm(), vector(), and zeros().
VXPhi()
function VXPhi (in v, in phi)
 Returns one vector per mode. n is the number of nodes and m is the number
 of modes. phi is in blocks of m, i.e. phi[mode1, mode2, ..., modem]
 Since version 1.
Form
 x = VXPhi( v, phi )
Inputs
 v                (3,n)   Matrix of vectors
 phi              (3,n*m) Nodal displacements per modal displacement
Outputs
 x                (3,m)   Product
References and(), Product(), and vector().
Water()
function Water (in t)
 Since version 1.
Form
 [rho, cP, visc, therCond] = Water( t )
Inputs
 t           (1,:)  Temperature deg-C
Outputs
 rho         (1,:)  Density of water (kg/m^3)
 cP          (1,:)  Specific heat at constant pressure (J/kg-K)
 visc        (1,:)  Viscosity (microPa s)
 thermCond   (1,:)  Thermal conductivity (W/Km)
References and(), isempty(), Plot2D(), and Water().
Referenced by Water().
Weather()
function Weather (in tS, in file)
Will edit out magnetometer glitches.
 Since version 3.
Form
 [b, t, bMag, x, e, p, header, a] = Weather( tS, file )
Inputs
 tS                (1,2)   Time standard ('UT' or 'SC')
 file              (1,:)   File name
Outputs
 b                 (3,:)  Magnetic field
 t                 (1,:)  Time in seconds from beginning of data or
                          local spacecraft time.
 bMag              (1,:)  Magnetic field magnitude
 x                 (1,:)  X-rays
 e                 (1,:)  Electrons
 p                 (1,:)  Particles
 header            (1,6)  [satID,year,dataType,AverageType,Month,jD]
 a                 (1,:)  Data
References and(), Date2JD(), FindDirectory(), Glitch(), GOESLon(), isempty(), length(), NewFig(), set(), TwoC2F(), Weather(), and WeathLeg().
Referenced by Weather(), and WeathLeg().
WeathLeg()
function WeathLeg (in l, in box, in hK)
Form
 WeathLeg( l, box, hK )
Inputs
 l              (n,:)     Text strings
 box            (1,4)     Where the legend should fit
 hK             (1,n)     Handles to the lines
Outputs
 none
References and(), get(), length(), Weather(), and WeathLeg().
Referenced by Weather(), and WeathLeg().
WheelSpeed()
function WheelSpeed (in inrSc, in wSc, in inrWheel, in uWheel)
 WheelSpeed generates a sun nadir pointing demo.
Form
 wWheel = WheelSpeed( inrSc, wSc, inrWheel, uWheel )
Inputs
 inrSc        (3,3)  Inertia of the spacecraft
 wSc          (3,1)  Wheel speed
 inrWheel     (1,:)  Wheel inertias
 uWheel       (3,:)  Wheel unit vectors
Outputs
 wWheel       (n,:)  Wheel Speed
References length(), Period(), Plot2D(), set(), Step(), SunNadir(), WheelSpeed(), and zeros().
Referenced by WheelSpeed().
WireC()
function WireC (in x, in t, in s, in mu, in torque, in force, in penalty)
 2    2
 The equations of motion are   M d x/dt  = Q
 The constraints are                phi  = 0
If nIts > 0 it will use the iterative formulation.
Form
 xDot = WireC( x, t, s, mu, torque, force, penalty )
Inputs
 x              (m,1)     The state vector
                          [x;v;q;w;xWire;vWire]
 t              (1,1)     Time
 s              (:)       Wire data structure
 mu             (1,1)     Earth's gravitational constant
 torque         (3,1)     External torque on core
 force          (3,1)     External force on core
 penalty        (:)       enalty function scalars [.alpha, .mu, .omega, .nIts]
 nIts           (1,1)     Number of iterations
Outputs
 xDot         (:,1)       The derivative of the state vector
Reference: Jalon, J.G., E. Bayo, "Kinematic and Dynamic Simulation of Multibody Systems, The Real-Time Challenge," Springer-Verlag, 1993, pp. 164-170.
References and(), Cross(), Initialize(), isempty(), Jacobian(), length(), Mag(), QForm(), QIToBDot(), SkewSq(), SkewSymm(), Unit(), vector(), and zeros().
WireDMch()
function WireDMch (in s, in x, in time)
 Since version 2.
Form
 [s, x] = WireDMch( s, x, time )
Inputs
 s             (:)       The wire data structure
 x             (m,1)     The state vector
Outputs
 s             (:)       The wire data structure
 x             (m,1)     The state vector
References Initialize(), length(), and vector().
WireFRB()
function WireFRB (in x, in t, in s, in mu, in torque, in force)
 Since version 2.
Form
 xDot = WireFRB( x, t, s, mu, torque, force )
Inputs
 x              (m,1)     The state vector
                          [x;v;q;w;xWire;vWire]
 t                        Time
 s              (:)       Wire data structure
 mu             (1,1)     Gravitational parameter
Outputs
 xDot         (m,1)       The derivative of the state vector
References and(), Cross(), isempty(), length(), Mag(), QForm(), QIToBDot(), Skew(), SkewSq(), SkewSymm(), Unit(), vector(), and zeros().
WireH()
function WireH (in x, in s)
 Since version 2.
Form
 h = WireH( x, s )
Inputs
 x            (m,1)     The state vector
                        [x;v;q;w;xWire;vWire]
 s            (:)       Wire data structure
Outputs
 h            (1,1)     The angular momentum
References and(), Cross(), Mag(), and vector().
WireInit()
function WireInit (in nNodes, in mass, in massWire, in lWireMax, in kSpring, in cSpring, in vDeploy, in)
 Since version 2.
Form
 [wireDS, x] = WireInit( nNodes, mass, massWire, lWireMax, kSpring, cSpring, vDeploy,...
                    cDeploy, nodeDeploying, rWireBase, rECI, vECI, q, omega,...
                    r0, inertia, gGOn )
Inputs
 nNodes          (1,n)     The number of nodes in each wire
 mass            (1,1)     Mass of the core spacecraft
 massWire        (1,n)     Mass of each wire
 lWireMax        (1,n)     The length of each wire
 kSpring         (1,n)     The extensional spring constant for each wire
 cSpring         (1,n)     The extensional damping constant for each wire
 vDeploy         (1,n)     The deployment velocity for each wire
 cDeploy         (1,n)     Rate feedback for the deployment mechanism
 nodeDeploying   (1,n)     The node that is about to deploy
 rWireBase       (3,n)     The location of the wire base wrt the c.m.
 rECI            (3,1)     The ECI location of the spacecraft c.m.
 vECI            (3,1)     The ECI velocity of the spacecraft c.m.
 q               (4,1)     The quaternion from the ECI frame to the core frame
 omega           (3,1)     The body rate.
 r0              (3,1)     Reference point
 inertia         (3,3)     Core inertia
 gGOn            (1,1)     1 = on
Outputs
 wireDS          (7,n)     The wire data structure
 x               (m,1)     The state vector
References abs(), DupVect(), Initialize(), length(), Mag(), quaternion(), set(), Unit(), vector(), and zeros().
WirePlot()
function WirePlot (in xPlot, in t, in s)
One wire is plotted on each page.
 Since version 2.
Form
 WirePlot( x, t, s )
Inputs
 xPlot        (m,:)     The state vector
                        [x;v;q;w;xWire;vWire]
 t            (1,1)     Time
 s            (:)       Wire data structure
Outputs
 None
References Plot2D(), and vector().
WMM()
function WMM (in action, in r, in jD)
The actions are:
 help            - load the file and see the help
 create mat file - create the mat file WWW.mat
 plot            - plot the data for the ECI vector r and jD
Type WMM for a demo that will plot the field in an ISS orbit.
Form
 WMM(action,r,jD)
Inputs
 action (1,:)  One of three actions
 r       (3,:)  ECI position vector if you type action 'plot'
 jD      (1,:)  Julian date  if you type action 'plot'
Outputs
 None
References: Software and Model Support: National Geophysical Data Center NOAA EGC/2
See also
: MagField
References and(), Demo(), ISSOrbit(), MagField(), RVOrbGen(), vector(), and WMM().
Referenced by BDipoleCoeff(), and WMM().
WordToFloat()
function WordToFloat (in k, in kMax, in kMin, in resolution)
 Numbers are assumed to be in standard integer format with kMax <= k <= kMax.
Form
 f = WordToFloat( k, kMax, kMin, resolution )
Inputs
 k                   (:)   Integer
 kMax          (1,1)  Maximum integer
 kMin          (1,1)  Minimum integer
 resolution    (1,1)  Floating point value of a 1.
Outputs
 f            (:)    Floating point value
Referenced by RWA(), and RWABristle().
WorstEclipseFraction()
function WorstEclipseFraction (in el0, in rP)
Compute the worst-case eclipse fraction (beta=0) for an eccentric orbit using the perigee.
fracE = WorstEclipseFraction(el0, rP)
 Input:
 el0        (:,6)  Kepler elements [a i W w e M]
 rP         (1,1)  Planet radius
 Output:
 fracE      (1,:) Eclipse fraction (0<f<1)
References Demo(), Eclipse(), and WorstEclipseFraction().
Referenced by WorstEclipseFraction().
WriteBSPFile()
function WriteBSPFile (in varargin)
.bsp is automatically added to filename. It writes 2 intermediate files filename_setup.txt and filename_input.txt. It is limited to state vector inputs. This requires mice. This function will delete an existing bsp file of name 'file name')
Type WriteBSPFile for a demo for an Earth orbit.
Form
 WriteBSPFile( varargin )
Inputs
 varargin {:} Parameter pairs
 'file name'         (1,:)
 'spacecraft id'     (1,1)
 'center id'         (1,1)
 'info'              (1,:) Any text you want
 'julian date start' (1,1)
 'time'              (1,n) Time (s)
 'position'          (3,n) Position (km)
 'velocity'          (3,n) Velocity (km/s)
 'polynomial degree' (1,1)
 'reference frame'   (1,:)
Outputs
 None
Reference: B.V. Semenov, "MKSPK User's Guide", March 01, 2016.
References and(), Date2JD(), Demo(), Parameter(), vector(), and WriteBSPFile().
Referenced by WriteBSPFile().