PSS MATLAB Toolboxes: Sail Functions
Sail Functions
Sail Module
The Sail module functions.
Directories
directory Actuator
Sail actuation including vanes and moving masses.
directory Analysis
Sail orbit analysis.
directory AttitudeDynamics
Sailcraft attitude dynamics, rigid and time-varying.
directory Control
Control functions.
directory Coordinates
Specialized sail coordinate systems.
directory DemoFuns
directory Disturbances
Sail disturbance and environment models.
directory GAOT
Genetic algorithms toolbox.
directory Graphics
Sail visualization and plotting functions.
directory Guidance
Guidance functions.
directory Missions
directory Optimization
directory OptTestFuns
Optimization test functions.
directory OrbitDynamics
directory SailData
directory SailEphem
Sail ephemeris.
directory SailModeling
directory Utilities
Description
Functions
function AccelToLoading (in acc0)
Convert sail characteristic acceleration to loading.
function AccelToSailProps (in accel, in mass)
Sail characteristic acceleration to mass or area for a perfect sail.
function adjswapmutation (in par, in bounds, in genInfo, in Ops)
Adjswap mutation performs a swap of two adjacent.
function AnglesMcInnesToU (in cone, in clock, in r, in v)
Angles to unit vector using McInnes' convention.
function AnglesRotToU (in cone, in clock, in q)
Angles and a reference frame to unit vector.
function ApplyProfileToModel (in g, in p, in k)
Apply a profile struct to a CAD model for display purposes.
function arithXover (in p1, in p2, in bounds, in Ops)
Arith crossover takes two parents P1,P2 and performs an interpolation.
function AsteroidTrajectory (in perturbations)
Example problem from AIAA challenge.
function AttitudeProfileToTorque (in q, in t, in inertia, in w0)
Compute an equivalent torque sequence from an attitude profile.
function b2f (in bval, in bounds, in bits)
Return the float number corresponing to the binary representation.
function BConeClock (in cone, in clock)
Compute a rotation matrix for cone and clock from the reference frame.
function binaryMutate (in parent, in bounds, in Ops)
Binary mutation changes each of the bits of the parent.
function boundaryMutate (in parent, in bounds, in Ops)
Boundary Mutation changes one of the parameters of the parent and.
function BoundedMutation (in parent, in bounds, in opts)
GA mutation function where change is bounded within a fraction.
function calcbits (in bounds, in precision)
Determine the number of bits to represent a float number to the.
function CartToI (in x, in ignoredArg)
Computes inclination from cartesian elements.
function CMToMassPositions (in cM, in m, in d, in u)
Determine mass positions from a desired center of mass.
function ComputeSailNormal (in g)
Find all sail components and calculate their composite normal.
function ConeClockConvention (in cone, in clock, in iConv)
Apply a selected cone/clock sign convention for angle ranges.
function ConeClockPatches (in cone, in clock, in rSC, in vSC, in s, in iConv, in h)
Plot a patch of a sail oriented to the given cone and clock angles.
function ConeClockToQConstrained (in cone, in clock, in r, in v, in s)
Compute a quaternion from cone and clock angles.
function ConeClockToU (in cone, in clock, in r, in v, in s, in c)
Compute a unit vector from cone and clock angles.
function coranaEval (in sol)
Determines the value of the Corana function at point sol.
function coranaMin (in sol, in options)
Function to minimize the Corana function.
function Cost3D (in lambda, in d)
Function to be used for trajectory optimization.
function CostSail2D (in lambda, in d)
Cost function for 2D solar sail trajectory optimization.
function CostSail3D (in lambda, in d)
Cost function for 3D solar sail trajectory optimization.
function CP1Props ()
Front and back optical and thermal properties of CP1 (Lambertian)
function cyclicXover (in p1, in p2, in bounds, in Ops)
Cyclic crossover takes two parents P1,P2 and performs cyclic.
function Cyl2Cart (in r, in theta, in z)
Converts cylindrical position coordinates to cartesian.
function deltaFunction (in ct, in mt, in y, in b)
The delta function is the non-uniform distributions used by the nonUniform.
function DisplaySailProperties (in g, in normal)
Display sail characteristics for a CAD model.
function dists (in X1, in X2, in p, in e)
Calculates distances between vectors of points.
function DisturbanceStruct (in d)
Return a default data structure for SailDisturbance.
function DrawCircularPlane (in qRef, in colorSpec, in l)
Represent the Y/Z plane with a circle with arrows for +X/+Y only.
function DrawSailAngles (in uSun, in r, in v, in c, in cone, in clock)
Draw cone and clock angles in 3D using translucent patches in a new figure.
function DrawSailAttitude (in g, in q, in uSun, in tag)
View a rotated CAD model and the sun vector.
function DrawSailCADModel (in g, in normal)
Draw the sail using DrawSCPlanPlugIn and then adjust colors and lighting.
function DrawSailFrames (in qIToS, in cone, in clock)
Draw cone and clock angles using one color per frame.
function DrawSailMeshVectors (in g, in uSun, in flux)
Draw a sail mesh with force vectors at each face.
function EarthGuidance (in ignoredArg, in x, in d, in env)
Guidance law for planet-centered missions.
function enhancederXover (in p1, in p2, in bounds, in ops)
EnhancederXover crossover takes two parents P1,P2 and performs.
function EnvironmentStruct (in d0)
Return a default data structure for SailEnvironment.
function er (in p1, in p2, in bounds, in ops)
Er crossover takes two parents P1,P2 and performs edge recombination.
function f2b (in fval, in bounds, in bits)
Return the binary representation of the float number fval.
function FCartOrbD (in x, in ignoredArg, in d)
Right hand side for cartesian orbital equations.
function FCoreAndMoving (in t, in x, in ignoredArg, in d)
Example system RHS which incorporates FMovingBody.
function FHingeOrbit (in x, in t, in f, in tq, in d)
Combined point-mass orbit and fixed-rate moving body dynamics model.
function FixedPitchControl (in z, in rho, in nu, in eta)
Correct sail pitch using elevation, dElevation = -dPitch.
function FLambdaToConeClock (in alpha, in d)
Generates the optimal cone and clock angles for 3D problems.
function FMovingBody (in t, in x, in force, in torque, in d)
Moving body dynamics model with instantaneous velocities.
function FOrbitGeneral (in t, in x, in rBodies, in center, in jD, in aExt)
General gravity model allowing point mass and harmonic models.
function FOrbitSingle (in t, in x, in rBodies, in center, in jD, in aExt)
Gravity model allowing a point mass or harmonic models for a single body.
function FPlanetControl (in t, in x, in theta, in accel, in x0, in k)
Sail planet-centered RHS with rho/z control via sail pitch angle.
function FractionalSelection (in oldPop, in opts)
GA selection function where a fixed fraction of the population survives.
function FRotatingFrame (in s, in t, in d)
Three-body dynamics in the rotating frame with a solar sail.
function FRotatingLagrange (in t, in s, in d)
Sail orbit RHS in a 3 body dimensionless rotating frame.
function FRotatingPlanet (in ignoredArg, in x, in theta, in accel)
Sail orbit RHS in a planet-centered cylindrical rotating frame.
function FRotatingSun (in ignoredArg, in x, in theta, in beta, in control)
Sail orbit equations in a sun-centered cylindrical rotating frame.
function FS4Deployment (in t, in x, in force, in ignoredArg, in d)
S4 Sail simplified deployment dynamics from reference.
function FSailCombined (in t, in x, in p, in d)
Simulation right hand side.
function FSailEarthMoon (in t, in x, in ignoredArg, in d)
Sail dynamics with Earth and Moon gravity.
function FSailEarthSun (in t, in x, in flag, in d)
Sail dynamics in the Earth-Sun three-body system.
function FSailGuidance (in t, in x, in a0, in cone, in clock, in mu, in d)
Right-hand-side for sail with fixed cone and clock angles (McInnes).
function FSailRB (in t, in x, in ignoredArg, in torque, in d)
Rigid body right-hand-side for Sail module.
function FSailTB (in t, in x, in force, in torque, in d)
Rewrite of FTB in preferred sail module format.
function FSolarSailAngles (in x, in d)
RHS for a Newton solver for sail angles.
function FTimeVaryingI (in t, in x, in ignoredArg, in torque, in d)
Attitude RHS with time varying inertia of a single body.
function ga (in bounds, in evalFN, in evalOps, in startPop, in opts, in)
GA run a genetic algorithm.
function gaDemo1Eval (in sol, in options)
Demonstration evaluation function used in gademo1.
function GAMin (in fun, in x, in d, in s)
Applies a genetic algorithm to minimizing a function.
function gaZBGradEval (in sol, in options)
This evaluation function takes in a potential solution and two options.
function GeneticAlgorithm (in fun, in x, in d, in s)
Applies a genetic algorithm to minimizing fun.
function GeoOptimalMission (in el0, in jD0, in nDays)
Simulate a geocentric locally optimal trajectory.
function GeoSwitchingMission (in el0, in jD0, in nDays)
Simulate a geocentric trajectory with on/off switching.
function GimbalRates (in angle, in angleCommand, in rateNom, in dT, in zeroTorque)
Compute commanded gimbal rates based on commanded angles and a fixed rate.
function GravityUnitsConverter (in mu, in dist, in time)
Converts mu from km^3/sec^2.
function HCircularBillow (in x, in y, in d)
Circular billow height model.
function HeliopauseSailAngle (in ignoredArg, in t)
Generates a constant angle to get a velocity reversal trajectory.
function heuristicXover (in p1, in p2, in bounds, in Ops, in seed)
Heuristic crossover takes two parents P1,P2 and performs an extrapolation.
function HGimballedBoom (in x, in g, in axis, in aDotNew, in hW)
Calculate angular momentum of boom system and update the body rates.
function HingeRotationMatrix (in angle, in axis)
Transformation matrix for an arbitrary number of single axis rotations.
function HQuadrantBillow (in x, in y, in data)
Models a single sail quadrant as a section of an oblique cone.
function HRakoczy (in x, in y, in d)
Height function for a square sail with billow.
function IDotS4 (in t, in d)
Inertia derivative of S4 sail.
function initializega (in num, in bounds, in evalFN, in evalOps, in options)
Initializega creates a matrix of random numbers with a number of rows.
function initializeoga (in num, in bounds, in evalFN, in evalOps, in options)
Initializeoga creates a matrix of random permutations with a number.
function InitializeSailGravity (in d, in bodyNames, in models, in nZ, in nT, in ids)
Initialize the sail simulation gravity model.
function InitializeSailSim (in jD, in cadModel, in guidance)
Initialize the sail simulation data for common cases.
function inversionMutation (in par, in bounds, in genInfo, in Ops)
Inversion mutation inverts the bits or permutation between two.
function LambdaToConeClock3D (in x, in type, in d)
Generates the optimal cone and clock angles for 3D problems.
function LightnessToLoading (in beta)
Sail loading (mass/area) from lightness parameter.
function LoadingToAccel (in sigma)
Sail loading parameter to characteristic acceleration.
function LoadingToLightness (in sigma)
Sail lightness parameter from loading (mass/area).
function LocallyOptimalConeClock3D (in x, in type, in d)
Generates locally optimal cone and clock angles for 3D problems.
function LocallyOptimalTraj (in type, in r, in v, in mu, in dirFlag, in ascendingNode)
Computes locally optimal solar sail control angles.
function lox (in p1, in p2, in bounds, in genInfo, in ops)
Linearorder crossover takes two parents P1,P2 and performs linear order.
function LunarDisplacement (in z0, in L, in muM, in muE)
Compute the sail acceleration needed for a displaced lunar Lagrange halo.
function LunarHalo (in accel, in L, in theta, in muM, in muE)
Initial conditions for a Sail halo in the Earth-Moon system.
function MakeSquareSail (in accel, in mass, in fileName)
Generate a flat, square, nonideal sail in the Y/Z plane, using CP1 properties.
function MassVehicle (in g, in angle, in axis)
This function computes the mass data structure given angles.
function maxGenTerm (in ops, in bPop, in endPop)
Returns 1, i.e.
function MEQToI (in x)
Compute inclination from modified equinoctial coordinates.
function multiNonUnifMutation (in parent, in bounds, in Ops)
Multi-Non uniform mutation changes all of the parameters of the parent.
function NewtonDemoFun (in x, in ignoredArg)
Returns the values of the equations.
function NewtonSolver (in fun, in x, in opt, in d)
Solves for the zeros of a set of n equations.
function NKPlanetPeriod (in planet, in radii, in z)
Compute non-Kepler orbit periods from parameters in planetary radii.
function NonKeplerianPlanet (in rho, in z, in omega, in mu)
Sail parameters for non-Keplerian orbits near a planet.
function NonKeplerianSun (in rho, in z, in omega)
Sail lightness and pitch for a sun-centered displaced non-Keplerian orbit.
function nonUnifMutate (in parent, in bounds, in Ops, in seed)
Non uniform mutation changes one of the parameters of the parent.
function normGeomSelect (in oldPop, in options, in seed)
NormGeomSelect is a ranking selection function based on the normalized.
function oox (in p1, in p2, in bounds, in Ops)
Orderbased crossover takes two parents P1,P2 and performs order.
function OpticalMcInnesToPSS (in r, in s)
Convert McInnes optical coefficients to PSS format.
function OptimalPeriodNonKepler (in z, in rho)
Optimal orbit rate for minimizing required sail lightness parameter.
function optMaxGenTerm (in ops, in bPop, in endPop)
Returns 1, i.e.
function OptTestFun (in x, in d)
10 test functions for optimization routines.
function OptTestFunEcon (in x, in ignoredArg)
There are two optima:
function OptTestFunParabola (in x, in ignoredArg)
A simple parabola, the function f = x^2.
function OptTestFunRosenbrock (in x, in ignoredArg)
Rosenbrock test function.
function parse (in inStr)
Parse is a function which takes in a string vector of blank separated.
function partmapXover (in par1, in par2, in bounds, in Ops)
Partmap crossover takes two parents P1,P2 and performs a partially.
function PlanetOptimalTraj (in dir, in r, in v, in uSun)
Computes locally optimal solar sail control angles for planet-centric.
function PlanetRot (in planet, in jD)
Transform from ECI to planet-fixed axes.
function Plot3DOrbit (in r, in v, in mu, in plotTitle)
Plot a trajectory in 3D with initial and final orbits marked.
function Plot3DTrajectory (in lambda, in d, in units, in plotTitle)
Propagate and plot a 3D trajectory using costate outputs from optimization.
function PlotSailClock2D (in f, in n, in a, in s, in r, in v, in c)
Plot clock angle and relevant vectors in the 2D clock plane.
function PlotSailForce (in f, in p, in env, in c)
Plot the solar sail disturbance forces from the force structure.
function PlotSailForce2D (in f, in n, in s, in a)
Plot relationship between force, normal, and sun vectors in 2D.
function PlotSailProfile (in p, in env, in normal, in c)
Default plots for the information stored in the sail orbit profile.
function PlottingParabolas (in rho0, in z0)
Compute parabolic bounding surfaces for manifolds.
function ProfileStruct ()
Return a default profile structure for SailDisturbance.
function QSail (in s, in r, in v, in c)
Quaternion from inertial to the local rotating sun-sail frame.
function QSteeringYAligned (in cone, in clock, in c)
Compute the steering rotation keeping the body axis aligned with Y.
function QToConeClock (in qIToB, in r, in v, in s)
Computes cone and clock angles from an inertial to body quaternion.
function Quadratic (in x, in ignoredArg)
The function f = x'*x.
function QXToAlphaDelta (in q, in x)
Cone and clock angles (alpha,delta) to inertial quaternion.
function RHS2DOrbit (in t, in x, in d)
This function is for the sail planar orbit problem.
function RHS3DOrbit (in t, in x, in flag, in d)
Right-hand-side for the sail 3D orbit optimization problem.
function RHSCartesian (in t, in x, in d)
Right-hand-side for point-mass cartesian orbit with external acceleration.
function RHSCartesianRadialAccel (in ignoredArg, in x, in d)
Right-hand-side for point-mass cartesian orbit with radial acceleration.
function RHSHelio2DOrbit (in t, in x, in flag, in d)
Planar heliocentric orbit problem with specular solar disturbance force.
function RHSOpt2DOrbit (in t, in x, in flag, in d)
Right-hand-side for the sail planar orbit optimization problem.
function RHSOpt3DOrbit (in t, in x, in flag, in d)
Right-hand-side for the sail 3D orbit optimization problem.
function roulette (in oldPop, in options)
Roulette is the traditional selection function with the probability of.
function S4DeployTorque (in ignoredArg, in p, in ignoredArg, in d)
Disturbances function for modeling deployment of scalable square sail.
function SailACS (in x, in d)
Control system.
function SailClosedLoopNLEqns (in ignoredArg, in x, in kappa0, in rho0, in z0, in G, in mode)
Nonlinear sail RHS with area control.
function SailDefaultColors (in action)
Define default colors for all sail plots.
function SailDisturbance (in g, in p, in e, in d)
Compute the forces and torques on a solar sail vehicle.
function SailEnvironment (in planet, in p, in d)
Space environment models.
function SailEphemAlmanac (in jD, in d)
Location of planets relative to Sun in ecliptic frame using the almanac.
function SailEphemEarth (in jD, in ignoredArg)
Location of Earth relative to Sun in the ecliptic frame.
function SailEphemJPL (in jD, in d)
Location of planets relative to Sun in ecliptic frame using JPL ephemerides.
function SailForceSubplots (in f, in n, in s, in q, in c)
View a single force vector in two planes using four subplots.
function SailMesh (in x, in y, in hFunc, in d, in nRefine)
Create a mesh with the height determined by a specified function.
function SailOrbitContours (in BetaFunction, in betaC, in x, in z, in varargin)
Create and draw sail orbit contours.
function SailPatchVertices (in kAxis)
Sail vertices for a default sail in the Y/Z plane.
function SailPropsToAccel (in area, in mass)
Sail characteristic acceleration from mass and area.
function SailSMAChange (in type, in a0, in accel, in nOrbits, in direction)
SMA change in Earth orbit.
function SARosenbrock (in x, in ignoredArg)
The function f = 100*(x(1)^2-x(2))^2 + (1-x(1))^2.
function SATestFun (in x, in ignoredArg)
Minimize the function f = 3x^3 + 5x^2 -2x + 3.
function SearchVaneAngles (in Td, in theta0, in g, in env, in p, in d)
Solve a three-axis control vane problem using fminsearch.
function shiftMutation (in par, in bounds, in genInfo, in Ops)
Shift mutation performs displaces one random genein a permutation.
function simpleXover (in p1, in p2, in bounds, in Ops)
Simple crossover takes two parents P1,P2 and performs simple single.
function SimulatedAnnealing (in fun, in x, in d, in s)
Implements simulated annealing.
function SingleCrossover (in p1, in p2, in ignoredArg, in opts)
GA crossover function which switches a randomly selected parameter between.
function singlePtX (in p1, in p2, in bounds, in Ops)
Uniform mutation changes one of the parameters of the parent based on.
function SolarPressureForce (in area, in nB, in uSun, in flux, in optical, in emissivity)
Combined thermal and optical solar pressure force model.
function SolveVaneAngles (in Td, in theta0, in g, in env, in p, in d)
Solve a two-axis control vane problem using Newton's method.
function SPIGuidance (in t, in x, in d, in env)
Guidance law for Solar Polar Imager using locally optimal control.
function SteeringAnglesToQ (in incidence, in clock, in uSun, in r, in v, in c)
Convert sail steering angles to a quaternion.
function StripedQuadrant (in l, in nStripes, in billow, in nSub)
Create a striped sail quadrant, with billow, in the x, y plane.
function SubL1Accel (in dX, in theta, in phi)
Find a sail acceleration to maintain a Sub-L1 station.
function SunGuidance (in ignoredArg, in x, in d, in env)
Guidance laws for common sun-centered profiles.
function swapmutate (in par, in bounds, in genInfo, in Ops)
Swap mutation exchanges the positions of two randomly chosen genes in.
function threeswapMutation (in p, in bounds, in genInfo, in Ops)
Three swap mutation performs a three way swap of three randomly.
function TorqueToCM (in T, in f, in Cp)
Sail actuation function computing needed CM to produce a given torque.
function tournSelect (in oldPop, in options)
Performs a tournament selection.
function TwoBodyRateModel (in x, in ignoredArg, in force, in torque, in g, in p, in hW)
Gimballed boom dynamics model for fixed gimbal rates.
function TwoDOptimalSailAngle (in x, in ignoredArg)
Generates the optimal sail angle for planar problems, from costates.
function uniformMutate (in parent, in bounds, in Ops)
Uniform mutation changes one of the parameters of the parent based on.
function uniformxover (in par1, in par2, in bounds, in Ops)
Uniform crossover takes two parents P1,P2 and performs uniform.
function UpdateSailOpticalProps (in g, in optical, in emissivity, in infrared)
Look up all the sail class components and update their properties.
function UToConeClock (in u, in r, in v, in s, in c)
Computes cone and clock angles from a unit vector.
function VaneAngles (in areaVane, in momentArm, in Tcommand, in solarFlux)
Compute angle commands for roll control using sail vanes.
function VarEqSailPlanet (in rho, in z, in omega)
Sail variational equations in state space form for a planet-centered orbit.
function VisualizeSailAttitude (in q, in uSun, in q2, in c, in kAxis)
Visualize the attitude of a sail in 3D using a patch and sun vector.
Function Documentation
AccelToLoading()
function AccelToLoading (in acc0)
The loading is the sail mass per unit area, m/A.
Form
 sigma = AccelToLoading( acc0 )
Inputs
 acc0         (1,n) Characteristic acceleration, m/s2
Outputs
 sigma        (1,n)  Sail loading (kg/m2)
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999, p. 14
References and(), and McInnes().
Referenced by MakeSquareSail().
AccelToSailProps()
function AccelToSailProps (in accel, in mass)
 Will create a matrix if two vectors are input. Otherwise it will output
 a row vector.
 Has a built-in demo for a range of acceleration and mass.
 Since version 7.
Form
 area = AccelToSailProps( accel, mass )
Inputs
 accel         (1,m)  Sail acceleration (m/s2)
 mass          (1,n)  Spacecraft total mass (kg)
Outputs
 area     (1,n) or (m,n) Sail area, m2
References and(), Constant(), Demo(), length(), Plot2D(), square(), vector(), and zeros().
adjswapmutation()
function adjswapmutation (in par, in bounds, in genInfo, in Ops)
 genes in a permutation
 Since version 7.
Form
 [child] = adjswapmutation(par,bounds,genInfo,Ops)
Inputs
 par            the first parent ( [solution string function value] )
 bounds            the bounds matrix for the solution space
 genInfo
 Ops               Options for binaryMutation [gen prob_of_mutation]
Outputs
 child
Reference: C.R. Houck, J.Joines, and M.Kay. A genetic algorithm for function optimization: A Matlab implementation. ACM Transactions on Mathmatical Software, Submitted 1996.
 See the included paper named "gaotv5.pdf" for more information.
References and().
AnglesMcInnesToU()
function AnglesMcInnesToU (in cone, in clock, in r, in v)
u will be AWAY from the sun.
The cone and clock angles define the vector from the reference axes such that
n = cos(cone)*r + sin(cone)*cos(clock)*p + sin(cone)*sin(clock)*z
where p is the orbit normal and z = p x r. A special function is necessary because McInnes does not define clock from the y-axis of a right-handed frame.
Form
 u = AnglesMcInnesToU( cone, clock, q )
Inputs
 cone          (1,:) Cone angle (rad)
 clock         (1,:) Clock angle (rad)
 q             (1,:) Rotation from inertial to clock reference frame
Outputs
 u
See also
AnglesRotToU
References McInnes(), and vector().
Referenced by FSailGuidance().
AnglesRotToU()
function AnglesRotToU (in cone, in clock, in q)
The cone and clock angles define the vector from the reference axes such that
n = cos(cone)*x + sin(cone)*cos(clock)*y + sin(cone)*sin(clock)*z
so that clock is defined from the reference y axis. The quaternion defines the rotation from the basis (inertial) frame to the clock reference frame.
Form
 u = AnglesRotToU( cone, clock, q )
Inputs
 cone          (1,:) Cone angle (rad)
 clock         (1,:) Clock angle (rad)
 q             (1,:) Rotation from inertial to clock reference frame
Outputs
 u
References and(), Cone(), QTForm(), quaternion(), and vector().
ApplyProfileToModel()
function ApplyProfileToModel (in g, in p, in k)
Puts the q, axis, and angle fields in the appropriate fields in g. g can then be passed into display functions like DrawSCPlanPlugIn.
Form
 g = ApplyProfileToModel( g, p, k )
Inputs
 g      (:)     CAD model
 p      (:)     Profile structure with state fields
                 .q           (4,:) ECI to body quaternion
                 .r           (3,:) ECI position vectors
                 .v           (3,:) ECI velocities
                 .jD          (1,:) Julian dates
                 .rPlanetH    (3,:) Vector to planet in heliocentric frame
                 .angle       (n,:) Angles (initialized empty)
                 .axis        (3,n) Axes for angles (empty)
                 .body        (1,n) Body hinge for angle (empty)
 k     (1,1)    Index to profile elements, if needed
Outputs
 g      (:)     Updated CAD model
References and(), DrawSCPlanPlugIn(), length(), and quaternion().
arithXover()
function arithXover (in p1, in p2, in bounds, in Ops)
 along the line formed by the two parents.
 Since version 7.
Form
 [c1,c2] = arithXover(p1,p2,bounds,Ops)
Inputs
 p1              the first parent ( [solution string function value] )
 p2              the second parent ( [solution string function value] )
 bounds          the bounds matrix for the solution space
 Ops             Options matrix for arith crossover [gen #ArithXovers]
Outputs
 c1
 c2
References and().
Referenced by ga().
AsteroidTrajectory()
function AsteroidTrajectory (in perturbations)
 The asteroid in question should hit the Earth.
 Demonstrates an n-body gravity model using point masses. There is an
 option to include the perturbations or to integrate with only the sun.
 The perturbations bring the final position from an 883 Earth radii miss
 distance to only 5 radii. The perturbations include the major planets,
 except Pluto, and the moon.
 Has a built-in RHS function combining ephemeris with gravity.
 The plots at the end can be replicated with the function output.
 Since version 7.
Form
 [xPlot,tPlot,rEarth,rMars] = AsteroidTrajectory( perturbations )
Inputs
 perturbations    (1,1)    1 to include perturbations, 0 otherwise
References and(), Initialize(), Mag(), Plot2D(), and RHS().
AttitudeProfileToTorque()
function AttitudeProfileToTorque (in q, in t, in inertia, in w0)
 The torque is calculated using an equivalent single-axis rotation for each
 step in the profile.
 This function has a built-in demo for LVLH tracking in an elliptical orbit.
 Since version 7.
Form
 [torque,omega] = AttitudeProfileToTorque( q, t, inertia, w0 )
Inputs
 q        (4,n)   Quaternion profile
 t        (1,n)   Time vector
 inertia  (3,3)   Vehicle inertia
 w0       (3,1)   Initial rotational velocity (default is zeros)
Outputs
 torque   (3,n-1)   Torque sequence
 omega    (3,n)   Angular velocity
References and(), AttitudeProfileToTorque(), Demo(), Mag(), OrbRate(), Plot2D(), Q2AU(), QLVLH(), QMult(), QPose(), RVFromKepler(), vector(), and zeros().
Referenced by AttitudeProfileToTorque().
b2f()
function b2f (in bval, in bounds, in bits)
 of bval.
 Since version 7.
Form
 [fval] = b2f(bval,bounds,bits)
Inputs
 bval              the binary representation of the number
 bounds            the bounds on the variables
 bits              the number of bits to represent each variable
Outputs
 fval              the float representation of the number
References and().
Referenced by ga().
BConeClock()
function BConeClock (in cone, in clock)
 assuming that clock is measured about the X axis from the Y axis.
 Cone is then a rotation about the new Z axis.
 B = cone|z * clock|x
 Since version 7.
Form
 B = BConeClock( cone, clock )
Inputs
 cone          (1,:) Cone angle (rad)
 clock         (1,:) Clock angle (rad)
Outputs
 B             (3,3) Transformation matrix
References and(), Cone(), and Eul2Mat().
binaryMutate()
function binaryMutate (in parent, in bounds, in Ops)
 based on the probability of mutation
 Since version 7.
Form
 [parent] = binaryMutate(parent,bounds,Ops)
Inputs
 parent            the first parent ( [solution string function value] )
 bounds            the bounds matrix for the solution space
 Ops               Options for binaryMutation [gen prob_of_mutation]
Outputs
 parent
References and().
boundaryMutate()
function boundaryMutate (in parent, in bounds, in Ops)
 changes it randomly either to its upper or lower bound.
 Since version 7.
Form
 [parent] = boundaryMutate(parent,bounds,Ops)
Inputs
 parent            the first parent ( [solution string function value] )
 bounds            the bounds matrix for the solution space
 Ops               Options for boundaryMutation [gen #BndMutations]
Outputs
 parent
References and().
BoundedMutation()
function BoundedMutation (in parent, in bounds, in opts)
of the range. Each element is mutated independently.
There are three options supplied by the user: nMut, the number of mutations attempted each generation,
 pMut, the probability that the randomly selected member will have a mutation,
 fracMut, the fraction of the range over which the mutations will occur.
The first option, iGen, is supplied by the genetic algorithm.
Form
 child = BoundedMutation( parent, bounds, opts )
Inputs
 parent            (1,m+1)  Parent member
 bounds            (m,2)    Variable bounds (-/+)
 opts              (4)      Options, [iGen nMut pMut fracMut]
Outputs
 child             (1,m+1)  Mutated child
References and(), and length().
calcbits()
function calcbits (in bounds, in precision)
 precision provided.
 Since version 7.
Form
 [bits]=calcbits(bounds,precision)
Inputs
 bounds            the bounds on the variables
 precision         the least difference to distinguish two numbers
Outputs
 bits              the number of bits required per variable
References and().
Referenced by ga().
CartToI()
function CartToI (in x, in ignoredArg)
Form
 i = CartToI( x, mu )
Inputs
 x               (6,1) [r;v]
 mu              (1,1) Gravitational constant (not used)
Outputs
 i               (1,1) Inclination
References Cross(), and Mag().
Referenced by Cost3D().
CMToMassPositions()
function CMToMassPositions (in cM, in m, in d, in u)
 Each mass is assumed to move along a track with a given unit vector.
Form
 [rho, kA] = CMToMassPositions( cM, m, d, u )
Inputs
 cM     (3,1)     Requested CM
 m      (1,n)     Mass, including core
 d      (3,n)     Position offset, including core
 u      (3,m)     Unit vector of moving masses
Outputs
 rho    (1,m)     Mass positions along track
References and(), Unit(), and vector().
ComputeSailNormal()
function ComputeSailNormal (in g)
 If no outputs, run a demo and draw the normal in black.
 Since version 7.
Form
 n = ComputeSailNormal( g )
Inputs
 g        (:)       CAD model data structure
Outputs
 n       (3,1)      Normal vector
References and(), Normal(), and vector().
Referenced by DisplaySailProperties(), and PlotSailProfile().
ConeClockConvention()
function ConeClockConvention (in cone, in clock, in iConv)
 1: Cone angle limited to [0,pi/2]
 2: Clock angle limited to [0,pi)
 Since version 7.
Form
 [cone, clock] = ConeClockConvention( cone, clock, iConv )
Inputs
 cone           (1,:)  In-plane angle (rad)
 clock          (1,:)  Out-of-plane angle (rad)
 iConv          (1,1)  Index of desired convention
Outputs
 cone           (1,:)  In-plane angle (rad)
 clock          (1,:)  Out-of-plane angle (rad)
References Cone(), ConeClockConvention(), Demo(), length(), and WrapPhase().
Referenced by ConeClockConvention().
ConeClockPatches()
function ConeClockPatches (in cone, in clock, in rSC, in vSC, in s, in iConv, in h)
 The patch is scaled to be visible on a plot of the orbit.
See also
ClockConversion.
 Since version 7.
Form
 ConeClockPatches( cone, clock, rSC, vSC, s, iConv, h )
Inputs
 cone    (1,n)     Cone angle
 clock   (1,n)     Clock angle
 rSC     (3,n)     Spacecraft position
 vSC     (3,n)     Spacecraft velocity
 s       (3,n)     Sun unit vector, can also be (3,1)
 iConv   (1,1)     Index of clock convention
 h       (1,1)     Figure handle
Outputs
 None.
References and(), ClockConversion(), Cone(), length(), Mag(), square(), vector(), and zeros().
ConeClockToQConstrained()
function ConeClockToQConstrained (in cone, in clock, in r, in v, in s)
 The sail rotation is constrained to the y and z axes. This is appropriate
 when the attitude control is limited, i.e. a control boom.
 The cone angle is the angle between the sail and sun vectors and the clock
 angle is in the sun normal plane measured from the intersection with the
 orbit plane. In a frame defined with the x axis towards the sun,
 the y axis along the cross product of the orbit normal and sun vector,
 and the third vector completing the set, the clock angle is measured from
 the y axis. The unit vector is in the same frame as r, v, and s.
 Requires the position, velocity and sun vectors. The latter is a unit
 vector. You can input multiple sets and the function will return
 a 3-by-n vector.
 See ConeClockToU for a demo showing the unit vectors for a circular
 orbit around the sun. See also QSail which uses the same frame.
 Since version 7.
Form
 q = ConeClockToQConstrained( cone, clock, r, v, s )
Inputs
 cone          (1,:) Cone angle (rad)
 clock         (1,:) Clock angle (rad)
 r             (3,:) Orbit vector
 v             (3,:) Velocity vector
 s             (3,:) Sun unit vector (from sc to sun)
Outputs
 q             (3,n) Quaternions
References and(), Cone(), ConeClockToU(), Cross(), Eul2Mat(), Euler(), length(), Mat2Q(), QSail(), quaternion(), set(), Unit(), vector(), and zeros().
ConeClockToU()
function ConeClockToU (in cone, in clock, in r, in v, in s, in c)
 The cone angle is the angle between the force and sun vectors and the clock
 angle is in the sun normal plane measured from the Y axis of the reference
 frame. The X axis is along the sun line s; this may be towards or away from the
 sun depending on user preference. The remaining axes are defined by the
 cross product of X with either the orbit normal or the velocity vector.
 u = cos(cone)*x + sin(cone)*cos(clock)*y + sin(cone)*sin(clock)*z
 Requires the position, velocity and sun vectors. The latter is a unit
 vector. You can input multiple sets and the function will return
 a 3-by-n vector.
 Type ConeClockToU for a demo showing the unit vectors for a circular
 orbit around the sun. See also QSail which uses the same frame.
 Since version 7.
Form
 [u,qItoCC] = ConeClockToU( cone, clock, r, v, s, c )
 [u,qItoCC] = ConeClockToU( cone, clock, q )
Inputs
 cone          (1,:)  Cone angle (rad)
 clock         (1,:)  Clock angle (rad)
 r             (3,:)  Orbit vector
 v             (3,:)  Velocity vector
 s             (3,:)  Sun unit vector
 c             (1,1)  Sign convention, optional
Outputs
 u             (3,n) Unit vectors
 qItoCC        (4,n) Quaternions from inertial frame to cone/clock frame
References and(), Cone(), ConeClockToU(), Constant(), Cross(), Demo(), Eul2Mat(), isempty(), length(), Mag(), Mat2Q(), Plot3D(), QSail(), QTForm(), RVFromKepler(), Unit(), vector(), and zeros().
Referenced by ConeClockToQConstrained(), ConeClockToU(), and UToConeClock().
coranaEval()
function coranaEval (in sol)
 This function is used in gademo2.
 Since version 7.
Form
 [val] = coranaEval(sol)
Inputs
 sol              the location to evaluate the Corana function
Outputs
 val              the value of the Corana function at point sol
 This function is used in gademo2.
 Since version 7.
Form
 [val] = coranaEval(sol)
Inputs
 sol              the location to evaluate the Corana function
Outputs
 val              the value of the Corana function at point sol
References and().
coranaMin()
function coranaMin (in sol, in options)
 Since version 7.
Form
 [sol,val] = coranaMin(sol,options)
Inputs
 sol              the location to evaluate the Corana function
 options
Outputs
 sol              the location to evaluate the Corana function
 val              the value of the Corana function at point sol
References and().
Cost3D()
function Cost3D (in lambda, in d)
It computes an err magnitude that the optimizer uses to find the minimum. This function is for 3D minimum time problems. The states are modified equinoctial or cartesian elements.
Form
 d = Cost3D( 'get' ) % data structure
 [errMag, err, x, t] = Cost3D( lambda, d )
Inputs
 lambda         (6,1)  Costates
 d               (.)  Structure
                       .rhsFun       @ Associated RHS function for optimizer
                       .plotFun      @ Associated plot function for optimizer
                       .eventsFun    @ Associated events function
                       .x0          (6,1) Initial state from optimizer
                       .xF          (6,1) Final state from optimizer
                       .tEnd        (1,1) Final time from opimizer
                       .boundCond   (1,:) Index
                       .errorScale  (6,1) weights for the errors
                       .data.absTol  (1,:) ode113 options
                       .data.relTol  (1,:) ode113 options
                       + fields for RHS function
Outputs
 errMag         (1,:)  Magnitude of the error
 err            (6,1)  Error vector
 x              (:,n)  States
 t              (1,n)  Time
References and(), CartToI(), Constant(), Cost3D(), ElToMEq(), get(), Initialize(), Mag(), MEQToI(), Plot3DTrajectory(), RHS(), RHSOpt3DOrbit(), TimeDisplay(), and vector().
Referenced by Cost3D(), and Plot3DTrajectory().
CostSail2D()
function CostSail2D (in lambda, in d)
It computes an error magnitude that the optimizer uses to find the minimum. This function is for the planar orbit problem which includes radial position, radial velocity, tangential velocity. Uses ode113 to integrate the orbit to tEnd and then truncates the solution at the minimum error point.
Form
 [errMag, err, x, t] = CostSail2D( lambda, d )
Inputs
 lambda         (3,1)  Costates [r;dr/dt;drtheta/dt]
 d                (.)  Structure
                       .rhsFun      (1,:)  Associated RHS function for optimizer
                       .plotFun     (1,:)  Associated plot function for optimizer
                       .accel       (1,1)  Sail acceleration
                       .mu          (1,1)  Gravitational parameter
                       .x0          (3,1)  Initial state from optimizer
                       .xF          (3,1)  Final state from optimizer
                       .tEnd        (1,1)  Final time from opimizer
                       .data         (.)   'absTol' and 'relTol'
                       .errorScale  (3,1)  Weights for the error
Outputs
 errMag         (1,:)  Magnitude of the error
 err            (3,1)  Error vector
 x              (:,n)  [states;costates]
 t              (1,n)  Time
References abs(), and(), Constant(), DupVect(), get(), length(), Mag(), Plot2DTrajectory(), RHS(), RHSOpt2DOrbit(), TwoDOptimalSailAngle(), and vector().
CostSail3D()
function CostSail3D (in lambda, in d)
It computes an err magnitude that the optimizer uses to find the minimum.
This function is specifically for the minimum time problem.
Form
 [errMag, err, x, t] = CostSail3D( lambda, d )
Inputs
 lambda         (6,1)  Costates [p;f;g;k;h;L]
 d              (1,1)  Structure
                       .rhsFun      (1,:)  Associated RHS function for optimizer
                       .plotFun     (1,:)  Associated plot function for optimizer
                       .accel       (1,1)  Sail acceleration
                       .mu          (1,1)  Gravitational parameter
                       .x0          (6,1)  Initial state from optimizer
                       .xF          (6,1)  Final state from optimizer
                       .tEnd        (1,1)  Final time from opimizer
                       .oDEOptions  (1,:)  ode113 options
                       .errorScale  (6,1)  Weights for the error
Outputs
 errMag         (1,1)  Magnitude of the error
 err            (6,1)  Erors
 x              (:,n)  States
 t              (1,n)  Time
References abs(), Constant(), DupVect(), get(), length(), Mag(), Planets(), RHS(), RHSOpt3DOrbit(), and vector().
CP1Props()
function CP1Props ()
 2.2 um CP1 with aluminized front and optically clear back.
 Since version 7.
Form
 [optical, infrared, thermal] = CP1Props
Inputs
 none
Outputs
 optical         (:)   Optical properties
 infrared        (:)   Infrared properties
 thermal         (:)   Thermal properties
References and(), and CP1Props().
Referenced by CP1Props(), and MakeSquareSail().
cyclicXover()
function cyclicXover (in p1, in p2, in bounds, in Ops)
 crossover by Davis on permutation strings.
 Since version 7.
Form
 [c1,c2] = cyclicXover(p1,p2,bounds,Ops)
Inputs
 p1              the first parent ( [solution string function value] )
 p2              the second parent ( [solution string function value] )
 bounds          the bounds matrix for the solution space
 Ops             Options matrix for simple crossover [gen #SimpXovers].
Outputs
 c1
 c2
References and().
Cyl2Cart()
function Cyl2Cart (in r, in theta, in z)
Form
 [x, y, z] = Cyl2Cart( r, theta, z )
Inputs
 r                     (:,:)  Either r or [r;theta;phi]
 theta                 (:)    theta (angle in xy-plane)
 z                     (:)    z
Outputs
 x                     (:,:)  Either x or [x;y;z]
 y                     (:)    y
 z                     (:)    z
deltaFunction()
function deltaFunction (in ct, in mt, in y, in b)
 mutations.  This function returns a change based on the current gen, the
 max gen and the amount of possible deviation.
Form
 [change] = deltaFunction(ct,mt,y,b)
Inputs
 ct         current generation
 mt         maximum generation
 y          maximum amount of change, i.e. distance from parameter
            value to bounds
 b          shape parameter
Outputs
 change
Reference: C.R. Houck, J.Joines, and M.Kay. A genetic algorithm for function optimization: A Matlab implementation. ACM Transactions on Mathmatical Software, Submitted 1996.
 See the included paper named "gaotv5.pdf" for more information.
References and().
DisplaySailProperties()
function DisplaySailProperties (in g, in normal)
 Draws the model in 3D and displays properties at the command line.
 Axes are drawn on the 3D sail view with X blue, Y green, and Z red.
 If the normal is not entered it will be calculated for all sail
 components. This is the front normal of the sail, i.e. the side directed
 towards the sun.
See also
ComputeSailNormal.
Form
 DisplaySailProperties( g, normal )
Inputs
 g       (:)       CAD model structure or a string file name
 normal  (3,1)     Normal vector (sail front) in body frame, optional
Outputs
 None.
References AddAxes(), and(), ComputeSailNormal(), CrossSection(), DisplaySailProperties(), DrawSCPlanPlugIn(), FindDirectory(), get(), isempty(), length(), Normal(), SailPropsToAccel(), and vector().
Referenced by DisplaySailProperties(), and InitializeSailSim().
dists()
function dists (in X1, in X2, in p, in e)
 Since version 7.
Form
 D = dists(X1,X2,p,e)
Inputs
 X1  = n x d matrix of n d-dimensional points
 X2  = m x d matrix of m d-dimensional points
 p   = 2, Euclidean (default): D(i,j) = sqrt(sum((X1(i,:) - X2(j,:))^2))
     = 1, rectilinear: D(i,j) = sum(abs(X1(i,:) - X2(j,:))
     = Inf, Chebychev dist: D(i,j) = max(abs(X1(i,:) - X2(j,:))
     = (1 Inf), lp norm: D(i,j) = sum(abs(X1(i,:) - X2(j,:))^p)^(1/p)
     = 'rad', great circle distance in radians of a sphere
       (where X1 and X2 are decimal degree latitudes and longitudes)
     = 'mi' or 'sm', great circle distance in statute miles on the earth
     = 'km', great circle distance in kilometers on the earth
 e   = epsilon for hyperboloid approximation gradient estimation
     = 0 (default); no error checking if any non-empty 'e' input
     ~= 0 => general lp used for rect., Cheb., and p outside [1,2]
Outputs
 D   = n x m matrix of distances
     = (n-1) x 1 vector of distances between X1 points, if X2 = []
References abs(), and(), isempty(), scalar(), and vector().
Referenced by CubeSatDisturbanceAnalysis().
DisturbanceStruct()
function DisturbanceStruct (in d)
 Will add the fields to an existing structure d0 if one is input.
 Since version 7.
Form
 d = DisturbanceStruct( d0 )
Inputs
 d0            (:)    Data structure, optional
Outputs
 d             (:)    Data structure with disturbance fields
References SailDisturbance().
Referenced by InitializeSailSim(), and SailDisturbance().
DrawCircularPlane()
function DrawCircularPlane (in qRef, in colorSpec, in l)
 Draws on the curernt figure.
 Since version 7.
Form
 DrawCircularPlane( qRef, colorSpec, l )
 qRef       (4,1)    Reference quaternion
 colorSpec   (:)     Color for the axes arrows
 l          (1,1)    Radius of the circle
References Circle(), QRand(), QTForm(), quaternion(), set(), and zeros().
Referenced by DrawSailAngles(), and VisualizeSailAttitude().
DrawSailAngles()
function DrawSailAngles (in uSun, in r, in v, in c, in cone, in clock)
 Also draws the reference plane. Does not draw the sail itself.
 The reference frame is first rotated about +X by the clock angle and then
 the cone angle is achieved by rotating about the new Z axis.
 The cone angle is drawn with a rad patch and the clock angle in green.
 Since version 7.
Form
 DrawSailAngles( uSun, r, v, c, cone, clock )
 DrawSailAngles( uSun, q, cone, clock )
Inputs
 uSun     (3,1)     Sun ephemeris unit vector (TO sun)
 r        (3,1)     Position vector (optional)
 v        (3,1)     Velocity vector
 c        (1,1)     Sign convention
 cone     (1,1)     Cone angle, radians (incidence to sun)
 clock    (1,1)     Clock angle, radians (azimuth from y)
Outputs
 None.
See also
QSail.
References and(), AnglePatch(), Cone(), Cross(), Dot(), DrawCircularPlane(), DrawSailAngles(), Eul2Mat(), isempty(), length(), Mag(), NewFig(), Q2Mat(), QSail(), QTForm(), SailDefaultColors(), set(), Unit(), vector(), and zeros().
Referenced by DrawSailAngles().
DrawSailAttitude()
function DrawSailAttitude (in g, in q, in uSun, in tag)
 If uSun has an extra column it is drawn as a planet vector.
 The sun and planet positions or sizes are not drawn to scale.
 Since version 7.
Form
 tag = DrawSailAttitude( g, q, uSun )
 DrawSailAttitude( g, q, uSun, tag )
Inputs
 g        (:)     CAD model data structure
 q        (4,1)   Inertial to body quaternion
 uSun     (3,n)   Sun/planet vector(s) in inertial frame
 tag      (:)     Window tag if updating an existing window
Outputs
 tag      (:)     Window tag if initializing a window
References AddAxes(), and(), DrawSCPlanPlugIn(), get(), PlotPlanet(), QPose(), quaternion(), QUnit(), SailDefaultColors(), set(), and vector().
DrawSailCADModel()
function DrawSailCADModel (in g, in normal)
 The default sun direction is [1;0;0], for sails with the shiny surface
 on +X.
Form
 DrawSailCADModel( g, normal )
Inputs
 g        (:)      CAD model
 normal  (3,1)     Sail normal (the direction the sun should shine from)
References AddAxes(), and(), DrawSCPlanPlugIn(), get(), and set().
DrawSailFrames()
function DrawSailFrames (in qIToS, in cone, in clock)
 The normal is assumed along +X. Cone is a co-elevation angle measured from
 the +X axis. Clock is measured from the Y axis to the projection of the
 normal on the Y-Z plane.
 The reference frame is first rotated about +X by the clock angle and then
 the cone angle is achieved by rotating about the new Z axis. The is
 visualized using translucent angle arcs.
 The quaternion defines the inertial to reference frame quaternion. By
 including this transformation additional inertial vectors can be added
 to the plot.
 Since version 7.
Form
 DrawSailFrames( qIToS, cone, clock )
Inputs
 qIToS    (4,1)     Quaternion from inertial to reference frame
 cone     (1,1)     Cone angle (coelevation from X)
 clock    (1,1)     Clock angle (azimuth from reference Y)
Outputs
 None.
References AddAxes(), and(), AnglePatch(), Cone(), DrawSailFrames(), Eul2Mat(), isempty(), NewFig(), Q2Mat(), QTForm(), quaternion(), QZero(), and SailDefaultColors().
Referenced by DrawSailFrames().
DrawSailMeshVectors()
function DrawSailMeshVectors (in g, in uSun, in flux)
 Calls SolarPressureForce on the input CAD model. Only components of the
 sail class are drawn. Drag and planet effects are neglected.
 The sun vector should be in the neighborhood of the sail front body normal,
 pointing out from the shiny side of the sail. The mesh is shaded by the
 temperature.
 The function can also plot a mesh if the optical and thermal properties
 are passed in as well.
 Since version 7.
Form
 DrawSailMeshVectors( g, uSun, flux )
Inputs
 g       (:)       Sailcraft CAD model
                      OR
                   Mesh structure with fields: v, f, optical, and thermal
 uSun   (3,1)      Sun vector in the body frame
 flux   (1,1)      Solar flux in W/m2  * Optional, default is 1 AU
References and(), AnglePatch(), Cone(), Dot(), length(), Mag(), NewFig(), PolygonProps(), set(), SolarFlx(), SolarPressureForce(), Unit(), vector(), and zeros().
EarthGuidance()
function EarthGuidance (in ignoredArg, in x, in d, in env)
The sail front normal is assumed to be +X in the body frame. Can be called in batch. The available profiles are:
 1. Sun-pointing (sun)
 2. Constant force component along velocity vector (v)
 3. Constant rotation with respect to LVLH frame (lvlh)
 4. Edge-on (no solar pressure force, 'off')
 5. Optimal orbit energy, see PlanetOptimalTraj (sma)
 6. Inclination (inc)
 7. Fixed, pass in d.cone and d.clock and see ConeClockToU (fixed)
Pass in a method of -5 to get orbit lowering.
Form
 [q,cone,clock,u] = EarthGuidance( t, x, d, env )
Inputs
 t         (1,1)      Time, unused
 x         (6,n)      ECI state [r;v]
 d          (:)       Data structure
                       .method  (1,1)   Control method
 env        (:)       Environment struct
                       .uSun  (3,1)  Vector to sun
Outputs
 q        (4,n)       Inertial to body quaterion
 cone     (1,n)       Cone angle (rad)
 clock    (1,n)       Clock angle (rad)
 u        (3,n)       Sail normal vector in inertial frame
References abs(), and(), Cone(), Constant(), get(), QLVLH(), vector(), and zeros().
enhancederXover()
function enhancederXover (in p1, in p2, in bounds, in ops)
 enhanced  edge recombination crossover on permutation strings.
 Since version 7.
Form
 [c1,c2] = enhancederXover(p1,p2,bounds,ops)
Inputs
 p1              the first parent ( [solution string function value] )
 p2              the second parent ( [solution string function value] )
 bounds          the bounds matrix for the solution space
 ops             Options matrix for simple crossover [gen #SimpXovers].
Outputs
 c1
 c2
References and().
EnvironmentStruct()
function EnvironmentStruct (in d0)
 Will add the fields to an existing structure d0 if one is input.
 Since version 7.
Form
 d = EnvironmentStruct( d0 )
Inputs
 d0            (:)    Data structure, optional
Outputs
 d             (:)    Data structure with environment fields
References AtmDens2(), BDipole(), IsVersionAfter(), and SailEnvironment().
Referenced by FOrbitMultiSpacecraft(), InitializeSailSim(), and SailDisturbance().
er()
function er (in p1, in p2, in bounds, in ops)
 crossover on permutation strings.
 Since version 7.
Form
 [c1,c2] = er(p1,p2,bounds,ops)
Inputs
 p1              the first parent ( [solution string function value] )
 p2              the second parent ( [solution string function value] )
 bounds          the bounds matrix for the solution space
 ops             Options matrix for simple crossover [gen #SimpXovers].
Outputs
 c1
 c2
References and().
f2b()
function f2b (in fval, in bounds, in bits)
 Since version 7.
Form
 [bval] = f2b(fval,bounds,bits)
Inputs
 fval          the float representation of the number
 bounds        the bounds on the variables
 bits          the number of bits to represent each variable
Outputs
 bval          the binary representation of the number
References and().
Referenced by ga().
FCartOrbD()
function FCartOrbD (in x, in ignoredArg, in d)
Accepts a data structure
 input. See also FOrbCart.
Form
 xDot = FCartOrbD( x, t, d )
Inputs
 x              (6,1)  [r;v] (km and km/s)
 d              (1,1)  Velocity vector (km/s)
                       .mu  (1,1) Gravitational parameter (km^3/s^2)
                       .a   (3,1) Acceleration vector (km/s^2)
Outputs
 xDot           (6,1)  d[r;v]/dt (km/s and km/s^2)
References and(), FOrbCart(), Mag(), and vector().
FCoreAndMoving()
function FCoreAndMoving (in t, in x, in ignoredArg, in d)
 The orbit states have a zero derivative. Loops through the n bodies
 and performs attitude kinematics on each.
Form
 vargout = FCoreAndMoving( t, x, flag, d )
Inputs
 t                      Time (s)
 x             (:,1)    The state vector, [r;v;q;w;...]
 flag          (1,:)    Flags for ode113 (unused)
 d             (1,1)    Data structure for FMovingBody
                         .g
                         .force
                         .torque
Outputs
 xDot          (:,1)     The state vector derivative
References and(), FMovingBody(), QIToBDot(), RHS(), RK4(), RK45(), and vector().
Referenced by FMovingBody().
FHingeOrbit()
function FHingeOrbit (in x, in t, in f, in tq, in d)
 Assumes two bodies with a single rotational hinge and no translation.
 FMovingBody must be called with new rates before this function is
 integrated. Designed to be called in a discrete integration with RK4.
Form
 xDot = FHingeOrbit( x, t, f, tq, d )
Inputs
 x             (26,1)   The state vector [ [r;v;q;w](0);  [r;v;q;w](1) ]
 t             (1,1)    Time
 f             (:)      Force structure
 tq            (:)      Torque structure
 d             (1,1)    Data structure
                        .g     (1,1) CAD model
                        .mu    (1,1) Gravitational constant
Outputs
 xDot          (26,1)  [ [rDot;vDot;...] [rDot;vDot;...] ]
References and(), FMovingBody(), FOrbCart(), RK4(), vector(), and zeros().
FixedPitchControl()
function FixedPitchControl (in z, in rho, in nu, in eta)
Form
 dGamma = FixedPitchControl( z, rho, nu, eta )
Inputs
 rho           (1,1)    Target radius
 z             (1,1)    Target out of plane displacement
 nu            (1,1)    Displacement in rho direction
 eta           (1,1)    Displacement in z direction
Outputs
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999, p. 193
 Since version 7.
References McInnes().
FLambdaToConeClock()
function FLambdaToConeClock (in alpha, in d)
Designed to be called by fzero.
Form
 f = FLambdaToConeClock( alpha, d )
Inputs
 alpha      (1,1)  Cone angle (rad)
 d           (.)   Data structure
                   .s     (1,1) Dot product of sun vector and (gm)'
                   .y     (1,1) Dot product of y vector and (gm)'
                   .z     (1,1) Dot product of z vector and (gm)'
                   .rhoS  (1,1) Specular reflection coefficent
                   .rhoR  (1,1) Thermal and diffuse coefficient
                   .rhoAD (1,1) Sum of diffuse and absorption coefficient
                   .cB    (1,1) Cosine of clock angle
                   .sB    (1,1) Sine of clock angle
Outputs
 f          (1,1)   Value of the rhs
References and(), Cone(), Dot(), and vector().
Referenced by LambdaToConeClock3D().
FMovingBody()
function FMovingBody (in t, in x, in force, in torque, in d)
 Returns the derivative of just the attitude states. Must be combined with an
 orbit derivative function for a full state derivative.
See also
FCoreAndMoving.
Form
 xDot = FMovingBody( t, x, force, torque, d )
 xNew = FMovingBody( 'init', xOld, xRates, torque, d )
Inputs
 t             (1,1)    Time
 x             (13n,1)  The state vector [r;v;q;omega;...]
 force         (:)      Force structure
 torque        (:)      Torque structure
 d             (1,1)    Data structure
                        .g     (1,1) CAD model
Outputs
 xDot          (6n,1)  [qDot;omegaDot;...]
 h
References and(), BHinge(), Cross(), FCoreAndMoving(), Initialize(), length(), QIToBDot(), Rename(), RK4(), RK45(), Skew(), SkewSq(), vector(), and zeros().
Referenced by FCoreAndMoving(), FHingeOrbit(), and FSailCombined().
FOrbitGeneral()
function FOrbitGeneral (in t, in x, in rBodies, in center, in jD, in aExt)
This function has persistent memory and should be cleared between implementations. The stored planets can be checked using 'planets'. When loading a simple list of mu's for major planets (including the sun), numeric ids and vector inputs can be used. See PlanetPosJPL. Designed for use with ode113. See also AsteroidOrbitDemo.
 Forms:
 FOrbitGeneral( 'add', planetName, d, nZ, nT )
 FOrbitGeneral( 'add', ids, mu )
 planets = FOrbitGeneral( 'planets' )
 xDot = FOrbitGeneral( t, x, rBodies, center, jD, aExt )
Inputs
 t             (1,1)     Time
 x             (6,1)     State vector [r;v]
 rBodies       (3,n)     Positions of bodies in same frame as x
 center        (1,1)     ID of center in stored list
 jD            (1,1)     Julian Date of epoch
 aExt          (3,1)     Additional external acceleration
 When data is entered on an 'add' call:
 planet (:)    Planet name string
 d      (:)    Gravity model structure, or mu for point mass model
 s     (k,k)   S terms  s(n,m) where n and m are degree and order of the model
 c     (k,k)   C terms  c(n,m)
 j     (k)     m = 0 terms
 mu    (1,1)   Spherical gravitational potential
 a     (1,1)   Planet radius
 nZ    (1,1)   Highest zonal harmonic (m = 0)
 nT    (1,1)   Highest sectorial and tesseral harmonic
 d may also be a number
Outputs
 xDot         (6,1)      State derivative
References and(), PlanetPosJPL(), and vector().
Referenced by FSailCombined(), and InitializeSailGravity().
FOrbitSingle()
function FOrbitSingle (in t, in x, in rBodies, in center, in jD, in aExt)
 This function has persistent memory and will use the last planet loaded.
 The stored planet can be checked using 'planets'. The sun id is 0, the
 moon id is 10, and the major planets have id's 1 to 9.
 Designed for use with ode113. See also SailCombinedDemo, SPICombinedDemo.
 Since version 7.
 Forms:
 FOrbitSingle( 'add', planetName, d, nZ, nT )
 FOrbitSingle( 'add', id, mu )
 planet = FOrbitSingle( 'planets' )
 xDot = FOrbitSingle( t, x, rBodies, center, jD, aExt )
Inputs
 t             (1,1)     Time
 x             (6,1)     State vector [r;v]
 rBodies         ()      Unused
 center          ()      Unused
 jD            (1,1)     Julian Date of epoch
 aExt          (3,1)     Additional external acceleration
 When data is entered on an 'add' call:
 planet (:)    Planet name string
 d      (:)    Gravity model structure, or mu for point mass model
 s     (k,k)   S terms  s(n,m) where n and m are degree and order of the model
 c     (k,k)   C terms  c(n,m)
 j     (k)     m = 0 terms
 mu    (1,1)   Spherical gravitational potential
 a     (1,1)   Planet radius
 isNormalized (1)
 nZ    (1,1)   Highest zonal harmonic (m = 0)
 nT    (1,1)   Highest sectorial and tesseral harmonic
 d may also be a number
Outputs
 xDot         (6,1)      State derivative
 planet        {1}       Cell array with planet name
References and(), and vector().
Referenced by FSailCombined(), and InitializeSailGravity().
FPlanetControl()
function FPlanetControl (in t, in x, in theta, in accel, in x0, in k)
 Theta is uncontrolled.
See also
FRotatingPlanet.
Form
 xDot = FPlanetControl( t, x, theta, accel, x0, k )
Inputs
 t                (1,1) Time
 x                (6,1) state [rho;theta;z;drho/dt;dtheta/dt;dz/dt]
 theta            (1,1) Sail nominal angle
 accel            (1,1) Sail acceleration
 x0               (2,1) Desired rho and z coordinates
 k                (1,4) Control gains [rho;z;drho;dz]
Outputs
 xDot             (6,1) state derivative
References abs(), and(), FRotatingPlanet(), and RHS().
FractionalSelection()
function FractionalSelection (in oldPop, in opts)
Ranking is the product of fitness normalized by max fitness (least cost) and random weights.
The user supplies the option fracDelete. The first option, iGen, is provided by the genetic algorithm.
Form
 newPop = FractionalSelection( oldPop, opts )
Inputs
oldPop (n,m+1) Original population, last column is fitness opts (2) Options, [iGen fracDelete]
Outputs
newPop (n,m+1) New population
References and().
FRotatingFrame()
function FRotatingFrame (in s, in t, in d)
 The frame's origin is the barycenter of the frame. The x-axis is
 positive from the barycenter to m1 and the distance between the bodies
 is 1.
Form
 sDot = FRotatingFrame( s, t, d )
Inputs
 s       (6,1)     Cartesian state
 t       (1,1)     Time
 d        (.)      Data structure
                   .kappa  (1,1)  Mass ratio, m2/(m1+m2)
                   .accel  (1,1)  Sail characteristic acceleration
Outputs
 sDot   (6,1)      Derivative of state
FRotatingLagrange()
function FRotatingLagrange (in t, in s, in d)
 The sail normal is always directed along the Sun-line. The state is the
 perturbation from the Lagrange point. This is a linearization.
See also
LunarHalo.
Form
 xDot = FRotatingLagrange( t, s, d )
Inputs
 t                (1,1) Time
 s                (6,1) State [x;y;z;dx/dt;dy/dt;dz/dt]
 d                 (.)  Structure
                         .theta   (1,1) Sail control angle
                         .accel   (1,1) Sail acceleration
                         .xL      (1,1) Coordinate of Lagrange point in corotating frame
                         .wS      (1,1) Rate of rotation of the sun vector
                         .mu      (1,1) System gravity parameter, m2/(m1+m2)
                         .control (1,1) Control flag
                         .r0      (1,3) Desired offsets
                         .linear  (1,1) Flag for linearized form
Outputs
 xDot             (6,1) state derivative
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999.
References abs(), Constant(), LunarHalo(), Mag(), McInnes(), Normal(), RHS(), and vector().
FRotatingPlanet()
function FRotatingPlanet (in ignoredArg, in x, in theta, in accel)
 The equations are nondimensionalized.
See also
SphOrb and FOrb.
 Since version 7.
Form
 xDot = FRotatingPlanet( t, x, theta, accel )
Inputs
 t                (1,1) Time
 x                (6,1) state [rho;theta;z;drho/dt;dtheta/dt;dz/dt]
 theta            (1,1) Sail control angle
 accel            (1,1) Sail acceleration
Outputs
 xDot             (6,1) state derivative
Reference: Colin McInnes, Solar Sailing, Springer-Praxis 1999.
References and(), FOrb(), McInnes(), Normal(), RHS(), SphOrb(), and vector().
Referenced by FPlanetControl().
FRotatingSun()
function FRotatingSun (in ignoredArg, in x, in theta, in beta, in control)
The equations are nondimensionalized. Sail angle control is included. Either sail pitch (angle fron the sun vector) or elevation from the ecliptic plane may be held constant.
See also
SphOrb and FOrb.
Form
 xDot = FRotatingSun( t, x, theta, beta, control )
Inputs
 t                (1,1) Time
 x                (6,1) state [rho;theta;z;drho/dt;dtheta/dt;dz/dt]
 theta            (1,1) Sail control angle
 beta             (1,1) Sail lightness number
 control          (1,1) Control type: (1) pitch angle (2) elevation
Outputs
 xDot             (6,1) state derivative
References and(), FOrb(), Normal(), SphOrb(), and vector().
FS4Deployment()
function FS4Deployment (in t, in x, in force, in ignoredArg, in d)
 Includes force and torque model which scale as area increases.
 In the state vector inertia is in columns
Form
 [xDot] = FS4Deployment( t, x, force, torque, d )
Inputs
 t             (1,1)    Time
 x             (13,1)   The state vector [r;v;q;omega;inertia]
 force         (:)      Force structure
                         .total   (3,1,2) Total torque on the vehicle
 torque        (:)      Torque structure (not used)
                         .total   (3,1,2) Total torque on the vehicle
 d             (1,1)    Data structure
                         .LDot (1,1) Deployment rate
Outputs
 xDot          (7+2n,1)  [qDot;omegaDot;aDot;aDDot]
 h             (3,1)     Inertial angular momentum in the body frame
 gIner         (3+n,3+n) Generalized inertia matrix
Reference: (Student Paper) Attitude Dynamics and Stability of Solar Sails During Deployment. LeFevre and Jha
 Since version 7.
References and(), IDotS4(), QIToBDot(), vector(), and zeros().
FSailCombined()
function FSailCombined (in t, in x, in p, in d)
Calls all needed portions in order.
 The state should contain at a minimum 10 states for [r;v;q], even if
 some are placeholders of 0. After a simulation, call it with multiple
 outputs to post-process the state.
 The portions are below. To use a default pass an empty matrix.
 1. d.ephemeris - default is SailEphemAlmanac, comparable is SailEphemJPL
 2. d.environment - default is SailEnvironment
 3. d.disturbance - default is SailDisturbance
 4. d.attitude - default dynamics is FSailRB, see also FMovingBody
 5. d.guidance - can be used to override attitude dynamics
 6. d.orbit - default is FOrbitGeneral, see also FOrbitSingle
 Also available embedded in this function are NoEphemeris, NoEnvironment,
 NoDisturbance, NoAttitude, and NoOrbit, which can be used to skip any portion.
 There is no default guidance function - you must specify one to override
 the attitude dynamics. Guidance will assume that the attitude is in states
 7 through 10. The function StoredDisturbance enables you to pass a stored
 force structure f and torque structure tq through d.
 The function formats are:
 rB  = FEphemeris( jD, d )
 env = FEnvironment( planet, p, d )
 [f, tq] = FDisturbance( g, p, env, d )
 xADot = FAttitude( t, x, f, tq, d )  OR   q = FGuidance( t, x, d, env )
 xODot = FOrbit( t, x, rB, center, jD, accel )
 planets = FOrbit( 'planets' )
 The resulting derivative is [xODot;xADot]
 Calling this function with no inputs will return a default data structure
 with empty matrices for each field.
 Forms:
 xDot = FSailCombined( t, x, p, d )
 d = FSailCombined()
 [p, env, f, tq, planets] = FSailCombined( t, x, p, d )
Inputs
 t             (1,1)    Time in seconds from jD0 epoch
 x             (n,1)    The state vector, at least [r;v;q;w]
 p              (.)     Profile data structure (angle, axis, body)
 d              (.)     Data structure. The following fields are required:
   .jD0, default is JD2000
   .kP, ids of gravitational bodies
   .center, defaults to 1 (1st planet in list)
   .g, CAD model, need at least mass structure, defaults to 1 kg
Outputs
 xDot          (n,1)    State derivative
See also
SailCombinedDemo.
References and(), AssignFHandle(), FMovingBody(), FOrbitGeneral(), FOrbitSingle(), FSailRB(), isempty(), JD2000(), length(), SailDisturbance(), SailEnvironment(), SailEphemAlmanac(), SailEphemJPL(), vector(), and zeros().
Referenced by InitializeSailSim(), SailEphemAlmanac(), SailEphemEarth(), and SailEphemJPL().
FSailEarthMoon()
function FSailEarthMoon (in t, in x, in ignoredArg, in d)
 Includes a point mass sun model. Uses MoonV1 and SunV1 for ephemeris.
 Designed to be called by ode113. See also EarthMoonSunSim.
Form
 varargout = FSailEarthMoon( t, x, flag, d )
Inputs
 t                      Time (sec)
 x             (:,1)    The state vector [r;v]
 d             (1,1)    Data structure
                        .earth (.)
                                   .mu (1.1) Gravitational constant
                        .moon  (.)
                                   .mu (1.1) Gravitational constant
                        .jDStart (1,1) Initial Julian date
                        .accel (1,1) Sail characteristic acceleration (km/s2)
Outputs
 vargout          (:,:)     Depends on flag
References and(), Constant(), Cross(), Date2JD(), FEarthMoonSun(), isempty(), length(), Mag(), MoonV1(), RK4(), RVFromKepler(), SunV1(), Unit(), and vector().
FSailEarthSun()
function FSailEarthSun (in t, in x, in flag, in d)
 Uses SunV1 for ephemeris.
 Designed to be called by ode113.
Form
 varargout = FSailEarthSun( t, x, flag, d )
Inputs
 t                      Time (sec)
 x             (:,1)    The state vector [r;v]
 d             (1,1)    Data structure
                        .earth (.)
                                   .mu (1.1) Gravitational constant
                        .moon  (.)
                                   .mu (1.1) Gravitational constant
                        .jDStart (1,1) Initial Julian date
                        .accel (1,1) Sail characteristic acceleration (km/s2)
Outputs
 vargout          (:,:)     Depends on flag
References and(), Cone(), Constant(), Date2JD(), FEarthMoonSun(), length(), Mag(), RK4(), SunV1(), and vector().
FSailGuidance()
function FSailGuidance (in t, in x, in a0, in cone, in clock, in mu, in d)
 Point mass gravity model. Calls AnglesMcInnesToU and, optionally,
 LocallyOptimalTraj for guidance. Assumes a heliocentric orbit.
 The default mu is the Sun. Can be called from RK45 or ode113.
Form
 xDot = FSailGuidance( t, x, a0, cone, clock, mu, d )
 xDot = FSailGuidance( x, t, a0, cone, clock, mu, d )  RK45 format
Inputs
 t          (1,1)  Time
 x          (6,1)  States [r;v]
 a0         (1,1)  Characteristic acceleration
 cone       (1,1)  Cone angle
 clock      (1,1)  Clock angle
 mu         (1,1)  Gravitational constant
 d           (:)   Optional data structure for LocallyOptimalTraj.
                    .type     (:)  string name of type
                    .dirFlag (1,1) Either +/-1
Outputs
 xDot       (6,1)   State derivatives d[r;v]/dt
References and(), AnglesMcInnesToU(), Cone(), isempty(), LocallyOptimalTraj(), McInnes(), RK4(), and RK45().
FSailRB()
function FSailRB (in t, in x, in ignoredArg, in torque, in d)
 The state is assumed to begin with [r;v;q;w]
Form
 xADot = FSailRB( t, x, force, torque, d )
Inputs
 t             (1,1)    Time
 x             (13,1)   The state vector [r;v;q;w]
 force         (:)      Force structure
                         .total   (3,1) Total force on the vehicle
 torque        (:)      Torque structure
                         .total   (3,1) Total torque on the vehicle
 d             (1,1)   Data structure
                         .inr     (3,3) Inertia
                         .invInr  (3,3) Inverse inertia
Outputs
 xADot         (7,1)     The derivative of the attitude state vector
References FRB(), and vector().
Referenced by FSailCombined(), and InitializeSailSim().
FSailTB()
function FSailTB (in t, in x, in force, in torque, in d)
 The state is assumed to begin with [r;v;q0;w0;q1;w1]
Form
 xDot = FSailTB( t, x, force, torque, d )
Inputs
 t             (1,1)    Time
 x             (20,1)   The state vector [r;v;q1;w1;q2;w2]
 force         (:)      Force structure
                         .totalBody   (3,1,2) Total force on each body
 torque        (:)      Torque structure
                         .total   (3,1) Total torque on the vehicle
 d             (1,1)    Data structure
                        .r0          (3,1)  The vector from the origin to the body 0 cm in the body 0 frame
                        .r1          (3,1)  The vector from the origin to the hinge in the body 0 frame
                        .lam1        (3,1)  The vector from the hinge to the body 1 cm in the body 1 frame
                        .iner0       (3,3)  The body 0 inertia in the body 0 frame
                        .iner1       (3,3)  The body 1 inertia in the body 1 frame
                        .m0          (1,1)  The body 0 mass
                        .m1          (1,1)  The body 1 mass
                        .hingeTorque (3,1) Torque at hinge
                        .iAxis       (1,1) Axis index
   iAxis   (1,:)     The axes of the second body that are not constrained.
   hingeTorque
Outputs
 xADot         (14,1)     The derivative of the attitude state vector
References and(), DefaultDataStructure(), FTB(), length(), and vector().
FSolarSailAngles()
function FSolarSailAngles (in x, in d)
Form
 f = FSolarSailAngles( x, d )
Inputs
 x             (2,1)   Sail angles [alpha;beta]
 d             (1,1)   Data structure
                       .rhoEps (1,1) Thermal plus diffuse
                       .rhoS   (1,1) Specular coefficient
                       .rhoDA  (1,1) Diffuse + absorption
                       .e      (3,1) Lambda
Outputs
 x             (:,1)   The solution
 err           (:,1)   The errors
 n             (1,1)   Number of iterations
References plus(), RHS(), and zeros().
FTimeVaryingI()
function FTimeVaryingI (in t, in x, in ignoredArg, in torque, in d)
 Computes dynamics and kinematics for q, w, and I.
Form
 xDot = FTimeVaryingI( t, x, ~, torque, d )
Inputs
 t             (1,1)    Time
 x             (24,1)   The state vector [r;v;q;w;I]
 force         (:)      Force structure (not used)
                         .total   (3,1) Total force on the vehicle
 torque        (:)      Torque structure
                         .total   (3,1) Total torque on the vehicle
 d             (1,1)    Data structure
                         .fInertia (:)  Function providing Idot, f( t, d )
                                        where Idot is in 3x3 matrix form
Outputs
 xDot          (18,1)  [qDot;omegaDot;IDot]
References and(), isempty(), QIToBDot(), RHS(), Skew(), vector(), and zeros().
ga()
function ga (in bounds, in evalFN, in evalOps, in startPop, in opts, in)
 Since version 7.
Form
 [x,endPop,bPop,traceInfo]=ga(bounds,evalFN,evalOps,startPop,opts,
 termFN,termOps,selectFN,selectOps,
 xOverFNs,xOverOps,mutFNs,mutOps)
Inputs
 bounds         a matrix of upper and lower bounds on the variables
 evalFN         the name of the evaluation .m function
 evalOps        options to pass to the evaluation function ([NULL])
 startPop       a matrix of solutions that can be initialized
                from initialize.m
 opts           [epsilon prob_ops display] change required to consider two
                solutions different, prob_ops 0 if you want to apply the
                genetic operators probabilisticly to each solution, 1 if
                you are supplying a deterministic number of operator
                applications and display is 1 to output progress 0 for
                quiet. ([1e-6 1 0])
 termFN         name of the .m termination function (['maxGenTerm'])
 termOps        options string to be passed to the termination function
                ([100]).
 selectFN       name of the .m selection function (['normGeomSelect'])
 selectOpts     options string to be passed to select after
                select(pop,#,opts) ([0.08])
 xOverFNS       a string containing blank seperated names of Xover.m
                files (['arithXover heuristicXover simpleXover'])
 xOverOps       A matrix of options to pass to Xover.m files with the
                first column being the number of that xOver to perform
                similiarly for mutation ([2 0;2 3;2 0])
 mutFNs         a string containing blank seperated names of mutation.m
                files (['boundaryMutation multiNonUnifMutation ...
                         nonUnifMutation unifMutation'])
 mutOps         A matrix of options to pass to Xover.m files with the
                first column being the number of that xOver to perform
                similiarly for mutation ([4 0 0;6 100 3;4 100 3;4 0 0])
Outputs
 x              the best solution found during the course of the run
 endPop         the final population
 bPop           a trace of the best population
 traceInfo      a matrix of best and means of the ga for each generation
References abs(), and(), arithXover(), b2f(), calcbits(), f2b(), ga(), heuristicXover(), initializega(), isempty(), maxGenTerm(), multiNonUnifMutation(), normGeomSelect(), parse(), Selection(), simpleXover(), and zeros().
Referenced by ga(), and initializega().
gaDemo1Eval()
function gaDemo1Eval (in sol, in options)
 f(x)=x+10sin(5x)+7cos(4x)
 Since version 7.
Form
 [sol, val] = gaDemo1Eval(sol,options)
Inputs
 sol         the individual, returned to allow for Lamarckian evolution
 options     [current_generation]
Outputs
 sol         the individual, returned to allow for Lamarckian evolution
 val         the fittness of this individual
References and().
GAMin()
function GAMin (in fun, in x, in d, in s)
The initial state is xand d is a data structure containing tuning parameters. Uses an elitist model and terminates after a set number of generations.
Form
 [x, fBest, fPlot] = GAMin( fun, x, d, s )
 where:
 errMag = fun( x, d )
Inputs
 fun       (1,:)  Cost function name or handle
 x         (m,1)  Initial state
 d         (1,1)  Data structure to pass to fun
 s          (.)   Data structure for genetic algorithm
                  .nI           (1,1)  Number of individuals
                  .nG           (1,1)  Number of generations
                  .bounds       (n,2)  Variable bounds, rows of [min max]
                  .fncMutate     (:)   Function for mutations
                  .optMutate    (1,:)  Options for mutation function
                  .fncSelect     (:)   Function for selection
                  .optSelect    (1,:)  Options for selection function
                  .fncXOver      (:)   Function for cross-overs
                  .optXOver     (1,:)  Options for cross-over function
Outputs
 x          (m,1)  Best state
 fBest      (1,1)  Best (lowest) cost
 fPlot      (1,:)  Cost vs. generation
References and(), Cross(), Demo(), GAMin(), get(), heuristicXover(), Initialize(), IsVersionAfter(), length(), normGeomSelect(), OptTestFunParabola(), Plot2D(), Selection(), set(), and zeros().
Referenced by GAMin().
gaZBGradEval()
function gaZBGradEval (in sol, in options)
 options(3) is the percent of time to perform the gradient heuristic to
 the potential solution
 options(4) is the percentage of time to update the solution based on
 the outcome of the gradient heuristic
 Since version 7.
Form
 [nsol, val] = gaZBGradEval(sol,options)
Inputs
 sol
 options
Outputs
 nsol
 val
References and(), gaZBGrad(), and gaZBGradEval().
Referenced by gaZBGradEval().
GeneticAlgorithm()
function GeneticAlgorithm (in fun, in x, in d, in s)
 The initial state is x and d is a data structure containing tuning
 parameters. This function is specifically designed to minimize functions
 of real numbers.
 Since version 7.
Form
 [x, fBest, fPlot] = GeneticAlgorithm( fun, x, d )
Inputs
 fun            (1,:)  Function name
 x              (m,1)  Initial state
 d              (1,1)  Data structure to pass to fun
 s              (1,1)  Data structure
                       .n            (1,1) Number of individuals
                       .nG           (1,1) Number of generations
                       .dX           (m,1) Maximum delta state
                       .fracMutation (1,1) Fraction of initial x for
                       mutations
                       .probMutation (1,1) Probability of a mutation
                       .probCrossover(1,1) Probability of a crossover
Outputs
 x              (m,1)  Best state
 fBest          (1,1)  Best cost
 fPlot          (1,:)  Cost vs. generation
Reference: Sipper, M., "A Brief Introduction to Genetic Algorithms," http://www.cs.bgu.ac.il/~sipper/ga.html
References and(), Demo(), GeneticAlgorithm(), length(), Odd(), and OptTestFunRosenbrock().
Referenced by GeneticAlgorithm().
GeoOptimalMission()
function GeoOptimalMission (in el0, in jD0, in nDays)
 This uses the control laws developed in McInnes.
 Functions demonstrated:
 PlanetOptimalTraj
 Eclipses are not modeled but the accurate sun angle is obtained from SunV1.
 The RHS function FPitch is embedded below for use with ode113. It uses
 FOrbCart for the orbit dynamics.
 Since version 7.
Form
 [xPlot, t] = GeoOptimalMission( el0, jD0, nDays )
Inputs
 el0      (6,1)     Initial Keplerian orbital elements
 jD0      (1,1)     Epoch, Julian date
 nDays    (1,1)     Number of days to simulate
Outputs
 xPlot
 t
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999, pp. 156-158, Sec. 4.4.2.3, "Locally Optimal Steering - Planet-Centered Orbits"
References and(), close(), Cone(), Constant(), Cross(), Demo(), El2RV(), FOrbCart(), GeoOptimalMission(), InformDlg(), length(), McInnes(), NewFig(), PlanetOptimalTraj(), Plot2D(), RHS(), RV2El(), RVFromKepler(), SailPropsToAccel(), square(), SunV1(), Unit(), and zeros().
Referenced by GeoOptimalMission().
GeoSwitchingMission()
function GeoSwitchingMission (in el0, in jD0, in nDays)
This uses the control laws developed in McInnes. The sail is turned "off" during half the orbit by placing it edge-on to the sun, or at a pitch angle of 90 degrees. Models solar pressure only, without planetary influences. Eclipses are modeled.
Functions demonstrated:
 PlanetOptimalTraj
Form
 [xPlot, t] = GeoSwitchingMission( el0, jD0, nDays )
Inputs
 el0      (6,1)     Initial Keplerian orbital elements
 jD0      (1,1)     Epoch, Julian date
 nDays    (1,1)     Number of days to simulate
Outputs
 xPlot
 t
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999, pp. 156-158, Sec. 4.4.2.3, "Locally Optimal Steering - Planet-Centered Orbits"
References and(), close(), Cone(), Constant(), Demo(), El2RV(), GeoSwitchingMission(), get(), InformDlg(), length(), McInnes(), NewFig(), Period(), PlanetOptimalTraj(), RV2El(), SailPropsToAccel(), SailSMAChange(), square(), and zeros().
Referenced by GeoSwitchingMission().
GimbalRates()
function GimbalRates (in angle, in angleCommand, in rateNom, in dT, in zeroTorque)
 Determines optimal angles and direction for minimum angular travel.
 Designed for a 12 gimbal sequence (from core to rotated body).
Form
 [rate,angleCommand] = GimbalRates( angle, angleCommand, rateNom, dT )
Inputs
 angle        (2,1)   Current gimbal angles
 angleCommand (2,1)   New angle command  (outer, inner)
 rateNom      (2,1)   Nominal gimbal rates
 dT           (1,1)   Discrete time interval
 zeroTorque   (1,1)   Flag to move inner gimbal first to prevent torques
Outputs
 rate         (2,1)   Gimbal rates
 angleCommand (2,1)   Updated angle commands
References abs(), and(), Mag(), set(), and WrapPhase().
GravityUnitsConverter()
function GravityUnitsConverter (in mu, in dist, in time)
 Possible output units are au^3/sec^2, au^3/day^2,
 m^3/sec^3 or m^3/day^2.
 Type GravityUnitsConverter for a demo.
Form
 mu = GravityUnitsConverter( mu, dist, time )
Inputs
 mu            (1,1)    Gravitational constant in km^3/sec^2
 dist          (1,:)    Either 'au' or 'm'
 time          (1,1)    Either 'days' or 'sec'
Outputs
 mu            (1,1)    Gravitational constant in units^3/sec^2
References Constant(), Demo(), and GravityUnitsConverter().
Referenced by GravityUnitsConverter().
HCircularBillow()
function HCircularBillow (in x, in y, in d)
Form
 h = HCircularBillow( x, y, d )
Inputs
 x       (1,m)      x position
 y       (1,m)      y position
 d        (:)       Data structure
                    .b   (1,1)   Surface slope at outer edge
                    .r   (1,1)   Sail radius
Outputs
 h       (1,m)
Reference: Generalized Models for Solar Sails, L. Rios-Reyes and D. J. Scheeres, AAS 04-286
References and(), and isempty().
Referenced by SailMesh().
HeliopauseSailAngle()
function HeliopauseSailAngle (in ignoredArg, in t)
The sail must have a high enough acceleration for this single-pass method to work.
Form
 angle = HeliopauseSailAngle( x, t )
Inputs
 x          (:,:)  States
 t          (1,:)  TIme
Outputs
 angle      (1,:)  Sail in plane angle (rad)
Reference: http://en.wikipedia.org/wiki/Fast_solar_sailing
References get(), length(), and zeros().
heuristicXover()
function heuristicXover (in p1, in p2, in bounds, in Ops, in seed)
 along the line formed by the two parents outward in the direction of the
 better parent.
 Since version 7.
Form
 [c1,c2] = heuristicXover(p1,p2,bounds,Ops,seed)
Inputs
 p1            the first parent ( [solution string function value] )
 p2            the second parent ( [solution string function value] )
 bounds        the bounds matrix for the solution space
 Ops           heuristic crossover, [gen #heurXovers number_of_retries]
 seed          optional seed for random numbers, for testing
Outputs
 c1
 c2
References and().
Referenced by ga(), and GAMin().
HGimballedBoom()
function HGimballedBoom (in x, in g, in axis, in aDotNew, in hW)
Form
 [hI, hW] = HGimballedBoom( x, g, axis, aDotNew, hW )
Inputs
 x             (17,1)   The state vector [r;v;q;omega;a;aDot]
 g             (1,1)    CAD model
 axis          (3,2)    Rotation axes of gimbals
 aDotNew       (2,1)    New gimbal rates
 hW            (3,1)    Stored angular momentum
Outputs
 hI            (3,1)    Inertial angular momentum
 hW            (3,1)    Updated stored momentum
References and(), HingeRotationMatrix(), and vector().
HingeRotationMatrix()
function HingeRotationMatrix (in angle, in axis)
 The angle vector goes from unrotated body to rotated and the
 transformation matrix is from unrotated frame to rotated frame.
 axis is a 3-by-n array of rotation axes
 that corresponds to the axis of rotation for each angle. For example
 if there are two rotations the transformation matrix will be
 u_rotated_frame = b(angle(2))*b(angle(1))*u_unrotated_frame
 This function is similar to BHinge.m except that it does not use
 the bHinge data structure and only handles axis, angle pairs.
 Since version 7.
Form
 [bT, bH] =  = HingeRotationMatrix( angle, axis )
Inputs
 angle          (1,:)  Angles
 axis           (3,:)  Axes in columns
Outputs
 bT             (3,3)  Transformation matrix from unrotated to rotated frame
 bH              {:}   Matrix for each rotation in the set
References and(), BHinge(), and vector().
Referenced by HGimballedBoom(), MassVehicle(), and TwoBodyRateModel().
HQuadrantBillow()
function HQuadrantBillow (in x, in y, in data)
 Linear billow displacement along center of quadrant from inside corner to
 outside edge. Quadratic billow along this reference line.
 Since version 7.
Form
 z = HQuadrantBillow( x, y, data )
Inputs
 x       (1,m)      x position
 y       (1,m)      y position
 data     (:)       Data structure
                    .b    % billow depth (fraction of boom length)
                    .L    % length along boom
Outputs
 z       (1,m)
References abs(), length(), Quadratic(), and zeros().
HRakoczy()
function HRakoczy (in x, in y, in d)
 The deflection increases radially from the center to the corners.
 The center of the sail is at h = 0.
Form
 h = HRakoczy( x, y, d )
Inputs
 x       (1,m)      x position
 y       (1,m)      y position
 d        (:)       Data structure
                    .p   (1,1)   Percentage billow (ex. 0.01)
                    .L   (1,1)   Sail diagonal length (m)
Outputs
 h       (1,m)      Out-of-plane position of points
Reference: John Rakoczy, NASA MSFC
References isempty(), length(), and square().
IDotS4()
function IDotS4 (in t, in d)
 This function has a built-in demo.
Form
 Idot = IDotS4( t, d )
Inputs
 t                 (1,1)  Time
 d                  (.)   Data structure
                           .LDot (1,1) Speed of deployment
Outputs
 Idot              (3,3)   Inertia derivative
Reference: (Student Paper) Attitude Dynamics and Stability of Solar Sails During Deployment. LeFevre and Jha
References and(), Demo(), IDotS4(), length(), Plot2D(), and zeros().
Referenced by FS4Deployment(), and IDotS4().
initializega()
function initializega (in num, in bounds, in evalFN, in evalOps, in options)
 equal to the populationSize and a number columns equal to the number
 of rows in bounds plus 1 for the f(x) value which is found by applying
 the evalFN.This is used by the ga to create the population if it
 is not supplied.
 Since version 7.
Form
 [pop] = initializega(num, bounds, evalFN,evalOps,options)
Inputs
 num       the size of the population, i.e. the number to create
 bounds    a matrix which contains the bounds of each variable, i.e.
           var1_high var1_low; var2_high var2_low; ....]
 evalFN    the evaluation fn, usually the name of the .m file for
           evaluation
 evalOps   any options to be passed to the eval function defaults []
 options   options to the initialize function, ie. [type prec] where
           eps is the epsilon value and the second option is 1 for
           float and 0 for binary, prec is the precision of the
           variables defaults [1e-6 1]
Outputs
 pop       the initial, evaluated, random population
References and(), ga(), and plus().
Referenced by ga().
initializeoga()
function initializeoga (in num, in bounds, in evalFN, in evalOps, in options)
 of rows equal to the populationSize and a number columns equal to the
 size of the permutation plus 1 for the f(x) value which is found by
 applying the evalFN. This initization function is used with an
 order-based representation.
 Since version 7.
Form
 [pop] = initializeoga(num,bounds,evalFN,evalOps,options)
Inputs
 num       the size of the population, i.e. the number to create
 bounds    the number of permutations in an individual (e.g., number
           of cities in a tsp
 evalFN    the evaluation fn, usually the name of the .m file for
           evaluation
 evalOps   any options to be passed to the eval function defaults []
 options   options to the initialize function, ie. [eps float/binary
           prec] where eps is the epsilon value and the second option
           is 1 for orderOps, prec is the precision of the variables
           defaults [1e-6 1]
Outputs
 pop       the initial, evaluated, random population
References and(), plus(), and tsp().
InitializeSailGravity()
function InitializeSailGravity (in d, in bodyNames, in models, in nZ, in nT, in ids)
Clears the necessary functions and sets up data consistently. Uses FOrbitSingle or FOrbitGeneral, along with the appropriate ephemeris function.
 Forms:
 d = InitializeSailGravity( d, bodyNames, models, nZ, nT, ids )
 d = InitializeSailGravity( d, 'earth', mu )
Inputs
 d         (:)    Initial simulation struct
 bodyNames {n}    Body names, with the first being the center
 models    {n}    Cell array of model names, or gravitational constants,
                    or harmonic model structs
 nZ       (1,n)   Number of zonal harmonics
 nT       (1,n)   Number of tesseral harmonics
 ids      (p,1)   Additional planets IDs to add as point sources
Outputs
 d         (:)    Simulation struct with gravity fields added
References and(), FOrbitGeneral(), FOrbitSingle(), and Initialize().
InitializeSailSim()
function InitializeSailSim (in jD, in cadModel, in guidance)
Clears the necessary functions and sets up data consistently. Uses SailDisturbance, SailEnvironment
Form
 [d,p] = InitializeSailSim( jD, cadModel, guidance )
Inputs
 jD        (1,1)  Epoch
 cadModel  (:)    name of CAD model or data structure
 guidance  (:)    guidance function name (optional)
Outputs
 d         (.)    Sail RHS data
 p         (.)    ProfileStruct
References and(), AssignFHandle(), DisplaySailProperties(), DisturbanceStruct(), EnvironmentStruct(), FSailCombined(), FSailRB(), Initialize(), isempty(), ProfileStruct(), RHS(), SailDisturbance(), and SailEnvironment().
inversionMutation()
function inversionMutation (in par, in bounds, in genInfo, in Ops)
 cut points.
 Since version 7.
Form
 [child] = inversionMutation(par,bounds,genInfo,Ops)
Inputs
 parent            the first parent ( [solution string function value] )
 bounds            the bounds matrix for the solution space
 Ops               Options for binaryMutation [gen prob_of_mutation]
Outputs
 child
References and().
LambdaToConeClock3D()
function LambdaToConeClock3D (in x, in type, in d)
Form
 d = LambdaToConeClock3D;   % data structure
 [a, cone, clock] = LambdaToConeClock3D( x, type, d )
Inputs
 x          (12,:)  [x;lambda];
 type       (1,:)   'cartesian' 'equinoctial'
 d           (.)    Data structure
                     .rhoS   (1,1) Specular reflection coefficient
                     .rhoR   (1,1) Thermal and diffuse coefficient
                     .rhoAD  (1,1) Diffuse + absorption coefficient
                     .accel  (1,1) Solar acceleration
                     .mu     (1,1) Gravitational constant
Outputs
 a          (3,:)   Acceleration vector
 cone       (1,:)   Cone angle
 clock      (1,:)   Clock angle
See also
: FLambdaToConeClock
References and(), Cone(), Constant(), Cross(), FLambdaToConeClock(), IsVersionBefore(), LambdaToConeClock3D(), Mag(), MEqToRV(), RHSEquinoctial(), Unit(), vector(), and zeros().
Referenced by LambdaToConeClock3D(), and RHSOpt3DOrbit().
LightnessToLoading()
function LightnessToLoading (in beta)
The lightness is the dimensionless ratio of solar radiation pressure force to the solar gravitational force.
Form
 sigma = LightnessToLoading( beta )
Inputs
 beta          (1,:)   Sail lightness parameter
Outputs
 sigma         (1,:)    Sail loading (kg/m2)
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999
References McInnes().
LoadingToAccel()
function LoadingToAccel (in sigma)
The loading is the sail mass per unit area, m/A.
Form
 acc0 = LoadingToAccel( sigma )
Inputs
 sigma        (1,n)  Sail loading (kg/m2)
Outputs
 acc0          (1,n) Characteristic acceleration, m/s2
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999, p. 14
References and(), Constant(), Demo(), McInnes(), and Plot2D().
Referenced by MakeSquareSail().
LoadingToLightness()
function LoadingToLightness (in sigma)
 The lightness is the dimensionless ratio of solar radiation pressure force
 to the solar gravitational force.
Form
 beta = LoadingToLightness( sigma )
Inputs
 sigma         (1,:)    Sail loading (kg/m2)
Outputs
 beta          (1,:)   Sail lightness parameter
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999
References and(), LoadingToLightness(), McInnes(), Parameter(), Plot2D(), and zeros().
Referenced by LoadingToLightness().
LocallyOptimalConeClock3D()
function LocallyOptimalConeClock3D (in x, in type, in d)
Form
 LocallyOptimalConeClock3D;  % default data structure
 [a, cone, clock] = LocallyOptimalConeClock3D( x, type, d )
Inputs
 x          (6,:)   [r;v]
 type       (1,:)   'cartesian' 'equinoctial'
 d           (.)    Data structure
                     .maneuverType
                     .mu
                     .dirFlag
                     .ascendingNode
                     .accel         Accel magnitude
                     .rhoS
                     .rhoR
                     .rhoAD
Outputs
 a          (3,:)   Acceleration vector
 cone       (1,:)   Cone angle
 clock      (1,:)   Clock angle
References Accel(), and(), Cone(), Constant(), Cross(), DefaultDataStructure(), LocallyOptimalConeClock3D(), LocallyOptimalTraj(), Mag(), MEqToRV(), Unit(), vector(), and zeros().
Referenced by LocallyOptimalConeClock3D(), and RHS3DOrbit().
LocallyOptimalTraj()
function LocallyOptimalTraj (in type, in r, in v, in mu, in dirFlag, in ascendingNode)
Constraints are applied to keep the cone angle within 35 degrees but they may be commented out.
The four types of maneuvers are:
 'semi-major axis'
 'eccentricity'
 'inclination'
 'ascending node'
Form
 [alpha, delta, alphaHat] = LocallyOptimalTraj( type, r, v, mu, dirFlag, ascendingNode )
Inputs
 type           (1,:)  Type (see above)
 r              (3,:)  Position vector (km)
 v              (3,:)  Velocity vector (km/s)
 mu             (1,1)  Gravitational parameter (km^3/s^2)
                       (Default is the sun)
 dirFlag        (1,1)  Directional flag, +/- 1
 ascendingNode  (1,1)  Ascending  node (rad)
Outputs
 alpha          (1,:)  In-plane angle (rad)
 delta          (1,:)  Out-of-plane angle (rad)
 alphaHat       (1,:)  Angle of required force direction
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999, pp. 136-148.
References abs(), Constant(), Demo(), isempty(), LocallyOptimalTraj(), M2Nu(), McInnes(), Plot2D(), RV2El(), RVFromKepler(), Step(), vector(), and zeros().
Referenced by FSailGuidance(), LocallyOptimalConeClock3D(), LocallyOptimalTraj(), and SunGuidance().
lox()
function lox (in p1, in p2, in bounds, in genInfo, in ops)
 crossover for permutation strings.
 Since version 7.
Form
 [c1,c2]=lox(p1,p2,bounds,genInfo,ops)
Inputs
 p1              the first parent ( [solution string function value] )
 p2              the second parent ( [solution string function value] )
 bounds          the bounds matrix for the solution space
 genInfo
 Ops             Options matrix for simple crossover [gen #SimpXovers].
Outputs
 c1
 c2
References and().
LunarDisplacement()
function LunarDisplacement (in z0, in L, in muM, in muE)
 An optimal sail pitch angle of atan(1/sqrt(2)) is assumed.
See also
LunarHalo.
 Since version 7.
Form
 [accel,r0] = LunarDisplacement( z0, L, muM, muE )
Inputs
 z0      (1,:)    Out-of-plane displacement from the Lagrange point (km)
 L       (1,1)    Index to collinear Lagrange point (1, 2, 3)
 muM     (1,1)    Moon gravitational parameter (optional)
 muE     (1,1)    Earth gravitational parameter (optional)
Outputs
 accel   (1,:)    Sail characteristic acceleration (km/s2)
 r0      (3,:)    Dimensions of halo (x,y,z)
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission
Applications", Springer Praxis, London, 1999.
References abs(), and(), Constant(), Demo(), isempty(), LagrangePointsL1ToL5(), length(), LunarDisplacement(), LunarHalo(), McInnes(), and zeros().
Referenced by LunarDisplacement().
LunarHalo()
function LunarHalo (in accel, in L, in theta, in muM, in muE)
 The x and y motion would then be x0*cos(wS*t) and y0*sin(wS*t).
 The z coordinate is the displacement out of the plane.
 The pitch angle, is not entered, is the optimal value to maximize the
 z coordinate, i.e. atan(1/sqrt(2))
 If no outputs are give it will plot the trajectory.
 Since version 7.
Form
 [r0,xL,wS,Omega,rMoon] = LunarHalo( accel, L, theta, muM, muE )
Inputs
 accel   (1,1)    Sail characteristic acceleration (km/s2)
 L       (1,1)    Index to collinear Lagrange point (1, 2, 3)
 theta   (1,1)    Sail pitch angle (optional)
 muM     (1,1)    Moon gravitational parameter (optional)
 muE     (1,1)    Earth gravitational parameter (optional)
Outputs
 r0     (3,1)     Displacements from the Lagrange point (km)
 xL     (1,1)     Linear distance to Lagrange point from corotating origin
 wS     (1,1)     Dimensioned lunar synodic orbit rate
 Omega  (1,1)     Rate of frame rotation
 rMoon  (1,1)     Average lunar distance for nondimensionalization
 U      (3,1)     Partial derivatives of potential
References: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission
Applications", Springer Praxis, London, 1999. Colin McInnes, "Solar Sail Trajectories at the Lunar L2 Lagrange Point", J. Spacecraft, Vol. 30, No. 6, 1993.
References abs(), Accel(), and(), Constant(), Coordinates(), Demo(), isempty(), LagrangePointsL1ToL5(), length(), LunarHalo(), McInnes(), Plot3D(), PlotPlanet(), and vector().
Referenced by FRotatingLagrange(), LunarDisplacement(), and LunarHalo().
MakeSquareSail()
function MakeSquareSail (in accel, in mass, in fileName)
The sail front is along +X in the body frame. The vertices and faces for a simple square are defined explicitly. The inertia is calculated for a square plate using the total mass. There are no other components.
See LoadingToAccel and SailPropsToAccel. Additional sail sizing functions are in Utilities.
Form
 g = MakeSquareSail( accel, mass, fileName )
Inputs
 accel      (1,1)     Characteristic acceleration, m/s2
 mass       (1,1)     Sail mass (kg)
 fileName   (1,:)     Name of a file to save to in SailData, optional
Outputs
 g           (:)      CAD model
References AccelToLoading(), and(), BuildCADModel(), CP1Props(), CreateBody(), CreateComponent(), FindDirectory(), get(), Inertias(), Initialize(), LoadingToAccel(), MakeSquareSail(), SailPropsToAccel(), SaveStructure(), set(), and square().
Referenced by MakeSquareSail().
MassVehicle()
function MassVehicle (in g, in angle, in axis)
 and axes. The function assumes a core body with appendages connected
 through hinges. Each hinge may have as many gimbals as desired.
 This angle and axis rotation is appended to any existing rotation of
 the body via the bHinge field.
See also
HingeRotationMatrix.
Form
 [mass, bBodyToCore] = MassVehicle( g, angle, axis )
Inputs
 g             (1,1)  CAD data structure
 angle         {}     Each cell is a n-by-1 matrix with angles
 axis          {}     Each cell is a 3-by-n matrix of axis for the angles
Outputs
 mass          (:)    Mass data structure
 bBodyToCore   {}     Each cell is a 3-by-3 rotation matrix.
References and(), and HingeRotationMatrix().
maxGenTerm()
function maxGenTerm (in ops, in bPop, in endPop)
terminates the GA when the maximal_generation is
 reached.
 Since version 7.
Form
 [done] = maxGenTerm(ops,bPop,endPop)
Inputs
 ops       a vector of options [current_gen maximum_generation]
 bPop      a matrix of best solutions [generation_found solution_string]
 endPop    the current generation of solutions
Outputs
 done
References and(), and vector().
Referenced by ga().
MEQToI()
function MEQToI (in x)
 p = a(1 + e^2)
 f = ecos(w + W);
 g = esin(w + W);
 h = tan(i/2)cosW
 k = tan(i/2)sinW
 L = W + w + nu
 W is right ascension of the ascending node
 w is argument of perigee
Form
 i = MEQToI( x )
Inputs
 x          (6,1) Modified equinoctial elements
Outputs
 i          (1,1) Inciination (rad)
References MEQToI().
Referenced by Cost3D(), and MEQToI().
multiNonUnifMutation()
function multiNonUnifMutation (in parent, in bounds, in Ops)
 based on a non-uniform probability distribution.  This Gaussian
 distribution starts wide, and narrows to a point distribution as the
 current generation approaches the maximum generation.
 Since version 7.
Form
 [parent] = multiNonUnifMutation(parent,bounds,Ops)
Inputs
 parent            the first parent ( [solution string function value] )
 bounds            the bounds matrix for the solution space
 Ops               Options for multiNonUnifMutation
                   [gen #MultiNonUnifMutations maxGen b]
Outputs
 parent
References and(), and multiNonUnifMutation().
Referenced by ga(), and multiNonUnifMutation().
NewtonDemoFun()
function NewtonDemoFun (in x, in ignoredArg)
 0 = x(1) + x(2)^2 - 2
 0 = x(1)^2 - 1
 This is the built in demo for NewtonSolver.
Form
 y = NewtonDemoFun( x, d )
Inputs
 x   (:,1) Initial guess
 d   (1,1) Data structure (not used)
Outputs
 f   (:,1) Values
References NewtonSolver().
Referenced by NewtonSolver().
NewtonSolver()
function NewtonSolver (in fun, in x, in opt, in d)
 The solver is based on the Taylor series
 f(x) = f(x0) + f'(x0)*(x - x0)
 Both f(x0) and f'(x0) are required. If f' is not supplied, it will
 compute it numerically using a first order Jacobian.
 For a demo type
 NewtonSolver
 for the equations
 0 = x(1) + x(2)^2 - 2
 0 = x(1)^2 - 1
Form
 [x, k, err] = NewtonSolver( fun, x, opt, d )
Inputs
 fun (1,:) Function containing the equations to be solved
 x   (:,1) Initial guess
 opt (1,1) Data structure with optional parameters
           .nMax   (1,1) Maximum number of iterations (Default 100)
           .tol    (1,1) Tolerance on weighted error (Default 1e-10)
           .w      (:,1) Weight on each equation (Default ones(:,1))
           .funJac (1,:) Jacobian function (Default internal numerical)
Outputs
 x   (:,1) Final values
 k   (1,1) Number of iterations
 err (:,1) Errors
References Jacobian(), NewtonDemoFun(), series(), set(), and zeros().
Referenced by NewtonDemoFun().
NKPlanetPeriod()
function NKPlanetPeriod (in planet, in radii, in z)
 Has a demo for an Earth synchronoous orbit at 30 radii (9.6 days).
 The desired orbit rate is an input to NonKeplerianPlanet.
 Since version 7.
Form
 [P,w] = NKPlanetPeriod( planet, radii )   % synchronous period
 [P,w] = NKPlanetPeriod( planet, rho, z )  % optimal period, sqrt(mu/r^3)
Inputs
 planet    (:)       Planet name string
 radii    (1,1)      Radius of synchronous orbit period or rho
 z        (1,1)      Displacement of orbit in Earth radii
Outputs
 P        (1,1)      Period (days)
 w        (1,1)      Orbit rate
References Constant(), NKPlanetPeriod(), NonKeplerianPlanet(), and Period().
Referenced by NKPlanetPeriod().
NonKeplerianPlanet()
function NonKeplerianPlanet (in rho, in z, in omega, in mu)
 If you choose the dimensionless version then the distances should be in
 planetary radii. The characteristic accel will be in units of the
 gravitational acceleration at 1 planetary radius.
 The optimal rate (minimum sail acceleration) is sqrt(1/r^3), where r
 is sqrt(rho^2 + z^2).
 Either rho or z may be a vector.
 Since version 7.
Form
 [pitch,accel] = NonKeplerianPlanet( rho, z, omega, mu )
Inputs
 rho           (1,1)    Orbit amplitude
 z             (1,1)    Displacement in the anti-sun direction
 omega         (1,1)    Orbit rate (default is optimal value)
 mu            (1,1)    Planet gravitational acceleration (default 1)
Outputs
 pitch         (1,1)   Sail pitch angle
 accel         (1,1)   Sail characteristic acceleration
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission
Applications", Springer Praxis, London, 1999, p. 199.
References Accel(), Demo(), isempty(), length(), McInnes(), NonKeplerianPlanet(), Period(), Plot2D(), vector(), and zeros().
Referenced by NKPlanetPeriod(), and NonKeplerianPlanet().
NonKeplerianSun()
function NonKeplerianSun (in rho, in z, in omega)
The sail enables a displaced orbit above (or below) the ecliptic plane. The units can be km or non-dimensional but must be consistent across the inputs.
Form
 [pitch,beta] = NonKeplerianSun( rho, z, omega )
Inputs
 rho           (1,1)    Halo amplitude (in-plane)
 z             (1,1)    Out of plane displacement
 omega         (1,1)    Orbital rate, 2*pi/period
Outputs
 pitch         (1,1)    Sail pitch angle
 beta          (1,1)    Sail lightness parameter (beta)
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999.
References and(), Constant(), Demo(), length(), McInnes(), NonKeplerianSun(), Plot2D(), and zeros().
Referenced by NonKeplerianSun().
nonUnifMutate()
function nonUnifMutate (in parent, in bounds, in Ops, in seed)
 based on a non-uniform probability distribution.  This Gaussian
 distribution starts wide, and narrows to a point distribution as the
 current generation approaches the maximum generation.
 Since version 7.
Form
 [parent] = nonUnifMutate(parent,bounds,Ops,seed)
Inputs
 parent        the first parent ( [solution string function value] )
 bounds        the bounds matrix for the solution space
 Ops           Options for nonUnifMutate[gen #NonUnifMutations maxGen b]
Outputs
 parent
References and(), and nonUnifMutate().
Referenced by nonUnifMutate().
normGeomSelect()
function normGeomSelect (in oldPop, in options, in seed)
 geometric distribution.
 Since version 7.
Form
 [newPop] = normGeomSelect(oldPop,options, seed)
Inputs
 oldpop    the current population
 options   options to normGeomSelect [gen probability_of_selecting_best]
 seed      optional seed for random numbers, for testing
Outputs
 newPop    the new population selected from the oldPop
References and(), and normGeomSelect().
Referenced by ga(), GAMin(), normGeomSelect(), and tournSelect().
oox()
function oox (in p1, in p2, in bounds, in Ops)
based crossover by Davis.
 Since version 7.
Form
 [c1,c2] = orderbasedXover(p1,p2,bounds,Ops)
Inputs
 p1              the first parent ( [solution string function value] )
 p2              the second parent ( [solution string function value] )
 bounds          the bounds matrix for the solution space
 Ops             Options matrix for simple crossover [gen #SimpXovers].
Outputs
 c1
 c2
References and().
OpticalMcInnesToPSS()
function OpticalMcInnesToPSS (in r, in s)
 PSS formulation supports ideal Lambertian coefficients only.
Form
 [rhoS, rhoD, rhoA] = OpticalMcInnesToPSS( r, s )
Inputs
 r      (1,n)    Fraction of photons which are reflected
 s      (1,n)    Fraction of r which are reflected specularly
Outputs
 rhoS   (1,n)    Specular reflection
 rhoD   (1,n)    Diffuse reflection
 rhoA   (1,n)    Absorption
References McInnes().
Referenced by UpdateSailOpticalProps().
OptimalPeriodNonKepler()
function OptimalPeriodNonKepler (in z, in rho)
 This is for sun-centered orbits only. The inputs can be dimensionless.
Form
 [wOpt,P] = OptimalPeriodNonKepler( z, rho );
Inputs
 z             (1,1)    Out of plane displacement
 rho           (1,1)    Halo amplitude (in-plane)
Outputs
 wOpt          (1,1)    Optimal orbit rate (rad/sec)
 P             (1,1)    Orbit period (sec)
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission
Applications", Springer-Praxis, London, 1999, p. 179
References Constant(), McInnes(), and OptimalPeriodNonKepler().
Referenced by OptimalPeriodNonKepler().
optMaxGenTerm()
function optMaxGenTerm (in ops, in bPop, in endPop)
terminates the GA, when either the maximal_generation
 is reached or when the optimal function val is found.
 Since version 7.
Form
 [done] = optMaxGenTerm(ops,bPop,endPop)
Inputs
 ops       a vector of options [maximum_generation optimal epsilon]
 bPop      a matrix of best solutions [generation_found solution_string]
 endPop    the current generation of solutions
Outputs
 done
References and(), and vector().
OptTestFun()
function OptTestFun (in x, in d)
The available functions are:
 'sphere'                      x( n)
 'griewank''s function'        x( n)
 'shekel''s foxholes'          x(10)
 'michalewicz''s function'     x(10)
 'langerman''s function'       x( n)
 'de jong 1'                   x( n)
 'de jong 2' ('rosenbrock''s') x( 2)
 'de jong 3'                   x( n)
 'de jong 4'                   x( n)
 'de jong 5'                   x( 2)
 Since version 7.
Form
 f =  OptTestFun( x, d )
Inputs
 x              (:,1)   Value of x
 d              (1,1)   Structure to pass to fun (not used)
                        .name (1,:) Name of function
                        .n    (1,1) Order (sphere, griewank michalewicz,
                                     langerman and de jong 1, 3, 4 only)
Outputs
 f              (1,1)  Cost
References and(), and OptTestFun().
Referenced by OptTestFun().
OptTestFunEcon()
function OptTestFunEcon (in x, in ignoredArg)
 F(.864,1.23) = 16.0817 (the global minumum) and F(2.35,-.319) = 20.9805.
Form
 f =  OptTestFunEcon( x, d )
Inputs
 x              (2,1)  Value of x
 d              (1,1)  Structure to pass to fun (not used)
Outputs
 f              (1,1)  Cost
References and().
OptTestFunParabola()
function OptTestFunParabola (in x, in ignoredArg)
Form
 f = OptTestFunParabola( x, d )
Inputs
 x              (1,1)  Value of x
 d              (1,1)  Structure to pass to fun (not used)
Outputs
 f              (1,1)  Cost
Referenced by GAMin().
OptTestFunRosenbrock()
function OptTestFunRosenbrock (in x, in ignoredArg)
 f = 100*(x(1)^2-x(2))^2 + (1-x(1))^2
Form
 f = OptTestFunRosenbrock( x, d )
Inputs
 x              (2,1)  Value of x
 d              (1,1)  Structure to pass to fun (not used)
Outputs
 f              (1,1)  Cost
Referenced by GeneticAlgorithm(), and SimulatedAnnealing().
parse()
function parse (in inStr)
 text and parses out the individual string items into a n item matrix,
 one row for each string.
 Since version 7.
Form
 [x] = parse(inStr)
Inputs
 inStr                the blank separated string vector
Outputs
 x                    the return matrix of strings
References and(), and vector().
Referenced by ga().
partmapXover()
function partmapXover (in par1, in par2, in bounds, in Ops)
 mapped crossover.
 Since version 7.
Form
 [ch1,ch2] = partmapXover(par1,par2,bounds,Ops)
Inputs
 par1              the first parent ( [solution string function value] )
 par2              the second parent ( [solution string function value] )
 bounds          the bounds matrix for the solution space
 Ops             Options matrix for simple crossover [gen #SimpXovers].
Outputs
 ch1
 ch2
References and(), and isempty().
PlanetOptimalTraj()
function PlanetOptimalTraj (in dir, in r, in v, in uSun)
 Since version 7.
Form
 [alphaStar, psi] = PlanetOptimalTraj( dir, r, v, uSun )
Inputs
 dir            (1,1)    Direction flag, +/- 1
 r              (3,:)    Position vector (km)
 v              (3,:)    Velocity vector (km/s)
 uSun    (3,:) or (3,1)  Sun vector in r/v frame
Outputs
 alphaStar      (1,:)    Pitch angle
 psi            (1,:)    Flight path angle (velocity from sun)
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999, pp. 156.
References and(), Cross(), Date2JD(), Demo(), McInnes(), PlanetOptimalTraj(), Plot2D(), PltOrbit(), RVFromKepler(), SunV1(), Unit(), vector(), and zeros().
Referenced by GeoOptimalMission(), GeoSwitchingMission(), and PlanetOptimalTraj().
PlanetRot()
function PlanetRot (in planet, in jD)
 The Earth, Mars, and the moon have high-fidelity functions.
 Other bodies use Seidelmann, The Explanatory Supplement to the Astronomical
 Almanac.
Form
 b = PlanetRot( planet, jD )
Inputs
 planet    (:)    String name of planet
 jD       (1,1)   Julian date
Outputs
 b        (3,3)   Rotation matrix from ECI to planet fixed frame
References and(), Date2JD(), EarthRot(), ECIToPlanet(), JD2T(), MarsRot(), and MoonRot().
Plot3DOrbit()
function Plot3DOrbit (in r, in v, in mu, in plotTitle)
Form
 Plot3DOrbit( r, v, mu, plotTitle )
Inputs
 r            (3,:) Position vector (km)
 v            (3,:) Velocity vector (km/s)
 mu           (1,1) Gravitation constant (km^3/s^2)
 plotTitle    (1,:) Title of plot
Outputs
 None
References and(), Constant(), NewFig(), Plot3DOrbit(), RV2El(), RVOrbGen(), set(), Trajectory(), vector(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by LargeFormationControl(), and Plot3DOrbit().
Plot3DTrajectory()
function Plot3DTrajectory (in lambda, in d, in units, in plotTitle)
Form
 b = Plot3DTrajectory( lambda, d, units, plotTitle  )
Inputs
 lambda         (6,1)  Costates
 d              (1,1)  Structure to pass to fun
                       .costFun
                       .mu
                       .rF
                       .xF
                       .el0     (1,6) Initial orbit orbital elements
                       .elF     (1,6) Final orbit orbital elements
 units          (1,:)  Units for position
 plotTitle      (1,:)  Title for plots
Outputs
 b              (1,1)  Data structure
                       .r (3,:) Position
                       .v (3,:) Velocity
                       .t (1,:) Times
[xF, xFErr, tF]
References and(), Cost3D(), DupVect(), get(), MEqToEl(), MEqToRV(), Plot3DTrajectory(), RVFromKepler(), TimeLabl(), and Trajectory().
Referenced by Cost3D(), and Plot3DTrajectory().
PlotSailClock2D()
function PlotSailClock2D (in f, in n, in a, in s, in r, in v, in c)
 This plane is perpendicular to the sun vector. The clock angle is
 measured from the reference frame y axis.
 This plot can account for the fact that the force vector may not be in the
 plane of the sail normal/sun flux vector (for an asymmetric sail).
 If the reference quaternion is known it can be passed in directly.
See also
QSail, PlotSailForce2D
 Since version 7.
Form
 PlotSailClock2D( f, n, a, s, r, v, c )
 PlotSailClock2D( f, n, a, q )
Inputs
 f              (3,1)  Force vector
 n              (3,1)  Sail front normal vector
 a              (1,1)  Axes handle (optional)
 s              (3,1)  Unit vector to sun (inertial)
 r              (3,1)  Position vector
 v              (3,1)  Velocity vector
 c              (1,1)  Sign convention
Outputs
 cone              (1,1)  Cone angle
 clock             (1,1)  Clock angle
References and(), AnglePatch(), Circle(), Cone(), Cross(), Dot(), isempty(), NewFig(), PlotSailClock2D(), PlotSailForce2D(), QSail(), QTForm(), quaternion(), SailDefaultColors(), SailPatchVertices(), set(), TitleS(), Unit(), UToConeClock(), and vector().
Referenced by PlotSailClock2D().
PlotSailForce()
function PlotSailForce (in f, in p, in env, in c)
 (1) plot the force vector in 3D in a rotating sun-referenced frame
 (2) plot the time history of the total force in the inertial frame
 (3) plot the time history of the solar pressure force in the inertial frame
 (4) plot the cone and clock angles for the total force
See also
SailDisturbance.
 Since version 7.
Form
 PlotSailForce( f, p, env, c )
Inputs
 f     (:)     Force data structure
 p     (:)     Profile data structure
 env   (:)     Environment data structure
 c     (1)     Flag for sign convention of rotating frame, optional
Outputs
 None.
References abs(), AddAxes(), and(), Plot2D(), Plot3D(), PlotSailForce(), QForm(), QSail(), SailDisturbance(), set(), TimeLabl(), and vector().
Referenced by PlotSailForce().
PlotSailForce2D()
function PlotSailForce2D (in f, in n, in s, in a)
 Clarifies the centerline angle, the angle between the sail normal and
 the resulting force vector. This angle is nonzero for sails with
 nonideal optical properties, i.e. a diffuse component to the reflected
 radiation.
 Since version 7.
Form
 PlotSailForce2D( f, n, s, a )
 f     (3,1)     Force vector
 n     (3,1)     Sail front normal vector
 s     (3,1)     unit vector to sun
 a     (1,1)     Axes handle (optional)
References and(), Cone(), Dot(), NewFig(), SailDefaultColors(), set(), TitleS(), Unit(), and vector().
Referenced by PlotSailClock2D(), and SailForceSubplots().
PlotSailProfile()
function PlotSailProfile (in p, in env, in normal, in c)
Pass in the environment data to add the center planet to the 3D view and generate plots of the orbital elements. Add the sail front normal (body frame), nominally +X, to view it in the rotating sail frame.
See also
QSail, QToConeClock.
Form
 h = PlotSailProfile( p )
 PlotSailProfile( p, env )
 PlotSailProfile( p, env, normal, c )
Inputs
 p        (:)     Profile data structure
 env      (:)     Environment data structure
 normal  (3,1)    Sail front body normal
 c       (1,1)    Sign convention for rotating frame
Outputs
References and(), ComputeSailNormal(), isempty(), Plot2D(), Plot3D(), PlotSailProfile(), QSail(), QToConeClock(), RV2El(), RVOrbGen(), TimeLabl(), and vector().
Referenced by PlotSailProfile().
PlottingParabolas()
function PlottingParabolas (in rho0, in z0)
 Since version 7.
Form
 PlottingParabolas( rho0, z0 )
Inputs
 rho0     (1,1)      Radius of synchronous orbit period or rho
 z0       (1,1)      Displacement of orbit in Earth radii
Outputs
 None.
Reference: John Bookless and Colin McInnes, "Dynamics and Control of Displaced Periodic Orbits Using Solar-Sail Propulsion", JOURNAL OF GUIDANCE, CONTROL, AND DYNAMICS, Vol. 29, No. 3, May-June 2006
References and(), Demo(), length(), McInnes(), NewFig(), PlottingParabolas(), and zeros().
Referenced by PlottingParabolas().
ProfileStruct()
function ProfileStruct ()
 Defaults to JD2000 with an equatorial LEO orbit. The sail is set to
 sun-pointing. The rotational fields are empty.
 See SunV1/SunV2 and CEcl2Eq for computing rPlanetH.
 For example,
 [uS,rS] = SunV1( jD );
 p.rPlanetH = CEcl2Eq'*rS*-uS;
 This field is use to compute eclipses for planetary orbits. The vector
 to the planet should be in the heliocentric ecliptic frame.
 Since version 7.
Form
 p = ProfileStruct
Inputs
 None.
Outputs
 p          (:)     Profile structure with state fields
               .q           (4,:) ECI to body quaternion
               .r           (3,:) ECI position vectors
               .v           (3,:) ECI velocities
               .jD          (1,:) Julian dates
               .rPlanetH    (3,:) Vector to planet in heliocentric frame
               .angle       (n,:) Angles (initialized empty)
               .axis        (3,n) Axes for angles (empty)
               .body        (1,n) Body hinge for angle (empty)
References and(), CEcl2Eq(), JD2000(), ProfileStruct(), SailDisturbance(), set(), SunV1(), and SunV2().
Referenced by InitializeSailSim(), ProfileStruct(), and SailDisturbance().
QSail()
function QSail (in s, in r, in v, in c)
The X axis is along the sun line s; this may be towards or away from the sun depending on user preference. The remaining axes are defined by the cross product of X with either the orbit normal or the velocity vector. Clock angles are always measured from the resulting Y axis. Has a built-in heliocentric demo.
For sun-pointing/orbit normal coordinates:
 x is along s
 y is perpendicular to the orbit normal, (h x uSun)
 z completes the set and is as close to the orbit normal as possible
 For sun-pointing/velocity coordinates:
 x is along s
 z is perpendicular to the velocity, (s x v)
 y completes the set and is in the same hemisphere as velocity
 For the second option pass in [] for r. For a heliocentric orbit, both
 frames have the orbit normal along z.
Form
 q = QSail( s, r, v )         Sun-pointing frame
 q = QSail( s, r, v, -1 )     Flux-aligned frame
 q = QSail( s, [], v )
 q = QSail( s, [], v, -1 )
Inputs
 uSun   (3,n) or (3,1)  Unit vectors to sun
 r          (3,n)       Position vectors
 v          (3,n)       Velocity vectors
 c          (1,1)       Sign convention for s to X axis, optional
Outputs
 q          (4,n) Quaternions
References AddAxes(), and(), close(), Constant(), Cross(), Demo(), isempty(), Mag(), Mat2Q(), Plot2D(), QSail(), set(), Unit(), vector(), and zeros().
Referenced by ConeClockToQConstrained(), ConeClockToU(), DrawSailAngles(), NorthFrame(), PlotSailClock2D(), PlotSailForce(), PlotSailProfile(), QSail(), SailForceSubplots(), SteeringAnglesToQ(), and UToConeClock().
QSteeringYAligned()
function QSteeringYAligned (in cone, in clock, in c)
Compute the cone rotation axis for a clock rotation about X. The sign convention indicates if clock is measured around the direction the sun (+1) or the AWAY from the sun (-1). With no output, creaes a figure using VisualizeSailAttitude. The built-in demo creates two figures, one for each sign convention.
Form
 qSteer = QSteeringYAligned( cone, clock, c )
Inputs
 cone              (1,1)  Cone angle
 clock             (1,1)  Clock angle
 c                 (1,1)  Sign convention for clock angle, measured
                          about direction TO the sun (+1) or AWAY from
                          the sun (-1). Default is +1.
Outputs
 qSteer            (4,1)     Reference frame to body frame quaternion
References AU2Q(), Cone(), Eul2Mat(), QMult(), QRand(), QSteeringYAligned(), QTForm(), quaternion(), QZero(), and VisualizeSailAttitude().
Referenced by QSteeringYAligned(), and SailForceSubplots().
QToConeClock()
function QToConeClock (in qIToB, in r, in v, in s)
 The cone and clock system is defined with one axis along the sun (x)
 vector, one along the cross product of the orbit normal and sun vector (y)
 and the third vector completes the orthogonal set (z). The clock angle
 is measured from the y axis.
 Since version 7.
Form
 [cone, clock] = QToConeClock( qIToB, r, v, s )
Inputs
 qIToB         (4,n) Quaternions
 r             (3,:) Orbit vector
 v             (3,:) Velocity vector
 s             (3,:) Sun unit vector (from sc to sun)
Outputs
 cone          (1,:) Cone angle (rad)
 clock         (1,:) Clock angle (rad)
Reference: Dachwald, B., "Low Thrust Trajectory Optimization and Interplanetary Mission Analysis Using Evolutionary Neurocontrol," PhD Thesis Universitat Bundeswehr Munchen, FRG, April 2004, p. 8.
References and(), Cone(), Cross(), Q2Mat(), quaternion(), Unit(), vector(), and zeros().
Referenced by PlotSailProfile().
Quadratic()
function Quadratic (in x, in ignoredArg)
Form
 f = Quadratic( x, d )
Inputs
 x              (:,1)  Value of x
 d              (1,1)  Data structure (unused)
Outputs
 f              (1,1)  Cost
Referenced by DrawMirror(), HQuadrantBillow(), LinearSinCosToQuadCos(), and StripedQuadrant().
QXToAlphaDelta()
function QXToAlphaDelta (in q, in x)
 delta is defined with respect to the osculating orbital plane, where
 k_hat is the unit vector orbit normal.
 The sail normal is defined along the X axis in the body frame.
 n = (cos alpha) r_hat + (sin alpha sin delta) theta_hat + (sin alpha cos delta) k_hat
 When the angles are zero, then
 n_hat = r_hat = Xbody
 theta_hat = Ybody
 k_hat = Zbody
 Since version 7.
Form
 [alpha, delta] = QToAlphaDelta( q, x )
Inputs
 q      (4,1)   Inertial quaternion in the solar ecliptic frame
 x      (6,1)   [r;v] Cartesian state
Outputs
 alpha  (1,1)   Cone angle
 delta  (1,1)   Clock angle
Reference: Bong Wie, Propellantless AOCS Design for a 160-m, 450-kg Sailcraft of the Solar Polar Imager Mission, AIAA 2005-3928, p. 11
References and(), Cone(), Cross(), Imager(), QTForm(), quaternion(), Unit(), and vector().
RHS2DOrbit()
function RHS2DOrbit (in t, in x, in d)
Includes radial position, radial velocity and tangential velocity only. Choice of specular or full disturbance model (requires CAD model).
See also
SailEnvironment and SailDisturbance.
Form
 d = RHS2DOrbit;
 xDot = RHS2DOrbit( t, x, d )
Inputs
 t          (1,1)  Time
 x          (4,1)  States [r;u;v;angle]
 d           (.)   Structure to pass to the integration RHS
                   .accel        (1,1) The characteristic acceleration
                   .sailAngleFun (.)   The guidance function, alpha = f(x, t)
                   .forceModel   (1,:)  Either 'specular' or 'full'
                   .distModel
                   .g             (.)  CAD model for full
Outputs
 xDot       (4,1)  State derivatives d[r;u;v;angle]/dt
References and(), AU2Q(), RHS(), RHS2DOrbit(), SailDisturbance(), SailEnvironment(), and vector().
Referenced by RHS2DOrbit(), and TwoDEscape().
RHS3DOrbit()
function RHS3DOrbit (in t, in x, in flag, in d)
This function is specifically for the minimum time problem. It is designed to be called by ode113. The terminal condition is the inclination. This routine can handle equinoctial or cartesian elements.
See also
LocallyOptimalTrajectories, LocallyOptimalConeClock3D,
RHSEquinoctial
Form
 d = RHS3DOrbit;
 varargout = RHS3DOrbit( t, x, flag, d )
Inputs
 t          ( 1,1)  Time
 x          (12,1)  States [elements]
 flag       ( 1,1)  Flag from ode113
 d             (.)  Structure to pass to the integration RHS
                    .coordType     ''   String
                    .coneClockFun  (*)  Handle
                    .accel (1,1) The acceleration
Outputs
 xDot       (12,1)  State derivatives d[elements]/dt
 or
 vnew       ( 1,1)  Value of constraint
 isterminal ( 1,1)  1 if a terminal constraint
 direction  ( 1,1)  Direction
References LocallyOptimalConeClock3D(), RHS(), RHS3DOrbit(), RHSCartesian(), and RHSEquinoctial().
Referenced by RHS3DOrbit().
RHSCartesian()
function RHSCartesian (in t, in x, in d)
Form
 d = RHSCartesian;
 xDot = RHSCartesian( t, x, d )
Inputs
 t          (1,1)  Time
 x          (6,1)  States [r;v]
 d          (1,1)  Structure to pass to the integration RHS
                   .mu, gravitational parameter
                   .f,  external acceleration, (3,1)
Outputs
 xDot       (3,1)   State derivatives d[v]/dt
References Mag(), RHS(), and RHSCartesian().
Referenced by RHS3DOrbit(), RHSCartesian(), and RHSOpt3DOrbit().
RHSCartesianRadialAccel()
function RHSCartesianRadialAccel (in ignoredArg, in x, in d)
Form
 d = RHSCartesianRadialAccel
 xDot = RHSCartesianRadialAccel( t, x, d )
Inputs
 t          (1,1)  Time
 x          (6,1)  States [r;v]
 d          (1,1)  Structure to pass to the integration RHS
                   .mu, gravitational parameter
                   .f,  external acceleration, (3,1)
Outputs
 xDot       (3,1)   State derivatives d[v]/dt
References Constant(), Mag(), RHS(), RHSCartesianRadialAccel(), and Unit().
Referenced by RHSCartesianRadialAccel().
RHSHelio2DOrbit()
function RHSHelio2DOrbit (in t, in x, in flag, in d)
Includes only radial position, radial velocity and tangential velocity. Has a built-in specular disturbance model.
See also
HeliopauseSimulation.
Form
 varargout = RHSHelio2DOrbit( t, x, flag, d )
Inputs
 t          (1,1)  Time
 x          (4,1)  States [r;u;v;angle]
 flag       (1,1)  Flag from ode113
 d           (.)   Structure to pass to the integration RHS
                   .distModel    (.)   Data structure
                   .sailAngleFun (@)   Angle function name/handle
                   .forceModel   ''    Either 'specular' or 'full'
                   .laserOn      (1,1) 1 if laser is on
                   .laser        (.)
                                      .power    Power (W)
                                      .lambda   Wavelength (m)
                                      .aperture Optical aperture (m)
                                      .area     Sail area (m^2)
                                      .f        Accel factor
                                      .aU       Distance for laser on
Outputs
 xDot       (4,1)  State derivatives d[r;u;v;angle]/dt
References Accel(), and(), RHS(), and Wavelength().
RHSOpt2DOrbit()
function RHSOpt2DOrbit (in t, in x, in flag, in d)
Includes only radial position, radial velocity and tangential velocity. This function is specifically for the minimum time problem. It is designed to be called by ode113. The terminal condition is the orbit radius of the target which precludes optimal orbits that may go outside this radius.
Form
 d = RHSOpt2DOrbit
 varargout = RHSOpt2DOrbit( t, x, flag, d )
Inputs
 t          (1,1)  Time
 x          (7,1)  States [r;u;v;lambda;theta]
 flag       (1,1)  Flag from ode113
 d          (1,1)  Structure to pass to the integration RHS
                   .accel        (1,1) The acceleration (km/s2)
                   .mu           (1,1) Gravitational parameter
                   .sailAngleFun (1,1) Function (x,t)
Outputs
 xDot       (7,1)  State derivatives d[r;u;v;lamDot;vOR]/dt
 or
 vnew       (1,1)  Value of constraint
 isterminal (1,1)  1 if a terminal constraint
 direction  (1,1)  Direction
See also
TwoDOptimalSailAngle
References and(), RHS(), RHSOpt2DOrbit(), and TwoDOptimalSailAngle().
Referenced by CostSail2D(), and RHSOpt2DOrbit().
RHSOpt3DOrbit()
function RHSOpt3DOrbit (in t, in x, in flag, in d)
This function is specifically for the minimum time problem. It is designed to be called by ode113. The terminal condition is the inclination. This routine can handle equinoctial or cartesian elements. Partials of the state equations with respect to the states are done by a first difference approximation.
Form
 d = RHSOpt3DOrbit;
 varargout = RHSOpt3DOrbit( t, x, flag, d )
Inputs
 t           (1,1)  Time
 x          (12,1)  States [elements;lambda]
 flag        (1,1)  Flag from ode113
 d             (.)  Structure to pass to the integration RHS
                    .lambdaToAccel (*)   Function handle
                    .coordType     (:)   'equinoctial' or 'cartesian'
                    .hasThruster   (1,1) Thruster flag
                    + lambdaToAccel fields
Outputs
 xDot       (12,1)  State derivatives d[elements;lambda]/dt
 or
 vnew       ( 1,1)  Value of constraint
 isterminal ( 1,1)  1 if a terminal constraint
 direction  ( 1,1)  Direction
See also
: RHSEquinoctial, RHSCartesian, LambdaToConeClock3D
References LambdaToConeClock3D(), RHS(), RHSCartesian(), RHSEquinoctial(), and RHSOpt3DOrbit().
Referenced by Cost3D(), CostSail3D(), and RHSOpt3DOrbit().
roulette()
function roulette (in oldPop, in options)
 surviving equal to the fittness of i / sum of the fittness of all
 individuals.
 Since version 7.
Form
 [newPop] = roulette(oldPop,options)
Inputs
 oldPop              the current population
 options             options [gen]
Outputs
 newPop              the new population selected from the oldPop
References and().
S4DeployTorque()
function S4DeployTorque (in ignoredArg, in p, in ignoredArg, in d)
Form
 [f,tq] = S4DeployTorque( ~, p, ~, d )
Inputs
 g         (1,1) CAD data structure (not used)
 p         (1,1) Profile data structure
 e         (1,1) Environment data structure  (not used)
 d         (1,1) Disturbance data structure
                  .Ldot, mast deployment rate (m/s)
                  .F, nominal force
Outputs
 force         (:)      Force structure
                         .total   (3,1) Total force on the vehicle
 torque        (:)      Torque structure
                         .total   (3,1) Total torque on the vehicle
Reference: (Student Paper) Attitude Dynamics and Stability of Solar Sails During Deployment. LeFevre and Jha
References and(), Disturbances(), and square().
SailACS()
function SailACS (in x, in d)
This control system does small angle attitude control using reaction wheels and momentum unloading using vanes. Momentum unloading is a PI controller. Attitude control is a PID controller.
 d = SailACS;
 [d,beta,tRWA] = SailACS(x,d)
Inputs
 x (10,1)   State vector [q;omega;omegaRWA]
 d (.)      Data structure
            .dT        (1,1) Time step (s)
            .inr       (3,3) Inertia matrix (kg-m^2)
            .kM        (1,1) Momentum unloading forward gain (Nm/Nms)
            .tauI      (1,1) Momentum unloading integral time constant (s)
            .inrRWA    (1,1) Reaction wheel inertia (kg-m^2)
            .hI        (3,1) Integral of the ECI momentum (Nms^2)
            .ECIToBody (4,1) Quaternion from ECI to body
Outputs
 d    (.)   Data structure
 beta (4,1) Vane angles
 tRWA (3,1) Torque demand for the thrusters (Reaction wheel Assemblies)
 tVane (3,1) Torque demand for the vanes
References and(), Integral(), Mag(), PID(), PID3Axis(), QForm(), QTForm(), SailACS(), and vector().
Referenced by SailACS().
SailClosedLoopNLEqns()
function SailClosedLoopNLEqns (in ignoredArg, in x, in kappa0, in rho0, in z0, in G, in mode)
Form
 xd = SailClosedLoopNLEqns(t,x,kappa0,rho0,z0,G,mode)
Inputs
 t            (1,1)     Time
 x            (6,1)     The state vector [rho;z;rhoDot;zDot;theta;thetaDot]
 kappa0       (1,1)     Sail characteristic acceleration
 rho0         (1,1)     Target orbit amplitude
 z0           (1,1)     Target orbit displacements
 G            (4,1)     Control gains
 mode         (1,1)     Control mode, (1) for area and (2) for pitch
Outputs
 xd           (6,1)     State derivative
References abs(), and(), Rename(), RHS(), and vector().
SailDefaultColors()
function SailDefaultColors (in action)
 The options are: sun, cone, clock, clock line, force, body frame,
 and ref frame.
Form
 color = SailDefaultColors( action )
Inputs
 action     (:)           Name
Outputs
 color  (1,1) or (1,3)    Character or (R,G,B) triple
References and(), and SailDefaultColors().
Referenced by DrawSailAngles(), DrawSailAttitude(), DrawSailFrames(), PlotSailClock2D(), PlotSailForce2D(), SailDefaultColors(), and VisualizeSailAttitude().
SailDisturbance()
function SailDisturbance (in g, in p, in e, in d)
You input the CAD model, g, the attitude, gimbal and orbit profile, p, and an additional data structure, d, to control the function.
The model assumes that the solar sail is composed of a core with multiple bodies attached to the core. Any component can be a sail, but it must be of the sail class for the combined thermal/optical force model to be applied. This function works on the face and vertex lists for the components. You can model a deformable sail by changing the sail vertices on each call.
 This function has memory of the CAD model for efficiency. You must
 clear it when switching CAD models.
 The output data structure is described below.
 Shadowing is not modeled. Planetary data is obtained from
 the Constant function. Planetary eclipses (when in planetary orbit)
 are modeled but lunar eclipses are not.
 SailDisturbance will plot all environmental variables even if
 the torque and force calculations do not include them. When you turn off
 disturbances they are still calculated and plotted, but are not included
 in the total torque and force.
 The entered optical properties are applied to albedo and solar force and
 torque calculations. The infrared properties are used for planetary
 radiation.
See also
SailEnvironment, ProfileStruct, DisturbanceStruct, EnvironmentStruct.
 This function has a built-in demo.
Form
 [f, t, b] = SailDisturbance( g, p, e, d )
Inputs
 g         (.) CAD data structure
 p         (.) Profile data structure
                 .q           (1,:) ECI to body quaternion
                 .r           (3,:) ECI position vectors (km)
                 .v           (3,:) ECI velocities (km/s)
                 .jD          (1,:) Julian dates
                 .rPlanetH    (3,n) Heliocentric planet vectors
                 .angle       (n,:) Angles
                 .axis        (3,n) Axes for angles
                 .body        (1,n) Body hinge for angle
 e         (.) Environment data structure (from SailEnvironment)
 d         (.) Disturbance data structure
                 .aeroOn      (1,1) 1 = aerodynamics on
                 .albedoOn    (1,1) 1 = planetary albedo on
                 .radOn       (1,1) 1 = planetary radiation on
                 .solarOn     (1,1) 1 = solar pressure on
                 .magOn       (1,1) 1 = magnetic field torques on
                 .ggOn        (1,1) 1 = gravity gradient torques on
Outputs
 f         (.) Data structure
                 .total          (3,:)   Total force in the ECI frame (N)
                 .totalAero      (3,:)   Total aero force in the ECI frame (N)
                 .totalSolar     (3,:)   Total solar force in the ECI frame (N)
                 .totalAlbedo    (3,:)   Total albedo force in the ECI frame (N)
                 .totalRadiation (3,:)   Total radiation force in the ECI frame (N)
                 .totalBody      (3,:,m) Total force in body frame (N)
 t         (.) Data structure
                 .total          (3,:)   Total torque in the body frame (Nm)
                 .totalAero      (3,:)   Total aero torque in the body frame (Nm)
                 .totalSolar     (3,:)   Total solar torque in the body frame (Nm)
                 .totalAlbedo    (3,:)   Total albedo torque in the body frame (Nm)
                 .totalRadiation (3,:)   Total radiation torque in the body frame (Nm)
                 .totalGG        (3,:)   Total gravity gradient torque in the body frame (Nm)
                 .totalMagnetic  (3,:)   Total magnetic torque in the body frame (Nm)
                 .totalBody      (3,:,m) Total torque in body frame (Nm)
 b          {m}  Body to core rotation matrices
References and(), Constant(), DisturbanceStruct(), EnvironmentStruct(), ProfileStruct(), quaternion(), SailDisturbance(), and SailEnvironment().
Referenced by DisturbanceStruct(), FSailCombined(), InitializeSailSim(), PlotSailForce(), ProfileStruct(), RHS2DOrbit(), SailDisturbance(), SailEnvironment(), and SearchVaneAngles().
SailEnvironment()
function SailEnvironment (in planet, in p, in d)
Designed to work with SailDisturbance.
 Planet choices include the major planets and the sun.
 Some models, such as AtmDens2 and AtmJ70, only apply to the Earth.
 This function stores certain planet parameters for efficiency, which are
 reset when it is called with a new planet name.
 Ephemeris of the planet should be computed separately.
See also
: Constant, EarthRad, EarthAlb, Eclipse, Altitude
 Since version 7.
Form
 env = SailEnvironment( planet, p, d )
Inputs
 planet   (:)     Planet name
 p       (1,1)    Profile data structure
                   .jD        (n)   Julian date(s)
                   .r        (3,n)  Position of spacecraft relative to planet
                   .rPlanetH (3,n)  Heliocentric position of planet (ecliptic)
 d       (1,1)    Function data
                   .magModel   (BDipole)
                   .atmModel   (AtmDens1, AtmDens2, AtmJ70)
                   .j70, needed for that atmosphere model only
Outputs
 env     (1,1)   Environment model data
                  .planet         (:)   Planet name
                  .radiation     (1,1)  Black body radiation
                  .albedo        (1,1)  Planet albedo fraction
                  .radius        (1,1)  Planet equatorial radius
                  .mu            (1,1)  Gravitational parameter
                  .uSun          (3,n)  Unit vector to sun, ECI frame
                  .solarFlux     (1,n)  Solar radiation flux (W/m2)
                  .altitude      (1,n)  Altitude above the planet
                  .rho           (1,n)  Atmospheric density*
                  .bField        (3,n)  Magnetic field strength*
                  .radiationFlux (1,n)  Planetary radiation flux (W/m2)*
                  .albedoFlux    (1,n)  Planetary albedo flux (W/m2)*
                                         * don't apply to the sun.
References Altitude(), and(), AtmDens1(), AtmDens2(), AtmJ70(), BDipole(), CEcl2Eq(), Constant(), EarthAlb(), EarthRad(), Eclipse(), isempty(), length(), Mag(), Plot2D(), SailDisturbance(), SailEnvironment(), SolarFluxPrediction(), square(), SunV1(), Unit(), vector(), and zeros().
Referenced by EnvironmentStruct(), FSailCombined(), InitializeSailSim(), RHS2DOrbit(), SailDisturbance(), and SailEnvironment().
SailEphemAlmanac()
function SailEphemAlmanac (in jD, in d)
 This function obtains the moon position using MoonV1. The function
 PlanetPosition must be initialized with the desired planet IDs before
 calling this function. This format is for use with FSailCombined.
 Note that the planet IDs are 1-9, the Moon ID is 10, and the sun ID is 0.
 If called with a vector of dates will compute the location of the
 center only (batch mode).
See also
PlanetPosition and PlanetPosJPL.
Form
 rB = SailEphemAlmanac( jD, d )
Inputs
 jD        (1,1)     Julian date(s).
 d          (:)      Data structure.
                     .kP      Array of planet IDs
                     .center  Index of gravity center, used in batch mode
Outputs
 rB        (3,:)     Position of planets OR positions of center planet
References and(), Date2JD(), FSailCombined(), isempty(), length(), MoonV1(), PlanetPosition(), PlanetPosJPL(), SailEphemAlmanac(), vector(), and zeros().
Referenced by FSailCombined(), and SailEphemAlmanac().
SailEphemEarth()
function SailEphemEarth (in jD, in ignoredArg)
 For use with FSailCombined.
See also
SunV2 and CEcl2Eq.
Form
 rB = SailEphemEarth( jD, d )
Inputs
 jD        (1,:)     Julian date.
 d          (:)      Data structure - unused.
Outputs
 rB        (3,:)     Position of Earth
References and(), CEcl2Eq(), Date2JD(), FSailCombined(), and SunV2().
SailEphemJPL()
function SailEphemJPL (in jD, in d)
 This function fixes the moon position to be heliocentric from geocentric.
 If you are using the Moon you should be using the Earth too. The function
 PlanetPosJPL must be initialized with the desired planet IDs before
 calling this function. You do this by calling
 PlanetPosJPL( 'initialize', 1:9 )
 This format is for use with FSailCombined.
See also
PlanetPosJPL.
Form
 rB = SailEphemJPL( jD, d )
Inputs
 jD        (1,1)     Julian date.
 d          (:)      Data structure.
                     .kP   Array of planet IDs
Outputs
 rB        (3,:)     Position of planets
References Date2JD(), FSailCombined(), isempty(), PlanetPosJPL(), and SailEphemJPL().
Referenced by FSailCombined(), and SailEphemJPL().
SailForceSubplots()
function SailForceSubplots (in f, in n, in s, in q, in c)
 Enter q to view clock angles.
See also
QSail.
 Since version 7.
Form
 SailForceSubplots( f, n, s, q )
Inputs
 f             (3,1)  Force vector
 n             (3,1)  Sail front normal vector
 s             (3,1)  Unit vector to sun
 q             (4,1)  Reference quaternion
Outputs
 none
References and(), AnglePatch(), Cross(), Dot(), Eul2Mat(), Mag(), Map(), NewFig(), PlotSailForce2D(), PlotVector(), Q2Mat(), QSail(), QSteeringYAligned(), QTForm(), quaternion(), SailForceSubplots(), set(), Unit(), UToConeClock(), and vector().
Referenced by SailForceSubplots().
SailMesh()
function SailMesh (in x, in y, in hFunc, in d, in nRefine)
 This can be used to model a sail shape such as billow. The x and y vectors
 should decribe the circumference of the sail. The origin is added so the
 mesh resembles a refined pinwheel.
 The height function is of the form:   HMesh( x, y, d )
 where x and y can be arrays. d is a data structure containing any
 user-defined fields. A function 'DefaultH' is provided for testing.
 The built-in demo creates a circular sail and a quadrant.
 Since version 7.
Form
 [v, f] = SailMesh( x, y, hFunc, d, nRefine )
Inputs
 x        (1,m)    x locations of mesh
 y        (1,m)    y locations of mesh
 hFunc     (:)     Function for h positions (string or handle)
 d         (:)     Data structure to pass to z function
 nRefine  (1,1)    Number of times to refine mesh. Default is once.
Outputs
 v        (:,3)    Vertices
 f        (:,3)    Faces
References and(), Demo(), HCircularBillow(), Initialize(), NewFig(), SailMesh(), set(), vector(), and zeros().
Referenced by SailMesh().
SailOrbitContours()
function SailOrbitContours (in BetaFunction, in betaC, in x, in z, in varargin)
 BetaFunction is a function computing sail loading, i.e.
 [angle,beta] = BetaFunction( x, z, arg1, arg2, ... )
See also
SampleOrbitContours.
 Since version 7.
Form
 [c,h] = SailOrbitContours( BetaFunction, betaC, x, z, varargin )
References and().
SailPatchVertices()
function SailPatchVertices (in kAxis)
The sail patch is a diamond with length 0.5 along booms. The default normal is the body X axis. Use a kAxis of 2 or 3 to put the sail normal along Y or Z, respectively.
Form
 v = SailPatchVertices( kAxis )
Inputs
 kAxis     (1,1)       Sail normal convention. 1 - x-axis (default)
                                               2 - y-axis
                                               3 - z-axis
Outputs
 v         (3,4)        Vertices for a sail patch
References AddAxes(), Demo(), length(), NewFig(), vector(), and zeros().
Referenced by PlotSailClock2D(), and VisualizeSailAttitude().
SailPropsToAccel()
function SailPropsToAccel (in area, in mass)
 Will create a matrix if two vectors are input. Otherwise it will output
 a row vector. Has a built-in demo showing the impact of sail sizing.
 Since version 7.
Form
 acc0 = SailPropsToAccel( area, mass )
Inputs
 area          (1,m)  Sail area (m2)
 mass          (1,n)  Sail mass (kg)
Outputs
 acc0     (1,n) or (m,n) Characteristic acceleration, m/s2
References and(), Demo(), and vector().
Referenced by DisplaySailProperties(), GeoOptimalMission(), GeoSwitchingMission(), and MakeSquareSail().
SailSMAChange()
function SailSMAChange (in type, in a0, in accel, in nOrbits, in direction)
Form
 [a,t] = SailSMAChange( type, a0, accel, nOrbits, direction )
Inputs
 type
 a0
 accel
 nOrbits
 direction
Outputs
 a
 t
Referenced by GeoSwitchingMission().
SARosenbrock()
function SARosenbrock (in x, in ignoredArg)
 Given the constraint that x(1) and x(2) be between
Form
 f = SARosenbrock( x, d )
Inputs
 x              (2,1)  Value of x
 d              (1,1)  Structure to pass to fun (not used)
Outputs
 f              (1,1)  Cost
References and(), and SARosenbrock().
Referenced by SARosenbrock().
SATestFun()
function SATestFun (in x, in ignoredArg)
 Given the constraint that -2 < x < 2
Form
 f = SATestFun( x, d )
Inputs
 x              (1,1)  Value of x
 d              (1,1)  Structure to pass to fun (not used)
Outputs
 f              (1,1)  Cost
SearchVaneAngles()
function SearchVaneAngles (in Td, in theta0, in g, in env, in p, in d)
Actual torque is computed using SailDisturbance. Requires 3 or more vanes for a 3 axis solution. The angles are limited to +/- 90 degrees.
Form
 [theta,k] = SearchVaneAngles( Td, theta0, g, env, p, d )
Inputs
 Td       (3,1)     Torque demand (N)
 theta0   (1,n)     Initial guess
 g         (:)      Sail CAD model struct
 env       (:)      Sail environment struct
 p         (:)      Sail profile struct
 d         (:)      Sail disturbance options struct
Outputs
 theta    (1,n)     Angles found
 k        (1,1)     Number of iterations
References Initialize(), isempty(), Mag(), and SailDisturbance().
shiftMutation()
function shiftMutation (in par, in bounds, in genInfo, in Ops)
 to another position.
 Since version 7.
Form
 [child] = shiftMutation(par,bounds,genInfo,Ops)
Inputs
 par               the first parent ( [solution string function value] )
 bounds            the bounds matrix for the solution space
 Ops               Options for binaryMutation [gen prob_of_mutation
 genInfo
Outputs
 child
References and().
simpleXover()
function simpleXover (in p1, in p2, in bounds, in Ops)
 point crossover.
 Since version 7.
Form
 [c1,c2] = simpleXover(p1,p2,bounds,Ops)
Inputs
 p1              the first parent ( [solution string function value] )
 p2              the second parent ( [solution string function value] )
 bounds          the bounds matrix for the solution space
 Ops             Options matrix for simple crossover [gen #SimpXovers].
Outputs
 c1
 c2
References and().
Referenced by ga().
SimulatedAnnealing()
function SimulatedAnnealing (in fun, in x, in d, in s)
 f = fun( x, d );
 where f is the cost or 'energy'
 Since version 7.
Form
 [xOpt, fPlot, err] = SimulatedAnnealing( fun, x, d, s )
Inputs
 fun            (1,:)  Function to be optimized
 x              (:,1)  Initial guess
 d              (1,1)  Structure to pass to fun
 s              (1,1)  Optional structure of parameters
Outputs
 xOpt           (:,1)  Final estimate
 fPlot          (1,:)  Cost plot
 err            (1,:)  Error message
References and(), Demo(), OptTestFunRosenbrock(), Plot2D(), SimulatedAnnealing(), and Step().
Referenced by SimulatedAnnealing().
SingleCrossover()
function SingleCrossover (in p1, in p2, in ignoredArg, in opts)
 the two parents.
 The user supplies two options:
 nCross, number of crossovers each generation, and
 pCross, probability of crossover between selected parents.
 The first option, iGen, is provided by the genetic algorithm.
Form
 [c1, c2] = SingleCrossover(p1, p2, bounds, opts)
Inputs
 p1                (1,m+1)  First parent
 p2                (1,m+1)  Second parent
 bounds            (m,2)    Variable bounds (-/+)
 opts              (3)      Options, [iGen nCross pCross]
Outputs
 c1                (1,m+1)  First child
 c2                (1,m+1)  Second child
References and(), and length().
singlePtX()
function singlePtX (in p1, in p2, in bounds, in Ops)
 a uniform probability distribution.
 Since version 7.
Form
 [c1,c2]= singlePtX(p1,p2,bounds,Ops)
Inputs
 p1              the first parent ( [solution string function value] )
 p2              the second parent ( [solution string function value] )
 bounds          the bounds matrix for the solution space
 Ops             Options matrix for simple crossover [gen #SimpXovers].
Outputs
 c1
 c2
References and().
SolarPressureForce()
function SolarPressureForce (in area, in nB, in uSun, in flux, in optical, in emissivity)
Returns both the solar force and membrane temperature on each element. The optical coefficients may be arrays or constant over all elements. Has a built-in demo.
Form
 [f, T, fT] = SolarPressureForce( area, nB, uSun, flux, optical, emissivity )
Inputs
 area       (1,n)    Vector of areas
 nB         (3,n)    Element normals in the body frame
 uSun       (3,1)    Unit vector to sun in body frame
 flux       (1,1)    Incoming flux, W
 optical     (:)     Optical coefficient structure
                      .sigmaS (n,2) or (1,2)
                      .sigmaD (n,2) or (1,2)
                      .sigmaA (n,2) or (1,2)
 emissivity (n,2)    Front and back thermal emissivity, can be [1,2]
Outputs
 f    (3,n)    Element forces (N)
 T    (1,n)    Element temperatures (k)
 fT   (3,1)    Total force on component (N)
References and(), Demo(), length(), Plot2D(), SolarFlx(), SolarPressureForce(), Unit(), vector(), and zeros().
Referenced by DrawSailMeshVectors(), and SolarPressureForce().
SolveVaneAngles()
function SolveVaneAngles (in Td, in theta0, in g, in env, in p, in d)
Actual torque is computed using SailDisturbance. The vanes are assumed to be on the Z axis.
Form
 [theta,k] = SolveVaneAngles( Td, theta0, g, env, p, d )
Inputs
 Td    (2,1)   Torque
 g      (.)     CAD data structure
 env   (.)     Environment data structure (from SailEnvironment)
 p      (.)     Profile data structure
 d      (.)     Disturbance data structure
Outputs
 theta (1,:) Vane angles
 k     (1,1) Number of iterations
References and(), and Jacobian().
SPIGuidance()
function SPIGuidance (in t, in x, in d, in env)
Decrease the semi-major axis to 0.48 AU then increase the inclination to 60 degrees. This function has a persistent variable for switching phases. The phase is reset to 1 when the input time is 0. The cone and clock angles follow McInnes' convention.
Form
 [q,alpha,delta] = SPIGuidance( t, x, d, env )
Inputs
 t         (1,1)      Time
 x         (6,n)      Heliocentric state
 d          (:)       Data structure
                       .mu  (1,1)   Gravitational parameter
 env        (:)       Environment structure - unused
Outputs
 q        (4,n)       Inertial to body quaterion
 alpha    (1,n)       Cone angle
 delta    (1,n)       Clock angle
References and(), Imager(), and McInnes().
SteeringAnglesToQ()
function SteeringAnglesToQ (in incidence, in clock, in uSun, in r, in v, in c)
Clock angle is measured around the sun direction from the y axis of the reference frame. This function aligns the body y axis with the reference y direction. If the reference quaternion is known it may be input directly.
Form
 q = SteeringAnglesToQ( incidence, clock, uSun, r, v, c )
 q = SteeringAnglesToQ( incidence, clock, qRef )
Inputs
 incidence    (1,1)        Sun incidence angle (rad)
 clock        (1,1)        Clock angle (rad)
 qRef         (4,1)        Reference quaternion
    OR
 uSun         (3,1)        Unit vector to the sun
 r            (3,1)        Orbital position
 v            (3,1)        Orbital velocity
 c            (1,1)        Sign convention*   (Optional, default is 1)
Outputs
 q       (4,1)     Inertial to body quaternion
See also
QSail
References and(), Eul2Mat(), get(), isempty(), Mat2Q(), Q2Mat(), QSail(), QTForm(), quaternion(), SteeringAnglesToQ(), Unit(), vector(), and VisualizeSailAttitude().
Referenced by SteeringAnglesToQ().
StripedQuadrant()
function StripedQuadrant (in l, in nStripes, in billow, in nSub)
 This function has a built-in demo which draws a quadrant colored by
 vertical displacement. The billow is assumed quadratic, with a billow
 fraction used to define the billow as a percent of the stripe width.
 If a quadrant edge is 10 m, and there are 4 stripes, each will be about
 1.76 m wide. The billow fraction operates on this dimension. If nSub
 is not entered a value between 2 and 6 will be selected based on the
 amount of billow. The minimum number of stripe subdivisions is two.
 Since version 7.
Form
 [v, f] = StripedQuadrant( l, nStripes, billow, nSub )
Inputs
 l          (1,1) Length of quadrant edge along x/y axes (not hypotenuse)
 nStripes   (1,1) Number of stripes
 billow     (1,1) Billow fraction, between 0 and 1
 nSub       (1,1) Subdivisions (rows of faces) per stripe, optional
Outputs
 v          (:,3) Vertices
 f          (:,3) Faces
References and(), Demo(), length(), Mag(), NewFig(), Quadratic(), StripedQuadrant(), Unit(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by StripedQuadrant().
SubL1Accel()
function SubL1Accel (in dX, in theta, in phi)
 L1 is at about 0.01 AU, equivalent to about 237 Earth radii.
 Assumes a circular orbit of the Earth-Moon barycenter at 1 AU.
 The angles theta and phi measure the displacement of the sail from the
 Sun-Earth line.
 Note: Unlike Carl Sauer's plotted results, a nonzero theta or phi seem to
 push the acceleration completely off the radial direction.
Form
 [a, a0, alpha] = SubL1Accel( dX, theta, phi )
Inputs
 dX         Distance from the Earth, AU
 theta      Ecliptic longitude (rad)
 phi        Ecliptic latitude (rad)
Outputs
 a          Sail acceleration at station
 a0         Characteristic accel, km/s2
 alpha      Sail normal angle
Reference: Carl G. Sauer, The L1 Diamond Affair. 14th AAS/AIAA Space Flight Mechanics Conference. Maui, Hawaii, 2004. AAS 04-278
References and().
SunGuidance()
function SunGuidance (in ignoredArg, in x, in d, in env)
The available methods are:
 'semi-major axis'
 'eccentricity'
 'inclination'
 'ascending node'
 'sun-pointing', 'sun'
 'edge-on', 'off'
Form
 [q,cone,clock,u] = SunGuidance( t, x, d, env )
Inputs
 t         (1,1)      Time
 x         (6,n)      Heliocentric state
 d          (:)       Data structure
                       .method   (:)   Method string
                       .dir     (1,1)  Direction flag
                       .mu      (1,1)  Gravitational parameter
Outputs
 q        (4,n)       Inertial to body quaterion
 cone     (1,n)       Cone angle (rad)
 clock    (1,n)       Clock angle (rad)
 u        (3,n)       Sail normal vector in inertial frame
See also
LocallyOptimalTraj
References Cone(), Constant(), LocallyOptimalTraj(), vector(), and zeros().
swapmutate()
function swapmutate (in par, in bounds, in genInfo, in Ops)
 a permutation
 Since version 7.
Form
 [child] = swapmutate(par,bounds,genInfo,Ops)
Inputs
 par               the first parent ( [solution string function value] )
 bounds            the bounds matrix for the solution space
 Ops               Options for binaryMutation [gen prob_of_mutation]
 genInfo
Outputs
 child
References and().
threeswapMutation()
function threeswapMutation (in p, in bounds, in genInfo, in Ops)
 chosen genes in a permutation
 Since version 7.
Form
 [c] = threeswapMutation(p,bounds,genInfo,Ops)
Inputs
 parent           the first parent ( [solution string function value] )
 bounds           the bounds matrix for the solution space
 Ops              Options for binaryMutation [gen prob_of_mutation]
Outputs
 c
References and().
TorqueToCM()
function TorqueToCM (in T, in f, in Cp)
 The torque model is:
 T = (Cp - Cm) x F
Form
 cM = TorqueToCM( T, f, Cp )
Inputs
 T     Torque
 f     Force acting to create the torque
 Cp    Center of pressure - optional
Outputs
 cM    Center of mass
References TorqueToCM().
Referenced by TorqueToCM().
tournSelect()
function tournSelect (in oldPop, in options)
 Since version 7.
Form
 [newPop] = tournSelect(oldPop,options)
Inputs
 oldPop                 the current population
 options                options to normGeomSelect [gen tournament_size]
Outputs
 newPop                 the new population selected from the oldPop
References and(), length(), and normGeomSelect().
TwoBodyRateModel()
function TwoBodyRateModel (in x, in ignoredArg, in force, in torque, in g, in p, in hW)
 The core body should be body 1 and the boom body 2 in the CAD model.
 The gimbal rates are termed aDot.
Form
 xDot = TwoBodyRateModel( x, t, force, torque, g, p, hW )
Inputs
 x             (15,1)   The state vector [q;omega;a;aDot]
 t             (1,1)    Time (unused)
 force         (.)      Force structure
                         .totalBody   (3,1,2) Total torque on the vehicle
 torque        (.)      Torque structure
                         .totalBody   (3,1,2) Total torque on the vehicle
 g             (1,1)    CAD model
 p             (.)     Profile
                         .axis
 hW            (3,1)    Stored angular momentum, body frame
Outputs
 xDot          (7+2n,1)  [qDot;omegaDot;aDot;aDDot]
References and(), HingeRotationMatrix(), Skew(), SkewSq(), vector(), and zeros().
TwoDOptimalSailAngle()
function TwoDOptimalSailAngle (in x, in ignoredArg)
For use with indirect optimization using costates.
Form
 alpha = TwoDOptimalSailAngle( x, t )
Inputs
 x          (:,:)  [r;u;v;lambdaR;lambdaU;lambdaV];
 t          (1,:)  Time (not used)
Outputs
 alpha      (1,:)  Sail in-plane angle (rad)
References and(), vector(), and zeros().
Referenced by CostSail2D(), and RHSOpt2DOrbit().
uniformMutate()
function uniformMutate (in parent, in bounds, in Ops)
 a uniform probability distribution.
 Since version 7.
Form
 [parent] = uniformMutate(parent,bounds,Ops)
Inputs
 parent            the first parent ( [solution string function value] )
 bounds            the bounds matrix for the solution space
 Ops               Options for uniformMutation [gen #UnifMutations]
Outputs
 parent
References and().
uniformxover()
function uniformxover (in par1, in par2, in bounds, in Ops)
 crossover on a permuation string.
 Since version 7.
Form
 [ch1,ch2,t] = uniformxover(par1,par2,bounds,Ops)
Inputs
 par1             the first parent ( [solution string function value] )
 par2             the second parent ( [solution string function value] )
 bound            the bounds matrix for the solution space
 Ops              Options matrix for simple crossover [gen #SimpXovers].
Outputs
 c1
 c2
 t
References and().
UpdateSailOpticalProps()
function UpdateSailOpticalProps (in g, in optical, in emissivity, in infrared)
To convert McInnes coefficients to this format see OpticalMcInnesToPSS.
Form
 g = UpdateSailOpticalProps( g, optical, emissivity )
 g = UpdateSailOpticalProps( g, optical, thermal, infrared )
Inputs
 g           (:)     CAD model
 optical     (:)     Struct of optical properties
                     .sigmaA (1,2)  Absorptive coefficient (front/back
                     .sigmaD (1,2)  Diffuse coefficient
                     .sigmaS (1,2)  Specular coefficient
                     .sigmaT (1,2)  Transmissivity coefficient
 emissivity  (1,2)   Emissivity (front/back) OR thermal struct
 infrared    (:)     Same as optical but for infrared band
                     .sigmaRA (1,2)  Absorptive coefficient (front/back
                     .sigmaRD (1,2)  Diffuse coefficient
                     .sigmaRS (1,2)  Specular coefficient
                     .sigmaRT (1,2)  Transmissivity coefficient
Outputs
 g      (:)     Update CAD model
 Copyright 2009 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since version 9.
References and(), length(), McInnes(), and OpticalMcInnesToPSS().
UToConeClock()
function UToConeClock (in u, in r, in v, in s, in c)
 The cone and clock system is defined with the X axis along the sun
 vector s; this may be towards or away from the sun. The remaining axes are
 defined by the cross product of X with either the orbit normal or the
 velocity vector. The clock angle is measured from the Y axis.
 See QSail for detailed frame descriptions.
 If the sail reference frame quaternion is known it can be passed in
 directly, or else the remaining inputs are passed to QSail.
 u should be in the same hemisphere as the reference X axis.
 Type UToConeClock for a demo showing the unit vectors for a circular
 orbit around the sun.
 Since version 7.
 Forms:
 [cone, clock] = UToConeClock( u, q )
 [cone, clock] = UToConeClock( u, r, v, s )
 [cone, clock] = UToConeClock( u, r, v, s, c )
 [cone, clock] = UToConeClock( u, [], v, s )
 [cone, clock] = UToConeClock( u, [], v, s, c )
Inputs
 u             (3,n) Unit vectors
 r             (3,:) Position vector (optional, for orbit normal reference)
 v             (3,:) Velocity vector
 s             (3,:) Sun unit vector
 c             (1,1) Sun sign convention (1 towards, -1 away)
Outputs
 cone          (1,:) Cone angle (rad)
 clock         (1,:) Clock angle (rad)
Reference: Dachwald, B., "Low Thrust Trajectory Optimization and Interplanetary Mission Analysis Using Evolutionary Neurocontrol," PhD Thesis Universitat Bundeswehr Munchen, FRG, April 2004, p. 8.
See also
: QSail
References and(), Cone(), ConeClockToU(), Constant(), Demo(), Dot(), Plot2D(), QSail(), QTForm(), quaternion(), Unit(), UToConeClock(), vector(), and zeros().
Referenced by PlotSailClock2D(), SailForceSubplots(), and UToConeClock().
VaneAngles()
function VaneAngles (in areaVane, in momentArm, in Tcommand, in solarFlux)
Uses a simple sine relation.
Form
 theta = VaneAngles( areaVane, momentArm, Tcommand, solarFlux )
Inputs
 areaVane        (n,1)        Area of each vane (m^2)
 momentArm   (1,1) or (n,1)   Moment arm of each vane on sail (m)
 Tcommand        (1,1)        Roll torque (Nm)
 solarFlux       (1,1)        Solar flux, optional. Default is 1 AU. (W)
Outputs
 theta           (n,1)        Vane angles
References abs(), and isempty().
VarEqSailPlanet()
function VarEqSailPlanet (in rho, in z, in omega)
Form
 M = VarEqSailPlanet( rho, z, omega )
Inputs
 rho     (1,1)    Amplitude
 z       (1,1)    Anti-sun displacement
 omega   (1,1)    Orbit rate
Outputs
 M       (2,2)    Dynamics matrix
Reference: Colin R. McInnes, "Solar Sailing: Technology, Dynamics and Mission Applications", Springer Praxis, London, 1999. p. 204
References McInnes().
VisualizeSailAttitude()
function VisualizeSailAttitude (in q, in uSun, in q2, in c, in kAxis)
The sail is assumed to have a body frame with a +X front normal and the sail membrane in the Y/Z plane, unless a different kAxis is entered. This actually draws two patches, a front and a back; the back is a darker gray.
If a second quaternion is entered clock angle is computed from the reference y axis to the sail back normal (nominal force direction).
Form
 [cone, clock] = VisualizeSailAttitude( q, uSun, q2, c, kAxis )
Inputs
 q                 (4,1)  Sail attitude quaternion (inertial to body)
 uSun              (3,1)  Vector to sun  (inertial)
 q2                (4,1)  Second set of reference axes (inertial to ref)
 c                 (1,1)  Sign convention for clock angle, measured
                          about direction TO the sun (+1) or AWAY from
                          the sun (-1). Default is +1.
 kAxis             (1,1)  Sail normal convention: [1/x], 2/y, 3/z.
Outputs
 cone              (1,1)  Cone angle
 clock             (1,1)  Clock angle
References AddAxes(), and(), AnglePatch(), Cone(), Dot(), DrawCircularPlane(), isempty(), QTForm(), quaternion(), QUnit(), SailDefaultColors(), SailPatchVertices(), set(), square(), TitleS(), Unit(), and vector().
Referenced by QSteeringYAligned(), and SteeringAnglesToQ().