PSS MATLAB Toolboxes: Orbit Functions
Orbit Functions
Orbit Module
The Orbit module functions.
Directories
directory Constellations
Element sets for constellations.
directory Demos
directory Glideslope
Glideslopes for rendezvous and circumnavigation.
directory GravityModels
directory OrbitControl
Compute gains, delta-V's and accelerations for orbit control.
directory OrbitCoord
Transformations between orbital state representations including equinoctial elements and rotating frames.
directory OrbitData
Orbit data such as two-line elements and constants.
directory OrbitManeuver
Compute delta-Vs for various maneuvers.
directory OrbitMechanics
Orbit mechanics including Kepler propagation, two-line elements, J2 effects, time of flight, sun synchronous elements, and variational equations.
directory OrbitPropagatorGUI
High-fidelity orbit propagation GUI.
directory OrbitSim
Orbit simulation and propagation functions.
directory RHSOrbit
Orbit dynamics functions for integration.
directory Visualization
Plotting functions specific to orbits.
Description
Files
file Alfriend2El.m
Convert an Alfriend orbital element set into the standard orbital element set [a,th,i,q1,q2,W] -> [a,i,W,w,e,M].
file FOrbLEOPStopping.m
Its companion function is FOrbLEOP.
Functions
function A2Apogee (in a, in e)
Computes the apogee radius from a and e.
function A2Perige (in a, in e)
Computes the perigee radius from a.
function AB2RADec (in i, in L, in w, in alpha, in beta)
Convert angles to right ascension and declination.
function AccelToThrustAndQ (in a, in m, in u)
Convert an acceleration vector into a thrust quaternion.
function AdjustMeanAnomaly (in el, in jD0, in jD)
Adjusts mean anomaly in an elements vector for a different start time.
function AE2RPRA (in a, in e)
Converts semi-major axis and eccentricity to right perigee and apogee.
function AE2VR (in a, in e, in nu, in mu)
Computes v and r given a, e and nu.
function AENuToVelAltFpa (in a, in e, in nu, in Rp, in mu)
Convert semi-major axis & ecc.
function AERToNu (in a, in e, in r)
Converts semi-major axis, eccentricy and r to true anomaly.
function AFLTSpiral (in a0, in dV, in accel, in mu)
Low thrust delta v between two circular orbits.
function AGravity (in nZ, in nT, in r, in lambda, in theta, in s, in c, in j, in mu, in a)
Compute the gravitational acceleration in spherical coordinates.
function AGravityC (in r, in nN, in nM, in s, in c, in j, in mu, in a, in useNormM)
Compute the gravitational acceleration in cartesian coordinates.
function APlanet (in r, in mu, in rho)
Perturbing acceleration due to a planet on a spacecraft.
function ApogeeDV (in eT, in iT, in a2, in e2, in i2, in mu)
Delta-V to change apogee.
function ApogeeRaisingDeltaV (in r, in v, in rDes, in aT)
Compute two delta-v's to raise the apogee and circularize the orbit.
function AttitudeFrames (in r, in v, in qECIToBody, in jD, in len)
Draw attitude frames.
function AZLaunch (in i, in lat)
Launch azimuth to achieve a desired orbit inclination.
function BallisticCoefficient (in cD, in u, in g, in varargin)
Compute the ballistic coefficient from a CAD model.
function CartOrb2Cyl (in x)
Convert a cartesian orbit state to cylindrical orbit coordinates.
function CEcl2SER (in jD)
Transformation matrix from ecliptic to Sun-Earth rotating frame.
function CEq2C (in eq)
Transformation matrix from equinoctial to cartesian coordinates.
function ChangePerigee (in d)
Compute the delta V required to change perigee.
function CircularManeuver (in p, in r, in m, in t, in uE)
Compute maneuver profile for a circular maneuver.
function CircularOrbitState (in R, in inc, in ra, in M, in n)
Compute inertial position and velocity given circular orbit elements.
function ClohessyWiltshire (in w, in t)
A special formulation of the Clohessy-Wiltshire equations.
function ComputeTLE (in elOsc, in jD, in Bstar)
Compute two-line elements from osculating elements.
function ConvertNORAD (in a, in threeLine)
Convert NORAD TLE string into a data structure.
function CoplanarOrbit (in el1, in deltaH)
Find a coplanar orbit with a different altitude.
function CostLowThrust2D (in lambda, in d)
Cost function for 2D low thrust trajectory optimization.
function CP2I (in i, in L, in w)
Transformation matrix from the perifocal frame to the inertial frame.
function CrossScaleConstellation (in l, in b)
Create a cross scale constellation.
function CT2R (in a, in e, in f, in at, in mu)
Converts tangential accelerations into radial using the true anomaly.
function CT2REl (in el, in at, in mu)
Converts tangential accelerations into radial using the elements vector.
function CT2REq (in eq, in aT, in mu)
Converts tangential accelerations into radial using equinoctial elements.
function CWSimAndPlot (in x0, in w, in dV, in t)
Visualize a set of maneuvers propagated with Clohessy-Wiltshire equations.
function CylOrb (in x, in a, in mu)
Right-hand-side of the cylindrical orbit equations about a mass point.
function CylOrb2Cart (in x)
Convert a cylindrical orbit state to a cartesian orbit.
function DiscreteTrajectoryToDeltaV (in p, in vMag)
Compute accelerations for a point to point trajectory.
function DLinOrb (in n, in dT)
Computes the linearized orbit equations for a discrete system.
function DoDeltaV (in el, in dV, in mu)
Updates orbital elements based on an impulsive delta-V.
function DrawOrbitPlane (in r, in v, in axesHandle)
Draw an orbit plane.
function DVAKM (in iT, in temp, in threeSig, in mF, in mO, in dV)
Computes the temperature required to achieve the desired delta-V.
function DVDisp (in i, in vA, in vT, in decErr, in vErr, in nPlot)
Computes the velocity and inclination errors for a delta V burn.
function DVGeoTrx (in lon, in box, in s, in c, in j, in mu, in a)
Delta-V needed to control the longitudinal acceleration in geo.
function DVGlideslope (in x0, in w, in N, in T, in rTarget, in vOrA)
Calculate delta-Vs for glideslope rendezvous.
function DVHoh (in r1, in r2, in v1, in mu)
Computes the delta-v for a coplanar Hohmann transfer.
function DVHohE (in e1, in a1, in e2, in a2, in mu)
Compute Hohmann transfer between two elliptical coplanar orbits.
function DVHohInc (in e1, in a1, in e2, in a2, in Di, in mu)
Compute impulses for an eccentric Hohmann transfer with a plane change.
function DVIDrift (in box, in year, in doPlot)
Computes inclination drift for geosynchronous orbits.
function DVLowThrust (in vI, in vF, in dI)
Delta-V from a circular to noncoplanar circular orbit.
function DVOCCapt (in muS, in muP, in r, in v)
Computes the optimal circular capture radius and delta-v.
function DVOHohmn (in R1, in R2, in rA, in rP, in mu, in muP)
Delta-v for injection into an interplanetary orbit using Olberth's method.
function DVOrbitDrag (in el, in nu, in b, in planet)
Compute the drag loss over an orbit arc in planetary orbit.
function DVReentry (in a, in e, in rEI, in c1, in c2, in mu)
Computes the delta-V for reentry from a near-circular orbit.
function DVTarget (in r1, in v1, in r2, in v2, in dT, in mu, in rPmin)
Perform targeting in Earth orbit using the Lambert algorithm.
function E2M (in ecc, in eccAnom)
Converts eccentric anomaly to mean anomaly.
function E2Nu (in e, in E)
Computes the true anomaly from the eccentric or hyperbolic anomaly.
function E2RAORP (in e)
Ratio of apogee radius to perigee radius given eccentricity for an ellipse.
function ECEFToECI (in gMT)
Compute the transformation matrix that rotates ECEF to ECI coordinates.
function ECI2OrbitPlane (in r, in n)
This function takes a position vector and orbit normal vector in ECI.
function ECIToRLP (in xS)
Transform from ECI to Rotating Libration Point Coordinates.
function El2Alfriend (in el, in nu)
Convert the standard orbital element set into an Alfriend orbital element set.
function El2Eq (in el)
Converts conventional elements to equinoctial elements.
function El2LKl (in el)
Converts orbital elements to commonly used angular quantities.
function El2RV (in el, in tol, in mu)
Converts orbital elements to r and v for an elliptic orbit.
function ElToMEq (in el, in mu)
Transforms Keplerian elements to modified equinoctial elements.
function Energy (in a, in mu)
Compute the energy for any orbit.
function ENUToECEF (in lat, in lon)
Compute the transformation matrix that rotates ENU to ECEF coordinates.
function Eq2El (in eq)
Converts equinoctial elements to Keplerian elements.
function Eq2RV (in eq, in tol, in mu)
Converts equinoctial elements to r and v for an elliptic orbit.
function FAero (in action, in modifier, in u, in t)
The aero force model.
function FAtmDensity (in action, in modifier, in u, in t)
Atmospheric density model function that calls the Jacchia J70 model.
function FBudget (in event, in x, in file, in title, in html)
Computes a fuel budget from a list of events.
function FEngine (in action, in modifier, in u, in t)
Computes the engine force vector in the ECI frame.
function FlightPathAngle (in r, in v, in mu)
Compute the flight path angle for a Cartesian state.
function FlightPathAngleFromCartEl (in el)
Compute the flight path angle from elements.
function FLowThrust2D (in t, in x, in flag, in d)
Derivatives for the low-thrust planar orbit problem.
function Flyby (in vA, in vD, in vP, in muP)
Calculates orbital elements and perigee radius for a planetary flyby.
function FOrb (in x, in t, in fType, in a, in mu)
Computes the right-hand-side of the orbit equations about a mass point.
function FOrbCart (in x, in t, in a, in mu)
Computes the right-hand-side of the orbit equations about a mass point.
function FOrbCartH (in x, in t, in accel, in gravityModel, in nN, in nM, in jD)
Computes the right-hand-side of a spherical harmonic orbit (Cartesian).
function FOrbHF (in x, in t, in options, in jD, in aExt, in mu, in s, in c, in j, in a)
High fidelity orbit model right-hand-side.
function FOrbHF2 (in t, in x, in flag, in d)
High fidelity orbit model designed to work with ode113.
function FOrbHFOP (in t, in x, in flag, in d)
High fidelity orbit model designed to work with ode113.
function FOrbLEOP (in t, in x, in d)
Orbit model for Launch and Early Orbit Operations.
function FOrbLowThrust (in t, in x, in flag, in d)
Right hand side of the planar orbit equations assuming constant thrust.
function FOrbLTE (in t, in x, in d)
Orbit model for low thrust escapes.
function FPA (in e, in nu)
Computes the flight path angle from eccentricity and true anomaly.
function FPlantNoise (in action, in modifier, in u, in t)
The plant noise model.
function FSolar (in action, in modifier, in u, in t)
The solar force model for OrbitPropagator.
function FVarEq (in x, in t, in eType, in aD, in tol, in mu)
Computes the right hand side of the variational equations.
function GetFuelBudgetDataFromCAD (in g)
Retrieve fuel budget information from a CAD model.
function GlideSlope (in uGS, in rTarget, in x, in rPlanet)
Compute the glide slope angle.
function GlideslopeCircumnav (in x0, in w, in N, in T, in rho, in a)
Calculate delta-Vs for a pulsed circumnavigation.
function GlideslopeGuidance (in x0, in w, in N, in T, in rTarget, in vCommand)
Guidance trajectory where range rate is proportional to range.
function GlideslopePlanner (in x0, in w, in d)
Calculate sequential glideslope maneuvers for planning purposes.
function GravityMap (in lat, in lon, in alt, in nN, in nM, in gravityModel, in f)
Create a gravity map from a gravity model.
function GroundCoverage (in xECI, in jD, in d)
Compute ground coverage for an orbit.
function GVEDynamics (in el, in mu)
Compute continuous-time relative dynamics for Gauss' variational equations.
function HEl (in el, in mu)
Computes orbit angular momentum from the elements vector.
function HEq (in eq, in mu)
Calculates the orbit angular momentum given the input in equinoctial elements.
function HohmannTransferRendezvous (in elT, in elC, in mu, in tol, in planet)
Compute delta-Vs for rendezvous using Hohmann transfers.
function IDrift (in W0, in i, in altitude, in qs)
Computes the inclination rate of an earth orbit due to the sun.
function InclinationRate (in x, in mu)
Finds the inclination rate and orbit normal vector.
function InitialOrientation (in r, in v, in uB, in uH)
Compute the initial quaternion and body rates for a circular orbit,.
function J2OrbitEffects (in a, in e, in i, in j2, in mu, in rP)
Compute J2 effects on the orbital elements - analytic model.
function J2Prop (in x0, in jD, in time, in gM, in showWaitBar)
Propagate an ECI state into the future with the J2 perturbation.
function K2L (in P1, in P2, in K)
Converts eccentric longitude to true longitude.
function L2K (in P1, in P2, in L)
Converts eccentric longitude to true longitude.
function LambertOpt (in r1, in v1, in r2, in v2, in dT, in mu)
Use Lambert with optimization of start and transfer time.
function LambertTOF (in r1, in r2, in dT, in orbitType, in mu, in tol, in maxIter)
Solves the Lambert time of flight problem using Battin's method.
function LatLonToRAz (in lat0, in lon0, in latF, in lonF, in Rp)
Compute range and azimuth angle between two points on a sphere.
function LinOrb (in x, in n, in aD, in dT)
Computes the linearized orbit equations.
function LoadGEM (in unNorm)
Load the GEMT1 data.
function LoadGravityModel (in action, in fileName, in isNormalized)
Load a spherical harmonic gravity model (.geo) from GSFC/U.
function LoadNORAD (in fName, in model, in kMax)
Load a set of NORAD elements (TLEs) and convert to Cartesian states.
function LocusOfVisibility (in rSat, in radiusPlanet, in n)
Determine the locus of visibility for a satellite above a planet.
function LonMot (in lon0, in lond0, in a, in t)
Computes the longitudinal motion due to an acceleration a.
function LowThrustControl (in x, in mode, in elTarget, in aMag, in tol, in angWidth)
Compute control acceleration for low thrust orbit raising.
function LowThrustEscape (in planet, in a0)
Compute the delta-V required for a low thrust escape.
function LowThrustSim (in a0, in aF, in uE, in thrust, in m0, in mu)
Simulate low thrust spacecraft.
function LQOrbitController (in x, in q, in r, in dT, in x0, in aD, in mu)
Creates a linear quadratic relative orbit controller.
function LTAN (in W, in jD)
Compute the local time of the ascending node.
function LTPlaneChange (in a0, in af, in dI, in accel, in mu)
Low-thrust transfer between two circular, nonplanar orbits.
function LTSpiral (in a0, in af, in accel, in mu)
Delta v of a low thrust spiral between two circular orbits.
function LTVCon (in r0, in r, in c1, in c2, in orbitType, in mu)
Solve the Linear Terminal Velocity Constraint problem.
function M2E (in e, in meanAnom, in tol, in nMax)
Computes the eccentric anomaly.
function M2EApp (in e, in meanAnom)
Approximate root to Kepler's Equation for elliptical and hyperbolic orbits.
function M2EEl (in ecc, in meanAnom, in tol, in nMax)
Eccentric anomaly for an ellipse.
function M2EHy (in e, in meanAnom, in tol, in nMax)
Eccentric anomaly for a hyperbola.
function M2Nu (in e, in M, in tol, in nMax)
Computes the true anomaly from the mean anomaly.
function M2NuAbs (in e, in M, in tol, in nMax)
Computes the true anomaly from the mean anomaly without wrapping.
function M2NuPb (in meanAnom)
Generate the true anomaly from the mean anomaly for a parabola.
function M2NuS (in e, in M)
Computes true anomaly from a series expansion.
function ManeuverDuration (in mI, in dV, in uE, in thrust)
Compute maneuver duration given constant thrust.
function ManeuverEnvelope (in f, in m)
Compute the maneuver envelope for a spacecraft rotating around another.
function MaximumDeltaV (in f, in uE)
Returns the maximum velocity change fraction.
function MeanAnom (in dt, in a, in p, in mu)
Computes the mean anomaly from change in time.
function MeanMotn (in a, in mu)
Computes the mean orbit rate for an elliptic orbit.
function MEQToECI (in r, in v)
Transform to ECI frame from tangential coordinates.
function MEqToEl (in x, in mu)
Transforms modified equinoctial elements to Keplerian elements.
function MEqToRV (in x, in mu)
Transforms modified equinoctial elements to r and v.
function ML2K (in P1, in P2, in meanLong, in tol, in nMax)
Eccentric longitude from the mean longitude by solving Kepler's equation.
function ML2KApp (in P1, in P2, in meanLong)
Approximate eccentric longitude from the mean longitude.
function N2A (in n, in mu)
Computes the semi-major axis given the mean orbit rate.
function NonDimensionalOrbit (in r, in v, in t, in mu, in rRef, in dir)
Dimensionalize or non-dimensionalize an orbit.
function NORAD (in dStart, in dEnd, in nPts, in model, in pType, in file)
Propagates the NORAD two line elements (TLE), ex.
function NORADToEl (in dStart, in dEnd, in nPts, in model, in s)
Convert NORAD to Keplerian elements.
function NormalizationMatrix (in nN, in nM)
Generate a normalization matrix for spherical harmonics.
function Nu2E (in e, in nu)
Converts true anomaly to eccentric or hyperbolic anomaly.
function Nu2M (in e, in nu)
Converts true anomaly to mean anomaly.
function Nu2MAbs (in e, in nu, in tol, in nMax)
Computes the mean anomaly from the true anomaly without wrapping btwn -pi / pi.
function NuInf (in e)
Computes the asymptote angle for a hyperbola.
function OptDIH (in e1, in a1, in e2, in a2, in Di, in mu)
Optimal inclination corrections for a Hohmann transfer with a plane change.
function OrbDecay (in h, in cD, in A, in m, in mu, in R, in rho0, in hScale)
Approximate time for an orbit to decay based on an exponential atmosphere.
function OrbElemDiff (in el0, in el, in type)
Computes the differences between orbital element vectors.
function OrbitalPlane (in rA, in inc, in jD, in color, in figH)
Display the orbital plane with the Earth.
function OrbitClosestPoint (in rEFTarget, in el, in jDEpoch, in n, in nOrbits)
Computes closest orbit point to points on the earth.
function OrbitDrag (in v0, in gamma0, in h, in bC)
Approximate the acceleration due to drag over an orbit arc, h0 to hF.
function OrbitFromSynodic (in elT, in p, in mu, in h)
Computes the elements of an orbit with the desired synodic period.
function OrbitInsertion (in rA, in phiM, in rM, in mu)
Compute orbit insertion velocity and flight path angle.
function OrbitJacobian (in t, in x, in d)
Computes the Jacobian for a spherical planet gravity model.
function OrbitProp (in x0, in time)
Propagate an ECI state into the future with point mass orbit.
function OrbitVel2D (in v0, in gamma0, in h0, in hF, in rE, in mu)
Compute (VF,gammaF) at hF from (v0,gamma0) at h0.
function OrbMnvrBielliptic (in rI, in rB, in rF, in mu)
Delta-V for a bielliptic orbit maneuver between circular orbits.
function OrbMnvrCircularize (in rI, in vI, in gammaI, in rF, in mu)
Computes the delta-V for a 2-burn transfer to a circular orbit at rF.
function OrbMnvrHohmann (in rI, in rF, in mu)
Computes the delta-V for a Hohmann transfer between circular orbits.
function OrbMnvrInclAndHohm (in rI, in rF, in iI, in iF, in mu)
Delta-V for a Hohmann transfer between circular non coplanar orbits.
function OrbMnvrInclination (in v, in e, in nu, in deltaI, in mu)
Computes the delta-V for an inclination correction.
function OrbMnvrInsertion (in r, in v, in rT, in vT, in rP, in i, in mu, in qCToP)
Computes the delta-V to insert into a planetary or lunar orbit.
function OrbMnvrLongAndIncl (in v, in iI, in iF, in deltaLon, in mu)
Delta-V for an longitude and inclination change maneuver for a circular orbit.
function OrbMnvrLongitude (in v, in i, in deltaLon, in mu)
Computes the delta-V for a longitude only maneuver for a circular orbit.
function OrbMnvrLowerApogee (in elI, in rAF, in mu)
Computes the delta-V to lower apogee.
function OrbMnvrOneTangent (in rI, in rF, in nuT, in type, in mu)
Computes the delta-V for a one-tangent transfer between coplanar orbits.
function OrbMnvrPerigee (in d)
Compute the delta V required to change perigee.
function OrbMnvrPhaseChange (in a0, in deltaA, in kTarget, in mu)
Computes the delta-V for a phase change.
function OrbMnvrSemimajor (in v, in a, in deltaA, in mu)
Computes the delta-V for a change in semi-major axis.
function OrbNEl (in varargin)
Conmputes the orbit normal from orbital elements.
function OrbNEq (in eq)
Computes the orbit normal from equinoctial elements.
function OrbRate (in r, in a, in mu)
Compute the orbital rate from distance and semi-major axis.
function OrbTrack (in r, in jD, in gType, in planet, in hFig)
Plot a planet-fixed orbit track in 2D or 3D.
function OrbTrackECI3D (in r, in planet, in hFig)
Plot an orbit track in the ECI frame.
function OrbView (in r, in jD)
View orbit related parameters on a quad chart.
function OverArea (in r, in lat, in lon)
Determine whether r is in a area on the surface of an Earth sphere.
function PAHohmn (in R1, in R2, in mu)
Computes the phase angles for a Hohmann intercept.
function Parameter (in e, in rP)
Computes the parameter for any orbit.
function PDrag (in r, in v, in mu, in R, in rho0, in h0, in hScale, in wP)
Dynamic pressure on a satellite based on an exponential atmospheric model.
function Period (in a, in mu)
Compute the period for an orbit.
function PeriodToSMA (in T, in mu)
Compute the semi major axis from the period.
function PlanetaryAccelerations (in r, in jD, in center)
Compute perturbations due to other planets aside from the center.
function Plot2DTrajectory (in lambda, in d, in units, in plotTitle)
Propagate and plot the planar trajectory from costates (indirect optimization).
function PlotLambertTransfer (in r1, in v1, in r2, in v2, in dT, in dV, in elT, in mu)
Plot a Lambert transfer trajectory as computed by DVTarget.
function PlotOrbitPage (in r, in t, in figTitle)
Create a plot page with 2D and 3D views of an orbit.
function PlotOrbitTransfer (in el1, in el2, in elT, in mu, in jdDep, in jdArr, in trans_dir)
Plot two initial orbits and a transfer orbit.
function PlotPlanetaryOrbit (in r, in p, in t, in jD0)
Plot the state in 3D with an planet map.
function PlotZermelo (in lambda, in d, in ignoredArg, in plotTitle)
Propagate and plot the Zermelo trajectory.
function ProcessASCIIGravityModel (in fileName)
Process an ascii file of spherical harmonic coefficients.
function PropagateLowThrust (in x0, in d)
Propagate a low thrust trajectory with constant thrust.
function PropagateOrbitPlugIn (in action, in modifier, in hFig, in position, in callback)
Main GUI for propagating an orbit using ode113 and user-selected models.
function PropagateTLE (in tVec, in file, in model)
Propagates the NORAD two line elements, ex.
function PropagateTLECommonTime (in jD0, in tVec, in file, in model)
Propagates a set of NORAD two line elements with a common time frame.
function PropEph (in elStart, in jd, in dT, in mu)
Propagates the ephemeris one step.
function PtchCnc (in vC, in vPC, in rC, in rPC, in muC, in muP)
Computes planet centered orbital elements.
function PToSMA (in p, in mu, in type)
Compute the semi-major axis from an orbit period or mean motion.
function RAEToM (in r, in a, in e)
Computes m, nu and E from r, a and e.
function RandomOrbit (in el, in el1S, in t, in mu, in n)
Monte-Carlo orbit simulation.
function RARP2A (in rA, in rP)
Computes the semi major axis from apogee and perigee radii.
function RARP2E (in rA, in rP)
Computes the eccentricity from apogee and perigee radii.
function RAzToLatLon (in r, in az, in lat0, in lon0, in R)
Transform (range,azimuth) to (latitude,longitude) coordinates.
function ReadHorizons (in file)
Reads in JPL Horizons data.
function ReadTopexPOE (in fileName, in m)
Reads a Topex Precision Orbit Ephemerides file.
function REl (in el)
Computes the orbit radius and the parameter from Keplerian elements.
function RelativeCoord (in r, in v, in r2, in v2)
Computes relative coordinates between two orbits.
function RelativeOrbitState (in x1, in x2)
Find the relative coordinate state vector between x2 and x1.
function RelState2Absolute (in x0, in xRel)
Given the reference absolute state, converts a relative orbit state to absolute.
function RendezvousPlanner (in rT, in vT, in rC, in vC, in dT, in planet, in mu, in tol)
Compute delta-Vs for rendezvous.
function REq (in eq)
Computes the orbit radius and the parameter from equinoctial elements.
function RHAzToECEF (in r, in h, in az, in latLon0, in R, in plt)
Transform (range,azimuth) to (latitude,longitude) coordinates.
function RHS2DPolarOrbit (in x, in ignoredArg, in d)
RHS for 2D polar orbit.
function RHSEquinoctial (in ignoredArg, in x, in d)
Right-hand-side for equinoctial elements.
function RHSGeoHarm (in x, in t, in d)
Computes the right hand side for a gravity model.
function RHSGeoJ2 (in x, in t, in d, in aExt)
Computes the right hand side for Earth gravity with J2.
function RHSLinOrb (in x, in ignoredArg, in n, in u)
Continuous form of linearized orbit (Hills equations).
function RHSOrbit (in x, in ignoredArg, in d)
Right hand side for a simple Cartesian orbit.
function RHSOrbit2D (in x, in t, in d)
Two dimensional orbit dynamics.
function RHSOrbitPlanetFixed (in x, in t, in d)
Cartesian orbital equations in a planet fixed (rotating) frame.
function RHSZermelo (in t, in x, in d)
Zermelo's differential equation right hand side.
function RLagrange (in rS, in mR, in lPoint)
Computes a collinear Lagrange point.
function ROrb (in e, in rp, in f)
Computes the orbit radius.
function RPQ (in e, in rP, in nu)
Computes the orbit position vector in the perifocal plane.
function RPRA2AE (in rP, in rA)
Converts perigee and apogee to semi-major axis and eccentricity.
function RPV2AE (in rP, in v, in mu)
Converts perigee and velocity at perigee to a and e.
function RToNu (in a, in e, in r)
Computes true anomaly from semi-major axis, eccentricity and radius.
function RV2A (in r, in v, in mu)
Computes the semimajor axis given position and velocity magnitudes.
function RV2AE (in r, in v, in mu)
Converts R and V to a, e, rP and rA.
function RV2El (in r, in v, in mu)
Converts Cartesian state to Keplerian orbital elements.
function RV2Eq (in r, in v, in mu)
Converts R and V to Equinoctial elements.
function RV2RaDec (in r, in v)
Right ascension and declination with their rates from position and velocity vectors.
function RVFromKepler (in elI, in t, in mu, in tol)
Generate an orbit by propagating Keplerian elements.
function RVOrbGen (in elI, in t, in uSun, in mu, in rPlanet, in tol)
Generate an orbit by propagating Keplerian elements.
function RVOrbHF (in r, in v, in jD, in options, in t, in aExt, in tol, in s, in c, in j, in mu, in a)
High fidelity orbit simulation with drag and planetary perturbations.
function RVSet2El (in r, in v, in mu, in tol)
Batch form of RV2El.
function RVToMEq (in r, in v, in mu)
Transforms elements r and v to modified equinoctial.
function SeeTLE (in group, in hours, in color)
View a set of satellite TLEs in Earth orbit, using TLEs from celestrak.
function SelectTLEGroup ()
A GUI to view / select from a list of TLE groups at www.celestrak.com.
function SemimajorAxisRevisit (in swath, in revisit, in mu, in rP, in day)
Computes semi-major axis from revisit and swath angle.
function SLR (in e, in a)
Computes the semi-latus rectum.
function SolveT (in vI, in vT, in rho0, in T)
Cost function for glideslope period solver.
function SolveTD (in vI, in vT, in rho0, in T)
Derivative for glideslope period solver.
function SpacecraftFromAccel (in sC, in s)
Size a spacecraft from acceleration time history.
function SphOI (in m, in M)
Computes the sphere of influence ratio.
function SphOrb (in x, in a, in mu)
Point mass orbit equations in equatorial spherical coordinates.
function StoppingConditions (in r, in v, in jD, in mu, in stopping, in planet)
Stopping conditions for an orbit.
function StoppingPlugIn (in action, in modifier, in hFig, in position, in callback)
Create a stopping conditions plug in for OrbitPropagator.
function SunSyncInclination (in a, in e, in j2, in mu, in R)
Compute the sun-synchronous inclination for an orbit.
function SunSyncNode (in lt, in jD)
Compute the ascending node for the desired local time.
function SynodicFromSemimajorAxes (in a1, in a2, in mu)
Computes the synodic period from semi-major axis.
function SynPer (in n1, in n2)
Computes the synodic period between two orbits.
function TARes (in r0, in r, in orbitType)
Resolves the transfer angle ambiguity.
function TEMEToPEF (in jD)
Computes the matrix from TEME to the pseudo-earth fixed frame.
function Tfr2Imp (in e1, in a1, in e2, in a2, in i1, in i2, in mu)
Two impulse optimal orbit transfer.
function Tfr3Imp (in e1, in a1, in e4, in a4, in n, in i1, in i4, in mu)
Three impulse orbit transfer.
function THohmn (in R1, in R2, in mu)
Computes all times for a Hohmann Transfer.
function TimeOfFlightHyperbola (in a, in e, in nu1, in nu2, in mu)
Time of flight in a hyperbola.
function TLETime (in tLE, in startDate, in endDate, in n)
Time vector for a TLE.
function TrajectoryOptimization (in d)
Performs indirect trajectory optimization on costates with fminsearch.
function TrajectoryPlot (in r, in t, in u, in varargin)
Draws a 2D or 3D trajectory plot.
function TransferAndPhaseAngle (in r1, in r2, in tT, in mu)
Computes the transfer and phase angle given transfer time.
function TransferTimeToDV (in elT, in elC, in transferTime, in mu, in tol, in planet)
Converts the transfer time to delta-V for a rendezvous.
function TriangularManeuver (in p, in r, in m, in t, in uE)
Compute maneuver profile for a triangular maneuver.
function TrueAnomalySpacing (in e, in nu0, in n, in duration, in nS, in eTol)
Generates an array of true anomalies.
function TrxCntrl (in eLon, in lonTol)
Plans delta-v maneuvers to correct triaxial motion.
function TTrnsHoh (in R1, in R2, in mu)
Computes the Hohman transfer time between two orbits.
function TWaitHoh (in R1, in R2, in mu)
Computes the wait time at the target.
function TwoObjectTrajectoryViewer (in action, in varargin)
Displays spacecraft and moon in a trajectory about the Earth in real time.
function UGravity (in nZ, in nT, in r, in lambda, in theta, in s, in c, in j, in mu, in a)
Compute the earth's gravitational potential.
function UnnormalizeGravity (in g)
Remove normalization from a gravity model.
function VarEqP (in eq, in aD, in tol, in mu)
Computes the right hand side of the equinoctial variational equations (polar).
function VarEqT (in eq, in aT, in tol, in mu)
Computes the right hand side of the variational equations (tangential)
function VarGausP (in el, in aD, in tol, in mu)
Computes the right hand side of the Gauss variational equations.
function VarGausT (in el, in aD, in tol, in mu)
Variational Keplerian equations with the acceleration in tangential coordinates.
function VDA (in d)
Computes the heliocentric departure vector for a spacecraft.
function VelAltFpaToAENu (in v, in h, in gamma, in mu, in R)
Converts flight path angle, velocity and r to orbital elements.
function VelAltFpaToHAE (in V, in h, in fpa, in h2, in mu, in R)
Compute (VF,gammaF) at hF from (V0,gamma0) at h0.
function VEscape (in r, in mu)
Computes the escape velocity.
function VInf (in a, in mu)
Computes the asymptotic velocity for a hyperbola (v infinity)
function VInfRPToRV (in vInf, in rP, in f, in mu, in i, in lon, in arg)
Generate RV from parameters v infinity and periapsis.
function VOrbit (in r, in a, in mu)
Computes the orbital velocity from radius.
function VPQ (in e, in p, in nu, in mu)
Computes the orbit velocity in the perifocal plane.
function VR2AE (in v, in r, in mu)
Computes sma and eccentricity given v and r.
function WalkerConstellation (in t, in p, in f, in inc, in sma, in doStar)
Compute orbital elements for a Walker constellation.
function ZermeloAnalyticalCost (in theta, in x1, in y1)
Computes the analytical cost for Zermelo's problem.
function ZermeloAnalyticalLambda (in x, in y, in v)
Computes the analytical lambda for Zermelo's problem.
function ZermeloCost (in lambda, in d)
Cost function of Zermelo's differential equations.
Function Documentation
A2Apogee()
function A2Apogee (in a, in e)
Form
 rA = A2Apogee( a, e )
Inputs
 a             (1,:)   Semi major axis
 e             (1,:)   Eccentricity
Outputs
 rA            (a,e)   Apogee radius
References and(), DupVect(), length(), and Mesh2().
Referenced by ApogeeDV(), and OptDIH().
A2Perige()
function A2Perige (in a, in e)
 Since version 1.
Form
 rP = A2Perige( a, e )
Inputs
 a                     Semi major axis
 e                     Eccentricity
Outputs
 rP                    Perigee radius
References: Bate, R. R., Fundamentals of Astrodynamics. pp. 20-40.
References abs(), DupVect(), length(), and Mesh2().
Referenced by EarthEclipseDuration(), and OptDIH().
AB2RADec()
function AB2RADec (in i, in L, in w, in alpha, in beta)
Converts angles in the orbit plane to right ascension and declination in the ECI frame.
Form
 [rA, dec] = AB2RADec( i, L, w, alpha, beta )
Inputs
 i                     Inclination
 L                     Longitude of the ascending node
 w                     Argument of perigee
 alpha                 Angle of the vector with respect to perigee
 beta                  Angle of the vector with respect to the orbit plane
Outputs
 rA                    Right ascension in the ECI frame
 dec                   Declination of the ECI fram
References and(), length(), RaDec2U(), U2RADec(), and vector().
AccelToThrustAndQ()
function AccelToThrustAndQ (in a, in m, in u)
 Type AccelToThrustAndQ for a demo.
Form
 [thrust, q] = AccelToThrustAndQ( a, m, u )
Inputs
 a            (3,:)     Acceleration vector(s)
 m            (1,1)     Mass (kg)
 u            (3,1)     Thruster unit force vector in the body frame
Outputs
 thrust       (1,:)     Thrust
 q            (4,:)     Quaternion
References AccelToThrustAndQ(), Demo(), length(), Mag(), Plot2D(), QForm(), quaternion(), U2Q(), Unit(), and vector().
Referenced by AccelToThrustAndQ().
AdjustMeanAnomaly()
function AdjustMeanAnomaly (in el, in jD0, in jD)
Only M is changed to account for a time difference. Epoch is the day for which the elements were generated. For example
 [el,jD0] = ISSOrbit;
generates current elements from two line elements downloaded from the web. jD0 is the Julian date of epoch.
Form
 el = AdjustMeanAnomaly(el,jD0,jD)
Inputs
 el  (1,6) [a i W w e M]
 jD0 (1,1) Julian date of epoch (days)
 jD  (1,1) Julian date of start (days)
Outputs
 el  (1,6) [a i W w e M]
References ISSOrbit(), Period(), and vector().
AE2RPRA()
function AE2RPRA (in a, in e)
Form
 [rP, rA] = AE2RPRA( a, e )
Inputs
 a               (1,:) Semi-major axis
 e               (1,:) Eccentricity
Outputs
 rP              (1,:) Perigee
 rA              (1,:) Apogee
References: Bate, R.R., et. al. Fundamentals of Astrodynamics, pp. 70-71.
References and().
Referenced by CoplanarOrbit(), and ThrustControlRaiseApogee().
AE2VR()
function AE2VR (in a, in e, in nu, in mu)
 Also gives the time for each step.
Form
 [v, r, t] = AE2VR( a, e, nu, mu )
Inputs
 a           (1,1)    Semi major axis
 e           (1,1)    Eccentricity
 nu          (1,n)    True anomaly (rad)
 mu          (1,1)    Gravitational parameter (default = 3.98600436e5)
Outputs
 v           (1,n)    Velocity
 r           (1,n)    Radius
 t           (1,n)    Time
References AE2VR(), and(), Nu2M(), Plot2D(), and RPRA2AE().
Referenced by AE2VR().
AENuToVelAltFpa()
function AENuToVelAltFpa (in a, in e, in nu, in Rp, in mu)
to velocity, altitude, flight path angle
 Since version 10.
Form
 [V,h,fpa] = AENuToVelAltFpa( a, e, nu, Rp, mu )
Inputs
 a               (1,1) Semi-major axis
 e               (1,1) Eccentricity
 nu              (1,:) True anomaly (rad)
 Rp              (1,1) Radius of planet (km)
 mu              (1,1) Gravitational constant (km^3/s^2)
Outputs
 V               (1,:) Velocity (km/s)
 h               (1,:) Altitude (km)
 fpa             (1,:) Flight path angle (rad)
References Altitude(), and Plot2D().
AERToNu()
function AERToNu (in a, in e, in r)
r and a must be in the same units. This only works for elliptical orbits.
Type AERToNu for a demo.
Form
 nu = AERToNu( a, e, r )
Inputs
 a   (1,1) Semi-major axis
 e   (1,1) Eccentricity
 r   (1,:) Position
Outputs
 nu (1,:) True anomaly (rad)
References AERToNu(), and(), Demo(), and Plot2D().
Referenced by AERToNu().
AFLTSpiral()
function AFLTSpiral (in a0, in dV, in accel, in mu)
 The acceleration is aligned with the velocity vector. Computes the final apogee
 Since version 2.
Form
 [aF, dVRatio, t] = AFLTSpiral( a0, dV, accel, mu )
Inputs
 a0                 Initial semi-major axis
 dV         (:)     Total delta-v
 accel              acceleration
 mu                 Gravitational parameter
Outputs
 aF         (:)     Final semi-major axis
 dVRatio    (:)     Ratio of total delta-v to Hohmann Delta-V
 t                  Maneuver duration (days)
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 89-90.
References DVHoh(), isempty(), Plot2D(), and vector().
AGravity()
function AGravity (in nZ, in nT, in r, in lambda, in theta, in s, in c, in j, in mu, in a)
Acceleration vectors are a [ a(r), a(lambda), a(theta) ]. The coefficients should be unnormalized. If they are not the function will throw a warning and unnormalize them.
 [s, c, j, mu, a] = LoadGEM( 1 )
 for k = 1:kMax
 [a, aS, aZ, aT] = AGravity( nZ, nT, r, lambda, theta, s, c, j, mu, a );
 end
 than
 for k = 1:kMax
 [a, aS, aZ, aT] = AGravity( nZ, nT, r, lambda, theta );
 end
Form
 [aG, aS, aZ, aT] = AGravity( nZ, nT, r, lambda, theta, d )
 [aG, aS, aZ, aT] = AGravity( nZ, nT, r, lambda, theta, s, c, j, mu, a )
Inputs
 nZ                   Highest zonal harmonic (m = 0) (empty gives the max #)
 nT                   Highest sectorial and tesseral harmonic (empty gives the max #)
 r                    Radius
 lambda               Equatorial angle
 theta                Angle from pole
 d            (.)     Gravity model struct
    -or-
 s           (:,:)    S terms
 c           (:,:)    C terms
 j              (:)   m = 0 terms
 mu                   Spherical gravitational potential
 a                    Earth radius
Outputs
 aG           (3,1)   Total gravitational acceleration km/sec^2
 aS           (3,1)   Spherical term                   km/sec^2
 aZ           (3,1)   Zonal term                       km/sec^2
 aT           (3,1)   Tesseral term                    km/sec^2
See also
AGravityC, PDAL, SCHarm
References AGravityC(), and(), isempty(), LoadGEM(), PDAL(), SCHarm(), UnnormalizeGravity(), vector(), and zeros().
Referenced by DVGeoTrx(), and GuidedLaunch3DRHS().
AGravityC()
function AGravityC (in r, in nN, in nM, in s, in c, in j, in mu, in a, in useNormM)
Acceleration vectors are a [ aX;aY;aZ ].
If the gravity coefficients are normalized, an additional matrix multiplication is required. The normalization matrix is stored as a persistent variable but AGravityC will gracefully update it if the normalization or order of the model changes between calls.
Form
 [aG, aS, aZ, aT] = AGravityC( r, nN, nM, d )  % structure
 [aG, aS, aZ, aT] = AGravityC( r, nN, nM, s, c, j, mu, a, useNormM )
Inputs
 r           (3,:)    Position vector, planet-fixed
 nN          (1,1)    Highest zonal harmonic (m = 0)
                      (empty gives the max #)
 nM          (1,1)    Highest sectorial and tesseral harmonic
                      (empty gives the max #)
 d            (.)     Gravity model struct
    -or-
 s           (:,:)    S terms
 c           (:,:)    C terms
 j             (:)    m = 0 terms
 mu          (1,1)    Spherical gravitational potential
 a           (1,1)    Planet radius
 useNormM    (1,1)    Generate the normalization matrix (default false)
Outputs
 aG           (3,:)   Total gravitational acceleration km/sec^2
 aS           (3,:)   Spherical term                   km/sec^2
 aZ           (3,:)   Zonal term                       km/sec^2
 aT           (3,:)   Tesseral term                    km/sec^2
Reference: Bond, V. R. and M. C. Allman (1996.) Modern Astrodynamics. Princeton. pp. 212-213. Lerch, F. J., Klosko, S. M., Labuscher, R. E., Wagner, C.A., "Gravity Model Improvement GEOS-3 (GEM 9 & 10)," N78-10645, September, 1977. Gottlieb, R. G., "Fast Gravity, Gravity Partials, Normalized Gravity, Gravity Graident Torque and Magnetic Field: Derivation, Code and Data, NASA CR 188243, February, 1993.
See also
UnnormalizeGravity, AGravity (output in spherical coords)
References AGravityC(), and(), and vector().
Referenced by AGravity(), AGravityC(), FEarthMoonSun(), FOrbCartH(), FOrbHFOP(), FOrbitMultiSpacecraft(), FOrbKF(), GravityHelio(), GravityMap(), RHSGeoHarm(), RHSGeoJ2(), and SafeGuidanceSim().
APlanet()
function APlanet (in r, in mu, in rho)
The spacecraft is within the sphere of influence of another body. The equations become
 2
d r mu r
2          3
dt |r|
This function is valid when r << rho. Multiple planets can be input at once.
Form
 [a, aP] = APlanet( r, mu, rho )
Inputs
 r           (3,1)   Vector of the spacecraft from the central body
 mu          (:)     Planet gravitational parameter(s)
 rho         (3,:)   Vector of the perturbing planet(s) from the central body
Outputs
 a           (3,1)   Total acceleration
 aP          (3,:)   Accelerations of individual planets
Reference: Bond, V.R., M.C. Allman, Modern Astrodynamics Princeton University Press, 1996, pp. 203-204.
References length(), Mag(), and zeros().
Referenced by CubeSatLunarEnvironment(), FEarthMoon(), FEarthMoonSun(), FOrbitMultiSpacecraft(), GravityHelio(), LunarTargeting(), PlanetaryAccelerations(), RHSHelioWithPlanets(), RHSStateLunarMission(), and RHSUKFCisLunarMission().
ApogeeDV()
function ApogeeDV (in eT, in iT, in a2, in e2, in i2, in mu)
Computes the delta-v needed to go from a transfer orbit to a final orbit with a plane change. Assumes that the node line coincides with the line of apsides.
If there are no arguments a figure is created.
Form
 [dV, theta] = ApogeeDV( eT, iT, a2, e2, i2, mu )
 ApogeeDV( eT, iT, a2, e2, i2 );   % create plot
Inputs
 eT                     eccentricity of the transfer orbit
 iT                     inclination of the transfer orbit (rad)
 a2                     semi-major axis of the final orbit
 e2                     eccentricity of the final orbit
 i2                     inclination of the final orbit (rad)
 mu                     gravitational parameter (default Earth, km^3/sec^2)
Outputs
 dV                     total delta v
 theta                  angle of burn with respect to the final
                           velocity vector
References: Kaplan, M., Modern Spacecraft Dynamics and Control, John Wiley & Sons, p. 91.
References A2Apogee(), and(), ApogeeDV(), AxesCart(), length(), Map(), vector(), and zeros().
Referenced by ApogeeDV().
ApogeeRaisingDeltaV()
function ApogeeRaisingDeltaV (in r, in v, in rDes, in aT)
Form
 [dV1,dV2,tOF,aT] = ApogeeRaisingDeltaV( r, v, rDes, aT );
Inputs
 r             (3,1)   ECI position (km)
 v             (3,1)   ECI velocity (km/s)
 rDes          (1,1)   Desired apogee (km)
 aT            (1,1)   Transfer orbit semi major axis. Optional. (km)
Outputs
 dV1           (3,1)   First delta-v to raise the apogee
 dV2           (3,1)   Second delta-v to circularize at apogee
 tOF           (1,1)   Time of flight from current state to final orbit
 aT            (1,1)   Semi major axis of transfer orbit
References abs(), and(), Mag(), and Nu2M().
Referenced by ThrustControlRaiseApogee().
AttitudeFrames()
function AttitudeFrames (in r, in v, in qECIToBody, in jD, in len)
You can add these to any 3D picture.
 Draws and labels the ECI, LVLH, and Body frames. Also draws a sun vector
 using SunV1 for ephemeris.
Form
 AttitudeFrames( r, v, qECIToBody, jD, len )
Inputs
 r          (3,1) Position vector
 v          (3,1) Position vector
 qECIToBody (4,1) ECI to body quaternion
 jD         (1,1) Julian date
 len        (1,1) Length of the axes
Outputs
 None
References and(), AttitudeFrames(), CosD(), get(), JD2000(), NewFig(), Q2Mat(), QLVLH(), QPose(), QRand(), quaternion(), set(), SinD(), SunV1(), Unit(), and vector().
Referenced by AttitudeFrames().
AZLaunch()
function AZLaunch (in i, in lat)
Form
 az = AZLaunch( i, lat )
Inputs
 i           (1,:)  Desired inclination (deg)
 lat                Latitude (deg)
Outputs
 az                 Launch azimuth (deg)
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 76-77.
References abs(), isempty(), length(), and Plot2D().
BallisticCoefficient()
function BallisticCoefficient (in cD, in u, in g, in varargin)
Add a fourth argument to account for shadowing.
Type BallisticCoefficient for a demo.
Form
 b = BallisticCoefficient( cD, u, g, shadows )
Inputs
 cD                 (1,1) Drag coefficient
 u                  (3,n) Velocity unit vector
 g                  (1,1) CAD model
 ~                  (1,1) Optional. If any value is provided, shadowing
                           calculations will be performed using HSRCAD.
Outputs
 b                  (1,n) Ballistic coefficent
References BallisticCoefficient(), Demo(), Dot(), HSRCAD(), length(), Plot2D(), ShowCAD(), vector(), and zeros().
Referenced by BallisticCoefficient().
CartOrb2Cyl()
function CartOrb2Cyl (in x)
Form
 d = CartOrb2Cyl( x )
Inputs
 x               (6,:) [r;v]
Outputs
 d               (6,:) [r;theta;z;rDot;thetaDot;zDot]
CEcl2SER()
function CEcl2SER (in jD)
 This is a single rotation about the z-axis. If the JD is not input it
 will use the ecliptic longitude for J2000.0.
 Since version 2014.1
Form
 c = CEcl2SER( jD )
Inputs
 jD            (1,1)    Julian date
Outputs
 c             (3,3)    Transformation matrix from the heliocentric
                         frame with xy ecliptic plane to Sun-Earth
                         rotating frame, with x along Sun-Earth line, y
                         orthoganal to xz plane.
Referenced by EarthEscape().
CEq2C()
function CEq2C (in eq)
 The equinoctial elements are
 a   - semimajor axis
 P1  - esin(W+w)
 P2  - ecos(W+w)
 Q1  - tan(i/2)sinW
 Q2  - tan(i/2)cosW
 l   - W + w + M
 Since version 1.
Form
 c = CEq2C( eq )
Inputs
 eq                    Elements vector [a,P1,P2,Q1,Q2,l]
Outputs
 c               (3,3) Transformation matrix
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, p. 494.
References and(), CEq2C(), and vector().
Referenced by CEq2C(), and Eq2RV().
ChangePerigee()
function ChangePerigee (in d)
Form
 b = ChangePerigee( d )
Inputs
 d            (:)     Input data structure
                       .a   (1,1)   Semi-major axis
                       .e   (1,1)   Eccentricity of initial orbit
                       .rP  (1,:)   New Perigee
                       .mu  (1,1)   Mu
Outputs
 b             (:)     Output data structure
                       .dV  (1,:)   Datastructure
                       .e   (1,:)   New eccentricity
                       .a   (1,:)   New semi-major axis
                       .vA  (1,:)   Apogee velocity
References abs(), and Plot2D().
CircularManeuver()
function CircularManeuver (in p, in r, in m, in t, in uE)
 Computes fuel consumption if duration and exhaust velocity are entered.
Form
 [fR, iT, fuel] = CircularManeuver( p, r, m, t, uE )
Inputs
 p            (1,1)     Period (min)
 r            (1,1)     Radius of orbit (m)
 m            (1,1)     Mass (kg)
 t            (1,1)     Duration (min), optional
 uE           (1,1)     Exhaust velocity (m/sec), optional
Outputs
 fR           (1,1)     Required radial force (N)
 iT           (1,1)     Required tangential impulse (Ns)
 fuel         (1,1)     Fuel consumption (kg)
References and(), CircularManeuver(), Demo(), and Period().
Referenced by CircularManeuver(), and FBudget().
CircularOrbitState()
function CircularOrbitState (in R, in inc, in ra, in M, in n)
Form
 [r,v] = CircularOrbitState( R, inc, ra, M, n );
Inputs
 R           (1,:)    Distance from planet center
 inc         (1,1)    Inclination [rad]
 ra          (1,1)    Right ascension [rad]
 M           (1,:)    Mean anomaly [rad]
 n           (1,:)    Orbit rate
Outputs
 lat         (1)       Latitude  [deg]
 lon         (1)       Longitude [deg]
 alt         (1)       Altitude  [km]
References Altitude(), and(), CircularOrbitState(), and RotMat().
Referenced by CircularOrbitState().
ClohessyWiltshire()
function ClohessyWiltshire (in w, in t)
Returns four Phi matrices which give the position and velocity as a function of time t when distance x along the orbit circumference is not necessarily small:
 r(t) = Phi.rr*r0 + Phi.rv*v0;
 v(t) = Phi.vr*r0 + Phi.vv*v0;
where v has been substituted for rDot for clarity. These matrices only apply to circular orbits.
Form
 Phi = ClohessyWiltshire( w, t )
Inputs
 w                 (1)    Orbit rate (rad/sec)
 t                 (1)    Time from initial state [r0; v0] (sec)
Outputs
 Phi               (:)    Propagation matrix structure
    .rr            (3,3)
    .rv            (3,3)
    .vr            (3,3)
    .vv            (3,3)
Reference: Hablani, Tapper, Bashian et al. "Guidance algorithms for Autonomous Rendezvous of Spacecraft with a Target Vehicle in Circular Orbit," 2001
References and(), and OrbRate().
Referenced by CWSimAndPlot(), DVGlideslope(), GlideslopeCircumnav(), GlideslopeGuidance(), and GlideslopePlanner().
ComputeTLE()
function ComputeTLE (in elOsc, in jD, in Bstar)
Form
 sTLE = ComputeTLE( elOsc, jD, Bstar )
Inputs
 elOsc        (1,6)   Osculating elements [a,i,W,w,e,M]
 jD           (1,1)   Julian date
 Bstar        (1,1)   Bstar drag parameter
Outputs
 sTLE         (3,:)   Two-line elements string
Reference: NORAD TLE CONVERSION FROM OSCULATING ORBITAL ELEMENT, Byoung-Sun Lee, J. Astron. Space Sci. 19(4), 395-402 (2002)
References abs(), and(), ComputeTLE(), Date2JD(), Demo(), Initialize(), isempty(), JD2000(), JD2Date(), MeanMotn(), NORAD(), NORADToEl(), plus(), RV2El(), and zeros().
Referenced by ComputeTLE().
ConvertNORAD()
function ConvertNORAD (in a, in threeLine)
Can process two or three-line version of elements. Three-line elements are determined by a line with a first character that is not a number (traditionally the spacecraft's name), example:
Mir
1 16609U 86017A 97059.07924160 .00056468 00000-0 66860-3 0 879 2 16609 51.6505 274.3828 0011764 122.9249 237.3208 15.60613928629999
Form
 x = ConvertNORAD( a, threeLine )
Inputs
 a                (:,1)   Data, file name or string
 threeLine      (1)    Boolean to force three-line format
Outputs
 x            (n)  Data structure
  .satelliteNumber  Object ID
  .launchYear       Year (part of international designator)
  .launchNumber     Launch number
  .launchpiece      Launch piece
  .epochYear        Two/one digit epoch year
  .epochDay         Epoch day number
  .n0Dot            1st Derivative of the Mean Motion (rad/min^2)
  .n0DDot           2nd Derivative of the Mean Motion
  .bStar            Adjusted ballistic coefficient
  .i0               Inclination (rad)
  .f0               Right Ascension of Ascending Node (rad)
  .e0               Eccentricity
  .w0               Argument of Perigee (rad)
  .M0               Mean Anomaly (rad)
  .n0               Mean Motion (rad/min)
 The following fields are computed from the element data.
 .ballisticCoeff   Ballistic coefficient (m2/kg)
 .julianDate       Epoch Julian date
 .fullLaunchYear   Four digit launch year
 .sma              Semi-major axis (km)
 n          (1,1)   Number of element sets
 t          (3,n)   Time information if present on second line
References and(), and NORAD().
Referenced by NORAD(), PropagateTLECommonTime(), SeeTLE(), and TLETime().
CoplanarOrbit()
function CoplanarOrbit (in el1, in deltaH)
Compute the new eccentricity and semimajor axis after adding the delta altitude to both the apogee and perigee.
Form
 el2 = CoplanarOrbit( el1, deltaH )
Inputs
 el1    (1,6) Element set [a i W w e M]
 deltaH (1,1) Altitude change
Outputs
 el2    (1,6) Element set [a i W w e M]
References AE2RPRA(), Altitude(), and(), CoplanarOrbit(), Demo(), Mag(), Plot2D(), RPRA2AE(), RVOrbGen(), set(), and TimeLabl().
Referenced by CoplanarOrbit().
CostLowThrust2D()
function CostLowThrust2D (in lambda, in d)
It computes an err magnitude that the optimizer uses to find the minimum. This function is for the planar orbit problem which includes radial position, radial velocity, tangential velocity and mass. This function is specifically for the minimum time problem.
Form
 [errMag, err, x, t] = CostLowThrust2D( lambda, d )
 d = CostLowThrust2D( 'get' )
Inputs
 lambda         (3,1)  Costates [r;dr/dt;drtheta/dt]
 d               (.)   Structure
                       .rhsFun      (*) Associated RHS function for optimizer
                       .plotFun     (*) Associated plot function for optimizer
                       .costFun     (*) Associated cost function
                       .thrust      (1,1) Thrust magnitude (kN)
                       .mDot        (1,1) Mass derivative (kg/s)
                       .mu          (1,1) Gravitational parameter
                       .x0          (4,1) Initial state, [r;v;mF]
                       .xF          (3,1) Final state from optimizer
                       .tEnd        (1,1) Final time from opimizer
                       .data.absTol (1,1) ode113 parameter
                       .data.relTol (1,1) ode113 parameter
                       .errorScale  (3,1) Weights on the errors
Outputs
 errMag         (1,:)  Magnitude of the error
 err            (4,1)  [costates;transversality condition]
 x              (:,n)  States [r;u;v;m;lambda;theta]
 t              (1,n)  Time
References abs(), and(), Constant(), CostLowThrust2D(), Dot(), DupVect(), FLowThrust2D(), get(), length(), Mag(), Planets(), Plot2DTrajectory(), RHS(), vector(), and zeros().
Referenced by CostLowThrust2D(), and TrajectoryOptimization().
CP2I()
function CP2I (in i, in L, in w)
 Since version 1.
Form
 c = CP2I( i, L, w )
Inputs
 i               (3,1) Inclination (rad)
 L               (3,1) Longitude of the ascending node (rad)
 w               (3,1) Argument of perigee (rad)
Outputs
 c               (3,3) Transformation matrix
References: Bate, Roger R., Fundamentals of Astrodynamics, Dover Publications, Inc., New York, 1971, pp. 82-83.
Referenced by ADGen(), ADPartls(), El2RV(), GPSOrbit(), GPSSatellite(), MeasGPS(), PltOrbit(), RotateOrbit(), RVFromKepler(), and RVOrbGen().
CrossScaleConstellation()
function CrossScaleConstellation (in l, in b)
Four spacecraft per scale. The rotation matrices allow you to rotate each scale.
Type CrossScaleConstellation for a demo.
Form
r = CrossScaleConstellation(l,b)
Inputs
 l   (1,n)   Distance from center for each scale
 b   {n}     3x3 transformation matrices for each scale
Outputs
 r   (3,5*n)    Positions
References CrossScaleConstellation().
Referenced by CrossScaleConstellation().
CT2R()
function CT2R (in a, in e, in f, in at, in mu)
 Since version 1.
Form
 aR = CT2R( a, e, f, at, mu )
Inputs
 a                     Semi-major axis or perigee radius if e = 1
 e                     Eccentricity
 f                     True anomaly
 at                    Tangential vector
 mu                    Gravitational parameter
Outputs
 aR                    Radial vector or transformation matrix
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, pp. 489.
References and(), and vector().
CT2REl()
function CT2REl (in el, in at, in mu)
 Since version 1.
Form
 ar = CT2REl( el, at, mu )
Inputs
 el                    Keplerian Elements [a,i,W,w,e,M]
 at                    Tangential vector [tangent;normal;out-of-plane]
 mu                    Gravitational parameter
Outputs
 ar                    Radial vector or transformation matrix
                       [radial;circumferential;out-of-plane]
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, pp. 489.
References and(), and vector().
CT2REq()
function CT2REq (in eq, in aT, in mu)
 Since version 1.
Form
 aR = CT2REq( eq, aT, mu )
Inputs
 eq                    Equinoctial elements
 aT                    Tangential vector
 mu                    Gravitational parameter
Outputs
 aR                    Radial vector or transformation matrix
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, pp. 490.
References and(), K2L(), ML2K(), vector(), and zeros().
Referenced by VarEqT().
CWSimAndPlot()
function CWSimAndPlot (in x0, in w, in dV, in t)
Has a built-in demo using Glideslope. The simulation uses 1000 points.
Form
 CWSimAndPlot( x0, w, dV, t )
Inputs
 x0                (6,1)    Initial state (LVLH frame)
 w                 (1)      Orbit rate
 dV                (3,n)    Delta-Vs to apply
 t                 (1,n)    Times of the delta-Vs
See also
ClohessyWiltshire, DVGlideslope
References ClohessyWiltshire(), CWSimAndPlot(), DVGlideslope(), length(), Mag(), NewFig(), OrbRate(), Plot2D(), set(), Trajectory(), and zeros().
Referenced by CWSimAndPlot(), DVGlideslope(), GlideslopeCircumnav(), GlideslopeGuidance(), and GlideslopePlanner().
CylOrb()
function CylOrb (in x, in a, in mu)
See also
SphOrb and FOrb.
 Since version 1.
Form
 xDot = CylOrb( x, a, mu )
Inputs
 x                (6,1) state [r;theta;z;dr/dt;dtheta/dt;dz/dt]
 a                (3,1) acceleration vector
 mu                     gravitational parameter
Outputs
 xDot             (6,1) state derivative
References and(), FOrb(), SphOrb(), and vector().
Referenced by FOrb().
CylOrb2Cart()
function CylOrb2Cart (in x)
Form
 d = CylOrb2Cart( x )
Inputs
 x               (6,1) [r;theta;z;rDot;thetaDot;zDot]
Outputs
 d               (6,:) [x;y;z;xDot;yDot;zDot]
DiscreteTrajectoryToDeltaV()
function DiscreteTrajectoryToDeltaV (in p, in vMag)
Form
 [dVDT, dVDTR, dV] = DiscreteTrajectoryToDeltaV( p, vMag )
Inputs
 p            (3,:)     Points
 vMag         (1,1)     Steady velocity
Outputs
 dVDT         (3,:)     Accelerations at each node
 dVDTR        (3,1)     Radial acceleration at each node
 dV           (3,:)     Velocity change at each node
References Demo(), DiscreteTrajectoryToDeltaV(), Dot(), length(), Mag(), Plot2D(), TimeLabl(), Unit(), and zeros().
Referenced by DiscreteTrajectoryToDeltaV().
DLinOrb()
function DLinOrb (in n, in dT)
x[k+1] = ad*x[k] + bd*u[k]
Form
 [ad,bd] = DLinOrb( n, dT )
Inputs
 n                (1,1) mean orbit rate (rad/s)
 dT               (1,1) time step
Outputs
 ad               (6,6) State transition matrix
 bd               (6,3) Input matrix
DoDeltaV()
function DoDeltaV (in el, in dV, in mu)
 Since version 1.
Form
 el = DoDeltaV( el, dV, mu )
Inputs
 el              (1,6)  Keplerian Elements [a,i,W,w,e,M] (angles in rad)
 dV              (3,1)  Vector delta-V
 mu                     Gravitational constant
Outputs
 el              (1,6)  Keplerian Elements [a,i,W,w,e,M] (angles in rad)
References El2RV(), length(), RV2El(), and vector().
DrawOrbitPlane()
function DrawOrbitPlane (in r, in v, in axesHandle)
You can add this to any 3D plot.
Form
 DrawOrbitPlane( r, v, axesHandle )
Inputs
 r           (3,1) Position vector
 v           (3,1) Velocity vector
 hAxis       (1,1) Handle to axis
Outputs
 None
References Cross(), DrawOrbitPlane(), isempty(), NewFig(), Period(), RV2El(), RVFromKepler(), set(), vector(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by DrawOrbitPlane().
DVAKM()
function DVAKM (in iT, in temp, in threeSig, in mF, in mO, in dV)
 Since version 1.
Form
 [tReq, dV3Sig, iTReq] = DVAKM( iT, temp, threeSig, mF, mO, dV )
Inputs
 iT          (1,2)  Total impulses (Ns)
 temp        (1,2)  Corresponding temperatures
 threeSig           Three sigma variation in impulse
 mF                 Fuel mass (kg)
 m0                 Initial mass (including fuel) (kg)
 dV                 Desired delta-V (m/sec)
Outputs
 tReq               AKM Temperature
 dV3Sig             Three sigma delta-V (m/sec)
 iTReq              Required impulse (N-s)
DVDisp()
function DVDisp (in i, in vA, in vT, in decErr, in vErr, in nPlot)
 Since version 1.
Form
 [v, dec, dV, dI] = DVDisp( i, vA, vT, decErr, vErr, nPlot )
Inputs
 i                   Target change in inclination (deg)
 vA                  Apogee velocity
 vT                  Target velocity
 decErr              Declination fractional error range (0.1 = 10%)
 vErr                Velocity fractional error range
 nPlot               Number of plot points
Outputs
 v                   Ideal delta-v
 dec                 Ideal declination (deg)
 dV                  Velocity Error
 dI                  Inclination Error
References and(), NewFig(), XLabelS(), YLabelS(), and ZLabelS().
DVGeoTrx()
function DVGeoTrx (in lon, in box, in s, in c, in j, in mu, in a)
Computes the delta-v needed per year to control the longitudinal acceleration due to the Earth triaxial gravitational harmonics in geosynchronous orbit.
The time between maneuvers will be infinite at the stable points.
If the gravitational parameters are not entered it will load the GEM-T1 model. The model coefficients should be unnormalized.
Type DVGeoTrx for a demo.
Form
 [dV, acc, dT] = DVGeoTrx( lon, box, s, c, j, mu, a )
Inputs
 lon         (1,:)    East longitude (deg)
 box         (1,1)    Stationkeeping box (deg)
 s           (36,36)  S terms
 c           (36,36)  C terms
 j              (36)  m = 0 terms
 mu          (1,1)    Spherical gravitational potential
 a           (1,1)    Earth radius
Outputs
 dV          (1,:)    Total delta v per year (m/sec)
 acc         (1,:)    Acceleration (deg/day^2)
 dT          (1,:)    Time between maneuvers
References abs(), AGravity(), Demo(), DVGeoTrx(), Geo(), length(), LoadGEM(), and zeros().
Referenced by DVGeoTrx(), and TrxCntrl().
DVGlideslope()
function DVGlideslope (in x0, in w, in N, in T, in rTarget, in vOrA)
For inbound glideslopes, the commanded velocity should be negative and the final velocity must have a smaller magnitude than the initial velocity. For outbound glidesopes the reverse is true. For circumnavigations, rTarget is the radius and the vector a defines the circumnavigation orbit normal. This function combines the capabilities of Glideslope and GlideslopeCircumnav. There is a built-in demo for a 100 m separation in LEO.
Form
 [dVM, t, x] = DVGlideslope( x0, w, N, T, rTarget, vOrA )
 Inputs
 x0      (6,1)           Initial relative state in LVLH frame
 w         (1)           Orbit rate
 N         (1)           Number of pulses
 T         (1)           Period for glideslope
 rTarget (3,1) or (1,1)  Vector target position in LVLH frame or
 radius for circumnavigation
 vOrA    (2,1) or (3,1)  Commanded initial and final velocity or
 orbit normal of circumnavigation. A normal of
 [0;1;0] produces an in-plane orbit.
 Outputs
 dVM  (3,N)   Delta-V in LVLH frame
 t    (1,N)   Times to apply the delta-V
 x    (3,N)   State at each delta-V point
Reference: Hablani, Tapper, Bashian et al. "Guidance algorithms for Autonomous Rendezvous of Spacecraft with a Target Vehicle in Circular Orbit," 2001
See also
Glideslope, GlideslopeCircumnav, CWSimAndPlot
References abs(), and(), ClohessyWiltshire(), CWSimAndPlot(), Demo(), GlideslopeCircumnav(), isempty(), length(), Mag(), NewtRaph(), OrbRate(), Period(), Rename(), SolveT(), SolveTD(), Unit(), vector(), and zeros().
Referenced by CWSimAndPlot(), and GlideslopePlanner().
DVHoh()
function DVHoh (in r1, in r2, in v1, in mu)
Form
 [dV, dV1, dV2, eT, aT] = DVHoh( r1, r2, v1, mu )
Inputs
 r1                    Radius 1
 r2                    Circular Orbit radius 2 (target)
 v1                    Velocity 1
 mu                    Gravitational parameter
Outputs
 dV                    Total required delta-v
 dV1                   Transfer ellipse injection delta-V
 dV2                   Final orbit injection delta-V
 eT                    Eccentricity of the transfer orbit
 aT                    Semimajor axis of the transfer orbit
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 71-74.
References abs().
Referenced by AFLTSpiral(), HohmannTransferRendezvous(), and LTSpiral().
DVHohE()
function DVHohE (in e1, in a1, in e2, in a2, in mu)
Computes the two impulses needed. Transfers from periapsis of 1 to apoapsis of 2.
Form
 [dv, dv1, dv2, et, at] = DVHohE( e1, a1, e2, a2, mu )
Inputs
 e1                     Eccentricity of first orbit
 a1                     Semi-major axis of first orbit
 e2                     Eccentricity of final orbit
 a2                     Semi-major axis of final orbit
 mu                     Gravitational parameter
Outputs
 dv                     Total delta v
 dv1                    Low orbit to transfer orbit delta v
 dv2                    Transfer orbit to high orbit delta v
 et                     Transfer orbit eccentricity
 at                     Transfer orbit semimajor axis
References: Kaplan, M., Modern Spacecraft Dynamics and Control, John Wiley, pp. 87-88.
References and().
Referenced by DVHohInc().
DVHohInc()
function DVHohInc (in e1, in a1, in e2, in a2, in Di, in mu)
Transfers from periapsis of 1 to apoapsis of 2.
Form
 [dv, dv1, dv2, Di1, Di2] = DVHohInc( e1, a1, e2, a2, Di, mu )
Inputs
 e1                     Eccentricity of first orbit
 a1                     Semi-major axis of first orbit
 e2                     Eccentricity of final orbit
 a2                     Semi-major axis of final orbit
 Di                     Change in inclination (rad)
 mu                     Gravitational parameter
Outputs
 dv                     Total delta v
 dv1                    Low orbit to transfer orbit delta v
 dv2                    Transfer orbit to high orbit delta v
 Di1                    Inclination correction during first Dv
 Di2                    Inclination correction during second Dv
References: Hornbeck, R., Numerical Methods, Quantum, 1975, pp. 66-67.
See also
: OptDIH, DVHohE, OrbMnvrInclAndHohm
References DVHohE(), OptDIH(), and OrbMnvrInclAndHohm().
DVIDrift()
function DVIDrift (in box, in year, in doPlot)
 Use this function to plan north/south stationkeeping.
Form
 [dV, dT, dI] = DVIDrift( box, year, doPlot )
Inputs
 box    (1,1) Size of stationkeeping box (deg)
 year   (1,:) Year of maneuvers
 doPlot (1,1) Create a plot
Outputs
 dV    (1,1) Delta V per maneuver (m/sec)
 dT    (1,:) Time between maneuvers (days)
 dI    (1,:) Change in inclination
Reference: Agrawal, B. N. (1986). Design of Geosynchronous Spacecraft. Prentice-Hall, Englewood Cliffs, NJ.
DVLowThrust()
function DVLowThrust (in vI, in vF, in dI)
Compute the velocity change for a transfer from a circular orbit to a noncoplanar circular orbit. vI or vF or dI may be a vector.
Type DVLowThrust for a demo from LEO to GEO.
Form
 dV = DVLowThrust( vI, vF, dI )
Inputs
 vI      (1,:)     Initial velocity
 vF      (1,:)     Final velocity
 dI      (1,:)     Change in inclination (rad)
Outputs
 dV      (1,:)     Velocity change
References Demo(), DVLowThrust(), length(), Plot2D(), and vector().
Referenced by DVLowThrust().
DVOCCapt()
function DVOCCapt (in muS, in muP, in r, in v)
 This can be used for heliocentric to planetary captures or
 moon captures.
 Since version 1.
Form
 [dV, rP] = DVOCCapt( muS, muP, r, v )
Inputs
 muS         (1,1)     Gravitational parameter of the central body
 muP         (1,1)     Gravitational parameter of the target body
 r           (1,1)     Target body orbit radius referenced to the center
 v           (1,:)     The central body velocity of the spacecraft
Outputs
 dV          (1,:)     Minimum delta-v
 rP          (1,:)     Optimal circular radius about the target
References and(), isempty(), and Plot2D().
DVOHohmn()
function DVOHohmn (in R1, in R2, in rA, in rP, in mu, in muP)
 First put the spacecraft into an elliptic orbit with a low perigee then do
 the delta-v to infinity
 ?---------> Direction of planet
 / psi
 /    ---------> Departure hyperbola asymptote
 Since version 1.
Form
 [dV, dV1, dV2, vInf, v, psi, eH] = DVOHohmn( R1, R2, rA, rP, mu, muP )
Inputs
 R1                    Heliocentric departure planet orbit radius
 R2                    Heliocentric target orbit radius
 rA                    Circular orbit radius about the departure planet
 rP                    Perigee radius
 mu                    Gravitational parameter of the central planet or sun
 muP                   Gravitational parameter of the departure planet
Outputs
 dV                    Required delta-v
 dV1                   Delta-v of first maneuver
 dV2                   Delta-v of second maneuver
 vInf                  The hyperbolic speed at infinity
 v                     The heliocentric velocity
 psi                   Angle between the target planet velocity vector and
                       the delta-v maneuver
 eH                    Eccentricity of the departure hyperbola
DVOrbitDrag()
function DVOrbitDrag (in el, in nu, in b, in planet)
All the built in constants are for the Earth. If no outputs are specified it will plot the drag acceleration. This function assumes that the velocity remains that of the unperturbed orbit. This approximation is only valid when the drag loss is low or there is a drag makeup system in operation. The planets are limited by the ones available in AtmDens1 which are
 'mercury', 'venus', 'mars', 'pluto', 'europa'
If Earth is selected the function uses the more accurate AtmDens2. nu should be between -pi and pi.
Type DVOrbitDrag for an example of slightly elliptical orbits around Earth and Mars.
Form
dV = DVOrbitDrag(el, nu, b, planet)
Inputs
el (1,6) [a i w W e M] w is argument of perigee, W ascending node nu (1,2) True anomaly [start finish] b (1,1) Ballistic coefficient drag coefficient*area/mass (m^2/kg) planet (1,1) Planet name
Outputs
dV (1,1) Total drag loss (km/s)
References and(), AtmDens1(), AtmDens2(), Constant(), Demo(), DVOrbitDrag(), Mag(), Nu2M(), Period(), RVOrbGen(), and TimeLabl().
Referenced by DVOrbitDrag().
DVReentry()
function DVReentry (in a, in e, in rEI, in c1, in c2, in mu)
You must select the entry interface radius, rEI and c! and c2 which are the LTVCON (Linear Terminal Velocity Constraint) constants such that
 vR = c1 + c2*vH
where vR is the radial velocity and vH is the horizontal velocity.
Form
 dV = DVReentry( a, e, rEI, c1, c2, mu )
Inputs
 a               (1,1) Semi-major axis of initial orbit
 e               (1,1) Eccentricity of the initial orbit
 rEI             (1,1) Radius of entry interface
 c1              (1,1) LTVCON 1
 c2              (1,1) LTVCON 2
 mu              (1,1) Gravitational constant
Outputs
 dV              (1,1) Required velocity change
Reference: Bond, V. R. and M. C. Allman, "Modern Astrodynamics," Princeton, 1996, pp. 103-107.
References Altitude(), and(), Demo(), DVReentry(), length(), Plot2D(), and zeros().
Referenced by DVReentry().
DVTarget()
function DVTarget (in r1, in v1, in r2, in v2, in dT, in mu, in rPmin)
Takes the states of two spacecraft at an epoch and a transfer time and performs Lambert targeting. Returns the delta-V and a flag for the long or short transfer. Propagation of the second state is performed with two-body dynamics using RVFromKepler.
Checks if the transfer hits the Earth. Another radius may be input or input empty ([]) to skip the check.
Form
 [dV,tM,okFlag] = DVTarget(r1,v1,r2,v2,dT)    % Earth
 [dV,tM,okFlag] = DVTarget(r1,v1,r2,v2,dT,mu,rPmin) % other planet(s)
Inputs
 r1               (3,1)  Position of spacecraft 1 (km)
 v1               (3,1)  Velocity of spacecraft 1 (km/s)
 r2               (3,1)  Position of spacecraft 2
 v2               (3,1)  Velocity of spacecraft 2
 dT               (1)    Transfer time (s)
 mu               (1)    Gravitional parameter, default is Earth
 rPmin            (1)    Minimum periapsis allowed, default is Earth radius
Outputs
 dV              (:)     Struct of delta-Vs
                  .a      (3,1) First delta-V (km/s)
                  .b      (3,1) Second delta-V (km/s)
                 .total  (1,1) Total delta-V
 tM              (1)     Flag: +/-1 for short/long transfer
 okFlag          (1)     Flag: 1 if maneuver is OK, 0 if hits the Earth
 elT            (1,6)    Transfer elements
See also
LambertTOF, RVFromKepler
References and(), Constant(), Cross(), Dot(), DVTarget(), isempty(), LambertTOF(), Mag(), PlotLambertTransfer(), RV2El(), RVFromKepler(), and Unit().
Referenced by DVTarget(), LambertOpt(), PlotLambertTransfer(), and PorkChopTOF().
E2M()
function E2M (in ecc, in eccAnom)
Form
 meanAnom = E2M( ecc, eccAnom )
Inputs
 ecc       (1,:) Eccentricity
 eccAnom   (1,:) Eccentric anomaly
Outputs
 meanAnom  (1,:) Mean anomaly
References: Bate, R. R. Fundamentals of Astrodynamics. pp. 185-187.
References DupVect(), E2M(), isempty(), length(), Plot2D(), scalar(), and zeros().
Referenced by E2M(), Nu2M(), RVOrbHF(), and RVSet2El().
E2Nu()
function E2Nu (in e, in E)
 Since version 1.
Form
 nu = E2Nu( e, E )
Inputs
 e             (1,:)   Eccentricity
 E             (1,:)   Eccentric or Hyperbolic anomaly
Outputs
 nu            (1,:)   True anomaly
References: Bate, R. R., Fundamentals of Astrodynamics. pp. 20-40.
References DupVect(), E2Nu(), isempty(), length(), Plot2D(), scalar(), and zeros().
Referenced by ADGen(), ADPartls(), E2Nu(), M2Nu(), Mean2OscS(), PltOrbit(), RVOrbGen(), and VarGausT().
E2RAORP()
function E2RAORP (in e)
Form
 x = E2RAORP( e )
Inputs
 e                  Eccentricity
Outputs
 x                  Apogee radius/perigee radius
ECEFToECI()
function ECEFToECI (in gMT)
 Assumes spherical Earth.
Form
 M = ECEFToECI( gMT );
Inputs
 gMT         (1,1)   Greenwich mean time (radians)
Outputs
 M           (3,3)   ECEF to ECI rotation matrix
References ECEFToECI().
Referenced by ECEFToECI().
ECI2OrbitPlane()
function ECI2OrbitPlane (in r, in n)
 and returns the rotation matrix that rotates from the ECI frame to the
 orbital plane. In the orbital plane, the y vector is aligned with r,
 the z vector is aligned with n, and x completes the right-hand system.
Form
 R = ECI2OrbitPlane( r, n )
Inputs
 r               (3,1) Position vector in ECI frame
 n               (3,1) Normal vector in ECI frame
Outputs
 R               (3,3) Rotation matrix from ECI to Orbital Plane
See also
: OrbNEl, OrbitalPlane
References and(), Cross(), ECI2OrbitPlane(), Normal(), OrbitalPlane(), OrbNEl(), RHS(), Unit(), and vector().
Referenced by ECI2OrbitPlane().
ECIToRLP()
function ECIToRLP (in xS)
Generates the transformation matrix from ECI to Rotating Libration Point Coordinates. Neglects perturbations due to other bodies.
Form
 c = ECIToRLP( xS )
Inputs
 xS          (6,1)  [r;v] of the secondary
Outputs
 c           (6,6)  Transformation from ECI To RLP
References Coordinates(), Cross(), Demo(), JD2000(), Mag(), MoonV1(), MoonV2(), RLP(), Unit(), and zeros().
El2Alfriend()
function El2Alfriend (in el, in nu)
 [a,i,W,w,e,M]           ->           [a,th,i,q1,q2,W]
Form
 ela = El2Alfriend( el, nu )
Inputs
 el            (:,6) Standard orbital element set [a,i,W,w,e,M]
Outputs
 ela           (:,6) Alfriend orbital element set [a,th,i,q1,q2,W]
                        where:   th = true latitude
                                 q1 = e*cos(w)
                                 q2 = e*sin(w)
References M2Nu(), set(), and WrapPhase().
Referenced by AutoFormGeometry(), CheckDeltaVs(), ClusterGoalsDemoSimStruct(), CollisionDemoSimStruct(), CollisionInit(), CollisionMonteCarlo(), CollisionSimStruct(), ECI2MeanElements(), FFEccGenerateTeamGoals(), FFEccHills2DeltaElem(), ImpulsiveManeuver(), InitializeFormation(), IterativeImpulsiveManeuver(), LPCircularTimeWeight(), Mean2Osc(), SafeGuidanceSimInit(), TeamManagementSimStruct(), TestLPCircular(), and TransformGeom2Hills().
El2Eq()
function El2Eq (in el)
 Since version 1.
Form
 eq = El2Eq( el )
Inputs
 el                    Elements vector [a,i,W,w,e,M]
Outputs
 eq                    Elements vector [a,P1,P2,Q1,Q2,l]
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, pp. 490-492.
References and(), and vector().
Referenced by RV2Eq().
El2LKl()
function El2LKl (in el)
 Since version 1.
Form
 [L, K, l] = El2LKl( el )
Inputs
 el                    Elements vector [a,i,W,w,e,M]
Outputs
 L                     True longitude      ( w + W + f )
 K                     Eccentric longitude ( w + W + E )
 l                     Mean longitude      ( w + W + M )
References and(), and vector().
El2RV()
function El2RV (in el, in tol, in mu)
Type El2RV for a demo. The Keplerian elements are defined as:
a is semi-major axis (km)
i is inclination (rad)
W is right ascension of the ascending node (rad)
w is argument of perigee (rad)
e is argument of perigee
M is mean anomaly
Form
 [r, v] = El2RV( el, tol, mu )
Inputs
 el    (:,6)  Elements vector [a,i,W,w,e,M]           (angles in radians)
 tol   (1,1)* Tolerance for Kepler's equation solver. (default = 1e-14)
 mu    (1,1)* Gravitational constant.                 (default = 3.98600436e5)
Outputs
 r     (3,:)  position vector
 v     (3,:)  velocity vector
References: Battin, R.H., An Introduction to the Mathematics and Methods of Astrodynamics, p 128.
See also
: RV2El, RVFromKepler
References and(), CP2I(), Demo(), DispWithTitle(), El2RV(), isempty(), M2Nu(), RV2El(), RVFromKepler(), vector(), and zeros().
Referenced by CollisionDemoSimStruct(), CollisionSimStruct(), DFFSim(), DoDeltaV(), DrawSCPlugIn(), EarthEscape(), EarthOrbToHelioOrb(), El2RV(), FFEccDeltaElem2Hills(), FFEccFrameCompare(), FFEccHills2DeltaElem(), GeoOptimalMission(), GeoSwitchingMission(), GetHSA(), GVEGuidance(), HohmannTransferRendezvous(), ISSCoord(), J2Prop(), LowEnergyEarthToMoonTransfer(), LQOrbitController(), LunarPolarOrbit(), LunarTargeting(), MinE4BP(), OrbitDeltaV(), OrbitProp(), OrbMnvrLowerApogee(), PlanetTransferLambert(), PlotLET(), PlotLET3BP(), PltOrbit(), ProjCirc(), ProjLine(), PropEph(), RendezvousPlanner(), RotateOrbit(), RV2El(), RVFromKepler(), RVOrbHF(), RVSet2El(), RVWithJ2(), SpaceCamera(), Targeting3BP2(), Targeting4BP(), TestFFEccLinOrb(), TestLPCircular(), TestLPEccentric(), TestLPEccentricGVE(), TransferTimeToDV(), TwoDEscape(), and VInfRPToRV().
ElToMEq()
function ElToMEq (in el, in mu)
The modified equinoctial elements are
 p = a(1 + e^2)
 f = ecos(w + W);
 g = esin(w + W);
 h = tan(i/2)cosW
 k = tan(i/2)sinW
 L = W + w + nu
W is right ascension of the ascending node. w is argument of perigee.
Form
 x = ElToMEq( el, mu )
Inputs
 el             (6,1)  Keplerian elements
 mu             (1,1)  Gravitational parameter
Outputs
 x              (6,1)  Elements
References ElToMEq(), and M2Nu().
Referenced by Cost3D(), ElToMEq(), MEqToEl(), and RVToMEq().
Energy()
function Energy (in a, in mu)
 Since version 1.
Form
 E = Energy( a, mu )
Inputs
 a                    Semi-major axis (is inf for a parabola and negative
                      for a hyperbola)
 mu                   Gravitational parameter
Outputs
 E                    Energy
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 53.
References and(), and Energy().
Referenced by ACResistance(), BatterySize(), BEP(), Energy(), EnergyHeight(), EnergyPerRing(), EnergyPhoton(), EnergyWRTMoon(), FFTEngy(), FlywheelStresses(), KEVToJ(), LowEnergyEarthToMoonTransfer(), LowEnergyTransferInCRTBP(), PlotLET(), PlotLET3BP(), PWMSeq(), RocketChemical(), RocketH2O2(), SkinDepth(), StoppingConditions(), WindShear(), and WindShearExponent().
ENUToECEF()
function ENUToECEF (in lat, in lon)
 ENU is East-North-Up. Assumes spherical Earth.
 Since version 8.
Form
 T = ENUToECEF( lat, lon )
 T = ENUToECEF( r )
Inputs
 lat         (1,1)   Latitude (rad)
 lon         (1,1)   Longitude (rad)
       OR
 r           (3,1)   Earth fixed position
Outputs
 T           (3,3)   ENU to ECEF rotation matrix
Referenced by VEFToVGamAz().
Eq2El()
function Eq2El (in eq)
 Since version 1.
Form
 el = Eq2El( eq )
Inputs
 eq                    Elements vector [a,P1,P2,Q1,Q2,l]
Outputs
 el                    Elements vector [a,i,W,w,e,M]
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, pp. 490-492.
References and(), and vector().
Eq2RV()
function Eq2RV (in eq, in tol, in mu)
 Since version 1.
Form
 [r, v] = Eq2RV( eq, tol, mu )
Inputs
 eq              (6,:) Elements vector [a,P1,P2,Q1,Q2,l]
 tol                   Tolerance for Kepler's equation solver
 mu                    Gravitational constant
Outputs
 r               (3,1) position vector
 v               (3,1) velocity vector
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, pp. 493-494.
References and(), CEq2C(), isempty(), K2L(), ML2K(), vector(), and zeros().
FAero()
function FAero (in action, in modifier, in u, in t)
This is a pure drag model.
Form
 x = FAero( action, modifier, u, t )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifier    (1,:)  Modifier to the action or data structure if initialization
 u           (7,1)  [v;rho] [km/sec;kg/m^3]
 t           (1,1)  Time
Outputs
 x           (3,1) Force vector in the v frame (kg-km/sec^2)
References close(), CloseFigure(), CreateCallback(), FAero(), get(), GetH(), GetNewTag(), HelpSystem(), Initialize(), isempty(), PropagateOrbitPlugIn(), PutH(), set(), and vector().
Referenced by FAero().
FAtmDensity()
function FAtmDensity (in action, in modifier, in u, in t)
Form
 x = FAtmDensity( action, modifier, u, t )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifier    (1,:)  Modifier to the action or data structure if intialization
 u           (7,1)  [v;rho]
 t           (1,1)  Time
Outputs
 x           (3,1) Force vector in the v frame
References close(), CloseFigure(), CreateCallback(), FAtmDensity(), get(), GetH(), GetNewTag(), HelpSystem(), Initialize(), isempty(), PropagateOrbitPlugIn(), PutH(), set(), and vector().
Referenced by FAtmDensity().
FBudget()
function FBudget (in event, in x, in file, in title, in html)
You need only fill in the data structure with the data needed for the types of maneuver used. The first event should always be 'initial'.
For delta-V maneuvers if some of the delta-V thrusters are chosen for acs use, those thrusters will be off-pulsed.
Form
 b = FBudget( event, x, file, title, html )
Inputs
 event           (:)    Event data structure
                        event.description   (1,:) String describing the event
                        event.type          (1,:) 'initial', 'delta-v', 'delta-h', 'acs','pulses', 'circular'
                        event.aCSThruster   (1,:) List of ACS thrusters to use    <-  all
                        event.dVThruster    (1,:) List of deltaV thrusters to use <- 'delta-V'
                        event.dVTotal       (1,1) Total delta-V                   <- 'delta-V'
                        event.dTControl     (1,1) Control period                  <- 'delta-V', 'acs'
                        event.burnEff       (1,1) Burn efficiency                 <- 'delta-V'
                        event.dHTotal       (1,1) Total delta-H                   <- 'delta-H'
                        event.disturbance   (3,1) Attitude disturbance            <- 'acs'
                        event.pulsewidth    (1,1) Pulsewidth to be used           <-  all
                        event.nPulses       (1,1) Number of pulses                <-  pulse
                        event.duration      (1,1) Used for attitude control       <- 'acs'
                        event.regulated     (1,1) 1 if regulated at following level
                        event.cM            (3,1) Center of mass
                        event.circular      (1,1) struct('period',p,'radius',r,'duration',t)                 <- 'circular'
 x               (1,1)  Spacecraft data
 x.regulatedPressure(1,:) Regulated pressure (if any)
 x.systemTemp       (1,:) Temperature of each system
 x.systemVol        (1,:) Volume of each system
 x.systemFuel       (1,:) Fuel per system
 x.pressurantMass   (1,:) Pressurant mass per system
 x.pressurantR      (1,1) Pressurant gas constant
 x.thrusterData     (:)   Data
 .systemID  (1,1)  System it is attached to
 .iSP       (1,:)  ISP coefficients*
 .thrust    (1,:)  Thrust coefficients*
 .riseTime  (1,:)  Thruster pulse rise time
 .fallTime  (1,:)  Thruster pulse fall time
 .u         (3,1)
 .r         (3,1)
 x.dryMass          (1,1) Dry mass
 x.fuelDensity      (1,1) Fuel density
 x.controlDT        (1,1) Control period
 file           (1,:)   File name
 title          (1,:)   Budget title
 html           (1,:)   Any argument here gives html
Outputs
 b               (:)     b.description      (1,:) String describing the event
                        b.massTotal        (1,1) Total mass
                        b.massFuel         (1,:) Mass of fuel per system
                        b.fuelUsed         (1,:) Fuel used per system
                        b.pressure         (1,:) Pressure per system
                        b.iSpACS           (1,:) Average ACS Isp
                        by.iSpDV           (1,:) Average DV Isp
 * Note: These coefficients model the thrust an Isp for short pulses. Please see
 the functions ISp and Thrust below.
References and(), CircularManeuver(), Constant(), Cross(), isempty(), length(), Mag(), Pressure(), Simplex(), SumV(), and zeros().
FEngine()
function FEngine (in action, in modifier, in u, in t)
 The input is in the LVLH frame.
Form
 x = FEngine( action, modifier, u, t )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifier    (1,:)  Modifier to the action or data structure if initialization
 u           (7,1)  [r;v;m]
 t           (1,1)  Time
Outputs
 x           (1,1)  The tag if action is 'initialize'
                    If the action is update
                    x.f    (3,1) Force vector in the ECI frame
                    x.mDot (1,1) Mass derivative
References close(), CloseFigure(), CreateCallback(), FEngine(), get(), GetH(), GetNewTag(), HelpSystem(), Initialize(), isempty(), PropagateOrbitPlugIn(), PutH(), set(), and vector().
Referenced by FEngine().
FlightPathAngle()
function FlightPathAngle (in r, in v, in mu)
 Type FlightPathAngle for a demo
Form
 phi = FlightPathAngle( r, v, mu )
Inputs
 r               (6,:) [r;v] or (3,1) r
 v               (3,:) v
 mu              (1,1) Gravitational parameter (only needed to plot)
Outputs
 phi             (1,:) Flight path angle
Reference: Vallado, D. A. Fundamentals of Astrodynamics and Applications McGraw-Hill. pp. 138-139.
References and(), Cross(), Dot(), FlightPathAngle(), length(), M2Nu(), Mag(), Plot2D(), RV2El(), RVOrbGen(), Unit(), and zeros().
Referenced by FlightPathAngle(), and StoppingConditions().
FlightPathAngleFromCartEl()
function FlightPathAngleFromCartEl (in el)
 Since version 8.
Form
 phi = FlightPathAngleFromCartEl( el )
Inputs
 el              (6,:) [a;i;w;W;e;M]
Outputs
 phi             (1,:) Flight path angle
Reference: Bond, V. R., M. C. Allman, "Modern Astrodynamics".
 Copyright (c) 2009 Princeton Satellite Systems, Inc.
 All rights reserved.
References Demo(), Dot(), DupVect(), FlightPathAngleFromCartEl(), Plot2D(), and Unit().
Referenced by FlightPathAngleFromCartEl().
FLowThrust2D()
function FLowThrust2D (in t, in x, in flag, in d)
This includes radial position, radial velocity and tangential velocity only. This function is specifically for the minimum time problem. It is designed to be called by ode113.
The thrust angle is: atan2(lambdaU, lambdaV)
Form
 varargout = FLowThrust2D( t, x, flag, d )
Inputs
 t          (1,1)  Time
 x          (8,1)  States [r;u;v;m;lambdaR;lambdaU;lambdaV;v/r]
 flag       (1,1)  Flag from ode113
 d           (.)   Structure to pass to the integration RHS
                   .thrust
                   .mDot
                   .mu
Outputs
 xDot       (7,1)  State derivatives d[r;u;v;m;lambdaR;lambdaU;lambdaV;v/r]/dt
 or
 vnew       (1,1)  Value of constraint
 isterminal (1,1)  1 if a terminal constraint
 direction  (1,1)  Direction
References and(), and RHS().
Referenced by CostLowThrust2D().
Flyby()
function Flyby (in vA, in vD, in vP, in muP)
 Since version 2.
Form
 [el, rP] = Flyby( vA, vD, vP, muP )
Inputs
 vA               (3,1)   Approach velocity of the spacecraft
 vD               (3,1)   Departure velocity of the spacecraft
 vP               (3,1)   Velocity of the planet
 muP         (1,1)   Gravitational parameter of the encountered planet
Outputs
 el               (:)     Elements in the planet frame
                     el.a, el.i, el.w, el.W, el.e, el.M
 rP               (1,1)   Radius of perigee
References abs(), and(), Cross(), Mag(), and RVOrbGen().
Referenced by FlybyConstantThrust(), MassFuelElectricConstantThrust(), MassFuelElectricConstantUE(), and StraightLineConstantAccel().
FOrb()
function FOrb (in x, in t, in fType, in a, in mu)
 with options for cartesian, spherical, or cylindrical coordinates.
 Since version 1.
Form
 xDot = FOrb( x, t, fType, a, mu )
Inputs
 x            (6,1)     The state vector [r;v]
 t                      Time
 fType                  Type of equations 'car','sph','cyl'
 a            (3,1)     External acceleration*
 mu                     Gravitational parameter*
                           *Optional
Outputs
 xDot         (6,1)     The derivative of the state vector
References CylOrb(), FOrbCart(), isempty(), SphOrb(), and vector().
Referenced by CompareHills(), CylOrb(), FRotatingPlanet(), FRotatingSun(), and LambertOpt().
FOrbCart()
function FOrbCart (in x, in t, in a, in mu)
 Only the first input is required.
Form
 xDot = FOrbCart( x, t, a, mu )
Inputs
 x            (6,1)     The state vector [r;v]
 t            (1,1)     Time (unused)
 a            (3,1)     External acceleration (default is zero)
 mu           (1,1)     Gravitational parameter (default is Earth)
Outputs
 xDot         (6,1)     The derivative of the state vector
References length(), Mag(), and vector().
Referenced by DFFRHS(), FCartOrbD(), FHingeOrbit(), FOrb(), FOrbitMultiSpacecraft(), GeoOptimalMission(), OrbitProp(), RHSRWA(), RHSRWAIDotSC(), and RHSRWASC().
FOrbCartH()
function FOrbCartH (in x, in t, in accel, in gravityModel, in nN, in nM, in jD)
Includes an external acceleration.
 Forms:
 xDot = FOrbCartH( x, t, accel, gravityModel, nN, nM, jD )
 xDot = FOrbCartH( t, x, accel, gravityModel, nN, nM, jD )  % ode113 format
Inputs
 x            (6,1)     The ECI state vector [r;v]
 t            (1,1)     Time (unused)
 accel        (3,1)     External acceleration (default is zero)
 gravityModel  (:)      Gravitational model (no default)
 nN           (1,1)     Highest zonal harmonic (2)
 nM           (1,1)     Highest sectorial and tesseral harmonic (0)
 jD           (1,1)     Julian Date
Outputs
 xDot         (6,1)     The derivative of the state vector
See also
: ECIToEF, AGravityC, RHSGeoHarm
References AGravityC(), and(), ECIToEF(), isempty(), JD2000(), JD2T(), length(), RHSGeoHarm(), and vector().
Referenced by J2Prop().
FOrbHF()
function FOrbHF (in x, in t, in options, in jD, in aExt, in mu, in s, in c, in j, in a)
Includes higher harmonics of the earth's gravitational field and sun and moon accelerations as options.
The gravity model should be unnormalized.
Form
 xDot = FOrbHF( x, t, options, jD, aExt, mu, s, c, j, a )
 xDot = FOrbHF( x, t, options, jD, aExt, d )
 xDot = FOrbHF( t, x, options, jD, aExt, mu, s, c, j, a )  (for ode113)
Inputs
 x             (6,1)    The state vector [x;y;z;dx/dt;dy/dt;dz/dt]
 t             (1,1)    Time
 options       (1,5)    [Highest zonal harmonic,Highest tesseral harmonic,
                         Sun,Moon,Drag]
 jD                     Julian date
 aExt          (3,1)    External acceleration vector [x;y;z] ECI
 d               (.)    Gravity model struct, unnormalized
    - or -
 mu                     Spherical gravitational potential
 s           (36,36)    S terms
 c           (36,36)    C terms
 j              (36)    m = 0 terms
 a                      Earth radius
Outputs
 xDot         (6,1)     The derivative of the state state vector
See also
AGravity, APlanet, AtmDens2, SolarF, and FOrb.
References and().
Referenced by CompareHills(), J2Prop(), and RVOrbHF().
FOrbHF2()
function FOrbHF2 (in t, in x, in flag, in d)
Inputs to this function are in the data structure d:
 1. The primary planet about which the spacecraft is orbiting
 2. Julian date in days
 3. Models:
 Thrust model
 Solar Pressure model
 Aerodynamic model
 Each model has three inputs
 1. Flag (1 == on)
 2. Tag to the GUI (see the example functions)
 3. Function name
 4. Propagate earth fixed flag (1 == true)
 5. Propagate ECI reference to earth fixed at start (1 == true)
 6. Data structure for the stopping condition (not needed if you aren't using
 stopping conditions.
 7. Number of tesseral and sectoral harmonics
 8. Number of zonal (0,2,3, ...)
 9. Planetary accelerations on (for the earth/moon/sun system only)
 10. Gravity model data structure
Form
 vargout = FOrbHF2( t, x, flag, d )
Inputs
 t                      Time
 x             (6,1)    The state vector [x;y;z;dx/dt;dy/dt;dz/dt]
 flag          (1,:)    Flags for ode113
 d             (1,1)    Data structure
                        .planet                 (1,:)   Planet name string
                        .jD                     (1,1)   Julian date (days)
                        .thrustModelOn          (1,1)   Thrust function flag
                        .thrustFunction         (1,:)   Thrust function name
                        .thrustFunctionTag      (1,1)   Thrust function tag
                        .solarModelOn           (1,1)   Solar function flag
                        .solarFunction          (1,:)   Solar function name
                        .solarFunctionTag       (1,1)   Solar function tag
                        .aeroModelOn            (1,1)   Aero function flag
                        .aeroFunction           (1,:)   Aero function name
                        .aeroFunctionTag        (1,1)   Aero function tag
                        .propagateEF            (1,1)   Propagate earth-fixed flag
                        .propagateECIR          (1,1)   Propagate ECIR flag
                        .stopping               (:)     Stopping condition data structure
                        .nTess                  (1,1)   Number of tesseral harmonics
                        .nZonal                 (1,1)   Number of zonal harmonics
                        .planetaryDisturbancesOn (1,1)   Turn on planetary disturbances for earth/moon/sun system
                        .gravityModel  (1,1)
                          .s           (36,36)  S terms
                          .c           (36,36)  C terms
                          .j              (36)  m = 0 terms
                          .mu                   Gravitational parameter (km^3/sec^2)
                          .a                    Earth radius
                          .name                 Planet name
Outputs
 xDot           (6,1)     The state vector derivative [x;y;z;dx/dt;dy/dt;dz/dt]
References Pressure().
FOrbHFOP()
function FOrbHFOP (in t, in x, in flag, in d)
Called by the OrbitPropagator GUI. Uses AGravityC. Uses ECIToPlanet with high-fidelity option for the Earth using TruEarth. Selects atmosphere model based on input.
Form
 vargout = FOrbHFOP( t, x, flag, d )
Inputs
 t     (1,1)    Time
 x     (6,1)    The state vector [x;y;z;dx/dt;dy/dt;dz/dt]
 flag   (1,:)   Event flag for ode113
 d     (.)   Data structure
             .planet             (1,:) Planet name
             .jD                 (1,1) Julian date
             .thrustModelOn      (1,1) Thrust function flag
             .thrustFunction     (*)   Thrust function name/handle
             .thrustFunctionTag  (1,1  Thrust function tag
             .solarModelOn       (1,1) Solar function flag
             .solarFunction      (*)   Solar function name/handle
             .solarFunctionTag   (1,1) Solar function tag
             .aeroModelOn        (1,1) Aero function flag
             .atmosphere         ''    Type of atmosphere model
             .densFunction       (*)   Aero function name/handle
             .densFunctionTag    (1,1) Aero function tag
             .propagateEF        (1,1) Propagate earth-fixed flag
             .propagateECIR      (1,1) Propagate ECIR flag
             .stopping           (:)   Stopping condition data structure
             .nTess              (1,1) Number of tesseral harmonics
             .nZonal             (1,1) Number of zonal harmonics
             .gravityModel       (.)   Gravity model
                   .s                  (:,:) S terms
                   .c                  (:,:) C terms
                   .j                   (:)   m = 0 terms
                   .mu                 (1,1) Gravitational parameter (km^3/sec^2)
                   .a                  (1,1) Earth radius
                   .name               (1,1) Planet name
                   .isNormalized       (1,1) Boolean for normalization
Outputs
 xDot   (6,1)     The state vector derivative [x;y;z;dx/dt;dy/dt;dz/dt]
References AGravityC(), ECIToPlanet(), TruEarth(), and vector().
FOrbLEOP()
function FOrbLEOP (in t, in x, in d)
 This model is compatible with ode113. It includes an event for
 apogee. If events are on it will stop at apogee unless a burn is
 underway. Its companion function is FOrbLEOPStopping
Form
 xDot = FOrbLEOP( t, x, d )
Inputs
 t                      Time
 x             (7,1)    The state vector [r;v;m]
 d             (1,1)    Data structure
                        .thrust    (1,1) Engine thrust (N)
                        .mu        (1,1) Gravitational parameter
                        .uE        (1,1) Exhaust velocity (m/s)
                        .cDA       (1,1) Drag area product
                        .burnStart (1,1) Start time of burn
                        .burnEnd   (1,1) End time of burn
Outputs
 xDot          (7,1)     The state vector derivative d[r;v;m]/dt
References and(), AtmDens1(), FOrbLEOPStopping(), Mag(), and vector().
Referenced by FOrbLEOPStopping().
FOrbLowThrust()
function FOrbLowThrust (in t, in x, in flag, in d)
 and thrust aligned with the velocity vector. This produces a nearly optimal
 spiral into or out from an orbit.
Form
 varargout = FOrbLowThrust( t, x, flag, d )
Inputs
 t             (1,1)  Time
 x             (5,1)  The state vector [r;phi;rDot;phiDot;mass]
 flag          (1,:)  Flags for ode113
 d             (1,1)  .stoppingCondition (1,:) 'time',
                                               'approaching distance',
                                               'receding distance',
                                               'increasing velocity',
                                               'decreasing velocity',
                                               'escape'
                      .stoppingValue     (1,1) value
                      .mu                (1,1) gravitational parameters
                      .thrust            (1,1) Thrust
                      .uE                (1,1) Exhaust velocity
                      .mass              (1,1) Dry mass
                      .absTol            (1,1) Absolute tolerance
                      .relTol            (1,1) Relative tolerance
                      .t                 (1,:) Time steps
Outputs
 varargout     (5,1)  The state vector derivative
References and(), and vector().
Referenced by PropagateLowThrust().
FOrbLTE()
function FOrbLTE (in t, in x, in d)
Designed for use with ode113. Includes a state for the mass and for the total delta-V, obtained by integrating the applied acceleration. Thrust and uE are treated as constant.
See also
LowThrustSim.
Form
 vargout = FOrbLTE( t, x, d )
Inputs
 t                      Time
 x             (n,1)    The state vector [r;v;m;DV]
 d             (.)      Data structure
                        .thrust  Engine thrust (N)
                        .mu      Gravitational parameter
                        .uE      Exhuast velocity (m/s)
Outputs
 xDot          (n,1)     The state vector derivative d[r1;v1;r2;v2...]/dt
References and(), LowThrustSim(), Mag(), Unit(), and vector().
Referenced by LowThrustSim().
FPA()
function FPA (in e, in nu)
 This is the angle between the tangent to r and the velocity vector for any
 orbit.
 Since version 1.
Form
 [gamma, cgamma, sgamma] = FPA( e, nu )
Inputs
 e                      Eccentricity
 nu                     True anomaly
Outputs
 gamma                  The flight path angle
 cgamma                 Cosine of gamma
 sgamma                 Sine of gamma
References and(), TextS(), and vector().
Referenced by GuidedLaunch2DSim().
FPlantNoise()
function FPlantNoise (in action, in modifier, in u, in t)
Form
 x = FPlantNoise( action, modifier, u, t )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifier    (1,:)  Modifier to the action or data structure if intialization
 u           (7,1)  [v;rho]
 t           (1,1)  Time
Outputs
 x           (3,1) Force vector in the v frame
References close(), CloseFigure(), CreateCallback(), FPlantNoise(), get(), GetH(), GetNewTag(), HelpSystem(), Initialize(), PropagateOrbitPlugIn(), PutH(), set(), and vector().
Referenced by FPlantNoise().
FSolar()
function FSolar (in action, in modifier, in u, in t)
 Assumes the surface normal is always aligned with the sun. Includes eclipses
 and distance from the sun.
Form
 x = FSolar( action, modifier, u, t )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifier    (1,:)  Modifier to the action or data structure if initialization
 u           (1,1)  .rSun (3,1) Sun Vector (km)
                    .r    (3,1) Spacecraft vector (km)
 t           (1,1)  Time
Outputs
 x           (1,1)  The tag if action is 'initialize'
                    If the action is update
                    x.f    (3,1) Force vector in the ECI frame
                    x.mDot (1,1) Mass derivative
References and(), close(), CloseFigure(), CreateCallback(), FSolar(), get(), GetH(), GetNewTag(), HelpSystem(), Initialize(), isempty(), PropagateOrbitPlugIn(), PutH(), set(), and vector().
Referenced by FSolar().
FVarEq()
function FVarEq (in x, in t, in eType, in aD, in tol, in mu)
 Since version 1.
Form
 xDot = FVarEq( x, t, eType, aD, tol, mu )
Inputs
 x                     Elements vector [a;i;W;w;e;M] or [a;P1;P2;Q1;Q2;l]
 t                     Current time (for use with RK4)
 eType                 'eqt','eqp','elt','elp' where
                         'eq' --> equinoctial
                         'el' --> elements (Gauss formulation)
                         't'  --> tangential
                         'p'  --> polar
 aD                    Disturbance vector [tangent;normal;z]
 tol                   Tolerance for Kepler's equation solver
 mu                    Gravitational parameter
Outputs
 xDot                  Derivative of the elements
References RK4(), and vector().
GetFuelBudgetDataFromCAD()
function GetFuelBudgetDataFromCAD (in g)
Obtain data from thruster and fuel tank components as identified by fields within deviceInfo.
Form
 x = GetFuelBudgetDataFromCAD( g )
Inputs
 g         (.) CAD data structure
               .deviceInfo.uECoefficient  (1,2)  Identifies a thruster
               .deviceInfo.massPressurant (1,2)  Identifies a tank
Outputs
 x
          .inr          (3,3) Inertia matrix
          .cM           (3,1) Center of mass
          .dryMass      (1,1) Vehicle dry mass
          .thrusterData (.)   Thruster data
                               .r  (3,:) Thruster position vectors
                               .u  (3,:) Thruster unit vectors
                               .iSP    (1,:) Specific impulse coeffs
                               .thrust (1,:) Thrust coeffs
                               .systemTemp (1,1) Tank temp
                               .systemVol  (1,1) Tank volume
                               .systemMass (1,1) Fuel mass
See also
: DeviceProperties
References and(), DeviceProperties(), and length().
GlideSlope()
function GlideSlope (in uGS, in rTarget, in x, in rPlanet)
Form
 gS = GlideSlope( uGS, rTarget, x, rPlanet )
Inputs
 uGS     (3,1) Glide slope reference
 rTarget (3,1) Target vector
 x       (3,:) Trajectory
 rPlanet    (1,1) Radius of the target planet
Outputs
 gS      (1,:) Glide slope angle (deg)
References ACosD(), and(), DupVect(), Glide(), GlideSlope(), Mag(), Plot2D(), RVOrbGen(), Trajectory(), Unit(), and vector().
Referenced by GlideSlope().
GlideslopeCircumnav()
function GlideslopeCircumnav (in x0, in w, in N, in T, in rho, in a)
Form
 [dVM, t, x] = GlideslopeCircumnav( x0, w, N, T, rho, a )
 Inputs
 x0   (6,1)   Relative state in LVLH frame (m, m/s)
 w      (1)   Orbit rate (rad/sec)
 N      (1)   Number of pulses, default is 4.
 T      (1)   Period of circumnavigation (s), default is 1 orbit period
 rho    (1)   Radius of circumnavigation (m), leave empty to calculate from x0
 a    (3,1)   Orbit normal of circumnavigation ([0;1;0] produces in-plane)
 Outputs
 dVM  (3,N)   Delta-V in LVLH frame
 t    (1,N)   Times to apply the delta-V
 x    (3,N)   State at each delta-V point (before maneuver)
Reference: Hablani, Tapper, Bashian et al. "Guidance algorithms for Autonomous Rendezvous of Spacecraft with a Target Vehicle in Circular Orbit," 2001
References ClohessyWiltshire(), CWSimAndPlot(), Demo(), isempty(), Mag(), OrbRate(), Period(), Unit(), and zeros().
Referenced by DVGlideslope(), and GlideslopePlanner().
GlideslopeGuidance()
function GlideslopeGuidance (in x0, in w, in N, in T, in rTarget, in vCommand)
Calculates inbound and outbound trajectories with a uniform interval of T/N between pulses. Either the period T or the initial velocity can be specified. You must provide a final target velocity.
Form
 [dVM, t, x] = GlideslopeGuidance( x0, w, N, T, rTarget, vCommand )
Inputs
 x0       (6,1)           Initial relative state in LVLH frame
 w          (1)           Orbit rate
 N          (1)           Number of pulses
 T          (1)           Period for glideslope, leave empty to specify
                             the initial commanded velocity instead.
 rTarget  (3,1)           Vector target position in LVLH frame
 vCommand (2,1)           Commanded initial and final velocity
Outputs
 dVM  (3,N)   Delta-V in LVLH frame
 t    (1,N)   Times to apply the delta-V
 x    (3,N)   State at each delta-V point (before maneuver)
References abs(), and(), ClohessyWiltshire(), CWSimAndPlot(), Demo(), isempty(), Mag(), NewtRaph(), OrbRate(), Period(), Rename(), SolveT(), SolveTD(), Unit(), and zeros().
GlideslopePlanner()
function GlideslopePlanner (in x0, in w, in d)
These algorithms apply only to circular orbits. Contains default data for an inbound slope, circumnavigation, and outbound slope (array of 3 segments)
Form
 [dV, t, xM] = GlideslopePlanner( x0, w, d )
Inputs
 x0     (6,1)    Initial relative state (m, m/s)
 w        (1)    Orbit rate
 d        (:)    Structure of data for glideslope segments
                   .N       (1)           Number of pulses
                   .T       (1)           Period for segment (sec)
                   .rTarget (3,1) or (1)  Target vector or radius
                   .a       (3,1)     Orbit normal for circumnavigation
                   .V       (2,1)     Commanded velocity for glideslope
Outputs
 dV      (3,:)    Delta-Vs (m/s)
 t       (1,:)    Time (sec)
 xM      (3,:)    State at each delta-V point (before maneuver)
See also
CWSimAndPlot, Glideslope, GlideslopeCircumnav.
References and(), ClohessyWiltshire(), CWSimAndPlot(), DefaultData(), Demo(), DVGlideslope(), GlideslopeCircumnav(), GlideslopePlanner(), isempty(), length(), OrbRate(), Period(), tj(), and vector().
Referenced by GlideslopePlanner().
GravityMap()
function GravityMap (in lat, in lon, in alt, in nN, in nM, in gravityModel, in f)
Plots the acceleration due to gravity relative to the spherical gravity (point mass model).
Type GravityMap for a demo.
Form
 gMap = GravityMap( lat, lon, alt, nN, nM, gravityModel, f )
Inputs
 lat          (1,:)    Latitude (rad)
 lon          (1,:)    Longitude (rad)
 alt          (1,1)    Altitude (km)
 nN           (1,1)    Highest zonal harmonic (m = 0) (empty gives the max #)
 nM           (1,1)    Highest sectorial and tesseral harmonic
                       (empty gives the max #)
 gravityModel  (.)     Data structure
                       .name (1,:) Model name
                       .mu   (1,1) Gravitational constant (km^3/sec^2)
                       .a    (1,1) Model earth radius (km)
                       .c    (n,n) Cosine coefficients
                       .s    (n,n) Sine coefficients
                       .j    (1,n) Zonal harmonics
                       .isNormalized (1,1)  Boolean
 f           (1,1)    Flattening factor
Outputs
 gMap        (lat,lon)  Gravity map in (m/s^2)
See also
AGravityC, LatLonAltToEF
References AGravityC(), Altitude(), and(), Demo(), GravityMap(), LatLonAltToEF(), and LoadGravityModel().
Referenced by GravityMap().
GroundCoverage()
function GroundCoverage (in xECI, in jD, in d)
Form
 [lat, lon] = GroundCoverage( xECI, jD, d )
Inputs
 xECI            (6,1) [r;v]
 jD              (1,1) Julian sdate
 d                (:)
                       .m    (3,3) Transformation from LVLH to Sensor
                       .fOV        .x  (1,1) angle along x
                                   .y  (1,1) angle along y
                       .e    (3,1) [a;b;c] Dimensions of planet
Outputs
 lat             (1,4) Latitude of the coverage points
 lon             (1,4) Longitude of the coverage points
References Gc2GdLat(), IntersectLineAndEllipsoid(), JD2T(), QLVLH(), QTForm(), R2LatLon(), and TruEarth().
GVEDynamics()
function GVEDynamics (in el, in mu)
The form is:
d/dt(del) = A(el)*del + B(el)*u
where A(el) is all zeros, except lower-left corner is -3n/2a, n is the mean orbit rate, and u is the input acceleration with x,y,z components in the radial, along-track, and orbit-normal (or cross-track) directions, respectively.
 Usage:
 [A,B] = GVEDynamics( el );
Inputs
 el         (1,6) Reference orbital elements [a,i,W,w,e,M]
Outputs
 A          (6,6) State dynamics matrix
 B          (6,3) Input effect matrix
Referenced by CollisionMonteCarlo(), DiscreteGVE(), LowThrustGVERHS(), LowThrustTimeToTransfer(), and LPEccentricGVE().
HEl()
function HEl (in el, in mu)
 Since version 1.
Form
 h = HEl( el, mu )
Inputs
 el                    Elements vector [a,i,W,w,e,M]
 mu                    Gravitational parameter
Outputs
 h                     Angular momentum
References vector().
HEq()
function HEq (in eq, in mu)
 Since version 1.
Form
 h = HEq( eq ,mu )
Inputs
 eq                    Elements vector [a,P1,P2,Q1,Q2,L,K,l,n]
 mu                    Gravitational parameter
Outputs
 h                     Angular momentum
References and(), and vector().
HohmannTransferRendezvous()
function HohmannTransferRendezvous (in elT, in elC, in mu, in tol, in planet)
 The inputs are the target and chase spacecraft elements.
Form
 maneuver  = HohmannTransferRendezvous( elT, elC, mu, tol, planet )
Inputs
 elT           (6,1)   Target orbit elements
 elC           (6,1)   Chase orbit elements
 mu            (1,1)   Gravitational parameter
 tol           (1,1)   Tolerance
 planet        (1,:)   Planet name
Outputs
 maneuver      (1,1)    Maneuver data structure
                        .dV1       (1,1) Transfer orbit insertion delta-V
                        .dV2       (1,1) Target orbit insertion delta-V
                        .tStart    (1,1) Start time relative to epoch
                        .tTransfer (1,1) Time in transfer orbit
References and(), Dot(), DVHoh(), El2RV(), isempty(), LambertTOF(), Map(), NewFig(), Period(), RV2El(), RVOrbGen(), THohmn(), and Unit().
IDrift()
function IDrift (in W0, in i, in altitude, in qs)
Form
 [didt, f, fave] = IDrift( W0, i, altitude, qs )
Inputs
 WO                    Phase of right ascension of the ascending node relative to
                       the sun angle        (deg)
 i                     Inclination          (deg)
 altitude              Altitude above earth ( km)
 qs               (:)  Sun angles with respect to the equatorial plane (deg)
Outputs
 didt                  Inclination rate (deg/yr)
 f                     Acceleration (km/yr)
 fave                  Average acceleration (km/yr)
References: Agrawal, B. R., Design of Geosynchronous Spacecraft, Prentice-Hall, 1986, pp. 72-80.
References Altitude(), length(), and Plot2D().
InclinationRate()
function InclinationRate (in x, in mu)
Computes the inclination change rate and orbit normal vector. This shows where in the orbit inclination changes fastest with a normal acceleration.
Type InclinationRate for a demo.
Form
 [dI, uN, dIMax] = InclinationRate( x, mu )
Inputs
 x     (6,:)  [r;v]
 mu    (1,1) Gravitational potential (km^3/s^2)
Outputs
 dI    (1,:) Inclination rate (rad/sec)
 uN    (3,:) Orbit normal
 dIMax (1,1) Maximum inclination rate (rad/sec)
Reference: Robert Falck and Leon Gefert," A Method of Efficient Inclination Changes for Low-Thrust Spacecraft," Astrodynamics Specialist Conference and Exhibit, Monterey, CA, United States, 2002.
References and(), Demo(), InclinationRate(), Plot2D(), RVOrbGen(), TimeLabl(), and vector().
Referenced by InclinationRate().
InitialOrientation()
function InitialOrientation (in r, in v, in uB, in uH)
 such that a body vector stays aligned with a Hills frame vector.
Form
 [qEB, wB] = InitialOrientation( r, v, uB, uH )
Inputs
 r         (3,:)   ECI position
 v           (3,:)   ECI velocity
 uB        (3,:)   Body vector to align
 uH        (3,:)   Reference Hills frame vector to stay aligned with
Outputs
 qEB          (4,:)   ECI to Body Quaternion
 wB        (3,:)   Body rate
References and(), Mag(), OrbRate(), QForm(), QHills(), QMult(), QPose(), quaternion(), U2Q(), vector(), and zeros().
J2OrbitEffects()
function J2OrbitEffects (in a, in e, in i, in j2, in mu, in rP)
Computes the advance of the perigee, orbit plane precession, critical inclination and the synchronous inclination as a function of the J2 term and other orbital parameters.
Form
 [wDot, WDot, thDot] = J2OrbitEffects( a, e, i, j2, mu, rP )
Inputs
 a              (1,1)  Semi major axis
 e              (1,1)  Eccentricity
 i              (1,1)  Orbit inclination
 j2             (1,1)  J2 term (unnormalized)
 mu             (1,1)  Gravitational parameter
 rP             (1,1)  Planet radius
Outputs
 wDot           (1,1)  Perigee advance  (rad/s)
 WDot           (1,1)  Orbit plane precession (rad/s)
 thDot                 Latitude drift rate        [rad/s]
Reference: Wiesel, W. E. (1989.) Spaceflight Dynamics. pp. 86-87.
See also
SunSyncInclination
References and(), and SunSyncInclination().
Referenced by J2Prop(), and SunSyncInclination().
J2Prop()
function J2Prop (in x0, in jD, in time, in gM, in showWaitBar)
Uses FOrbCartH with the GEMT1.geo Earth gravity model, specifying only the second zonal harmonic, nN = 2, nM = 0.
Form
 x = J2Prop( x0, jD, time, gM, showWaitBar )
Inputs
 x0              (6,1) Initial state [km; km/s]
 jD              (1,1) Initial Julian Date [JD]
 time            (1,:) Time vector [sec]
 gM              (.)   Gravity Model
 showWaitBar     (1,1)  Flag. Set to 1 to show wait bar. Default 0.
Outputs
 x               (6,:) Time history of ECI states [km; km/s]
References abs(), close(), Date2JD(), El2RV(), FOrbCartH(), FOrbHF(), J2OrbitEffects(), J2Prop(), length(), LoadGravityModel(), Period(), Plot3D(), RHS(), RK45(), RV2El(), vector(), and zeros().
Referenced by J2Prop(), and RVSet2El().
K2L()
function K2L (in P1, in P2, in K)
 Since version 1.
Form
 [L, sinL, cosL] = K2L( P1, P2, K )
Inputs
 P1                   e sin(longitude of pericenter)
 P2                   e cos(longitude of pericenter)
 K                    Eccentric longitude
Outputs
 L                    True longitude
 sinL                 Sine of true longitude
 cosL                 Cosine of true longitude
References and().
Referenced by CT2REq(), and Eq2RV().
L2K()
function L2K (in P1, in P2, in L)
 Since version 1.
Form
 K = L2K( P1, P2, L )
Inputs
 P1                   e sin(longitude of pericenter)
 P2                   e cos(longitude of pericenter)
 L                    True longitude
Outputs
 K                    Eccentric longitude
References and().
LambertOpt()
function LambertOpt (in r1, in v1, in r2, in v2, in dT, in mu)
Uses fmins/fminsearch. This routine checks both direct and retrograde orbit types. This is a local minimum and does not exhaustively search specific ranges of start and tranfer time, only in the vicinity of the initial guess.
Form
 [dV, tOptimal, elT] = LambertOpt( r1, v1, r2, v2, dT, mu )
Inputs
 r1            (3,1)   Initial position vector
 v1            (3,1)   Initial velocity
 r2            (3,1)   Target position vector at current time
 v2            (3,1)   Target velocity
 dT            (1,2)   Ideal start and maximum transfer time to reach target
 mu            (1,1)   Gravitational parameter
Outputs
 dV             (:)     Delta-V to apply at start time
                  .a      (3,1) First delta-V (km/s)
                  .b      (3,1) Second delta-V (km/s)
                  .total  (1,1) Total delta-V
 tOptimal      (1,2)    Optimal start and transfer time
 elT           (1,:)    Elements of the transfer trajectory
See also
DVTarget
References and(), DVTarget(), FOrb(), isempty(), RK45(), and vector().
Referenced by TransferTimeToDV().
LambertTOF()
function LambertTOF (in r1, in r2, in dT, in orbitType, in mu, in tol, in maxIter)
 Type LambertTOF for a demo
Form
 [vT, a, p, tol] = LambertTOF( r1, r2, dT, orbitType, mu, tol, maxIter )
Inputs
 r1            (3,1)   Initial position vector
 r2            (3,1)   Final position vector
 dT            (1,1)   Time between position 2 and 1 (s)
 orbitType     (1,:)   'direct' (1) or 'retrograde' (-1)*
 mu            (1,1)   Gravitational parameter*
 tol           (1,1)   Desired tolerance [1e-10]*
 maxIter       (1,1)   Maximum number of iterations [20]*
                         * optional
Outputs
 vT            (3,2)    Transfer velocity at beginning and end of
                        the transfer ellipse
 a             (1,1)    Semi-major axis of the trajectory
 p             (1,1)    The parameter for the orbit
 tol           (1,1)    Achieved tolerance
Reference: Battin, R. H. "An Introduction to the Mathematics and Methods of Astrodynamics", AIAA Education Series. Vallado, D. A. Fundamentals of Astrodynamics and Applications.
References abs(), and(), Cross(), Series(), Unit(), vector(), and zeros().
Referenced by DVTarget(), HohmannTransferRendezvous(), LunarTargeting(), PlanetTransferLambert(), PorkChopTOF(), RendezvousPlanner(), and TransferTimeToDV().
LatLonToRAz()
function LatLonToRAz (in lat0, in lon0, in latF, in lonF, in Rp)
Range is measured along the sphere. Azimuth is from north towards East. The latitude and longitude are geocentric.
See also
RAzToLatLon.
Form
 [r,az] = LatLonToRAz( lat0, lon0, lat, lon, Rp );
Inputs
 lat0         (1)       Initial Latitude     [rad]
 lon0         (1)       Initial Longitude    [rad]
 latF        (1,:)      Final Latitude       [rad]
 lonF        (1,:)      Final Longitude      [rad]
 Rp          (1,1)      Radius of the planet [km]
Outputs
 range       (1,:)      Range along Earth's surface (km)
 az          (1,:)      Azimuth angle back to source site
References and(), LatLonToRAz(), RAzToLatLon(), and set().
Referenced by LatLonToRAz().
LinOrb()
function LinOrb (in x, in n, in aD, in dT)
To get normalized equations with nt as the independent variable, just set n = 1. Pass x as empty to get the state equations. If dT is entered it will generate the discrete time equations
 y      = c*x[k] + d*u[k]
 x[k+1] = a*x[k] + b*u[k]
otherwise
 y      = c*x + d*u
 dx/dt  = a*x + b*u
Form
 xD           = LinOrb( x, n, aD )
 [a, b, c, d] = LinOrb( [], n, [], dT )
Inputs
 x             (6,1) state [dr;rtheta;z;ddr/dt;drtheta/dt;dz/dt]
 n             (1,1) orbit rate
 aD            (3,1) acceleration vector
 dT            (1,1) time step
Outputs
 a or xD       (6,6) State transition matrix or (6,1) state derivative
 b             (6,3) Input matrix
 c             (3,6) Output matrix (position)
 d             (3,3) Feedthrough matrix
References: Kaplan, M., Modern Spacecraft Dynamics and Control, p. 111. Valado, D., Fundamentals of Astrodynamics and Applications, pp. 348-51.
References and(), get(), isempty(), set(), vector(), and zeros().
Referenced by LinOrbLQG(), LPCircular(), LQOrbitController(), RHSLinOrb(), and SafeGuidanceSim().
LoadGEM()
function LoadGEM (in unNorm)
If there is only one output it will output a data structure. GEM is "Goddard Earth Model". GEMT1 dates to 1987.
Loads the GEMT1 mat-file. Corrects the c(2,1) and s(2,1) coefficients for consistency with the IERS Terrestrial reference frame
Form
 gravityModel = LoadGEM( unNorm )
 [sO, c, j, mu, a] = LoadGEM( unNorm )
Inputs
 unNorm           If any input here generate unnormalized coefficients
Outputs
 s0       (36,36) S terms  s(n,m) where n and m are degree and order of the model.
 c        (36,36) C terms  c(n,m)
 j        (36)    m = 0 terms
 mu               Spherical gravitational potential
 a                Earth radius
 or
 gravityModel    (.)   Data structure
 .name (1,:) Model name
 .mu   (1,1) Gravitational constant (km^3/sec^2)
 .a    (1,1) Model earth radius (km)
 .c    (n,n) Cosine coefficients
 .s    (n,n) Sine coefficients
 .j    (1,n) Zonal harmonics
 .isNormalized  (1,1) Boolean
Reference: Seidelmann, P.K, (ed) (1992). Explanatory Supplement to the Astronomical Almanac. University Science Books, Mill Valley, CA. pp. 227-233.
References and(), DupVect(), Factorl(), LoadGEM(), Mesh2(), Plot2D(), and zeros().
Referenced by AGravity(), DVGeoTrx(), LoadGEM(), LoadGravityModel(), RHSGeoHarm(), and RVOrbHF().
LoadGravityModel()
function LoadGravityModel (in action, in fileName, in isNormalized)
of Texas at Austin.
The coefficients returned from this file are normalized by default. Pass true for the last argument to unnormalize them.
This routine works with GEMT1, JGM2 and JGM3. JGM3 is the most accurate earth gravitational model currently available. JGM2 is used by Vallado in his book. GEMT1 is also available within the toolbox by typing LoadGEM. The gravity files all have the suffix '.geo'.
NOTE
All these models are publicly available, however, the proper authorizations to obtain the GEM-*, JGM-1, and JGM-2 models should be directed to NASA/GSFC (Steve Klosko, internet: klosk.nosp@m.o@cc.nosp@m.mail..nosp@m.stx..nosp@m.com (Steve Klosko)). The request for other models should be directed to UT/CSR (shum@.nosp@m.csr..nosp@m.utexa.nosp@m.s.ed.nosp@m.u).
Form
 gravityModel = LoadGravityModel( action, fileName, normalized )
Inputs
 action          (1,:) 'get url' or 'load file'
 fileName        (1,:) fileName
 isNormalized    (1,1) flag whether to output normalized (default) or not
Outputs
 gravityModel    (1,1) Data structure
                       .name (1,:) Model name
                       .mu   (1,1) Gravitational constant (km^3/sec^2)
                       .a    (1,1) Model earth radius (km)
                       .c    (n,n) Cosine coefficients
                       .s    (n,n) Sine coefficients
                       .j    (1,n) Zonal harmonics
                       .isNormalized (1,1)   Boolean
References and(), get(), isempty(), length(), and LoadGEM().
Referenced by AutoDualPCSimStruct(), AutoFormSimStruct(), ClusterGoalsDemoSimStruct(), CollisionDetectSimStruct(), CompareHills(), DemoManeuverSimStruct(), DFFSim(), DFFSimStruct(), EccentricTetrahedronSimStruct(), GravityMap(), J2Prop(), MainDemoSimStruct(), ProjCircSimStruct(), SimpleManeuverSimStruct(), TeamManagementSimStruct(), TestCollisionSimStruct(), TestControlSimStruct(), and TestTeamMgtSimStruct().
LoadNORAD()
function LoadNORAD (in fName, in model, in kMax)
Calls NORAD. May take a few minutes for very long files. See http://celestrak.com/NORAD/archives/ for historical data sets. This function has a built-in demo using historical data for Mir.
Form
 [r, v, jD, s, x] = LoadNORAD( fName, model, kMax )
Inputs
 fName    (:)     File name
 model    (:)     Propagation model, SGP, SGP4, etc.
 kMax    (1,1)    Maximum number of points to get (default: 1e4)
Outputs
 r       (3,:)    Position vectors
 v       (3,:)    Velocity vectors
 jD      (1,:)    Epoch, in Julian date
 s        {:}     Cell array of element set strings
 x        (:)     Data structure of NORAD info
See also
: ConvertNORAD, NORADToEl
References and(), get(), NORAD(), and set().
Referenced by NORAD(), and PropagateTLECommonTime().
LocusOfVisibility()
function LocusOfVisibility (in rSat, in radiusPlanet, in n)
 The planet is spherical.
 Type LocusOfVisibility for a demo.
Form
 rLocus      = LocusOfVisibility( rSat, radiusPlanet, n )
 [lat, lon]  = LocusOfVisibility( rSat, radiusPlanet, n )
Inputs
 rSat          (3,1)   Location of the satellite in the planet frame
 radiusPlanet   (1,1)   Radius of planet
 n             (1,1)   Number of points in the locus
Outputs
 rLocus        (3,n)   Locust of points
 or
 lat           (1,n)   Latitude (rad)
 lon           (1,n)   Longitude (rad)
References and(), Cross(), Demo(), EFToLatLonAlt(), isempty(), LocusOfVisibility(), Mag(), Unit(), and zeros().
Referenced by LocusOfVisibility().
LonMot()
function LonMot (in lon0, in lond0, in a, in t)
Form
 [lon, lond] = LonMot( lon0, lond0, a, t )
Inputs
 lon0                   Initial longitude
 lond0                  Initial longitude rate
 a                      Acceleration
 t                      Time
Outputs
 lon                    Longitude (rad)
 lond                   Longitude rate
LowThrustControl()
function LowThrustControl (in x, in mode, in elTarget, in aMag, in tol, in angWidth)
The control has four discrete modes:
 mode 0 is semi-major axis raising.
 mode 1 is ascending node.
 mode 2 is inclination.
 mode 3 is zero acceleration.
The mode sequence is suitable if your semi-major axis is increasing and inclination is increasing. The angular width is the allowable control region around the optimal true anomaly, which is pi/2 and 3*pi/2 for longitude of the ascending node and 0 and pi for inclination.
Form
 [a,mode,el] = LowThrustControl( x, mode, elTarget, aMag, tol, angWidth )
Inputs
 x         (6,1) [r;v]
 mode      (1,1) Mode index, 0, 1, 2, or 3
 elTarget  (1,6) Elements target [a i W w e M]
 aMag      (1,1) Acceleration magnitude
 tol       (1,1) Maneuver tolerance
 angWidth  (1,1) Width of angles for maneuvers (rad)
Outputs
 a         (3,1) Acceleration vector
 mode      (1,1) Mode index
 el        (1,6) Current elements computed from x
References abs(), and(), Cross(), RV2El(), Unit(), and vector().
LowThrustEscape()
function LowThrustEscape (in planet, in a0)
If planet is entered as a string, a0 must be in km.
This equation is an approximation assuming the orbit is nearly circular throughout the spiral. See also LTSpiral.
Type LowThrustEscape for a demo for escape from Titan's orbit.
Form
 dV = LowThrustEscape( planet, a0 )
Inputs
 planet        (1,:)   Planet name or mu
 a0            (1,1)   Initial semimajor axis
Outputs
 dV            (1,1)    Delta-V
Reference: Wiesel, W. (1989.) Spaceflight Dynamics p. 90.
References and(), LowThrustEscape(), and LTSpiral().
Referenced by LowThrustEscape(), LTSpiral(), and TwoDEscape().
LowThrustSim()
function LowThrustSim (in a0, in aF, in uE, in thrust, in m0, in mu)
Form
 [dV, tDuration] = LowThrustSim( a0, aF, uE, thrust, m0, mu )
Inputs
 a0            (1)   Initial semimajor axis
 aF            (1)   Final semimajor axis
 uE            (1)   Exhaust velocity
 thrust        (1)   Thrust
 m0            (1)   Initial mass
 mu            (1)   Gravitational parameter
                         * includes demo
Outputs
 dV            (1)   Total delta-V expended
 tDuration     (1)   Time to reach aF
See also
LTSpiral and FOrbLTE.
References and(), FOrbLTE(), LTSpiral(), Mag(), Plot2D(), Plot3D(), PlotPlanet(), RV2AE(), TimeLabl(), vector(), and zeros().
Referenced by FOrbLTE().
LQOrbitController()
function LQOrbitController (in x, in q, in r, in dT, in x0, in aD, in mu)
Assumes full state feedback. This means that relative position and velocity must be available as measurements. This would be the case with GPS.
The controller has control along x and y. No control is available along the radial direction.
If aD or x0 are entered it will run a simulation. The plant model is found in LinOrb.m.
The gain produces a control in units km/sec^2. To convert to N multiply k by 1000*mass.
To run an demo without control enter q as a zero matrix.
Form
 k = LQOrbitController( x, q, r, dT, aD, mu )
Inputs
 x                (6,1) State [x;y;z;dX;dY;dZ]
 q                (6,6) State cost matrix
 r                (3,1) Control cost matrix
 dT               (1,1) Time step
 aD               (3,1) Disturbance acceleration vector
 mu               (1,1) Gravitational parameter (default is earth)
Outputs
 k                (2,6) Gain matrix [in track; out of track]
See also
C2DZOH, LinOrb
References and(), C2DZOH(), Constant(), DQCR(), El2RV(), isempty(), LinOrb(), Period(), Plot2D(), RV2El(), vector(), and zeros().
LTAN()
function LTAN (in W, in jD)
The mean sun is computed using the Simon Newcomb equations which are also used in the Astronomal Almanac. The local time is just the difference between this mean sun angle and the right ascension of the ascending node.
Form
 lt = LTAN( W, jD )
Inputs
 W    (1,1)  Right ascension of the ascending node
 jD   (1,1)  Julian date
Outputs
 lt   (1,1)  Local time, in hours (0-24)
References and(), and JDToMidnight().
Referenced by SunSyncNode().
LTPlaneChange()
function LTPlaneChange (in a0, in af, in dI, in accel, in mu)
Valid for inclination changes up to 114.6 degrees. The inputs may be all scalars, all vectors, or two scalars and one vector. Enter acceleration to get a trip time output.
Form
 LTPlaneChange;   % demo
 [dV, dVRatio, t] = LTPlaneChange( a0, af, dI, accel, mu )
Inputs
 a0     (1,:)   Initial semi-major axis (km)
 af     (1,:)   Final semi-major axis   (km)
 dI     (1,:)   Inclination change      (rad)
 accel   (1,1)   Acceleration            (km/s^2)
 mu      (1,1)   Gravitational parameter (km^3/sec^2)*
                     * default, Earth
Outputs
 dV      (1,:)   Total delta-v
 dVRatio (1,:)   Ratio of total delta-v to Hohmann Delta-V
 t       (1,:)   Maneuver duration (days)
Reference: J. Kechichian, "Reformulation of Edelbaum?s Low-Thrust Transfer Problem Using Optimal Control Theory", Journal of Guidance, Control, and Dynamics Vol. 20, No. 5, September?October 1997
References and(), Demo(), get(), length(), LTPlaneChange(), OptDIH(), OrbMnvrInclination(), Plot2D(), vector(), VOrbit(), and zeros().
Referenced by LTPlaneChange().
LTSpiral()
function LTSpiral (in a0, in af, in accel, in mu)
The acceleration is aligned with the velocity vector. This equation is an approximation assuming the orbit is nearly circular throughout the spiral. See also LowThrustEscape.
The acceleration must be in the same units as a0 and mu.
Form
 [dV, dVRatio, t] = LTSpiral( a0, af, accel, mu )
Inputs
 a0      (1,:)   Initial semi-major axis (km)
 af      (1,:)   Final semi-major axis   (km)
 accel   (1,1)   Acceleration            (km/s^2)
 mu      (1,1)   Gravitational parameter (km^3/sec^2)
Outputs
 dV      (1,:)   Total delta-v
 dVRatio (1,:)   Ratio of total delta-v to Hohmann Delta-V
 t       (1,:)   Maneuver duration (days)
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 89-90.
References abs(), and(), Constant(), Demo(), DVHoh(), length(), LowThrustEscape(), LTSpiral(), Plot2D(), and vector().
Referenced by L2OrbitPlots(), LowThrustEscape(), LowThrustSim(), and LTSpiral().
LTVCon()
function LTVCon (in r0, in r, in c1, in c2, in orbitType, in mu)
 dr/dt = c1 + c2*vH where vH is the horizontal velocity and c1
 and c2 are constants
 Since version 2.
Form
 v0 = LTVCon( r0, r, c1, c2, orbitType, mu )
Inputs
 r0            (3,1)   Initial position vector
 r             (3,1)   Final position vector
 c1            (1,1)   Constant
 c2            (1,1)   Constant
 orbitType     (1,:)   'direct' or 'retrograde'
 mu            (1,1)   Gravitational parameter (default is the earth)
Outputs
 v0            (1,1)    Initial velocity
References: Bond, V.R. and M. C. Allman, "Modern Astrodynamics", Princeton University Press, 1996, pp. 88-90
References and(), Constant(), isempty(), Mag(), TARes(), and vector().
M2E()
function M2E (in e, in meanAnom, in tol, in nMax)
from the mean anomaly and the eccentricity.
Form
 eccAnom  = M2E( e, meanAnom, tol, nMax )
Inputs
 e            (1,:)    Eccentricity
 meanAnom     (1,:)    Mean anomaly (rad)
 tol          (1,1)    Tolerance
 nMax         (1,1)    Maximum number of iterations
Outputs
 eccAnom     (1,:)     Eccentric anomaly (rad)
References and(), Demo(), DupVect(), isempty(), length(), M2E(), M2EEl(), M2EHy(), Plot2D(), scalar(), and zeros().
Referenced by M2E(), M2Nu(), Mean2OscS(), RVFromKepler(), and RVOrbGen().
M2EApp()
function M2EApp (in e, in meanAnom)
 Since version 1.
Form
 eccAnom = M2EApp( e, meanAnom )
Inputs
 e             (: or 1)  Eccentricity
 meanAnom      (:)       Mean anomaly
Outputs
 eccAnom       (:)       Eccentric anomaly
References: Battin, R.H. (1987). An Introduction to the Mathematics and Methods of Astrodynamics, AIAA Press, p. 194.
References and(), isempty(), length(), M2EApp(), Plot2D(), Sep(), and zeros().
Referenced by M2EApp(), and M2EEl().
M2EEl()
function M2EEl (in ecc, in meanAnom, in tol, in nMax)
 Computed from the mean anomaly and the eccentricity. The user can optionally
 specify a tolerance and maximum number of iterations.
 For a demo plot call M2EEl( ecc ).
Form
 eccAnom = M2EEl( ecc, meanAnom, tol, nMax )   or
 eccAnom = M2EEl( ecc, meanAnom, tol )         or
 eccAnom = M2EEl( ecc, meanAnom)
Inputs
 ecc            (1,:) Eccentricity
 meanAnom       (1,:) Mean anomaly
 tol            (1,1) Tolerance(optional, default is 1e-8)
 nMax           (1,1) Maximum number of iterations
                      (optional, default is no maximum. Can
                      only be input if tol is also specified.)
Outputs
 eccAnom        (1,:) Eccentric anomaly
References abs(), and(), length(), M2EApp(), M2EEl(), and Plot2D().
Referenced by ADGen(), ADPartls(), M2E(), M2EEl(), PltOrbit(), and VarGausT().
M2EHy()
function M2EHy (in e, in meanAnom, in tol, in nMax)
 Computed from the mean anomaly and the eccentricity.
 This uses Kepler's method to iterate on the solution
 For a demo plot use  M2EHy( e ).
Form
 eccAnom = M2EHy( e, meanAnom, tol, nMax )
Inputs
 e             (1,:)  Eccentricity
 meanAnom      (1,:)  Mean anomaly
 tol           (1,1)  Tolerance
 nMax          (1,1)  Maximum number of iterations
Outputs
 eccAnom       (1,:)   Eccentric anomaly
References and(), and M2EHy().
Referenced by M2E(), and M2EHy().
M2Nu()
function M2Nu (in e, in M, in tol, in nMax)
Form
 nu  = M2Nu( e, M, tol, nMax )
Inputs
 e               (1,1)  Eccentricity
 M               (1,:)  Mean anomaly (rad)
 tol             (1,1)  Tolerance
 nMax            (1,1)  Maximum number of iterations
Outputs
 nu              (1,:)  True anomaly (rad)
References E2Nu(), isempty(), length(), M2E(), M2NuPb(), and Plot2D().
Referenced by AutoFormGeometry(), CheckDeltaVs(), CollisionMonitor(), CollisionMonteCarlo(), DeltaAlfriend2El(), DeltaEl2Alfriend(), El2Alfriend(), El2RV(), ElToMEq(), FFEccDeltaElem2Goals(), FFEccDiscreteHills(), FFEccEstimateCost(), FFEccFrameCompare(), FFEccGenerateTeamGoals(), FFEccTargetTrueAnom(), FlightPathAngle(), GPSOrbit(), GVEGuidance(), ImpulsiveLPManeuver(), LinOrbLQG(), LocallyOptimalTraj(), LPEccentricGVE(), LPEccentricTimeWeight(), Lyapunov(), M2NuAbs(), MeanAnom2TrueLat(), OrbitLoweringManeuvers(), TestFFEccLinOrb(), TestLPEccentric(), TestLPEccentricGVE(), and TransformGeom2Hills().
M2NuAbs()
function M2NuAbs (in e, in M, in tol, in nMax)
 Between -pi / pi
Form
 nu  = M2NuAbs( e, M, tol, nMax )
Inputs
 e                     Eccentricity
 M                     Mean anomaly (rad)
 tol                   Tolerance                      (optional)
 nMax                  Maximum number of iterations   (optional)
Outputs
 nu                    True anomaly (rad)
References M2Nu().
Referenced by LPEccentricGVE(), and TrueAnomalySpacing().
M2NuPb()
function M2NuPb (in meanAnom)
 Since version 1.
Form
 nu = M2NuPb( meanAnom )
Inputs
 meanAnom       (1,:) Mean anomaly
Outputs
 nu             (1,:) True anomaly for a parabola
References abs(), length(), and Plot2D().
Referenced by M2Nu().
M2NuS()
function M2NuS (in e, in M)
 Since version 1.
Form
 nu = M2NuS( e, M )
Inputs
 e                     Eccentricity
 M              (1,:)  Mean anomaly (rad)
Outputs
 nu                    True anomaly
References length(), Plot2D(), series(), and SHarm().
ManeuverDuration()
function ManeuverDuration (in mI, in dV, in uE, in thrust)
This routine computes maneuver duration given the desired velocity change, exhaust velocity, initial mass and thrust.
Type ManeuverDuration for a demo.
Form
 [t, mP] = ManeuverDuration( mI, dV, uE, thrust )
Inputs
 mI      (1,1) Initial mass (kg)
 dV      (1,1) Desired change in velocity (km/s)
 uE      (1,1) Exhaust velocity  (km/s)
 thrust  (1,1) Thrust (N)
Outputs
 t          (1,1) Maneuver duration (s)
 mP      (1,1) Fuel mass (kg)
References and(), Demo(), ManeuverDuration(), and TimeLabl().
Referenced by ManeuverDuration(), and OrbitLoweringManeuvers().
ManeuverEnvelope()
function ManeuverEnvelope (in f, in m)
Form
 [p, r] = ManeuverEnvelope( f, m )
Inputs
 f            (:,1)     Available force
 m            (1,1)     Mass
Outputs
 p            (1,:)     Period
 r            (1,:)     Corresponding radius
References length(), Period(), and Plot2D().
MaximumDeltaV()
function MaximumDeltaV (in f, in uE)
If uE is not entered you get the ratio.
Type MaximumDeltaV for a demo.
Form
 maxDV = MaximumDeltaV(f,uE)
Inputs
 f       (1,:) Tank fraction
 uE      (1,1) Exhaust velocity
Outputs
 maxDV   (1,:)  Maximum velocity change or ratio
References Demo(), get(), MaximumDeltaV(), and Plot2D().
Referenced by MaximumDeltaV().
MeanAnom()
function MeanAnom (in dt, in a, in p, in mu)
Form
 M = MeanAnom( dt, a, p, mu )
Inputs
 dt                   Change in time
 a                    Semi-major axis (+ for ellipse, inf for parabola
                      and - for hyperbola)
 p                    Parameter (used for parabolas)
 mu                   Gravitational parameter
Outputs
 M                    Mean anomaly
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 56-57.
References abs(), and(), and Plot2D().
MeanMotn()
function MeanMotn (in a, in mu)
Form
 omegaMean = MeanMotn( a, mu )
Inputs
 a                     Semi-major axis
 mu                    Gravitational constant
Outputs
 omegaMean             mean orbit rate
Referenced by ComputeTLE().
MEQToECI()
function MEQToECI (in r, in v)
 Since version 7.
Form
 m = MEQToECI( r, v )
Inputs
 r          (3,1)  Position (km)
 v          (3,1)  Velocity (km/s)
Outputs
 m          (3,3) Transformation matrix
References Cross(), and Unit().
MEqToEl()
function MEqToEl (in x, in mu)
The modified equinoctial elements are
 p = a(1 + e^2)
 f = ecos(w + W);
 g = esin(w + W);
 h = tan(i/2)cosW
 k = tan(i/2)sinW
 L = W + w + nu
W is right ascension of the ascending node and w is argument of perigee.
Form
 el = MEqToEl( x, mu )
Inputs
 x              (6,:)  Modified equinoctial elements [p;f;g;h;k;L]
 mu             (1,1)  Gravitational parameter
Outputs
 el             (6,:)  Keplerian elements [a;i;W;w;e;M]
References and(), ElToMEq(), MEqToEl(), and Nu2M().
Referenced by MEqToEl(), and Plot3DTrajectory().
MEqToRV()
function MEqToRV (in x, in mu)
 The modified equinoctial elements are
 p = a(1 + e^2)
 f = ecos(w + W);
 g = esin(w + W);
 h = tan(i/2)cosW
 k = tan(i/2)sinW
 L = W + w + nu
 W is right ascension of the ascending node
 w is argument of perigee
 Since version 7.
Form
 [r, v] = MEqToRV( x, mu )
Inputs
 x              (6,:)  Elements
 mu             (1,:)  Gravitational parameter
Outputs
 r              (3,:) Position vector
 v              (3,:) Velocity vector
References and(), MEqToRV(), and vector().
Referenced by LambdaToConeClock3D(), LocallyOptimalConeClock3D(), MEqToRV(), Plot3DTrajectory(), and RVToMEq().
ML2K()
function ML2K (in P1, in P2, in meanLong, in tol, in nMax)
 If meanLong is not entered a vector from 0 to 2*pi is used.
 Since version 1.
Form
 eccLong = ML2K( P1, P2, meanLong, tol, nmax )
Inputs
 P1                   e sin(longitude of pericenter)
 P2                   e cos(longitude of pericenter)
 meanLong             Mean longitude
 tol                  Tolerance for Newton-Raphson (default 1e-8)
 nMax                 Max number of iterations (default is inf)
Outputs
 eccLong              Eccentric longitude (K)
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, p. 493.
Referenced by CT2REq(), and Eq2RV().
ML2KApp()
function ML2KApp (in P1, in P2, in meanLong)
 Uses a series approximation to Kepler's equation.
 Since version 1.
Form
 eccLong = ML2KApp( P1, P2, meanLong )
Inputs
 P1                   e sin(longitude of pericenter)
 P2                   e cos(longitude of pericenter)
 meanLong             Mean longitude
Outputs
 eccLong              Eccentric longitude (K)
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, p. 196.
References series().
N2A()
function N2A (in n, in mu)
 Has a built-in demo with a plot.
 Since version 1.
Form
 a = N2A( n, mu )
Inputs
 n                     Mean orbit rate
 mu                    Gravitational constant (default is Earth)
Outputs
 a                     Semi-major axis
References: Bates, R.B. Fundamentals of Astrodynamics, pp. 185-187.
NonDimensionalOrbit()
function NonDimensionalOrbit (in r, in v, in t, in mu, in rRef, in dir)
 dir determines the direction. dir = 0 or dir omitted
 will non-dimensionalizes r, v, t and mu. r, v and t may be vectors.
 We non-dimesionalize as follows:
 Quantity   Units       Nondimensionalizing Constanst
 r           [L]         rRef
 t           [T]         rRef/sqrt(mu/rRef)
 v           [L/T]       sqrt(mu/rRef)
 mu          [L^3/T^2]  mu
 accel       [L/T^2]     mu/rRef^2
 sqrt(mu/r) = v = L/T so we pick T = rRef/sqrt(mu/r)
 Non-dimensional units are often better for estimation and optimization.
 For circular orbits the nominal orbit radius is best for rRef. For
 other orbits, such as a geosynchronous transfer orbit you can pick
 the mean orbit. When using nondimensional units you must
 non-dimensionalize the external accelerations by multiplying by
 fAcc.
 Type NonDimensionalOrbit for a simulation of a circular planar orbit
 at 1 AU from the sun. It will plot non-dimensional and dimensional
 units. In non-dimensional units r and v will oscillate between +/- 1.
 Since version 2014.1
Form
 [r, v, t, mu, fAcc] =  NonDimensionalOrbit( r, v, t, mu, rRef, dir )
Inputs
 r       (3,:)   Position vectors
 v       (3,:)   Velocity vectors
 t       (1,:)   Time vector
 mu      (1,1)   Gravitational constant
 rRef   (1,1)   Reference length
 dir     (1,1)   0 or no input means non-dimensionalize
Outputs
 r       (3,:)   Position vectors
 v       (3,:)   Velocity vectors
 t       (1,:)   Time vector
 mu      (1,1)   Gravitational constant
 fAcc    (1,1)   Acceleration scaling
References and(), Constant(), Demo(), length(), NonDimensionalOrbit(), Period(), Plot2D(), RHSOrbit(), RK4(), vector(), and zeros().
Referenced by NonDimensionalOrbit().
NORAD()
function NORAD (in dStart, in dEnd, in nPts, in model, in pType, in file)
SGP, SGP4, SGP8.
[] can be entered for any input. To input a time vector, pass it in for dStart and pass an empty matrix ([]) for dEnd and nPts. file can be a file name or a string input. The string must have the same format as the file for example:
 s = [sprintf('SGPTest \n'),...
 sprintf('1 88888U          80275.98708465  .00073094  13844-3  66816-4 0     8\n'),...
 sprintf('2 88888  72.8435 115.9689 0086731  52.6988  110.5714 16.05824518  105')];
See also
LoadNORAD, ConvertNORAD, TNORAD, and PropagateTLE.
 Forms:
 rV = NORAD( dStart, dEnd, nPts, model, [], file )
 rV = NORAD( tVec, [], [], model, [], file )
 NORAD( tVec, [], [], model, pType, file ), creates desired plot type
Inputs
 dStart    (1,1) or (1,:)   Days from Epoch of start or time vector (sec)
 dEnd          (1,1)        Days from Epoch of end
 nPts          (1,1)        Number of points
 model         (1,:)        Model type 'SGP', 'SGP4', 'SDP4', 'SGP8', 'SGD8'
 pType         (1,:)        Either '2d' or '3d' plot, 3d is default
 file          (1,:)        File name
Outputs
 rV            (n)     Structure for position and velocity vectors
                       rV.v    (3,:)
                       rV.r    (3,:)
                       rV.name (1,:)
 x             (n)     Structure of NORAD element data
References and(), ConvertNORAD(), Demo(), isempty(), LoadNORAD(), NORAD(), PropagateTLE(), and vector().
Referenced by ComputeTLE(), ConvertNORAD(), LoadNORAD(), NORAD(), NORADToEl(), PropagateTLE(), and PropagateTLECommonTime().
NORADToEl()
function NORADToEl (in dStart, in dEnd, in nPts, in model, in s)
 s can be a file name or a string input. The string must have the
 same format as the file for example:
 s = [sprintf('SGPTest \n'),...
 sprintf('1 88888U          80275.98708465  .00073094  13844-3  66816-4 0     8\n'),...
 sprintf('2 88888  72.8435 115.9689 0086731  52.6988  110.5714 16.05824518  105')];
 A file may contain multiple sets of elements.
Form
 [el, name, jD] = NORADToEl( jDStart, jDEnd, nPts, model, s )
Inputs
 dStart        (1,1)   Days from Epoch of start
 dEnd          (1,1)   Days from Epoch of end
 nPts          (1,1)   Number of points
 model         (1,:)   Model type 'SGP', 'SGP4', 'SDP4', 'SGP8', 'SGD8'
 s             (1,:)   File name or string containing the two line elements
                         * includes demo
Outputs
 el            (:,6)   Elements vector [a,i,W,w,e,M]
 name          {:}     Satellite name
 jD            (1,1)   Julian day number
References NORAD(), and vector().
Referenced by ComputeTLE().
NormalizationMatrix()
function NormalizationMatrix (in nN, in nM)
c unnormalized * f = c normalized s unnormalized * f = s normalized p normalized = p unnormalized / fp
Form
 [f,fp] = NormalizationMatrix( nN, nM )
Inputs
 nN (1,1)  Rows
 nM     (1,1)  Columns
Outputs
 f   (nN,mM)   State derivatives
 fp (1,nM)    Coefficients for p (zonal terms)
See also
UnnormalizeGravity
References and(), DispWithTitle(), NormalizationMatrix(), UnnormalizeGravity(), and zeros().
Referenced by NormalizationMatrix(), and UnnormalizeGravity().
Nu2E()
function Nu2E (in e, in nu)
For a demo plot use Nu2E(e).
Form
 E = Nu2E( e, nu )
Inputs
 e  (1,:)  or (1,1) Eccentricity
 nu (1,:)  True anomaly
Outputs
 E   (1,:)  Eccentric or hyperbolic anomaly
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 57,60.
References abs(), DupVect(), isempty(), length(), Nu2E(), Plot2D(), scalar(), and zeros().
Referenced by Nu2E(), Nu2M(), RV2El(), RVOrbHF(), and RVSet2El().
Nu2M()
function Nu2M (in e, in nu)
Form
 [meanAnom,eccAnom] = Nu2M( e, nu )
Inputs
 e             (1,1)  Eccentricity
 nu            (1,:)  True anomaly
Outputs
 meanAnom       (1,:)  Mean anomaly
 eccAnom        (1,:)  Eccentric anomaly
References E2M(), Nu2E(), and Plot2D().
Referenced by AE2VR(), Alfriend2El(), ApogeeRaisingDeltaV(), CheckDeltaVs(), DVOrbitDrag(), FFEccDiscreteHills(), FFEccTargetTrueAnom(), LPEccentric(), LPEccentricGVE(), LPEccentricTimeWeight(), MEqToEl(), Nu2MAbs(), OrbitLoweringManeuvers(), OrbMnvrCircularize(), RAEToM(), RV2El(), RVOrbGen(), TimeUntilTheta(), TrueAnomalySpacing(), and VInfRPToRV().
Nu2MAbs()
function Nu2MAbs (in e, in nu, in tol, in nMax)
Form
 M = Nu2MAbs( e, nu, tol, nMax );
Inputs
 e                     Eccentricity
 nu                    True anomaly (rad)
 tol                   Tolerance                      (optional)
 nMax                  Maximum number of iterations   (optional)
Outputs
 M                     Mean anomaly (rad)
References Nu2M().
Referenced by TestLPEccentricGVE().
NuInf()
function NuInf (in e)
If e is < 1 it substitutes 1.
Form
 psi = NuInf( e )
Inputs
 e                    Eccentricity
Outputs
 psi                  Asymptote angle (rad)
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 54.
OptDIH()
function OptDIH (in e1, in a1, in e2, in a2, in Di, in mu)
The Hohman transfer is done from the perigee of the first orbit to the apogee of the second.
Form
 [dv, dv1, dv2, et, Di1] = OptDIH( e1, a1, e2, a2, Di, mu )
Inputs
 e1                    Parking orbit eccentricity
 a1                    Parking orbit semimajor axis
 e2                    Final orbit eccentricity
 a2                    Final orbit semimajor axis
 Di                    Change in inclination (rad)
 mu                    Gravitational parameter
Outputs
 dv                    Total delta v
 dv1                   Low orbit to transfer orbit delta v
 dv2                   Transfer orbit to high orbit delta v
 et                    Transfer orbit eccentricity
 Di1                   Inclination correction during first Dv
References: Hornbeck, R., Numerical Methods, Quantum, 1975, pp. 66-67.
References A2Apogee(), A2Perige(), and abs().
Referenced by DVHohInc(), and LTPlaneChange().
OrbDecay()
function OrbDecay (in h, in cD, in A, in m, in mu, in R, in rho0, in hScale)
Default units are km.
 Type OrbDecay for a demo in earth orbit
Form
 t = OrbDecay( h, cD, A, m, mu, R, rho0, hScale )
Inputs
 h                  Altitudes                                  [km]
 cD                 Drag coefficient (2 to 4)
 A                  Effective satellite area                   [m2]
 m                  Satellite mass                             [kg]
 mu                 Gravitational parameter              [km3/sec2]
 R                  Planet radius                              [km]
 rho0               Base density (at zero altitude)         [kg/m3]
 hScale             Atmospheric scale height (default is 6 km) [km]
Outputs
 t                  Decay time
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 83-86. Hughes, P. C., Spacecraft Attitude Dynamics, John Wiley 1986, p. 259.
References Demo(), and OrbDecay().
Referenced by OrbDecay().
OrbElemDiff()
function OrbElemDiff (in el0, in el, in type)
This wraps the phase appropriately for all the angular elements.
Form
 dEl = OrbElemDiff( el0, el, type )
Inputs
 el0            (1,6) reference orbital elements
 el             (1,6) secondary orbital elements
 type            (1)  type
                        1 -- [a,th,i,q1,q2,W]
                        2 -- [a,i,W,w,e,M] (default)
Outputs
 dEl           (:,6) orbital element differences
References and(), Demo(), OrbElemDiff(), and WrapPhase().
Referenced by DFFSim(), ECI2MeanElements(), FFEccHills2DeltaElem(), GVEGuidance(), InitializeFormation(), LowThrustTimeToTransfer(), and OrbElemDiff().
OrbitalPlane()
function OrbitalPlane (in rA, in inc, in jD, in color, in figH)
 The Earth is shown at the time when the ascending node is crossed
Form
 OrbitalPlane( rA, inc, jD, color, figH )
Inputs
 rA             (1,1)  Right ascension (rad)
 inc            (1,1)  Inclination (rad)
 jD             (1,1)  Julian date UT (day)
 color           (:)   Color of orbital plane (optional)
 figH           (1,1)  Figure handle (optional)
Outputs
 none
References Circle(), GMSTime(), isempty(), length(), OrbNEl(), RotMat(), set(), square(), Unit(), and zeros().
Referenced by ECI2OrbitPlane(), and LaunchTime().
OrbitClosestPoint()
function OrbitClosestPoint (in rEFTarget, in el, in jDEpoch, in n, in nOrbits)
You can input any number of orbits to check. The function propagates the orbit with a Kepler propagator. The Earth rotation is found using TruEarth.
Type OrbitClosestPoint for a demo.
Form
 [rMin, dMin, jDMin] = OrbitClosestPoint( rEFTarget, el, jDEpoch, n, nOrbits )
Inputs
 rEFTarget   (3,m)   Target vectors to check
 el          (1,6)   Keplerian elements [a i Lon Arg e M]
 jDEpoch     (1,1)   Julian date epoch of elements
 n           (1,1)   Number of points to check
 nOrbits     (1,1)   Number of orbits to check
Outputs
 rMin        (3,m)   Nearest orbital point
 dMin        (1,m)   Distance to each point
 jDMin       (1,m)   Julian date for each point (days)
References Demo(), isempty(), JD2000(), JD2T(), Mag(), NewFig(), OrbitClosestPoint(), Period(), RVOrbGen(), TitleS(), TruEarth(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by OrbitClosestPoint().
OrbitDrag()
function OrbitDrag (in v0, in gamma0, in h, in bC)
 Uses AtmDens2.
Form
 [a,t,rho] = OrbitDrag( v0, gamma0, h, BC );
Inputs
 v0              (1,:)     Initial velocity at h (km/s)
 gamma0          (1,:)     Initial flight path angle at h0 (rad)
 h               (1,:)     Altitude (km)
 bC              (1,1)     Ballistic coefficient (kg/m^2)
Outputs
 a               (1,:)     Acceleration over arc (km/s/s)
 t               (1,:)     Time (monotonic from 0) over arc (s)
 rho             (1,:)     Atmospheric density over arc (kg/m^3)
References Altitude(), AtmDens2(), length(), OrbitVel2D(), and zeros().
Referenced by RHSOptimalFPA().
OrbitFromSynodic()
function OrbitFromSynodic (in elT, in p, in mu, in h)
 Type OrbitFromSynodic for a demo.
 Since version 2014.1
Form
 el = OrbitFromSynodic( elT, p, mu, h )
Inputs
 el            (1,6)   Target orbit [a i W w e M]
 p             (1,1)   Desired synodic period
 mu            (1,1)   Gravitational constant
 h             (1,1)   Any entry get a higher orbit
Outputs
 el            (1,6)   Orbit [a i W w e M]
References Constant(), Demo(), get(), OrbitFromSynodic(), Period(), Plot2D(), and RVOrbGen().
Referenced by OrbitFromSynodic().
OrbitInsertion()
function OrbitInsertion (in rA, in phiM, in rM, in mu)
 Since version 8.
Form
 [v, gamma, a, e] = OrbitInsertion( rA, phiM, rM, mu )
Inputs
 rA              (1,1) Apogee radius
 phiM            (1,1) Insertion true anomaly (rad)
 rM              (1,1) Insertion altitude
 mu              (1,1) Gravitational constant
Outputs
 v               (2,1) Insertion velocity
 gamma           (1,1) Insertion flight path angle (rad)
 a               (1,1) Semi-major axis transfer orbit
 e               (1,1) Eccentricity transfer orbit
Reference: Bond, V. R. and M. C. Allman, "Modern Astrodynamics," Princeton, 1996, pp. 100-107.
References and(), Demo(), length(), Mag(), OrbitInsertion(), and Plot2D().
Referenced by OrbitInsertion().
OrbitJacobian()
function OrbitJacobian (in t, in x, in d)
Form
 j = OrbitJacobian( t, x, d )
Inputs
 t               (1,1) Time
 x               (6,1) [r;v]
 d               (1,1) Data structure
                       .gravityModel.mu    (1,1)
Outputs
 j               (6,6) Jacobian
References Jacobian(), and zeros().
OrbitProp()
function OrbitProp (in x0, in time)
Propagate an orbit around the Earth with no acceleration. Uses FOrbCart.
Form
 x = OrbitProp( x0, time )
Inputs
 x0              (6,1) Initial state [km; km/s]
 time            (1,:) Time vector [sec]
Outputs
 x               (6,:) Time history of ECI states [km; km/s]
See also
: FOrbCart
References Constant(), El2RV(), FOrbCart(), length(), OrbitProp(), Period(), Plot3D(), RK4(), vector(), and zeros().
Referenced by OrbitProp().
OrbitVel2D()
function OrbitVel2D (in v0, in gamma0, in h0, in hF, in rE, in mu)
Form
 [VF, gammaF, a, e, H] = OrbitVel2D( v0, gamma0, h0, hF, rE, mu )
Inputs
 v0         (1,:)     Initial velocity (km/s)
 gamma0     (1,:)     Initial flight path angle (rad)
 h0         (1,:)     Initial altitude (km)
 hF         (1,:)     Final altitude for orbit (km)
 rE         (1,1)     Planet radius (km) (earth is the default)
 mu         (1,1)     Gravitational potential (km^3/s^2) (earth is the default)
Outputs
 vF         (1,:)     Velocity at hF (km/s)
 gammaF     (1,:)     Flight path angle at hF (rad)
 a          (1,:)     Orbit semi major axis (km)
 e          (1,:)     Orbit eccentricity
 H          (1,:)     Orbit angular momentum, (km^2/s)
Referenced by OrbitDrag().
OrbMnvrBielliptic()
function OrbMnvrBielliptic (in rI, in rB, in rF, in mu)
 The intermediate radius is much larger than the final radius.
 The delta-Vs are at
 The initial orbit
 Apogee of the transfer orbit
 The final orbit
Form
 [deltaV, tOF] = OrbMnvrBielliptic( rI, rB, rF, mu )
Inputs
 rI          (1,1)  Initial radius
 rB          (1,1)  Intermediate radius
 rF          (1,1)  Final radius
 mu          (1,1)  Gravitational parameter
Outputs
 deltaV      (1,1)  Delta-V data structure.
                    .total (1,1)    Total required delta-V
                    .a     (1,1) Delta-V at point a
                    .b     (1,1) Delta-V at point b
                    .c     (1,1) Delta-V at point c
 tOF         (1,1)  Time of flight
References abs(), and and().
OrbMnvrCircularize()
function OrbMnvrCircularize (in rI, in vI, in gammaI, in rF, in mu)
The delta-Vs are at
 a. the initial orbit
 b. the final orbit
Form
 [deltaV, tOF, transfer] = OrbMnvrCircularize( rI, vI, gammaI, rF, mu )
Inputs
 rI          (1,1)  Initial radius
 vI          (1,1)  Initial velocity
 gammaI      (1,1)  Initial flight path angle   (rad)
 rF          (1,1)  Final radius
 mu          (1,1)  Gravitational parameter
Outputs
 deltaV      (1,1)  Delta-V data structure.
                    .total (1,1)    Total required delta-V
                    .a     (1,1) Delta-V at point a
                    .b     (1,1) Delta-V at point b
                    .dVaHoriz (1,1) Horizontal portion of (a)
                    .dVaVert  (1,1) Vertical portion of (a)
 tOF         (1,1)  Time of flight
References abs(), Mag(), Nu2M(), RV2AE(), and VOrbit().
Referenced by GuidedLaunch2DCost().
OrbMnvrHohmann()
function OrbMnvrHohmann (in rI, in rF, in mu)
The delta-Vs are at:
 1. The initial orbit
 2. The final orbit
Type OrbMnvrHohmann for a demo with a plot.
Form
 [deltaV, tOF] = OrbMnvrHohmann( rI, rF, mu )
Inputs
 rI          (1,1)  Initial radius
 rF          (1,1)  Final radius
 mu          (1,1)  Gravitational parameter
Outputs
 deltaV      (1,1)  Delta-V data structure.
                    .total (1,1)    Total required delta-V
                    .a     (1,1) Delta-V at point a
                    .b     (1,1) Delta-V at point b
 tOF         (1,1)  Time of flight
Reference: Vallado, D. A. (1997.) Fundamentals of Astrodynamics and Applications. pp 281-282.
References abs(), and(), NewFig(), OrbMnvrHohmann(), Period(), RVOrbGen(), square(), TitleS(), XLabelS(), and YLabelS().
Referenced by OrbMnvrHohmann().
OrbMnvrInclAndHohm()
function OrbMnvrInclAndHohm (in rI, in rF, in iI, in iF, in mu)
 The delta-Vs are at
 The initial orbit
 The final orbit
Form
 [deltaV, deltaI, tOF] = OrbMnvrInclAndHohm( rI, rF, iI, iF, mu )
Inputs
 rI          (1,1)  Initial radius
 rF          (1,1)  Final radius
 II          (1,1)  Initial inclination (rad)
 iF          (1,1)  Final inclination (rad)
 mu          (1,1)  Gravitational parameter
Outputs
 deltaV      (.)    Delta-V data structure.
                    .total (1,1)    Total required delta-V
                    .a     (1,1) Delta-V at point a
                    .b     (1,1) Delta-V at point b
 deltaI      (.)    Delta-Inclination data structure.
                    .total (1,1)    Total required delta-Inc (rad)
                    .a     (1,1) Delta-Inclination at point a (rad)
                    .b     (1,1) Delta-Inclination at point b (rad)
 tOF         (.)    Time of flight
Reference: Vallado, D. A. (1997.) Fundamentals of Astrodynamics and Applications. pp 281-282.
References and().
Referenced by DVHohInc().
OrbMnvrInclination()
function OrbMnvrInclination (in v, in e, in nu, in deltaI, in mu)
Type OrbMnvrInclination for a demo.
Form
 deltaV = OrbMnvrInclination( v, e, nu, deltaI, mu )
Inputs
 v           (1,1)  Velocity (km/s)
 e           (1,1)  Orbit eccentricity
 nu          (1,1)  True anomaly (rad)
 deltaI      (1,1)  Change in inclination (rad)
 mu          (1,1)  Gravitational parameter (km^3/s^2)
Outputs
 deltaV      (1,1)  Delta-V data structure.
                    .total (1,1)    Total required delta-V (km/s)
Reference: Vallado, D. A. (1997.) Fundamentals of Astrodynamics and Applications. p. 300.
References and(), and OrbMnvrInclination().
Referenced by LTPlaneChange(), and OrbMnvrInclination().
OrbMnvrInsertion()
function OrbMnvrInsertion (in r, in v, in rT, in vT, in rP, in i, in mu, in qCToP)
The maneuver is done instantaneously. The default mu is for the Earth's moon.
Type OrbMnvrInsertion for a lunar insertion demo.
Form
 deltaV = OrbMnvrInsertion( r, v, rT, vT, rP, i, mu, qCToP )
Inputs
 r           (3,1)  Spacecraft position in central body frame
 v           (3,1)  Spacecraft velocity in the central body frame
 rT          (3,1)  Planet position in the central body frame
 vT          (3,1)  Planet velocity in the central body frame
 rP          (1,1)  Perigee altitude (km)
 i           (1,1)  Planet orbit inclination (rad)
 mu          (1,1)  Gravitational parameter (Moon is the default)
 qCToP       (4,1)  Quaternion from central body to planet fixed frame
Outputs
 deltaV      (3,1)  Vector velocity change in the central body frame
References OrbMnvrInsertion().
Referenced by OrbMnvrInsertion().
OrbMnvrLongAndIncl()
function OrbMnvrLongAndIncl (in v, in iI, in iF, in deltaLon, in mu)
Form
 [deltaV, u] = OrbMnvrLongAndIncl( v, iI, iF, deltaLon, mu )
Inputs
 v           (1,1)  Velocity
 iI          (1,1)  Initial orbit inclination (rad)
 iF          (1,1)  Final orbit inclination (rad)
 deltaLon    (1,1)  Change in longitude
 mu          (1,1)  Gravitational parameter
Outputs
 deltaV      (1,1)  Delta-V data structure.
                    .total (1,1)    Total required delta-V
 u           (1,1)  Argument of latitude for the common points
                    .final   (1,1) Final latitude (rad)
                    .initial (1,1) Initial latitude (rad)
Reference: Vallado, D. A. (1997.) Fundamentals of Astrodynamics and Applications. p. 306.
References and().
OrbMnvrLongitude()
function OrbMnvrLongitude (in v, in i, in deltaLon, in mu)
The delta-V will have the same units as the velocity entered, using the formula:
$$ DV = 2 v \sin(a/2) $$
Form
 [deltaV, u] = OrbMnvrLongitude( v, i, deltaLon, mu )
Inputs
 v           (1,1)  Velocity
 i           (1,1)  Orbit inclination (rad)
 deltaLon    (1,:)  Change in longitude (rad)
 mu          (1,1)  Gravitational parameter (optional)
Outputs
 deltaV       (.)  Delta-V data structure.
                    .total (1,1)    Total required delta-V
                    .angle (1,1) Angle (rad)
 u            (.)  Argument of latitude for the common points
                    .final   (1,1) Final latitude (rad)
                    .initial (1,1) Initial latitude (rad)
Reference: Vallado, D. A. (1997.) Fundamentals of Astrodynamics and Applications. p. 304.
References and(), and OrbMnvrLongitude().
Referenced by OrbMnvrLongitude().
OrbMnvrLowerApogee()
function OrbMnvrLowerApogee (in elI, in rAF, in mu)
Generates the time to the maneuver which is done at perigee. It is assumed that the maneuver is an impulse.
Type OrbMnvrLowerApogee for a circularization demo.
Form
 [deltaV, tToM] = OrbMnvrLowerApogee( el0, rAF, mu )
Inputs
 elI         (1,6)  Initial elements [a i W w e M]
 rAF         (1,1)  Final apogee
 mu          (1,1)  Gravitational parameter (Earth is the default)
Outputs
 deltaV      (1,1)  Delta-V
 tOM         (1,1)  Time of maneuver
References Demo(), El2RV(), OrbMnvrLowerApogee(), Period(), Plot3D(), RPRA2AE(), RVOrbGen(), and VOrbit().
Referenced by OrbMnvrLowerApogee().
OrbMnvrOneTangent()
function OrbMnvrOneTangent (in rI, in rF, in nuT, in type, in mu)
 The maneuver starts at E = 0 for the transfer orbit.
 Will perform a demo from LEO to GEO if given less than 4 inputs.
Form
 [deltaV, tOF] = OrbMnvrOneTangent( rI, rF, nuT, type, mu )
Inputs
 rI          (1,1)  Initial radius
 rF          (1,1)  Final radius
 nuT         (1,1)  True anomaly between initial and final burn
 type        (1,1)  Either 'apoapsis' or 'periapsis'
 mu          (1,1)  Gravitational parameter
Outputs
 deltaV      (1,1)  Delta-V data structure.
                    .total (1,1)    Total required delta-V
                    .a     (1,1) Delta-V at point a
                    .b     (1,1) Delta-V at point b
 tOF         (1,1)  Time of flight
Reference: Vallado, D. A. (1997.) Fundamentals of Astrodynamics and Applications. pp 287-292.
References abs(), and and().
OrbMnvrPerigee()
function OrbMnvrPerigee (in d)
 This function has a built-in demo.
Form
 b = OrbMnvrPerigee( d )
Inputs
 d            (:)     Input data structure
                       .a   (1,1)   Semi-major axis
                       .e   (1,1)   Eccentricity of initial orbit
                       .rP  (1,:)   New Perigee
                       .mu  (1,1)   Mu
Outputs
 b             (:)     Output data structure
                       .dV  (1,:)   Datastructure
                       .e   (1,:)   New eccentricity
                       .a   (1,:)   New semi-major axis
                       .vA  (1,:)   Apogee velocity
References abs(), and Plot2D().
OrbMnvrPhaseChange()
function OrbMnvrPhaseChange (in a0, in deltaA, in kTarget, in mu)
The velocity change is tangent to the orbit. The separation angle is positive when the interceptor leads the target. In this case the transfer orbit is larger than the target orbit. When the separation angle is negative and the interceptor trails the target, the transfer orbit is smaller.
Has a built-in demo for low Earth orbit.
Form
 [deltaV,aTrans] = OrbMnvrPhaseChange( a0, deltaA, kTarget, mu )
Inputs
 a0          (1,1)  Initial semi-major axis
 deltaA      (1,1)  Initial separation (rad)
 kTarget     (1,1)  Number of revolutions (1,...)
 mu          (1,1)  Gravitational parameter (km^3/sec^2)
Outputs
 deltaV      (1,1)  Required delta-V (km/s)
 aTrans      (1,1)  Transfer ellipse semi-major axis
 Vallado, D. A., "Fundamentals of Astrodynamics and Applications,"
 McGraw-Hill, 1996, p. 318.
References and(), Demo(), and OrbMnvrPhaseChange().
Referenced by OrbMnvrPhaseChange().
OrbMnvrSemimajor()
function OrbMnvrSemimajor (in v, in a, in deltaA, in mu)
 Will perform a demo for a low earth orbit.
Form
 deltaV = OrbMnvrSemimajor( v, a, deltaA, mu )
Inputs
 v           (1,1)  Velocity
 a           (1,1)  Semimajor axis
 deltaA      (1,1)  Change in semimajor axis
 mu          (1,1)  Gravitational parameter
Outputs
 deltaV      (1,1)  Delta-V data structure.
                    .total (1,1)    Total required delta-V
Reference: Vallado, D. A. (1997.) Fundamentals of Astrodynamics and Applications. p. 300.
References and().
OrbNEl()
function OrbNEl (in varargin)
 Since version 1.
Form
 n = OrbNEl( el )
 -or-
 n = OrbNEl( i, W )
Inputs
One input:
 el              (1,6) Elements vector [a,i,W,w,e,M]
      -or-
 Two inputs:
 inc             (1,:) Inclination (i)     [rad]
 rA              (1,:) Right ascension (W) [rad]
Outputs
 n               (3,:) Orbit normal
References: Bate, R.R., et. al. Fundamentals of Astrodynamics, p 82.
References vector().
Referenced by ECI2OrbitPlane(), EclipticInjectionPlane(), and OrbitalPlane().
OrbNEq()
function OrbNEq (in eq)
 Since version 1.
Form
 n = OrbNEq( eq )
Inputs
 eq                    Elements vector [a,P1,P2,Q1,Q2,l]
Outputs
 n               (3,1) Orbit Normal
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, p. 494.
References and(), Normal(), and vector().
OrbRate()
function OrbRate (in r, in a, in mu)
Form
 w = OrbRate( r, a, mu )
Inputs
 r             (1,1)   Radius
 a             (1,1)   Semi major axis (inf for parabola)
 mu            (1,1)   Gravitational parameter
Outputs
 w             (1,1)   Angular velocity
References: Bates, R.B. Fundamentals of Astrodynamics, pp. 28,34.
References and(), OrbRate(), and Plot2D().
Referenced by AttitudeProfileToTorque(), AutoDualPCSimStruct(), AutoFormGeometry(), AutoFormSimStruct(), CheckDeltaVs(), ClohessyWiltshire(), ClusterGoalsDemoSimStruct(), CollisionDetectSimStruct(), CollisionInit(), CollisionMonitor(), CompareHills(), CWSimAndPlot(), DFFSim(), DFFSimStruct(), DiscreteGVE(), DVGlideslope(), FFEccDeltaElem2Goals(), FFEccDeltaElem2Hills(), FFEccEstimateCost(), FFEccFrameCompare(), FFEccGenerateTeamGoals(), FOrbKF(), GetHillsMats(), GlideslopeCircumnav(), GlideslopeGuidance(), GlideslopePlanner(), GPSSatellite(), ImpulsiveLPManeuver(), InitialOrientation(), LinOrbLQG(), LPCircular(), LPCircularTimeWeight(), LPEccentric(), LPEccentricGVE(), LPEccentricTimeWeight(), Lyapunov(), MainDemoSimStruct(), MeasGPS(), OrbRate(), PackageOrbitDataForPlayback(), PlanetAlignments(), PlaybackOrbitSim(), ProjCirc(), ProjCircSimStruct(), SimpleManeuverSimStruct(), TeamManagementSimStruct(), TestCollisionSimStruct(), TestControlSimStruct(), TestFFEccLinOrb(), TestLPCircular(), TestLPEccentric(), TestLPEccentricGVE(), TestTeamMgtSimStruct(), TransformGeom2Hills(), and ViewRelativeMotion().
OrbTrack()
function OrbTrack (in r, in jD, in gType, in planet, in hFig)
Converts the input inertial positions to planet-fixed using ECIToPlanet. Has a built-in demo showing a Mars orbit in both 3D and 2D.
Form
 OrbTrack( r, jD, gType, planet, hFig )
Inputs
 r                (3,:) ECI position vectors (km) or
                  (1,6) elements
 jD               (:)   Julian dates
 gType            (1,:) '2d' or '3d' Default is '3d'
 planet           (1,:) Any planet in the database
 hFig             (1,:) Figure handle
Outputs
 none
See also
ECIToPlanet, Map, PlotPlanet, JD2Array, RVOrbGen
References abs(), and(), Constant(), ECIToPlanet(), isempty(), JD2000(), JD2Array(), length(), Map(), NewFig(), OrbTrack(), Period(), PlotPlanet(), R2LatLon(), RVOrbGen(), TitleS(), Trajectory(), Watermark(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by OrbTrack().
OrbTrackECI3D()
function OrbTrackECI3D (in r, in planet, in hFig)
The planet picture does not represent any particular time and is there just to show how the orbit relates to the planet. This can be a standalone figure or embedded in another figure. if orbital elements are entered it will plot one orbit.
Has a built-in demo for an inclined Earth orbit.
Form
 OrbTrackECI3D( el, planet )  % creates a new figure
 OrbTrackECI3D( r, planet, hFig )  % plot in figure
Inputs
 r                (3,:) ECI position vectors (km) -or-
                  (1,6) elements [a i w W e M]
 planet           (1,:) Any planet in the database
 hFig             (1,:) Figure handle
Outputs
 none
References and(), Demo(), isempty(), Map(), NewFig(), OrbTrackECI3D(), PlotPlanet(), RVOrbGen(), TitleS(), Trajectory(), Watermark(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by OrbTrackECI3D().
OrbView()
function OrbView (in r, in jD)
Plots a 2D ground track, time histories of position, magnetic field, and either latitude vs. longitude or atmospheric density (for orbits under 8000 km).
Form
 OrbView( r, jD )
Inputs
 r                (3,:) ECI position vectors (km)
 jD               (:)   Julian dates
Outputs
 none
See also
OrbViewDemo, BMF, AtmDens2, R2LatLon
References abs(), and(), AtmDens2(), BMF(), Date2JD(), Demo(), ECIToEF(), JD2T(), length(), Mag(), Map(), NewFig(), OrbView(), R2LatLon(), RVFromKepler(), TitleS(), Watermark(), XLabelS(), YLabelS(), and zeros().
Referenced by OrbView().
OverArea()
function OverArea (in r, in lat, in lon)
lat and lon are the vertices. They should form a simple closed region. The ordering of the vertices must be as shown in the demo.
Type OverArea for a demo.
Form
 [j,rS] = OverArea( r, lat, lon )
Inputs
 r      (3,:)  Point of interest
 lat    (1,:)  Latitude of points in region
 lon (1,:)  Longitude of points in region
Outputs
 j    (1,:)  1 = yes
 rS  (3,:)  Position vectors of region points
References and(), Cross(), Demo(), Dot(), LatLonAltToEF(), length(), LoadEarthMap(), OverArea(), RAzToLatLon(), Unit(), and zeros().
Referenced by OverArea().
PAHohmn()
function PAHohmn (in R1, in R2, in mu)
Form
 [phi1, phi2, Tt] = PAHohmn( R1, R2, mu )
Inputs
 R1                    Orbit radius 1
 R2                    Orbit radius 2 (target)
 mu                    Gravitational parameter
Outputs
 phi1                  phase angle between 1 and 2 at launch
                       + implies 2 leads 1
 phi2                  phase angle between 1 and 2 at intercept
                       + implies 1 leads 2
 Tt                    Transfer time
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 292-294.
References and().
Parameter()
function Parameter (in e, in rP)
Form
 p = Parameter( e, rP )
Inputs
 e                   Eccentricity
 rP                  Perigee radius
Outputs
 p                    Parameter
References: Bate, R. R., Fundamentals of Astrodynamics, Dover, 1971, p. 25.
References Parameter().
Referenced by AddScan(), AircraftCostCalculation(), BlurParameter(), Boeing737(), CameraCalibration(), CreateBody(), CreateComponent(), CRTBP2kms(), EnergyWRTMoon(), GravityGradientEigenvalues(), GravityGradientFromR(), ImpulsiveLPManeuver(), ImpulsiveManeuver(), IterativeImpulsiveManeuver(), J20002RotPuls(), JHAPLSatelliteMass(), Kms2CRTBP(), LandingLegsCAD(), LoadingToLightness(), LowEnergyEarthToMoonTransfer(), MachFromMassFlowParameter(), MassBudgetInput(), MassFlowParameter(), MassFlowParameterR(), MinE4BP(), Parameter(), PointingBudgetGUI(), REl(), REq(), Residual(), RotPuls2J2000(), SafeGuidanceParameters(), TSTOSizing(), VarEqP(), WingedLaunchVehicleDesign(), and WriteBSPFile().
PDrag()
function PDrag (in r, in v, in mu, in R, in rho0, in h0, in hScale, in wP)
Form
 [p, rho] = PDrag( r, v, mu, R, rho0, h0, hScale, wP )
Inputs
 r              (3,:) r in the ECI frame
 v              (3,:) v in the ECI frame
 mu                   Gravitational parameter
 R                    Planet radius
 rho0                 Base density
 h0                   Base altitude for rho0
 hScale               Atmospheric scale height
 wP                   Planetary rotation rate (rad/sec)
Outputs
 p                    Pressure
 rho                  Atmospheric Density
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 83-86. Escobal, P.R., Methods of Orbit Determination, 1976, p. 60.
References Altitude(), Cross(), length(), Mag(), Plot2D(), Pressure(), and zeros().
Period()
function Period (in a, in mu)
You specify the semi-major axis. The default central body is the Earth.
Type Period for a demo
Form
 p = Period( a, mu )
Inputs
 a   (1,:) Semi-major axis (inf for a parabola and negative for a hyperbola)
 mu (1,1) Gravitational parameter (default = Earth)
Outputs
 p   (1,:) Period (s)
References and(), Demo(), isempty(), Period(), and Plot2D().
Referenced by ACModes(), AdjustMeanAnomaly(), AutoFormGeometry(), BDipole(), BDipoleCoeff(), CheckDeltaVs(), CircularManeuver(), ClockConversion(), CollisionMonitor(), ConstellationGroundContact(), ConstellationMaxDistance(), CubeSatDisturbanceAnalysis(), DemoManeuverSimStruct(), DiscreteGVE(), DistAero(), DistAlbedo(), DistRadiation(), DistributedAlbedo(), DistSolar(), DrawOrbitPlane(), DrawSpacecraftInOrbit(), DVGlideslope(), DVOrbitDrag(), EarthAlb(), EarthEclipseDuration(), EccentricTetrahedronSimStruct(), FFEccFrameCompare(), GenerateSwath(), Geo(), GeoSwitchingMission(), GlideslopeCircumnav(), GlideslopeGuidance(), GlideslopePlanner(), GravityGradientFrequency(), GroundTrack(), HohmannTransferRendezvous(), HSAPlot(), ImpulsiveLPManeuver(), J2Prop(), LinkAnalysisTool(), LinkOrbitAnalysis(), LowEnergyEarthToMoonTransfer(), LPvsCF(), LQOrbitController(), LunarTargeting(), LunarTrajectoryControl(), ManeuverEnvelope(), NKPlanetPeriod(), NonDimensionalOrbit(), NonKeplerianPlanet(), OrbitClosestPoint(), OrbitFromSynodic(), OrbitLoweringManeuvers(), OrbitProp(), OrbMnvrHohmann(), OrbMnvrLowerApogee(), OrbTrack(), Osc2Mean(), PackageOrbitDataForPlayback(), PatchedConicPlanner(), Period(), PeriodToSemimajorAxis(), PlanetAlignments(), PlanetOpposition(), PlanetYear(), PlaybackOrbitSim(), PlotOrbitTransfer(), PowerDesign(), PtchCnc(), PToSMA(), QSunNadir(), RotateOrbit(), RVSet2El(), RVWithJ2(), SemimajorAxisRevisit(), StoppingConditions(), SynodicFromSemimajorAxes(), TestLPCircular(), TestLPEccentric(), TestLPEccentricGVE(), THohmn(), TransferOrbit(), TriangularManeuver(), TwoDEscape(), UDipole(), WheelSpeed(), and WindModel().
PeriodToSMA()
function PeriodToSMA (in T, in mu)
Form
 a = PeriodToSMA( T, mu )
Inputs
 T             (1,1)    Orbit period (sec)
 mu            (1,1)    Gravitational constant (km^3/sec^2)
                        Optional. Earth gravitational constant used if
                        not provided.
Outputs
 a             (1,1)    Semi major axis (km)
PlanetaryAccelerations()
function PlanetaryAccelerations (in r, in jD, in center)
Includes the ephemeris of the bodies. Currently only a center at the Earth or the Moon is supported with Earth, Moon, and sun perturbations. Has a demo for GEO orbit around the Earth.
Form
 a = PlanetaryAccelerations( r, jD, center )
Inputs
 r               (3,1) Position vector wrt center
 jD              (1,1) Julian Date
 center          (1,:) Center, 'earth' or 'moon'
Outputs
 a               (3,1) Acceleration
See also
SunV1, MoonV1, and APlanet.
References and(), APlanet(), Constant(), Date2JD(), isempty(), MoonV1(), SunV1(), and vector().
Referenced by FOrbitMultiSpacecraft(), and FOrbKF().
Plot2DTrajectory()
function Plot2DTrajectory (in lambda, in d, in units, in plotTitle)
The cost function returns the state and time.
Form
 [xF, xFErr, tF] = Plot2DTrajectory( lambda, d, units, plotTitle  )
Inputs
 lambda         (3,1)  Costates
 d               (.)   Structure to pass to fun
                       .costFun @
                       .orbRate (if nondimensional)
                       .aU
                       .mu
                       .rF, optional
                       .xF
 units          (1,:)  Units for position
 plotTitle      (1,:)  Title for the plot
Outputs
 xF             (:,1)  Achieved State
 xFErr          (:,1)  State Error
 tF             (1,1)  Time of achieved state
References abs(), and(), Constant(), length(), Plot2D(), RV2El(), set(), TimeLabl(), Trajectory(), and zeros().
Referenced by CostLowThrust2D(), and CostSail2D().
PlotLambertTransfer()
function PlotLambertTransfer (in r1, in v1, in r2, in v2, in dT, in dV, in elT, in mu)
Plot the initial and final trajectories and the transfer trajectory. Labels the plot with the total delta-V.
Form
 PlotLambertTransfer(r1,v1,r2,v2,dT,dV,elT,mu)
Inputs
 r1              (3,1)  Position of spacecraft 1 (km)
 v1              (3,1)  Velocity of spacecraft 1 (km/s)
 r2              (3,1)  Position of spacecraft 2
 v2              (3,1)  Velocity of spacecraft 2
 dT              (1)    Transfer time (s)
 dV              (:)     Struct of delta-Vs
                 .total  (1,1) Total delta-V
 elT             (1,6)    Transfer elements
 mu              (1)    Gravitional parameter, default is Earth
Outputs
 None.
References and(), Constant(), DVTarget(), Plot3D(), RV2El(), RVFromKepler(), RVOrbGen(), and square().
Referenced by DVTarget(), and PorkChopTOFKepler().
PlotOrbitPage()
function PlotOrbitPage (in r, in t, in figTitle)
 If t is entered, the upper left will show the 3D and the remaining plots
 will show each axis against time.
 If t is empty, the 2D plots will show x/y, y/z, and x/z views.
 The built-in demo creates one of each type of plot.
 Forms:
 h = PlotOrbitPage( r )
 h = PlotOrbitPage( r, t, figTitle )
 h = PlotOrbitPage( r, [], figTitle )
Inputs
 r          (3,:)    x, y, z values
 t          (n,:)    Time vector, optional
 figTitle            Figure title
Outputs
 h          (1,1)    Figure handle
 hA         (:)      Data structure of handles to line objects
                     .h
References and(), Demo(), isempty(), NewFig(), Plot2D(), PlotOrbitPage(), set(), vector(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by PlotOrbitPage().
PlotOrbitTransfer()
function PlotOrbitTransfer (in el1, in el2, in elT, in mu, in jdDep, in jdArr, in trans_dir)
The default planet is the Earth. Figure has a black background.
Form
 PlotOrbitTransfer( el1, el2, elT );
 PlotOrbitTransfer( el1, el2, elT, mu );
 PlotOrbitTransfer( el1, el2, elT, mu, jdDep, jdArr, trans_dir)
Inputs
 e11       (1,6)   Orbital elements of first orbit [a,i,W,w,e,M]
 e12       (1,6)   Orbital elements of final orbit
 e1T       (1,6)   Orbital elements of transfer orbit
 mu        (1,1)   Gravitational parameter [km^3/sec^2]
 jdDep     (1)     Julian date of departure
 jdArr     (1)     Julian date of arrival
 trans_dir (1)     transfer type - 1 direct, -1 retrograde
Outputs
 None
References and(), Constant(), NewFig(), Period(), PlotOrbitTransfer(), RVFromKepler(), set(), and Watermark().
Referenced by PlotOrbitTransfer().
PlotPlanetaryOrbit()
function PlotPlanetaryOrbit (in r, in p, in t, in jD0)
Note that the location relative to the map is only accurate for Planet-fixed frame input. Enter time and Julian date to compute the Planet-fixed positions from ECI data automatically. Can enter multiple satellites using a cell array. The start point is a green dot, the end is a red dot.
Type PlotPlanetaryOrbit for a demo of 2 satellites around Venus. This is similar to PlotPlanetOrbit but does not create time labels along the trajectory.
Form
 h = PlotPlanetaryOrbit( rPF, p )
 h = PlotPlanetaryOrbit( rECI, p, t, jD0 )
Inputs
 r         (3,m)  Position vectors (km)
        or
            {n}   Cell array of position matrices for multiple satellites
 p         (1,:)  Planet name, default Earth
 t         (1,:)  Time array (sec)
 jD0       (1,1)  Epoch Julian date
Outputs
 h         (1,1)  Figure handle
 l         (1,n)  Handle to orbit lines
See also
: PlotOrbit, ECIToPlanet
References and(), PlotPlanetaryOrbit(), and PlotPlanetOrbit().
Referenced by LunarTrajectoryControl(), and PlotPlanetaryOrbit().
PlotZermelo()
function PlotZermelo (in lambda, in d, in ignoredArg, in plotTitle)
Form
 [xF, xFErr] = PlotZermelo( lambda, d, units, plotTitle  )
Inputs
 lambda         (2,1)  Costates
 d              (1,1)  Structure to pass to fun
 units          (1,:)  Units for position
 plotTitle      (1,:)  Plot title
Outputs
 xF             (:,1)  Achieved State
 xFErr          (:,1)  State Error
References abs(), and(), length(), Plot2D(), set(), TimeLabl(), and Trajectory().
ProcessASCIIGravityModel()
function ProcessASCIIGravityModel (in fileName)
The coefficients are unnormalized. A preprocessed version of jgl075g1.sha is available in LunarGravityModel.mat.
Form
 gravityModel = ProcessASCIIGravityModel( fileName )
Inputs
 fileName        (1,:) fileName
Outputs
 gravityModel    (.)   Data structure
                       .name (1,:) Model name
                       .mu   (1,1) Gravitational constant (km^3/sec^2)
                       .a    (1,1) Model earth radius (km)
                       .c    (n,n) Cosine coefficients
                       .s    (n,n) Sine coefficients
                       .j    (1,n) Zonal harmonics
                       .nZ   (1,1) Number of Zonal harmonics
                       .nT   (1,n) Number of Tesseral harmonics
                       .isNormalized (1,1)  Boolean
References Demo().
PropagateLowThrust()
function PropagateLowThrust (in x0, in d)
Assumes that the thrust is constant and tangential to the orbit. The mass flow is modeled as Thrust = mDot*uE.
Form
 PropagateLowThrust( x0, d )
Inputs
 x0          (1,:)  Initial state
 d           (1,1)  .stoppingCondition (1,:) 'time',
                                             'approaching distance',
                                             'receding distance'
                                             'increasing velocity',
                                             'decreasing velocity',
                                              'escape'
                    .stoppingValue     (1,1) value
                    .thrust            (1,1) Thrust
                    .mu                (1,1) gravitational parameter
                    .uE                (1,1) Exhaust velocity
                    .mass              (1,1) Initial mass
                    .absTol            (1,1) Absolute tolerance
                    .relTol            (1,1) Relative tolerance
                    .t                 (1,:) Time steps
Outputs
 x           (1,1)  The tag if action is 'initialize'
References and(), close(), Date2JD(), Demo(), FOrbLowThrust(), get(), Initialize(), isempty(), length(), Planets(), Plot2D(), TimeGUI(), and zeros().
PropagateOrbitPlugIn()
function PropagateOrbitPlugIn (in action, in modifier, in hFig, in position, in callback)
Form
 x = PropagateOrbitPlugIn( action, modifier, hFig, position, callback )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifier    (1,:)  Modifier to the action or data structure if intialization
 hFig        (1,1)  Handle to the figure or if 'update' radio button handles
 position    (1,4)  [left bottom width height]
 callback    (1,:)  Callback string when something has changed in this gui
Outputs
 x           (1,1)  The tag if action is 'initialize'
References and(), close(), CloseFigure(), get(), GetH(), HelpSystem(), Initialize(), OpenFile(), and set().
Referenced by FAero(), FAtmDensity(), FEngine(), FPlantNoise(), and FSolar().
PropagateTLE()
function PropagateTLE (in tVec, in file, in model)
SGP, SGP4, SGP8.
SGP4 output is in the TEME frame - true equator, mean equinox. file can be a file name or a string input. The string must have the same format as the file for example:
 s = [sprintf('SGPTest \n'),...
 sprintf('1 88888U          80275.98708465  .00073094  13844-3  66816-4 0     8\n'),...
 sprintf('2 88888  72.8435 115.9689 0086731  52.6988  110.5714 16.05824518  105')];
Form
 [r,v,x] = PropagateTLE( tVec, file, model )
 [r,v,x] = PropagateTLE( tVec, x, model )
Inputs
 tVec          (1,:)   Time vector (sec)
 file          (1,:)   File name OR converted data structure
 model         (1,:)   Model type 'SGP', 'SGP4', 'SDP4', 'SGP8', 'SGD8'
                         The default model is SGP4.
Outputs
 r      (3,:) or {:}   Position vectors, TEME frame
 v      (3,:) or {:}   Velocity vectors
 x             (:)     Structure of NORAD element data
See also
NORAD, LoadNORAD, ConvertNORAD.
References: Hoots, F. R. and R. L. Roehrich, "Spacetrack Report No. 3: Models for Propagation of NORAD Element Sets", Dec. 1980.
References NORAD(), and vector().
Referenced by NORAD(), and PropagateTLECommonTime().
PropagateTLECommonTime()
function PropagateTLECommonTime (in jD0, in tVec, in file, in model)
For each each TLE set, Propagate TLE is called with the appropriate "tVec" input so that the starting epoch of all trajectories is "jD0".
If "jD0" is empty, the latest Julian date of the given TLEs is used.
See also
NORAD, LoadNORAD, ConvertNORAD, PropagateTLE
Form
 [r,v,x] = PropagateTLECommonTime( jD, tVec, file, model )
 [r,v,x] = PropagateTLECommonTime( jD, tVec, x, model )
Inputs
 jD0           (1,1)   Epoch Julian date for all TLEs
 tVec          (1,:)   Time vector (sec). Referenced to jD0.
 file          (1,:)   File name OR converted data structure
 model         (1,:)   Model type 'SGP', 'SGP4', 'SDP4', 'SGP8', 'SGD8'
                         The default model is SGP4.
Outputs
 r      (3,:) or {:}   Position vectors, TEME frame
 v      (3,:) or {:}   Velocity vectors
 x             (:)     Structure of NORAD element data
References: Hoots, F. R. and R. L. Roehrich, "Spacetrack Report No. 3: Models for Propagation of NORAD Element Sets", Dec. 1980.
References ConvertNORAD(), LoadNORAD(), NORAD(), PropagateTLE(), set(), and vector().
Referenced by DrawSpacecraftInOrbit(), and SeeTLE().
PropEph()
function PropEph (in elStart, in jd, in dT, in mu)
 Since version 1.
Form
 [el, jd, uSun, uMoon, uNadir, radiusEarth] = PropEph( elStart, jd, dT, mu )
Inputs
 elStart      (1,6)     Initial Keplerian orbital elements [a,i,W,w,e,M] (angles in rad)
 jd                     Julian date (days)
 dT           (:)       Time step (sec)
 mu                     Gravitational parameter for the earth
Outputs
 el           (6,:)     Keplerian orbital elements
 jd                     Julian date (days)
 uSun         (3,:)     Sun unit vector
 uMoon        (3,:)     Moon unit vector
 uNadir       (3,:)     Earth unit vector
 radiusEarth  (:)       Earth angular radius (rad)
References DupVect(), El2RV(), length(), Mag(), MoonV2(), Nadir(), Plot2D(), SunV1(), Unit(), vector(), and zeros().
PtchCnc()
function PtchCnc (in vC, in vPC, in rC, in rPC, in muC, in muP)
 vC and rC must be inside the patch condition, i.e. when the spacecraft
 orbit intersects the sphere of influence. At that point the target
 planet or moon is the central body and orbital elements with respect
 to that body are computed. If you do the conversion too far inside
 the sphere of influence your results will not be correct.
 vC, vPC, rC and rPC can be 3x1 or 3xn. In the latter case it finds
 the crossing point for the sphere of influence.
 If no outputs are specified, it will plot the planet centered orbit.
 Velocity, mu and position must be in consistent units. This function
 shows the effect of flying by another body but does not directly
 help in designing a trajectory.
 Type PtchCnc for a demo of a spaceraft approaching the moon in an
 Earth-centered elliptical orbit.
 Since version 2.
Form
 el = PtchCnc( vC, vPC, rC, rPC, muC, muP )
Inputs
 vC (3,1)   Velocity of the spacecraft in the central frame
 vPC    (3,1)   Velocity of the planet in the central frame
 rC (3,1)   Position of the spacecraft in the central frame
 rPC    (3,1)   Position of the planet in the central frame
 muC    (1,1)   Gravitational parameter of the central body
 muP    (1,1)   Gravitational parameter of the planet
Outputs
 el (:)     Elements in the planet frame
             el.a, el.e, el.i, el.w, el.L, el.M
References abs(), and(), Constant(), Demo(), DispWithTitle(), isempty(), Mag(), Period(), PtchCnc(), RPRA2AE(), RV2El(), RVOrbGen(), and SphOI().
Referenced by PtchCnc().
PToSMA()
function PToSMA (in p, in mu, in type)
 The default central body is the Earth.
Form
 a = PToSMA( p, mu, type )
Inputs
 p            (1,1) or (6,1)  Period or mean motion
 mu           (1,1)           Gravitational parameter (default = 3.98600436e5)
 type         (1,1)           Specify type of units. Either
                                 (1)   Period in seconds
                                 (2)   Rate in revolutions per day
                                 (3)   Rate in rad/sec
Outputs
 p            (1,1)           Period
References isempty(), and Period().
RAEToM()
function RAEToM (in r, in a, in e)
 Type RAEToM for a demo
Form
 [m, nu, E] = RAEToM( r, a, e )
Inputs
 r          (1,1) Orbit radius
 a          (1,1) Orbit semi-major axis
 e          (1,1) Orbit eccentricity
Outputs
 m          (1,1) Mean anomaly (rad)
 nu         (1,1) True anomaly (rad)
 E          (1,1) Eccentrci anomaly (rad);
References abs(), and(), Demo(), Nu2M(), and RAEToM().
Referenced by RAEToM().
RandomOrbit()
function RandomOrbit (in el, in el1S, in t, in mu, in n)
 Type RandomOrbit for a demo with 2008 AE9
 Since version 11.
Form
 [r1S, v1S, rN, vN] = RandomOrbit( el, el1S, t, mu, n )
Inputs
 elI     (1,6) Elements vector [a,i,W,w,e,M]
 el1S    (1,6) Gaussian noise vector [a,i,W,w,e,M]
 t       (1,1) Times from 0 to  (sec)
 mu      (1,1) Gravitational parameter
Outputs
 r1S     (3,1)  Mean position 1 sigma (km)
 v1S     (3,1)  Mean velocity 1 sigma (km)
 rN      (3,1)  Nominal position (km)
 vN      (3,1)  Nominal velocity (km)
References Constant(), Demo(), isempty(), Mag(), RandomOrbit(), RVOrbGen(), and vector().
Referenced by RandomOrbit().
RARP2A()
function RARP2A (in rA, in rP)
Form
 a = RARP2A( rA, rP )
Inputs
 rA             (1,m)  Apogee radius
 rP             (1,n)  Perigee radius
Outputs
 a              (m,n)  Semi major Axis
References and().
RARP2E()
function RARP2E (in rA, in rP)
 Since version 1.
Form
 e = RARP2E( rA, rP )
Inputs
 rA             (1,m)  Apogee radius
 rP             (1,n)  Perigee radius
Outputs
 e              (m,n)  eccentricity
References and().
RAzToLatLon()
function RAzToLatLon (in r, in az, in lat0, in lon0, in R)
 Range is measured along the sphere. Azimuth is from north toward East.
 The latitude and longitude returned are geocentric.
Form
Inputs
 r              (1,:)      Range along sphere
 az             (1,:)      Azimuth angle
 lat0           (1,1)      Initial latitude
 lon0           (1,1)      Initial longitude
 R              (1,1)      Radius of sphere (default is Earth)
Outputs
 lat            (1,:)      Latitude on sphere
 lon            (1,:)      Longitude on sphere
References and(), length(), NewFig(), RAzToLatLon(), and set().
Referenced by LatLonToRangeAzimuth(), LatLonToRAz(), OverArea(), RAzToLatLon(), and RHAzToECEF().
ReadHorizons()
function ReadHorizons (in file)
 http://ssd.jpl.nasa.gov/horizons.cgi#top
The format should look like
 Ephemeris Type [change] :  VECTORS
 Target Body [change] :     Earth [Geocenter] [399]
 Coordinate Origin [change] :   Sun (body center) [500@10]
 Time Span [change] :   Start=2010-09-03, Stop=2012-10-03, Step=1 d
 Table Settings [change] :  defaults
 Display/Output [change] :  download/save (plain text file)%   Save the data to a text file. Call without the file input to get a
 dialog box.
Units should be au and au/day.
For a demo type
 ReadHorizons('Messenger.txt')
Form
 [r, v, jD, lT, rG, rR] = ReadHorizons( file )
Inputs
 file              (1,:)  File name
Outputs
 r                 (3,:)  Position vector (AU)
 v                 (3,:)  Velocity vector (AU/day)
 jD                (1,:)  Julian date (day)
 lT                (1,:)  Light time (day)
 rG                (1,:)  Range (AU)
 rR                (1,:)  Range Rate (AU/day)
References and(), Constant(), get(), Plot3D(), Step(), vector(), and zeros().
ReadTopexPOE()
function ReadTopexPOE (in fileName, in m)
Form
 d = ReadTopexPOE( fileName )
Inputs
 fileName        (1,:) Filename
 m               (1,1) Save every  mth record
Outputs
 d               (1,1) Topex Data Structure
                       .uTC(:)          .year
                                        .month
                                        .day
                                        .hour
                                        .min
                                        .sec
                        .sidereal     (1,:)   Greenwich hour angle satellite epoch (deg).
                        .polarMotion  (2,:)   Polar Motion(milli arc-seconds)
                        .epochTime    (1,:)   Ephemeris time (days from Jan 0.0)
                        .xECI         (6,:)   (km)
                        .xEF          (6,:)   (km)
References and(), close(), flength(), isempty(), Plot2D(), WaitBarManager(), and zeros().
REl()
function REl (in el)
 Since version 1.
Form
 [r, p] = REl( el )
Inputs
 el                  Elements vector [a,i,W,w,e,M] where a is perigee
                     radius for a parabola
Outputs
 r                    Radius
 p                   Parameter
References and(), Parameter(), and vector().
RelativeCoord()
function RelativeCoord (in r, in v, in r2, in v2)
 Find relative coordinates between an orbit defined by r and v
 and orbit with position vector r2. This coordinate system uses Kaplan's
 convention and is consistent with LinOrb.
Form
 d = RelativeCoord( r, v, r2, v2 )
Inputs
 r               (3,:) Position vector
 v               (3,:) Velocity vector
 r2              (3,:) Second orbit position
 v2              (3,:) Second orbit velocity
Outputs
 d               (3,:) Relative position [dr;rtheta;z]
                 (6,:) And velocity if v2 is entered
References: Kaplan, M. H., Modern Spacecraft Dynamics and Control J. Wiley, 1986, pp. 109-111.
References and(), and vector().
RelativeOrbitState()
function RelativeOrbitState (in x1, in x2)
This function is consistent with Hill's equations.
Form
 [d, y, z] = RelativeOrbitState( x1, x2 )
Inputs
 x1              (6,1) [r;v]
 x2              (6,1) [r;v]
Outputs
 d               (6,1) [dR;r1*dTheta;dZ;dRDot;r1*dThetaDot;dZDot]
 y               (3,1) Tangent vector
 z               (3,1) Orbit normal vector
References and(), and vector().
RelState2Absolute()
function RelState2Absolute (in x0, in xRel)
Consistent with Hills equations.
Form
 x1 = RelState2Absolute( x0, xRel )
Inputs
 x0  (6,1) [r;v] ECI frame
 xH  (6,n) [r;v] Hills frame
Outputs
 x1  (6,n) [r;v] ECI frame
Reference: Kaplan, M., Modern Spacecraft Dynamics and Control, p. 111. Valado, D., Fundamentals of Astrodynamics and Applications, Orbital Maneuvering, Relative Motion.
References and(), and RHS().
RendezvousPlanner()
function RendezvousPlanner (in rT, in vT, in rC, in vC, in dT, in planet, in mu, in tol)
The inputs are the initial target position and velocity vector, the initial chase vehicle position and velocity vector, the time allowed for the rendezvous, the gravitational parameter and the tolerance for the Lambert problem solver. It computes both direct and retrograde trajectories.
Form
 [dV1D, dV2D, dV1R, dV2R] = RendezvousPlanner( rT, vT, rC, vC, dT, planet, mu, tol )
Inputs
 rT            (3,1)   Target orbit position
 vT            (3,1)   Target orbit velocity
 rC            (3,1)   Chase vehicle orbit position
 vC            (3,1)   Chase vehicle orbit velocity
 dT            (1,1)   Time between position 2 and 1
 planet        (1,1)   Name of planet
 mu            (1,1)   Gravitational parameter
 tol           (1,1)   Tolerance
Outputs
 dV1D          (3,1)    Initial delta-V direct transfer
 dV2D          (3,1)    Final delta-V direct transfer
 dV1R          (3,1)    Initial delta-V retrograde transfer
 dV2R          (3,1)    Final delta-V retrograde transfer
See also
LambertTOF
References and(), El2RV(), LambertTOF(), Mag(), Map(), NewFig(), RV2El(), RVOrbGen(), and vector().
REq()
function REq (in eq)
 Since version 1.
Form
 [r, p] = REq( eq )
Inputs
 eq               Elements vector [a,P1,P2,Q1,Q2,L]
Outputs
 r                 Radius
 p                Parameter
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, pp. 484-490.
References and(), Parameter(), and vector().
RHAzToECEF()
function RHAzToECEF (in r, in h, in az, in latLon0, in R, in plt)
 Since version 8.
Form
 [rEFx,rEFy,rEFz,lat,lon] = RHAzToECEF( r, h, az, latLon0, R )
Inputs
 r              (1,:)      Range along sphere (km)
 h              (1,:)      Altitude above sphere (km)
 az             (1,:)      Azimuth angle (rad)
 latLon0        (2,1)      Reference latitude and longitude (rad)
 R              (1,1)      Sphere radius (default Earth: 6378.14 km)
 plt            (1,1)      Plot flag. Set to 1 to create plot. Default 0
Outputs
 rEFx           (1,:)      x component of Earth-fixed coordinates
 rEFx           (1,:)      y component of Earth-fixed coordinates
 rEFx           (1,:)      z component of Earth-fixed coordinates
 lat            (1,:)      Latitude on sphere
 lon            (1,:)      Longitude on sphere
References Altitude(), and(), length(), LLAToECEF(), Map(), RAzToLatLon(), set(), and zeros().
RHS2DPolarOrbit()
function RHS2DPolarOrbit (in x, in ignoredArg, in d)
The tangential and radial components of acceleration are throttled independently. Default data structure is for Pluto. u is the radial direction and v is the tangent direction.
Form
 xDot = RHS2DPolarOrbit( x, t, d )
Inputs
 x     (4,1) [r;u;v;theta] [km;km/s;km/s;rad/s]
 t     (1,1) Time (s) (unused)
 d     (.)   Data structure describing spacecraft model
            .a    (2,1) Throttle -1 to 1 in [u;v]
             .mu   (1,1) Gravitational parameter (km^3/s^2)
             .aMax (1,1) Maximum acceleration (km/s^2)
Outputs
 xDot  (4,1) [rDot;uDot;vDot;thetaDot] [km;km/s;km/s;rad/s]/s
Reference: Bryson, A, and Ho Yu-Chi, "Applied Optimal Control", Hemisphere, p 67.
References and(), RHS(), and Throttle().
Referenced by Simulate2DApproach().
RHSEquinoctial()
function RHSEquinoctial (in ignoredArg, in x, in d)
Form
 d = RHSEquinoctial
 xDot = RHSEquinoctial( t, x, d )
Inputs
 t          (1,1)  Time
 x          (6,1)  States [p;f;g;h;k;L]
 d           (.)   Structure to pass to the integration RHS
                   .mu  (1,1)
                   .f   (3,1) Acceleration vector
Outputs
 xDot       (6,1)   State derivatives d[p;f;g;h;k;L]/dt
 a          (6,6)   a matrix
References and(), Constant(), RHS(), RHSEquinoctial(), and vector().
Referenced by EqPartials(), LambdaToConeClock3D(), RHS3DOrbit(), RHSEquinoctial(), and RHSOpt3DOrbit().
RHSGeoHarm()
function RHSGeoHarm (in x, in t, in d)
Allows for any spherical harmonic model to be passed in as a data structure. Uses the highest fidelity Earth ephemeris function.
Form
 xDot = RHSGeoHarm( x, t, d )
Inputs
 x           (6,1)    Position vector [rECI (km); vECI (km)];
 t           (1,1)    Time since start Julian Date (s)
 d            (.)     Gravity model data structure
                      .nN    (1,1)  Highest zonal harmonic (m = 0)
                      .nM    (1,1)  Highest sectorial and tesseral harmonic
                      .s     (:,:)  S terms
                      .c     (:,:)  C terms
                      .j     (1,:)  m = 0 terms
                      .mu    (1,1)  Spherical gravitational potential
                      .a     (1,1)  Planet radius
                      .jD0    (1,1) Start Julian Date
                      .isNormalized (1) Coefficient are normalized, or not
Outputs
 xDot        (6,1)   [rDot;vDot]
See also
: TruEarth, AGravityC
References AGravityC(), and(), JD2000(), JD2T(), LoadGEM(), RHSGeoHarm(), TruEarth(), and vector().
Referenced by FOrbCartH(), RHSGeoHarm(), and RHSGeoJ2().
RHSGeoJ2()
function RHSGeoJ2 (in x, in t, in d, in aExt)
Uses a local version of AGravityC that explicitly uses only the J2 term.
Form
 d = RHSGeoJ2; % default data
 xDot = RHSGeoJ2( x, t, d, aExt )
Inputs
 x           (6,1)    Position vector [rECI (km); vECI (km)];
 t           (1,1)    Time since start Julian Date (s)
 d            (.)     Gravity model struct
                       .j2    (1,2) J2 term (unnormalized and positive)
                       .mu    (1,1) Spherical gravitational potential
                       .a     (1,1) Planet radius
                       .jD0   (1,1) Start Julian Date
aExt          (3,1)   External acceleration vector [x;y;z] ECI
Outputs
 xDot        (6,1)   [rDot;vDot]
See also
: ECIToEF, RHSGeoHarm
References AGravityC(), and(), DefaultData(), ECIToEF(), JD2T(), RHSGeoHarm(), RHSGeoJ2(), vector(), and zeros().
Referenced by RHSGeoJ2(), and RVWithJ2().
RHSLinOrb()
function RHSLinOrb (in x, in ignoredArg, in n, in u)
x and y are in the orbit plane. x is radial. z is out of plane.
Form
 [xDot,A,B] = RHSLinOrb( x, ~, n, u)
Inputs
 x     (6,1) [x;y;z;vX;vY;vZ] [dr;rtheta;z;ddr/dt;drtheta/dt;dz/dt]
 t     (1,1) Time (unused)
 n     (1,1) Orbital Rate (rad/s)
 u     (3,1) Control acceleration
Outputs
 xDot  (6,1) d[x;y;z;vX;vY;vZ]/dt
 A     (6,6) State matrix
 B     (6,3) Input matrix
References and(), and LinOrb().
RHSOrbit()
function RHSOrbit (in x, in ignoredArg, in d)
External disturbances may be passed in via the data structure.
Form
 d = RHSOrbit; % data structure
 xDot = RHSOrbit( x, t, d )
Inputs
 x   (6,1) Orbital state [r;v] in km and km/s
 t   (1,1) Time (unused)
 d    (.)   Data structure
            .mu     (1,1) Gravitational constant
            .a      (3,1)   Acceleration (km/s2)
            .states {6}   State names
            .x0     (6,1) Initial state
Outputs
 xDot (6,1) d[r;v]/dt
References and(), and RHSOrbit().
Referenced by NonDimensionalOrbit(), RHSOrbit(), and TrajectoryBetweenTwoPlanets().
RHSOrbit2D()
function RHSOrbit2D (in x, in t, in d)
Form
 xDot = RHSOrbit2D( x, t, d )
Inputs
 x          (4,1)   [r;v]
 t          (1,1)   Time (unused)
 d          (1,1)   Data structure
                    .mu (1,1) Gravitational potential
                    .a  (2,1) External acceleration
Outputs
 xDot       (4,1)   d[r;v]/dt
References Mag().
RHSOrbitPlanetFixed()
function RHSOrbitPlanetFixed (in x, in t, in d)
The gravity function returns the gravitational accelerations in the planet fixed frame. It must be of the form
 a = GravFun( r, gFunData )
where a is in the planet fixed frame. d.mu is not used in this case.
The optional rotation matrix function must be of the form
 [bECIToEF, omega] = bFun( jD, bFunData )
bECIToEF is 3x3 and omega is 3x1. Omega is the planet angular rate vector in the ECI frame.
If bFun is not used, the rotation is around the ECI z axis.
The default data structure is for the the Earth on March 22, 2016 at 11:58:19.
Form
 xDot = RHSOrbitPlanetFixed( x, t, d )
Inputs
 x     (6,1)   State [r;v]
 d      (.)    Data structure
               .mu       (1,1) Gravitational constant
               .gFun     (2,1) Pointer to the gravity function
               .gFunData     (.)  Gravity function data
               .omega    (1,1) Planet rotation rate
               .aECI     (1,1) Non-gravitational acceleration in the ECI frame
               .theta0   (1,1) Initial planet to ECI angle
               .jD0      (1,1) Initial Julian Date
               .bFun     (1,1) Pointer to the rotation matrix function
               .bFunData     (.)  Rotation matrix function data
Outputs
 xDot   (6,1)   State derivative [r;v]
References and(), Constant(), Date2JD(), isempty(), Mag(), Skew(), and vector().
Referenced by RHSRVPlanetFixed().
RHSZermelo()
function RHSZermelo (in t, in x, in d)
Models a constant velocity field. Test function for TrajectoryOptimization.
Form
 vargout = RHSZermelo( t, x, d )
Inputs
 t              (1,1) Time
 x              (4,1) State [x;y;lambdaX;lambdaY]
 d              (1,1) Data structure
                      .h (1,1) Characteristic dimension
                      .v (1,1) Velocity
Outputs
 xDot           (4,1) State derivative
Reference: Bryson, Ho, "Applied Optimal Control", Hemisphere Publishing, 1975.
Referenced by ZermeloCost().
RLagrange()
function RLagrange (in rS, in mR, in lPoint)
Default is for the earth/moon system.
Form
 rL = RLagrange( rS, mR, lPoint )
Inputs
 rS          (3,1)  R of the secondary
 mR          (1,1)  Mass secondary/mass primary
 lPoint      (1,1)  Desired Lagrange point
Outputs
 rL          (3,1)  Lagrange coordinates
References Constant(), Date2JD(), Demo(), FLagrange(), isempty(), IsVersionAfter(), and MoonV1().
ROrb()
function ROrb (in e, in rp, in f)
Type ROrb for a demo
Form
 r = ROrb( e, rp, f )
Inputs
 e   (1,1) Eccentricity
 rp (1,1) Perigee radius
 f   (1,:) True anomaly
Outputs
 r   (1,:) Radius
References: Bate, R. R., Fundamentals of Astrodynamics. pp. 20-40.
References length(), Plot2D(), and ROrb().
Referenced by ROrb(), and RPQ().
RPQ()
function RPQ (in e, in rP, in nu)
 Since version 1.
Form
 r = RPQ( e, rP, nu )
Inputs
 e                     Eccentricity
 rP                    Perigee radius
 nu                    True anomaly (rad)
Outputs
 r                     [xP;xQ;0]
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, p. 63.
References abs(), Coordinates(), length(), Plot2D(), ROrb(), vector(), and zeros().
RPRA2AE()
function RPRA2AE (in rP, in rA)
Form
 [a, e] = RPRA2AE( rP, rA )
Inputs
 rP              (1,:) Perigee
 rA              (1,1) Apogee
Outputs
 a               (1,:) Semi-major axis
 e               (1,:) Eccentricity
References: Bate, R.R., et. al. Fundamentals of Astrodynamics, pp. 70-71.
References and().
Referenced by AE2VR(), CoplanarOrbit(), EarthMoon(), EarthMoonRotFrame(), LunarVisibility(), OrbMnvrLowerApogee(), PatchedConicPlanner(), PtchCnc(), RadiationBelts(), and RVOrbGen().
RPV2AE()
function RPV2AE (in rP, in v, in mu)
Form
 [a, e] = RPV2AE( rP, v, mu )
Inputs
 rP              (1,1) Perigee
 v               (1,1) Velocity
 mu              (1,1) Gravitational potential
Outputs
 a               (1,1) Semi-major axis
 e               (1,1) Eccentricity
References: Bate, R.R., et. al. Fundamentals of Astrodynamics, pp. 70-71.
References and(), Demo(), RPV2AE(), and RV2A().
Referenced by RPV2AE().
RToNu()
function RToNu (in a, in e, in r)
a and r must be in the same units.
Type RToNu for a demo of an elliptic orbit.
Form
 nu =  RToNu( a, e, r )
Inputs
 a     (1,1)  Semi-major axis
 e     (1,1)  Eccentricity
 r     (1,:)  Radius
Outputs
 nu     (1,:)  True anomaly (rad)
References abs(), and(), Demo(), Mag(), Plot2D(), RToNu(), and RVOrbGen().
Referenced by RToNu().
RV2A()
function RV2A (in r, in v, in mu)
 The default central body is the Earth.
Form
 a = RV2A( r, v, mu )
Inputs
 r       (1,:)   Position magnitude
 v       (1,:)   Velocity magnitude
 mu      (1,1)   Gravitational parameter (default is Earth)
Outputs
 a       (1,:)   Semimajor axis
References and().
Referenced by FlybyHyperbola(), FOrbKF(), and RPV2AE().
RV2AE()
function RV2AE (in r, in v, in mu)
Form
 [a, e, rP, rA] = RV2AE( r, v, mu )
Inputs
 r               (3,:) Position vector
 v               (3,:) Velocity vector
 mu              (1,1) Gravitational constant
Outputs
 a               (1,:) Semi-major axis
 e               (1,:) Eccentricity
 rP              (1,:) Perigee
 rA              (1,:) Apogee
References: Bate, R.R., et. al. Fundamentals of Astrodynamics, pp. 70-71.
References and(), Cross(), Dot(), DupVect(), length(), Mag(), Plot2D(), RV2AE(), and vector().
Referenced by GuidedLaunch2DCost(), LowThrustSim(), OrbMnvrCircularize(), RV2AE(), StoppingConditions(), and ThrustControlRaiseApogee().
RV2El()
function RV2El (in r, in v, in mu)
Form
 [el, E, f] = RV2El( r, v, mu )
Inputs
 r               (3,1) Position vector
 v               (3,1) Velocity vector
 mu              (1,1) Gravitational constant
Outputs
 el              (1,6) Elements vector [a,i,W,w,e,M]
 E               (1,1) Eccentric anomaly
 f               (1,1) True anomaly
See also
: El2RV, RVFromKepler
References: Vallado, D. A. (1997.) Fundamentals of Astrodynamics and Applications. pp. 144-147.
References abs(), and(), Cross(), El2RV(), Limit(), Mag(), Nu2E(), Nu2M(), RVFromKepler(), vector(), and zeros().
Referenced by ApophisOrbit(), CheckDeltaVs(), CompareHills(), ComputeTLE(), DoDeltaV(), DrawOrbitPlane(), DVTarget(), EarthOrbToHelioOrb(), ECI2MeanElements(), El2RV(), FFEccFrameCompare(), FFEccHills2DeltaElem(), FlightPathAngle(), GeoOptimalMission(), GeoSwitchingMission(), GetHillsMats(), GetLVLHMats(), HohmannTransferRendezvous(), J2Prop(), LETPhasing(), LocallyOptimalTraj(), LowEnergyEarthToMoonTransfer(), LowThrustControl(), LQOrbitController(), LunarTargeting(), MoonECIElements(), OrbitDeltaV(), PackageOrbitDataForPlayback(), PatchedConicPlanner(), PlanetTransferLambert(), Plot2DTrajectory(), Plot3DOrbit(), PlotLambertTransfer(), PlotSailProfile(), ProjCirc(), PtchCnc(), QSunNadir(), RendezvousPlanner(), RotateOrbit(), RV2Eq(), RVOrbGenDV(), RVOrbHF(), RVSet2El(), RVToMEq(), SafeGuidanceSim(), StoppingConditions(), TestFFEccLinOrb(), TestLPEccentricGVE(), TrajectoryBetweenTwoPlanets(), and TwoDEscape().
RV2Eq()
function RV2Eq (in r, in v, in mu)
Form
 eq = RV2Eq( r, v, mu )
Inputs
 r               (3,1) Position vector
 v               (3,1) Velocity vector
 mu                    Gravitational constant
Outputs
 eq                    Elements vector [a,P1,P2,Q1,Q2,l]
References: Bate, R.R., et. al. Fundamentals of Astrodynamics, pp. 70-71.
References and(), El2Eq(), RV2El(), and vector().
RV2RaDec()
function RV2RaDec (in r, in v)
 You can just enter r to get just rA and dec.
Form
 [rA, dec, rARate, decRate] = RV2RaDec( r, v )
Inputs
 r            (3,n)     Position vectors
 v            (3,n)     Velocity vectors
Outputs
 rA           (1,n)     Right ascension
 dec          (1,n)     Declination
 rARate       (1,n)     Right ascension rate
 decRate      (1,n)     Declination rate
References and(), and get().
RVFromKepler()
function RVFromKepler (in elI, in t, in mu, in tol)
If t is not entered it will plot one orbit. Only handles elliptical orbits.
Form
 [r, v, t] = RVFromKepler( elI, t, mu, tol )
Inputs
 elI        (1,6) Elements vector [a,i,W,w,e,M] or structure
 t          (1,:) Times from 0 to  (sec)
 mu         (1,1) Gravitational parameter
 tol        (1,1) Orbit propagation tolerance
Outputs
 r          (3,:) Position vectors for times t
 v          (3,:) Velocity vectors for times t
 t          (1,:) Times at which r and v are calculated
See also
: El2RV
References abs(), and(), CP2I(), El2RV(), isempty(), M2E(), Plot2D(), Plot3D(), TimeLabl(), vector(), and zeros().
Referenced by AeroDragForce(), ApophisOrbit(), AttitudeProfile(), AttitudeProfileToTorque(), AttitudeProfileWithCon(), BDipole(), BDipoleCoeff(), ClockConversion(), ConeClockToU(), CubeSatAero(), CubeSatDisturbanceAnalysis(), CubeSatPowerAnalysis(), DistributedAlbedo(), DrawOrbitPlane(), DrawSpacecraftInOrbit(), DVTarget(), EarthAlb(), EarthMoon(), El2RV(), FSailEarthMoon(), GenerateSwath(), GeoOptimalMission(), GPSSatellite(), GroundStationVisibility(), GroundTrack(), HSAData(), Isothermal(), IsothermalLunar(), LinkAnalysisTool(), LinkOrbitAnalysis(), LocallyOptimalTraj(), MagControlTwoAxis(), MagField(), OrbView(), PackageOrbitDataForPlayback(), PlanetAlignments(), PlanetEnvironment(), PlanetOptimalTraj(), PlanetTransferLambert(), PlaybackOrbitSim(), Plot3D(), Plot3DTrajectory(), Plot3Vector(), PlotLambertTransfer(), PlotLunarOrbit(), PlotOrbitTransfer(), PowerDesign(), QSunNadir(), RV2El(), RVOrbGen(), RVSet2El(), SolarVisibility(), and WalkerConstellation().
RVOrbGen()
function RVOrbGen (in elI, in t, in uSun, in mu, in rPlanet, in tol)
The orbit may have any eccentricity, including parabolic or hyperbolic.
If t is not entered it generate one orbit. If there are no arguments it will plot the orbit. Enter rPlanet to draw a planet sphere. If the sun vector is entered as well the planet sphere will be illuminated.
Form
 [r, v, t] = RVOrbGen( el, t, uSun, mu, rPlanet, tol )
Inputs
 elI        (1,6) Elements vector [a,i,W,w,e,M] or structure
 t          (1,:) Time vector (sec)
 uSun       (3,1) Sun vector*
 mu         (1,1) Gravitational parameter
 rPlanet    (1,1) Planet radius*
 tol        (1,1) Orbit propagation tolerance (1e-8)
                  * inputs for plotting purposes only
Outputs
 r          (3,:) Position vectors for times t
 v          (3,:) Velocity vectors for times t
 t          (1,:) Times at which r and v are calculated
See also
RVFromKepler
References abs(), and(), Axis3D(), CP2I(), Demo(), E2Nu(), Equal(), isempty(), M2E(), NewFig(), Nu2M(), Plot2D(), RPRA2AE(), RVFromKepler(), RVOrbGen(), SLR(), TimeLabl(), vector(), Watermark(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by AtmNRLMSISE(), BatterySize(), BDipolePlanet(), CheckDeltaVs(), CompareHills(), ConstellationGroundContact(), ConstellationMaxDistance(), CoplanarOrbit(), DataRateOrbit(), DistAero(), DistAlbedo(), DistRadiation(), DistSolar(), DVOrbitDrag(), EarthEnvironment(), EarthMoonRotFrame(), EclipseFromECI(), EclipticInjectionPlane(), FFEccFrameCompare(), FlightPathAngle(), Flyby(), GlideSlope(), HohmannTransferRendezvous(), InclinationRate(), LunarVisibility(), MoonECIElements(), NadGen(), OrbitClosestPoint(), OrbitFromSynodic(), OrbMnvrHohmann(), OrbMnvrLowerApogee(), OrbTrack(), OrbTrackECI3D(), PatchedConicPlanner(), PermanentMagnetRHS(), PlanetTrajectoryPlot(), PlanetTransferLambert(), Plot3DOrbit(), PlotLambertTransfer(), PlotSailProfile(), PtchCnc(), RadiationBelts(), RandomOrbit(), RendezvousPlanner(), RotateOrbit(), RToNu(), RVOrbGen(), RVOrbGenDV(), RVOrbHF(), SolarFluxFromPlateECI(), TransferTimeToDV(), TwoDEscape(), TwoUToQ(), and WMM().
RVOrbHF()
function RVOrbHF (in r, in v, in jD, in options, in t, in aExt, in tol, in s, in c, in j, in mu, in a)
If t is omitted one orbit will be computed with 100 points. If jD is omitted a Keplerian orbit will be generated. If options is omitted the simplified model will be used.
 If no outputs are specified it will plot the orbit and the deviation
 from a Keplerian orbit.
Options:
 Highest zonal harmonic    - 0 through n
 Highest tesseral harmonic - 0 through m
 Sun                       - 0 equals off, 1 equals on
 Moon                      - 0 equals off, 1 equals on
 Drag                      - CD*A/m
Type RVOrbHF for a demo with the EGM50x50 model. The otput is compared to Kepler propagation using RVOrbGen.
Form
 [rP, vP] = RVOrbHF( r, v, jD, options, t, aExt, tol, gM )
 [rP, vP] = RVOrbHF( r, v, jD, options, t, aExt, tol, s, c, j, mu, a )
Inputs
 r             (3,1)  Initial position vector (km)
 v             (3,1)  Initial velocity vector (km)
 jD                   Julian date of the start
 options         (5)  [Highest zonal harmonic,Highest tesseral harmonic,Sun,Moon,Drag]
 t               (n)  Times at which the new r and v are to be computed;
                         need not be uniform
 aExt        (3,n|1)  External acceleration vector [x;y;z] ECI
 tol                  Tolerance for the integration
 d               (.)  Gravity model struct, unnormalized
    - or -
 s             (:,:)  S terms
 c             (:,:)  C terms
 j               (:)  m = 0 terms
 mu                   Gravitational parameter (km^3/sec^2)
 a                    Earth radius
Outputs
 rP                  Position vectors at times t
 vP                  Velocity vectors at times t
See also
: FOrbHF, RK45, RV2El
References abs(), and(), AxesCart(), Axis3D(), DupVect(), E2M(), El2RV(), Equal(), FOrbHF(), isempty(), JD2000(), length(), LoadGEM(), NewFig(), Nu2E(), Plot2D(), RK45(), RV2El(), RVOrbGen(), RVOrbHF(), SunV1(), TimeLabl(), UnnormalizeGravity(), vector(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by RVOrbHF().
RVSet2El()
function RVSet2El (in r, in v, in mu, in tol)
Enforces continuous true anomaly for an osculating orbit. Handles special cases like equatorial and circular orbits. The numerical tolerance should be consistent with that used to generate the ephemeris, see RVFromKepler.
Form
 el = RVSet2El( r, v, mu, tol )
Inputs
 r               (3,:) Position vector
 v               (3,:) Velocity vector
 mu              (1,1) Gravitational constant*
 tol             (1,1) Numerical tolerance* (Default 1e-8)
                          * optional
Outputs
 el              (:,6) Elements vector [a,i,W,w,e,M]
References: Vallado, D. A. (2001) Fundamentals of Astrodynamics and Applications. pp. 104-111.
References abs(), and(), Cross(), Date2JD(), Dot(), E2M(), El2RV(), isempty(), J2Prop(), length(), Limit(), Mag(), Nu2E(), Period(), Plot2D(), RV2El(), RVFromKepler(), vector(), and zeros().
RVToMEq()
function RVToMEq (in r, in v, in mu)
 The modified equinoctial elements are
 p = a(1 + e^2)
 f = ecos(w + W);
 g = esin(w + W);
 h = tan(i/2)cosW
 k = tan(i/2)sinW
 L = W + w + nu
 W is right ascension of the ascending node
 w is argument of perigee
Form
 x = RVToMEq( r, v, mu )
Inputs
 r              (3,1)  Position vector
 v              (3,1)  Velocity vector
 mu             (1,1)  Gravitational parameter
Outputs
 x              (6,1)  Elements
References and(), Demo(), ElToMEq(), MEqToRV(), RV2El(), RVToMEq(), and vector().
Referenced by RVToMEq().
SeeTLE()
function SeeTLE (in group, in hours, in color)
Draws on an existing figure if one exists. Specify a unique color to view distinct groups. Computes the trajectories in increments of 1 minute.
Form
 [fig,r0,jD0] = SeeTLE( group, hours, color )
Inputs
 group        (:)     Name of TLE group. Several groups are provided on
                         www.celestrak.com.
 hours       (1,1)    Number of hours to propagate all TLEs.
 color  (1,3) or 'c'  RGB triple or character for color, default 'r'
Outputs
 fig         (1,1)   Figure handle, if one created
 r0          (3,n)   EF initial positions of the satellites
 jD0         (1,1)   Epoch from datetime("now")
References and(), ConvertNORAD(), Date2JD(), isempty(), LocalTimeToGMT(), Map(), PropagateTLECommonTime(), SeeTLE(), SelectTLEGroup(), set(), TEMEToPEF(), vector(), and zeros().
Referenced by SeeTLE(), and SelectTLEGroup().
SelectTLEGroup()
function SelectTLEGroup ()
The list of groups is hard-coded and may need to updated from time to time. Also, the link used in SeeTLE may change. The callback to view the orbits is:
 'SeeTLE( get(gco,''string'') )'
 Forms:
 [fig,groups] = SelectTLEGroup
Inputs
 None
Outputs
 fig         (1,1)   Figure handle to the GUI.
 groups      {}      If requested, the figure is suppressed.
See also
: SeeTLE
References and(), SeeTLE(), and SelectTLEGroup().
Referenced by SeeTLE(), and SelectTLEGroup().
SemimajorAxisRevisit()
function SemimajorAxisRevisit (in swath, in revisit, in mu, in rP, in day)
Computes semi-major axis from the desired revisit time and the swath angle. The default parameters are for the earth. The swath angle is the full angle. It recomputes swath for the new orbits.
Type SemimajorAxisRevisit for a demo around the earth.
Form
 [a, swath] = SemimajorAxisRevisit( swath, revisit, mu, rP, day )
 [a, swath] = SemimajorAxisRevisit( swath, revisit ) (Earth)
Inputs
 swath   (1,1) Swath angle (rad)
 revisit (1,:) Revisit time (days)
 mu      (1,1) Gravitational parameter (km^3/s^2)
 rP      (1,1) Planet radius (km)
 day     (1,1) Length of day (sec)
Outputs
 a       (1,:) Semi-major axis (km)
 swath   (1,:) Swath angle (rad)
See also
PeriodToSemimajorAxis.
References and(), Demo(), Period(), PeriodToSemimajorAxis(), SemimajorAxisRevisit(), and Swath().
Referenced by SemimajorAxisRevisit().
SLR()
function SLR (in e, in a)
Form
 p = SLR( e, a )
Inputs
 e  (1,:)  Eccentricity
 a  (1,:)  Semi major axis (or perigee radius for parabola)
Outputs
 p  (1,:)  Semi-latus rectum
References: Bates, R.B. Fundamentals of Astrodynamics, pp. 28,34.
References DupVect(), length(), and Mesh2().
Referenced by RVOrbGen().
SolveT()
function SolveT (in vI, in vT, in rho0, in T)
Function to pass to NewtRaph for solving for the period of a glideslope given the initial and final velocities.
Form
 y = SolveT( vI, vT, rho0, T )
 Inputs
 vI    (1,:) Initial velocity
 vT    (1,:) Terminal velocity
 rho0  (1,1) Weight on ratio of terminal to initial velocity
 T     (1,1) Weight on difference in terminal and initial velocity
Outputs
 y     (1,:) Cost
References abs(), and(), and NewtRaph().
Referenced by DVGlideslope(), and GlideslopeGuidance().
SolveTD()
function SolveTD (in vI, in vT, in rho0, in T)
Derivative function to pass to NewtRaph for solving the period of a glideslope given the initial and final velocities.
Form
 y = SolveTD( vI, vT, rho0, T )
 Inputs
 vI    (1,:) Initial velocity
 vT    (1,:) Terminal velocity
 rho0  (1,1) Weight on ratio of terminal to initial velocity
 T     (1,1) Weight on difference in terminal and initial velocity
Outputs
 y     (1,:) Cost
References and(), and NewtRaph().
Referenced by DVGlideslope(), and GlideslopeGuidance().
SpacecraftFromAccel()
function SpacecraftFromAccel (in sC, in s)
The acceleration and time is typically an output of the orbit optimization. Some combinations of parameters will not converge and the mission will be impossible for the given maximum acceleration, which is used to compute the maximum thrust and therefore the power plant size. You will get an error if it does not converge.
Payload mass includes everything that is not engine, fuel or fuel tanks.
Creates a plot of the thrust, mass, and power over time.
Form
 sC = SpacecraftFromAccel;  % data structure for input
 out = SpacecraftFromAccel( sC, s )
Inputs
 sC  (.)
         .uE     (1,1) Exhaust velocity (km/s)
         .sigma  (1,1) Specific power (W/kg)
         .mP     (1,1) Payload mass (kg)
         .fS     (1,1) Fuel structural fraction (0-1)
         .eff    (1,1) Engine thrust efficiency (0-1)
 s   (.)
         .a      (3,:) Acceleration profile (km/s^2)
         .t      (1,:) Times corresponding to a
Outputs
 out (.)
         .DV      (1,1)     Total delta-V (km/s)
         .p       (1,1)     Engine power (W)
         .m0      (1,1)     Initial mass (kg)
         .mP      (1,1)     Payload mass (kg)
         .mE      (1,1)     Engine mass (kg)
         .mF      (1,1)     Fuel mass (kg)
         .mS      (1,1)     Structural mass (kg)
References and(), get(), and SpacecraftFromAccel().
Referenced by SpacecraftFromAccel().
SphOI()
function SphOI (in m, in M)
Computes the ratio of the sphere of influence to the distance between two bodies. Uses 2/5 power based on the argument due to Lagrange.
 m                         M
 ?-------------------------?
 |<---------- 1 ---------->|
 |----->|
 rOR
Form
 rOR = SphOI( m, M )
Inputs
 m              (1,n)  Mass of planet of interest
 M              (1,m)  Mass of other planet
Outputs
 rOR            (n,m)  Ratio of sphere of influence for m to
                       distance between the two planets
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 288-291.
References Demo().
Referenced by PatchedConicPlanner(), and PtchCnc().
SphOrb()
function SphOrb (in x, in a, in mu)
 (phi is 0 in the equatorial plane and ?/2 at the pole)
 Since version 1.
Form
 xd = SphOrb( x, a, mu )
Inputs
 x                (6,1) State [r;theta;phi;dr/dt;dtheta/dt;dphi/dt]
 a                (3,1) acceleration vector
 mu                     gravitational parameter
Outputs
 xd               (6,1) state derivative
References: Bate, R. R., Fundamentals of Astrodynamics. pp. 389-390.
References and(), SphOrb(), and vector().
Referenced by CylOrb(), FOrb(), FRotatingPlanet(), FRotatingSun(), and SphOrb().
StoppingConditions()
function StoppingConditions (in r, in v, in jD, in mu, in stopping, in planet)
Form
 [value, direction] = StoppingConditions( r, v, jD, mu, stopping, planet )
Inputs
 r           (3,1)  Position vector in ECI frame
 v           (3,1)  Velocity vector in ECI frame
 jD          (1,1)  Time
 mu          (1,1)  Gravitational potential
 stopping    (1,1)  Stopping condition structure
                    condition   (:)    Stopping condition structure
                                       .name    (1,:) Name of the condition
                                       .value   (1,1) Value of the condition
                    vInit       (3,1)  Initial velocity
 planet      (1,:)  Planet name
Outputs
 value       (1,1)  Value of the stopping condition
 direction   (1,1)  Direction (-1,0,1)
References abs(), Altitude(), and(), ECIToPlanet(), EFToLatLonAlt(), Energy(), FlightPathAngle(), isempty(), length(), Mag(), Period(), R2LatLon(), RV2AE(), RV2El(), vector(), and zeros().
StoppingPlugIn()
function StoppingPlugIn (in action, in modifier, in hFig, in position, in callback)
Form
 x = StoppingPlugIn( action, modifier, hFig, position, callback )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifer     (1,:)  Modifier to the action or data structure if intialization
 hFig        (1,1)  Handle to the figure or if 'update' radio button handles
 position    (1,4)  [left bottom width height]
 callback    (1,:)  Callback string when something has changed in this gui
Outputs
 x           (1,1)  The tag if action is 'initialize'
References get(), GetH(), GetNewTag(), Initialize(), isempty(), and set().
SunSyncInclination()
function SunSyncInclination (in a, in e, in j2, in mu, in R)
All parameters beyond semi-major axis are optional.
Form
 [iSync,WDot] = SunSyncInclination( a, e, j2, mu, R )
Inputs
 a              (1,1)  Semi major axis
 e              (1,1)  Eccentricity (Default: 0)
 j2             (1,1)  J2 term
 mu             (1,1)  Gravitational parameter
 R              (1,1)  Planet radius
Outputs
 iSync          (1,1)  Synchronous inclination (rad)
 WDot           (1,1)  Orbit plane precession (rad/s)
See also
J2OrbitEffects.
Reference: Wiesel, W. E. (1989.) Spaceflight Dynamics. pp. 86-88. Vallado, 2nd Edition, p. 782-784
References J2OrbitEffects().
Referenced by J2OrbitEffects().
SunSyncNode()
function SunSyncNode (in lt, in jD)
The mean sun is computed using the Simon Newcomb equations which are also used in the Astronomal Almanac. The local time is just the difference between this mean sun angle and the right ascension of the ascending node. See also LTAN.
Form
 W = SunSyncNode( lt, jd )
Inputs
 lt   (1,1)  Local time, expressed in hours (0-23)
 jD   (1,1)  Julian date
Outputs
 W    (1,1)   Right ascension of the ascending node
References and(), JDToMidnight(), and LTAN().
SynodicFromSemimajorAxes()
function SynodicFromSemimajorAxes (in a1, in a2, in mu)
Type SynodicFromSemiMajorAxes for an example of Mars and Earth.
Form
 p = SynodicFromSemimajorAxes( a1, a2, mu )
Inputs
 al            (1,1)   Orbit 1 semi-major axis (km)
 a2            (1,1)   Orbit 2 semi-major axis (km)
 mu            (1,1)   Gravitational constant
Outputs
 p             (1,1)   Synodic period
References and(), Constant(), Demo(), Period(), SynodicFromSemimajorAxes(), SynPer(), and TimeLabl().
Referenced by SynodicFromSemimajorAxes(), and SynodicPlanets().
SynPer()
function SynPer (in n1, in n2)
Type SynPer of a demo of orbit periods from Mercury's to Mars relative to the Earth.
Form
 p = SynPer( n1, n2 )
Inputs
 n1            (:)     Orbit rate 1 (rad/s)
 n2                    Orbit rate 2 (rad/s)
Outputs
 p             (:)     Synodic period (sec)
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 293.
References SynPer().
Referenced by PlanetAlignments(), PlanetOpposition(), SynodicFromSemimajorAxes(), and SynPer().
TARes()
function TARes (in r0, in r, in orbitType)
 Since version 2.
Form
 phi = TARes( r0, r, orbitType )
Inputs
 r0            (3,1)   Initial position vector
 r             (3,1)   Final position vector
 orbitType     (1,:)   'direct' or 'retrograde'
Outputs
 phi           (1,1)    Transfer angle
References: Bond, V.R. and Allman, M. C., "Modern Astrodynamics", Princeton University Press, 1996, pp. 233-235
References and(), Cross(), Unit(), and vector().
Referenced by LTVCon().
TEMEToPEF()
function TEMEToPEF (in jD)
Equivalent to a rotation about the Z axis by GMST. TEME is the true equator, mean equinox frame of satellite ephemerides generated from TLEs using SGP4 propagation.
Form
 c = TEMEToPEF( jD )
Inputs
 jD            Julian date
Outputs
 c                Matrix from TEME to planet fixed
References: Vallado
References JD2000().
Referenced by SeeTLE().
Tfr2Imp()
function Tfr2Imp (in e1, in a1, in e2, in a2, in i1, in i2, in mu)
Computes the delta-v needed to go from a transfer orbit to a final orbit with a plane change in two impulses.
Form
 [dv, dv1t, dvt2, et, theta] = Tfr2Imp( e1, a1, e2, a2, i1, i2, mu )
Inputs
 e1                     Eccentricity of the first orbit
 a1                     Semi-major axis of the first orbit
 e2                     Eccentricity of the final orbit
 a2                     Semi-major axis of the final orbit
 i1                     Initial inclination (deg)
 i2                     Final inclination (deg)
 mu                     Gravitational parameter
Outputs
 dv                     Total delta v
 dv1t                   Delta v for first burn
 dvt2                   Delta v for second burn
 et                     Eccentricity of second orbit
 theta                  Angle of 2nd delta-v (deg)
References: Kaplan, M., Modern Spacecraft Dynamics and Control, John Wiley, pp. 87-91.
References and().
Tfr3Imp()
function Tfr3Imp (in e1, in a1, in e4, in a4, in n, in i1, in i4, in mu)
Computes the delta-v needed to go from a transfer orbit to a final orbit with a plane change in three impulses. Generally n should be as large as possible but this will run into the law of diminishing returns and operational constraints.
Form
 [dv, dv12, dv23, dv34, e2, e3, theta] = Tfr3Imp( e1, a1, e4, a4, n, i1, i4 ,mu )
Inputs
 e1                     Eccentricity of the first orbit
 a1                     Semi-major axis of the first orbit
 e4                     Eccentricity of the final orbit
 a4                     Semi-major axis of the final orbit
 n                      Ratio of intermediate apogee to final apogee
 i1                     Initial inclination (deg)
 i4                     Final inclination (deg)
 mu                     Gravitational parameter
Outputs
 dv                     Total delta v
 dv12                   Delta v for first burn
 dv23                   Delta v for second burn
 dv34                   Delta v for third burn
 e2                     Eccentricity of second orbit
 e3                     Eccentricity of third orbit
 theta                  Angle of 2nd delta-v (deg)
References: Kaplan, M., Modern Spacecraft Dynamics and Control, John Wiley, p. 87.
References and().
THohmn()
function THohmn (in R1, in R2, in mu)
 Since version 1.
Form
 [Ts, Tt, Tw, T, phi1, phi2, P1, P2] = THohmn( R1, R2, mu )
Inputs
 R1                    Orbit radius 1
 R2                    Orbit radius 2
 mu                    Gravitational parameter
Outputs
 Ts                    Synodic Period
 Tt                    Transfer time
 Tw                    Wait Time
 T                     Total trip time
 phi1                  phase angle between 1 and 2 at launch
                       + implies 2 leads 1
 phi2                  phase angle between 1 and 2 at intercept
                       + implies 1 lags 2
 P1                    Period of orbit 1
 P2                    Period of orbit 2
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 291-294.
References and(), and Period().
Referenced by HohmannTransferRendezvous(), and TransferTimeToDV().
TimeOfFlightHyperbola()
function TimeOfFlightHyperbola (in a, in e, in nu1, in nu2, in mu)
This function gives the time of flight between two true anomalies. This function only works for hyperbolas. It will throw an error if either true anomaly is outside the maximum true anomaly for the hyperbola.
Type TimeOfFlightHyperbola for a demo in lunar orbit.
Form
 t = TimeOfFlightHyperbola(a,e,nu1,nu2,mu)
Inputs
 a   (1,1)   Semi-major axis
 e      (1,1)   Eccentricity
 nu1    (1,1)   Initial true anomaly (rad)
 nu2    (1,:)   Final true anomaly (rad)
 mu  (1,1)   Gravitational parameter
Outputs
 t   (1,1)   Time of flight
Reference: http://www.braeunig.us/space/orbmech.htm equation 4.86
References abs(), Demo(), and TimeOfFlightHyperbola().
Referenced by OrbitLoweringManeuvers(), TimeOfFlightHyperbola(), and TrueAnomalyStartHyperbola().
TLETime()
function TLETime (in tLE, in startDate, in endDate, in n)
Time vector for a TLE
Type TLETime for a demo.
Form
 t = TLETime( tLE, startDate, endDate, n )
Inputs
 tLE         (1,:)           TLE string
 startDate   (1,1) or (1,6)  Julian date or date array
 endDate     (1,1) or (1,6)  Julian date or date array
 n           (1,1)           Number of steps (default is 100)
Outputs
 t           (1,n)  Time vector
References ConvertNORAD(), Date2JD(), length(), Plot2D(), TLETime(), and vector().
Referenced by TLETime().
TrajectoryOptimization()
function TrajectoryOptimization (in d)
Available methods are: 'downhill simplex' and 'genetic algorithm' (Sail module only). d is an array of datastructures defining the different methods. You can set up the methods to operate sequentially, i.e. on the end condition of the previous method, or to use the new initial lambda (costate) and redo the problem.
This function has a built-in demo for a low thrust 2D trajectory.
Form
 d = TrajectoryOptimization; % init data structure
 d = TrajectoryOptimization( costFun )
 [lambda,xF,tF] = TrajectoryOptimization( d )
Inputs
 d              (:)  Input data structure
                     .method (1,:) Method
                     .repeat (1,1) 1 means use the last lambda for the next
                                   pass; implies length(d) > 1
                     .d            Data structure with method parameters
Outputs
 lambda         (:)  The computed costates
 xF            (1,:) The final state achieved
 tF            (1,:) Time of final state
References and(), CostLowThrust2D(), Demo(), length(), set(), Simplex(), and TrajectoryOptimization().
Referenced by TrajectoryOptimization().
TrajectoryPlot()
function TrajectoryPlot (in r, in t, in u, in varargin)
If t is entered it will annotate r with times. If u is entered it will draw the vectors u as arrows and points along r.
r and u may be (3,:) or (2,:)
Form
 TrajectoryPlot( r, t, u, varargin )
Inputs
 r             (3,:)   Positions
 t             (1,:)   Times
 u             (3,:)   Unit vectors orginating along r
 varargin      {}      Parameter pairs
                       'xlabel'            x axis label
                       'ylabel'            y axis label
                       'zlabel'            z axis label
                       'title'             plot title
                       'ntags              number of u and t tags
                       'time units'        time units
                       'half angle'        half angle of the arrows
                       'arrow line width'  width of the arrow lines
Outputs
 None
References and(), TrajectoryPlot(), and Unit().
Referenced by TrajectoryPlot().
TransferAndPhaseAngle()
function TransferAndPhaseAngle (in r1, in r2, in tT, in mu)
Form
 [transferAngle, phaseAngle] = TransferAndPhaseAngle( r1, r2, tT, mu )
Inputs
 r1                    Orbit radius 1
 r2                    Orbit radius 2
 tT                    TransferTime
 mu                    Gravitational parameter
Outputs
 transferAngle         Transfer angle (rad)
 phaseAngle            Phase angle (rad)
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 292.
References and().
TransferTimeToDV()
function TransferTimeToDV (in elT, in elC, in transferTime, in mu, in tol, in planet)
Uses the MATLAB function fmins to optimize the start and transfer times for the maneuver. Draws a figure for no outputs.
See also
LambertOpt.
 Forms:
 maneuver  = TransferTimeToDV( elT, elC, transferTime, mu, tol, planet )
 maneuver  = TransferTimeToDV
 TransferTimeToDV  % built-in demo
Inputs
 elT           (6,1)   Target orbit elements for current position
 elC           (6,1)   Chase orbit elements for current position
 transferTime  (1,2)   Transfer times [nominal max]
 mu            (1,1)   Gravitational parameter*
 tol           (1,1)   Tolerance*
 planet        (:)     Orbit center*
                          * Optional
Outputs
 maneuver      (1,1)    Maneuver data structure
                        .dV1       (1,1) Transfer orbit insertion delta-V
                        .dV2       (1,1) Target orbit insertion delta-V
                        .tStart    (1,1) Start time relative to epoch
                        .tTransfer (1,1) Time in transfer orbit
                        .u         (3,2) Unit vectors of thrust
References and(), El2RV(), isempty(), LambertOpt(), LambertTOF(), Map(), NewFig(), RVOrbGen(), THohmn(), TitleS(), TransferTimeToDV(), and Unit().
Referenced by TransferTimeToDV().
TriangularManeuver()
function TriangularManeuver (in p, in r, in m, in t, in uE)
r is the perpendicular bisector. The triangle is assumed to be equilateral. This maneuvers in a triangle around a point. This is useful for maneuvering around a target.
Form
 [dV, fuel] = TriangularManeuver( p, r, m, t, uE )
Inputs
 p            (1,1)     Period (min)
 r            (1,1)     Perpendicular bisector of maneuver (m)
 m            (1,1)     Mass (kg)
 t            (1,1)     Duration (min)
 uE           (1,1)     Exhaust velocity (m/sec)
Outputs
 dV           (1,1)     Total delta-V (m/s)
 fuel         (1,1)     Fuel consumption (kg)
References Demo(), Period(), Perpendicular(), TanD(), and TriangularManeuver().
Referenced by TriangularManeuver().
TrueAnomalySpacing()
function TrueAnomalySpacing (in e, in nu0, in n, in duration, in nS, in eTol)
Form
 [nu, dT, t] = TrueAnomalySpacing( e, nu0, n, duration, nS, eTol )
Inputs
 e           (1,1)   Eccentricity
 nu0         (1,1)   Initial true anomaly (rad)
 n           (1,1)   Mean orbit rate (rad/s)
 duration    (1,1)   Duration of array (sec)
 nS          (1,1)   Total number of samples
 eTol        (1,1)   Tolerance on e (circular orbit)
Outputs
 nu          (1,:)  True anomalies
 dT          (1,:)  Time steps
 t           (1,:+1)    Time vector
References Demo(), M2NuAbs(), Nu2M(), TrueAnomalySpacing(), UnwrapPhase(), and vector().
Referenced by TrueAnomalySpacing().
TrxCntrl()
function TrxCntrl (in eLon, in lonTol)
 Generates plots when called with no outputs.
Form
 [lonD0, lon0, dv, dvP, te, a] = TrxCntrl( eLon, lonTol )
Inputs
 eLon                   East longitude of station (deg)
 lonTol                 Longitude tolerance (deg)
Outputs
 lonD0                  Initial longitude rate at lon0
 lon0                   Starting longitude (will be lonTol)
 dv                     Total delta-v requirement per year (m/sec)
 dvP                    Delta-v per maneuver (split into two) (m/sec)
 te                     Time between maneuvers (days)
 a                      Apparent acceleration (rad/day^2)
References: Michielsen, H.F., E.D. Webb, Stationkeeping of Stationary Satellites Made Simple, pp. 706-709.
References abs(), Demo(), DVGeoTrx(), length(), NewFig(), TextS(), XLabelS(), and YLabelS().
TTrnsHoh()
function TTrnsHoh (in R1, in R2, in mu)
 Since version 1.
Form
 T = TTrnsHoh( R1, R2, mu )
Inputs
 R1                    Orbit radius 1
 R2                    Orbit radius 2
 mu                    Gravitational parameter
Outputs
 T                     Transfer time (sec)
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 292.
TWaitHoh()
function TWaitHoh (in R1, in R2, in mu)
 Since version 1.
Form
 T = TWaitHoh( R1, R2, mu )
Inputs
 R1                    Orbit radius 1
 R2                    Orbit radius 2
 mu                    Gravitational parameter
Outputs
 T                     Wait time (sec)
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 294.
TwoObjectTrajectoryViewer()
function TwoObjectTrajectoryViewer (in action, in varargin)
This function uses persistent variables.
Type TwoObjectTrajectoryViewer for a demo.
Form
 TwoObjectTrajectoryViewer( 'initialize', n, s, gP, gM )
 TwoObjectTrajectoryViewer( 'update', r1, r2, k, t )
Inputs
 action  (1,:) 'initialize', 'update'
Outputs
 None
References and(), Demo(), and TwoObjectTrajectoryViewer().
Referenced by TwoObjectTrajectoryViewer().
UGravity()
function UGravity (in nZ, in nT, in r, in lambda, in theta, in s, in c, in j, in mu, in a)
r must be a scalar but theta and phi may be arrays. If you want to call this routine multiple times it is faster to do
 [s, c, j, mu, a] = LoadGEM( 1 )
 for k = 1:kMax
 [u, uS, uZ, uT] = UGravity( nZ, nT, r, lambda, theta, s, c, j, mu, a );
 end
than
 for k = 1:kMax
 [u, uS, uZ, uT] = UGravity( nZ, nT, r, lambda, theta );
 end
Form
 [u, uS, uZ, uT] = UGravity( nZ, nT, r, lambda, theta, s, c, j, mu, a )
Inputs
 nZ                   Highest zonal harmonic (m = 0)
 nT                   Highest sectorial and tesseral harmonic
 r                    Radius
 lambda        (j)    Equatorial angle
 theta         (i)    Angle from pole
 s           (36,36)  S terms
 c           (36,36)  C terms
 j              (36)  m = 0 terms
 mu                   Spherical gravitational potential
 a                    Earth radius
Outputs
 u             (i,j)  Total gravitational potential
 uS                   Spherical term
 uZ            (i)    Zonal terms
 uT            (i,j)  Tesseral and sectorial terms
Reference: Seidelmann, P.K, (ed) (1992). Explanatory Supplement to the Astronomical Almanac. University Science Books, Mill Valley, CA. p. 226.
References and(), length(), Mesh2(), PAL(), SCHarm(), and zeros().
UnnormalizeGravity()
function UnnormalizeGravity (in g)
Type UnnormalizeGravity for a demo.
Form
 h = UnnormalizeGravity( g )
Inputs
 g   (.) Gravity model data structure
Outputs
 h   (.) Gravity model data structure
References length(), NormalizationMatrix(), UnnormalizeGravity(), and zeros().
Referenced by AGravity(), NormalizationMatrix(), RVOrbHF(), and UnnormalizeGravity().
VarEqP()
function VarEqP (in eq, in aD, in tol, in mu)
Based on the equinoctial formulation with the acceleration in polar coordinates. These equations are singular when i = pi/2 and/or h = 0.
Form
 dEqDt = VarEqP( eq, aD, tol, mu )
Inputs
 eq                    Elements vector [a,P1,P2,Q1,Q2,l]
 aD                    Disturbance vector [r,theta,z]
 tol                   Tolerance for the Kepler equation solver
 mu                    Gravitational parameter
Outputs
 dEqDt                 Derivative to the elements
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, pp. 492-493.
References and(), Parameter(), and vector().
Referenced by VarEqT().
VarEqT()
function VarEqT (in eq, in aT, in tol, in mu)
Based on the equinoctial formulation with the acceleration in tangential coordinates. These equations are singular when i = pi/2 and/or h = 0.
See also
CT2REq and VarEqP.
Form
 dEqDt = VarEqT( eq, aT, tol, mu )
Inputs
 eq                    Elements vector [a,P1,P2,Q1,Q2,l]
 aT                    Tangential disturbance vector [tangent;normal;z]
                         (default is zeros)
 tol                   Tolerance for the Kepler equation solver (0.0001)
 mu                    Gravitational parameter (3.98600436e5)
Outputs
 dEqDt                 Derivative to the elements
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, pp. 492-493.
References and(), CT2REq(), VarEqP(), vector(), and zeros().
VarGausP()
function VarGausP (in el, in aD, in tol, in mu)
Based on the Gauss formulation with the acceleration in polar coordinates. These equations are singular when i = 0.
Form
 dElDt = VarGausP( el, aD, tol, mu )
Inputs
 el                    Elements vector [a,i,W,w,e,M]
 aD                    Disturbance vector [r,theta,z] (default is zeros)
 tol                   Tolerance for Kepler's equation solver (0.0001)
 mu                    Gravitational parameter (3.98600436e5;)
Outputs
 dElDt                 Derivative to the elements
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, pp. 484-490.
References vector(), and zeros().
VarGausT()
function VarGausT (in el, in aD, in tol, in mu)
 Computes the right hand side of the variational equations
 based on the Gauss formulation with the acceleration
 in tangential coordinates. These equations are singular
 when i = 0.
Form
 dElDt = VarGausT( el, aD, tol, mu )
Inputs
 el    (6,1) Elements vector [a,i,W,w,e,M]
 aD    (3,1) Disturbance vector [tangent,normal,z]
 tol   (1,1) Tolerance for Kepler's equation solver
 mu    (1,1) Gravitational parameter
Outputs
 dElDt  (6,1) Derivative to the elements
References: Battin, R.H., An Introduction to the Methods and Mathematics of Astrodynamics, AIAA, New York, 1987, pp. 484-490.
References and(), E2Nu(), M2EEl(), vector(), and zeros().
VDA()
function VDA (in d)
Form
 b = VDA( d )
Inputs
 d            (:)     Input data structure
                       d.rInjection         (1,:) Injection radius
                       d.planet             (1,:) Planet name
                       d.jD                 (1,1) Julian date
Outputs
 b             (:)     Data structure
                       .v    (3,1) Departure velocity
                       .dV   (1,1) Delta V
                       .el   (1,6) Elements
                       .
References and(), Date2JD(), JD2T(), Planets(), SolarSys(), vector(), and zeros().
VelAltFpaToAENu()
function VelAltFpaToAENu (in v, in h, in gamma, in mu, in R)
 Type VelAltFpaToAENu for a demo.
 mu is optional and 3.98600436e5 will be used if mu is not entered.
Form
 [a, e, nu] = VelAltFPAToAENu( v, h, gamma, mu )
Inputs
 v           (1,1)  Velocity
 h           (1,1)  Altitude
 gamma       (1,1)  Flight path angle (rad)
 mu          (1,1)  Gravitational parameter
Outputs
 a           (1,1)  Semi-major oxis
 e           (1,1)  Eccentricity
 nu          (1,1)  True anomaly
References Altitude(), and(), Demo(), and VelAltFpaToAENu().
Referenced by VelAltFpaToAENu().
VelAltFpaToHAE()
function VelAltFpaToHAE (in V, in h, in fpa, in h2, in mu, in R)
Given the initial velocity, altitude and flight path angle, compute the angular momentum, semi-major axis and eccentricity, as well as velocity and flight path angle at a second altitude.
Form
 [H,a,e,V2,fpa2] = VelAltFpaToHAE( V, h, fpa, h2, mu, R )
Inputs
 V             (1,1)    Velocity magnitude                       (km/s)
 h             (1,1)    Altitude                                 (km)
 fpa           (1,1)    Flight path angle                        (rad)
 h2            (1,1)    Second altitude to compute V2,fpa2 for   (rad)
 mu            (1,1)    Gravitational constant
 R             (1,1)    Planet equatorial radius
Outputs
 H             (1,1)    Angular momentum                 (km^2/s)
 a             (1,1)    Semi-major axis                  (km)
 e             (1,1)    Eccentricity
 V2            (1,1)    Velocity at altitude h2          (km/s)
 fpa2          (1,1)    Flight path angle at altitude h2 (rad)
References Altitude(), and(), Constant(), and VelAltFpaToHAE().
Referenced by VelAltFpaToHAE().
VEscape()
function VEscape (in r, in mu)
 Type VEscape for a demo of earth escape.
 Since version 1.
Form
 v = VEscape( r, mu )
Inputs
 r     (1,:) Radius
 mu (1,1) Gravitational parameter (default = 3.98600436e5 km^3/sec^2)
Outputs
 v  (1,:) Escape velocity for a hyperbola
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 48.
References Demo(), Plot2D(), and VEscape().
Referenced by EarthEscape(), PlotBPlane(), and VEscape().
VInf()
function VInf (in a, in mu)
Form
 v = VInf( a, mu )
Inputs
 a                    Semi-major axis (- for a hyperbola)
 mu                   Gravitational parameter (default = 3.98600436e5)
Outputs
 v                    Asymptotic velocity for a hyperbola
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 68.
References length(), and Plot2D().
VInfRPToRV()
function VInfRPToRV (in vInf, in rP, in f, in mu, in i, in lon, in arg)
Computes hyperbolic elements from velocity at infinity, radius at periapsis Inclination, argument of periapsis and longitude of the ascending node are optional. If true anomaly is not entered a default value of 90% of the max, as computed from eccentricity, will be used.
Type VInfRPToRV for a demo.
Form
 [r,v,el] = VInfRPToRV( vInf, rP, f, mu, i, lon, arg )
Inputs
 vInf  (1,1)   Velocity at infinity (km/s)
 rP    (1,1)   Radius of periapsis (km)
 f     (1,1)   True anomaly (rad)
 mu    (1,1)   Gravitational parameter (km^2/s^3) (Default earth)
 i     (1,1)   Inclination (rad)
 lon   (1,1)   Longitude of the ascending node (rad)
 arg   (1,1)   Argument of periapsis (rad)
Outputs
 r     (3,1)   Position (km)
 v     (3,1)   Velocity (km/s)
 el    (1,6)   [a i W w e M]
References abs(), and(), Constant(), DispWithTitle(), El2RV(), isempty(), Nu2M(), and VInfRPToRV().
Referenced by Simulate2DApproach(), and VInfRPToRV().
VOrbit()
function VOrbit (in r, in a, in mu)
If you don't enter a, you will get v for a circular orbit.
Either a or r can be scalars. It will plot v against whichever is a vector.
Form
 v = VOrbit( r, a, mu )
Inputs
 r           (1,:)   Radius
 a           (1,:)   Semi major axis (inf for parabola)
 mu          (1,1)   Gravitational parameter [default is Earth in km^3/sec^2]
Outputs
 v           (1,:)   Velocity
References: Bates, R.B. Fundamentals of Astrodynamics, pp. 28,34.
References VOrbit().
Referenced by Disturbances(), FlybyHyperbola(), GravityGradientStiffness(), LibrationFrequency(), LTPlaneChange(), OrbitLoweringManeuvers(), OrbMnvrCircularize(), OrbMnvrLowerApogee(), and VOrbit().
VPQ()
function VPQ (in e, in p, in nu, in mu)
 Since version 1.
Form
 vPQ = VPQ( e, p, nu, mu )
Inputs
 e                     Eccentricity
 p                     The parameter
 nu              (:)   True anomaly (rad)
 mu                    Gravitational parameter
Outputs
 vPQ             (3,:) Velocity
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 63-64.
References abs(), length(), Plot2D(), and zeros().
VR2AE()
function VR2AE (in v, in r, in mu)
Will generate a plot when called with no outputs. If the lengths of v and r are equal it will treat them sequentially so a and e are both (1,n).
Form
 [a, e] = VR2AE( v, r, mu )
Inputs
 v           (1,n)    Velocity
 r           (1,m)    Radius
 mu                   Gravitational parameter (default = 3.98600436e5)
Outputs
 a           (m,n)    Semi major axis
 e           (m,n)    Eccentricity
References and(), and vector().
WalkerConstellation()
function WalkerConstellation (in t, in p, in f, in inc, in sma, in doStar)
Generates a delta constellation be default, also called a rosette. For a star geometry, pass in true for the optional doStar parameter. The notation is i:n/p/f; f, the relative spacing, is an integer which can take any value from 0 to (p-1).
Real-life examples include the Galileo, a delta geometry, and Iridium, a star geometry. If there are no arguments the function creates a plot.
Form
 [elements, pl] = WalkerConstellation( t, p, f, inc, sma, doStar )
Inputs
 t         (1,1)    Total number of satellites
 p         (1,1)    Number of orbital planes
 f         (1,1)    Relative spacing between satellites in adjacent planes
 inc       (1,1)    Inclination (rad)
 sma       (1,1)    Semi-major axis (km)
 doStar    (1,1)    Optional. True for a star constellation.
Outputs
 elements   (6,t)    Kepler elements
 pl         (1,t)    Planet
Reference: Larson and Wertz, Space Mission Analysis and Design, second edition (1996), "Constellation Patterns", p. 191
References and(), AssignColors(), Demo(), isempty(), NewFig(), PlotPlanet(), RVFromKepler(), set(), WalkerConstellation(), Watermark(), and zeros().
Referenced by ConstellationMaxDistance(), and WalkerConstellation().
ZermeloAnalyticalCost()
function ZermeloAnalyticalCost (in theta, in x1, in y1)
This is a test case for TrajectoryOptimization.
Form
 c = ZermeloAnalyticalCost( theta, x1, y1 )
Inputs
 theta         (2,1) Control angles, [initial final]
 x1            (1,1) x-coordinate target
 y1            (1,1) y-coordinate target
Outputs
 c             (1,1) Cost
 xf            (2,1) Actual coordinates
Reference: Bryson and Ho, "Applied Optimal Control", Hemisphere Publishing, 1975.
Referenced by ZermeloAnalyticalLambda().
ZermeloAnalyticalLambda()
function ZermeloAnalyticalLambda (in x, in y, in v)
Finds the costates for the minimum cost solution by using fminsearch with the analytical trajectory function to find the initial and final control angles. This is a test case for TrajectoryOptimization.
Form
 [lambda,theta] = ZermeloAnalyticalLambda( x, y, v )
Inputs
 x            (1,1) x/h
 y            (1,1) y/h
 v            (1,1) Velocity
Outputs
 lambda       (2,1) Costates. [x;y]
 theta        (2,1) Control angles, [initial final]
Reference: Bryson, Ho, "Applied Optimal Control", Hemisphere Publishing.
See also
: ZermeloAnalyticalCost
References ZermeloAnalyticalCost().
ZermeloCost()
function ZermeloCost (in lambda, in d)
Models a constant velocity field. This integrates the equations over the time interval 0 to d.tEnd and finds the minimum distance from the target. The cost is just the magnitude of this minimum distance.
Returns a datastructure if no arguments are passed. This is a test case for TrajectoryOptimization.
Form
 [errMag, err, x, t] = ZermeloCost( lambda, d )
Inputs
 lambda         (2,1) Costates [x;y]
 d               (.)  Data structure
                      .rhsFun  (1,:) RHS Function
                      .h       (1,1) Characteristic dimension
                      .v       (1,1) Velocity
                      .x0      (2,1) Initial position
                      .xF      (2,1) Desired final position
                      .tEnd    (1,1) Final time from the optimizer
                      .data    (1,1) Integration tolerances
                                     .relTol  (1,1) ode113 relative tol
                                     .absTol  (1,1) ode113 absolute tol
                                     .maxStep (1,1) ode113 max step size
Outputs
 errMag        (1,:) Magnitude of the error
 err           (4,1) [costates;transversality condition]
 x             (4,:) [x;y;;u;v]
 t             (1,:) Time
Reference: Bryson, Ho, "Applied Optimal Control", Hemisphere Publishing.
References get(), length(), and RHSZermelo().