var group___cube_sat_demos =
[
    [ "AttitudeControl", "dir_21bd8c400523f79d26919f46cc2cf878.html", null ],
    [ "Demos", "dir_c2565d8821fedb154ee10557890872d6.html", null ],
    [ "Design", "dir_98b3dd9656f21a64d164f9301975dd83.html", null ],
    [ "MissionPlanning", "dir_538724511b69d48963d05231533475d3.html", null ],
    [ "Power", "dir_66d485d00fe1d4ad46236de53dc24bb8.html", null ],
    [ "RelativeOrbit", "dir_5921f6e6446d53faeabbdb86185f8fb1.html", null ],
    [ "Simulation", "dir_06c1c3c5f1a3006d01599d7476b9d63f.html", null ],
    [ "Thermal", "dir_01acf1dbdfb3bf5e235402b5588e4832.html", null ],
    [ "AnimateISSAndNanosat.m", "_animate_i_s_s_and_nanosat_8m.html", null ],
    [ "AttitudeProfileDemo.m", "_attitude_profile_demo_8m.html", null ],
    [ "BatterySizing.m", "_battery_sizing_8m.html", null ],
    [ "CubeSatFaceTemperaturesDemo.m", "_cube_sat_face_temperatures_demo_8m.html", null ],
    [ "CubeSatGGStabilized.m", "_cube_sat_g_g_stabilized_8m.html", null ],
    [ "CubeSatPowerDemo.m", "_cube_sat_power_demo_8m.html", null ],
    [ "CubeSatRWASimulation.m", "_cube_sat_r_w_a_simulation_8m.html", null ],
    [ "CubeSatSimulation.m", "_cube_sat_simulation_8m.html", null ],
    [ "CubeSatTiltedWings.m", "_cube_sat_tilted_wings_8m.html", null ],
    [ "DesignMagneticTorquer.m", "_design_magnetic_torquer_8m.html", null ],
    [ "DisturbancesDemo.m", "_disturbances_demo_8m.html", null ],
    [ "DisturbancesSolarWings.m", "_disturbances_solar_wings_8m.html", null ],
    [ "IsothermalCubeSatDemo.m", "_isothermal_cube_sat_demo_8m.html", null ],
    [ "MagneticControlDemo.m", "_magnetic_control_demo_8m.html", null ],
    [ "MagneticHysteresisControl.m", "_magnetic_hysteresis_control_8m.html", null ],
    [ "MagneticHysteresisOrbit.m", "_magnetic_hysteresis_orbit_8m.html", null ],
    [ "MomentumManagement.m", "_momentum_management_8m.html", null ],
    [ "NanoSatNearISS.m", "_nano_sat_near_i_s_s_8m.html", null ],
    [ "NanoSatSimulation.m", "_nano_sat_simulation_8m.html", null ],
    [ "OrbitAndSensorConeAnimation.m", "_orbit_and_sensor_cone_animation_8m.html", null ],
    [ "RadiationDisturbance.m", "_radiation_disturbance_8m.html", null ],
    [ "RepeatingGroundTrackDemo.m", "_repeating_ground_track_demo_8m.html", null ],
    [ "SpacecraftWithDamping.m", "_spacecraft_with_damping_8m.html", null ],
    [ "SunSynchPowerDemo.m", "_sun_synch_power_demo_8m.html", null ],
    [ "TubeSatSimulation.m", "_tube_sat_simulation_8m.html", null ],
    [ "TwoSpacecraftOrbitSimulation.m", "_two_spacecraft_orbit_simulation_8m.html", null ],
    [ "TwoSpacecraftSimpleOrbitSimulation.m", "_two_spacecraft_simple_orbit_simulation_8m.html", null ]
];