PSS MATLAB Toolboxes: SpacecraftEstimation Functions
SpacecraftEstimation Functions
SpacecraftEstimation Module
The SpacecraftEstimation module functions.
Description
Functions
function AdjustMeasSetForKnownMeas (in starID, in measPairs, in hitPairs)
Remove known measurements and solved for measurement pairs.
function ApplyThreshold (in pixels, in b, in T)
APPLYTHRESHOLD Apply a threshold to a pixelmap.
function AssessCatalog (in uStars)
Assess the global and local uniformity of a star catalog.
function AttProp (in w, in q, in dT)
Propagates a quaternion one step.
function BatchLSQOD (in x0G, in zM, in W, in d, in opts)
Perform batch least-squares method for orbit determination.
function Blobify (in pixels, in options, in doPlot)
Group adjacent pixels together into blobs.
function CCDNoise (in d)
Computes the CCD noise structure.
function CCDRes (in focalLength, in wPixel, in bits)
Computes the angular resolution of the CCD.
function CDKF45 (in d)
Continuous discrete iterated Kalman Filter.
function CentroidCOM (in pixels, in iCenter, in options)
Center of mass centroiding algorithm.
function CoarseCentroids (in pixels, in options, in doPlot)
Finds the centroids given a pixelmap.
function ComputePixelMapScale (in pixelWidth, in fOV)
Computes the pixel map conversion factor.
function ConvertPairs (in hitPairsOld)
Convert pairs from the old format to the new format.
function CreateKVector (in data)
Create the k vector from an array of data.
function DefaultData ()
Copyright (c) 2014, 2015, 2016, 2018 Princeton Satellite Systems, Inc.
function DeFocus (in w, in iAperture, in fStop, in focalLength, in d, in nMesh)
Spread of a point light source due to defocusing.
function DisplayCatalog (in catalog)
Display a star catalog.
function DisplayStars (in camera, in uStar, in ignoredArg)
Models a pinhole camera.
function DrawBlobs (in blobs, in pixels, in useLog)
Draw the blobs on top of the pixelmap using imagesc.
function DrawPixelmap (in pixels, in logscale)
Draw a pixelmap using imagesc.
function DrawStarImageCentroids (in pixels, in rCOM, in IDs, in logscale)
Create a figure with two subplots, for the pixels and the centroids.
function DSTM (in w, in dT)
Computes the discrete state transition matrix for a plant.
function DSTMQ (in w, in dT)
Computes the state transition matrix for the delta quaternion only.
function EarthBc (in jD)
Compute the barycentric position and velocity of the earth.
function EKFSSG (in phi, in q, in h, in r, in p, in dz, in s)
A standard discrete Kalman Filter.
function FImage (in x, in w)
Cost function for image matching.
function FitHist (in pixels)
Calculate a histogram of the pixels and fit a Gaussian to the mode.
function FitStarHist (in pixels, in x0, in doPlot)
Fit a 2D gaussian to a star image.
function FitStarMoffat (in pixels, in x0)
Fit a 2D Moffat PSF to a star image.
function FOrbitKFPointMass (in x, in ignoredArg, in d)
Computes the right-hand-side of the for a point mass gravity model.
function FOrbKF (in x, in t, in d)
Computes the right-hand-side of the orbit equations for OrbitKalmanFilter.
function FRBwRIG (in x, in t, in inr, in invInr, in torque, in uRIG, in nRWRIG, in nBRIG, in betaRIG)
Simulates a spacecraft with rate integrating gyros.
function GetStarPatch (in starCatalog, in rA, in dec, in rAWidth, in decWidth)
Generates a star catalog for a patch of sky.
function GPressure (in mFuel, in d)
Pressure given fuel mass for a blowdown propulsion system.
function GroundStation (in t, in omega, in rEF)
Generate the ECI coordinates of an Earth-fixed position at a given time.
function GStarUKFLin (in x, in d)
Linearized star measurement function for in the UKF.
function GStarUKFNL (in x, in mfd)
Nonlinear star measurement function for use in the UKF.
function GUKFOrbit (in x, in d)
A linear measurement.
function GyroKalmanFilter (in qMeas, in iMUAng, in d)
Gyro Kalman Filter.
function HRangeMeasurement (in x, in d)
Generate the range/range rate measurement matrix and the estimated measurement.
function HRangeRangeRate (in x, in d)
Measurement matrix for range and range rate.
function Int2VM (in i)
Converts intensity in watts/m^2 to apparent visual magnitude.
function IntGyroQuaternion (in ignoredArg, in x, in dT, in ignoredArg, in d)
Propagates the quaternion assuming constant rate.
function KFSunAndEarth2 (in p, in x, in d, in w)
A Kalman Filter using the sun vector and the earth vector for GEO.
function LatLonToNEU (in lat, in lon)
Transformation matrix from EF to NEU.
function LightDef (in p, in e, in q)
Compute gravitational light deflection.
function LoadCatalog (in name, in visualMagnitude, in minDeclination, in doPlot)
Load a catalog and reduce it based on visual magnitude.
function LoadILRSDataFromFRD (in filename)
Loads information from a CRD formatted file such as those used by the.
function LoadStarImage (in fileName, in fmt, in doFlip, in doPlot)
Load a star image with imread and generate metadata.
function MeasCamera (in x, in d)
Camera model which returns the centroid locations in the imaging plane.
function MeasDoris (in x, in d)
Range rate to an Earth target.
function MeasEarthChord (in x, in d)
Earth chord model for use with UKF.
function MeasEarthTarget (in x, in d)
Range and range rate to an Earth target.
function MeasGPS (in x, in d)
GPS range and range rate model for use with UKF.
function MeasNadirStar (in x, in d)
Nadir/star measurement for use with UKF.
function MeasOrbitState (in x, in d)
Full state measurement of an orbit.
function MeasRadar (in x, in d)
3D radar model for use with Kalman Filters.
function MeasRangeGroundStation (in x, in d)
Range and range rate to ground station.
function Measurements (in r, in sensorData, in qECIToB, in qBToS, in catalog, in fScale, in threshold)
Outputs the set of acceptable attitude measurements from vectors.
function MeasurementsSunMagUKF (in x, in d)
Outputs the set of acceptable attitude measurements from vectors.
function NASANavCatalog (in visualMagnitude, in fileName)
Generates a text file with stars above the cutoff magnitude.
function Occurences (in x)
Finds the number of unique numbers in x and how many times they appear.
function OrbitKFRHS (in x, in t, in d, in q)
Computes the right-hand-side of the orbit equations about a mass point.
function OrbitODGenObs (in x0, in d)
Generates a set of observations given an initial orbit state.
function PinholeCameraStruct (in pixels, in fOV)
Default data structure for a pinhole camera.
function PinholeStarCamera (in bCatalogToCamera, in camera, in catalog, in drawImage)
Models a pinhole camera for star identification.
function Pix2U (in p, in f, in offset)
Converts a pixel location into a unit vector.
function PixelMapCentroid (in pixelMap, in threshold, in show)
Finds the centroids of bright objects in the pixelMap.
function PixelsHist (in pixels)
Plot the distribution of pixels values assuming integer bits.
function PlotCentroids (in pixels, in xCOM)
PLOTCENTROIDS Plot star centroids on the image using pcolor.
function PostProcessCOM (in rCOM, in pixels, in doPlot)
Post process center-of-mass data.
function ProcessCatalog (in minInt, in fOV, in angularRes, in jD)
Load the Hipparcos catalog and create the near matrix.
function ProcessStarImage (in fileName, in fmt, in doFlip, in doPlot)
Load a star image and process it for centroids.
function QFromU (in uCatalog, in uMeas)
Computes an attitude quaternion given a set of measured and cataloged.
function RADecToPix (in x, in pixels, in fOV)
Convert right ascension and declination to pixels.
function RandSC (in n, in d, in mVM, in sVM)
Generates a random star catalog in star matrix format.
function RateFromDQ (in q, in qOld, in dT)
Computes angular rate from the equation mDot = m*Skew(w)
function RearrangeCatalog (in cat)
Convert the catalog data structure to a structure array.
function ReduceCatalog (in catalog, in angularResolution, in useTimeGUI)
REDUCECATALOG Reduce the catalog based on the angular resolution.
function RelativeStateFromPoints (in rW, in rF)
Finds the transformation matrix and relative position given at least.
function ReshapeCovariance (in p)
Reshape a covariance matrix from square to a column and back.
function RHSEarthOrbitUKF (in x, in ignoredArg, in d)
Point mass gravity model.
function RHSGyro (in x, in ignoredArg, in d)
RHSGyro models a rate gyro or rate integrating gyro (RIG)
function RHSIsothermalPState (in x, in t, in d)
Model a spacecraft as an isothermal radiator with an input state.
function RHSIsothermalUKF (in x, in t, in u)
Right-hand-side for an isothermal spacecraft model.
function RHSOrbitUKF (in x, in ignoredArg, in d)
Right-hand-side for a cartesian orbit.
function RHSPressure (in mFuel, in ignoredArg, in d)
Right-hand-side for a thruster based on the input pulsewidth.
function RHSQ (in qECIToBody, in t, in omega)
Quaternion derivative.
function RMABEst (in tMeas, in newMeas, in RMARate, in x, in r, in q, in dT)
Estimates gyro bias using a steady state Kalman Filter.
function RollYawEstimator (in x, in omega, in roll, in rollNoise, in dT)
Estimates roll and yaw given a roll measurement and body rates.
function RYGCAttDet (in angInc, in q, in dT, in b, in p, in Q, in r, in m, in mGyro)
An attitude determination system using roll/yaw gyrocompassing.
function SearchKVector (in k, in q, in m, in y1, in y2)
SEARCHKVECTOR Implement the range searching of data using a k vector.
function SelectMeasurementSet (in firstMeas, in nMeas, in measPairs, in hitPairs)
Select a subset of measurements.
function SeqBatchLSQOD (in dx0, in P0Inv, in x0, in zMNew, in WNew, in d, in opts)
Perform sequential batch least-squares method for orbit determination.
function Snapshots (in starDataMeas, in fileName, in starID, in starName, in xYPixels)
Make star ID snapshots and plot in a single figure.
function SqrFOV (in u, in x, in y)
Determines if a unit vector falls within a square FOV.
function SReduce (in rA0, in dec0, in pMRA, in pMDec, in parallax, in rV, in vSc, in jD)
Reduction of stellar coordinates to apparent coordinates.
function StarCentroidCOM (in p, in threshold, in nROI, in doPlot)
Finds the centroid given intensities on n pixels and their coordinates.
function StarDataFromStarMatrix (in starMatrix, in fieldOfView, in angularResolution)
Generates a star data structure from a star matrix.
function StarDataGeneration (in starCatalog, in fieldOfView, in angularResolution)
Generates a star data structure.
function StarDensity (in name, in visualMagnitude, in fOV)
Generates a star density plot.
function StarIDPyramid (in starMeas, in d, in options)
STARIDPYRAMID Identifies the best star matches using triads.
function StarIDTestCatalog (in n, in fOV, in nPixels, in thetaRes, in testData, in displayStars)
Generates a star catalog for testing the starid functions.
function StarImageHistogram (in pixels, in fname, in threshold)
Generate a figure with two subplots of the histogram.
function StarMeasurement (in r, in starDataMeas, in q, in qBodyToCamera, in starData, in fScale)
Computes the measurement matrix, measurements and noise.
function StarMeasurementUKF (in x, in d)
Computes the measurements for the UKF.
function StarMovie (in starDataMeas)
Make a star ID movie.
function StarPrediction (in camera, in uStar, in qBoresight)
Finds stars in the field of view.
function StarSensor (in qECIToB, in qBToS, in ignoredArg, in starMatrix, in fov, in fScale)
Computes the output of a star sensor.
function StellAbr (in u, in v, in abType)
Adjust the vector u for aberration.
function StellarAttDetEKF (in angInc, in q, in dT, in b, in p, in Q, in r, in qBToS, in starDataMeas, in starData, in fScale)
A stellar attitude determination system.
function StellarAttDetEKFNoGyros (in q, in qOld, in w, in dT, in p, in Q, in r, in qBToS, in starDataMeas, in starData, in fScale)
A stellar attitude determination system that does not use gyros.
function StellarAttDetUKF (in angInc, in q, in dT, in b, in qBToS, in starDataMeas, in starData, in fScale, in rStar, in ukf)
Stellar attitude determination using the Unscented Kalman Filter.
function StellarNavigation (in d, in range, in angleMeas, in kAngle, in rEst)
Demonstrate stellar navigation.
function STM (in w, in dT)
Quaternion state transition matrix.
function SubCatalog (in d, in k)
Create a sub catalog.
function SunBc (in jD)
Compute the barycentric position of the sun.
function SunEarthAttDet (in angInc, in q, in dT, in b, in p, in Q, in r, in qBToS, in sensorData, in catalog, in fScale)
An attitude determination system using a sun and earth vector.
function SunEarthMagAttDet (in angInc, in q, in b, in ukf, in r, in dT, in sensorData)
Attitude determination using a sun, earth and magnetic field vectors.
function SunMagAttDet (in x, in p, in r, in qBToS, in bMeas, in sensorData, in catalog, in fScale)
An attitude determination system using vector measurements.
function Swath (in ra, in dec, in VM, in VMMin, in decLim, in raLim)
Generates a swath catalog in star matrix format.
function TelescopeAperture (in catalog, in D, in eta)
Computes the number of stars that are visible for a given aperture.
function TelescopeUKF (in x, in d)
Telescope model for satelite tracking.
function UKFUpdateAtt (in d)
Unscented Kalman Filter measurement update step.
function VM2Electrons (in v, in c)
Converts apparent visual magnitude to electrons per second per mm^2.
function VM2PSFPeak (in vM, in pSF, in lambda, in a, in tau, in pSFData, in xLim, in yLim)
Finds the peak of the point spread function from visual magnitude.
function WorldToCamera (in q, in t, in xW, in f, in s, in o)
Finds the camera focal plane locations of world points.
function YawRollGyroCompassing (in x, in omega, in dT, in wo)
Implements yaw/roll gyrocompassing attitude estimation.
Function Documentation
AdjustMeasSetForKnownMeas()
function AdjustMeasSetForKnownMeas (in starID, in measPairs, in hitPairs)
Any nonzero entry in starID will be removed.
Form
 hitPairsSubSet = AdjustMeasSetForKnownMeas( starID, measPairs, hitPairs )
Inputs
 starID          (1,n)     List of solved stars. 0 indicates not foun d
 measPairs       (2,n)     Column is a measurement. Each row gives the meas id
 hitPairs        {n}       Dot product hits. Each two numbers gives a star pair
                           [star1_meas1 star2_meas1 star1_meas2 star2_meas2...]
Outputs
 hitPairsSubSet  {n}       Dot product hits. Each two numbers gives a star pair
                           [star1_meas1 star2_meas1 star1_meas2 star2_meas2...]
References and().
ApplyThreshold()
function ApplyThreshold (in pixels, in b, in T)
Applies a threshold and substracts the noise. If the threshold is not entered it will be computed from the pixel histogram using FitHist. The threshold will be 4 sigma above the mean.
Form
 [p,b,T] = ApplyThreshold( pixels, b, T )
 Inputs
 p  (m,n)   Modified pixelmap
 b  (1,1)   Center of noise Gaussian
 T  (1,1)   Threshold
 Outputs
 p  (m,n)   Thresholded pixelmap
 b  (1,1)   Noise
 T  (1,1)   Threshold
See also
FitHist
References and(), FitHist(), and isempty().
Referenced by CoarseCentroids().
AssessCatalog()
function AssessCatalog (in uStars)
The eigenvalues of u*u'/N will be each 1/3 if the stars are uniformly distributed. We calculate a single measure of global uniformity from these eigenvalues as sum(eigs * log(3*eigs). Phi should be small.
Type AssessCatalog for a demo of 3 3x3 identify matrices.
Inputs
 uStars    (3,:) Star unit vectors
Outputs
 phi       (1,1) Uniformity
 eigs      (3,1) Eigenvalues
References and().
AttProp()
function AttProp (in w, in q, in dT)
Assuming that the angular velocity is constant.
Form
 q = AttProp( w, q, dT )
Inputs
 w            (3,1)     Angular velocity
 q            (4,1)     Old quaternion
 dT           (1,1)     Time change
Outputs
 q            (4,1)     Updated quaternion
References quaternion(), QUnit(), and SkewSymm().
Referenced by GyroKalmanFilter(), IntGyroQuaternion(), StellarAttDetEKF(), StellarAttDetEKFNoGyros(), StellarAttDetUKF(), SunEarthAttDet(), and SunEarthMagAttDet().
BatchLSQOD()
function BatchLSQOD (in x0G, in zM, in W, in d, in opts)
Form
 [x0,P0,dx0] = BatchLSQOD( x0G, zM, W, d, opts );
Inputs
 x0G           (6,1)    Guess for epoch state x0, ECI position (km) and
                           velocity (km/s) vector.
 zM            (N,1)    Vector of measurements.
 W            (6N,6N)   Diagonal weighting matrix. Should be inverse of
                        measurement variances.
 d              (.)     Data structure for observation function. Fields:
                 .name    (:)      Name of observation function.
                 .mu      (1)      Value for gravitational parameter mu
                 .dT      (1)      Desired time step for orbit propagation [sec]
                 .obsTime (1,nObs) Observation times [sec] (MET)
                 .rGS     (1,nObs) ECI position of ground station at observation times
                 .vGS     (1,nObs) ECI position of ground station at observation times
                 .accTime (1,nC)   Time vector of applied accelerations [sec] (MET)
                 .acc     (1,nC)   Applied acceleration vector (3x1) [km/s/s]
 opts           (.)     Data structure of options for this algorithm.
 .tol     (1)      Tolerance for size of dx0 (differential corrector)
 .maxIter (1)      Maximum allowed iterations
Outputs
 x0            (6,1)  Solution for epoch state x0.
 P0            (6,6)  Covariance matrix.
 dx0           (6,1)  Last differential correction term.
References and(), DeleteSuffix(), Jacobian(), Mag(), and vector().
Blobify()
function Blobify (in pixels, in options, in doPlot)
A bounding box is stored along with the indices of the pixels in the blob.
Form
 blobs = Blobify(pixels,options,doPlot)
Inputs
 pixels  (n,m)   Thresholded pixelmap
 options  (.)    Options data structure
                 .minPix
 doPlot   (tf)   Boolean for creating a plot (false)
Outputs
 blobs   (:)    Array of blob structures
                .r0      (1,1) Bottom row
                .r1      (1,1) Top row
                .c0      (1,1) Left-hand column
                .c1      (1,1) Right-hand column
                .iPixels (1,:) Indices of all pixels in the blob
                .nPix    (1,1) Number of pixels in the blob
                .pMax    (1,1) Maximum value of blob pixels
                .iMax    (1,1) Index of blob maximum value
References Blobify(), DrawBlobs(), Initialize(), isempty(), length(), and Mag().
Referenced by Blobify(), CoarseCentroids(), and StarCentroidCOM().
CCDNoise()
function CCDNoise (in d)
Form
 sigma = CCDNoise( d )
Inputs
 d              (1,1)  Noise data structure
                       .c                    (1,1) Capacitance  (F)
                       .vD                   (1,1) Dark voltage (V)
                       .iDark                (1,1) Dark current (electrons)
                       .transferInefficiency (1,1) Transfer inefficiency
                       .nTransfers           (1,1) Number of transfers
                       .temperature          (1,1) Temperature
                       .doubleSampling       (1,1) 1 = true;
                       .electronsPerStep     (1,1) Number of electons per step
                       .eMax                 (1,1) Maximum number of electrons
Outputs
 sigma          (1,1)  Noise data structure
                       .total        (1,1) Total noise
                       .thermal      (1,1) Thermal noise
                       .transfer     (1,1) Transfer noise
                       .reset        (1,1) Reset noise
                       .signal       (1,1) Sigmal noise
                       .quantization (1,1) Quantization noise
CCDRes()
function CCDRes (in focalLength, in wPixel, in bits)
Assumes that the star is blurred so it fits within one pixel. This function ignores all real effects in a CCD such as dark current, blooming etc.
Form
 r = CCDRes( focalLength, wPixel, bits )
Inputs
 focalLength        (1,1) Focal length (*)
 wPixel             (1,1) Width of each cell
 bits               (1,1) Number of bits per pixel
 * indicates any unit of length.
Outputs
 r                  (1,1)   Resolution (rad)
References length().
CDKF45()
function CDKF45 (in d)
 The state and covariance matrices are numerically integrated.
 The model is of the form:
 dx/dt = f(x,t,u)
 y = h(x)*x + y0
 F(x,t,u) = df/dx
 fName is a RHS function for the state and covariance of the form
 xDot = fName( x, t, d.fData, q )
 hName is an observation partials function of the form
 [z, dhdx] = hName( x, t, d.hData )
 See OrbitKalmanFilter for a demo. There are m measurements with a total
 of j elements (the measurements do not need to be the same type or size).
Form
 d = CDKF45( d )
Inputs
 d            (:)     Data structure
                     .time             Current Julian date (days)
                     .dT               Integration time step (sec)
                     .secFromStart     Seconds from start (sec)
                     .nIterations      Number of iterations
                     .propagator       Choice of propagator, RK4 or RK45
                     .hLast            Last step for RK45
                     .tol              Tol for RK45
                     .x     (n,1)      State
                     .p     (n,n)      Covariance
                     .k     (n,j)      Gain matrix (calculated)
                     .q     (n,n)      Plant noise matrix
                     .r     {m}        Measurement noise matrix
                     .meas             Measurements
                          .z(j,1)      New measurement(s) in column vector
                     .fName            fRHS function name
                     .fData            fRHS data
                          .dFName         Derivative function
                          .nStates        Number of elements in the state vector
                          ...             (user defined)
                     .hName            h function name
                     .hData(m)         h data for measurements
                          ...             (user defined)
                     .xMeas (n,1)      State from measurements (calculated)
                     .pMeas (n,n)      Covariance from measurements (calculated)
Outputs
 d            (:)     Data structure
References: Gelb, A. Ed., Applied Optimal Estimation, MIT Press. p.188. Table 6.1-1. Also, pp. 190-191.
References and(), RHS(), RK4(), and RK45().
CentroidCOM()
function CentroidCOM (in pixels, in iCenter, in options)
Pixels below the noise threshold will not be included in the center of mass calculation. The noise will be subtracted from the remaining pixels. The threshold is generally some amount, i.e. 3-5 sigma, above the mean noise floor value.
If 'edge' is true, the pixels beyond the region of interest will be averaged to compute the 'edge noise'. This value will then be used for options.b. The maximum edge pixel will be used as the threshold.
If the pixelmap has already had noise removed, pass 'false' for the edge option and zero for the noise.
Form
 options    = CentroidCOM
 [x0,y0,iC] = CentroidCOM( pixels, iCenter, options )
Inputs
 pixels     (:,:)  Pixel map or array
 iCenter    (1,n)  Index of bright centers in array
 options     (.)   Options data
                     .b      (1,1)  Sky-background noise floor
                     .T      (1,1)  Sky-background threshold
                     .nROI   (1,1)  Size of region of interest (pixels)
                     .edge    (1)   Logical for computing edge noise
                     .minPix (1,1)  Minimum number of significant pixels
Outputs
 x0           (1,:)  x coordinates (column)
 y0           (1,:)  y coordinates (row)
 iC           (1,:)  Total intensity of the centroids
Reference: Liebe, C. "Accuracy Performance of Star Trackers - A Tutorial", IEEE Transactions on Aerospace and Electronic Systems. Vol. 38, N0. 2, April, 2002.
References and(), CentroidCOM(), Centroids(), isempty(), length(), and zeros().
Referenced by CentroidCOM(), and CoarseCentroids().
CoarseCentroids()
function CoarseCentroids (in pixels, in options, in doPlot)
This uses the center of mass method. The centroids are calculated assuming a lost-in-space condition. If the noise floor 'b' is empty, a noise floor will be calculated from the pixelmap histogram. To calculate an edge noise instead specify true for the edge flag.
x is defined in the column direction, y in the row direction. iC is in the same units as the intensity of the pixel map. With one output it will return [x0;y0;iC]
Type CoarseCentroids for a demo which will generate a small image using ImagerPSF, add noise with PoissonNoise, calculate the centroids and plot the results.
Form
 options = CoarseCentroids;
 [r0, iC, d] = CoarseCentroids( pixels, options, doPlot )
 [x0] = CoarseCentroids( pixels, options, doPlot )
Inputs
 pixels     (:,:)  Pixel map
 options     (.)   Options data
                     .edge    (1)  Logical for computing edge noise
                     .blobify (1)  Logical for using the Blobify algo
                     .T      (1,1) Threshold indicating a star is present
                     .b      (1,1) Sky-background noise floor
                     .nROI   (1,1) Size of region of interest (pixels)
                     .minPix (1,1) Minimum number of pixels for valid star
 doPlot     (1,1)  Specify true to generate the demo plots
                   -- Blobs if blobify was performed
                   -- Pixels above threshold
                   -- Pixelmap with centroids
Outputs
 r0           (2,:)  (x,y) centroid (column,row)
 iC           (1,:)  Total intensity of the centroids
 d             (.)   Algorithm data
                     .R  (1,1) RMS of sky-background noise
Reference: Liebe, C. "Accuracy Performance of Star Trackers - A Tutorial", IEEE Transactions on Aerospace and Electronic Systems. Vol. 38, N0. 2, April, 2002.
See also
FitHist, Blobify, CentroidCOM
References and(), ApplyThreshold(), Blobify(), CentroidCOM(), Centroids(), close(), CoarseCentroids(), Demo(), DrawBlobs(), FitHist(), ImagerPSF(), isempty(), length(), NewFig(), PlotCentroids(), PoissonNoise(), and set().
Referenced by CoarseCentroids(), and ProcessStarImage().
ComputePixelMapScale()
function ComputePixelMapScale (in pixelWidth, in fOV)
The width and field of view should both be the full width and angle of the chip, not the half-angle.
Form
 f = ComputePixelMapScale( pixelWidth, fOV )
Inputs
 pixelWidth    (1,1)   Width in pixels
 fOV           (1,1)   Field of view in same direction (rad)
Outputs
 f             (1,1)   Scale
References and().
ConvertPairs()
function ConvertPairs (in hitPairsOld)
Old format:
 hitPairs{k}{i} = [star1_pair1 star1_pair2 ... star1_pairN;...
 star2_pair1 star2_pair2 ... star2_pairN
To the new format:
 hitPairs = {[ star1_pair1 star2_pair1 star1_pair2 star2_pair2 ... ],... % meas pair 12
 [ star1_pair1 star2_pair1 star1_pair2 star2_pair2 ... ],... % meas pair 13
       ...
 [ star1_pair1 star2_pair1 star1_pair2 star2_pair2 ... ]}    % meas pair nm
Form
 [hitPairs = ConvertPairs( hitPairsOld )
Inputs
 hitPairsOld    {n,m}  Dot product hits. Each ell
Outputs
 hitPairs       {1,1}  Dot product hits. Each two numbers gives a star pair
                       [star1_meas1 star2_meas1 star1_meas2 star2_meas2...]
CreateKVector()
function CreateKVector (in data)
The k vector gives the number of elements in the sorted data that lie below a linear fit - k(i) gives the number of elements below z(i), where the line z is defined as
 z(i) = m*i + q
The k indices are for the sorted data. If the data is not sorted on input, it will be and the sorted data is returned in s.
Type CreateKVector for a demo (produces 2 figures).
Form
[k,m,q,s] = CreateKVector(data)
Inputs
 data       (1,:)   Array of data (star angles)
Outputs
 k          (1,:) Set of integer indices
 m          (1,1) Slope of linear fit
 q          (1,1) Intercept of linear fit
 s          (1,:) Sorted data
See also
: SearchKVector
References and(), CreateKVector(), Demo(), length(), NewFig(), SearchKVector(), vector(), Watermark(), and zeros().
Referenced by CreateKVector(), and SearchKVector().
DefaultData()
function DefaultData ()
 Finds the output of each pixel through numerical integration.
 The default plot output colors the pixels as a function of height.
 A built in 2D Gaussian function is available for demos or as a
 reasonable approximation to a real point spread function.
 The demo is for a 64 by 64 imaging chip. As you make the imager bigger
 it will slow down. For most studies you can use fewer than the full
 imager.
 funPSF must be of the form:
 funPSF(x,y,d)
 x and y are arrays passed by integral. They are two dimensional. Your
 function must return the same size array. funPSF gets passed the
 centroids and intensities of the point spread functions through the
 data structure d as d.rPSF and d.iPSF. You can attach any other
 data you want to d.funData as shown above.
 Type IntegratePSFs for a demo using RHSGaussianPSF.
Form
 d = IntegratePSFs       % default data structure
p = IntegratePSFs(d)
Inputs
 d      (.)     Data structure for imager
                 .funPSF    (*)  Pointer to point spread function RHS
                 .funData   (.)  Function data
                 .rPSF     (2,:) Location of PSF in imager frame (um)
                                 1st row (x): columnwise
                                 2nd row (y): rowwise
                 .iPSF     (1,:) Magnitude of each PSF
                 .m        (1,1) Rows
                 .n        (1,1) Columns
                 .xPixel   (1,1) X dimension of each pixel (um)
                 .yPixel   (1,1) Y dimension of each pixel (um)
 nPix  (1,1)   Number of pixels (radius) to integrate each PSF over when
                  computing individual pixels values. default: 6
Outputs
 p           (m,n)  Pixel output
 iC          (1,:)  Intensity of each centroid
All rights reserved.
Since version 2018.1 Demo Integrate over all p This code integrates each centroid over the full field of view center a box nPix around pixel Plot the image if no outputs are specified < IntegratePSFs>>DefaultData
DeFocus()
function DeFocus (in w, in iAperture, in fStop, in focalLength, in d, in nMesh)
Computes the spread of a point light source at infinity due to defocusing of the lens. The point is on the boresight of the lens. The function computes the total amount of light deposited in each cell of an nxn focal plane. This model assumes that the incoming radiation is uniformly distributed across the aperture. The integration function is very simple and requires a large mesh size for accuracy.
If no arguments are entered it will generate a mesh plot.
Form
 h = DeFocus( w, iAperture, fStop, focalLength, d, nMesh )
Inputs
 w                  (1,1) Width of each cell in fraction of focal length
 iAperture          (1,1) Intensity of light at the aperture (watts/*^2)
 fStop              (1,1)  F stop of the lens
 focalLength        (1,1)  Focal length (*)
 d                  (1,1) Distance from lens to focal plane in fraction
                          or multiples of focalLength
 nMesh              (1,1) The number of elements in the pixel mesh
                          (Default = 20)
 * indicates any unit of length.
Outputs
 h                  (n,n) Intensity profile (watts/*^2)
References and(), and length().
DisplayCatalog()
function DisplayCatalog (in catalog)
 Type DisplayCatalog to see Hipparcos
Form
 DisplayCatalog( catalog )
Inputs
 catalog         (:)    Catalog data structure
                        vM       (:,1) Visual magnitude
                        rA       (:,1) Right ascension
                        dec      (:,1) Declination
                        parallax (:,1) Parallax
                        rV       (:,1) Radial velocity
                        pMRA     (:,1) Proper motion right ascension
                        pMDec    (:,1) Proper motion declination
                        name1    (:,1) Name for the star
                        name2    (:,1) Name for the star
                        name3    (:,1) Name for the star
                        name4    {:}   Name for the star
Outputs
 None
References DisplayCatalog(), and Parallax().
Referenced by DisplayCatalog().
DisplayStars()
function DisplayStars (in camera, in uStar, in ignoredArg)
Projects the catalog into the camera frame.
The star unit vectors must be in the frame of the camera. If there are no outputs a figure is generated displaying the stars in the camera field of view with labels; a table of stars is also printed to the command line.
Type DisplayStars for a demo with random unit vectors.
Form
 [d, camera] = DisplayStars( camera, uStar, show )
Inputs
 camera               (.)      Camera data structure
                               .f       (1,1) Focal length in
                               .wX      (1,1) Width of sensing element in X
                               .wY      (1,1) Width of sensing element in Y
 uStar               (3,:)     The star unit vectors
 show                (1,1)     Any input shows the stars
Outputs
 d                    (.)      Output data structure
                               .star     (1,:)
                               .position (2,:) [xP;yP]
                               .pixel    (2,:) [pixelX;pixelY]
 camera               (.)      Camera data structure
                               .f       (1,1) Focal length in
                               .wX      (1,1) Width of sensing element in X
                               .wY      (1,1) Width of sensing element in Y
References abs(), Demo(), DisplayStars(), isempty(), length(), NewFig(), set(), U2Pix(), and Unit().
Referenced by DisplayStars().
DrawBlobs()
function DrawBlobs (in blobs, in pixels, in useLog)
A white box is drawn around the blob and the maximum pixel is marked with a red circle.
Form
 h = DrawBlobs(blobs,pixels,useLog)
Inputs
 blobs     (.)   Data structure
                 .c0 (1,1)
                 .c1 (1,1)
                 .r0 (1,1)
                 .r1 (1,1)
 pixels    (m,n) Pixels
 useLog    (1,1)    Boolean for log scale (false)
Outputs
 h         (1,1) Handle to figure
 Copyright (c) 2018 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since 2018.1
References and(), length(), set(), and Watermark().
Referenced by Blobify(), and CoarseCentroids().
DrawPixelmap()
function DrawPixelmap (in pixels, in logscale)
Form
 h = DrawPixelmap(pixels,logscale)
Inputs
 pixels    (:,:) Pixels
 logscale  (1,1) If true use logscale
Outputs
 h         (1,1) Handle
 Copyright (c) 2018 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since 2018.1
References DrawPixelmap().
Referenced by DrawPixelmap().
DrawStarImageCentroids()
function DrawStarImageCentroids (in pixels, in rCOM, in IDs, in logscale)
Uses imagesc with an option for log scaling to display the pixelmap. The centroids are plotted with markers.
The colormap is brightened by 0.5
Form
 [h,a] = DrawStarImageCentroids( pixels, rCOM, IDs, logscale )
Inputs
 pixels    (:,:) Pixel values
 rCOM      (:,:) Centers of mass of centroids
 IDs       (1,:) Ids of centroids
 logscale  (1,1) true is use logscale
Outputs
 h         (1,1) Figure handle
 a          (:)   Subplot handles
 Copyright (c) 2018 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since 2018.1
References and(), Centroids(), get(), isempty(), length(), and set().
DSTM()
function DSTM (in w, in dT)
 The plant equations are
 qDot   = -skew(w)*angle + b/2
 bDot   = zeros(3,3);
 This functions uses a 5th order expansion. For |w| = 1 this routine
 will be equivalent to C2DZOH to 1e-14 if dT < 0.03125 sec.
 Since version 3.
Form
 phi = DSTM( w, dT )
Inputs
 w            (3,1)     Rate vector
 dT           (1,1)     Time step
Outputs
 phi          (6,6)     State transition matrix
References C2DZOH(), Skew(), vector(), and zeros().
Referenced by GyroKalmanFilter(), StellarAttDetEKF(), StellarAttDetUKF(), SunEarthAttDet(), and SunEarthMagAttDet().
DSTMQ()
function DSTMQ (in w, in dT)
 Since version 3.
Form
 phi = DSTMQ( w, dT )
Inputs
 w            (3,1)     Nominal rate
 dT           (1,1)     Time step
Outputs
 phi          (3,3)     State transition matrix
References quaternion(), and SkewSymm().
Referenced by StellarAttDetEKFNoGyros().
EarthBc()
function EarthBc (in jD)
 Type EarthBc for a demo
 Since version 3.
Form
 [eB, eBDot] = EarthBc( jD )
Inputs
 jD              (1,:)    Julian date
Outputs
 eB              (3,:)    Barycentric position (aU)
 eBDot           (3,:)    Barycentric rate (aU/y)
References and(), CosD(), Demo(), EarthBc(), JD2000(), length(), Plot2D(), SinD(), and zeros().
Referenced by EarthBc(), ProcessCatalog(), and SReduce().
EKFSSG()
function EKFSSG (in phi, in q, in h, in r, in p, in dz, in s)
Automatically forces the covariance matrix to be symmetric. This does not include the state update.
Form
 [dx, p, k] = EKFSSG( phi, q, h, r, p, dz, s )
Inputs
 phi     (n,n)     The state transition matrix
 q       (n,n)     The state noise covariance matrix
 h       (m,n)     The measurement matrix = dh/dx
 r       (m,m)     The measurement covariance matrix
 p       (n,n)     The state covariance matrix
 dz      (m)       The measurement residuals
 s       (1,1)     Forgetting factor < 1
 (n is the # of states, m is the # of measurements)
Outputs
 dx      (n)       The state vector update
 p       (n,n)     The state covariance matrix
 k       (n,m)     The Kalman gain matrix
References vector().
Referenced by GyroKalmanFilter(), RYGCAttDet(), StellarAttDetEKF(), StellarAttDetEKFNoGyros(), SunEarthAttDet(), and SunMagAttDet().
FImage()
function FImage (in x, in w)
 Since version 8.
Form
 j = FImage( x, w )
Inputs
 x              (6,1)       State vector [dQ;rECI]
 w              (1,1)       Data structure
                            .image  (:,:,3) Image RGB
                            .g      (1,1)   Spacecraft data structure
                            .q0     (4,1)   Nominal quaternion
                            .tag    (1,1)   Tag to spacecamera function
                            .jD     (1,1)   Julian date
Outputs
 j              (1,1)     Cost
References abs(), get(), QMult(), QPose(), quaternion(), QUnit(), SpaceCamera(), and vector().
FitHist()
function FitHist (in pixels)
This approximates the sky background. Typically this should exit in 2-3 iterations.
Form
 [b,R,iter] = FitHist( pixels )
Inputs
 pixels (:,:) Pixels
Outputs
 b     (2,1) Noise center
 R     (1,1) Standard deviation
 iter  (1,1) Number of iterations in the Newton-Gauss method
See also
Jacobian
References abs(), and(), Jacobian(), and length().
Referenced by ApplyThreshold(), CoarseCentroids(), LoadStarImage(), and ProcessStarImage().
FitStarHist()
function FitStarHist (in pixels, in x0, in doPlot)
Calculate a histogram of the pixels and fit a 2D Gaussian. The height of the marginal distributions, that is the sum along each coordinate, is related to the height of the circular distribution by 1/sqrt(2*pi).
Form
 [xfit,sigma,height,iter] = FitStarHist( pixels, x0, doPlot )
Inputs
 pixels  (:,:) Pixels
 x0      (2,1) Center
 doPlot  (1,1) If true, plot
Outputs
 xfit    (2,1)  Gaussian center
 sigma   (2,1)  Standard deviation
 height  (2,1)  Height
 iter    (1,1)  Number of iterations in the Newton-Gauss method
 Copyright (c) 2018 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since 2018.1
References abs(), and(), DispWithTitle(), FitStarHist(), isempty(), length(), and zeros().
Referenced by FitStarHist().
FitStarMoffat()
function FitStarMoffat (in pixels, in x0)
Calculate a histogram of the pixels and fit a 2D Moffat. The height of the marginal distributions, that is the sum along each coordinate, is related to the height of the circular distribution by 1/sqrt(2*pi).
Form
 [xfit,sigma,height,iter] = FitStarMoffat( pixels, x0 )
Inputs
 pixels (:,:)  Pixels
 x0     (2,1)  Center
Outputs
 xfit   (2,1)  Gaussian center
 rho    (2,1)  Radial parameter
 height (2,1)  Height
 iter          Number of iterations in the Newton-Gauss method
 Copyright (c) 2018 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since 2018.1
References abs(), and(), DispWithTitle(), FitStarMoffat(), Jacobian(), length(), and zeros().
Referenced by FitStarMoffat().
FOrbitKFPointMass()
function FOrbitKFPointMass (in x, in ignoredArg, in d)
Form
 xDot = FOrbitKFPointMass( x, t, d )
Inputs
 x            (6,1)     The state vector [r;v]
 t            (1,1)     Time (sec)
 d            (1,1)     Data structure*
                        .mu   (1,1)   Gravitational potential
                        .aExt (3,1)   External acceleration, ex. thruster firings
Outputs
 xDot         (6,1)     The derivative of the state vector
References Mag(), and vector().
FOrbKF()
function FOrbKF (in x, in t, in d)
Low-fidelity mode computes about a mass point, high-fidelity mode uses nonlinear orbit equations, planetary perturbations and modeled forces. Includes an onboard clock model.
Form
 xDot = FOrbKF( x, t, d )
Inputs
 x            (n,1)     The state vector [r;v] or [r;v;b;f;...]
 t                      Time
 d            (1,1)     Data structure*
                        .highFidelity        (1,1)   High fidelity flag
                        .planetaryOn         (1,1)   Planetary accelerations flag
                        .forcesOn            (1,1)   Disturbance force modeling
                        .jD                  (1,1)   Julian date
                        .nZonal              (1,1)   Number of zonal harmonics
                        .nTess               (1,1)   Number of tesseral harmonics
                        .gravityModel        (1,1)   Gravity model struct
                        .aExt                (3,1)   External acceleration, ex. thruster firings
                        * Can be left empty for low-fidelity mode
Outputs
 xDot         (n,1)     The derivative of the state vector
References AGravityC(), and(), ECIToPlanet(), isempty(), length(), Mag(), OrbRate(), PlanetaryAccelerations(), RV2A(), vector(), and zeros().
FRBwRIG()
function FRBwRIG (in x, in t, in inr, in invInr, in torque, in uRIG, in nRWRIG, in nBRIG, in betaRIG)
See also
RIGModel and RBModel.
 Since version 3.
Form
 xDot = FRBwRIG( x, t, inr, invInr, torque, uRIG, nRWRIG, nBRIG, betaRIG )
Inputs
 x            (7+2n,1)  State vector with integrated angle and bias
                        [q(4); w(3); a(n); b(n)]
 t                      Time
 inr          (3,3)     Spacecraft inertia matrix
 invInr       (3,3)     Spacecraft inverse inertia matrix
 torque       (3,1)     Body torque
 uRIG         (3,n)     Unit vectors for rate integrating gyros
 nWBRIG       (n)       Random walk noise for RIGs
 nBRIG        (n)       Bias drift noise for RIGs
 betaRIG      (n)       Bias Correlation time constant for RIGs
Outputs
 xDot         (7+2n,1)  Derivative of the state vector
References and(), QIToBDot(), Random(), RBModel(), RIGModel(), Unit(), and vector().
GetStarPatch()
function GetStarPatch (in starCatalog, in rA, in dec, in rAWidth, in decWidth)
Form
 [patch, k, s] = GetStarPatch( starCatalog, rA, dec, rAWidth, decWidth )
Inputs
 starCatalog (1,1)        Star catalog data structure
 rA          (1,1)        Right ascension center (rad)
 dec         (1,1)        Declination center (rad)
 rAWidth     (1,1)        Width in right ascension about center (rad)
 decWidth    (1,1)        Width in declination about center (rad)
Outputs
 patch        (3,:)       [Intensity;rA;dec]
 k            (1,:)       Indexes
 s            (1,1)       Catalog data structure
References abs(), DeltCirc(), Demo(), GetStarPatch(), NewFig(), set(), and SubCatalog().
Referenced by GetStarPatch().
GPressure()
function GPressure (in mFuel, in d)
Form
 y = GXUKF( x, d )
Inputs
 mFuel     (1,1)  Mass of fuel (kg)
 d         (1,1)  Data structure
                  .mPress (1,1) Mass of pressurant (kg)
                  .rhoFuel (1,1) Fuel density (kg/m^3)
                  .vTank   (1,1) Volume of fuel (m^3)
                  .rPress  (1,1) Gas constant for the pressurant (m^2/sec^2)/deg-K
                  .T       (1,1) Fuel tank temperature (deg-K)
References BloDown(), and Pressure().
GroundStation()
function GroundStation (in t, in omega, in rEF)
 Type GroundStation for a demo.
 Since version 8.
 Usage:
 [r, v] = GroundStation( t, omega, rEF );
Inputs
 t          (1)   Mean sidereal time (sec)
 omega      (1)   Planet angular rate (rad/s)
 rEF       (3,1)  Earth-fixed position (km)
Outputs
 r         (3,1)  Earth-Centered Inertial position (km)
 v         (3,1)  Earth-Centered Inertial velocity (km/s)
References Cross(), Demo(), and GroundStation().
Referenced by GroundStation().
GStarUKFLin()
function GStarUKFLin (in x, in d)
 Since version 9.
Form
 y = GStarUKFLin( x, d )
Inputs
 x                 (6,1)   Attitude states
 d                 (n,6)   Linearized measurement matrix
Outputs
 y                 (n,1)    Struct of delta-Vs
References UKF().
GStarUKFNL()
function GStarUKFNL (in x, in mfd)
Form
 y = GStarUKFNL( x, mfd )
Inputs
 x   (6,1   Attitude states (sigma points)
 d   (.)    Data structure
         q (4,1) Quaternion
                            fScale: (1x1)
                            qBToS: [4x1 double]
                            starMeas: [3xn double]
                            starCat: [4x600 double]
                            starID: [1xn]
Outputs
 y                 (n,1)    Expected measurement
References length(), QForm(), QMult(), U2Pix(), and UKF().
GUKFOrbit()
function GUKFOrbit (in x, in d)
Returns y = x.
d is not used.
Form
 y = GUKFOrbit( x, d )
Inputs
 x         (:,1)  Input
Outputs
 y         (:,1)  Output
GyroKalmanFilter()
function GyroKalmanFilter (in qMeas, in iMUAng, in d)
The gyro model is built into the function.q
Form
 d = GyroKalmanFilter; % To get the data structure
 d = GyroKalmanFilter(qMeas,iMUAng,d)
Inputs
 qMeas   (4,1) Measured quaternion (ECI to Body)
 iMUAng  (3,1) IMU angles (rad)
 d        (.)  Data structure
               .p          (6,6) Covariance matrix
               .q          (6,6) Plant covariance matrix
               .iMUAngOld  (3,1) Previous IMU angle (rad)
               .r          (3,3) Measurement matrix
               .x          (6,1) State estimate
               .dT         (1,1) Time step (s)
               .qECIToBody (4,1) Estimated quaternion
               .b          (3,1) Estimated bias
Outputs
 d      (.)    Data structure
References AttProp(), DSTM(), EKFSSG(), get(), Gyro(), GyroKalmanFilter(), IMU(), QFromDQ(), QMult(), QPose(), quaternion(), and zeros().
Referenced by GyroKalmanFilter().
HRangeMeasurement()
function HRangeMeasurement (in x, in d)
 This gives the measurements in the form
 y = meas0 + H*dX
Form
 [meas0, h] = HRangeMeasurement( x, d )
Inputs
 x        (m,:)    State estimate [Position;Velocity;clock bias;clock drift;...]
 d        (n)      Measurement data structure
                    .rSourceECI  (3,1)  Position of source (ECI)
                    .vSourceECI  (3,1)  Velocity of source (ECI)
Outputs
 meas0    (2*n,1)  [range;range rate]
 h        (2*n,m)  H matrix [Hrange;HRange rate]
References and(), Dot(), length(), Mag(), and zeros().
HRangeRangeRate()
function HRangeRangeRate (in x, in d)
Form
 [m, h] = HRangeRangeRate( x, d )
Inputs
 x        (6,:)    State estimate [Position;Velocity]
Outputs
 m        (2,1)  [range;range rate]
 h        (2,6)  H matrix [Hrange;HRange rate]
References and(), and Mag().
Int2VM()
function Int2VM (in i)
 The apparent visual magnitude of the Sun is -26.85.
 Since version 3.
Form
 v = Int2VM( i )
Inputs
 i               (:)     Intensity (watts/m^2)
Outputs
 v               (:)     Visual magnitude
References: Berry, M. (1981). Principles of cosmology and gravitation. Cambridge University Press, Cambridge, England, p. 10.
References and().
IntGyroQuaternion()
function IntGyroQuaternion (in ignoredArg, in x, in dT, in ignoredArg, in d)
For use by UKF.
Form
 x = IntGyroQuaternion( fun, x, dT, t, d )
Inputs
 fun          (1,:)     Not used
 x            (3,1)     [delta Q; delta bias]
 dT           (1,1)     Time step
 t            (1,1)     Time (not used)
 d            (1,1)     Data structure
                        .q (4,1) Quaternion
                        .w (3,1) angular velocity
                        .b (3,1) bias error
Outputs
 x            (6,1)     [delta Q; delta bias]
References AttProp(), QMult(), QPose(), quaternion(), UKF(), and Unit().
KFSunAndEarth2()
function KFSunAndEarth2 (in p, in x, in d, in w)
 The sun sensor boresight is the positive x body axis. The attitude base is
 the output of a gyro. The attitude states are small angles.
See also
KFilter.
 The measurements are the Earth angle theta and sun vector uMeas.
Form
 [p, x] = KFSunAndEarth2( p, x, d, w )
Inputs
 p          (6,6) Covariance matrix
 x          (6,1) State vector [attitude;gyroBias;attitudeBias]
 d          (1,1) .q          (9,9) Plant noise
                  .r          (4,4) Measurement noise
                  .u          (3,1) Sun vector in the LVLH frame
                  .wO         (1,1) Orbit rate
                  .theta      (2,1) Earth sensor measurements
                  .noSun      (1,1) Cosine of half FOV angle
                  .a          (9,9) The state transition matrix
                  .b          (9,9) The input matrix
                  .uMeas      (3,1) Measured unit sun vector
                  .biasStates (1,1) If no, there are no estimates of biases
 w          (3,1) Gyro rates
Outputs
 p          (9,9) Covariance matrix
 x          (9,1) State vector [attitude;gyroBias;attitudeBias]
References and(), Gyro(), KFilter(), vector(), and zeros().
LatLonToNEU()
function LatLonToNEU (in lat, in lon)
Form
 mEFToNEU = LatLonToNEU( lat, lon )
Inputs
 lat       (1,1)  Latitude (rad)
 lon       (1,1)  Longitude (rad)
Outputs
 mEFToNEU   (3,3)   Transforms from earth fixed to north east up
LightDef()
function LightDef (in p, in e, in q)
 Since version 3.
Form
 p1 = LightDef( p, e, q )
Inputs
 p       (3,1) Vector from observing body to observed body
 e       (3,1) Vector from sun
 q       (3,1) Vector to observed body from sun
Outputs
 p1      (3,1) Corrected p
References: Siedelmann, P., ed. (1992). Explanatory Supplement to the Astronomical Almanac, University Science Books, Mill Valley, CA, 136-137.
References Mag().
Referenced by SReduce().
LoadCatalog()
function LoadCatalog (in name, in visualMagnitude, in minDeclination, in doPlot)
Includes a demo of the Hipparcos catalog. The figure will be generated if called with no outputs or if the doPlot flag is true.
Form
 catalog = LoadCatalog( name, visualMagnitude, minDeclination, doPlot )
Inputs
 name            (1,:)  Catalog name 'Hipparcos', 'FK5', 'FK5 Polar',
                        or 'FK5 Short'
 visualMagnitude (1,:)  Visual magnitude or 'all', default 6
 minDeclination  (1,1)  Minimum declination (rad)
 doPlot          (1,1)  Create the figure
Outputs
 catalog         (.)    Catalog data structure
                        vM       (:,1) Visual magnitude
                        rA       (:,1) Right ascension
                        dec      (:,1) Declination
                        parallax (:,1) Parallax (mas)
                        rV       (:,1) Radial velocity
                        pMRA     (:,1) Proper motion right ascension (mas/yr)
                        pMDec    (:,1) Proper motion declination (mas/yr)
                        name1    (:,1) Name for the star
                        name2    (:,1) Name for the star
                        name3    (:,1) Name for the star
                        name4    [:]   Index for the star
References abs(), and(), isempty(), length(), LoadCatalog(), LoadFK5(), NewFig(), Parallax(), set(), and TitleS().
Referenced by LoadCatalog(), NASANavCatalog(), NavigationCamera(), NavigationCameraSunStar(), NavTargetTrackingLunar(), NavTargetTrackingPlanetary(), OpticalNavPlanetStarNoiseMatrix(), PinholeStarCamera(), PolarStars(), ProcessCatalog(), RearrangeCatalog(), ReduceCatalog(), SpaceCamera(), StarDataGeneration(), StarDensity(), StarIDTestCatalog(), StarTexture(), and TelescopeAperture().
LoadILRSDataFromFRD()
function LoadILRSDataFromFRD (in filename)
 ILRS for laser ranging file the the extension '.frd'.  The data file is
parsed, and the info is stored in the structure 'd'.
Type LoadILRSDataFromFRD for a demo.
Form
 d = LoadILRSDataFromFRD( filename )
Inputs
 filename  (1,1)  path to a .frd file
Outputs
 d         (:)    data structure containing the information stored in
                  'filename'
References: Pearlman, M.R., Degnan, J.J., and Bosworth, J.M., "The International Laser Ranging Service", Advances in Space Research, Vol. 30, No. 2, pp. 135-143, July 2002, DOI:10.1016/S0273-1177(02)00277-6
References and(), Demo(), and LoadILRSDataFromFRD().
Referenced by LoadILRSDataFromFRD().
LoadStarImage()
function LoadStarImage (in fileName, in fmt, in doFlip, in doPlot)
Example: LoadStarImage('test.fits', [], [], true)
Form
 [pixels,d] = LoadStarImage( fileName, fmt, doFlip, doPlot )
Inputs
 fileName   (1,:)   Path to file
 fmt        (1,:)   Image format (gif, tiff, fits), leave empty to use extension
 doFlip    (1,1)    Whether to invert image (fliplr)
 doPlot    (1,1)    Whether to create figures (default: false)
 d         (.)   Metadata
                 .pMin (1,1)    Minimum pixel value
                 .pMax (1,1)    Maximum pixel value
                 .flip (1,1)     Whether image was flipped
Outputs
 pixels     (:,:) Pixels
 d         (.)    Metadata
 Copyright (c) 2018 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since 2018.1
References and(), FitHist(), FocalPlaneImage(), and isempty().
Referenced by PostProcessCOM(), and ProcessStarImage().
MeasCamera()
function MeasCamera (in x, in d)
 The boresight is along the camera z-axis. This function uses a
 pinhole camera model. Another assumption is that the flat plate
 representing the target is always normal to the camera boresight.
 v, visibility, includes orbital effects and camera imager size
 limitations. y always returns all measurements but v tells you if
 they are valid. e is the flux which can be used to determine the
 signal to noise ratio. The noise value is the total centroid noise
 which is from 0.005 to 0.1 pixel.
 This function uses the PinholeCamera, SatelliteVisibility and
 SolarFluxFromPlateECI functions.
 Since version 2014.1
Form
 [y, e, v] = MeasCamera( x, d )
Inputs
 x         (:,1)  State vector
 d         (1,1)  Camera data structure
                 .r              (3,1) ECI camera position
                 .kState         (2,:) Indices to target states
                 .noise         (1,1) 1 sigma centroid noise
                 .qECIToBody    (4,1) Quaternion from ECI to body
                 .qBodyToCamera (4,1) Quaternion from body to camera
                 .rho            (1,:) Object reflectivity
                 .area           (1,:) Object area (m^2)
                 .jD             (1,1) Julian date
                 .widthImager    (1,1) Imaging chip width (mm)
                 .horizonAngle   (1,1) Horizon angle for acquisition
Outputs
 y          (2,:) Measurements [x;y]
 e          (1,:) Flux
 v          (1,:) 1 if the target is visible
References and(), Constant(), Measurements(), PinholeCamera(), QForm(), QMult(), QTForm(), SatelliteVisibility(), SolarFluxFromPlateECI(), Unit(), vector(), and zeros().
MeasDoris()
function MeasDoris (in x, in d)
Includes Earth rotational rate. This is a simple model of a Doris sensor. It measures Doppler shift, producing range rate. It is designed for use by UKFUpdate.
Form
 [y, rT] = MeasDoris( x, d )
Inputs
 x   (3,1)  Position of spacecraft (km)
 d   (.)   Data structure
           .jD0          (1,1) Julian date
           .omegaSkew     (3,3) Skew symmetric matrix for earth rate
           .t               (1,1) Time (s)
           .rEF          (3,1) Earth fixed target location
           .noise1Sigma  (1,1) range rate 1 sigma (km,km/s)
Outputs
 y  (1,1) range rate
 rT     (3,1) Target on Earth in ECI frame (km)
References Date2JD(), DefaultDataStructure(), EarthRot(), JD2T(), Mag(), MeasDoris(), Skew(), UKFUpdate(), Unit(), and zeros().
Referenced by MeasDoris().
MeasEarthChord()
function MeasEarthChord (in x, in d)
 If d.angleNoise is entered it will add Gaussian noise to the angle
 measurement. If d.altNoise is added it will add altitude noise. This
 gets processed through an arc sine so is no longer Gaussian.
 Since version 2014.1
Form
 y = MeasEarthChord( x, d )
Inputs
 x  (6,1)   State [r;v]
 d  (1,1)   Filter data structure
             .cO2Altitude    (1,1) Altitude of the CO2 layer (km)
             .angleNoise     (1,1) 1 sigma angle noise
             .altNoise       (1,1) 1 sigma altitude noise
             .rE             (1,1) Earth radius
Outputs
 y  (1,1)   Chordwidth (rad)
References abs(), Altitude(), and UKF().
MeasEarthTarget()
function MeasEarthTarget (in x, in d)
Includes Earth rotational rate.
Form
 [y, rT] = MeasEarthTarget( x, d )
Inputs
 x   (3,1)  Position of spacecraft (km)
 d   (.)   Data structure
           .jD0          (1,1) Julian date
           .omegaSkew     (3,3) Skew symmetric matrix for earth rate
           .t               (1,1) Time (s)
           .rEF          (3,1) Earth fixed target location
           .noise1Sigma  (2,1) [range;range rate] 1 sigma (km,km/s)
Outputs
 y  (2,1) [range;range rate]
 rT     (3,1) Target on Earth in ECI frame (km)
References and(), Date2JD(), DefaultDataStructure(), EarthRot(), JD2T(), Mag(), Skew(), Unit(), and zeros().
MeasGPS()
function MeasGPS (in x, in d)
If d.noise is entered it will add Gaussian noise to the values.
Form
 y = MeasGPS( x, d )
Inputs
 x   (6,1)   State [r;v]
 d   (1,1)   Filter data structure
             .jD     (1,1) Julian date
             .jD0    (1,1) Initial Julian Date
             .noise (2,1) [range;range rate] noise
             .rE     (1,1) Earth radius
             .hMin   (1,1) Minimum altitude for GPS visibility
Outputs
 y  (2*n,1)   GPS range and range rate
References and(), Constant(), CP2I(), Cross(), Date2JD(), EarthRot(), GPSSatellite(), IntersectPlanet(), JD2T(), length(), Mag(), MeasGPS(), OrbRate(), UKF(), and zeros().
Referenced by MeasGPS().
MeasNadirStar()
function MeasNadirStar (in x, in d)
 If d.angleNoise is entered it will add Gaussian noise to the angle
 measurement.
 Since version 2014.1
Form
 y = MeasNadirStar( x, d )
Inputs
 x  (6,1)   ECI state [r;v]
 d  (1,1)   Filter data structure
             .uStar          (3,n) ECI star vector
             .angleNoise     (1,1) 1 sigma angle noise
Outputs
 y  (n,1)   Star angle (rad)
References abs(), Dot(), Nadir(), UKF(), Unit(), and vector().
MeasOrbitState()
function MeasOrbitState (in x, in d)
Form
 y = MeasOrbitState ( x, d )
Inputs
 x            (6,1)    State [x;y;z;vX;vY;vZ]
 sensorData   (.)      Structurenoise1Sigma
                       .noise1Sigma (6,1) State noise
Outputs
 x            (6,1)    State measurements  [x;y;z;vX;vY;vZ]
MeasRadar()
function MeasRadar (in x, in d)
 Since version 2014.1
Form
 [y, sN, v] = MeasRadar( x, d )
Inputs
 x         (:,1)  Target ECI state [r;v] (km,km/s)
 d         (1,1)  Radar data structure
                 .lambda         (1,1) Wavelength (m)
                 .noise         (4,1) 1 sigma noise [range;rangeRate;
                                       azimuth;elevation]
                 .qECIToBody    (4,1) Quaternion from ECI to body
                 .qBodyToRadar  (4,1) Quaternion from body to radar
                 .xRadar         (6,1) Radar ECI state  [r;v] (km,km/s)
                 .horizonAngle   (1,1) Horizon angle for acquisition
                 .sigma          (1,:) Radar crosssection
Outputs
 y          (4,1) Measurements [range;rangeRate;azimuth;elevation]
 sN         (1,1) Signal to noise ratio (dB)
 v          (1,1) 1 if sensor is visible.
References Mag(), Measurements(), QForm(), QMult(), RadarSN(), SatelliteVisibility(), Unit(), Wavelength(), and zeros().
MeasRangeGroundStation()
function MeasRangeGroundStation (in x, in d)
 It just uses earth rotation for the EF to ECI conversion. d.rRef
 is for use with non-dimensional states. Set it to 1 for dimensional
 states.
 If d.noise is entered it will add Gaussian noise to the measurements.
See also
EarthRot.
Form
 y = MeasRangeGroundStation( x, d )
Inputs
 x  (6,1)   State [r;v]
 d  (1,1)   Filter data structure
             .rGSEF  (3,1) Ground station position
             .noise (2,1) [range;range rate]
             .jD     (1,1) Julian Date
             .rRef   (1,1) Reference length
Outputs
 y  (2,1)   [range;range rate]
References and(), Cross(), EarthRot(), EarthRte(), JD2000(), JD2T(), length(), and Mag().
Measurements()
function Measurements (in r, in sensorData, in qECIToB, in qBToS, in catalog, in fScale, in threshold)
Computes the measurement matrix, measurements and noise matrix given a pixel map from the unit vector measurements. Will update q if it has three valid vectors and the attitude error is large threshold prevents bad measurement estimates if the attitude estimate is greatly different from the actual attitude.
Form
 [h, dz, R] = Measurements( r, sensorData, qECIToB, qBToS, catalog, fScale, threshold )
Inputs
 r            (1,1)    Measurement noise
 sensorData   (:)      Structure
                        .xy    Pixel values in the xy focal plane
                        .valid 1 = valid measurement
 qECIToB      (4,1)    Quaternion from ECI to body axes
 qBToS        (4,1)    Quaternion from body to sensor axes
 catalog      (3,:)    Target catalog unit vectors
 fScale       (1,1)    Sensor scale factor
 threshold    (1,1)    Threshold for sensor incorporation
Outputs
 h            (n,6)    Linearized measurement matrix
 dz           (n)      The measurement residuals
 R            (n,n)    Measurement noise
 qECIToB      (4,1)    Quaternion from ECI to body axes
References abs(), and(), Initialize(), length(), Q2Mat(), QForm(), QMult(), set(), Skew(), U2Pix(), vector(), and zeros().
Referenced by ADComp(), ADCull(), AutoRadar(), AutoRadarUKF(), CDKF(), DCMotorParitySpace(), DetectionFilter(), DetectionFilterSimulation(), DetectionFilterUnnormalized(), KSmooth(), MeasCamera(), MeasEarthSensor(), MeasMagnetometerEarth(), MeasRadar(), MeasRateGyro(), MeasRateIntegratingGyro(), MeasRelativePosition(), MeasStarTracker(), MeasState(), MeasSunSensorAnalog(), MeasSunSensorDigital(), MeasurementsSunMagUKF(), MHTTrkToB(), OpticalNavPlanetStar(), Outliers(), Residual(), StarMeasurementUKF(), SunEarthAttDet(), UKF(), UKFP(), UKUDF(), and ZCull().
MeasurementsSunMagUKF()
function MeasurementsSunMagUKF (in x, in d)
Computes measurements given a pixel map from the unit vector measurements. This function is for use with the UKF as it does not return a linearized measurement matrix.
Form
 y = MeasurementsSunMagUKF( x, d )
Inputs
 x   (6,1)  [dQ;b]
 d   (.)    Data structure
Outputs
 y  (:,1)    Measurements
References and(), BDipole(), length(), Measurements(), QForm(), QFromDQ(), QMult(), quaternion(), set(), U2AzEl(), U2Pix(), UKF(), Unit(), and vector().
Referenced by SunEarthMagAttDet().
NASANavCatalog()
function NASANavCatalog (in visualMagnitude, in fileName)
Store the following fields:
 [HIP vM rA dec parallax rV pMRA pMDec]
The default file name is NASANavStarCatalog.txt; the file will be stored in the same directory as this function.
Form
 NASANavCatalog( visualMagnitude, fileName )
Inputs
 visualMagnitude (1,1)  Visual magnitude or 'all'
 fileName        ('')   Name of output file
Outputs
 None
References isempty(), and LoadCatalog().
Occurences()
function Occurences (in x)
Form
 [y, n] = Occurences( x )
Inputs
 x              (n,m)  List
Outputs
 y              (1,:)  Unique numbers
 n              (1,:)  Number of occurrences
References and(), isempty(), and length().
OrbitKFRHS()
function OrbitKFRHS (in x, in t, in d, in q)
The derivative function d.dFName must be of the form fun(x, t, d) where d may be a data structure.
Form
 xDot = OrbitKFRHS( x, t, d, q )
Inputs
 x (:,1)     The state vector [x;p]
 t (1,1)     Time
 d (1,1)     Data structure
            .dFName     (:,1)   Derivative function
            .nStates    (1,1)   Number of elements in the state vector
            ...                 Data for derivative function
 q           Plant noise matrix
Outputs
 x  (:,1)     The state vector derivative[xDot;pDot]
References Jacobian(), ReshapeCovariance(), and vector().
OrbitODGenObs()
function OrbitODGenObs (in x0, in d)
 Since version 8.
Form
 [z,xS,time] = OrbitODGenObs( x0, d );
Inputs
 x0            (6,1)    Initial orbit state (ECI position; ECI velocity)
 d              (.)     Data structure for observation function. Fields:
                 .name    (:)      Name of observation function.
                 .mu      (1)      Value for gravitational parameter mu
                 .dT      (1)      Desired time step for prop. [sec]
                 .obsTime (1,nObs) Observation times [sec] (MET)
                 .rGS     (1,nObs) ECI pos. of grnd. stn. at obs. times
                 .vGS     (1,nObs) ECI pos. of grnd. stn. at obs. times
                 .accTime (1,nC)   Times of applied accels. [sec] (MET)
                 .acc     (3,nC)   Applied accel. vector (3x1) [km/s/s]
Outputs
 z             (M,1)  Vector of range and range rate observations
                        (M = 2*nObs)
 xS            (6,N)  Predicted time history of orbit state at
                        all obs. times and control times (N = nC+nObs)
 time          (1,N)  Time vector associated with xS history.
References and(), length(), RK4(), set(), vector(), and zeros().
PinholeCameraStruct()
function PinholeCameraStruct (in pixels, in fOV)
Form
 camera = PinholeCameraStruct( pixels, fOV )
Inputs
 pixels   (1,1)    Number of pixels in the sensor
 fOV      (1,1)    Field of view (rad)
Outputs
 camera    (.)    Camera data structure
                    .fScale  (1,1) Pixel conversion factor
                    .wX      (1,1) Width of sensing element in X
                    .wY      (1,1) Width of sensing element in Y
                    .gain    (1,1) Camera gain
                    .noise   (1,1) Include the noise model
                    .sigmaXY (1,1) Position noise
                    .sigmaI  (1,1) Intensity noise
                    .sigmaFS (1,1) False star noise
References isempty(), and length().
Referenced by NavigationCamera(), NavigationCameraSunStar(), and PinholeStarCamera().
PinholeStarCamera()
function PinholeStarCamera (in bCatalogToCamera, in camera, in catalog, in drawImage)
 Projects the catalog into the camera frame. This model does not
 account for lense effects. The function includes a noise model that
 accounts for random intensity variations, random centroid shifts and
 false stars.
Form
 [starMeasurement, camera] = PinholeStarCamera( bCatalogToCamera, camera,
 catalog, drawImage )
Inputs
 bCatalogToCamera    (3,3)    Transforms from the catalog frame to the
                              camera frame. The boresight is along +Z.
 camera               (.)     Camera data structure
                              .fScale  (1,1) Pixel conversion
                              .wX      (1,1) Width of sensing element in X
                              .wY      (1,1) Width of sensing element in Y
                              .gain    (1,1) Camera gain
                              .noise   (1,1) Include the noise model (T/F)
                              .sigmaXY (1,1) Position noise (pixels)
                              .sigmaI  (1,1) Intensity noise (after gain)
                              .sigmaFS (1,1) False star noise
                              .fSAtEnd (1,1) 1 if false stars are at the end of the measurements
 catalog             (1,1)    Star catalog data structure or name
 drawImage           (:)      If entered will draw a star image
Outputs
 starMeasurement      (.)    Data structure
                              .pixelLocation  (2,m) Coordinates of centroid [x;y]
                              .pixelIntensity (1,m) Intensity of each object
                              .star           (1,m) Star indices
                              .uStar          (3,m) Star unit vectors
 camera               (.)    Camera data structure
See also
: U2Pix, VM2Int, PinholeCameraStruct, PinholeCameraDemo
References abs(), and(), Coordinates(), isempty(), length(), LoadCatalog(), NewFig(), PinholeCameraStruct(), RaDec2U(), set(), U2Pix(), VM2Int(), and zeros().
Referenced by CameraDatabase(), and NavigationCameraSunStar().
Pix2U()
function Pix2U (in p, in f, in offset)
 Works for any f which is normally the focal length in the same units as
 p. The offset allows you to specify an origin for the pixel map other
 than the center. For example, to transform locations measured from the
 lower left of the pixelmap, input the halfwidth of the frame.
 Since version 3.
Form
 u = Pix2U( p, f, offset )
Inputs
 p            (2,:)   [x;y] (a column vector)
 f   (1,1) or (2,1)   Scale factor (focal length in units of pixels)
 offset       (1,2)   Pixel offset in [x y]
Outputs
 u            (3,:)   Unit vector
References length(), Unit(), and vector().
Referenced by StarIDPyramid(), and U2Pix().
PixelMapCentroid()
function PixelMapCentroid (in pixelMap, in threshold, in show)
 If the name 'demo' is given it will perform a demo with the image
 StarFieldDemo.jpg
Form
 starMeasurement = PixelMapCentroid( pixelMap, threshold, show )
Inputs
 pixelMap        (1,:)    PixelMap file name or 'demo'
                          If empty will open a dialog box
 threshold       (1,1)    Fraction of maximum value, default is 0.97
 show                     If entered, will show pictures
Outputs
 starMeasurement (1,1)    Data structure
                           .pixelLocation  (2,m) Coordinates of centroid [x;y]
                           .intensity      (1,m) Intensity of each object
References Coordinates(), get(), isempty(), NewFig(), PixelMapCentroid(), set(), TitleS(), XLabelS(), YLabelS(), and zeros().
Referenced by PixelMapCentroid().
PixelsHist()
function PixelsHist (in pixels)
Form
 PixelsHist( pixels )
Inputs
 pixels (:,:) Pixel values
Outputs
 None
 Copyright (c) 2018 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since 2018.1
References length(), and zeros().
PlotCentroids()
function PlotCentroids (in pixels, in xCOM)
Form
 fig = PlotCentroids( pixels, xCOM )
Inputs
 pixels (:,:)   Pixel values
 xCOM    (4,1) Center of mass values
Outputs
 None
 Copyright (c) 2018 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since 2018.1
References NewFig(), and set().
Referenced by CoarseCentroids().
PostProcessCOM()
function PostProcessCOM (in rCOM, in pixels, in doPlot)
[rCOM,d] = PostProcessCOM(rCOM, pixels, doPlot)
x is along the column dimension and y along the row dimension.
Inputs
 rCOM   (3,:)   Centroids with intensity [x;y;i]
 pixels (m,n)   Pixelmap
Outputs
 rCOM    (3,:)   Reduced centroids
 d        (.)    Metadata
 .iMax    (1,1) Index of blob maximum value
 Copyright (c) 2018 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since version 2018.1
References and(), Centroids(), LoadStarImage(), PostProcessCOM(), and StarCentroidCOM().
Referenced by PostProcessCOM(), and ProcessStarImage().
ProcessCatalog()
function ProcessCatalog (in minInt, in fOV, in angularRes, in jD)
The catalog is limited by the specified minimum visual magnitude. A magnitude of 5 gives about 1500 stars and a magnitude of 6.1 gives about 5000 stars. Accounts for the stellar motion if a Julian date is entered.
Form
 [d,catalog,fullCatalog] = ProcessCatalog( minInt, fOV, angularRes, jD )
Inputs
 minInt      (1,1) Minimum intensity
 fOV         (1,1) Field of view (rad)
 angularRes  (1,1) Angular resolution (rad)
 jD          (1,1) Julian date
Outputs
 d       (.)    Struct
             .starMatrix
             .fieldOfView
             .starCatalog
             .nearMatrix
             .nearSlope
             .nearQ
catalog  (:)     Struct array
             .name4
             .rA
             .dec
             .vM
fullCatalog
 Copyright (c) 2018 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since version 2018.1
References and(), close(), Date2JD(), EarthBc(), EarthNut(), EarthPre(), isempty(), length(), Limit(), LoadCatalog(), Mag(), Map(), RaDec2U(), SReduce(), SunBc(), Unit(), and zeros().
ProcessStarImage()
function ProcessStarImage (in fileName, in fmt, in doFlip, in doPlot)
[xCOM,pixels,d] = ProcessStarImage(fileName, fmt, doFlip, doPlot)
Inputs
 fileName  Path to file
 fmt       Image format (gif, tiff)
 doFlip    Whether to invert image (fliplr)
 doPlot    Whether to create figures
Outputs
 xCOM      Centroid locations and intensity, [x;y;I]
 pixels    Pixel data
 d  (.)    Metadata
            .threshold  Pixel threshold for stars
            .nPixels    Size of pixel region of interest (odd integer)
            .coarseCM   Coarse centroids before processing
            .pMax       Maximum pixel value
            .flip       Whether image was flipped
See also
:
 LoadStarImage
 StarCentroidCOM
 PostProcessCOM
 FocalPlaneImage
References and(), Centroid(), CoarseCentroids(), FitHist(), FocalPlaneImage(), LoadStarImage(), PostProcessCOM(), ProcessStarImage(), and StarCentroidCOM().
Referenced by ProcessStarImage().
QFromU()
function QFromU (in uCatalog, in uMeas)
 unit vectors. The quaternion transforms from the catalog frame to the
 reference frame. The solution is found from:
 uMeas = m*uCatalog
 m     = uMeas*pinv(uCatalog);
 The number of columns should be >= 3 although 2 columns will give an
 m that is close to the correct matrix. The routine actually computes
 m and converts m to q.
Form
 [q, m] = QFromU( uCatalog, uMeas )
Inputs
 uCatalog        (3,:)  Unit vectors from the catalog
 uMeas           (3,:)  Corresponding measured unit vectors
Outputs
 q               (4,1)  Quaternion from reference
 m               (3,3)  Transformation matrix from reference
References and(), close(), Demo(), isempty(), Mat2Q(), Orthogonalize(), Q2Mat(), QFromU(), QRand(), quaternion(), set(), and Unit().
Referenced by QFromU(), and StarMeasurement().
RADecToPix()
function RADecToPix (in x, in pixels, in fOV)
The z-axis is along the boresight and the x and y axes are in the focal plane.
Form
 d = RADecToPix( x, pixels, fOV )
Inputs
 x               (2,:)       [rA;dec]
 pixels          (1,1)       Pixels in fOV
 fOV             (1,1)       Square field-of-view (rad)
Outputs
 d               (2,:)       [x;y]
References and(), Demo(), Plot2D(), RaDec2U(), RADecToPix(), Square(), square(), and U2Pix().
Referenced by RADecToPix().
RandSC()
function RandSC (in n, in d, in mVM, in sVM)
If mVM or sVM are not input it will generate visual magnitudes using statistics derived from the FK5 catalog. Visual magnitude is rounded to 2 decimal places.
Form
 [starMatrix, catalog] = RandSC( n, d, mVM, sVM )
Inputs
 n               (1,1)    Number of stars
 d               (1,1)    Digits accuracy
 mVM             (1,1)    Mean visual magnitude
 sVM             (1,1)    Standard deviation visual magnitude
Outputs
 starMatrix      (4,:)    Catalog [VisualMagnitude;UnitVector]
 catalog         (.)      Catalog data structure
                          .vM (1,:) Visual magnitude  (rad)
                          .rA (1,:) Right Ascension  (rad)
                          .dec (1,:) Declination (rad)
References length(), and U2RADec().
Referenced by StarDataFromStarMatrix().
RateFromDQ()
function RateFromDQ (in q, in qOld, in dT)
 Since version 3.
Form
 w = RateFromDQ( q, qOld, dT )
Inputs
 q          (4,1)         Quaternion
 qOld       (4,1)         Last quaternion
 dT         (1,1)         Time step
Outputs
 w          (3,1)         Rate (rad/sec)
References QMult(), QPose(), quaternion(), and Unit().
Referenced by StellarAttDetEKFNoGyros().
RearrangeCatalog()
function RearrangeCatalog (in cat)
Type RearrangeCatalog for a demo.
Form
 catalog = ReduceCatalog( catalog, angularResolution, useTimeGUI )
Inputs
 catalog    (.)   Star catalog data structure
Outputs
 stars   (.)   Structure array
References length(), LoadCatalog(), and RearrangeCatalog().
Referenced by RearrangeCatalog().
ReduceCatalog()
function ReduceCatalog (in catalog, in angularResolution, in useTimeGUI)
Eliminates stars that cannot be separated based on the input angular resolution.
catalog = ReduceCatalog(catalog, angularResolution, useTimeGUI)
Inputs
 catalog             (.)   Star catalog data structure
 angularResolution   (1,1) Angular resolution (rad)
 useTimeGUI          T/F
Outputs
 catalog             (.)   Star catalog data structure
References close(), Initialize(), isempty(), length(), LoadCatalog(), ReduceCatalog(), and TimeDisplay().
Referenced by ReduceCatalog().
RelativeStateFromPoints()
function RelativeStateFromPoints (in rW, in rF)
 7 points in the world and the corresponding points in the imager.
 It also computes the focal plane parameters.
 rW must not be coplanar.
Form
 [b, t, fX, fY] = RelativeStateFromPoints( rW, rF )
Inputs
 rW              (3,:)  Points in the world frame
 rF              (2,:)  Same points in the imager plane
Outputs
 b               (3,3)   Transformation matrix
 t               (3,1)   Offset
 fX              (1,1)   X focal length/imager x width
 fY              (1,1)   Y focal length/imager y width
Reference: Trucco, E. and A. Verri, "Introductory Techniques for 3-D Computer Vision," Prentice-Hall, pp. 125-130.
References and(), Cross(), Demo(), length(), Mag(), Q2Mat(), QRand(), RelativeStateFromPoints(), Unit(), WorldToCamera(), and zeros().
Referenced by RelativeStateFromPoints(), and WorldToCamera().
ReshapeCovariance()
function ReshapeCovariance (in p)
 The covariance matrix is reshaped as
 [p11 p12 p13]
 [p21 p22 p23]
 [p31 p32 p33]
 to
 [p11 p12 p13 p22 p23 p33]'
 and back. Notice that the diagonals appear only once.
Form
 pR = ReshapeCovariance( p )
Inputs
 p            (:,:) The covariance matrix (n,n) or (m,1)
Outputs
 pR           (:,:) The covariance matrix (n,n) or (m,1)
References and(), and square().
Referenced by OrbitKFRHS().
RHSEarthOrbitUKF()
function RHSEarthOrbitUKF (in x, in ignoredArg, in d)
Form
 d    = RHSEarthOrbitUKF;
 xDot = RHSEarthOrbitUKF( x, t, d )
Inputs
 x             (6,1)  State vector [r;v]
 t             (1,1)  Time (unused)
 d              (.)   Data structure
                      .mu (1,1) Gravitational constant (default earth)
                      .a  (3,1) Acceleration vector in ECI Frame
Outputs
 x             (6,1)  State vector derivative d[r;v]/dt
References Mag(), RHSEarthOrbitUKF(), and vector().
Referenced by RHSEarthOrbitUKF().
RHSGyro()
function RHSGyro (in x, in ignoredArg, in d)
Set d.rIG to true for a rate integrating gyro. If an RIG, the state will be length 6.
Form
 [xDot, y] = RHSGyro( x, ~, d )
Inputs
 x   (6,1)  State [b;integral omega]
 t   (3,1) Time (unused)
 d   (.) Data structure
        .rIG         (1,1) True for RIG
        .randomWalk  (3,1) Random walk noise (rad/s)
        .angleNoise  (3,1) Angle noise (rad)
        .sigma       (1,1) Markovian 1/tau
Outputs
 xDot (6,1) State d[b;integral omega]/dt
References DefaultDataStructure(), length(), Random(), and RHSGyro().
Referenced by RHSGyro().
RHSIsothermalPState()
function RHSIsothermalPState (in x, in t, in d)
 This model works only in Earth orbit. It has a second state for a
 flux modeled as a Markov process.
Form
 xDot = RHSIsothermal( x, t, d )
Inputs
 x        (2,1) [Temperature;flux]
 t        (1,1) TIme
 d        (1,1) Data structure
                .a1    (1,1) epsilon*a_r/cp*m
                .a2    (1,1) alpha*a_s/cp*m
                .a3    (1,1) 1/cp*m
                .a4    (1,1) 1/tau
                .p     (1,1) Internal power
                .jD0   (1,1) Julian date at t = 0
                .rECI  (3,1) ECI Position vector
 jD       (1,n) Julian dates
Outputs
 x        (2,1) [Temperature;flux]
References Markov(), RHSIsothermal(), and vector().
RHSIsothermalUKF()
function RHSIsothermalUKF (in x, in t, in u)
This is a wrapper function for RHSIsothermal
Form
 f = RHSIsothermalUKF( x, t, u )
Inputs
 x         (1,1)  State [t]
 t         (1,1)  Time (not used)
 u         (1,1)  Data structure
Outputs
 f         (1,1)  State derivative
References length(), and RHSIsothermal().
RHSOrbitUKF()
function RHSOrbitUKF (in x, in ignoredArg, in d)
 t is not used. This is compatible with RK4 and RK45.
Form
 f = RHSUKF( x, t, d )
Inputs
 x         (6,1)  State [r;v]
 t         (1,1)  Time (not used)
 d         (1,1)  Data structure
                  .a   (3,1) Acceleration
                  .mu  (1,1) Gravitational parameter
Outputs
 f         (6,1)  State derivative
References: None
References and(), Mag(), RK4(), and RK45().
RHSPressure()
function RHSPressure (in mFuel, in ignoredArg, in d)
t is not used. This is compatible with RK4 and RK45.
Form
 f = RHSPressure( mFuel, t, d )
Inputs
 x         (1,1)  State (fuel mass, not used)
 t         (1,1)  Time (not used)
 d         (1,1)  Data structure
                  .mDot (1,1) Mass flow
                  .pw   (1,1) pulsewidth
                  .dT   (1,1) Time step
Outputs
 f         (1,1)  State derivative
References and(), RK4(), and RK45().
RHSQ()
function RHSQ (in qECIToBody, in t, in omega)
Form
 dQ = RHSQ( qECIToBody, t, omega )
Inputs
 qECIToBody    (4,1)   Quaternion from the ECI to body frame
 t             (1,1)   Time (sec)
 omega         (3,1)   Angular rate (rad/sec)
Outputs
 dQ            (4,1)   Quaternion derivative
References QIToBDot().
RMABEst()
function RMABEst (in tMeas, in newMeas, in RMARate, in x, in r, in q, in dT)
 The steady state gain is computed automatically each time. In practice it
 could be uploaded as a command if the time between measurements was
 constant. The measurement is the time between updates of an inertial sensor.
 Since version 1.
Form
 [x, k] = RMABEst( tMeas, newMeas, RMARate, x, r, q, dT )
Inputs
 tMeas         (1,1)    The measured period (sec)
 newMeas       (1,1)    When == 1 incorporate a new measurement
 RMARate       (1,1)    Rate as measured by the RMAs
 x             (1,1)    Bias estimate state
 r             (1,1)    Measurement noise covariance
 q             (1,1)    State noise covariance
 dT            (1,1)    Time since last measurement
Outputs
 x             (1,1)    Bias estimate
 k             (1,1)    Gain
RollYawEstimator()
function RollYawEstimator (in x, in omega, in roll, in rollNoise, in dT)
Form
 xEst = RollYawEstimator( x, omega, roll, rollNoise, dT )
Inputs
 x                 (2,1)  Initial [roll;yaw]
 omega             (3,:)  Body Rates
 roll              (1,:)  Roll angle (rad)
 rollNoise         (1,1)  1 sigma roll noise
 dT                (1,1)  Time step
Outputs
 xEst              (2,:)  [roll;yaw]
References and(), C2DZOH(), DQCE(), isempty(), length(), Plot2D(), and zeros().
RYGCAttDet()
function RYGCAttDet (in angInc, in q, in dT, in b, in p, in Q, in r, in m, in mGyro)
Form
 [q, p] = RYGCAttDet( angInc, q, dT, b, p, Q, r, m, mGyro )
Inputs
 angInc       (n,1)     Angular increments
 q            (3,1)     Attitude vector
 dT           (1,1)     Time step
 b            (3,1)     Bias
 p            (3,3)     State covariance matrix
 Q            (3,3)     State noise covariance
 r            (1,1)     Measurement noise
 m            (2,1)     [roll;pitch] (rad)
 mGyro        (3,3)     Gyro unit vectors
Outputs
 q            (4,1)     Attitude quaternion
 p            (3,3)     State covariance matrix
References EKFSSG(), Gyro(), quaternion(), Step(), vector(), and YawRollGyroCompassing().
SearchKVector()
function SearchKVector (in k, in q, in m, in y1, in y2)
The output are the indices into the sorted data that are guaranteed to include the interval, [ya,yb]. There may be additional data points outside this interval.
k1 and k2 guarantee that:
 y(k1) < y(a)
 yb < y(k2)
Note that the data itself is not an input to this function. There is no searching within the data; only the line parameters m and q are needed to find the indices in k which bracket the desired interval.
Form
 [k1,k2] = SearchKVector(k,q,m,y1,y2)
Inputs
 k          (1,:) Set of integer indices
 m          (1,1) Slope of linear fit
 q          (1,1) Intercept of linear fit
 y1         (1,1) Start value for interval
 y2         (1,1) Final value for interval
Outputs
 k1         (1,1) Start index for interval
 k2         (1,1) Final index for interval
See also
: CreateKVector
References and(), CreateKVector(), length(), SearchKVector(), and vector().
Referenced by CreateKVector(), SearchKVector(), and StarIDPyramid().
SelectMeasurementSet()
function SelectMeasurementSet (in firstMeas, in nMeas, in measPairs, in hitPairs)
Form
 [measPairsSubset, hitPairsSubset, measMap] = SelectMeasurementSet( firstMeas,
 nMeas, measPairs, hitPairs )
Inputs
 kSet            (1,:)     Set measurement to be used
 nMeas           (1,1)     Number of measurements to use
 measPairs       (2,n)     Column is a measurement. Each row gives the meas id
 hitPairs        {n}       Dot product hits. Each two numbers gives a star pair
                           [star1_meas1 star2_meas1 star1_meas2 star2_meas2...]
Outputs
 measPairsSubset (2,n)     Column is a measurement. Each row gives the meas id
 hitPairsSubSet  {n}       Dot product hits. Each two numbers gives a star pair
                           [star1_meas1 star2_meas1 star1_meas2 star2_meas2...]
 measMap         (1,:)     Maps measurement pair subset to input measurements
SeqBatchLSQOD()
function SeqBatchLSQOD (in dx0, in P0Inv, in x0, in zMNew, in WNew, in d, in opts)
 Since version 8.
Form
 [x0,P0,dx0] = SeqBatchLSQOD( x0G, zMNew, WNew, d, opts );
Inputs
 dx0           (6,1)    Last computed differential correction term.
 P0Inv         (6,6)    Inverse of P0, last computed covariance matrix.
 x0            (6,1)    Last computed solution for epoch state x0.
 zMNew         (N,1)    Vector of new measurements.
 WNew         (6N,6N)   Diagonal weighting matrix for new measurements.
                           Should be inverse of measurement variances.
 d              (.)     Data structure for observation function. Fields:
                 .name    (:)      Name of observation function.
                 .mu      (1)      Value for gravitational parameter mu
                 .dT      (1)      Desired time step for orbit propagation [sec]
                 .obsTime (1,nObs) Observation times [sec] (MET)
                 .rGS     (1,nObs) ECI position of ground station at observation times
                 .vGS     (1,nObs) ECI position of ground station at observation times
                 .accTime (1,nC)   Time vector of applied accelerations [sec] (MET)
                 .acc     (1,nC)   Applied acceleration vector (3x1) [km/s/s]
 opts           (.)     Data structure of options for this algorithm.
 .tol     (1)      Tolerance for size of dx0 (differential corrector)
 .maxIter (1)      Maximum allowed iterations
Outputs
 x0            (6,1)  Solution for epoch state x0.
 P0            (6,6)  Covariance matrix.
 dx0           (6,1)  Last differential correction term.
References Jacobian(), and vector().
Snapshots()
function Snapshots (in starDataMeas, in fileName, in starID, in starName, in xYPixels)
 Pass a cell array of starDataMeas structures.
Form
 Snapshots( starDataMeas, fileName, starID, starName, xYPixels  )
Inputs
 starDataMeas {:}      Data structure
                       .pixelLocation  (2,m) Coordinates of centroid [x;y]
                       .pixelIntensity (1,m) Intensity of each object
 fileName     {:}      File name
 starID       {:}      Identified stars
 starName     {:}      Star names
 xYpixels     (1,2)    Pixel Dimenstions
Outputs
 None
References and().
SqrFOV()
function SqrFOV (in u, in x, in y)
Determines if a unit vector falls within a square x by y field of view. The boresight is along +z.
Form
 k = SqrFOV( u, x, y )
Inputs
 u            (3,:)     Unit vectors
 x            (1,1)     x width (rad)
 y            (1,1)     y width (rad)
Outputs
 k            (1,:)     Columns that are within the field-of-view
References abs(), square(), Unit(), and vector().
Referenced by StarSensor().
SReduce()
function SReduce (in rA0, in dec0, in pMRA, in pMDec, in parallax, in rV, in vSc, in jD)
Includes corrections for
Form
 u = SReduce( rA0, dec0, pMRA, pMDec, parallax, rV, vSc, jD )
Inputs
 rA0           (1,1)      Catalog right ascension
 dec0          (1,1)      Catalog declination
 pMRA          (1,1)      Proper motion in right ascension
 pMDec         (1,1)      Proper motion in declination
 parallax      (1,1)      Stellar parallax
 rV            (1,1)      Radial velocity (km/sec)
 vSc           (1,1)      Spacecraft velocity vector (km/sec)
 jD            (1,1)      Julian date
Outputs
 u             (3,1)     Unit vector
References: Astronomical Almanac for 1993, U.S. Government Printing Office, B39-B41
References and(), EarthBc(), EarthNut(), EarthPre(), JD2T(), LightDef(), RaDec2U(), StellAbr(), SunBc(), Unit(), and vector().
Referenced by ProcessCatalog().
StarCentroidCOM()
function StarCentroidCOM (in p, in threshold, in nROI, in doPlot)
 This uses the center of mass method. The center of mass will have
 larger errors if the width of the region of interest goes outside
 the pixel mask. Generally, star measurements on the edge will not
 be reliable due to optical errors so should be discarded if you have
 enough stars that for than n pixels from the edges.
 x is defined in the column direction, y in the row direction.
 iPSF is in the same units as the intensity of the pixel map.
 Type StarCentroidCOM for a demo which will draw the centroid and the
 intensity map. With one output it will return [x0;y0]
 Since version 2014.1.
Form
 [x0, y0, iC] = StarCentroidCOM( p, threshold, nROI, doPlot )
Inputs
 p            (:,:)  Pixel map
 threshold    (1,1)  Threshold indicating a star is present
 nROI         (1,1)  Size of region of interest (pixels)
 doPlot       (1,1)  Specify true to generate the demo plot
Outputs
 x0           (1,:)  x centroid or (3,:) [x0;y0;iPSF]
 y0           (1,:)  y centroid
 iC           (1,:)  Total intensity of the centroid
Reference: M. Knutson and D. Miller, "Fast Star Tracker Centroid Algorithm for High Performance CubeSat with Air Bearing Validation," June 2012 MIT SSL # 5-12
References and(), Blobify(), Centroids(), close(), Demo(), get(), ImagerPSF(), length(), NewFig(), RHSGaussianPSF(), set(), StarCentroidCOM(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by FitPSFToData(), PostProcessCOM(), ProcessStarImage(), and StarCentroidCOM().
StarDataFromStarMatrix()
function StarDataFromStarMatrix (in starMatrix, in fieldOfView, in angularResolution)
 Most of the data structure is empty. This routine primarily
 creates a matrix which is a list of stars that are close
 to each other for search purposes. The data structure
 collects the inputs and the resulting "nearMatrix" into
 a data structure. starCatalog in the data structure is the
 star matrix in star catalog form. This routine can be slow. Normally
 this would not be done in flight.
 The field of view angle determines how close a star has to be
 to another to be visible in the field-of-view. The angular resolution
 determines which stars must be considered a single star.
 Type StarDataFromStarMatrix for a demo with a random star
 catalog and a half-sky field-of-view.
Form
 d = StarDataFromStarMatrix( starMatrix, fieldOfView, angularResolution )
Inputs
 starMatrix        (4,:) Star catalog matrix
 fieldOfView       (1,1) Angle for dot products (rad)
 angularResolution (1,1) Angular resolution (rad)
Outputs
 d                 (1,1) Data structure
                         .starMatrix         (4,:) [Intensity;u]
                         .nearMatrix         (3,:) [dot;star;base star]
                         .starCatalog        (1,1) Reduced Star catalog
                         .angularResolution  (1,1) Angular resolution
                         .fieldOfView        (1,1) Field of view
References and(), close(), Initialize(), isempty(), length(), RandSC(), StarDataFromStarMatrix(), TimeGUI(), and U2RADec().
Referenced by StarDataFromStarMatrix().
StarDataGeneration()
function StarDataGeneration (in starCatalog, in fieldOfView, in angularResolution)
It contains a list of nearby stars and their dot products. The fieldOfView input defines the radius for a small circle on a sphere. This routine eliminates duplicate stars (i.e. it stores the dot from k to j but not from j to k.)
The starMatrix field is a matrix
[intensity;unitVector]
The nearMatrix field is a matrix of dot product pairs of stars within the fieldOfView of other stars. For example if the field of view is 10 deg it will compute the dot products for all stars within 20 deg of star k.
The starCatalog field is a reduced version of the input star catalog with the stars that are too close to separate eliminated.
The angular resolution and fieldOfView fields are the same as the input variables.
To admit all stars set angularResolution to 0.
Form
 d = StarDataGeneration( starCatalog, fieldOfView, angularResolution )
Inputs
 starCatalog       (1,1) Star catalog data structure
 fieldOfView       (1,1) Angle to admit dot products (rad)
 angularResolution (1,1) Angular resolution between stars (rad)
 q                 (4,1) Quaternion
Outputs
 d                 (1,1) Data structure
                         .starMatrix         (4,:) [Intensity;u]
                         .nearMatrix         (3,:) [dot;star;base star]
                         .starCatalog        (1,1) Reduced Star catalog
                         .angularResolution  (1,1) Angular resolution
                         .fieldOfView        (1,1) Field of view
                         .nearSlope          (1,1) Slope
                         .nearQ              (1,1) Quaternion
References and(), close(), Initialize(), isempty(), length(), LoadCatalog(), set(), StarDataGeneration(), TimeGUI(), and VM2Int().
Referenced by StarDataGeneration().
StarDensity()
function StarDensity (in name, in visualMagnitude, in fOV)
 This is plot of the numbers of stars in the square field of view.
 The survey is done by incrementing the right ascension and declination
 by 0.1 x fOV.
 Type StarDensity for a demo
Form
 d = StarDensity( name, visualMagnitude, fOV )
Inputs
 name            (1,:)  Catalog name 'Hipparcos', 'FK5', 'FK5 Polar',
                        or 'FK5 Short'
 visualMagnitude (1,1)  Visual magnitude
 fOV             (1,1)  Field of view (rad)
Outputs
 d               (:,:)  Density [declination,right ascension]
References and(), Demo(), isempty(), length(), LoadCatalog(), NewFig(), RaDec2U(), set(), square(), StarDensity(), TitleS(), XLabelS(), YLabelS(), and zeros().
Referenced by StarDensity().
StarIDPyramid()
function StarIDPyramid (in starMeas, in d, in options)
One or more measurements may be bad. This routine requires at least three measurements. Assumes a pinhole transformation with Pix2U; you must set the pixel scale factor in the options for successful star identification.
Form
 options = StarIDPyramid
 [starID, uMeas, uCatalog] = StarIDPyramid( starMeas, d, options  )
Inputs
 starMeas  (.)     Star measurement data structure
                    .pixelLocation         (2,m) vectors of [xloc,yloc]
                    .pixelIntensity        (1,m) Intensity
 d         (.)     Catalog data structure
                    .starMatrix            (4,p)  Star catalog of p stars stored as [intensity;u]
                    .fieldOfView           (1,1)  Field of view
                    .nearMatrix            (3,:)  [dot;star1;star2]
 options   (.)    Options
                    .angleTolerance        (1,1)  Tolerance on star angles
                    .pixelMapScale    (2 or 1,1)  Pixel map scale factor
                                                  (focal length in pixels)
                    .nMeasMax              (1,1)  Max number of measurements
                    .verbosity               (1)  Verbosity level
                    .stars                   (:)  A set of a priori star indices
Outputs
 starID     (m)     Catalog id's of measured stars
 uMeas      (3,:)   Measured unit vectors
 uCatalog   (3,:)   Corresponding catalog vectors
Reference: Mortari, The Pyramid Star Identification Technique
References and(), length(), Limit(), Pix2U(), SearchKVector(), set(), StarIDPyramid(), and zeros().
Referenced by StarIDPyramid().
StarIDTestCatalog()
function StarIDTestCatalog (in n, in fOV, in nPixels, in thetaRes, in testData, in displayStars)
 Test types are determined by the data in the testData function
 Missing Stars
Outputs
that include all stars in the catalog. The StarID function should identify all of the stars. The nMissing field in testData contains the number of missing stars.
 Matching Sets
 More than one non overlapping sets are generated. The sets match except for
 a specified number of stars that don't match. This test determines the
 ability of StarID4 to find the correct set among several possible sets.
 Use the nSets field in testData to set the number of sets and nMissingPerSet
 to specify how many stars are not identical.
Form
 d = StarIDTestCatalog( n, fOV, nPixels, thetaRes, testData, displayStars )
Inputs
 n              (1,1)  Number of stars needed for a match
 fOV            (1,1)  Field of view (deg)
 nPixels        (1,1)  Number of pixels
 thetaRes       (1,1)  Angular resolution
 testData       (.)    Test data structure
 displayStars   (1,1)  Any argument causes a star display
Outputs
 d              (.)    Output data structure
                       starDataMeas (2,m) m vectors of [xloc,yloc]
                       starMatrix   (4,p) Star catalog of p stars stored as [intensity;u]
                       fScale       (1,1) Pixel map scale factor
                       thetaRes     (1,1) Angular resolution
                       nearMatrix   (3,:) [dot;star1;star2]
                       starCatalog  (:)   Star catalog data structure
Reference: Buil, C. (1991.) CCD Astronomy. Willman-Bell, Inc. p. 42-46.
References and(), LoadCatalog(), and set().
StarImageHistogram()
function StarImageHistogram (in pixels, in fname, in threshold)
The first shows the background noise at the low end of the scale. The second shows the pixels above the noise threshold.
Form
 StarImageHistogram( pixels, fname, threshold )
Inputs
 pixels     (:,:) Pixel values
 fname      (1,:) File name
 threshold  (1,1) Threshold
Outputs
 None
 Copyright (c) 2018 Princeton Satellite Systems, Inc.
 All rights reserved.
 Since 2018.1
References isempty(), and set().
StarMeasurement()
function StarMeasurement (in r, in starDataMeas, in q, in qBodyToCamera, in starData, in fScale)
matrix given a pixel map from the star tracker. Will update q if it has three valid stars and the attitude error is large.
Form
 [h, dz, R, q] = StarMeasurement( r, starDataMeas, q, qBodyToCamera, starData, fScale )
Inputs
 r             (1,1)    Measurement noise
 starDataMeas  (3,m)    m vectors of [intensity,xloc,yloc]
 q             (4,1)    Quaternion from ECI to body axes
 qBodyToCamera (4,1)    Quaternion from body to sensor axes
 starData               Star Data
                        .starMatrix (4,n)     Star catalog containing n stars stored as [intensity;u]
                        .starID     (1,m)     Identified stars
                        or just starMatrix (4,n)
 fScale        (1,1)    Sensor scale factor
Outputs
 h            (n,6)     Linearized measurement matrix
 dz           (n)       The measurement residuals
 R            (n,n)     Measurement noise
 q            (4,1)     Quaternion from ECI to body axes
References abs(), and(), isempty(), length(), Q2Mat(), QForm(), QFromU(), QMult(), QPose(), Skew(), U2Pix(), and zeros().
Referenced by StellarAttDetEKF(), and StellarAttDetEKFNoGyros().
StarMeasurementUKF()
function StarMeasurementUKF (in x, in d)
Form
 y = StarMeasurementUKF( x, d )
Inputs
 x   (6,1)  [dQ;b]
 d   (.)    Data structure
Outputs
 y  (:,1)   Measurements
References Measurements(), QMult(), quaternion(), StarSensor(), UKF(), vector(), and zeros().
Referenced by StellarAttDetUKF().
StarMovie()
function StarMovie (in starDataMeas)
Pass a cell array of starDataMeas arrays.
Form
 StarMovie( starDataMeas  )
Inputs
 starDataMeas {:}    data struct containing the following
                     .pixelLocation(2,:)   [xloc;yloc]
                     .pixelIntensity(1,:)   [intensity] (not required)
Outputs
 None
StarPrediction()
function StarPrediction (in camera, in uStar, in qBoresight)
Return the indices of the star vectors within the camera FOV qBoresight locates the camera axis in the inertial frame assuming the boresight is along +z. This uses persistent store. Pixels are square.
Form
 [stars,xY] = StarPrediction(camera,uStar,qBoresight)
Inputs
 camera      (.)   Camera data structure
                   .m      (1,1) Number of pixels in x
                   .n      (1,1) Number of pixels in y
                   .pixel   (1,1) Pixel width
                   .f      (1,1) Focal length
 uStar       (3,:) Star vectors
 qBoresight  (4,1) Quaternion from camera base to catalog
Outputs
 v           (1,:) Star ids
 xY          (2,:) Star focal plane locations
References abs(), isempty(), length(), plus(), Q2Mat(), square(), and U2Pix().
StarSensor()
function StarSensor (in qECIToB, in qBToS, in ignoredArg, in starMatrix, in fov, in fScale)
Compute the stars seen in the field-of-view from attitude and the star catalog.
Form
 starData = StarSensor( qECIToB, qBToS, uS, starMatrix, fov, fScale )
Inputs
 qECIToB      (4,1)     Quaternion from body to ECI axes
 qBToS        (4,1)     Quaternion from body to sensor axes
 uS           (3,1)     Unit vector (unused)
 starMatrix   (4,p)     Star matrix [intensity;u]
 fov          (1,1)     Circular field-of-view
 fScale       (1,1)     Sensor scale factor
Outputs
 starData     (3,m)     Vector of [intensity;xloc;yloc]
See also
SqrFOV
References and(), isempty(), QForm(), QMult(), SqrFOV(), U2Pix(), Unit(), and vector().
Referenced by StarMeasurementUKF().
StellAbr()
function StellAbr (in u, in v, in abType)
 Since version 3.
Form
 uC = StellAbr( u, v, abType )
Inputs
 u                 (3,1)  Unit position vector
 v                 (3,1)  Velocity vector divided by the speed of
                          light
 abType            (1,1)  Type of computation 'n' (Newtonian) or 's'
                          (special-relativistic)
Outputs
 uC                       Corrected u
References: Siedelmann, P., ed. (1992). Explanatory Supplement to the Astronomical Almanac, University Science Books, Mill Valley, CA, 129.
References Unit(), and vector().
Referenced by SReduce().
StellarAttDetEKF()
function StellarAttDetEKF (in angInc, in q, in dT, in b, in p, in Q, in r, in qBToS, in starDataMeas, in starData, in fScale)
Form
 [q, b, p] = StellarAttDetEKF( angInc, q, dT, b, p, Q, r, qBToS,
 starDataMeas, starData, fScale )
Inputs
 angInc       (n,1)     Angular increments
 q            (4,1)     Attitude quaternion
 dT           (1,1)     Time step
 b            (3,1)     Bias
 p            (6,6)     State covariance matrix
 Q            (6,6)     State noise covariance
 r            (1,1)     Measurement noise
 qBToS        (4,1)     Quaternion from body to sensor axes
 starDataMeas (3,m)     Vector of [intensity;xloc;yloc]
 starData     (1,1)     Star Data
                        .starMatrix (4,n)     Star catalog containing n stars stored as [intensity;u]
                        .starID     (1,m)     Identified stars
 fScale                 Sensor scale factor
Outputs
 q            (4,1)     Attitude quaternion
 b            (3,1)     Bias
 p            (6,6)     State covariance matrix
References and(), AttProp(), DSTM(), EKFSSG(), isempty(), QFromDQ(), quaternion(), and StarMeasurement().
StellarAttDetEKFNoGyros()
function StellarAttDetEKFNoGyros (in q, in qOld, in w, in dT, in p, in Q, in r, in qBToS, in starDataMeas, in starData, in fScale)
Form
 [q, p, qOld, w] = StellarAttDetEKFNoGyross( q, qOld, w, dT, p, Q, r, qBToS, starMeas, starData, fScale )
Inputs
 q            (4,1)     Attitude quaternion
 qOld         (4,1)     Last attitude quaternion
 w            (3,1)     Body rate
 dT                     Time step
 p            (6,6)     State covariance matrix
 Q            (6,6)     State noise covariance
 r                      Measurement noise
 qBToS        (4,1)     Quaternion from body to sensor axes
 starDataMeas
 starData     (m,3)     Vector of [intensity,xloc,yloc]
 fScale       (1,1)     Sensor scale factor
Outputs
 q            (4,1)     Attitude quaternion
 p            (3,3)     State covariance matrix
 qOld         (4,1)     Old quaternion
 w            (3,1)     Rate
References and(), AttProp(), DSTMQ(), EKFSSG(), isempty(), QMult(), quaternion(), RateFromDQ(), StarMeasurement(), and Step().
StellarAttDetUKF()
function StellarAttDetUKF (in angInc, in q, in dT, in b, in qBToS, in starDataMeas, in starData, in fScale, in rStar, in ukf)
Get the default data structure by typing just the function name. RHSFun is not used if integrator is used.
Form
 [q, b, ukf] = StellarAttDetUKF( angInc, q, dT, b, p, qBToS,
 starDataMeas, starData, fScale, rStar, ukf )
 ukf         = StellarAttDetUKF
Inputs
 angInc       (3,1) Angular increments from the gyro
 q            (4,1) Attitude quaternion
 dT           (1,1) Time step
 b            (3,1) Gyro bias
 qBToS        (4,1) Quaternion from body to sensor axes
 starDataMeas (2,m) Vector of [xloc;yloc] from the star sensor
 starData     (1,1) Star Data
                    .uCatalog   (3,n)   Star catalog containing n stars stored as [intensity;u]
                    .starID     (1,m)   Identified stars
 fScale       (1,1) Sensor scale factor
 rStar        (1,1) Covariance matrix term for a star measurements
 ukf          (.)       UKF Data structure
Outputs
 q            (4,1) Attitude quaternion
 b            (3,1) Bias
 ukf          (.)       UKF Data structure
References AttProp(), DefaultDataStructure(), DSTM(), Gyro(), isempty(), KFInitialize(), length(), QFromDQ(), quaternion(), StarMeasurementUKF(), StellarAttDetUKF(), UKF(), UKFUpdate(), UKFWeight(), vector(), and zeros().
Referenced by StellarAttDetUKF().
StellarNavigation()
function StellarNavigation (in d, in range, in angleMeas, in kAngle, in rEst)
 Generates the spacecraft position vector given a star catalog and
 a range measurement from a ground station. The landmark is assumed
 to be the ground station. If rEst is entered it will use a
 recursive Kalman Filter. The least squares is unweighted.
 The estimator estimates the unit vector from the ground station to the
 spacecraft. The range is used directly. This routine implements
 the measurement update alone. In practice, you would also use the
 state update.
 This system does not estimate velocity. Normally, range rate would be
 an additional measurement. With the addition of the state update,
 this would give estimates of rate better than differencing position.
 Normally, it would also be necessary to estimate the clock error.
Form
 [r, p] = StellarNavigation( d, range, angleMeas, kAngle, rEst )
Inputs
 d           (1,1)   Database
                     .rG   (3,1) Ground station position in ECI frame
                     .uS   (3,:) Star unit vectors referred to the origin
                                 of the ECI frame
                     .rho  (1,:) Measurement uncertainty
                     .p    (3,3) Initial state covariance
 range        (1,1)  Range from the ground station to the spacecraft
 angleMeas    (1,:)  Measured star angles from between the star
                     vector and the ground station
 kAngle       (1,:)  Index relating angleMeas to d.uS
 rEst         (3,1)  Initial estimate
Outputs
 r            (3,1)   Position vector
 p            (3,3)   Covariance (Kalman Filter only)
References and(), Database(), length(), Unit(), and vector().
STM()
function STM (in w, in dT)
Generates the state transition matrix to propagate a quaternion one step assuming that the angular velocity is constant.
Form
 phi = STM( w, dT )
Inputs
 w            (3,1)     Angular rate
 dT           (1,1)     Time change
Outputs
 phi          (4,4)     State transition matrix
References Mag(), quaternion(), and SkewSymm().
Referenced by Propagate3BP(), Propagate4BP(), and PropagateCRTBP().
SubCatalog()
function SubCatalog (in d, in k)
Form
 s = SubCatalog( d, k )
Inputs
 d               (.)    Catalog
 k              (1,:)   Array of star indices to keep
Outputs
 d               (.)    Reduced catalog
Referenced by GetStarPatch().
SunBc()
function SunBc (in jD)
This function currently returns [0;0;0] which is in error by about 0.002 Au.
Form
 sB = SunBc( jD )
Inputs
 jD                (1,1)  Julian date
Outputs
 sB                (3,1)  Barycentric position (aU)
Referenced by ProcessCatalog(), and SReduce().
SunEarthAttDet()
function SunEarthAttDet (in angInc, in q, in dT, in b, in p, in Q, in r, in qBToS, in sensorData, in catalog, in fScale)
Form
 [q, b, p] = SunEarthAttDet( angInc, q, dT, b, p, Q, r, qBToS, sensorData, catalog, fScale )
Inputs
 angInc       (n,1)     Angular increments
 q            (4,1)     Attitude quaternion
 dT           (1,1)     Time step
 b            (3,1)     Bias
 p            (6,6)     State covariance matrix
 Q            (6,6)     State noise covariance
 r            (1,1)     Measurement noise
 qBToS        (4,1)     Quaternion from body to sensor axes
 sensorData   (m,3)     Vector of [intensity,xloc,yloc]
 catalog      (3,p)     Catalog of unit vectors
 fScale                 Sensor scale factor
Outputs
 q            (4,1)     Attitude quaternion
 b            (3,1)     Bias
 p            (6,6)     State covariance matrix
References and(), AttProp(), DSTM(), EKFSSG(), isempty(), Measurements(), QFromDQ(), quaternion(), Step(), and vector().
SunEarthMagAttDet()
function SunEarthMagAttDet (in angInc, in q, in b, in ukf, in r, in dT, in sensorData)
Uses an IMU base. angInc comes from the IMU. This uses the Unscented Kalman Filter (UKF).
Form
 ukf = SunEarthMagAttDet    % default data structure
 [q, b, ukf] = SunEarthMagAttDet( angInc, q, b, ukf, r, dT, sensorData )
Inputs
 angInc      (n,1)  Angular increments
 q          (4,1)   Attitude quaternion
 b          (3,1)   Bias
 ukf            (.)   UKF data structure
 r           (.)   Measurement data structure
 dT          (1,1)  Time step
 sensorData (.)     Sensor data structure
Outputs
 q           (4,1)  Attitude quaternion
 b          (3,1)   Bias
 ukf        (.)     UKF data structure
See also
UKFUpdate, MeasurementsSunMagUKF, QFromDQ, DSTM, RHSGyroUKF
References and(), AttProp(), DefaultDataStructure(), DSTM(), IMU(), isempty(), KFInitialize(), length(), MeasurementsSunMagUKF(), QFromDQ(), quaternion(), SunEarthMagAttDet(), UKF(), UKFUpdate(), UKFWeight(), vector(), and zeros().
Referenced by SunEarthMagAttDet().
SunMagAttDet()
function SunMagAttDet (in x, in p, in r, in qBToS, in bMeas, in sensorData, in catalog, in fScale)
 The first column of catalog is the magnetometer data.
Form
 [x, p] = SunMagAttDet( x, p, r, qBToS, bMeas, sensorData, catalog, fScale )
Inputs
 x            (3,1)     Attitude [x;y;z]
 p            (3,3)     State covariance matrix
 r            (m)       Measurement noise
 qBToS        (4,1)     Quaternion from body to sensor axes
 bMeas        (3,1)     Measured magnetic field
 sensorData   (m,3)     .xy        (2,:) Focal plane data
                        .validMeas (:)   1 if measurement is valid
 catalog      (3,p)     Catalog of unit vectors
 fScale                 Sensor scale factor
Outputs
 x            (3,1)     Attitude [x;y;z]
 p            (3,3)     State covariance matrix
References EKFSSG(), length(), Mag(), Q2Mat(), Skew(), Step(), vector(), and zeros().
Swath()
function Swath (in ra, in dec, in VM, in VMMin, in decLim, in raLim)
Form
 starMatrix = Swath( ra, dec, VM, VMMin, decLim, raLim )
Inputs
 ra           (n)       Right ascensions (rad)
 dec          (n)       Declinations     (rad)
 VM           (n)       Visual magnitude
 VMMin        (n)       Minimum visual magnitude
 decLim       (1,2)     Range of declinations     [min,max] (rad)
 raLim        (1,2)     Range of right ascensions [min,max] (rad)
Outputs
 starMatrix  (4,n)     Star catalog [intensity;u]
References RaDec2U(), and VM2Int().
Referenced by PackageOrbitDataForPlayback(), PlaybackOrbitSim(), and SemimajorAxisRevisit().
TelescopeAperture()
function TelescopeAperture (in catalog, in D, in eta)
Form
 TelescopeAperture.
 [a, D] = TelescopeAperture( catalog, apertureMax, eta )
Inputs
 catalog     (1,:)     Catalog data structure
 D           (1,:)     The range of apertures (mm)
 eta         (1,1)     Product of fill factor and quantum efficiency
Outputs
 a           (1,:)     Number of stars visible
 m           (1,:)     Visual magnitude vs aperture
References and(), Demo(), isempty(), length(), LoadCatalog(), Plot2D(), Product(), TelescopeAperture(), and zeros().
Referenced by TelescopeAperture().
TelescopeUKF()
function TelescopeUKF (in x, in d)
This function does not account for field-of-view so it produces measurements even when the spacecrat is behind the planet.
Form
 d = TelescopeUKF;
 y = TelescopeUKF( x, d )
Inputs
 x  (3,1)  State vector r
 d  (1,1)  Data structure
          .noise   (2,1) Noise vector 1 sigma
          .jD      (1,1) Julian day number
          .rGS     (3,1) Ground station position vector
          .eFToNEU  (3,3) Transformation from EF to NEU
Outputs
 y  (6,1)  [azimuth;elevation] in NEU frame
References EarthRot(), JD2000(), JD2T(), TelescopeUKF(), Unit(), and vector().
Referenced by TelescopeUKF().
UKFUpdateAtt()
function UKFUpdateAtt (in d)
The kMeas field is a list of measurement sets (i.e. measurement functions) to use. This only generates sigma points for the first 3 states.
Form
 d = UKFUpdateAtt( d )
Inputs
 d  (.)    UKF data structure
            .m       (:,1)  Mean
            .p       (:,:)  Covariance
            .h       {}    Measurement function pointers
            .hData   {}    Measurement function data
            .kH      (1,:)  Which measurements are in y
            .r       {}    Measurement covariance matrices
            .y       (1,1)  Measurement data structure
                            .data   (m,1) Measurements
                           .param  (1,1) Parameter data structure
                                          .hFun  (1,:) Measurement function pointer
                                          .hData (1,1) Measurement function data structure
                                          .r     (m,m) Measurement covariance
            .w       (:,:)  Weighting matrix
            .wM      (:,1)  Weights
            .kMeas   (1,:)  Measurement sets to use.
Outputs
 d  (1,1)  UKF data structure
            .m       (:,1)  Mean
            .p       (:,:)  Covariance
            .v       (m,1)  Residuals
References UKF().
VM2Electrons()
function VM2Electrons (in v, in c)
 Since version 8.
Form
 VM2Electrons;
 VM2Electrons( v );
 VM2Electrons( v, c );
 e =  VM2Electrons( v )
 e =  VM2Electrons( v, c )
Inputs
 v                 (:)    Visual magnitude
 c                 (1,1)  Amps/W
Outputs
 e                 (:)    Electrons (e-/s/mm^2)
References Demo(), Plot2D(), VM2Electrons(), and VM2Int().
Referenced by VM2Electrons().
VM2PSFPeak()
function VM2PSFPeak (in vM, in pSF, in lambda, in a, in tau, in pSFData, in xLim, in yLim)
Computes the value integrated over time tau. The number of photons is approximated assuming they are all at the specified wavelength.
The PSF data must correspond to the dimensions of the PSF in the focal plane. The units of sigma and xLim must be consistent. For example for a Gaussian PSF sigma might be 20 microns so xLim and yLim should be +/- 100.
Integration is done in xy-coordinates so the PSF does not have to be symmetric. The PSF function has the form
 f = RHS_PSF(x,y,d)
Type VM2PSFPeak for a demo using RHSGaussianPSF.
Form
[p,photons] = VM2PSFPeak(vM, pSF, lambda, a, tau, pSFData, xLim, yLim)
Inputs
 vM      (1,:)   Visual Magnitude
 pSF      (*)    Pointer to point spread function
 lambda  (1,1)   Wavelength (nm)
 a       (1,1)   Aperture (mm)
 tau     (1,1)   Integration time (s)
 pSFData  (.)    Data structure for the PSF function
                 .r   (2,:) Centers of PSF
                 .i   (1,:) Intensities of PSF
                 .d    (.)  Data structure for PSF parameters
 xLim    (1,2)   X limits
 yLim    (1,2)   Y limits
Outputs
 p       (1,:)   Magnitude of the PSF
 photons (1.:)   Total number of photons for each PSF
References and(), Demo(), RHSGaussianPSF(), vector(), VM2Int(), VM2PSFPeak(), and Wavelength().
Referenced by VM2PSFPeak().
WorldToCamera()
function WorldToCamera (in q, in t, in xW, in f, in s, in o)
Type WorldToCamera for a demo
Form
 WorldToCamera;   % demo
 xC = WorldToCamera(q,t,xW,f,s,o)
Inputs
 q   (4,1) Quaternion from world to camera
 t   (3,1) Translation in the world
 xW  (3,:) Points in the world
 f   (1,1) Focal length
 s   (1,1) Pixel width in the same units as f
 o   (2,1) Focal plane offset in pixels
Outputs
 xC  (2,:) Points in the focal plane in pixels
Reference: Trucco, E. and A. Verri, "Introductory Techniques for 3-D Computer Vision," Prentice-Hall, pp. 125-130.
See also
RelativeStateFromPoints
References and(), Demo(), length(), Q2Mat(), RelativeStateFromPoints(), and WorldToCamera().
Referenced by RelativeStateFromPoints(), and WorldToCamera().
YawRollGyroCompassing()
function YawRollGyroCompassing (in x, in omega, in dT, in wo)
 Computes the angle derivative and state transition matrix for
 roll-yaw gyromcompassing. This system works when you have
 rate information and roll and pitch angles. You can then
 estimate yaw. This works if roll and pitch rates are small.
Form
 [xDot, phi] = YawRollGyroCompassing( x, omega, wo )
Inputs
 x            (3,1)     Angle vector (rad)
 omega        (3,1)     Body rates in the body frame (rad/sec)
 dT           (1,1)     Time step
 wo           (1,1)     Frame rotation rate (rad/sec)
Outputs
 xDot         (3,1)     Angle derivative (rad/sec)
 phi          (3,3)     State transition matrix
References and(), and vector().
Referenced by RYGCAttDet().