PSS MATLAB Toolboxes: Dynamics Functions
Dynamics Functions
Dynamics Module
The Dynamics module functions are grouped into directories.
Directories
directory Automotive
directory Plasma
directory Process
directory Robotics
Description
Functions
function DBump (in t, in d)
Model of a quarter automobile model for the suspension.
function DrawRobot (in action, in varargin)
Draw a robot.
function DrawSCARA (in action, in x)
Draw a SCARA.
function ELM (in tau1, in tau2, in k, in t)
Disturbance in a Tokamak plasma due to edge localized modes (ELMs).
function FrictionSmooth (in x, in d)
Smooth friction model.
function HpH (in pH, in x, in d)
pH measurement of a pH process.
function MuFermenter (in x, in d)
Computes the specific growth rate of a fermenter.
function RHSAutoSuspension (in x, in t, in d)
Model of a quarter automobile for the suspension with a hydraulic actuator.
function RHSBatchR (in x, in ignoredArg, in d)
Model of a batch reactor.
function RHSBZ (in ignoredArg, in state, in ignoredArg, in d)
Model of a Belousov-Zhabotinskii reactor.
function RHSCSTR (in x, in t, in d)
Model of continuously-stirred tank reactors in series.
function RHSCSTRStartup (in x, in t, in d)
Model the startup of a CSTR.
function RHSFermenter (in x, in ignoredArg, in d)
Model of a constant volume reactor.
function RHSFluidizedBed (in x, in ignoredArg, in d)
Model of a Fluidized bed.
function RHSICSTR (in x, in ignoredArg, in d)
Model of CSTR with an irreversible first order reaction.
function RHSpH (in x, in ignoredArg, in d)
Simulates a simple model of a pH process.
function RHSRobot (in x, in ignoredArg, in h)
Robot dynamics model.
function RHSRobotInitialize (in varargin)
Robot dynamics model initialization.
function RHSTPVC (in x, in t, in d)
Simulates a model of the vertical position of a plasma in a Tokamak.
function SCARAIK (in r, in theta, in d)
Generate SCARA states for desired end effector position and angle.
function SSTokamak (in d)
Generates a state space model of a tokamak.
Function Documentation
DBump()
function DBump (in t, in d)
It includes a hydraulic actuator. Bumps occur with the frequency wBump.
Form
 r = DBump( t, d )
Inputs
 t           (1,1) Time
 d           (.)   data structure
                   .aBump   (1,1) Bump amplitude (m)
                   .wBump   (1,1) Bump frequency (rad/sec)
Outputs
 r           (1,1) Bump
Reference: Lin, J. and I. Kanellakopoulos (1997.) Nonlinear Design of Active Suspensions. IEEE Control Systems Magazine, June 1997. pp. 45-59.
References and().
Referenced by RHSAutoSuspension().
DrawRobot()
function DrawRobot (in action, in varargin)
 This uses the data structure created with RHSRobotInitialize.m. You
 need to define the following parameters in RHSRobotInitialize.m
 to use this routine:
 'robot name'
 'name'
 'radius'
 'parent'
 'state'
 'link vector'
 'hinge'
 'transformation matrix'
 Type DrawRobot for a demo.
Form
 m = DrawRobot( action, varargin )
Inputs
 action      (1,:) 'initialize', 'update' or 'close'
 'initialize'
h (1,1) Data structure
 'update'
x (:,1) State
 h           (:,1) Data structure
 tPause      (1,1) Time to pause between updates (sec)
 'close'
Outputs
 m           (1,:) If there is an output it makes a movie
References close(), Demo(), DrawRobot(), Initialize(), RHSRobotInitialize(), vector(), and zeros().
Referenced by DrawRobot().
DrawSCARA()
function DrawSCARA (in action, in x)
 The SCARA acronym stands for Selective Compliance Assembly Robot Arm
 or Selective Compliance Articulated Robot Arm.
 Type DrawSCARA for a demo.
Form
 d = DrawSCARA( 'defaults' )
 DrawSCARA( 'initialize', d )
 m = DrawSCARA( 'update', x )
Inputs
 x       (4,:) [theta1;theta2;d4;theta4]
 or
 d       (1,1) Data structure for dimensions
               .a1 (1,1) Link arm 1 joint to joint
               .a2 (1,1) Link arm 2 joint to joint
               .b  (1,3) Box dimensions [x y z] See Box
               .z1 (1,1) Z position of link 1 and link2
               .l1 (1,5) Link arm 1 dimensions [x y z t d] See UChannel
               .l2 (1,3) Link arm 2 dimensions [x y z] See Box
               .c1 (1,2) Cylinder 1 [r l]
               .c2 (1,2) Cylinder 2 [r l]
               .c3 (1,2) Cylinder 2 [r l]
               .c4 (1,2) Cylinder 2 [r l]
               .l4 (1,5) Hand dimensions [x y z t d] See UChannel
Outputs
 m       (1,:) If there is an output it makes a movie
 Tsai, Lung-Wen, "Robot Analysis," Wiley, p. 112.
References and(), Box(), Demo(), DrawSCARA(), Frustrum(), Initialize(), Mag(), NewFig(), set(), UChannel(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by DrawSCARA(), SaveMovie(), and SCARAIK().
ELM()
function ELM (in tau1, in tau2, in k, in t)
These disturbances repeat. Thus, every tau3, set t = 0.
Form
 eLM = ELM( tau1, tau2, k, t )
Inputs
 tau1        (1,1) Time constant 1
 tau2        (1,1) Time constant 2
 k           (1,1) Gain
 t           (1,:) Time
Outputs
 d            (1,:1) State derivative
Reference: Scibile, L. and B. Kouvaritakis (2001.) "A Discrete Adaptive Near-Time Optimum Control for the Plasma Vertical Position in a Tokamak." IEEE Transactions on Control System Technology. Vol. 9, No. 1, January 2001.
References and(), Plot2D(), and set().
FrictionSmooth()
function FrictionSmooth (in x, in d)
 This model uses functions that are differentiable. x may be an array
 and d has coefficients for different joints. f is a two dimensional
 array with one row per element of d and one column per element of x.
 Type FrictionSmooth
Form
 f = FrictionSmooth( x, d )
Inputs
 x  (n,:)   Rate (linear or angular)
 d  (1,1)   Friction data structure
             .fStatic   (1,1)   Static friction maximum
             .kStatic    (1,1)  Static friction scaling coefficient
             .fCoulomb   (1,1)  Coulomb friction maximum
             .kCoulomb   (1,1)  Coulomb friction scaling coefficient
                                 (higher means a faster rise)
             .bViscous   (1,1)  Viscous friction coefficient
Outputs
 f  (n,:)   Friction
References and(), Demo(), Friction(), FrictionSmooth(), Initialize(), Plot2D(), and zeros().
HpH()
function HpH (in pH, in x, in d)
The process consists of an acid (HNO3) stream, buffer (NaHCO3) stream, and base (NaOH) stream that are mixed in a stirred tank. The chemical equilibria is modeled by introducting two reaction invariants for each inlet stream.
 +        -         -         =
 wAi = [H ]i - [OH ]i - [HCO3]i - 2[CO3]i
 -         =
 wBi = [H2CO3]i + [HCO3]i + 2[CO3]i
Form
 y = HpH( pH, x, d )
Inputs
 pH          (1,1) Measurement
 x           (3,1) State [wA4;wB4;h]
 d           (1,1) Structure
                   .wA1       (1,1) See above
                   .wA2       (1,1)
                   .wA3       (1,1)
                   .wB1       (1,1)
                   .wB2       (1,1)
                   .wB3       (1,1)
                   .pK1       (1,1) Base 10 log of equilibrium constant
                   .pK2       (1,1) Base 10 log of equilibrium constant
                   .a         (1,1) Crossectional area of mixing tank
                   .cV        (1,1) Valve coefficient
                   .n         (1,1) Valve exponent
                   .z         (1,1) Vertical distance between bottom of
                                    tank and outlet of effluent
                   .q1        (1,1) Volumetric flow of HNO3
                   .q2        (1,1) Volumetric flow of NaHCO3
                   .q3        (1,1) Volumetric flow of NaOH
Outputs
 y           (1,1) Quantity to be zeroed
Reference: Henson, M. A. and D. E. Seborg. (1997.) Nonlinear Process Control Prentice-Hall. pp. 207-210.
References and().
MuFermenter()
function MuFermenter (in x, in d)
Form
 mu = MuFermenter( x, d )
Inputs
 x           (4,1) State [CA1;T1;CA2;T2]
 d           (1,1) data structure
                   .yXS      (1,1)   Cell-mass yield parameter
                   .beta     (1,1)   Yeild parameter
                   .pM       (1,1)   Constant parameter
                   .kI       (1,1)   Constant parameter
                   .sF       (1,1)   Dilution rate
                   .d        (1,1)   Yield parameter
                   .alpha    (1,1)   Maximum specific growth rate
                   .muM      (1,1)   Constant parameter
                   .kM       (1,1)   Feed substrate concentration
Outputs
 mu          (3,1) State derivative
Reference: Henson, M. A. and D. E. Seborg. (1997.) Nonlinear Process Control, Prentice-Hall. pp. 203-204.
References and(), and Constant().
Referenced by RHSFermenter().
RHSAutoSuspension()
function RHSAutoSuspension (in x, in t, in d)
Form
 xDot = RHSAutoSuspension( x, t, d )
Inputs
 x           (6,1) State
                   [car body displacement;...
                    car body rate;...
                    wheel displacement;...
                    wheel rate;...
                    pressure drop across the piston;...
                    spool valve displacement]
 t           (1,1) Time
 d           (.)   Data structure
                   .mB    (1,1)  Body mass (kg)
                   .mUS   (1,1)  Wheel mass (kg)
                   .kA    (1,1)  Spring constant (N/m)
                   .cA    (1,1)  Damping constant (N/(m/sec))
                   .kT    (1,1)  Tire spring constant (N/m)
                   .alpha (1,1)  (N/m^5)
                   .beta  (1,1)  alpha*piston leakage coefficient (1/s)
                   .gamma (1,1)  (N/(m^5/2 kg^1/2)
                   .tau   (1,1)  Spool valve time constant (s)
                   .pS    (1,1)  Supply pressure (Pa)
                   .a     (1,1)  Piston area (m^2)
                   .aBump (1,1)  Bump amplitude (m)
                   .wBump (1,1)  Bump frequency (rad/sec)
References abs(), and(), and DBump().
RHSBatchR()
function RHSBatchR (in x, in ignoredArg, in d)
Form
 xDot = RHSBatchR( x, t, d )
Inputs
 x           (2,1) State [CA;T]
 t           (1,1) Time
 d           (1,1) data structure
                   .dH   (1,1) Delta H/rho*C liter - deg-C/gmole
                   .uA   (1,1) UA/VrhoC 1/s
                   .tC   (1,1) mol/L
                   .k0   (1,1) liter/gmole-sec
                   .eAR  (1,1) Ea/R deg-C
Outputs
 xDot        (2,1) State derivative
Reference: Henson, M. A. and D. E. Seborg. (1997.) Nonlinear Process Control, Prentice-Hall. pp. 312-313.
References and().
RHSBZ()
function RHSBZ (in ignoredArg, in state, in ignoredArg, in d)
Form
 stateDot = RHSBZ( t, state, d )
Inputs
 t           (1,1) Time
 state       (2,1) State [x;z]
 d           (1,1) data structure
                   .eps  (1,1) kC*B/k5*A
                   .q    (1,1) 2*k3*k4/k2*k5
                   .f    (1,1) Stoichiometric factor
Outputs
 stateDot    (2,1) State derivative
Reference: Scott, S.K. (1994.) Oscillations, Waves and Chaos in Chemical Reactions. pp. 27-39.
References and().
RHSCSTR()
function RHSCSTR (in x, in t, in d)
Form
 xDot = RHSCSTR( x, t, d )
Inputs
 x           (4,1) State [CA1;T1;CA2;T2]
 t           (1,1) Time
 d           (1,1) data structure
                   .q    (1,1) Flow rate
                   .qC   (1,1) Coolant flow rate (control)
                   .cAF  (1,1) Concentration of the feed
                   .tF   (1,1) Temperature of feed stream
                   .tCF  (1,1) Temperature of coolant stream
                   .v1   (1,1) Volume tank 2
                   .v2   (1,1) Volume tank 2
                   .k0   (1,1)
                   .eOR  (1,1) E/R
                   .nDH  (1,1) Negative change in enthalpy
                   .rho  (1,1) Density
                   .rhoC (1,1) Density of coolant
                   .cP   (1,1) Specific heat constant pressure
                   .cPC  (1,1) Specific heat const pressure of coolant
                   .hA1  (1,1)
                   .hA2  (1,1)
Outputs
 xDot        (2,1) State derivative
Reference: Henson, M. A. and D. E. Seborg. (1997.) Nonlinear Process Control, Prentice-Hall. pp. 198-199.
References and(), and series().
RHSCSTRStartup()
function RHSCSTRStartup (in x, in t, in d)
Form
 xDot = RHSCSTRStartup( x, t, d )
Inputs
 x           (5,1) State [composition;temperature]
 t           (1,1) Time
 d           (1,1) data structure
                   .v0      (1,1) Flow rate   (ft^3/h)
                   .hR      (1,1) Heat of reaction (Btu/lb-mol-A)
                   .v       (1,1) Tank volume (ft^3)
                   .cA0     (1,1) Conc. propylene oxide (A) lb-mol/ft^3
                   .cB0     (1,1) Conc of water (B)  lb-mol/ft^3
                   .cM0     (1,1) Conc. of methanol (M) lb-mol/ft^3
                   .cPA     (1,1) Specific heat of propylene oxide at
                                  constant pressure Btu/(lb-mol-deg F)
                   .cPB     (1,1) Specific heat of water at constant
                                  pressure Btu/(lb-mol-deg F)
                   .cPC     (1,1) Specific heat of propylene glycol at
                                  constant pressure Btu/(lb-mol-deg F)
                   .cPM     (1,1) Specific heat at methanol constant
                                  pressure Btu/(lb-mol-deg F)
                   .tA1     (1,1) Temperature at water inlet (deg-F)
                   .fA0     (1,1) Flow of A (lb-mol/h)
                   .T0      (1,1) Initial temperature (deg-F)
                   .uA      (1,1) Heat exchanger coef (Btu/h deg-F)
                   .u       (1,1) Control water flow rate (lb mol/h)
                   .thetaCP (1,1) (Btu/(lb-mol-deg F))
Outputs
 xDot        (5,1) State derivative
Reference: Fogler, H. S. (1999.) Elements of Chemical Reaction Engineering. pp. 554-557;
RHSFermenter()
function RHSFermenter (in x, in ignoredArg, in d)
A single, rate limiting substrate promotes biomass growth and product formation.
Form
 xDot = RHSFermenter( x, t, d )
Inputs
 x           (3,1) State [biomass;substrate;product] concentrations
 t           (1,1) Time (unused)
 d           (.)   data structure
                   .yXS      (1,1)   Cell-mass yield parameter
                   .beta     (1,1)   Yeild parameter
                   .pM       (1,1)   Constant parameter
                   .kI       (1,1)   Constant parameter
                   .sF       (1,1)   Dilution rate
                   .d        (1,1)   Yield parameter
                   .alpha    (1,1)   Maximum specific growth rate
                   .muM      (1,1)   Constant parameter
                   .kM       (1,1)   Feed substrate concentration
Outputs
 xDot        (3,1) State derivative
Reference: Henson, M. A. and D. E. Seborg. (1997.) Nonlinear Process Control, Prentice-Hall. pp. 203-204.
References and(), Constant(), and MuFermenter().
RHSFluidizedBed()
function RHSFluidizedBed (in x, in ignoredArg, in d)
Form
 xDot = RHSFluidizedBed( x, t, d )
Inputs
 x           (4,1) State [concentration of A; concentration of B; temp]
 t           (1,1) Time (unused)
 d           (.)   Data structure
                   .lEA     (1,1) Lewis number
                   .lEB     (1,1) Lewis number
                   .betaHat (1,1) Residence time
                   .beta1   (1,1) Heat of reaction
                   .beta2   (1,1) Heat of reaction
                   .gamma1  (1,1) Activation energy
                   .gamma2  (1,1) Activation energy
                   .alpha1  (1,1) Rate constant factor
                   .alpha2  (1,1) Rate constant factor
                   .xAF     (1,1) Concentration of A in the feed stream
                   .xBF     (1,1) Concentration of B in the feed stream
                   .tF      (1,1) Inlet stream temperature
                   .u       (1,1) Control
Outputs
 xDot        (4,1) State derivative
Reference: Henson, M. A. and D. E. Seborg. (1997.) Nonlinear Process Control, Prentice-Hall. p. 244.
References and().
RHSICSTR()
function RHSICSTR (in x, in ignoredArg, in d)
Form
 xDot = RHSICSTR( x, t, d )
Inputs
 x           (4,1) State [composition;temperature]
 t           (1,1) Time (unused)
 d           (.)   Data structure
                   .dA    (1,1)
                   .gamma (1,1)
         b          .b     (1,1)
                   .beta  (1,1)
                   .u     (1,1) Control
Outputs
 xDot        (2,1) State derivative
Reference: Henson, M. A. and D. E. Seborg. (1997.) Nonlinear Process Control Prentice-Hall. pp. 398-399.
References and().
RHSpH()
function RHSpH (in x, in ignoredArg, in d)
The process consists of an acid (HNO3) stream, buffer (NaHCO3) stream, and base (NaOH) stream that are mixed in a stirred tank. The chemical equilibria is modeled by introducing two reaction invariants for each inlet stream.
 +        -         -         =
 wAi = [H ]i - [OH ]i - [HCO3]i - 2[CO3]i
 -         =
 wBi = [H2CO3]i + [HCO3]i + 2[CO3]i
Form
 xDot = RHSpH( x, t, d )
Inputs
 x           (3,1) State [wA4;wB4;h] h is liquid level
 t           (1,1) Time (unused)
 d           (.)   Structure
                   .wA1       (1,1) See above
                   .wA2       (1,1)
                   .wA3       (1,1)
                   .wB1       (1,1)
                   .wB2       (1,1)
                   .wB3       (1,1)
                   .pK1       (1,1) Base 10 log of equilibrium constant
                   .pK2       (1,1) Base 10 log of equilibrium constant
                   .a         (1,1) Crosssectional area of mixing tank
                   .cV        (1,1) Valve coefficient
                   .n         (1,1) Valve exponent
                   .z         (1,1) Vertical distance between bottom of
                                    tank and outlet of effluent
                   .q1        (1,1) Volumetric flow of HNO3
                   .q2        (1,1) Volumetric flow of NaHCO3
                   .q3        (1,1) Volumetric flow of NaOH
Outputs
 xDot        (3,1) State derivative
Reference: Henson, M. A. and D. E. Seborg. (1997.) Nonlinear Process Control, Prentice-Hall. pp. 207-210.
References and().
RHSRobot()
function RHSRobot (in x, in ignoredArg, in h)
 Each hinge has one degree-of-freedom which may be either revolute or
 prismatic. The rotation or translation axis for each hinge is always z.
 Additional transformation matrices are defined in the cell array R.
 This routine is for a general topological tree with no closed loops.
 Branching is allowed. link defines the topological tree. For example
 a six link robot might have link = [0 1 2 3 3 3]. This means that
 link 1 connects to ground, 0. Link 2 connects to link 1. Link 3
 connects to link 2. Links 4, 5 and 6 connect to link 3 so we have
 a branch at link 3.
 linkOrder relates the link to the state vector.
 RHSRobot can take a function for external torques and forces on the
 links.
 [force, torque] = forceFun( x, t, k, forceData )
 where k is the link id
 The name of forceFun is the pointer forceFun. forceFun may be empty.
 u = frictionFun( v, frictionData ) is the friction function. u is
 the joint friction and may be sliding or rotational. cFriction
 is an array of data structures for the friction function. u is an
 array of friction forces and torques.
 u = jointFun( x, jointData ) is the joint torque or force function.
Form
 xDot = RHSRobot( x, t, h )
Inputs
 x       (:,1)   State vector [positions or angles;velocities]
 t       (1,1)   Time (passed to forceFun)
 h       (:,1)   Data structure (n links)
                 .forceFun       (1,:)   Pointer to the link force and torque function.
                 .forceData      (1,1)   Data structure for forceFun
                 .jointFun       (1,:)   Pointer to the jointFun
                 .jointData      (1,1)   Data structure for the joint function
                 .frictionFun   (1,:)   Pointer to the friction function.
                 .frictionData  (1,1)   Friction data structure.
                 .actuatorMap    (1,:)   Maps the u vector to the links.
                 .u              (:,1)   Control vector (of length(h.actuatorMap)
                 .g0             (3,1)   Gravity vector
                 .name           {n}     Link name
                 .inertia        {(3,3)} 3-by-3 inertia matrices.
                 .R              {(3,3)} transformation matrix that rotates the hinge axis into z.
                 .c              {(3,1)} vector from the i hinge to the cm in a link.
                 .r              {(3,1)} vector from the i-1 hinge to the i hinge in a link.
                 .parent         (1,:)   Parent of the link
                 .rParent        (1,:)   Parent hinge vector in the path to this link
                 .hinge          (1,n)   Type of hinge 0 for prismatic 1 for revolute
                 .radius         (1,n)   Radius of the arm
                 .mass           (1,n)   Mass of the link
                 .stateLinkIndex    (1,n)   Maps the links to the state vector.
                 .windVel        (3,1)   Wind velocity vector
                 .cP             {(3,1}) vector from the cm to center of pressure?
 The remaining entries in the data structure h are autogenerated by
 the function RHSRobotInitialize
 .path           {(:)}   The link path to each end point
 .link           (1,n)   Previous link.
 .linkV          (1,n)   Velocity source for link.
 .linkOrder      (1,n)   The order of links in the topological tree.
 .rMap           {(:)}   Maps the r vectors to the links
 .nB             (1,1)   Number of branches
 .branches       {k}     Branches per link
 .nBranches      (:)     Number of branches per link
Outputs
 xDot   (:,1)       State derivative vector
 massMatrix (:,:)   Generalized mass matarix
References and(), connect(), Friction(), length(), RHSRobot(), and vector().
Referenced by RHSRobot(), RHSRobotInitialize(), and WT_MultiBody().
RHSRobotInitialize()
function RHSRobotInitialize (in varargin)
 The initialization function uses parameter pairs. The ones starting with
 name are links. Entering name creates a new link. All link parameters
 for that link must be specified before the next name
 Each hinge has one degree-of-freedom which may be either revolute or
 prismatic. The rotation or translation axis for each hinge is always z.
 Additional transformation matrices are defined in fileName in cell
 array R.
 This routine is for a general topological tree with no closed loops.
 Branching is allowed.
 RHSRobot can take a function for external torques and forces
 [force, torque] = forceFun( k, v, d )
 where k is the link id
 The name of forceFun is the pointer forceFun. forceFun may be empty.
 u = frictionFun( v, cFriction ) is the friction function. u is
 the joint friction and may be sliding or rotational. cFriction
 is an array of data structures for the friction function. u is an
 array of friction forces and torques.
Form
 h = RHSRobotInitialize( varargin )
Inputs
Outputs
 h       (:,1)   Data structure (n links)
                 .robotName      (1)     Robot name
                 .forceFun       (1,:)   Pointer to the link force and torque function.
                 .forceData      (1,1)   Data structure for forceFun
                 .jointFun       (1,:)   Pointer to the jointFun
                 .jointData      (1,1)   Data structure for the joint function
                 .frictionFun   (1,:)   Pointer to the friction function.
                 .frictionData  (1,1)   Friction data structure.
                 .actuatorMap    (1,:)   Maps the u vector to the links.
                 .u              (:,1)   Control vector (of length(h.actuatorMap)
                 .g0             (3,1)   Gravity vector
                 .name           {n}     Link name
                 .inertia        {(3,3)} 3-by-3 inertia matrices.
                 .R              {(3,3)} transformation matrix that rotates the hinge axis into z.
                 .c              {(3,1)} vector from the i hinge to the cm in a link.
                 .r              {(3,1)} vector from the i-1 hinge to the i hinge in a link.
                 .parent         {n}     parent of current link
                 .rParent
                 .hinge          (1,n)   Type of hinge 0 for prismatic 1 for revolute
                 .radius
                 .mass
                 .stateLinkIndex    (1,n)   Maps the links to the state vector.
                 .windVel        {(3,1)} Wind velocity vector
                 .cP             {(3,1}) vector from the cm to center of pressure
                 .fname          (1)     Name of .mat file to load data structure from
 The remaining entries in the data structure h are autogenerated by
 the function RHSRobotInitialize
 .path           {(:)}   The link path to each end point
 .link           (1,n)   Previous link.
 .linkV          (1,n)   Velocity source for link.
 .linkOrder      (1,n)   The order of links in the topological tree.
 .rMap           {(:)}   Maps the r vectors to the links
 .nB             (1,1)   Number of branches
 .branches       {k}     Branches per link
 .nBranches      (:)     Number of branches per link
References and(), Friction(), length(), RHSRobot(), and vector().
Referenced by DrawRobot().
RHSTPVC()
function RHSTPVC (in x, in t, in d)
Form
 xDot = RHSTPVC( x, t, d )
Inputs
 x           (3,1) State [wA4;wB4;h]
 t           (1,1) Time
 d           (1,1) Structure
                   .a         (1,1) State space model
                   .b         (1,1)
                   .c         (1,1)
                   .d         (1,1)
                   .v         (1,1)
                   .eLM       (1,1) Edge limited mode disturbance
Outputs
 xDot        (3,1) State derivative
Reference: Scibile, L. and B. Kouvaritakis (2001.) "A Discrete Adaptive Near-Time Optimum Control for the Plasma Vertical Position in a Tokamak." IEEE Transactions on Control System Technology. Vol. 9, No. 1, January 2001.
References and().
SCARAIK()
function SCARAIK (in r, in theta, in d)
 Type SCARAIK for a demo.
Form
x = SCARAIK(r, theta)
Inputs
 r          (3,:) End effector position
 theta      (1,:) End effector angle
 d          (1,1) Geometry data structure
                  .a1 (1,1) Link 1 length
                  .a2 (1,1) Link 2 length
                  .z1 (1,1) Distance of link 4 from ground
Outputs
 x          (4,:) SCARA states
References and(), Demo(), DrawSCARA(), length(), RHS(), SCARAIK(), and zeros().
Referenced by SCARAIK().
SSTokamak()
function SSTokamak (in d)
The output is the vertical current moment of the plasma current centroid. this system is unstable.
Type SSTokamak to see the eigenvalues and eigenvectors.
Form
 g = SSTokamak( d )
Inputs
 d  (1,1) Data structure
         .rAA (1,1)  Active coil resistance (Ohm)
         .rVV (1,1)  Passive coil resistance (Ohm)
         .lAV (1,1)  Active-passive coil mutual inductance (H)
         .lAA (1,1)  Active coil self-inductance (H)
         .lVV (1,1)  Passive coil self-inductance  (H)
         .lAP (1,1)  Mutual change inductance between the
                     active coils and plasma displacement (H/m)
         .lVP (1,1)  Mutual change inductance between the
                     passive coils and plasma displacement(H/m)
         .aPP (1,1)  Normalized destabilizing force
                     0.4 to 0.6 e-6 H/m^2
Outputs
 g  (1,1) Statespace object
Reference: Scibile, L, "Non-linear Control of Plasma Vertical Position in a Tokamak," Ph.D Thesis 1997.
References and(), Demo(), DispG(), eig(), EigEval(), Integral(), SSTokamak(), statespace(), and zeros().
Referenced by SSTokamak().