PSS MATLAB Toolboxes: OpticalNavigation Functions
OpticalNavigation Functions
OpticalNavigation Module
Module functions.
Directories
directory Core
Container for general purpose modules.
directory Dynamics
directory LROImages
directory Measurements
directory NeuralNetwork
directory Terrain
directory Utilities
Description
Functions
function AsteroidCentroid (in i, in thresh)
Compute the centroid for an asteroid.
function ImageGallery (in z, in n, in g)
Display images in a gallery.
function LandingConst2DONS (in x, in d)
Equality constraints for the landing for a 2D flat planet problem.
function LandingCost2DONS (in x, in ignoredArg)
Cost for the landing for a 2D flat planet problem.
function LunarTrajectoryControl (in action, in x, in jD, in d)
Generates the 2D lunar landing trajectory.
function MeasRangeGroundStationEF (in x, in d)
Range and range rate to ground station.
function MeasStarAngleAndChord (in x, in d)
Measure star angle and chord.
function NavigationCameraSunStar (in x, in q, in d)
Returns the sun angular radius and intensity and star vectors.
function NavTargetTrackingLunar (in x, in uSCatalog, in rLCatalog, in jD, in fOV)
Selects landmark targets for an optical navigation system.
function NavTargetTrackingPlanetary (in x, in g)
Selects planetary navigation targets for an optical navigation system.
function OpticalNavAccuracy (in d, in fileName)
Computes optical navigation accuracy.
function OpticalNavigation (in action, in d, in varargin)
Implements optical navigation using two targets.
function OpticalNavigationMeasurement (in x, in g)
Computes three types of optical measurements.
function OpticalNavigationMoon (in action, in d, in varargin)
Implements optical navigation using the Moon as a target.
function OpticalNavigationSun (in action, in d, in varargin)
Implements optical navigation using the Sun as a target.
function OpticalNavLunarLandmarkStar (in x, in g, in noise)
Computes optical using lunar landmarks and stars.
function OpticalNavPlanetStar (in x, in g, in noise)
Computes optical measurements for planets and stars.
function OpticalNavPlanetStarNoiseMatrix (in g, in r, in noise)
Computes the noise matrix for navigation with stars and planets.
function OptimalLunarLanding (in a, in h, in n, in opts)
Compute an optimal landing, 2D (fmincon)
function PlanetCentroid (in i, in thresh)
Compute the centroid for a planet.
function PlanetSim2D (in x, in t, in a, in beta)
Simulate a 2D planetary orbit.
function PlotXYTrajectory (in x, in y, in i, in xScale, in name)
Draw an xy trajectory over an image.
function PolarStars (in catalog, in dec, in vMag)
Find polar stars.
function PrintToImage (in f, in fName, in pixelWidth, in res, in type)
Prints specified figure to an image file at a specified size.
function RHSCisLunarMission (in x, in t, in d)
Right hand side for a cislunar mission.
function RHSHelioMission (in x, in t, in d)
Right hand side for a heliocentric mission.
function RHSPlanet2D (in x, in ignoredArg, in a, in beta, in mu)
Right-hand-side for a 2 dimensional planet takeoff.
function RHSPlanet3DONS (in x, in ignoredArg, in d)
Right-hand-side for a 3 dimensional planet takeoff.
function RHSStateLunarMission (in x, in t, in d)
Right hand side for a lunar mission.
function RHSUKFCisLunarMission (in x, in t, in d)
Right hand side for a lunar mission for use in the UKF.
function RHSUKFHelioMission (in x, in t, in d)
Right hand side for a heliocentric mission, for UKF.
function RotateOrbit (in x1, in x2, in mu, in x2S, in pt)
Rotate a 2D trajectory to be in the desired plane.
function SelectTarget (in r1, in r2, in d)
Determines which target to select for optical navigation.
function StitchImages (in s, in tol)
Stitch images together.
function TerrainCamera (in r, in h, in nBits, in w, in nP)
TERRAINCAMERA Models a camera taking a photo of terrain.
Function Documentation
AsteroidCentroid()
function AsteroidCentroid (in i, in thresh)
It uses CannyEnhancer, then creates and binary image and finally does a circle fit. It also does a mean fit.
Type AsteroidCentroid for a demo.
Form
 [x,y,r,xM,yM] = AsteroidCentroid(i,thresh,rF)
Inputs
 i       (:,:,1 or 3) Image, grayscale or RGB.
 thresh (1,1) Threshold for binary conversion
 rF      (1,1) Use simplex for the ellipse fit
Outputs
 x     (1,1) Center x using circle fit
 y     (1,1) Center y using circle fit
 r     (1,1) Radius
 xM    (1,1) Center x using mean fit
 yM    (1,1) Center y using mean fit
References and(), AsteroidCentroid(), CannyEnhancer(), CircleFit(), Demo(), and ShowThreeImages().
Referenced by AsteroidCentroid().
ImageGallery()
function ImageGallery (in z, in n, in g)
Type ImageGallery for a demo
Form
 h = ImageGallery( z, n, g )
Inputs
 z       {:}   Images (or a single image)
 n       (1,1)  Rows
 g       (1,1) Gap
Outputs
 h       (1,1)  Figure handle
References ImageGallery().
Referenced by ImageGallery().
LandingConst2DONS()
function LandingConst2DONS (in x, in d)
The constraint is the terminal altitude and velocities. They must be zero. The function integrates the trajectory to find the values.
Form
 [cIn, cEq, s, t] = LandingConst2DONS( x, d )
Inputs
 x       (:,1)   [beta;dT]
 d        (.)    Data structure describing spacecraft model
Outputs
 cIn    (1,1)   Inequality contraints
 cEq    (3,1)   Equality constraints
 s      (4,:)   States
 t      (1,:)   Corresponding times
References and(), LandingConst2DONS(), Mag(), RHSPlanet2D(), RK4(), and zeros().
Referenced by LandingConst2DONS(), and OptimalLunarLanding().
LandingCost2DONS()
function LandingCost2DONS (in x, in ignoredArg)
 The cost is the total time for the maneuver.
 This is computed from the decision variable.
Form
 cost = LandingCost2DONS( x, ~ )
Inputs
 x       (:,1)   [beta;dT]
 d        (.)    Data structure describing spacecraft model
Outputs
 cost    (1,1)   Total time
References LandingCost2DONS(), and length().
Referenced by LandingCost2DONS(), and OptimalLunarLanding().
LunarTrajectoryControl()
function LunarTrajectoryControl (in action, in x, in jD, in d)
With action 'initialize' it creates an optimal trajectory from the start time to termination. It automatically selects the start time. jD must be less than d.jDTarget. If not, it returns an error.
Type LunarTrajectoryControl for a demo for a polar landing. In progress: 'descend' and 'terminate' actions planned but not yet implemented.
Form
 d = LunarTrajectoryControl( action, x, jD, d )
Inputs
 action  (1,:) Action ('initialize')
 x       (6,1) State ECI Frame (km,km/s)
 jD      (1,1) Julian date
 d       (.)   Data structure
               .dT         (1,1) Time step (s)
               .xTargetLF  (6,1) Target in the LF frame, unused
               .jDTarget   (1,1) Desired landing date
               .xTrajECI   (6,:) Desired trajectory
               .accelMax   (1,1) Acceleration in lunar gravity g
Outputs
 d       (.)   Augmented data structure
               .xTrajECI   (6,:) Desired trajectory
               .tTraj      (1,:) Corresponding times
               .thrustECI  (3,1) ECI thrust vector, unset
               .error      (1,:) Error flag, unset
See also
: OptimalLunarLanding
References and(), Constant(), Date2JD(), DefaultDataStructure(), Demo(), get(), length(), LFToECI(), LunarTrajectoryControl(), Mag(), OptimalLunarLanding(), Period(), Plot2D(), Plot3D(), PlotPlanetaryOrbit(), RotateOrbit(), TimeLabl(), Trajectory(), vector(), and zeros().
Referenced by LunarTrajectoryControl().
MeasRangeGroundStationEF()
function MeasRangeGroundStationEF (in x, in d)
It just uses earth rotation for the ECI to EF conversion. If d.noise is entered it will add Gaussian noise to the measurements.
Form
 y = MeasRangeGroundStationEF( x, d )
Inputs
 x  (6,1)   State [r;v] ECI
 d   (.)    Filter data structure
             .rGS    (3,1) Ground station position
             .noise (2,1) [range;range rate]
             .jD     (1,1) Julian Date
Outputs
 y  (2,1)   [range;range rate]
References and(), Cross(), EarthRot(), JD2T(), and Mag().
MeasStarAngleAndChord()
function MeasStarAngleAndChord (in x, in d)
It allows two targets. Target 2 is the central body. Target 1 is any other body. For example Target 2 could be the Earth or Sun and Target 1 the Moon or Mars. The central body is the gravitational reference.
Form
 d = MeasStarAngleAndChord
 [y,d] = MeasStarAngleAndChord( x, d )
Inputs
 x  (6,1)   State [r;v] ECI
 d  (.)     Data structure
           .target     (1,1) Target that is in use
           .type       (1,1) 1 = centroid, 2 = horizon
           .ref        (1,1) Target reference (2 is the central body)
           .r1         (3,1) Position of body 1
           .v1         (3,1) Velocity of body 1
           .aBody1     (1,1) Radius of body 1 (km)
           .aBody2     (1,1) Radius of body 2 (km)
           .cam        (.)   Camera data structure
Outputs
 y  (:,1)   [ang;chord]
References and(), HorizonUnitVectors(), Mag(), MeasStarAngleAndChord(), Unit(), and vector().
Referenced by MeasStarAngleAndChord().
NavigationCameraSunStar()
function NavigationCameraSunStar (in x, in q, in d)
Assumes a pinhole camera model. It returns the pixel locations for the stars in the field of view. For the sun it returns the flux and the angular radius as separate measurements.
Hipparcos is the default star catalog.
d.camera = PinholeCameraStruct;
The default camera has a 15 degree field-of-view.
This function does not handle planetary eclipses.
Type NavigationCameraSunStar for a demo.
Form
 d = NavigationCameraSunStar;  % Returns the data structure
 y = NavigationCameraSunStar( x, q, d )
Inputs
 x     (3,1) Heliocentric position of the sensor (km)
 q     (4,:) Quaternion from ECI to the navigation camera
 d     (.)   Data structure
             .starCatalog       (.)     Star catalog data structure
             .camera         (.)     Camera data structure
Outputs
 y     (.)   Measurement data structure
             .star     (.)   Star measurement data structure
             .angRad   (1,:) Sun angular radius (rad)
             .radiance (1,:) Sun radiance (km)
References and(), DefaultDataStructure(), Demo(), LoadCatalog(), Mag(), NavigationCameraSunStar(), PinholeCameraStruct(), PinholeStarCamera(), Q2Mat(), StarCameraViewer(), and zeros().
Referenced by NavigationCameraSunStar().
NavTargetTrackingLunar()
function NavTargetTrackingLunar (in x, in uSCatalog, in rLCatalog, in jD, in fOV)
 The idea is to pick 3 stars and 3 landmarks on each pass.
 This way the errors are randomized. The total number of measurements
 from this set is 11. There are 2 landmark/landmark angles and 9
 landmark/star angles.
 The algorithm assumes that all landmarks are visible.
 The algorithm picks 2 stars that are close to the moon and one that is near
 the +z ECI axis. It picks 3 landmarks from rLCatalog randomly every
 time it is called. This function uses MoonV2 for the moon ephemeris.
 It randomly selects the pole star from the set within the field of
 view.
 Since version 9.
Form
 NavTargetTrackingLunar;
 [uS, rL] = NavTargetTrackingLunar( x, uSCatalog, rLCatalog, jD, fOV )
Inputs
 x            (:,1) ECI position of sensor [r;...]
 uSCatalog    (3,:) Star unit vectors
 rLCatalog    (3,:) ECI position vectors of landmarks
 jD           (1,1) Julian date
 fOV          (1,1) Sensor field of view
Outputs
 uS           (3,3) Three stars
 rL           (3,3) Three landmarks
References and(), close(), Constant(), Date2JD(), Demo(), get(), isempty(), length(), LoadCatalog(), MoonV2(), NavTargetTrackingLunar(), RaDec2U(), set(), and Unit().
Referenced by NavTargetTrackingLunar().
NavTargetTrackingPlanetary()
function NavTargetTrackingPlanetary (in x, in g)
 Tracks one planet and 3 stars about that planet plus three polar stars
 in 'polar star' mode. In 'two planet' mode it tracks two planets
 and up to three stars around each planet
Form
 NavTargetTrackingPlanetary;
 g = NavTargetTrackingPlanetary( x, g )
Inputs
 x            (:,1) ECI position of sensor [r;...]
 g            (1,1) Data structure
                    .uSCatalog    (3,:) Star unit vectors
                    .pCatalog     (1,1) Planetary ephemeris data structure
                    .jD           (1,1) Julian date
                    .fOV          (1,1) Sensor field of view
                    .trackPlanet  (1,1) Planet id being tracked
                    .trackCount   (1,1) Counts looing at the planet
                    .trackCountMax(1,1) Maximum counts
                    .mode         (1,:) 'polar star', 'two planet'
Outputs
 g            (1,1) Additions to data structure
                    .uS           (3,:) Stars
                    .nS           (1,1) Number of stars for the planet
                    .rP           (3,1) Planet position
                    .kP           (1,1) Planet ids
References and(), Constant(), Date2JD(), Demo(), Dot(), isempty(), JD2T(), length(), LoadCatalog(), Mag(), NavTargetTrackingPlanetary(), Planets(), plus(), RaDec2U(), SolarSys(), Unit(), and zeros().
Referenced by NavTargetTrackingPlanetary(), and OpticalNavPlanetStarNoiseMatrix().
OpticalNavAccuracy()
function OpticalNavAccuracy (in d, in fileName)
 Assumes that one camera looks at the polar star field and the other
 looks at planets.
 At each point in the trajectory the planet camera cycles through all
 selected planets. This function uses moderate precision ephemerides
 but these are suitable for accuracy measurements.
 Planet numbers are 1-9 for Mercury through Pluto and 301 for the moon.
 Since version 11.
Form
 s = OpticalNavAccuracy( d, fileName )
Inputs
 d     (1,1) Data structure
Outputs
 f     (3,:) [x;y;z] accuracy vs time.
References and(), Constant(), Date2JD(), Demo(), isempty(), JD2T(), OpticalNavAccuracy(), Planets(), PolarStars(), and SolarSys().
Referenced by OpticalNavAccuracy().
OpticalNavigation()
function OpticalNavigation (in action, in d, in varargin)
This function implements orbit determination in a two body system. system. It allows for two types of measurements, planet chord and planet horizon. The latter is used when the spacecraft is near a planet or moon and it is too close to see the whole planet. The function assumes that the camera is pointing so that it sees the whole planet or the horizon.
The function assumes that the navigation camera points instantly at the target. It does not require a star camera.
There are three actions: 'initialize,' 'get unit vector,' and 'update.' 'initialize' sets the output to the input r and v. 'get unit vector' gets the pointing vector for the navigation camera. This is sent to the camera. 'update' updates the filter.
Form
 d = OpticalNavigation
 OpticalNavigation( 'initialize', d, r, v )
 OpticalNavigation( 'ukf parameters', q, p, alpha, f )
 OpticalNavigation( 'get unit vector', d, rPlanet, vPlanet, r, v )
 OpticalNavigation( 'update', d, y, rPlanet, vPlanet, r, v )
 OpticalNavigation( 'update trn', d, y, rPlanet, vPlanet, r, v )
 [d,rE,vE] = OpticalNavigationMoon( action, d, varargin )
Inputs
 action  (1,:) 'initialize,' 'get unit vector,' and 'update'
 d       (.) Data structure
             .starCat    (.) Star catalog data structure
             .uStarCat   (3,:) Unit vectors for the stars
             .aBody1    (1,1) Radius of the first body (km)
             .aBody2     (1,1) Radius of the second body (km)
             .uCamera    (3,1) Unit vector for camera in body frame
             .dNav       (.)   Navigation camera data structure
             .rE         (3,1) Spacecraft position vector (km)
             .vE         (3,1) Spacecraft velocity vector (km/s)
             .dT         (1,1) Time step (s)
             .rES        (3,1) Static solution position estimate (km)
             .vES        (3,1) Static solution velocity estimate (km/s)
             .rESOld     (3,1) Static solution old position estimate
             .useStatic  (1,1) If 1 return the static solution
             .target     (1,1) 1 = moon, 2 = Earth
             .type       (1,1) 1 = horizion, 2 = centroid
             .halfAng    (1,1) Navigation camera half field-of-view
 meas    (.)   Navigation camera data struture
 rMoon   (3,1) Moon position vector (km)
 vMoon   (3,1) Moon velocity vector (km/s)
 r       (3,1) Spacecraft position vector (km)
 v       (3,1) Spacecraft velocity vector (km/s)
Outputs
 d       (.) Data structure
References and(), close(), DefaultDataStructure(), OpticalNavigation(), Unit(), and vector().
Referenced by OpticalNavigation().
OpticalNavigationMeasurement()
function OpticalNavigationMeasurement (in x, in g)
This routine computes up to 5 measurements. You enter information in g for up to 2 planets. The data is
 vector from the reference center to planet 1
 radius of planet 1
 star near planet 1
 vector from the reference center to planet 2
 radius of planet 2
 star near planet 2
The first two are required. The remainder are optional You will get the following angular measurements
 chord of planet 1
 angle between star and planet 1
 chord of planet 2
 angle between star and planet 2
 angle between planet 1 and planet 2
Type OpticalNavigationMeasurement for a demo. The demo rotates the spacecraft around the center but everything else is fixed.
Form
 y = OpticalNavigationMeasurement( x, g )
Inputs
 x     (n,1) [x;y;z;...]
 g     (1,1) Data structure
             .l1                  (3,1)   Vector to planet 1
             .a1                  (1,1)   Planet 1 radius
             .u1                  (3,1)   Unit vector to star 1*
             .l2                  (3,1)   Vector to planet 2*
             .a2                  (1,1)   Planet 2 radius*
             .u2                  (3,1)   Unit vector to star 2*
                                          *optional
Outputs
 y     (5,1) Measurement [chord1;star/planet1;chord2;star/planet2;planet/planet]
References and(), Constant(), Demo(), get(), OpticalNavigationMeasurement(), Unit(), vector(), and zeros().
Referenced by OpticalNavigationMeasurement().
OpticalNavigationMoon()
function OpticalNavigationMoon (in action, in d, in varargin)
This function implements static orbit determination in the Earth-Moon system. It allows for two types of measurements, planet chord and planet horizon. The latter is used when the spacecraft is near a planet or moon and it is too close to see the whole planet. The function assumes that the navigation camera points instantly at the target. It does not require a star camera.
There are three actions: 'initialize,' 'get unit vector,' and 'update.' 'initialize' sets the output to the input r and v. 'get unit vector' gets the pointing vector for the navigation camera. This is sent to the camera. 'update' updates the filter.
This version only has the static solution.
Form
 d = OpticalNavigationMoon
 OpticalNavigationMoon( 'initialize', d, r, v )
 OpticalNavigationMoon( 'get unit vector', d, rMoon, vMoon, r, v )
 OpticalNavigationMoon( 'update', d, y, rMoon, vMoon, r, v )
 [d,rE,vE] = OpticalNavigationMoon( action, d, varargin )
Inputs
 action  (1,:) 'initialize,' 'get unit vector,' and 'update'
 d       (.) Data structure
             .starCat    (.) Star catalog data structure
             .uStarCat   (3,:) Unit vectors for the stars
             .aMoon      (1,1) Radius of the moon (km)
             .uCamera    (3,1) Unit vector for camera in body frame
             .dNav       (.)   Navigation camera data structure
             .rE         (3,1) Spacecraft position vector (km)
             .vE         (3,1) Spacecraft velocity vector (km/s)
             .dT         (1,1) Time step (s)
             .rES        (3,1) Static solution position estimate (km)
             .vES        (3,1) Static solution velocity estimate (km/s)
             .rESOld     (3,1) Static solution old position estimate
             .useStatic  (1,1) If 1 return the static solution
             .target     (1,1) 1 = moon, 2 = Earth
             .type       (1,1) 1 = horizion, 2 = centroid
             .halfAng    (1,1) Navigation camera half field-of-view
 y       (.)   Navigation camera data struture
 rMoon   (3,1) Moon position vector (km)
 vMoon   (3,1) Moon velocity vector (km/s)
 r       (3,1) Spacecraft position vector (km)
 v       (3,1) Spacecraft velocity vector (km/s)
Outputs
 d       (.) Data structure
 rE      (3,1) Estimated position
 vE      (3,1) Estimated velocity
References and(), close(), DefaultDataStructure(), OpticalNavigationMoon(), Unit(), and vector().
Referenced by OpticalNavigationMoon().
OpticalNavigationSun()
function OpticalNavigationSun (in action, in d, in varargin)
This function implements static orbit determination in the heliocentric system.
The function assumes that the navigation camera points instantly at the sun. It does not require a star camera.
There are three actions: 'initialize,' 'get unit vector,' and 'update.' 'initialize' sets the output to the input r and v. 'get unit vector' gets the pointing vector for the navigation camera. This is sent to the camera. 'update' updates the filter.
This version only has the static solution.
Form
 d = OpticalNavigationSun
 OpticalNavigationSun( 'initialize', d, r, v )
 OpticalNavigationSun( 'get unit vector', d, r )
 OpticalNavigationSun( 'update', d, y, r, v )
 [d,rE,vE] = OpticalNavigationSun( action, d, varargin )
Inputs
 action  (1,:) 'initialize,' 'get unit vector,' and 'update'
 d       (.) Data structure
             .starCat    (.) Star catalog data structure
             .uStarCat   (3,:) Unit vectors for the stars
             .uCamera    (3,1) Unit vector for camera in body frame
             .dNav       (.)   Navigation camera data structure
             .rE         (3,1) Spacecraft position vector (km)
             .vE         (3,1) Spacecraft velocity vector (km/s)
             .dT         (1,1) Time step (s)
             .rES        (3,1) Static solution position estimate (km)
             .vES        (3,1) Static solution velocity estimate (km/s)
             .rESOld     (3,1) Static solution old position estimate
             .useStatic  (1,1) If 1 return the static solution
             .halfAng    (1,1) Navigation camera half field-of-view
 y       (.)   Navigation camera data structure
 r       (3,1) Spacecraft position vector (km)
 v       (3,1) Spacecraft velocity vector (km/s)
Outputs
 d       (.) Data structure
 rE      (3,1) Estimated position
 vE      (3,1) Estimated velocity
References and(), DefaultDataStructure(), OpticalNavigationSun(), Unit(), and vector().
Referenced by OpticalNavigationSun().
OpticalNavLunarLandmarkStar()
function OpticalNavLunarLandmarkStar (in x, in g, in noise)
Inputs
Computes measurements between all landmarks and each star.
Form
 y = OpticalNavLunarLandmarkStar( x, g, noise )
Inputs
 x     (:,1) ECI position of sensor [r;...]
 g     (1,1) Data structure
             .u                   (3,3)   Star unit vectors in ECI
             .rL                  (3,3)   Landmarks in lunar coordinates
             .jD                  (1,1)   Julian date
 noise (1,1) Data structure
             .landmark            (1,1)   Landmark error (m)
             .angle               (1,1)   Angle error (rad)
             .moon                (1,1)   Moon centroid error (m)
             .moonRot             (1,1)   Moon rotation error (rad)
Outputs
 y     (12,1) Measurement [landmark/landmark;landmark1/stars;landmark2/stars]
References and(), DupVect(), Initialize(), MoonRot(), MoonV2(), Q2Mat(), QUnit(), Unit(), and zeros().
OpticalNavPlanetStar()
function OpticalNavPlanetStar (in x, in g, in noise)
Inputs
angles between planets and star/planet angles. Noise may be added. Position noise is added to all 3 axes.
Form
 y = OpticalNavPlanetStar( x, g, noise )
Inputs
 x     (:,1) ECI position of sensor [r;...]
 g     (1,1) Data structure
             .uS                  (3,:)   Star unit vectors in ECI
             .nS                  (1,:)   Number of stars per planet
             .kP                  (1,:)   Planet to use
             .planet              (1,1)   Planet data structure
             .jD                  (1,1)   Julian date
             .mode                (1,:)   'polar star' or 'two planet'
 noise (1,1) Data structure
             .planetPosition      (1,9)   Position error (m)
             .planetRadius        (1,9)   Radius Error
             .angle               (1,1)   Angle error (rad)
Outputs
 y     (:,1) Measurement [chords;planet/planet;planet/star]
References and(), Initialize(), length(), Mag(), Measurements(), Unit(), and zeros().
OpticalNavPlanetStarNoiseMatrix()
function OpticalNavPlanetStarNoiseMatrix (in g, in r, in noise)
Form
 OpticalNavPlanetStarNoiseMatrix
 [dY, rM] = OpticalNavPlanetStarNoiseMatrix( g, r, noise )
Inputs
 g
              .uS   (3,:) Star vectors
              .kP   (1,1) Planet id
              .rP   (3,1) Two planets
              .mode  (1,:) 'polar star' or 'two planet'
 r            (3,1) Position vector
 noise        (1,1) Noise data structure
Outputs
 dY           (1,1) Number of measurements
 rM           (n,n) Measurement noise matrix
References and(), Constant(), Date2JD(), Demo(), JD2T(), LoadCatalog(), Mag(), NavTargetTrackingPlanetary(), OpticalNavPlanetStarNoiseMatrix(), Planets(), RaDec2U(), SolarSys(), Unit(), vector(), and zeros().
Referenced by OpticalNavPlanetStarNoiseMatrix().
OptimalLunarLanding()
function OptimalLunarLanding (in a, in h, in n, in opts)
Computes an optimal trajectory using a planar (2D) orbit model. Assumes a circular initial orbit. The track is along x. Requires fmincon from the Mathworks Optimization Toolbox.
Type OptimalLunarLanding for a demo.
Form
 [x,t,beta] = OptimalLunarLanding( a, h, n, opts )
Inputs
 a       (1,1)   Control acceleration typically 2-3 x lunar g
 h       (1,1)   Initial altitude (km)
 n       (1,1)   Number of decision variable increments
 opts    (.)     fmincon options
Outputs
 x       (4,:)   State [x;y;vX;vY]
 t       (1,:)   Time (s)
 beta    (1,:)   Thrust angle (rad)
References and(), Constant(), Demo(), isempty(), LandingConst2D(), LandingConst2DONS(), LandingCost2D(), LandingCost2DONS(), length(), OptimalLunarLanding(), Plot2D(), TimeLabl(), Trajectory(), Unit(), vector(), and zeros().
Referenced by LunarTrajectoryControl(), and OptimalLunarLanding().
PlanetCentroid()
function PlanetCentroid (in i, in thresh)
It uses CannyEnhancer, then creates and binary image and finally does a circle fit.
Type PlanetCentroid for a demo.
Form
 [c,e] = PlanetCentroid(i,thresh,rF)
Inputs
 i       (:.:) uint8 Image
 thresh (1,1) Threshold for binary conversion
 rF      (1,1) Use simplex for the ellipse fit
Outputs
 x     (1,1) Center x, pixels
 y     (1,1) Center y, pixels
 r     (1,1) Radius, pixels
References and(), CannyEnhancer(), CircleFit(), Demo(), PlanetCentroid(), and ShowThreeImages().
Referenced by PlanetCentroid().
PlanetSim2D()
function PlanetSim2D (in x, in t, in a, in beta)
Type PlanetSim2D for a demo
Form
 xP = PlanetSim2D(x,t,a,beta)
Inputs
 x    (4,1) State vector [r;v]
 t    (1,:) Time vector
 a    (1,1) Acceleration
 beta (1,:) Thrust angle, 0 is along +x
Outputs
 xP   (4,:) Propagated trajectory
See also
: RHSPlanet2D, RK4
References Demo(), length(), PlanetSim2D(), RHSPlanet2D(), RK4(), vector(), and zeros().
Referenced by PlanetSim2D().
PlotXYTrajectory()
function PlotXYTrajectory (in x, in y, in i, in xScale, in name)
Can plot multiple sets of data. Type PlotXYTrajectory for a demo.
Form
 PlotXYTrajectory( x, y, i, xScale, name )
Inputs
 x       (:,:) X coordinates (m)
 y       (:,:) Y coordinates (m)
 i       (n,m) Image
 w       (1,1) x dimension of the image
 xScale  (1,1) Scale of x dimension
 name    (1,:) Figure name
Outputs
 None
References Demo(), NewFig(), PlotXYTrajectory(), set(), and Trajectory().
Referenced by PlotXYTrajectory().
PolarStars()
function PolarStars (in catalog, in dec, in vMag)
 Type PolarStars for a demo.
 Since version 11.
Form
 [u, id] = PolarStars( catalog, dec, vMag )
Inputs
 catalog     (1,:)  Catalog name '' gives 'Hipparcos'
 dec         (1,1)  Modifier to the action
Outputs
 x           (1,3) Color
References abs(), Demo(), LoadCatalog(), NewFig(), PolarStars(), RaDec2U(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by OpticalNavAccuracy(), and PolarStars().
PrintToImage()
function PrintToImage (in f, in fName, in pixelWidth, in res, in type)
The default type is 'png' and res will be computed, if it is not entered.
Type PrintToImage for a demo. The second figure is the saved image.
Form
 PrintToImage( f, fName, pixelWidth res, type )
Inputs
 f           (1,1) figure to print
 fName       (1,:) File name
 pixelWidth  (1,1) Pixel width of printed image
 res         (1,1) Screen resolution
 type        (1,:) 'png' or 'jpg' (default png)
Outputs
 none
References and(), Box(), Demo(), get(), isempty(), and PrintToImage().
Referenced by PrintToImage().
RHSCisLunarMission()
function RHSCisLunarMission (in x, in t, in d)
The reentry vehicle can be controlled using angle of attack and bank angle. This function handles the changing fuel mass as the last state. It calls RHSStateLunarMission for the derivatives of r and v.
Form
 d = RHSStateLunarMission;
 [xDot, rMoon, vMoon, aAero, acc] = RHSCisLunarMission(x,t,d)
Inputs
 x   (7,1) [r;v;m] (km,km/s,kg)
 t   (1,1) Time (s)
 d   (.)   Data structure
           .mu         (2,1) [mu Earth; mu Moon] (km^3/s^2)..
           .ref        (1,1) Orbit reference
           .thrust     (3,1) Thrust vector (kN)
           .jD0        (1,1) Reference Julian data (days)
           .uE         (1,1) Exhaust velocity (m/s)
           .mD         (1,1) Dry mass (kg)
           .cD0        (1,1) Zero lift drag coefficent
           .cLAlpha    (1,1) Lift coefficent
           .s          (1,1) Surface area (m^2)
           .alpha      (1,1) Angle of attack (rad)
           .bankAngle  (1,1) Bank angle (rad);
Outputs
 xDot   (7,1) d[r;v;m/dt] (km,km/s,kg)
 rMoon  (3,1) Position of moon in ECI (km)
 vMoon  (3,1) Velocity of moon in ECI (km/s)
 aAero  (3,1) Aerodynamic acceleration (km/s^2)
 acc    (3,1) Total non-gravitational acceleration  (km/s^2)
See also
RHSStateLunarMission
References and(), Mag(), RHSStateLunarMission(), and vector().
RHSHelioMission()
function RHSHelioMission (in x, in t, in d)
Select between multiple values of the gravitational constant (mu) using the d.ref index
Form
 d = RHSHelioMission
 [xDot, rPlanet, vPlanet, acc] = RHSHelioMission(x,t,d)
Inputs
 x   (7,1) [r;v;m] (km,km/s,kg)
 t   (1,1) Time (s)
 d   (.)   Data structure
           .mu         (2,1) [mu Planet; mu Sun] (km^3/s^2)..
           .ref        (1,1) Orbit reference index
           .thrust     (3,1) Thrust vector (N)
           .jD0        (1,1) Reference Julian data (days)
           .uE         (1,1) Exhaust velocity (m/s)
           .mD         (1,1) Dry mass (kg)
           .x0         (7,1) Default initial state
           .states     {:}   State names
Outputs
 xDot      (7,1) d[r;v;m]/dt (km,km/s,kg)
 rPlanet   (3,1) Position of planet  (km)
 vPlanet   (3,1) Velocity of planet (km/s)
 acc       (3,1) Total non-gravitational acceleration  (km/s^2)
References RHSHelioMission(), and vector().
Referenced by RHSHelioMission().
RHSPlanet2D()
function RHSPlanet2D (in x, in ignoredArg, in a, in beta, in mu)
Form
 d = RHSPlanet2D
 xDot = RHSPlanet2D( x, ~, a, beta )
Inputs
 x       (4,1)  State vector [x;y;vX;vY]
 t       (1,1)  Time (s) (unused)
 a       (1,1)  Thruster acceleration
 beta    (1,1) Thrust angle from the horizontal (rad)
 mu      (1,1) Gravitational parameter, default moon
Outputs
 xDot   (:,1)   d[x;y;vX;vY]/dt
References Mag(), RHSPlanet2D(), and vector().
Referenced by LandingConst2DONS(), PlanetSim2D(), and RHSPlanet2D().
RHSPlanet3DONS()
function RHSPlanet3DONS (in x, in ignoredArg, in d)
Form
 d     = RHSPlanet3D
 xDot  = RHSPlanet3D( x, ~, d )
Inputs
 x       (6,1)  State vector [r;v]
 t       (1,1)  Time (s) (unused)
 d       (.)   Data structure
               .acc (3,1)   Thruster acceleration
               .mu  (1,1)  Gravitational parameter
Outputs
 xDot    (6,1)  d[r;v]/dt
References Mag(), RHSPlanet3D(), and vector().
RHSStateLunarMission()
function RHSStateLunarMission (in x, in t, in d)
This includes all phases from lunar landing to Earth reentry. The reentry vehicle can be controlled using angle of attack and bank angle. It does not include fuel consumption.
Form
 [xDot, rMoon, vMoon, aAero, acc] = RHSStateLunarMission(x,t,d)
Inputs
 x   (6,1) [r;v] (km,km/s)
 t   (1,1) Time (s)
 d   (.)   Data structure
           .mu         (2,1) [mu Earth; mu Moon] (km^3/s^2)..
           .ref        (1,1) Orbit reference 1 is the moon, 2 is the Earth
           .thrust     (3,1) Thrust vector (kN)
           .jD0        (1,1) Reference Julian data (days)
           .uE         (1,1) Exhaust velocity (m/s)
           .mD         (1,1) Dry mass (kg)
           .cD0        (1,1) Zero lift drag coefficent
           .cLAlpha    (1,1) Lift coefficent
           .s          (1,1) Surface area (m^2)
           .alpha      (1,1) Angle of attack (rad)
           .bankAngle  (1,1) Bank angle (rad);
Outputs
 xDot   (7,1) d[r;v;m/dt] (km,km/s,kg)
 rMoon  (3,1) Position of moon in ECI (km)
 vMoon  (3,1) Velocity of moon in ECI (km/s)
 aAero  (3,1) Aerodynamic acceleration (km/s^2)
 acc    (3,1) Total non-gravitational acceleration  (km/s^2)
References and(), APlanet(), AtmDens2(), Constant(), Cross(), JD2000(), Mag(), PlanetPosJPL(), RHSStateLunarMission(), Unit(), and vector().
Referenced by RHSCisLunarMission(), and RHSStateLunarMission().
RHSUKFCisLunarMission()
function RHSUKFCisLunarMission (in x, in t, in d)
The reentry vehicle can be controlled using angle of attack and bank angle.
Form
 [xDot, rMoon, vMoon] = RHSUKFCisLunarMission(x,t,d)
Inputs
 x   (6,1) [r;v;m] (km,km/s)
 t   (1,1) Time (s)
 d   (.)   Data structure
           .mu         (2,1) [mu Earth; mu Moon] (km^3/s^2)..
           .ref        (1,1) Orbit reference
           .mD         (1,1) Dry mass (kg)
Outputs
 xDot   (7,1) d[r;v;m/dt] (km,km/s,kg)
 rMoon  (3,1) Position of moon in ECI (km)
 vMoon  (3,1) Velocity of moon in ECI (km/s)
References and(), APlanet(), Constant(), JD2000(), Mag(), PlanetPosJPL(), and UKF().
RHSUKFHelioMission()
function RHSUKFHelioMission (in x, in t, in d)
This is a three body model with the sun, a planet (or asteroid). Either the sun or the planet/asteroid can be the gravitational center.
Form
 d = RHSUKFHelioMission
 [xDot, rPlanet, vPlanet] = RHSUKFHelioMission(x,t,d)
Inputs
 x   (7,1) [r;v;m] (km,km/s)
 t   (1,1) Time (s)
 d   (.)   Data structure
           .mu         (2,1) [mu Sun; mu Planet] (km^3/s^2)..
           .ref        (1,1) Orbit center reference
           .acc        (3,1) Acceleration vector (km/s^2)
           .jD0        (1,1) Reference Julian data (days)
           .x0         (7,1) Default initial state
           .states     {:}   State names
Outputs
 xDot      (7,1) d[r;v;m]/dt (km,km/s,kg)
 rPlanet   (3,1) Position of secondary body  (km)
 vPlanet   (3,1) Velocity of secondary body (km/s)
 acc       (3,1) Total non-gravitational acceleration  (km/s^2)
References RHSUKFHelioMission(), UKF(), and vector().
Referenced by RHSUKFHelioMission().
RotateOrbit()
function RotateOrbit (in x1, in x2, in mu, in x2S, in pt)
theta rotates in the plane. The original trajectory is in the xy-plane. x2S gives the desired angle of the last element of x1.
Type RotateOrbit for a demo.
Form
 [x1R, b] = RotateOrbit(x1,x2,mu,x2S,pt)
Inputs
 x1      (4,:) State vector [x;y;vX;vY]
 x2      (6,1) Desired orbit plane
 mu      (1,1) Gravitational constant
 x2S     (6,1) Desired ending point of x1 in the x2 plane
 pt      (1,:) 'start' or 'end'
Outputs
 x1R     (6,1)  State vector [r;v]
 b       (3,3) Transformation matrix
References Constant(), CP2I(), Demo(), El2RV(), isempty(), NewFig(), Period(), RotateOrbit(), RV2El(), RVOrbGen(), set(), Unit(), vector(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by LunarTrajectoryControl(), and RotateOrbit().
SelectTarget()
function SelectTarget (in r1, in r2, in d)
Form
 [target, blocked] = SelectTarget(r1,r2,d)
Inputs
 r1 (3,1) Position of target 1 relative to spacecraft
 r1 (3,1) Position of target 2 relative to spacecraft
 d   (.)   Data structure
           .aBody1  (1,1) Radius of target 1
           .aBody2  (1,1) Radius of target 2
Outputs
 target  (1,1) 1 or 2
 blocked (1,1) 1 if farther target is blocked
References Demo(), Mag(), Plot2D(), SelectTarget(), Unit(), and zeros().
Referenced by SelectTarget().
StitchImages()
function StitchImages (in s, in tol)
The images must all be the same size. This will work with color or monochrome images. It assumes the images are aligned.
Type StitchImages for a demo.
Form
 y = StitchImages(s,tol)
Inputs
 s   {:}     Images
 tol (1,1)   Tolerance for comparing pixels
Outputs
 y   (:,:)   Combined image
 oL  (1,n-1) Overlap
References StitchImages().
Referenced by StitchImages().
TerrainCamera()
function TerrainCamera (in r, in h, in nBits, in w, in nP)
Type TerrainCamera for a demo.
Form
 d = TerrainCamera( r, h, nBits, w, nP )
Input
 r       (3,1) Position with respect to the terrain center (m)
 h       (1,1) Handle to the figure with the terrain image
 nBits   (1,1) Pixels in the image from the camera
 w       (1,1) x dimension of the base image
 nP      (1,2) Dimensions of base image
Output
 d      (.)   Data structure
 .p (n,n,3) Pixel map
 .r (2,1) [x;y]
References ColorMapGrayScale(), Demo(), isempty(), NewFig(), and TerrainCamera().
Referenced by TerrainCamera().