PSS MATLAB Toolboxes: LaunchVehicle Functions
LaunchVehicle Functions
LaunchVehicle Module
The LaunchVehicle module functions.
Directories
directory Hypersonic
directory LaunchOpt
directory LaunchSim
directory LVCoord
directory LVData
directory LVDatabase
directory LVGuidance
directory LVModels
directory MultiStage
directory SubOrbital
directory TSTO
Two stage to orbit.
directory Utilities
directory VehicleModels
Description
Functions
function BoostPhaseDeltaV (in v0I, in gamma0, in h0, in hF, in rE, in mu)
Compute DV required to enter circular orbit at hF given V0 and gamma0.
function BurnoutVelocity (in varargin)
Compute the burnout velocity for a multi-stage rocket.
function CreateRocketModel (in mStructure, in mFuel, in thrust, in Isp, in name, in type)
Create a rocket model from individual fields.
function EntryLiftAndDrag (in d, in v, in h)
Models lift and drag for reentry.
function FGravityTurn (in angle, in d, in tPitch)
Cost function for gravity turn to zero flight path angle.
function FMinTOrbitInjection (in x, in d)
Function to be minimized by fmins for MinTOrbitInjection.
function FormatRocketDB (in s)
Reformat the data from the csv file into the standard data structure.
function GetStage (in lv, in k)
Get all of the LV data fields for a particular stage.
function GravityTurnSim2D (in d, in pitchover, in tPitch, in verbose)
Perform a gravity-turn simulation using RHSLaunchVehicle2D.
function GuidedLaunch2DCost (in params, in d, in verbose)
Cost function for the 2D launch via GuidedLaunchOpt2D.
function GuidedLaunch2DRHS (in x, in t, in d)
The right hand side of a guided 2D launch model.
function GuidedLaunch2DSim (in params, in d)
Simulates a 2D guided launch with the specified payload mass.
function GuidedLaunch3D (in rocket, in lla0, in vg0, in altDes, in incDes, in raDes, in jD0, in params)
Simulate a guided launch to LEO, for 'examplerocket'.
function GuidedLaunch3DRHS (in x, in t, in d)
Right hand side for 3D guided launch to orbit in ECI frame.
function GuidedLaunchOpt2D (in name, in scale, in options, in p0)
Compute the parameters to perform a 2D launch into a circular orbit.
function HSVMassEstimation (in d, in tol, in doPlot, in fileName)
Computes high speed vehicle weight using RocketMass to compute the fuel mass.
function IncLatVelToAzimuthHeading (in inc, in lat, in V, in rotation)
Compute azimuth and heading req.d at lat.
function LatLonToRangeAzimuth (in lat0, in lon0, in latF, in lonF, in Rp)
Compute range and azimuth angle from a source site to a destination.
function LaunchConstants (in name, in value)
Uses persistent variables to store launch vehicle constants.
function LaunchGUI ()
Select a launch vehicle, set initial conditions, simulate 2D launch.
function LaunchOptions ()
Specify the options for a launch simulation using GuidedLaunch2D.
function LaunchRHSData (in dimension, in rocket)
Create the data structure needed for launch simulations.
function LaunchSummary (in data)
Print out summary of launch data.
function LaunchTime (in lat, in lon, in inc, in ra, in jD0)
Compute the time until launch, given launch site and desired orbit.
function LiftAndDragSeaLevelToOrbit (in x, in d)
Two dimensional lift and drag with skin friction.
function LSQLaunch (in p0G, in zM, in W, in d, in opts)
Use least squares approach to compute launch conditions.
function LSQLaunchSim (in p0, in d)
Simulate a launch trajectory given initial parameters.
function LVCombineSRB (in lv0)
Combine the SRB(s) and first stage into a new first stage.
function LVModelFeasibility (in lv, in opts)
Compute the feasibility of a given LV model.
function LVModelFeasibilityFix (in lv, in opts)
Fix a launch vehicle model to make it feasible.
function LVModelFeasibilityReport (in dBFile, in opts)
Compute the feasibility of all models in the LVDatabase.csv.
function LVStageTimes (in lvModel, in coastTimes)
Compute the launch vehicle staging times from the model and coast times.
function LVThrustToWeight (in lv)
Compute takeoff thrust to weight ratio for a launch vehicle.
function MinTOrbitInjection (in h, in u, in a, in g)
Constant thrust minimum time orbit injection.
function MSData (in varargin)
Complete the stage data for a multi-stage launch vehicle.
function MSThrustModel (in mFuel, in rocket, in t, in coast)
Simple thrust model for multi-stage vehicle.
function MSVRatio (in sR, in pR, in nStages)
Compute the velocity ratio for a multi-stage rocket.
function NewtonianAeroPropertiesFromOBJFile (in vInf, in fileName)
Computes the normal coefficient of a body in hypersonic flow.
function NewtonianLD3D (in vInf, in alt, in fileName)
Newtonian lift and drag for hypersonic flight in a standard atmosphere.
function OptimalPayloadRatio (in VBO, in Ve, in sR)
Compute the optimal payload ratios for a multi-stage rocket.
function ParallelToSerialStages (in p1, in p2, in m0)
Separate 2 parallel stages with partial overlap, into 2 serial stages.
function PayloadMassForBurnoutVelocity (in d, in vBO)
Compute the payload mass to achieve a given burnout velocity.
function ReentryPlot (in x, in t, in d, in u)
Plot values from reentry simulations.
function RemoveStage (in d, in k)
Remove a stage from a multi-stage data structure.
function RHSLaunchVehicle2D (in x, in t, in d)
The right hand side of a 2D launch model with gravity turn.
function RHSLaunchVehicle3D (in x, in t, in d)
The right hand side of a 3D launch model with gravity turn.
function RHSLiftingReentry3D (in x, in ignoredArg, in d)
The right hand side of a 3D lifting launch vehicle model.
function RHSMinTOrbitInjection (in x, in t, in beta, in g, in a)
RHS for planar equations.
function RHSOptimalFPA (in gamma, in h0, in hF, in v0, in bC)
Compute the delta-V required to raise the orbit to altitude "hF".
function RHSReentry (in x, in ignoredArg, in d)
Non dimensional reentry dynamics model.
function RHSTSTO (in x, in t, in d)
Compute state and mass derivatives for a two-stage launch vehicle.
function RocketDatabase (in name, in file)
Load the properties for a rocket: mS, thrust, ISP, exhaust velocity.
function RocketDrag (in r, in v, in d, in j)
Compute the drag on a rocket using a plate model or Jones/Sears/Haack.
function ScaleVehicle (in d, in scale)
Scale a vehicle's properties.
function SetPayloadMass (in d, in mPLD)
Set payload mass in structure d.
function SS2O (in Isp, in mP, in fS, in dV)
Compute single-stage fuel mass needed to reach a velocity.
function StageTimes (in m)
Compute the ignition and burnout times given stage mass histories.
function SubOrbDistance (in lat0, in lon0, in latF, in lonF, in Rp)
Compute the min angular distance (around the Earth) that connects 2 pts.
function SubOrbLambert (in tFDes, in h0, in hF, in angleDist, in tol, in maxIter)
Find initial velocity and flight path angle that gives desired distance.
function SubOrbMaxRange (in V)
Computes maximum range for a sub-orbital traj.
function SubOrbTrajAnalysis (in lla0, in llaF, in tFDes, in dragIsOn)
Analyze the trajectories for around-the-Earth sub-orbital launches.
function SubOrbVelocity (in gamma, in h0, in hF, in angleDist)
Compute initial velocity and flight time for a sub-orbital trajectory.
function ThrustAngleConstant (in x, in d, in params)
Constant thrust angle control for 2D simulations.
function ThrustAngleExplicit (in x, in d, in params)
Explicit guidance for a 2D launch simulation.
function ThrustAngleGravity (in x, in d, in params)
Gravity turn thrust angle (0 degrees) for 2D simulations.
function ThrustAngleVGain (in x, in d, in params)
Velocity to be gained for a 2D launch simulation.
function ThrustControlConstantAngle (in r, in v, in d, in params)
Thrust control function to apply thrust at a fixed angle above horizon.
function ThrustControlGravityTurn (in r, in v, in d, in params)
Thrust control function during gravity turn.
function ThrustControlRaiseApogee (in r, in v, in d, in params)
Thrust control function to raise the apogee using fminbnd.
function TSFCToIsp (in tSFC)
Convert Thrust Specific Fuel Consumption to Specific Impulse.
function TSTODragData (in dO, in dF)
Generates TSTO drag data for use byLiftAndDragJonesSearsHaack.
function TSTOFlightProfile ()
Computes the TSTO flight profile.
function TSTOSizing (in d, in p, in f, in tol)
Size a horizontal launch/horizontal landing two stage to orbit vehicle.
function TurboRamjetSim (in x, in tEnd, in dT, in d, in plott)
Simulates a turboramjet engine on a fixed flight path angle trajectory.
function VEFToVGamAz (in vEF, in lat, in lon)
Compute the velocity mag, flight path angle and azimuth from a vector.
function VonBraunRocket ()
The fictional Von Braun three-stage space shuttle.
function WingedLaunchVehicleDesign (in varargin)
Provides a layout of a winged launch vehicle.
function WriteEngineData (in fileName, in d)
Write engine data to a table.
Function Documentation
BoostPhaseDeltaV()
function BoostPhaseDeltaV (in v0I, in gamma0, in h0, in hF, in rE, in mu)
 Assumes two delta-v's are applied. First at h0, then at hF.
 Since version 2015.1
Form
 [dV,dV1,dV2,gammaF] = BoostPhaseDeltaV( v0I, gamma0, h0, hF, rE, mu )
Inputs
 v0I        (1,1)     Initial velocity, before the first delta-v (km/s)
 gamma0     (1,1)     Initial flight path angle (rad)
 h0         (1,1)     Initial altitude (km)
 hF         (1,1)     Final altitude for orbit (km)
 rE         (1,1)     Planet radius (default earth)
 mu         (1,1)     Planet gravitational constant  (default earth)
Outputs
 dV         (1,1)     Total delta-v, dV1 + dV2 (km/s)
 dV1        (1,1)     First delta-v at h0 (km/s)
 dV2        (1,1)     Second delta-v at hF (km/s)
 gammaF     (1,1)     Flight path angle at hF (km/s)
See also
OrbitVel2D
References and().
Referenced by RHSOptimalFPA().
BurnoutVelocity()
function BurnoutVelocity (in varargin)
If the model in d has solid boosters, they will be incorporated via LVCombineSRB.
Form
 [vBO,dV,tOF] = BurnoutVelocity( d )
 -or-
 [vBO,dV,tOF] = BurnoutVelocity( mPLD, mSS, sR, Isp, thrust )
Inputs
 d            (.)    Data structure with fields
               .mPLD    (1,1)    Mass of payload (kg)
               .mSS     (1,N)    Mass of structure for each stage (kg)
               .eS      (1,N)    Structural mass ratio for each stage
               .Isp     (1,N)    Specific impulse for each stage (sec)
               .thrust  (1,N)    Thrust for each stage (kN)
 -or-
 mPLD        (1,1)   Mass of payload (kg)
 mSS         (1,N)   Mass of structure for each stage (kg)
 sR          (1,N)   Structural mass ratio for each stage
 Isp         (1,N)   Specific impulse for each stage (sec)
 thrust      (1,N)   Thrust for each stage (kN)
Outputs
 vBO         (1,1)  Burnout velocity [km/s]
 dV          (1,N)  Delta-v for each stage [km/s]
 tOF         (1,N)  Time of flight for each stage [sec]
See also
LVCombineSRB, MS2M
References BurnoutVelocity(), Demo(), LVCombineSRB(), and MS2M().
Referenced by BurnoutVelocity(), LVModelFeasibilityFix(), OptimalPayloadRatio(), and PayloadMassForBurnoutVelocity().
CreateRocketModel()
function CreateRocketModel (in mStructure, in mFuel, in thrust, in Isp, in name, in type)
Specify whether each stage is liquid or solid using 'type'.
Form
 d = CreateRocketModel( mStructure, mFuel, thrust, Isp, name, type )
Inputs
 mStructure    (1,n)    Structural mass of stages
 mFuel         (1,n)    Fuel mass (kg)
 thrust        (1,n)    Thrust (kN)
 Isp           (1,n)    Specific impulse (s)
 name          (1,:)    Name of vehicle
 type          (1,n)    Fuel type: 'l' or 's'
Outputs
 d             (.)      Rocket data structure
References and().
Referenced by VonBraunRocket().
EntryLiftAndDrag()
function EntryLiftAndDrag (in d, in v, in h)
Form
 [lift,drag] = EntryLiftAndDrag( d, v, h )
Inputs
 d  (.)     Data structure for vehicle data
 v   (1,:) Velocity (m/s)
 h   (1,:) Altitude (m)
Outputs
lift (1,:) Lift (N)
drag (1,:) Drag (N)
References Altitude(), and(), DefaultDataStructure(), Demo(), length(), and StdAtm().
FGravityTurn()
function FGravityTurn (in angle, in d, in tPitch)
Returns the final flight path angle. Does not consider the altitude or velocity magnitude.
Form
 cost = FGravityTurn( angle, d, tPitch )
Inputs
 angle       (1,1)  Pitchover angle
 d            (.)   Simulation data
                     .rocket   (.)   Rocket model
 tPitch      (1,1)  Time for pitchover event
Outputs
 cost        (1,1)  Final flight path angle
See also
GravityTurnSim2D, RHSLaunchVehicle2D.
References GravityTurnSim2D(), and RHSLaunchVehicle2D().
FMinTOrbitInjection()
function FMinTOrbitInjection (in x, in d)
 Since version 1.0
Form
 y = FMinTOrbitInjection( x, d )
Inputs
 x           (2,1) [x;y;vX;vY]
 d            (.)  Data structure
                   .f1 (1,1) 2*altitude*height/final horizontal v^2
                   .f2 (1,1) acceleration/gravitational acceleration;
Outputs
 y           (1,1) Cost
References MinTOrbitInjection().
Referenced by MinTOrbitInjection().
FormatRocketDB()
function FormatRocketDB (in s)
 Since version 2015.1
Form
 d = FormatRocketDB( s )
Inputs
 s       (.)    Data structure from csv file
Outputs
 d       (.)    Formatted data structure
Referenced by LVModelFeasibilityReport(), and PayloadMassForBurnoutVelocity().
GetStage()
function GetStage (in lv, in k)
 Since version 2015.1
Form
 s = GetStage( lv, k )
Inputs
 lv        (.)     Launch vehicle data structure
 k         (1,1)   Index of stage to get
Outputs
 s         (.)     Stage data for stage "k"
References and(), get(), and length().
Referenced by LVCombineSRB(), and ParallelToSerialStages().
GravityTurnSim2D()
function GravityTurnSim2D (in d, in pitchover, in tPitch, in verbose)
At a fixed time, the flight path angle will be set discretely to the specified angle, resulting in a gravity-turn trajectory.
The simulation is a fixed-step integration using RK4. The pitchover altitude and velocity will be printed to the screen if verbose is true.
Form
 [traj,t] = GravityTurnSim2D( d, pitchover, tPitch, verbose )
Inputs
 d            (.)   Data structure for RHSLaunchVehicle2D
                    .rocket       (.)   Rocket model from RocketDatabase
                    .cDA         (1,:)  Drag coefficient * area
                    .fControl     {:}   Array of function handles
 pitchover   (1,1)  Pitchover angle from vertical, degrees
 tPitch      (1,1)  Time of the pitchover maneuver
 verbose     (1,1)  Flag for verbose output
Outputs
 traj         (.)   Output data structure
     .t      (1,n)  Time (s)
     .x      (:,n)  State [x h v gamma massFuel]'
     .angle  (1,n)  Control angle (rad)
     .mass   (1,n)  Vehicle mass (kg)
     .thrust (1,n)  Vehicle thrust (kN)
     .drag   (1,n)  Vehicle drag (kN)
     .pitch   (.)   Pitchover conditions
                    .t     Pitchover time
                    .angle Pitchover angle
                    .h0    Pitchover altitude
                    .v0    Pitchover velocity
See also
RHSLaunchVehicle2D, LaunchRHSData, RK4
References and(), RHSLaunchVehicle2D(), RK4(), RocketDatabase(), and set().
Referenced by FGravityTurn().
GuidedLaunch2DCost()
function GuidedLaunch2DCost (in params, in d, in verbose)
Performs a simulation followed by a circularization burn by the specified upper stage.
Form
 [cost,data] = GuidedLaunch2DCost( params, d, verbose )
Inputs
 params       (3,1)  Initial guess at parameters.
 d             (.)   Data structure including launch vehicle model data
                        and all launch options.
                      .rocket
                      .upperStage
 verbose       (1)   Flag to specify whether to print output. Optional.
Outputs
 cost          (1)   Computed cost.
 data          (.)   Data structure with launch results.
See also
GuidedLaunch2DSim, LaunchSummary
References and(), GuidedLaunch2DSim(), GuidedLaunchOpt2D(), LaunchSummary(), OrbMnvrCircularize(), and RV2AE().
Referenced by GuidedLaunch2DSim(), GuidedLaunchOpt2D(), LaunchOptions(), and LaunchSummary().
GuidedLaunch2DRHS()
function GuidedLaunch2DRHS (in x, in t, in d)
The states are vertical and horizontal position, velocity and flight path angle. The model assumes a flat Earth that isn't rotating. The model can handle multiple stages and different fuels for each stage. The dry masses and exhaust velocities are entered using the data structure d. For each stage you add a fuel state to x. Thus a 3 stage vehicle will have 7 states and d.mSS, d.thrust, d.uE and d.cDA (the drag coefficient) will each have three entries.
The control function has the form:
 alpha = fControl( x )
Has a drag model with an exponential atmosphere.
Form
 [xDot,alpha] = GuidedLaunch2DRHS( x, t, d )
Inputs
 x           (:,1)  [x h v gamma massFuel]
 t           (1,1)  Time (not used)
 d            (.)   Data structure
                    .rocket    (.)  Rocket data structure
                    .cDA      (1,:) Drag coefficient of each stage times area
                    .mu       (1,1) Gravitational constant (km/s^2)
                    .Rp       (1,1) Planet radius (km)
                    .fThrust  (1,1) Function handle for thrust model
                    .fControl {1,:} Array of function handles to
                                    determine thrust angle for each
                                    stage. Takes "x" as input.
                    .drag      (.)  Drag data structure
Outputs
 xDot        (:,1)  Derivatives
 alpha       (1,1)  Control angle
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 207-211.
See also
LaunchVehicle2D, LaunchRHSData, LiftAndDragJonesSearsHaack
References and().
Referenced by GuidedLaunch2DSim(), GuidedLaunchOpt2D(), LaunchOptions(), LaunchRHSData(), and LSQLaunchSim().
GuidedLaunch2DSim()
function GuidedLaunch2DSim (in params, in d)
Called from GuidedLaunch2DCost and LaunchGUI. See GuidedLaunch2DRHS for information on the dynamic model and LaunchOptions for further documentation of the data structure. The simulation is terminated when either the altitude or final fuel mass is zero.
For a direct launch, all stages follow a gravity turn. For an indirect launch, the first stage always follows a gravity turn and the last stage always follows a fixed control angle with the intermediate stages as follows:
 3 stages: 1) and 2) gravity turn, 3) fixed angle
 4 stages: 1) and 2) gravity turn, 3) horizontal, 4) fixed angle
Uses ode45 for the integration.
Form
 [time,xTraj,d] = GuidedLaunch2DSim( params, d )
Inputs
 params       (3,1)  Initial guess at parameters.
                      1) initial flight path angle (rad)
                      2) mass of last (solid) stage (%)
                      3) coast time before last stage (min), direct
                          OR thrust angle for last stage (rad), indirect
 d             (.)   Data structure including launch vehicle model data
                      .rocket  (.)    Rocket data
                      .rhsFun   ()    Function handle (GuidedLaunch2DRHS)
                      .fControl {}    Array of function handles
                      .mDes   (1,1)   Desired payload mass (kg)
                      .direct (1,1)   Direct flag
                      .h0     (1,1)   Initial altitude
                      .v0     (1,1)   Initial velocity
Outputs
 time       (nt,1)   Time vector (sec)
 xTraj      (nt,ns)  State vector (output of ode45)
                     [range altitude velocity FPA mSP alpha]
 d           (.)     Data structure supplied to RHS
See also
: GuidedLaunch2DRHS
References and(), FPA(), GuidedLaunch2DCost(), GuidedLaunch2DRHS(), GuidedLaunch2DSim(), LaunchGUI(), LaunchOptions(), length(), RHS(), RocketDatabase(), set(), SetPayloadMass(), vector(), and zeros().
Referenced by GuidedLaunch2DCost(), GuidedLaunch2DSim(), GuidedLaunchOpt2D(), and LaunchGUI().
GuidedLaunch3D()
function GuidedLaunch3D (in rocket, in lla0, in vg0, in altDes, in incDes, in raDes, in jD0, in params)
 Integration is performed with RK4 in the inertial frame.
 Has a built-in demo with a target orbit of 350 km and 51.6 degrees
 inclination. The initial flight path angle is 81 degrees. The rocket
 has four stages and a guidance function is specified for each stage.
 Utilizes three guidance functions:
 1. ThrustControlGravityTurn
 2. ThrustControlConstantAngle
 3. ThrustControlRaiseApogee
 These guidance functions have the form
 [on,thrustDir] = ThrustControlFunction( r, v, d, params )
 Since version 1.0
Form
 d = GuidedLaunch3D( rocket, lla0, vg0, altDes, incDes, raDes, jD0, params )
 params = GuidedLaunch3D
Inputs
 rocket      (.)     Rocket model data structure
 lla0       (3,1)    Latitude, longitude, altitude of launch site [rad; rad; km]
 vg0        (2,1)    Initial velocity and flight path angle [km/s; rad]
                        (Relative to rotating Earth)
 altDes     (1,1)    Desired altitude of orbit        [km]
 incDes     (1,1)    Desired inclination of orbit     [rad]
 raDes      (1,1)    Desired right ascension of orbit [rad]
 jD0        (1,1)    Initial Julian date
 params      (.)
   .J2      (1,1)    Flag. Include J2 effects (1) or not (0). Default 0.
   .cDA     (1,1)    Drag coefficient (times area)
   .fControl {}      Cell array of guidance function handles
   .fParams  {}      Cell array of parameters
Outputs
 d           (.)     Data structure of simulation output
                     .VBO       (1,nS) Velocity at burnout, per stage
                     .gammaBO   (1,nS) FPA at burnout
                     .thetaBO   (1,nS) Angle at burnout
                     .altBO     (1,nS) Altitude at burnout
                     .rangeBO   (1,nS) Range at burnout
                     .kBO       (1,nS) Index of burnout events
                     .timeBO    (1,nS) Time at burnout
                     .time      (1,n)   Time
                     .range     (1,n)   Range
                     .alt       (1,n)   Altitude
                     .xs        (:)   Simulated state
                     .rOP       (:)   State in the orbital plane frame
                     .rEF      (3,:)  Earth-fixed position
                     .gamma     (:)   Flight path angle
                     .mFuel     (:)   Fuel mass
                     .thrustDir (:)   Thrust direction
                     .thrustMag (1,:) Thrust magnitude
See also
GuidedLaunch3DRHS.
References and(), GuidedLaunch3D(), RK4(), ThrustControlConstantAngle(), ThrustControlGravityTurn(), and ThrustControlRaiseApogee().
Referenced by GuidedLaunch3D(), ThrustControlConstantAngle(), ThrustControlGravityTurn(), and ThrustControlRaiseApogee().
GuidedLaunch3DRHS()
function GuidedLaunch3DRHS (in x, in t, in d)
 Compute position, velocity, mass derivatives. The thrust direction is
 computed externally to this function and passed in. There is an option
 for including J2 effects from a full gravity model. Assumes a spherical
 earth and exponential atmosphere.
See also
RHSLaunchVehicle3D, MSThrustModel, AGravity.
Form
 xDot = GuidedLaunch3DRHS( x, t, d )
Inputs
 x         (6+n,1)  State, [r v massFuel]
 t           (1,1)  Time since launch (sec)
 d            (.)   Data structure
                    .rocket     (.)  Rocket model
                    .cDA       (1,:) Drag coefficient of each stage times area (m^2)
                    .Rp        (1,1) Planet radius
                    .omegaE    (3,1) Planet rotation
                    .thrustOn  (1,1) Thrust on flag
                    .thrustDir (3,1) Thrust direction
                    .gravityModel
Outputs
 xDot        (:,1)  Derivatives
References AGravity(), and(), Constant(), Cross(), ECIToEF(), GuidedLaunch3DRHS(), JD2T(), LaunchRHSData(), length(), Limit(), Mag(), MSThrustModel(), RHS(), RHSLaunchVehicle3D(), RocketDatabase(), RPhiTheta2Cart(), vector(), and zeros().
Referenced by GuidedLaunch3DRHS(), and LaunchRHSData().
GuidedLaunchOpt2D()
function GuidedLaunchOpt2D (in name, in scale, in options, in p0)
Uses fminsearch on the cost function in options, then performs a final simulation with the selected parameters. Includes a demo for Pegasus air launch.
Tunable parameters:
initial flight path angle
Last stage mass (fraction of original, keep structural ratio)
DATO: coast time before last stage ignition
SATO/HATO: thrust angle for last stage
The vehicle is simulated using GuidedLaunch2DSim, then the specified upper stage is used to perform a circularization burn.
Form
 data = GuidedLaunchOpt2D( name, scale, options, p0 )
Inputs
 name          (:)   Name of the launch vehicle model to use.
                        Stored in "RocketDatabase.m"
 scale         (1)   Scale to apply to that model.
 options       (.)   Set of launch options, including
                       .costFun, i.e. GuidedLaunch2DCost
                       .rhsFun,  i.e. GuidedLaunch2DRHS
                       .direct   Flag: (1) direct or (0) indirect
                     Can specify with "LaunchOptions.m"
 p0           (3,1)  Initial guess at parameters.
                     1. initial flight path angle (rad)
                     2. last stage mass scaling factor
                     3. coast time before last stage ignites (minutes)
                        OR last stage thrust angle, for indirect
Outputs
 data          (.)   Data structure with launch results.
See also
LaunchOptions, GuidedLaunch2DRHS, GuidedLaunch2DCost,
GuidedLaunch2DSim
References and(), Demo(), Gamma(), GuidedLaunch2DCost(), GuidedLaunch2DRHS(), GuidedLaunch2DSim(), GuidedLaunchOpt2D(), LaunchOptions(), LaunchRHSData(), LaunchSummary(), NewFig(), RemoveStage(), RocketDatabase(), ScaleVehicle(), and set().
Referenced by GuidedLaunch2DCost(), GuidedLaunchOpt2D(), and LaunchSummary().
HSVMassEstimation()
function HSVMassEstimation (in d, in tol, in doPlot, in fileName)
This is an alternative to AircraftGroupMassStatement that uses a different weight model. The model is based on R. Miller's model from MIT course 16.751. If you enter fileName it will create a file with a latex table.
Not all values of parameters will produce a feasible design. If the weight goes to infinity you will need to adjust some of your parameters. See the demo for a working set of inputs.
Form
 d       = HSVMassEstimation; % Return default data structure
 [g, h]  = HSVMassEstimation( d, tol, doPlot, fileName )
Inputs
 d           (.)    Data structure
                     .massPayload            (1,1) Mass of payload
                     .dFuselage              (1,1) Fuselage diameter (m)
                     .lFuselage              (1,1) Fuselage length (m)
                     .wingLoading            (1,1) Wing loading (kg/m^2)
                     .structuralLF           (1,1) Structural load factor
                     .thicknessRatio         (1,1) Thickness Ratio
                     .sweepAngle             (1,1) Sweep ratio
                     .tipRootChordRatio      (1,1) Tip Chord/Root Chord
                     .aspectRatio            (1,1) Aspect ratio
                     .fuelStructuralFraction    (1,1) Fuel to gross weight ratio
                     .massEngine             (1,1) Engine mass
                     .fSMaterial             (1,1) Factor to adjust for materials
 tol         (1,1) Tolerance on computation
 doPlot      (1,:) Print output
 fileName    (1,:) Filename for the latex table (for one design)
Outputs
 g           (.)   Data structure
                     .gM             (1,1)  Gross mass
                     .wing           (1,1)  Wing mass
                     .fuselage     (1,1)  Fuselage mass
                     .engine       (1,1)  Engine mass
                     .fuel         (1,1)  Fuel mass
                     .fixedE        (1,1)  Fixed equipment mass
                     .empWT          (!,1)  Empanage mass
                     .landingGear    (1,1)  Landing gear mass
                     .payload        (1,1)  Payload mass
                     .misc           (1,1)  Everything else
 h            (.)  Data structure
                     .wingArea       (1,1)  Wing area
                     .mF             (1,1)  Mass fueld
Reference: Miller, R. "16.751 Course Notes," MIT Aero & Astro, 1977.
References AircraftGroupMassStatement(), Fuselage(), RocketMass(), and Wing().
IncLatVelToAzimuthHeading()
function IncLatVelToAzimuthHeading (in inc, in lat, in V, in rotation)
and V to reach inclination.
 Since version 1.0
Form
 [beta,psi] = IncLatVelToAzimuthHeading( inc, lat, V, rotation );
Inputs
 inc             (1,1)     Desired inclination (rad)
 lat             (1,1)     Current latitude (rad)
 V               (1,1)     Current airspeed velocity (km/s)
 rotation        (1,1)     Flag. Consider Earth rotation (1) or not (0)
Outputs
 beta            (1,1)     Azimuth angle to fly at (rad)
 psi             (1,2)     Heading angle to fly at (rad). Note that
                           there are two possible headings, towards the
                           East (+) or towards the West (-).
References and(), and IncLatVelToAzimuthHeading().
Referenced by IncLatVelToAzimuthHeading().
LatLonToRangeAzimuth()
function LatLonToRangeAzimuth (in lat0, in lon0, in latF, in lonF, in Rp)
 Range is measured along the sphere. Azimuth is from north, [-pi,pi].
 The latitude and longitude are geocentric. Has a built-in demo.
 Since version 2015.1
Form
 [range,az,coaz] = LatLonToRangeAzimuth( lat0, lon0, latF, lonF, Rp )
Inputs
 lat0         (1)       Initial Latitude     [rad]
 lon0         (1)       Initial Longitude    [rad]
 latF        (1,:)      Final Latitude       [rad]
 lonF        (1,:)      Final Longitude      [rad]
 Rp          (1,1)      Radius of the planet [km]
Outputs
 range       (1,:)      Range along Earth's surface (km)
 az          (1,:)      Azimuth angle from source site to satellite
 coaz        (1,:)      Azimuth angle back to source from satellite
See also
RAzToLatLon.
References: Zarchan, P. (2002) Tactical and Strategic Missile Guidance, 4th Edition, pp. 239-244.
References and(), Demo(), LatLonToRangeAzimuth(), NewFig(), RAzToLatLon(), and set().
Referenced by LatLonToRangeAzimuth().
LaunchConstants()
function LaunchConstants (in name, in value)
Form
 LaunchConstants( name, value )   % set the value of a constant
 d = LaunchConstants              % get a data structure with all constants
 c = LaunchConstants( name )      % get a single constant
 Constants:
 Re    Radius of the earth, equatorial (km)
 mu    Gravitational constant of the earth
 wE    Rotational velocity of the earth (rad/sec)
 gE    Acceleration of gravity at the earth's surface (km/s2)
References Constant(), get(), LaunchConstants(), and set().
Referenced by LaunchConstants(), LVThrustToWeight(), ParallelToSerialStages(), SubOrbDistance(), SubOrbLambert(), SubOrbTrajAnalysis(), and SubOrbVelocity().
LaunchGUI()
function LaunchGUI ()
Includes plots of:
This is a callback GUI.
Form
 LaunchGUI
Inputs
 None
Outputs
 None
See also
RocketDatabase, ScaleVehicle, GuidedLaunch2DSim
References Altitude(), GuidedLaunch2DSim(), Initialize(), LaunchGUI(), RocketDatabase(), ScaleVehicle(), and set().
Referenced by GuidedLaunch2DSim(), and LaunchGUI().
LaunchOptions()
function LaunchOptions ()
 Since version 1.0
Form
 d = LaunchOptions
Inputs
 None
Outputs
 d             (.)   Launch option data.
  .h0                  initial altitude (km)
  .v0                  initial velocity (km/s)
  .cDA                 drag coefficient
  .direct              flag for direct (1) or indirect (0)
  .hDes                desired altitude (km)
  .mDes                desired mass to orbit (kg)
  .minAlt              minimum altitude to reach at burnout (km)
  .upperStage          upper stage data
     .Isp                 specific impulse (s)
     .thrust              thrust (kN)
     .maxBurnTime         burn time (s)
  .g                   acceleration due to gravity (m/s2)
  .mu                  gravitational constant (km3/s2)
  .Rp                  radius of planet (km)
  .rhsFun              RHS function handle (GuidedLaunch2DRHS)
  .costFun             Cost function handle (GuidedLaunch2DCost)
See also
GuidedLaunch2DRHS and GuidedLaunch2DCost.
References and(), GuidedLaunch2DCost(), GuidedLaunch2DRHS(), LaunchOptions(), LaunchRHSData(), MSThrustModel(), and RHS().
Referenced by GuidedLaunch2DSim(), GuidedLaunchOpt2D(), and LaunchOptions().
LaunchRHSData()
function LaunchRHSData (in dimension, in rocket)
Prepopulate with data for an unguided 2D simulation for Earth. Compatible with RHSLaunchVehicle2D, RHSLaunchVehicle3D, GuidedLaunch2DRHS, and GuidedLaunch3DRHS.
Form
 d = LaunchRHSData( dimension, rocket )
Inputs
 dimension   (1,1)  Either 2 or 3, for 2D or 3D simulation
 rocket       (.)   If entered, make cDA the same size as m0 and store
                    the given rocket model.
Outputs
 d            (.)   Data structure
                    .rocket   (.)  Rocket data structure
                    .fThrust  (:)  Function handle for thrust model
                    .fControl (:)  Function handle for guidance
                    .rhsFun   (:)  Function hangle for RHS
                    .mu     (1,1)  Gravitational constant
                    .Rp     (1,1)  Planet radius (km)
                    .planet (1,:)  Planet name, if not Earth
                    .drag     (.)  Empty or 3D drag data structure
                    .cDA    (1,:)  Drag coefficient of each stage times area
                    .thrustOn (1)  Thrust on/off flag
                    .aE     (1,1)  Exit area
                    .coast  (1,:)  Coast times (s)
   3D only:
                    .thrustDir (3,1) Thrust direction
                    .omegaE    (3,1) Earth rotation vector
References and(), GuidedLaunch2DRHS(), GuidedLaunch3DRHS(), MSThrustModel(), RHS(), RHSLaunchVehicle2D(), RHSLaunchVehicle3D(), and vector().
Referenced by GuidedLaunch3DRHS(), GuidedLaunchOpt2D(), LaunchOptions(), RHSLaunchVehicle2D(), and RHSLaunchVehicle3D().
LaunchSummary()
function LaunchSummary (in data)
For use with GuidedLaunchOpt2D.
Form
 LaunchSummary( data )
Inputs
 data          (.)   Data structure returned by GuidedLaunch2D or
                     GuidedLaunch2DCost.
Outputs
 None
References Altitude(), Constant(), GuidedLaunch2DCost(), GuidedLaunchOpt2D(), Pressure(), and Takeoff().
Referenced by GuidedLaunch2DCost(), and GuidedLaunchOpt2D().
LaunchTime()
function LaunchTime (in lat, in lon, in inc, in ra, in jD0)
 Since version 1.0
Form
 [dT,jD] = LaunchTime( lat, lon, inc, ra, jD0 )
Inputs
 lat            (1,1)  Latitude of launch site (rad)
 lon            (1,1)  East longitude of launch site (rad)
 inc            (1,1)  Inclination (rad)
 ra             (1,1)  Right ascension (rad)
 jD0            (1,1)  Julian date right now
Outputs
 dT             (1,2)  Time until next launch opportunities (sec)
 jD             (1,2)  Julian date of next launch opportunities
References abs(), and(), Date2JD(), GMSTime(), LaunchTime(), LLAToECEF(), OrbitalPlane(), and WrapPhase().
Referenced by LaunchTime().
LiftAndDragSeaLevelToOrbit()
function LiftAndDragSeaLevelToOrbit (in x, in d)
 Includes both hypersonic and low speed models. The models are
 analytical.
 Since version 1.0
Form
 [f, lift, drag] = LiftAndDragSeaLevelToOrbit( x, d )
 d = LiftAndDragSeaLevelToOrbit
Inputs
 x           (6,:)  [x;y;z;vX;vY;vZ] ECI frame (km, km/s)
 d            (.)   Data structure
                    .rPlanet     (1,1) Planet radius (km)
                    .omega       (1,1) Planet rate (rad/s)
                    .l           (1,1) Characteristic length
                    .sRef        (1,1) Reference area for lift and drag
                    .alpha       (1,1) Angle of attack
                    .cLAlpha     (1,1) Lift coefficient
                    .thickness   (1,1) Thickness ratio
                    .aspectRatio (1,1) Wing aspect ratio
                    .oswaldEff   (1,1) Oswald efficiency factor
                    .mHyper      (1,1) Transition mach number
Outputs
 f           (3,:)  Force vector ECI (N)
 lift        (1,:)  Lift (N)
 drag        (1,:)  Drag (N)
References: R. Miller, MIT 16.751 Notes, 1978.
References Altitude(), and(), AtmScaleHeightsStdAtm(), Cross(), Demo(), length(), LiftAndDragSeaLevelToOrbit(), Mag(), Unit(), vector(), Wing(), and zeros().
Referenced by LiftAndDragSeaLevelToOrbit(), and RHSLiftingReentry3D().
LSQLaunch()
function LSQLaunch (in p0G, in zM, in W, in d, in opts)
 In order to achieve orbit, the final states are a vRatio of 1 and a
 flight path angle of 0.
 Since version 1.0
Form
 [p0,z] = LSQLaunch( p0G, z, W, d, opts )
Inputs
 p0G           (2,1)    Initial parameters guess. [gamma; scale], where:
                           gamma:   Initial flight path angle
                           scale:   Scale of 3rd stage
 zM            (2,1)    Final states to match. [vRatio; gamma], where:
                           vRatio:  Final velocity over orbital velocity
                           gamma:   Final flight path angle
 W             (2,2)   Diagonal weighting matrix.
 d              (.)     Data structure for launch problem. Fields:
                 .simFun  (:)      Name of simulation function
                 .rocket  (.)      Launch vehicle data structure (see RocketDatabase)
                 .direct  (1)      Flag. Direct (1) or indirect (0) launch
                 .mPLD    (1)      Payload mass (kg)
                 .h0      (1)      Launch altitude
                 .v0      (2)      Launch velocity
                 .dT      (1)      Desired time step for orbit propagation [sec]
                 .g       (1)      Gravitational acceleration (km/s/s)
                 .Rp      (1)      Planet radius (km)
                 .mu      (1)      Gravitational constant (km^3/s/s)
 opts           (.)     Data structure of options for this algorithm.
 .tol     (1)      Tolerance for size of dp0 (differential corrector)
 .maxIter (1)      Maximum allowed iterations
 .verbose (1)      Print out additional information
Outputs
 p0            (2,1)  Solution for best parameters p0
 z             (2,1)  Final states, [vRatio; gamma]
See also
LSQLaunchSim, Jacobian
References and(), Jacobian(), LSQLaunchSim(), RocketDatabase(), and zeros().
Referenced by LSQLaunchSim().
LSQLaunchSim()
function LSQLaunchSim (in p0, in d)
Returns final states.
Form
 [z,xS,time] = LSQLaunchSim( p0, d )
Inputs
 p0            (2,1)    Initial parameters. [gamma; scale], where:
                           gamma:   Initial flight path angle
                           scale:   Scale of 3rd stage
 d              (.)     Data structure for launch problem. Fields:
                 .rocket  (.)      Launch vehicle data structure (see RocketDatabase)
                 .direct  (1)      Flag. Direct (1) or indirect (0) launch
                 .h0      (1)      Launch altitude
                 .v0      (2)      Launch velocity
                 .Rp      (1)      Planet radius (km)
                 .mu      (1)      Gravitational constant (km^3/s/s)
Outputs
 z             (2,1)    Final states. [vRatio; gamma], where:
                           vRatio:  Ratio of final velocity to orbital velocity
                           gamma:   Final flight path angle
 xS           (4+n,:)   Time history of states for launch simulation
                           [range;alt;vel;gamma;mass]
 time          (1,:)    Time vector for launch simulation
See also
GuidedLaunch2DRHS, LSQLaunch
References GuidedLaunch2DRHS(), LSQLaunch(), MS2M(), RocketDatabase(), and vector().
Referenced by LSQLaunch().
LVCombineSRB()
function LVCombineSRB (in lv0)
 The remaining time of the first stage (after SRB burnout) is treated as
 a new second stage.
 The original stages 2-N are appended after these first 2 new stages.
 Thus, original stage 2 becomes new stage 3, and so on.
 Since 2015.1
Form
 lv = LVCombineSRB( lv0 )
Inputs
 lv0       (.)   Original launch vehicle data structure
Outputs
 lv        (.)   Modified data structure with SRBs combined into
                 separate first stage.
See also
GetStage, ParallelToSerialStages, M2MS
References and(), get(), GetStage(), isempty(), length(), M2MS(), and ParallelToSerialStages().
Referenced by BurnoutVelocity(), LVModelFeasibilityFix(), LVThrustToWeight(), MSThrustModel(), and PayloadMassForBurnoutVelocity().
LVModelFeasibility()
function LVModelFeasibility (in lv, in opts)
Checks several conditions.
Returns an array of logicals indicating pass (1) or fail (0) for each condition:
Thrust to weight ratio at takeoff. Must be above opts.minThrustToWeight
Total delta-v. Must be below opts.maxDeltaV
 Add more as needed to this list. When a condition is added here:
 LVModelFeasibilityReport will automatically display it.
 LVModelFeasibilityFix must be edited separately to implement a fix.
 Since version 2015.1
Form
 [f,v,d,s] = LVModelFeasibility( lv, opts )
Inputs
 lv      (.)     Launch vehicle data structure. See RocketDatabase.
 opts    (.)     Options. Default values used if not entered. To get
                   default values type: LVModelFeasibility('opts');
Outputs
 f       (1,:)   Feasibility array. Array of logicals (0,1). If any is
                 zero then that condition is not feasible.
 v       (1,:)   Value of the conditions checked.
 d       (.)     Data structure of values. Compare to thresholds in opts
 s       {:}     String label for each condition
References get(), LVModelFeasibility(), LVModelFeasibilityFix(), LVModelFeasibilityReport(), and RocketDatabase().
Referenced by LVModelFeasibility(), LVModelFeasibilityFix(), and LVModelFeasibilityReport().
LVModelFeasibilityFix()
function LVModelFeasibilityFix (in lv, in opts)
 Changes the payload mass if necessary in order to achieve:
 1) thrust > weight at takeoff, and
 2) small enough burnout velocity so orbit is not hyperbolic.
 Since verion 2015.1
Form
 lv = LVModelFeasibilityFix( lv, opts )
Inputs
 lv      (.)     Launch vehicle data structure. See RocketDatabaseDA.
 opts    (.)     Options. Default values used if not entered. To get
                   default values type: LVModelFeasibility('opts');
Outputs
 lv      (.)     Updated launch vehicle data structure. Fixed so that
                 all conditions pass in LVModelFeasibility.
References and(), BurnoutVelocity(), Demo(), get(), LVCombineSRB(), LVModelFeasibility(), LVModelFeasibilityFix(), PayloadMassForBurnoutVelocity(), RocketDatabase(), set(), and SetPayloadMass().
Referenced by LVModelFeasibility(), and LVModelFeasibilityFix().
LVModelFeasibilityReport()
function LVModelFeasibilityReport (in dBFile, in opts)
Returns an array of logicals indicating pass (1) or fail (0) for each condition:
Thrust to weight ratio at takeoff. Must be above opts.minThrustToWeight
Total delta-v. Must be below opts.maxDeltaV
 Since verstion 2015.1
Form
 feas = LVModelFeasibilityReport( dBFile, opts )
Inputs
 dBFile  (:)     Name of database file to load. Default: LVDatabase.csv
 opts    (.)     Options. Default values used if not entered. To get
                   default values type: LVModelFeasibility('opts');
Outputs
 feas    (N,:)   Feasibility array. Array of logicals (0,1).
                 N columns for N launch vehicles in database.
References FormatRocketDB(), get(), length(), LVModelFeasibility(), LVModelFeasibilityReport(), ReadCSVTable(), and zeros().
Referenced by LVModelFeasibility(), and LVModelFeasibilityReport().
LVStageTimes()
function LVStageTimes (in lvModel, in coastTimes)
 Since version 2015.1
Form
 [t0,tF] = LVStageTimes( lvModel, coastTimes )
Inputs
 lvModel      (.)     Launch vehicle data structure
 coastTimes  (1,n)    Coast times
Outputs
 t0          (1,n)     Stage start times
 tF          (1,n)     Stage end times
References and(), length(), plus(), and zeros().
LVThrustToWeight()
function LVThrustToWeight (in lv)
 Accounts for solid boosters using LVCombineSRB.
 Since version 2015.1
Form
 [ratio,time] = LVThrustToWeight( lv )
Inputs
 lv             (.)    Launch vehicle data structure
Outputs
 ratio         (1,:)   Takeoff thrust to weight ratio per stage
 time          (1,:)   Start time of each stage
References Demo(), LaunchConstants(), LVCombineSRB(), LVThrustToWeight(), RocketDatabase(), and Takeoff().
Referenced by LVThrustToWeight().
MinTOrbitInjection()
function MinTOrbitInjection (in h, in u, in a, in g)
 Compute the initial and final burn angles and total delta-v for a
 constant thrust minimum time trajectory. Assumes a constant gravity
 field and a flat planet model. Assumes a constant mass vehicle.
 Since version 1.0
Form
 [dV, beta] = MinTOrbitInjection( h, u, a, g )
Inputs
 h           (1,1) Altitude
 u           (1,1) Final horizontal velocity
 a           (1,1) Acceleration
 g           (1,1) Gravitational acceleration.
Outputs
 dV          (1,1) Total delta-v
 beta        (2,1) [beta0;betaF] (rad)
See also
FMinTOrbitInjection
Reference: Bryson, A. E. and Y. Ho, "Applied Optimal Control', Hemisphere, pp. 84-86.
References Altitude(), and(), Constant(), and FMinTOrbitInjection().
Referenced by FMinTOrbitInjection().
MSData()
function MSData (in varargin)
 1 2 3 4 ... payload
 Provide the payload mass and 2 other parameters to retrieve a data
 structure with the complete set of data.
 The parameter names can be selected to be one of the following:
 m0    Initial (wet) mass above each stage including the stage
 mF    Final (dry) mass above each stage including the stage
 mS    Total mass of each stage
 mSS   Mass of the structure for each stage
 mSP   Mass of the propellant for each stage
 eS    Structural ratio for each stage
 pS    Payload ratio for each stage
 Note: the following pairs of parameters do not provide sufficient
 information:
 [m0,mS]
 [m0,pS]
 [pS,mS]
 [mF,mSS]
 Since version 1.0
Form
 d = MSData;   % returns a multi-stage data structure with empty fields
 -or-
 d = MSData( mPLD, p1, v1, p2, v2 );
 -or-
 d = MSData( d );   % where d is a multi-stage data structure
Inputs
 mPLD        (1,1)  Payload mass
 p1           (:)   Name of the first parameter (string)
 v1          (1,:)  Value of parameter 1
 p2           (:)   Name of the second parameter (string)
 v2          (1,:)  Value of paramter 2
 -OR-
 d            (.)   Multi-stage data structure with "mPLD" and two other
 fields specified.
Outputs
 d            (.)   Multi-stage data structure with fields:
  .m0    Initial (wet) mass above each stage including the stage
  .mF    Final (dry) mass above each stage including the stage
  .mS    Total mass of each stage
  .mSS   Mass of the structure for each stage
  .mSP   Mass of the propellant for each stage
  .eS    Structural ratio for each stage
  .pS    Payload ratio for each stage
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 199-202.
References and(), MSData(), and set().
Referenced by MSData().
MSThrustModel()
function MSThrustModel (in mFuel, in rocket, in t, in coast)
Stages fire sequentially. The current mass and flow rate are calculated. Coast times may be inserted between the stages. To ignore coast times and burn continuously, the last two inputs may be left out.
This model does not handle parallel solid boosters. To incorporate boosters see LVCombineSRB.
Form
 [thrust,mass,mDot,j] = MSThrustModel( mFuel, rocket, t, coast )
Inputs
 mFuel       (n,1)    Fuel mass states
 rocket       (.)     Rocket model
                       .mSS      (1,n) Structural (dry) mass of the stages
                       .thrust   (1,n) Thrust of the stages (vacuum)
                       .uE       (1,n) Exhaust velocity (vacuum)
                       .tBurn    (1,n) Burn time of stage
                       .mPLD     (1,1) Mass of payload
 t           (1,1)    Current elapsed time*
 coast       (1,:)    Coast times (sec)*
                        * Optional, required only for coasting
Outputs
 thrust      (1,1)    Current thrust
 mass        (1,1)    Vehicle current mass
 mDot        (:,1)    Mass derivative
 j           (1,1)    Current stage index
References and(), isempty(), length(), LVCombineSRB(), and zeros().
Referenced by GuidedLaunch3DRHS(), LaunchOptions(), LaunchRHSData(), and RHSLaunchVehicle2D().
MSVRatio()
function MSVRatio (in sR, in pR, in nStages)
 Call this function with no inputs and no outputs to show a plot of the
 velocity ratio as a function of payload ratio for different numbers of
 stages.
 The equations used to compute the velocity ratio neglect the effects of
 gravity and drag.
 Since version 1.0
Form
 vRatio = MSVRatio( sR, pR, nStages )
Inputs
 sR           (1,1)  Ratio of stage dry mass to stage wet mass
 pR           (1,M)  Ratio of total mass above the stage to total mass
                     of the stage
 nStages      (1,N)  Number of stages
Outputs
 vRatio       (M,N)  Ratio of burnout velocity to exhaust velocity.
See also
: M2EP
References: Wiesel, W. E., Spaceflight Dynamics, 2nd Ed. McGraw-Hill, 1995, p. 201.
References and(), length(), M2EP(), MSVRatio(), NewFig(), set(), and zeros().
Referenced by MSVRatio(), and RocketDatabase().
NewtonianAeroPropertiesFromOBJFile()
function NewtonianAeroPropertiesFromOBJFile (in vInf, in fileName)
 Since version 1.0
Form
 Initialization:
 [cN, normalVec, area, g] = NewtonianAeroPropertiesFromOBJFile( vInf, fileName )
 Aero Property Calculation:
 [cN, normalVec, area, g] = NewtonianAeroPropertiesFromOBJFile( vInf, g )
Inputs
 vInf             (3,1) Free stream velocity vector in body frame (any units)
 fileName         (1,:) File name or data structure
Outputs
 cN               (1,1) Normal coefficient
 normalVec        (3,1) Unit vector in the direction of the normal
 area             (1,1) Total surface area
 g                 (.)  Data structure with geometry information
References and(), Demo(), Initialize(), length(), LoadCAD(), Mag(), NewtonianAeroPropertiesFromOBJFile(), Normal(), PolygonProps(), Unit(), vector(), and zeros().
Referenced by NewtonianAeroPropertiesFromOBJFile().
NewtonianLD3D()
function NewtonianLD3D (in vInf, in alt, in fileName)
 Since version 1.0
Form
 [L, D, machNo, g] = NewtonianLD3D( vInf, alt, filename )
Inputs
 vInf        (3,1) Freestream velocity vector (m/s) in the body frame
 alt         (1,1) altitude (km)
 fileName    (1,1) path to OBJ file, or a data structure containing
                   geometry information
Outputs
 L           (1,:) Lift
 D           (1,:) Drag
 machNo      (1,1) Mach Number
 g            (.)  Data structure containing geometry data from OBJ file
Reference: Anderson, J.D., 'Hypersonic and High-Temperature Gas Dynamics," 2006.
References and(), and vector().
OptimalPayloadRatio()
function OptimalPayloadRatio (in VBO, in Ve, in sR)
 The objective is to maximize the overall payload ratio. In other words,
 maximize the payload mass given a total takeoff mass.
 The payload ratio is defined as the ratio of initial masses:
 pR(k) = m0(k+1)/m0(k)
 where the "payload" is the mass of everything above that stage.
 The overall payload ratio is the fraction of the actual payload m* to
 the total initial mass:
 pR* = m*&zwj;/m0(1)
 Since version 1.0
Form
 pR = OptimalPayloadRatio( VBO, Ve, sR )
Inputs
 VBO           (1,1)    Burnout velocity (km/s)
 Ve            (1,N)    Exhaust velocity at each stage (km/s)
 sR            (1,N)    Structural ratio for each stage
                           sR(k) = mSk / (mSk + mPk)
                              where mSk = structure mass of stage k
                                    mPk = propellant mass of stage k
Outputs
 pR            (1,N)    Optimal set of payload ratios.
 pRTot         (1,1)    Total (overall) payload ratio. Product of all
                        elements of pR.
See also
: BurnoutVelocity, M2EP
References: Weisel, "Spaceflight Dynamics", 2nd Edition, 1995. pp. 212-214.
References BurnoutVelocity(), Demo(), length(), M2EP(), OptimalPayloadRatio(), Product(), set(), and zeros().
Referenced by OptimalPayloadRatio(), and RocketDatabase().
ParallelToSerialStages()
function ParallelToSerialStages (in p1, in p2, in m0)
 Assume p1 and p2 start at same time.
 Since version 2015.1
Form
 [s1,s2] = ParallelToSerialStages(p1,p2,m0)
Inputs
 p1      (.)     Parallel stage 1
 p2      (.)     Parallel stage 2
 m0      (1,1)   Initial wet mass (same for both stages)
Outputs
 s1      (.)     First serial stage
 s2      (.)     Second serial stage
References and(), GetStage(), LaunchConstants(), Parallel(), ParallelToSerialStages(), and RocketDatabase().
Referenced by LVCombineSRB(), and ParallelToSerialStages().
PayloadMassForBurnoutVelocity()
function PayloadMassForBurnoutVelocity (in d, in vBO)
 The maximum burnout velocity is achieved when the payload mass is zero.
 The built-in demo chooses a vehicle from the database and computes this
 maximum for generating the vector of vBO and resulting plot of the
 range of feasible payload mass.
 Since version 2015.1
Form
 mP = PayloadMassForBurnoutVelocity( d, vBO )
Inputs
 d         (d)    Vehicle structure.
 vBO      (1,1)   Target exhuast velocity.
Outputs
 mP       (1,1)   Payload mass
See also
BurnoutVelocity
References and(), BurnoutVelocity(), FormatRocketDB(), length(), LVCombineSRB(), PayloadMassForBurnoutVelocity(), Plot2D(), ReadCSVTable(), SetPayloadMass(), vector(), and zeros().
Referenced by LVModelFeasibilityFix(), and PayloadMassForBurnoutVelocity().
ReentryPlot()
function ReentryPlot (in x, in t, in d, in u)
 Requires the same state vector and data structure as RHSReentry.
Form
 ReentryPlot( x, t, d, u )
Inputs
 x           (7,:)  [r;theta;phi;v;gamma;psi;massFuel]
 t           (1,:)  Time
 d            (.)   Data structure
                    .thrust  (1,1) Thrust (N)
                    .uE      (1,:) Exhaust velocity engine (m/s)
                    .g       (1,1) Gravity (km/s^2)
                    .rPlanet (1,1) Planet radius (km)
                    .planet  (1,:) Planet name
                    .mDry    (1,1) Dry mass
                    .atmData (1,1) Data for atmosphere
                    .l       (1,1) Characteristic length
                    .cDP     (1,1) Parasitic drag coefficient
                    .sRef    (1,1) Reference area for lift and drag
                    .alpha   (1,1) Angle of attack
                    .sigma   (1,1) Bank angle
 u           (2,:)  [sigma;alpha]
Outputs
 None
References and(), length(), RHSReentry(), StdAtm(), and vector().
RemoveStage()
function RemoveStage (in d, in k)
 Since version 1.0
Form
 d = RemoveStage( d, k )
Inputs
 d             (.)   Initial multi-stage data structure
 k             (1)   Index of stage to be removed
Outputs
 d             (.)   Updated data structure without stage k
References MS2M().
Referenced by GuidedLaunchOpt2D().
RHSLaunchVehicle2D()
function RHSLaunchVehicle2D (in x, in t, in d)
The states are vertical and horizontal position, velocity and flight path angle. The model assumes a flat Earth that isn't rotating. The model can handle multiple stages. The dry masses and exhaust velocities are entered using the data structure d. For each stage you add a fuel state to x. Thus a 3 stage vehicle will have 7 states and d.mStage, d.thrust, d.uE and d.cDA (the drag coefficient) will each have three entries. The data structure is the same as is used in LaunchVehicle3D.
This model does not include lift.
Any planet that is included in AtmDens1 can be simulated if entered by name. For Earth, the standard atmosphere is used below 80 km altitude.
Form
 xDot = RHSLaunchVehicle2D( x, t, d )
Inputs
 x           (:,1)  [x h v gamma massFuel]'
                      x        Downrange distance (km)
                      h        Altitude (km)
                      v        Velocity (km/s)
                      gamma    Flight path angle (rad)
                      massFuel Fuel mass of each stage (kg)
 t           (1,1)  Time (not used)
 d            (.)   Sim RHS data structure
                    .fThrust (:)  Function handle for thrust model
                    .cDA    (1,:) Drag coefficient of each stage times area
                    .mu     (1,1) Gravitational constant
                    .Rp     (1,1) Planet radius (km)
                    .planet (1,:) Planet name, or empty for Earth
                    .drag     (.) Empty or 3D drag data structure
                    .rocket   (.) Rocket model data structure
Outputs
 xDot        (:,1)  State derivatives
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 207-211.
See also
MSThrustModel, StdAtm, RocketDatabase, LiftAndDragJonesSearsHaack
References and(), LaunchRHSData(), LiftAndDragJonesSearsHaack(), MSThrustModel(), RHS(), RHSLaunchVehicle2D(), RocketDatabase(), RocketDrag(), and StdAtm().
Referenced by FGravityTurn(), GravityTurnSim2D(), LaunchRHSData(), RHSLaunchVehicle2D(), and RHSLaunchVehicle3D().
RHSLaunchVehicle3D()
function RHSLaunchVehicle3D (in x, in t, in d)
Compute position, velocity and mass derivatives assuming a rotating spherical planet and an exponential atmosphere. The model can handle multiple stages. For each stage you add a fuel state to x. Thus a 3 stage vehicle will have 9 states. Any planet that is included in AtmDens1 can be simulated.
The data structure is the same as is used in RHSLaunchVehicle2D with the addition of mu and omegaE.
Form
 xDot = RHSLaunchVehicle3D( x, t, d )
Inputs
 x         (6+n,1)  [r v massFuel]
 t           (1,1)  Time (not used)
 d            (.)   Data structure
                    .rocket  (.)  Rocket model
                    .cDA    (1,:) Drag coefficient of each stage times area
                    .Rp     (1,1) Planet radius (km)
                    .planet (1,:) Planet name, may be empty for Earth
                    .omegaE (3,1) Earth rotation
                    .mu     (1,1) Gravitational parameter
Outputs
 xDot        (:,1)  State derivative
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 207-211.
References and(), AtmDens1(), Cross(), isempty(), LaunchRHSData(), Mag(), RHSLaunchVehicle2D(), RHSLaunchVehicle3D(), RocketDatabase(), Unit(), and vector().
Referenced by GuidedLaunch3DRHS(), LaunchRHSData(), and RHSLaunchVehicle3D().
RHSLiftingReentry3D()
function RHSLiftingReentry3D (in x, in ignoredArg, in d)
 Compute position, velocity and mass derivatives for a launch vehicle.
 The model assumes a rotating spherical planet. If the altitude is
 less than or equal to zero it sets the acceleration of gravity to
 zero. The data structure is that needed by LiftAndDragSeaLevelToOrbit.
Form
 d = RHSLiftingReentry3D;
 xDot = RHSLiftingReentry3D( x, t, d )
Inputs
 x           (:,1)  [r v]
 t           (1,1)  Time (not used)
 d            (.)   Data structure
                    .rPlanet     (1,1) Planet radius (km)
                    .omega       (1,1) Planet rate (rad/s)
                    .l           (1,1) Characteristic length
                    .sRef        (1,1) Reference area for lift and drag
                    .alpha       (1,1) Angle of attack
                    .cLAlpha     (1,1) Lift coefficient
                    .thickness   (1,1) Thickness ratio
                    .aspectRatio (1,1) Wing aspect ratio
                    .oswaldEff   (1,1) Oswald efficiency factor
                    .mass        (1,1) Mass of the vehicle
                    .mu          (1,1) Gravitational parameter
Outputs
 xDot        (6,1)  Stage structural ratios
See also
LiftAndDragSeaLevelToOrbit
References and(), Constant(), DefaultDataStructure(), length(), LiftAndDragSeaLevelToOrbit(), Mag(), RHSLiftingReentry3D(), and Wing().
Referenced by RHSLiftingReentry3D(), and RHSTSTO().
RHSMinTOrbitInjection()
function RHSMinTOrbitInjection (in x, in t, in beta, in g, in a)
 Since version 1.0
Form
 xDot = RHSMinTOrbitInjection( x, t, beta, g, a )
Inputs
 x           (4,1) [x;y;vX;vY]
 beta        (1,1) Thrust vector angle from horizontal (rad)
 g           (1,1) Graviational acceleration.
 a           (1,1) Acceleration
Outputs
 xDot        (4,1) State derivative
References RHS(), and vector().
RHSOptimalFPA()
function RHSOptimalFPA (in gamma, in h0, in hF, in v0, in bC)
 The first delta-v is applied at a point when the vehicle is at altitude
 "h0", velocity "v0", and flight path angle "gamma". The delta-v is
 applied along the original velocity vector at flight path angle "gamma"
 The first delta-v is computed so that the transfer orbit achieves
 apogee at altitude "hF".
 The second delta-v is applied at apogee of the transfer orbit, which is
 at altitude "hF". The flight path angle at this point is zero. The
 final velocity is the circular orbit velocity for this altitude. The
 delta-v is simply the difference between the circular orbit velocity
 and the transfer orbit velocity at its apogee.
 Since version 2015.1
Form
 [dV,dV1,dV2,dVDrag] = RHSOptimalFPA( gamma, h0, hF, v0, bC )
Inputs
 gamma      (1,1)     Initial flight path angle (rad)
 h0         (1,1)     Initial altitude (km)
 hF         (1,1)     Final altitude for orbit (km)
 v0         (1,1)     Initial velocity (km/s)
 bC         (1,1)     Ballistic coefficient (kg/m^2). If not supplied,
                      drag is ignored;
Outputs
 dV         (1,1)     Total delta-v, dV1 + dV2 + dVDrag (km/s)
 dV1        (1,1)     First delta-v at h0 (km/s)
 dV2        (1,1)     Second delta-v at hF (km/s)
 dVDrag     (1,1)     Approximate delta-v due to drag
See also
BoostPhaseDeltaV, OrbitDrag
References and(), BoostPhaseDeltaV(), isempty(), OrbitDrag(), and vector().
RHSReentry()
function RHSReentry (in x, in ignoredArg, in d)
 The time derivative is with respect to non-dimensional time. Includes
 the Earth rotation terms (if d.omega is not zero)
Form
 xDot = RHSReentry( x, t, d )
Inputs
 x           (:,1)  [r;theta;phi;v;gamma;psi;massFuel]
 t           (1,1)  Normalized time (not used)
 d            (.)   Data structure
                    .thrust  (1,1) Thrust (N)
                    .uE      (1,:) Exhaust velocity engine (m/s)
                    .g       (1,1) Gravity (km/s^2)
                    .rPlanet (1,1) Planet radius (km)
                    .omega   (1,1) Planet rate (rad/s)
                    .planet  (1,:) Planet name
                    .mDry    (1,1) Dry mass
                    .atmData (1,1) Data for atmosphere
                    .l       (1,1) Characteristic length
                    .cDP     (1,1) Parasitic drag coefficient
                    .sRef    (1,1) Reference area for lift and drag
                    .alpha   (1,1) Angle of attack
                    .sigma   (1,1) Bank angle
Outputs
 xDot        (:,1)  Stage structural ratios
References: Shen, Z. and Lu, P., "On-Board Entry Trajectory Planning Expanded to Sub-Orbital Flights". Vinh, N. X. and A. Busemann and Robert D. Culp, "Hypersonic and Planetary Entry Flight Mechanics," Ann Arbor University of Michigan Press, 1980.
References and(), DefaultDataStructure(), length(), RHSReentry(), and StdAtm().
Referenced by ReentryPlot(), and RHSReentry().
RHSTSTO()
function RHSTSTO (in x, in t, in d)
 The model assumes a rotating spherical planet.
 Since version 1.0
Form
 xDot = RHSTSTO( x, t, d )
Inputs
 x          (14,1)  [r v m r v m] states of the two stages
 t           (1,1)  Time (not used)
 d            (.)   Data structure
                    .rPlanet     (1,1) Planet radius (km)
                    .omega       (1,1) Planet rate (rad/s)
                    .mu          (1,1) Gravitational parameter
                    .vehicle1     (.)  Vehicle 1 data structure
                    .vehicle2     (.)  Vehicle 2 data structure
Outputs
 xDot        (14,1)  Derivatives
See also
RHSLiftingReentry3D
References and(), RHSLiftingReentry3D(), and zeros().
RocketDatabase()
function RocketDatabase (in name, in file)
If the vehicle is not hard-coded in this database it will load the csv database and check there. The default database is LVDatabase.csv Data from the loaded csv files is stored persistently for faster calls. To load a case from an alternate file, pass it in with the name.
Form
 d = RocketDatabase( name )  % Get data for a case
 d = RocketDatabase( name, file )  % Get data for a case from file
 list = RocketDatabase                % List all case names
 RocketDatavase( [], files )   % Load additional file
Inputs
 name           (:)     Name of the rocket
 file           (:)     Name of the file to load, optional
Outputs
 d              (.)        Data structure with fields:
                 .name         (1)     Name of the Launch Vehicle
                 .mTotal       (1)     Total mass of fueled rocket    (kg)
                 .mS          (1,N)    Total mass of each stage       (kg)
                 .mSS         (1,N)    Structural mass of each stage  (kg)
                 .mSP         (1,N)    Propellant mass of each stage  (kg)
                 .eS          (1,N)    Structural Ratio of each stage
                 .pS          (1,N)    Payload Ratio of each stage
                 .uE          (1,N)    Exhaust velocity of each stage (km/s)
                 .ISP         (1,N)    Specific impulse of each stage (s)
                 .thrust      (1,N)    Thrust of each stage           (kN)
                 .tBurn       (1,N)    Burn time of each stage        (s)
                 .mDot        (1,N)    Rate of mass flow              (kg/s)
                 .type        (1,N)    Stage type - 'l' or 's'
                 .SRB          (1)     Boolean. 1 has SRB's, 0 Does not
                 .SRBmSS       (1)     Structural mass of all SRB's   (kg)
                 .SRBuE        (1)     Exhaust velocity of all SRB's  (km/s)
                 .SRBthrust    (1)     Net Thrust of all SRB's        (kN)
                 .SRBmSP       (1)     Propellent mass of all SRB's   (kg)
 mTot           (1)        Total mS of fueled rocket.
See also
OptimalPayloadRatio, MSVRatio
References: Weisel, "Spaceflight Dynamics", 2nd Edition.
References and(), isempty(), MSVRatio(), OptimalPayloadRatio(), and RocketDatabase().
Referenced by GravityTurnSim2D(), GuidedLaunch2DSim(), GuidedLaunch3DRHS(), GuidedLaunchOpt2D(), LaunchGUI(), LSQLaunch(), LSQLaunchSim(), LVModelFeasibility(), LVModelFeasibilityFix(), LVThrustToWeight(), ParallelToSerialStages(), RHSLaunchVehicle2D(), RHSLaunchVehicle3D(), RocketDatabase(), ThrustAngleExplicit(), and ThrustAngleVGain().
RocketDrag()
function RocketDrag (in r, in v, in d, in j)
Uses a scale height atmosphere for the Earth above 80 km, otherwise StdAtm for the Earth or exponential atmosphere (AtmDens1) for other planets. If only r and v magnitudes are input, the drag magnitude is returned.
The standard atmosphere data is stored in a persistent variable.
Form
 [drag,rho] = RocketDrag( r, v, d, j )
Inputs
 r        (3,:)      Position (km)
 v        (3,:)      Velocity (km/s)
 d         (.)       Data structure
                     .cDA   (1,:) Coefficient times area for plate model
                     .drag   (.)  Data for LiftAndDragJonesSearsHaack
                     .planet (:)  For planets other than Earth
 j        (1,1)      Stage index, if needed
Outputs
 drag     (3,:)      Drag force (kN)
 rho      (1,:)      Atmospheric density (kg/m3)
See also
AtmDens1, AtmDens2, StdAtm, LiftAndDragJonesSearsHaack
References and(), AtmDens1(), AtmDens2(), isempty(), length(), LiftAndDragJonesSearsHaack(), Mag(), StdAtm(), and zeros().
Referenced by RHSLaunchVehicle2D().
ScaleVehicle()
function ScaleVehicle (in d, in scale)
 Volume is scaled by the cube of the given factor. Area is scaled by the
 square. Affected fields include: mS, mSS, mSP, m0, mF, mTotal, mPLD,
 mDot, thrust, tBurn, cDA.
 Since version 1.0
Form
 d = ScaleVehicle( d, scale )
Inputs
 d             (.)      Data structure
                        .mS     (1,1) Mass structure
                        .mPLD   (1,1) Mass payload
                        .thrust (1,1) Thrust
                        .eS     (1,1) Stage structural ratios
                        .m0     (1,1) Total mass of each stage (including everything above)
                        .mF     (1,1) Final mass of each stage (including everything above)
                        .pS     (1,1) Stage payload ratios
                        .mSP    (1,1) Stage propellant mass
                        .mSS    (1,1) Stage structural mass
                        .mDot   (1,1) Mass flow
                        .tBurn  (1,1) Burn duration
                        .cDA    (1,1) Product of drag coeff and area
                        .mTotal (1,1) Total mass
 scale        (1,1)     Linear scale factor
Outputs
 d             (.)      Data structure after scaling
Referenced by GuidedLaunchOpt2D(), and LaunchGUI().
SetPayloadMass()
function SetPayloadMass (in d, in mPLD)
 Since version 2015.1
Form
 d = SetPayloadMass( d, mPLD )
Inputs
 d              (.)        Rocket data structure with fields
 mPLD          (1,1)       New payload mass (kg)
Outputs
 d              (.)        Updated data structure
References length().
Referenced by GuidedLaunch2DSim(), LVModelFeasibilityFix(), PayloadMassForBurnoutVelocity(), ThrustAngleExplicit(), ThrustAngleVGain(), and VonBraunRocket().
SS2O()
function SS2O (in Isp, in mP, in fS, in dV)
 Type SS2O for a demo.
 Since version 1.0
Form
 [mF, mT, mS, e] = SS2O( Isp, mP, fS, dV )
Inputs
 Isp          (1,1) Specific impulse    (sec)
 mP           (1,1) Payload mass
 fS           (1,1) Structural fraction
 dV           (1,:) Required delta v    (km/sec)
Outputs
 mF          (1,:) Fuel mass
 mT          (1,:) Total mass
 mS          (1,:) Structural mass
 e           (1,:) Fraction of the launcher that is the payload
References: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, p. 187.
References Plot2D(), and SS2O().
Referenced by SS2O().
StageTimes()
function StageTimes (in m)
Form
 [kI,kB,mode] = StageTimes( m )
Inputs
 m            (:,n)  "n" columns of mass histories for "n" stages
Outputs
 kI           (1,n)  Index of ignition point for each stage
 kB           (1,n)  Index of burnout point for each stage
 mode         (:,1)  Mode at each time, 1 for stage 1, 2 for stage 2, etc
References abs(), and(), isempty(), length(), vector(), and zeros().
SubOrbDistance()
function SubOrbDistance (in lat0, in lon0, in latF, in lonF, in Rp)
 Since version 1.0
Form
 [angleDist,range] = SubOrbDistance( lat0, lon0, latF, lonF );
Inputs
 lat0         (1)       Initial Latitude  [rad]
 lon0         (1)       Initial Longitude [rad]
 latF         (1)       Final Latitude    [rad]
 lonF         (1)       Final Longitude   [rad]
Outputs
 angleDist    (1)       Angular distance of flight around Earth (rad)
 range        (1)       Corresponding range along Earth's surface (km)
See also
: SubOrbLambert
References: Zarchan, P. (2002) Tactical and Strategic Missile Guidance, 4th Edition, pp. 239-244.
References and(), LaunchConstants(), and SubOrbLambert().
Referenced by SubOrbLambert(), SubOrbTrajAnalysis(), and SubOrbVelocity().
SubOrbLambert()
function SubOrbLambert (in tFDes, in h0, in hF, in angleDist, in tol, in maxIter)
 Given initial and final altitudes, the desired time of flight, and the
 desired angular distance to fly around the globe, this routine conducts
 an iterative search for the initial flight path angle using the Lambert
 method.
 Since version 1.0
Form
 [gamma,V,tF] = SubOrbLambert( tFDes, h0, hF, angleDist, tol, maxIter );
Inputs
 tFDes           (1,1) Desired time of flight (sec)
 h0              (1,1) Initial altitude (km)
 hF              (1,1) Final altitude (km)
 angleDist       (1,1) Angular distance of flight around Earth (rad)
 tol             (1,1) Tolerance for converging to tFDes
                           (optional, default is 1e-3 sec)
 maxIter         (1,1) Maximum number of iterations
                           (optional, default is 100)
Outputs
 gamma           (1,1) Initial flight path angle (rad)
 V               (1,1) Initial velocity required (km/s)
 tF              (1,1) Flight Time (sec)
 soln            (1,1) Boolean to indicate whether solution was found.
 k               (1,1) Number of terations performed
See also
SubOrbDistance, SubOrbVelocity
References: Zarchan, P. (2002) Tactical and Strategic Missile Guidance, 4th Edition, pp. 239-244.
References abs(), and(), LaunchConstants(), SubOrbDistance(), SubOrbVelocity(), and zeros().
Referenced by SubOrbDistance(), SubOrbTrajAnalysis(), and SubOrbVelocity().
SubOrbMaxRange()
function SubOrbMaxRange (in V)
given initial velocity.
 Also returns the initial flight path angle required to reach the max
 range.
 Assumes spherical Earth and initial / final altitudes of zero.
 Since version 1.0
Form
 [maxRange,gammaOpt] = SubOrbMaxRange( V );
Inputs
 V           (1,N)   Initial velocity (km/s)
Outputs
 maxRange    (1,N)   Maximum range around the Earth (km)
 gammaOpt    (1,N)   Optimal flight path angle to reach max range (rad)
References: Zarchan, P. (2002) Tactical and Strategic Missile Guidance, 4th Edition, pp. 239-244.
References and().
SubOrbTrajAnalysis()
function SubOrbTrajAnalysis (in lla0, in llaF, in tFDes, in dragIsOn)
 Generates multiple sub-orbital trajectories that connect the given
 coordinate sets. Creates plots to analyze the relationship
 between time of flight, initial velocity, initial flight path angle,
 maximum altitude.
 Simplifications made for this analysis:
 + Desired velocity is applied instantaneously -- no launch dynamics.
 + The rotation of the Earth is ignored
 + Atmospheric forces are ignored
 Since version 1.0
Form
 d = SubOrbTrajAnalysis( lla0, llaF, tFDes, dragIsOn )
Inputs
 lla0            (3,1)    Initial latitude, longitude, altitude
 llaF            (3,1)    Final
 tFDes           (1,:)    Desired time of flight
 dragIsOn        (1,1)    Optional, default is 0 (off)
Outputs
 d                (.)   Data structure of output
References and(), Circle(), connect(), Demo(), LaunchConstants(), length(), Mag(), NewFig(), RHS(), RK4TI(), set(), SubOrbDistance(), SubOrbLambert(), SubOrbTrajAnalysis(), and zeros().
Referenced by SubOrbTrajAnalysis().
SubOrbVelocity()
function SubOrbVelocity (in gamma, in h0, in hF, in angleDist)
 Given an initial altitude and flight path angle, compute the required
 velocity for it to hit the target. The target is located at a given
 altitude and a specified angular distance (around the Earth).
 If not outputs are specified it will perform a simulation of the
 initial conditions using a 0.5 sec timestep, demonstrating that the
 correct trajectory is obtained.
 Since version 1.0
Form
 [V,tF,lambda] = SubOrbVelocity( gamma, h0, hF, angleDist )
Inputs
 gamma           (1,1) Initial flight path angle (rad)
 h0              (1,1) Initial altitude (km)
 hF              (1,1) Final altitude (km)
 angleDist       (1,1) Angular distance of flight around Earth (rad)
Outputs
 V               (1,1) Initial velocity required (km/s)
 tF              (1,1) Flight Time (sec)
 lambda          (1,1)
See also
SubOrbDistance, SubOrbLambert
References: Zarchan, P. (2002) Tactical and Strategic Missile Guidance, 4th Edition, pp. 239-244.
References and(), LaunchConstants(), Mag(), Plot2D(), RK4TI(), SubOrbDistance(), SubOrbLambert(), and SubOrbVelocity().
Referenced by SubOrbLambert(), and SubOrbVelocity().
ThrustAngleConstant()
function ThrustAngleConstant (in x, in d, in params)
 Since version 2015.1
Form
 angle = ThrustAngleConstant( x, d, params )
Inputs
 x        (4+n,1)   State
 d           (.)    Data structure, unused
 params      (.)    Parameters
   .thrustAngle       Constant thrust angle
Outputs
 angle    (1,1)    Commanded thrust angle
References Constant().
ThrustAngleExplicit()
function ThrustAngleExplicit (in x, in d, in params)
Computes the thrust angle based on the targeted position and velocity at burnout.
Form
 params = ThrustAngleExplicit( 'params' )
 angle = ThrustAngleExplicit( x, d, params )
Inputs
 x        (4+n,1)   State
 d           (.)    Data structure
   .rocket            Rocket model data structure
 params      (.)    Parameters
   .hT                Altitude target
   .rDotT             Velocity target
   .maxAngle          Maximum angle
   .endTime           End time (s)
Outputs
 angle    (1,1)    Commanded thrust angle
References Altitude(), and(), length(), RocketDatabase(), and SetPayloadMass().
ThrustAngleGravity()
function ThrustAngleGravity (in x, in d, in params)
 Since version 2015.1
Form
 angle = ThrustAngleGravity( x, d, params )
Inputs
 x        (4+n,1)   State
 d           (.)    Data structure, unused
 params      (.)    Parameters
                      None.
Outputs
 angle    (1,1)    Commanded thrust angle (zero)
ThrustAngleVGain()
function ThrustAngleVGain (in x, in d, in params)
Computes the thrust angle based on the targeted velocity at burnout. Will predict the burnout radius for a target.
Form
 params = ThrustAngleVGain( 'params' )
 angle  = ThrustAngleVGain( x, d, params )
Inputs
 x        (4+n,1)   State
 d           (.)    Data structure
   .rocket            Rocket model data structure
   .Rp                Planet radius
 params      (.)    Parameters
    .hT               Target altitude, optional
Outputs
 angle    (1,1)    Commanded thrust angle
Reference: Battin, Revised Edition, Sect. 11.7 Powered Orbital Transfer Maneuvers
References Cross(), isempty(), length(), RocketDatabase(), SetPayloadMass(), and Unit().
ThrustControlConstantAngle()
function ThrustControlConstantAngle (in r, in v, in d, in params)
For use with GuidedLaunch3D.
Form
 [on,thrustDir] = ThrustControlConstantAngle( r, v, d, params )
Inputs
 r             (3,1)   ECI position (km)
 v             (3,1)   ECI velocity (km/s)
 d              (.)    Model data
         Rp            (1,1)   Planet radius (km)
 params         (.)    Parameters
         minAlt        (1,1)   Altitude above which to apply thrust (km)
         angle         (1,1)   Angle above local horizon to apply thrust (rad)
Outputs
 on            (1,1)   Whether thrust is commanded on or not.
 thrustDir     (3,1)   ECI unit thrust direction
References Altitude(), GuidedLaunch3D(), Mag(), QLVLH(), and QTForm().
Referenced by GuidedLaunch3D().
ThrustControlGravityTurn()
function ThrustControlGravityTurn (in r, in v, in d, in params)
Use with GuidedLaunch3D.
Computes the unit thrust direction along the current ground-relative velocity vector of the vehicle. When the velocity is very close to the initial velocity of the vehicle, the thrust direction is instead defined to be along the position vector.
Form
 [on,thrustDir] = ThrustControlGravityTurn( r, v, d, params )
Inputs
 r             (3,1)   ECI position (km)
 v             (3,1)   ECI velocity (km/s)
 d              (.)    Model data
        .Rp            (1,1)   Planet radius (km)
        .v0            (1,1)   Initial ECI velocity.
 params         (.)    Parameters
        .minAlt        (1,1)   Altitude above which to apply thrust (km)
Outputs
 on            (1,1)   Whether thrust is commanded on or not.
 thrustDir     (3,1)   ECI unit thrust direction
References Altitude(), close(), GuidedLaunch3D(), Mag(), Unit(), and vector().
Referenced by GuidedLaunch3D().
ThrustControlRaiseApogee()
function ThrustControlRaiseApogee (in r, in v, in d, in params)
 Use with GuidedLaunch3D.
 Computes the apogee of the current state. If it is less than the
 desired apogee, it calls the ApogeeRaisingDeltaV function to compute
 the desired thrust direction for raising the apogee. If the altitude is
 close to the desired apogee, it applies thrust along the vector
 difference between the desired orbital velocity and the current
 velocity to circularize the orbit.
 Since version 1.0
Form
 [on,thrustDir] = ThrustControlRaiseApogee( r, v, d, params );
Inputs
 r             (3,1)   ECI position (km)
 v             (3,1)   ECI velocity (km/s)
 d              (.)    Model data
        .mu            (1,1)   Gravitational parameter
 params         (.)    Parameters
        .rA            (1,1)   Desired apogee (km)
Outputs
 on            (1,1)   Whether thrust is commanded on or not.
 thrustDir     (3,1)   ECI unit thrust direction
References AE2RPRA(), and(), ApogeeRaisingDeltaV(), close(), GuidedLaunch3D(), Mag(), RV2AE(), Unit(), and vector().
Referenced by GuidedLaunch3D().
TSFCToIsp()
function TSFCToIsp (in tSFC)
Form
 iSp = TSFCToIsp( tSFC )
Inputs
 tSFC  (1,:) Thrust specific fuel consumption (kg/N-s)
Outputs
 iSp   (1,:) Specific impulse (s)
References Plot2D(), and TSFCToIsp().
Referenced by TSFCToIsp().
TSTODragData()
function TSTODragData (in dO, in dF)
 Assumes a horizontally launched ferry stage with an orbiter stage.
 Type TSTODragData for a demo.
Form
 d = TSTODragData( dO, dF )
Inputs
 dO       (.)  Orbiter data structure
                .massH2      (1,1) Mass of liquid hydrogen
                .massO2      (1,1) Mass of liquid oxygen
                .wingArea    (1,1) Wing area
 dF       (.)  Ferry data structure
                .massH2      (1,1) Mass of liquid hydrogen
                .massO2      (1,1) Mass of liquid oxygen
                .massJP      (1,1) Mass of jet fuel
                .wingArea    (1,1) Wing area
Outputs
 d        (.)  Data structure
               .l   (1,1) Aircraft length (m)
               .h   (1,:) Altitude (m)
               .p    (.)  Standard Atmosphere structure
               .b   (1,1) Span (m)
               .s   (1,1) Surface area (m^2)
               .v   (1,1) Volume (m^3)
               .sL (1,1) Lifting surface  (m^2)
References Altitude(), and(), Demo(), length(), LiftAndDragJonesSearsHaack(), TSTODragData(), TSTOFlightProfile(), and Wing().
Referenced by TSTODragData().
TSTOFlightProfile()
function TSTOFlightProfile ()
Form
[m, h, p, v] = TSTOFlightProfile
Inputs
 None.
Outputs
 m  (1,:) Mach number
 h   (1,:) Altitude (m)
 p   (1,1) Standard atmosphere data
 v   (1,:) Velocity (m/s)
References Altitude(), length(), Plot2D(), StdAtm(), Step(), TemperatureStagnation(), and TSTOFlightProfile().
Referenced by TSTODragData(), and TSTOFlightProfile().
TSTOSizing()
function TSTOSizing (in d, in p, in f, in tol)
 The mission is:
 Stage 0 (Stages 1 and 2 combined)
 Takeoff roll
 Liftoff
 Constant angle climb
 Separation
 Stage 1
 Turn to landing
 Descent
 Landing
 Stage 2
 Insertion into transfer orbit
 Insertion into circular orbit
 Reentry interface burn
 Gliding reentry
 Landing
 The separation height an Mach number are inputs. This fixes the upper
 stage mass.
 The filename should be entered without at suffix. The outputs will be
 f_table.txt
 f_param.txt
 f_table.txt has the mass and velocity table
 Since version 1.0
Form
 d = TSTOSizing( d, p, f, tol )
Inputs
 d               (1,1) Data structure of vehicle parameters
 p               (1,1) Data structure of orbit
                       .rAT (1,1) Apogee of target orbit
                       .mu  (1,1) Gravitational parameter
                       .rEI (1,1) Radius of entry interface
                       .c1  (1,1) LTVCON parameter
                       .c2  (1,1) LTVCON parameter
                       .hS  (1,1) Separation altitude
                       .MS  (1,1) Separation Mach number
                       .MR  (1,1) Mach number to switch to ramjet
 f               (1,:) Filename for saving latex output
 tol             (1,1) Tolerance on mass
Outputs
 d               (1,1) Data structure ef vehicle parameters
                       .stage0 Data structure of stage 0 parameters
                               .events {:} Events
                               .param (1,1) Parameter data structure
                       .stage1 Data structure of stage 1 parameters
                               .events {:} Events
                               .param (1,1) Parameter data structure
                       .stage2 Data structure of stage 1 parameters
                               .events {:} Events
                               .param (1,1) Parameter data structure
References and(), Constant(), Demo(), Parameter(), Takeoff(), and TSTOSizing().
Referenced by TSTOSizing().
TurboRamjetSim()
function TurboRamjetSim (in x, in tEnd, in dT, in d, in plott)
 It transitions from turbofan to ramjet at d.mTransition.
 Type TurboRamjetSim for a demo.
 Since version 1.0.
Form
 d = TurboRamjetSim;
 [mFuel,machNo,x,xP,t] = TurboRamjetSim( x, tEnd, dT, d, plott )
Inputs
 x           (5,1)  [v;gamma;h;m;range]
 tEnd        (1,1)  End time
 dT          (1,1)  Time step
 d            (.)   Data structure
                    .engine       (.)  Engine data
                    .machEnd     (1,1) Mach end condition
                    .altitudeEnd (1,1) Altitude end condition
                    .atmData      (.)  For StdAtm
                    .cDCL         (f)  Function handle
                    .tFcn         (f)  Function handle
                    .rP          (1,1) Planet radius (m)
                    .g           (1,1) Gravity (m/s2)
                    .aero         (.)  Aero data structure
                    .constrainGamma    Flag
 plott       (1,1)  1 = plot, 0 = no plot
Outputs
 mFuel       (1,:)  Mass of fuel consumed (kg)
 machNo      (1,1)  Final Mach number
 x           (5,1)  Final state
 xP          (7,:)  [x;machNo;alpha];
 t           (1,:)  Time vector for xP
See also
Ramjet, Turbofan, SimpleLiftAndDrag, Turbofanramjet,
ComputeAlphaConstantFlightPathAngle
References Altitude(), ComputeAlphaConstantFlightPathAngle(), Demo(), Initialize(), Ramjet(), RHS2DPointMass(), RK45(), SimpleLiftAndDrag(), StdAtm(), TimeLabl(), Turbofan(), Turbofanramjet(), TurboRamjetSim(), vector(), and zeros().
Referenced by TurboRamjetSim().
VEFToVGamAz()
function VEFToVGamAz (in vEF, in lat, in lon)
 Since version 2015.1
Form
 [V,gamma,az] = VEFToVGamAz( vEF )
Inputs
 vEF           (3,1)    Earth fixed frame velocity vector
 lat           (1,1)    Latitude             (rad)
 lon           (1,1)    Longitude            (rad)
Outputs
 V             (1,1)    Velocity magnitude   (km/s)
 gamma         (1,1)    Flight path angle    (rad)
 az            (1,1)    Azimuth angle        (rad)
See also
ENUToECEF
References and(), ENUToECEF(), Mag(), and vector().
VonBraunRocket()
function VonBraunRocket ()
 This model is not in the database because it is so much larger than any
 physical rocket in existence, however it is used in examples in many
 textbooks. This design used nitric acid and hydrazine in all three
 stages.  The rocket would have stood over 80 m tall.
 Since version 2015.1
Form
 d = VonBraunRocket
Outputs
 d              (.)        Rocket data structure
Reference: Wiesel, W. E., Spaceflight Dynamics, McGraw-Hill, 1988, pp. 196-197 and table 7-2.
References and(), CreateRocketModel(), SetPayloadMass(), and VonBraunRocket().
Referenced by VonBraunRocket().
WingedLaunchVehicleDesign()
function WingedLaunchVehicleDesign (in varargin)
It can layout a vehicle with a rocket engine or a jet engine. It automatically sizes the fuselage to carry the fuel load.
Type WingedLaunchVehicleDesign for a demo.
Form
 [d,l] = WingedLaunchVehicleDesign( varargin )
Inputs
 varargin       Parameter pairs
Outputs
 d              (.)    Data structure
 l              {:,3}  Latex formatted output
References Parameter(), and WingedLaunchVehicleDesign().
Referenced by WingedLaunchVehicleDesign().
WriteEngineData()
function WriteEngineData (in fileName, in d)
 The text file is compatible with the DSim2 function sc_ac_engine.cc/h.
 Performs a demo using SRT data for the turbofan and ramjet.
 Since version 1.0
Form
 WriteEngineData( fileName, d )
Inputs
 fileName    (1,:)  Filename
 d            (.)   Data structure with thrust and sFC data
                    .m        (1,n) Mach number
                    .h        (1,m) Altitude (m)
                    .thrust   (m,n) Thrust (N)
                    .sFC      (m,n) Specific fuel consumption  (kg/N-s)
Outputs
 None
References Altitude(), and(), Demo(), FindDirectory(), length(), and WriteEngineData().