var group___straight_line_demos =
[
    [ "AlphaCentauri", "dir_1dcd38da17e97a50e54ff74d3c1504bd.html", null ],
    [ "ConstantThrust", "dir_df51eb1c524b37320b5f306a0d860850.html", null ],
    [ "Flyby", "dir_9457178f670577dda38787abe20d6377.html", null ],
    [ "Rectilinear", "dir_278e00d02e1341c4afdd76e7bb3f47ce.html", null ],
    [ "SLPowerLimited", "dir_2a3fb38988c028268cf06a36a2ef0d1d.html", null ],
    [ "AlphaCentauriFlyby.m", "_alpha_centauri_flyby_8m.html", null ],
    [ "DataRateAlphaCentauri.m", "_data_rate_alpha_centauri_8m.html", null ],
    [ "DistanceForFixedTime.m", "_distance_for_fixed_time_8m.html", null ],
    [ "DurationDemo.m", "_duration_demo_8m.html", null ],
    [ "DVLimitDemo.m", "_d_v_limit_demo_8m.html", null ],
    [ "DVMapDemo.m", "_d_v_map_demo_8m.html", null ],
    [ "DVvsTripTime.m", "_d_vvs_trip_time_8m.html", null ],
    [ "FlybyForFixedTime.m", "_flyby_for_fixed_time_8m.html", null ],
    [ "MaxDistanceDemo.m", "_max_distance_demo_8m.html", null ],
    [ "NASADemos.m", "_n_a_s_a_demos_8m.html", null ],
    [ "NASAMissionChart.m", "_n_a_s_a_mission_chart_8m.html", null ],
    [ "OptimalImpulseDemo.m", "_optimal_impulse_demo_8m.html", null ],
    [ "PayloadDemo.m", "_payload_demo_8m.html", null ],
    [ "PayloadFractionDemo.m", "_payload_fraction_demo_8m.html", null ],
    [ "PointSolution.m", "_point_solution_8m.html", null ],
    [ "PowerLimitedRocket.m", "_power_limited_rocket_8m.html", null ],
    [ "RectilinearDemo.m", "_rectilinear_demo_8m.html", null ],
    [ "SLPLComparisonDemo.m", "_s_l_p_l_comparison_demo_8m.html", null ],
    [ "StraightLineAlphaCentauri.m", "_straight_line_alpha_centauri_8m.html", null ],
    [ "TripTimeDemo.m", "_trip_time_demo_8m.html", null ],
    [ "UEVsSigma.m", "_u_e_vs_sigma_8m.html", null ]
];