PSS MATLAB Toolboxes: AerospaceUtils Functions
AerospaceUtils Functions
AerospaceUtils Module
The AerospaceUtils module functions.
Directories
directory CAD
CAD model and OBJ file utilities. .
directory ComponentModels
CAD component models. .
directory Coord
Coordinate transformations. .
Description
Functions
function AddCubesatComponent (in varargin)
Add a component to a CAD model.
function AddThermalDevices (in g, in heaterPower)
Add a heater and thermistor to each component.
function AirCoreTorquerModel (in nTurns, in rWire, in dims)
Get vertices and faces for an air core magnetic torquer CAD component.
function AirData (in v, in altitude, in AtmData, in units)
Computes air data based on a simplified standard atmosphere model.
function AntennaPatch (in x, in y, in d, in theta, in u, in t, in n)
Get vertices and faces for an antenna CAD component.
function AreaTriMesh (in v, in f)
Computes the area of a triangle mesh.
function ArrayPatch (in d)
Get vertices and faces for solar array CAD models.
function AtmDens1 (in h, in planet)
Computes the atmospheric density using an exponential model.
function AtmDens2 (in h)
Computes the Earth's atmospheric density using scale heights.
function AtmGamma (in T)
Computes the ratio of specific heats for air.
function AtmJ70 (in d)
Computes the atmospheric density using Jacchia's 1970 model.
function AtmSnd (in T)
Computes the speed of sound in the atmosphere.
function AtmTemp (in h)
Computes the atmospheric temperature using a simplified model.
function AutoCADColor (in k)
Converts an AutoCAD color into a [r,g,b] color.
function AzCoElToU (in az, in co)
Converts azimuth and coelevation to a unit vector.
function AzElRangeRangeDotToRV (in az, in el, in range, in rangeDot)
Compute r, v from range, range rate, az and el.
function AzElToU (in az, in el)
Converts azimuth and elevation to a unit vector.
function BankAngle (in r, in ignoredArg, in n, in x)
Bank angle computations.
function BaromExp (in z, in tX, in t90)
Computes the barometric exponent.
function BHinge (in bHinge)
Compute a transformation matrix from a bHinge data structure.
function BinaryToString (in b)
Converts a bit array to a string.
function BodyPlugIn (in action, in modifier, in hFig, in position, in callback)
Create the CAD body GUI plug in.
function BoundingBox (in c)
Compute a bounding box for a component.
function BuildCADModel (in action, in modifier, in mod2, in mod3, in mod4)
Build a model of a spacecraft using repeated calls to this function.
function CADColor (in action, in g)
Color a CAD Model.
function CADNotebook (in g, in varargin)
Work with a model using the CAD data structure.
function CameraModel (in type, in uBoresight)
Get CAD vertices and faces for a star camera model.
function CentroidOBJFile (in file, in path)
Computes the centroid of an obj file.
function CircuitBoard (in board, in component)
Get vertices and faces for a circuit board CAD model.
function CombineOBJFiles (in file, in fileNew, in b, in scale, in delta, in flip)
Combines obj files and writes a new file.
function CompactPCIChassis (in n)
Get vertices and faces for a CompactPCI 3U Chassis CAD component.
function ComponentPlugIn (in action, in modifier, in hFig, in position, in callback)
Create an component GUI plug in.
function ComponentPopup (in component)
Draw a component.
function CoordinateTransform (in from, in to, in x, in jD)
Transform between selected coordinate frames and representations.
function CreateBody (in action, in varargin)
Create a body with hinge data.
function CreateCADReport (in g, in type, in fileName)
Creates CAD model report.
function CreateCADTable (in g, in fileName)
Creates a CAD Report by subystem.
function CreateComponent (in action, in type, in varargin)
Create a CAD component.
function CreateReport (in g, in type, in fileName, in report, in bySubsystem, in noZero, in summary)
Creates power and mass reports from a CAD model.
function CrossSection (in g, in bodyAngle, in viewV, in plot)
Determine cross-sectional area from CAD model.
function CylindricalTank (in r, in l, in n)
A cylindrical tank with spherical end caps.
function DeltaWing (in angle1, in angle2, in angleTE, in z1, in z2, in xTE, in n, in lERatio, in taper, in tRatio, in tTE)
Get vertices and faces for a single or double delta wing CAD model.
function DeviceProperties (in type, in m, in properties, in values, in computeInertia)
Generates default properties for specific devices.
function DiffusionExp (in z, in tX, in t90, in tE)
Computes the diffusion exponent.
function Dim (in varargin)
Set the transparency for components of a particular name.
function DownrangeAndAltFromTarget (in r, in rT)
Finds the altitude and downrange from a target on a planet.
function Draw2DViewPlugIn (in action, in modifier, in hFig, in position)
Draw the spacecraft CAD components in a 2D representation.
function DrawPatch (in varargin)
Draw a series of patches.
function DrawSCPlanPlugIn (in action, in modifier, in hFig, in position)
Draw a spacecraft CAD model in a plain 3D box with Gouraud lighting.
function DrawSpacecraftPatches (in hAxis, in g, in B0, in r0, in ambientStrength, in scale, in explode)
Draw the spacecraft CAD model using patches.
function ECEFToLLA (in rECEF, in rP)
Compute latitude, longitude, altitude from ECEF position.
function ECIToEF (in T)
Computes the matrix from mean of Aries 2000 to the earth fixed frame.
function EFToLatLonAlt (in r, in f, in a, in tol)
Convert an earth fixed position vector to [latitude;longitude;altitude].
function ExportCAD (in g, in fileName)
Export a CAD file to a text file.
function ExportDSim (in g, in fileName, in default, in package)
Export fields required by DSim.
function ExportDXF (in g, in fileName)
Export a DXF file.
function ExportOBJ (in g, in fileName)
Export an OBJ file.
function ExportVerticesToOBJ (in v, in f, in fileName)
Export an OBJ file from vertex and face data.
function FindComponents (in g, in field, in str, in caseSensitive, in exact)
Find the indices of components containing a particular string.
function FLagrange (in x, in v, in lPoint)
Lagrange point RHS.
function ForceAndTorqueEnvelope (in u, in r, in thrust, in n)
Computes the force and torque envelope.
function Fuselage (in middle, in front, in back, in type, in n)
Get vertices and faces for a fuselage CAD model.
function Gc2GdLat (in geoc, in f)
Convert geocentric latitude to geodetic latitude.
function Gd2GcLat (in geod, in f)
Convert geodetic latitude to geocentric latitude.
function GenericProperties (in type, in varargin)
Generates generic properties for CAD components.
function GetCADVF (in g, in notInside)
Return a single set of vertices "v" and faces "f" for the CAD model.
function GetSubsystemMass (in g, in subsystem)
Compute the total mass in the requested subsystem.
function HallThrusterModel (in s)
Get CAD vertices and faces for a Hall thruster.
function HorizonAngle (in rG, in rS)
Angle between the horizon and a vector from rG to rS.
function HSRCAD (in v, in f, in z, in n, in showScans)
Finds the visible surfaces given a vertex and face list.
function ICONS (in demo)
Get CAD vertices and faces for the Integrated Communications and Navigation Sensor.
function IntersectPlanet (in r1, in r2, in a)
Altitude of the nearest point to a sphere.
function JacchiaLineberry (in d, in use70)
Jacchia-Lineberry model of the upper atmosphere.
function LAETR308CAD ()
Generate CAD vertices and faces for a Northrop Grumman TR-308 engine.
function LatLonAltToEF (in x, in f, in a)
Convert [latitude;longitude;altitude] to an earth fixed position vector.
function LatLonToR (in lat, in lon, in f, in a, in type)
Converts geodetic latitude and longitude to r for an ellipsoidal planet.
function LLAToECEF (in lla, in rP)
Compute ECEF position from latitude, longitude, altitude.
function LoadCAD (in file, in path, in format, in kScale)
Load a 3D CAD file.
function LoadOBJFile (in file, in kScale)
Load a 3D CAD file.
function LunarModuleFirstStage ()
Get CAD vertices and faces for a lunar module first stage.
function LunarModuleSecondStage ()
Generates a CAD component for a lunar module ascent stage.
function MassBudget (in c, in type, in fileName, in nIts)
Create a mass budget for a flight vehicle.
function MassBudgetInput (in varargin)
Create a data structure for MassBudget.
function MatlabColorToObj (in faceColor, in specularStrength, in specularExponent, in diffuseStrength, in specularColorReflectance)
Convert Matlab color parameters to obj parameters.
function NoseCone (in r, in l, in n, in h)
Get CAD vertices and faces for a nose cone.
function NuclearReactorModel (in powerThermal, in conversionEfficiency, in unitVector)
Get CAD vertices and faces for an SP-100 based space nuclear reactor.
function OmegaFromU (in u, in omega)
Finds a total angular rate from a set of unit vectors.
function OmegaLVLH (in r, in v)
Generate the LVLH angular rate vector.
function Panel (in r, in n)
Get CAD vertices and faces for a panel in the x, y plane.
function PanelBoxCAD (in xBox, in yBox, in zBox, in panelThickness, in rho, in materialPanel, in materialFrame, in r, in mass, in bodyID)
Build a box with panels.
function PanelFrame (in x, in y, in h, in t)
Get CAD vertices and faces for a frame for a honeycomb panel.
function Panels (in x, in y, in z, in face)
Draw panels for a spacecraft.
function PanelWithCenterHole (in rO, in rI, in nO, in nI)
Get CAD vertices and faces for a panel with a center hole.
function PanelWithCutout (in xW, in yW, in t, in c)
Get CAD vertices and faces for a panel with a cutout.
function Q2RADec (in u, in q)
Compute right ascension and declination of a vector from a quaternion.
function QAcq (in uTrue, in uMeas)
Given at least three vectors computes the initial quaternion.
function QAlign (in q0, in uBAxis, in uBVec, in uITarget)
Rotate about a body axis to align a body vector with an inertial vector.
function QFrom2U (in u1ECI, in u2ECI, in u1, in u2)
Finds a quaternion with u1 aligned with u1ECI and u2 close to u2ECI.
function QHills (in rE, in vE)
Generate the quaternion that transforms from the ECI to the Hills frame.
function QIToBDot (in q, in w, in dT)
Computes the time derivative of a quaternion.
function QLatLon (in lat, in lon, in r, in v, in q, in f, in a)
Generate the quaternions that transform from ECI to a lat/long frame.
function QLVLH (in r, in v)
Generate the quaternions that transform from ECI to LVLH coordinates.
function QNadirPoint (in r, in v, in uB)
Generate a quaternion that points a body vector uB towards nadir.
function QRotateToAlign (in axis, in ua, in ut)
Rotate about an axis to align "ua" as close as possible to target "ut".
function QSLERP (in qFrom, in qTo, in t)
Interpolate a quaternion using the SLERP algorithm.
function QToPFTarget (in x, in lat, in lon, in rECI, in jD, in planet, in type)
Generate a quaternion to go to a planet fixed lat/long target.
function R2LatLon (in x, in y, in z)
Computes geocentric latitude and longitude from r.
function RaDec2Q (in u, in rA, in dec)
Right ascension and declination to a quaternion.
function REAModel (in type, in uPlume)
Get CAD vertices and faces for General Dynamics REAs.
function ReynoldsNumber (in rho, in v, in mu, in x)
Reynold's number as a function of atmospheric density.
function RollPitchToQECI (in r, in v, in roll, in pitch)
Convert roll, pitch, r and v to QECIToBody.
function RotateOBJFile (in file, in path, in b, in scale, in delta, in flipNormal)
Rotates and scales an obj file name.obj.
function RVToRADec (in r, in v)
Computes right ascension and declination and their rates.
function RWAArray (in model, in cantAngle, in wH, in b, in rA, in body)
Get CAD components for an array of four reaction wheels.
function RWAModel (in r, in u)
Get CAD vertices and properties for a specific RWA model.
function RWAPatch (in r, in u)
Get CAD vertices for an RWA.
function SaturnsRings ()
Get CAD vertices and faces for the rings of Saturn.
function SCMG (in rR, in rG, in hR, in hG, in n)
Get CAD vertices and faces for a single-axis control moment gyro.
function SetCADQuaternion (in g, in qECIToBody)
Set the inertial attitude of a CAD model.
function SetCADRotation (in g, in varargin)
Set CAD model rotations using parameter/value pairs.
function SetCADState (in g, in rECI, in vECI)
Set the inertial state of a CAD model.
function SHELSFlange ()
Get CAD vertices and faces for the SHELS Flange component.
function SHELSInterface ()
Get vertices and faces for the SHELS Interface CAD components.
function ShowCAD (in g)
Display a stored CAD model in a plain 3D box using DrawSCPlanPlugIn.
function SimpleFuselage (in w, in lMiddle, in lTop, in h, in zM)
Get CAD vertices and faces for a simple fuselage.
function SolarWingSupport (in w, in l, in t)
Get CAD vertices and faces for a triangle strut for a solar wing.
function SpacecraftPlugIn (in action, in modifier, in hFig, in position, in callback)
Create a Spacecraft GUI plug in.
function StarCameraBasicModel (in a, in fL, in aS, in lS)
Get vertices and faces for a basic star camera CAD component.
function StarCameraModel (in type, in uBoresight)
Get CAD vertices and faces for various star cameras.
function SunAzEl (in varargin)
Approx.
function SurfaceOfRevolution (in r, in z, in n, in ang)
Generate CAD vertices and faces for a surface of revolution about z.
function SutherlandsLaw (in t, in mu0, in t0, in s)
Sutherland's law for dynamic viscosity.
function TargetFromRPVD (in r, in rP, in v, in d)
Finds a target on a planet.
function TemperatureStagnation (in v, in h, in r)
Compute the stagnation temperature in the earth's atmosphere.
function TesselatePolygon (in g)
Tesselate polygons by breaking them into triangles.
function ThrusterCAD (in uPlume, in dExit, in l, in n, in rC, in lC, in lOC)
Get CAD vertices and faces for a thruster model.
function ThrusterPatch (in uPlume, in dExit, in l, in n, in hasBox)
Get vertices and faces for a thruster CAD component.
function TPlate (in xB, in xT, in yB, in yT, in h)
Generate CAD vertices and faces for a T-shaped plate.
function TreeBldCAD (in g, in s, in spring)
Take the CAD data and create the body array for Tree.
function TreeDraw (in g, in x, in treeDS)
Update the 3D drawing data structure.
function TriMesh3DMF (in v, in vM, in fileName, in colorAtt)
Generate a 3DMF for a trimesh.
function TubeBetweenPoints (in x1, in x2, in r, in n)
Generate CAD vertices and faces for a tube going from x1 to x2.
function U2AzEl (in u, in x, in y)
Converts a unit vector to azimuth and elevation.
function U2RADec (in u, in ignoredArg)
Computes the right ascension and declination from a unit vector.
function USR30Motor (in demo)
Generate CAD vertices and faces for a motor model.
function Wing (in xLE, in xTE, in z, in lERatio, in taper, in tOC, in angle)
Generate vertices and faces for a wing.
function XenonTank (in mXenon)
Generate a Xenon Tank CAD model based on the ETS VIII Tank.
function XenonTankSupport (in l)
Generate CAD vertices for a Xenon Tank support based on the ETS VIII Tank.
Function Documentation
AddCubesatComponent()
function AddCubesatComponent (in varargin)
Position or length units are in mm. To use this function type
 AddCubesatComponent( 'My CubeSat Name' );
Then call it once for each component with pairs of inputs. Some examples:
AddCubesatComponent('device', 'frame', 'name', 'Frame', 'subtype', '3U')
AddCubesatComponent('device', 'board', 'name', 'CPU', 'position',
cPUBoardPosition, 'power', cPUBoardPower)
'position' is an array [x;y;z] except for boards when it is the z position in the frame. Boards fill up the entire crossectional area.
Type AddCubesatComponent for a demo.
List of input types supported:
 device
 name
 subtype
 position
 power
 unit vector
 boresight
 mass
 outward normal
 dimensions
 dipole
 color
 transformation matrix
 file
 path
List of INSIDE devices supported:
 board
 gps
 box
 rectangular hysteresis damper
 cylindrical hysteresis damper
 reaction wheel
 imu
 torquer
 external (OBJ file)
List of OUTSIDE devices supported:
 frame
 antenna
 solar panel
 goid foil
 radiator
 camera
 magnetometer
Form
 AddCubesatComponent( varargin )
Inputs
 varargin       {} Pairs of 'type' and 'data'
Outputs
 None
References AddCubesatComponent(), length(), and vector().
Referenced by AddCubesatComponent().
AddThermalDevices()
function AddThermalDevices (in g, in heaterPower)
It only adds devices to the subsystems that exist when this is called.
Form
 AddThermalDevices( g, heaterPower )
Inputs
 g               (1,1)  Component data structure
 heaterPower     (1,1)  Heater power
Outputs
 None
References and().
AirCoreTorquerModel()
function AirCoreTorquerModel (in nTurns, in rWire, in dims)
Type AirCoreTorquerModel for a demo.
Form
 [v, f] = AirCoreTorquerModel( nTurns, rWire, dims )
Inputs
 nTurns      (1,1) Wire turns
 rWire       (1,1) Wire radius (m)
 dim         (1,2) Dimensions of the coil (m)
Outputs
 v           (:,3) Vertices
 f           (:,3) Faces
References AirCoreTorquerModel(), and(), Box(), Demo(), and DrawVertices().
Referenced by AirCoreTorquerModel().
AirData()
function AirData (in v, in altitude, in AtmData, in units)
If no arguments are specified it will plot m and q versus v and h.
Type AirData for demo.
Form
 [m, q, rho, pS] = AirData( v, altitude, AtmData, units )
Inputs
 v          (1,:)       Velocity (m/sec)
 altitude   (1,:)       Altitude (m)
 AtmData    (:,6)       Standard atmosphere data
 units      (1,:)       'si' or 'eng' i.e. m & kg or lb & ft
Outputs
 m          (v,h)       Mach number
 q          (v,h)       Dynamic Pressure
 rho        h           Density
 pS         h           Static Pressure
References abs(), AirData(), Altitude(), and(), Demo(), length(), NewFig(), Pressure(), StdAtm(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by AC(), ACEngEq(), ACSensor(), AirData(), AirshipStabConDerivatives(), and AirshipTrim().
AntennaPatch()
function AntennaPatch (in x, in y, in d, in theta, in u, in t, in n)
The vertices are defined as x width, y width, d depth, u boresight and t is the unit vector along x. Patch means graphical object.
Type AntennaPatch for a demo.
Since version 2.
Form
 [v, f] = AntennaPatch( x, y, d, theta, u, t, n )
Inputs
 x           (1,1) X width
 y           (1,1) Y width
 d           (1,1) Depth
 theta       (1,1) Angle that represents the part of a sphere (rad)
 u           (3,1) Boresight unit vector
 t           (3,1) X axis unit vector
 n           (1,1) Number of divisions
Outputs
 v           (:,3) Vertices
 f           (:,3) Faces
References and(), AntennaPatch(), Cross(), DrawVertices(), GeomPatch(), isempty(), Unit(), and vector().
Referenced by AntennaPatch().
AreaTriMesh()
function AreaTriMesh (in v, in f)
Form
 a = AreaTriMesh( v, f )
Inputs
 v               (:,3)  Vertices
 f               (:,3)  Faces
Outputs
 area            (1,1)  Area
References AreaTriMesh(), Demo(), and Unit().
Referenced by AreaTriMesh(), and PanelWithCutout().
ArrayPatch()
function ArrayPatch (in d)
Two sets are created, one for the front and one for the back. The array is nominally in the xz-plane. Its center is at x = 0 and it goes from z = 0 to z = length. The cell face normal is +Y.
If there are no outputs the function will draw the components in a figure.
Form
 [mFront, mBack] = ArrayPatch( d )
Inputs
 d                 Data structure
                   d.nZ          Number of segments along z
                   d.nX          Number of segments along x
                   d.z           Dimension of each panel in z
                   d.x           Dimension of each panel in x
                   d.theta(d.nX) Angle between panels along z. Sign determines
                                 the sign of the first panel.
                                 One element is required for each nX
                                 If omitted will be set to zero.
                   d.flat        If true don't alternate angles
                   d.dirZ        If entered gives the direction for z
Outputs
 mFront            struct( 'v', 'f' )
 mBack             struct( 'v', 'f' )
References and(), length(), and set().
AtmDens1()
function AtmDens1 (in h, in planet)
If planet is not entered the default is earth. It has coefficients for all of the planets, Europa, and Titan. You can enter [] for h. If you just enter the planet, it will create a range of h.
The Earth model has an additional scaling coefficient in the exponent.
Type AtmDens1 for demo.
Form
 rho = AtmDens1( planet )
 rho = AtmDens1( h )
 rho = AtmDens1( h, planet )
Inputs
 h          (1,:)   Altitude (km)
 planet     (1,:)   'earth', 'mercury', 'venus', 'mars',
                    'jupiter', 'europa', 'saturn', 'uranus',
                    'neptune', 'pluto'
Outputs
 rho        (1,:)   Atmospheric Density kg/m^3
Reference: Lang, K. R., "Astrophysical Data: Planets and Stars", Springer-Verlag, p 50.
References Altitude(), and(), AtmDens1(), Demo(), isempty(), MolWt2R(), NewFig(), TitleS(), XLabelS(), and YLabelS().
Referenced by AtmDens1(), Disturbances(), DVOrbitDrag(), FOrbLEOP(), PlanetaryAtmDens(), PlanetEnvironment(), RelativeDisturb(), RHSLaunchVehicle3D(), RocketDrag(), and SailEnvironment().
AtmDens2()
function AtmDens2 (in h)
Valid from 0 to 1000 km.
Type AtmDens2 for demo.
Form
 rhoOut = AtmDens2( h )
Inputs
 h            (1,:) Altitude (km)
Outputs
 rhoOut       (1,:) Atmospheric Density (kg/m^3)
References: Wertz, J.R., Spacecraft Attitude Determination and Control, Kluwer, 1976, p. 820.
Referenced by AeroDragForce(), AircraftPointMassRHSWithSideslip(), AtmEarth(), AtmScaleHeightsStdAtm(), CubeSatDisturbanceAnalysis(), CubeSatEnvironment(), CubeSatLunarEnvironment(), Disturbances(), DVFromMassAndIsp(), DVOrbitDrag(), EarthEnvironment(), EnvironmentStruct(), FOrbitMultiSpacecraft(), Knudsen(), OrbitDrag(), OrbView(), PlanetaryAtmDens(), RHSCubeSat(), RHSLiftingSatellite(), RHSStateLunarMission(), RocketDrag(), SafeGuidanceSim(), SailEnvironment(), and WorstCasePerturbations().
AtmGamma()
function AtmGamma (in T)
The ratio is a function of temperature of the atmosphere.
Type AtmGamma for demo showing gamma from 0 to 80 km altitude.
Form
 gamma = AtmGamma( T )
Inputs
 T       (1,:)   Temperature (deg-K)
Outputs
 gamma   (1,:)   Ratio of specific heats
References: Hill, P.G., C. R. Peterson, Mechanics and Thermodynamics of Propulsion, Addison-Wesley, Reading, MA, 1970, p. 541.
References Altitude(), and(), AtmGamma(), Demo(), Gamma(), Plot2D(), and StdAtm().
Referenced by AtmGamma(), CD0Composite(), CDCLHypersonic(), MassFlow(), MixedFlowTurbofan(), MixedFlowTurbofanProfile(), RayleighPitotTube(), StaticPumping(), and TotalPressureAndTemperature().
AtmJ70()
function AtmJ70 (in d)
Valid above 80 km. Type AtmJ70 for demo.
Form
 [rho, nHe, nN2, nO2, nO, tZ, eM] = AtmJ70( d )
Inputs
 d    (:) Data structure
          .aP         Geomagnetic index 6.7 hours before the computation
          .dd         Day number since Jan 1., days
          .f          Daily 10.7 cm solar flux (e-22 watts/m^2/cycle/sec)
          .fHat       81-day mean of f (e-22 watts/m^2/cycle/sec)
          .fHat400    fHat 400 days before computation date
          .lat        Latitude of computation point + north (deg)
          .lng        Longitude of computation point + east (deg)
          .mm         Greenwich mean time from 0000 GMT, minutes
          .yr         Year
          .z          Geometric altitude (km)
 or
 .jD         Julian date
 .rECI       ECI position vector
 .aP         Geomagnetic index 6.7 hours before the computation
 .f          Daily 10.7 cm solar flux (e-22 watts/m^2/cycle/sec)
 .fHat       81-day mean of f (e-22 watts/m^2/cycle/sec)
 .fHat400    fHat 400 days before computation date
Outputs
 rho  (:) Density (g/cm^3)
 nHe  (:) Number density of helium
 nN2  (:) Number density of nitrogen
 nO2  (:) Number density of oxygen
 nO   (:) Number density of monatomic oxygen
 tZ   (:) Temperature
 eM   (:) Mean molecular mass
See also
SolarFluxPrediction.
Reference: Models of the Earth's Atmosphere (90 to 2500 kM) NASA SP-8021. Roberts, C.E. Jr, "An Analytic Model for Upper Atmosphere Densities Based Upon Jacchia's 1970 Models", Celestial Mechanics Vol. 4, 1971, pp. 368-377.
References abs(), and(), Constant(), CosD(), Demo(), EFToLatLonAlt(), get(), Limit(), Mag(), and vector().
Referenced by BaromExp(), CubeSatDisturbanceAnalysis(), CubeSatEnvironment(), CubeSatLunarEnvironment(), FOrbitMultiSpacecraft(), JacchiaLineberry(), SailEnvironment(), SolarFluxHistorical(), and SolarFluxPrediction().
AtmSnd()
function AtmSnd (in T)
Type AtmSnd for demo.
Form
 aOut = AtmSnd( T )
Inputs
 T            (1,:) Temperature (K)
Outputs
 aOut         (1,:) Speed of sound (m/sec)
References: Hill, P.G., C. R. Peterson, Mechanics and Thermodynamics of Propulsion, Addison-Wesley, Reading, MA, 1970, p. 541.
References and(), AtmSnd(), and Plot2D().
Referenced by AtmEarth(), AtmSnd(), and RHSLiftingSatellite().
AtmTemp()
function AtmTemp (in h)
Type AtmTemp for demo.
Form
 tOut = AtmTemp( h )
Inputs
 h          (1,:) Altitude (km)
Outputs
 tOut       (1,:) Atmospheric Temperature (K)
References: Wertz, J.R., Spacecraft Attitude Determination and Control, Kluwer, 1976, p. 820.
References Altitude(), and(), AtmTemp(), and Plot2D().
Referenced by AtmEarth(), AtmTemp(), CLCDFreeMolecular(), Knudsen(), and RHSLiftingSatellite().
AutoCADColor()
function AutoCADColor (in k)
Type AutoCADColor for demo.
Form
 rGB = AutoCADColor( k )
Inputs
 k            (1,:) AutoCAD color from 0 to 255
Outputs
 rGB          (1,3) [r, g, b]
Reference: Rule, K. (1996.) 3D Graphics File Formats. Addison-Wesley.
References AutoCADColor(), length(), NewFig(), and set().
Referenced by AutoCADColor().
AzCoElToU()
function AzCoElToU (in az, in co)
Coelevation is the angle from z and is more useful than elevation for many sensor problems.
Type AzCoElToU for a demo.
Form
 u = AzCoElToU( az, co )
Inputs
 az        (1,:)   Azimuth (rad)
 co        (1,:)   Coelevation  (rad)
Outputs
 u         (3,:)   Unit vectors
References and(), AzCoElToU(), Plot2D(), Unit(), and vector().
Referenced by AzCoElToU(), and GenerateSwath().
AzElRangeRangeDotToRV()
function AzElRangeRangeDotToRV (in az, in el, in range, in rangeDot)
The algorithm is
r = [cos(az)*cos(el);sin(az)*cos(el);sin(el)]; v = pinv(r)'*range*rangeRate;
This is a fit to velocity. With 4 measurements v cannot be known exactly. If one component is zero then the result will be exact.
Type AzElRangeRangDotToRV for a demo.
Form
 [r, v] = AzElRangeRangeDotToRV( az, el, range, rangeDot )
Inputs
 az              (1,1)  Azimuth (rad)
 el              (1,1)  Elevation (rad)
 range           (1,1)  Range
 rangeRate       (1,1)  Range rate
Outputs
 r              (3,1)  Position
 v              (3,1)  Velocity
References and().
AzElToU()
function AzElToU (in az, in el)
Type AzEleToU for a demo.
Form
 u = AzElToU( az, el )
Inputs
 az        (1,:)   Azimuth.
 el        (1,:)   Elevation.
Outputs
 u         (3,:)   Unit vectors
References and(), AzElToU(), Demo(), Plot2D(), Unit(), and vector().
Referenced by AzElToU().
BankAngle()
function BankAngle (in r, in ignoredArg, in n, in x)
The angle between the vehicle's normal axis and the Earth's vertical plane containing the aircraft's longitudinal axis. All vectors must be in the same frame.
Type BankAngle for a demo.
 function:
 sigma = BankAngle( r, v, n, x )
Inputs
 r               (3,1) Vector to vehicle
 v               (3,1) Velocity vector
 n               (3,:) Normal vectors
 x               (3,1) Longitudinal axis
Outputs
 sigma           (1,:) Bank angle (rad)
BaromExp()
function BaromExp (in z, in tX, in t90)
This is used by AtmJ70 by a quadrature routine.
Form
 x = BaromExp( z, tX, t90 )
Inputs
 z          (1,1)   Height
 tX         (1,1)   Inflection point temperature (deg-K at altitude = 125 km)
 t90        (1,1)   Assumed temperature at 90km altitude (deg-K)
Outputs
 x          (1,1)   Barometric Exponent
References AtmJ70().
BHinge()
function BHinge (in bHinge)
There are four possiblities:
 1) You can just input a transformation matrix by entering only the b field.
 2) You can input a quaternion by just entering the q field. This supercedes
 a b field.
 3) You can input an angle and axis of rotation (1=x,2=y,3=z).
 If no axis is specified, the rotation will be about the positive z-axis.
 This supercedes a quaternion.
 4) If you enter the angle field and the b field, the output transformation
 matrix will be the total rotation first through the angle about
 the specified axis followed by rotation through the initial b matrix.
 If no axis is specified, the rotation will be about the positive z-axis.
They are executed in
Form
 b = BHinge( bHinge )
Inputs
 bHinge  (.)
 .b     (3,3) Transformation matrix
 .q     (4,1) Quaternion
 .angle (1,1) Angle of rotation (radians)
 .axis  (1,1) Axis of rotation 1=x, 2=y, 3=z (default)
 Positive integer means transform from
 unrotated to rotated, negative means reverse
 or
 (3,1) Axis of rotation - see AUToQ
Outputs
 b            (3,3)  Rotation matrix
References and(), BHinge(), IsValidField(), Q2Mat(), and quaternion().
Referenced by BHinge(), CreateBody(), Disturbances(), DrawSpacecraftPatches(), FMovingBody(), HingeRotationMatrix(), and SetCADRotation().
BinaryToString()
function BinaryToString (in b)
[1 0 1 0] will become 0101.
Type BinaryToString for demo.
Form
 s = BinaryToString( b )
Inputs
 b            (1,:) Binary array
Outputs
 s            (1,:) String
References BinaryToString(), Demo(), and length().
Referenced by BinaryToString().
BodyPlugIn()
function BodyPlugIn (in action, in modifier, in hFig, in position, in callback)
Typing BodyPlugIn is the same as BodyPlugIn('initialize');
Form
 x = BodyPlugIn( action, modifier, hFig, position, callback )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifer     (1,:)  Modifier to the action or data structure if intialization
 hFig        (1,1)  Handle to the figure or if 'update' radio button handles
 position    (1,4)  [left bottom width height]
 callback    (1,:)  Callback string when something has changed in this gui
Outputs
 x           (1,1)  The tag if action is 'initialize'
References BodyPlugIn(), get(), GetNewTag(), Initialize(), isempty(), and set().
Referenced by BodyPlugIn().
BoundingBox()
function BoundingBox (in c)
Form
 b = BoundingBox( component )
Inputs
 c       (1,1) Component data structure
Outputs
 b        (3,2) [xMin, xMax;yMin yMax;zMin zMax]
References zeros().
BuildCADModel()
function BuildCADModel (in action, in modifier, in mod2, in mod3, in mod4)
A GUI displays the results. It is not designed to allow you to interactively modify the design. With no inputs it returns a list of actions. All 'add ...' require data and most return an index to the new body or component(s).
The basic structure of a script using BuildCADModel is
 BuildCADModel('initialize',...)
 kBody = BuildCADModel('add body',...)
 BuildCADModel('compute paths')      % once all bodies are added
 kComp = BuildCADModel('add component',...)
 BuildCADModel('add subsystem',...)
 BuildCADModel('set external model',g)
 g = BuildCADModel( 'get cad model' )
 BuildCADModel( 'show vehicle' )
The mass properties for the spacecraft may either be set manually or computed from the mass properties of the components. To set them manually, enter:
   BuildCADModel('set mass',mass);
where mass is a struct with fields mass (scalar), cM (3x1 vector) and inertia (3x3 matrix). The mass properties are otherwise automatically
updated when the model is retrieved or saved. To command an update, enter:
   BuildCADModel('update spacecraft mass properties');
If the mass properties are set manually, they are considered "locked", and they cannot be overwritten by an automatic update until they are un- locked. To lock or unlock the mass properties at any time, enter:
 BuildCADModel('lock mass properties');
 -or-
 BuildCADModel('unlock mass properties');
When adding components to subsystems pass in their names, as well as the name of the subsystem. The exact name is not required, i.e. 'thruster' for Thruster 1, Thruster 2, etc.
 BuildCADModel('add subsystem','subsys name',{'component 1','component 2'})
In order to perform shadowing calculations on the model, you need to explicitly generate the body-level lists vertices and faces after all the components have been added.
 BuildCADModel('create body arrays')
Inputs
 action    (1,:)   Action string. These are not case sensitive.
 modifier  ()      Data for the action
 mod2      ()      Second modifier
 mod3      ()      Third modifier
 mod4      ()      Fourth modifier
Outputs
 g         (.)     The CAD data structure
See also
: BuildCADModel>AddSubassembly,
 BuildCADModel>AddSubsystem
References and(), BuildCADModel(), scalar(), set(), and vector().
Referenced by AddRobotArm(), BuildCADModel(), CADNotebook(), CreateBody(), CreateComponent(), DesignUpperStage(), DrawCAD(), ExportVerticesToOBJ(), FindComponents(), LoadCAD(), LoadOBJFile(), MakeSquareSail(), NewtonianAeroTable(), ShowCAD(), and SpacecraftPlugIn().
CADColor()
function CADColor (in action, in g)
This function can be used only to change the colors
of a CAD model. It is usually used to change colors for an imported model.
Form
 g = CADColor( mode, g )
 CADColor( 'initialize', g )
 g = CADColor( 'get model' )
Inputs
 mode        (1,:) See above
 g           (1,1) Input CAD model
Outputs
 g           (1,1) Output CAD model
References close(), CloseFigure(), get(), GetH(), isempty(), and length().
CADNotebook()
function CADNotebook (in g, in varargin)
You can use CADNotebook to associate a Matlab script and reference pdf or html page with each component.
You use this via parameter pairs.
 Action         Data              Description
 'component'    Component name    Designates this component
 'open'        'pdf' or 'html'    Opens a pdf file or web page
 'add xxx'      data              Adds data to field 'xxx'
 'matlab'       ''                Run a Matlab script
 'show'         ''                Opens the model in BuildCADModel
 'report xxx'   type              Prints a 'type' report
 xxx is 'html', 'tex' or 'txt'
An example of adding a component is
 g = CADNotebook(  g,  'component',       'Panels',...
 'add x',            coreX,...
 'add y',            coreY,...
 'add z',            coreZ,...
 'add faceColor',   'gold foil',...
 'add inside',       0,...
 'add rA',           corePosition,...
 'add mass',         massPanel,...
 'add type',        'box');
'add type' should be last to make sure all of these parameters are included.
See CADNotebookCubesat for a example of building a CAD model using CADNotebook.
Type CADNotebook for demo.
Form
 g = CADNotebook;
 g = CADNotebook( g, varargin )
Inputs
 g           (1,1)   Data structure or mat file name
 varargin    {:}     Argument pairs, 'string' parameter
Outputs
 g           (1,1)   Component data structure
References and(), BuildCADModel(), and CADNotebook().
Referenced by CADNotebook().
CameraModel()
function CameraModel (in type, in uBoresight)
Type CameraModel for a demo.
Form
 [v, f, d] = CameraModel( type, uBoresight )
Inputs
 type          (3,:) Type
 uBoresight    (3,1) Unit vector for the boresight
Outputs
 v             (:,3) Vertices
 f             (:,3) Faces
 d              (.)  Data
                     .mass  (1,1) Mass
                     .power (1,1) Power requirements
References and(), Box(), CameraModel(), DispWithTitle(), DrawVertices(), Frustrum(), Inertias(), isempty(), Q2Mat(), U2Q(), Unit(), and vector().
Referenced by CameraModel().
CentroidOBJFile()
function CentroidOBJFile (in file, in path)
If there are no inputs the function will open a file dialog.
Type CentroidOBJFile('Demo') for demo
Form
 c = CentroidOBJFile( file, path )
Inputs
 file              (1,:) Filename
 path              (1,:) Path to the file, optional
Outputs
 c                 (3,1) Centroid
References and(), Centroid(), CentroidOBJFile(), and isempty().
Referenced by CentroidOBJFile().
CircuitBoard()
function CircuitBoard (in board, in component)
l is along x, w along y. The board thickness is along z. Dimensions are mm. It outputs two vertex and face lists. One has components, the other the circuit board.
Type CircuitBoard for a demo.
Since version 10.
Form
 [v, f, c] = CircuitBoard( board, component )
Inputs
 board       (3,1)  [l w t]
 component   (:,8)  [x y l w h]
Outputs
 v           {2}    Vertices, each (n,3)
 f           {2}    Faces, each (n,3)
 c           {2}    Color, each (1,3)
References and(), and CircuitBoard().
Referenced by CircuitBoard().
CombineOBJFiles()
function CombineOBJFiles (in file, in fileNew, in b, in scale, in delta, in flip)
Creates both an obj file and mtl file. Don't enter the suffixes; enter xxx not xxx.obj. The vertices may be rotated and translated. After rotation delta is subtracted from the rotated vertex positions i.e. v = b*v - delta.
If the fileNew does not include a path, it will be saves at the same location as the first file in the list.
Form
 CombineOBJFiles( file, fileNew, b, scale, delta, flip )
Inputs
 file              {n}(1,:) Filenames
 fileNew           (1,:)    New model file
 b                 {:}(3,3) Transformation matrices
 scale             (1,n) Optional scale factor for the model
 delta             (3,n) Offset applied after scaling and rotation
 flip              (1,n) 1 if flip faces
Outputs
 None
References and(), and length().
CompactPCIChassis()
function CompactPCIChassis (in n)
Sizes it based on the number of boards.
Type CompactPCIChassis for a demo.
Form
 [v, f, d] = CompactPCIChassis( n )
Inputs
 n          (1,1) Number of boards
Outputs
 v          (:,3)  Vertices
 f          (:,3)  Faces
 d          (1,3)  Dimensions
References and(), Box(), CompactPCIChassis(), Demo(), DrawVertices(), and Panel().
Referenced by CompactPCIChassis().
ComponentPlugIn()
function ComponentPlugIn (in action, in modifier, in hFig, in position, in callback)
Form
 x = ComponentPlugIn( action, modifier, hFig, position, callback )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifer     (1,:)  Modifier to the action or data structure if intialization
 hFig        (1,1)  Handle to the figure or if 'update' radio button handles
 position    (1,4)  [left bottom width height]
 callback    (1,:)  Callback string when something has changed in this gui
Outputs
 x           (1,1)  The tag if action is 'initialize'
References ComponentPlugIn(), get(), GetNewTag(), Initialize(), isempty(), and set().
Referenced by ComponentPlugIn().
ComponentPopup()
function ComponentPopup (in component)
Form
 ComponentPopup( component )
Inputs
 component         (1,1) Component data structure
Outputs
 none
References get(), GetH(), isempty(), Mag(), PutH(), set(), XLabelS(), YLabelS(), and ZLabelS().
CoordinateTransform()
function CoordinateTransform (in from, in to, in x, in jD)
The frames are:
ECI Earth centered inertial ECR/EF Earth fixed LLR Geodetic latitude, longitude and altitude
Form
 x = CoordinateTransform( from, to, x, jD )
Inputs
 from      (1,:)   From (ECI, EF/ECR, LLR)
 to        (1,:)   To (ECI, EF/ECR, LLR)
 x         (3,:)   Vectors
 jD        (3,1)   Julian date
Outputs
 xT        (3,:)   Vectors transformed
References and().
Referenced by AirshipControlSim(), AirshipInit(), AirshipState(), and TerminatorLine().
CreateBody()
function CreateBody (in action, in varargin)
 param = CreateBody( 'parameters' ) Lists all parameters
 m     = CreateBody( 'make', 'name', 'thename', val1, ..., paramN, valN)
Creates the data structure for the body using the parameter pairs param1,val1 through paramN,valN. m can be input to BuildCADModel.
Note that the parameter 'mass' may be a mass structure. The 'component' and 'path' fields will be added by BuildCADModel.
Form
 m = CreateBody( action, varargin )
Inputs
 action         (1,:)   Action 'parameters', 'make'
 varargin       (:,:)   Parameter pairs
Outputs
 m               (.)    Body data structure
                         .previousBody
                         .rHinge
                         .bHinge
                         .name
                         .mass
                         .components
See also
: BHinge
References and(), BHinge(), BuildCADModel(), CreateBody(), and Parameter().
Referenced by AddRobotArm(), CreateBody(), DesignUpperStage(), ExportVerticesToOBJ(), and MakeSquareSail().
CreateCADReport()
function CreateCADReport (in g, in type, in fileName)
It will create HTML tables or formatted output.
If the fileName is not entered it will print to the command window. This doesn't make much sense with HTML tables. You need to use an HTML enabled package to see the formatted HTML table.
Form
 CreateCADReport( g, type, fileName )
 or
 CreateCADReport( g, type )
Inputs
 g               (1,1)  Component data structure
 type            (1,:)  'html' or 'txt'
 fileName        (1,:)  Filename
Outputs
 None
CreateCADTable()
function CreateCADTable (in g, in fileName)
Lists the following:
subsystem
component
mass
power
heater
manufacturer
model
Form
 CreateCADTable( g, fileName )
Inputs
 g               (.)    Component data structure
 fileName        (1,:)  Filename (if not entered prints to the command window)
Outputs
 None
References CreateCADTable(), and length().
Referenced by CreateCADTable().
CreateComponent()
function CreateComponent (in action, in type, in varargin)
This function has a built-in demo.
Available calls which return help information are:
m = CreateComponent() Returns a demo component types = CreateComponent('type') Lists all available component types param = CreateComponent('parameter', type) Lists all parameters for type param = CreateComponent(type) also lists all parameters
 CreateComponent( 'inputs' ), additional generic inputs
 CreateComponent( 'colors' ), creates a GUI with named colors
The call to create a component is:
m = CreateComponent('make', type, param1, val1, ..., paramN, valN)
This function creates the data structure for the component using the parameter pairs param1,val1 through paramN,valN. m can be input to BuildCADModel. The common parameter structures are:
 'thermal' 'mass' 'power' 'optical' 'infrared' 'aero' 'rf'
 'magnetic' 'propulsion' 'graphics'
Notes:
 primitives, such as sphere and cylinder.
 properties. If this is not the desired behavior specify an RGB triple
 instead.
See also
GenericProperties, DeviceProperties, and OpticalSurfaceProperties.
Form
 m = CreateComponent( action, type, varargin )
Inputs
 action        ':'    Action 'type', 'parameters', 'make'
 type         (1,:)   Type of component
 varargin     (:,:)   Parameter pairs
Outputs
 m             (.)    Component data structure
References and(), BuildCADModel(), CreateComponent(), DeviceProperties(), GenericProperties(), OpticalSurfaceProperties(), and Parameter().
Referenced by AddRobotArm(), CreateComponent(), DeviceProperties(), ExportVerticesToOBJ(), LoadCAD(), and MakeSquareSail().
CreateReport()
function CreateReport (in g, in type, in fileName, in report, in bySubsystem, in noZero, in summary)
It will create HTML tables or formatted output. If the fileName is not entered it will print to the command window. This doesn't make much sense with HTML or latex tables. If you enter any value for bySubsystem it will organize components by subsystem with subtotals. Any component not in a subsystem will be lumped into "Miscellaneous."
The mass and power reports will list all components with a total row. The html, pdf, and matlab reports will list any files that have been associated with each component. Summary only will print just the total row.
See also
: CreateHTMLTable, CreateLatexTable
Form
 CreateReport( g, type, fileName, report, bySubsystem, noZero, summary )
Inputs
 g               (1,1)  Component data structure
 type            (1,:)  'html', 'tex' or 'txt'
 fileName        (1,:)  Filename
 report          (1,:)  'mass', 'power', 'html', 'pdf', 'matlab'
 bySubsystem     (1,1)  Print by subystem
 noZero          (1,1)  1 means omit items with 0 value
 summary         (1,1)  1 means summary report only
Outputs
 None
References and().
CrossSection()
function CrossSection (in g, in bodyAngle, in viewV, in plot)
This routine assumes that the first body is the core and the next n bodies, if any, are rotated by the corresponding body angle.
Type CrossSection for demo.
Form
 area = CrossSection( g, bodyAngle, viewV, plot )
Inputs
 g                 (:)  CAD model struct
 bodyAngle       (n,1)  Body angles, if applicable*
 viewV           (3,1)  Vector viewpoint, nominally [1;0;0] *
 plot              (1)  Plot flag*
                           * Optional
Outputs
 area              (1)  Cross-sectional area of spacecraft
References and(), Cross(), CrossSection(), isempty(), length(), and zeros().
Referenced by CrossSection(), and DisplaySailProperties().
CylindricalTank()
function CylindricalTank (in r, in l, in n)
Uses SurfaceOfRevolution
Type CylindricalTank for a demo.
Form
 [v,f] = CylindricalTank(r,l,n)
Inputs
 r (1,1) Radius
 l (1,1) Length of cylinder
 n (1,1) Number of circumferential divisions
Outputs
 v (:,3) Vertices
 f (:,3) faces
See also
SurfaceOfRevolution.
References CylindricalTank(), Demo(), DrawVertices(), and SurfaceOfRevolution().
Referenced by CylindricalTank().
DeltaWing()
function DeltaWing (in angle1, in angle2, in angleTE, in z1, in z2, in xTE, in n, in lERatio, in taper, in tRatio, in tTE)
y is vertical, x is along the chord and z is along the span. z1 is the spanwise location of the break in z2 is the spanwise location of the wing tip. n is the number of z divisions. The wing is an ellipsoidal front determined by lERatio. For a delta wing make angle1 = angle2 and z1 = z2. Angles are from the span vector. The taper fraction is the ratio of tip chord to root chord. The wing thickness is always 1. The leading edge of the root is at x = 0; the trailing edge is always at negative x.
Type DeltaWing for a demo.
Form
 [v, f] = DeltaWing( angle1, angle2, angleTE, z1, z2, xTE,
 n, lERatio, taper, tRatio, tTE )
Inputs
 angle1     (1,1) Angle of the first section (deg)
 angle2     (1,1) Angle of the second section (deg)
 angleTE    (1,1) Trailing edge angle
 z1         (1,1) Spanwise break of the first section
 z2         (1,1) Wing tip
 xTE        (1,1) X of the trailing edge
 n          (1,1) Number of spanwise sections
 lERatio    (1,1) Leading edge x to y ratio
 taper      (1,1) Ratio of root to tip
 tRatio     (1,1) Ratio of thickness to chord at root
 tTE        (1,1) Trailing edge tickness
Outputs
 v           (:,3)  Vertices
 f           (:,3)  Faces
References abs(), and(), DeltaWing(), Demo(), Extrude(), SinD(), TanD(), vector(), Wing(), and zeros().
Referenced by DeltaWing().
DeviceProperties()
function DeviceProperties (in type, in m, in properties, in values, in computeInertia)
This function can perform the following actions:
return a list of available device types
return a list of parameters used to define any specific device
return component data for the device when passed the needed parameters
The third form should only be used from within CreateComponent.
Form
 types = DeviceProperties
 [p,g] = DeviceProperties( type )
 m = DeviceProperties( type, m, properties, values, computeInertia )
Inputs
 type           (1,:)   Type
 m               (:)    Component struct
 properties      {:}    Property names
 values          {:}    Property values
 mass            (:)    Mass structure
Outputs
 types           {:}   List of all available device types
 p               (.)   Properties data structure
 g               (.)   Geometry fields data structure
 m               (:)   Updated component struct
                         .v   Vertices
                         .f   Faces
References CreateComponent(), and DeviceProperties().
Referenced by CreateComponent(), DeviceProperties(), GetFuelBudgetDataFromCAD(), and HydrazineThruster().
DiffusionExp()
function DiffusionExp (in z, in tX, in t90, in tE)
Form
 x = DiffusionExp( z, tX, t90, tE )
Inputs
 z          (1,1)   Height
 tX         (1,1)   Inflection point temperature (deg-K at altitude = 125 km)
 t90        (1,1)   Assumed temperature at 90km altitude (deg-K)
 tE         (1,1)   Exospheric temperature (deg-K)
Outputs
 x          (1,1)   Diffusion Exponent
References isempty().
Dim()
function Dim (in varargin)
NOTE: Transparency only supported for MATLAB versions after 5.2. If you are using MATLAB v5.2 or prior, components will be simply toggled between being visible and being invisible.
Form
 Dim(       compName1, alpha1, compName2, alpha2, ... )
 -or-
 Dim( figH, compName1, alpha1, compName2, alpha2, ... )
Inputs
 figH       Figure handle(s) (optional)
 compName   Component name (any string within the name)
 alpha      Transparency setting (0-1)
Outputs
 none
References and().
Referenced by PlotEMTraj().
DownrangeAndAltFromTarget()
function DownrangeAndAltFromTarget (in r, in rT)
Given the current spacecraft location, r, and a target point rT on the surface of the planet, computes the altitude and downrange distance (distance along an arc on surface).
Type DownrangeAndAltFromTarget for a demo.
Form
 [d,h] = DownrangeAndAltFromTarget( r, rT )
Inputs
 r     (3,:)   Spacecraft location
 rT    (3,1)   Target point
Outputs
 d     (1,:)   Down range distance
 h     (1,:)   Altitude
References Altitude(), and(), Demo(), DownrangeAndAltFromTarget(), Mag(), Plot2D(), Random(), TargetFromRPVD(), and Unit().
Referenced by DownrangeAndAltFromTarget(), and SecondOrderGuidance3D().
Draw2DViewPlugIn()
function Draw2DViewPlugIn (in action, in modifier, in hFig, in position)
To initialize:
 tag = Draw2DViewPlugIn( 'initialize', g, hFig, position )
g is the spacecraft CAD data structure.
hFig is the handle to the figure window
position is an array [left bottom width height] which gives the position
of the plugin in the window
If hFig is not entered it will create a new window. You need to save tag for subsequent calls. To pass new information to the plugin use:
 Draw2DViewPlugIn( 'update', tag, g )
To erase:
 Draw2DViewPlugIn( 'erase', tag )
To redraw:
 Draw2DViewPlugIn( 'draw', tag )
To close the display type:
 Draw2DViewPlugIn( 'quit', tag )
Type Draw2DViewPlugIn for demo.
Form
 Draw2DViewPlugIn( action, modifier, hFig, position )
Inputs
 action      (1,:)  Action
 modifier    (1,:)  Modifier to the action
 hFig        (1,1)  Handle to the figure or if 'update' is jD
 position    (1,4)  [left bottom width height]
Outputs
 tag         (1,:)  The tag that identifies the display
References and(), close(), CloseFigure(), CreateCallback(), Draw2DViewPlugIn(), DupVect(), get(), GetH(), GetNewTag(), Initialize(), isempty(), length(), PutH(), set(), and zeros().
Referenced by Draw2DViewPlugIn(), and SpacecraftPlugIn().
DrawPatch()
function DrawPatch (in varargin)
Enter as many v,f pairs as desired. Each grouping will be assigned a different color.
Type DrawPatch for demo.
Form
 h = DrawPatch( v, f, v, f, ... )
Inputs
 v           (n,1) Vertices
 f           (m,1) Faces
Outputs
 h           (1,1) Figure handle
References AssignColors(), Box(), Demo(), DrawPatch(), Frustrum(), length(), NewFig(), PlotPlanet(), and series().
Referenced by DrawPatch(), SCMG(), and SHELSInterface().
DrawSCPlanPlugIn()
function DrawSCPlanPlugIn (in action, in modifier, in hFig, in position)
Components will be grouped by subsystem. Sun and Earth vectors may be added. To initialize:
 tag = DrawSCPlanPlugIn( 'initialize', g, hFig, position ), or
 tag = DrawSCPlanPlugIn( g )
g is the spacecraft CAD data structure.
hFig is the handle to the figure window
position is an array [left bottom width height] which gives the position
of the plugin in the window
If hFig is not entered it will create a new window 450 pixels square. You need to save tag for subsequent calls.
To pass new information to the plugin (erase/update/draw) use:
 DrawSCPlanPlugIn( 'update', tag, g )
To display Sun and Earth vectors use the 'vectors' action. The rECI and vECI fields of g must be set. The spacecraft attitude is set by the first body's hinge data. The Earth vector is green, the Sun vector is yellow, and the velocity vector is red.
 DrawSCPlanPlugIn( 'vectors', tag, g, jD ),  -or-
 DrawSCPlanPlugIn( 'vectors', tag, g, uSun )
To erase:
 DrawSCPlanPlugIn( 'erase', tag )
To move components away from the center:
 DrawSCPlanPlugIn( 'scale', tag, scaleFactor )
To redraw:
 DrawSCPlanPlugIn( 'draw', tag )
To close the display, type:
 DrawSCPlanPlugIn( 'quit', tag )
Type DrawSCPlanPlugIn for demo. See SetCADQuaternion for updating the spacecraft's attitude.
Form
 DrawSCPlanPlugIn( action, modifier, hFig, position )
Inputs
 action      (1,:)  Action
 modifier    (1,:)  Modifier to the action
 hFig        (1,1)  Handle to the figure or if 'update' is jD
 position    (1,4)  [left bottom width height]
Outputs
 tag         (1,:)  The tag that identifies the display
See also
DrawSpacecraftPatches, SetCADQuaternion.
References and(), DrawSpacecraftPatches(), isempty(), JD2000(), set(), SetCADQuaternion(), and square().
Referenced by ApplyProfileToModel(), DisplaySailProperties(), DrawSailAttitude(), DrawSailCADModel(), ShowCAD(), and SpacecraftPlugIn().
DrawSpacecraftPatches()
function DrawSpacecraftPatches (in hAxis, in g, in B0, in r0, in ambientStrength, in scale, in explode)
Handles truss or line components. The model can be scaled up or exploded by passing in the appropriate factor.
Type DrawSpacecraftPatches for demo.
Form
 [h, vMinS, vMaxS] = DrawSpacecraftPatches( hAxis, g, B0, r0,
 ambientStrength, scale, explode  )
 DrawSpacecraftPatches( h, g, [], [], ambientStrength, scale, explode  )
Inputs
 hAxis (1,1)  or (:)   Handle to the axes, or to the patches for a redraw
 g                 (.) CAD model
 B0              (3,3) Rotation matrix
 r0              (3,1) Initial position
 ambientStrength (1,1) Ambient light strength
 scale           (1,1) Scale, default 1
 explode         (1,1) Explode factor, default 1
Outputs
 h         (:)      Handles to the patch objects
 vMinS     (3)      Minimum limits on axes
 vMaxS     (3)      Maximum limits on axes
References and(), BHinge(), DrawSpacecraftPatches(), get(), isempty(), length(), NewFig(), set(), and zeros().
Referenced by DrawSCPlanPlugIn(), and DrawSpacecraftPatches().
ECEFToLLA()
function ECEFToLLA (in rECEF, in rP)
Assumes spherical planet.
Form
 lla = ECEFToLLA( rECEF, rP );
Inputs
 rECEF       (3,:)   ECEF position vector [km]
 rP          (1,1)   Radius of planet (for Earth: 6378.14) [km]
Outputs
 lla         (3,:)   Latitude [rad], longitude [rad], altitude [km]
References Mag(), and vector().
Referenced by DrawSpacecraftInOrbit(), and PackageOrbitDataForPlayback().
ECIToEF()
function ECIToEF (in T)
Accounts for Earth rotation, nutation, and precession.
Form
 c = ECIToEF( T )
Inputs
 T      (1,1)       Julian century
Outputs
 c          (3,3)      Matrix from Mean of 2000.0 to planet fixed
References: Seidelmann, The Explanatory Supplement to the Astronomical Almanac, University Science Books, 1992, p. 705. Montenbruck, O., Pfleger, T., "Astronomy on the Personal Computer, Second Edition."
References and(), Date2JD(), ECIToEF(), isempty(), JD2T(), and T2JD().
Referenced by AeroDragForce(), AirshipSim(), AtmNRLMSISE(), AttitudeProfileVis(), BDipole(), BMF(), CubeSatEnvironment(), DataRateOrbit(), DrawSpacecraftInOrbit(), ECIToEF(), EFToLatLonAlt(), FOrbCartH(), GroundStationVisibility(), GuidedLaunch3DRHS(), JacchiaLineberry(), LinkOrbitAnalysis(), MagField(), OrbView(), PackageOrbitDataForPlayback(), QToPFTarget(), RHSGeoJ2(), and RVWithJ2().
EFToLatLonAlt()
function EFToLatLonAlt (in r, in f, in a, in tol)
Altitude is the distance above the subsatellite point. Assumes an ellipsoidal planet.
Form
 x =  EFToLatLonAlt( r, f, a, tol )
Inputs
 r         (3,:)   Vectors
 f         (1,1)   Flattening factor*
 a         (1,1)   Equatorial radius*
 tol       (1,1)   Tolerance*
                      * optional
Outputs
 x         (3,:)   [lat (rad); lon (rad); altitude]
Reference: Vallado, D. A. (1999) Fundamentals of Astrodynamics and Applications. pp. 204-205.
References abs(), Altitude(), and(), Constant(), ECIToEF(), isempty(), JD2T(), Mag(), Unit(), vector(), and zeros().
Referenced by AirshipSim(), AtmJ70(), AtmNRLMSISE(), LocusOfVisibility(), LunarRelativeState(), and StoppingConditions().
ExportCAD()
function ExportCAD (in g, in fileName)
The default extension is .cad.
Form
 ExportCAD( g, fileName )
Inputs
 g           (:,:) CAD Data structure
 fileName    (1,:) Optional file name
Outputs
 None
References isempty(), and length().
ExportDSim()
function ExportDSim (in g, in fileName, in default, in package)
This routine will create three files.
 fileName.obj  - geometry data (Wavefront format)
 fileName.mtl  - material data (Wavefront format)
 fileName.dss  - the DSim setup file
If you enter a fileName the extension will be ignored.
Form
 ExportDSim( g, fileName, default, package )
Inputs
 g            (.)  CAD Data structure
 fileName    (1,:) Optional file name
 default     (1,:) Default object class
 package     (1,:) Package containing classes
Outputs
 None
References isempty(), length(), and TesselatePolygon().
ExportDXF()
function ExportDXF (in g, in fileName)
It only generates 3DFACE entities. BLOCKS are not used.
If you enter a fileName the extension will be ignored. If you do not enter a fileName the name of the CAD model will used.
Form
 ExportDXF( g, fileName )
Inputs
 g           (:,:) CAD Data structure
 fileName    (1,:) Optional file name
Outputs
 None
References isempty(), and length().
ExportOBJ()
function ExportOBJ (in g, in fileName)
This routine will create two or three files.
 fileName.obj  - geometry data
 fileName.mtl  - material data
 fileName.cad  - other than geometry data
If you enter a fileName the extension will be ignored. If you do not enter a fileName the name of the CAD model will used.
Form
 ExportOBJ( g, fileName )
Inputs
 g           (:,:) CAD Data structure
 fileName    (1,:) Optional file name
Outputs
 None
References isempty(), and length().
Referenced by ExportVerticesToOBJ().
ExportVerticesToOBJ()
function ExportVerticesToOBJ (in v, in f, in fileName)
This routine will create an OBJ file.
 fileName.obj  - geometry data
If you enter a fileName the extension will be ignored.
Form
 ExportVerticesToOBJ(v,f,fileName)
Inputs
 v           (:,3) Vertices
 f           (:,3) Faces
 fileName    (1,:) File name
Outputs
 None
See also
: ExportOBJ
References and(), BuildCADModel(), CreateBody(), CreateComponent(), ExportOBJ(), get(), Initialize(), and set().
FindComponents()
function FindComponents (in g, in field, in str, in caseSensitive, in exact)
For example:
 FindComponents(g,'class','generic')
Form
 [k,c] = FindComponents(g,field,str,caseSensitive,exact);
Inputs
 g              CAD Model data structure, returned from BuildCADModel
 field          Field to search in, located at: g.component().FIELD
 str            String to search for
 caseSensitive  Flag. Case sensitive (1) or not (0) [default 0].
 exact          Flag. Search for exact string (1) or not (0) [default 0].
Outputs
 k          Indices of components
 c          Field value (ex. name, class)
References BuildCADModel(), and length().
FLagrange()
function FLagrange (in x, in v, in lPoint)
RHS for the fraction of the distance from the primary to the secondary at which L1, L2 or L3 exist.
Form
 y = FLagrange( x, v, lPoint )
Inputs
 x           (1,1)  Value at which y is zero
 v           (1,1)  Coefficient
 lPoint      (1,1)  Lagrange point, 1, 2 or 3
Outputs
 y           (1,1)  Zero
References RHS().
Referenced by RLagrange().
ForceAndTorqueEnvelope()
function ForceAndTorqueEnvelope (in u, in r, in thrust, in n)
n is the number of samples.
If set to zero it will compute only along the axes. For n > 0 it always computes along the axes and n additional random directions.
Form
 [fE, tE] = ForceAndTorqueEnvelope( u, thrust, n )
Inputs
 u              (3,:)     Unit vectors
 r              (3,:)     Position vectors wrt cm
 thrust         (1,:)     Maximum thrust vector
 n              (1,1)     Number of samples
Outputs
 s              (1,n+6)  Maximum along the corresponding 6 vector
 b              (6,n+6)  6 Vector [u;rXu];
References and(), Cross(), set(), Simplex(), Unit(), vector(), and zeros().
Fuselage()
function Fuselage (in middle, in front, in back, in type, in n)
The fuselage centerline is along x. Fuselages may be ellipsoidal in crossection or be an inverted U. The latter is similar to the Space Shuttle or Hermes.
Type Fuselage or Fuselage('shuttle') for a demo.
Form
 [v, f] = Fuselage( middle, front, back, type, n )
Inputs
 middle      (.)  Data structure
                  .length (1,1) Length of middle
                  .radius (1,1) Radius (type o)
                  .width  (1,1) Width (type u)
                  .height (1,1) Height (type u)
                  .roof   (1,1) Roof height (type u)
 front       (.)  Data structure
                  .a   (1,1) x coefficient
                  .b   (1,1) y coefficient
 back        (.)  Data structure
                  .a   (1,1) x coefficient
                  .b   (1,1) y coefficient
 type       (1,1) 'u' or 'o'
 n          (1,1) Number of z divisions
Outputs
 v          (:,3)  Vertices
 f          (:,3)  Faces
References and(), Demo(), DrawVertices(), Extrude(), Fuselage(), isempty(), length(), and zeros().
Referenced by ACWeightEstimation(), AircraftDesign(), Fuselage(), HSVMassEstimation(), MissileMassEstimation(), and SimpleFuselage().
Gc2GdLat()
function Gc2GdLat (in geoc, in f)
Type Gc2GdLat for a demo.
Form
 geod = Gc2GdLat( geoc, f )
Inputs
 geoc         Geocentric latitude (rad)
 f            Flattening factor
Outputs
 geod         Geodetic latitude (rad)
References: Escobal, P., Methods of Orbit Determination, Krieger, 1975, p. 30.
References Gc2GdLat().
Referenced by Gc2GdLat(), and GroundCoverage().
Gd2GcLat()
function Gd2GcLat (in geod, in f)
Type Gd2GcLat for a demo.
Form
 geoc = Gd2GcLat( geod, f )
Inputs
 geod               Geodetic latitude (rad)
 f                  Flattening factor
Outputs
 geoc               Geocentric latitude (rad)
References: Escobal, P., Methods of Orbit Determination, Krieger, 1975, p. 30.
References Gd2GcLat().
Referenced by Gd2GcLat().
GenericProperties()
function GenericProperties (in type, in varargin)
The types are:
 'thermal'
 'absorptivity','emissivity','heatGeneratedOn','heatGeneratedStandby',
 'temperature','surfaceArea','uNormal','thermalMass'
 'power'
 'powerStandby', 'powerOn','electricalConversionEfficiency',
 'powerHeater','powerIsOn'
 'optical'
 'sigmaT', 'sigmaA', 'sigmaD', 'sigmaS'
 'infrared'
 'sigmaRT', 'sigmaRA', 'sigmaRD', 'sigmaRS'
 'mass'
 'mass', 'cM', 'inertia'
 'aero'
 'cD'
 'rF'
 'flux', 'u', 'r'
 'magnetic'
 'dipole'
 'propulsion'
 'thrust' 'iSP' 'feedPressure' 'efficiency'
 'graphics'
 'faceColor' 'edgeColor' 'specularStrength' 'diffuseStrength'
 'ambientStrength'
 'specularColorReflectance' 'specularExponent'
You can customize properties by adding property/value pairs. Type GenericProperties to have a list describing the properties printed to the command window.
Form
 p = GenericProperties( type, varargin )
Inputs
 type           (1,:)   Type
Outputs
 p              (1,1)  Properties data structure
 desc            {:}   Descriptions of the properties
References GenericProperties().
Referenced by CreateComponent(), GenericProperties(), NuclearReactorModel(), and REAModel().
GetCADVF()
function GetCADVF (in g, in notInside)
No body rotations are applied. Type GetCADVF for a demo.
The default is to include all components in the output. To exclude those which are marked as 'inside' the vehicle, pass true for notInside.
Form
 [v,f] = GetCADVF( g, notInside );
Inputs
 g           (.)  CAD model data structure with "component" field
 notInside   (1)  Boolean to include only components that are not
                     'inside', default is false (return all components)
Outputs
 v         (:,3)  Vertices for all components
 f         (:,3)  Faces for all components
References and(), Demo(), GetCADVF(), length(), NewFig(), set(), and SliderBar().
Referenced by AttitudeProfileVis(), and GetCADVF().
GetSubsystemMass()
function GetSubsystemMass (in g, in subsystem)
Type GetSubsystemMass for a demo using CubeSat3U.
Form
 mass = GetSubsystemMass( g, subsystem )
Inputs
 g           (.)      CAD model structure
 subsystem   ''       Subsystem name (string)
Outputs
 mass        (1,1)    Mass (kg)
References Demo(), DispWithTitle(), and GetSubsystemMass().
Referenced by GetSubsystemMass().
HallThrusterModel()
function HallThrusterModel (in s)
Type HallThrusterModel for a demo.
Form
 [v, f] = HallThrusterModel( s )
Inputs
 s           (1,2)  Scale [Diameter, length]
Outputs
 v           (:,3)   Vertices
 f           (:,3)   Faces
References and(), Demo(), DrawVertices(), Frustrum(), HallThrusterModel(), and length().
Referenced by HallThrusterModel().
HorizonAngle()
function HorizonAngle (in rG, in rS)
Angles below the horizon are zero. Assumes the planet is a sphere.
Type HorizonAngle for a demo.
Form
 angle = HorizonAngle( rG, rS )
Inputs
 rG             (3,1)  Position vector on ground
 rS             (3,:)  Position vector in space
Outputs
 angle          (1,:)  Horizon angle (rad)
References and(), Demo(), DupVect(), HorizonAngle(), length(), Plot2D(), Unit(), vector(), and zeros().
Referenced by HorizonAngle(), LinkAnalysisTool(), LinkBudget(), LinkOrbitAnalysis(), and LossPrecipitation().
HSRCAD()
function HSRCAD (in v, in f, in z, in n, in showScans)
Computes surface shadowing ("hidden surface removal") using backface culling. Uses the infinite line method for determining whether a point is within a polygon. The ordering of vertices is consistent with Polygon.m.
Includes a built-in demo.
Form
 [aV, cV, area] = HSRCAD( v, f, z, n, showScans )
Inputs
 v           (:,3) Vertex list
 f           (:,3) Face list
 z           (3,1) Unit vector to the source
 n           (1,1) Number of scan lines (default 20)
 showScans   (1,1) Any argument will cause a plot to be drawn
Outputs
 aV          (1,:) Visible area per face
 cV          (3,:) Centroid for each face
 area        (n,n) Matrix showing the ID of the visible surface
                   0 means no surface is visible
Reference: Hill, F.S. Jr., Computer Graphics, p. 243.
References abs(), and(), Centroid(), Coordinates(), Cross(), Dot(), get(), HSRCAD(), isempty(), length(), Polygon(), set(), Unit(), vector(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by BallisticCoefficient(), Disturbances(), HSRCAD(), and SpacecraftThermal().
ICONS()
function ICONS (in demo)
Type ICONS for a demo.
This is an example of how to build up models of devices and compute their inertias. The sensor consists of two cameras and gimbals.
Form
 [v, f, inr] = ICONS( demo )
Inputs
 demo        (1,1) Anything draws icons
Outputs
 v           (:,3) Vertices
 f           (:,3) Faces
 inr         (1,1) Inertia data structure
References and(), Demo(), ICONS(), Inertias(), and USR30Motor().
Referenced by ICONS().
IntersectPlanet()
function IntersectPlanet (in r1, in r2, in a)
Type IntersectPlanet for a demo.
Form
 h = IntersectPlanet( r1, r2, a )
Inputs
 r1             (3,n)  Position vector 1
 r2             (3,m)  Position vector 2
 a              (1,1)  Radius of the planet
Outputs
 h              (n,m)  Minimum altitude of vector
References Altitude(), Demo(), IntersectPlanet(), NewFig(), vector(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by IntersectPlanet(), and MeasGPS().
JacchiaLineberry()
function JacchiaLineberry (in d, in use70)
Uses interpolating functions to replace the integrals in the full Jacchia model. See also AtmJ70. Since Version 11.
Form
 [rho,T] = JacchiaLineberry( d, use70 )
Inputs
 d       (.)       Data structure
  .Kp
  .jD
  .rECI
  .f
  .fHat
 use70  (1,1)      Flag to use 1970 coefficients, if 0 then 1971
 coefficients will be used. Defaults to 1.
Outputs
 rho    (1,1)      Density, g/cm^3
 T      (1,1)      Exospheric temperature
Reference: Jacchia-Linberry Upper Atmosphere Density Model, NASA Mission Planning and Analysis Division, October 1982 NASA-CR-167824
References abs(), ACosD(), Altitude(), and(), AtmJ70(), CosD(), Date2JD(), ECIToEF(), JacchiaLineberry(), JD2MJD(), JD2T(), LatLonAltToEF(), length(), Mag(), SinD(), and SunV1().
Referenced by JacchiaLineberry().
LAETR308CAD()
function LAETR308CAD ()
This is a liquid apogee engine. Type LAETR308CAD for a demo. This does not have any data for the engine, it just creates vertices and faces.
Form
 [v, f] = LAETR308CAD
Inputs
 None
Outputs
 v  (:,3)   Vertices
 f  (:,3)   Faces
References and(), DrawVertices(), LAETR308CAD(), and SurfaceOfRevolution().
Referenced by LAETR308CAD().
LatLonAltToEF()
function LatLonAltToEF (in x, in f, in a)
Altitude is the distance above the subsatellite point. Assumes an ellipsoidal planet.
Type LatLonAltToEF for a demo.
Form
 r = LatLonAltToEF( x, f, a )
Inputs
 x         (3,:)   [lat (rad); lon (rad); altitude (km)]
 f         (1,1)   Flattening factor
 a         (1,1)   Equatorial radius
 tol       (1,1)   Tolerance
Outputs
 r         (3,:)   Vectors
Reference: Escobal, P. Methods of Orbit Determination.
References Altitude(), Constant(), isempty(), LatLonAltToEF(), and vector().
Referenced by GravityMap(), GroundStationVisibility(), JacchiaLineberry(), LatLonAltToEF(), LinkAnalysisTool(), LinkBudget(), LinkOrbitAnalysis(), LossPrecipitation(), LunarLandingTargetState(), and OverArea().
LatLonToR()
function LatLonToR (in lat, in lon, in f, in a, in type)
The default for f is the flattening factor for the earth. The default for type is geodetic.
Type LatLonToR for a demo.
Form
 r = LatLonToR( lat, lon, f, a, type )
Inputs
 lat                   (:)    Geodetic latitude (rad)
 lon                   (:)    Longitude (rad)
 f                     (1,1)  Flattening factor
 a                     (1,1)  Equatorial radius
 type                  (1,:)  'geodetic' or 'geocentric'
Outputs
 r                     (3,:)  Position vectors
Reference: Escobal, P. R., "Methods of Orbit Determination," Kreiger, 1965, pp. 24-28.
References and(), Axis3D(), Constant(), Equal(), isempty(), LatLonToR(), length(), NewFig(), Plot2D(), square(), XLabelS(), YLabelS(), zeros(), and ZLabelS().
Referenced by AttitudeTarget(), DataRateOrbit(), DFFAttitudeTarget(), EarthMoonRotFrame(), LatLonToR(), LunarVisibility(), QLatLon(), and QToPFTarget().
LLAToECEF()
function LLAToECEF (in lla, in rP)
Assumes spherical planet.
Form
 rECEF = LLAToECEF( lla, rP )
Inputs
 lla         (3,:)   Latitude [rad], longitude [rad], altitude [km]
 rP          (1,1)   Radius of planet (for Earth: 6378.14) [km]
Outputs
 rECEF       (3,1)   ECEF position vector [km]
References vector().
Referenced by AttitudeProfileVis(), DrawSpacecraftInOrbit(), DrawSphere(), LaunchTime(), and RHAzToECEF().
LoadCAD()
function LoadCAD (in file, in path, in format, in kScale)
Handles .dxf, .obj and .3DMF files.
If format is entered and file does not have a suffix (.dxf, .obj or .3DMF) it will be appended. For example, if you enter
 LoadCAD( 'myFile.dxf' )        or
 LoadCAD( 'myFile','','dxf' )
LoadCAD will open myFile.dxf. If you want to scale the units of the model, for example from vertex units to inches, you can define the factor using kScale.
If you call the function with no outputs it will draw the model. If you call the function with an empty filename you can select a file using the dialog box. For a demo of an OBJ file, type LoadCAD.
If you want to use the model data in BuildCADModel, pass the component vertex (v) and face (f) fields to a generic component.
 m = CreateComponent( 'make', 'generic', 'vertex', v, 'face', f ... )
Form
 g = LoadCAD( file, path, format, kScale )
 LoadCAD        % Demo
 LoadCAD( [] )  % Dialog box
Inputs
 file        (1,:) Filename
 path        (1,:) Path to the file
 format      (1,:) Format 'dxf', 'obj', '3DMF'
 kScale      (1,1) Optional scale factor of the model
Outputs
 g           (1,1) Data structure
                   .name       (1,:)  Model name
                   .component   (:)   Component structure
                   .radius     (1,1)  Maximum radius of the object
References and(), BuildCADModel(), CreateComponent(), Demo(), GetFileSuffix(), isempty(), length(), LoadCAD(), and Mag().
Referenced by ActiveAeroSurfacesDisplay(), CreateAircraftModel(), DrawAircraft(), DrawCAD(), InertiaFromOBJFile(), LoadCAD(), MassPropertiesSolidObjFile(), NewtonianAerodynamicsFromCAD(), NewtonianAeroPropertiesFromOBJFile(), NewtonianAlphaFromCAD(), NewtonianCPFromCAD(), NewtonianForceFromCAD(), RotateOBJFile(), and ThrusterLayout().
LoadOBJFile()
function LoadOBJFile (in file, in kScale)
Handles .obj
LoadOBJFile will open myFile.obj. If you want to scale the units of the model, for example from vertex units to inches, you can define the factor using kScale.
If you call the function with no outputs it will draw the model. If you call the function with an empty filename you can select a file using the dialog box.
If you want to use the model data in BuildCADModel, pass the component vertex (v) and face (f) fields to a generic component.
 m = CreateComponent( 'make', 'generic', 'vertex', v, 'face', f ... )
Form
 g = LoadOBJFile( file, path, format, kScale )
 LoadOBJFile        % Demo
 LoadOBJFile( [] )  % Dialog box
Inputs
 file        (1,:) Filename
 kScale      (1,1) Optional scale factor of the model
Outputs
 g           (.)   Data structure
                   .name       (1,:)  Model name
                   .component   (:)   Component structure
                   .radius     (1,1)  Maximum radius of the object
References and(), BuildCADModel(), Demo(), Initialize(), isempty(), length(), LoadOBJFile(), Mag(), NewFig(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by LoadOBJFile().
LunarModuleFirstStage()
function LunarModuleFirstStage ()
Type LunarModuleFirstStage for a demo.
Form
 component = LunarModuleFirstStage
Inputs
 None
Outputs
 component (:)     Data structure
                    .v
                    .f
                    .color
                    .name
References and(), Extrude(), ExtrudeFromProfile(), length(), LunarModuleFirstStage(), NewFig(), Strut(), TanD(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by LunarModuleFirstStage().
LunarModuleSecondStage()
function LunarModuleSecondStage ()
Type LunarModuleSecondStage for a demo.
Form
 component = LunarModuleSecondStage
Inputs
 None
Outputs
 component (:)     Data structure
                    .v
                    .f
                    .color
                    .name
References Box(), Extrude(), length(), LunarModuleSecondStage(), NewFig(), Panel(), Triangle(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by LunarModuleSecondStage().
MassBudget()
function MassBudget (in c, in type, in fileName, in nIts)
The function uses the mass data structure which is
 structure('mass',mass,'cM',centerOfMass,'inertia',inertiaMatrix)
The type is the type of vehicle for computations.
If type is entered for a component it will look for a model. If there are any models that depend on the total vehicle mass (such as landing gear) the mass properties will be computed recursively
Available types:
'military aircraft'
'commercial aircraft'
'satellite'
If fileName is entered it generates a file 'fileName.tex' with the contents of a latex formatted table. You can add this directly to your latex file.
If you type in MassBudget you will get results for a satellite and/or aircraft example depending on whether you have the Spacecraft or Aircraft Control Toolbox.
Form
 m = MassBudget( c, type, fileName, nIts )
Inputs
 c        (:)   Data structure array
                .name      (1,:) Name of component
                .type      (1,:) Type of component
                .mass      (1,1) Mass of component
                .inertia   (3,3) Inertia of component
                .pos       (3,1) Position
                .param     (1,:) Parameters (varies with type)
                .subsystem (1,:) Subsystem name
                .compute   (1,1) If 1 compute from a model
 type     (1,:) Type of vehicle for computed properties
                 'spacecraft'  or 'aircraft'
 fileName (1,:) File name for latex file
 nIts     (1,1) Number of iterations
Outputs
 m        (.)  Mass data structure with total mass
See also
: MassBudgetInput, SatelliteSubsystemMass, AircraftGroupMass
exclude SatelliteSubsystemMass AircraftGroupMass
References AircraftGroupMass(), and(), Demo(), get(), MassBudget(), MassBudgetInput(), and SatelliteSubsystemMass().
Referenced by AircraftGroupDataStructure(), MassBudget(), and MassBudgetInput().
MassBudgetInput()
function MassBudgetInput (in varargin)
Enter parameter pairs.
Type MassBudgetInput to see the data structure. This function will fill in any fields that are not entered. The param field is a data structure. It depends on type.
Form
 MassBudgetInput;  % demo
 c = MassBudgetInput( varargin )
Inputs
 varargin    (:)     Parameter pairs
Outputs
 c           (1,1)   MassBudget data structure
See also
: MassBudget
References Demo(), length(), MassBudget(), MassBudgetInput(), and Parameter().
Referenced by MassBudget(), and MassBudgetInput().
MatlabColorToObj()
function MatlabColorToObj (in faceColor, in specularStrength, in specularExponent, in diffuseStrength, in specularColorReflectance)
Type MatlabColorToObj for a demo.
Form
 [Ns, d, illum, Kd, Ks, Ka] = MatlabColorToObj( faceColor, specularStrength,
 specularExponent, diffuseStrength, specularColorReflectance )
Inputs
 faceColor                (1,3) Face color
 specularStrength         (1,1) Specular strength
 specularExponent         (1,1) Specular exponent
 diffuseStrength          (1,1) Diffuse exponent
 specularColorReflectance (1,1) Specular color reflectance
Outputs
 Ns                       (1,1) Shininess 10 = 91% shininess
 d                        (1,1) Flag indicating transparency (0 to 1)
 illum                    (1,1) 1 = flat shading, 2 = specular
 Kd                       (1,3) Diffuse color
 Ks                       (1,3) Specular color
 Ka                       (1,3) Ambient color
References Demo(), and MatlabColorToObj().
Referenced by MatlabColorToObj().
NoseCone()
function NoseCone (in r, in l, in n, in h)
Type NoseCone for a demo.
Form
 [v, f] = NoseCone( r, l, n, h )
Inputs
 r            (1,:) R as a function of z
 l            (1,1) Length
 n            (1,1) Number of divisions
 h            (1,1) 1 if half cone
Outputs
 v            (:,3) Vertices
 f            (:,3) Faces
References and(), Cone(), Demo(), DrawVertices(), isempty(), length(), and NoseCone().
Referenced by NoseCone().
NuclearReactorModel()
function NuclearReactorModel (in powerThermal, in conversionEfficiency, in unitVector)
This model assumes:
1600 kWThermal reactor
33% efficient Stirling engine conversion
591 deg-K radiator temperature
Type NuclearReactorModel for a demo.
Form
 [v, f, d] = NuclearReactorModel( powerThermal, powerElectric, unitVector )
Inputs
 powerThermal         (1,1)    Output power
 conversionEfficiency (1,1)    Electrical power
 unitVector           (3,1)    Unit vector
Outputs
 v                    (:,3)    Vertices
 f                    (:,3)    Faces
 d                    (1,1)    Data
                               .mass
                               .power
References and(), Demo(), GenericProperties(), NuclearReactorModel(), Unit(), and vector().
Referenced by NuclearReactorModel().
OmegaFromU()
function OmegaFromU (in u, in omega)
Form
 omegaTotal = OmegaFromU(u,omega)
Inputs
 u     (3,:) Unit vectors
 omega (1,:) Corresponding angular rate
Outputs
 omegaTotal (3,1) Total angular rate vector
References Demo(), OmegaFromU(), set(), Unit(), and vector().
Referenced by OmegaFromU().
OmegaLVLH()
function OmegaLVLH (in r, in v)
Type OmegaLVLH for a demo.
Form
 omega = OmegaLVLH( r, v )
Inputs
 r          (3,n) Position vectors
 v          (3,n) Velocity vectors
Outputs
 omega      (3,n) Rate vectors
References Cross(), Demo(), Mag(), OmegaLVLH(), Unit(), vector(), and zeros().
Referenced by GravityGradientEigenvalues(), and OmegaLVLH().
Panel()
function Panel (in r, in n)
To see a demo type Panel. This has seven divisions.
Form
 Panel;
 [v, f] = Panel( r, n )
Inputs
 r          (1,1) Outer radius
 n          (1,1) Number of outer circumferential divisions
Outputs
 v          (:,3) Vertices
 f          (:,3) Faces
 area       (1,1) Area of panel
 side       (1,1) Dimension of side
References and(), Demo(), DrawVertices(), and Panel().
Referenced by CompactPCIChassis(), CubeSatModel(), LunarModuleSecondStage(), NRLArray(), OpenFrame(), Panel(), PanelFrame(), PanelThermalModel(), PanelWithCenterHole(), PanelWithCutout(), and SolarWingSupport().
PanelBoxCAD()
function PanelBoxCAD (in xBox, in yBox, in zBox, in panelThickness, in rho, in materialPanel, in materialFrame, in r, in mass, in bodyID)
Adds components to the CAD model. The last parameter is for the total mass of internal components called 'electronics'. The demo creates a new CAD model and adds the box.
Form
 PanelBoxCAD;    % demo
 PanelBoxCAD( xBox, yBox, zBox, panelThickness, rho, materialPanel,
 materialFrame, r, mass, bodyID )
Inputs
 xBox            (1,1) x dimension of box
 yBox            (1,1) y dimension of box
 zBox            (1,1) z dimension of box
 panelThickness  (1,1) Thickness of panels
 rho             (1,1) Density of material
 materialPanel   (1,1) Material color [r,g,b] or name
 materialFrame   (1,1) Material color [r,g,b] or name
 r               (3,1) Position
 mass            (1,1) Optional mass inside (kg)
 bodyID          (1,1) Body id
Outputs
 None
References and(), Demo(), PanelBoxCAD(), and Panels().
Referenced by PanelBoxCAD().
PanelFrame()
function PanelFrame (in x, in y, in h, in t)
The panel fits into the frame and the frame is fastened to struts to form a satellite frame. The following runs around the periphery.
 t
| | h -> this corner is h x h | -— | | h
With no outputs this generates a picture.
Type PanelFrame for a demo.
Form
 [v, f, vol] = PanelFrame( x, y, h, t )
Inputs
 x          (1,1) Width of the panel  (x)
 y          (1,1) Length of the panel (y)
 h          (1,1) Panel thickness
 t          (1,1) Frame thickness
Outputs
 v          (:,3)  Vertices
 f          (:,3)  Faces
 vol        (1,1)  Volume of material
References and(), Demo(), DrawVertices(), Panel(), and PanelFrame().
Referenced by PanelFrame().
Panels()
function Panels (in x, in y, in z, in face)
These have no thickness. If there are no outputs, draws the panel in a figure with surface normal vectors.
Type Panels for a demo of 6 panels forming a box.
Form
 [v, f] = Panels( x, y, z, face )
Inputs
 x    x length
 y    y length
 z    z length
 face Which face is drawn, in {'+x' '-x' '+y' '-y' '+z' '-z'}
Outputs
 v    Vertices
 f    Faces
References length(), and Panels().
Referenced by ComputeCoeffFromShape(), PanelBoxCAD(), and Panels().
PanelWithCenterHole()
function PanelWithCenterHole (in rO, in rI, in nO, in nI)
To see a demo type PanelWithCenterHole.
Form
 [v, f] = PanelWithCenterHole( rO, rI, nO, nI )
Inputs
 rO         (1,1) Outer radius
 rI         (1,1) Inner radius
 nO         (1,1) Number of outer circumferential divisions
 nI         (1,1) Number of inner circumferential divisions
Outputs
 v          (:,3) Vertices
 f          (:,3) Faces
References abs(), and(), Demo(), DrawVertices(), isempty(), length(), Panel(), PanelWithCenterHole(), and zeros().
Referenced by PanelWithCenterHole().
PanelWithCutout()
function PanelWithCutout (in xW, in yW, in t, in c)
Type PanelWithCutout to see a demo that creates a rectangular plate with a hexagonal cutout.
Form
 [v, f, vol] = PanelWithCutout( xW, yW, t, c )
Inputs
 xW         (1,1) x width of the panel  (x)
 yW         (1,1) y width
 t          (1,1) Thickness (Can be zero)
 c          (1,1)
                  .x (1,1) x location
                  .y (1,1) y location
                  .r (1,1) z location
                  .n (1,1) Number of points in cutout
Outputs
 v          (:,3)  Vertices
 f          (:,3)  Faces
 vol        (1,1)  Volume of panel (area if flat)
References abs(), and(), AreaTriMesh(), Demo(), DrawVertices(), Panel(), and PanelWithCutout().
Referenced by PanelWithCutout().
Q2RADec()
function Q2RADec (in u, in q)
Given Q which transforms from the inertial frame to the body frame and u in the body frame, finds the right ascension and declination of u in the inertial frame.
Form
 [rA, dec] = Q2RADec( u, q )
Inputs
 u                   (3,1)    Vector
 q                   (4,1)    Quaternion
Outputs
 rA                  (1,1)    Right ascension (rad)
 dec                 (1,1)    Declination (rad)
References and(), QTForm(), quaternion(), U2RADec(), and vector().
QAcq()
function QAcq (in uTrue, in uMeas)
Since version 1.
Form
 q = QAcq( uTrue, uMeas )
Inputs
 uTrue        (3,3)     True unit vectors
 uMeas        (3,3)     Measured unit vectors
Outputs
 q            (4,1)     New quaternion
References Mat2Q(), and quaternion().
QAlign()
function QAlign (in q0, in uBAxis, in uBVec, in uITarget)
Begin with an initial quaternion
Rotate about a body-frame axis to align a body-frame vector with an
inertial target vector
Return the new quaternion
Will generate a plot if no outputs are requested.
Form
 [q,rotAngle,sepAngle] = QAlign( q0, uBAxis, uBVec, uITarget );
Inputs
 q0          (4,:) Beginning inertial to body quaternion
 uBAxis      (3,1) Body-frame axis to rotate about
 uBVec       (3,1) Body-frame vector to align
 uITarget    (3,:) Inertial-frame vector to point at
Outputs
 q           (4,:) Resulting Inertial-to-Body quaternion after rotation
 rotAngle    (1,:) Angle of rotation [rad]
 sepAngle    (1,:) Separation angle between body vector and target [rad]
References and(), NewFig(), QAlign(), QForm(), QMult(), QPose(), QRotateToAlign(), QTForm(), quaternion(), vector(), and zeros().
Referenced by AutoPoint(), QAlign(), and QFrom2U().
QFrom2U()
function QFrom2U (in u1ECI, in u2ECI, in u1, in u2)
This is useful for when you need to point a thruster along an acceleration vector and a sensor near nadir.
Type QFrom2U for a demo. It takes two vectors, [0;1;0] and [0;0;1] and aligns them with ECI [1;0;0] and [0;1;0]. This is a case when it will be exact.
Form
q = QFrom2U(u1ECI, u2ECO, u1, u2)
Inputs
 u1ECI       (3,1) Vector that u1S must be aligned with
 u2ECI       (3,1) Vector that should be close to u2
 u1          (3,1) Vector in the body frame
 u2          (3,1) Second vector in the body frame
Outputs
 qECIToBody  (4,1) Quaternion
References and(), close(), Demo(), QAlign(), QForm(), QFrom2U(), quaternion(), U2Q(), and vector().
Referenced by QFrom2U().
QHills()
function QHills (in rE, in vE)
 The coordinates of the Hills frame are defined as:
 x: Radial
 z: Orbit-normal, or cross-track
 y: Completes RHS (Along-track for circular orbits)
 The relative position vector in the Frenet frame can be computed as:
 rF = QForm( qEF, drE );
 where dr is the relative position vector in the ECI frame. Or you may obtain
 the transformation matrix, mEF, as the second output. In this case, use:
 rF = mEF*drE;
 Usages:
 qEH       = QHills( rE, vE );
 [qEH,mEH] = QHills( rE, vE );
Inputs
 rE          (3,n) Position vectors
 vE          (3,n) Velocity vectors
Outputs
 qEH        (4,n) Quaternions
 qEH        (4,n) Quaternions
References quaternion(), and vector().
Referenced by AlignThruster(), InitialOrientation(), QHillsToBody(), QNadirPoint(), and ThrusterAlignment().
QIToBDot()
function QIToBDot (in q, in w, in dT)
The quaternion transforms from the inertial frame to the body frame. Requires the angular velocity measured in the body frame.
Form
 qD                 = QIToBDot( q, w )
 [a, b, c, d, dqdt] = QIToBDot( q, w )
 [a, b, c, d, dqdt] = QIToBDot( q, w, dT )
Inputs
 q              (4,1)  Quaternion from a to b
 w              (3,1)  Rate of b with respect to a measured in b
 dT             (1,1)  Time step
Outputs
 qD             (4,1)  Derivative of Q
 or
 a              (4,4)  Plant matrix
 b              (4,3)  Input matrix
 c              (4,4)  Measurement matrix
 d              (4,3)  Feedthrough matrix
 dqdt           (4,1)  Constant quaternion derivative
References C2DZOH(), Constant(), quaternion(), SkewSymm(), and zeros().
Referenced by AC(), ASim(), DFFRHS(), FAKM(), FCoreAndMoving(), FGs(), FMagSim(), FMovingBody(), FPivot(), FRB(), FRBWithMag(), FRBwRIG(), FS4Deployment(), FTB(), FTBRef(), FTimeVaryingI(), KConstQ(), PermanentMagnetRHS(), RHSCubeSat(), RHSGGRotational(), RHSGyroWithOrbit(), RHSLunarLander(), RHSLunarMission(), RHSQ(), RHSReactionWheel(), RHSRigidBody(), RHSRigidBody6DOF(), RHSRigidBodyLinear(), RHSRigidBodyMass(), RHSRigidBodyOffsetCM(), RHSRigidBodyWithDamping(), RHSRigidBodyWithTarget(), RHSRWA(), RHSRWAIDotSC(), RHSRWASC(), RHSSpacecraftWithIMU(), RHSSpacecraftWithRWA(), RHSThreeBody(), SCWithRollPivot(), Tree(), WireC(), and WireFRB().
QLatLon()
function QLatLon (in lat, in lon, in r, in v, in q, in f, in a)
defined by z is in the direction pointing to [latitude, longitude] y is in the - rxv direction x completes the set
Form
 q = QLatLon( lat, lon, r, v, q, f, a )
Inputs
 lat        (1,n) Latitude
 lon        (1,n) Longitude
 r          (3,n) Position vectors
 v          (3,n) Velocity vectors
 q          (4,n) Quaternion from ECI to EF
 f          (1,1) Flattening factor
 a          (1,1) Equatorial radius
Outputs
 q          (4,n) Quaternions
References Constant(), Cross(), LatLonToR(), Mat2Q(), Plot2D(), QTForm(), set(), Unit(), and zeros().
QLVLH()
function QLVLH (in r, in v)
For LVLH coordinates; z is in the -r direction y is in the - rxv direction x completes the set; along v in a circular orbit
Form
 q = QLVLH( r, v )
Inputs
 r          (3,n) Position vectors
 v          (3,n) Velocity vectors
Outputs
 q          (4,n) Quaternions
References set().
Referenced by AlphaBetaToU(), AngleDetermination(), AttitudeFrames(), AttitudeProfileToTorque(), AttitudeTarget(), AutoPoint(), CubeSatDisturbanceAnalysis(), CubeSatPowerAnalysis(), DFFAttitudeTarget(), EarthGuidance(), GenerateSwath(), GravityGradientEigenvalues(), GroundCoverage(), HorizonUnitVectors(), ISSCoord(), LVLH2ECI(), MagControlTwoAxis(), PowerDesign(), QHillsToBody(), QSunNadir(), RollPitchToQECI(), SetCADState(), ThrustControlConstantAngle(), and TwoUToQ().
QNadirPoint()
function QNadirPoint (in r, in v, in uB)
The input is the orbit vectors (r,v).
Form
 qIB = QNadirPoint( r, v, uB )
Inputs
 r           (3,n) Position vectors of an orbit
 v           (3,n) Velocity vectors of an orbit
 uB          (3,1) Body unit vector
Outputs
 qIB         (4,n) Inertial-to-Body quaternions that point uB to nadir
See also
: QHills
References QHills(), QMult(), quaternion(), U2Q(), and vector().
QRotateToAlign()
function QRotateToAlign (in axis, in ua, in ut)
Form
 QRotateToAlign; % demo with random axis
 [qRot,ub,rotAngle,sepAngle] = QRotateToAlign( axis, ua, uat);
Inputs
 axis       (3,1)  Axis of rotation
 ua         (3,1)  Vector to align
 ut         (3,:)  Target vector to be aligned with
Outputs
 qRot       (4,1)  Quaternion that rotates ua to ub about axis
 ub         (3,1)  Vector achieved after rotation
 rotAngle   (4,1)  Angular rotation about the axis
 sepAngle   (4,1)  Separation angle between ub and ut
References abs(), and(), close(), Coordinates(), Cross(), Plot2D(), QForm(), QRotateToAlign(), Sep(), Unit(), and vector().
Referenced by QAlign(), and QRotateToAlign().
QSLERP()
function QSLERP (in qFrom, in qTo, in t)
Interpolates between qFrom and qTo using the scaled time t
Form
 q = QSLERP( qFrom, qTo, t )
Inputs
 qFrom (4,1) Starting quaterion
 qTo   (4,1) Final quaternion
 t     (1,1) 0 to 1
Outputs
 q     (4,1) Quaternion
References and(), and quaternion().
QToPFTarget()
function QToPFTarget (in x, in lat, in lon, in rECI, in jD, in planet, in type)
Computes an array of quaternions that align a vector x in the body fixed frame with a target specified by lat and lon.
Type QToPFTarget for a demo.
Form
 [qECIToBody, err] = QToPFTarget( x, lat, lon, rECI, jD, planet, type )
Inputs
 x         (3,1)        Vector in the body frame
 lat        (:) or (1,1) Latitude (rad)
 lon        (:) or (1,1) Longitude (rad)
 rECI       (3,:)        Spacecraft Position
 jD         (:)          Julian dates
 planet     (1,:)        Planet name
 type       (1,:)        'geocentric' or 'geodetic' latitude
Outputs
 qECIToBody (4,:)       Array of quaternions that rotate from the ECI
                        frame
 err        (1,1)       Norm of the errors (rad)
References abs(), and(), Constant(), DupVect(), ECIToEF(), isempty(), JD2000(), JD2T(), LatLonToR(), length(), Plot2D(), QTForm(), QToPFTarget(), quaternion(), TruEarth(), U2Q(), Unit(), and vector().
Referenced by QToPFTarget().
R2LatLon()
function R2LatLon (in x, in y, in z)
Form
 [lat, lon] = R2LatLon( x, y, z )
 [lat, lon] = R2LatLon( r )
Inputs
 x            (1,:)     X or [x;y;z]
 y            (1,:)     Y
 z            (1,:)     Z
Outputs
 lat          (1,:)     Latitude (rad)
 lon          (1,:)     East longitude (0 in xz-plane, +right hand rule
                        about +z)  (rad)
References and(), Plot2D(), and Unit().
Referenced by GenerateSwath(), GroundCoverage(), GroundTrack(), OrbTrack(), OrbView(), and StoppingConditions().
RaDec2Q()
function RaDec2Q (in u, in rA, in dec)
If right ascension and declination are defined in frame a, and u is fixed in frame b, q transforms from frame a to b such that u lies along the vector determined by (rA,dec) in frame a.
Since version 1.
Form
 q = RaDec2Q( u, rA, dec )
Inputs
 u                   (3,1)    Vector in question
 rA                  (1,1)    Right ascension (radians)
 dec                 (1,1)    Declination  (radians)
Outputs
 q                   (4,1)    Equivalent quaternion
References abs(), and(), quaternion(), RaDec2U(), and vector().
Referenced by AStarAttitudeTrajectory(), and SPMMnvr().
REAModel()
function REAModel (in type, in uPlume)
These are reaction engine assemblies, i.e. thrusters. Units are meters. Available types:
 mr-103c
 mr-106e
 mr-111c
 lm
Type REAModel for a demo.
Form
 [v, f, d] = REAModel( type, uPlume )
Inputs
 type         (1,:) Type
 uPlume       (3,1) Unit vector for plume
Outputs
 v            (n,3) Vertices
 f            (n,3) Faces
 d            (1,1) Data
                    .mass
                    .power
                    .propulsion
References and(), DrawVertices(), Frustrum(), GenericProperties(), Inertias(), isempty(), Q2Mat(), REA(), REAModel(), U2Q(), Unit(), and vector().
Referenced by REAModel().
ReynoldsNumber()
function ReynoldsNumber (in rho, in v, in mu, in x)
If viscosity isn't entered it is computed using Sutherland's Law.
Type ReynoldsNumber for a demo using the Standard Atmosphere.
Form
 ReynoldsNumber
 rE = ReynoldsNumber( rho, v, mu, x )
Inputs
 rho          (1,:)     Density
 v            (1,:)     Velocity
 mu           (1,:)     Dynamic viscosity
 x            (1,:)     Characteristic length
Outputs
 rE           (1,:)     Reynold's number
See also
TemperatureStagnation, SutherlandsLaw
References: http://en.wikipedia.org/wiki/Reynolds_number
References Demo(), Plot2D(), ReynoldsNumber(), SutherlandsLaw(), and TemperatureStagnation().
Referenced by BEMVAWT(), HeatTransferCoeffTaylor(), and ReynoldsNumber().
RollPitchToQECI()
function RollPitchToQECI (in r, in v, in roll, in pitch)
The spacecraft is assumed aligned with LVLH when roll and pitch are zero. Roll is about the LVLH x vector and Pitch about the LVLH y vector.
Type RollPitchToQECI for a demonstration.
Form
 q = RollPitchToQECI( r, v, roll, pitch )
Inputs
 r      (3,:)   Position vector in the ECI frame (km)
 v      (3,:)   Velocity vector in the ECI frame (km)
 roll       (1,:)   Roll angle (rad)
 pitch  (1,:)   Pitch angle (rad)
Outputs
 q          (4,:)   Quaternion ECI to Body
References and(), Demo(), Mat2Q(), Q2Mat(), QLVLH(), QPose(), RollPitchToQECI(), vector(), and zeros().
Referenced by RollPitchToQECI().
RotateOBJFile()
function RotateOBJFile (in file, in path, in b, in scale, in delta, in flipNormal)
Writes the new file into the file name_R.obj. After rotation delta is subtracted from the rotated vertex positions i.e. v = scale*(b*v - delta). If file is empty it will open a dialog box.
Form
 RotateOBJFile( file, path, b, scale, delta, flipNormal )
Inputs
 file              (1,:) Filename
 path              (1,:) Path to the file
 b                 (3,3) Transformation matrix
 scale             (1,1) Optional scale factor for the model
 delta             (3,1) Unscaled offset applied before scaling and
 after rotation
 flipNormal        (1,1) If entered flip normal sign
Outputs
 None
References and(), length(), LoadCAD(), and RotateOBJFile().
Referenced by RotateOBJFile().
RVToRADec()
function RVToRADec (in r, in v)
Type RVToRADec for a demo.
Form
 [rA, dec, rADot, decDot] = RVToRADec( r, v )
Inputs
 r             (3,n)    Position vectors
 v             (3,n)    Velocity vectors
Outputs
 rA           (1,n)     Right ascension
 dec          (1,n)     Declination
 rADot        (1,n)     Right ascension rate
 decDot       (1,n)     Declination rate
References and(), and RVToRADec().
Referenced by RVToRADec().
RWAArray()
function RWAArray (in model, in cantAngle, in wH, in b, in rA, in body)
The wheels are stuck on top of each other since the internal geometry is not defined. There is a fifth component for the containing box.
Type RWAArray for a demo.
Form
 m = RWAArray( model, cantAngle, wH, b, rA, body )
Inputs
 model       (1,:)     RWA model name
 cantAngle   (1,1)     Cant angle from z
 wH          (1,2)     [width, height]
 b           (3,3)     Box orientation
 rA          (3,1)     Box location
 body        (1,1)     Body
Outputs
 m           {5}       Component information cell array
                        .name
                        .class, etc.
References Box(), RWA(), and RWAArray().
Referenced by RWAArray().
RWAModel()
function RWAModel (in r, in u)
Dimensions are in meters. If no outputs are given it will draw the wheel. Available types are:
 'dynacon1000'
 'hr02'
 'hr04'
 'hr01'
 'hr15S'
 'hr17'
 'hm07'
 'hr20m'
 'hr20x'
 'hr15m'
 'hm55'
 'hr60'   (default)
 'hm45'
 'hr150'
 'hr195'
 'hm1800'
Form
 [v, f, p] = RWAModel( type, u )
 [v, f, p] = RWAModel( r, u )
Inputs
 r           (1,:) Type string or struct with following fields:
                   ('r','rTop','rBottom','hTop','hCenter','hBottom', 'u')
 u           (3,1) Unit vector if r is a string.
Outputs
 v           (:,3) Vertices
 f           (:,3) Faces
 p            (.)  Properties data structure
                     mass  (.)
                     power (.)
References and(), Demo(), Frustrum(), RWA(), RWAModel(), Unit(), and vector().
Referenced by RWAModel(), and RWAPatch().
RWAPatch()
function RWAPatch (in r, in u)
Type RWAPatch for a demo.
Form
 [v, f] = RWAPatch( r, u )
Inputs
 r           (1,:) Type or struct:
                   ('r','hCenter','rTop','hTop', 'rBottom', 'hBottom', 'u')
 u           (3,1) Unit vector is r is a character.
Outputs
 v           (:,3) Vertices
 f           (:,3) Faces
See also
: RWAModel
References Cross(), Demo(), NewFig(), RWA(), RWAModel(), RWAPatch(), Unit(), vector(), and zeros().
Referenced by RWAPatch().
SaturnsRings()
function SaturnsRings ()
This is an array vertices and faces for four components.
Type SaturnsRings for a demo that draws the rings and the planet.
Form
 m = SaturnsRings
Inputs
 None
Outputs
 m          (4,1)   Rings
                    .v vertices
                    .f faces
References and(), GeomPatch(), NewFig(), SaturnsRings(), set(), and zeros().
Referenced by SaturnsRings().
SCMG()
function SCMG (in rR, in rG, in hR, in hG, in n)
See also
ExtrudeFromProfile and Frustrum.
Type SCMG for a demo.
Form
 [vR, fR, vG, fG] = SCMG( rR, rG, hR, hG, n )
Inputs
 type     (1,:) Battery type 'lion' only
 el       (1,6) Elements vector [a,i,W,w,e,M] or structure
 planet   (1,:) Name of planet
 jD       (1,1) Julian date (days)
 powerMax (1,1) Maximum power from the solar panels (W)
Outputs
 vR       (:,3) Vertices for extrusion
 fR       (:,3) Faces for extrusion
 vG       (:,3) Vertices for frustrum
 fG       (:,3) Faces for frustrum
References and(), Demo(), DrawPatch(), ExtrudeFromProfile(), Frustrum(), SCMG(), and vector().
Referenced by SCMG().
SetCADQuaternion()
function SetCADQuaternion (in g, in qECIToBody)
This helper function inserts the quaternion in the correct part of the data structure. Due to the successive hinge model, i.e. the hinge specifies the rotation to the PRIOR frame, the TRANSPOSE of the inertial to body quaternion is assigned to the first hinge. This is not intuitive but makes the model self-consistent. The field set is:
 g.body(1).bHinge.q
Form
 g = SetCADQuaternion( g, qECIToBody )
Inputs
 g            (.)     CAD model
 qECIToBody   (.)     ECI to body quaternion
Outputs
 g            (.)     Updated CAD model
References QPose(), quaternion(), and set().
Referenced by DrawSCPlanPlugIn(), and SetCADRotation().
SetCADRotation()
function SetCADRotation (in g, in varargin)
Specify one body per call. Specify either a quaternion, angle/axis pair, or a transformation matrix for a body hinge. The information is stored in the bHinge field of the specified body, g.body(k).bHinge
Inertial data can be passed as well. When specifying the inertial state, the LVLH quaternion will be computed automatically if the position and velocity are both entered. Otherwise an LVLH quaternion may be specified separately.
The examples below show some possibilities. Specify one body per call to the function but list as many parameters as desired.
Form
 g = SetCADRotation( g, varargin )
 Hinge data:
 g = SetCADRotation( g, 'body', k, ...
 'quaternion', q )         % no transpose
 g = SetCADRotation( g, 'body', k, ...
 'axis', j, ...
 'angle', theta )
 g = SetCADRotation( g, 'body', k, ...
 'matrix', b )
 Inertial data:
 g = SetCADRotation( g, 'position', rECI, ...
 'velocity', vECI )
 g = SetCADRotation( g, 'attitude', qECIToBody )   % takes transpose
 g = SetCADRotation( g, 'qlvlh',    qLVLH )
See also
BHinge, SetCADQuaternion, SetCADState
References and(), BHinge(), quaternion(), SetCADQuaternion(), and SetCADState().
SetCADState()
function SetCADState (in g, in rECI, in vECI)
This helper function inserts the state in the correct part of the data structure. The LVLH quaternion is also computed, it is used for camera pointing in the 3D views.
Form
 g = SetCADState( g, rECI, vECI )
Inputs
 g          (.)      CAD model
 rECI      (3,1)     ECI position vector (km)
 vECI      (3,1)     ECI velocity vector (km/s)
Outputs
 g          (.)     Updated CAD model
                    .rECI
                    .vECI
                    .qLVLH
References QLVLH(), quaternion(), SetCADState(), and vector().
Referenced by SetCADRotation(), and SetCADState().
SHELSFlange()
function SHELSFlange ()
SHELS is the Shuttle Hitchhiker Ejection Launch System.
Type SHELSFlange for a demo.
Form
 [v, f] = SHELSFlange
Inputs
 None
Outputs
 v          (:,3) Vertices
 f          (:,3) Faces
 volFlange  (1,1) Volume of the flange
Reference: SHELS Users Guide. SSPP-SPEC-040. Revised Dec. 1999.
References and(), Constant(), ExtrudeFromProfile(), length(), and SHELSFlange().
Referenced by SHELSFlange(), and SHELSInterface().
SHELSInterface()
function SHELSInterface ()
SHELS is Space Shuttle Hitchhiker Ejection Launch System. This includes the Marman clamp flange and the umbilical interfaces. Each is generated as a separate object.
Type SHELSInterface for a demo.
Form
 [vF, fF, vPI, fPI, vSI, fSI, volFlange] = SHELSInterface
Inputs
 None
Outputs
 vF         (:,3) Vertices for the flange
 fF         (:,3) Faces for the flange
 vPI        (:,3) Vertices for the power interface
 fPI        (:,3) Faces for the power interface
 vSI        (:,3) Vertices for the signal interface
 fSI        (:,3) Faces for the signal interface
 volFlange  (1,1) Volume of the flange
Reference: SHELS Users Guide. SSPP-SPEC-040. Revised Dec. 1999.
References and(), DrawPatch(), Frustrum(), set(), SHELSFlange(), and SHELSInterface().
Referenced by SHELSInterface().
ShowCAD()
function ShowCAD (in g)
This will apply gouraud lighting for a more realistic image. Any rotations in the body hinges are accounted for. Components will be grouped by subsystem. This window will NOT be able to interact with BuildCADModel; for the interactive GUI, use the button on the Vehicle tab.
Type ShowCAD for a demo.
Form
 tag = ShowCAD( g )
Inputs
 g      (.)   CAD model structure
Outputs
 tag   (1,:)  The tag that identifies the display
See also
: DrawSCPlanPlugIn, DrawCAD
References BuildCADModel(), Demo(), DrawCAD(), DrawSCPlanPlugIn(), and ShowCAD().
Referenced by BallisticCoefficient(), and ShowCAD().
SimpleFuselage()
function SimpleFuselage (in w, in lMiddle, in lTop, in h, in zM)
 5                  4
 ------------------    ^ +z
 |                 \ 3   |
 |                 /     |
 -----------------      ---------> +x +y into the paper
 1                 2
The origin is in the middle of the bottom.
Type SimpleFuselage for a demo.
Form
 [v, f] = SimpleFuselage( w, lMiddle, lTop, h, zM )
Inputs
 w           (1,1)  y width
 lBottom     (1,1)  x length at the bottom
 lTop        (1,1)  x length
 h           (1,1)  z height
 zM          (1,1)  Height of middle point
Outputs
 v           ( 8,3) Vertices
 f           (12,3) Faces
References and(), Demo(), DrawVertices(), Fuselage(), length(), and SimpleFuselage().
Referenced by SimpleFuselage().
SolarWingSupport()
function SolarWingSupport (in w, in l, in t)
l is in the +y direction and w in the +x direction.
Type SolarWingSupport for a demo.
Form
 [v, f] = SolarWingSupport( w, l, t )
Inputs
 w           (1,1)  Panel width (m)
 l           (1,1)  Strut length (m)
 t           (1,1)  Strut thickness (m)
Outputs
 v           (:,3) Vertices
 f           (:,3) Faces
References and(), Demo(), DrawVertices(), length(), Panel(), SolarWingSupport(), Strut(), and Wing().
Referenced by SolarWingSupport().
SpacecraftPlugIn()
function SpacecraftPlugIn (in action, in modifier, in hFig, in position, in callback)
This is a tab of the BuildCADModel GUI.
Form
 x = SpacecraftPlugIn( action, modifier, hFig, position, callback )
Inputs
 action      (1,:)  Action 'initialize', 'update'
 modifier    (1,:)  Modifier to the action or data structure if intialization
 hFig        (1,1)  Handle to the figure or if 'update' radio button handles
 position    (1,4)  [left bottom width height]
 callback    (1,:)  Callback string when something has changed in this gui
Outputs
 x           (1,1)  The tag if action is 'initialize'
See also
Draw2DViewPlugIn, DrawSCPlanPlugIn, DrawSCPlugIn
References BuildCADModel(), close(), CreateCallback(), Draw2DViewPlugIn(), DrawSCPlanPlugIn(), DrawSCPlugIn(), get(), GetH(), GetNewTag(), Initialize(), isempty(), PutH(), and set().
StarCameraBasicModel()
function StarCameraBasicModel (in a, in fL, in aS, in lS)
The vertices are output in meters.
Type StarCameraBasicModel for a demo.
Form
 [v, f] = StarCameraBasicModel( a, fL, aS, lS )
Inputs
 a           (1,1) Aperture (mm)
 fL          (1,1) Focal length (mm)
 aS          (1,1) Aperture of sun shade (mm)
 lS          (1,1) Sun shade length (mm)
Outputs
 v           (:,3) Vertices
 f           (:,3) Faces
References and(), Box(), Demo(), DrawVertices(), Frustrum(), length(), and StarCameraBasicModel().
Referenced by StarCameraBasicModel().
StarCameraModel()
function StarCameraModel (in type, in uBoresight)
This also outputs mass and power data for the models.
Type StarCameraModel for a demo.
Form
 [v, f, d] = StarCameraModel( type, uBoresight )
Inputs
 type              Type, 'astro 5' (default), 'ct633', 'ons'
 uBoresight        Unit vector for the boresight
Outputs
 v                 Vertices
 f                 Faces
 d                 Data
                   .mass
                   .power
References and(), Demo(), length(), StarCameraModel(), Unit(), and vector().
Referenced by StarCameraModel().
SunAzEl()
function SunAzEl (in varargin)
azimuth and elevation of the sun for a time and place on earth.
Type SunAzEl for a demo.
Form
 [az,el,dec] = SunAzEl( day, hour, lat, lon );
 - or -
 [az,el,dec] = SunAzEl( jD, lat, lon );
Inputs
 day         (1,n)   The day of the year, 0 <= day <= 365
 hour        (1,n)   The hour of the day, 0 at midnight, 12 at noon
 lat         (1,n)   The geographic latitude
 lon         (1,n)   The geographic longitude
 jD          (1,n)   The julian date
 lat         (1,n)   The geographic latitude
 lon         (1,n)   The geographic longitude
Outputs
 az          (1,n)   Azimuth angle of the sun (rad)
 el          (1,n)   Elevation angle of the sun (rad)
 dec         (1,n)   The declination of the sun (rad)
References and(), Demo(), and SunAzEl().
Referenced by SunAzEl().
SurfaceOfRevolution()
function SurfaceOfRevolution (in r, in z, in n, in ang)
Type SurfaceOfRevolution for a demo.
Form
 [v, f] = SurfaceOfRevolution( r, z, n, ang )
Inputs
 r      (1,:)   Radius at each z
 z    (1,:)   z length
 n    (1,1)   Number of segments per revolution (Default 20)
 ang (1,2)   Angle range
Outputs
 v  (:,3)   Vertices
 f  (:,3)   Faces
References and(), Demo(), DrawVertices(), length(), SurfaceOfRevolution(), and zeros().
Referenced by CylindricalTank(), LAETR308CAD(), and SurfaceOfRevolution().
SutherlandsLaw()
function SutherlandsLaw (in t, in mu0, in t0, in s)
Defaults are for air. Defaults are mks.
Type SutherlandsLaw for a demo.
Form
 SutherlandsLaw
 mu = SutherlandsLaw( t, mu0, t0, s )
 mu = SutherlandsLaw( t)
Inputs
 t            (1,:)     Temperature
 mu0          (1,1)     Reference viscosity
 t0           (1,1)     Reference temperature
 s            (1,1)     Sutherland temperature
Outputs
 mu           (1,:)     Dynamic viscosity
References: http://www.cfd-online.com/Wiki/Sutherland_law
Referenced by ReynoldsNumber().
TargetFromRPVD()
function TargetFromRPVD (in r, in rP, in v, in d)
Given the current spacecraft location, r, the planet radius, rP, the velocity vector, v and the downrange distance (distance along an arc on surface) it computes the target point on the surface.
Type TargetFromRPVD for a demo.
Form
 [rT,q] = TargetFromRPVD( r, rP, v, d )
Inputs
 r     (3,1)   Spacecraft location
 rP    (1,1)   Radius of planet
 v     (3,1)   Velocity vector
 d     (1,1)   Down range distance
Outputs
 rT    (3,1)   Target point
 q     (4,1)   Quaternion to the target plane coordinate system
References and(), AU2Q(), Cross(), Demo(), Mag(), Mat2Q(), QForm(), Random(), TargetFromRPVD(), Unit(), and vector().
Referenced by DownrangeAndAltFromTarget(), SecondOrderGuidance3D(), and TargetFromRPVD().
TemperatureStagnation()
function TemperatureStagnation (in v, in h, in r)
The the altitude is greater than 80 km it uses values at 80 km.
Type TemperatureStagnation for a demo.
Form
 t0 = TemperatureStagnation( v, h, r )
Inputs
 v              (1,:) Velocity (m/s)
 h              (1,:) Altitude (m)
 r              (1,1) Recovery factor (0.88 turbulent (default) 0.85 laminar)
Outputs
 t0             (1,1) Stagnation temperature (K)
References: http://en.wikipedia.org/wiki/Stagnation_temperature
Referenced by DynamicPressureAndHeat(), ReynoldsNumber(), and TSTOFlightProfile().
TesselatePolygon()
function TesselatePolygon (in g)
This updates the faces and vertices fields, f and v. If there are no outputs, draws a picture of the updated model.
Form
 g = TesselatePolygon( g )
Inputs
 g              (.)  CAD data structure
Outputs
 g              (.)  Updated CAD model
References and(), Centroid(), isempty(), length(), NewFig(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by ExportDSim().
ThrusterCAD()
function ThrusterCAD (in uPlume, in dExit, in l, in n, in rC, in lC, in lOC)
This is a cylinder for the thruster body and a cone for the plume. Leave out the last three inputs to draw only the plume.
 \    /                 |
 \  /          l       | uPlume
 \/
 -
Type ThrusterCAD for a demo.
Form
 [v, f] = ThrusterCAD( uPlume, dExit, l, n, rC, lC, lOC )
Inputs
 uPlume      (3,1) Unit vector for the plume
 dExit       (1,1) Nozzle exit diameter
 l           (1,1) Nozzle length
 n           (1,1) Number of divisions, optional, default 20
 rC          (1,1) Radius of interface cylinder, optional
 lC          (1,1) Length of interface cylinder, optional
 lOC         (1,1) Offset of interface cylinder, optional
Outputs
 v           (:,3) Vertices
 f           (:,3) Faces
References and(), Cone(), Demo(), DrawVertices(), Frustrum(), isempty(), length(), Q2Mat(), ThrusterCAD(), U2Q(), Unit(), and vector().
Referenced by ThrusterCAD().
ThrusterPatch()
function ThrusterPatch (in uPlume, in dExit, in l, in n, in hasBox)
This is a box for the thruster body and a cone for the plume.
 \    /                 |
 \  /          l       | uPlume
 \/
 -
Type ThrusterPatch for a demo.
Form
 [v, f] = ThrusterPatch( uPlume, dExit, l, n, hasBox )
Inputs
 uPlume      (3,:) Unit vector for plume
 dExit       (1,1) Nozzle exit diameter
 l           (1,1) Nozzle length
 n           (1,1) Number of divisions
 hasBox      (1,1) Puts a box at the base
Outputs
 v           (:,3) Vertices
 f           (:,3) Faces
References and(), Box(), Cone(), Demo(), DrawVertices(), isempty(), length(), Q2Mat(), ThrusterPatch(), U2Q(), Unit(), and vector().
Referenced by ThrusterPatch().
TPlate()
function TPlate (in xB, in xT, in yB, in yT, in h)
With no outputs this generates a picture. The T is in the +Y direction. The base is along T = 0. It is symmetric about the y-axis.
Type TPlate for a demo.
Form
 [v, f, vol, area] = TPlate( xB, xT, yB, yT, h )
Inputs
 xB         (1,1) Width of base
 xT         (1,1) Width of T
 yB         (1,1) Length of base
 yT         (1,1) Length of T
 h          (1,1) Plate thickness
Outputs
 v          (:,3)  Vertices
 f          (:,3)  Faces
 vol        (1,1)  Volume of material
 area       (1,1)  Aggregate surface area
References and(), Demo(), DrawVertices(), and TPlate().
Referenced by TPlate().
TreeBldCAD()
function TreeBldCAD (in g, in s, in spring)
Since version 2.
Form
 x = TreeBldCAD( g, s, spring )
Inputs
 g               (:)   Spacecraft data structure generated by Build3DSC
 s               (:)  .w    (3,1) or (1,1) Rate
                      .q    (4,1) or (1,1) Attitude
 spring          (:)  .k    (3,3) Data structure General stiffness matrix
                      .c    (3,3) Data structure General damping matrix
Outputs
 x               (:,:) Data structure
References and(), isempty(), length(), and Tree().
Referenced by TreeDraw().
TreeDraw()
function TreeDraw (in g, in x, in treeDS)
This routine assumes that the bodies in g are in the same order as the states in x. This is guaranteed if TreeBldCAD is used to create the bodies.
Form
 g = TreeDraw( g, x, treeDS )
Inputs
 g            (.)   CAD data structure
 x            (:,:) States
 treeDS       (:)   Tree data structure
Outputs
 g            (1,:) CAD data structure
References length(), Tree(), TreeBldCAD(), and vector().
TriMesh3DMF()
function TriMesh3DMF (in v, in vM, in fileName, in colorAtt)
This function will append ".t3d" to the file.
The vertices in the vertex list must be in order, for example if the following are the vertices of a rectangle
 1     2
 4     3
they must be entered as [1;2;3;4]
colorAtt is vertex color information. One column vector is entered per vertex. The column vector is composed of
[ RGBDiffuse; RGBSpecular; SpecularExponent; RGBTransparency]
Each RGB variable is a column vector [r;g;b] where r,g and b are between 0 and 1. SpecularExponent is > 1 and can be large.
Since version 3.
Form
 TriMesh3DMF( v, vM, fileName, colorAtt )
Inputs
 v             (3,:)   Vertices
 vM            (:,:)   Vertex map. Must be in order.
 fileName      (:)     Filename
 colorAtt      (10,:)  Color information [[r;g;b];[r;g;b];e;[r;g;b]]
Outputs
 None
References and(), Centroid(), length(), Normal(), and vector().
TubeBetweenPoints()
function TubeBetweenPoints (in x1, in x2, in r, in n)
Type TubeBetweenPoints for a demo.
Form
 [v, f] = TubeBetweenPoints( x1, x2, r, n )
Inputs
 x1      (3,1) Point 1
 x2      (3,1) Point 2
 r       (1,1) Radius (m)
 n       (1,1) Number of divisions, optional, default 20
Outputs
 v       (:,3) Vertices
 f       (:,3) Faces
References and(), Demo(), DrawVertices(), DupVect(), Frustrum(), Mag(), QForm(), Tube(), TubeBetweenPoints(), and U2Q().
Referenced by TubeBetweenPoints().
U2AzEl()
function U2AzEl (in u, in x, in y)
Form
 [az, el] = U2AzEl( u, x, y )
Inputs
 u         (3,:)   Unit vectors
 x         (3,1)   x-axis
 y         (3,1)   y-axis
Outputs
 az        (1,:)   Azimuth
 el        (1,:)   Elevation
References and(), Cross(), Unit(), and vector().
Referenced by AutoPoint(), MeasEarthSensor(), and MeasurementsSunMagUKF().
U2RADec()
function U2RADec (in u, in ignoredArg)
Form
 [rA, dec] = U2RADec( u, rALimit )
Inputs
 u            (3,n)     Unit vectors
 rALimit       (1)      If > 0, will force 0 <= rA < 2*pi,
                         otherwise -pi <= rA <= pi (default)
Outputs
 rA           (1,n)     Right ascension
 dec          (1,n)     Declination
References and(), Unit(), and vector().
Referenced by AB2RADec(), DSunCone(), LunarVisibility(), Q2RADec(), RandSC(), RLPMnvr(), SPMMnvr(), StarDataFromStarMatrix(), SunBeta(), SunCone(), and SunRA().
USR30Motor()
function USR30Motor (in demo)
Type USR30Motor for a demo.
Since version 10.
Form
 [v, f, d] = USR30Motor( demo )
Inputs
 demo        (1,1) If entered run the demo
Outputs
 v           (:,3) Vertices
 f           (:,3) Faces
 d           (1,1) Data
                   .r (1,3) Radii
                   .z (1,3) Z locations of base
References and(), Demo(), DrawVertices(), Frustrum(), and USR30Motor().
Referenced by ICONS(), and USR30Motor().
Wing()
function Wing (in xLE, in xTE, in z, in lERatio, in taper, in tOC, in angle)
The wing span is in the z direction. You enter the leading and trailing edge locations as a function of z, which is the span direction. x is along the fuselage direcion.
Type Wing for a demo.
Form
 [v, f] = Wing( xLE, xTE, z, lERatio, taper, tOC, angle )
Inputs
 xLE        (1,:) Leading edge position
 xTE        (1,:) Trailing edge position
 z          (1,:) Spanwise position
 lERatio    (1,1) Leading edge x to y ratio bigger gives more pointed
                  edge
 taper      (1,1) Ratio of root to tip
 tOC        (1,1) Thickness to chord ratio
 angle      (1,1) Rotates model about x by this angle
Outputs
 v          (:,3)  Vertices
 f          (:,3)  Faces
References abs(), and(), CosD(), Demo(), DrawVertices(), Extrude(), isempty(), length(), and Wing().
Referenced by ACWeightEstimation(), AeroCoefficientPointMass(), AircraftDesign(), AircraftEquilibrium(), AircraftPowerAndThrust(), AircraftThrustFromFlight(), CDCLSubsonic(), ConcordeProperties(), CubeSatModel(), DeltaWing(), DragLoss(), Glide(), GroundEffect(), HSVMassEstimation(), InducedDragCoeff(), LiftAndDrag(), LiftAndDragJonesSearsHaack(), LiftAndDragSeaLevelToOrbit(), MachSwept(), MissileMassEstimation(), RHSLiftingReentry3D(), RHSPointMassAircraft(), SolarWingSupport(), TSTODragData(), VStall(), WettedArea(), WindGust(), Wing(), WingAreaToTaper(), WingFromParameters(), and WingSizingForPullUp().
XenonTank()
function XenonTank (in mXenon)
When you change the mass of Xenon it adjusts the cylindrical section.
Type XenonTank to see a picture.
Form
 [v, f, d] = XenonTank( mXenon )
Inputs
 mXenon     (1,:) Mass of Xenon
Outputs
 v          (:,3)  Vertices
 f          (:,3)  Faces
 d           (.)   Data
                   .pressure    (1,1) Pressure (2175 psi)
                   .length      (1,1) Length, boss to boss
                   .lengthTotal (1,1) Total length
                   .diameter    (1,1) Diameter (13.26")
References length(), Pressure(), and XenonTank().
Referenced by XenonTank().
XenonTankSupport()
function XenonTankSupport (in l)
Type XenonTankSupport for a demo.
Form
 [v, f, vol] = XenonTankSupport( l )
Inputs
 l          (1,:) Length of Strut
Outputs
 v          (:,3)  Vertices
 f          (:,3)  Faces
 vol        (1,1)  Volume of material
References Demo(), DrawVertices(), Frustrum(), Strut(), and XenonTankSupport().
Referenced by XenonTankSupport().