PSS MATLAB Toolboxes: WindTurbine Functions
WindTurbine Functions
WindTurbine Module
The WindTurbine module functions.
Directories
directory AirfoilData
directory Blade
directory ControlAlgos
directory ControlDesign
directory DeviceDesign
directory DynamicModels
directory Generator
directory Mechanical
directory Multibody
directory Sim
directory Utility
directory WindData
directory WindModel
Description
Functions
function ActuatorDiskFromPower (in rho, in p, in eff, in v0, in a)
Compute actuator disk area and power coefficient.
function AreaFromActuatorDisk (in rho, in p, in v0, in a)
Compute area and power coefficient using actuator disk theory.
function BearingLife (in rPM, in d)
Equivalent bearing load and bearing life.
function BEMVAWT (in d)
Two dimensional blade element model for a VAWT.
function BetzLimit ()
Betz limit for maximum power extractable from the air.
function BladeSolidity (in n, in c, in d)
Blade solidity.
function BldComps (in theta, in Xu, in Xd, in V, in Vpm, in Ret)
Computes inflow velocity, blade Reynold's number and angle of attack.
function CLAlpha (in airfoil, in rE)
Computes the lift curve slope for an airfoil.
function ComputeCoeffFromShape (in x, in y, in n, in alpha)
Computes lift, drag and moment coefficients for an airfoil.
function CouplingStress (in d)
Calculates the stress acting on coupling.
function CP2D (in beta, in lambda)
Coefficient of power as a function of pitch and lambda.
function CustomPC2 (in theta, in alpha1)
Custom Pitch Control Algorithm.
function DFIGEquilibrium (in qRef, in omegaM, in d, in options, in x)
Doubly fed induction generator model equilibrium voltages.
function DFIGRHS (in x, in t, in d)
Doubly fed induction generator model.
function DMSModel (in af, in bld, in rot, in wnd, in DynStlModel, in ControlAlgo, in)
Double Multiple Streamtube Model.
function DragAnlytMdl (in cL, in alpha, in kD0, in kD)
Computes drag using an anayltical model.
function DragForce (in d)
Calculates maximum drag force acting on a plate-shaped blade.
function DrawHAWT (in action, in varargin)
Draw a horizontal axis wind turbine.
function DrawVAWT (in action, in varargin)
Draw a vertical axis wind turbine.
function Gearbox (in n, in omegaIn, in torqueIn)
Computes torque and angular rate for a gearbox.
function HAWTRHS (in x, in t, in d)
Horizontal Axis Wind Turbine Dynamics.
function HelicalGear (in d)
Maximum allowable torque and safe horsepower capacity for helical gear.
function HingeMoment (in d)
Calculates moment at a hinge joint.
function IGormont (in af, in bld, in Reb, in alpha, in alphadot, in W)
Improved Gormont Dynamic Stall Model.
function InterferenceFit (in d)
Calculates torque transfer and factor of safety.
function Kaimal (in tau, in dT)
Creates a Kaimal filter.
function LiftAndDragCoeff (in d, in alpha)
Lift and drag coefficients for an airfoil.
function LiftAnlytMdl (in alpha, in cmag, in linmag, in sf)
Computes lift using an analytical model.
function LoadAirfoilFile (in file)
Loads an airfoil file with the file extension .af.
function LoadShapeFile (in file)
Loads a NREL GIS Shapefile for wind.
function MaxTimeStep (in dTs, in n)
Default Wind Turbine Tachometer Model.
function NACABladeMOI (in d)
Approximates the mass moment of inertia about a point.
function Obstruction (in zO, in xO, in x)
Obstruction turbulent flow height.
function ParseIOData (in data, in name)
Parse the i/o data structure into inputs, outputs, states and params.
function PitchMotorSizing (in omega, in delta, in fac)
Determine size of pitch motor based on driving acceleration requirements.
function PitchServo (in beta, in t, in d)
Pitch servo model.
function PMABCMachineSwitchedRHS (in x, in t, in d)
Permanent magnet machine model in ABC coordinates with 6 switches.
function PMBMachineRHS (in x, in ignoredArg, in d)
Permanent magnet brushless machine in DQ coordinates.
function PMMachineABCRHS (in x, in t, in d)
Permanent magnet machine model in ABC coordinates.
function PowCompAnlytBsd (in ignoredArg, in x, in d)
Constant wind model that returns power and angles of attack.
function PowerFromActuatorDisk (in rho, in A, in v0, in a)
Compute power and power coefficient using actuator disk theory.
function RectangularBeam (in d, in V, in M, in yS)
Calculates the tensile and shear stresses acting on a rectangular beam.
function ReluctanceMachineRHS (in x, in t, in d)
Right hand side for a 3 phase reluctance motor or generator.
function RHSVAWTPitchControl (in x, in ignoredArg, in d)
Dynamical model for VAWT pitch control.
function RotationalDynamicsRHS (in ignoredArg, in ignoredArg, in d)
Rotational dynamics model.
function RotBeamBending (in d, in r, in omega)
Calculates maximum bending stress on a rotating beam.
function RotorAssemblyAerodynamics (in v, in k, in f)
Computes the aerodynamic force and torque of each surface in the rotor assembly.
function sign2 (in x)
Computes sign.
function SinePC (in theta, in ignoredArg, in offset)
Sine Pitch Control Algorithm.
function SpurGear (in d)
Maximum allowable torque and safe horsepower capacity for spur gear.
function StaticStall (in af, in ignoredArg, in Reb, in alpha, in ignoredArg, in ignoredArg)
Static Stall Model.
function TorqueHAWT (in w, in d)
Torque produced by a wind turbine rotor.
function TorqueVAWT (in phi, in w, in d)
Torque produced by a VAWT wind turbine rotor.
function VAWTAspectRatio ()
VAWT Aspect ratio.
function VAWTBearingDistance (in d, in yS, in F, in FoS)
Calculates minimum rotor shaft bearing distance.
function VAWTBldMdlRHS (in t, in x, in ignoredArg, in d)
VAWT blade model with a pitch controller.
function VAWTRHS (in x, in t, in d)
Vertical wind turbine model.
function WeldThroatArea (in l)
Calculates the minimum throat area for a fillet weld.
function Wind (in mode, in d)
Wind model.
function WindAdmittance (in harm, in dTF, in dT)
Creates a wind admittance filter.
function WindClass (in type, in k, in height)
Wind class.
function WindDeterministic (in d)
Deterministic wind model.
function WindFromLatLon (in w, in lat, in lon)
Outputs wind data given latitude and longitude.
function WindMdl (in t)
Wind model with constant velocity and angle.
function WindPowerClass (in class, in height)
Gives the wind power class.
function WindProfile (in z, in u30, in dObstacle, in surfaceType)
Surface wind profile.
function WindShear (in vRef, in zRef, in z, in alpha)
Wind shear.
function WindShearExponent (in type)
Wind shear exponent.
function WindspeedHours (in kRef, in hRef, in cRef, in h, in v, in dV, in u)
The hours that the wind is between v(k) +/- dV/2.
function WindStochastic (in mode, in d)
Stochastic wind model.
function WindTurbinePower (in a, in cP, in u, in h, in temp, in lambda, in beta)
Compute the power from a wind turbine.
function WTSim (in action, in modifier)
GUI for running wind turbine simulations.
Function Documentation
ActuatorDiskFromPower()
function ActuatorDiskFromPower (in rho, in p, in eff, in v0, in a)
 Uses actuator disk theory.
 This provides a limit on how much power a wind turbine can produce.
 "a" is defined from the relationship v3 = v0*(1 - 2*a) where v0 is the
 wind speed in front of the machine and v3 is the wind speed at the end
 of the wake. Note that v3 = 0 is NOT the optimum value. The optimum
 value is with a = 1/3 so cP = 16/27. This can never be achieved in
 practice due to aerodynamic losses.
 Type ActuatorDiskFromPower for a demo.
Form
 [A, cP] = ActuatorDiskFromPower( rho, p, eff, v0, a )
Inputs
 rho                (1,1)  Atmospheric density (kg/m^3)
 p                   (1,:)  Power (W)
 eff                 (1,1)  Efficiency
 v0                  (1,:)  Wind velocity (m/s)
 a                   (1,1)  See above
Outputs
 A                   (1,1)  Blade area (m^2)
 cP                  (1,:)  Power coefficient
Reference: Wortman, A. J., "Introduction to Wind Turbine Engineering," Butterworth Publishers, 1983, pp. 3-4.
References ActuatorDiskFromPower(), and(), Demo(), and Wind().
Referenced by ActuatorDiskFromPower().
AreaFromActuatorDisk()
function AreaFromActuatorDisk (in rho, in p, in v0, in a)
 This provides a limit on how much power a wind turbine can produce.
 "a" is defined from the relationship v3 = v0*(1 - 2*a) where v0 is the
 wind speed in front of the machine and v3 is the wind speed at the end
 of the wake. Note that v3 = 0 is NOT the optimum value. The optimum
 value is with a = 1/3 so cP = 16/27. This can never be achieved in
 practice due to aerodynamic losses.
 Type AreaFromActuatorDisk for a demo.
Form
 [A, cP] = AreaFromActuatorDisk( rho, p, v0, a )
Inputs
 rho                (1,1)  Atmospheric density (kg/m^3)
 p                   (1,:)  Power (W)
 v0                  (1,:)  Wind velocity (m/s)
 a                   (1,1)  See above
Outputs
 A                   (1,1)  Blade area (m^2)
 cP                  (1,:)  Power coefficient
Reference: Wortman, A. J., "Introduction to Wind Turbine Engineering," Butterworth Publishers, 1983, pp. 3-4.
References and(), AreaFromActuatorDisk(), Demo(), and Wind().
Referenced by AreaFromActuatorDisk().
BearingLife()
function BearingLife (in rPM, in d)
Units in d can be N or lbs as long as c, fAxial, fRadial are the same. Type BearingLife for a demo for ball bearings.
Form
 [bLife,bLoad] = BearingLife( rPM, d )
Inputs
 rpm        (1,:) RPM
 d           (.)  Data structure
                   .x          (1,1)  Radial Load Factor
                   .fRadial    (1,1)  Radial Load
                   .y          (1,1)  Axial Load Factor
                   .fAxial     (1,1)  Axial Load
                   .c          (1,1)  Dynamic Load Rating
Outputs
 bLife         (1,:)  Bearing Life (hrs)
 bLoad         (1,1)  Equivalent Bearing Load (lbs)
Reference: ISO Standards https://www.amroll.com/bearing-selection-load-life.html
References and(), BearingLife(), DefaultDataStructure(), Demo(), ISO(), and Plot2D().
Referenced by BearingLife().
BEMVAWT()
function BEMVAWT (in d)
Computes the force and torque on a blade element.
Type BEMVAWT for a demo.
Form
 [q, t, alpha] = BEMVAWT( d )
Inputs
 d           (1,1) Data structure
                   .u0       (1,1) Wind velocity (m/s)
                   .rho      (1,1) Density (kg/m^3)
                   .omega    (1,1) Angular rate (rad/s)
                   .r        (1,1) Radius (m)
                   .c        (1,1) Chordwidth (m)
                   .phi      (1,1) Angle from wind (rad)
                   .gamma    (1,1) Pitch angle (rad)
                   .lDFun    (1,:) Lift and drag function pointer
                   .cLAlpha  (1,1) Lift curve slope
Outputs
 q           (1,1) Torque (Nm)
 t           (1,1) Thrust (N)
 alpha       (1,1) Angle of attack (rad)
References and(), BEMVAWT(), Demo(), LoadAirfoilFile(), Plot2D(), ReynoldsNumber(), Wind(), and zeros().
Referenced by BEMVAWT().
BetzLimit()
function BetzLimit ()
 Returns a constant.
Form
 f = BetzLimit
Inputs
 None
Outputs
 f          (1,1)  Betz limit
References BetzLimit().
Referenced by BetzLimit(), and PowerFromActuatorDisk().
BladeSolidity()
function BladeSolidity (in n, in c, in d)
 Solidity of 0.1 is typical. Since solidity is n*c/d you can get
 a solidity > 1.
 Type BladeSolidity for a demo
Form
 s = BladeSolidity( n, c, d )
Inputs
 n          (1,1)  Number of blades
 c          (1,1)  Chordwidth
 d          (1,1)  Diameter
Outputs
 s          (1,1)  Solidity
Reference:
References and(), BladeSolidity(), Demo(), and get().
Referenced by BladeSolidity().
BldComps()
function BldComps (in theta, in Xu, in Xd, in V, in Vpm, in Ret)
Form
 [W, Reb, alpha] = BldComps( theta, Xu, Xd, V, Vpm, Ret )
Inputs
 theta       (1,1)   Angle to wind
 Xu          (1,1)   Upwind tip-speed ratio
 Xd          (1,1)   Downwind tip-speed ratio
 V           (1,1)   Upwind induced velocity (m/s)
 Vpm         (1,1)   Downwind induced velocity (m/s)
 Ret         (1,1)   Wind turbine Reynold's number
Outputs
 W           (1,1)   Relative inflow velocity
 Reb         (1,1)   Blade Reynold's number
 alpha       (1,1)   Angle of attack
References and().
CLAlpha()
function CLAlpha (in airfoil, in rE)
 cL = cLAlpha*alpha with alpha in radians.
Type CLAlpha for a demo with a NACA 0012 airfoil.
Form
 cLAlpha = CLAlpha( airfoil, rE )
Inputs
 airfoil            (1,1) Airfoil data structure
                          .reCL    (1,:) Reynold's number
                          .alphaCL (1,:) Angle of attack (deg)
                          .cL      (:,:) Lift coefficient
                          .reCD    (1,:) Reynold's number
                          .alphaCD (1,:) Angle of attack (deg)
                          .cD      (:,:) Drag coefficient
                          .reCM    (1,:) Reynold's number
                          .alphaCM (1,:) Angle of attack (deg)
                          .cM      (:,:) Moment coefficient
 rE                 (1,1) Reynold's number
Outputs
 cLAlpha            (1,1) Lift curve slope
References CLAlpha(), Demo(), LeastSq(), LoadAirfoilFile(), and Plot2D().
Referenced by CLAlpha().
ComputeCoeffFromShape()
function ComputeCoeffFromShape (in x, in y, in n, in alpha)
The airfoil may be entered as a file with x and y coordinates an image file (such as a .jpg) or as data. Files of numbers are a text file with a .dat suffix and consist of a line with a name and then a list of x,y pairs.
For a demo type
ComputeCoeffFromShape
It will demonstrate an airfoil from a .jpg file and and airfoil from a .dat file.l
The computation uses the vortex panel method and is for inviscid flow only. n can be a number of panels (top and bottom) or a list of x-coordinates for both top and bottom.
If you enter x and y, x must form a closed loop (i.e. start and end at 1.0)
Form
 [cL, cD, cM] = ComputeCoeffFromShape( x, y,          n, alpha )
 [cL, cD, cM] = ComputeCoeffFromShape(     imageFile, n, alpha )
 [cL, cD, cM] = ComputeCoeffFromShape( 'airfoil.dat', n, alpha )
Inputs
 x              (1,:) x coordinates or file name
 y or n         (1,:) y coordinates or number of panels or alpha
 n              (1,1) Number of panels or alpha (deg)
 alpha          (1,n) Angles of attack (rad)
Outputs
 cL             (1,n) Lift coefficients
 cD             (1,n) Drag coefficients
 cM             (1,n) Moment coefficients
References: Kuethe, A.M., and C. Chow, "Foundations of Aerodynamics, Fifth Edition," John Wiley & Sons, 1998.
References and(), ComputeCoeffFromShape(), Demo(), isempty(), length(), Panels(), Plot2D(), set(), and zeros().
Referenced by ComputeCoeffFromShape().
CouplingStress()
function CouplingStress (in d)
Form
 [sigma , tau] = CouplingStress ( d )
Inputs
 d          (1,1)  Data structure
                   .OD         (1,1)  Outer diameter (m)
                   .ID         (1,1)  Bore Diameter (m)
                   .v          (1,1)  Speed (m/s)
                   .t          (1,1)  Chord (m)
Outputs
 sigma      (1,1)  Axial Stress (Pa)
 tau        (1,1)  Shear Stress (Pa)
Reference:
References CouplingStress(), and Demo().
Referenced by CouplingStress().
CP2D()
function CP2D (in beta, in lambda)
Form
 cP = CP2D( beta, lambda )
Inputs
 beta          (1,n)       Pitch angle
 lambda        (1,m)       Tip speed ratio
Outputs
 cP            (n,m)       Coefficient of power
Reference: Gill Estevez, P. ,"Model Dinamico de Una Turbina de velocidad variable con Generador de Imanes Permanentes y control de angulo de calaje ? Analisis de Control de Velocidad. Figure 4.
References and().
Referenced by TorqueHAWT(), and WindTurbinePower().
CustomPC2()
function CustomPC2 (in theta, in alpha1)
 This control algorithm implements an control pitch angle
 increment as a function of the rotor angle such that the effective
 angle of attack follows a certain profile set in the file.
Form
 PitchInc = CustomPC2(theta,alpha1)
Inputs
theta (1,1) Rotor angle (rad) alpha1 (1,1) Zero-pitch angle of attack (rad)
Outputs
 PitchInc        (1,1)      Pitch angle control increment (rad)
References set().
DFIGEquilibrium()
function DFIGEquilibrium (in qRef, in omegaM, in d, in options, in x)
 Computes the equilibrium voltages and states
Form
 [u, x] = DFIGEquilibrium( qRef, omegaM, options, x )
Inputs
 qRef       (1,1)  Reference reactive power
 omegaM     (1,1)  Mechanical power
 d          (1,1)  Machine data structure
                   .p      (1,1) Number of poles
                   .lM     (1,1) Mutual inductance (H)
                   .lR     (1,1) Rotor inductance (H)
                   .lR     (1,1) Stator inductance (H)
                   .rR     (1,1) Rotor resistance (Ohm)
                   .rS     (1,1) Stator resistance (Ohm)
                   .u      (4,1) Phase voltages [uDS;uQS;uDR;uQR] (V)
                   .omegaS (1,1) Synchronous speed (rad/s)
                   .tM     (1,1) Mechanical torque (Nm)
                   .j      (1,1) Inertia (kg-m^2)
 options    {}     Options for fminsearch
 x          (4,1)  Initial guess for [iDS;iQS;iDR;iQR]
Outputs
 uR         (2,1)  Rotor voltages[uD;uQ]
 x          (6,1)  States [iDS;iQS;iDR;iQR;omega;angle]
References and().
DFIGRHS()
function DFIGRHS (in x, in t, in d)
Form
 d = DFIGRHS
 [xDot, tE, pD] = DFIGRHS( x, t, d )
Inputs
 x          (6,1)  States [iDS;iQS;iDR;iQR;omega;angle]
 t          (1,1)  Time (not used)
 d          (1,1)  Machine data structure
                   .p      (1,1) Number of poles
                   .lM     (1,1) Mutual inductance (H)
                   .lR     (1,1) Rotor inductance (H)
                   .lS     (1,1) Stator inductance (H)
                   .rR     (1,1) Rotor resistance (Ohm)
                   .rS     (1,1) Stator resistance (Ohm)
                   .u      (4,1) Phase voltages [uDR;uDQ;uDS;uQS] (V)
                   .omegaS (1,1) Synchronous speed (rad/s)
                   .tM     (1,1) Mechanical torque (Nm)
                   .j      (1,1) Inertia (kg-m^2)
Outputs
 xDot       (5,1)  State Derivatives  [iDS;iQS;iDR;iQR;omega;angle]
 tE         (1,1)  Electrical torque (Nm)
 q          (2,1)  Reactive power [s;r] (W)
 p          (2,1)  Power [s;r] (W)
Reference: T. Demiray, F. Milano and G. Andersson,"Dynamic Phasor Modeling of the Doubly-fed Induction Generator under Unbalanced Conditions
References and(), and DFIGRHS().
DMSModel()
function DMSModel (in af, in bld, in rot, in wnd, in DynStlModel, in ControlAlgo, in)
Predict upwind and downwind interference parameters.
Form
 [u, upm] = DMSModel(af,bld,rot,wnd,DynStlModel,ControlAlgo,
 nItLim,nAngStps)
Inputs
  af              (.)       Airfoil data structure
                            .reCL    (1,:) Reynolds number
                            .alphaCL (1,:) Angle of attack (deg)
                            .cL      (:,:) Lift coefficient
                            .reCD    (1,:) Drag Reynolds number
                            .alphaCD (1,:) Angle of attack (deg)
                            .cD      (:,:) Drag coefficient
                            .reCM    (1,:) Reynolds number
                            .alphaCM (1,:) Angle of attack (deg)
                            .cM      (:,:) Moment coefficient
                            .alpha0  (1,1) Angle of atack for zero lift
 bld              (.)       Blade data structure
                            .c       (1,1) Chord (m)
                            .H       (1,1) Blade half length (m)
                            .thknss  (1,1) Blade thickness (m)
 rot              (.)       Rotor data structure
                            .R       (1,1) Rotor radius (m)
                            .N       (1,1) Number of blades
                            .omega   (1,1) Rotor speed (rad/s)
                            .zR      (1,1) Ground clearance (m)
 wnd              (.)       Wind data structure
                            .Vinf    (1,1) Free stream wind speed (m/s)
                            .alphaw  (1,1) Wind shear component
                            .rho     (1,1) Air density (kg/m^3)
                            .nu      (1,1) Kinematic viscosity (m^2/2)
 DynStlMdl        (1,1)     String specifying Dynamic Stall Model
 ControlAlgo      (1,1)     String specifying Control Algorithm
Outputs
 u               (1,1)     Upwind interference parameter
 upm             (1,1)     Downwind interference parameter
References:
[1] I. Paraschivoiu, "Double-Multiple Streamtube Model for Studying @iverbatim Vertical Axis Wind Turbines", Journal of Propulsion, Vol. 4, No. 4, pp 370-377
[2] Y. Staelens, F. Saeed, and I. Paraschivoiu, "A straight-bladed @iverbatim variable-pitch VAWT concept for improved power generation", Proc. 41st Aerospace Sciences Meeting and Exhibit, 2003, Reno, NV; AIAA-2003-0524
References abs(), and(), isempty(), length(), Limit(), and Wind().
DragAnlytMdl()
function DragAnlytMdl (in cL, in alpha, in kD0, in kD)
For a demo, type DragAnlytMdl. The model is a quadratic law.
Form
 cD = DragAnlytMdl( cL, alpha, kD0, kD )
Inputs
 cL                 (1,1) Lift coefficient
 alpha              (1,:) Angle of attack (rad)
 kD0                (1,1) Zero angle of attack value
 kD                 (1,1) Lift coupling coefficient
Outputs
 cD                 (1,:) Drag coefficient
References Demo(), DragAnlytMdl(), isempty(), and Plot2D().
Referenced by DragAnlytMdl(), PowCompAnlytBsd(), TorqueVAWT(), and VAWTBldMdlRHS().
DragForce()
function DragForce (in d)
Form
 [F] = DragForce( d )
Inputs
 d          (1,1)  Data structure
                   .h          (1,1)  Blade height (m)
                   .c          (1,1)  Chord length (m)
                   .v          (1,1)  Speed (m/s)
                   .rho        (1,1)  Fluid density (kg/m^3)
Outputs
 F          (1,1)  Drag force (N)
Reference:
References Demo(), DragForce(), and length().
Referenced by DragForce(), and HingeMoment().
DrawHAWT()
function DrawHAWT (in action, in varargin)
 Allows for variable yaw, generator angle, propeller angle and
 blade angles. The length and diameter of the tower and the length
 and chord of the blades can be specified. All other parameters
 are generated automatically.
 To use first initialize
 DrawHAWT( 'initialize', name, lBlade, chordBlade, lTower, dTower, nBlades )
 Then update each time step
 DrawHAWT( 'update', yaw, angleGen, angleProp, angleBlade, windVector )
 When you are done close the window
 DrawHAWT( 'close' )
 Type DrawHAWT for a demo.
Form
 DrawHAWT( 'initialize', name, lBlade, chordBlade, lTower, dTower, nBlades )
 DrawHAWT( 'update', yaw, angleGen, angleProp, angleBlade, windVector )
 DrawHAWT( 'close' )
Inputs
 action     (1,:) 'initialize', 'update' or 'close'
 'initialize'
 name       (1,:) Name
 lBlade     (1,1) Length of the blades
 chordBlade (1,1) Chord of the blades
 lTower     (1,1) Length of the tower
 dTower     (1,1) Diameter of tower
 nBlades    (1,1) Number of blades
 'update'
 yaw        (1,1) Yaw angle (rad)
 angleGen   (1,1) Generator angle (rad)
 angleProp  (1,1) Propeller angle (rad)
 angleBlade (n,1) Blade pitch angles (rad)
 windVector (3,1) Wind vector
 'close'
 none
Outputs
 none
References and(), close(), Demo(), DrawHAWT(), Initialize(), length(), vector(), Wind(), and zeros().
Referenced by DrawHAWT().
DrawVAWT()
function DrawVAWT (in action, in varargin)
 Allows for variable generator angle, propeller angle and
 blade angles. The length and diameter of the tower and the length
 and chord of the blades can be specified. All other parameters
 are generated automatically.
 To use first initialize
 DrawVAWT( 'initialize', name, lBlade, lArm, chordBlade, lTower, dTower, nBlades )
 Then update each time step
 DrawVAWT( 'update', angleGen, angleProp, angleBlade, windVector )
 When you are done close the window
 DrawVAWT( 'close' )
 Type DrawVAWT for a demo.
Form
 DrawVAWT( 'initialize', name, lBlade, lArm, chordBlade, lTower, dTower, nBlades )
 DrawVAWT( 'update', angleGen, angleProp, angleBlade, windVector )
 DrawVAWT( 'close' )
Inputs
 action     (1,:) 'initialize', 'update' or 'close'
 'initialize'
 name       (1,:) Name
 lBlade     (1,1) Length of the blades
 lArm       (1,1) Length of the blade support arms
 chordBlade (1,1) Chord of the blades
 lTower     (1,1) Length of the tower
 dTower     (1,1) Diameter of tower
 nBlades    (1,1) Number of blades
 'update'
 angleGen   (1,1) Generator angle (rad)
 angleProp  (1,1) Propeller angle (rad)
 angleBlade (n,1) Blade pitch angles (rad)
 windVector (3,1) Wind vector
 'close'
 none
Outputs
 none
References and(), close(), Demo(), DrawVAWT(), Initialize(), length(), vector(), Wind(), and zeros().
Referenced by DrawVAWT().
Gearbox()
function Gearbox (in n, in omegaIn, in torqueIn)
 This function does not model losses or nonlinearities.
 Type Gearbox for a demo.
 n will be > 1 to decrease the angular rate and increase the torque.
 n will be < 1 to increase the angular rate and decrease the torque.
Form
 [omegaOut, torqueOut] = Gearbox( n, omegaIn, torqueIn )
Inputs
 n          (1,1)  Gear ratio n = omegaIn/omegaOut
 omegaIn    (1,:)  Incoming angular rate
 torqueIn   (1,:)  Incoming torque
Outputs
 omegaOut   (1,:)  Outgoing angular rate
 torqueOut  (1,:)  Outgoing torque
References and(), Demo(), and Gearbox().
Referenced by Gearbox().
HAWTRHS()
function HAWTRHS (in x, in t, in d)
This model includes an electrical machine in direct-quadrature form.
Form
 xDot = HAWTRHS( x, t, d )
Inputs
 x          (4,1)  State [angle;rate;iD;iQ]
 t          (1,1)  Time (not used)
 d          (1,1)  Data structure
                   .rho      (1,1) Atmospheric density (kg/m^3
                   .rTurbine (1,1) Blade radius (m)
                   .wind     (1,1) Wind speed (m/s)
                   .beta     (1,1) Pitch angle (rad)
                   .uD       (1,1) Direct voltage
                   .uQ       (1,1) Quadrature voltage
                   .inr      (1,1) Inertia
Outputs
 xDot       (4,1)  State derivative [angle;rate;iD;iQ]
References PMBMachineRHS(), TorqueHAWT(), and Wind().
Referenced by WT_HAWTDFIGSetup(), and WT_HAWTSetup().
HelicalGear()
function HelicalGear (in d)
 Uses 45 degree helix angle parallel shaft helical gears based on the
 gear tooth form factor.
Form
 [ Load, Torque, Power, Thrust ] = HelicalGear( d )
Inputs
 d          (1,1)  Data structure
                   .dia        (1,1)  Pitch Diameter (in)
                   .s          (1,1)  Maximum Safe Material Stress (PSI)
                   .f          (1,1)  Face Width (in)
                   .y          (1,1)  Tooth Form Factor
                   .pn         (1,1)  Normal Diametral Pitch (teeth/in)
                   .v          (1,1)  Pitch Line Velocity (ft/min)
                   .rpm        (1,1)  Rotations Per Minute
Outputs
 Load       (1,1)  Tooth Load (lbf)
 Torque     (1,1)  Maximum Allowable Torque (lbs*in)
 Power      (1,1)  Power Capacity (Horsepower)
 Thrust     (1,1)  Axial Thrust Load (lbf)
Reference: Lewis Formula, Barth Revision
References and(), Demo(), HelicalGear(), and Normal().
Referenced by HelicalGear().
HingeMoment()
function HingeMoment (in d)
Form
 M2 = HingeMoment( d )
Inputs
 d          (1,1)  Data structure
                   .h          (1,1)  Blade height (m)
                   .c          (1,1)  Chord length (m)
                   .v          (1,1)  Velocity (m/s)
                   .F          (1,1)  Force (N)
                   .L          (1,1)  Member length (m)
                   .a          (1,1)  Cross-sectional area (m^2)
                   .rho        (1,1)  Density (kg/m^3)
Outputs
 M2         (1,1)  Maximum hinge moment at center
Reference:
References Cross(), Demo(), DragForce(), HingeMoment(), and length().
Referenced by HingeMoment().
IGormont()
function IGormont (in af, in bld, in Reb, in alpha, in alphadot, in W)
 Obtain blade lift, drag and moment coefficients.
Form
 [CL, CD, CM] = IGormont( af, bld, Reb, alpha, alphadot, W )
Inputs
 af               (1,1)   Airfoil data structure
                          .reCL    (1,:) Reynolds number
                          .alphaCL (1,:) Angle of attack (deg)
                          .cL      (:,:) Lift coefficient
                          .reCD    (1,:) Drag Reynolds number
                          .alphaCD (1,:) Angle of attack (deg)
                          .cD      (:,:) Drag coefficient
                          .reCM    (1,:) Reynolds number
                          .alphaCM (1,:) Angle of attack (deg)
                          .cM      (:,:) Moment coefficient
                          .alpha0  (1,1) Angle of atack for zero lift
 bld              (1,1)   Blade data structure
                          .c       (1,1) Chord (m)
                          .H       (1,1) Blade half length (m)
                          .thknss  (1,1) Blade thickness (m)
 Reb              (1,1)   Blade Reynolds number
 alpha            (1,1)   Angle of attack (rad)
 alphadot         (1,1)   Angle of attack rate (rad/s)
 W                (1,1)   Relative wind speed (m/s)
Outputs
 CL            (1,1)      Blade lift coefficient
 CD            (1,1)      Blade drag coefficient
 CM            (1,1)      Blade moment coefficient
Reference: Gormont, R. E., "A Mathematical Model of Unsteady Aerodynamics and Radial Flow for Application to Helicopter Rotors," US Army Air Mobility R&D Lab, Report on Boeing- Vertol Contract DAAJ02-71-C-0045, May 1973.
References abs(), and(), and length().
InterferenceFit()
function InterferenceFit (in d)
 Determined from the stress distribution in the fit.
Form
 [T, FOS] = InterferenceFit ( d )
Inputs
 d          (1,1)  Data structure
                   .delta      (1,1)  Total diametral interference (m)
                   .ri         (1,1)  Inner radius of shaft (m)
                   .ro         (1,1)  Outer radius of hub (m)
                   .r          (1,1)  Radius of interference (m)
                   .Eo         (1,1)  Young's modulus (Pa)
                   .Ei         (1,1)  Young's modulus (Pa)
                   .mu         (1,1)  Viscosity (Pa*s)
                   .nuo        (1,1)  Poisson's ratio of Hub
                   .nui        (1,1)  Poisson's ratio of shaft
                   .l          (1,1)  Length of engagement (m)
Outputs
 T          (1,1)  Torque (N*m)
 FOS        (1,1)  Factor of Safety
Reference: Robert L. Norton. Machine Design: An Integrated Approach. Upper Saddle River, NJ: Prentice Hall, 2000
References abs(), and(), Demo(), and InterferenceFit().
Referenced by InterferenceFit().
Kaimal()
function Kaimal (in tau, in dT)
 If dT is entered
 x[k+1] = a*x[k] + b*u[k]
 y[k]   = c*x[k] + d*u[k]
 else
 dx/dt  = ax + bu
 y  = cx + du
 Type Kaimal for a demo
Form
 [a,b,c,d] = Kaimal( tau, dT )
Inputs
 tau        (1,1) Time constant
 dT         (1,1) Sample time
Outputs
 a          (1,1) State transition matrix
 b          (1,1) Input matrix
 c          (1,1) Output matrix
 d          (1,1) Feedthrough matrix
Reference: Rosas, P., "DYNAMIC INFLUENCES OF WIND POWER ON THE POWER SYSTEM", Orsted DTU, PhD Thesis, March 2003, pp. 47-53. Figure 3.14.
References and(), C2DZOH(), FResp(), Kaimal(), and ND2SS().
Referenced by Kaimal(), Wind(), WindStochastic(), WT_HAWTDFIGSetup(), WT_HAWTSetup(), and WT_WindModel().
LiftAndDragCoeff()
function LiftAndDragCoeff (in d, in alpha)
Form
 [cL, cD] = LiftAndDragCoeff( d, alpha )
Inputs
 d          (1,1)  Data structure
                   .cLAlpha    (1,1)  Lift curve slope
                   .rho        (1,1)  Air density (kg/m^3)
                   .u0         (1,1)  Speed (m/s)
                   .c          (1,1)  Chord (m)
                   .s          (1,1)  Span (m)
                   .e          (1,1)  Oswald efficency factor
                   .mu         (1,1)  Viscosity
 alpha      (1,:)  Angle of attack (rad)
Outputs
 cL         (1,1)  Lift coefficient
 cD         (1,1)  Drag coefficient
Reference: R. Miller. 16.751 Course Notes. M.I.T. Department of Aeronautics and Astronautics, 1977.
References and(), Demo(), LiftAndDragCoeff(), and Plot2D().
Referenced by BEMHAWT(), and LiftAndDragCoeff().
LiftAnlytMdl()
function LiftAnlytMdl (in alpha, in cmag, in linmag, in sf)
For a demo, type LiftAnlytMdl.
Form
 cL = LiftAnlytMdl( alpha )
Inputs
 alpha              (1,:) Angle of attack (rad)
Outputs
 cL                 (1,:) Lift coefficient
References abs(), Demo(), isempty(), LiftAnlytMdl(), and Plot2D().
Referenced by LiftAnlytMdl(), PowCompAnlytBsd(), TorqueVAWT(), and VAWTBldMdlRHS().
LoadAirfoilFile()
function LoadAirfoilFile (in file)
The file format is:
 CL
 Reynold's numbers
 alpha CL at Reynold's numbers
 CD
 Reynold's numbers
 alpha CD at Reynold's numbers
 CM
 Reynold's numbers
 alpha CM at Reynold's numbers
Type LoadAirfoilFile('demo') for a demo.The default airfoil file is NACA0018.
Form
 airfoil = LoadAirfoilFile( file )
Inputs
 file               (1,:)  Airfoil file name
Outputs
 airfoil            (.)   Airfoil data structure
                          .reCL    (1,:) Reynold's number
                          .alphaCL (1,:) Angle of attack (deg)
                          .cL      (:,:) Lift coefficient
                          .reCD    (1,:) Drag Reynold's number
                          .alphaCD (1,:) Angle of attack (deg)
                          .cD      (:,:) Drag coefficient
                          .reCM    (1,:) Reynold's number
                          .alphaCM (1,:) Angle of attack (deg)
                          .cM      (:,:) Moment coefficient
References isempty(), length(), LoadAirfoilFile(), and Plot2D().
Referenced by BEMVAWT(), CLAlpha(), ComputeAirfoilCoeff(), LoadAirfoilFile(), and RHSVAWTPitchControl().
LoadShapeFile()
function LoadShapeFile (in file)
If no inputs are given it will display a file open dialog box. If will only show .shp files and will automatically load all files of the same name and different suffixes. Shapefiles can have up to 8 components:
 filename.shp  Shapes
 filename.shx  Index for shapes (not used)
 filename.dbf  Attribute file (in dbase format)
 filename.sbn  Part I of spatial index of features
 filename.sbx  Part II of spatial index of features
 filename.ain  Part I of attribute index of active fields in a table
 filename.aix  Part II of attribute index of active fields in a table
 filename.avl  Legend for a shapefile
The first 3 are always required. The last 4 are required if present.
Enter LoadShapeFile('demo') for a demo
Form
 w = LoadShapeFile( file )
Inputs
 file     (1,:)  shp file name
Outputs
 w        (.)    Data structure
                   .lon      {n} (1,:) Longitude of polygon vertices (deg)
                   .lat      {n} (1,:) Latitude of polygon vertices (deg)
                   .wind(n)            Wind values
                   .lonRange (1,2)     Longitude range [min max]  (deg)
                   .latRange (1,2)     Latitude range [min max]  (deg)
                   .name     (1,:)     File name
References and(), and LoadShapeFile().
Referenced by LoadShapeFile(), and WindFromLatLon().
MaxTimeStep()
function MaxTimeStep (in dTs, in n)
For use in WTSim.m.
Form
 dTMax = MaxTimeStep( dTs, n )
Inputs
 dTs       (1,:)  Time steps
 n         (1,1)  Number of bits
Outputs
 dTMax      (1,1)  Maximum time step
References length(), Wind(), and WTSim().
NACABladeMOI()
function NACABladeMOI (in d)
on the blade cross-section for symmetrical NACA blades.
Form
 MOI = NACABladeMOI(d)
Inputs
 d          (.)    Data structure
                   .t          (1,1)  Thickness Ratio
                   .c          (1,1)  Chord length (m)
                   .x0         (1,1)  X Coordinate of Rotation Axis (m)
                   .y0         (1,1)  Y Coordinate of Rotation Axis (m)
                   .M          (1,1)  Mass (kg)
                   .dx         (1,1)  Resolution (m)
Outputs
 MOI        (1,1)  Moment of Inertia (kg*m^2)
Reference:
References Demo(), length(), and NACABladeMOI().
Referenced by NACABladeMOI().
Obstruction()
function Obstruction (in zO, in xO, in x)
 Type Obstruction for a demo.
Form
 z = Obstruction( zO, xO, x
Inputs
 zO         (1,1)  Obstruction height
 xO         (1,1)  Obstruction width
 x          (1,:)  Position from obstruction can be negative
Outputs
 z          (1,:)  Turbulent flow height
Reference: Wind New Zealand's Energy
References Obstruction(), and Wind().
Referenced by Obstruction().
ParseIOData()
function ParseIOData (in data, in name)
 Usage:
 [inputs,outputs,states,params] = ParseIOData( data, name )
Inputs
 data       (.)   The i/o data structure. Can be obtained by calling a
                     wind turbine simulation model with no inputs.
 name       (:)   Name of the block (ie, blades, generator)
Outputs
 inputs     {:}   Cell array of input names.
 outputs    {:}   Cell array of output names.
 states     {:}   Cell array of state names. Includes all variable names
                     in the "memory" field.
 params     {:}   Cell array of parameter names.
References and().
PitchMotorSizing()
function PitchMotorSizing (in omega, in delta, in fac)
The pitching moment aerodynamic effect is not explicitly considered.
We assume a sinusoidal function for the desired pitching function. If DeltPitch = -Delta*sin(omega*t) is the desired pitching profile as a function of time,
 d/dt (DeltPitch) = -Delta*omega*cos(omega*t), and
 d^2/dt^2 (DeltPitch) = Delta*Omega^2*sin(omega*t).
Form
 [maxSpd, maxAngAcc] = PitchMotorSizing( omega, delta, fac )
Inputs
 omega       (1,1)  Maximum rotor speed (rad)
 delta       (1,1)  Magnitude of sinusoidal pitching (rad)
 fac         (1,1)  Design limit factor
Outputs
 maxSpd      (1,1)  Maximum speed
 maxAngAcc   (1,1)  Maximum angular acceleration
References and(), Demo(), and PitchMotorSizing().
Referenced by PitchMotorSizing().
PitchServo()
function PitchServo (in beta, in t, in d)
Form
 betaDot = PitchServo( beta, t, d )
Inputs
 beta          (1,1)       Pitch angle
 t             (1,1)       Time (not used)
 d             (1,1)       Data structure
                           .k             (1,1) Forward gain
                           .betaLimit     (1,1) Maximum beta
                           .betaRateLimit (1,1) Maximum beta rate
Outputs
 betaDot       (2,1)       Beta rate
Reference: Gill Estevez, P. ,"Model Dinamico de Una Turbina de velocidad variable con Generador de Imanes Permanentes y control de angulo de calaje ? Analisis de Control de Velocidad. Figure 6.
PMABCMachineSwitchedRHS()
function PMABCMachineSwitchedRHS (in x, in t, in d)
The switches connect the 3 phases to a resistor and capactor in parallel. Assumes a 3 phase machine in a Y connection. Control is by setting the switch positions. The permanent magnet flux distribution is assumed sinusoidal. The switch state has six possibilities. For a six switch inverter we define
 v
 |
 s1
 |- Phase A ----------
 s4
 |
 ground
 v
 |
 s3
 |- Phase B ----------
 s6
 |
 ground
 v
 |
 s5
 |- Phase C ----------
 s2
 |
 ground
The switch states are
 uA        uB        uC
 1 S5,S6,S1 closed      1/3      -2/3      1/3
 2 S6,S1,S2 closed      2/3      -1/3     -1/3
 3 S1,S2,S3 closed      1/3       1/3     -2/3
 4 S2,S3,S4 closed     -1/3       2/3     -1/3
 5 S3,S4,S5 closed     -2/3       1/3      1/3
 6 S4,S5,S6 closed     -1/3      -1/3      2/3
Form
 xDot = PMMachineABCSwitchedRHS( x, t, d )
Inputs
 x       (6,1)    The state vector [iA;iB;iC;omegaM;thetaM;u]
 t       (1,1)    Time
 d       (1,1)    Data structure
                  .lM   (1,1) Mutual inductance
                  .psiM (1,1) Permanent magnet flux
                  .lSS  (1,1) Stator self inductance
                  .rS   (1,1) Stator resistance
                  .p    (1,1) Number of poles (1/2 pole pairs)
                  .s    (1,1) Switch state
                  .tL   (1,1) Load torque
                  .bM   (1,1) Viscous damping (Nm/rad/s)
                  .j    (1,1) Inertia
                  .cL   (1,1) Load capacitance
                  .rL   (1,1) Load resistance
Outputs
 x       (6,1)    The state vector derivative
Reference: Lyshevski, S. E., "Electromechanical Systems, Electric Machines, and Applied Mechatronics," CRC Press, 2000,
References and(), Capacitor(), connect(), PMABCMachineRHS(), and vector().
PMBMachineRHS()
function PMBMachineRHS (in x, in ignoredArg, in d)
It returns only the motor current derivatives. It assumes that the inductances and magnet flux are not functions of time.
Form
 d = PMBMachineRHS;
 [xDot, tE, pD] = PMBMachineRHS( x, t, d )
Inputs
 x          (3,1)  States [iD;iQ;omegaM;thetaM]
 t          (1,1)  Time (not used)
 d          (1,1)  Machine data structure
                   .p   (1,1) Number of poles
                   .lMD (1,1) Direct mutual inductance (H)
                   .lMQ (1,1) Quadrature mutual inductance (H)
                   .psi (1,1) Magnet Flux
                   .rS  (1,1) Stator resistance (Ohm)
                   .u   (2,1) Phase voltages [uD;uQ] (V)
                   .inr (1,1) Polar inertia
                   .tM  (1,1) Mechanical torque (Nm)
Outputs
 xDot       (2,1)  State Derivative [iD;iQ;omegaM;thetaM]
 tE         (1,1)  Electrical torque (Nm)
 pD         (1,1)  Power dissipated (W)
References and(), and PMBMachineRHS().
PMMachineABCRHS()
function PMMachineABCRHS (in x, in t, in d)
Assumes a 3 phase machine in a Y connection. The permanent magnet flux distribution is assumed sinusoidal.
Form
 xDot = PMMachineABCRHS( x, t, d )
Inputs
 x       (5,1)    The state vector [iA;iB;iC;omegaM;thetaM]
 t       (1,1)    Time
 d       (1,1)    Data structure
                  .lM   (1,1) Mutual inductance
                  .psiM (1,1) Permanent magnet flux
                  .lSS  (1,1) Stator self inductance
                  .rS   (1,1) Stator resistance
                  .p    (1,1) Number of poles (1/2 pole pairs)
                  .u    (3,1) [uA;uB;uC]
                  .tL   (1,1) Load torque
                  .bM   (1,1) Viscous damping (Nm/rad/s)
                  .j    (1,1) Inertia
Outputs
 x       (5,1)    The state vector derivative
Reference: Lyshevski, S. E., "Electromechanical Systems, Electric Machines, and Applied Mechatronics," CRC Press, 2000,
References vector(), and zeros().
PowCompAnlytBsd()
function PowCompAnlytBsd (in ignoredArg, in x, in d)
Form
 [Pow, alpOut] = PowCompAnlytBsd( t, x, d )
Inputs
 t            (1,1) Not used
 x            (:,1) States: (2+2*(number of blades),1)
 d            (.)   Data structure containing model parameters
                    .nBlades (1,1) Number of blades
                    .R       (1,1) Radius (m)
                    .vWind   (1,1) Velocity of wind (m/s)
                    .rho     (1,1) Density (kg/m^3)
                    .A       (1,1) Blade area (m^2)
Outputs
 Pow                (1,1)         Power
 alpVEC             (d.nBlades,1) Angles of attack vector
References and(), Constant(), DragAnlytMdl(), Initialize(), LiftAnlytMdl(), sign2(), vector(), and zeros().
PowerFromActuatorDisk()
function PowerFromActuatorDisk (in rho, in A, in v0, in a)
 This provides a limit on how much power a wind turbine can produce.
 "a" is defined from the relationship v3 = v0*(1 - 2*a) where v0 is the
 wind speed in front of the machine and v3 is the wind speed at the end
 of the wake. Note that v3 = 0 is NOT the optimum value. The optimum
 value is with a = 1/3 so cP = 16/27. This can never be achieved in
 practice due to aerodynamic losses.
 The rotor swept area is pi*r^2 for a HAWT and hd for a VAWT.
 Type PowerFromActuatorDisk for a demo.
Form
 [p, cP] = PowerFromActuatorDisk( rho, A, v0, a )
Inputs
 rho                 (1,1)  Atmospheric density (kg/m^3)
 A                   (1,1)  Rotor swept area (m^2)
 v0                  (1,:)  Wind velocity (m/s)
 a                   (1,1)  See above
Outputs
 p                   (1,:)  Power (W)
 cP                  (1,:)  Power coefficient
Reference: Wortman, A. J., "Introduction to Wind Turbine Engineering," Butterworth Publishers, 1983, pp. 3-4.
References and(), BetzLimit(), Demo(), PowerFromActuatorDisk(), and Wind().
Referenced by PowerFromActuatorDisk().
RectangularBeam()
function RectangularBeam (in d, in V, in M, in yS)
 and the design factor of safety for the material used.
Form
 [sigma, tau, FOS] = RectangularBeam( d, V, M, yS)
Inputs
 d          (1,1)  Data structure
                   .w          (1,1)  Width (m)
                   .h          (1,1)  Height (m)
                   .t          (1,1)  Thickness (m)
 V          (1,1)  Shear Force (N)
 M          (1,1)  Bending Moment (N*m)
 yS         (1,:)  Yield Stress (Pa)
Outputs
 sigma      (1,1)  Flexural stress (Pa)
 tau        (1,1)  Shear stress (Pa)
 FOS        (1,1)  Factor of Safety
References abs(), and(), Demo(), and RectangularBeam().
Referenced by RectangularBeam().
ReluctanceMachineRHS()
function ReluctanceMachineRHS (in x, in t, in d)
Static and coulomb friction are allowed.
Form
 [xDot, tE] = ReluctanceMachineRHS( x, t, d )
Inputs
 x          (5,1)  States [iAS;iBS;iCS;omegaR;thetaR]
 t          (1,1)  Time (not used)
 d          (1,1)  Machine data structure
                   .p   (1,1) Number of poles
                   .b   (1,1) Viscous friction (Nms/rad)
                   .s   (1,1) Static friction (Nm)
                   .j   (1,1) Inertia (kg-m^2)
                   .lMD (1,1) Direct mutual inductance (H)
                   .lMQ (1,1) Quadrature mutual inductance (H)
                   .lLS (1,1) Self inductance (H)
                   .rS  (1,1) Stator resistance (Ohm)
                   .tL  (1,1) Load torque (Nm)
                   .u   (3,1) Phase voltages (V)
Outputs
 xDot       (5,1)  State Derivative [iAS;iBS;iCS;omega;theta]
 tE         (1,1)  Electrical torque (Nm)
Reference: Lyshevski, S. E., "Electromechanical Systems, Electric Machines, and Applied Mechatronics," CRC Press, 2000, pp. 567-575.
References and(), and Friction().
RHSVAWTPitchControl()
function RHSVAWTPitchControl (in x, in ignoredArg, in d)
Form
 xDot = RHSVAWTPitchControl( x, ~, d )
Inputs
 x               (6*n,1)   [omega;omegaDot]
 t               (1,1)     Time (not used)
 d               (.)       Data structure
                           .m        (1,1) Mass
                           .rho      (n,1) Blade chord
                           .d        (n,1) Blade length
                           .inr      (1,1) Blade polar inertia
                           .airfoil  (.) See LoadAirfoilFile
Outputs
 xDot           (6*n,1)   d[omega;omegaDot]/dt
References Cross(), length(), LoadAirfoilFile(), Mag(), Unit(), vector(), Wind(), and zeros().
RotationalDynamicsRHS()
function RotationalDynamicsRHS (in ignoredArg, in ignoredArg, in d)
The angular acceleration is the difference between the electromagnetic torque and the wind (or mechanical) torque.
Form
 omegaDot = RotationalDynamicsRHS( omega, t, d )
Inputs
 omega         (1,1)       Angular rate
 t             (1,1)       Time (not used)
 d             (1,1)       Data structure
                           .h             (1,1) Forward gain (sec)
                           .tEM           (1,1) Back emf torque (Nm)
                           .tW            (1,1) Wind torque (Nm)
Outputs
 omegaDot      (1,1)       Angular accelerations
Reference: Gill Estevez, P. ,"Model Dinamico de Una Turbina de velocidad variable con Generador de Imanes Permanentes y control de angulo de calaje ? Analisis de Control de Velocidad. Figure 5.
References and(), and Wind().
RotBeamBending()
function RotBeamBending (in d, in r, in omega)
 Beam is cylindrical and supported at its ends.
 Axis of rotation is parallel to the beam.
Form
 [bS, FOS] = RotBeamBending( d, r, omega)
Inputs
 d          (1,1)  Data structure
                   .m          (1,1)  Mass (kg)
                   .OD         (1,1)  Outer Diameter (m)
                   .ID         (1,1)  Inner Diameter (m)
                   .L          (1,1)  Length (m)
                   .yS         (1,1)  Yield Stress (Pa)
 r          (1,1)  Distance from axis of rotation (m)
 omega      (1,1)  Angular speed (rad/s)
Outputs
 bS         (1,1)  Bending Stress (Pa)
 FoS        (1,1)  Factor of Safety
References and(), Demo(), and RotBeamBending().
Referenced by RotBeamBending().
RotorAssemblyAerodynamics()
function RotorAssemblyAerodynamics (in v, in k, in f)
This function should be replaced by a more detailed model. This model assumes that the wing camber is along x and the normal to the wing is along z. y is along the wing length. Loads RotorAssemblyAeroData.mat and saves the data into a persistent variable.
Form
 [force, torque] = RotorAssemblyAerodynamics( v, k, d )
Inputs
 v            (3,1)  Wind-relative velocity vector in the local frame
 k           (1,1)  Element ID
 d           (3,1)  Additional data* optional
Outputs
 force        (3,1)  Force vector
 torque      (3,1)  Torque vector
References and(), Cross(), isempty(), length(), Mag(), Unit(), vector(), and Wind().
sign2()
function sign2 (in x)
If x >= 0 it equals 1.
Form
 sign2 = sign2(x)
Inputs
 x                  (1,:) Input
Outputs
 sign2              (1,:) Sign
References sign2().
Referenced by PowCompAnlytBsd(), sign2(), TorqueVAWT(), and VAWTBldMdlRHS().
SinePC()
function SinePC (in theta, in ignoredArg, in offset)
 This control algorithm implements an sinusoidal control pitch angle
 increment as a function of the rotor angle. The magnitude and phase of
 the sine law, as well as a constant pitch offset can be set in the
 file.
Form
 PitchInc = SinePC(theta,alpha1,offset)
Inputs
theta (1,1) Rotor angle (rad) alpha1 (1,1) Zero-pitch angle of attack (rad) [NOT USED] offset (1,1) Desired offset angle
Outputs
 PitchInc        (1,1)      Pitch angle control increment (rad)
References and(), and set().
SpurGear()
function SpurGear (in d)
This is valid for metals.
Form
 [Load, Torque, Power] = SpurGear( d )
Inputs
 d          (1,1)  Data structure
                   .dia        (1,1)  Pitch Diameter (in)
                   .s          (1,1)  Maximum Safe Material Stress (PSI)
                   .f          (1,1)  Face Width (in)
                   .y          (1,1)  Tooth Form Factor
                   .p          (1,1)  Diametral Pitch (teeth/in)
                   .v          (1,1)  Pitch Line Velocity (ft/min)
                   .rpm        (1,1)  Rotations Per Minute
Outputs
 Load       (1,1)  Tooth Load (lbs)
 Torque     (1,1)  Maximum Allowable Torque (lbs*in)
 Power      (1,1)  Power Capacity (Horsepower)
Reference: Lewis Formula, Barth Revision
References and(), DefaultDataStructure(), Demo(), DispWithTitle(), and SpurGear().
Referenced by SpurGear().
StaticStall()
function StaticStall (in af, in ignoredArg, in Reb, in alpha, in ignoredArg, in ignoredArg)
This model simply returns the lift, drag and moment coefficients by looking up the airfoil data files. The static stall information is contained in the raw airfoil data
Form
 [CL,CD,CM] = StaticStall(af,bld,Reb,thknss,alpha,alphadot,c,W)
Inputs
 af              (.)      Airfoil data structure
                          .reCL    (1,:) Reynolds number
                          .alphaCL (1,:) Angle of attack (deg)
                          .cL      (:,:) Lift coefficient
                          .reCD    (1,:) Drag Reynolds number
                          .alphaCD (1,:) Angle of attack (deg)
                          .cD      (:,:) Drag coefficient
                          .reCM    (1,:) Reynolds number
                          .alphaCM (1,:) Angle of attack (deg)
                          .cM      (:,:) Moment coefficient
                          .alpha0  (1,1) Angle of atack for zero lift
bld              (.)      Blade data structure [NOT USED]
                          .c       (1,1) Chord (m)
                          .H       (1,1) Blade half length (m)
                          .thknss  (1,1) Blade thickness (m)
Reb              (1,1)     Blade Reynolds number
alpha            (1,1)     Angle of attack (rad)
alphadot         (1,1)     Angle of attack rate (rad/s) [NOT USED]
W                (1,1)     Relative wind speed (m/s)
Outputs
 CL            (1,1)       Blade lift coefficient
 CD            (1,1)       Blade drag coefficient
 CM            (1,1)       Blade moment coefficient
References and(), and length().
TorqueHAWT()
function TorqueHAWT (in w, in d)
 Uses CP2D.
Form
 d = TorqueHAWT;
 [t, pWind] = TorqueHAWT( w, d )
Inputs
 w          (1,1)  Rotor angular rate (rad/s)
 d          (1,1)  Data structure
                   .rho      (1,1) Atmospheric density (kg/m^3
                   .rTurbine (1,1) Blade radius (m)
                   .wind     (1,1) Wind speed (m/s)
                   .beta     (1,1) Pitch angle (rad)
Outputs
 t          (1,1)  Torque (Nm)
 pWind      (1,1)  Power (W)
Reference: Rosas, P., "DYNAMIC INFLUENCES OF WIND POWER ON THE POWER SYSTEM", Orsted DTU, PhD Thesis, March 2003.
References CP2D(), TorqueHAWT(), and Wind().
Referenced by HAWTRHS(), TorqueHAWT(), WT_Blades(), WT_Controller(), WT_HAWTDFIGSetup(), WT_HAWTSetup(), and WT_VAWTSetup().
TorqueVAWT()
function TorqueVAWT (in phi, in w, in d)
 Uses Analytical Lift and Drag Models
Form
 d = TorqueVAWT;
 [t, pWind] = TorqueVAWT( w, d )
Inputs
 phi        (1,1)  Blade pitch (degrees)
 w          (1,1)  Rotor angular rate (rad/s)
 d          (1,1)  Data structure
                   .rho      (1,1) Atmospheric density (kg/m^3
                   .rTurbine (1,1) Blade radius (m)
                   .wind     (1,1) Wind speed (m/s)
                   .n        (1,1) Number of blades
                   .A        (1,1) Reference area
Outputs
 t          (1,1)  Torque (Nm)
 pWind      (1,1)  Power (W)
References and(), DragAnlytMdl(), Initialize(), LiftAnlytMdl(), sign2(), TorqueVAWT(), and Wind().
Referenced by TorqueVAWT(), and WT_VAWTBlades().
VAWTAspectRatio()
function VAWTAspectRatio ()
Outputs
Form
 a = VAWTAspectRatio
Inputs
 None
Outputs
 a          (1,:) Aspect ratio range
References length(), Plot2D(), and VAWTAspectRatio().
Referenced by VAWTAspectRatio().
VAWTBearingDistance()
function VAWTBearingDistance (in d, in yS, in F, in FoS)
 Assumes axial load capacity of bearings is appropriate for load.
Form
 dist = VAWTBearingDistance( d, yS, F, FoS )
Inputs
 d          (1,1)  Data structure
                   .do         (1,1)  Outer Rotor Shaft Diameter (m)
                   .di         (1,1)  Inner Rotor Shaft Diameter (m)
                   .A          (1,1)  Bearing to Blade Distance (m)
                   .B          (1,1)  Blade mounting distance (m)
 yS         (1,:)  Yield Strength (Pa)
 F          (1,1)  Axial Load (N)
 FoS        (1,1)  Factor of Safety
Outputs
 dist       (1,1)  Distance (m)
Reference:
 Copyright (c) 2009 Princeton Satellite Systems, Inc.
 All rights reserved.
References Demo(), and VAWTBearingDistance().
Referenced by VAWTBearingDistance().
VAWTBldMdlRHS()
function VAWTBldMdlRHS (in t, in x, in ignoredArg, in d)
Form
 d = VAWTBldMdlRHS
 xDot = VAWTBldMdlRHS( t, x, flag, d )
Inputs
 t                  Time       (1,1) Not used
 x                  States     (2 + 2*(number of blades),1)
 d                  Structure containing model parameters
                    .nBlades   (1,1) Number of blades
                    .VWind     (1,1) Wind velocity (m/s)
                    .R         (1,1) Rotor radius (m)
                    .alprefmag (1,1  Preference magnitude
                    .A         (1,1) Blade area (m^2)
                    .Jb        (1,1) Blade inertia (kg-m^2)
                    .rho       (1,1) Atmospheric density (kg/m^3)
                    .Omdes     (1,1) Desired angular rate (rad/s)
                    .phi       (1,1) Phase angle (rad/s)
Outputs
 xDot               States     (2 + 2*(number of blades),1)
Form
 d = VAWTBldMdlRHS
 xDot = VAWTBldMdlRHS( t, x, flag, d )
Inputs
 t                  Time       (1,1) Not used
 x                  States     (2 + 2*(number of blades),1)
 d                  Structure containing model parameters
                    .nBlades   (1,1) Number of blades
                    .VWind     (1,1) Wind velocity (m/s)
                    .R         (1,1) Rotor radius (m)
                    .alprefmag )1,1)
                    .A         (1,1) Blade area (m^2)
                    .Jb        (1,1) Blade inertia (kg-m^2)
                    .rho       (1,1) Atmospheric density (kg/m^3)
                    .Omdes     (1,1) Desired angular rate (rad/s)
                    .phi       (1,1) Phase angle (rad/s)
Outputs
 xDot               States     (2 + 2*(number of blades),1)
References DefaultDataStructure(), DragAnlytMdl(), Initialize(), LiftAnlytMdl(), sign2(), VAWTBldMdlRHS(), Wind(), and zeros().
Referenced by VAWTBldMdlRHS().
VAWTRHS()
function VAWTRHS (in x, in t, in d)
Form
 d = VAWTRHS
 [xDot, torque] = VAWTRHS( x, t, d )
Inputs
 x             (2,1)       [theta;omega]
 t             (1,1)       Time (not used)
 d             (1,1)       Data structure
                           .rho        (1,1) Atmosphere density
                           .alpha0     (1,1) Angle of attack at zero pitch
                           .pitchAngle (1,3) Pitch angles
                           .cD0        (1,1) Drag coefficient
                           .cLAlpha    (1,1) Lift as a function of alpha
                           .K          (1,1) Induced drag factor
                           .angle      (1,3) Angle of blade mount
                           .wind       (3,1) Wind vector
                           .r          (3,3) Blade arms to axis
                           .inr        (1,1) System axial inertia
Outputs
 xDot          (2,1)       d[theta;omega]/dt
 torque        (1,1)       Axial torque
References Cross(), DefaultDataStructure(), Mag(), Unit(), VAWTRHS(), vector(), Wind(), and zeros().
Referenced by VAWTRHS().
WeldThroatArea()
function WeldThroatArea (in l)
Form
 a = WeldThroatArea( l )
Inputs
 l          (1,:)  Load (N)
Outputs
 a          (1,1)  Throat area (m^2)
Reference: ASTM Standards for weld strength.
References Demo(), and WeldThroatArea().
Referenced by WeldThroatArea().
Wind()
function Wind (in mode, in d)
 Generates a discrete time model using a zero order hold for the
 wind noise filters. First call with Wind( 'init', d ) to
 initialize the model. Then call w = Wind( 'run', d ) to
 get the wind model. This model is designed for 3 blade
 horizontal axis wind turbines as the harmonic filters are order 3.
 Type
 Wind
 for a demo.
Form
 w = Wind( mode, d )
Inputs
 mode       (1,:)  'demo', 'init' or 'run'
 d          (1,1)  Data structure
                   .n         (1,1) Number of blades
                   .tau       (1,1) Cutoff for Kaimal Filter
                   .dTF       (1,1) Blade Radius/Mean Wind Speed
                   .sigmaWind (1,1) 1 sigma wind noise speed
                   .angle     (1,1) Blade angle
                   .dT        (1,1) Time step
                   .wHarm     (1,1) Amplitude of nth harmonic
                   .angle     (1,1) Blade angle
                   .wMean     (1,1) Mean wind speed
Outputs
 w          (1,1)  Wind speed
Reference: Rosas, P., "DYNAMIC INFLUENCES OF WIND POWER ON THE POWER SYSTEM", Orsted DTU, PhD Thesis, March 2003.
References Demo(), get(), Kaimal(), Plot2D(), TimeLabl(), Wind(), WindDeterministic(), WindStochastic(), and zeros().
Referenced by ActuatorDiskFromPower(), AircraftPointMassCLPSim(), AircraftPointMassControl(), AircraftPointMassRHS(), AircraftPointMassSim(), AirshipInit(), AreaFromActuatorDisk(), BEMHAWT(), BEMVAWT(), DMSModel(), DrawHAWT(), DrawVAWT(), HAWTRHS(), MaxTimeStep(), NOAAWindData(), Obstruction(), PlotWindField(), PowerFromActuatorDisk(), RHSVAWTPitchControl(), RotationalDynamicsRHS(), RotorAssemblyAerodynamics(), SSFromNonlinear(), TorqueHAWT(), TorqueVAWT(), VAWTBldMdlRHS(), VAWTRHS(), Wind(), WindClass(), WindDeterministic(), WindFunction(), WindGust(), WindLatLon(), WindLatLonAlt(), WindMdl(), WindProfile(), WindShear(), WindShearExponent(), WindspeedHours(), WindStochastic(), WindTrendsDemo(), WindTurbinePower(), WT_Blades(), WT_Controller(), WT_Converter(), WT_DFIG(), WT_Estimator(), WT_Generator(), WT_Grid(), WT_HAWTDFIGSetup(), WT_HAWTSetup(), WT_Structure(), WT_Tach(), WT_Transmission(), WT_VAWTBlades(), WT_VAWTController(), WT_VAWTEstimator(), WT_VAWTSetup(), WT_VAWTTach(), WT_WindModel(), and WT_WindSensor().
WindAdmittance()
function WindAdmittance (in harm, in dTF, in dT)
 If dT is entered
 x[k+1] = a*x[k] + b*u[k]
 y[k]   = c*x[k] + d*u[k]
 else
 dx/dt  = ax + bu
 y  = cx + du;
 Type WindAdmittance for a demo
Form
 WindAdmittance
 [a,b,c,d] = WindAdmittance( harm, dTF, dT )
Inputs
 tau        (1,1) Time constant
 dTF        (1,1) Frequency scaling constant = Blade radius/mean wind
 dT         (1,1) Sample time
Outputs
 a          (1,1) State transition matrix
 b          (1,1) Input matrix
 c          (1,1) Output matrix
 d          (1,1) Feedthrough matrix
Reference: Rosas, P., "DYNAMIC INFLUENCES OF WIND POWER ON THE POWER SYSTEM", Orsted DTU, PhD Thesis, March 2003, pp. 47-53. Figure 3.14.
References and(), C2DZOH(), Demo(), Frequency(), FResp(), ND2SS(), set(), and WindAdmittance().
Referenced by WindAdmittance(), and WindStochastic().
WindClass()
function WindClass (in type, in k, in height)
Returns information related to a U.S. wind class. Classes are from 1 to 7. The information can be a 30 m or 50 m. Default is 30 m.
For a demo yype
 WindClass
Form
 [w, p] = WindClass( type, k, height )
Inputs
 type       (1,:) 'class' or 'speed'
 k          (1,1) Class number (1-7) or wind speed (m/s)
 height     (1,1) Height (m) can only be 30 or 50
Outputs
 w          (1,1) If type == 'class' speed: [min, max] otherwise class
 p          (1,1) If type == 'class' power: [min, max]
Reference: http://www.windpower.org/en/stat/unitsw.htm#visco
References and(), Demo(), length(), Wind(), and WindClass().
Referenced by WindClass().
WindDeterministic()
function WindDeterministic (in d)
Models tower effect.
 n is the harmonic. It is the number of blades for odd numbers of blades
 and half the number of blades for even numbers of blades.
 Type
 WindDeterministic
 for a demo.
Form
 w = WindDeterministic( d )
Inputs
 d          (1,1)  Data structure
                   .n       (1,1) Harmonic
                   .wHarm   (1,1) Amplitude of nth harmonic
                   .angle   (1,1) Blade angle
                   .wMean   (1,1) Mean wind speed
Outputs
 w          (1,1)  Wind speed
Reference: Rosas, P., "DYNAMIC INFLUENCES OF WIND POWER ON THE POWER SYSTEM", Orsted DTU, PhD Thesis, March 2003, pp. 47-53. Figure 3.14.
References and(), Demo(), Plot2D(), TimeLabl(), Wind(), and WindDeterministic().
Referenced by Wind(), WindDeterministic(), WT_HAWTDFIGSetup(), and WT_WindModel().
WindFromLatLon()
function WindFromLatLon (in w, in lat, in lon)
The data is derived from the w data structure which is obtained from LoadShapeFile. This function is slow so once you have obtained your wind file it is best so save it!
Enter WindFromLatLon for a demo
Form
 WindFromLatLon
 wind = WindFromLatLon( w, lat, lon )
Inputs
 w         (.)    Data structure
                   .lon      {n} (1,:) Longitude of polygon vertices (deg)
                   .lat      {n} (1,:) Latitude of polygon vertices (deg)
                   .wind(n)            Wind values
                   .lonRange (1,2)     Longitude range [min max]  (deg)
                   .latRange (1,2)     Latitude range [min max]  (deg)
                   .name     (1,:)     File name
 lat       (1,:)  Latitudes
 lon       (1,:)  East Longitudes
Outputs
 wind     (n,m)  Wind class (lon,lat)
References and(), LoadShapeFile(), and WindFromLatLon().
Referenced by WindFromLatLon().
WindMdl()
function WindMdl (in t)
Use as a replacement for the variable wind model.
Form
 [VWind, AngWind] = WindMdl
Inputs
 t                  (1,1) Not used
Outputs
 VWind              (1,1) Wind velocity
 AngWind            (1,1) Wind angle
References and(), Wind(), and WindMdl().
Referenced by WindMdl().
WindPowerClass()
function WindPowerClass (in class, in height)
Enter WindPowerClass for a demo
Form
 wind = WindPowerClass( class, height )
Inputs
 class     (1,1) 1-7
 height    (1,1) 10m or 50m
Outputs
 wind     (n,m)  Wind (lon,lat)
Reference: http://www.nrel.gov/gis/wind.html
References and(), and WindPowerClass().
Referenced by WindPowerClass().
WindProfile()
function WindProfile (in z, in u30, in dObstacle, in surfaceType)
 Computes a wind profile for neutral stability conditions. z will be
 limited internally to >= (2/3)*dObstacle.
 surfaceType may be a number or a type. Allowable types are
 'water'  'grassland' 'cropland' 'forest' 'brush'
 Type
 WindProfile
 for a demo
Form
 w = WindProfile( z, u30, dObstacle, surfaceType )
Inputs
 z           (1,:) 'class' or 'speed'
 u30         (1,1) Wind velocity at 30 m (m/s)
 dObstacle   (1,1) Average obstacle height (m)
 surfaceType (1,1) Surface type name or number (m if number)
Outputs
 w           (1,:) Wind speed
Reference: http://en.wikipedia.org/wiki/Log_wind_profile
References Demo(), Wind(), and WindProfile().
Referenced by WindProfile().
WindShear()
function WindShear (in vRef, in zRef, in z, in alpha)
 Type WindShear for a demo.
Form
 WindShear
 v = WindShear( vRef, zRef, z, alpha )
Inputs
 vRef       (1,:)  Reference velocity
 zRef       (1,1)  Reference height
 z          (1,:)  Height
 alpha      (1,:)  Number or type
Outputs
 v          (1,:)  Velocity
Reference: Wind: New Zealand's Energy
References Demo(), Energy(), Plot2D(), Wind(), WindShear(), and WindShearExponent().
Referenced by WindShear().
WindShearExponent()
function WindShearExponent (in type)
 Type WindShearExponent for a demo.
Form
 alpha = WindShearExponent( type )
Inputs
 type       (1,:)  Type of surface
Outputs
 alpha      (1,1)  Wind shear exponent
Reference: Wind ? New Zealand?s Energy
References Demo(), Energy(), Wind(), and WindShearExponent().
Referenced by WindShear(), and WindShearExponent().
WindspeedHours()
function WindspeedHours (in kRef, in hRef, in cRef, in h, in v, in dV, in u)
 kRef and cRef are at hRef. h is the actual height of the hub.
 The function adjusts v so that v(k+1) - v(k) = dV.
 Type WindspeedHours for a demo in Lubbock Texas.
Form
 [w, v] = WindspeedHours( kRef, hRef, cRef, h, v, dV, u )
Inputs
 kRef       (1,1) Reference k
 hRef       (1,1) Reference height
 cRef       (1,1) Reference c
 h          (1,1) Actual hub height
 v          (1,:) Wind speed range
 dV         (1,1) Bin width
 u          (1,:) Units for plots
Outputs
 w          (1,:) Hours at windspeed
 v          (1,:) Wind speed range
Reference: Eggleston, D. M, and F. S. Stoddard, "Wind Turbine Engineering Design, "Van Nostrand Rheinhold, 1987, pp. 68-71.
References and(), Demo(), isempty(), length(), Plot2D(), Wind(), WindspeedHours(), and zeros().
Referenced by WindspeedHours().
WindStochastic()
function WindStochastic (in mode, in d)
Generates a discrete time model using a zero order hold for the wind noise filters. First call with WindStochastic('init', d) to initialize the model. Then call w = WindStochastic('run', d) to get the stochastic wind model.
Type
 WindStochastic( 'demo' )
for a demo.
Form
 w = WindStochastic( mode, d )
Inputs
 mode       (1,:)  'demo', 'init' or 'run'
 d          (1,1)  Data structure
                   .n         (1,1) Number of blades
                   .tau       (1,1) Cutoff for Kaimal Filter
                   .dTF       (1,1) Blade Radius/Mean Wind Speed
                   .sigmaWind (1,1) 1 sigma wind noise speed
                   .angle     (1,1) Blade angle
                   .dT        (1,1) Time step
Outputs
 w          (1,1)  Wind speed
Reference: Rosas, P., "DYNAMIC INFLUENCES OF WIND POWER ON THE POWER SYSTEM", Orsted DTU, PhD Thesis, March 2003.
References C2DZOH(), Demo(), get(), Kaimal(), Plot2D(), Series(), TimeLabl(), Wind(), WindAdmittance(), WindStochastic(), and zeros().
Referenced by Wind(), WindStochastic(), WT_HAWTDFIGSetup(), and WT_WindModel().
WindTurbinePower()
function WindTurbinePower (in a, in cP, in u, in h, in temp, in lambda, in beta)
 If tip speed ratio is input it will compute the torque
 and rotational speed.
 The power coefficient "cP" can be specified in one of several ways:
 * A fixed value of cP can be given explicitly.
 * The input cP can be a function name of the form:
 - fun( lambda )       -OR-
 - fun( lambda, beta )
 * If cP is empty:
 - if lambda and beta are not provided, by default cP = 0.44
 - if only lambda is provided, cP is computed using the
 CPvsTipSpeedRatio function.
 - if both lambda and beta are provided, cP is computed using the
 CP2D function.
 Type WindTurbinePower for a demo.
Form
 [p, torque, omega] = WindTurbinePower( a, cP, u, h, temp, lambda, beta )
Inputs
 a          (1,1)  Disk area (m^2)
 cP         (1,1)  Power coefficient. Can be a function name.
 u          (1,:)  Wind velocity (m/s),   default: u = [0:20]
 h          (1,1)  Altitude (m),          default: h = 30
 temp       (1,1)  Temperature (deg-C)    default: temp = 0
 lambda     (1,1)  Tip speed ratio (r*omega/u)
 beta       (1,1)  Blade pitch
Outputs
 power      (1,:)  Power (W)
 torque     (1,:)  Turbine shaft torque (Nm)
 omega      (1,:)  Rotational rate (rad/s)
References Altitude(), and(), CP2D(), CPvsTipSpeedRatio(), Demo(), Disk(), isempty(), Plot2D(), Wind(), and WindTurbinePower().
Referenced by WindTurbinePower().
WTSim()
function WTSim (in action, in modifier)
Form
 WTSim( action, modifier )
Inputs
 action           (:)  Action to be taken by the GUI
 modifier         (:)  Accompanying data
Outputs
 none
Referenced by MaxTimeStep(), WT_Blades(), WT_Controller(), WT_Converter(), WT_DFIG(), WT_Estimator(), WT_Generator(), WT_Grid(), WT_HAWTDFIGSetup(), WT_HAWTSetup(), WT_MultiBody(), WT_Structure(), WT_Tach(), WT_Transmission(), WT_VAWTBlades(), WT_VAWTController(), WT_VAWTEstimator(), WT_VAWTSetup(), WT_VAWTTach(), WT_WindModel(), and WT_WindSensor().