PSS MATLAB Toolboxes: Functions
Functions
StraightLine Module
The StraightLine module functions by directory.
Directories
directory ConstantAccel
Straight-line, constant-acceleration analysis.
directory ConstantThrust
Straight-line, constant-thrust analysis.
directory Data
Supporting data files.
directory Flyby
Straight-line, constant-thrust analysis of a flyby with no decceleration.
directory Rectilinear
Burn, coast, burn rectilinear motion.
directory SLPowerLimited
A power-limited rocket that has variable specific impulse.
Description
Functions
function ComputeDuration (in power, in d)
Compute straight-line duration given power and distance (analytic)
function ComputeDurationFraction (in lambda, in d)
Compute the duration from the desired payload fraction.
function ComputePayload (in power, in d)
Compute payload mass given power, distance, and time (analytic).
function ComputePayloadFraction (in d, in quiet)
Compute payload fraction given time, distance, and uE (analytic)
function ComputeThrust (in d, in doPlot)
Compute the thrust for a mission, given time and distance.
function ConstantAccelDV (in d)
Estimate DV using constant acceleration approximation.
function DryMass (in thrust, in d)
Dry mass of vehicle from thrust: payload + engine + fuel tanks.
function DVConstantThrust (in thrust, in mD, in mF, in uE, in t)
Velocity change with constant thrust given fuel and time.
function DVForTime (in power, in d)
Straight-line DV given payload, power and engine properties.
function DVLimit (in tF, in uE, in sigma, in eta, in f)
Straight-line DV limit from engine parameters and time.
function EngineMass (in thrust, in d)
Compute engine mass given straight-line thrust.
function EnginePower (in thrust, in d)
Compute engine power from thrust.
function EngineReport (in thrust, in d, in doPlot)
Report of constant-thrust engine properties.
function EngineThrust (in power, in d)
Compute engine thrust given power.
function FlybyConstantThrust (in thrust, in uE, in m0, in tF, in v0)
Flyby distance and velocity for constant thrust.
function FlybyOptimal (in d, in maxIter, in iterDisp)
Compute exhaust velocity and thrust for a minimum mass trajectory (fmincon)
function FlybyOptimalImpulse (in d)
Find exhaust velocity to maximise payload fraction (fminsearch)
function FlybyReport (in mP, in d, in doPlot)
Report of engine properties for a straight-line flyby mission.
function FuelMass (in thrust, in d)
Fuel mass from the thrust and duration.
function InitialMass (in thrust, in d)
Initial mass of vehicle from straight-line thrust and time.
function MassFuelElectricConstantPower (in d0)
Fuel mass for a constant accel/power electric propulsion system.
function MassFuelElectricConstantThrust (in d0)
Fuel mass for a constant thrust electric propulsion system.
function MassFuelElectricConstantUE (in d)
Fuel mass for a constant accel/exhaust velocity electric propulsion system.
function MaximumDV (in d, in Pmax)
Maximum DV calculated from power level.
function OptimalCharacteristicVelocity (in lambda, in doInverse)
Optimal velocity ratio for straight-line mission.
function OptimalExhaustVelocity (in d, in quiet)
Find a mass-optimal straight-line exhaust velocity using fminbnd.
function OptimalImpulseDuration (in d, in lambda)
Find the exhaust velocity to minimize duration using fminbnd.
function OptimalTripTime (in d)
Optimal straight-line trip time for an ideal rocket.
function PlotPayloadFraction (in d)
Plot the payload fraction for a range of transfer times.
function RectilinearMission (in thrust, in massDry, in uMax, in uE, in xF, in eff, in sigmaS, in sigmaP)
Generate a mission plan for a burn, coast burn mission.
function RectilinearMotion (in thrust, in massDry, in massFuel, in uE, in t, in u0)
Simulate rectilinear motion.
function RoundTripTime (in dF, in Isp, in thrust, in Mf)
Round trip time for a straight-line, constant thrust (Kammash)
function SimulateFlyby (in mD, in mF, in thrust, in uE, in tF, in n)
Straight line flyby simulation.
function SimulateStraightLineTrajectory (in d, in dontPlot)
Simulate a straight line, constant-thrust trajectory.
function SLPLDataStructure (in mDry)
Straight-line, power-limited data structure.
function SLPLDeltaV (in A, in tau, in tF)
Compute delta-V of an ideal power-limited rocket (straight-line)
function SLPLFindDistance (in tF, in Pj, in vF, in mDry, in m0)
Finds duration, ideal power-limited rocket, straight-line trajectory.
function SLPLFindDuration (in dF, in Pj, in vF, in mDry, in m0)
Finds duration, ideal power-limited rocket, straight-line trajectory.
function SLPLFindMass (in dF, in tF, in Pj, in vF, in mDry)
Finds final mass, ideal power-limited rocket, straight-line trajectory.
function SLPLFindPower (in dF, in tF, in vF, in mDry, in m0)
Finds required power, ideal power-limited rocket, straight-line traj.
function SLPLReport (in Pj, in m0, in tF, in A, in tau, in sigma, in f, in doPlot)
Print a summary of an SLPL problem.
function SLPLSolver (in d, in doPlot)
Solve a straight-line power-limited rocket problem.
function SLPLTrajectory (in A, in tau, in Pj, in m0, in tF, in t, in doPlot)
Compute trajectory for an ideal power-limited rocket (straight-line)
function SolveFlybyPower (in d, in dF, in tau)
Solve a flyby problem and compute engine power for the payload.
function SolveLambdaFlyby (in d)
Compute the payload fraction for a straight-line flyby (fminbnd).
function SolveSigma (in power, in d)
Solve for a sigma given a time, distance, and payload (fzero)
function Straight2DStructure ()
Data structure for straight line mission analysis.
function StraightLineConstantAccel (in d, in n)
Constant acceleration simulation.
function StraightLineConstantThrust (in d0)
Compute straight line bang-bang trajectory with constant thrust.
function StraightLineDataStructure (in d)
Returns data structure for straight line functions.
function StraightLineOptimal (in d, in doPlot)
Compute exhaust velocity and thrust for a minimum mass trajectory.
function StraightLineReport (in data)
Text report for straight line trajectory output.
function SwitchTime (in thrust, in uE, in tF, in m0)
Calculate the switch time for a straight line trajectory.
function ThrustElectric (in tM, in d, in uE, in sigma, in f, in eta, in mP)
Computes power and thrust as a function of specific power.
function TimeToVelocity (in thrust, in massDry, in massFuel, in uE, in u, in u0)
Compute the time to reach a given velocity.
function TripDistance (in thrust, in d)
Distance traveled in time for straight-line constant thrust.
function TripTime (in m0, in d, in doPlot)
Compute the trip time and thrust from distance and total mass (analytic)
function UToMF (in thrust, in uE, in d)
Calculate masses for a spacecraft with an electric propulsion system.
function ZeroPayloadDistance (in tF, in uE, in sigma, in eta, in f)
Maximum straight-line distance achievable in specified time.
function ZeroPayloadFlyby (in d, in tau)
Compute the zero payload flyby distance for duration, or time for distance.
function ZeroPayloadTime (in dF, in uE, in sigma, in eta, in f)
Solve for minimum time to achieve a straight-line distance (fzero).
Function Documentation
ComputeDuration()
function ComputeDuration (in power, in d)
Has a built-in demo for Jupiter.
Form
 [tau,thrust,data] = ComputeDuration( power, d )
Inputs
 power   (1,:)   Power (W), may be an array
 d        (.)    Engine data structure
Outputs
 tau     (1,:)   Trip time (s)
 thrust  (1,1)   Engine thrust (N)
 data     (.)    Engine report
References and(), ComputeDuration(), Constant(), EngineReport(), EngineThrust(), length(), Straight2DStructure(), and zeros().
Referenced by ComputeDuration().
ComputeDurationFraction()
function ComputeDurationFraction (in lambda, in d)
This is an analytic solution for a straight-line, constant-thrust problem. If there are no outputs, will print a report to the command line or, for an input array, create a plot as a function of payload fraction.
Form
 ComputeDurationFraction;   % demo
 [tF,alpha] = ComputeDurationFraction( lambda, d )
 ComputeDurationFraction( lambda, d );   % make plot
Inputs
 lambda   (1,:)  Payload fraction, mPL/m0, must be <1
 d        (.)    Engine data structure
Outputs
 tF      (1,:)   Trip duration (s)
 alpha   (1,:)   Payload/power ratio, mPL/P (kg/W)
See also
: ComputePayloadFraction
References ComputeDurationFraction(), ComputePayloadFraction(), Constant(), EngineReport(), isempty(), length(), Plot2D(), Straight2DStructure(), and TimeLabel().
Referenced by ComputeDurationFraction(), and OptimalImpulseDuration().
ComputePayload()
function ComputePayload (in power, in d)
If the requested distance is not achievable the function will throw an error. For 125 AU/10 year mission, need Isp of 120 km/s. For 5 year Pluto mission, 100 km/s suffices.
Has a built-in demo for 125 AU with a uE of 120 km/s.
Form
 [mP,m0] = ComputePayload( power, d )
Inputs
 power   (1,1)   Power (W)
 d        (.)    Engine data structure
Outputs
 mP      (1,1)   Payload mass
 m0      (1,1)   Initial mass
See also
: ComputePayloadFraction
References and(), ComputePayload(), ComputePayloadFraction(), Constant(), and Straight2DStructure().
Referenced by ComputePayload().
ComputePayloadFraction()
function ComputePayloadFraction (in d, in quiet)
This is for a straight-line, constant-thrust problem. The delta-V is also independent of power or payload mass and is an available output. If the distance is not achievable the function throws a warning.
Form
 [lambda,alpha,dV] = ComputePayloadFraction( d, quiet )
Inputs
 d        (.)    Engine data structure
                    See Straight2DStructure
 quiet    (1)    Boolean. If true, will suppress the warning
Outputs
 lambda   (1,1) Payload fraction, mPL/m0
 alpha    (1,1) Payload/power ratio, mPL/P (kg/W)
 dV       (1,1) Total delta-velocity (km/s)
References and(), ComputePayloadFraction(), Constant(), Demo(), Straight2DStructure(), and ZeroPayloadDistance().
Referenced by ComputeDurationFraction(), ComputePayload(), ComputePayloadFraction(), ComputeThrust(), OptimalExhaustVelocity(), OptimalImpulseDuration(), OptimalTripTime(), PlotPayloadFraction(), and TripTime().
ComputeThrust()
function ComputeThrust (in d, in doPlot)
Find the thrust (and power) that achieves the requested distance dF in the time tF. No other parameters are needed. The solution is analytic. The function will throw an error if the duration is too short.
Type ComputeThrust for a demo.
Form
 [thrust,data] = ComputeThrust( d, doPlot )
Inputs
 d       (.)     Data structure
                    See Straight2DStructure
 doPlot  (1,1)     Display report
Outputs
 thrust  (1,1)    Thrust, N
 data     (.)     Data structure output
                    See EngineReport
See also
: TripDistance, EngineReport, ComputePayloadFraction
References and(), ComputePayloadFraction(), ComputeThrust(), EngineReport(), EngineThrust(), Straight2DStructure(), and TripDistance().
Referenced by ComputeThrust(), MassFuelElectricConstantThrust(), StraightLineOptimal(), and TripTime().
ConstantAccelDV()
function ConstantAccelDV (in d)
The average velocity is just the distance over the time, the peak velocity is twice that, and the delta-V is twice the peak.
Form
 DV = ConstantAccelDV( d )
Inputs
 d       (.)     Data structure
Outputs
 DV     (1,1)     Delta-V
References and(), and ConstantAccelDV().
Referenced by ConstantAccelDV().
DryMass()
function DryMass (in thrust, in d)
Form
 mass = DryMass( thrust, d )
Inputs
 thrust  (1,1)    Thrust, N
 d       (.)     Data structure
                    See Straight2DStructure
Outputs
 mass    (1,1)    Dry mass, kg
References DryMass(), EnginePower(), and Straight2DStructure().
Referenced by DryMass().
DVConstantThrust()
function DVConstantThrust (in thrust, in mD, in mF, in uE, in t)
Computes the velocity change with constant thrust as a function of exhaust velocity. This is an analytical solution. If the time vector is not entered, it consumes all of the fuel.
Type DVConstantThrust for a demo.
Form
 dV = DVConstantThrust( thrust, mD, mF, uE, t )
Inputs
 thrust  (1,1) Thrust level (N)
 mD      (1,1) Dry mass (kg)
 mF      (1,1) Fuel mass (kg)
 uE      (1,:) Exhaust velocity (km/s)
 t       (1,:) Time (s)
Outputs
 dV      (1,:) Velocity change (m/s)
References and(), Demo(), DVConstantThrust(), length(), Plot2D(), TimeLabl(), and vector().
Referenced by DVConstantThrust(), MaximumDV(), and PlanarHelioOptimal().
DVForTime()
function DVForTime (in power, in d)
Also calculates the maximum DV achievable for the given time.
Form
 [DV,limit] = DVForTime(power, d)
Inputs
 power      (1,1)     Power (W)
 d           (.)      Engine data struct
Outputs
 DV         (1,1)     Delta-V (km/s)
 limit      (1,1)     Limit of DV (km/s)
See also
: DVLimit
References and(), DVForTime(), DVLimit(), EngineThrust(), length(), Limit(), Plot2D(), and Straight2DStructure().
Referenced by DVForTime().
DVLimit()
function DVLimit (in tF, in uE, in sigma, in eta, in f)
This is an analytic solution for the maximum delta-V. It is independent of the distance traveled, depending only on the time, exhaust velocity, engine specific power and efficiency, and fuel tank fraction.
Form
 DVmax = DVLimit( d )
 DVmax = DVLimit( tF, uE, sigma, eta, f )
Inputs
 d           (.)      Engine data
Outputs
 DVmax      (1,1)     Maximum Delta-V (km/s)
References and(), DVLimit(), and Straight2DStructure().
Referenced by DVForTime(), and DVLimit().
EngineMass()
function EngineMass (in thrust, in d)
Form
 mass = EngineMass( thrust, d )
Inputs
 thrust  (1,1)    Thrust, N
 d       (.)     Data structure
                    See Straight2DStructure
Outputs
 mass    (1,1)    Engine mass, kg
References EngineMass(), EnginePower(), and Straight2DStructure().
Referenced by EngineMass(), InitialMass(), and TripDistance().
EnginePower()
function EnginePower (in thrust, in d)
The ideal electric propulsion equation is:
 P = T*uE/2/eta
Form
 power = EnginePower( thrust, d )
Inputs
 thrust   (1,:)   Thrust (N)
 d         (.)    Engine data structure
Outputs
 power    (1,:)   Power (W)
References EnginePower(), and Straight2DStructure().
Referenced by DryMass(), EngineMass(), and EnginePower().
EngineReport()
function EngineReport (in thrust, in d, in doPlot)
If there are no outputs the report is printed to the command line. If the thrust is empty, the payload-independent quantities will be reported - payload mass fraction, payload specific power, delta-V. If the thrust is zero, the value will be computed from the payload mass.
Form
 EngineReport( [], d )   % report
 EngineReport( 0, d )    % compute thrust for mP
 [s,dOut] = EngineReport( thrust, d, doPlot )
Inputs
 thrust     (1,1)     Thrust (N), may be empty
 d           (.)      Engine data struct
                       .mP  Payload mass (kg)
 doPlot     (1,1)     Display report even if there are outputs
Outputs
 s           {:}       Latex
 dOut        (.)       Updated data
                       .lambda  Payload ratio (mP/m0)
                       .alpha   Power ratio (mP/P)
                       .dV      Delta-V (km/s)
                       .thrust  Engine power (W)
                       .p       Engine power (W)
                       .m0      Initial mass (kg)
                       .mE      Engine mass (kg)
                       .mF      Fuel mass (kg)
                       .mD      Dry mass (kg)
                       .mDot    Mass flow rate (kg/s)
                       .tS      Switch time (s)
                       .vS      Switch velocity (km/s)
See also
: ComputePayloadFraction, EngineThrust, EnginePower,
TripDistance
Referenced by ComputeDuration(), ComputeDurationFraction(), and ComputeThrust().
EngineThrust()
function EngineThrust (in power, in d)
The ideal electric propulsion equation is:
 P = T*uE/2/eta
Form
 thrust = EngineThrust( power, d )
Inputs
 power    (1,:)   Power (W)
 d         (.)    Engine data structure
Outputs
 thrust   (1,:)   Thrust (N)
References EngineThrust(), and Straight2DStructure().
Referenced by ComputeDuration(), ComputeThrust(), DVForTime(), EngineThrust(), SolveFlybyPower(), and SolveSigma().
FlybyConstantThrust()
function FlybyConstantThrust (in thrust, in uE, in m0, in tF, in v0)
Analytical solution. This automatically computes the fuel mass. mD needs to include the propulsion system mass and the tankage mass.
Type FlybyConstantThrust for a demo including verification by numerical simulation.
Form
 [dF, vF, mFuel] = FlybyConstantThrust( thrust, d )
 [dF, vF, mFuel] = FlybyConstantThrust( thrust, uE, m0, tF, v0 )
Inputs
 thrust (1,:) Thrust (N)
 uE      (1,1) Exhaust velocity (km/s)
 m0      (1,1) Total mass (kg)
 tF      (1,1) Duration (s)
 v0      (1,1) Initial velocity (km/s) (optional, default 0)
Outputs
 dF      (1,1)  Final distance (km)
 vF      (1,:)  Final velocity (km/s)
 mFuel   (1,1) Required fuel (kg)
References and(), Constant(), Demo(), Flyby(), FlybyConstantThrust(), InitialMass(), isempty(), and SimulateFlyby().
Referenced by FlybyConstantThrust(), FlybyOptimal(), and ZeroPayloadFlyby().
FlybyOptimal()
function FlybyOptimal (in d, in maxIter, in iterDisp)
The power is calculated from the thrust and thrust efficiency. The engine mass is calculated from the specific power. Requires fmincon.
 P  = 0.5 T*uE/eta
 mE = P/sigma
The total mass is
 m0 = mP + (1 + f)*mF + mE
where mP is the mass of the payload, f is the fuel structural fraction, and mE is the mass of the engine.
Type FlybyOptimal for a demo to Alpha Centauri.
Form
 d = FlybyOptimal;   % data
 [uE, thrust, data] = FlybyOptimal( d, maxIter, iterDisp )
Inputs
 d        (.)   Data structure
                   See StraightLineConstantThrust with additional fields:
                 .eta          Thrust efficiency
                 .sigma        Specific power (W/kg)
                 .thrustRange
                 .uERange
 maxIter     (1,1)  Maximum number of iterations
 iterDisp
Outputs
 uE      (1,1) Exhaust velocity (km/s)
 thrust  (1,1) Thrust (N)
 data     (.)  Results data structure
               .p  (1,1) Power       (W)
               .mD (1,1) Dry mass   (kg)
               .mF (1,1) Fuel mass  (kg)
               .dV (1,1) Delta-V  (km/s)
               .dF (1,1) Final distance achieved (km)
               .vF (1,1) Final velocity achieved (km/s)
See also
StraightLineConstantThrust, SimulateFlyby
References and(), Demo(), FlybyConstantThrust(), FlybyOptimal(), isempty(), SimulateFlyby(), StraightLineConstantThrust(), StraightLineDataStructure(), StraightLineReport(), and UToMF().
Referenced by FlybyOptimal().
FlybyOptimalImpulse()
function FlybyOptimalImpulse (in d)
Form
[uEOpt,lambda] = FlybyOptimalImpulse(d)
Inputs
 d        (.)    Engine data structure
                    See Straight2DStructure
See also
ZeroPayloadFlyby, SolveLambdaFlyby
References Constant(), FlybyOptimalImpulse(), SolveLambdaFlyby(), Straight2DStructure(), and ZeroPayloadFlyby().
Referenced by FlybyOptimalImpulse().
FlybyReport()
function FlybyReport (in mP, in d, in doPlot)
Compute the payload fraction from the time, distance, and engine properties. Compute the power requirement from the payload mass. If there are no outputs the report is printed to the command line.
Form
 [s,dOut] = FlybyReport( mP, d, doPlot )
Inputs
 mP          (1)       Payload mass (kg)
 d           (.)       Structure, see Straight2DStructure
 doPlot      (1)       Flag to print a report despite outputs
Outputs
 s           {:}       Latex
 dOut        (.)       Updated data
                       .p    Engine power (W)
                       .m0   Initial mass (kg)
                       .mE   Engine mass (kg)
                       .mF   Fuel mass (kg)
                       .mD   Dry mass (kg)
                       .mDot Mass flow rate (kg/s)
See also
: SolveLambdaFlyby
References and(), and Straight2DStructure().
Referenced by SimulateFlyby().
FuelMass()
function FuelMass (in thrust, in d)
Form
 mass = FuelMass( thrust, d )
Inputs
 thrust     (1,1)     Thrust (N)
 d           (.)      Engine data
Outputs
 mass       (1,1)     Fuel mass
References and(), FuelMass(), and Straight2DStructure().
Referenced by FuelMass().
InitialMass()
function InitialMass (in thrust, in d)
The initial mass is composed of the payload, engine, fuel, and fuel tank. This depends on the mission duration and engine parameters.
Form
 mass = InitialMass( thrust, d )
Inputs
 thrust   (1,1)   Thrust (N)
 d         (.)    Engine data structure
Outputs
 mass     (1,1)   Initial mass (kg)
References and(), EngineMass(), InitialMass(), and Straight2DStructure().
Referenced by FlybyConstantThrust(), and InitialMass().
MassFuelElectricConstantPower()
function MassFuelElectricConstantPower (in d0)
Assumes constant power and constant acceleration. The spacecraft slows to zero velocity at its target. This uses a straight line model. This model assumes power is constant. This means exhaust velocity increases as the mass drops. There are two cases in the demo, one for a flyby mission and one for a rendezvous.
Form
 d = MassFuelElectricConstantPower(d0)
Inputs
 d0     (.)   Data structure
               See StraightLineDataStructure
                 .mis  ''  Mission type, 'flyby' or 'stop'
                 .p    (1) Power (W)
Outputs
 d      (.)   Data structure with updated fields
                 .a      (1) Acceleration (km/s2)
                 .mF     (1) Fuel mass (kg)
                 .thrust (1) Thrust (N)
                 .uE     (1) Exhaust velocity (N)
See also
MassFuelElectricConstantUE
References and(), Constant(), Demo(), MassFuelElectricConstantPower(), MassFuelElectricConstantUE(), StraightLineConstantAccel(), and StraightLineDataStructure().
Referenced by MassFuelElectricConstantPower(), MassFuelElectricConstantUE(), and StraightLineConstantAccel().
MassFuelElectricConstantThrust()
function MassFuelElectricConstantThrust (in d0)
Assumes constant exhaust velocity and constant thrust. Flyby and stopping are supported. This uses a straight line model.
Type MassFuelElectricConstantThrust for a demo.
Form
 d = MassFuelElectricConstantThrust( d0 )
Inputs
 d0     (.)   Data structure
               See StraightLineDataStructure
Outputs
 d      (.)   Data structure with updated fields
               See StraightLineDataStructure
See also
: ComputeThrust
References and(), ComputeThrust(), Constant(), Demo(), Flyby(), MassFuelElectricConstantThrust(), MassFuelElectricConstantUE(), SimulateStraightLineTrajectory(), and StraightLineDataStructure().
Referenced by MassFuelElectricConstantThrust().
MassFuelElectricConstantUE()
function MassFuelElectricConstantUE (in d)
Assumes constant acceleration with constant exhaust velocity. The power and thrust will decrease throughout the trajectory. Flyby and stopping are supported. This uses a straight line model.
Type MassFuelElectricConstantUE for a demo.
Form
 d = MassFuelElectricConstantUE;   % data structure
 dOut = MassFuelElectricConstantUE( d )
Inputs
 d      (.)   Data structure
               See StraightLineDataStructure
Outputs
 dOut    (.) Data structure with additions
             .a      (1,1) Acceleration (km/s^2)
             .mF    (1,1) Mass of fuel (kg)
             .p         (1,2) Initial/final Power (W)
             .thrust    (1,2) Initial/final Thrust (N)
             .uE     (1,2) Exhaust velocity (km/s)
             .mE        (1,1) Mass of engine (kg)
             .mD     (1,1) Dry mass (kg)
             .dV     (1,1) Velocity change (km/s)
See also
MassFuelElectricConstantPower
References and(), DefaultDataStructure(), Demo(), Flyby(), MassFuelElectricConstantPower(), MassFuelElectricConstantUE(), StraightLineConstantAccel(), and StraightLineDataStructure().
Referenced by MassFuelElectricConstantPower(), MassFuelElectricConstantThrust(), MassFuelElectricConstantUE(), and StraightLineConstantAccel().
MaximumDV()
function MaximumDV (in d, in Pmax)
Form
 DV = MaximumDV( d, Pmax )
Inputs
 d           (.)      Engine data struct
 Pmax       (1,1)     Power (W)
Outputs
 DV         (1,1)     Delta-V (km/s)
See also
: DVConstantThrust
References DVConstantThrust(), length(), MaximumDV(), Plot2D(), Straight2DStructure(), and zeros().
Referenced by MaximumDV().
OptimalCharacteristicVelocity()
function OptimalCharacteristicVelocity (in lambda, in doInverse)
This is the ratio of exhaust velocity to characteristic velocity, uE/Vc, to produce the given payload fraction. This is for a propulsion system characterized by a specific power in W/kg, exhaust velocity, and time of flight, so that Vc = sqrt(2*eta*P/m*tF) and the defining ratio is uE/Vc. This relation is independent of distance traveled, depending only on the rocket equation and the mass fractions. This formulation ignores the tankage mass fraction.
The rocket equation is expressed via mass fractions,
 DV = uE*log( (1 + mE/mF) / (mP/m0) )
where mE is the engine mass, mF is the propellant mass, and the payload fraction lambda is mP/m0. Noting that
 mE/mF = (uE/Vc)^2
 Vc = sqrt(2*eta*P/m*tF)
we have the result that
 exp(DV/uE) = (1 + (uE/Vc)^2)/(lambda + (uE/Vc)^2)
For every DV there is an optimum (uE/Vc) which maximizes lambda. This function saves the solution in persistent variables and interpolates the solution. It will generate the data on the first call of each MATLAB session.
Form
 cVc    = OptimalCharacteristicVelocity(lambda);
 lambda = OptimalCharacteristicVelocity(cVc,true);
 [cVc,lambda] = OptimalCharacteristicVelocity; % return internal data
Inputs
 lambda    (1,:)   Payload fraction, mP/m0
 doInverse (1,1)   Invert operation
Outputs
 cVc       (1,:)   Ratio, uE/Vc
Reference: Craig Williams, An Analytic Approximation to Very High Specific Impulse and Specific Power Interplanetary Space Mission Analysis, AAS Space Flight Mechanics Meeting, 1996
References abs(), and(), isempty(), length(), OptimalCharacteristicVelocity(), Plot2D(), and zeros().
Referenced by OptimalCharacteristicVelocity(), OptimalImpulseDuration(), and OptimalTripTime().
OptimalExhaustVelocity()
function OptimalExhaustVelocity (in d, in quiet)
This is the exhaust velocity that maximises the payload fraction for the requested mission (time and distance).
Type OptimalExhaustVelocity for a demo to Jupiter.
Form
 [uEOpt,lambda,eflag,alpha] = OptimalExhaustVelocity( d )
Inputs
 d        (.)     Engine data structure
Outputs
 uE       (1,1)   Exhaust velocity (km/s)
 lambda   (1,1)   Maximum payload fraction (kg/kg)
 eflag    (1,1)   Exit flag
 alpha    (1,1)   Payload/power ratio, mPL/P (kg/W)
See also
ComputePayloadFraction
References and(), ComputePayloadFraction(), Constant(), length(), OptimalExhaustVelocity(), Plot2D(), Straight2DStructure(), ZeroPayloadDistance(), and zeros().
Referenced by OptimalExhaustVelocity(), OptimalImpulseDuration(), and StraightLineOptimal().
OptimalImpulseDuration()
function OptimalImpulseDuration (in d, in lambda)
This is the exhaust velocity that minimizes the duration for the requested mission (payload fraction, distance and specific power).
Type OptimalExhaustVelocity for a demo to Jupiter.
Form
 [uEOpt,tF] = OptimalImpulseDuration( d, lambda )
Inputs
 d        (.)    Engine data structure
 lambda  (1,1)   Payload fraction
Outputs
 uE       (1,1)   Exhaust velocity (km/s)
 tF       (1,1)   Minimum duration (s)
See also
ComputePayloadFraction
References abs(), and(), ComputeDurationFraction(), ComputePayloadFraction(), Constant(), OptimalCharacteristicVelocity(), OptimalExhaustVelocity(), OptimalImpulseDuration(), and Straight2DStructure().
Referenced by OptimalImpulseDuration().
OptimalTripTime()
function OptimalTripTime (in d)
Computes optimal trip time for distance given engine specific power and specific impulse. This is a numerical process. This formulation neglects fuel tank fraction.
Form
 OptimalTripTime;  % demo
 [T,lambda,iter] = OptimalTripTime( d )
Inputs
 d       (.)      Straight 2D structure
                   .dF
                   .eta
                   .sigma
                   .uE
Outputs
 T       (1,1)    Time
 lambda  (1,1)    Payload ratio
 iter    (1,1)    Iterations
Reference: Craig Williams, An Analytic Approximation to Very High Specific Impulse and Specific Power Interplanetary Space Mission Analysis, AAS Space Flight Mechanics Meeting, 1996
References abs(), and(), ComputePayloadFraction(), Constant(), OptimalCharacteristicVelocity(), OptimalTripTime(), Straight2DStructure(), and TripTime().
Referenced by OptimalTripTime().
PlotPayloadFraction()
function PlotPayloadFraction (in d)
Plots the payload fraction and payload per unit power for a range of transfer times given the specific target distance.
Form
 PlotPayloadFraction( d )
Inputs
 d        (.)  Straight2D data structure
Outputs
 ts      (1,:) Range of times based on ZeroPayloadTime
 lambda  (1,:) Payload fraction (mP/m0)
 alpha   (1,:) Payload/power (kg/kW)
See also
: ComputePayloadFraction
References and(), ComputePayloadFraction(), Constant(), length(), PlotPayloadFraction(), Straight2DStructure(), TimeHistory(), ZeroPayloadTime(), and zeros().
Referenced by PlotPayloadFraction().
RectilinearMission()
function RectilinearMission (in thrust, in massDry, in uMax, in uE, in xF, in eff, in sigmaS, in sigmaP)
Has a built-in demo to Alpha Centauri. This function generates an acceleration, coast and decceleration profile for the mission. uMax is the velocity you want to reach. It will compute the distance traversed during acceleration and then the distance traveled during decceleration. If that is insufficient to reach the destination it will coast.
If the distance covered during acceleration and decceleration is longer than the distance to the target it will return an error as this would require a negative coast time (i.e. time travel.)
If you enter only 6 inputs it will use the massDry as the sum of the fuel tank mass, payload and power system mass. If you enter the last two the dry mass will be
 massDry + sigmaS*mF + sigmaP*power
Form
 [mF, tE, x, power, s] = RectilinearMission( thrust, massDry, uMax, uE, xF, eff, sigmaS, sigmaP )
Inputs
 thrust  (1,1)  Thrust (N)
 massDry  (1,1)  Dry mass (kg)
 uMax     (1,1)  Maximum velocity during the mission (m/s)
 uE       (1,1)  Exhaust velocity (m/s)
 xF       (1,1)  Final distance (m)
 eff      (1,1)  Efficiency
 sigmaS   (1,1)  Structural fraction
 sigmaP   (1,1)  Power fraction (kW/kg)
Outputs
 mF       (1,1)  [mF mA mD]
 tE       (1,3)  [acceleration time, coast time, mission duration]
 x        (1,:)  [xF xA xD]
 power    (1,1)  Power (W)
 s        {}     Results in a cell array
References and().
RectilinearMotion()
function RectilinearMotion (in thrust, in massDry, in massFuel, in uE, in t, in u0)
Uses an analytical solution.
Form
 [x, u, mF] = RectilinearMotion( thrust, massDry, massFuel, uE, t, u0 )
Inputs
 thrust  (1,1)  Thrust (N)
 massDry  (1,1)  Dry mass (kg)
 massFuel (1,1)  Mass of fuel (kg)
 uE       (1,1)  Exhaust velocity (m/s)
 t        (1,:)  Time vector (s)
 u0       (1,1)  Initial velocity (m/s)
Outputs
 x        (1,:)  Position vector (m)
 u        (1,:)  Velocity vector (m)
 mF       (1,:)  Fuel mass vector (m)
References abs(), Constant(), Demo(), isempty(), length(), Plot2D(), RectilinearMotion(), TimeLabl(), vector(), and zeros().
Referenced by RectilinearMotion().
RoundTripTime()
function RoundTripTime (in dF, in Isp, in thrust, in Mf)
Kammash's simple formula masks the engine specific power and fuel tank fraction, but shows the impact and tradeoff of specific impulse and thrust. The mass delivered is proportional to the thrust while the time is inversely related to the specific impulse.
 tauRT = 4*dF/(g*Isp) + 4*sqrt(dF*Mf/thrust)
Form
 RoundTripTime;  % demo
 [tauRT,mP] = RoundTripTime( dF, Isp, thrust, Mf )
Inputs
 dF        (1,1)   One-way distance (km)
 Isp       (1,1)   Specific impulse (s)
 thrust    (1,1)   Thrust (N)
 Mf        (1,1)   Final mass (kg)
Outputs
 tauRT     (1,:)   Round trip time, s
 mP        (1,:)   Propellant mass consumed, kg
Reference: T. Kammash, Ed., Fusion Energy in Space Propulsion, AIAA, Vol. 167, 1995. p. 4 and 69
SimulateFlyby()
function SimulateFlyby (in mD, in mF, in thrust, in uE, in tF, in n)
If there are no outputs the function creates a plot. Type SimulateFlyby for a demo including verification by an analytical solution.
Form
 [xP,t] = SimulateFlyby( data ), or
 [xP,t] = SimulateFlyby( mD, mF, thrust, uE, tF, n )
Inputs
 mD      (1,1) Dry mass (kg)
 mF      (1,1) Mass of fuel (kg)
 thrust (1,1) Thrust (N)
 uE      (1,1) Exhaust velocity (km/s)
 tF      (1,1) Final time (s)
 n       (1,1) Number of steps
Outputs
 xP      (3,n)  Simulation results [x;v;m]
 t       (1,n) Time vector
See also
FlybyReport
References Demo(), DistanceLabel(), FlybyReport(), isempty(), RHS(), RK4(), SimulateFlyby(), TimeLabl(), vector(), and zeros().
Referenced by FlybyConstantThrust(), FlybyOptimal(), and SimulateFlyby().
SimulateStraightLineTrajectory()
function SimulateStraightLineTrajectory (in d, in dontPlot)
Type SimulateStraightLineTrajectory for a demo.
Form
 [xP,t] = SimulateStraightLineTrajectory( d, dontPlot )
Inputs
 d         (.) Data structure
                  See StraightLineDataStructure
 dontPlot  (1) Flag to skip plot, default false
Outputs
 xP   (3,:)   State [distance;velocity;mass]
 t    (1,:)   Time (s)
References and(), Constant(), Demo(), DistanceLabel(), isempty(), RK4(), SimulateStraightLineTrajectory(), StraightLineConstantAccel(), StraightLineDataStructure(), TimeLabl(), and zeros().
Referenced by MassFuelElectricConstantThrust(), SimulateStraightLineTrajectory(), StraightLineConstantThrust(), and TripTime().
SLPLDataStructure()
function SLPLDataStructure (in mDry)
Each of dF, tF, Pj, and m0 can be found given the other quantities. A and tau are outputs of the calculation. The default struct contains a self-consistent demo.
Form
 d = SLPLDataStructure( mDry )
Inputs
 mDry (1)   Dry mass, optional, for scaling initial m0
Outputs
 d    (.)   Data structure
              .dF   (1,1) Final distance (km)
              .tF   (1,1) Final time (s)
              .Pj   (1,1) Jet power (eta*P, eta*sigma*mE) (W)
              .vF   (1,1) Final velocity (km/s)
              .mD   (1,1) Dry mass: Engine, payload, tanks, structure (kg)
              .m0   (1,1) Initial (wet) mass (kg)
              .A    (1,1) Acceleration scale parameter, (m/s^3)
              .tau  (1,1) Time between turnaround and tF (s)
See also
: SLPLSolver
References and(), Constant(), set(), SLPLDataStructure(), and SLPLSolver().
Referenced by SLPLDataStructure(), and SLPLSolver().
SLPLDeltaV()
function SLPLDeltaV (in A, in tau, in tF)
Power limit is the only constraint; thrust and exhaust velocity can go to zero or infinity. Uses Leitmann's 1961 result that the optimal acceleration profile is linear in time. The optimal can be either:
Constrained fuel and time, maximized distance OR
Constrained distance and time, minimized fuel OR
Constrained fuel and distance, minimized time.
The acceleration profile is:
 a(t) = A*(tF-tau-t)
a is acceleration, A is a constant, tau is a constant, t is mission time, tF is the final time.
Type SLPLDeltaV for a demo.
Form
 dV = SLPLDeltaV( A, tau, tF )
Inputs
 A       (1,:) Acceleration scale parameter, (m/s^3). Find this using
               another SLPLFind function, such as SLPLFindMass.
 tau     (1,:) Time between turnaround and tF (s). Find this using
               another SLPLFind function, such as SLPLFindMass.
 tF      (1,:) Final time (s)
Outputs
 dV      (1,:) Delta-V expended over the course of the mission (km/s)
Reference: Leitmann, George. "Minimum Transfer Time for a Power-Limited Rocket." Journal of Applied Mechanics 28, no. 2 (June 1, 1961): 171-78. https://doi.org/10.1115/1.3641648.
See also
: SLPLTrajectory
References and().
SLPLFindDistance()
function SLPLFindDistance (in tF, in Pj, in vF, in mDry, in m0)
This is analytic except in the case of a finite, nonzero vF, in which case fzero is used. Power limit is the only constraint; thrust and exhaust velocity can go to zero or infinity. Uses Leitmann's 1961 result that the optimal acceleration profile is linear in time. Optimal: Constrained fuel and time, maximized distance OR constrained distance and time, minimized fuel OR constrained constrained fuel and distance, minimized time.
 a(t) = A*(tF-tau-t)
a is acceleration, A is a constant, tau is a constant, t is mission time, tF is the final time. Type SLPLFindDistance for a demo.
Form
 [dF,A,tau] = SLPLFindDistance( tF, Pj, vF, mDry, m0 )
Inputs
 tF      (1,:) Final time (s)
 Pj      (1,:) Jet power (eta*P, eta*sigma*mE) (W)
 vF      (1,:) Final velocity (km/s).
               Rendezvous/insertion: vF = 0.
               Intercept/flyby: vF = [], unconstrained
 mDry    (1,:) Dry mass: Engine, payload, tanks, structure (kg)
 m0      (1,:) Initial (wet) mass (kg)
Outputs
 dF      (1,:) Final distance (km)
 A       (1,:) Acceleration scale parameter, (m/s^3)
 tau     (1,:) Time between turnaround and tF (s)
Reference: Leitmann, George. "Minimum Transfer Time for a Power-Limited Rocket." Journal of Applied Mechanics 28, no. 2 (June 1, 1961): 171-78. https://doi.org/10.1115/1.3641648.
See also
: SLPLTrajectory
References and().
Referenced by SLPLSolver().
SLPLFindDuration()
function SLPLFindDuration (in dF, in Pj, in vF, in mDry, in m0)
This is analytic except in the case of a finite, nonzero vF, in which case fzero is used. Power limit is the only constraint; thrust and exhaust velocity can go to zero or infinity. Uses Leitmann's 1961 result that the optimal acceleration profile is linear in time. The optimal can be either:
Constrained fuel and time, maximized distance OR
Constrained distance and time, minimized fuel OR
Constrained fuel and distance, minimized time.
The acceleration profile is:
 a(t) = A*(tF-tau-t)
a is acceleration, A is a constant, tau is a constant, t is mission time, tF is the final time.
Form
 [tF,A,tau] = SLPLFindDuration( xF, Pj, vF, mDry, m0 )
Inputs
 xF      (1,:) Final distance (km)
 Pj      (1,:) Jet power (eta*P, eta*sigma*mE) (W)
 vF      (1,:) Final velocity (km/s).
               Rendezvous/insertion: vF = 0.
               Intercept/flyby: vF = [], unconstrained
 mDry    (1,:) Dry mass: Engine, payload, tanks, structure (kg)
 m0      (1,:) Initial (wet) mass (kg)
Outputs
 tF      (1,:) Final time (s)
 A       (1,:) Acceleration scale parameter, (m/s^3)
 tau     (1,:) Time between turnaround and tF (s)
Reference: Leitmann, George. "Minimum Transfer Time for a Power-Limited Rocket." Journal of Applied Mechanics 28, no. 2 (June 1, 1961): 171-78. https://doi.org/10.1115/1.3641648.
See also
See also: SLPLTrajectory
References and().
Referenced by SLPLSolver().
SLPLFindMass()
function SLPLFindMass (in dF, in tF, in Pj, in vF, in mDry)
This is an analytic solution. Power limit is the only constraint; thrust and exhaust velocity can go to zero or infinity. Uses Leitmann's 1961 result that the optimal acceleration profile is linear in time. The optimal can be either:
Constrained fuel and time, maximized distance OR
Constrained distance and time, minimized fuel OR
Constrained fuel and distance, minimized time.
The acceleration profile is:
 a(t) = A*(tF-tau-t)
a is acceleration, A is a constant, tau is a constant, t is mission time, tF is the final time.
Type SLPLFindMass for a demo.
Form
 [m0,A,tau] = SLPLFindMass( dF, tF, Pj, vF, mDry )
Inputs
 dF      (1,:) Final distance (km)
 tF      (1,:) Final time (s)
 Pj      (1,:) Jet power (eta*P, eta*sigma*mE) (W)
 vF      (1,:) Final velocity (km/s).
               Rendezvous/insertion: vF = 0.
               Intercept/flyby: vF = [], unconstrained
 mDry    (1,:) Dry mass: Engine, payload, tanks, structure (kg)
Outputs
 m0      (1,:) Initial (wet) mass (kg)
 A       (1,:) Acceleration scale parameter, (m/s^3)
 tau     (1,:) Time between turnaround and tF (s)
Reference: Leitmann, George. "Minimum Transfer Time for a Power-Limited Rocket." Journal of Applied Mechanics 28, no. 2 (June 1, 1961): 171-78. https://doi.org/10.1115/1.3641648.
See also
: SLPLTrajectory
References and().
Referenced by SLPLSolver().
SLPLFindPower()
function SLPLFindPower (in dF, in tF, in vF, in mDry, in m0)
This is an analytic solution for the rocket jet power. Power limit is the only constraint; thrust and exhaust velocity can go to zero or infinity. Uses Leitmann's 1961 result that the optimal acceleration profile is linear in time. The optimal can be either:
Constrained fuel and time, maximized distance OR
Constrained distance and time, minimized fuel OR
Constrained fuel and distance, minimized time.
The acceleration profile is:
 a(t) = A*(tF-tau-t)
a is acceleration, A is a constant, tau is a constant, t is mission time, tF is the final time.
Type SLPLFindPower for a demo.
Form
 [Pj,A,tau] = SLPLFindPower( xF, tF, vF, mDry, m0 )
Inputs
 xF      (1,:) Final distance (km)
 tF      (1,:) Final time (s)
 vF      (1,:) Final velocity (km/s).
               Rendezvous/insertion: vF = 0.
               Intercept/flyby: vF = [], unconstrained
 mDry    (1,:) Dry mass: Engine, payload, tanks, structure (kg)
 m0      (1,:) Initial (wet) mass (kg)
Outputs
 Pj      (1,:) Jet power (eta*P, eta*sigma*mE) (W)
 A       (1,:) Acceleration scale parameter, (m/s^3)
 tau     (1,:) Time between turnaround and tF (s)
Reference: Leitmann, George. "Minimum Transfer Time for a Power-Limited Rocket." Journal of Applied Mechanics 28, no. 2 (June 1, 1961): 171-78. https://doi.org/10.1115/1.3641648.
See also
: SLPLTrajectory
References and().
Referenced by SLPLSolver().
SLPLReport()
function SLPLReport (in Pj, in m0, in tF, in A, in tau, in sigma, in f, in doPlot)
tau is the time in the second half of the trajectory, between the turnaround and tF. It is zero for a flyby, tF/2 for a rendezvous, and a value inbetween gives a non-zero final velocity.
Form
 [s,dOut] = SLPLReport( Pj, m0, tF, A, tau )
 [s,dOut] = SLPLReport( Pj, m0, tF, A, tau, sigma, f, doPlot )
Inputs
 Pj       (1,1)    Jet power (eta*P, eta*sigma*mE) (W)
 m0       (1,1)    Initial (wet) mass (kg)
 tF       (1,1)    Final time (s)
 A        (1,1)    Acceleration scale parameter, (m/s^3)
 tau      (1,1)    Time between turnaround and tF (s)
 sigma    (1,1)    Specific power (W/kg)
 f        (1,1)    Tank mass fraction, mTank = f*mF
 doPlot   (1,1)    Always display output
Outputs
 s         {}      Latex report
 dOut     (.)      Output data structure
References and().
SLPLSolver()
function SLPLSolver (in d, in doPlot)
One of m0, tF, dF, or Pj fields may be empty. This field will be solved for using the remaining problem parameters. The solution assumes the optimal power-limited rocket trajectory which is a linear acceleration profile.
When solving for mass or power, the solution is analytical. When solving for distance or time, the solution is found numerically using fzero.
Type SLPLSolver for a demo.
Form
 data = SLPLSolver( d, doPlot )
Inputs
 d       (.)   Data structure
                One of .m0, .tF, .dF or .Pj may be empty
 doPlot  (1,1) If true, plot
Outputs
 data    (.) Data structure
Reference: Leitmann, George. "Minimum Transfer Time for a Power-Limited Rocket." Journal of Applied Mechanics 28, no. 2 (June 1, 1961): 171-78. https://doi.org/10.1115/1.3641648.
See also
: SLPLDataStructure, SLPLTrajectory
References Constant(), isempty(), Plot2D(), SLPLDataStructure(), SLPLFindDistance(), SLPLFindDuration(), SLPLFindMass(), SLPLFindPower(), SLPLSolver(), SLPLTrajectory(), and TimeLabl().
Referenced by SLPLDataStructure(), and SLPLSolver().
SLPLTrajectory()
function SLPLTrajectory (in A, in tau, in Pj, in m0, in tF, in t, in doPlot)
If there are no outputs the function produces two plots. Power limit is the only constraint; thrust and exhaust velocity can go to zero or infinity. Uses Leitmann's 1961 result that the optimal acceleration profile is linear in time. The optimal can be either:
Constrained fuel and time, maximized distance OR
Constrained distance and time, minimized fuel OR
Constrained fuel and distance, minimized time.
The acceleration profile is:
 a(t) = A*(tF-tau-t)
a is acceleration, A is a constant, tau is a constant, t is mission time, tF is the final time.
Type SLPLTrajectory for a demo.
Form
 SLPLTrajectory( d ); % create plots
 [t,d,v,a,m,uE,T] = SLPLTrajectory( d );
 [t,d,v,a,m,uE,T] = SLPLTrajectory( A, tau, Pj, m0, tF, t, doPlot )
Inputs
 A       (1,1) Acceleration scale parameter, (m/s^3). Find this using
               the SLPLSolver function.
 tau     (1,1) Time between turnaround and tF (s).
 Pj      (1,1) Jet power (eta*P, eta*sigma*mE) (W)
 m0      (1,1) Initial (wet) mass (kg)
 tF      (1,1) Final time (s)
 t       (1,:) Time vector (optional) (s)
 doPlot   (1)  Flag to create plots
Outputs
 t       (1,:) Time vector (same as argument, if given) (s)
 d       (1,:) Distance at t (km)
 v       (1,:) Velocity at t (km/s)
 a       (1,:) Acceleration at t (m/s^2)
 m       (1,:) Mass at t (kg)
 uE      (1,:) Exhaust velocity at t (km/s)
 T       (1,:) Thrust at t, (N)
Reference: Leitmann, George. "Minimum Transfer Time for a Power-Limited Rocket." Journal of Applied Mechanics 28, no. 2 (June 1, 1961): 171-78. https://doi.org/10.1115/1.3641648.
References and(), and Trajectory().
Referenced by SLPLSolver().
SolveFlybyPower()
function SolveFlybyPower (in d, in dF, in tau)
Solve for the payload and power fractions given the engine parameters. Compute the engine power and initial mass from the payload. Enter dF or tau to override the value stored in d.
Form
 [P,m0] = SolveFlybyPower( d, dF, tau )
Inputs
 d     (.)    Engine data structure
 dF   (1,1)   Distance (km), optional
 tau  (1,1)   Transit time (s), optional
Outputs
 P    (1,1)    Power (MW)
 m0   (1,1)    Initial mass (kg)
See also
: Straight2DStructure, ZeroPayloadFlyby, SolveLambdaFlyby
References and(), Constant(), EngineThrust(), isempty(), Plot2D(), RHS(), SolveFlybyPower(), SolveLambdaFlyby(), Straight2DStructure(), and ZeroPayloadFlyby().
Referenced by SolveFlybyPower().
SolveLambdaFlyby()
function SolveLambdaFlyby (in d)
For a flyby, this is a simple bounded problem using the distance equation. From here, the power or payload mass can each be found from the other, and they are proportional to each other.
The distance must be less than the "zero payload distance", and the payload must be greater than zero.
Form
 [lambda,alpha,gamma] = SolveLambdaFlyby( d )
Inputs
 d        (.)    Engine data structure
                    See Straight2DStructure
Outputs
 lambda   (1,1) Payload fraction, mPL/m0
 alpha    (1,1) Payload/power ratio, mPL/P (kg/W)
 gamma    (1,1) Ratio, mDot/m0
References abs(), and(), Constant(), SolveLambdaFlyby(), Straight2DStructure(), and ZeroPayloadFlyby().
Referenced by FlybyOptimalImpulse(), SolveFlybyPower(), and SolveLambdaFlyby().
SolveSigma()
function SolveSigma (in power, in d)
The demo shows Jupiter, Pluto, and 125 AU missions for 1 to 10 MW. There may be no solution for some combinations of distance and time.
Form
 [sigma,eFlag] = SolveSigma( power, d )
Inputs
 power   (1,1)   Power (W)
 d        (.)    Engine data structure
Outputs
 sigma   (1,:)   Specific power (W/kg)
 eFlag   (1,1)   Flag from fzero
References and(), Constant(), EngineThrust(), length(), Plot2D(), SolveSigma(), Straight2DStructure(), and TripDistance().
Referenced by SolveSigma().
Straight2DStructure()
function Straight2DStructure ()
Form
 d = Straight2DStructure
Outputs
 g  (.)   Data structure
           .tF    (1,1) Final time                (s)
           .dF    (1,1) Final distance            (km)
           .f     (1,1) Fuel structural fraction  (kg/kg)
           .uE    (1,1) Exhaust velocity          (km/s)
           .sigma (1,1) Engine specific power     (W/kg)
           .eta   (1,1) Efficiency, power to thrust
           .mP   (1,1) Payload mass               (kg)
           .mE   (1,1) Engine mass                (kg)
References Constant(), and Straight2DStructure().
Referenced by ComputeDuration(), ComputeDurationFraction(), ComputePayload(), ComputePayloadFraction(), ComputeThrust(), DryMass(), DVForTime(), DVLimit(), EngineMass(), EnginePower(), EngineThrust(), FlybyOptimalImpulse(), FlybyReport(), FuelMass(), InitialMass(), MaximumDV(), OptimalExhaustVelocity(), OptimalImpulseDuration(), OptimalTripTime(), PlotPayloadFraction(), SolveFlybyPower(), SolveLambdaFlyby(), SolveSigma(), Straight2DStructure(), StraightLineOptimal(), TripDistance(), TripTime(), and ZeroPayloadFlyby().
StraightLineConstantAccel()
function StraightLineConstantAccel (in d, in n)
Assumes constant acceleration. Flyby and stopping are supported. This uses a straight line model. If d.p is entered (and constant), d.uE is not used. Otherwise, power is computed from uE. Use either MassFuelElectricConstantUE or MassFuelElectricConstantPower to compute the fuel mass.
Type StraightLineConstantAccel for a demo.
Form
 d = StraightLineConstantAccel;  % data structure, constant uE
 [mF,xP,t] = StraightLineConstantAccel(d,n)
Inputs
 d  (.)   Data structure
            See StraightLineDataStructure
            .a Acceleration
 n   (1,1) Number of steps
Outputs
 mF  (1,1) Mass of fuel (kg)
 xP  (3,:) State [x;v;mF]
 t   (1,:) Time (s)
See also
MassFuelElectricConstantUE, MassFuelElectricConstantPower
References abs(), and(), Constant(), Demo(), Flyby(), isempty(), MassFuelElectricConstantPower(), MassFuelElectricConstantUE(), RHS(), RK4(), StraightLineConstantAccel(), StraightLineDataStructure(), TimeLabl(), and zeros().
Referenced by MassFuelElectricConstantPower(), MassFuelElectricConstantUE(), SimulateStraightLineTrajectory(), and StraightLineConstantAccel().
StraightLineConstantThrust()
function StraightLineConstantThrust (in d0)
Compute the switch time as a function of thrust, exhaust velocity, initial mass, and flight time. Can account for an initial velocity v0.
Type StraightLineConstantThrust for a demo.
Form
 [d,dF] = StraightLineConstantThrust( d0 )
Inputs
 d0     (.)   Data structure
               See StraightLineDataStructure
                 .thrust (1,1) Thrust, N
                 .uE     (1,1) Exhaust velocity, km/s
                 .v0     (1,1) Initial velocity, km/s
                 .sigma  (1,1) Engine specific power, W/kg
                 .eta    (1,1) Efficiency, power to thrust
  if engine mass mE is empty, it will be computed.
Outputs
 d      (.)   Data structure with updated fields
               .p   Power
               .mF  Fuel mass
               .mE  Engine mass
               .mD  Dry mass
               .m0  Initial mass
               .tS  Switch time
               .vS  Switch velocity
               .dF  Final distance
 See StraightLineDataStructure
 dF     (1,1)  Distance achieved
References and(), Constant(), Demo(), isempty(), SimulateStraightLineTrajectory(), StraightLineConstantThrust(), StraightLineDataStructure(), and SwitchTime().
Referenced by FlybyOptimal(), and StraightLineConstantThrust().
StraightLineDataStructure()
function StraightLineDataStructure (in d)
If you enter d it will return a latex formatted version
Form
 d = StraightLineDataStructure
 l = StraightLineDataStructure( d )
Inputs
 d  (.)   Data structure
Outputs
 d  (.)   Data structure
         .dF         (1,1) Final distance (km)
         .tF         (1,1) Final time (s)
         .eta        (1,1) Thrust efficiency
         .sigma      (1,1) Specific power (W/kg)
         .uE         (1,1) Constant exhaust velocity (km/s)
         .f          (1,1) Tank fraction (kg/kg)
         .mP         (1,1) Payload mass (kg)
         .mE         (1,1) Engine mass (kg)
         .mF         (1,1) Fuel mass (kg)
         .mD         (1,1) Dry mass (kg)
         .m0         (1,1) Initial mass (kg)
         .thrust     (1,1) Thrust (N)
         .accel      (1,1) Accel (km/s^2)
        .tS         (1,1) Thrust sign switch time  (s)
         .v0         (1,1) Initial velocity (km/s)
         .vS         (1,1) Switch velocity (km/s)
         .dV         (1,1) Total delta velocity (km/s)
         .p          (1,1) Power (W)
         .useAccel   (1,1) If true is acceleration for simulations
         .constPower (1,1) If true hold power constant
 or
 l  {:,3} Latex formatted data structure
References Accel(), Constant(), and StraightLineDataStructure().
Referenced by FlybyOptimal(), MassFuelElectricConstantPower(), MassFuelElectricConstantThrust(), MassFuelElectricConstantUE(), SimulateStraightLineTrajectory(), StraightLineConstantAccel(), StraightLineConstantThrust(), and StraightLineDataStructure().
StraightLineOptimal()
function StraightLineOptimal (in d, in doPlot)
Computes the exhaust velocity that optimizes the payload fraction for the desired mission distance and time. The power is calculated from the thrust and thrust efficiency. The engine mass is calculated from the specific power.
 P  = 0.5 T*uE/eta
 mE = P/sigma
The total mass is
 m0 = mP + (1 + f)*mF + mE
where mP is the mass of the payload, f is the fuel structural fraction, and mE is the mass of the engine. If the time is not sufficient given the other engine parameters the function with throw an error.
Type StraightLineOptimal for a demo to Alpha Centauri
Form
 [uE, thrust, data] = StraightLineOptimal( d, doPlot )
Inputs
 d        (.)   Data structure with dF and tF
 doPlot  (1,1)  Display report
Outputs
 uE      (1,1) Exhaust velocity (km/s)
 thrust  (1,1) Thrust (N)
 data     (.)  Results data structure
               .p  (1,1) Power       (W)
               .mD (1,1) Dry mass   (kg)
               .mF (1,1) Fuel mass  (kg)
               .dV (1,1) Delta-V  (km/s)
               .dF (1,1) Final distance achieved (km)
               .vF (1,1) Final velocity achieved (km/s)
See also
OptimalExhaustVelocity, ZeroPayloadTime, ComputeThrust
References and(), ComputeThrust(), Demo(), OptimalExhaustVelocity(), Straight2DStructure(), StraightLineOptimal(), and ZeroPayloadTime().
Referenced by StraightLineOptimal().
StraightLineReport()
function StraightLineReport (in data)
Form
 s = StraightLineReport( data )
Inputs
 d           (.)      Data structure
Outputs
 s          {:,:} or (:,:) Cell array of latex table entries
Referenced by FlybyOptimal().
SwitchTime()
function SwitchTime (in thrust, in uE, in tF, in m0)
This ensures the the final velocity is zero. It assumes that the thrust and exhaust velocity are constant.
Type SwitchTime for a demo.
Form
 tS = SwitchTime( thrust, uE, tF, m0 )
Inputs
 thrust (1,1) Thrust (N)
 uE      (1,1) Exhaust velocity (km/s)
 tF      (1,1) Duration (s)
 m0      (1,1) Initial mass (kg)
Outputs
 tS      (1,1)  Switch time (s)
References and(), Demo(), and SwitchTime().
Referenced by StraightLineConstantThrust(), and SwitchTime().
ThrustElectric()
function ThrustElectric (in tM, in d, in uE, in sigma, in f, in eta, in mP)
Assumes constant acceleration to the midpoint then constant deceleration. It automatically limits results to sigma's that will work. Type ThrustElectric for a demo for an Alpha Centauri mission.
Form
 [thrust, sigma, mE, mF, power, dV] = ThrustElectric( tM, d, uE, sigma, f, eta, mP )
Inputs
 tM      (1,1) Mission time (sec)
 d       (1,1) Distance (km)
 uE      (1,1) Exhaust velocity (km/s)
 sigma   (1,:) Specific power (W/kg)
 f       (1,1) Structural fraction (kg/kg fuel)
 eta     (1,1) Engine efficiency
 mP      (1,1) Mass of spacecraft not including fuel, fuel tankage or engine
Outputs
 thrust  (1,:) Maximum thrust (N)
 sigma   (1,:) Specific power (W/kg)
 mE      (1,:) Engine mass (kg)
 mF      (1,:) Fuel mass (kg)
 vMax    (1,1) Maximum velocity
 power   (1,:) Engine power (W)
 dV      (1,1) Delta V (km/s)
References and().
Referenced by PlanarHelioOptimal().
TimeToVelocity()
function TimeToVelocity (in thrust, in massDry, in massFuel, in uE, in u, in u0)
Form
 t = TimeToVelocity( thrust, massDry, massFuel, uE, u, u0 )
Inputs
 thrust  (1,1)  Thrust (N)
 massDry  (1,1)  Dry mass (kg)
 massFuel (1,1)  Fuel mass (kg)
 uE       (1,1)  Exhaust velocity (m/s)
 u        (1,1)  Final velocity (m/s)
 u0       (1,1)  Initial velocity (m/s), defaults to 0
Outputs
 t           (1,1)  Time (s)
References abs(), Constant(), Demo(), TimeLabl(), TimeToVelocity(), and VelocityLabel().
Referenced by TimeToVelocity().
TripDistance()
function TripDistance (in thrust, in d)
This is an analytic solution.
Form
 [dF,v,vS,tS] = TripDistance( thrust, d )
Inputs
 thrust     (1,1)     Thrust (N)
 d           (.)      Engine data struct
Outputs
 dF         (1,1)     Distance
 v          (1,1)     Final velocity
 vS         (1,1)     Switch velocity
 tS         (1,1)     Switch time
References Constant(), Demo(), EngineMass(), isempty(), Straight2DStructure(), and TripDistance().
Referenced by ComputeThrust(), SolveSigma(), and TripDistance().
TripTime()
function TripTime (in m0, in d, in doPlot)
Note that the trip time is fixed from the resulting payload fraction, and the amount of payload will then determine the engine thrust required. In order to first determine the relationship between payload fraction and time given the distance and remaining parameters, see ComputePayloadFraction.
Form
 [tF,thrust,data] = TripTime( m0, d )
Inputs
 m0      (1,1)    Mission wet mass
 d       (.)     Data structure
                    See Straight2DStructure
                    .mP   (1,1) Payload, kg
                    .dF   (1,1) Distance, km
 doPlot  (1,1)    Display engine report
Outputs
 tau     (1,:)   Trip time (s)
 thrust  (1,1)   Engine thrust (N)
 data     (.)    Engine report
See also
: ComputeThrust, ComputePayloadFraction
References and(), ComputePayloadFraction(), ComputeThrust(), Constant(), Demo(), SimulateStraightLineTrajectory(), Straight2DStructure(), TripTime(), and ZeroPayloadTime().
Referenced by OptimalTripTime(), and TripTime().
UToMF()
function UToMF (in thrust, in uE, in d)
Form
 [m0, mF, mE, p] = UToMF( thrust, uE, d )
Inputs
 thrust  (1,1) Thrust (N)
 uE      (1,1) Exhaust velocity (km/s)
 d       (.)   Data structure
               .tF     (1,1) Duration (s)
               .eta    (1,1) Power fraction converted to thrust
               .mP     (1,1) Payload mass (kg)
               .sigma  (1,1) Specific power (W/kg)
               .f      (1,1) Fuel tank fraction
Outputs
 m0      (1,1) Initial mass (kg)
 mF      (1,1) Fuel mass (kg)
 mE      (1,1) Engine mass (kg)
 p       (1,1)  Power (W)
References and(), and UToMF().
Referenced by FlybyOptimal(), PlanarHelioOptimal(), and UToMF().
ZeroPayloadDistance()
function ZeroPayloadDistance (in tF, in uE, in sigma, in eta, in f)
This is an analytic solution to compute the maximum distance achievable, given the engine parameters. Its equivalent to just getting the engine to that distance, without any additional payload.
The built-in demo shows the maximum distance for several values of exhaust velocity over 10 years.
Form
 dMax = ZeroPayloadDistance( d )      % struct input
 dMax = ZeroPayloadDistance( tF, uE, sigma, eta, f )
Inputs
 d           (.)      Engine data struct
Outputs
 dMax       (1,1)     Distance
See also
: ZeroPayloadTime
References Constant(), length(), Plot2D(), ZeroPayloadDistance(), and ZeroPayloadTime().
Referenced by ComputePayloadFraction(), OptimalExhaustVelocity(), and ZeroPayloadDistance().
ZeroPayloadFlyby()
function ZeroPayloadFlyby (in d, in tau)
The zero payload flyby distance is independent of power, depending only on time and the engine parameters. If requested, the zero payload time is computed numerically to achieve d.dF.
Form
 dZero = ZeroPayloadFlyby( d, tau )
Inputs
 d         (.)     Straight 2D structure
                    .dF  Distance (km)
                    .tF  Time (s)
 tau      (1,1)    Duration (s), optional, overrides d.tF
Outputs
 dZero    (1,1)    Distance (km)
 tZero    (1,1)    Time (s)
References and(), Constant(), FlybyConstantThrust(), Straight2DStructure(), and ZeroPayloadFlyby().
Referenced by FlybyOptimalImpulse(), SolveFlybyPower(), SolveLambdaFlyby(), and ZeroPayloadFlyby().
ZeroPayloadTime()
function ZeroPayloadTime (in dF, in uE, in sigma, in eta, in f)
This is a numerical routine that uses fzero to compute the time corresponding to the requested distance, given the engine parameters.
The built-in demo shows several values of uE.
Form
 tF = ZeroPayloadTime( d )      % struct input
 tF = ZeroPayloadTime( dF, uE, sigma, eta, f )
Inputs
 d           (.)      Engine data struct
Outputs
 tF         (1,1)     Trip time (s)
References Constant(), length(), Plot2D(), and ZeroPayloadTime().
Referenced by PlotPayloadFraction(), StraightLineOptimal(), TripTime(), ZeroPayloadDistance(), and ZeroPayloadTime().