PSS MATLAB Toolboxes: SAAD Functions
SAAD Functions
SAAD Module
The SAAD module functions.
Directories
directory GUI
directory SAADData
directory SAAttDet
Description
Functions
function ADComp (in el, in jDEpoch, in tLE1, in tTE1, in tLE2, in tTE2, in sA, in jD, in spinRate, in cant, in dihedral, in rA, in dec)
Compare attitude data with a computed solution.
function ADCull (in el, in jDEpoch, in tLE1, in tTE1, in tLE2, in tTE2, in sA, in jD, in spinRate, in cant, in dihedral, in rA, in dec, in dev)
Eliminate HSA measurements that do not fit the predicted curves.
function AddBias (in varargin)
Adds biases to the non-zero elements of measurement vectors.
function ADGen (in el, in uSun, in uSpin, in spinRate, in mA, in hSADelay, in hSAQuant, in)
Generate horizon sensor and sun sensor data.
function ADPartls (in el, in jDEpoch, in jD, in ignoredArg, in cant, in ignoredArg, in rA, in dec)
Compute the measurement partials.
function BObjIntF (in u, in uBO, in rhoBO, in cant, in fOV)
Determines if a bright object will interfere with a sensor scan.
function BShuster (in usun, in unadir, in sa, in tle, in tte, in cant, in eradius, in spinrate, in)
Schuster's batch attitude determination method.
function BShuster2 (in usun, in unadir, in sa, in tle_cw, in tte_da, in cant, in eradius, in spinrate, in)
Schuster's batch attitude determination method.
function ConeInt (in usun, in unadir, in sa, in tle, in tte, in cant, in eradius, in spinrate, in threshold)
Cone intercept method.
function ConeInt2 (in usun, in unadir, in sa, in tle_cw, in tte, in cant, in eradius, in spinrate, in threshold, in type)
Cone intercept attitude determination method.
function ConjGrad (in F, in CF, in S0, in xA, in kX, in tol, in prog, in sd)
Solves the least squares problem.
function ConvertHSA (in action, in varargin)
Convert HSA times to dihedral angles and chordwidths.
function CostF (in alpha, in x0, in d, in S0, in xA)
Finds the cost function.
function CostNM (in x, in kX, in S0, in xA, in lX)
Cost functional for the Nelder-Meade algorithm.
function CostNMTE (in x, in kX, in S0, in xA, in lX, in type1, in type2)
Nelder-Meade cost function using trailing edge angles.
function CwValid (in ra, in dec, in er, in g, in ue)
Checks for valid HSA chordwiths.
function DataWindow ()
Brings up the SAAD GUI data window.
function DHArcDX (in ra, in dec, in u)
Computes the Jacobian for an arc measurement.
function DHArcDXi (in x, in u)
Interface to DHArcDX.
function DHCWDX (in ra, in dec, in cg, in sg, in er, in ue)
Computes the derivative of the chordwidth.
function DHCWDXi (in x, in u)
Interface to dhcwdx.
function DHDADX (in ra, in dec, in us, in ue)
Derivatives of the dihedral angle.
function DHDADXi (in x, in u)
Interface to DHDADX.
function DiffCorr (in f, in S0, in xA, in kx, in tol, in tolSVD, in ignoredArg)
Solves the least squares problem with SVD.
function DSunCone (in uSun, in rAI, in decI, in beta)
Possible right ascensions and declinations given a sun angle.
function DWInputs (in action, in varargin)
Brings up a window for entering the desired data information.
function FX (in x)
Find vectors.
function FXNM (in x)
Find vectors.
function FXNMTE (in x, in type1, in type2)
Find vectors using trailing edge angles.
function HArc (in ua, in u)
Computes an arc measurement.
function HArci (in x, in u)
Interface to HArc.
function HCw (in ua, in e, in g, in ue)
Computes the chordwidth.
function HCw2R (in ua, in g, in e1, in e2, in ue1, in ue2)
Chordwidth with different nadir vectors.
function HCwi (in x, in u)
Interface to HCw.
function HDA (in uA, in uS, in uE)
Computes the dihedral angle for a spinning spacecraft.
function HDAi (in x, in u)
Interface to HDA.
function HLE (in uA, in uS, in uE, in earthRadius, in cant)
Computes the leading edge dihedral angle for a spinning spacecraft.
function HTE (in uA, in uS, in uE, in earthRadius, in cant)
Computes the trailing edge dihedral angle for a spinning spacecraft.
function KFExItMu (in hname, in Hname, in H, in Hindex, in R, in z, in x, in P, in f, in nits, in u)
One step of the extended iterated Kalman Filter measurement update.
function KFSAAD (in x0, in P0, in Rcw, in Rda, in Rsb, in cw1, in cw2, in da1, in da2, in sb, in ue, in us, in)
Extended Iterated Kalman Filter (EIKF) for SAAD.
function LoadAtt (in file, in path)
Template to read in attitude data from a formatted text file.
function LoadSAADData (in files)
Default function to load attitude data from formatted text files.
function NadGen (in el, in jDEpoch, in jD)
Generated Earth and sun data for date.
function Outliers (in z, in ra, in dec, in bias, in type, in range, in u1, in u2, in er, in cant, in erbias)
Outputs the set of acceptable measurements.
function PlotPred (in sensorInputs, in spinRate, in)
Computes predicted measurements, plot with actual measurements.
function QuadCost (in fX, in x0, in xA, in d, in S0, in aMin, in aMax)
Finds the alpha that minimizes the quadratic cost functional J.
function Radiance (in lat, in dateTime, in year)
Computes the Earth's peak radiance.
function ResidStat (in dAngles, in cWidths, in sunAngles, in kV, in hSAData)
Computes and displays residual statistics.
function SAADFile (in action, in varargin)
Data file functions used by SAAD GUI.
function SAADHelp (in topic)
Brings up a text window explaining the given topic.
function SAADMain (in action, in state)
Brings up the main SAAD GUI window - the SAAD Control Center.
function SAADMenu (in action, in varargin)
Menu tools used by SAAD GUI.
function SAADTool (in action, in varargin)
Window management tools used by SAAD GUI.
function SFShustr (in usun, in unadir, in sa, in tle, in tte, in cant, in eradius, in)
Schuster's single frame method.
function SFShustr2 (in usun, in unadir, in sa, in tle_cw, in tte_da, in cant, in eradius, in)
Schuster's single frame method.
function SolutionWindow ()
Brings up the SAAD GUI solution window.
function SunCone (in uSun, in rAI, in decI, in beta)
Compute possible right ascensions and declinations given a sun angle.
function SunData (in usun, in uspin, in quant, in qtype, in onesigma, in bias)
Computes the sun sensor data for a spinning spacecraft.
function ZCull (in ra, in dec, in g, in ue, in us, in er, in der, in zh, in Wh)
Cull horizon sensor measurements.
Function Documentation
ADComp()
function ADComp (in el, in jDEpoch, in tLE1, in tTE1, in tLE2, in tTE2, in sA, in jD, in spinRate, in cant, in dihedral, in rA, in dec)
Form
 ADComp( el, jDEpoch, tLE1, tTE1, tLE2, tTE2, sA, jD, spinRate, cant, dihedral, rA, dec )
Inputs
 el                     Keplerian elements
 jDEpoch                Epoch for the measurements
 tLE1                   Leading edge time HSA 1
 tTE1                   Trailing edge time HSA 1
 tLE2                   Leading edge time HSA 2
 tTE2                   Trailing edge time HSA 2
 sA                     Sun angles
 jD                     Julian dates corresponding to the above
 spinRate               Spin rate (rad/sec)
 cant           (2)     Cants
 dihedral       (2)     Dihedral angles
 rA                     Estimated right ascension
 dec                    Estimated declination
Outputs
 None
References Dot(), HSAData(), Measurements(), NadGen(), NewFig(), RaDec2U(), XLabelS(), and YLabelS().
ADCull()
function ADCull (in el, in jDEpoch, in tLE1, in tTE1, in tLE2, in tTE2, in sA, in jD, in spinRate, in cant, in dihedral, in rA, in dec, in dev)
You need a rough attitude estimate to use this routine effectively. This routine uses the leading edge data as the reference. dev is the fractional deviation from the estimated data.
Form
 [tLE1Cull, tTE1Cull, tLE2Cull, tTE2Cull] =
 ADCull( el, jDEpoch, tLE1, tTE1, tLE2, tTE2, sA, jD, spinRate,
 cant, dihedral, rA, dec, dev )
Inputs
 el                     Keplerian elements
 jDEpoch                Epoch for the measurements
 tLE1           (n,1)   Leading edge time HSA 1
 tTE1           (n,1)   Trailing edge time HSA 1
 tLE2           (n,1)   Leading edge time HSA 2
 tTE2           (n,1)   Trailing edge time HSA 2
 sA                     Sun angles (rad)
 jD                     Julian dates corresponding to the above
 spinRate               Spin rate (rad/sec)
 cant           (2)     Cants
 dihedral       (2)     Dihedral angles
 rA                     Estimated right ascension
 dec                    Estimated declination
 dev                    Allowable fractional deviation from the estimated data
Outputs
 tLE1Cull               Culled leading edge times HSA 1
 tTE1Cull               Culled trailing edge times HSA 1
 tLE2Cull               Culled leading edge times HSA 2
 tTE2Cull               Culled trailing edge times HSA 2
References abs(), ADCull(), Dot(), HSAData(), length(), Measurements(), NadGen(), NewFig(), RaDec2U(), XLabelS(), YLabelS(), and zeros().
Referenced by ADCull().
AddBias()
function AddBias (in varargin)
Form
varargout = AddBias(varargin)
Inputs
 Meas1          Measurement vector 1 - any size or units
  ...
 MeasN          Measurement vector n- any size or units
 biases  (n)    Bias values to be added. Units must match measurement
                vectors
Outputs
 adjMeas1       Adjusted measurement vector 1
  ...
 adjMeasN       Adjusted measurement vector n
References vector().
ADGen()
function ADGen (in el, in uSun, in uSpin, in spinRate, in mA, in hSADelay, in hSAQuant, in)
Creates a plot window.
Form
 [tLE,tTE,sA,uNadir,eRadius] = ADGen( el, uSun, uSpin, spinRate, mA,
 hSADelay, hSAQuant,hSAQuantType,
 hSAOneSigma, cantAngle, cantBias,
 dihedralBias, sSAQuant, sSAQuantType,
 sSAOneSigma, sSABias, eRadiusBias )
Inputs
 el           (6)       Orbital elements
 uSpin        (3,1)     Spin axis
 uSun         (3,n)     Sun vector
 spinRate               Spacecraft spin rate (rad/sec)
 mA           (n)       Mean anomalies at which to take the data
 hSADelay     (m)       Delay in the edge times (sec)
 hSAQuant     (m)       HSA data quantization
 hSAQuantType (m)       Type of quantization-either 'round' or 'truncate'
 hSAOneSigma  (m)       Noise
 cantAngle    (m)       Sensor cant angles
 cantBias     (m)       Cant angle bias
 dihedralBias (m)       dihedral angle bias
 sSAQuant               Sun sensor data quantization
 sSAQuantType           Type of quantization-either 'round' or 'truncate'
 sSAOneSigma            Noise
 sSABias                Sun sensor data bias
 eRadiusBias            Earth bias
Outputs
 tLE          (m,n)     Leading edge times
 tTE          (m,n)     Trailing edge time
 sA           (n)       Sun angles
 uNadir       (3,n)     Nadir vectors
 eRadius      (n)       Earth radius
References and(), CP2I(), Delay(), E2Nu(), HSAData(), length(), M2EEl(), Nadir(), NewFig(), SunData(), vector(), Watermark(), and zeros().
ADPartls()
function ADPartls (in el, in jDEpoch, in jD, in ignoredArg, in cant, in ignoredArg, in rA, in dec)
Creates three plots.
Form
 ADPartls( el, jDEpoch, jD, spinRate, cant, dihedral, rA, dec )
Inputs
 el           (6)       Orbital elements
 jDEpoch                The Julian date corresponding to the mean anomaly
                        in el
 jD           (n)       Julian dates at which to compute the data
 spinRate               Spin rate (rad/sec) (not used)
 cant         (2)       Cant angles (rad)
 dihedral     (2)       Dihedral angles (rad) (not used)
 rA                     Right Ascension (rad)
 dec                    Declination (rad)
Outputs
 none
References CP2I(), DHArcDX(), DHCWDX(), DHDADX(), E2Nu(), M2EEl(), NewFig(), SunV1(), XLabelS(), and YLabelS().
BObjIntF()
function BObjIntF (in u, in uBO, in rhoBO, in cant, in fOV)
Form
 k = BObjIntF( u, uBO, rhoBO, cant, fOV )
Inputs
 u       (3,1)  Spin axis unit vector or [rA,dec];
 uBO    (3,n)   Unit vectors of bright object(s)
 rhoBO   (1,n)  Angular radii of bright object(s)
 cant   (1,1) Cant angle of scanning sensor wrt the spin axis
 fOV    (1,1)   Field of view of the sensor
Outputs
 k                      Indexes of bright objects that interfere
References length(), Unit(), and vector().
BShuster()
function BShuster (in usun, in unadir, in sa, in tle, in tte, in cant, in eradius, in spinrate, in)
Computes the solution to the attitude determination problem using Schuster's batch method. Uses sun angles, dihedral angles and chordwidths.
Requires the corresponding sun vectors and nadir vectors.
Form
 [ra,dec,p] = BShuster( usun, unadir, sa, tle, tte, cant, eradius,
 spinrate, threshold, dihedral, sigmas, sigmae, sigman )
Inputs
 usun         (3,n)     Unit sun vector
 unadir       (3,n)     Unit nadir vectors
 sa           (1,n)     The angle between the sun line and the spin axis
 tle                    Leading edge times
 tte                    Trailing edge time
 cant                   Cant angle (rad)
 eradius      (1,n)     Angular radius of the earth (rad)
 spinrate               Spin rate (rad/sec)
 threshold              Threshold chord width (rad)
 dihedral               Dihedral angle of hsa (rad)
 sigmas                 Standard deviation of each sun measurement
 sigmae                 Standard deviation of each nadir measurement
 sigman                 Standard deviation of each dihedral measurement
Outputs
 ra                     Right ascension of the spin axis
 dec                    Declination of the spin axis
 p                      Covariance
References: Shuster, M.D., Efficient Algorithms for Spin-Axis Attitude Determination, The Journal of the Astronautical Sciences, Vol. XXXI, No. 2, April-June, 1983, pp. 237-249.
References and(), Unit(), and vector().
BShuster2()
function BShuster2 (in usun, in unadir, in sa, in tle_cw, in tte_da, in cant, in eradius, in spinrate, in)
Computes the solution to the attitude determination problem using Schuster's batch method. Uses sun angles, dihedral angles and chordwidths.
Requires the corresponding sun vectors and nadir vectors.
The 4th and 5th inputs can either be leading and trailing edge times or chordwidths and mid-scan dihedral angles, respectively. The last input must be set to either 'time' or 'angl'. The default is 'time'.
Form
 [ra,dec,p] = BShuster2( usun, unadir, sa, tle_cw, tte_da, cant, eradius,
 spinrate, threshold, dihedral, sigmas, sigmae, sigman, type )
Inputs
 usun         (3,n)     Unit sun vector
 unadir       (3,n)     Unit nadir vectors
 sa           (1,n)     The angle between the sun line and the spin axis
 tle_cw                 Leading edge times (sec) or chordwidths (rad)
 tte_da                 Trailing edge time  (sec) or mid-scan dihedral angles (rad)
 cant                   Cant angle (rad)
 eradius      (1,n)     Angular radius of the earth (rad)
 spinrate               Spin rate (rad/sec)
 threshold              Threshold chord width (rad)
 dihedral               Dihedral angle of hsa (rad)
                        Send an empty matrix for chordwidths and mid-scan dihedral angles
 sigmas                 Standard deviation of each sun measurement
 sigmae                 Standard deviation of each nadir measurement
 sigman                 Standard deviation of each dihedral measurement
 type                   'time' = leading and trail edge times entered (default)
                        'angl' = chordwidths and dihedral angles entered
Outputs
 ra                     Right ascension of the spin axis
 dec                    Declination of the spin axis
 p                      Covariance
References: Shuster, M.D., Efficient Algorithms for Spin-Axis Attitude Determination, The Journal of the Astronautical Sciences, Vol. XXXI, No. 2, April-June, 1983, pp. 237-249.
References and(), set(), Unit(), and vector().
ConeInt()
function ConeInt (in usun, in unadir, in sa, in tle, in tte, in cant, in eradius, in spinrate, in threshold)
Computes the solution to the attitude determination problem using the cone intercept method. Only uses sun angles and chordwidths. Requires the corresponding sun vectors and nadir vectors. Creates plots.
Form
 [ra,dec,rd] = ConeInt( usun, unadir, sa, tle, tte, cant, eradius,
 spinrate, threshold )
Inputs
 usun         (3,n)     Unit sun vector
 unadir       (3,n)     Unit nadir vectors
 sa           (1,n)     The angle between the sun line and the spin axis
 tle                    Leading edge times
 tte                    Trailing edge time
 cant                   Cant angle (rad)
 eradius      (1,n)     Angular radius of the rearth (rad)
 spinrate               Spin rate (rad/sec)
 threshold              Threshold chord width (rad)
Outputs
 ra                     Right ascension of the spin axis
 dec                    Declination of the spin axis
 rd           (2,n)     [Right Ascension;Declination] vector
References and(), Cone(), Unit(), and vector().
ConeInt2()
function ConeInt2 (in usun, in unadir, in sa, in tle_cw, in tte, in cant, in eradius, in spinrate, in threshold, in type)
Computes the solution to the attitude determination problem using the cone intercept method. Only uses sun angles and chordwidths. Creates plots.
Requires the corresponding sun vectors and nadir vectors.
The 4th input can either be leading edge times or chordwidths. The last input must be set to either 'time' or 'angl'. The default is 'time'. To input chordwidths, set the 5th input (tte) to be empty.
Form
 [ra,dec,rd] = ConeInt2( usun, unadir, sa, tle_cw, tte, cant, eradius,
 spinrate, threshold, type )
Inputs
 usun         (3,n)     Unit sun vector
 unadir       (3,n)     Unit nadir vectors
 sa           (1,n)     The angle between the sun line and the spin axis
 tle_cw       (1,n)     Leading edge times (sec) or chordwidths (rad)
 tte                    Trailing edge time (sec) (Set to empty for chordwidths)
 cant                   Cant angle (rad)
 eradius      (1,n)     Angular radius of the rearth (rad)
 spinrate               Spin rate (rad/sec)
 threshold              Threshold chord width (rad)
 type                   'time' = leading and trail edge times entered (default)
                        'angl' = chordwidths and dihedral angles entered
Outputs
 ra                     Right ascension of the spin axis
 dec                    Declination of the spin axis
 rd           (2,n)     [Right Ascension;Declination] vector
References and(), Cone(), set(), Unit(), and vector().
ConjGrad()
function ConjGrad (in F, in CF, in S0, in xA, in kX, in tol, in prog, in sd)
Uses the conjugate gradient method to solve the least squares problem.
 J     = 0.5 rho'*W*rho + 0.5*(x-xA)'*S0*(x-xA)
 rho   = y - h(x)
 h/x = H(x)
 J/x = g = -H'*W*rho + S0*(x-xA)
The next step is
 x(k+1) - x(k) = alpha*d(k)
where
 d(k) = -g(k) + [(g(k)'(g(k)-g(k-1))/g(k-1)'g(k-1)]d(k-1)
alpha is found by minimizing J with respect to alpha at each step.
Form
 [x, k, P, wmr, sr, J, sig, nz] = ConjGrad( F, CF, S0, xA, kX, tol, prog, sd )
Inputs
 F                      [rho,H,W,jL]  = F(xA)
 CF                     [J] = CF( alpha, x0, d, S0, xA )
 S0                     A priori state covariance matrix
 xA                     A priori state
 kX                     States to be found
 tol                    Cost tolerance
 prog                   If not = 0 give progress reports
 sd                     Use steepest descent
Outputs
 x                      Matrix of state vectors
 k                      Number of iterations
 P                      Covariance matrix: inv[S0 + G'WG]
 wmr                    Weighted mean of the residuals
 sr                     Weighted rms deviation of the residuals
 J                      Loss estimate
 sig                    Uncertainty in the estimates
 nz                     Number of measurements used
References: Strang, G., Introduction to Applied Mathematics, Wellesley- Cambridge Press, 1986, pp. 378-379.
References abs(), and(), IsVersionAfter(), length(), and zeros().
ConvertHSA()
function ConvertHSA (in action, in varargin)
or convert HSA data from the type provided to the desired processing type.
Form
 [varargout] = ConvertHSA( action, varargin )
Inputs
 action               'TimeToAngles' or 'AnglesToTime' or
                      'Processing'
 dAngle   {2}         dihedral angles (rads)
 cWidth   {2}         chordwidths (rads)
 tLE      {2}         leading edge times (sec past CEP)
 tTE      {2}         trailing edge times (sec past CEP)
 jDCEP   (n,1)        Julian date of CEP time for each period
 hSAData  struct      Contains data and processing types for HSA measurements
 spinRate             Spin rate (rad/sec)
Outputs
 dAngle1              Dihedral angles from HSA 1
 dAngle2              Dihedral angles from HSA 2
 cWidth1              Chordwidths from HSA 1
 cWidth2              Chordwidths from HSA 2
 hSAData              Same as input, but updated if converted times to angles
References and().
CostF()
function CostF (in alpha, in x0, in d, in S0, in xA)
 x     = x0 + alpha*d;
 J     = 0.5 rho'*W*rho + 0.5*(x-xA)'*S0*(x-xA)
Form
 J = CostF( alpha, x0, d, S0, xA )
Inputs
 alpha                  Current value of alpha
 x0                     Current value of x
 d                      Alpha*d is the next increment to x
 S0                     A priori state covariance matrix
 xA                     A priori state
Outputs
 J                      The cost function.
See also
FX
References CostF(), and FX().
Referenced by CostF().
CostNM()
function CostNM (in x, in kX, in S0, in xA, in lX)
Computes the cost functional for the Nelder-Meade algorithm for least-squares attitude determination.
Form
 J = CostNM( x, kX, S0, xA, lX )
Inputs
 x                      State
 kX                     Subindex for states to be used
 S0                     Inverse of initial state covariance
 xA                     Initial state
 lX                     Length of the state vector
Outputs
 J                      Cost
References vector().
CostNMTE()
function CostNMTE (in x, in kX, in S0, in xA, in lX, in type1, in type2)
Computes the cost functional for the Nelder-Meade algorithm for least-squares attitude determination. Dihedral angles are replaced by trailing edge angles.
Form
 J = CostNMTE( x, kX, S0, xA, lX, type1, type2 )
Inputs
 x                      State
 kX                     Subindex for states to be used
 S0                     Inverse of initial state covariance
 xA                     Initial state
 lX                     Length of the state vector
 type1                  Type of dihedral angle used for HSA1
 type2                  HSA2: 'leading' 'trailing' or 'midscan'(default)
Outputs
 J                      Cost
References vector().
CwValid()
function CwValid (in ra, in dec, in er, in g, in ue)
Form
 yesNo = CwValid( ra, dec, er, g, ue )
Inputs
 ra           (1,1) Right ascension
 dec          (1,1) Declination
 er           (1,1) Earth radius
 g            (1,1) Nominal cant angle
 ue           (3,1)  Nadir vector
Outputs
 yesNo        (1,1) 0 if the chordwidth is invalid
References abs(), er(), Nadir(), and vector().
DataWindow()
function DataWindow ()
Form
DataWindow
References and(), DataWindow(), and get().
Referenced by DataWindow(), and SAADMain().
DHArcDX()
function DHArcDX (in ra, in dec, in u)
Used for sun angle measurements.
Form
 H = DHArcDX( ra, dec, u )
Inputs
 ra                     Right ascension
 dec                    Declination
 u                      Unit vector
Outputs
 H                      [h/dra h/ddec]
References Jacobian(), Unit(), and vector().
Referenced by ADPartls(), and DHArcDXi().
DHArcDXi()
function DHArcDXi (in x, in u)
Form
 H = DHArcDXi( x, u )
Inputs
 x             State vector [ra, dec, bias]
 u             Auxiliary vector [us]
Outputs
 H             Jacobian of the Arc length
References DHArcDX(), Jacobian(), length(), and vector().
DHCWDX()
function DHCWDX (in ra, in dec, in cg, in sg, in er, in ue)
The derivative is with respect to the vector:
 [ right ascension  ]
 [ declination      ]
 [ cant angle bias  ]
 [ earth width bias ]
The output is:
 [w/ra, w/dec, w/cantAngleBias, w/earthWidthBias]
Form
 H = DHCWDX( ra, dec, cg, sg, er, ue )
Inputs
 ra                     Right ascension
 dec                    Declination
 cg                     Cosine of the cant angle
 sg                     Sine of the cant angle
 er         (n)         Angular earth radius
 ue         (3,n)       Nadir vector
Outputs
 H                      Derivative
References and(), er(), Jacobian(), Nadir(), and vector().
Referenced by ADPartls().
DHCWDXi()
function DHCWDXi (in x, in u)
Form
 H = DHCWDXi( x, u )
Inputs
 x             State vector [ra, dec, dcant, dearthRadius, bias]
 u             Auxiliary vector [cant;er;ue]
Outputs
 H             Jacobian of the chordwidth
References er(), Jacobian(), and vector().
DHDADX()
function DHDADX (in ra, in dec, in us, in ue)
Computes the derivatives of the dihedral angle with respect to right ascension and declination.
Form
 H = DHDADX( ra, dec, us, ue )
Inputs
 ra                     Right Ascension
 dec                    Declination
 us           (3,n)     Unit sun vectors
 ue           (3,n)     Unit nadir vectors
Outputs
 H            (n,2)     [da/ra da/dec]
References and(), Jacobian(), and Unit().
Referenced by ADPartls(), and DHDADXi().
DHDADXi()
function DHDADXi (in x, in u)
Form
 H = DHDADXi( x, u )
Inputs
 x             State vector [ra, dec, bias]
 u             Auxiliary vector [us;ue]
Outputs
 da            Dihedral angle
References DHDADX(), and vector().
DiffCorr()
function DiffCorr (in f, in S0, in xA, in kx, in tol, in tolSVD, in ignoredArg)
Solves
 y = h(x)
by linearizing about the reference vector xA:
 y = h(xA) + H(xA)(x-xA)
Uses the singular value decomposition to solve the least squares problem
Form
 [x, k, rsvd, cHWH, rank, P, wmr, sr, J, sig, nz] = DiffCorr( f, S0, xA, kx, tol, tolSVD, initCHWH )
Inputs
 F                      [rho,H,W]  = f(xA)
 S0                     A priori state covariance matrix
 xA                     A priori state
 kx                     States to be found
 tol                    Error tolerance
 tolSVD                 SVD tolerance
 initCHWH               1 = show condition number of initial HWH
Outputs
 x                      Matrix of state vectors. Each column is one iteration.
 k                      Number of iterations
 rsvd                   Residuals from the least squares
 cHWH                   Condition number of H'WH
 rank                   Rank of the A matrix
 P                      Covariance matrix: inv[S0 + H'WH]
 wmr                    Weighted mean of the residuals
 sr                     Weighted rms deviation of the residuals
 J                      Loss estimate
 sig                    Uncertainty in the estimates
 nz                     Number of measurements used
References: Wertz, J.R., Spacecraft Attitude Determination and Control, Kluwer, 1976, pp. 447-454.
References and(), DiffCorr(), length(), and vector().
Referenced by DiffCorr().
DSunCone()
function DSunCone (in uSun, in rAI, in decI, in beta)
Compute possible right ascensions and declinations given a sun angle as a function of the angular distance from the nominal orientation. If there are no output arguments it creates a plot.
Form
 [rA, dec, phi] = DSunCone( uSun, rAI, decI, beta )
Inputs
 uSun   (3,1)     Sun Vector
 rAI   (1,1)     Nominal right ascension (rad)
 decI   (1,1)     Nominal declination (rad)
 beta   (1,1)     Sun angle (rad)
Outputs
 rA    (1,:)     Right Ascension (rad)
 dec   (1,:)     Declination  (rad)
 phi   (1,:)     Dot product of nominal vector sun cone
References and(), Cross(), Dot(), length(), Plot2D(), U2RADec(), Unit(), and vector().
DWInputs()
function DWInputs (in action, in varargin)
Form
 h = DWInputs( action )
Inputs
 action               'Sensor Data' or 'Orbit Data'
Outputs
 h                    Handle to the window created
FX()
function FX (in x)
Finds the vectors
 rho   = z - h
 dh/dx = H
Form
 [rho, H, W, JL] = FX( x )
Inputs
 x         State vector
Outputs
 rho       Residual vector z - h
 H         dh/dx
 W         The measurement weighting vector
 JL        Cost eliminated by eliminating measurements
References Jacobian(), Residual(), and vector().
Referenced by CostF().
FXNM()
function FXNM (in x)
Finds the vectors
 rho   = z - h
Form
 [rho, W, JL] = FXNM( x )
Inputs
 x         State vector
Outputs
 rho       Residual vector z - h
 W         The measurement weighting vector
 JL        Cost eliminated by eliminating measurements
References Residual(), and vector().
FXNMTE()
function FXNMTE (in x, in type1, in type2)
Finds the vectors
 rho   = z - h
Dihedral angles are replaced by trailing edge angles.
Form
 [rho, W, JL] = FXNMTE( x )
Inputs
 x         State vector
 type1     'leading' 'trailing' or 'midscan'
 type2     'leading' 'trailing' or 'midscan'
Outputs
 rho       Residual vector z - h
 W         The measurement weighting vector
 JL        Cost eliminated by eliminating measurements
References Residual(), and vector().
HArc()
function HArc (in ua, in u)
If there are no outputs it creates a plot.
Form
 h = HArc( ua, u )
Inputs
 ua             (3,1)   Spacecraft unit vector
 u              (3,n)   Unit vector
Outputs
 h                      Expected measurement
References NewFig(), Unit(), and vector().
Referenced by HArci().
HArci()
function HArci (in x, in u)
Form
 a = HArci( x, u )
Inputs
 x             State vector [ra, dec, bias]
 u             Auxiliary vector [us]
Outputs
 a             Arc length
References HArc(), length(), and vector().
HCw()
function HCw (in ua, in e, in g, in ue)
If there are no outputs create a plot.
Form
 w = HCw( ua, e, g, ue )
Inputs
 ua                     Spacecraft unit vector
 e                      Earth angular radius
 g                      Cant angle
 ue                     Nadir vector
Outputs
 w                      Chordwidth
References Nadir(), and vector().
Referenced by HCwi(), HLE(), and HTE().
HCw2R()
function HCw2R (in ua, in g, in e1, in e2, in ue1, in ue2)
Computes the chordwidth when the nadir vector is different for the leading and trailing edges. If there are no outputs it creates a plot.
Form
 w = HCw2R( ua, g, e1, e2, ue1, ue2 )
Inputs
 ua          (3,1)      Spacecraft unit vector
 g           (1,1)      Cant angle
 e1          (n)        Earth angular radius (LE)
 e2          (n)        Earth angular radius (TE)
 ue1         (3,n)      Nadir vector (LE)
 ue2         (3,n)      Nadir vector (TE)
Outputs
 w                      Chordwidth
References abs(), and(), length(), Nadir(), NewFig(), and vector().
HCwi()
function HCwi (in x, in u)
Form
 w = HCwi( x, u )
Inputs
 x             State vector [ra, dec, dcant, dearthRadius, bias]
 u             Auxiliary vector [cant;er;ue]
Outputs
 w             Chordwidth
References er(), HCw(), and vector().
HDA()
function HDA (in uA, in uS, in uE)
Form
 dA = HDA( uA, uS, uE )
Inputs
 uA           (3,1)     Spacecraft unit vector
 uS           (3,n)     Unit sun vectors
 uE           (3,n)     Unit nadir vectors
Outputs
 dA           (n)       Dihedral angle
References Cross(), Dot(), NewFig(), Unit(), and vector().
Referenced by HDAi(), and Outliers().
HDAi()
function HDAi (in x, in u)
us is the sun unit vector and ue is the nadir vector.
Form
 da = HDAi( x, u )
Inputs
 x     (2,1) State vector [ra, dec, bias]
 u     (6,1) Auxiliary vector [us;ue]
Outputs
 da            Dihedral angle
References and(), HDA(), and vector().
HLE()
function HLE (in uA, in uS, in uE, in earthRadius, in cant)
Form
 lE = HLE( uA, uS, uE, earthRadius, cant )
Inputs
 uA           (3,1)     Spacecraft spin axis unit vector
 uS           (3,n)     Unit sun vectors
 uE           (3,n)     Unit nadir vectors
 earthRadius  (1,1)     Radius of the earth (km)
 cant         (1,1)     Sensor cant angle (rad)
Outputs
 lE           (1,n)     Leading edge dihedral angle (rad)
References Cross(), Dot(), HCw(), NewFig(), Unit(), and vector().
HTE()
function HTE (in uA, in uS, in uE, in earthRadius, in cant)
Form
 tE = HTE( uA, uS, uE, earthRadius, cant )
Inputs
 uA           (3,1)     Spacecraft spin axis unit vector
 uS           (3,n)     Unit sun vectors
 uE           (3,n)     Unit nadir vectors
 earthRadius  (1,1)     Radius of the earth (km)
 cant         (1,1)     Sensor cant angle (rad)
Outputs
 tE           (n,1)     Trailing edge dihedral angle (rad)
References Cross(), Dot(), HCw(), NewFig(), Unit(), and vector().
KFExItMu()
function KFExItMu (in hname, in Hname, in H, in Hindex, in R, in z, in x, in P, in f, in nits, in u)
Also can include a forgetting factor to keep the covariance from going to zero. This can be used independently if the state is constant. This can also be used to process measurements one at a time by passing different hname and Hname with each call.
Form
 [x, P, K] = KFExItMu( hname, Hname, H, Hindex, R, z, x, P, f, nits, u )
Inputs
 hname                  The name of the function that supplies the
                        constant term in the measurement equation
 Hname                  The name of the function that supplies the
                        partials in the measurement equation
 H                      Dummy H vector (for sizing only)
 Hindex                 The location of Hname in H
 R                      Measurement covariance matrix
 z                      Measurement vector
 x                      State
 P                      Covariance matrix
 f                      Forgetting factor (0 to 1)
 nits                   Maximum number of iterations
 u                      Auxiliary vector to pass to hname and Hname
Outputs
 x                      State
 P                      Covariance matrix
 K                      Gain matrix
References: Gelb, A., Applied Optimal Estimation, MIT Press, Cambridge, 1974, pp. 190-191.
References and(), Initialize(), and vector().
KFSAAD()
function KFSAAD (in x0, in P0, in Rcw, in Rda, in Rsb, in cw1, in cw2, in da1, in da2, in sb, in ue, in us, in)
Implements an extended iterated Kalman Filter for the spin-axis attitude determination problem.
Form
 [xF, P] = KFSAAD( x0, P0, Rcw, Rda, Rsb, cw1, cw2, da1, da2, sb, ue, us,...
 er, cant1, cant2, ff, nits, attRef )
Inputs
 x0                     Initial state [    ra;        dec;   cwbias1; cwbias2; dabias1;
                                       dabias2; cantbias1; cantbias2; sunbias;  erbias]
 P0                     Initial covariance
 Rcw                    Chordwidth covariance
 Rda                    Dihedral angle measurement covariance
 Rsb                    Sun sensor measurement covariance
 cw1                    Chordwidth measurement 1
 cw2                    Chordwidth measurement 2
 da1                    Dihedral angle measurement 1
 da2                    Dihedral angle measurement 2
 sb                     Sun sensor measurement
 ue                     Nadir vector
 us                     Sun vector
 er                     Earth radius
 cant1                  HSA 1 cant angle
 cant2                  HSA 2 cant angle
 ff                     Forgetting factor (0 to 1)
 nits                   Number of iterations
 attRef                 Reference attitude for plotting [ra dec] (rad)
Outputs
 x                      Final State
 P                      Covariance matrix
References and(), er(), Initialize(), isempty(), Nadir(), NewFig(), vector(), Watermark(), XLabelS(), and YLabelS().
LoadAtt()
function LoadAtt (in file, in path)
If there are no outputs it creates a plot. You need to add your own code to process the incoming data. To try the function, open the file
 LoadAtt( 'SpinAttData.txt')
This file has each line in the form:
 Time tag, hsa le 1, hsa width 1, hsa le 2, hsa width 2 spin rate, sun angle
All hsa data is in times. The spin rate is used to convert times to angles. This function can read in multiple files.
Form
 [tLE1, tTE1, tLE2, tTE2, tTag, sA, wSpin, sAB] = LoadAtt( file, path )
Inputs
 file             (:)     File names
 path                     Name of path
Outputs
 tLE1             (:)     HSA 1 leading edge
 tTE1             (:)     HSA 1 trailing edge
 tLE2             (:)     HSA 2 leading edge
 tTE2             (:)     HSA 2 trailing edge
 tTag             (:)     Time tags
 sA               (:)     Sun angles
 wSpin            (:)     Spin rate
 sAB              (1,2)   Sun angles from the leading and trailing blocks
References and(), NewFig(), XLabelS(), YLabelS(), and zeros().
LoadSAADData()
function LoadSAADData (in files)
 If called without inputs it will load SampleData.txt.
Form
 measuredData = LoadSAADData(files)
Inputs
 files            (:)     Struct array of file names - Fields are
    .pathName   string
    .fileName   string
Outputs
 measuredData   (1,1)    Struct array of measured data. Fields are:
    .jD          (:)     Time tags
    .cW1         (:)     HSA 1 Chordwidths
    .cW2         (:)     HSA 2 Chordwidths
    .dA1         (:)     HSA 1 Dihedral Angles
    .dA2         (:)     HSA 2 Dihedral Angles
    .sA          (:)     Sun angles
References Demo(), length(), and LoadSAADData().
Referenced by LoadSAADData().
NadGen()
function NadGen (in el, in jDEpoch, in jD)
Generate earth radius, nadir vector and sun vector data at the selected Julian dates. The sun vector includes the effects of parallax.
Form
 [uNadir, eRadius, uSun] = NadGen( el, jDEpoch, jD )
Inputs
 el         (1,6) Orbital elements
 jDEpoch    (1,1) The Julian date corresponding to the mean anomaly in el
 jD      (1,n) Julian dates at which to compute the data
Outputs
 uNadir     (3,n)     Nadir vectors
 eRadius    (n)       Earth radius
 uSun       (3,n)     Sun vectors
References and(), Date2JD(), Mag(), NadGen(), Nadir(), Plot2D(), RVOrbGen(), SunV1(), Unit(), and vector().
Referenced by ADComp(), ADCull(), and NadGen().
Outliers()
function Outliers (in z, in ra, in dec, in bias, in type, in range, in u1, in u2, in er, in cant, in erbias)
The last 3 inputs are only needed for chordwidth measurements.
Form
 k = Outliers( z, ra, dec, bias, type, range, u1, u2, er, cant, erbias )
Inputs
 z                      Measurement vector
 ra                     Right ascension
 dec                    Declination
 bias                   Sensor bias
 type                   Measurement type [1=ssa,2=chordwidth,3=dihedral]
 range                  Allowable maximum value
 u1                     Vector [us if ssa or dihedral, ue if chordwidth]
 u2                     Vector ue if dihedral angle
 er                     Earth radii
 cant                   Cant angle
 erbias                 Earth radius bias
Outputs
 k                      Set of acceptable measurements
References abs(), er(), HDA(), isempty(), Measurements(), NewFig(), Outliers(), set(), and vector().
Referenced by Outliers().
PlotPred()
function PlotPred (in sensorInputs, in spinRate, in)
Form
 [dA1P,dA2P,cW1P,cW2P,sA1P] = PlotPred(sensorInputs,spinRate,sensorData,
 hSAData,measurements,jD,cantBiases)
Inputs
 sensorInputs   {4}    Inputs to HSAData - function that simulates an HSA
    uSun       (n,1)   Unit vectors to sun
    uNadir     (n,1)   Unit vectors to earth
    eRadius    (n,1)   Earth radii
    spinAxis   (3,1)   Spacecraft spin axis
 spinRate      (1,1)   Spin rate (rads/sec)
 sensorData   struct   HSA & sun sensor cant and dihedral angles, delay
 hSAData      struct   Contains data and processing types for HSA measurements
 measurements   {5}    Measurement vectors
    dA1M       (n,1)   Dihedral angles from HSA 1 (rads)
    dA2M       (n,1)   Dihedral angles from HSA 2 (rads)
    cW1M       (n,1)   Chordwidth angles from HSA 1 (rads)
    cW2M       (n,1)   Chordwidth angles from HSA 2 (rads)
    sA1M       (n,1)   Sun angles from SSA 1 (rads)
 jD            (n,1)   Time of each measurement
 cantBiases    (2,1)   HSA cant angle biases (rad) - optional
 vData          {2}    Each element is a vector of indices to valid measurements
                        if omitted, all measurements are considered valid
Outputs
 dA1P       (n,1)      Predicted dihedral angles from HSA 1 (rads)
 dA2P       (n,1)      Predicted dihedral angles from HSA 2 (rads)
 cW1P       (n,1)      Predicted chordwidth angles from HSA 1 (rads)
 cW2P       (n,1)      Predicted chordwidth angles from HSA 2 (rads)
 sA1P       (n,1)      Predicted sun angles from SSA 1 (rads)
QuadCost()
function QuadCost (in fX, in x0, in xA, in d, in S0, in aMin, in aMax)
Where
 x         = x0 + alpha*d;
 J         = (1/2) (rho'*W*rho + 0.5*(x-xA)'*S0*(x-xA))
 dJ/dalpha = d'*(S0*(x-xA) - H'*W*rho);
 rho       = z - h
 h/x       = H
Calls a function fx defined by
 [rho,H,W,JL] = fX(x);
 rho       = y - h
 H         = dh/dx
 W         = Residual weighting vector
 JL        = is a cost adjustment scalar
 fX must have a global y and a global index k that corresponds to each x.
If there are no outputs, it creates a plot.
Form
 [J, dJ] = QuadCost( fx, x0, xA, d, S0, aMin, aMax )
Inputs
 fX                     The name of the function
 x0                     Current value of x
 xA                     Reference value of x (for S0)
 d                      Alpha*d is the next increment to x
 S0                     A priori state covariance matrix
 xA                     A priori state
 aMin                   Minimum alpha
 aMax                   Maximum alpha
Outputs
 J                      Cost
 dJ                     Derivative of the cost
References and(), Demo(), Plot2D(), Residual(), scalar(), and vector().
Radiance()
function Radiance (in lat, in dateTime, in year)
If there are no outputs it creates a plot.
Form
 f = Radiance( lat, dateTime, year )
Inputs
 lat             (n)           latitude (rad)
 dateTime        (6 or m)      [ year month day hour minute seconds ]
                                 or fraction of year
 year                          year if dateTime is fraction of a year.
Outputs
 f             (n,m)         Radiance values (W/m^2sr)
References Radiance().
Referenced by Radiance(), and TargetInFocalPlane().
ResidStat()
function ResidStat (in dAngles, in cWidths, in sunAngles, in kV, in hSAData)
Form
 ResidStat( dAngles,cWidths,kV,sunAngle,hSAData )
Inputs
 dAngles   {4}       Measured and predicted dihedral angles (rads)
 cWidths   {4}       Measured and predicted chordwidths (rads)
 sunAngles {2}       Measured and predicted sun angles (rads)
 kV        {2}       Indices to valid HSA data
 hSAData  struct     Contains data and processing types for HSA measurements
Outputs
 none
References and().
SAADFile()
function SAADFile (in action, in varargin)
Form
 h = SAADFile( action )
Inputs
 action               'OpenAddDeleteWindow' or 'GetDirectory' or
                      'SetButtons' or 'MakeFileList'
Outputs
 h                    Handle to the window that was created, or
                      cell array of full file names
                      1 if they do
SAADHelp()
function SAADHelp (in topic)
Form
 h = SAADHelp( topic )
Inputs
 topic       String containing the help topic
Outputs
 h           Handle to the help window created
SAADMain()
function SAADMain (in action, in state)
 Called by ISAAD. Should not be called directly.
Form
SAADMain(action, state)
Inputs
 action            'Create' or 'ToggleView' or 'CheckForSaveWarning'
 state   string    'solve', 'view', or 'toggle' - when used with ToggleView
         struct    With fields 'displayedThisSession, displayNextSolve, and
                      displayFrequency - when used with CheckForSaveWarning
Outputs
 h                  Handle to the figure created (for 'Create'), see
                     forms for other cases
References and(), DataWindow(), get(), isempty(), Quit(), SAADMain(), set(), and SolutionWindow().
Referenced by SAADMain().
SAADMenu()
function SAADMenu (in action, in varargin)
Form
 SAADMenu( action )
Inputs
 action               'MakeMenu' or 'UpdateSubMenus' or
                      'SaveCase' or 'LoadCase'
                      or
Outputs
 none                 See individual cases
SAADTool()
function SAADTool (in action, in varargin)
Form
 [varargout] = SAADTool( action, varargin )
Inputs
 action               'ResizeCovariances' or 'CopyCovariances' or
                      'CovarianceUnitsSwitch' or 'DisplayUnitsSwitch'
                      or 'UnitsLabelingSwitch' or 'VerticallySortObjs' or
                      'OrbitDataExist' or 'SaveWarning' or 'LoadWarning'
                      or 'DisplayLoadedValues' or 'NoDataFilesWarning' or
                      'SaveChangesWarning' or 'GetSolutionFlag' or
                      'SetSolutionFlags'
Outputs
 See individual functions
References get().
Referenced by ClosedFormMethod().
SFShustr()
function SFShustr (in usun, in unadir, in sa, in tle, in tte, in cant, in eradius, in)
Computes the solution to the attitude determination problem using Schuster's single frame method. Uses sun angles, dihedral angles and chordwidths. Creates a plot.
Requires the corresponding sun vectors and nadir vectors.
Form
 [ra, dec, rd] = SFShustr( usun, unadir, sa, tle, tte, cant, eradius,
 spinrate, threshold, dihedral )
Inputs
 usun         (3,n)     Unit sun vector
 unadir       (3,n)     Unit nadir vectors
 sa           (1,n)     The angle between the sun line and the spin axis
 tle                    Leading edge times
 tte                    Trailing edge time
 cant                   Cant angle (rad)
 eradius      (1,n)     Angular radius of the rearth (rad)
 spinrate               Spin rate (rad/sec)
 threshold              Threshold chord width (rad)
 dihedral               Dihedral angle of hsa (rad)
Outputs
 ra                     Right ascension of the spin axis
 dec                    Declination of the spin axis
 rd           (2,n)     [Right Ascension;Declination] vector
References: Shuster, M.D., Efficient Algorithms for Spin-Axis Attitude Determination, The Journal of the Astronautical Sciences, Vol. XXXI, No. 2, April-June, 1983, pp. 237-249.
References and(), Unit(), and vector().
SFShustr2()
function SFShustr2 (in usun, in unadir, in sa, in tle_cw, in tte_da, in cant, in eradius, in)
Computes the solution to the attitude determination problem using Schuster's single frame method. Uses sun angles, dihedral angles and chordwidths. Creates a plot.
Requires the corresponding sun vectors and nadir vectors.
The 4th and 5th inputs can either be leading and trailing edge times or chordwidths and mid-scan dihedral angles, respectively. The last input must be set to either 'time' or 'angl'. The default is 'time'.
Form
 [ra, dec, rd] = SFShustr2( usun, unadir, sa, tle_cw, tte_da, cant, eradius,
 spinrate, threshold, dihedral, type )
Inputs
 usun         (3,n)     Unit sun vector
 unadir       (3,n)     Unit nadir vectors
 sa           (1,n)     The angle between the sun line and the spin axis
 tle_cw       (1,n)     Leading edge times (sec) or chordwidths (rad)
 tte_da       (1,n)     Trailing edge time (sec) or mid-scan dihedral angles (rad)
 cant                   Cant angle (rad)
 eradius      (1,n)     Angular radius of the rearth (rad)
 spinrate               Spin rate (rad/sec)
 threshold              Threshold chord width (rad)
 dihedral               Dihedral angle of hsa (rad)
 type                   'time' = leading and trail edge times entered (default)
                        'angl' = chordwidths and dihedral angles entered
Outputs
 ra                     Right ascension of the spin axis
 dec                    Declination of the spin axis
 rd           (2,n)     [Right Ascension;Declination] vector
References: Shuster, M.D., Efficient Algorithms for Spin-Axis Attitude Determination, The Journal of the Astronautical Sciences, Vol. XXXI, No. 2, April-June, 1983, pp. 237-249.
References and(), set(), Unit(), and vector().
SolutionWindow()
function SolutionWindow ()
Form
SolutionWindow
Inputs
 None
Outputs
 None
References and(), get(), and SolutionWindow().
Referenced by SAADMain(), and SolutionWindow().
SunCone()
function SunCone (in uSun, in rAI, in decI, in beta)
If there are no outputs it creates a plot.
Form
 [rA, dec] = SunCone( uSun, rAI, decI, beta )
Inputs
 uSun         (3,1)     Sun Vector
 rAI          (1,1)     Nominal right ascension (rad)
 decI         (1,1)     Nominal declination (rad)
 beta         (1,1)     Sun angle (rad)
Outputs
 rA           (1,1)     Nearest Right Ascension (rad)
 dec          (1,1)     Nearest Declination  (rad)
References and(), Cone(), Cross(), length(), NewFig(), RaDec2U(), U2RADec(), Unit(), XLabelS(), and YLabelS().
SunData()
function SunData (in usun, in uspin, in quant, in qtype, in onesigma, in bias)
This computes the angle between the sun and the spin-axis.
Form
 sa = SunData( usun, uspin, quant, qtype, onesigma, bias )
Inputs
 usun         (3,n)     Unit sun vector
 uspin        (3,1)     Unit spin axis vector
 quant        (1,1)     Quantization
 qtype        (1,:)     Type of quantization-either 'round' or 'truncate'
 onesigma     (1,1)     One sigma noise
 bias         (1,1)     Sensor bias
Outputs
 sa           (1,n)     The angle between the sun line and the spin axis
References and(), Unit(), vector(), and zeros().
Referenced by ADGen().
ZCull()
function ZCull (in ra, in dec, in g, in ue, in us, in er, in der, in zh, in Wh)
Eliminates horizon sensor measurements whose corresponding estimated measurement is a complex number because the |arcosine| > 1
Form
 [ue, us, er, zh, Wh, zc, Wc] = ZCull( ra, dec, g, ue, us, er, der, zh, Wh )
Inputs
 ra                     Right Ascension
 dec                    Declination
 g                      Cant angle
 ue                     Nadir vector
 us                     Sun vector
 er                     Earth radius
 der                    Delta earth radius
 zh                     Measurements
 Wh                     Chordwidths
Outputs
 ue                     Nadir vector
 us                     Sun vector
 er                     Earth radius
 der                    Delta earth radius
 zh                     Measurements
 Wh                     Chordwidths
 zc                     Culled measurements
 Wc                     Culled chordwidths
References er(), Measurements(), Nadir(), and vector().