PSS MATLAB Toolboxes: CubeSat Functions
CubeSat Functions
CubeSat Module
The CubeSat module functions.
Directories
directory Actuators
Actuator models, including a cold gas propulsion system.
directory AttitudeControl
Attitude control functions with wheels and magnetic torquers. Also disturbance and momentum unloading analysis.
directory Communications
Link analysis along an orbit.
directory MissionPlanning
Find time windows for observations and visualize sensor fields of view with cones. Support for predefined attitude profiles and repeating ground tracks.
directory Modeling
Various CubeSat geometry and inertia models.
directory Power
CubeSat solar power model.
directory Simulation
Simulation functions and combined RHS including environment, disturbances, and attitude and orbit dynamics.
directory Thermal
Isothermal and thermal matrix models.
directory Utilities
CubeSat utilities.
directory Visualization
Plotting and graphics functions. Visualize the simple CubeSat area model.
Description
Functions
function AddThermalConductivity (in d, in i, in j, in k)
Add a thermally conductive path between cubesat faces.
function AttitudeControlSimRWA (in qEB0, in wB0, in qEBDes, in t, in inrBody, in inrWhl, in maxRate, in control)
Simulate a rigid body with 3-axis attitude control.
function AttitudeProfile (in d, in varargin)
Build an attitude profile consisting of multiple overlapping modes.
function CADToSimParameters (in fileName, in batteryCapacity, in powerConversionEff)
Convert CAD model to CubeSat arrays.
function CubeSatAero (in p, in d)
Aerodynamic model for a CubeSat.
function CubeSatAttitude (in d, in r, in v)
Returns the CubeSat attitude quaternion from ECI to body.
function CubeSatDisturbanceAnalysis (in d, in q, in r, in v, in jD)
CubeSat disturbance analysis from batch data using RHSCubeSat.
function CubeSatEnvironment (in x, in t, in d)
Environment calculations for the CubeSat dynamical model.
function CubeSatFaces (in type, in rear)
Returns the faces along each axis of a linear CubeSat.
function CubeSatModel (in type, in d, in frameOnly)
Generate vertices and faces for a CubeSat model.
function CubeSatPowerAnalysis (in d, in q, in r, in jD)
CubeSat power analysis from batch orbit data.
function CubeSatPropulsion (in mass, in p, in d)
Returns the force, torque and mass flow for a cold gas system.
function CubeSatRadiationPressure (in p, in d)
Radiation pressure model for a CubeSat around the Earth.
function CubeSatThermalMatrix (in type, in kEdge, in kCore, in node)
Generates a 7 node CubeSat thermal matrix.
function DrawCubeSat (in v, in f, in d, in h)
Draw a CubeSat with surface normals.
function DrawCubeSatSolarAreas (in d)
Visualize the solar cell area for the CubeSat.
function DrawSpacecraftInOrbit (in jD0, in orbit, in gSC, in qEB, in planet, in cone, in gps)
Draw the Earth, CubeSat model, orbit, sensor cone(s), and GPS constellation.
function DrawSpacecraftStruct ()
Create the structure needed by DrawSpacecraftInOrbit.
function FindTimeWindows (in t, in x, in lim)
Find time windows when elements of vector x are within specified range.
function FOrbitMultiSpacecraft (in t, in x, in d)
Multispacecraft orbit model designed to work with ode113.
function GroundTrack (in r, in t, in jD0, in planet, in gS)
Plot an orbit track.
function InertiaCubeSat (in type, in mass)
Compute the inertia of a CubeSat.
function InertiaTubeSat (in l, in mass)
Compute the inertia of a TubeSat.
function IsothermalCubeSatSim (in d, in r, in q, in jD, in t0)
An isothermal CubeSat simulation using Euler integration.
function LatLonPlot (in lat, in lon, in tol, in varargin)
Plot latitude vs.
function LinkOrbitAnalysis (in r, in jD, in d)
Link analysis computing bit error probability along an orbit.
function LoadOBJModel (in file, in path, in kScale)
Load a Wavefront OBJ file.
function MagneticControl (in b, in tDemand, in u, in c)
Implement instantaneous magnetic control with torquers.
function MomentumUnloading (in b, in gain, in h)
Compute the torque from a magnetic momentum unloading system.
function ObservationTimeWindows (in orbit, in targets, in jD, in horizon, in fOV, in minEl, in doPlot)
Generate a set of observation time windows for each lat/lon target.
function ObservationTimeWindowsPlot (in track, in obs)
Plot ground track and observation windows for a satellite and targets.
function PackageOrbitDataForPlayback (in jD0, in t, in r, in v, in coneFOV, in conePitch, in coneAzimuth, in inputFrame)
Package orbit data into a structure for use in PlaybackOrbitSim.
function PlaybackOrbitSim (in time, in object, in planet, in style)
Play back an orbit simulation of multiple objects with sensor cones.
function PlotOrbit (in r, in t, in jD0)
Plot the orbital state in 3D with an Earth map.
function RapidSwath (in lat, in lon, in h, in halfAngleFOV, in pitch, in azimuth, in Rp)
Compute the intersection curve between a sensor cone and spherical planet.
function ReactionWheelDesign (in d)
Design a reaction wheel to meet input requirements.
function RepeatGroundTrack (in g, in doplot)
Design a repeat ground-track orbit.
function RHSCubeSat (in x, in t, in d)
Right-hand-side for a CubeSat orbit and attitude dynamical model.
function RHSIsothermalCubeSat (in t0, in ignoredArg, in d, in p)
An isothermal CubeSat model dynamical right-hand-side.
function RHSMomentum (in ignoredArg, in ignoredArg, in torque)
RHS for momentum in the inertial frame.
function RVWithJ2 (in el, in jD0, in tEnd, in j2)
Propagate orbital elements with J2 gravity term.
function SolarCellPower (in d, in pSun)
Compute the power generated by a solar power system.
function TubeSatDefaultDataStructure (in l, in jD)
Default data structure for TubeSat model.
function TubeSatFaces (in l, in ignoredArg)
Returns the faces along each axis of a cylindrical TubeSat.
function TubeSatModel (in l)
Generate vertices and faces for a TubeSat model.
function WrapSegments (in x, in tol)
Separate a wrapped vector into a series of segments in cells.
Function Documentation
AddThermalConductivity()
function AddThermalConductivity (in d, in i, in j, in k)
Ensures that the thermal conductivity matrix, d.k, is consistent.
Form
 d = AddThermalConductivity( d, i, j, k )
Inputs
 d      (.)     Thermal data structure
                  .mass       (1,6) or (1,1) face mass or total mass
                  .uSurface   (3,6) Surface unit vectors
                  .alpha      (1,6) Absorptivity
                  .epsilon    (1,6) Emissivity
                  .area       (1,6) Area
                  .cP         (1,1) Specific heat
                  .powerTotal (1,6) or (1,1) Internal power (W)
                  .k          (6,6) Thermal conductivity (W/deg-K)
 i      (1,1)    Index of one of the nodes (1-6)
 j      (1,1)    Index of the other node (1-6)
 k      (1,1)    The thermal conductivity value (Watts per Kelvins)
Outputs
 d      (.)    Thermal data structure with the adjusted d.k thermal
                  conductivity matrix
References AddThermalConductivity(), and StructToText().
Referenced by AddThermalConductivity().
AttitudeControlSimRWA()
function AttitudeControlSimRWA (in qEB0, in wB0, in qEBDes, in t, in inrBody, in inrWhl, in maxRate, in control)
Form
 data = AttitudeControlSimRWA( qEB0, wB0, qEBDes, t, inrBody, inrWhl, ...
 maxRate, control );
Inputs
 qEB0       (4,1)    Initial ECI to Body quaternion
 qEBDes     (4,:)    Desired ECI to Body quaternion over time
 t          (1,:)    Time vector (sec)
 inrBody    (3,3)    Inertia matrix for the rigid body
 inrWhl     (3,1)    Wheel inertias. Enter a scalar if all the same.
 maxRate    (1,1)    Maximum slew rate (rad/s)
 control     (.)     Control data structure with fields:
                      .a      A matrix of discretestate space controller
                      .b      B matrix of discretestate space controller
                      .c      C matrix of discretestate space controller
                      .d      D matrix of discretestate space controller
                      .tSamp  Sampling time (sec)
Outputs
 data        (.)     Data structure with fields:
                     .t      (1,:)    Time vector (intervals at tSamp)
                     .qEB    (4,:)    ECI to Body quaternion
                     .wB     (3,:)    Body rate (rad/s)
                     .torque (3,:)    Body torque (Nm)
                     .wW     (3,:)    Wheel rates (rad/s)
                     .power  (3,:)    Required power draw (Watts)
References abs(), AttitudeControlSimRWA(), AU2Q(), C2DelZOH(), Demo(), FRB(), length(), PIDMIMO(), Q2AU(), QMult(), QPose(), quaternion(), Rename(), RK4(), scalar(), vector(), and zeros().
Referenced by AttitudeControlSimRWA().
AttitudeProfile()
function AttitudeProfile (in d, in varargin)
The first mode listed is the nominal mode. The attitude is defined according to this pointing mode by default. Additional modes are optional.
Each mode defines the ECI-to-Body quaternion through the combination of primary and secondary alignments. The primary alignment directly aligns a body vector with an inertial target. The secondary alignment rotates about that primary body vector to align a second body vector with a second inertial vector as closely as possible.
Each alignment can be defined as one of the following types, with the associated target data.
 #  Alignment type      Target data
 ====================================================================
 1    'sun'                -
 2    'nadir'              -
 3    'orbitnormal'        -
 4    'latlon'             [lat;lon]   Target latitude and longitude
 5    'lvlh'               [x;y;z]     Target LVLH direction
 6    'ueci'               [x;y;z]     Target ECI direction
 7    'reci'               [x;y;z]     Target ECI point
Form
 d = AttitudeProfileBuilder( d, mode1, mode2, mode3, ... );
Inputs
 d       (.)   Data structure with orbit and time information
                  .jD0        (1,1)    Epoch Julian date
                  .t          (1,:)    Time vector from jD0 (sec)
                  .r          (3,:)    ECI position  (km)
                  .v          (3,:)    ECI velocity (km/s)
 mode1   (.)   Nominal Attitude Mode with fields:
 .type1      '...'    Primary alignment type
 .body1      (3,1)    Primary body vector to align
 .target1    (:,1)    Primary Target
 .type2      '...'    Secondary alignment type
 .body2      (3,1)    Secondary body vector to align
 .target2    (:,1)    Secondary target
 mode2   (.)   Same as nominal mode but with additional field:
 .window     (:,2)    Time windows to use this mode
 mode3
 mode4
 ...
Outputs
 d       (.)   Data structure with added quaternion, and alignment info
                  .jD0        (1,1)    Epoch Julian date
                  .t          (1,:)    Time vector from jD0 (sec)
                  .r          (3,:)    ECI position  (km)
                  .v          (3,:)    ECI velocity (km/s)
                  .el         (1,6)    Initial orbital elements
                  .q          (4,:)    ECI-to-body quaternion
                  .type1      (1,:)    # for primary alignment type
                  .type2      (1,:)    # for secondary alignment type
                  .rot        (1,:)    Rotation angle about primary body axis
                  .sep        (1,:)    Separation angle from secondary target
References and(), AttitudeProfile(), Date2JD(), ObservationTimeWindows(), quaternion(), RVFromKepler(), and vector().
Referenced by AttitudeProfile(), AttitudeProfilePlugIn(), and AttitudeProfileWithCon().
CADToSimParameters()
function CADToSimParameters (in fileName, in batteryCapacity, in powerConversionEff)
The resulting data structure can be used by the dynamical model.
If the CAD model has 'solar panel' components they will be converted to the power model. The mapping is:
 power.electricalConversionEfficiency to solarCellEff
 power.powerOn                        to consumption
Form
 d = CADToSimParameters( fileName, batteryCapacity, powerConversionEff )
Inputs
 fileName            (1,:)   CAD mat file name
 batteryCapacity     (1,1)   Battery capacity (J)
 powerConversionEff (1,1)   Power conversion efficiency
Outputs
 d          (.)    Data structure including
                     .mass       (1,1)  Total CubeSat Mass (kg)
                     .inertia    (3,3)  Inertia tensor matrix
                     .surfData    (.)   Surface properties
                       .cM              (3,1)  Center of mass (m)
                       .area            (1,n)  Area for each of n faces (m^2)
                       .nFace           (3,n)  Unit normal for each face
                       .r               (3,n)  Position of centroid of each
                                             face (m)
                       .cD              (1)    Coefficient of drag
                       .sigma           (3,n)  Optical coefficients
                     .power      (.)    Power data structure
                       .solarCellNormal (3,N) Normal vector of each solar cell
                       .solarCellArea   (1,N) Area of each cell (m^2)
                       .solarCellEff    (1,N) Efficiency of each cell
                       .consumption     (1,1) Total power consumption (W)
                       .batteryCapacity (1,1) Battery capacity (J)
                       .effPowerConversion (1,1) Conversion efficiency
See also
: RHSCubeSat, SolarCellPower
References CADToSimParameters(), CubeSatAero(), Demo(), DupVect(), length(), Normal(), RHSCubeSat(), SolarCellPower(), Unit(), and vector().
Referenced by CADToSimParameters().
CubeSatAero()
function CubeSatAero (in p, in d)
Contains a built-in demo for a 1U CubeSat in a 6500 km orbit. Also contains an option to retrieve the default data structure. Note that it is most efficient to combine the areas into one per face for simple CubeSat models - i.e. 6 areas.
The attitude model in CubeSatAttitude will be used if p.q is empty.
Form
 [force, torque] = CubeSatAero( p, d )
 d = CubeSatAero     % data structure
 CubeSatAero         % demo for LEO orbit with LVLH alignment
Inputs
 p         (.)    Profile data structure
                  .r    (3,1) ECI position
                  .v    (3,1) ECI velocity
                  .q    (4,1) ECI to body quaternion
                  .vRel (3,1) ECI velocity relative to the earth (km/s)
                  .rho  (1,1) Atmospheric density (kg/m^3)
 d         (.)    Aero data structure
                  .cD         (1,1) Drag coefficient
                  .nFace      (3,:) Face outward unit normals
                  .rFace      (3,:) Face vectors with respect to the origin
                  .cM         (3,1) Center of mass with respect to the orgin
                  .area       (1,:) Area of each face (m^2)
                  .att         (.)  Attitude data structure
Outputs
 force    (3,1)   ECI force (N)
 torque   (3,1)   Body fixed torque (Nm)
See also
CubeSatFaces, CubeSatAttitude
References CubeSatAero(), CubeSatAttitude(), CubeSatFaces(), Demo(), Plot2D(), quaternion(), RVFromKepler(), TimeLabl(), and zeros().
Referenced by AeroDragForce(), CADToSimParameters(), CubeSatAero(), CubeSatDisturbanceAnalysis(), FOrbitMultiSpacecraft(), and RHSCubeSat().
CubeSatAttitude()
function CubeSatAttitude (in d, in r, in v)
There are two options. One is ECI in which case it just passes out d.qECIToBody. For LVLH frame the routine computes the ECI to LVLH quaternion from the entered r and v and multiplies that times qLVLHToBody, to produce the qECIToBody.
This function is used when you don't want to simulate attitude dynamics. There is an option to retrieve the default data structure. % This sets both qLVLHToBody and qECIToBody to [1;0;0;0].
Form
 d = CubeSatAttitude;   % data structure
 q = CubeSatAttitude( d, r, v )
Inputs
 d         (.)    Data structure
                  .type        (1,:) 'eci' or 'lvlh'
                  .qLVLHToBody (4,1) Quaternion from LVLHToBody
                  .qECIToBody  (4,1) Quaternion from ECI to body frame
 r        (3,1)   ECI position vector
 v        (3,1)   ECI velocity vector
Outputs
 q        (4,1)   qECIToBody
References and(), and quaternion().
Referenced by CubeSatAero(), CubeSatEnvironment(), CubeSatLunarEnvironment(), CubeSatPropulsion(), CubeSatRadiationPressure(), and FOrbitMultiSpacecraft().
CubeSatDisturbanceAnalysis()
function CubeSatDisturbanceAnalysis (in d, in q, in r, in v, in jD)
Compute the drag, magnetic, gravity gradient, and optical disturbances. The environment is computed using AtmJ70, BDipole, and SunV1. AtmDens2 can be used instead by supplying an empty matrix for d.atm.
The built-in demo computes the disturbances on a 3U satellite for one day. The center of mass is assumed to be offset from the geometric center of the spacecraft by a few cm. Note the growth in momentum. the gravity gradient torque is zero in the demo because the attitude entered is perfect LVLH and the inertia is symmetric.
Form
 [tT, fECI, h, hECI, f, t, powers] = CubeSatDisturbanceAnalysis( d, q, r, v, jD )
 CubeSatDisturbanceAnalysis  % demo
Inputs
 d        (.)      Data structure from RHSCubeSat
 q       (4,:)     Quaternion, ECI to body
 r       (3,:)     Position vector
 v       (3,:)     Velocity vector
 jD      (1,:)     Julian dates
Outputs
 tT      (3,:)   Torque in body (Nms)
 fECI    (3,:)   Force in ECI (N)
 h       (3,:)   Body momentum (Nms)
 hECI    (3,:)   ECI momentum (Nms)
 torque   (.)    Torque structure
                   .total   (3,:)  Torque in body frame
                   .aero    (3,:)  Aerodynamic torque
                   .mag     (3,:)  Magnetic torque
                   .optical (3,:)  Optical torque
                   .gg      (3,:)  Gravity gradient torque
 force    (.)    Force structure
                  .total   (3,:)  Force in ECI frame
                  .aero    (3,:)  Aerodynamic force
                  .optical (3,:)  Optical force
 powers (1,:)   Total power from the solar cells (W)
See also
CubeSatAero, CubeSatRadiationPressure, GravityGradientFromR,
 RHSCubeSat
References and(), AtmDens2(), AtmJ70(), AU2Q(), AxesCart(), BDipole(), CubeSatAero(), CubeSatDisturbanceAnalysis(), CubeSatRadiationPressure(), Date2JD(), Demo(), dists(), Figui(), GravityGradientFromR(), length(), OpticalSurfaceProperties(), Period(), Plot2D(), Plot3D(), PlotPlanet(), QLVLH(), QMult(), QTForm(), quaternion(), Residual(), RHSCubeSat(), RVFromKepler(), SunV1(), TimeLabl(), vector(), and zeros().
Referenced by CubeSatDisturbanceAnalysis().
CubeSatEnvironment()
function CubeSatEnvironment (in x, in t, in d)
Uses the J70 atmosphere model or AtmDens2 if the data required by J70 is absent. Computes sun location with SunV1 and accounts for eclipses from the Earth via Eclipse. All environment constants including gravity are defined here.
Form
 env = CubeSatEnvironment             % data structure
 env = CubeSatEnvironment( x, t, d )
Inputs
 x        (14,1)  State, [r;v;q;w;b]
 t         (1,1)  Time, sec
 d          (.)   Data structure
                   .jD0          Julian date of epoch
                   .att      (.) Attitude
                   .atm      (.) optional; empty to skip J70 and use AtmDens2
                   .surfData (.) optional; empty to skip drag/optical calcs
Outputs
 env        (.)   Environmental data
                  .r            (3,1) ECI position (km)
                  .v            (3,1) ECI velocity (km/s)
                  .q            (4,1) ECI to body quaternion
                  .mu           (1)   Gravitational constant (km3/s2)
                  .radiusPlanet (1)   Radius of the planet (km)
                  .vRel         (3,1) Velocity relative to the atmosphere (km/s)
                  .rho          (1)   Atmospheric density (kg/m3)
                  .radiation    (1)   Planetary radiation (W/m2)
                  .albedo       (1)   Planet bond albedo fraction
                  .uSun         (3,1) Sun unit vector (ECI)
                  .rSun         (1)   Sun distance (km)
                  .solarFlux    (1)   Solar flux at position (W/m2)
                  .nEcl         (1)   Eclipse fraction (source intensity, 0-1)
                  .bField       (3,1) Magnetic field, ECI frame (T)
See also
SunV1, Eclipse, AtmDens2, AtmJ70, BDipole
References and(), AtmDens2(), AtmJ70(), BDipole(), CubeSatAttitude(), CubeSatEnvironment(), ECIToEF(), Eclipse(), isempty(), JD2T(), Mag(), quaternion(), Skew(), SunV1(), and vector().
Referenced by CubeSatEnvironment(), CubeSatRadiationPressure(), FOrbitMultiSpacecraft(), and RHSCubeSat().
CubeSatFaces()
function CubeSatFaces (in type, in rear)
1U means a 10 cm cube. The x and y faces are always the long faces. Alternatively a custom CubeSat may be specified by the U along each axis, such as [1 2 3] for a 2x3 6U CubeSat.
Form
 [a,n,r] = CubeSatFaces( type, rear )
Inputs
 type     (1,:)   'nU' n may be a fraction, i.e. 1.5
                    or for a custom CubeSat, enter 3 axes: [x y z], as
                    in [1 2 3] (U)
 rear     (1,1)   Flag to include the rear faces, i.e. -X, -Y, -Z
Outputs
 a    (1,3) or (1,6)   Areas [aX aY aZ]
 n    (3,3) or (3,6)   Outward normals
 r    (3,3) or (3,6)   Location from geometric center of spacecraft
References and(), CubeSatFaces(), CubeSatModel(), Demo(), DrawCubeSat(), and length().
Referenced by CubeSatAero(), CubeSatFaces(), InertiaCubeSat(), and RHSIsothermalCubeSat().
CubeSatModel()
function CubeSatModel (in type, in d, in frameOnly)
If there are no outputs it will generate a plot with surface normals, or you can draw the cubesat model using patch:
 patch('vertices',v,'faces',f,'facecolor',[0.5 0.5 0.5]);
type can be '3U' or [3 2 1] i.e. a different dimension for x, y and z.
Type CubeSatModel for a demo of a 3U CubeSat.
This function will populate dRHS for use in RHSCubeSat. The surface data for the cube faces will be 6 surfaces that are the dimensions of the core spacecraft. Additional surfaces are added for the deployable
solar panels. Solar panels are grouped into wings that attached to the edges of the CubeSat.
The function computes the inertia matrix, center of mass and total mass. The mass properties of the interior components are computed from total mass and center of mass.
If you set frameOnly to true (or 1), v and f will not contain the walls. However, dRHS will contain all the wall properties.
Form
 d            = CubeSatModel( 'struct' )
 [v, f]       = CubeSatModel( type, t )
 [v, f, dRHS] = CubeSatModel( type, d, frameOnly )
 Demo:
 CubeSatModel
Inputs
 type        (1,:) 'nU' where n may be any number, or [x y z]
 d            (.)  Data structure for the CubeSat
         .thicknessWall          (1,1) Wall thickness (mm)
         .thicknessRail          (1,1) Rail thickness (mm)
         .densityWall            (1,1) Density of the wall material (kg/m3)
         .massComponents         (1,1) Interior component mass (kg)
         .cMComponents           (1,1) Interior components center of mass
         .sigma                  (3,6) [absorbed; specular; diffuse]
         .cD                     (1,6) Drag coefficient
         .solarPanel.dim         (3,1) [side attached to cubesat, side perpendicular, thickness]
         .solarPanel.nPanels     (1,1) Number of panels per wing
         .solarPanel.rPanel      (3,w) Location of inner edge of panel
         .solarPanel.sPanel      (3,w) Direction of wing spine
         .solarPanel.cellNormal  (3,w) Wing cell normal
         .solarPanel.sigmaCell   (3,1) [absorbed; specular; diffuse] coefficients
         .solarPanel.sigmaBack   (3,1) [absorbed; specular; diffuse]
         .solarPanel.mass        (1,1) Panel mass
    - OR -
 t                               (1,1) Wall thickness (mm)
 frameOnly   (1,1) If true just draw the frame, optional
Outputs
 v      (:,3) Vertices
 f      (:,3) Faces
 dRHS    (.)  Data structure for the function RHSCubeSat
Reference: CubeSat Design Specification (CDS) Revision 9
References AddMass(), and(), Box(), CubeSatModel(), Demo(), DupVect(), Inertias(), Initialize(), Panel(), RHSCubeSat(), set(), and Wing().
Referenced by AttitudeProfileVis(), CubeSatFaces(), CubeSatModel(), DrawCubeSat(), DrawSpacecraftInOrbit(), and DrawSpacecraftStruct().
CubeSatPowerAnalysis()
function CubeSatPowerAnalysis (in d, in q, in r, in jD)
Simple batch calculation of power. Uses the same ephemeris model as RHSCubeSat.
The built-in demo simulates a 1U satellite for one orbit.
Form
 [power] = CubeSatPowerAnalysis( d, q, r, jD )
 CubeSatPowerAnalysis  % demo
Inputs
 d        (.)      Data structure from RHSCubeSat or SolarCellPower
 q       (4,:)     Quaternion, ECI to body
 r       (3,:)     Position vector (for eclipse calculations)
 jD      (1,:)     Julian dates
Outputs
 power   (1,:)     Power produced by the solar cells
References AddFillToPlots(), CubeSatPowerAnalysis(), Date2JD(), Demo(), Eclipse(), Initialize(), length(), Plot2D(), QForm(), QLVLH(), RHSCubeSat(), RVFromKepler(), SolarCellPower(), Step(), SunV1(), TimeLabl(), and vector().
Referenced by CubeSatPowerAnalysis().
CubeSatPropulsion()
function CubeSatPropulsion (in mass, in p, in d)
Will call CubeSatAttitude for the attitude model if p.q is empty.
Form
 [force, torque, mDot] = CubeSatPropulsion( mass, p, d )
Inputs
 mass     (1,1)   Total system mass
 p         (.)    Data structure
                  .r    (3,1) ECI position
                  .v    (3,1) ECI velocity
                  .q    (4,1) ECI to body quaternion
 d         (.)    Data structure
                  .gas            (1,:) Gas name
                  .throatArea     (1,1) Area of throat (m^2)
                  .volumeTank     (1,1) Tank volume (m^3)
                  .temperature    (1,1) Tank temperature (deg-K)
                  .expansionRatio (1,1) Expansion ratio of nozzle
                  .rNozzle        (3,n) Position of thruster (m)
                  .uNozzle        (3,n) Thrust unit vector
                  .cM             (3,1) Center-of-mass (m)
                  .pulsewidthFraction (1,n)
                  .pRegulator     (1,1) Regulator pressure (N/m^2)
                  .att             (.)  Attitude data structure
Outputs
 force    (3,1)   ECI Force vector (N)
 torque   (3,1)   Torque vector (N)
 mDot     (1,1)   Mass flow rate (kg/s)
See also
GasProperties, CubeSatAttitude
References and(), Cross(), CubeSatAttitude(), CubeSatPropulsion(), Demo(), GasProperties(), IdealRkt(), isempty(), Pressure(), QTForm(), quaternion(), vector(), and zeros().
Referenced by CubeSatPropulsion(), and FOrbitMultiSpacecraft().
CubeSatRadiationPressure()
function CubeSatRadiationPressure (in p, in d)
Includes solar pressure, earth radiation pressure, and earth albedo. Has a built-in demo. Retrieve a default data structure by calling with no inputs, or append the additional fields to an existing structure. Set d.planet to 0 (false) to ignore planetary disturbances and calculate only solar pressure.
 Forms:
 [force, torque] = CubeSatRadiationPressure( p, d )
 d = CubeSatRadiationPressure       % default d
 d = CubeSatRadiationPressure( d )  % add needed fields to d
 CubeSatRadiationPressure           %
Inputs
 p         (.)    Data structure from CubeSatEnvironment
                  .r    (3,1) ECI position
                  .v    (3,1) ECI velocity
                  .q    (4,1) ECI to body quaternion
                  .uSun (3,1) ECI sun unit vector
                  .solarFlux (1,1) Solar flux at position (W/m2)
                  .nEcl      (1,1) Normalized source intensity from Eclipse
                  .radiation (1,1) Planet radiation
                  .albedo    (1,1) Planet albedo fraction
                  .radiusPlanet (1,1) Planet radius (km)
 d         (.)    Surface data structure
                  .nFace      (3,:) Face outward unit normals
                  .rFace      (3,:) Face vectors with respect to the origin
                  .cM         (3,1) Center of mass with respect to the orgin
                  .area       (1,:) Area of each face
                  .sigma      (3,:) Radiation coefficients [absorbed;
                                    specular; diffuse]
                  .planet     (1,1) Flag for planetary contributions
                  .att         (.)  Attitude data structure
Outputs
 force    (3,1)   ECI force (N)
 torque   (3,1)   Body fixed torque (Nm)
See also
SolarF, CubeSatAttitude
References and(), CubeSatAttitude(), CubeSatEnvironment(), CubeSatRadiationPressure(), Demo(), Eclipse(), quaternion(), SolarF(), and vector().
Referenced by CubeSatDisturbanceAnalysis(), CubeSatRadiationPressure(), FOrbitMultiSpacecraft(), RHSCubeSat(), and RHSLunarMission().
CubeSatThermalMatrix()
function CubeSatThermalMatrix (in type, in kEdge, in kCore, in node)
The CubeSat has 6 faces and a core node that represents everything else in the CubeSat.
kEdge is a unit conductivity in Watts/mm deg-K
kCore is W/deg-K
x, y, z are the edge lengths in mm.
The default node convention is:
 node = {'+x','+y','+z','-x','-y','-z'};
 node 7 is always the core
Type CubeSatThermalMatrix for a 3U CubeSat demo. The x faces have the short edges.
Form
 k = CubeSatThermalMatrix( type,kEdge,kCore,node )
Inputs
 type    (1,:) 'nU' n may be a fraction, i.e. 1.5
                    or for a custom CubeSat, enter 3 axes: [x y z], as
                    in [1 2 3] (U)
 kEdge   (1,1) Edge conductivity (W/m/deg-K)
 kCore   (1,1) Conductivity to the core node (W/deg-K)
 node    {1,6} Definitions of node '+x' '-x' etc. *optional
Outputs
 k     (7,7) Conductivity matrix
References and().
DrawCubeSat()
function DrawCubeSat (in v, in f, in d, in h)
The vertices and faces can be obtained from CubeSatModel. If d or d.surfData is input after the faces, it will draw surface normals.
Form
 h = DrawCubeSat( v, f, d, h )
 DrawCubeSat;               % Demo
Inputs
 v      (:,3)   Vertices
 f      (:,3)   Faces
 d       (.)    Data structure from the function RHSCubeSat
                .surfData  (.)  Surface data
                .nFace    (3,n) Face normals
                .rFace    (3,n) Face locations (m)
 h     (1,1)   Figure handle (optional)
Outputs
 h     (1,1)   Figure handle
See also
CubeSatModel, RHSCubeSat
References and(), CubeSatModel(), Demo(), DrawCubeSat(), isempty(), NewFig(), RHSCubeSat(), set(), TitleS(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by CubeSatFaces(), DrawCubeSat(), TubeSatFaces(), and TubeSatModel().
DrawCubeSatSolarAreas()
function DrawCubeSatSolarAreas (in d)
Plots the solar cell areas and normals from the power substructure. You may pass in the full RHS data structure or the power substructure.
Form
 h = DrawCubeSatSolarAreas( d )
 DrawCubeSatSolarAreas;          % Demo
Inputs
 d      (.)     Model data structure from RHSCubeSat
                .power  (.)  Power data, see also SolarCellPower
                    .solarCellArea    (1,:) Total cell area (m^2)
                    .solarCellNormal  (3,:) Unit normal vector to the cell face
Outputs
 h     (1,1)   Figure handle
See also
SolarCellPower, RHSCubeSat
References and(), Demo(), DrawCubeSatSolarAreas(), length(), Mag(), NewFig(), RHS(), RHSCubeSat(), SolarCellPower(), TitleS(), Unit(), vector(), XLabelS(), YLabelS(), and ZLabelS().
Referenced by DrawCubeSatSolarAreas().
DrawSpacecraftInOrbit()
function DrawSpacecraftInOrbit (in jD0, in orbit, in gSC, in qEB, in planet, in cone, in gps)
The spacecraft can be left out (empty) to just view the cones. If GPS satellites are requested the elements will be loaded from Celestrak, requiring an internet connection.
Form
 out = DrawSpacecraftInOrbit( jD0, orbit, gSC, qEB, planet, cone, gps )
Inputs
 jD0           (1,1)    Julian date epoch.
 orbit         (1,6)    Orbital elements [a,i,W,w,e,M]
 gSC           (.)      Data structure array or mat-file that stores it.
                        Each element of array is a component in the body.
                        .name    String name of component
                        .v       Vertices
                        .f       Faces
                        .scale   Scale
                        .color   Color of each component
                        .alpha   Transparency (0-1) of each component
 qEB           (4,1)    ECI to Body quaternion. Uses [1;0;0;0] if not
                         entered.
 planet         (:)     Name of planet file to use (e.g. 'Earth')
 cone           (.)     Cone geometry. Includes:
                        .fov     Field of view
                        .pitch   Pitch angle from nadir
                        .azimuth Azimuth angle from north
 gps           (1,1)    Flag to include GPS constellation or not.
Outputs
 out            (.)     Data structure with satellite Earth fixed
                        position, cone
See also
: PlaybackOrbitSim.m
References and(), AU2Q(), CameraControls(), Cone(), Cross(), CubeSatModel(), Date2JD(), Dot(), DrawSpacecraftInOrbit(), DupVect(), ECEFToLLA(), ECIToEF(), Initialize(), isempty(), JD2T(), length(), LLAToECEF(), Mag(), Map(), Period(), PlaybackOrbitSim(), PropagateTLECommonTime(), QForm(), QMult(), QRand(), QTForm(), quaternion(), RapidSwath(), RVFromKepler(), set(), SunV1(), TerminatorLine(), Unit(), vector(), and zeros().
Referenced by DrawSpacecraftInOrbit(), and DrawSpacecraftStruct().
DrawSpacecraftStruct()
function DrawSpacecraftStruct ()
Replace v and f with the vertex/face information for your model.
Form
 g = DrawSpacecraftStruct()
Inputs
 None.
Outputs
 g        (.)    Data structure
                    .name    String name of spacecraft
                    .v     (n,3)  Vertices
                    .f     (n,3)  Faces
                    .scale (1,1)  Scale
                    .color (1,3)  Color spacecraft
                    .alpha (1,1)  Transparency (0-1)
See also
: DrawSpacecraftInOrbit
References and(), CubeSatModel(), and DrawSpacecraftInOrbit().
FindTimeWindows()
function FindTimeWindows (in t, in x, in lim)
Type FindTimeWindows for a demo.
Form
 window = FindTimeWindows( t, x, lim );
Inputs
 t           (1,N)   N time points
 x           (M,N)   Set of M variables across N time points
 lim         (1,2)   Time window limits (min,max)
Outputs
 window       (.)    Data structure array with window information.
                     Each element "i" of this array is for a different
                     row of the x matrix. Fields are:
                .nObs:       (1,1)     Number of observations (windows)
                .window:     (nObs,2)  Each row is a new time window
                .time:       {1,nObs}  Time vectors from t inside each window
                .x:          {1,nObs}  Data vectors from x(i,:) inside each window
                .indexStart  (1,nObs)  Starting time index for window
                .indexEnd    (1,nObs)  Ending time index for window
See also
: ObservationTimeWindows
References FindTimeWindows(), and vector().
Referenced by FindTimeWindows().
FOrbitMultiSpacecraft()
function FOrbitMultiSpacecraft (in t, in x, in d)
You can include aerodynamic, radiation pressure and thrust models. Sun, earth, and moon perturbations are computed if the planet (Earth or Moon) is given. Uses SunV1 and MoonV1 for ephemeris.
Form
 d = FOrbitMultiSpacecraft             % data structure
 xDot = FOrbitMultiSpacecraft( t, x, d )
Inputs
 t                Time
 x       (7*n,1)  The state vector [r1;v1;m1;r2;v2;m2;...]
 d       (:)      Data structure array
                  .jD0                       (1,1)   Julian date at start
 This is only needed for planetary disturbances
 and if a gravity model is entered:
 .planet                   (1,:)   Planet name, 'earth', 'moon'
 These are optional:
 .thrusterModel            (1,:)   Thrust function handle
 .thrusterData             (.)     Thrust data structure
 .opticalModel             (1,:)   Optical function handle
 .aeroModel                (1,:)   Aero function handle
 .surfData                 (.)     Surface data structure
 .gravityModel             (.)     Gravity model structure;
 default is point-mass.
 The following are only needed if you want J70, otherwise
 AtmDens2 will be used.
 .atm.aP                   (1,1)   Geomagnetic index 6.7 hours before the computation
 .atm.f                    (1,1)   Daily 10.7 cm solar flux (e-22 watts/m^2/cycle/sec)
 .atm.fHat                 (1,1)   81-day mean of f (e-22 watts/m^2/cycle/sec)
 .atm.fHat400              (1,1)   fHat 400 days before computation date
Outputs
 xDot    (7*n,1)  The state vector derivative [v1;r1Dot;m1Dot...]
See also
CubeSatEnvironment, ECIToPlanet, AGravityC, FOrbCart,
PlanetaryAccelerations CubeSatRadiationPressure, CubeSatAero
 CubeSatPropulsion
References AGravityC(), and(), APlanet(), AtmDens2(), AtmJ70(), BDipole(), Constant(), CubeSatAero(), CubeSatAttitude(), CubeSatEnvironment(), CubeSatPropulsion(), CubeSatRadiationPressure(), ECIToPlanet(), Eclipse(), EnvironmentStruct(), FOrbCart(), FOrbitMultiSpacecraft(), isempty(), JD2000(), length(), Mag(), MoonV1(), PlanetaryAccelerations(), QZero(), RHSCubeSat(), Skew(), SunV1(), Unit(), vector(), and zeros().
Referenced by FOrbitMultiSpacecraft().
GroundTrack()
function GroundTrack (in r, in t, in jD0, in planet, in gS)
Converts the inertial positions to planet-fixed.
Pass in the time array and the initial epoch. The epoch may be a Julian date or a datetime array. The initial position is marked with an 'o'. Ground stations are marked with 'x'.
You generate the planet data structure like this example; The replication of the image map is needed because the png is gray scale.
 p = imread('planet.png');
 p3(:,:,1) = p;
 p3(:,:,2) = p;
 p3(:,:,3) = p;
 planet.planetMap = p3;
 planet.radius = 1000;
 planet.name = 'MyPlanet';
Type GroundTrack for a demo showing an orbit around the Earth.
Form
 GroundTrack( r, t, jD0, planet, gS )
 GroundTrack( r, t, datetime, planet, gS )
Inputs
 r                (3*n,:) ECI position vectors (km)
 t                (1,:) Time array (sec)
 jD0              (1,1) Epoch Julian date
           -or-
 datetime         (1,6) [year month day hour minute seconds]
 planet           (1,:) Planet name (default is 'Earth')
 -or-
 (.)
 (1,:) name
 (:)   planetMap
 (:)   planetColorMap (optional)
 (1,1) radius (km)
 gS               (2,:) Ground stations [lat;lon] (deg)
Outputs
 h                (1,1) Figure handle
See also
ECIToPlanet, R2LatLon, Date2JD
References abs(), and(), Date2JD(), ECIToPlanet(), GroundTrack(), isempty(), JD2000(), length(), Map(), NewFig(), Period(), R2LatLon(), RVFromKepler(), XLabelS(), and YLabelS().
Referenced by GroundTrack().
InertiaCubeSat()
function InertiaCubeSat (in type, in mass)
This assumes the mass is uniformly distributed throught the volume. This is a good first cut.
Type InertiaCubeSat for a demo. See also CubeSatFaces.
If mass is omitted is selects the maximum mass for your CubeSat size, which is 1 kg per U.
Form
 inertia = InertiaCubeSat( type, mass )
Inputs
 type    (1,2)    '1U' '2U' '3U' or [x y z] with U of each side
 mass    (1,1)    Mass (kg)
Outputs
 inertia (3,3)    Inertia matrix (kg-m^2)
 mass    (1,1)    Mass (kg)
References and(), CubeSatFaces(), Demo(), InertiaCubeSat(), Inertias(), and length().
Referenced by InertiaCubeSat(), RHSGGRotational(), RHSLunarMission(), RWAMnvrSizing(), and RWASizing().
InertiaTubeSat()
function InertiaTubeSat (in l, in mass)
This assumes a cylindrical shape and the mass is uniformly distributed throught the volume. This is a good first cut.
Type InertiaTubeSat for a demo. See also TubeSatFaces.
Form
 inertia = InertiaTubeSat( type, mass )
Inputs
 l      (1,1)     Either (1,2,3,4) for single, double, triple or quad
 mass   (1,1)     Mass (kg)
Outputs
 inertia (3,3)     Inertia matrix (kg-m^2)
References and(), Demo(), Inertias(), InertiaTubeSat(), length(), scalar(), and TubeSatFaces().
Referenced by InertiaTubeSat(), and TubeSatDefaultDataStructure().
IsothermalCubeSatSim()
function IsothermalCubeSatSim (in d, in r, in q, in jD, in t0)
The entire spacecraft is assumed to be at the same temperature. The spacecraft temperature is computed over the given orbit.
Form
 IsothermalCubeSatSim -- demo
 t = IsothermalCubeSatSim( d, r, q, jD, t0 )
Inputs
 d       (.)      Data structure
                  .mass       (1,1) Total mass
                  .uSurface   (3,6) Surface unit vectors
                  .alpha      {1,6} Absorptivity
                  .epsilon    {1,6} Emissivity
                  .area       (1,6) Area
                  .cP         (1,1) Specific heat
                  .powerTotal (1,1) Internal power (W)
 r      (3,:)     Orbit
 q      (4,:)     Quaternion
 jD     (1,:)     Julian date
 t0     (1,1)     Initial Temperature( deg-K )
Outputs
 t      (1,:)     Temperature
See also
SunV1, Eclipse, RHSIsothermalCubeSat.
References Euler(), and IsothermalCubeSatSim().
Referenced by IsothermalCubeSatSim().
LatLonPlot()
function LatLonPlot (in lat, in lon, in tol, in varargin)
longitude nicely on existing figure
The wrapped longitude will not create lines across the plot. This does not create a figure but plots into the current axes. Type LatLonPlot for a demo.
Form
 [lat2,lon2,p] = LatLonPlot( lat, lon, tol, varargin )
Inputs
 lat     (1,:)  Latitude vector (rad)
 lon     (1,:)  Longitude vector (rad)
 tol     (1,1)  Tolerance used for WrapSegments call. See WrapSegments
 varargin (:)  Any additional inputs are treated as additional inputs
                  to the plot command, as: plot(x,y,varargin)
Outputs
 lat2    (1,N)  Cell array of N segments of latitude vectors (rad)
 lon2    (1,N)  Cell array of N segments of longitude vectors (rad)
 p       (1,N) Pointers to plots
References isempty(), LatLonPlot(), length(), NewFig(), vector(), WrapSegments(), and zeros().
Referenced by LatLonPlot().
LinkOrbitAnalysis()
function LinkOrbitAnalysis (in r, in jD, in d)
The orbit is the spaceraft position in km. Each orbit position must have a corresponding Julian day number. Modulations are 'BPSK' 'QPSK' 'DE-BPSK' 'DE-QPSK' 'D-BPSK' The output is the bit error probability as a function of the orbit position. This will be zero if the ground station is not visible. Assumes antenna is omni-directional.
Note that the TSky model is limited to frequencies between 2.5 and 60 GHz. If a frequency outside this is entered the closest endpoint is used.
Type LinkOrbitAnalysis for a demo.
Form
 bEP = LinkOrbitAnalysis( r, jD, d )
Inputs
 r      (3,:) Orbit Earth Fixed (km)
 jD     (1,:) Julian date (days)
 d      (.)   Comm data structure
              .fGHz                 (1,1) Frequency (GHz)
              .modulation           (1,:) Modulation e.g. 'D-BPSK';
              .bitRate              (1,1) Bit rate (bps)
       Satellite transmitter:
              .ampAntennaLoss       (1,1) Antenna loss (dB)
              .beamEdgeLoss         (1,1) Beam edge loss (dB)
              .gainTransmit         (1,1) Gain of satellite transmitter (dB)
              .powerTransmit        (1,1) Transmit power (W)
              .polarizationAngle    (1,1) Polarization angle mismatch (deg)
       Ground station:
              .latitude             (1,1) Ground station latitude (rad)
              .longitude            (1,1) Ground station longitude (rad)
              .altitude             (1,1) Ground station altitude (km)
              .diameterReceive      (1,1) Receive antenna diameter (m)
              .apertureEfficiency   (1,1) Aperture efficiency
              .temperatureERX       (1,1) Effective receiver noise temperature (deg-K)
              .temperatureFeeder    (1,1) Feeder temperature (deg-K)
              .lossFeeder           (1,1) Feeder loss (dB)
              .horizonAngle         (1,1) Horizon angle cutoff (rad)
Outputs
 bEP      (1,:)  Bit error probability
See also
LatLonAltToEF, FrequencyToWavelength, DBSignalToPower, TSky,
TAntennaGround, TReceiver, GroundStationVisibility
References and(), BEP(), Date2JD(), DBSignalToPower(), Demo(), ECIToEF(), Frequency(), FrequencyToWavelength(), GroundStationVisibility(), HorizonAngle(), JD2T(), LatLonAltToEF(), LinkOrbitAnalysis(), LossAtmosphericGas(), LossPolarization(), Mag(), Period(), Plot2D(), RVFromKepler(), TAntennaGround(), TimeLabl(), TReceiver(), TSky(), and zeros().
Referenced by LinkOrbitAnalysis().
LoadOBJModel()
function LoadOBJModel (in file, in path, in kScale)
The file can have an associated .mtl file.
If you call the function with no outputs it will draw the model. If you call the function with no inputs you can select a file using the dialog box.
Form
 g = LoadOBJModel( file, path, kScale )
Inputs
 file        (1,:) Filename
 path        (1,:) Path to the file
 kScale      (1,1) Optional scale factor of the model
Outputs
 g           (.)   Data structure
                   .name       (1,:)  Model name
                   .component  (:)    Component structure
                   .radius     (1,1)
References and(), Initialize(), isempty(), length(), Mag(), NewFig(), XLabelS(), YLabelS(), and ZLabelS().
MagneticControl()
function MagneticControl (in b, in tDemand, in u, in c)
Magnetic torquers only produce 2-axis torque. This function generates a least squares fit that matches the torque the torquers can produce to the torque demand. The output is the dipole demand in ATM^2 (amp-turn-meter-squared). The scalar cost is any number >= 0. It assumes that the cost of using any dipole is the same. The output will need to be pulsewidth modulated if the torquers do not have linear actuation.
For example, the torque is T = [m1 m2 m3] x b, or
 T = -b x [m1 m2 m3]
m1, m2 and m3 are dipoles. [b x] cannot be inverted hence the least squares. Has a built-in demo.
Form
 [m, tErr] = MagneticControl( b, tDemand, u, c )
Inputs
 b          (3,1)  Magnetic Field (T)
 tDemand    (3,1)  Torque Demand (Nm)
 u          (3,n)  Unit dipole vectors for n dipoles
 c          (1,1)  Scalar cost of using a dipole
Outputs
 m          (n,1)  Dipole values (ATM^2)
 tErr       (3,1)  Torque error (Nm)
References and(), Demo(), Dipole(), MagneticControl(), scalar(), and Unit().
Referenced by MagneticControl().
MomentumUnloading()
function MomentumUnloading (in b, in gain, in h)
If the magnetic field is aligned the the momentum no control is possible and you will see a spike in the response. This only works with 3 orthogonal torquers. This system works in the inertial frame. m needs to be transformed into the body frame.
The dipole commands can be implemented by a linear control of the dipole current or by pulsewidth modulation.
Form
 [tMM, m, angle,tD] = MomentumUnloading( b, gain, h )
Inputs
 b            (3,1)     B-Field (T)
 gain         (1,1)     Proportional gain (N/Nms)
 h            (3,1)     Momentum (Nms)
Outputs
 tMM          (3,1)     Total torque from the torquers (Nm)
 m            (:,1)     Dipole commands (ATm^2)
 angle        (1,1)     b dot h (rad)
 tD           (3,1)     Torque demand (Nm)
References and(), BDipole(), Cross(), Demo(), Dipole(), DispWithTitle(), Dot(), JD2000(), MomentumUnloading(), and Skew().
Referenced by MomentumUnloading().
ObservationTimeWindows()
function ObservationTimeWindows (in orbit, in targets, in jD, in horizon, in fOV, in minEl, in doPlot)
 Usage:
 [track,obs] = ObservationTimeWindows( orbit, targets, jD, horizon, ...
 fOV, minEl, doPlot )
Inputs
 orbit      (1,6)    Orbital elements vector, OR
             (.)     Data structure w/ time (.t) and ECI pos (.r)
 targets    (2,N)    List of N targets [lat;lon] in deg
 jD         (1,1)    Julian date start epoch
 horizon    (1,1)    Duration
 fOV        (1,1)    Field of view (deg)
 minEl      (1,1)    Minimum elevation (deg)
 doPlot     (1,1)    Flag to generate plot (1) or not (0). Default 0.
Outputs
 track       (.)  Data structure with time, lat. and long. of satellite,
                  azimuth, elevation and range of satellite with respect
                  to targets.
 obs         (.)  Data structure array with fields:
                  .target:    (2,1)    Lat and lon coordinates of target
                  .boundary:  (2,:)    Lat/lon boundary around target
                  .nObs:      (1,1)    Number of observations of this target
                  .window:  (nObs,2) Each row is start/stop time of window
                  .time:      {1,nObs} Each entry is a (1,T) time vector
                  .path:      {1,nObs} Each entry is a (2,T) lat/lon vector
References and(), set(), and vector().
Referenced by AttitudeProfile(), and AttitudeProfileWithCon().
ObservationTimeWindowsPlot()
function ObservationTimeWindowsPlot (in track, in obs)
 Usage:
 ObservationTimeWindowsPlot( track, obs )
Inputs
 track       (.)    Data structure with time, lat and lon vectors.
 obs         (.)    Data structure array with fields:
                .target:    (2,1)    Lat and lon coordinates of target
                .boundary:  (2,:)    Lat/lon boundary around target
                .nObs:      (1,1)    Number of observations of this target
                 .window:    (nObs,2) Each row is start/stop time of window
                .time:      {1,nObs} Each entry is a (1,T) time vector
                .path:      {1,nObs} Each entry is a (2,T) lat/lon vector
Outputs
 none
References and().
PackageOrbitDataForPlayback()
function PackageOrbitDataForPlayback (in jD0, in t, in r, in v, in coneFOV, in conePitch, in coneAzimuth, in inputFrame)
For the sensor cone FOV, pitch and azimuth angles: you may supply any one of them as either a scalar or a vector with the same number of points as the time vector.
Since version 8.
Form
 object = PackageOrbitDataForPlayback( jD0, t, r, v, coneFOV, conePitch,
 coneAzimuth, inputFrame )
Inputs
 jD0           (1,1)    Julian date epoch.
 t             (1,N)    Time vector. Seconds from epoch.
 r             (3,N)    Position history of orbit.
 v             (3,N)    Velocity history of orbit.
 coneFOV       (1,:)    Cone field of view (rad)
 conePitch     (1,:)    Cone pitch from nadir (rad)
 coneAzimuth   (1,:)    Cone azimuth from north (rad)
 inputFrame     (:)     Frame of r,v inputs. 'ECI' or 'EF'
Outputs
 object         (:)     Data structure array of simulated objects in orbit
                        See PackageOrbitDataForPlayback.m. Fields are:
                           rEF: [3xN double] Earth fixed position (km)
                           vEF: [3xN double] Earth fixed velocity (km/s)
                           lat: [1xN double] Latitude (rad)
                           lon: [1xN double] Longitude (rad)
                             h: [1xN double] Altitude (km)
                       coneFOV: [1xN double] Cone field of view (rad)
                     conePitch: [1xN double] Cone pitch from nadir (rad)
                   coneAzimuth: [Nx1 double] Cone azimuth from north (rad)
                      coneAxis: [3xN double] Cone axis in Earth-fixed frame
                        swathX: [NxP double] Swath curve, Earth-fixed x-coord.
                        swathY: [NxP double] Swath curve, Earth-fixed y-coord.
                        swathZ: [NxP double] Swath curve, Earth-fixed z-coord.
                      swathLat: [NxP double] Swath curve, latitude
                      swathLon: [NxP double] Swath curve, longitude
See also
: PlaybackOrbitSim.m
References Altitude(), and(), AnimationGUI(), AU2Q(), Cone(), Cross(), Date2JD(), ECEFToLLA(), ECIToEF(), isempty(), JD2T(), length(), OrbRate(), PackageOrbitDataForPlayback(), Period(), PlaybackOrbitSim(), QForm(), QMult(), RapidSwath(), RV2El(), RVFromKepler(), scalar(), Swath(), Unit(), vector(), and zeros().
Referenced by PackageOrbitDataForPlayback(), and PlaybackOrbitSim().
PlaybackOrbitSim()
function PlaybackOrbitSim (in time, in object, in planet, in style)
Utilizes AnimationGUI.
Form
 PlaybackOrbitSim( time, object, planet, style )
Inputs
 time       (1,N) Time vector. For display only. Use any units.
 object (:)   Data structure array of simulated objects in orbit
               See PackageOrbitDataForPlayback.m. Fields are:
               .rEF         (3,N) Earth fixed position (km)
               .vEF         (3,N) Earth fixed velocity (km/s)
               .lat         (1,N) Latitude (rad)
               .lon         (1,N) Longitude (rad)
               .h           (1,N) Altitude (km)
               .coneFOV     (1,N) Cone field of view (rad)
               .conePitch   (1,N) Cone pitch from nadir (rad)
               .coneAzimuth (N,1) Cone azimuth from north (rad)
               .coneAxis    (3,N) Cone axis in Earth-fixed frame
               .swathX      (N,P) Swath curve, Earth-fixed x-coord.
               .swathY      (N,P) Swath curve, Earth-fixed y-coord.
               .swathZ      (N,P) Swath curve, Earth-fixed z-coord.
               .swathLat    (N,P) Swath curve, latitude
               .swathLon    (N,P) Swath curve, longitude
 planet    (:)  Name of planet file to use (e.g. 'EarthHR')
 style     (:)  '2D' or '3D'
                 NOTE: '2D' is not yet supported. To be supported
                 in a future release.
Outputs
 None
See also
: PackageOrbitDataForPlayback.m
References Altitude(), AnimationGUI(), ColorSpread(), Cone(), Date2JD(), length(), OrbRate(), PackageOrbitDataForPlayback(), Period(), RVFromKepler(), Swath(), and vector().
Referenced by DrawSpacecraftInOrbit(), and PackageOrbitDataForPlayback().
PlotOrbit()
function PlotOrbit (in r, in t, in jD0)
Note that the location relative to the map is only accurate for Earth-fixed frame input. Enter time and Julian date to compute the Earth-fixed positions from ECI data automatically.
Form
 [h, l] = PlotOrbit( rEF )
 [h, l] = PlotOrbit( rECI, t, jD0 )
Inputs
 r         (3,m)  Position vectors (km)
         or
            {n}   Cell array of position matrices for multiple satellites
 t         (1,:)  Time array (sec)
 jD0       (1,1)  Epoch Julian date
Outputs
 h         (1,1)  Figure handle
 l         (1,n)  Handle to orbit lines
See also
: LoadEarthMap
References and().
Referenced by RadiationBelts(), and RVWithJ2().
RapidSwath()
function RapidSwath (in lat, in lon, in h, in halfAngleFOV, in pitch, in azimuth, in Rp)
If no outputs are given this will generate a 3D plot of the sensor field of view. The nadir axis is drawn in green and the sensor boresight in yellow. This function has a built-in demo.
Since version 8.
Form
 d = RapidSwath( lat, lon, h, halfAngleFOV, pitch, azimuth, Rp );
Inputs
 lat           (1,1)    Latitude of satellite  (rad)
 lon           (1,1)    Longitude of satellite (rad)
 h             (1,1)    Altitude of satellite  (km)
 halfAngleFOV  (1,1)    Sensor cone half-angle field of view (rad)
                        Note: 0 <= halfAngleFOV <= PI/2
 pitch         (1,1)    Pitch angle between boresight axis and nadir axis (rad)
                        Note: 0 <= pitch <= PI
 azimuth       (1,1)    Azimuth angle from north (rad)
 Rp            (1,1)    Planet radius. Optional. Default is Earth radius. (km)
Outputs
 d         (.)  Data structure with fields:
            .r             Set of 3D position curves for each elevation
            .lat           Set of latitude vectors for each elevation
            .lon           Set of longitude vectors for each elevation
            .intersect     Flag indicating whether the cone intersects
                              the planet.
            .aboveHorizon   Flag indicating whether any part of the cone
                              goes above the horizon.
References abs(), Altitude(), and(), AU2Q(), Cone(), Cross(), Map(), QForm(), QMult(), set(), and Unit().
Referenced by DrawSpacecraftInOrbit(), and PackageOrbitDataForPlayback().
ReactionWheelDesign()
function ReactionWheelDesign (in d)
Each input has a corresponding input d.units.name which contains the units in a string.
Type ReactionWheelDesign for a demo.
Form
 d  = ReactionWheelDesign;  % data structure
 [thickness, inertia, torque, mass]  = ReactionWheelDesign( d )
Inputs
 d      (.)       Data structure
                  .radius      (1,1) Allowable wheel radius    (m)
                  .wheelSpeed  (1,1) Allowable wheel speed     (rad/s)
                  .h           (1,1) Maximum momentum storage  (Nms)
                  .density     (1,1) Density of wheel material (kg/m^3)
                  .dhdt        (1,1) Maximum momentum change   (Nm)
Outputs
 thickness   (1,1) Wheel thickness           (m)
 inertia     (1,1) Wheel polar inertia       (Nm^2)
 torque      (1,1) Wheel torque              (Nm)
 mass       (1,1) Wheel mass                  (kg)
References Demo(), and ReactionWheelDesign().
Referenced by ReactionWheelDesign().
RepeatGroundTrack()
function RepeatGroundTrack (in g, in doplot)
Determines the semi-major axis values closest to the desired ratio of orbits / days. Utilizes the J2 drift to model the satellite orbit rate.
 Usage:
 g = RepeatGroundTrack( 'input' );
 d = RepeatGroundTrack( g );
 d = RepeatGroundTrack( g, 1 );   % generates a plot
Inputs
 g       (.)   Data structure with fields
                  .P0   Desired number of orbits (integer)
                  .Q0   Desired number of days over which P0 orbits occur
                  .inc  Orbit inclination (rad)
                  .ecc  Orbit eccentricity
                  .da   Range of semi-major axis values to consider (km)
                  .PMax Maximum number of orbits to consider
                  .QMax Maximum number of days to consider
 doplot  (1)   Flag to create plot. Default 0.
Outputs
 d       (.)   Data structure with fields
                  .P    Closest number of orbits to meet ratio (integer)
                  .Q    Closest number of days to meet ratio (integer)
                  .a0   Initial semi major axis guess
                  .a    Closest semi major axis values to meet ratio
                  .dLon Longitude drift per orbit
                  .days Number of days per repeat
                  .anomalisticPeriod   Anomalistic period (sec)
                  .nodalPeriod         Nodal period (sec)
 doplot (1,1)  Plotting flag. Set to 1 to create a plot.
Reference: Vallado, "Fundamentals of Astrodynamics and Applications", Second Edition. Sec. 11.4.2, Repeat-Groundtrack orbits.
References and(), isempty(), length(), NewFig(), and RepeatGroundTrack().
Referenced by RepeatGroundTrack().
RHSCubeSat()
function RHSCubeSat (in x, in t, in d)
Includes drag and optical surface disturbances, magnetic dipole, gravity gradient, rigid body dynamics and power. Uses the J70 atmosphere model and applies a point-mass gravity model. Computes sun location with SunV1 and accounts for eclipses from the Earth. The surface parameters in surfData are passed to both the optical and aerodynamic disturbance model functions.
The states are [position;velocity;quaternion;angular velocity; battery charge]. The battery charge must always be the last state. Its units are J. If there are wheel states they must be between the spacecraft angular velocity and the battery charge, and the indices be logged in kWheels.
Can output the disturbance forces and torques for post-processing. There is also a call to retrieve the default data structure.
Form
 [xDot,dist,power] = RHSCubeSat( x, t, d )
 d = RHSCubeSat
Inputs
 x        (14,1)    [r;v;q;w;wRWA;b]
 t         (1,1)    Time, sec
 d          (.)     Data structure
                    .jD0      (1,1) Julian date of epoch
                    .mass     (1,1) Spacecraft mass (kg)
                    .inertia  (3,3) Inertia matrix (kg-m2)
                    .dipole   (3,1) Residual dipole (ATM^2)
                    .power     (.)  Power data, see SolarCellPower
                                    .batteryCapacity
                                    .consumption
                    .aeroModel    * Handle, see CubeSatAero
                    .opticalModel * Handle, see CubeSatRadiationPressure
                    .surfData  (.)  optional; empty to skip drag/optical calcs
                                    .cD    (3,1) Drag coefficient
                                    .cM    (3,1) Center of mass (m)
                                    .area  (1,n) Area (m2)
                                    .nFace (3,n) Face normals
                                    .rFace (3,n) Face locations (m)
                                    .att    (.)  Attitude model
                                    .sigma (3,n) Optical coefficients
                                    .planet (1)  Planet effects flag
                    .atm       (.) optional; empty to skip J70 and use AtmDens2
                    .kWheels         (n), empty if no wheels, indices of wRWA
                    .inertiaRWA     (1,1), optional, polar inertia (kg-m2)
                    .tRWA           (3,1), optional, wheel torque (Nm)
Outputs
 x           (14,1)    d[r;v;q;w;b]/dt
 dist         (.)       Disturbances data
  .fTotal      (3,1)   Total force, ECI frame  (N)
  .tTotal       (3,1)   Total torque, body frame (Nm)
  .fAerodyn    (3,1)   Aerodynamic force
  .tAerodyn     (3,1)   Aerodynamic torque
  .fOptical    (3,1)   Optical force
  .tOptical     (3,1)   Optical torque
  .tMag         (3,1)   Magnetic torque
  .tGG          (3,1)   Gravity gradient torque
 power       (1,1)      Power from solar cells (W)
See also
SolarCellPower, CubeSatAero, CubeSatRadiationPressure,
SolarFluxPrediction, CubeSatEnvironment, CubeSatSimulation
CubeSatRWASimulation
References and(), AtmDens2(), Cross(), CubeSatAero(), CubeSatEnvironment(), CubeSatRadiationPressure(), Date2JD(), Disturbances(), GravityGradientFromR(), isempty(), Limit(), Mag(), QForm(), QIToBDot(), quaternion(), Residual(), RHS(), RHSCubeSat(), SolarCellPower(), SolarFluxPrediction(), SunV1(), and zeros().
Referenced by CADToSimParameters(), CubeSatDisturbanceAnalysis(), CubeSatModel(), CubeSatPowerAnalysis(), DrawCubeSat(), DrawCubeSatSolarAreas(), FOrbitMultiSpacecraft(), RHSCubeSat(), TubeSatDefaultDataStructure(), and TubeSatModel().
RHSIsothermalCubeSat()
function RHSIsothermalCubeSat (in t0, in ignoredArg, in d, in p)
The entire spacecraft is assumed to be at the same temperature. p should be the net input vector and include sun, albedo and earth radiation. You should also factor in eclipses. The total power is the internal power that is absorbed by the spacecraft. The specific heat is the average over the whole spacecraft. If mass is a vector it will compute temperatures separately for each face. An optional matrix k provides face thermal conductivities. For multiple faces, internal power is per face.
If there are no output arguments the demo will plot the equilibrium temperature.
Form
 RHSIsothermalCubeSat -- demo
 d = RHSIsothermalCubeSat -- default data structure
 [tDot, Teq] = RHSIsothermalCubeSat( t0, t, d, p )
Inputs
 t0     (1,6) or (1,1) Temperature of faces or total temperature
 t      (1,1)     Time (unused)
 d       (.)      Data structure
                  .mass       (1,6) or (1,1) face masss or total mass
                  .uSurface   (3,6) Surface unit vectors
                  .alpha      (1,6) Absorptivity
                  .epsilon    (1,6) Emissivity
                  .area       (1,6) Area
                  .cP         (1,1) Specific heat
                  .powerTotal (1,6) or (1,1) Internal power (W)
                  .k          (6,6) Thermal conductivity (W/deg-K)
 p      (3,:)     Thermal flux in the body frame (W/m2)
Outputs
 tDot     (:,6) or (1,:) Temperature derivative of faces or total
 Teq      (:,6) or (1,:) Equilibrium temperature of faces or total
References and(), CubeSatFaces(), Demo(), Initialize(), length(), Plot2D(), RHSIsothermalCubeSat(), vector(), and zeros().
Referenced by RHSIsothermalCubeSat().
RHSMomentum()
function RHSMomentum (in ignoredArg, in ignoredArg, in torque)
dh/dt = torque
Form
 hDot = RHSMomentum( h, t, torque )
Inputs
 h            (3,1)     Angular momentum
 t            (1,1)     Time (unused)
 torque       (3,1)     Torque vector
Outputs
 hDot         (4,1)     Momentum derivative
References RHS(), and vector().
RVWithJ2()
function RVWithJ2 (in el, in jD0, in tEnd, in j2)
Integrates the orbit using RHSGeoJ2 and ode45. Using the J2 term requires a Julian date as the inertial state must be converted to Earth-fixed at every timestep. RHSGeoJ2 uses ECIToEF which is fast and of moderate precision.
Form
 [r, v, t] = RVWithJ2( el, jD0, time, j2 )
Inputs
 el              (1,6) Initial Keplerian elements
 jD0             (1,1) Initial Julian Date [JD]
 time            (1,:) Time vector [sec]
Outputs
 r          (3,:) Position vectors for times t
 v          (3,:) Velocity vectors for times t
 t          (1,:) Times at which r and v are calculated
See also
: RHSGeoJ2, El2RV
References and(), Date2JD(), ECIToEF(), El2RV(), isempty(), Period(), PlotOrbit(), RHSGeoJ2(), and vector().
SolarCellPower()
function SolarCellPower (in d, in pSun)
Has a built-in demo. Can also return the default data structure.
Type SolarCellPower for a demo.
Form
 power = SolarCellPower( d, pSun )
 d = SolarCellPower
Inputs
 d       (.)      Data structure
                  .solarCellEff       (1,1) Efficiency of the cells
                  .effPowerConversion (1,1) Efficiency of the power
                                            conversion
                  .solarCellArea      (1,:) Total cell area (m^2)
                  .solarCellNormal    (3,:) Unit normal vector to the
                                            cell face
 pSun   (3,1)     Solar power flux vector (W)
Outputs
 power  (1,1)     Power (W)
References Demo(), length(), Plot2D(), SolarCellPower(), Unit(), vector(), and zeros().
Referenced by CADToSimParameters(), CubeSatPowerAnalysis(), DrawCubeSatSolarAreas(), RHSCubeSat(), RHSLunarMission(), and SolarCellPower().
TubeSatDefaultDataStructure()
function TubeSatDefaultDataStructure (in l, in jD)
Form
 d = TubeSatDefaultDataStructure( l, jD )
Inputs
 l          (1,1)   Either (1,2,3,4) for single, double, triple or quad
 jD         (1,1)   Julian date for solar data, optional
Outputs
 d          (.)     Data structure
                    .jD0
                    .mass
                    .inertia
                    .power
                    .dipole
                    .surfData, optional; empty to skip drag calcs
                    .aeroModel
                    .opticalModel
                    .atm
                    .kWheels, empty if no wheels
                    .inertiaRWA, optional
                    .tRWA, optional
See also
InertiaTubeSat, TubeSatFaces, RHSCubeSat, SurfaceProperties
References and(), Date2JD(), InertiaTubeSat(), OpticalSurfaceProperties(), RHSCubeSat(), SolarFluxPrediction(), and TubeSatFaces().
Referenced by TubeSatModel().
TubeSatFaces()
function TubeSatFaces (in l, in ignoredArg)
The z axis is always the long axis.
Form
 [a,n,r] = TubeSatFaces( l, rear )
Inputs
 l        (1,1)   Either (1,2,3,4) for single, double, triple or quad
 rear     (1,1)   Flag to include the rear faces
Outputs
 a    (1,9) or (1,18)   Areas [aXY ... aZ]
 n    (3,9) or (3,18)   Outward normals
 r    (3,9) or (3,18)   Location from geometric center of spacecraft
References Demo(), DrawCubeSat(), Frustrum(), length(), scalar(), set(), TitleS(), TubeSatFaces(), TubeSatModel(), Unit(), and zeros().
Referenced by InertiaTubeSat(), TubeSatDefaultDataStructure(), and TubeSatFaces().
TubeSatModel()
function TubeSatModel (in l)
You can draw the TubeSat model using DrawCubeSat. A figure is created if there are no outputs.
Type TubeSatModel for a demo of a single TubeSat.
Form
 [v, f, d] = TubeSatModel( l )
Inputs
 l           (1,:) Scaling factor, 1 for single, or 2, 3, 4
Outputs
 v           (:,3) Vertices
 f           (:,3) Faces
 dRHS         (1,1) Data structure for the function RHSCubeSat
Reference: TubeSat brochure from Interorbital.com
See also
: TubeSatDefaultDataStructure, Frustrum, DrawCubeSat
References and(), Demo(), DrawCubeSat(), Frustrum(), get(), length(), RHSCubeSat(), scalar(), set(), TubeSatDefaultDataStructure(), and TubeSatModel().
Referenced by TubeSatFaces(), and TubeSatModel().
WrapSegments()
function WrapSegments (in x, in tol)
Form
 [y,k] = WrapSegments( x, tol )
Inputs
 x       (1,:)    Vector of data points
 tol     (1,1)    Jump tolerance.
                  If x(k+1)-x(k) > tol, the segment ends at x(k).
Outputs
 y       {1,n}    Cell array of segments.
                  Each segment "i" is 1 x m(i) array and sum(m)=n
 k       {1,n}    Cell array of index values so that: y{j} = x( k{j} );
References series(), and vector().
Referenced by LatLonPlot().