PSS MATLAB Toolboxes: Common/Classes/@quat/quat.m File Reference
quat.m File Reference
Returns the vector part of a quaternion.
Functions
function ctranspose (in a)
Computes the transpose of a quaternion.
function get (in a)
Gets the scalar and vector equivalent of a quat.
function quat (in x)
Create an object of class quat.
function scalar (in a)
Returns the scalar part of a quaternion.
function vector (in a)
Returns the vector part of a quaternion.
Function Documentation
ctranspose()
function ctranspose (in a)
Form
 b = ctranspose( a )
Inputs
 a           (:)   Object of type quat
Outputs
 b           (:)   Object of class quat
get()
function get (in a)
Form
 [s, v] = get( a )
Inputs
 a           (:)   Object of type transmat
Outputs
 s           (1,1) Scalar part
 v           (3,1) Vector part
Referenced by AC(), ACInit(), ACModes(), ACPlot(), ACSensor(), AddOuterLoop(), AddToList(), AddView(), AeroF(), AircraftGroupDataStructure(), Airship_KLat(), Airship_KLon(), AirshipBallonets(), AirshipDesignGUI(), AirshipLinMod(), AirshipSensor(), AirshipSim(), AirshipSimGUI(), AirshipStabConDerivatives(), AirshipStatespace(), AirshipTrim(), AlbedoFromTextureMap(), AllanVariance(), AnimateCube(), AnimateSpacecraft(), AssemblePlant(), AtmJ70(), AttitudeFrames(), AttitudeProfilePlugIn(), AttitudeProfileVis(), AxesCart(), AxisEqual(), BalRealG(), BiotSavart(), BladeSolidity(), BlockDiagramPlugIn(), BodyPlugIn(), CADColor(), CalibrationCube(), CenterFigure(), CGAdv(), CLComposite(), ClosedFormMethod(), CloseIfHandle(), CloseUIElement(), ColorSpread(), CommandPlugIn(), ComponentPlugIn(), ComponentPopup(), ComputeGainsPlugIn(), ComStar(), Constant(), Cost3D(), CostLowThrust2D(), CostSail2D(), CostSail3D(), Counter(), Covariances(), DataWindow(), DCAdv(), DeleteFromList(), DeriveData(), DetectionFilterBuilder(), DetectorModel(), DFFAttitudeController(), DFFAttitudeCoordination(), DFFAttitudeManagement(), DFFAttitudeManeuver(), DFFCollisionMonitor(), DFFControl(), DFFControlLaw(), DFFCoordinateTransformation(), DFFDeltaVManagement(), DFFGuidanceLaw(), DFFISLManagement(), DFFParameterDatabase(), DFFSimGUI(), DFFTeamManagement(), DispG(), DisplayFilter(), DisplaySailProperties(), Disturbances(), Draw2DViewPlugIn(), DrawAC(), DrawAircraft(), DrawSailAttitude(), DrawSailCADModel(), DrawSCPlugIn(), DrawSpacecraftPatches(), DrawStarImageCentroids(), DrawThermalPlugIn(), EarthGuidance(), EarthMoonSystemConstants(), EarthRot(), ECIToSunEarthRot(), EditDlg(), EigEval(), ESAssign(), ESAssignDraper(), ExportVerticesToOBJ(), Extrude(), FAero(), FAtmDensity(), FEngine(), FFEccGenerateTeamGoals(), FFSim(), Figui(), FImage(), Finder(), FindPeaks(), FirstLineOfCode(), fixpopupuicontrol(), FPlantNoise(), FResp(), FRespG(), FRWA(), FRWABristle(), FSolar(), FSWClock(), FXModel(), GAMin(), GASTime(), GenerateTeamGoals(), GeoSwitchingMission(), GetCurrentGUIObject(), GetListString(), GetStage(), GOESLeg(), GPMargin(), GPoly(), GPSReceiver(), GPSReceiverNav(), GravityGradientBoom(), GroundTrackErrorBudget(), GroupVariables(), GUIColors(), Gyro(), GyroKalmanFilter(), HalbachField(), HeliopauseSailAngle(), HelpSystem(), HorizontalWind(), HSRCAD(), HUD(), HyperRDE(), IdealActuator(), ImageOverlay(), Imager(), ImagerPSF(), InformDlg(), Initialize(), IntegratePSFs(), JDToDateString(), JetEngineAnalysis(), JetEnginePerformance(), KalAdv(), L2OrbitPlots(), LandingControlGravityTurn(), LaunchConstants(), LegendTitle(), LinOrb(), LoadGravityModel(), LoadNORAD(), Loc3D(), LossPrecipitation(), LPvsCF(), LQC(), LTPlaneChange(), LumenToWatt(), LunarTrajectoryControl(), LVCombineSRB(), LVModelFeasibility(), LVModelFeasibilityFix(), LVModelFeasibilityReport(), MagneticTorquer(), MagneticTorquerDesign(), MakeSquareSail(), MassBudget(), Mat2Q(), MaximumDeltaV(), MBModel(), MeasRateIntegratingGyro(), MergeNOAAWindData(), MeshToPatch(), MessageAnalysis(), MessageQueue(), MHTTrackScore(), MHTTrackTable(), MixedFlowTurbofan(), MLog(), ModalReductionPlugIn(), ModelPlugIn(), MSR(), NavTargetTrackingLunar(), NOAAWindData(), NormalizePlugIn(), NPlot(), ODETimeDisplay(), OpticalNavigationMeasurement(), OrbitDisplayPlugIn(), OrbitFromSynodic(), ParamGUI(), PatchedConicPlanner(), PeriodToSemimajorAxis(), PhasePlane(), PID3Axis(), PIDWithLag(), PILeaky(), PixelFlux2D(), PixelMapCentroid(), Plot3DTrajectory(), PlotArrays(), PlotBPlane(), PlotDoubleYAxis(), PlotTracks(), PlotWindField(), PointingBudgetGUI(), PorkChopPlot(), PrintEigenvalues(), PrintFig(), PrintToImage(), PropagateLowThrust(), PropagateOrbitPlugIn(), PropStateSpace(), PTVersion(), QRHydrocarbon(), Quit(), RayTraceLens(), RayTraceMirror(), ReactionWheel(), ReadHorizons(), ReduceOrderPlugIn(), RHSGyroNBody(), RHSGyroWithOrbit(), RHSNBodyCentralHub(), RHSNBodySH(), RHSPointMassAircraft(), RHSReactionWheel(), RHSReactionWheelWithOrbit(), RHSRWAOrbit(), RHSRWASC(), RHSSlosh(), RotMat(), RV2RaDec(), RWA(), RWABristle(), RWASmart(), RWASpec(), SAADMain(), SAADTool(), SafeGuidanceSim(), SCClock(), ScDB(), ShowThreeImages(), Simplex(), Simulate2DLanding(), SimulatePlugIn(), SingleAxisDrive(), SingleAxisLinearDrive(), SolarFluxPrediction(), SolutionWindow(), SortFigs(), SpaceCamera(), SpacecraftFromAccel(), SpacecraftParameters(), SpacecraftPlugIn(), SpacecraftStatePlugIn(), SpacecraftThermal(), spline_maths(), square(), SSA(), StarCentroid(), StarCentroidCOM(), StateSensor(), StateSpacePlot(), StateSpacePlugIn(), StdAtm(), SteamTablesSuperheatedEnthalpy(), SteeringAnglesToQ(), Step(), StopGUI(), StoppingPlugIn(), SunEarthMoonSystemConstants(), SunSensor(), SystemTime(), TCoeff(), TestLPCircular(), TestLPEccentric(), TestLPEccentricGVE(), TimeGUI(), TitleS(), TorqueRod(), TubeSatModel(), UKFPredict(), VantagePoint(), Watermark(), WeathLeg(), Wind(), WindStochastic(), WingAreaToTaper(), XLabelS(), YLabelS(), YRMax(), and ZermeloCost().
quat()
function quat (in x)
You can input:
 4-by-1 matrix - assumed to be a quaternion
 3-by-1 matrix - assumed to be an array of angles
 3-by-3 matrix - assumed to be a transformation matrix
Form
 q = quat( x )
Inputs
 x       (4,1) Quaternion
         (3,3) Matrix
         (3,1) Array of angles
Outputs
 q      (1,1) Object of class  quaternion.
References quat(), and quaternion().
Referenced by AttitudeTarget(), ctranspose(), PID3Axis(), quat(), and transmat().
scalar()
function scalar (in a)
Form
 s = scalar( a )
Inputs
 a       (:,:) Quaternion
Outputs
 s       (1,1) Scalar part
Referenced by AttitudeControlSimRWA(), BuildCADModel(), dists(), DupVect(), E2M(), E2Nu(), EarthEnvironment(), FGravityGradientStiffness(), ForceSimple(), HydrazineThruster(), InertiaTubeSat(), Limit(), LumenToWatt(), M2E(), MagneticControl(), Mesh2(), Nu2E(), PackageOrbitDataForPlayback(), PlanetEnvironment(), QuadCost(), RadarEquation(), RadarEquationPulse(), RHS2DPointMass(), RHS3DPointAircraft(), SXV(), TubeSatFaces(), TubeSatModel(), UDKalmanFilter(), and ZFresp().
vector()
function vector (in a)
Form
 s = vector( a )
Inputs
 a       (:,:) Quaternion
Outputs
 s       (3,1) Scalar part
Referenced by AB2RADec(), ABToDQ(), AC(), ACAero(), ACBuild(), Accel(), AccelToSailProps(), AccelToThrustAndQ(), AccelVector2ManeuverStruct(), ACInit(), ACModes(), ACPlot(), ACSRWAAndTorquers(), acstate(), ActiveAeroSurfacesDisplay(), AddBias(), AddCubesatComponent(), ADGen(), AdjustMeanAnomaly(), AeroD(), AeroDragForce(), AerodynamicShock(), AerodynamicShockMinimize(), AeroF(), AeroForceAndTorqueCombined(), AFLTSpiral(), AGravity(), AGravityC(), AircraftPointMassCLPSim(), AircraftPointMassControl(), AircraftPointMassDLM(), AircraftPointMassRHS(), AircraftPointMassSim(), AircraftTrajectoryControl(), AirshipMassModel(), AirshipMaxCruise(), AirshipSim(), AirshipStabConDerivatives(), AirshipState(), AirshipTrim(), AirshipTrimAnalysis(), AlignThruster(), AllanVariance(), AlongTrackMotion(), AlphaBetaToU(), AlphaCentauriSystem(), AlphaFromQNV(), AltitudeHold(), AngleDetermination(), AnglePatch(), AngleSensor(), AngleSepFromRotation(), AnglesMcInnesToU(), AnglesRotToU(), AngRate(), AnimateVectors(), AnimationGUI(), AntennaPatch(), AntennaPoint(), ApogeeDV(), ApolloGuidanceCoordinates(), ApolloLunarDescentGuidance(), AStarAttitudeTrajectory(), AtmJ70(), AttitudeControlSimRWA(), AttitudeFrames(), AttitudeProfile(), AttitudeProfilePlugIn(), AttitudeProfileToTorque(), AttitudeProfileVis(), AttitudeProfileWithCon(), AttitudeTarget(), AU2M(), AU2Q(), AutoPoint(), AutoRadar(), AzCoElToU(), AzElToU(), BallisticCoefficient(), BatchLSQOD(), BatteryDesign(), BDipole(), BDipolePlanet(), BilinearTangentAltitude(), BilinearTangentLaw(), BilinearTangentVector(), BiotSavart(), BMF(), BObjIntF(), BShuster(), BShuster2(), BuildCADModel(), CADToSimParameters(), CalibrationCube(), CameraControls(), CameraDatabase(), CameraModel(), Cart2Sph(), CEq2C(), CheckAlignment(), ClockConversion(), CMAirship(), CMG(), CMGAMatrix(), CMToMassPositions(), CollisionMonAlg(), CollisionMonitor(), CollisionMonteCarlo(), CompareHills(), ComputeDistance(), ComputeSailNormal(), Cone(), ConeClockPatches(), ConeClockToQConstrained(), ConeClockToU(), ConeInt(), ConeInt2(), CoordinateFrameFromUV(), Core2SA(), Cost3D(), CostEstimate_Structure(), CostLowThrust2D(), CostNM(), CostNMTE(), CostSail2D(), CostSail3D(), CostVis(), CovarianceRHS(), CRand(), CreateKVector(), CreateMVSSetupFileEntries(), CRTBP2kms(), CRTBPJacobi(), CRTBPJacobiConstant(), CRTBPRHS(), CT2R(), CT2REl(), CT2REq(), CubeSatDisturbanceAnalysis(), CubeSatEnvironment(), CubeSatLunarEnvironment(), CubeSatPowerAnalysis(), CubeSatPropulsion(), CubeSatRadiationPressure(), CwValid(), CylOrb(), DBode(), DCMotorDetectionFilter(), DefaultACState(), DelLZ(), DeltaAngleForNewRADec(), DeltaElem2Hills(), DeltaVChart(), DeltaWing(), DetectionFilterSimulation(), DFFAttitudeManeuver(), DFFAttitudeTarget(), DFFRHS(), DFFSim(), DHArcDX(), DHArcDXi(), DHCWDX(), DHCWDXi(), DHDADXi(), DiffCorr(), Dipole(), DiscreteGVE(), DisplaySailProperties(), DistAero(), DistAlbedo(), DistRadiation(), dists(), DistSolar(), Disturbances(), DoDeltaV(), DoubleIntegratorWithAccel(), DrawAC(), DrawAircraft(), DrawCubeSatSolarAreas(), DrawFOV(), DrawHAWT(), DrawOrbitPlane(), DrawRobot(), DrawSailAngles(), DrawSailAttitude(), DrawSailMeshVectors(), DrawSCPlugIn(), DrawSpacecraftInOrbit(), DrawVAWT(), DSTM(), DSunCone(), DualDCMotors(), DUnit(), DupVect(), DVConstantThrust(), DVGlideslope(), DVLowThrust(), Dyn(), DynP(), EarthAlb(), EarthEclipseDuration(), EarthEscape(), EarthGuidance(), EarthOrbToHelioOrb(), ECEFToLLA(), ECI2OrbitPlane(), ECIToEarthMoonRot(), ECIToNED(), ECIToSunEarthRot(), Eclipse(), EclipseFromECI(), EclipseHelio(), EclipticInjectionPlane(), EFToLatLonAlt(), EKFSSG(), EKFUpdate(), El2Eq(), El2LKl(), El2RV(), EllipseImageFit(), EMBToEMBND(), EnergyWRTMoon(), Eq2El(), Eq2RV(), ErrorCombination(), ESA(), ESACS(), EstimateCost(), EulNED(), F16(), FAero(), FAeroSurfaceAccommodation(), FAKM(), FAtmDensity(), FCartOrbD(), FCoreAndMoving(), FCRTBPRHS(), FDC(), FEngine(), FFEccDiscreteHills(), FFEccDMatPeriodic(), FFEccEstimateCost(), FFEccHills2Goals(), FFEccProp(), FFEccRMat(), FFEccShapes(), FFEccTargetTrueAnom(), FFIntegrate(), FFSim(), FGravityGradientStiffness(), FGs(), FHel(), FHingeOrbit(), FIC(), FICP(), FImage(), FindDriftTerm(), FindTimeWindows(), FindValidAngleRange(), FLambdaToConeClock(), FMagSim(), FMovingBody(), FOrb(), FOrbCart(), FOrbCartH(), FOrbHFOP(), FOrbitGeneral(), FOrbitKFPointMass(), FOrbitMultiSpacecraft(), FOrbitSingle(), FOrbKF(), FOrbLEOP(), FOrbLEOPStopping(), FOrbLowThrust(), FOrbLTE(), ForceAndTorqueEnvelope(), ForceSimple(), FormationDesignGUI(), FPA(), FPivot(), FPlantNoise(), FRB(), FRBWithMag(), FRBwRIG(), FResp(), FRespG(), FRespPlot(), FRotatingLagrange(), FRotatingPlanet(), FRotatingSun(), FRSCGen(), FRSMPlan(), FRSProp(), FRSTarg(), FRWA(), FS4Deployment(), FSailCombined(), FSailEarthMoon(), FSailEarthSun(), FSailRB(), FSailTB(), FSDG(), FSolar(), FSolarSail(), FTB(), FTBRef(), FThrustLander(), FTimeVaryingI(), FTrim(), FuelMassFromAccel(), FVarEq(), FX(), FXModel(), FXNM(), FXNMTE(), GenerateAirshipAeroMats(), GenerateSwath(), GenerateTimeVector(), GeoEclps(), GeoMagLatLon(), GetEntry(), GlideSlope(), GlideslopePlanner(), GND(), GPMargin(), GPSOrbit(), GravityGradientBoom(), GravityHelio(), GSModel(), GSS(), GuidedLaunch2DSim(), GuidedLaunch3DRHS(), GVEGuidance(), HArc(), HArci(), HCw(), HCw2R(), HCwi(), HDA(), HDAi(), HEl(), HelioToBPlane(), HEq(), HGimballedBoom(), Hills2DeltaElem(), Hills2LVLH(), HillsEqns(), HillsEqnsSLO(), HingeRotationMatrix(), HLE(), HorizonAngle(), HorizonUnitVectors(), HSAData(), HSRCAD(), HTE(), HUD(), HydrazineThruster(), I2B(), IC(), IConv(), IConvP(), Illumination(), IMU(), InclinationRate(), InitialOrientation(), InjDataT(), IntData(), IntersectPlaneAndSphere(), IntersectPlanet(), ISLFOV(), Isothermal(), ISSOrbit(), J20002RotPuls(), J20002RotPulsPlanetMoon(), J2Prop(), KConst(), KConstP(), KConstQ(), KFExItMu(), KFilter(), KFPredict(), KFSAAD(), KFSunAndEarth2(), KFUpdate(), Kms2CRTBP(), KSmooth(), L2OrbitSim(), LambdaToConeClock3D(), LambertOpt(), LambertTOF(), LandingControl(), LandingControlBilinear(), LandingControlGravityTurn(), LandingForce(), LatLonAltToEF(), LatLonPlot(), LaunchRHSData(), LFToECI(), LiftAndDragSeaLevelToOrbit(), LinkBudget(), LinOrb(), Lissajous(), LLAToECEF(), LoadFlex(), LocalAngleOfAttack(), LocallyOptimalConeClock3D(), LocallyOptimalTraj(), LocalSolarTime(), LocalStarMap(), LogB(), LogLimit(), LossPrecipitation(), LowEnergyEarthToMoonTransfer(), LowSpeedAeroData(), LowThrustControl(), LowThrustGVE_EventFcn(), LowThrustGVERHS(), LowThrustRendezvousSim(), LowThrustSim(), LPCircular(), LPCircularTimeWeight(), LPEccentric(), LPEccentricGVE(), LPEccentricTimeWeight(), LPvsCF(), LQOrbitController(), LSQLaunchSim(), LTPlaneChange(), LTSpiral(), LTVCon(), LunarHalo(), LunarLandingControl(), LunarOrbitInsertion(), LunarRelativeState(), LunarTarget(), LunarTargeting(), LunarTrajectoryControl(), LVLH2Hills(), Lyapunov(), Mag(), MagAirC(), MagControlThreeAxis(), MagControlTwoAxis(), MagDPT(), MagneticDipoleCart(), MagneticFieldDipole(), MagPlot(), MahalanobisDistance(), ManeuverStruct2AccelVector(), maxGenTerm(), MBModel(), MCDynamics(), Mean2Osc(), Mean2OscS(), MeanAnom2TrueLat(), MeasCamera(), MeasEarthSensor(), MeasMagnetometerEarth(), MeasNadirStar(), MeasRateGyro(), MeasRateIntegratingGyro(), MeasRelativePosition(), MeasStarAngleAndChord(), MeasStarTracker(), MeasState(), MeasSunSensorAnalog(), MeasSunSensorDigital(), Measurements(), MeasurementsSunMagUKF(), MEqToRV(), Mesh3DMF(), MHTDistance(), MHTLLR(), MHTTrackScore(), MHTTrackScoreKinematic(), MoonRot(), MoonV1(), MoonV2(), MutualInductanceCoil(), NadGen(), NeptuneAirshipSizing(), NewtonianAerodynamicsFromCAD(), NewtonianAeroPropertiesFromOBJFile(), NewtonianAeroTable(), NewtonianCPFromCAD(), NewtonianForceECI(), NewtonianForceFromCAD(), NewtonianLD3D(), NLFilter(), NoForce(), NonDimensionalOrbit(), NonKeplerianPlanet(), NORAD(), NORADToEl(), NOrbVector(), NorthFrame(), NPSPM(), Nu2TimeDomain(), NuclearReactorModel(), Nyquist(), ObservationTimeWindows(), OmegaFromU(), OmegaLVLH(), OpticalAngleError(), OpticalNavigation(), OpticalNavigationMeasurement(), OpticalNavigationMoon(), OpticalNavigationSun(), OpticalNavPlanetStarNoiseMatrix(), OptimalAssignment(), OptimalLunarLanding(), optMaxGenTerm(), OrbitDeltaV(), OrbitKFRHS(), OrbitLoweringManeuvers(), OrbitODGenObs(), OrbitProp(), OrbitStateMatrices(), OrbNEl(), OrbNEq(), Outliers(), P3Axis(), PackageOrbitDataForPlayback(), Parallax(), parse(), PatchedConicPlanner(), PayloadMassForBurnoutVelocity(), PeriodicOrbitFromGuess(), PermanentMagnetRHS(), PGains(), PID3Axis(), PIDProper(), Pix2U(), PlanetaryAccelerations(), PlanetaryRadiationAndAlbedo(), PlanetOptimalTraj(), PlanetSensorDualScan(), PlanetSim2D(), PlaybackOrbitSim(), Plot3DOrbit(), Plot3Vector(), PlotBPlane(), PlotCone(), PlotEMTraj(), PlotLET3BP(), PlotLunarOrbit(), PlotOrbitPage(), PlotSailClock2D(), PlotSailForce(), PlotSailForce2D(), PlotSailProfile(), PlottingToolStruct(), PlotV(), PlotVector(), PlotWindField(), PltOrbit(), Plume(), PMABCMachineRHS(), PMABCMachineSwitchedRHS(), PMMachineABCRHS(), Polygon(), PopulateCostMatrix(), PowCompAnlytBsd(), PPDelay(), PrivilegedAssignment(), Product(), ProjCirc(), ProjLine(), Propagate3BP(), Propagate4BP(), PropagateCRTBP(), PropagateCRTBPBackwards(), PropagateCRTBPToPeriapse(), PropagateCRTBPToXAxis(), PropagateNBody(), PropagateTLE(), PropagateTLECommonTime(), PropEph(), PropStateSpace(), Q2AU(), Q2RADec(), QAlign(), QAlignWithCon(), QECI(), QForm(), QFrenet(), QFrom2U(), QHills(), QNadirPoint(), QProp(), QRotateToAlign(), QRotateToAlignWithCon(), QSail(), QSpin(), QSunPointing(), QTForm(), QToConeClock(), QToPFTarget(), QuadCost(), QXToAlphaDelta(), RadarPulseTrain(), RadarSN(), RaDec2Q(), RadiationBelts(), Ramp(), RandomOrbit(), RayTraceLens(), RayTraceMirror(), REA(), ReadBSPFile(), ReadHorizons(), REAModel(), RectilinearMotion(), ReentryPlot(), RefineXAxisIntercept(), ReflectionLaw(), REl(), RelativeCoord(), RelativeOrbitRHS(), RelativeOrbitState(), ReliabilityMOfN(), ReliabilityParallel(), ReliabilitySeries(), RendezvousPlanner(), REq(), Residual(), RHS2DOrbit(), RHS2DPointMass(), RHS3DPointAircraft(), RHSAlphaCentauriMission(), RHSCisLunarMission(), RHSCMG(), RHSCRTBP(), RHSEarthOrbitUKF(), RHSEquinoctial(), RHSFlatEarthSet(), RHSGeoHarm(), RHSGeoJ2(), RHSGGRotational(), RHSGyrostat(), RHSGyrostatNoFriction(), RHSGyroWithOrbit(), RHSHelioMission(), RHSHelioWithPlanets(), RHSIsothermal(), RHSIsothermalCubeSat(), RHSIsothermalPState(), RHSLaunchVehicle3D(), RHSLiftingSatellite(), RHSLunarLander(), RHSMinTOrbitInjection(), RHSMomentum(), RHSNBodyCentralHub(), RHSNSpacecraft(), RHSOptimalFPA(), RHSOrbitPlanetFixed(), RHSPlanet2D(), RHSPlanet3D(), RHSPlanet3DONS(), RHSPlanet3DToAB(), RHSPlanetTakeoff(), RHSPointMass(), RHSPointMassAircraft(), RHSReactionWheel(), RHSReactionWheelWithOrbit(), RHSRigidBody(), RHSRigidBody6DOF(), RHSRigidBodyLinear(), RHSRigidBodyMass(), RHSRigidBodyOffsetCM(), RHSRigidBodyWithDamping(), RHSRigidBodyWithTarget(), RHSRobot(), RHSRobotInitialize(), RHSRWA(), RHSRWAIDotSC(), RHSRWAOrbit(), RHSRWASC(), RHSSpacecraftWithRWA(), RHSStateLunarMission(), RHSThreeBody(), RHSTrajectory(), RHSUKFHelioMission(), RHSVAWTPitchControl(), RIGModel(), RIGOut(), RK45(), RK4TI(), RLPMnvr(), RMoonECI(), RollPitchToQECI(), RotateOrbit(), RotorAssemblyAerodynamics(), RotPuls2J2000(), RPhiTheta2Cart(), RPQ(), RSunECI(), RTSS(), RV2AE(), RV2El(), RV2Eq(), RVFromKepler(), RVOrbGen(), RVOrbGenDV(), RVOrbHF(), RVSet2El(), RVToMEq(), RVWithJ2(), RWA(), RWAModel(), RWAPatch(), RYGCAttDet(), SA2Core(), Sa2Q(), SailACS(), SailClosedLoopNLEqns(), SailEnvironment(), SailEphemAlmanac(), SailForceSubplots(), SailMesh(), SailPatchVertices(), SailPropsToAccel(), SCHarm(), SCMG(), SCWithRollPivot(), SCwPivot(), SDG(), SearchKVector(), SectorPatch(), SeeTLE(), SEMGravAcc(), SEMIToSEMR(), SEMRToSEMI(), SEMToSEMND(), Sep(), SeparationGuidance(), SeqBatchLSQOD(), SetCADState(), SetupAssignmentProblem(), SFShustr(), SFShustr2(), Shadow(), SHarm(), Simplex(), Simplex(), Simplex2(), SimplexScaling(), Simulate2DApproach(), Simulate2DLanding(), Simulate3DLanding(), SimulateFlyby(), Skew(), SkewDipl(), SkewSymm(), SnellsLaw(), SolarCellPower(), SolarF(), SolarFluxFromPlateECI(), SolarPressureForce(), SolarSys(), SolidR(), SpaceCamera(), SpacecraftParameters(), SpacecraftThermal(), SphOrb(), SPMMnvr(), SqrFOV(), SReduce(), SS2ND(), SSA(), SSAD(), SSOutput(), StageTimes(), StarCameraModel(), StarMeasurementUKF(), StarSensor(), StateSpacePlot(), SteeringAnglesToQ(), StellAbr(), StellarAttDetUKF(), StellarNavigation(), Step(), StoppingConditions(), SunBeta(), SunData(), SunEarthAttDet(), SunEarthMagAttDet(), SunGuidance(), SunMagAttDet(), SunV1(), SunV2(), SunVectorECI(), SunVectorPointing(), SVPlot(), SXV(), TARes(), TargetFromRPVD(), TargetInFocalPlane(), TBModel(), TCoeff(), TelescopeUKF(), TempCyl(), TempFP(), TerminatorLine(), TerminatorPlanet(), TerrestrialSolarFlux(), TGG(), Thermnet(), ThreeAxisControlDisturb(), ThrstLevel(), ThrustConstant(), ThrustControlGravityTurn(), ThrustControlRaiseApogee(), ThrusterAlignment(), ThrusterAndRWACommand(), ThrusterCAD(), ThrusterColdGas(), ThrusterCommand(), ThrusterLayout(), ThrusterPatch(), Time2NuDomain(), TLETime(), TOMHTAssignment(), TorqueHysteresisDamper(), TrajectoryBetweenTwoPlanets(), Trans3DMF(), TransformECIToEMBR(), TransformECIToSEMR(), TransformEMBRToECI(), TransformSEMRToECI(), TransformSEMRToHelio(), TranslateAxes(), Tree(), TreeDraw(), TreeH(), TreeInit(), TResp(), TriMesh3DMF(), TrueAnomalySpacing(), TSolarP(), TTPlots(), TurboRamjetSim(), TwoBodyRateModel(), TwoDEscape(), TwoDOptimalSailAngle(), TwoUToQ(), U2AzEl(), U2Pix(), U2Q(), U2RADec(), UFromAlphaBeta(), UKF(), UKFP(), UKUDF(), UMinGG(), UnitVectorAverage(), UnitVectorFromOffset(), UnwrapPhase(), UranusAirshipSizing(), UToConeClock(), UVAA(), VarEqP(), VarEqT(), VarGausP(), VarGausT(), VAWTRHS(), VCFlatFile(), VDA(), VEFToVGamAz(), VerSin(), ViewFormation(), VIModel(), VisualizeSailAttitude(), VM2PSFPeak(), VR2AE(), VXPhi(), WaveletMorlet(), WiensDsp(), WindModel(), WireC(), WireDMch(), WireFRB(), WireH(), WireInit(), WirePlot(), WMM(), WPZ(), WrapPhase(), WrapSegments(), WReson(), WriteBSPFile(), WT_Controller(), WT_MultiBody(), WT_VAWTController(), YawRollGyroCompassing(), ZCull(), and ZFresp().