PSS MATLAB Toolboxes: Common/Classes/@statespace/statespace.m File Reference
statespace.m File Reference
Set an element of the class statespace.
Functions
function and (in e, in f)
Append two state space system.
function close (in h, in e)
Close the loop on a statespace control system.
function connect (in e, in f, in c)
Connection of two state space systems.
function eig (in g)
Get the eigenvalues of a statespace system.
function get (in x, in s)
Get an element of the class statespace.
function getabcd (in x)
Get the state space matrices.
function getsub (in x, in kS, in kI, in kO, in name)
Get a subset of state space matrices.
function isempty (in x)
Determine if x is an empty statespace system.
function plus (in e, in f)
Parallel connection of two state space systems.
function series (in e, in f, in m)
Connection of two state space systems.
function set (in x, in y, in s)
Set an element of the class statespace.
function statespace (in a, in b, in c, in d, in name, in states, in inputs, in outputs, in sType, in dT)
Create a state space object.
Function Documentation
and()
function and (in e, in f)
 [ e ]
 [ f ]
Form
 g = and( e, f )
Inputs
 e           (:)   Object of class statespace
 f           (:)   Object of class statespace
Outputs
 g           (:)   Appended
Referenced by A10(), A2Apogee(), AB2RADec(), AbsRelECI2Hills(), ABToDQ(), AC(), ACAero(), Accel(), AccelToLoading(), AccelToSailProps(), AccelVector2ManeuverStruct(), ACEngine(), ACInit(), ACModes(), ACPlot(), ACPointMassControl(), ACResistance(), ACSRWAAndTorquers(), ActiveAeroSurfacesDisplay(), ACTrim(), ActuatorDiskFromPower(), ACWeightEstimation(), AdaptiveThresholding(), AddAxes(), AddedMass(), AddFillToPlots(), AddGoals(), AddMass(), AddMassDot(), AddPlot(), AddRobotArm(), AddSurf(), AddThermalDevices(), AddToPath(), AddZoom(), ADGen(), adjswapmutation(), AdjustMeasSetForKnownMeas(), AdvanceRatio(), AE2RPRA(), AE2VR(), AeroCoefficientPointMass(), AerodynamicShock(), AeroF(), AeroForceAndTorqueCombined(), AeroFormFactor(), AeroHeatFlux(), AERToNu(), AggregateComponents(), AGravity(), AGravityC(), AI2Rate(), AIRC(), AirCoreMagneticTorquerDesign(), AirCoreTorquerModel(), AircraftCostCalculation(), AircraftDesign(), AircraftDragDataStructures(), AircraftEquilibrium(), AircraftGroupDataStructure(), AircraftGroupMass(), AircraftGroupMassStatement(), AircraftPointMassDLM(), AircraftPointMassRHSWithSideslip(), AircraftPowerAndThrust(), AircraftTrajectoryControl(), AircraftWeights(), AirData(), AirlinerSeat(), AirlinerSeats(), AirMass(), Airship3DLayout(), Airship_KLat(), Airship_KLon(), AirshipAero(), AirshipAeroAnalysis(), AirshipAutopilot(), AirshipBallonets(), AirshipCoefficients(), AirshipControlSim(), AirshipCV(), AirshipGeometry(), AirshipInit(), AirshipLinMod(), AirshipMassModel(), AirshipMaxCruise(), AirshipPropeller(), AirshipSim(), AirshipStabConDerivatives(), AirshipState(), AirshipStatespace(), AirshipTrim(), AirshipTrimAnalysis(), AiryDefocused(), AiryDisk(), AlbedoFromTextureMap(), AlignThruster(), AlongTrackMotion(), AlphaBetaToU(), AlphaCentauriSystem(), AlphBeta(), AltitudeSH(), AnalyzeVariableTimeDV(), AngleDetermination(), AngleOfView(), AnglePatch(), AngleSensor(), AngleSepFromRotation(), AnglesRotToU(), AngRate(), AnimateCube(), AnimateSpacecraft(), AnimationGUI(), AntennaGain(), AntennaPatch(), AOverAStar(), APMLinMod(), ApogeeDV(), ApogeeRaisingDeltaV(), ApolloGuidanceCoordinates(), ApolloLunarDescentGuidance(), ApolloTrajectory(), ApophisOrbit(), Append(), ApplyDeltaV(), ApplyProfileToModel(), ApplyThreshold(), ArcEff(), AreaFromActuatorDisk(), AreaOfRectCircInt(), arithXover(), Armijo(), ArrayPatch(), ASM1(), ASM2(), ASM3(), ASM4(), AssemblePlant(), AssessCatalog(), AssignColors(), AStarSearch(), AsteroidCentroid(), AsteroidTrajectory(), AtmDens1(), AtmDensTitan(), AtmDensUranus(), AtmGamma(), AtmJ70(), AtmNRLMSISE(), AtmSnd(), AtmTemp(), AtomicMass(), AttitudeFrames(), AttitudeProfile(), AttitudeProfilePlots(), AttitudeProfilePlugIn(), AttitudeProfileToTorque(), AttitudeProfileVis(), AttitudeProfileWithCon(), AttitudeTarget(), AU2M(), AU2Q(), AutoCorr(), AutoFormCommandList(), AutoFormGeometry(), AutoFormSimStruct(), AutomobileLaneChange(), AutomobilePassing(), AutoPoint(), AutoRadar(), AutoRadarUKF(), AxialTurbineDesign(), AzCoElToU(), AzElRangeRangeDotToRV(), AzElToU(), b2f(), BalReal(), BalRealG(), BankedTurn(), BarycenterEarthMoon(), BatchLSQOD(), BathtubCurve(), BatteryDesign(), BatterySize(), BConeClock(), BDDesign(), BDipoleCoeff(), BDipolePlanet(), Beamwidth3dB(), BearingLife(), BEMHAWT(), BEMVAWT(), BEP(), BFromHHysteresis(), BHalbach(), BHalbachAxialFluxMotor(), BHinge(), BilinearInterpolation(), BilinearTangentAltitude(), BilinearTangentLaw(), BinaryImage(), binaryMutate(), BiotSavart(), BisectionZero(), BladeElement(), BladeSolidity(), BladeStress(), BlckBody(), BldComps(), BlurParameter(), BMF(), BoostPhaseDeltaV(), boundaryMutate(), BoundedMutation(), Brayton(), BraytonIdeal(), BraytonWithRecuperator(), BreguetRangeEquation(), BShuster(), BShuster2(), BToS(), BuildAirshipMassModel(), BuildAirshipModel(), BuildCADModel(), BuildConstant(), C2DelZOH(), C2DFOH(), C2DPulse(), C2DZOH(), C2DZOHWD(), CADNotebook(), calcbits(), CalibrationCube(), CameraCalibration(), CameraCalibrationModel(), CameraControls(), CameraDatabase(), CameraModel(), CameraTransform(), CannyEnhancer(), Capacitor(), CatmullRomSpline(), CCV(), CCVModel(), CCVSobel(), CD0Composite(), CDAirship(), CDCLComposite(), CDCLHypersonic(), CDCLSubsonic(), CDKF(), CDKF45(), CDSkinFriction(), Cell2DToStruct(), CentroidCOM(), CentroidOBJFile(), Centroids(), CEq2C(), CFract(), CheckDeltaVs(), CheckForDuplicateTracksMS(), CircleOfConfusion(), CircuitBoard(), CircularManeuver(), CircularOrbitState(), CLAirship(), ClassERFAmplifier(), CLCDFreeMolecular(), CLCMWing(), CLComposite(), ClimbAngle(), ClockConversion(), ClohessyWiltshire(), CLoopS(), ClosedFormMethod(), CloseMatFile(), ClutterArea(), CMAirship(), CMG(), CMToMassPositions(), CNRComp(), CoarseCentroids(), CoarseProb(), ColdGas(), CollisionDemoCommandList(), CollisionDemoSimStruct(), CollisionMonAlg(), CollisionMonitor(), CollisionMonteCarlo(), CollisionSurvey(), CollProbSet(), CollProbVol(), ColorSpread(), CombineOBJFiles(), CommandPlugIn(), CompactPCIChassis(), CompareHills(), ComplexToReal(), ComputeAirfoilCoeff(), ComputeAlphaConstantFlightPathAngle(), ComputeCoeffFromShape(), ComputeDeltaV(), ComputeDuration(), ComputePayload(), ComputePayloadFraction(), ComputePixelMapScale(), ComputeSailNormal(), ComputeThrust(), ComputeTLE(), ConcordeLD(), ConcordeProperties(), Cone(), ConeAreaAndDerivatives(), ConeClockPatches(), ConeClockToQConstrained(), ConeClockToU(), ConeInt(), ConeInt2(), ConjGrad(), Constant(), ConstantAccelDV(), ConstantDynamicPressureVelocity(), ConstellationGroundContact(), ConstraintForceAndTorque(), ConvertHSA(), ConvertNORAD(), CookeTriplet(), CoordinateFrameFromUV(), Coordinates(), CoordinateTransform(), CoplanarOrbit(), coranaEval(), coranaEval(), coranaMin(), CornerDetector(), Cost3D(), CostLowThrust2D(), CostMatrixRows(), CostSail2D(), Covariances(), CP1Props(), CP2D(), CreateAircraftModel(), CreateBody(), CreateComponent(), CreateHTMLTable(), CreateKVector(), CreateLatexTable(), CreateReport(), CreateRocketModel(), CreateTable(), Cross(), CrossSection(), CrossTrackDeltaV(), CRTBP2kms(), CRTBPJacobiConstant(), CRTBPLinearSystem(), CT2R(), CT2REl(), CT2REq(), CubeSatAttitude(), CubeSatDisturbanceAnalysis(), CubeSatEnvironment(), CubeSatFaces(), CubeSatLunarEnvironment(), CubeSatModel(), CubeSatPropulsion(), CubeSatRadiationPressure(), CubeSatThermalMatrix(), CycleDesign(), cyclicXover(), CylOrb(), Database(), DataRate(), DataRateGain(), DataSize(), DataWindow(), DBalReal(), DblPivot(), DBPower(), DBSignal(), DBump(), DC8(), DCMotorParitySpace(), DeBlankAll(), DeBlankLT(), DeFocus(), Deg2DMS(), Deg2HMS(), DeltaAngleForNewRADec(), DeltaElem2Hills(), deltaFunction(), DeltaML(), DeltaQToRate(), DeltaT(), DeltaWing(), DeltCirc(), DemoManeuverCommandList(), DesignUpperStage(), DetectionFilterBuilder(), DetectionFilterSimulation(), DetectorModel(), DFFAttitudeController(), DFFAttitudeCoordination(), DFFAttitudeManagement(), DFFAttitudeManeuver(), DFFAttitudeTarget(), DFFCollisionMonitor(), DFFCommandProcessing(), DFFControl(), DFFControlLaw(), DFFCoordinateTransformation(), DFFDeltaVManagement(), DFFGuidanceLaw(), DFFISLManagement(), DFFParameterDatabase(), DFFRHS(), DFFSim(), DFFSimGUI(), DFFSimulation(), DFFTeamManagement(), DFIGEquilibrium(), DFIGRHS(), DFIGRHS(), DHCWDX(), DHDADX(), DiffCorr(), Dim(), DiscreteHills(), DisplaySailProperties(), DistAero(), DistAlbedo(), DistanceLabel(), DistantPtToEll(), DistRadiation(), DistributeClusterGoals(), dists(), DistSolar(), Disturbances(), DLyapG(), DMS2Deg(), DMS2Rad(), DMSModel(), DN2Date(), DN2JD(), Dot(), DownrangeAndAltFromTarget(), DragCoeff(), DragLoss(), DragPolarFromData(), DragUndercarriage(), Draw2DViewPlugIn(), DrawAirship(), DrawAlphaBeta(), DrawAngles(), DrawBlobs(), DrawCubeSat(), DrawCubeSatSolarAreas(), DrawFieldLines(), DrawHAWT(), DrawSailAngles(), DrawSailAttitude(), DrawSailCADModel(), DrawSailFrames(), DrawSailMeshVectors(), DrawSCARA(), DrawSCPlanPlugIn(), DrawSCPlugIn(), DrawSpacecraftInOrbit(), DrawSpacecraftPatches(), DrawSpacecraftStruct(), DrawSphere(), DrawStarImageCentroids(), DrawThermalPlugIn(), DrawTreeDiagram(), DrawVAWT(), DRiccati(), DriftRateSigma(), DSpnStab(), DST(), DSTCrit(), DSunCone(), DualRotorDesign(), DVConstantThrust(), DVDisp(), DVForTime(), DVFromMassAndIsp(), DVGlideslope(), DVHohE(), DVLimit(), DVOCCapt(), DVOrbitDrag(), DVReentry(), DVTarget(), DWheel(), Dyn(), DynamicPressureAndHeat(), DynP(), EarthAlb(), EarthBc(), EarthEclipseDuration(), EarthEnvironment(), EarthEscape(), EarthGuidance(), EarthHelioState(), EarthMoon(), EarthMoonRotFrame(), EarthMoonSystemConstants(), EarthOrbToHelioOrb(), EccentricTetrahedronCommandList(), EccentricTetrahedronSimStruct(), EccTeamGoals_Structure(), ECI2LVLH(), ECI2MeanElements(), ECI2OrbitPlane(), ECIToEarthMoonRot(), ECIToEF(), ECIToNED(), ECIToPlanet(), ECIToSunEarthRot(), Eclipse(), EclipseFromECI(), EclipseHelio(), EclipticInjectionPlane(), ECLSSSizing(), EffFocalLength(), EffPw(), EFToLatLonAlt(), EigEval(), EKFUpdate(), El2Eq(), El2LKl(), El2RV(), ElectricPropulsionDesign(), ElectricThrust(), ElectricThrusterPower(), EllipseImageFit(), EllipsePatch(), EllipsePropCirc(), Ellipsoid(), ELM(), EMarkov(), EMBToEMBND(), Energy(), EnergyHeight(), EnergyPerRing(), EnergyWRTMoon(), EngineDataFromTable(), EngineTable(), enhancederXover(), EntryLiftAndDrag(), EP2M(), EPPS(), Eq2El(), Eq2RV(), Equal(), er(), er(), ESA(), ESAChord(), ESACS(), ESAssign(), ESAssignDraper(), EstimateCost(), EulNED(), EulRate(), EVAssgnC(), EVAssgnE(), ExportVerticesToOBJ(), ExtrudeFromProfile(), F100(), F18Model(), f2b(), FAeroSurfaceAccommodation(), FAIR(), FBudget(), FCartOrbD(), FCoreAndMoving(), FEarthMoon(), FEarthMoonSun(), FElectricPropulsion(), FFEccAnalyzeShape(), FFEccDiscreteHills(), FFEccDMatPeriodic(), FFEccDYDX(), FFEccDYDX2(), FFEccEstimateCost(), FFEccFrameCompare(), FFEccFrenet2Goals(), FFEccGenerateTeamGoals(), FFEccGoals(), FFEccGoals2Hills(), FFEccHexahedronGeometry(), FFEccHills2DeltaElem(), FFEccHills2Goals(), FFEccLawdensEqns(), FFEccProp(), FFEccRMat(), FFEccShapes(), FFEccTetrahedronGeometry(), FFEccYExt(), FFEccZExt(), FFIntegrate(), FFMaintenancePlotter(), FFMaintenanceSim(), FFMaintenanceTests(), FFSim(), FFSimPlotter(), FHingeOrbit(), FileFullpath(), FindDriftTerm(), Finder(), FindIfInBetween(), FindSolsticeOrEquinox(), FindValidAngleRange(), FinFactors(), FinGeometry(), FirstLineOfCode(), FitEllipse(), FitHist(), FitStarHist(), FitStarMoffat(), fixpopupuicontrol(), FLambdaToConeClock(), FlightEquilibrium(), FlightPathAngle(), FLowThrust2D(), Flyby(), FlybyConstantThrust(), FlybyOptimal(), FlybyReport(), FlywheelStresses(), FMagSim(), FMovingBody(), FocalLengthFromAngleOfView(), FOPID(), FOrbCartH(), FOrbHF(), FOrbitGeneral(), FOrbitMultiSpacecraft(), FOrbitSingle(), FOrbKF(), FOrbLEOP(), FOrbLowThrust(), FOrbLTE(), ForceAndTorqueEnvelope(), ForceSimple(), FormationDesignGUI(), FormFactorSurfaceOfRevolution(), FormFactorWing(), FourierSeries(), FP2RADec(), FPA(), FPFA(), FPlanetControl(), FPSensors(), FracDI(), Fractal(), FractionalSelection(), FRBwRIG(), Frenet2Hills(), FResp(), FRespG(), FRespPlot(), FrictionBristle(), FrictionSmooth(), FRotatingPlanet(), FRotatingSun(), FRSCGen(), FRSMPlan(), FRSProp(), FS4Deployment(), FSailCombined(), FSailEarthMoon(), FSailEarthSun(), FSailGuidance(), FSailTB(), FSolar(), FSolarPanelThermal(), FSWClock(), FThrustLander(), FTimeVaryingI(), FuelMass(), Fuels(), FuelUpdt(), Fuselage(), FXModel(), ga(), gaDemo1Eval(), Gain3dB(), gaMichEval(), GAMin(), GaussianCPDF(), GaussianDerivative(), GaussianImageFilter(), GaussianPDF(), gaZBGrad(), gaZBGradEval(), Gearbox(), Gen2nd(), GenerateAirshipAeroMats(), GenerateGrid(), GenerateSwath(), GenerateTeamGoals(), GeneticAlgorithm(), Geo(), GeoEclps(), GeoMagLatLon(), GeomPatch(), GeoOptimalMission(), GeoSwitchingMission(), GetCADVF(), GetEntry(), GetFlex(), GetFuelBudgetDataFromCAD(), GetHillsMats(), GetInputFromString(), GetLVLHMats(), GetNewTag(), GetStage(), GimbalC(), GimbalRates(), GJInv(), Glide(), GlideSlope(), GlideslopeGuidance(), GlideslopePlanner(), GlobeGrid(), GMSTime(), Goals2DeltaElem(), Goals2Hills(), GOESLeg(), GondolaGeometry(), GoodYearBlimp(), GPMargin(), GPSOrbit(), GPSReceiverNav(), GPSSatellite(), GravityGradientBoom(), GravityGradientFromR(), GravityGradientStiffness(), GravityHelio(), GravityMap(), GravityTurnSim2D(), GrayBody(), GroundTrack(), GroundTrackErrorBudget(), GSS(), GuidedLaunch2DCost(), GuidedLaunch2DRHS(), GuidedLaunch2DSim(), GuidedLaunch3D(), GuidedLaunch3DRHS(), GuidedLaunchOpt2D(), GVEGuidance(), Gyro(), GyroData(), HalbachField(), HalbachMotorDesign(), HalfEllipsoid(), HallThrusterModel(), HALOFamily(), HALOInit(), HAngleUKF(), HCircularBillow(), HCw2R(), HDAi(), HeatExchanger(), HeatingValue(), HeatTransferChannel(), HeatTransferCoeffTaylor(), HelicalGear(), HelioPlot(), HelioToBPlane(), HelioToPlanet(), HEq(), heuristicXover(), Hexahedron(), HeXeMixture(), HGimballedBoom(), HierarchicalListPlugIn(), Hills2DeltaElem(), Hills2Frenet(), Hills2Goals(), HillsEqnsSLO(), HillsFramePlot(), HingeRotationMatrix(), HMagEl(), HMS2Deg(), HMS2Rad(), HMS2S(), HohmannTransferRendezvous(), HorizonAngle(), HorizontalWind(), HpH(), HRangeMeasurement(), HRangeRangeRate(), HRG(), HSAData(), HSRCAD(), HUD(), HydrazineThruster(), HyperRDE(), HypgF1(), HypgFr(), HypgMr(), I2B(), IC3X326(), ICONS(), ICSN(), IdealRkt(), IDotS4(), IGormont(), Illumination(), ImageNoise(), ImageOverlay(), Imager(), ImagerPSF(), IMMPredict(), IMMUpdate(), ImpulsiveLPManeuver(), ImpulsiveManeuver(), IncLatVelToAzimuthHeading(), InclinationRate(), IndexedImageToRGB(), InducedDragCoeff(), Inductor(), InertiaCubeSat(), InertiaFromOBJFile(), InertiaTotal(), InertiaTubeSat(), InitializeFormation(), initializega(), initializeoga(), InitializeSailGravity(), InitializeSailSim(), InitialMass(), InitialOrientation(), InletAndNozzle(), InletLoss(), Int2VM(), Integral(), IntegrateMassProps(), IntegratePSFs(), InterferenceFit(), InterpolateCircle(), InterpolateState(), IntersectLineAndCone(), IntersectLineAndEllipsoid(), IntersectPlaneAndSphere(), IntExp(), IntExpR(), inversionMutation(), InvSys(), ISLFOV(), Isothermal(), IsothermalLunar(), ISSOrbit(), IsValidField(), IteratePeriodicOrbit(), IterativeImpulsiveManeuver(), J2OrbitEffects(), JacchiaLineberry(), Jacobian(), JacobianODE(), JacobVB(), JCart2Sp(), JD2Date(), JDStartTransfer(), JetEngine(), JetEngineAnalysis(), JetEngineDefinitions(), JetEnginePerformance(), JSp2Cart(), K2L(), Kaimal(), KalmanFilterCombine(), KConst(), KConstP(), KConstQ(), KFExItMu(), KFInitialize(), KFPredict(), KFSAAD(), KFSunAndEarth2(), Kms2CRTBP(), KronProd(), KronSum(), KSmooth(), L1011(), L2K(), L2OrbitPlots(), L2OrbitSim(), LADAREquation(), LADARTransmitPower(), LAETR308CAD(), LambdaToConeClock3D(), LambertDoubleRendezvous(), LambertOpt(), LambertTOF(), LandingConst2D(), LandingConst2DONS(), LandingConst3D(), LandingControl(), LandingControlBilinear(), LandingControlGravityTurn(), LandingCost3D(), LandingForce(), LandingLegsCAD(), LatLon(), LatLonToR(), LatLonToRangeAzimuth(), LatLonToRAz(), LaunchOptions(), LaunchRHSData(), LaunchTime(), LDDeltaWing(), LeadLag(), LeapYear(), LeastSq(), LegendFig(), LEPDS(), LETPhasing(), LFBal(), LFState(), LFToECI(), LibrationData(), LibrationFrequency(), LiftAndDrag(), LiftAndDragCoeff(), LiftAndDragJonesSearsHaack(), LiftAndDragSeaLevelToOrbit(), LightDetectorIntegrals(), LightGathering(), LinkAnalysisTool(), LinkBudget(), LinkOrbitAnalysis(), LinOrb(), LinOrbLQG(), LinOrbNormalized(), LiquidMetalProps(), LLRToProb(), LoadAtt(), LoadCAD(), LoadCatalog(), LoadEarthMap(), LoadFlex(), LoadGEM(), LoadGravityModel(), LoadILRSDataFromFRD(), LoadingToAccel(), LoadingToLightness(), LoadLunarTopography(), LoadNORAD(), LoadOBJFile(), LoadOBJModel(), LoadShapeFile(), LoadSolarFluxHistory(), LoadStarImage(), LocallyOptimalConeClock3D(), LocalSolarTime(), LocusOfVisibility(), LossAtmosphericGas(), LossDepointing(), LossFreeSpace(), LossPolarization(), LossPrecipitation(), LowEnergyEarthToMoonTransfer(), LowEnergyTransferInCRTBP(), LowThrustControl(), LowThrustEscape(), LowThrustGVE_EventFcn(), LowThrustGVERHS(), LowThrustSim(), lox(), LPCircular(), LPEccentric(), LPEccentricGVE(), LPvsCF(), LQC(), LQOrbitController(), LRLoopAntenna(), LRRectangleAntenna(), LSQLaunch(), LTAN(), LTPlaneChange(), LTSpiral(), LTVCon(), LumenToWatt(), LunarDisplacement(), LunarHalo(), LunarLandingControl(), LunarModuleFirstStage(), LunarOrbitInsertion(), LunarProfile(), LunarRelativeState(), LunarTargeting(), LunarTrajectoryControl(), LVCombineSRB(), LVModelFeasibilityFix(), LVStageTimes(), LyapG(), Lyapunov(), LyapunovFamily(), LyapunovInit(), M2E(), M2EApp(), M2EEl(), M2EHy(), M2EP(), M2MS(), MachFromAreaRatio(), MachFromPR(), MagAirC(), MagControlTwoAxis(), MagField(), MagFieldData(), MagFieldPlanet(), MagneticControl(), MagneticDipole(), MagneticHysteresis(), MagneticTorquerDesign(), MagPlot(), MagTComp(), MakeSquareSail(), ManeuverDuration(), ManeuverSuccessorNodes(), ManeuverSuccessorNodes3D(), Map(), Markov(), MassBudget(), MassCrewAndPassenger(), MassEquivalentDV(), MassFlow(), MassFlowParameterR(), MassFuelElectricConstantPower(), MassFuelElectricConstantThrust(), MassFuelElectricConstantUE(), MassPressureVessel(), MassProp(), MassPropertiesSolidObjFile(), MassPropertiesTetrahedron(), MassVehicle(), MassVolH2O2(), Mat2Q(), MatchingCircuit(), maxGenTerm(), MBModel(), MeanAnom(), MeanAnom2TrueLat(), MeasCamera(), MeasEarthSensor(), MeasEarthTarget(), MeasGPS(), MeasMagnetometerEarth(), MeasRangeGroundStation(), MeasRangeGroundStationEF(), MeasRateGyro(), MeasRateIntegratingGyro(), MeasRelativePosition(), MeasStarAngleAndChord(), MeasState(), MeasSunSensorDigital(), Measurements(), MeasurementsSunMagUKF(), MEqToEl(), MEqToRV(), MergeConstantDB(), Mesh2(), Mesh3DMF(), MeshSOR(), MeshToPatch(), MHTDistance(), MHTGUI(), MHTInitialize(), MHTInitialTrackScore(), MHTLLRUpdate(), MHTTrackMerging(), MHTTrackMgmt(), MHTTrackScore(), MHTTrackScoreKinematic(), MHTTrackScoreSignal(), MHTTrkToB(), MinDEllipsoid(), MinE4BP(), MinTOrbitInjection(), MixedFlowTurbofan(), MixedFlowTurbofanProfile(), MLog(), ModulationSpectralEfficiency(), MomentumUnloading(), MoonECIElements(), MS2M(), MSData(), MSThrustModel(), MSTOR(), MSVRatio(), MuFermenter(), MultiBEPPlot(), multiNonUnifMutation(), MutualInductanceCoaxialCoil(), NadGen(), Nadir(), NavigationCamera(), NavigationCameraSunStar(), NavigationMeasurement(), NavTargetTrackingLunar(), NavTargetTrackingPlanetary(), ND2SS(), NearestOffset(), NeptuneAirshipSizing(), NewStats(), NewtonianAerodynamicsFromCAD(), NewtonianAeroPropertiesFromOBJFile(), NewtonianAeroTable(), NewtonianAlphaFromCAD(), NewtonianForceECI(), NewtonianLD3D(), NewtonsMethod(), NewtRaph(), NewtRaph2(), NFromJ(), NFromMT(), NLFilter(), NOAAWindData(), NoisePower(), NominalSafeGuidance(), NonDimensionalOrbit(), NonKeplerianSun(), NonlinearEstimator(), NonlinearSpring(), NonlinearSpringFault(), NonMaxSuppression(), nonUnifMutate(), NORAD(), NormalizationMatrix(), normGeomSelect(), NoseCone(), Notch(), NPlot(), NRLArray(), NuclearReactorModel(), NutDelta(), ObservationTimeWindows(), ObservationTimeWindowsPlot(), Occurences(), OddEven(), ODETimeDisplay(), OnlineApproximator(), oox(), OpenFrame(), OpticalAngleError(), OpticalBackgroundNoise(), OpticalLinkBudget(), OpticalNavAccuracy(), OpticalNavigation(), OpticalNavigationMeasurement(), OpticalNavigationMoon(), OpticalNavigationSun(), OpticalNavLunarLandmarkStar(), OpticalNavPlanetStar(), OpticalNavPlanetStarNoiseMatrix(), OpticalRadialDistortion(), OpticalReceiverNoiseDensity(), OpticalSurfaceProperties(), OptimalAngleOfAttackHypersonic(), OptimalAssignment(), OptimalCharacteristicVelocity(), OptimalExhaustVelocity(), OptimalImpulseDuration(), OptimalLunarLanding(), OptimalMLIDensity(), OptimalTrajectory(), OptimalTripTime(), OptimalVehicle(), optMaxGenTerm(), OptTestFun(), OptTestFunEcon(), OrbElemDiff(), OrbitDisplayPlugIn(), OrbitInsertion(), OrbitLoweringManeuvers(), OrbitODGenObs(), OrbMnvrBielliptic(), OrbMnvrHohmann(), OrbMnvrInclAndHohm(), OrbMnvrInclination(), OrbMnvrLongAndIncl(), OrbMnvrLongitude(), OrbMnvrOneTangent(), OrbMnvrPhaseChange(), OrbMnvrSemimajor(), OrbNEq(), OrbRate(), OrbTrack(), OrbTrackECI3D(), OrbView(), OutOfPlane(), OverArea(), P3Axis(), PackageOrbitDataForPlayback(), Pade(), PAHohmn(), PAL(), Panel(), PanelBoxCAD(), PanelFrame(), PanelWithCenterHole(), PanelWithCutout(), ParabolaToS(), ParabolicReflector(), Parallel(), ParallelToSerialStages(), ParamGUI(), parse(), ParseIOData(), PartialDisk(), partmapXover(), PatchedConicElements(), PayloadMassForBurnoutVelocity(), PBudget(), PCState(), PDAL(), Period(), PeriodicOrbitFromGuess(), PhasePlane(), PID3Axis(), PIDesign(), PIDMIMO(), PIDProper(), PIDWithLag(), PILeaky(), Pilot(), PinholeStarCamera(), PitchLoop(), PitchMotorSizing(), PivotMch(), PlanarHelioOptimal(), PlanarHelioOptimalSlidingTime(), PlanetaryAccelerations(), PlanetaryAtmDens(), PlanetaryDistanceToSun(), PlanetaryRadiationAndAlbedo(), PlanetCentroid(), PlanetEnvironment(), PlanetOpposition(), PlanetOptimalTraj(), PlanetPosition(), PlanetPositionEMBarycenter(), PlanetPosJPL(), PlanetRot(), PlanetRotation(), Planets(), PlanetSensorDualScan(), PlanetTrajectoryPlot(), PlanetWithTerrain(), PlanetWithTerrainPatch(), PlanningParameters_Structure(), Plot2D(), Plot2DTrajectory(), Plot3DEllipsoids(), Plot3DOrbit(), Plot3DTrajectory(), PlotDoubleYAxis(), PlotEMTraj(), PlotEngine(), PlotLambertTransfer(), PlotLET(), PlotOrbit(), PlotOrbitPage(), PlotOrbitTransfer(), PlotPayloadFraction(), PlotPlanet(), PlotPlanetaryOrbit(), PlotSailClock2D(), PlotSailForce(), PlotSailForce2D(), PlotSailProfile(), PlotSEMTraj(), PlotThermal(), PlottingParabolas(), PlottingTool(), PlotVector(), PlotWindField(), PlotZermelo(), PltOrbit(), Plume(), PMABCMachineSwitchedRHS(), PMBMachineRHS(), PointCameraModel(), PointInGridInTriangle(), PointInPolygon(), PointInTriangle(), PointSpreadFunction(), PointSpreadFunction2DGaussian(), PoissonNoise(), PolygonProps(), PopulateCostMatrix(), PorkChopMin(), PorkChopPlot(), PorkChopTOF(), PorkChopTOFKepler(), PositionDeltaV(), PostProcessCOM(), PowCompAnlytBsd(), PowerDesign(), PowerFromActuatorDisk(), PowerReceived(), PPDelay(), PrandtlNumber(), Pressure(), PressureRatioFromMach(), PressureRatioFromTemp(), PrincipalAxes(), PrintTitle(), PrintToImage(), PrivilegedAssignment(), ProbDetection(), ProbToLLR(), ProcessCatalog(), ProcessStarImage(), ProcessTag(), Product(), ProfileStruct(), ProjCirc(), Propagate4BP(), PropagateCRTBP(), PropagateCRTBPToPeriapse(), PropagateLowThrust(), PropagateNBody(), PropagateOrbitPlugIn(), PropagateState3D(), PropellantMass(), PropellerMomentum(), PropellerPower(), PropellerThrust(), PtchCnc(), Q2AU(), Q2RADec(), QAlign(), QAlignWithCon(), QECI(), QError(), QForm(), QFrom2U(), QFromDQ(), QFromU(), QHillsToBody(), QMult(), QMultJPL(), QProp(), QRotateToAlign(), QRotateToAlignWithCon(), QSail(), QSLERP(), QSpin(), QSunNadir(), QSunPointing(), QTForm(), QToConeClock(), QToPFTarget(), QuadCost(), QXToAlphaDelta(), R2LatLon(), Rad2DMS(), Rad2HMS(), RadarAccuracy(), RadarCrosssection(), RadarEquation(), RadarEquationPulse(), RadarSN(), RADec2FP(), RaDec2Q(), RaDec2U(), RADecToPix(), RadiationBelts(), RadiationShapeFactor(), RadiationShield(), RAEToM(), Ramjet(), RamjetExternalHeatSource(), RamjetKerrebrock(), RandPM(), RangeMeasurement(), RankineCycle(), RapidSwath(), RARP2A(), RARP2E(), RateGyro(), RateOfClimb(), RayleighPitotTube(), RayTransferMatrix(), RAzToLatLon(), RBModel(), RDE(), REA(), ReactionWheel(), ReactionWheelFriction(), ReactionWheelStress(), ReadAsteroidDatabase(), ReadBSPFile(), ReadCSVTable(), ReadHorizons(), ReadLensData(), ReadTopexPOE(), REAModel(), RectangularBeam(), RectilinearMission(), ReentryPlot(), REl(), RelativeCoord(), RelativeOrbitState(), RelativeStateFromPoints(), RelativeVelocityError(), ReliabilityMOfN(), ReliabilityParallel(), ReliabilitySeries(), RelState2Absolute(), ReluctanceMachineRHS(), ReluctanceMachineRHS(), RendezvousPlanner(), RepeatGroundTrack(), REq(), ReshapeCovariance(), ResidStat(), Residual(), ResistanceAWG(), ResistivityAluminum(), ResistivityCopper(), RestrictDeltaV(), RFromCPAndGamma(), RFSystemNoise(), RHAzToECEF(), RHS1DWithAccel(), RHS1DWithAccelUKF(), RHS2DAnglePolarOrbit(), RHS2DOrbit(), RHS2DPointMass(), RHS2DPolarOrbit(), RHS3DPointAircraft(), RHSAiryDefocusedPSF(), RHSAiryPSF(), RHSAlphaCentauriMission(), RHSAutoSuspension(), RHSBatchR(), RHSBZ(), RHSCisLunarMission(), RHSClockDrift(), RHSCMG(), RHSCSTR(), RHSCubeSat(), RHSEquinoctial(), RHSFermenter(), RHSFlatEarthSet(), RHSFluidizedBed(), RHSFriction(), RHSGeoHarm(), RHSGeoJ2(), RHSGyroNBody(), RHSGyroWithOrbit(), RHSHelio2DOrbit(), RHSHelioWithPlanets(), RHSHysteresisDamper(), RHSICSTR(), RHSIsothermal(), RHSIsothermalCubeSat(), RHSLaunchVehicle2D(), RHSLaunchVehicle3D(), RHSLiftingReentry3D(), RHSLiftingSatellite(), RHSLinOrb(), RHSLunarLander(), RHSLunarMission(), RHSMEMSGyro(), RHSMoffatPSF(), RHSNLSpring(), RHSOpt2DOrbit(), RHSOptimalFPA(), RHSOrbit(), RHSOrbitPlanetFixed(), RHSOrbitUKF(), RHSPartialNLSpring(), RHSpH(), RHSPlanet3DToAB(), RHSPlanetTakeoff(), RHSPointMass(), RHSPressure(), RHSRBUKF(), RHSReactionWheel(), RHSReactionWheelWithOrbit(), RHSReentry(), RHSRigidBody(), RHSRigidBody6DOF(), RHSRigidBodyMass(), RHSRigidBodyWithTarget(), RHSRobot(), RHSRobotInitialize(), RHSRollingMissileLinear(), RHSRVPlanetFixed(), RHSRWA(), RHSRWAIDotSC(), RHSRWASC(), RHSSpacecraftWithRWA(), RHSStateLunarMission(), RHSTPVC(), RHSTSTO(), RHSUKF(), RHSUKFCisLunarMission(), Riccati(), RIGModel(), Ring(), RK4(), RLP(), RMarkov(), RNEH(), RocketChemical(), RocketDatabase(), RocketDrag(), RocketEquation(), RocketFromUEAndT(), RocketH2O2(), RocketModel(), RocketVariableUEAndT(), RollPitchToQECI(), RollYawEstimator(), RotateOBJFile(), RotationalDynamicsRHS(), RotBeamBending(), RotMat(), RotorAssemblyAerodynamics(), roulette(), RPhiTheta2Cart(), RPRA2AE(), RPV2AE(), RSHMoon(), RToNu(), RV2A(), RV2AE(), RV2El(), RV2ElDPT(), RV2Eq(), RV2RaDec(), RVFromKepler(), RVOrbGen(), RVOrbGenDV(), RVOrbHF(), RVSet2El(), RVToMEq(), RVToRADec(), RVWithJ2(), RWA(), RWABristle(), RWAModel(), RWASizing(), RWASmart(), RWAWithPower(), RYDyn(), S2Damp(), S2HMS(), S4DeployTorque(), Sa2Q(), SAADMain(), SafeEllipsePosVel(), SafeGuidance(), SafeGuidanceBurnData(), SafeGuidanceParameters(), SafeGuidanceSim(), SafeGuidanceSimInit(), SailACS(), SailClosedLoopNLEqns(), SailDefaultColors(), SailDisturbance(), SailEnvironment(), SailEphemAlmanac(), SailEphemEarth(), SailForceSubplots(), SailMesh(), SailOrbitContours(), SailPropsToAccel(), SARosenbrock(), SatelliteSubsystemMass(), SatelliteVisibility(), SaturnsRings(), SaveMovie(), SaveStructure(), SaveSurfacePropertiesDSim(), ScanToTrackAuto(), SCARAIK(), ScDB(), SCHarm(), SCHarmD(), SCMG(), SCWithRollPivot(), SCwPivot(), SDG(), SearchKVector(), SecondOrderGuidance(), SecondOrderGuidance3D(), SectorPatch(), SecToString(), SeeTLE(), SegmentIntersection(), SelectTLEGroup(), SEMGravAcc(), SemimajorAxisRevisit(), SEMIToSEMR(), SEMRToSEMI(), SEMToSEMND(), Sep(), SeparationGuidance(), Series(), SetCADRotation(), SetupAssignmentProblem(), SFShustr(), SFShustr2(), SFunc(), Shadow(), Shannon(), ShapedStrut(), ShapeFlt(), SHELSFlange(), SHELSInterface(), shiftMutation(), SigmaPointsChol(), SimpleFuselage(), SimpleLiftAndDrag(), Simplex(), Simplex(), Simplex2(), simpleXover(), Simulate2DApproach(), Simulate2DLanding(), Simulate3DLanding(), SimulatedAnnealing(), SimulatePlanarHelioTrajectory(), SimulateStraightLineTrajectory(), SinePC(), SingleCrossover(), singlePtX(), SizeABCD(), SizeAC(), SizeTurbineAndCompressor(), SkewDipl(), SkinDepth(), SLPLDataStructure(), SLPLDeltaV(), SLPLFindDistance(), SLPLFindDuration(), SLPLFindMass(), SLPLFindPower(), SLPLReport(), SLPLTrajectory(), SMADiffDPT(), SMarkov(), Snapshots(), SNR(), SolarCellCoverage(), SolarF(), SolarFlux(), SolarFluxFromPlateECI(), SolarFluxPrediction(), SolarPanelThermal(), SolarPressureForce(), SolarSysJPL(), SolarSystemElements(), SolarSystemProperties(), SolarVisibility(), SolarWingSupport(), SolidR(), SolidRocketInertia(), SolutionWindow(), SolveFlybyPower(), SolveLambdaFlyby(), SolveSigma(), SolveT(), SolveTD(), SolveVaneAngles(), SortFK5(), SortTeamGoals(), SpaceCamera(), SpacecraftFromAccel(), SpacecraftThermal(), SpecificPower(), SpectralRadiusJumpMarkov(), Spectrum(), SpeedSnd(), SphereOfInfluenceHelio(), SphericalGrid(), SphOrb(), SPIGuidance(), Splash(), spline_maths(), SPMMnvr(), SpurGear(), square(), SReduce(), SRiccati(), SS2ND(), SSA(), SSTokamak(), StageTimes(), StagnationPAndT(), StarCameraBasicModel(), StarCameraModel(), StarCameraViewer(), StarCentroid(), StarCentroidCOM(), StarDataFromStarMatrix(), StarDataGeneration(), StarDensity(), StarIDPyramid(), StarIDTestCatalog(), StarMeasurement(), StarSensor(), StateSpacePlugIn(), StaticStall(), SteamTablesSuperheatedEnthalpy(), SteeringAnglesToQ(), StellarAttDetEKF(), StellarAttDetEKFNoGyros(), StellarNavigation(), StepSim(), STKAtt(), STKOrbit(), StopGUI(), StoppingConditions(), STOVL(), SToW(), StraightLineConstantAccel(), StraightLineConstantThrust(), StraightLineOptimal(), StrehlRatio(), StringMatch(), StripedQuadrant(), StructToCell2D(), StructToText(), StructuralMass(), StructureAnalysis(), StructureList(), SubGoals(), SubL1Accel(), SubOrbDistance(), SubOrbLambert(), SubOrbMaxRange(), SubOrbTrajAnalysis(), SubOrbVelocity(), SunAzEl(), SunBeta(), SunCone(), SunData(), SunEarthAttDet(), SunEarthMagAttDet(), SunEarthMoonSystemConstants(), SunNadir(), SunRA(), SunSensor(), SunSyncNode(), SunV2(), SunVectorECI(), SunVectorPointing(), SurfaceAreaEllipsoid(), SurfaceOfRevolution(), SVPlot(), swapmutate(), Sweep(), SwitchTime(), SXV(), Symmetrize(), SynchronousSpeed(), SynodicFromSemimajorAxes(), SynodicPlanets(), TabBox(), Takeoff(), TakeoffTransition(), TankVolume(), TAntennaGround(), TARes(), TargetFromRPVD(), Targeting4BP(), TargetSlew(), TAttenuator(), TaxiingFuel(), TBModel(), TCoeff(), TeamGoals_Structure(), TElec(), TelescopeAperture(), TempRatioFromMachAndGamma(), TerminatorLine(), TerminatorPlanet(), TerrestrialSolarFlux(), TesselatePolygon(), TestControlCommandList(), TestControlSimStruct(), TestFFEccLinOrb(), TestLPCircular(), TestLPEccentric(), TestLPEccentricGVE(), Tetrahedron(), Tfr2Imp(), Tfr3Imp(), ThermalConductivityAndViscHeXe(), ThermalEquilibrium(), Thermnet(), THohmn(), threeswapMutation(), Throttle(), ThrstLevel(), ThrustAngleExplicit(), ThrustConstant(), ThrustControlRaiseApogee(), ThrustElectric(), ThrusterAlignment(), ThrusterAndRWACommand(), ThrusterCAD(), ThrusterColdGas(), ThrusterCommand(), ThrusterLayout(), ThrusterPatch(), ThrustModel(), ThrustPropeller(), ThrustTurbofan(), TileOBJSphere(), TimeGUI(), TimeLabel(), TimeLabl(), TimeToGo(), TitanAtmosphere(), TMoon(), TNoiseCascade(), TOMHTAssignment(), TOMHTPruneTracks(), TOMHTTree(), TorqueHysteresisDamper(), TorqueVAWT(), TotalPressureAndTemperature(), tournSelect(), TPlanet(), TPlate(), TrackingAccuracy(), TrajectoryBetweenTwoPlanets(), TrajectoryOptimization(), TrajectoryPlot(), TransferAndPhaseAngle(), TransferOrbit(), TransferTimeToDV(), TransformECIToEMBR(), TransformECIToSEMR(), TransformEMBRToECI(), TransformerRHS(), TransformGeom2Hills(), TransformGridCoordinates(), TransformLagrangePoints(), TransformSEMRToECI(), TransformSEMRToHelio(), TReceiver(), Tree(), TreeAdd(), TreeBldCAD(), TreeH(), TreeInit(), TriangleWave(), TriMesh3DMF(), TripTime(), TrnsZero(), TruEarth(), Truss(), TSCurve(), TSky(), TSolarP(), tsp(), TSTODragData(), TSTOSizing(), TSun(), TTPlots(), Tube(), TubeArc(), TubeBetweenPoints(), TubeSatDefaultDataStructure(), TubeSatModel(), TubeSection(), TubeWithBends(), Turbofan(), Turbofanramjet(), Turbojet(), TurbojetNoThrust(), TurboRamjet(), TurboRamRocket(), TurningRadius(), TVDesign(), TwoBodyRateModel(), TwoDEscape(), TwoDOptimalSailAngle(), TwoObjectTrajectoryViewer(), TwoUToQ(), U2AzEl(), U2RADec(), UDKalmanFilter(), UFromAlphaBeta(), UGravity(), UIElement(), UKF(), UKFRTSS(), UKFUT(), UKFWeight(), UKUDF(), uniformMutate(), uniformxover(), Unit(), UnitVectorAverage(), UnitVectorFromOffset(), UpdateSailOpticalProps(), UranusAirshipSizing(), USR30Motor(), UToConeClock(), UToMF(), V0FromJacobiConstant(), ValidData(), VarEqP(), VarEqT(), VarGausT(), VAtm(), VBDToVBT(), VCFlatFile(), VDA(), VEFToVGamAz(), VelAltFpaToAENu(), VelAltFpaToHAE(), VerifyCollStruct(), VerSin(), VFToMassStructure(), ViewEllipsoid(), ViewGeometry(), ViewHills(), ViewRelativeMotion(), VInfRPToRV(), VisualizeSailAttitude(), VM2Int(), VM2Photons(), VM2PSFPeak(), VMToPhotons(), VonBraunRocket(), VR2AE(), VStall(), VTToVB(), VXPhi(), WalkerConstellation(), Water(), Watermark(), WaveletMorlet(), Weather(), WeathLeg(), Wedge(), WettedArea(), WindAdmittance(), WindClass(), WindDeterministic(), WindFromLatLon(), WindGust(), WindLatLon(), WindLatLonAlt(), WindMdl(), WindModel(), WindPowerClass(), WindspeedHours(), WindTrendsDemo(), WindTurbinePower(), Wing(), WingAreaToTaper(), WingFromParameters(), WireC(), WireFRB(), WireH(), WMM(), WorldToCamera(), WorstCasePerturbations(), WorstFirstAssignment(), WPZ(), WrapPhase(), WReson(), WriteBSPFile(), WriteCM(), WriteEngineData(), WT_DFIG(), WT_Generator(), WT_HAWTDFIGSetup(), WT_HAWTSetup(), WT_MultiBody(), WT_Structure(), WT_VAWTSetup(), YawRollGyroCompassing(), YBComp(), Z2Damp(), ZeroPayloadFlyby(), ZFresp(), and ZodiacalLight().
close()
function close (in h, in e)
 e relates y to u.
 u = -ey
Form
 g = close( h, e )
Inputs
 h           (:)   Object of class statespace
 e           (:)   Connection matrix
Outputs
 g           (:)   Closed loop system
References CellToMat(), isempty(), length(), and zeros().
Referenced by AccelVector2ManeuverStruct(), AlignThruster(), AllanVariance(), AnimateCube(), AnimateSpacecraft(), AssemblePlant(), BiotSavart(), BlockDiagramPlugIn(), CADColor(), CloseIfHandle(), CloseMatFile(), CoarseCentroids(), CompareHills(), DFFSimGUI(), Disturbances(), Draw2DViewPlugIn(), DrawAC(), DrawAircraft(), DrawHAWT(), DrawRobot(), DrawSCPlugIn(), DrawVAWT(), FAero(), FAtmDensity(), FEngine(), Figui(), FPlantNoise(), FSolar(), GeoOptimalMission(), GeoSwitchingMission(), ImageOverlay(), J2Prop(), LambertDoubleRendezvous(), LargeFormationControl(), LowEnergyEarthToMoonTransfer(), NavTargetTrackingLunar(), NominalSafeGuidance(), OpticalNavigation(), OpticalNavigationMoon(), PeriodicOrbitFromGuess(), PlottingTool(), ProcessCatalog(), PropagateLowThrust(), PropagateOrbitPlugIn(), QFrom2U(), QFromU(), QRotateToAlign(), QRotateToAlignWithCon(), QSail(), QSunPointing(), ReadTopexPOE(), ReduceCatalog(), SaveMovie(), SaveSurfacePropertiesDSim(), SpaceCamera(), SpacecraftPlugIn(), StarCentroidCOM(), StarDataFromStarMatrix(), StarDataGeneration(), Sweep(), TelemetryOffline(), ThrustControlGravityTurn(), ThrustControlRaiseApogee(), ThrusterAlignment(), TimeDisplay(), TimeGUI(), and WaitBarManager().
connect()
function connect (in e, in f, in c)
The connection is
 e -> f
The connection matrix is lists the indices of the matching outputs of e and inputs of f. For example
 u       (4,1)           y (3,1)
 f                       e
c might be [1 1;1 3] which means that output 1 of y goes into input 1 of u. Output 3 of y also goes into 1 of u.
c is [uF;yE]
Empty c implies parallel connection with separate inputs and outputs:
Form
 g = connect( e, f, c )
Inputs
 e           (:)     Object of class statespace
 f           (:)     Object of class statespace
 c           (:,2)   Connection matrix
Outputs
 g           (:)   Series connection
References isempty(), and statespace().
Referenced by PMABCMachineSwitchedRHS(), RHSRobot(), and SubOrbTrajAnalysis().
eig()
function eig (in g)
Form
 [v, s] = eig( g )
Inputs
 e           (:)   Object of class statespace
Outputs
 v           (:)   Eigenvectors
 s           (:)   Eigenvalues
Referenced by ACModes(), DeltaEig(), EigEval(), GravityGradientAnalytical(), GravityGradientEigenvalues(), GravityGradientFrequency(), LibrationFrequency(), LQC(), ModalTransform(), PitchLoop(), PrintEigenvalues(), ReduceModal(), ReduceOrder(), RollEst(), RootLocus(), RootSort(), SRiccati(), SSTokamak(), Step(), TMatrix(), WPZ(), WReson(), WT_HAWTDFIGSetup(), and WT_HAWTSetup().
get()
function get (in x, in s)
Form
 y = get( x, s )
Inputs
 x           (:)   Object of class statespace
 s           (1,:) Element of class statespace
Outputs
 y           (:)   Output
getabcd()
function getabcd (in x)
Form
 [a, b, c, d] = getabcd( x )
Inputs
 x           (:)   Object of class statespace
Outputs
 a           (:)   State matrix
 b           (:)   Input matrix
 c           (:)   Output matrix
 d           (:)   Feedthrough matrix
Referenced by AddOuterLoop(), Airship_KLat(), Airship_KLon(), AirshipStatespace(), BalRealG(), CToD(), DetectionFilter(), DetectionFilterBuild(), DetectionFilterSimulation(), DetectionFilterUnnormalized(), DispG(), ESAssign(), ESAssignDraper(), EVAssgnC(), EVAssgnE(), FResp(), JLQTWOF(), LFBal(), LQC(), ModalTransform(), NormalizeMatrix(), PropStateSpace(), ReduceModal(), ReduceOrder(), RootLocus(), Step(), and TMatrix().
getsub()
function getsub (in x, in kS, in kI, in kO, in name)
Form
 g = getsub( x, kS, kI, kO, name )
Inputs
 x           (:)   Object of class statespace
 kS          (1,:) States
 kI          (1,:) Inputs
 kO          (1,:) Outputs
 name        (1,:) Name
Outputs
 g           (:)   Object of class statespace
Referenced by AeroD(), and ReduceOrder().
isempty()
function isempty (in x)
Form
 k = isempty( x )
Inputs
 x           (:)   Object of class statespace
Outputs
 k           (1,1) 1 if empty
Referenced by AC(), AccelVector2ManeuverStruct(), ACResistance(), ACThrust(), AdaptiveThresholding(), AddAxes(), AddGoals(), AddMass(), AddMassDot(), AddOuterLoop(), AddScan(), AddSurf(), AddToList(), AeroDragForce(), AFLTSpiral(), AGravity(), AirlinerSeats(), AirshipDesignGUI(), AirshipInit(), AirshipSimGUI(), AirshipStabConDerivatives(), AlbedoFromTextureMap(), Altitude(), AngleEncoder(), AnglePatch(), AntennaGain(), AntennaPatch(), ApplyThreshold(), AreaOfRectCircInt(), AssemblePlant(), AssignColors(), AStarSearch(), AtmDens1(), AtmScaleHeightsStdAtm(), AttitudeProfilePlots(), AttitudeProfilePlugIn(), AttitudeProfileVis(), AttitudeTarget(), AutoFormGeometry(), AutoPoint(), AZLaunch(), BalanceAirshipPayload(), BatterySize(), BDipole(), Beamwidth3dB(), BHarm(), BilinearTangentLaw(), BldFlex(), Blobify(), BlockDiagramPlugIn(), BloDown(), BloDownMass(), BodyPlugIn(), BTrans(), BuildAirshipModel(), C2DZOH(), CADColor(), CameraDatabase(), CameraModel(), CCVSobel(), CD0Composite(), CDCLHypersonic(), CDKF(), CDSkinFriction(), Cell2DToStruct(), CentroidCOM(), CentroidOBJFile(), CheckForDuplicateTracksMS(), CLCDFreeMolecular(), CLComposite(), ClockConversion(), close(), CloseMatFile(), CoarseCentroids(), CollisionDemoSimStruct(), CollisionMonitor(), CollisionSimStruct(), CollProbSet(), ColorSpread(), CompE(), ComponentPlugIn(), ComponentPopup(), ComputeCoeffFromShape(), ComputeDurationFraction(), ComputeGainsPlugIn(), ComputeTLE(), ComStar(), Cone(), ConeClockToU(), connect(), Constant(), ConstellationGroundContact(), ConstellationMaxDistance(), CPHypersonic(), CPvsTipSpeedRatio(), CrossSection(), CubeSatEnvironment(), CubeSatLunarEnvironment(), CubeSatPropulsion(), CW2Roll(), CycleDesign(), Database(), DateStringToJD(), DeBlankAll(), DeriveData(), DetectionFilterSimulation(), DFFAttitudeController(), DFFControl(), DFFThrusters(), DiffusionExp(), DigitalFilter(), Dipole(), DiskWithHole(), DispG(), DisplayFilter(), DisplaySailProperties(), DisplayStars(), DispWithTitle(), DistAlbedo(), DistRadiation(), dists(), DistSolar(), Disturbances(), DMSModel(), DragAnlytMdl(), DragCoeff(), Draw2DViewPlugIn(), DrawAC(), DrawAircraft(), DrawAirship(), DrawCubeSat(), DrawFOV(), DrawImage(), DrawLens(), DrawMirror(), DrawOrbitPlane(), DrawSailAngles(), DrawSailFrames(), DrawSCPlanPlugIn(), DrawSpacecraftInOrbit(), DrawSpacecraftPatches(), DrawSphere(), DrawStarImageCentroids(), DrawThermalPlugIn(), DrawVertices(), DriftRateSigma(), DualRotorDesign(), DUnit(), DVGlideslope(), DVOCCapt(), DVTarget(), E2M(), E2Nu(), EarthAlb(), EarthEnvironment(), EarthEscape(), EarthRad(), EarthRot(), ECIToEF(), ECIToNED(), Eclipse(), EclipseHelio(), EditDlg(), EditScroll(), EffPw(), EFToLatLonAlt(), El2RV(), EllipseToS(), EnergyPerRing(), Eq2RV(), ESA(), ESAChord(), ESACS(), ESAssign(), ESAssignDraper(), EVAssgnC(), ExportCAD(), ExportDSim(), ExportDXF(), ExportOBJ(), Extrude(), ExtrudeFromProfile(), Factorl(), FAero(), FAIR(), FAtmDensity(), FBudget(), FEngine(), FFEccGenerateTeamGoals(), FFEccGoals2Hills(), FFEccHills2Goals(), FFEccYExt(), FFEccZExt(), Figui(), FileFullpath(), FindSolsticeOrEquinox(), FindValidAngleRange(), FirstLineOfCode(), FitStarHist(), FixLineEndings(), fixpopupuicontrol(), FlybyConstantThrust(), FlybyOptimal(), FOrb(), FOrbCartH(), FOrbitMultiSpacecraft(), FOrbKF(), Fractal(), Frequency(), FrequencyToWavelength(), FResp(), FRespG(), FRespPlot(), Frustrum(), FSailCombined(), FSailEarthMoon(), FSailGuidance(), FSolar(), FTimeVaryingI(), Fuselage(), ga(), Gain3dB(), GasMass(), GaussianCPDF(), GaussianPDF(), GenerateTeamGoals(), GetFileSuffix(), GetFlex(), GetInputFromString(), GetListString(), GetModificationDate(), GlideslopeCircumnav(), GlideslopeGuidance(), GlideslopePlanner(), Glitch(), glpk(), GPoly(), GPSSatellite(), GravityGradientStiffness(), GravityHelio(), GroundTrack(), GroundTrackErrorBudget(), GroupVariables(), GSS(), GTrack(), GUIColors(), GXUKF(), Gyro(), HALOInit(), HCircularBillow(), HelpSystem(), HillsFramePlot(), HMagEl(), HMS2Rad(), HohmannTransferRendezvous(), HorizonUnitVectors(), HRakoczy(), HSAData(), HSRCAD(), HysteresisOutput(), IdealJetEngineEfficiency(), ImageNoise(), Imager(), InertiaFromOBJFile(), InitializeSailSim(), InsideAngleRange(), InterpolateState(), IsCircGeom(), IsEccGeom(), IsFunction(), IsValidField(), JD2Date(), JetEngineAnalysis(), JetEnginePerformance(), JLQTWOF(), KFSAAD(), L2OrbitPlots(), LabelLine(), LabelS(), LambertOpt(), LatLonAltToEF(), LatLonPlot(), LatLonToR(), LiftAndDrag(), LiftAnlytMdl(), LiftCoeffStall(), LinkBudget(), LinOrb(), LoadAirfoilFile(), LoadCAD(), LoadCatalog(), LoadFlex(), LoadGOES(), LoadGravityModel(), LoadLunarTopography(), LoadOBJFile(), LoadOBJModel(), LoadSatP(), LoadStarImage(), LocallyOptimalTraj(), LocusOfVisibility(), LossAtmosphericGas(), LowEnergyEarthToMoonTransfer(), LPEccentric(), LPEccentricGVE(), LQC(), LQOrbitController(), LTVCon(), LumenToWatt(), LunarDisplacement(), LunarHalo(), LunarProfile(), LunarTargeting(), LVCombineSRB(), M2E(), M2EApp(), M2Nu(), MachAcrossShock(), MachFromPressureRatio(), MagAirC(), MagControlTwoAxis(), MagFieldPlanet(), MagneticTorquerDipoleMoment(), ManeuverSuccessorNodes(), ManeuverSuccessorNodes3D(), MassFlow(), MassPropertiesSolidObjFile(), MassVolH2O2(), MBModel(), MergeAngleRange(), Mesh3DMF(), MessageAnalysis(), MessageQueue(), MHTHypothesisDisplay(), MHTTrackMgmt(), MHTTrackScoreKinematic(), MHTTrackTable(), MHTTrkToB(), ModalReductionPlugIn(), ModelPlugIn(), MSR(), MSThrustModel(), MultiBEPPlot(), NASANavCatalog(), NavTargetTrackingLunar(), NavTargetTrackingPlanetary(), ND2SS(), NFromJ(), NoisePower(), NonKeplerianPlanet(), NORAD(), NormalizePlugIn(), NoseCone(), NPlot(), Nu2E(), ObliqueShockAngle(), Occurences(), ODETimeDisplay(), OpenFile(), Optic2D(), OpticalNavAccuracy(), OptimalAngleOfAttackHypersonic(), OptimalCharacteristicVelocity(), OptimalLunarLanding(), OrbitalPlane(), OrbitClosestPoint(), OrbitDisplayPlugIn(), OrbitRoundTripTransferTimes(), OrbTrack(), OrbTrackECI3D(), Outliers(), P3Axis(), PackageOrbitDataForPlayback(), PanelWithCenterHole(), ParabolaToS(), ParabolicReflector(), PartialDisk(), partmapXover(), Period(), Pilot(), PinholeCameraStruct(), PinholeStarCamera(), PitchLoop(), PixelMapCentroid(), PlanarHelioOptimal(), PlanetaryAccelerations(), PlanetEnvironment(), PlanetWithTerrainPatch(), Plot3D(), PlotCone(), PlotDoubleYAxis(), PlotFlex(), PlotModeShape(), PlotOrbitPage(), PlotPlanet(), PlotSailClock2D(), PlotSailProfile(), PlotVector(), PltOrbit(), Plume(), PointCameraModel(), PopulateCostMatrix(), PorkChopTOF(), PorkChopTOFKepler(), PrandtlNikuradse(), PressureDropChannel(), PressureRatioFromMach(), PrintEigenvalues(), PrintFig(), PrintToImage(), ProcessCatalog(), ProjCircSimStruct(), PropagateCRTBPToPeriapse(), PropagateLowThrust(), PropellantMass(), PtchCnc(), PToSMA(), QFromU(), QProp(), QSail(), QToPFTarget(), RadarEquationPulse(), RadarSN(), Ramjet(), RamjetKerrebrock(), Ramp(), RandomOrbit(), RandP(), RandPN(), RankineCycle(), ReactionWheel(), ReadTopexPOE(), REAModel(), RectilinearMotion(), ReduceCatalog(), ReduceOrderPlugIn(), RepeatGroundTrack(), Residual(), RestrictIDSet(), RFSystemNoise(), RHSCubeSat(), RHSLaunchVehicle3D(), RHSLunarMission(), RHSLunarOrbit(), RHSOptimalFPA(), RHSOrbitPlanetFixed(), RHSPlanet3D(), RHSPointMass(), RHSRigidBody(), RHSRigidBodyMass(), RLagrange(), RocketChemical(), RocketDatabase(), RocketDrag(), RollEst(), RollYawEstimator(), RotateOrbit(), RotorAssemblyAerodynamics(), RSHMoon(), RVFromKepler(), RVOrbGen(), RVOrbHF(), RVSet2El(), RVWithJ2(), RWA(), RWABristle(), RWASmart(), SAADMain(), SafeGuidance(), SafeGuidanceSim(), SailEnvironment(), SailEphemAlmanac(), SailEphemJPL(), SatelliteVisibility(), SaveStructure(), ScDB(), SearchVaneAngles(), SeeTLE(), ShapeFlt(), ShowTeams(), SimpAtm(), SimpleLiftAndDrag(), Simplex(), SimplexScaling(), SimulateFlyby(), SimulatePlugIn(), SimulateStraightLineTrajectory(), SLPLSolver(), SolarCell(), SolarFluxHistorical(), SolarFluxPrediction(), SolarVisibility(), SolveFlybyPower(), SolveLinearSinCos(), SortFigs(), SortFK5(), SpaceCamera(), SpacecraftPlugIn(), SpacecraftStatePlugIn(), SpacecraftThermal(), SRiccati(), SSAD(), SSFromNonlinear(), StageTimes(), StarDataFromStarMatrix(), StarDataGeneration(), StarDensity(), StarImageHistogram(), StarMap(), StarMeasurement(), StarPrediction(), StarSensor(), StateSpacePlugIn(), StdAtm(), SteamTablesSuperheatedEnthalpy(), SteeringAnglesToQ(), StellarAttDetEKF(), StellarAttDetEKFNoGyros(), StellarAttDetUKF(), Step(), StoppingConditions(), StoppingPlugIn(), StraightLineConstantAccel(), StraightLineConstantThrust(), Strut(), SubGoals(), SunEarthAttDet(), SunEarthMagAttDet(), SunNadir(), SunRA(), SunV1(), SunV2(), TargetSlew(), TCoeff(), TeamGoals2Geom(), TelescopeAperture(), TerminatorLine(), TerrainCamera(), TesselatePolygon(), TestFFEccLinOrb(), ThermalEquilibrium(), ThrustAngleVGain(), ThrusterCAD(), ThrusterLayout(), ThrusterPatch(), ThrustModel(), TimeGUI(), TitanAtmosphere(), TitleS(), TOMHTAssignment(), Torus(), TrajectoryBetweenTwoPlanets(), Trans3DMF(), TransferOrbit(), TransferTimeToDV(), Tree(), TreeAdd(), TreeBldCAD(), TreeInit(), TreePlot(), TriangleWave(), TriangularTruss(), TripDistance(), TruEarth(), Truss(), TSCurve(), TSky(), TSolarP(), Turbofanramjet(), Turbojet(), TurbojetNoThrust(), TurboRamjet(), U2Pix(), U2Q(), Unit(), VaneAngles(), VantagePoint(), ViewFormation(), ViewGeometry(), VInfRPToRV(), VisualizeSailAttitude(), VMToPhotons(), WaitBarManager(), WalkerConstellation(), Water(), Watermark(), WavelengthToFrequency(), Weather(), WindspeedHours(), WindTurbinePower(), Wing(), WireC(), WireFRB(), WPZ(), WriteCM(), XLabelS(), and YLabelS().
plus()
function plus (in e, in f)
 The connection is
 [ e ]
 [ f ]
Form
 g = plus( e, f )
Inputs
 e           (:)   Object of class statespace
 f           (:)   Object of class statespace
Outputs
 g           (:)   Parallel connection
Referenced by AxialTurbineDesign(), CloseUIElement(), ComputeTLE(), DemoManeuverCommandList(), FRBWithMag(), FSolarSailAngles(), HeatExchanger(), HeatTransferChannel(), initializega(), initializeoga(), Isothermal(), Limit(), LVStageTimes(), NavTargetTrackingPlanetary(), RHSNLSpring(), RHSPartialNLSpring(), SizeTurbineAndCompressor(), SpinREst(), StarPrediction(), TestControlCommandList(), UKF(), UKFP(), and UKUDF().
series()
function series (in e, in f, in m)
The connection is
 e -> f
The connection matrix is lists the indices of the matching outputs of e and inputs of f. For example:
 u       (4,1)           y (3,1)
 f                       e
c might be [1 1;1 3] which means that output 1 of y goes into input 1 of u. Output 3 of y also goes into 1 of u.
Form
 g = series( e, f, c )
Inputs
 e           (:)     Object of class statespace
 f           (:)     Object of class statespace
 m           (:,2)   Connection matrix
Outputs
 g           (:)     Series connection
Referenced by AddPlot(), AssemblePlant(), BHarm(), CFract(), CHarm(), CHarmD(), CompE(), Disturbances(), DrawPatch(), EccentricTetrahedronCommandList(), FourierSeries(), M2NuS(), MatchingCircuit(), ML2KApp(), NewtonSolver(), NutDelta(), PAL(), PDAL(), Plot2D(), QSpin(), ReliabilitySeries(), RHSCSTR(), SCHarm(), SCHarmD(), SCSeries(), SHarm(), SHarmD(), SSEye(), TimeLabel(), TimeLabl(), TNoiseCascade(), and WrapSegments().
set()
function set (in x, in y, in s)
Form
 x = set( x, y, s )
Inputs
 x           (:)   Object of class statespace
 y           (:)   Value of element
 s           (1,:) Element of class statespace
Outputs
 x           (:)   Object of class statespace
Referenced by ACPlot(), ACPointMassControl(), ACWeightEstimation(), AddAxes(), AddGoals(), AddView(), AddZoom(), AerodynamicShockMinimize(), AeroF(), AI2Rate(), AircraftPowerAndThrust(), AircraftSizing(), AirshipAutopilot(), AirshipBallonets(), AirshipControlSim(), AirshipDesignGUI(), AirshipDynamics(), AirshipInit(), AirshipMassModel(), AirshipMDot(), AirshipSimGUI(), AirshipState(), AiryDisk(), AlbedoFromTextureMap(), Alfriend2El(), AllanVariance(), AlphaCentauriSystem(), AltitudeHold(), AnglePatch(), AnimateCube(), AnimateSpacecraft(), AnimateVectors(), AnimationGUI(), Animator(), ArrayPatch(), AssemblePlant(), AtmNRLMSISE(), AttitudeFrames(), AttitudeProfilePlots(), AttitudeProfileVis(), AttitudeTarget(), AutoCADColor(), AutoDualPCCommandList(), AutoDualPCSimStruct(), AutoFormCommandList(), AutoFormGeometry(), AutomobilePassing(), AutoRadar(), AxisEqual(), BalanceAirshipPayload(), BalRealG(), BinaryImage(), BodyPlugIn(), BShuster2(), BuildCADModel(), CameraCalibration(), CannyEnhancer(), CButter(), CenterFigure(), Centroid(), Centroids(), CheckDeltaVs(), ClusterGoalsDemoCommandList(), CMG(), CoarseCentroids(), CollisionDemoCommandList(), CollisionDemoSimStruct(), CollisionDetectCommandList(), CollisionDetectSimStruct(), CollisionMonitor(), CollisionSimStruct(), CollProbSet(), CollProbVol(), ColorSpread(), CommandPlugIn(), CompareHills(), ComponentPlugIn(), ComponentPopup(), ComputeCoeffFromShape(), ComStar(), ConeClockToQConstrained(), ConeInt2(), Constant(), ConstellationGroundContact(), Constraints_Structure(), ConvertOBJFileColorToMatlab(), CoordinateFrameFromUV(), Coordinates(), CoplanarOrbit(), CostEstimate_Structure(), CreateAircraftModel(), CToD(), CubeSatModel(), CustomPC2(), CWSimAndPlot(), DefaultCommandList(), DefaultTankData(), Delay(), DeltaVAnalysis(), DemoManeuverCommandList(), DeriveData(), DesignUpperStage(), DFFSimGUI(), DFFSimStruct(), DispG(), DisplayFilter(), DisplayStars(), DistributeClusterGoals(), Disturbances(), Draw2DViewPlugIn(), DrawAC(), DrawAircraft(), DrawAirship(), DrawBlobs(), DrawCircularPlane(), DrawCubeSat(), DrawFOV(), DrawOrbitPlane(), DrawSailAngles(), DrawSailAttitude(), DrawSailCADModel(), DrawSailMeshVectors(), DrawSCARA(), DrawSCPlanPlugIn(), DrawSpacecraftInOrbit(), DrawSpacecraftPatches(), DrawStarImageCentroids(), DrawThermalPlugIn(), EarthMoon(), EarthMoonRotFrame(), EccentricTetrahedronCommandList(), ECIToEarthMoonRot(), ECIToSunEarthRot(), EclipticInjectionPlane(), EditDlg(), EigEval(), El2Alfriend(), Ellipsoid(), ELM(), EMarkov(), Equal(), ESAChord(), ESACS(), EstimateCost(), ExportVerticesToOBJ(), FAero(), FAeroSurfaceAccommodation(), FAtmDensity(), FEngine(), FFEccDeltaElem2Goals(), FFEccDeltaElem2Hills(), FFEccEstimateCost(), FFEccGenerateTeamGoals(), FFEccHexahedronGeometry(), FFEccHills2DeltaElem(), FFEccShapes(), FFEccTetrahedronGeometry(), FFSimPlotter(), Finder(), FindInFiles(), fixpopupuicontrol(), ForceAndTorqueEnvelope(), ForceBetweenCoils(), FourierSeries(), FPlantNoise(), FrictionBristle(), FSolar(), FThrustLander(), GAMin(), GaussianDerivative(), GaussianImageFilter(), GenerateAirshipLinMods(), GenerateGrid(), GenerateSwath(), GenerateTeamGoals(), GetCADVF(), GetStarPatch(), GimbalRates(), GOESLeg(), GPoly(), GPSReceiver(), GravityTurnSim2D(), GroupVariables(), GUIColors(), GUICounter(), GuidedLaunch2DSim(), GuidedLaunchOpt2D(), Gyro(), HallThrusterArray(), HelpSystem(), Hexahedron(), HillsFramePlot(), HorizontalWind(), HorizonUnitVectors(), HSRCAD(), HUD(), IdealActuator(), ImageDerivative(), ImageNoise(), ImageOverlay(), ImagerPSF(), ImpulsiveLPManeuver(), Inflation(), InformDlg(), InitializeFormation(), IntegratePSFs(), IsDuplicateState(), ISSCoord(), ISSOrbit(), JacobianODE(), KSmooth(), L2OrbitPlots(), LandingControl(), LandingControlBilinear(), LatLonToRangeAzimuth(), LatLonToRAz(), LaunchConstants(), LaunchGUI(), LeadLag(), LeastSq(), LegendTitle(), LFBal(), Limit(), LinearImageFilter(), LinOrb(), ListCases(), LoadCatalog(), LoadEarthMap(), LoadNORAD(), Loc3D(), LocalStarMap(), LogLimit(), LowSpeedAeroData(), LPvsCF(), LQC(), LVModelFeasibilityFix(), Mag(), MagneticTorquer(), MagneticTorquerDipoleMoment(), MainDemoCommandList(), MainDemoSimStruct(), MakeDistribution(), MakeSquareSail(), ManeuverSuccessorNodes(), ManeuverSuccessorNodes3D(), Map(), MeasMagnetometerEarth(), MeasRateGyro(), MeasRateIntegratingGyro(), MeasRelativePosition(), MeasState(), Measurements(), MeasurementsSunMagUKF(), MedianImageFilter(), MergeConstantDB(), MergeNOAAWindData(), MHTTrkToB(), MinDEllipsoid(), MixedFlowTurbofan(), MLog(), ModalReductionPlugIn(), MomArm(), MSData(), MSVRatio(), NavTargetTrackingLunar(), ND2SS(), NewStats(), NewtonianAeroTable(), NewtonSolver(), NLEqSolver(), NOAAWindData(), NominalSafeGuidance(), Normal(), NormalizeMatrix(), Notch(), NPlot(), NumericalTransferFunction(), ObliqueShockAngle(), ObservationTimeWindows(), ODETimeDisplay(), OmegaFromU(), OptimalAssignment(), OptimalPayloadRatio(), OptimalVehicle(), OrbitalPlane(), OrbitODGenObs(), Outliers(), ParabolicReflector(), ParasiticDragCoefficient(), PDDesign(), PeriodicOrbitFromGuess(), PhasePlane(), PhasePlanePlot(), PIDesign(), PIDMIMO(), PIDProper(), PILeaky(), PinholeStarCamera(), PixelFlux2D(), PixelMapCentroid(), PlanetTransferLambert(), PlaybackControls(), Plot2DTrajectory(), Plot3D(), Plot3DOrbit(), PlotArrays(), PlotBPlane(), PlotCentroids(), PlotCone(), PlotDoubleYAxis(), PlotEMTraj(), PlotLET(), PlotLET3BP(), PlotModeShape(), PlotOrbitPage(), PlotOrbitTransfer(), PlotPlanet(), PlotSailClock2D(), PlotSailForce(), PlotSailForce2D(), PlotSEMTraj(), PlotSet(), PlotV(), PlotVector(), PlotWindField(), PlotXYTrajectory(), PlotZermelo(), PltOrbit(), Plume(), PointInGridInTriangle(), PorkChopPlot(), PredictCollision(), PrincipalAxes(), PrintFig(), ProfileStruct(), ProjCircCommandList(), ProjCircSimStruct(), PropagateOrbitPlugIn(), PropagateState3D(), PropagateTLECommonTime(), PWM(), PWMSeq(), Q2AU(), QFromU(), QLatLon(), QLVLH(), QSail(), QSunPointing(), Quit(), RapidSwath(), RayTraceLens(), RAzToLatLon(), ReactionWheel(), ReadImage(), ReduceOrder(), RestrictIDSet(), RHAzToECEF(), RHS3DPointAircraft(), RHSAlphaCentauriMission(), RHSFlatEarthSet(), RHSGyroNBody(), RHSPointMass(), RHSRigidBodyMass(), RHSThreeBody(), RLPMnvr(), RMSNoiseImager(), RotateOrbit(), RotateState(), RWABristle(), RWASmart(), S2Damp(), SAADMain(), SafeGuidanceSimInit(), SafeGuidanceSimPlots(), SailForceSubplots(), SailMesh(), SatelliteVisibility(), SaturnsRings(), SaveStructure(), ScaleState(), SCClock(), ScDB(), SDG(), SectorPatch(), SeeTLE(), SetCADQuaternion(), SFShustr2(), SFunc(), ShapeFlt(), SHELSInterface(), SignTest(), SimpleManeuverCommandList(), Simulate2DLanding(), SinePC(), SingleAxisDrive(), SingleAxisLinearDrive(), SizeAB(), SizeABCD(), SizeAC(), SliderBar(), SLPLDataStructure(), SolarF(), SortTeamGoals(), SpaceCamera(), SpacecraftParameters(), SpacecraftPlugIn(), SpacecraftStatePlugIn(), SphereOfInfluenceHelio(), SSAD(), StarCentroidCOM(), StarDataGeneration(), StarDensity(), StarIDPyramid(), StarIDTestCatalog(), StarImageHistogram(), State_Structure(), StateSensor(), StateSpacePlugIn(), StopGUI(), StoppingPlugIn(), SubGoals(), SubOrbTrajAnalysis(), SumRXF(), SumV(), Sweep(), SystemTime(), TargetInFocalPlane(), TCoeff(), TeamManagementCommandList(), Telemetry(), TerminatorLine(), TestADCSSimStruct(), TestCollisionSimStruct(), TestControlCommandList(), TestLPCircular(), TestLPEccentric(), TestLPEccentricGVE(), TestMonitoringCommandList(), TestTeamMgtCommandList(), Tetrahedron(), ThermalColorMap(), Thermnet(), ThrstLevel(), ThrusterAndRWACommand(), ThrusterCommand(), ThrustModel(), TimeGUI(), TimeHistory(), TimePlugIn(), TMatrix(), TOMHTAssignment(), TorqueRod(), TrackingAccuracy(), Trajectory(), TrajectoryOptimization(), TransformECIToEMBR(), TransformECIToSEMR(), TransformEMBRToECI(), TransformSEMRToECI(), TransformSEMRToHelio(), TRF(), TubeSatFaces(), TubeSatModel(), UKFWeight(), UnitVectorFromOffset(), VCFlatFile(), ViewFormation(), ViewGeometry(), ViewRelativeMotion(), VisualizeSailAttitude(), WalkerConstellation(), Watermark(), Weather(), WheelSpeed(), WindAdmittance(), WingAreaToTaper(), WireInit(), Z2Damp(), and ZOH().
statespace()
function statespace (in a, in b, in c, in d, in name, in states, in inputs, in outputs, in sType, in dT)
Everything after c is optional.
 dx/dt = ax + bu
 y = cx + du
Form
 g = statespace( a, b, c, d, name, states, inputs, outputs, sType, dT )
Inputs
 a                          State transition matrix
 b                          State input matrix
 c                          State output matrix
 d                          State feedthrough matrix
 name     (1,:)             Name of the system
 states   (:,:)   or {:}    State  names
 inputs   (:,:)   or {:}    Input names
 outputs  (:,:)   or {:}    Outputs
 sType    (1,:)             's', 'z', 'delta'
 dT       (1,1)             Time step
Outputs
 g            (:)     Plant
                 g.a       State transition matrix
                 g.b       State input matrix
                 g.c       State output matrix
                 g.d       State feedthrough matrix
                 g.n       Number of states
                 g.nI      Number of inputs
                 g.nO      Number of outputs
                 g.states  Names of states
                 g.inputs  Names of inputs
                 g.outputs Names of outputs
                 g.sType   's', 'z', 'delta'
                 g.dT      Time step
Referenced by ACModes(), ACTF(), AddOuterLoop(), AeroD(), Airship_KLat(), Airship_KLon(), AirshipStatespace(), AssembleBlock(), AssemblePlant(), BalRealG(), BuildLinearDF(), CCVModel(), CCVSobel(), CompE(), connect(), ControlDesignGUI(), DispG(), EigEval(), EmptyBlock(), EmptySISO(), ESAssign(), EVAssgnC(), EVAssgnE(), FResp(), FRespG(), GetAirshipLinMod(), GSModel(), IC(), L1011(), LFBal(), LinOrbLQG(), LQC(), ModalTransform(), NumericalTransferFunction(), Nyquist(), OH6A(), PGains(), PIDProper(), PILeaky(), Pilot(), PrintEigenvalues(), PropStateSpace(), ReduceModal(), RootLocus(), SISOPlugIn(), SSTokamak(), StateSpacePlot(), StateSpacePlugIn(), Step(), SVPlot(), TMatrix(), TResp(), and WindGust().