PSS MATLAB Toolboxes: Common/Classes/@transmat/transmat.m File Reference
transmat.m File Reference
Converts an input of type transmat to type quat.
Functions
function ctranspose (in a)
Computes the transpose of a matrix.
function get (in a)
Gets the matrix equivalent of a transmat.
function quaternion (in a)
Converts an input of type transmat to type quat.
function transmat (in x)
Create an object of class transMat.
Function Documentation
ctranspose()
function ctranspose (in a)
Form
 b = ctranspose( a )
Inputs
 a           (:)   Object of type transmat
Outputs
 b           (:)   Object of class transmat
References Eul2Mat(), quat(), and transmat().
get()
function get (in a)
Form
 c = get( a )
Inputs
 a           (:)   Object of type transmat
Outputs
 c           (3,3) Matrix
quaternion()
function quaternion (in a)
Form
 b = quaternion( a )
Inputs
 a           (:)   Object of type transmat
Outputs
 b           (:)  Object of class quaternion
Referenced by AC(), AccelToThrustAndQ(), ACPlot(), AddAxes(), AirshipControlSim(), AirshipInit(), AirshipLinMod(), AirshipStabConDerivatives(), AirshipState(), AirshipTrim(), AlignThruster(), AnglesRotToU(), AnimQ(), AntennaPoint(), ApplyProfileToModel(), ASim(), AStarAttitudeTrajectory(), AttitudeControlSimRWA(), AttitudeFrames(), AttitudeProfile(), AttitudeProfileVis(), AttitudeProfileWithCon(), AttitudeTarget(), AttProp(), AU2Q(), AutoPoint(), BHinge(), BToS(), BToW(), CameraImage(), ConeClockToQConstrained(), CubeSatAero(), CubeSatAttitude(), CubeSatDisturbanceAnalysis(), CubeSatEnvironment(), CubeSatLunarEnvironment(), CubeSatPropulsion(), CubeSatRadiationPressure(), DefaultACState(), DeltaQTarget(), DeltaQToRate(), DFFAttitudeController(), DFFAttitudeManeuver(), DFFAttitudeTarget(), DQ2Mat(), DrawAC(), DrawCircularPlane(), DrawSailAttitude(), DrawSailFrames(), DrawSCPlugIn(), DrawSpacecraftInOrbit(), DSTMQ(), ECIToNED(), Eul2Q(), EulNED(), FImage(), FRBWithMag(), FRSCGen(), FRSMPlan(), FRSProp(), FRSTarg(), FTBRef(), FTrim(), GenerateSwath(), GyroKalmanFilter(), ICSN(), InitialOrientation(), IntGyroQuaternion(), ISLFOV(), KConstQ(), Mat2Q(), MeasEarthSensor(), MeasMagnetometerEarth(), MeasStarTracker(), MeasSunSensorAnalog(), MeasSunSensorDigital(), MeasurementsSunMagUKF(), Orientation_Structure(), P3Axis(), PID3Axis(), PlotSailClock2D(), PointCameraModel(), Q2AU(), Q2Eul(), Q2Mat(), Q2RADec(), QAcq(), QAlign(), QAlignWithCon(), QAxisRot(), QBToIDot(), QECI(), QError(), QForm(), QFrenet(), QFrom2U(), QFromDQ(), QFromU(), QHills(), QHillsToBody(), QIToBDot(), QNadirPoint(), QPose(), QProp(), QRotateToAlignWithCon(), QSLERP(), QSteeringYAligned(), QSunNadir(), QTForm(), QToConeClock(), QToPFTarget(), quat(), QUnit(), QXToAlphaDelta(), QZero(), RaDec2Q(), RateFromDQ(), RHSCubeSat(), RHSRigidBodyOffsetCM(), RYGCAttDet(), Sa2Q(), SailDisturbance(), SailForceSubplots(), SetCADQuaternion(), SetCADRotation(), SetCADState(), SPMMnvr(), StarMeasurementUKF(), SteeringAnglesToQ(), StellarAttDetEKF(), StellarAttDetEKFNoGyros(), StellarAttDetUKF(), STKAtt(), STM(), SToW(), SunEarthAttDet(), SunEarthMagAttDet(), TBModel(), ThreeAxisControlDisturb(), ThrusterAlignment(), Tree(), TreeH(), TwoUToQ(), U2Q(), UToConeClock(), VisualizeSailAttitude(), and WireInit().
transmat()
function transmat (in x)
You can input:
 quat
 3-by-1 matrix - assumed to be an array of angles
 3-by-3 matrix - a transformation matrix
transmat will orthogonalize the matrix automatically.
Form
 m = transmat( x )
Inputs
 x       (:,:) Quaternion
         (3,3) Matrix
         (3,1) Array of angles
Outputs
 m      (1,1) Object of class transMat.
References quat(), and transmat().
Referenced by ctranspose(), and transmat().